### PR TITLE
Fix SO issue of BObject and BIntersection toString

### LINKED ISSUE #30001: Runtime stack overflow from cloneReadOnly on array of recursive read-only objects
This gets a StackOverflowError at runtime:

```
type Obj readonly & object {
    function foo(Obj t) returns Obj;
};

public function main() {
   Obj[] v = [];
   any x = v.cloneReadOnly();
}
```

### PR DESCRIPTION
**Pull request by KRVPerera**
Fixes #30001

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java [hunk 1]
```diff
@@ -81,6 +84,20 @@ public int getTag() {
 
     @Override
     public String toString() {
+        if (resolving) {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:87]: Can you share an example of when this fails for the intersection type rather than the effective type?

File: tests/jballerina-unit-test/src/test/resources/test-src/object/readonly_objects.bal [hunk 2]
```diff
@@ -305,6 +305,16 @@ public function testReadOnlyClassIntersectionWithValidQualifiers() {
     assertEquality(9876, getBits(new Corge()));
 }
 
+type Obj readonly & object {
+    function foo(Obj t) returns Obj;
+};
+
+public function testRecursiveObjectArrayReadonlyClone() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/object/readonly_objects.bal:312]: Let's add relevant tests for each type that has been changed in this PR.

**Review by MaryamZi — COMMENTED** [review]
@KRVPerera, there are test failures too.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java [hunk 3]
```diff
@@ -81,6 +84,20 @@ public int getTag() {
...
+            return "";
+        }
+        resolving = true;
+        computeStringRepresentation();
+        resolving = false;
+        return cachedToString;
+
```
Comment (rdulmina) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:94]:
```suggestion
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java (hunk 1 above)
Comment (KRVPerera) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:87]: I have to rework the code experiencing some issues in debugging. Almost like race conditions.
Check the same example in the original problem. The return type of the method and parameter is the intersection type of the object.
So this stack overflow loops over Object and Intersection both. Intersection type having a collection of other types is easily susceptible to this issue. That is why I decided to fix it there too.

Screenshot 2021-06-21 at 1 27 40 PM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java [hunk 4]
```diff
@@ -441,20 +419,41 @@ public BIntersectionType getImmutableType() {
...
+            return;
+        }
+        if (tsymbol != null && !tsymbol.getName().getValue().isEmpty()) {
+            String typeName = tsymbol.getName().getValue();
+            String packageId = tsymbol.pkgID.toString();
+            boolean isTypeParam = Symbols.isFlagOn(flags, Flags.TYPE_PARAM);
+            // improve readability of cyclic union types
+            if (isCyclic && (pCloneable.matcher(typeName).matches() ||
+                    (isTypeParam && pCloneableType.matcher(typeName).matches()))) {
+                System.out.printf("433");
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java:437]: Is this for testing purposes?

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BUnionType.java]: Done 31673ea

**Review by gimantha — APPROVED** [review]
LGTM

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java (hunk 1 above)
Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:87]: But shouldn't this get fixed automatically when the object case is fixed?

Comment (KRVPerera) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:87]: Missed the comment.
What if this also happens with records?

Comment (KRVPerera) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:87]: Missed the comment.
What if this also happens with records?

Comment (KRVPerera) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:87]: Missed the comment.
What if this also happens with records?

Comment (KRVPerera) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:87]: Missed the comment.
What if this also happens with records?

Comment (KRVPerera) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:87]: I will check if this is redundant and revert the change in another PR.
