### PR TITLE
Fix issue with invalid qualifier order

### LINKED ISSUE #32445: Invalid text range for token
**Description:**
Consider the following source code.
```
function myFunc {
    isolated client 
}
```
The text range of client token is as follows.
tec

Irrespective of where the above code segment is used. The text range of client token always seem to be as depicted above.

**Steps to reproduce:**
Mentioned above

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #32445 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -4618,7 +4618,8 @@ private STNode createMissingSimpleObjectField(STNode metadata, List<STNode> qual
     }
 
     private STNode modifyNodeWithInvalidTokenList(List<STNode> qualifiers, STNode node) {
-        for (STNode qualifier : qualifiers) {
+        for (int i = qualifiers.size() - 1; i >= 0; i--) {
+            STNode qualifier = qualifiers.get(i);
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4622]: R we having the same issue with `reportInvalidQualifierList` as well?

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4622]: Inside `reportInvalidQualifierList()` we call `addInvalidNodeToNextToken()` for each token, which keeps the tokens in a stack. Since stack is FILO order we get the right order there.

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4622]: Cool

**Review by rdulmina — APPROVED** [review]
