### PR TITLE
Fix non-isolated method scheduling to be sequential

### LINKED ISSUE #29322: Support runtime api for non isolated function scheduling
Provide an API such as `invokeMethodAsync` but to schedule functions with an exclusive way. That is, functions from the same object never run in parallel.

### PR DESCRIPTION
**Pull request by manuranga**
Fixes #29322

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java [hunk 1]
```diff
@@ -54,23 +61,46 @@ public static Runtime getCurrentRuntime() {
...
+        if (isIsolate) {
+            return scheduler.schedule(new Object[1], func, null, callback, strandName, metadata).result;
+        } else {
+            return scheduler.scheduleToObjectGroup(object, new Object[1], func, null, callback, strandName, metadata)
+                    .result;
+        }
+    }
+
+    private boolean isIsolated(ObjectType type, String methodName) {
+        for (MethodType method : type.getMethods()) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java:89]: Shall we keep the set of isolated object method/resource method names as a set inside ObjectType. We can get that list during compile time and set it during codegen. https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java#L1154

Comment (sameerajayasoma) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java:89]: The complete service object has to be isolated. This should come from the compiler frontend. 

Something similar to `ObjectType.isolated()` or a flag in the `ObjectType`. Checking all resource methods is not enough

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java [hunk 2]
```diff
@@ -54,23 +61,46 @@ public static Runtime getCurrentRuntime() {
...
+            }
+        }
+        if (type.getTag() == SERVICE_TAG) {
+            for (ResourceMethodType method : ((BServiceType) type).getResourceMethods()) {
+                if (method.getName().equals(methodName)) {
+                    return SymbolFlags.isFlagOn(method.getFlags(), SymbolFlags.ISOLATED);
+                }
+            }
+        }
+        assert false : "object type does not contain method : " + methodName;
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java:101]: I think we do not need this check. We already codegen no such error method if we call non defined object method.

Comment (manuranga) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java:101]: it's `assert` so it will get removed by jvm. just here to catch code issues.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java (hunk 1 above)
Comment (manuranga) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java:89]: Modified to check both object and resource

**Review by warunalakshitha — APPROVED** [review]
