### PR TITLE
Fix bal pack crashes when [[dependency]] section is missing in the CompilerPlugin.toml file

### LINKED ISSUE #41418: [Bug]: `bal pack` crashes when `[[dependency]]` section is missing in the CompilerPlugin.toml file
### Description

$Subject
When a Ballerina project has `CompilerPlugin.toml` file with no `[[dependency]]` sections specified, executing `bal pack` gives the following crash log:

```
[2023-09-20 15:19:48,152] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:361)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at io.ballerina.projects.JBallerinaBalaWriter.addCompilerPlugin(JBallerinaBalaWriter.java:121)
        at io.ballerina.projects.BalaWriter.populateBalaArchive(BalaWriter.java:135)
        at io.ballerina.projects.BalaWriter.write(BalaWriter.java:108)
        at io.ballerina.projects.JBallerinaBackend.emitBala(JBallerinaBackend.java:241)
        at io.ballerina.projects.JBallerinaBackend.emit(JBallerinaBackend.java:218)
        at io.ballerina.cli.task.CreateBalaTask.execute(CreateBalaTask.java:79)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.PackCommand.execute(PackCommand.java:256)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

### Steps to Reproduce

Add an empty `CompilerPlugin.toml` file or with only `[plugin]` section to a Ballerina project. 

`CompilerPlugin.toml`
```toml
[plugin]
id = "id"
class = "path.to.class"
```

### Affected Version(s)

ballerina-lang master, update-8 RC1
NPE observed with earlier versions when an empty `CompilerPlugin.toml` file added. 

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Shadow-Devil**
Fixes #41418 and #42120

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBalaWriter.java [hunk 1]
```diff
@@ -138,32 +138,28 @@ protected void addCompilerPlugin(ZipOutputStream balaOutputStream) throws IOExce
             List<String> compilerPluginLibPaths = new ArrayList<>();
             List<String> compilerPluginDependencies = this.compilerPluginToml.get().getCompilerPluginDependencies();
 
-            if (compilerPluginDependencies.get(0) == null) {
+            if (compilerPluginDependencies.isEmpty()) {
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBalaWriter.java:141]: @Shadow-Devil The fix is working fine now we get the below error message. 
image

Shall we add a negative test case for this? 
We have a few negative test cases in `io.ballerina.projects.test.plugins.CompilerPluginNegativeTests`. Can you please add one for this fix?

**Comment by Shadow-Devil** [comment]
@gimantha i think this is blocked until #43466 is fixed

**Comment by gimantha** [comment]
> @gimantha i think this is blocked until #43466 is fixed

Yep.. initially it was failing due to the exact reason your mentioned. But now it is failing due to an error in debugger tests. We will have a look

**Review by gimantha — APPROVED** [review]
