### PR TITLE
Fix incorrect results for interop of Java instance methods with Ballerina client resource methods

### LINKED ISSUE #40226: [Bug]: Error message seems incorrect when calling a Java instance method via a client resource method
### Description

$title

### Steps to Reproduce

Ballerina:
```ballerina
public client isolated class Client {

    public isolated function init() {
    }
    isolated function newFoo() returns handle = @java:Constructor {
        'class: "javalibs.app.Foo"
    } external;

    isolated resource function get xyz/[string p1]/[string p2] (handle h) returns float = @java:Method {
        'class: "javalibs.app.Foo",
        name: "getResource"
    } external;
}

public function main() {
    Client cl = new Client();
    handle h = cl.newFoo();
    float f = cl->/xyz/["asd"]/jef.get(h);
}
```
Java:
```java
public class Foo {

    public Foo() {
    }

    public double getResource(BObject self, BString p1, BString p2) {
        return 2.4;
    }
}
```
error:
```
ERROR [main.bal:(206:5,209:16)] {ballerina/jballerina.java}METHOD_NOT_FOUND 'No such public static method 'getResource' with '3' parameter(s) found in class 'class javalibs.app.Foo''
```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #40226

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Review by Nadeeshan96 — APPROVED** [review]
LGTM

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/InstanceMethods.java [hunk 1]
```diff
@@ -37,6 +39,9 @@ public class InstanceMethods {
 
     private Integer counter = 0;
 
+    public InstanceMethods() {
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/InstanceMethods.java:42]: Shall we check whether we need to explicitly have a constructor here? It can use the default constructor.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/InstanceMethodResourceClientTest.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+import org.ballerinalang.test.BRunUtil;
+import org.ballerinalang.test.CompileResult;
+import org.testng.annotations.AfterClass;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Test;
+
+/**
+ * Test cases for interop of Java instance methods with client resource methods.
+ *
+ * @since 2201.6.0
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/InstanceMethodResourceClientTest.java:30]:
```suggestion
 * @since 2201.7.0
```

File: tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/instance_method_resource_client_test.bal [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+
+    isolated resource function get xyz/[string p1]/[string p2] (handle h) returns int = @java:Method {
+        'class: "org.ballerinalang.nativeimpl.jvm.tests.InstanceMethods",
+        name: "getResource"
+    } external;
+
+    isolated resource function get abc/[string p1]/[string p2] (handle h, int i) returns string = @java:Method {
+        'class: "org.ballerinalang.nativeimpl.jvm.tests.InstanceMethods",
+        name: "getResourceWithBundledPaths",
+        paramTypes: ["io.ballerina.runtime.api.Environment", "io.ballerina.runtime.api.values.BObject", "io.ballerina.runtime.api.values.BArray", "long"]
```
Comment (Nadeeshan96) [inline tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/instance_method_resource_client_test.bal:38]: Shall we split this line since it is longer than 120 characters? Other changes LGTM.

**Review by Nadeeshan96 — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM
