### PR TITLE
Fix LSPackage loader to avoid duplicate packages

### LINKED ISSUE #36234: Getting the same suggestion twice for a module when typing it for the first time
**Description:**
$subject. This is when referring to a module for the first time. i.e. No previously added import declaration for the module.

Screenshot from 2022-05-20 12-15-45

**Affected Versions:**
Noticed in the 2201.1.0 rc2 for the first time. Could have affected previous versions also.

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject

Fixes #36234 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java [hunk 1]
```diff
@@ -116,8 +117,10 @@ public List<PackageInfo> getDistributionRepoPackages() {
      * @return {@link List} packages
      */
     public List<PackageInfo> getAllVisiblePackages(DocumentServiceContext ctx) {
-        List<PackageInfo> packagesList = new ArrayList<>();
-        packagesList.addAll(this.getDistributionRepoPackages());
+        Map<String, PackageInfo> packagesList = new HashMap<>();
+        this.getDistributionRepoPackages().forEach(packageInfo ->
+                packagesList.put(packageInfo.packageOrg.toString() + "/"
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java:122]: We can use `packageInfo.getPackageIdentifier()` here right?

**Review by IMS94 — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java (hunk 1 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java]: Done

**Review by IMS94 — APPROVED** [review]
