### PR TITLE
Align parser with explicit-new-expr latest grammar

### LINKED ISSUE #29171: Semantic Analyzer gives NPE for explicit-new-expr
**Description:**
$subject.

Following tests are failed to compile.
https://github.com/ballerina-platform/ballerina-lang/blob/fc0a209e74ba11a0d2916b8c06350d6519b54327/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java#L57-L63

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #29171 

## Approach
N/A

## Samples
N/A

## Remarks
The parser was supporting the old grammar: [explicit-new-expr](https://ballerina.io/spec/lang/draft/v2020-06-18/#explicit-new-expr) := `new type-descriptor ( arg-list )`.
But, according to the latest grammar: [explicit-new-expr](https://ballerina.io/ballerina-spec/spec.html#explicit-new-expr) := `new class-descriptor ( arg-list )`,

Due to deviation some inputs causing NPE at the semantic analyzer.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [x] Added necessary documentation  
  - [x] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 1]
```diff
@@ -2541,7 +2549,7 @@ private Result seekMatchInExpressionRhs(int lookahead, int currentDepth, int cur
         } else if (parentCtx == ParserRuleContext.ON_CLAUSE) {
             nextContext = ParserRuleContext.EQUALS_KEYWORD;
         } else {
-            throw new IllegalStateException(parentCtx.toString());
+            throw new IllegalStateException("seekMatchInExpressionRhs found: " + parentCtx);
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:2552]: btw these changes are done in order to quickly spot the location of the bug when tests are falling.
e.g.
Screenshot from 2021-03-16 19-21-14

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 2]
```diff
@@ -4899,32 +4894,70 @@ private boolean isClassDescriptorStartToken(SyntaxKind tokenKind) {
...
+            case STREAM_KEYWORD:
+                classDescriptor = parseStreamTypeDescriptor(consume());
+                break;
+            default:
+                if (isQualifiedIdentifierPredeclaredPrefix(nextToken.kind)) {
+                    classDescriptor = parseTypeReference();
+                    break;
+                }
+                
+                recover(nextToken, ParserRuleContext.CLASS_DESCRIPTOR, newKeyword);
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4938]:
```suggestion
                recover(nextToken, ParserRuleContext.CLASS_DESCRIPTOR);
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 3]
```diff
@@ -4858,38 +4861,30 @@ private STNode parseNewKeyword() {
...
+        if (nextToken.kind == SyntaxKind.OPEN_PAREN_TOKEN) {
+            return parseImplicitNewExpr(newKeyword);
         }
-        return STNodeFactory.createImplicitNewExpressionNode(newKeyword, STNodeFactory.createEmptyNode());
+        
+        if (isClassDescriptorStartToken(nextToken.kind)) {
+            return parseExplicitNewExpr(newKeyword);
+        }
+
+        return createImplicitNewExpr(newKeyword, STNodeFactory.createEmptyNode());
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4882]: Let's add recovery for NewKeyWordRhs. ErrorHandler already supports it. Recovery inside `parseClassDescriptor` will not hit because we call `parseExplicitNewExpr` only after seeing a class descriptor token. Let's move the recovery inside ``parseClassDescriptor` to `parseNewKeywordRhs`

**Review by rdulmina — CHANGES_REQUESTED** [review]

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 4]
```diff
@@ -4829,7 +4829,10 @@ private boolean isValidExprStart(SyntaxKind tokenKind) {
      * <code>
      * new-expr := explicit-new-expr | implicit-new-expr
      * <br/>
-     * explicit-new-expr := new type-descriptor ( arg-list )
+     * explicit-new-expr := new class-descriptor ( arg-list )
+     * <br/>
+     * class-descriptor := identifier | qualified-identifier |
+     * <br/>&nbsp;stream-type-descriptor
```
[the remark this answers is not in the document]
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4835]: although we write in a single line, they don't render in a single line.
Screenshot from 2021-03-26 16-17-54

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 5]
```diff
@@ -4858,38 +4861,30 @@ private STNode parseNewKeyword() {
         }
     }
 
-    private STNode parseNewKeywordRhs(STNode newKeyword) {
-        STNode token = peek();
-        return parseNewKeywordRhs(token.kind, newKeyword);
-    }
```
[the remark this answers is not in the document]
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4864]: it is called inside the  `parseNewExpression()` right?

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4835]: Cool

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 3 above)
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4882]: Adding recovery to new-keyword rhs is not possible. I tried. But, we can't predetermine all the new-keyword rhs.
e.g. tests like the below started to fail.
```
    RecordWithReadOnlyFields rec2 = {
        a: new AnotherReadOnlyClass(4567),
        c: new
    };
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4864]: consume inside `parseNewExpression`

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 3 above)
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4882]: Anyway, a recover point was added to parseClassDescriptor in case if we call it in an other place in furture.

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4882]: New keyword rhs tokens should be the tokens as implemented in errorhandler right?

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4882]: Resolving as per the discussion offline.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:4864]: Resolving as per the discussion offline.

**Review by rdulmina — APPROVED** [review]
