### PR TITLE
Fix starting transaction coordinator even if the local transactions are used

### LINKED ISSUE #27198: Fix starting transaction coordinator even if the local transactions are used
As of current implementation, HTTP transactions coordinator is started whenever there is a transaction block. Coordinator is only required if there are transactional services.

### PR DESCRIPTION
**Pull request by lasinicl**
Fixes #27198

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -1176,6 +1179,12 @@ public void visit(BLangFunction funcNode) {
         BType currentReturnType = this.forceCastReturnType;
         this.forceCastReturnType = null;
         funcNode.body = rewrite(funcNode.body, funcEnv);
+        if (serviceStarted) {
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:1182]: Lets move this to transactionDesugar or rename it to TransactionCoordinatorService.

Comment (lasinicl) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:1182]: This approach was modified via https://github.com/ballerina-platform/ballerina-lang/pull/27477
