### PR TITLE
Fix extract to constant code action when there's no newline between the import and content

### LINKED ISSUE #38843: [Bug]: Invalid Extract to constant code action
### Description

In the following scenario, the constant is created inside the record when there's no newline between the import and content.

https://user-images.githubusercontent.com/61020198/204202899-4223954a-8f1f-4543-8742-f5ef173e6af0.mov

### Steps to Reproduce

```
import ballerina/io;
type RecordType record {
    string name;
};

function testFunctionxx(RecordType rec) {
    int x = 2 + 3;
}
```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
This PR fixes the position of the constant created with the extract to constant code action.

Fixes #38843

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by malinthar — DISMISSED** [review]
The changes look good. But good if we can refactor the logic to add a space before and after the constant declaration as depicted below.

Case 1: There is no other constant
image

Case 2: There are other constants

image

If this is not within the scope of this issue,  let's create a separate issue to handle this.

Let's send this fix to 2201.3.x branch as well

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToConstantCodeAction.java [hunk 1]
```diff
@@ -146,10 +150,16 @@ public String getName() {
...
+                                        boolean newLineAtStart) {
         String value = node.toSourceCode().strip();
         LineRange replaceRange = node.lineRange();
-        String constDeclStr = String.format("const %s %s = %s;%n", typeSymbol.signature(), constName, value);
+        String constDeclStr;
+        if (newLineAtStart) {
+            constDeclStr = String.format("%n" + "const %s %s = %s;%n", typeSymbol.signature(), constName, value);
+        } else {
+            constDeclStr = String.format("const %s %s = %s;%n", typeSymbol.signature(), constName, value);
+        }
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToConstantCodeAction.java:162]: We can rewrite this as:
```java
       if (newLineAtStart) {
            constDeclStr += String.format("%n");
        }
        constDeclStr = String.format("const %s %s = %s;%n", typeSymbol.signature(), constName, value);
```

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToConstantCodeAction.java [hunk 2]
```diff
@@ -171,15 +181,29 @@ private String getConstantName(CodeActionContext context) {
...
-            return PositionUtil.toPosition(modulePartNode.lineRange().startLine());
+            return new ConstantData(
+                    PositionUtil.toPosition(modulePartNode.lineRange().startLine()), false);
+        } else if (declarationNode == null) {
+            ImportDeclarationNode lastImport = importsList.get(importsList.size() - 1);
+            return new ConstantData(
+                    new Position(lastImport.lineRange().endLine().line() + 1, 0), true);
+        } else {
+            return new ConstantData(new Position(declarationNode.lineRange().startLine().line(), 0),
+                    !declarationNode.toString().startsWith("\n"));
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToConstantCodeAction.java:205]: Seems like we don't have a test case for this scenario. Shall we add one?

Also, shall we use `System.lineSeparator()` instead of hardcoding `\n` here? That can change on windows.

**Review by IMS94 — CHANGES_REQUESTED** [review]
