### PR TITLE
Remove single quote from doc parameters

### LINKED ISSUE #29076: Invalid WARNING message when function has a parameter with a hyphen
**Description:**
$Subject

**Steps to reproduce:**
Run the following sample.

```
import ballerina/io;

public function main() {
    error e = error("bad sad");
    foo(e);
}

# + 'error - The error struct to be logged
function foo(error 'error) {
    io:println('error);
}
```

The following WARNING appears.
```
Compiling source
	error.bal
WARNING [error.bal:(8:5,8:11)] no such documentable parameter ''error'
```

**Affected Versions:**
Current master

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/23045

### PR DESCRIPTION
**Pull request by KRVPerera**
Fixes #29076

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 1]
```diff
@@ -5432,9 +5432,12 @@ private BLangMarkdownDocumentation createMarkdownDocumentationAttachment(Optiona
 
                     BLangIdentifier paraName = new BLangIdentifier();
                     Token parameterName = parameterDocLineNode.parameterName();
-                    paraName.value = parameterName.isMissing() ? "" : parameterName.text();
+                    var parameterNameValue = parameterName.isMissing() ? "" : parameterName.text();
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:5435]: Can we use `String`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 2]
```diff
@@ -5432,9 +5432,12 @@ private BLangMarkdownDocumentation createMarkdownDocumentationAttachment(Optiona
...
                     bLangParaDoc.parameterName = paraName;
-
+                    if (stringStartsWithSingleQuote(parameterNameValue)) {
+                        parameterNameValue = parameterNameValue.substring(1);
+                    }
+                    paraName.value = parameterNameValue;
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:5440]: Adding these lines before `bLangParaDoc.parameterName = paraName;` is more cleaner right?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java [hunk 3]
```diff
@@ -319,6 +319,11 @@ public void testDocFunction() {
         Assert.assertEquals(references.get(7).type, DocumentationReferenceType.ANNOTATION);
         Assert.assertEquals(references.get(7).referenceName, "annot");
 
+        var fooFunction = packageNode.getFunctions().get(5).getMarkdownDocumentationAttachment();
+        var exapmpleParam = fooFunction.getParameterDocumentations().get("example");
```
Comment (rdulmina) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java:323]:
```suggestion
        var exampleParam = fooFunction.getParameterDocumentations().get("example");
```

Comment (rdulmina) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java:323]: Why we use `var` instead of exact types?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 1 above)
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:5435]: We also need to replace unicode code points with respective unicode characters.
```suggestion
                    var parameterNameValue = parameterName.isMissing() ? "" : IdentifierUtils.unescapeUnicodeCodepoints(parameterName.text());
```

Try this example.
```bal
# + 'foo_\u{2345}\u{0376} - The error struct to be logged
function foo(error 'foo_\u{2345}\u{0376}) {}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 4]
```diff
@@ -5432,9 +5432,12 @@ private BLangMarkdownDocumentation createMarkdownDocumentationAttachment(Optiona
 
                     BLangIdentifier paraName = new BLangIdentifier();
                     Token parameterName = parameterDocLineNode.parameterName();
-                    paraName.value = parameterName.isMissing() ? "" : parameterName.text();
+                    var parameterNameValue = parameterName.isMissing() ? "" : parameterName.text();
                     bLangParaDoc.parameterName = paraName;
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:5436]: The order is a bit messy. We assign the `paraName` to `bLangParaDoc.parameterName` and then modify the `paraName` again. Shall we move the assignment to the end?

**Review by lochana-chathura — COMMENTED** [review]
There is one other place we use identifiers in the documentation.  Shall we fix that as well? :)

The below sample is also valid.
```bal
const string 'testConst = "YYY";

# This function prints const `'testConst`
function printTestConst() {
    // print 'testConst
}
```
Should be fixed at,
https://github.com/ballerina-platform/ballerina-lang/blob/addc95e27d632bc09bce135e5146548f5c8cb8b5/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java#L5559

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java (hunk 3 above)
Comment (KRVPerera) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java:323]: It is okay to use var right.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 5]
```diff
@@ -5637,6 +5641,12 @@ private void transformDocumentationBacktickContent(Node backtickContent,
             default:
                 throw new IllegalArgumentException("Invalid backtick content transformation");
         }
+        if (bLangRefDoc.identifier != null) {
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:5644]: Hope this is clean

Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:5644]: Looks good. 
btw I think we have to do this for `bLangRefDoc.qualifier` as well.
e.g. `'int:'β`

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java (hunk 3 above)
Comment (hasithaa) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java]: Even in Ballerina, we don't encourage to use `var`, because it reduces the readability of the code.

File: tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_function.bal [hunk 6]
```diff
@@ -52,3 +52,7 @@ function searchPeople () returns [string, int, float] {
 # + y - another thing to be added
 # + return - the sum of them
 function add (int x, int y) returns int  { return x + y; }
+
+# Test variable `'testQuotedConst`
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/documentation/markdown_function.bal:56]: We need to give a valid reference in order to test the removal of the quote here. Since `'testQuotedConst` is not defined in the scope this line anyway will give a warning.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 1 above)
Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java]: @KRVPerera shall we add this sample as a test case too. We don't have a test case for `IdentifierUtils.unescapeUnicodeCodepoints()` filter.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java (hunk 3 above)
Comment (KRVPerera) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/documentation/MarkdownDocumentationTest.java]: I replaced var with `BLangMarkdownParameterDocumentation`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 1 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java]: added a test

**Review by hasithaa — APPROVED** [review]
