### PR TITLE
Fix converting reference type values to `json`

### LINKED ISSUE #39907: [Bug]: `cloneWithType` is not working with TypeReferenceType
### Description

Gets the error message `value cannot be converted to 'json'` when trying to use `cloneWithType` with a TypeReferenceType

### Steps to Reproduce

Sample Ballerina code 

```bal
import ballerina/io;

public type GraphQLQuery record {|
    # The name of the operation if multiple exist in the query.
    string operationName?;
    # Query based on GraphQL syntax.
    string query?;
    # Additional variables for the query.
    record {} variables?;
|};

public type GraphQLQueries GraphQLQuery[];

GraphQLQueries payload = [{query : "abc"}, {query : "xyz"}];

public function main() returns error?{
    json stdJson = check payload.cloneWithType(json);

    io:println(stdJson);
}
```

execute `bal run` 

### Affected Version(s)

Ballerina Swan Lake 2201.4.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #39907

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by warunalakshitha** [comment]
Shall we add same fix for 4.x too

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 1]
```diff
@@ -2567,52 +2567,55 @@ private static boolean checkIsLikeStreamType(Object sourceValue, BStreamType tar
...
-            if (isValueType(elementType)) {
-                return checkIsType(elementType, targetType, new ArrayList<>());
-            }
+        Type referredSourceType = TypeUtils.getReferredType(sourceType);
+        switch (referredSourceType.getTag()) {
+            case TypeTags.ARRAY_TAG:
+                ArrayValue source = (ArrayValue) sourceValue;
+                Type elementType = ((BArrayType) referredSourceType).getElementType();
+                if (isValueType(elementType)) {
+                    return checkIsType(elementType, targetType, new ArrayList<>());
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2576]: Can we add a test for this line?

Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java]: Added a test and improved further.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 2]
```diff
@@ -2599,52 +2599,55 @@ private static boolean checkIsLikeStreamType(Object sourceValue, BStreamType tar
...
+                return true;
+            case TypeTags.RECORD_TYPE_TAG:
+                TypeValuePair typeValuePair = new TypeValuePair(sourceValue, targetType);
+                if (unresolvedValues.contains(typeValuePair)) {
+                    return true;
                 }
-            }
-            return true;
+                unresolvedValues.add(typeValuePair);
+                for (Object object : ((MapValueImpl) sourceValue).values()) {
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2641]: Shall we move this to a common method because this is similar to the `map` case as well?

File: langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal [hunk 3]
```diff
@@ -3359,6 +3359,89 @@ function testCloneWithTypeToTableNegative() {
...
+    if (stdJson7 is error) {
+        assertEquality("'GraphQLQueries3' value cannot be converted to 'json'",
+        <string>checkpanic stdJson7.detail()["message"]);
+    }
+    json|error stdJson8 = payload8.cloneWithType();
+    assertEquality(stdJson8 is error, true);
+    if (stdJson8 is error) {
+        assertEquality("'GraphQLQueries4' value cannot be converted to 'json'",
+        <string>checkpanic stdJson8.detail()["message"]);
+    }
```
Comment (HindujaB) [inline langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal:3442]: Shall we add some negative tests with table values?

Comment (Nadeeshan96) [reply langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal:3449]: Added.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java (hunk 2 above)
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java]: Moved.

**Review by HindujaB — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Comment by warunalakshitha** [comment]
Let's add the error message changes as a breaking change in release note.

**Comment by Nadeeshan96** [comment]
> Let's add the error message changes as a breaking change in release note.

Added them with https://github.com/ballerina-platform/ballerina-dev-website/pull/6589/commits/6064feaaffe0e49c347353cbb31246662a94c7dc.
