### PR TITLE
Fix issue when a referred constant cannot be resolved 

### LINKED ISSUE #31751: When type is not provided for constants with expressions, Compiler gives Bad Sad error
Consider the following code

```ballerina
public const UT_OBJECT_RW  = 0x16;
public const UT_COUNT = UT_OBJECT_RW + 1;
const int UT_MASK = (1 << UT_COUNT) - 1;
```

Compiling the above, gives the below error

```java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visit(ConstantValueResolver.java:123)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef.accept(BLangSimpleVarRef.java:61)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visitExpr(ConstantValueResolver.java:422)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visit(ConstantValueResolver.java:172)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr.accept(BLangBinaryExpr.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visitExpr(ConstantValueResolver.java:422)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visit(ConstantValueResolver.java:177)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangGroupExpr.accept(BLangGroupExpr.java:43)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visitExpr(ConstantValueResolver.java:422)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visit(ConstantValueResolver.java:171)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr.accept(BLangBinaryExpr.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visitExpr(ConstantValueResolver.java:422)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.visit(ConstantValueResolver.java:88)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangConstant.accept(BLangConstant.java:107)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.lambda$resolve$1(ConstantValueResolver.java:81)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.resolve(ConstantValueResolver.java:81)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:310)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:295)
        at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:204)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:112)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:398)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:343)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:179)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
        at io.ballerina.projects.Package.getCompilation(Package.java:135)
        at org.ballerinalang.test.BCompileUtil.jBallerinaBackend(BCompileUtil.java:185)
        at org.ballerinalang.test.BCompileUtil.compile(BCompileUtil.java:80)
```

### PR DESCRIPTION
**Pull request by SandaruJayawardana**
Fixes #31751

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 1]
```diff
@@ -86,8 +86,10 @@ public void visit(BLangConstant constant) {
         BConstantSymbol tempCurrentConstSymbol = this.currentConstSymbol;
         this.currentConstSymbol = constant.symbol;
         this.currentConstSymbol.value = visitExpr(constant.expr);
-        unresolvedConstants.remove(this.currentConstSymbol);
-        this.currentConstSymbol = tempCurrentConstSymbol;
+        if (this.currentConstSymbol.value != null) {
+            unresolvedConstants.remove(this.currentConstSymbol);
+            this.currentConstSymbol = tempCurrentConstSymbol;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:91]: Shouldn't this be reset irrespective of whether or not the constant was resolved.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 2]
```diff
@@ -86,8 +86,10 @@ public void visit(BLangConstant constant) {
         BConstantSymbol tempCurrentConstSymbol = this.currentConstSymbol;
         this.currentConstSymbol = constant.symbol;
         this.currentConstSymbol.value = visitExpr(constant.expr);
-        unresolvedConstants.remove(this.currentConstSymbol);
-        this.currentConstSymbol = tempCurrentConstSymbol;
+        if (this.currentConstSymbol.value != null) {
+            unresolvedConstants.remove(this.currentConstSymbol);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:90]: With this approach wouldn't we try to resolve the constant every time it is referenced even though we know it is an error. Wondering if we should fix the resolving logic instead and consider the key not being present + value being null to indicate an error.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 1 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:91]: Yes. I had done a mistake here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 2 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:90]: Yes I had done a mistake. We have to indicate an error for such scenarios.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 3]
```diff
@@ -122,6 +122,13 @@ public void visit(BLangSimpleVarRef varRef) {
             return;
         }
 
+        if (!this.unresolvedConstants.containsKey(varRef.symbol)) {
+            dlog.error(varRef.pos, DiagnosticErrorCode.INVALID_CONST_EXPRESSION,
+                    "cannot resolve '" + varRef.symbol.name.value + "'");
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:127]: Let's add a new diagnostic code (like CANNOT_RESOLVE_CONST) for this and pass the name of the constant as an argument.

e.g., https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java#L38

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 4]
```diff
@@ -122,6 +122,12 @@ public void visit(BLangSimpleVarRef varRef) {
             return;
         }
 
+        if (!this.unresolvedConstants.containsKey(varRef.symbol)) {
+            dlog.error(varRef.pos, DiagnosticErrorCode.CANNOT_RESOLVE_CONST, varRef.symbol.name.value);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:126]: Shall we use `constSymbol` instead of `varRef.symbol`.

Let's update L132 also.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java [hunk 5]
```diff
@@ -147,7 +147,11 @@ public void testNegative() {
                 294, 7);
         BAssertUtil.validateError(compileResult, index++, "expression is not a constant expression",
                 294, 17);
-        BAssertUtil.validateError(compileResult, index, "constant declarations are allowed only at module level",
+        BAssertUtil.validateError(compileResult, index++, "constant declarations are allowed only at module level",
                 297, 5);
+        BAssertUtil.validateError(compileResult, index++, "type is required for constants with expressions",
+                301, 25);
+        BAssertUtil.validateError(compileResult, index,
+                "cannot resolve constant 'UT_COUNT'", 302, 27);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java:155]: Can't these be merged?

```suggestion
        BAssertUtil.validateError(compileResult, index, "cannot resolve constant 'UT_COUNT'", 302, 27);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 6]
```diff
@@ -122,8 +122,14 @@ public void visit(BLangSimpleVarRef varRef) {
             return;
         }
 
+        if (!this.unresolvedConstants.containsKey(varRef.symbol)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:125]:
```suggestion
        if (!this.unresolvedConstants.containsKey(constSymbol)) {
```

**Review by MaryamZi — APPROVED** [review]
