### PR TITLE
Fix issue in parsing nil literal inside match guard

### LINKED ISSUE #32053: nballerina bad/sad from type guard/anonymous function confusion
See

https://github.com/ballerina-platform/nballerina/blob/97bb9ebe11f6cd3c2c36e998f20c1544113e1624/compiler/modules/front/parseExpr.bal#L377

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$title

Fixes #32053

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -10875,6 +10862,11 @@ private STNode parseImplicitAnonFunc(STNode params, boolean isRhsExpr) {
             case BRACED_EXPRESSION:
                 params = getAnonFuncParam((STBracedExpressionNode) params);
                 break;
+            case NIL_LITERAL:
+                STNilLiteralNode nilLiteralNode = (STNilLiteralNode) params;
+                params = STNodeFactory.createImplicitAnonymousFunctionParameters(nilLiteralNode.openParenToken,
+                        STNodeFactory.createNodeList(new ArrayList<>()), nilLiteralNode.closeParenToken);
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:10868]:
```suggestion
                        STNodeFactory.createEmptyNodeList(), nilLiteralNode.closeParenToken);
```

**Review by lochana-chathura — APPROVED** [review]
