### PR TITLE
Fix path parameter URL in OpenAPI client generation

### LINKED ISSUE #26149: Cannot access OpenAPI generated client code URL with the path parameter
**Description:**
Parameter value for path parameters couldn't assaign properly when openAPI generated client  code function has URL with path parameter.  Please refer for more information : [https://ballerina-platform.slack.com/archives/C47EAELR1/p1601157193008700](url)
 
**Steps to reproduce:**

1. Create openapi client using below command:
`ballerina openapi gen-client mcClient:MarketContext openapi-marketcontext.yaml`

Generated client
```ballerina
import ballerina/http;//=====================================
//============Client Config============
//=====================================
public type MarketContextClientConfig record {
    string serviceUrl;
    http:ClientConfiguration clientConfig;
};//==============================
//============Client============
//==============================
public type MarketContextClient client object {
    public http:Client clientEp;
    public MarketContextClientConfig config;    public function __init(MarketContextClientConfig config) {
        http:Client httpEp = new(config.serviceUrl, {auth: config.clientConfig.auth, cache: config.clientConfig.cache});
        self.clientEp = httpEp;
        self.config = config;
    }    public remote function getMarketContext(string tid) returns http:Response | error {
        http:Client getMarketContextEp = self.clientEp;
        http:Request request = new;        // TODO: Update the request as needed
        return check getMarketContextEp->get("/marketcontext/{tid}", message = request);
    }};
``` 

2. Try to create client call using this main file

```ballerina 
import ballerina/io;
   public function main() {    
        MarketContextClientConfig mcConfig = {
             serviceUrl: "http://localhost:8004/api",
             clientConfig: { }
        };    
      MarketContextClient mcClient = new MarketContextClient(mcConfig);   
      http:Response resp = mcClient->getMarketContext("42");   
    //result details = mcClient->getMarketContext("42");
     io:println(resp.toString());}
```
 
**Affected Versions:**
1.2.8 ballerina

**OS, DB, other environment details and versions:**

**Related Issues:**
[https://ballerina-platform.slack.com/archives/C47EAELR1/p1601157193008700](url)

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
Fixes #26149

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java [hunk 1]
```diff
@@ -127,8 +127,37 @@ private void setPaths(OpenAPI openAPI) throws BallerinaOpenApiException {
...
+        }
+    }
+
+    /**
+     * Checks if there are any path parameters in the operations.
+     * @param path  The path item in the OpenAPI spec.
+     * @return True if there are path parameters, else false.
+     */
+    private boolean hasPathParams(PathItem path) {
+        if (null != path.getParameters() && path.getParameters().size() > 0) {
```
Comment (praveennadarajah) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java:147]:
```suggestion
        if (path.getParameters() != null && path.getParameters().size() > 0) {
```

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java [hunk 2]
```diff
@@ -127,8 +127,37 @@ private void setPaths(OpenAPI openAPI) throws BallerinaOpenApiException {
...
+            return path.getParameters().stream()
+                    .anyMatch(parameter -> null != parameter.getIn() && parameter.getIn().equals("path"));
```
Comment (praveennadarajah) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java:149]:
```suggestion
                    .anyMatch(parameter -> parameter.getIn() != null) && parameter.getIn().equals("path"));
```

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java [hunk 3]
```diff
@@ -127,8 +127,37 @@ private void setPaths(OpenAPI openAPI) throws BallerinaOpenApiException {
...
+        }
+        if (path.readOperations().size() > 0) {
+            return path.readOperations().stream().anyMatch(operation -> {
+                if (null != operation.getParameters() && operation.getParameters().size() > 0) {
```
Comment (praveennadarajah) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java:153]:
```suggestion
                if (operation.getParameters() != null && operation.getParameters().size() > 0) {
```

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java [hunk 4]
```diff
@@ -127,8 +127,37 @@ private void setPaths(OpenAPI openAPI) throws BallerinaOpenApiException {
...
+                    return operation.getParameters().stream()
+                            .anyMatch(parameter -> null != parameter.getIn() && parameter.getIn().equals("path"));
```
Comment (praveennadarajah) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java:155]:
```suggestion
                            .anyMatch(parameter -> parameter.getIn() != null && parameter.getIn().equals("path"));
```

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java [hunk 5]
```diff
@@ -127,8 +127,37 @@ private void setPaths(OpenAPI openAPI) throws BallerinaOpenApiException {
...
+
+    /**
+     * Checks if there are any path parameters in the operations.
+     * @param path  The path item in the OpenAPI spec.
+     * @return True if there are path parameters, else false.
+     */
+    private boolean hasPathParams(PathItem path) {
+        if (path.getParameters() != null && path.getParameters().size() > 0) {
+            return path.getParameters().stream()
+                    .anyMatch(parameter -> parameter.getIn() != null && parameter.getIn().equals("path"));
```
Comment (praveennadarajah) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java:149]: Shall we assign the string `"path" ` to private static final variable and use it here instead of hard coding the value directly?
`private static final String PATH = "path"`

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java [hunk 6]
```diff
@@ -127,8 +127,37 @@ private void setPaths(OpenAPI openAPI) throws BallerinaOpenApiException {
...
+        }
+        if (path.readOperations().size() > 0) {
+            return path.readOperations().stream().anyMatch(operation -> {
+                if (operation.getParameters() != null && operation.getParameters().size() > 0) {
+                    return operation.getParameters().stream()
+                            .anyMatch(parameter -> parameter.getIn() != null && parameter.getIn().equals("path"));
```
Comment (praveennadarajah) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java:155]: Do the same [change](https://github.com/ballerina-platform/ballerina-lang/pull/26386/files#r506323527) here as well.

**Review by praveennadarajah — APPROVED** [review]

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java [hunk 7]
```diff
@@ -127,8 +128,37 @@ private void setPaths(OpenAPI openAPI) throws BallerinaOpenApiException {
...
+        if (path.readOperations().size() > 0) {
+            return path.readOperations().stream().anyMatch(operation -> {
+                if (operation.getParameters() != null && operation.getParameters().size() > 0) {
+                    return operation.getParameters().stream().anyMatch(parameter -> parameter.getIn() != null &&
+                            parameter.getIn().equals(GeneratorConstants.PATH));
+                }
+                return false;
+            });
         }
+        return false;
```
Comment (NipunaRanasinghe) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java:161]: IMO better to do an early return in here. WDYT? 
```suggestion
        if (path.readOperations().isEmpty()) {
            return false;
        }
        return path.readOperations().stream().anyMatch(operation -> {
            if (operation.getParameters() != null && operation.getParameters().size() > 0) {
                return operation.getParameters().stream().anyMatch(parameter -> parameter.getIn() != null &&
                        parameter.getIn().equals(GeneratorConstants.PATH));
            }
            return false;
        });
    }
```

Comment (NipunaRanasinghe) [reply misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java:161]: Also, don't we need to validate whether `path.readOperations()` is null ?

Comment (lnash94) [reply misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/model/BallerinaOpenApi.java]: yeah we don't need to validate with null :) it return list

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM

**Review by hevayo — APPROVED** [review]
