### PR TITLE
Reduce memory taken during compilation

### LINKED ISSUE #41384: [Task]: Optimise ballerina bir storing logic
### Description

$Subject requires for reduce memory during ballerina compilation 

### Describe your task(s)

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #41407: [Bug]: OOM when a large project is compiled for the first time when generating BIRs
### Description

This is originally observed when the openhealth projects are build for the first time. When we first compile a project the dependencies are downlaoded as Bala (source files) projects and compiled locally and the BIRs are generated locally. We cache these BIRs in ModuleContext and in BPackageSymbol for all the modules (dependencies) and consumes a lots of memory to keep these BIRs. If the project is big enough, there is a possibility that the program goes OOM.  for example, the below code snippet can cause a OOM

```bal
import ballerina/io as _;
import ballerinax/health.fhir.r4 as _;
import ballerinax/health.fhir.r4.international401 as _;
import ballerinax/health.hl7v2 as _;
import ballerinax/health.hl7v2.utils.v2tofhirr4 as _;
import ballerinax/health.hl7v23 as _;
import ballerinax/health.hl7v2commons as _;
```
We have done further optimisations on memory usages on lambda functions from the compiler frontend side and still we see OOM occurring due to compilation and BIR generation. Initially we saw that the OOM happened due to the capturedClosureEnv variable in lambda functions which we keep them unnecessarily. Once the links to those variables are removed now the OOM occur at the later stage. After analysing the heap dump, we saw that the cause for the OOM is the number of lambda functions. This is due to the number of module level annotations written. Each annotation is wrapped with a lambda function in compiler side. But if we further dig into the lambda functions, what actually take up the most of the memory is the body of the lambda functions, which are the annotation themselves. 
image
In the above image, 1, 2, 3 are the ModuleContext, BPackageSymbol and the BIRPackage, which take up the most of the memory.

In ModuleContext, srcDocContextMap takes up the majority of the memory and the compilationUnit inside it, has lots of typeDefinitions and these type definitions have annotations which are represented by record literals. There is no way to remove those record literals as they are the real representation of the annotations. See the image below, there are a large number of DocumentContexts in a single ModuleContext.
image
In BPackageSymbol, We have the BIR stored as a field. This BIR mostly contains BIRFunctions mostly. Some module may have thousands of BIRFunctions due to annotation desugaring. But what takes up the memory is not the function itself, but the body of the function, which is the annotation itself. By looking at the Retained memory and comparing that to the shallow memory taken up by the function, I don't think removing the lambda functions will solve the problem.
image
image
With the front end changes we did to the compiler, the OOM occur only for a fresh build (Easily reproducible if we delete the BIR cache and keep the Bala cache). So to fix the OOM happening for such large projects, we have to either increase the memory allocation per JVM with the current design or we have to change the way we compile the dependencies and keeping them in the cache (right now we compile all the dependencies and keep their BIRs in the memory)

Adding @hasithaa @sameeragunarathne

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
This PR reduces the memory taken during compilation by means of the following.
1. Cleans up the BIR after the code generation phase.
2. Do not cache the TextDocument instance of dependent modules.
3. Remove BLangPackages of dependent modules after the code generation phase.

Fixes #41384
Fixes #41407

With Ballerina 2201.7.3 version without these changes the following code took about 900 MB memory for the heap at average when compiling the code for the first time.
```bal
import ballerina/io as _;
import ballerinax/health.fhir.r4 as _;
import ballerinax/health.fhir.r4.international401 as _;
import ballerinax/health.hl7v2 as _;
import ballerinax/health.hl7v2.utils.v2tofhirr4 as _;
import ballerinax/health.hl7v23 as _;
import ballerinax/health.hl7v2commons as _;

public function main() returns error? {}
```
With these changes introduced on top of that it takes about 700 MB memory for the heap at average when compiling the code for the first time.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by HindujaB — APPROVED** [review]
LGTM

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java [hunk 1]
```diff
@@ -177,8 +177,10 @@ private void performCodeGen() {
                         new PackageDiagnostic(diagnostic, moduleContext.descriptor(), moduleContext.project()));
             }
 
-            //TODO: remove this once ballerina-lang#41407 is fixed
             ModuleContext.shrinkDocuments(moduleContext);
+            if (moduleContext.project().kind() == ProjectKind.BALA_PROJECT) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java:181]: Why do we need this check?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java [hunk 2]
```diff
@@ -837,12 +837,10 @@ private BIRFunction getFunction(BIRPackage module, String funcName) {
...
-        } else {
-            for (BPackageSymbol importPkgSymbol : packageSymbol.imports) {
-                if (importPkgSymbol == null) {
-                    continue;
-                }
-                return listenerDeclarationFound(importPkgSymbol);
+        }
+        for (BPackageSymbol importPkgSymbol : packageSymbol.imports) {
+            if (importPkgSymbol != null && listenerDeclarationFound(importPkgSymbol)) {
+                return true;
```
Comment (gabilang) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java:843]: Shall we consider to add a test cases to cover this line?

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java (hunk 1 above)
Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java:181]: We only make `null` the BLangPackages of the dependencies of a Ballerina package (e.g. the imported modules of this Ballerina snippet https://github.com/ballerina-platform/ballerina-lang/issues/41407#issue-1902210827 here) because the `BLangPackage`s of the Ballerina package is needed for other tasks such as to return the semantic model to be used by the language server and vscode. The `if` check returns true for such modules.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java (hunk 2 above)
Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java:843]: Added

**Review by warunalakshitha — APPROVED** [review]
LGTM
