### PR TITLE
Fix is-expression with service type objects

### LINKED ISSUE #31942: Subtype check for service objects with remote methods produce incorrect results
**Description:**
$title.

Remote methods are part of the type so they need to be considered for type checking. Resource methods are not, so they can/should be ignored.

**Steps to reproduce:**
```ballerina
import ballerina/io;

service class Foo {
    remote function x() {
        
    }
}

service class Bar {

}


public function main() {
    // Foo f = new Bar(); // Compilation error.

    any b = new Bar();
    io:println(b is Foo); // true, should be false!
}
```

**Affected Versions:**
slbeta2

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/31906

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title

Fixes #31942

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java [hunk 1]
```diff
@@ -391,6 +391,11 @@ public void testObjectIsCheckWithCycles() {
         BRunUtil.invoke(result, "testObjectIsCheckWithCycles");
     }
 
+    @Test(description = "Test is-expr with service type objects")
+    public void testServiceObjects() {
+        BRunUtil.invoke(result, "testServiceObjects");
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java:396]: We have several other tests that have the same `BRunUtil.invoke(result, <function-name>);` approach. Shall we move them to a data provider?
Like this, 
https://github.com/ballerina-platform/ballerina-lang/blob/ebae8819aed845fb7a3c53e3508d635f2fd2faa9/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/MultiplyOperationTest.java#L81

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal [hunk 2]
```diff
@@ -536,6 +536,54 @@ function testObjectIsCheckWithCycles() {
...
+    }
+}
+
+function testServiceObjects() {
+    any a = new ServiceClassA();
+    any b = new ServiceClassB();
+    any c = new ServiceClassC();
+    any d = new ServiceClassD();
+
+    assertTrue(a is ServiceClassA);
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal:570]: Shall we check the `ServiceClassB` & `ServiceClassC` as well for variables `a` & `d`?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java (hunk 1 above)
Comment (Nadeeshan96) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/TypeTestExprTest.java:396]: I will look into this.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal (hunk 2 above)
Comment (Nadeeshan96) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal:570]: I have not added them yet because I have this question, https://github.com/ballerina-platform/ballerina-lang/issues/31942#issuecomment-890961115. I will add them after I get the answer for this. Currently the runtime behaves as same as the compile time. When there is no compile time error the `is` check will give `true` otherwise `false`.

**Review by warunalakshitha — COMMENTED** [review]
LGTM

**Review by HindujaB — COMMENTED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
