### PR TITLE
Return user-defined errors in `create variable and check error` with check CA

### LINKED ISSUE #42127: [Bug]: Incorrect result for "create variable and check error" code action
### Description

When we have a function call expression where the expression type is a subtype of an error, we add a union of error type references to the enclosing function's return type. This behaviour is incorrect and error prone.

### Steps to Reproduce

Consider the below two sample.

1. Code action result in a valid code
```ballerina
public type Error E1|E2;
public type E1 distinct error;
public type E2 distinct error;

public function main() {
    <cursor>getValueOrError();
}

function getValueOrError() returns int|Error => 1;
```
2. Code action result in an invalid code
```ballerina
import ballerina/yaml;

public function main() {
    <cursor>yaml:readFile("./resources/sample.yaml");
}
```

### Affected Version(s)

2201.8.4

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose

Fixes #42127

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 1]
```diff
@@ -329,6 +331,75 @@ public static TypeSymbol getRawType(TypeSymbol typeDescriptor) {
         }
         return typeDescriptor;
     }
+    
+    public static boolean isErrorOrUnionOfErrors(TypeSymbol type) {
```
Comment (nipunayf) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:335]: Can we document this function since it's a public method in CommonUtil?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 2]
```diff
@@ -329,6 +331,75 @@ public static TypeSymbol getRawType(TypeSymbol typeDescriptor) {
...
+                        getErrorTypes(memberType, memberType, errorTypes);
+                    }
+                }
+            } else {
+                getErrorTypes(rawType, type, errorTypes);
+            }
+        }
+    }
+
+    public static List<TypeSymbol> extractErrorTypesFromUnion(UnionTypeSymbol unionType) {
```
Comment (nipunayf) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:372]: Same with this method

File: language-server/modules/langserver-stdlib/src/main/ballerina/type_source1.bal [hunk 3]
```diff
@@ -37,3 +37,10 @@ public type TestObject1 object {
 public type ErrorOne error<record { int code; }>;
 
 public type ErrorTwo error<record { string[] alternatives; }>;
+
+public type Error1 E1|E2;
+public type E1 distinct error;
+public type E2 distinct error;
+public type E3 distinct error;
+public type Error2 E3|int;
+public type Error Error1|Error2;
```
Comment (SasinduDilshara) [inline language-server/modules/langserver-stdlib/src/main/ballerina/type_source1.bal:46]: shall we add a test with a scenario of intersection between two error types?

File: language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableWithCheck3.bal [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+function foo1() {
+    getValueOrError1();
+}
+
+function getValueOrError1() returns int|Error1 => 1;
+
+public type E3 distinct error;
+public type Error2 E3|int;
+public type Error Error1|Error2;
+
```
Comment (LakshanWeerasinghe) [inline language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableWithCheck3.bal:14]: We need to add a negative test where on union member of the error is non-public and its a union with another non-error type.

```ballerina
type Error3 E3|int;
public type NonPublicError Error1|Error3;

function getValueOrError2() returns NonPublicError => 1;
```

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 1 above)
Comment (KavinduZoysa) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:341]: Added

File: language-server/modules/langserver-stdlib/src/main/ballerina/type_source1.bal (hunk 3 above)
Comment (KavinduZoysa) [reply language-server/modules/langserver-stdlib/src/main/ballerina/type_source1.bal:46]: Added

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java [hunk 5]
```diff
@@ -109,6 +122,29 @@ public List<CodeAction> getCodeActions(Diagnostic diagnostic,
...
+            if (errorMemType.typeKind() != TypeDescKind.TYPE_REFERENCE) {
+                continue;
+            }
+            Optional<ModuleSymbol> module = errorMemType.getModule();
+            if (module.isEmpty()) {
+                continue;
+            }
+            if (currentModule.equals(module.get().id().moduleName())) {
+                continue;
+            }
```
Comment (mindula) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java:137]: Shall we combine these two checks?

File: language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableWithCheck3.bal (hunk 4 above)
Comment (KavinduZoysa) [reply language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/source/createVariableWithCheck3.bal:14]: Added

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java [hunk 6]
```diff
@@ -83,9 +91,14 @@ public List<CodeAction> getCodeActions(Diagnostic diagnostic,
...
-                .filter(member -> CommonUtil.getRawType(member).typeKind() == TypeDescKind.ERROR)
-                .collect(Collectors.toList());
+        List<TypeSymbol> errorMemberTypes = CommonUtil.extractErrorTypesFromUnion(unionTypeDesc);
+        Path path = Path.of(URI.create(uri));
+        Optional<Module> module = context.workspace().module(path);
+        if (module.isPresent()) {
+            if (containsModuleLevelPrivateTypes(module.get().moduleName().toString(), errorMemberTypes)) {
+                return Collections.emptyList();
+            }
+        }
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java]: Changed

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 7]
```diff
@@ -330,6 +331,88 @@ public static TypeSymbol getRawType(TypeSymbol typeDescriptor) {
...
+            TypeSymbol rawType = getRawType(type);
+            if (rawType.typeKind() == TypeDescKind.UNION) {
+                if (((UnionTypeSymbol) rawType).memberTypeDescriptors().stream()
+                        .allMatch(CommonUtil::isErrorOrUnionOfErrors)) { 
+                    errorTypes.add(type);    
+                } else {
+                    for (TypeSymbol memberType : ((UnionTypeSymbol) rawType).userSpecifiedMemberTypes()) {
+                        getErrorTypes(memberType, memberType, errorTypes);
+                    }
+                }
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java]: Changed

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java [hunk 8]
```diff
@@ -109,6 +122,24 @@ public List<CodeAction> getCodeActions(Diagnostic diagnostic,
...
+            }
+            Optional<ModuleSymbol> module = errorMemType.getModule();
+            if (module.isEmpty() || currentModule.equals(module.get().id().moduleName())) {
+                continue;
+            }
+            TypeReferenceTypeSymbol typeRef = (TypeReferenceTypeSymbol) errorMemType;
+            Symbol typeDef = typeRef.definition();
+            if (typeDef instanceof Qualifiable && !((Qualifiable) typeDef).qualifiers().contains(Qualifier.PUBLIC)) {
+                return true;
+            }
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java]: Changed

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 9]
```diff
@@ -330,6 +331,88 @@ public static TypeSymbol getRawType(TypeSymbol typeDescriptor) {
...
+        List<TypeSymbol> exactErrorTypes = new ArrayList<>();
+        for (TypeSymbol memType : unionType.userSpecifiedMemberTypes()) {
+            getErrorTypes(memType, null, exactErrorTypes);
+        }
+        List<TypeSymbol> errorMemberTypes = unionType.memberTypeDescriptors().stream()
+                .filter(member -> CommonUtil.getRawType(member).typeKind() == TypeDescKind.ERROR)
+                .collect(Collectors.toList());
+        List<TypeSymbol> missingErrorTypes = new ArrayList<>();
+        setMissingErrorTypes(exactErrorTypes, errorMemberTypes, missingErrorTypes);
+        errorMemberTypes.addAll(missingErrorTypes);
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java]: Yes, this logic is redundant, hence removed. Thank you.

**Comment by nipunayf** [comment]
The same error occurs for the `change return type` CA as well: https://github.com/ballerina-platform/ballerina-lang/issues/42292. We may use the same methods for this CA and perhaps complete it in a different PR.

**Comment by LakshanWeerasinghe** [comment]
Let say the below code is in a separate module.
```ballerina
public type Error1 distinct error;
type Error2 distinct error;
public type NonPublicError int|Error2;

public function getValueOrError4() returns NonPublicError|Error1 => 1;
```

And we have another ballerina file like below,
```ballerina
import package_test.mod1;

public function main() {
    <cursor>mod1:getValueOrError4();
}
```
When we apply the code action it gives an error. This should be negative test case where we shouldn't suggest the code action.

**Comment by LakshanWeerasinghe** [comment]
> Let say the below code is in a separate module.
> 
> ```ballerina
> public type Error1 distinct error;
> type Error2 distinct error;
> type NonPublicError int|Error2;
> 
> public function getValueOrError4() returns NonPublicError|Error1 => 1;
> ```
> 
> And we have another ballerina file like below,
> 
> ```ballerina
> import package_test.mod1;
> 
> public function main() {
>     <cursor>mod1:getValueOrError4();
> }
> ```
> 
> When we apply the code action it gives an error. This should be negative test case where we shouldn't suggest the code action.

Moved this to a separate issue #42340 because this PR is addressing issues related to "create variable with check" code action.

**Review by LakshanWeerasinghe — APPROVED** [review]
LGTM!
