### PR TITLE
Check decimal overflow at compile time

### LINKED ISSUE #37541: [Bug]: No error for out of range large decimal value
### Description

$title.

### Steps to Reproduce

```ballerina
function errorFunction() {
    decimal _ = 10092233720368547758081009223372036854775; // no error
}
```

### Affected Version(s)
Current master, 2201.3.0-SNAPSHOT

### OS, DB, other environment details and versions

_No response_

### Labels

CompilerFE

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose

Fixes #37541

### CODE REVIEW

**Comment by KavinduZoysa** [comment]
Decimal MAX and MIN are determined based on https://speleotrove.com/decimal/dbover.html

**Comment by chiranSachintha** [comment]
> Decimal MAX and MIN are determined based on https://speleotrove.com/decimal/dbover.html

According to this 
Decimal Max value contains
- 34 digits in significand 
- 6144 in exponent(In ballerina spec this value is `6111`)
So the following program should be allowed. Isn't it?
```ballerina
public function main() {
    decimal k = 9999999999999999999999999999999999E6144d;
}
```
Decimal Min value contains
- 34 digits in significand
- -6143  in exponent(In ballerina spec this value is `-6176`)

According to that following program should be disallowed.
```ballerina
public function main() {
    decimal k = -9999999999999999999999999999999999E-6178d;
}
```

**Comment by prakanth97** [comment]
```
decimal z = 9.999999999999999999999999999999999e6144 * 9.999999999999999999999999999999999e6144;
```
According to the spec https://ballerina.io/spec/lang/master/#section_5.2.4.2,  this is runtime decimal overflow. Right?
Shall we include the runtime changes as well?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -4024,6 +4030,24 @@ boolean validateFloatLiteral(Location pos, String numericLiteral) {
...
     }
 
+    boolean validateDecimalLiteral(Location pos, String decimalLiteral) {
+        BigDecimal bd;
+        try {
+            bd = new BigDecimal(decimalLiteral, MathContext.DECIMAL128);
+        } catch (NumberFormatException e) {
+            // If there is an error, that means there is a parsing error.
+            if (dlog.errorCount() == 0) {
+                dlog.error(pos, DiagnosticErrorCode.OUT_OF_RANGE, decimalLiteral, symTable.decimalType);
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4040]: Shall we add a test for this

**Comment by KavinduZoysa** [comment]
> ```
> decimal z = 9.999999999999999999999999999999999e6144 * 9.999999999999999999999999999999999e6144;
> ```
> 
> According to the spec https://ballerina.io/spec/lang/master/#section_5.2.4.2, this is runtime decimal overflow. Right? Shall we include the runtime checks as well?

Runtime team is working on that

**Comment by KavinduZoysa** [comment]
> ```
> decimal z = 9.999999999999999999999999999999999e6144 * 9.999999999999999999999999999999999e6144;
> ```
> 
> According to the spec https://ballerina.io/spec/lang/master/#section_5.2.4.2, this is runtime decimal overflow. Right? Shall we include the runtime checks as well?

Runtime team is working on that

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 2]
```diff
@@ -169,6 +169,12 @@ public class Types {
     private SymbolEnv env;
     private boolean ignoreObjectTypeIds = false;
 
+    private static final BigDecimal DECIMAL_MAX =
+            new BigDecimal("9.999999999999999999999999999999999e6144", MathContext.DECIMAL128);
+
+    private static final BigDecimal DECIMAL_MIN =
+            new BigDecimal("-9.999999999999999999999999999999999e6144", MathContext.DECIMAL128);
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:176]: I think you are talking about the smallest value(negative exponents). This PR is only for detecting maximum and minimum values (positive exponent).

**Comment by KavinduZoysa** [comment]
> According to this Decimal Max value contains
> 
> * 34 digits in significand
> * 6144 in exponent(In ballerina spec this value is `6111`)
>   So the following program should be allowed. Isn't it?
> 

No, we need to consider about the scientific notation, Otherwise `6144` is not the maximum value, please go through the last paragraphs of pointed documentation.

> 
> Decimal Min value contains
> 
> * 34 digits in significand
> * -6143  in exponent(In ballerina spec this value is `-6176`)
> 

We are not working on smallest values in this PR.

> According to that following program should be disallowed.
> 
> ```ballerina
> public function main() {
>     decimal k = -9999999999999999999999999999999999E-6178d;
> }
> ```
 This is incorrect because k = -9.999999999999999999999999999999999E-6145d, which is less than E_min (-6143)

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java [hunk 3]
```diff
@@ -76,5 +76,12 @@ void testDecimalValueNegativeLiteral() {
         BAssertUtil.validateError(negative, i++, "operator '+' not defined for 'float' and 'decimal'", 38, 17);
         BAssertUtil.validateError(negative, i++, "operator '-' not defined for 'float' and 'decimal'", 39, 17);
         BAssertUtil.validateError(negative, i++, "operator '+' not defined for 'decimal' and 'float'", 41, 17);
+        BAssertUtil.validateError(negative, i++, "'9.9999999999999999999999999999999999e6144' is out of range" +
```
Comment (prakanth97) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java:79]: Shall we change the error msg to not to include the larger number because if overflow number is bigger then error msg also will increase?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 4]
```diff
@@ -4024,6 +4030,24 @@ boolean validateFloatLiteral(Location pos, String numericLiteral) {
         return true;
     }
 
+    boolean validateDecimalLiteral(Location pos, String decimalLiteral) {
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4033]: Shall we rename the name the method to `isValidDecimalNumber` or similar, instead of mentioning literal? because I can use this function in my fix #37726 as well

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Changed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 1 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4052]: Added

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java (hunk 3 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java:79]: @gimantha, WDYT?
An error message like `decimal is out of range` is enough?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:179]: Ack. Then we can use `DECIMAL_MAX.negate()`, instead of defining the `DECIMAL_MIN` value. right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 5]
```diff
@@ -172,6 +172,12 @@ public class Types {
     private boolean ignoreObjectTypeIds = false;
     private static final String BASE_16 = "base16";
 
+    private static final BigDecimal DECIMAL_MAX =
+            new BigDecimal("9.999999999999999999999999999999999e6144", MathContext.DECIMAL128);
+
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:177]: Is this value correct?
According to the pdf that you shared,
```
The finite numbers are defined by a sign, an exponent (which is a power of ten), and a 
decimal integer coefficient. The value of a finite number is given by (–1)sign × coefficient × 10^exponent. 
```
According to this coefficient is a decimal integer. So `decimal_max` value should be `9999999999999999999999999999999999e6144`. Isn't it?

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:177]: Hope you have read the pointed documentation as mentioned in https://github.com/ballerina-platform/ballerina-lang/pull/37823#issuecomment-1265156320, at the end, it is mentioned that `For the decimal32 format, the largest normal number is 9.999999 × 10Emax` 
If `9999999999999999999999999999999999e6144` is max value for decimal128, how does 6144 becomes max value?

Also please go through the topic `decContext module` at https://speleotrove.com/decimal/decnumber.pdf

The sentence you pointed out says how decimal value is represented in the implementation.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:179]: Yes, but that does not introduce much difference right?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java (hunk 3 above)
Comment (gimantha) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java:79]: Dont we need to make this consistent with ints and floats?

Comment (gimantha) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java:79]: for ints, we give `Integer <int value> too large`

Comment (gimantha) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueNegativeTest.java:79]: In master we dont have `Integer <int value> too large` or `Integer <int value> too small` errors. instead we have `out of range`. I dont think it is good to reformat what user has given originally. Also we cannot reformat to smaller length always right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:179]: Yeah. My concern is with the name of the variable.

**Review by chiranSachintha — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_large_exponent_literal.bal [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+// Unless required by applicable law or agreed to in writing,
+// software distributed under the License is distributed on an
+// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+// KIND, either express or implied.  See the License for the
+// specific language governing permissions and limitations
+// under the License.
+
+function testTooLargeExponents() {
+    decimal _ = 1e10000000000000; // error
+}
```
Comment (prakanth97) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/decimal/decimal_large_exponent_literal.bal:19]: Shall we add a new line here

**Review by chiranSachintha — APPROVED** [review]
