### PR TITLE
Fix issue in isolation inference with isolated start action

### LINKED ISSUE #37036: Function with isolated start action not inferred as isolated
**Description:**
$title.

**Steps to reproduce:**
```ballerina
function test() {
    _ = start invoke();
}

public function main() {
    panic error((test is isolated function ()).toString()); // false
}

public isolated function invoke() {
}
```

**Affected Versions:**
2201.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by lasinicl**
## Purpose
$title

Fixes #37036

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedWorkerTest.java [hunk 1]
```diff
@@ -201,10 +217,64 @@ public Object[] functionsToTestIsolationInferenceWithStartAction() {
...
                 "testNonIsolationInferenceWithStartAction",
                 "testServiceClassMethodIsolationInference",
-                "testClientClassMethodIsolationInference"
+                "testClientClassMethodIsolationInference",
+                "testIsolationInferenceWithStarActionInvokingPublicFunction"
         };
     }
 
+    // This is called from the test file via the attach method of the listener.
+    public static Object testServiceDeclarationMethodIsolationInference(BObject listener, BObject s, Object name) {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedWorkerTest.java:226]: Can this be void instead, to avoid having to return null?

File: tests/jballerina-unit-test/src/test/resources/test-src/isolated-workers/isolation_inference_with_start_action.bal [hunk 2]
```diff
@@ -399,6 +399,69 @@ function testClientClassMethodIsolationInference() {
...
+function f18() {
+    _ = start invoke2();
+}
+
+public isolated function invoke() {
+}
+
+public function invoke2() {
+}
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/isolated-workers/isolation_inference_with_start_action.bal:415]: Shall we also add a test where the called function is non-isolated due to actually not being isolated (rather than not inferring because public)?

**Review by MaryamZi — APPROVED** [review]
Let's also send a PR to master with these changes.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedWorkerTest.java (hunk 1 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/isolation/IsolatedWorkerTest.java:226]: Never mind, just realized this is mapped directly to attach.

**Review by MaryamZi — APPROVED** [review]
