### PR TITLE
[LS] Fix find all references for user defined error types and rename module alias

### LINKED ISSUE #30466: Renaming a module alias causes compilation failures
**Description:**
Consider the following capture

https://user-images.githubusercontent.com/1329674/117640160-5d1e0980-b1a2-11eb-959e-41caebc9a009.mp4

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
$subject

Partially address the issue in #29276
Fixes #30466

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/rename/RenameUtil.java [hunk 1]
```diff
@@ -51,8 +68,26 @@ private RenameUtil() {
...
+        NonTerminalNode nodeAtCursor = CommonUtil.findNode(cursorPosRange, document.get().syntaxTree());
+
+        if (onQNameReferenceNode(context, nodeAtCursor)) {
+            return handleQNameReferenceRename(context, document.get(), nodeAtCursor, newName);
+        } else if (onImportPrefixNode(context, nodeAtCursor)) {
+            return handleImportPrefixRename(context, document.get(), nodeAtCursor, newName);
+        } else if (onImportDeclarationNode(context, nodeAtCursor)) {
+            return handleImportDeclarationRename(context, document.get(),
+                    (ImportDeclarationNode) nodeAtCursor.parent(), newName);
+        }
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/rename/RenameUtil.java:88]: since we return we can use a set of if clauses instead as well

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/rename/RenameUtil.java [hunk 2]
```diff
@@ -51,8 +68,26 @@ private RenameUtil() {
...
+
+        Optional<Document> document = context.currentDocument();
+        if (document.isEmpty()) {
+            return Collections.emptyMap();
+        }
+
+        Range cursorPosRange = new Range(context.getCursorPosition(), context.getCursorPosition());
+        NonTerminalNode nodeAtCursor = CommonUtil.findNode(cursorPosRange, document.get().syntaxTree());
+
+        if (onQNameReferenceNode(context, nodeAtCursor)) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/rename/RenameUtil.java:81]: Can't we use the `QNameReferencesUtil` here? It has a util called `onQualifiedNameIdentifier`. We can use modify it to accept a `PositionedOperationContext`

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

**Review by malinthar — DISMISSED** [review]
LGTM

**Review by malinthar — DISMISSED** [review]

**Comment by IMS94** [comment]
Related VSCode plugin change https://github.com/wso2-enterprise/ballerina-plugin-vscode/pull/34

**Comment by mohanvive** [comment]
@IMS94 Can you please resolve the conflicts?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java [hunk 3]
```diff
@@ -475,6 +480,30 @@ void setClientCapabilities(LSClientCapabilities clientCapabilities) {
         });
     }
 
+    @Override
+    public CompletableFuture<Either<Range, PrepareRenameResult>> prepareRename(PrepareRenameParams params) {
+        return CompletableFuture.supplyAsync(() -> {
+            try {
+                ReferencesContext context = ContextBuilder.buildReferencesContext(params.getTextDocument().getUri(),
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java:487]: Shall we create a separate context type as PrepareRenameContext? It's true it will be the same but that will avoid future API hierarchy changes. Same applies for Rename operation as well.

**Review by nadeeshaan — APPROVED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java (hunk 3 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java]: Done!
