### PR TITLE
Fix issues with final fields

### LINKED ISSUE #25963: Cannot update a mutable value assigned to a `final` object field using field access
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Details record {|
    int id;
    string country;
|};

class Employee {
    string department;
    final Details details;

    function init(string department, Details details) {
        self.department = department;
        self.details = details;
    }
}

public function main() {
    Employee emp = new ("IT", {
        id: 112233,
        country: "Sri Lanka"
    });

    emp.details = { // error, ok
        id: 2211,
        country: "Sri Lanka"
    };

    emp.details.id = 2211; // error, but should be allowed!

    Details dt = emp.details;
    dt.id = 2211; // works, but should be able to do `emp.details.id = 2211;`
}
```

**Affected Versions:**
Current master for slp4

### LINKED ISSUE #26021: Object with all `final` fields is marked as immutable even when a type of a field is mutable
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Details record {|
    int id;
    string country;
|};

class Employee {
    final Details details;

    function init(Details details) {
        self.details = details;
    }
}

public function main() {
    Employee emp = new ({
        id: 112233,
        country: "Sri Lanka"
    });

    emp.details.id = 1;
}
```

Compilation fails with
```cmd
$ ballerina run test.bal 
Compiling source
        test.bal
error: .::test.bal:20:5: cannot update 'readonly' value of type 'Employee'
```

**Affected Versions:**
slp4

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/25963

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$title.

Fixes #25963 - Cannot update a mutable value assigned to a `final` object field using field access
Fixes #26021 - Object with all `final` fields is marked as immutable even when a type of a field is mutable

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 1]
```diff
@@ -2228,24 +2228,32 @@ private void validateFieldsAndSetReadOnlyType(List<BLangNode> typeDefNodes, Symb
...
+                for (BField field : fields) {
+                    if (!Symbols.isFlagOn(field.symbol.flags, Flags.READONLY)) {
+                        allImmutableFields = false;
+                        break;
+                    }
+                }
+            } else {
+                for (BField field : fields) {
+                    if (!Symbols.isFlagOn(field.symbol.flags, Flags.FINAL) ||
+                            !Symbols.isFlagOn(structureType.flags, Flags.READONLY)) {
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:2249]: :pick: Extract this out of for loop? `Symbols.isFlagOn(structureType.flags, Flags.READONLY)`

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: We don't actually need this check here now since object type descriptor fields cannot be marked as `final`. Removed in e2badab.

**Review by hasithaa — APPROVED** [review]
