### PR TITLE
Change error cause type in BLangErrorVariableNode to BLangVariable

### LINKED ISSUE #25313: Parser Error Handler Throws Exception for incomplete Source
**Description:**
Consider the following source snippet

```
import ballerina/io;
import ballerina/http;

public const int HELLO = 12;

public function main() {
    e
    io:println(testArr.length());
    
}

type HelloErr error<map<string>>;

```

the above source snippet throws the following exception

```
java.util.NoSuchElementException
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:285)
	at java.util.ArrayDeque.pop(ArrayDeque.java:522)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.endContext(AbstractParserErrorHandler.java:209)
	at io.ballerinalang.compiler.internal.parser.AbstractParser.endContext(AbstractParser.java:126)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:175)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:94)
	at io.ballerinalang.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:55)
	at io.ballerinalang.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:50)
	at org.ballerinalang.langserver.compiler.workspace.WorkspaceDocument.<init>(WorkspaceDocument.java:44)
	at org.ballerinalang.langserver.compiler.workspace.WorkspaceDocument.<init>(WorkspaceDocument.java:50)
	at org.ballerinalang.langserver.compiler.workspace.WorkspaceDocumentManagerImpl.openFile(WorkspaceDocumentManagerImpl.java:89)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didOpen(BallerinaTextDocumentService.java:664)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Affected Versions:**
Swan Lake Preview3 at least

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
Change the type of error cause in `BLangErrorVariableNode` from `BLangSimpleVariable` to `BLangVariable.`

Fixes #25313

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by rdhananjaya — DISMISSED** [review]

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorDestructureNegetiveTest.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+import org.ballerinalang.test.util.BAssertUtil;
+import org.ballerinalang.test.util.BCompileUtil;
+import org.ballerinalang.test.util.CompileResult;
+import org.testng.Assert;
+import org.testng.annotations.Test;
+
+/**
+ * Test cases for Invalid error destructure binding pattern.
+ *
+ * @since 2.0 Swan Lake
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorDestructureNegetiveTest.java:29]:
```suggestion
 * @since Swan Lake
```

File: tests/jballerina-unit-test/src/test/resources/test-src/error/error_destructure_binding_pattern_error_cause.bal [hunk 2]
```diff
@@ -0,0 +1,5 @@
+public function main() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/error/error_destructure_binding_pattern_error_cause.bal:1]: Shall we add the licence header?

**Review by MaryamZi — COMMENTED** [review]
Shall we update the PR title to better reflect the change? Also see https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md#submit-your-contribution

**Review by SupunS — APPROVED** [review]
