### PR TITLE
Fix create function code action generate invalid source

### LINKED ISSUE #21714: Create function code action generate invalid source
**Description:**

```
function func(int a) {
   record {
      string recField = "";
   } testRec = {};
   record {
      int recField = 1;
   } testRec2 = thisIsANewFunction(testRec);
}
```

Consider the above code snippet. testRec and testRec2 are inline defined records and when the code action generates the types with $$anonType$$ causing syntax errors.

**Affected Versions:**
v1.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by rasika**
Fixes #21714

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java [hunk 1]
```diff
@@ -577,6 +577,16 @@ public static String generateReturnValue(ImportsAcceptor importsAcceptor, Packag
             String paramsStr = String.join(", ", list);
             String newObjStr = "new " + pkgPrefix + bStruct.name.getValue() + "(" + paramsStr + ")";
             return template.replace("{%1}", newObjStr);
+        } else if (bType instanceof BRecordType) {
+            BRecordType recordType = (BRecordType) bType;
+            StringJoiner sb = new StringJoiner(", ");
+            if (recordType.tsymbol != null && recordType.tsymbol.name != null &&
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java:583]: Shall we use isInvalidSymbol() util method in CommonUtil.java?
