### PR TITLE
Fix `xml:Text` and `xmlSequence` equality comparison

### LINKED ISSUE #42836: [Bug]: `xml:map` operation when returning consecutive xml:Texts doesn't merge them together
### Description

Consider the following code

```ballerina
import ballerina/io;

public function main() {
    xml x1 = xml `<a>abc</a><b>def</b>`;
    xml r = xml:map(xml:elements(x1), y => y.getChildren());
    io:println(r); // abcdef
    boolean b = xml `abcdef` == r;
    io:println(b); // false
}
```

The equality check here is returned `false`. This is due to xml:map not merging the consecutive `xml:Text`.

### Steps to Reproduce

_No response_

### Affected Version(s)

2201.9.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by ravinperera00**
## Purpose
The Ballerina specification states the following regarding `xml:Text` singleton and xml sequences.
```
# Type for zero or more text characters.
# Built-in subtype of xml.
# Adjacent xml text items are automatically concatenated,
# so an xml sequence belongs to this type if it is a singleton text sequence
# or the empty sequence.
@builtinSubtype
public type Text xml;
```
This means, when an xml sequence contains only children of `xml:Text` type, the sequence belongs to the `xml:Text` type and its value should be equal to an xml:Text value with the concatenation of the children of the sequence. The current implementation does not consider the above two values as equal and the changes included in this PR fixes that.

Fixes #42836

## Approach

- Modify the `xmlSequence` constructor to concatenate adjacent `xml:Text` elements into one member. 
- Change the `equals` methods of both `XmlSequence` and `XmlText` to accept the opposing type as equal if their text values are equal.

## Samples
```
import ballerina/io;

public function main() {
    xml x1 = xml `<a>abc</a><b>def</b>`;
    xml r = xml:map(xml:elements(x1), y => y.getChildren());
    boolean b = (xml `abcdef` == r);
    io:println(b); // true
}
```
The map method will return an xml sequence containing a single `xml:Text` member (generated using the concatenation of the two `xml:Text` elements). This xml sequence will be equal to the `xml:Text` value of "abcdef".

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java [hunk 1]
```diff
@@ -675,6 +675,14 @@ public boolean equals(Object o, Set<ValuePair> visitedValues) {
             return this.getChildrenList().size() == 1 &&
                     isEqual(this.getChildrenList().get(0), o);
         }
+        if (o instanceof XmlText rhsXMLText) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:678]: This logic will break if rhdType is xml never and child list is empty.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java [hunk 2]
```diff
@@ -130,6 +130,14 @@ public boolean equals(Object o, Set<ValuePair> visitedValues) {
         if (o instanceof XmlText rhsXMLText) {
             return this.getTextValue().equals(rhsXMLText.getTextValue());
         }
+        if (o instanceof XmlSequence rhsXMLSequence) {
+            for (BXml child : rhsXMLSequence.children) {
+                if (child.getNodeType() != XmlNodeType.TEXT) {
+                    return false;
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java:136]: Same with here as well

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java (hunk 1 above)
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:678]: I'm not sure if this is the correct fix. Shouldn't this have been an xml:Text value to start with, and not a sequence?

Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:678]: Are you asking about the fix for the issue that is tagged in the PR (#42836)?

Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:678]: I'll fix this.

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:678]: Basically, I'm thinking we shouldn't have XML sequences with only xml:Text members.

Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:678]: Ok I see your point. I'll look into that.

Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java]: The logic was changed due to other changes related to `xmlSequence`. Refer to eee266780c1186097bc83dcc8f5ab3cf30ae5aee and later commits for updates.

Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java]: Made changes to the `xmlSequence` to concatenate adjacent `xml:Text` elements together and to the `equals` method to equate `xml:Text` and `xmlSequence` values that has a singleton `xml:Text` element. Please let me know what you think.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java [hunk 3]
```diff
@@ -127,8 +127,9 @@ public boolean equals(Object obj) {
      */
     @Override
     public boolean equals(Object o, Set<ValuePair> visitedValues) {
-        if (o instanceof XmlText rhsXMLText) {
-            return this.getTextValue().equals(rhsXMLText.getTextValue());
+        if ((o instanceof XmlText) || ((o instanceof XmlSequence)
+                && ((XmlSequence) o).isSingleton() && ((XmlSequence) o).getItem(0).getNodeType() == XmlNodeType.TEXT)) {
```
Comment (SasinduDilshara) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java:131]:
```suggestion
        if ((o instanceof XmlText) || ((o instanceof XmlSequence)
                && ((XmlSequence) o).isSingleton() && ((XmlSequence) o).getItem(0).getNodeType() == XmlNodeType.TEXT)) {
```

I think this should be define as a separate function and name it properly, otherwise the logic is not clear.
ex:-

Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java:131]: Got it. I'll fix that.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java [hunk 4]
```diff
@@ -628,6 +633,28 @@ public Object next() {
         };
     }
 
+    private void createXmlSequenceByCheckingAdjacentTextItems(List<BXml> values) {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:636]:
```suggestion
    private void setSequenceMembersConcatenatingAdjacentTextItems(List<BXml> values) {
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java [hunk 5]
```diff
@@ -628,6 +633,28 @@ public Object next() {
...
+        this.children = new ArrayList<>();
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:637]: I would use a local variable and set it to `this.children` at the end.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java [hunk 6]
```diff
@@ -628,6 +633,28 @@ public Object next() {
...
+        boolean prev = false;
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:638]: Can we use a name that is better reflection of what this is tracking?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java [hunk 7]
```diff
@@ -671,9 +698,8 @@ public boolean equals(Object o, Set<ValuePair> visitedValues) {
         if (o instanceof XmlSequence rhsXMLSequence) {
             return isXMLSequenceChildrenEqual(this.getChildrenList(), rhsXMLSequence.getChildrenList());
         }
-        if (o instanceof XmlItem) {
-            return this.getChildrenList().size() == 1 &&
-                    isEqual(this.getChildrenList().get(0), o);
+        if (o instanceof XmlItem || (o instanceof XmlText && this.isSingleton())) {
+            return isEqual(this.getChildrenList().get(0), o);
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:702]: This change isn't correct? Produces incorrect results now for

```ballerina
xml x1 = xml:concat(xml `<foo/>`, xml `<bar/>`);
xml:Element x2 = xml `<foo/>`;
boolean equal = x1 == x2;
```

File: langlib/langlib-test/src/test/resources/test-src/xmllib_constrained_test.bal [hunk 8]
```diff
@@ -67,8 +67,16 @@ public function xmlConstraintRuntimeCast() {
 public function xmlCastSingleElementAsConstrainedSequence() {
     string elemText = "<hello>xml element 1</hello>";
     xml<'xml:Element> elementSequence = <xml<'xml:Element>> checkpanic 'xml:fromString(elemText);
+    xml x1 = xml `<a>abc</a><b>def</b>`;
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/resources/test-src/xmllib_constrained_test.bal:70]: Is this the correct test for these?

File: langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal [hunk 9]
```diff
@@ -110,10 +110,13 @@ function testXmlIsComment() returns [boolean, boolean] {
         emptyConcatCall() is 'xml:Comment];
 }
 
-function testXmlIsText() returns [boolean, boolean] {
+function testXmlIsText() returns [boolean, boolean, boolean, boolean, boolean] {
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal:113]: I would add a new test (and do the assertions in Ballerina itself too).

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java (hunk 4 above)
Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java]: Fixed with cfc81cfad46986467573c70a6c7a316ea085d2ae

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java (hunk 6 above)
Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java]: Fixed with cfc81cfad46986467573c70a6c7a316ea085d2ae

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java (hunk 7 above)
Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java]: Fixed with cfc81cfad46986467573c70a6c7a316ea085d2ae

File: langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal (hunk 9 above)
Comment (ravinperera00) [reply langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal]: Fixed with cfc81cfad46986467573c70a6c7a316ea085d2ae

File: langlib/langlib-test/src/test/resources/test-src/xmllib_constrained_test.bal (hunk 8 above)
Comment (ravinperera00) [reply langlib/langlib-test/src/test/resources/test-src/xmllib_constrained_test.bal]: Fixed with 1751575fae13160249464038cd0491e8e143ce14

**Review by SasinduDilshara — APPROVED** [review]

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java [hunk 10]
```diff
@@ -671,9 +699,8 @@ public boolean equals(Object o, Set<ValuePair> visitedValues) {
         if (o instanceof XmlSequence rhsXMLSequence) {
             return isXMLSequenceChildrenEqual(this.getChildrenList(), rhsXMLSequence.getChildrenList());
         }
-        if (o instanceof XmlItem) {
-            return this.getChildrenList().size() == 1 &&
-                    isEqual(this.getChildrenList().get(0), o);
+        if (this.isSingleton() && (o instanceof XmlItem || o instanceof XmlText)) {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:702]: Still won't work for things like

```ballerina
xml x1 = xml:concat(xml `<!--foo-->`, xml ``);
xml:Comment x2 = xml `<!--foo-->`;
boolean equal = x1 == x2;
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java [hunk 11]
```diff
@@ -143,4 +143,10 @@ public int hashCode() {
     public Type getType() {
         return this.type;
     }
+
+    private boolean isXmlSequenceWithSingletonTextValue(Object o) {
+        return ((o instanceof XmlSequence)
+                && ((XmlSequence) o).isSingleton()
+                && ((XmlSequence) o).getItem(0).getNodeType() == XmlNodeType.TEXT);
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java:150]: Break into separate checks extracting `(XmlSequence) o` out to a variable.

File: langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal [hunk 12]
```diff
@@ -4783,6 +4791,14 @@ function testXMLWithAngleBrackets() {
     panic error("AssertionError : expected: " + expected + " found: " + exy.toString());
 }
 
+function testXMLSequenceWithOneTextElement() {
+    xml text1 = xml `<a>abc</a><b>def</b>`;
+    xml text2 = xml:map(xml:elements(text1), y => y.getChildren());
+    var item = text2.cloneWithType(xml:Text);
+    assertTrue(item is xml:Text);
+    assertTrue(item == xml `abcdef`);
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal:4799]: Can use `assertEquality`?

File: tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal [hunk 13]
```diff
@@ -90,6 +90,14 @@ function testIntToByteExplicitCast(int b) returns byte|error {
     return a;
 }
 
+function testXMLSequenceWithOneTextMember() {
+    xml text1 = xml `<a>abc</a><b>def</b>`;
+    xml text2 = xml:map(xml:elements(text1), y => y.getChildren());
+    xml:Text t1 =  <xml:Text>text2;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal:96]:
```suggestion
    xml:Text t1 = <xml:Text>text2;
```

File: tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal [hunk 14]
```diff
@@ -90,6 +90,14 @@ function testIntToByteExplicitCast(int b) returns byte|error {
...
+    xml:Text text3 = <xml:Text>xml`abcdef`;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal:97]:
```suggestion
    xml:Text text3 = xml `abcdef`;
```

Why do we need the cast?

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal:97]: Variable names seem to be a mix too.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java [hunk 15]
```diff
@@ -628,6 +633,29 @@ public Object next() {
...
     }
 
+    private void setSequenceMembersConcatenatingAdjacentTextItems(List<BXml> values) {
+        ArrayList<BXml> members = new ArrayList<>();
+        boolean isPreviousValueText = false;
+        StringBuilder text = new StringBuilder();
+        for (BXml value : values) {
+            if (value.getNodeType() == XmlNodeType.TEXT) {
+                isPreviousValueText = true;
+                text.append(value.getTextValue());
```
[the remark this answers is not in the document]
Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java:643]: Fixed with dd8e19f2a0e5255dbe863e931bffe66bf0190024

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java (hunk 10 above)
Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlSequence.java]: Fixed with dd8e19f2a0e5255dbe863e931bffe66bf0190024

File: langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal (hunk 12 above)
Comment (ravinperera00) [reply langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal]: Fixed with dd8e19f2a0e5255dbe863e931bffe66bf0190024

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java (hunk 11 above)
Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlText.java]: Fixed with dd8e19f2a0e5255dbe863e931bffe66bf0190024

File: tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal (hunk 13 above)
Comment (ravinperera00) [reply tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal]: Fixed with dd8e19f2a0e5255dbe863e931bffe66bf0190024

File: tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal (hunk 14 above)
Comment (ravinperera00) [reply tests/jballerina-unit-test/src/test/resources/test-src/jvm/types.bal]: Fixed with dd8e19f2a0e5255dbe863e931bffe66bf0190024

**Comment by gimantha** [comment]
@ravinperera00 The build is failing
image

**Review by warunalakshitha — APPROVED** [review]
LGTM
