### PR TITLE
Set offline resolution on unnecessary places

### LINKED ISSUE #40024: [Bug]: Experiencing slowness compiling nBallerina with SL Update 4
### Description

**2201.4.0**
$subject. Build time details are as follows.

- `bal build --dump-build-time` after a `bal clean`:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680065492243
        offline : false
        compile : false
        projectLoadDuration : 674
        packageResolutionDuration : 10824
        packageCompilationDuration : 126542
        codeGenDuration : 4080
        emitArtifactDuration : 566
        testingExecutionDuration : 0
        totalDuration : 142717
```     
 - 2nd build:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680066214492
        offline : false
        compile : false
        projectLoadDuration : 771
        packageResolutionDuration : 5496
        packageCompilationDuration : 60900
        codeGenDuration : 4861
        emitArtifactDuration : 568
        testingExecutionDuration : 0
        totalDuration : 72633        
```        
- `bal build --offline --dump-build-time` after a `bal clean`:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680066323368
        offline : true
        compile : false
        projectLoadDuration : 783
        packageResolutionDuration : 1066
        packageCompilationDuration : 5740
        codeGenDuration : 4630
        emitArtifactDuration : 532
        testingExecutionDuration : 0
        totalDuration : 12783
```
- 2nd build:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680066367428
        offline : true
        compile : false
        projectLoadDuration : 763
        packageResolutionDuration : 955
        packageCompilationDuration : 5539
        codeGenDuration : 6000
        emitArtifactDuration : 991
        testingExecutionDuration : 0
        totalDuration : 14289
```     
**2201.3.0**

`bal build --dump-build-time` after a `bal clean`:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680066549834
        offline : false
        compile : false
        projectLoadDuration : 663
        packageResolutionDuration : 9604
        packageCompilationDuration : 3114
        codeGenDuration : 5437
        emitArtifactDuration : 1011
        testingExecutionDuration : 0
        totalDuration : 19855
```        
- 2nd build:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680066649461
        offline : false
        compile : false
        projectLoadDuration : 763
        packageResolutionDuration : 5726
        packageCompilationDuration : 3340
        codeGenDuration : 5156
        emitArtifactDuration : 753
        testingExecutionDuration : 0
        totalDuration : 15778        
```
- `bal build --offline --dump-build-time` after a `bal clean`:
```        
Dumping build time information
        target/build-time.json
        timestamp : 1680066711687
        offline : true
        compile : false
        projectLoadDuration : 688
        packageResolutionDuration : 1079
        packageCompilationDuration : 3482
        codeGenDuration : 6225
        emitArtifactDuration : 689
        testingExecutionDuration : 0
        totalDuration : 12187
```      
 - 2nd build:
```
 Dumping build time information
        target/build-time.json
        timestamp : 1680066748891
        offline : true
        compile : false
        projectLoadDuration : 695
        packageResolutionDuration : 935
        packageCompilationDuration : 3358
        codeGenDuration : 7358
        emitArtifactDuration : 1113
        testingExecutionDuration : 0
        totalDuration : 13497       
```         

### Steps to Reproduce

Execute `bal build` at nBallerina repo compiler module. https://github.com/ballerina-platform/nballerina/tree/main/compiler

### Affected Version(s)

2201.4.0

### OS, DB, other environment details and versions

Ubuntu 20.04

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
Fixes #40024

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java [hunk 1]
```diff
@@ -306,4 +307,14 @@ PackageContext duplicate(Project project) {
                 this.cloudTomlContext, this.compilerPluginTomlContext, this.packageMdContext,
                 this.compilationOptions, duplicatedModuleContextMap, this.pkgDescDependencyGraph);
     }
+
+    public Set<ModuleLoadRequest> getAllImports() {
```
Comment (azinneera) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java:311]: Lets keep this package private. To make it accessible in the CLI module, expose it as a util via the ProjectUtils

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/Package.java [hunk 2]
```diff
@@ -170,6 +171,10 @@ public CompilationOptions compilationOptions() {
         return packageContext.compilationOptions();
     }
 
+    public Set<ModuleLoadRequest> getAllImports() {
```
Comment (azinneera) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/Package.java:174]: Lets keep this package private. To make it accessible in the CLI module, expose it as a util via the ProjectUtils

**Review by azinneera — APPROVED** [review]
