### PR TITLE
Fix data mapper code actiion for multi module projects

### LINKED ISSUE #27876: Datamapper Code action is not working for multi module projects
**Description:**
Data mapper code action is not working for multimodule projects. Code action breaks.

Screenshot 2021-01-15 at 16 13 02

Screenshot 2021-01-15 at 16 21 31

**Steps to reproduce:**
Create a multi-module project and map two record types.
Sample code 

```
type Grades record {|
    int maths;
    int physics;
    int chemistry;
    int...;
|};

type Student record {
    string name;
    int age;
    Grades grades;
    string city;
};

public function main() {
    Student Kamal = {
        name : "Kamal",
        age : 10,
        grades : {
            maths : 90,
            physics : 99,
            chemistry : 95
        },
        city : "Colombo"
    };

    Grades Kamal_grades = Kamal;
}
```

### PR DESCRIPTION
**Pull request by isuruRuhu**
## Purpose
Fixes #27876

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java [hunk 1]
```diff
@@ -96,135 +97,149 @@
...
      * @return return the symbol
      */
-    public static Symbol findSymbol(String symbolName, List<Symbol> fileContentSymbols) {
-        Iterator<Symbol> iterator = fileContentSymbols.iterator();
-        while (iterator.hasNext()) {
-            Symbol symbol = iterator.next();
-            if (symbol.name().equals(symbolName)) {
+    public static Symbol findSymbol(List<TypeSymbol> fileContentSymbols) {
+        for (Symbol symbol : fileContentSymbols) {
+            if (!symbol.name().equals("ERROR")) {
```
Comment (rasika) [inline misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java:242]: This should be otherway, to avoid possible NPEs. `"ERROR".equals(symbol.name())`

File: misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java [hunk 2]
```diff
@@ -96,135 +97,149 @@
...
-                                    functionParameters);
-                    fEdits.add(new TextEdit(newTextRange, generatedFunctionName));
+                default:
+                    throw new IllegalStateException("Unexpected value: " + symbolAtCursorType);
+            }
+
+            // Insert function declaration at the bottom of the file
+            String functionName = String.format("map%sTo%s", foundTypeRight, foundTypeLeft);
+            boolean found = fileContentSymbols.stream().anyMatch(p -> p.name().contains(functionName));
+            if (!found) {
```
Comment (rasika) [inline misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java:192]: Can we reverse this logic to return `if(found)` logic first

**Review by rasika — CHANGES_REQUESTED** [review]

File: misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java [hunk 3]
```diff
@@ -96,135 +97,149 @@
...
-                    generatedFunctionName =
-                            String.format("map%sTo%s(%s)", foundTypeRight, foundTypeLeft, functionCall);
-                    fEdits.add(new TextEdit(newTextRange, generatedFunctionName));
+                case "FUNCTION":
+                case "MODULE":
+                    boolean foundErrorLeft = false;
+                    boolean foundErrorRight = false;
+
+                    // If the function is returning a record | error
+                    if (foundTypeLeft.equals("")) {
```
[the remark this answers is not in the document]
Comment (isuruRuhu) [reply misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java:151]: Modified the code according to the comment

File: misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java [hunk 4]
```diff
@@ -96,135 +97,149 @@
...
+                        List<TypeSymbol> leftTypeSymbols = ((UnionTypeSymbol) lftTypeSymbol).memberTypeDescriptors();
+                        lftTypeSymbol = findSymbol(leftTypeSymbols);
+                        foundTypeLeft = lftTypeSymbol.name();
+                        foundErrorLeft = true;
+                    }
+                    // If the check or checkpanic is used
+                    if (foundTypeRight.equals("")) {
```
[the remark this answers is not in the document]
Comment (isuruRuhu) [reply misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java:158]: Modified the code according to the comment

File: misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java [hunk 5]
```diff
@@ -234,50 +249,46 @@ public static Symbol findSymbol(String symbolName, List<Symbol> fileContentSymbo
...
         // Schema 2
-        Map<String, RecordFieldSymbol> leftSchemaFields;
-        if (positionDetails.matchedSymbol() == null) {
-            Symbol leftSymbol = findSymbol(foundTypeLeft, fileContentSymbols);
-            leftSchemaFields = SymbolUtil.getTypeDescForRecordSymbol(leftSymbol).fieldDescriptors();
-        } else {
-            leftSchemaFields = SymbolUtil.getTypeDescForRecordSymbol(positionDetails.matchedSymbol()).
-                    fieldDescriptors();
+        TypeSymbol lftSymbol = ((TypeReferenceTypeSymbol) lftTypeSymbol).typeDescriptor();
+        if (lftSymbol.typeKind().name().equals("RECORD")) {
```
[the remark this answers is not in the document]
Comment (isuruRuhu) [reply misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java:281]: Modified the code according to the comment

File: misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java (hunk 1 above)
Comment (isuruRuhu) [reply misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java:242]: Modified the code according to the comment

File: misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java (hunk 2 above)
Comment (isuruRuhu) [reply misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java:192]: I made the change according to the comment. But IntelliJ Suggest me to extract the common parts.

Comment (rasika) [reply misc/ballerinalang-data-mapper/src/main/java/org/ballerinalang/datamapper/AIDataMapperCodeActionUtil.java]: Issue here is if-block is too lengthy and we tend to lost the the context when reading the code. anyway that's a minor issue can improve in a separate PR

**Review by rasika — APPROVED** [review]
LGTM
