### PR TITLE
Check array capacity before `unshift()`

### LINKED ISSUE #34394: Bug in array.unshift
**Description:**

**Steps to reproduce:**

1. Create this script
```
public function main() {
    int[] list = [];
    foreach int i in 0 ..< 200 {
        list.unshift(i);
    }
}
```

2. Run it
3. Scripts crashes with
```
[2021-12-17 14:09:45,293] SEVERE {b7a.log.crash} - arraycopy: last destination index 101 out of bounds for long[100]
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 101 out of bounds for long[100]
        at java.base/java.lang.System.arraycopy(Native Method)
        at io.ballerina.runtime.internal.values.ArrayValueImpl.unshiftArray(ArrayValueImpl.java:1218)
        at io.ballerina.runtime.internal.values.ArrayValueImpl.unshift(ArrayValueImpl.java:1131)
        at io.ballerina.runtime.internal.values.ArrayValueImpl.unshift(ArrayValueImpl.java:619)
        at org.ballerinalang.langlib.array.Unshift.unshift(Unshift.java:34)
        at ballerina.lang$0046array.0.array.unshift(array.bal:272)
        at app.main(app.bal:5)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:323)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at io.ballerina.runtime.internal.scheduling.Scheduler.start(Scheduler.java:278)
        at $_init.main(.)
```

Sound like array has a fixed size and isn't doubled as soon as it hits the limit.

**Affected Versions:**
At least Swan Lake beta 6

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
Fixing the index out of bounds bug in array `unshift()` function. 

Fixes #34394 

## Approach
Add a check for array capacity before shifting the internal array.

## Samples
```ballerina
public function main() {
    int[] list = [];
    foreach int i in 0 ..< 200 {
        list.unshift(i);
    }
}
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java [hunk 1]
```diff
@@ -656,34 +656,38 @@ public String stringValue(BLink parent) {
...
-                        }
-                    }
-                }
+                getRefValuesString(parent, sj);
                 break;
         }
         return "[" + sj + "]";
     }
 
+    private void getRefValuesString(BLink parent, StringJoiner sj) {
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java:665]: This is a refactoring done to reduce the complexity of the method `stringValue(BLink parent)`.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java [hunk 2]
```diff
@@ -1206,15 +1210,14 @@ private void shiftArray(int index, Object arr) {
...
-        Object arr = getArrayFromType(elementType.getTag());
-
         if (index > lastIndex) {
             throw BLangExceptionHelper.getRuntimeException(
                     getModulePrefixedReason(ARRAY_LANG_LIB, INDEX_OUT_OF_RANGE_ERROR_IDENTIFIER),
                     RuntimeErrors.INDEX_NUMBER_TOO_LARGE, index);
         }
-
         int i = (int) index;
+        ensureCapacity(this.size + unshiftByN, this.size);
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java:1219]: Does "if (index > lastIndex)" condition  not handle capacity?

Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java:1219]: no. 
As per the current implementation, we first shift the array by the no. of values and then add the new values to the array. The error happens when we shift the array due to the default array size (=100) we have for open arrays. 
The `if (index > lastIndex)` check only validates the size of the BArray, not the size of internal array (Eg. : `intValues`, `refValues` etc.).

**Review by warunalakshitha — APPROVED** [review]
LGTM
