### PR TITLE
Fix bad sad error when a function from a transitive dependency is mocked

### LINKED ISSUE #42034: [Bug]: Bad sad error when a function from a transitive dependency is mocked.
### Description

Say a multi-packaged module has 3 modules `x`, `y`, `z` with dependencies x<-y<-z. i.e.
- `y` imports `x`
- `z` imports `y` (and doesn't import `x`)

When a function in `x` is mocked within `z`, it produces the following error.
``` 
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2024-01-24 09:31:33,735] SEVERE {b7a.log.crash} - Mock Function and Function to Mock cannot be null 
java.lang.IllegalStateException: Mock Function and Function to Mock cannot be null
        at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateMockFunction(MockDesugar.java:194)
        at org.wso2.ballerinalang.compiler.desugar.MockDesugar.generateMockFunctions(MockDesugar.java:147)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:773)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8952)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:473)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:454)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:174)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:143)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:121)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:176)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:120)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:354)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
 
ERROR [modules/z/choreo_issue.z:(1:1,1:1)] Compilation failed due to: Mock Function and Function to Mock cannot be null
```

### Steps to Reproduce

add 3 modules x,y,z.

- modules/x/x.bal
``` ballerina
public function hello(string name) returns string {
    return "Hello, " + name;
}
```

- modules/y/y.bal
``` ballerina
import choreo_issue.x;

public function hello(string name) returns string {
    return x:hello(name);
}
```

- modules/z/z.bal
``` ballerina
import choreo_issue.y;

public function hello(string name) returns string {
    return y:hello(name);
}
```

- modules/z/tests/z_tests.bal
``` ballerina
import ballerina/test;

@test:Mock {
    moduleName: "choreo_issue.x",
    functionName: "hello"
}
function mockHello(string name) returns string {
    return "Hello, Ballerina";
}

@test:Config
function testZ() {
    test:assertEquals(hello("Java"), "Hello, Ballerina");
}
```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/wso2-enterprise/internal-support-ballerina/issues/567

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
Fixes #42034

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangTestablePackage.java [hunk 1]
```diff
@@ -29,6 +29,8 @@ public class BLangTestablePackage extends BLangPackage {
     // Semantic Data
     //Map to maintain all the mock functions
     private Map<String, String> mockFunctionNamesMap = new HashMap<>();
+
+    private final Map<String, String> mockFunctionTypeMap = new HashMap<>();
```
Comment (Dilhasha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangTestablePackage.java:33]: Shall we use a Map<String, boolean> instead? it's either Legacy or latest right?

Comment (Thevakumar-Luheerathan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangTestablePackage.java]: Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/42091/commits/ef0fc467445c85fdbe56a9810b1572f5ac988205

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/MockDesugar.java [hunk 2]
```diff
@@ -115,35 +115,13 @@ public void generateMockFunctions(BLangPackage pkgNode) {
...
-            }
-            if (importsList.contains(importPkg.symbol.toString())) {
-                continue;
-            }
-            if (!importPkg.symbol.toString().contains(testPackageSymbol)) {
-                importsList.add(importPkg.symbol.toString());
-            }
-        }
+        // Get the mock function type map from the pkgNode
+        Map<String, Boolean> isLegacyMockingMap = pkgNode.getTestablePkg().getIsLegacyMockingMap();
```
Comment (gayaldassanayake) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/MockDesugar.java:119]: I feel like the name `isLegacyMockingMap` feels as if it is a boolean. Instead if we make an enum, and make the variable `mockTypes` as below, it would be cleaner.
``` java
enum MockingType {
   LEGACY, NEW
}

private Map<String, MockType> mockTypes;
```

Comment (Thevakumar-Luheerathan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/MockDesugar.java:119]: we can use `enum`. But, the map above is accessed by multiple classes. We need to define this `enum` as `public`  and need to move to a separate file. As the use-case of this map is limited. I feel, that is quite unnecessary.

**Review by gayaldassanayake — APPROVED** [review]

**Review by gayaldassanayake — APPROVED** [review]
