### PR TITLE
Fix issue when exponent indicator of floating-point literal is not followed by a digit

### LINKED ISSUE #32839: Bad Sad for certain invalid decimal floating point numbers
**Description:**
All of the invalid decimal floating point numbers in the code snippet below result in a compiler crash.    

**Steps to reproduce:**
```
public function main() {
    float|decimal a = 25.E;1742;
    a = 25.E=1742;
    a = 25.E:1742;
    a = 25.E,1742;
// NOTE: In above samples there might be other symbols that can cause these to fail

    a = .99E-;
    a = .99E+;
    a = .99E;
}
```

<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
[2022-03-09 15:31:51,138] SEVERE {b7a.log.crash} - For input string: "25.E" 
java.lang.NumberFormatException: For input string: "25.E"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.validateFloatLiteral(Types.java:3589)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getTypeOfDecimalFloatingPointLiteral(TypeChecker.java:651)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.setLiteralValueAndGetType(TypeChecker.java:704)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:425)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangLiteral.accept(BLangLiteral.java:55)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:380)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:354)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1052)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4020)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1907)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:4024)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:524)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:500)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4020)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:349)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:309)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:436)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:103)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
```
</details>

### LINKED ISSUE #32840: Bad Sad for certain invalid hex floating point literals
**Description:**
All of the invalid hex floating point literals in the code snippet below result in a compiler crash.  

**Steps to reproduce:**

```
public function main() {
    float|decimal a = 0x 3eA3p34;
    a = 0Xp34;
    a = 0x3eA3p-;
    a = 0x3eA3p+;
    a = 0x3eA3p;
    a = 0x 3eA3 .4Eb2 p45;
    a = 0x 3eA3.4Eb2p+45;
    
    a = 0X3eAp;
    a = 0x3eA3p=34;
    a = 0x3eA3p:34;
    a = 0x3eA3p,34;
    a = 0x=4Eb2P-45;
    a = 0x:4Eb2P-45;
    a = 0x,4Eb2P-45;
// NOTE: In above samples there might be other symbols that can cause these to fail
}
```

**Related Issues (optional):**
#32750

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$title

Fixes #32839
Fixes #32840

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 1]
```diff
@@ -5346,11 +5346,18 @@ private BLangLiteral createSimpleLiteral(Node literal, SyntaxKind sign, boolean
                 //TODO: Check effect of mapping negative(-) numbers as unary-expr
                 kind = NodeKind.DECIMAL_FLOATING_POINT_LITERAL;
                 typeTag = NumericLiteralSupport.isDecimalDiscriminated(textValue) ? TypeTags.DECIMAL : TypeTags.FLOAT;
+                String val = textValue;
+                
+                // Remove exponent indicator if it is not followed by a digit
+                if (val.matches(".*[eE][+-]?[fd]?")) {
+                    val = val.replaceAll("[eE][+-]?", "");
+                }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5354]: Consider the following two examples
Example 1
```ballerina
public function main() {
    10f a = 10Ef ; 
}
```
Gives error as
```
ERROR [test3.bal:(23:13,23:17)] missing digit after exponent indicator
```
Example 2
```ballerina
public function main() {
    10f a = 100Ef ; 
}
```
Gives error as
```
ERROR [test3.bal:(23:13,23:18)] incompatible types: expected '10ff', found 'float'
ERROR [test3.bal:(23:13,23:18)] missing digit after exponent indicator
```
In the first example, identify the `10Ef ` as `10f`(due to that didn't we get incompatible types error). It's not correct. right?
In the second example,  identify the `100Ef ` as `100f`(due to that we get an incompatible types error).
IMO we cannot set the type for incorrect values. (In the first example we set the type of `10Ef ` as `10f `)

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 2]
```diff
@@ -5928,6 +5935,16 @@ private Object parseLong(Node literal, String originalNodeValue,
...
     private String getHexNodeValue(String value) {
+        // Remove exponent indicator if it is not followed by a digit
+        if (value.matches(".*[pP][+-]?")) {
+            value = value.replaceAll("[pP][+-]?", "");
+        }
+        
+        // Add 0 if there is no hex digit precedes hex indicator
+        if (value.matches("0[xX][pP].*")) {
+            value = value.replaceAll("[pP]", "0p");
+        }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5946]: Here also the same thing,
Example 1
```ballerina
public function main() {
    0f a = 0Xp34; // type set as 0f
}
```
Gives error as
```
ERROR [test3.bal:(22:12,22:17)] missing hex number after hex indicator
```
Example 2
```ballerina
public function main() {
    10f a = 0Xp34; // identify type as float
}
```
Gives error as
```
ERROR [test3.bal:(22:13,22:18)] incompatible types: expected '10ff', found 'float'
ERROR [test3.bal:(22:13,22:18)] missing hex number after hex indicator
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java (hunk 1 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5354]: We can move this logic to Types.validateFloatLiteral() and return `false` there for invalid literals which will fix the above issue. Should we go for it?

Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5354]: I feel giving the syntax error is enough in these scenarios. One has to fix the syntax error first.

We can simply do the following at L5370, to avoid any crashes in the compiler phases. WDYT?

```java
            if (literal.hasDiagnostics()) {
                value = "0";
                originalValue = "0";
            }
```

Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5354]: Another option would be to use a try-catch for `Double.parseDouble()` and if an exception is thrown we simply return false. But, the problem there is we can't guarantee the syntax error is there. Ideally, there should be a syntax error if `Double.parseDouble()` is failing though.

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5354]: setting value to `"0"` will still give the incompatible type error right?

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5354]: We don't need try-catch right? we have `Types.validateFloatLiteral()` method so we can include those checks to it and return false there

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5354]:
```bal
public function main() {
   "A" a = "\u{0041";
}
```
The above sample also gives `incompatible types: expected 'A', found 'string'` error on an invalid string literal

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java]: Fixed in [932a51e](https://github.com/ballerina-platform/ballerina-lang/pull/35646/commits/932a51ecb0f19f3946d3394d71c2ed14ad5dcb73)

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java]: Created a separate issue for string case #35794

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java (hunk 2 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java]: Fixed in [932a51e](https://github.com/ballerina-platform/ballerina-lang/pull/35646/commits/932a51ecb0f19f3946d3394d71c2ed14ad5dcb73)

**Comment by chiranSachintha** [comment]
The following kind of scenario still crashes.
```ballerina
public function main() {
    10d a = 0xp ; 
    10d a = 0xpd ;
    10d a = 0xpf;
}

**Review by chiranSachintha — APPROVED** [review]
