### PR TITLE
Fix value equality checks for self referencing values

### LINKED ISSUE #11457: Value equality checks fail for self-referencing structural values
### Description:

Value equality checks (`==` and `!=`) fail for `anydata` structural values that refer themselves. This needs to be handled by maintaining already checked/checking-in-progress member values.

**Sample Code**
```ballerina
import ballerina/io;

public function main() {
    map<anydata> m = {"0": 0};
    m["1"] = m;

    map<anydata> n = {"0": 0};
    n["1"] = n;

    io:println(m == n);
}
```
**Error**
```cmd
$ ballerina run value_eq.bal
error: {}
        at main(value_eq.bal:10)
```

### Affected Versions:
0.985.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
This PR fixes value equality checks for structural values that refer themselves/have a cyclic reference.
Fixes #11457 

ToDo: Add tests for records once self referencing record type-checking is fixed.

### CODE REVIEW

File: bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java [hunk 1]
```diff
@@ -4740,4 +4756,28 @@ public boolean equals(Object obj) {
...
+        }
+
+        @Override
+        public boolean equals(Object otherPair) {
+            if (!(otherPair instanceof ValuePair)) {
+                return false;
+            }
+
+            List otherValuePairValueList = ((ValuePair) otherPair).valueList;
+            return valueList.stream().allMatch(otherValuePairValueList::contains);
```
Comment (Shan1024) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java]: Cant we simplify this with `otherValuePairValueList.containsAll(valueList)`?

File: bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java [hunk 2]
```diff
@@ -4740,4 +4756,27 @@ public boolean equals(Object obj) {
...
+            valueList.add(valueTwo);
+        }
+
+        @Override
+        public boolean equals(Object otherPair) {
+            if (!(otherPair instanceof ValuePair)) {
+                return false;
+            }
+
+            return ((ValuePair) otherPair).valueList.containsAll(valueList);
```
Comment (SupunS) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java]: this will return true for the following case:
otherPair = [x, y]
valueList = [x', x'']

where x' and x'' are two equal values to x.

Comment (MaryamZi) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java]: Fixed with 91dccd1.
