### PR TITLE
[stdlib] [task] - Implement stop function and remove redundant compiler plugin

### LINKED ISSUE #14474: Hanging test in Jenkins
**Description:**
```
2019-03-15 04:25:48 INFO  HTTPServicesRegistry:125 - Service deployed : hello with context /hello
    in-request-native-function.bal
2019-03-15 04:25:49 INFO  HTTPServicesRegistry:125 - Service deployed : hello with context /hello
    get_request_as_string_and_json.bal
2019-03-15 04:25:49 INFO  HTTPServicesRegistry:125 - Service deployed : MyService with context /foo
    uri-template-default.bal
2019-03-15 04:25:49 INFO  HTTPServicesRegistry:125 - Service deployed : $anonService$5 with context /
2019-03-15 04:25:49 INFO  HTTPServicesRegistry:125 - Service deployed : $anonService$3 with context /
2019-03-15 04:25:49 INFO  HTTPServicesRegistry:125 - Service deployed : serviceWithNoAnnotation with context /serviceWithNoAnnotation
2019-03-15 04:25:49 INFO  HTTPServicesRegistry:125 - Service deployed : serviceEmptyName with context /
2019-03-15 04:25:49 INFO  HTTPServicesRegistry:125 - Service deployed : serviceName with context /serviceName
    circuit-breaker-test.bal
    circuit-breaker-test.bal
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  HTTPServicesRegistry:125 - Service deployed : circuitBreakerService with context /cb
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  HTTPServicesRegistry:125 - Service deployed : circuitBreakerService with context /cb
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  ballerina/http:42 - CircuitBreaker failure threshold exceeded. Circuit tripped from CLOSE to OPEN state.
2019-03-15 04:25:51 INFO  ballerina/http:42 - CircuitBreaker failure threshold exceeded. Circuit tripped from CLOSE to OPEN state.
2019-03-15 04:25:51 INFO  ballerina/http:42 - CircuitBreaker failure threshold exceeded. Circuit tripped from CLOSE to OPEN state.
2019-03-15 04:25:51 INFO  ballerina/http:42 - CircuitBreaker failure threshold exceeded. Circuit tripped from CLOSE to OPEN state.
2019-03-15 04:25:51 INFO  ballerina/http:42 - CircuitBreaker failure threshold exceeded. Circuit tripped from CLOSE to OPEN state.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  HTTPServicesRegistry:125 - Service deployed : circuitBreakerService with context /cb
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  HTTPServicesRegistry:125 - Service deployed : circuitBreakerService with context /cb
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 ERROR BVMScheduler:75 - 
java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2333)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:581)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.stdlib.task.utils.TaskExecutor.execute(TaskExecutor.java:41)
	at org.ballerinalang.stdlib.task.utils.TaskJob.execute(TaskJob.java:44)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2019-03-15 04:25:51 ERROR JobRunShell:211 - Job DEFAULT.cd27449a-386a-4911-ae55-62db5e486534 threw an unhandled Exception: 
java.lang.RuntimeException: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.stdlib.task.utils.TaskExecutor.execute(TaskExecutor.java:41)
	at org.ballerinalang.stdlib.task.utils.TaskJob.execute(TaskJob.java:44)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2333)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:581)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	... 6 more
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-03-15 04:25:51 ERROR ErrorLogger:2401 - Job (DEFAULT.cd27449a-386a-4911-ae55-62db5e486534 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.RuntimeException: java.lang.NullPointerException]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeFunction(BVMExecutor.java:112)
	at org.ballerinalang.stdlib.task.utils.TaskExecutor.execute(TaskExecutor.java:41)
	at org.ballerinalang.stdlib.task.utils.TaskJob.execute(TaskJob.java:44)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BVM.execTypeCastOpcodes(BVM.java:2333)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:581)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	... 6 more
2019-03-15 04:25:51 INFO  QuartzScheduler:547 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
```

Complete log - [consoleText.txt](https://github.com/ballerina-platform/ballerina-lang/files/2976321/consoleText.txt)

### LINKED ISSUE #14642: Intermittent failure - tests/task_scheduler_timer_test
**Description:**
```
Generating executable
    ./target/strings.balx
Compiling source
    ballerina-examples/task-scheduler-appointment:0.0.1

Running tests
    ballerina-examples/task-scheduler-appointment:0.0.1
	1 passing
	0 failing
	0 skipped

Generating executable
    ./target/task-scheduler-appointment.balx
Compiling source
    ballerina-examples/task-scheduler-timer:0.0.1

Running tests
    ballerina-examples/task-scheduler-timer:0.0.1
	[fail] testFunc:
	    error: Assertion Failed!: expected 'Hi Sam you are 10 years old now.' but found 'End.' {}
	    	at ballerina/test:createBallerinaError(assert.bal:42)
	    	ballerina/test:assertEquals(assert.bal:83)
	    	ballerina-examples/task-scheduler-timer:0.0.1:testFunc(tests/task_scheduler_timer_test.bal:31)

	0 passing
	1 failing
	0 skipped
```

Complete log - [log-tests:task_scheduler_timer_test.txt](https://github.com/ballerina-platform/ballerina-lang/files/2998966/log-tests.task_scheduler_timer_test.txt)

### PR DESCRIPTION
**Pull request by ThisaruGuruge**

### CODE REVIEW

File: stdlib/task/src/main/java/org/ballerinalang/stdlib/task/objects/AbstractTask.java [hunk 1]
```diff
@@ -141,66 +141,44 @@ private void validateMaxRuns(long maxRuns) throws SchedulingException {
...
-        if (quartzJobs.containsKey(taskId)) {
-            try {
-                scheduler.deleteJob(quartzJobs.get(taskId));
-            } catch (SchedulerException e) {
-                throw new SchedulingException("Cannot cancel the task. ");
+    public void stop() throws SchedulingException {
+        try {
+            this.scheduler.shutdown(true);
+        } catch (SchedulerException e) {
+            if (log.isDebugEnabled()) {
```
Comment (wggihan) [inline stdlib/task/src/main/java/org/ballerinalang/stdlib/task/objects/AbstractTask.java]: This is not a correct way. Either we have to log it here or throw an error. Shall we add the exception instance to newly created SchedulingException and handle it in upper layer?

Comment (ThisaruGuruge) [reply stdlib/task/src/main/java/org/ballerinalang/stdlib/task/objects/AbstractTask.java]: Done

File: stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Pause.java [hunk 2]
```diff
@@ -61,6 +65,7 @@ public void execute(Context context) {
         try {
             task.pause();
         } catch (SchedulingException e) {
+            LOG.error(e.getMessage(), e);
```
Comment (anupama-pathirage) [inline stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Pause.java]: Wny do we need to log this as we are returning the error message to the user?

File: stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Resume.java [hunk 3]
```diff
@@ -60,6 +64,7 @@ public void execute(Context context) {
         try {
             task.resume();
         } catch (SchedulingException e) {
+            LOG.error(e.getMessage(), e);
```
Comment (anupama-pathirage) [inline stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Resume.java]: Wny do we need to log this as we are returning the error message to the user?

File: stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Pause.java (hunk 2 above)
Comment (ThisaruGuruge) [reply stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Pause.java]: The returning error is a custom error we created inside ballerina native functions. But we are logging that error with the error / exception from the Quartz, for debugging purposes.

File: stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Resume.java (hunk 3 above)
Comment (ThisaruGuruge) [reply stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Resume.java]: The returning error is a custom error we created inside ballerina native functions. But we are logging that error with the error / exception from the Quartz, for debugging purposes.

File: stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Pause.java (hunk 2 above)
Comment (anupama-pathirage) [reply stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Pause.java]: Do we  follow this approach for any other stdlib extern functions? @wggihan Is this the best practice to follow?

Comment (wggihan) [reply stdlib/task/src/main/java/org/ballerinalang/stdlib/task/actions/Pause.java]: In here when we use the e.getMessage() it will return a custom error message that generated by us. The original quartz exception will be wrapped inside the SchedulingException. We don't want to expose the quartzness to the outside. But we might need that if there is an exception. That is the reason the log the exception. We have done that in other places as well.
