### PR TITLE
Infer type-binding in outer join as nillable.

### LINKED ISSUE #34897: NPE for outer join
**Description:**

This is related to BBE https://ballerina.io/learn/by-example/join-clause

```Ballerina
type User record {|
    readonly int id;
    string name;
|};

type Login record {|
    int userId;
    string time;
|};

public function main() {
    table<User> key(id) users = table [
            {id: 1234, name: "Keith"},
            {id: 6789, name: "Anne"}
        ];

    Login[] logins = [
        {userId: 6789, time: "20:10:23"},
        {userId: 1234, time: "10:30:02"},
        {userId: 3987, time: "12:05:00"}
    ];

    string[] _ = from var login in logins
        outer join var user in users on login.userId equals user.id
        select user.name + ":" + login.time;
}
```

## Output
```LogTalk
[2022-01-29 15:06:25,191] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at t1.$streamLambda$_4(t1.bal:25)
        at t1.$streamLambda$_4$lambda4$(t1.bal:25)
        at ballerina.lang$0046query.0.$value$_SelectFunction.process(types.bal:590)
        at ballerina.lang$0046query.0.$value$_SelectFunction.call(types.bal)
        at ballerina.lang$0046query.0.types.$annon$method$delegate$0(types.bal:91)
        at ballerina.lang$0046query.0.$value$_StreamPipeline.$annon$method$delegate$0$lambda0$(types.bal)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:611)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:317)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:284)
        at java.base/java.lang.Thread.run(Thread.java:834)
 
[2022-01-29 15:06:25,229] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.api.values.BError.<init>(BError.java:37)
        at io.ballerina.runtime.internal.values.ErrorValue.<init>(ErrorValue.java:92)
        at io.ballerina.runtime.internal.values.ErrorValue.<init>(ErrorValue.java:82)
        at io.ballerina.runtime.api.creators.ErrorCreator.createError(ErrorCreator.java:51)
        at io.ballerina.runtime.api.creators.ErrorCreator.createError(ErrorCreator.java:140)
        at io.ballerina.runtime.internal.scheduling.Scheduler.postProcess(Scheduler.java:379)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:333)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:284)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**

**Affected Versions:**
all

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by ushirask**
Fixes #34897 & #38223

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -6454,6 +6454,13 @@ public void visit(BLangJoinClause joinClause, AnalyzerData data) {
         checkExpr(joinClause.collection, data.commonAnalyzerData.queryEnvs.peek(), data);
         // Set the type of the foreach node's type node.
         types.setInputClauseTypedBindingPatternType(joinClause);
+        if (joinClause.isOuterJoin) {
+            if (!joinClause.isDeclaredWithVar) {
+                this.dlog.error(joinClause.variableDefinitionNode.getPosition(),
+                        DiagnosticErrorCode.OUTER_JOIN_MUST_BE_DECLARED_WITH_VAR);
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6460]: Shouldn't we return here?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/JoinClauseTest.java [hunk 2]
```diff
@@ -150,7 +155,13 @@ public void testNegativeScenarios() {
         validateError(negativeResult, i++, "missing on keyword", 309, 1);
         validateError(negativeResult, i++, "undefined symbol 'dept'", 329, 24);
         validateError(negativeResult, i++, "missing equals keyword", 330, 1);
-        validateError(negativeResult, i, "missing identifier", 330, 1);
+        validateError(negativeResult, i++, "missing identifier", 330, 1);
+        validateError(negativeResult, i++, "incompatible types: expected 'Department?', found 'Department'", 353, 19);
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/JoinClauseTest.java:159]: Instead, we should get the error for `var must be used with outer join`

File: tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal [hunk 3]
```diff
@@ -325,15 +325,35 @@ function testOnClauseWithoutEquals() returns boolean {
...
+    Person[] personList = [p1, p2];
+    Department[] deptList = [d1, d2];
+
+    DeptPerson[] deptPersonList =
+       from Person person in personList
+       outer join Department dept in deptList
+       select {
+           fname : person.fname,
+           lname : person.lname,
+           dept : dept?.name
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal:357]: Add negative tests for using `var` in type binding in join clause, but not considering nilable expression during access at `on`, `select` and other clauses.

File: tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal [hunk 4]
```diff
@@ -325,15 +325,35 @@ function testOnClauseWithoutEquals() returns boolean {
...
+       };
+}
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal:359]: Add a test where inner join case, does not require type binding to be `var` type

File: tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause.bal [hunk 5]
```diff
@@ -455,3 +455,51 @@ function getDeptName(int id) returns string {
...
+        {userId: 3987, time: "12:05:00"}
+    ];
+
+    string?[] selected = from var login in logins
+        outer join var user in users on login.userId equals user?.id
+        select (user?.name);
+
+    assertEquality("Anne", selected[0]);
+    assertEquality("Keith", selected[1]);
+    assertEquality(null, selected[2]);
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause.bal:487]: Add few more positive tests with `do` and other clauses

File: tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal (hunk 4 above)
Comment (ushirask) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal:359]: There's already such cases in `join-clause.bal` right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6460]: Fixed.

File: tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal [hunk 6]
```diff
@@ -325,15 +325,75 @@ function testOnClauseWithoutEquals() returns boolean {
...
+    ];
+
+    Department[] departments = [
+        {id: 1, name:"HR"},
+        {id: 2, name:"Operations"}
+    ];
+
+    string?[] _ = from Department dept in departments
+        outer join var person in people on dept.id equals person?.id
+        select person.fname;
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal:374]: Shouldn't `person` be nilable at this point?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 7]
```diff
@@ -1950,3 +1950,6 @@ error.module.generated.for.client.decl.must.have.a.client.object.type=\
 
 error.module.generated.for.client.decl.cannot.have.mutable.state=\
   a module generated for a client declaration cannot have mutable state
+
+error.outer.join.must.be.declared.with.var=\
+  outer join must be declared with var
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1955]: Missing new line

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/JoinClauseTest.java [hunk 8]
```diff
@@ -150,7 +155,16 @@ public void testNegativeScenarios() {
...
         validateError(negativeResult, i++, "missing equals keyword", 330, 1);
-        validateError(negativeResult, i, "missing identifier", 330, 1);
+        validateError(negativeResult, i++, "missing identifier", 330, 1);
+        validateError(negativeResult, i++, "outer join must be declared with var", 353, 19);
+        validateError(negativeResult, i++, "undefined symbol 'dept'", 357, 19);
+        validateError(negativeResult, i++, "invalid operation: type 'Person?' does not support field access", 374, 16);
+        validateError(negativeResult, i++, "incompatible types: expected 'int', found 'other'", 389, 59);
+        validateError(negativeResult, i++, "invalid operation: type 'Person?' does not support field access", 389, 59);
+        validateError(negativeResult, i++, "invalid operation: type 'Person?' does not support field access", 395, 22);
+        validateError(negativeResult, i++, "order by not supported for complex type fields, order key should belong" +
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/JoinClauseTest.java:165]: Wondering why we get this error? Seems at that point, `person` type is `other`. Can you please check

Comment (pcnfernando) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/JoinClauseTest.java:165]: This is because `person` is Person? which is expected. Hence, resolving

File: tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal [hunk 9]
```diff
@@ -325,15 +325,75 @@ function testOnClauseWithoutEquals() returns boolean {
...
+    ];
+
+    string?[] _ = from Department dept in departments
+        outer join var person in people on dept.id equals person.id
+        select person?.fname;
+
+    string[] ordered_names = [];
+    error? e = from Department dept in departments
+            outer join var person in people on dept.id equals person?.id
+            order by person.id
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal:395]: Can you add an optional field access used in order by positive test as well

**Review by pcnfernando — APPROVED** [review]
Approving even though https://github.com/ballerina-platform/ballerina-lang/pull/38232#discussion_r1017640473 is pending. Tested such a sample locally

File: tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal (hunk 9 above)
Comment (ushirask) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/join-clause-negative.bal:395]: Added.

**Review by pcnfernando — APPROVED** [review]

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 10]
```diff
@@ -1958,6 +1958,9 @@ error.module.generated.for.client.decl.must.have.a.client.object.type=\
 
 error.module.generated.for.client.decl.cannot.have.mutable.state=\
   a module generated for a client declaration cannot have mutable state
+  
+error.outer.join.must.be.declared.with.var=\
+  outer join must be declared with var
```
Comment (lasinicl) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1963]: Shouldn't this be 
```suggestion
  outer join must be declared with 'var'
```

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1963]: Yes, missed this

**Review by pcnfernando — CHANGES_REQUESTED** [review]
Please check this https://github.com/ballerina-platform/ballerina-lang/pull/38232#discussion_r1019947576

**Review by lasinicl — APPROVED** [review]

**Review by pcnfernando — APPROVED** [review]
