### PR TITLE
Fix Ballerina shell CLI tests to remove some special characters

### LINKED ISSUE #28080: [Ballerina Shell] Shell CLI integrator tests should be enabled
**Description:**
Shell CLI tests were disabled by #28079  due to inconsistency with test case passing.
These tests need to be fixed and re-enabled.

**Steps to reproduce:**
Testing shell-cli in some computers will yield in following errors.
```
ballerina-shell-cli-test-suite > ballerina-shell-cli-test > io.ballerina.shell.cli.test.integration.FunctionEvaluatorTest > testEvaluatePointers STANDARD_ERROR
    Exception in thread "Thread-59" java.lang.AssertionError: Define function named add. expected [] but found [>
    ]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at io.ballerina.shell.cli.test.base.TestIntegrator.run(TestIntegrator.java:102)

ballerina-shell-cli-test-suite > ballerina-shell-cli-test > io.ballerina.shell.cli.test.integration.FunctionEvaluatorTest > testEvaluatePointers FAILED
    java.io.IOError: java.io.IOException: Pipe broken
        at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:143)
        at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
        at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
        at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:839)
        at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:859)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:586)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:417)
        at io.ballerina.shell.cli.jline.DumbJlineTerminalAdapter.readLine(DumbJlineTerminalAdapter.java:44)
        at io.ballerina.shell.cli.BallerinaShell.run(BallerinaShell.java:101)
        at io.ballerina.shell.cli.ReplShellApplication.execute(ReplShellApplication.java:88)
        at io.ballerina.shell.cli.test.integration.AbstractIntegrationTest.test(AbstractIntegrationTest.java:63)
        at io.ballerina.shell.cli.test.integration.FunctionEvaluatorTest.testEvaluatePointers(FunctionEvaluatorTest.java:45)

        Caused by:
        java.io.IOException: Pipe broken
```

### PR DESCRIPTION
**Pull request by kdsuneraavinash**
## Purpose
Ballerina shell CLI tests depend on the terminal output to assert its checks. However, due to the behavior in some terminals, the output included unexpected control characters which resulted in tests failing when running via terminals.
This pull request removes the control characters and fixes the tests to be more verbose on failure.

However, these tests are required to test locally on different terminals before merging.

Addresses #28080 
However, due to CLI taking too long to run, the tests are kept disabled.

## Approach
- Cleaned the terminal output of more control characters
- Fix the tests to compare the final output instead of comparing split substrings
- Refactor ballerina cli test to include a couple of more test cases and to follow the same logic as shell-cli tests

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java [hunk 1]
```diff
@@ -57,61 +62,84 @@ public TestIntegrator(InputStream inputStream, OutputStream outputStream,
...
     public void run() {
         try {
-            String shellPrompt = PropertiesLoader.getProperty(REPL_PROMPT);
             PrintStream testPrint = new PrintStream(outputStream, true, Charset.defaultCharset());
             InputStreamReader inStreamReader = new InputStreamReader(inputStream, Charset.defaultCharset());
             BufferedReader testReader = new BufferedReader(inStreamReader);
 
+            sendRequest(testPrint, "");
+            readResponse(testReader);
+            readResponse(testReader);
```
Comment (Kishanthan) [inline ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java:71]: Why are we reading twice here? And the read response also ignored?

Comment (kdsuneraavinash) [reply ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java:71]: The response here is not testable because they can change. 
The first `readResponse` is to read and ignore all the initial output from the CLI. (header text, etc...)
The second `readResponse` is to read any response to the first request. (L69)

After that we can send a request and read its correct response.

Comment (Kishanthan) [reply ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java:71]: Ok, then can you add a comment describing this?

**Review by Kishanthan — APPROVED** [review]
