### PR TITLE
Eliminate BType based old isAssignable path

### LINKED ISSUE #34965: Incorrect type narrowing for `x is int && x == 2`
**Description:**
$subject. Consider the following code.

```bal
function test1(2|"foo" x) {
    if x is int && x == 2 {
        2 _ = x; // OK
    } else {
        "foo" _ = x; // Gives expression of type 'never' or equivalent to type 'never' not allowed here
    }

    if x is 2 && x == 2 {
        2 _ = x; // OK
    } else {
        "foo" _ = x; // Gives an issue expression of type 'never' or equivalent to type 'never' not allowed here
    }

    if x == 2 && x == 2 {
        2 _ = x; // OK
    } else {
        "foo" _ = x; // Gives an issue expression of type 'never' or equivalent to type 'never' not allowed here
    }
}
```

**Affected Versions:**
2201.0.0

### LINKED ISSUE #43126: [Improvement]: Eliminate BType based old isAssignable path
### Description

$subject. 

Now that semtype support is implemented for all the types and has been integrated with the compile-time via BTypes, the next step is to $subject.

### LINKED ISSUE #43348: [Task]: Investigate into the ballerina library level 5 failure for PR #43303
### Description

$subject.

Quoting from https://github.com/ballerina-platform/ballerina-lang/issues/43126#issuecomment-2325694181

> Regarding the ballerina library level 5 failure.
> 
> It was observed that `testInterceptableServiceInterceptors()` test in `CompilerPluginTest.java` class only fails when the other 3 tests quoted here are enabled. When either one of them is disabled, the `testInterceptableServiceInterceptors()` gets passed.
> 
> ```java
>     @Test
>     public void testInValidQueryInfoArgs() {
>         Package currentPackage = loadPackage("sample_package_8");
>         PackageCompilation compilation = currentPackage.getCompilation();
>         DiagnosticResult diagnosticResult = compilation.diagnosticResult();
>         Assert.assertEquals(diagnosticResult.errorCount(), 9);
>         assertTrue(diagnosticResult, 0, "invalid resource parameter type: 'ballerina/mime", HTTP_106);
>         assertError(diagnosticResult, 1, "invalid union type of query param 'a': 'string', 'int', " +
>                 "'float', 'boolean', 'decimal', 'map<anydata>' type or the array types of them can only be union" +
>                 " with '()'. Eg: string? or int[]?", HTTP_113);
>         assertError(diagnosticResult, 2, "invalid union type of query param 'b': 'string', 'int', " +
>                 "'float', 'boolean', 'decimal', 'map<anydata>' type or the array types of them can only be union" +
>                 " with '()'. Eg: string? or int[]?", HTTP_113);
>         assertError(diagnosticResult, 3, "invalid union type of query param 'c': 'string', 'int', " +
>                 "'float', 'boolean', 'decimal', 'map<anydata>' type or the array types of them can only be union" +
>                 " with '()'. Eg: string? or int[]?", HTTP_113);
>         assertError(diagnosticResult, 4, "invalid type of query param 'd': expected one of the " +
>                 "'string', 'int', 'float', 'boolean', 'decimal', 'map<anydata>' types or the array types of them",
>                 HTTP_112);
>         assertError(diagnosticResult, 5, "invalid type of query param 'a': expected one of the " +
>                 "'string', 'int', 'float', 'boolean', 'decimal', 'map<anydata>' types or the array types of them",
>                 HTTP_112);
>         assertError(diagnosticResult, 6, "invalid type of query param 'aa': expected one of the " +
>                 "'string', 'int', 'float', 'boolean', 'decimal', 'map<anydata>' types or the array types of them",
>                 HTTP_112);
>         assertError(diagnosticResult, 7, "invalid type of query param 'd': expected one of the " +
>                 "'string', 'int', 'float', 'boolean', 'decimal', 'map<anydata>' types or the array types of them",
>                 HTTP_112);
>         assertError(diagnosticResult, 8, "invalid type of query param 'e': expected one of the " +
>                 "'string', 'int', 'float', 'boolean', 'decimal', 'map<anydata>' types or the array types of them",
>                 HTTP_112);
>     }
> 
>     @Test
>     public void testCallerInfoAnnotation() {
>         Package currentPackage = loadPackage("sample_package_10");
>         PackageCompilation compilation = currentPackage.getCompilation();
>         DiagnosticResult diagnosticResult = compilation.diagnosticResult();
>         Assert.assertEquals(diagnosticResult.errorCount(), 11);
>         assertError(diagnosticResult, 0, "incompatible respond method argument type : expected " +
>                 "'int' according to the 'http:CallerInfo' annotation", HTTP_114);
>         assertError(diagnosticResult, 1, "incompatible respond method argument type : expected " +
>                 "'decimal' according to the 'http:CallerInfo' annotation", HTTP_114);
>         assertError(diagnosticResult, 2, "incompatible respond method argument type : expected " +
>                 "'Person' according to the 'http:CallerInfo' annotation", HTTP_114);
>         assertError(diagnosticResult, 3, "incompatible respond method argument type : expected " +
>                 "'string' according to the 'http:CallerInfo' annotation", HTTP_114);
>         assertError(diagnosticResult, 4, "invalid multiple 'http:Caller' parameter: 'xyz'", HTTP_115);
>         assertError(diagnosticResult, 5, "incompatible respond method argument type : expected " +
>                 "'Person' according to the 'http:CallerInfo' annotation", HTTP_114);
>         assertError(diagnosticResult, 6, "incompatible respond method argument type : expected " +
>                 "'Person' according to the 'http:CallerInfo' annotation", HTTP_114);
>         assertError(diagnosticResult, 7, "incompatible respond method argument type : expected " +
>                 "'Person' according to the 'http:CallerInfo' annotation", HTTP_114);
>         assertError(diagnosticResult, 8, "incompatible respond method argument type : expected " +
>                 "'http:Error' according to the 'http:CallerInfo' annotation", HTTP_114);
>         assertError(diagnosticResult, 9, "incompatible respond method argument type : expected " +
>                 "'http:Ok' according to the 'http:CallerInfo' annotation", HTTP_114);
>         assertError(diagnosticResult, 10, "incompatible respond method argument type : expected " +
>                 "'http:StatusCodeResponse' according to the 'http:CallerInfo' annotation", HTTP_114);
>     }
> 
>     @Test
>     public void testAnnotationUsageWithReturnType() {
>         Package currentPackage = loadPackage("sample_package_22");
>         PackageCompilation compilation = currentPackage.getCompilation();
>         DiagnosticResult diagnosticResult = compilation.diagnosticResult();
>         Assert.assertEquals(diagnosticResult.errorCount(), 4);
>         assertError(diagnosticResult, 0, "invalid usage of cache annotation with return type : " +
>                 "'error'. Cache annotation only supports return types of anydata and SuccessStatusCodeResponse",
>                 CompilerPluginTestConstants.HTTP_130);
>         assertError(diagnosticResult, 1, "invalid usage of payload annotation with return type : " +
>                 "'error'", CompilerPluginTestConstants.HTTP_131);
>         assertError(diagnosticResult, 2, "invalid usage of payload annotation with return type : " +
>                 "'error?'", CompilerPluginTestConstants.HTTP_131);
>         assertError(diagnosticResult, 3, "invalid usage of cache annotation with return type : " +
>                 "'error?'. Cache annotation only supports return types of anydata and SuccessStatusCodeResponse",
>                 CompilerPluginTestConstants.HTTP_130);
>     }
> 
>     @Test
>     public void testInterceptableServiceInterceptors() {
>         Package currentPackage = loadPackage("sample_package_39");
>         PackageCompilation packageCompilation = currentPackage.getCompilation();
>         DiagnosticResult diagnosticResult = packageCompilation.diagnosticResult();
>         Assert.assertFalse(diagnosticResult.hasWarnings());
>         Assert.assertFalse(diagnosticResult.hasErrors()); // Fails here
>     }
> ```

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #43126
Fixes #34965 except for one case
Resolves #43348

## Approach
n/a

## Samples
n/a

## Remarks
- Fixed distinct error type and distinct error intersection issues
- Fixed `transactional function` and `isolated function` resolution
- Fixed ignoring return type in generic function subtyping
- Fixed remote qualifier being ignored in function semtype
- Fixed mapping type for optional never fields

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BIntersectionType.java [hunk 1]
```diff
@@ -144,7 +145,13 @@ public SemType semType() {
     private SemType computeResultantIntersection() {
         SemType t = PredefinedType.VAL;
         for (BType constituentType : this.getConstituentTypes()) {
-            t = SemTypes.intersect(t, SemTypeHelper.semTypeComponent(constituentType));
+            t = SemTypes.intersect(t, SemTypeHelper.semType(constituentType));
+        }
+
+        // TODO: this is a temporary workaround to propagate effective typeIds
+        BType referredType = Types.getReferredType(this.effectiveType);
+        if (referredType instanceof BErrorType effErr) {
```
Comment (heshanpadmasiri) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BIntersectionType.java:153]: Could we have the same issue with objects here as well?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BRecordType.java [hunk 2]
```diff
@@ -158,34 +156,37 @@ public SemType semType() {
...
-                } else {
+            if (ty == null || NEVER.equals(ty)) {
+                if (!optional) {
                     // if there is a non-optional field with `never` type(BType Component + SemType Component),
                     // it is not possible to create a value. Hence, the whole record type is considered as `never`.
                     md.setSemTypeToNever();
                     return NEVER;
                 }
+
+                if (restFieldSemType.equals(NEVER)) {
```
Comment (heshanpadmasiri) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BRecordType.java:179]: Can we use `Core.isNever(restFieldSemType)` here?

**Review by heshanpadmasiri — APPROVED** [review]
Minor nits. Other than that LGTM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BObjectType.java [hunk 3]
```diff
@@ -241,6 +248,10 @@ public boolean isNullable() {
         return false;
     }
 
+    public static void resetAllocatedIds() {
+        DistinctIdSupplier.allocatedIds.clear();
```
Comment (heshanpadmasiri) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BObjectType.java:252]: Here instead of doing this shall we add a map of allocatedIds to the DistinctIdSupplier
```java
private static final Map<Env, Map<BTypeIdSet.BTypeId, Integer>> allocatedIds = Collections.synchronizedMap(new WeakHashMap());

...
private DistinctIdSupplier(Env env) {
      this.env = env;
      allocatedIds.putIfAbscent(env, new ConcurrentHashMap<>());
}
```

**Review by heshanpadmasiri — APPROVED** [review]
LGTM
