### PR TITLE
Fix several closures in query expressions/actions

### LINKED ISSUE #32710: [Query Expressions]Some queries fail resolving closure symbols
**Description:**
```ballerina
 var res = from var emp in (from var x in (from var xx in (from var xxx in (from var {firstName, lastName, dept} in employeeList
                        where 1 == 1
                        select firstName + " " + lastName)
                    select xxx)
                select xx)
            select x)
        select emp;
```
 
**Steps to reproduce:**

**Affected Versions:**
SL Beta 3 rc 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #39497: [Bug]: Compiler crash in nested from-clause
### Description

```ballerina
public function main() {
    var input = [{name: "Saman", price: 11}];
    var res = from var {name} in input
                select from var {price} in input
                        select {name, price}; 
}
```
This code crashes with following stacktrace.
```
[2023-02-02 20:42:12,051] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.createFunctionInfoArray(MainMethodGen.java:341)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.loadCLIArgsForMain(MainMethodGen.java:298)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.generateUserMainFunctionCall(MainMethodGen.java:273)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MainMethodGen.generateMainMethod(MainMethodGen.java:167)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:428)
	at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1040)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:399)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:810)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:96)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:71)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:317)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:477)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:165)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:213)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### Steps to Reproduce

Check the description

### Affected Version(s)

Ballerina 2201.3.0 (Swan Lake Update 3)

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by TharushiJay**
## Purpose
This PR fixes several closures in query expressions/actions.

Fixes #39497 
Fixes #32710
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/36286
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/36488
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/37425

Created #39760 to track the test case `testClosureInQueryActionInDo2`.
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by KavinduZoysa** [comment]
@TharushiJay, can you check whether [this issue](https://github.com/ballerina-platform/ballerina-lang/issues/35254) is fixed on your PR?

**Comment by TharushiJay** [comment]
> @TharushiJay, can you check whether [this issue](https://github.com/ballerina-platform/ballerina-lang/issues/35254) is fixed on your PR?

It's not fixed. Getting the following error.
```
error: {ballerina}TypeCastError {"message":"incompatible types: '()' cannot be cast to 'int'"}
	at test:$streamLambda$_2(test.bal:0)
	   ballerina.lang.query.0._FilterFunction:process(types.bal:551)
	   ballerina.lang.query.0._SelectFunction:process(types.bal:645)
	   ballerina.lang.query.0:$anon$method$delegate$_StreamFunction.process$0(types.bal:93)
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 1]
```diff
@@ -1716,8 +1717,8 @@ public void visit(BLangSimpleVarRef bLangSimpleVarRef) {
 
                 if (symbol instanceof BVarSymbol) {
                     ((BVarSymbol) symbol).originalSymbol = null;
-                    if (withinLambdaOrArrowFunc) {
-                        if (symbol.closure) {
+                    if (withinLambdaOrArrowFunc || withinQuery) {
+                        if ((withinLambdaOrArrowFunc && symbol.closure) || (!withinLambdaOrArrowFunc && withinQuery)) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:1721]: We can simplify this check as `!withinLambdaOrArrowFunc || symbol.closure`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 2]
```diff
@@ -2173,17 +2174,37 @@ public void visit(BLangIf ifNode) {
...
+        boolean prevWithinQuery = withinQuery;
+        if (isInQuery(queryExpr.parent)) {
+            this.withinQuery = true;
+        }
         queryExpr.getQueryClauses().forEach(this::acceptNode);
+        this.withinQuery = prevWithinQuery;
         this.queryEnv = prevQueryEnv;
     }
 
+    private boolean isInQuery(BLangNode parent) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:2198]: Pass the `node` to this function (not `node.parent`), and change the method like this.
```java
    private boolean isInQuery(BLangNode node) {
        BLangNode parent = node.parent;
        while (parent != null) {
            if (isQueryExprOrAction(parent)) {
                return true;
            }
            parent = parent.parent;
        }
        return false;
    }
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 3]
```diff
@@ -2173,17 +2174,37 @@ public void visit(BLangIf ifNode) {
...
+        while (parent != null) {
+            if (isQueryExprOrAction(parent)) {
+                return true;
+            }
+            parent = parent.parent;
+        }
+        return false;
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:2205]: Do we have tests to cover this line?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 4]
```diff
@@ -2214,6 +2236,16 @@ public void visit(BLangSelectClause selectClause) {
         this.acceptNode(selectClause.expression);
     }
 
+    private boolean isQueryExprOrAction(BLangNode node) {
+        if (node.getKind() == NodeKind.QUERY_EXPR || node.getKind() == NodeKind.DO_ACTION) {
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:2240]: Let's extractout node kind to a variable and do the checks

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 3 above)
Comment (TharushiJay) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java]: Modified the code since this line is never reached.

**Review by KavinduZoysa — APPROVED** [review]
