### PR TITLE
Fix the addition of multiple whitespaces through missing tokens

### LINKED ISSUE #26767: [Formatter] Handle addition of multiple whitespaces through missing tokens
**Description:**
When there are missing tokens, the formatter adds the trailing minutiaes to ensure the formatting in the remaining code is not distorted. But if there are multiple whitespaces added due to this, they should be reduced to 1 whitespace. 

For instance, a sample code would be as follows:

**Source:**
```ballerina
public function foo() returns {

}
```

**Current Output:**
```ballerina
public function foo() returns  {

}
```
Notice the 2 whitespaces after the `returns` keyword.

**Expected Output:**
```ballerina
public function foo() returns {

}
```

**Steps to reproduce:**
SLP5

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by IrushiL**
## Purpose

Fixes #26767

## Check List 
- [X] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 1]
```diff
@@ -264,6 +264,9 @@
     // Range of the file to be formatted.
     private final LineRange lineRange;
 
+    // Previous token's trailing whitespaces.
+    private int prevTokensTrailingWS;
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:268]: Shall we move this to `env`?

Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java]: Done

**Review by SupunS — APPROVED** [review]
