### PR TITLE
Fix issue with using destructuring recording binding pattern in query expression and foreach

### LINKED ISSUE #35741: Compilation error when destructuring recording binding pattern used in query expressions
```ballerina
type ScoreEvent readonly & record {|
    string email;
    string problemId;
    float score;
|};

public function main() {
    ScoreEvent[] events = [];
    json j = from var {email, problemId, score} in events
    select {email, score};
}
```

Compilation errors 
```
ERROR [main.bal:(108:19,108:48)] invalid record binding pattern with type 'ScoreEvent'
ERROR [main.bal:(109:13,109:18)] undefined symbol 'email'
ERROR [main.bal:(109:20,109:25)] undefined symbol 'score'
```

Compilation errors disappear when I remoe the readonly from the `ScoreEvent` record.

### PR DESCRIPTION
**Pull request by lasinicl**
## Purpose
$title

Fixes #35741

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 1]
```diff
@@ -3726,8 +3726,8 @@ public void visit(BLangForeach foreach, AnalyzerData data) {
         // Create a new block environment for the foreach node's body.
         SymbolEnv blockEnv = SymbolEnv.createBlockEnv(foreach.body, currentEnv);
         // Check foreach node's variables and set types.
-        handleForeachDefinitionVariables(foreach.variableDefinitionNode, foreach.varType, foreach.isDeclaredWithVar,
-                                         false, blockEnv);
+        handleForeachDefinitionVariables(foreach.variableDefinitionNode, Types.getReferredType(foreach.varType),
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:3729]: If we do `getReferredType()` at this level; we loose the type reference information here itself. We'll have to handle at the lower levels where we actually need the actual type and use the reference type in the errors even so.
eg:

```ballerina
type Foo record {|
int id;
|};

type Bar Foo;
public function dummyTest() {
    Bar[] arr = [];
    foreach int item in arr { //now error is expected 'Foo' found int. But it should be 'Bar'

    }
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 2]
```diff
@@ -4232,7 +4232,7 @@ private void handleForeachDefinitionVariables(VariableDefinitionNode variableDef
         // Check whether the foreach node's variables are declared with var.
         if (isDeclaredWithVar) {
             // If the foreach node's variables are declared with var, type is `varType`.
-            handleDeclaredVarInForeach(variableNode, varType, blockEnv);
+            handleDeclaredVarInForeach(variableNode, Types.getReferredType(varType), blockEnv);
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:4235]: Even if we do this; we'll lose the type ref information. My suggestion is to pass the reference type to `handleDeclaredVarInForeach()`. Extract out the actual type there; use it where needed. eg: type tag checks. Use the reference type in errors as in https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java#L1851 and https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java#L1890

**Review by pcnfernando — APPROVED** [review]
