### PR TITLE
Revamp `Update documentation` code action

### LINKED ISSUE #31678: Update 'add documentation' code action to show 'update documentation' as code action title for already documented nodes
**Description:**

$subject

Screenshot from 2021-07-13 10-59-18

**Steps to reproduce:**
```
service / on new http:Listener(8080) {

   
    # Description
    #
    # + name - Parameter Description
    # + return - Return Value Description   
    resource function get greeting() returns string {
        return "Hello";
    }
}
```
**Affected Versions:**

**OS, DB, other environment details and versions:**

### LINKED ISSUE #31881: Incorrect behaviour in `Update documentation` code action when parameter and return value descriptions span across several lines
**Description:**

In the current documentation implementation, only the `description` & `deprecated description` are considered to span across several lines. This makes `Update documentation` code action behave incorrectly when `parameter descriptions` and `return value descriptions` span across several lines.

parameter description

### PR DESCRIPTION
**Pull request by TharushiJay**
## Purpose
This PR adds a `node based Update documentation` code action and disables the existing `diagnostic based Update documentation` code action to ensure `Update documentation` code action is shown only if there is a mismatch in the documentation.
update documentation

Also adds support for `parameter descriptions` and `return value descriptions` that span across several lines.
parameter description (2)

Fixes #31678
Fixes #31881

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/NodeBasedUpdateDocumentationCodeAction.java [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+        action.setCommand(command);
+        return Collections.singletonList(action);
+    }
+
+    private boolean hasMismatch(CodeActionContext context, NonTerminalNode node) {
+        SemanticModel semanticModel = context.workspace().semanticModel(context.filePath()).orElseThrow();
+        Optional<Symbol> documentableSymbol = getDocumentableSymbol(node, semanticModel);
+        SyntaxTree syntaxTree = context.workspace().syntaxTree(context.filePath()).orElseThrow();
+        Optional<DocAttachmentInfo> docAttachmentInfo = getDocumentationEditForNode(node, syntaxTree);
+        DocAttachmentInfo docs = docAttachmentInfo.get();
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/NodeBasedUpdateDocumentationCodeAction.java:98]: Shall we add the empty here for docAttachmentInfo

**Review by malinthar — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/NodeBasedUpdateDocumentationCodeAction.java [hunk 2]
```diff
@@ -0,0 +1,130 @@
+/*
+ * Copyright (c) 2020, WSO2 Inc. (http://wso2.com) All Rights Reserved.
```
Comment (gayalkuruppu) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/NodeBasedUpdateDocumentationCodeAction.java:2]: Shall we change this year to 2021?

File: language-server/modules/langserver-core/src/test/resources/command/update-documentation/source/updateDocumentationSource4.bal [hunk 3]
```diff
@@ -0,0 +1,11 @@
+
```
Comment (gayalkuruppu) [inline language-server/modules/langserver-core/src/test/resources/command/update-documentation/source/updateDocumentationSource4.bal:1]: Shall we remove this line?

**Review by IMS94 — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/NodeBasedUpdateDocumentationCodeAction.java [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+import static org.ballerinalang.langserver.command.docs.DocumentationGenerator.getDocumentationEditForNode;
+import static org.ballerinalang.langserver.command.docs.DocumentationGenerator.hasDocs;
+
+/**
+ * Code Action for updating single documentation.
+ *
+ * @since 2.0.0
+ */
+@JavaSPIService("org.ballerinalang.langserver.commons.codeaction.spi.LSCodeActionProvider")
+public class NodeBasedUpdateDocumentationCodeAction extends AbstractCodeActionProvider {
```
[the remark this answers is not in the document]
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/NodeBasedUpdateDocumentationCodeAction.java:53]: @IMS94 as per the design, even if we can use the both the `getNodeBasedCodeActions` and `getDiagnosticBasedCodeActions` in the same class, we do not encourage to do so, in order to maintain the single responsibility practices. Also, We have to keep the diagnostic based code action since we can support update documentation through the diagnostics shown on the parameters. 
Hence let's keep both for the moment and do an evaluation before removing. WDYT?

[the remark this answers is not in the document]
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/docs/NodeBasedUpdateDocumentationCodeAction.java:53]: @nadeeshaan Agreed. There can be scenarios which are not just mismatches, but best practices reported via diagnostics. In such cases, we may need the diagnostics based one. Otherwise, almost all the cases will be covered by the node based one.

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

**Review by IMS94 — APPROVED** [review]
