### PR TITLE
Fix not throwing exception

### LINKED ISSUE #39189: [Bug]: Testerina fails to throw exceptions with `bal test --native`
### Description

Constraint module fails with the `8fb5b5deb75d3fee6d248f1b7498ff35b71aecc9` commit in master for native test. We couldn't get any exceptions from Testerina side during this failure.

Refer 
https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TesterinaFunction.java#L101

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Test Framework

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
Fixes #39189 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java [hunk 1]
```diff
@@ -204,8 +204,12 @@ private static void startSuite(TestSuite suite, Scheduler initScheduler, Class<?
     private static void stopSuite(Scheduler scheduler, Class<?> initClazz) {
         TesterinaFunction stop = new TesterinaFunction(initClazz, STOP_FUNCTION_NAME, scheduler);
         stop.setName("$moduleStop");
-        stop.directInvoke(new Class<?>[]{RuntimeRegistry.class},
+        Object response = stop.directInvoke(new Class<?>[]{RuntimeRegistry.class},
                 new Object[]{scheduler.getRuntimeRegistry()});
+        if (response instanceof Throwable) {
+            throw new BallerinaTestException("stopping modules for test suite failed due to " +
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java:210]:
```suggestion
            throw new BallerinaTestException("dependant module stop for test suite failed due to " +
```

**Review by azinneera — APPROVED** [review]
