### PR TITLE
[Java21] Fix failing debugger for java 21

### LINKED ISSUE #43430: [Task]: [Java21] Fix failing debugger integration tests
### Description

$subject

### Describe your task(s)

Fail log - https://scans.gradle.com/s/znd44xczn7wcs/tests/overview?outcome=FAILED

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes #43430 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java [hunk 1]
```diff
@@ -518,19 +518,34 @@ public void workerVariableVisibilityTest() throws BallerinaTestException {
...
-
-        // variable visibility test inside worker (only worker's variables should be visible).
-        debugTestRunner.resumeProgram(debugHitInfo.getRight(), DebugTestRunner.DebugResumeKind.NEXT_BREAKPOINT);
-        debugHitInfo = debugTestRunner.waitForDebugHit(10000);
-        localVariables = debugTestRunner.fetchVariables(debugHitInfo.getRight(), DebugTestRunner.VariableScope.LOCAL);
-        debugTestRunner.assertVariable(localVariables, "x", "10", "int");
-
-        // variables outside worker should not be visible
-        Assert.assertFalse(localVariables.containsKey("a"));
+        if (debugHitInfo.getKey().getLine() == 23) {
```
Comment (HindujaB) [inline tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java:521]: This fix is added because with new virtual thread implementation, the order of execution for workers is not consistent. Therefore, we can't rely on the debug point hitting order. I modified the assertions depending on which debug point hits first. 
@warunalakshitha Is this expected?

File: tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/CallStackDebugTest.java [hunk 2]
```diff
@@ -83,7 +83,7 @@ public void stackFrameDebugTest() throws BallerinaTestException {
         // Stack frame representation test for strand creation with 'start' keyword.
         // Results of the strand is not assigned to any variable. In this case frame name is assigned to 'anonymous'.
         debugTestRunner.assertCallStack(frames[0], "sayHello", 45, "main.bal");
-        debugTestRunner.assertCallStack(frames[1], "start:anonymous", 10, "main.bal");
+        debugTestRunner.assertCallStack(frames[1], "start:anon", 10, "main.bal");
```
Comment (HindujaB) [inline tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/CallStackDebugTest.java:86]: Here, the default strand name is changed to `anon` if the future value name is not provided.

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java [hunk 3]
```diff
@@ -1105,6 +1109,8 @@ private void attachToRemoteVM(String hostName, int portName) throws IOException,
         EventRequestManager erm = context.getEventManager();
         ClassPrepareRequest classPrepareRequest = erm.createClassPrepareRequest();
         classPrepareRequest.enable();
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java:1111]: Just to make be consistent
```suggestion
        ClassPrepareRequest classPrepareRequest = erm.createClassPrepareRequest().enable();
```

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java [hunk 4]
```diff
@@ -57,6 +60,7 @@ public class JDIEventProcessor {
     private boolean isRemoteVmAttached = false;
     private final List<EventRequest> stepRequests = new ArrayList<>();
     private static final Logger LOGGER = LoggerFactory.getLogger(JDIEventProcessor.class);
+    private static final List<ThreadReference> virtualThreads = new ArrayList<>();
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java:63]:
```suggestion
    private static final Logger LOGGER = LoggerFactory.getLogger(JDIEventProcessor.class);
    private static final List<ThreadReference> virtualThreads = new ArrayList<>();
```
```suggestion
    private static final List<ThreadReference> virtualThreads = new ArrayList<>();
    private static final Logger LOGGER = LoggerFactory.getLogger(JDIEventProcessor.class);
   
```

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java [hunk 5]
```diff
@@ -121,6 +129,20 @@ private void processEvent(EventSet eventSet, Event event) {
...
+                    virtualThreads.add(thread);
+                }
+            }
+            eventSet.resume();
+        } else if (event instanceof ThreadDeathEvent threadDeathEvent) {
+            ThreadReference thread = threadDeathEvent.thread();
+            synchronized (virtualThreads) {
+                virtualThreads.remove(thread);
+            }
+            eventSet.resume();
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java:145]: For the `virtualThreads` variable, using a `ConcurrentLinkedQueue` or `CopyOnWriteArrayList` (concurrent data structures) is generally better than using an ArrayList with explicit synchronization blocks.

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM

File: tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java (hunk 1 above)
Comment (warunalakshitha) [reply tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java:521]: Yes. That should be ok

**Review by warunalakshitha — APPROVED** [review]
LGTM

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java [hunk 6]
```diff
@@ -56,6 +60,7 @@ public class JDIEventProcessor {
     private final BreakpointProcessor breakpointProcessor;
     private boolean isRemoteVmAttached = false;
     private final List<EventRequest> stepRequests = new ArrayList<>();
+    private static final List<ThreadReference> virtualThreads = new CopyOnWriteArrayList<>();
```
Comment (warunalakshitha) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java:63]: Why CopyOnWriteArrayList?

Comment (HindujaB) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java:63]: As the `virtual Threads` can be updated and accessed asynchronously, we need a thread-safe approach. 
I used `CopyOnWriteArrayList` because the `read` is more frequent than the `write` operations.
