### PR TITLE
Fix error on calling json to record convert api

### LINKED ISSUE #31312: LSExtensions/convertJsonToBalRecord API call results in internal error
**Description:**
`LSExtensions/convertJsonToBalRecord` LS API call results in an internal error when using the `Paste JSON as record` VS Code command.

```
java.lang.UnsupportedOperationException: The json request 'LSExtensions/convertJsonToBalRecord' is unknown.\n\tat org.ballerinalang.langserver.extensions.AbstractExtendedLanguageServer.request(AbstractExtendedLanguageServer.java:
```

**Steps to reproduce:**
Execute the "Paste JSON as a record" palette command.

**Affected Versions:**
Swan Lake beta2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

@tharindu-nw

### PR DESCRIPTION
**Pull request by tharindu-nw**
Fixes #31312

### CODE REVIEW

File: misc/ls-extensions/modules/json-to-record-converter/src/main/java/io/ballerina/converters/JsonToRecordConverterService.java [hunk 1]
```diff
@@ -34,7 +34,7 @@
  * @since 2.0.0
  */
 @JavaSPIService("org.ballerinalang.langserver.commons.service.spi.ExtendedLanguageServerService")
-@JsonSegment("LSExtensions")
+@JsonSegment("JsonToRecord")
```
Comment (nadeeshaan) [inline misc/ls-extensions/modules/json-to-record-converter/src/main/java/io/ballerina/converters/JsonToRecordConverterService.java:37]: Shall we avoid stating the name with a capital letter? Let's use `jsonToRecord` instead.

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: misc/ls-extensions/modules/json-to-record-converter/src/main/java/io/ballerina/converters/JsonToRecordConverterService.java (hunk 1 above)
Comment (tharindu-nw) [reply misc/ls-extensions/modules/json-to-record-converter/src/main/java/io/ballerina/converters/JsonToRecordConverterService.java]: fixed in a71ebee
