### PR TITLE
Fix object private field access

### LINKED ISSUE #7747: Fix object public/private field access
Following checks has to be mandated for public/private field access 

1. Objects should not expose private objects as fields in their public fields section. Following will fail in compilation error.
```
public type ParentFoo object {
    public {
        int i;
        ChildFoo c;
    }

    public new (i, c){}
};

type ChildFoo object {
    private {
        string name;
    }

    new (name) {}
};
```
2. Explicitly defined objects initializers has to be marked public if its intended to be used outside of the package. Following object should not be allowed to init outside of its package. 

```
public type Foo object {
    public {
        int i;
    }

    new (i, c){}
};
```

### PR DESCRIPTION
**Pull request by Kishanthan**
Resolves #7747

Following checks are mandated for public/private field access

1. Objects cannot not expose private objects as fields in their public fields section. Following will fail in compilation error.
```
public type ParentFoo object {
    public {
        int i;
        ChildFoo c;
    }

    public new (i, c){}
};

type ChildFoo object {
    private {
        string name;
    }

    new (name) {}
};
```
2. Explicitly defined objects initializers has to be marked public if its intended to be used outside of the package. Following object should not be allowed to init outside of its package.
```
public type Foo object {
    public {
        int i;
    }

    new (i, c){}
};
```

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 1]
```diff
@@ -617,9 +618,22 @@ public void visit(BLangStruct structNode) {
     }
 
     public void visit(BLangObject objectNode) {
+        objectNode.fields.stream()
```
Comment (sameera-jayasoma) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Can we also analyze and report situations where a private object contains public fields?
