### PR TITLE
[master] Improve ExpectedType API for function call expression context

### LINKED ISSUE #39407: [Bug]: Incorrect expected type for type param cases
### Description

Consider following example

```ballerina
type Type record {|
    string name;
|};

function testPositionalArgs() {
    json myJson;
    myJson.cloneWithType(<cursor>)
}

```

Here expectedType provided by `expectedType` API is incorrect. Due to this following completion test is affected `completion/expression_context/config/function_call_expression_ctx_config22.json`

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39597: [Bug]: Index Out of Bound exception in ExpectedTypeFinder
### Description

The IOB exception is thrown as follows.

image

Stack trace
```
[Error - 07:54:27] Operation 'text/completion' failed! {uri: '/home/malintha/Documents/wso2/experimental/projects/ballerina/test3/test1/main.bal', [57:9], error: 'Index 0 out of bounds for length 0'}
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at io.ballerina.compiler.api.impl.ExpectedTypeFinder.getParamType(ExpectedTypeFinder.java:986)
	at io.ballerina.compiler.api.impl.ExpectedTypeFinder.getExpectedTypeFromFunction(ExpectedTypeFinder.java:1044)
	at io.ballerina.compiler.api.impl.ExpectedTypeFinder.transform(ExpectedTypeFinder.java:325)
	at io.ballerina.compiler.api.impl.ExpectedTypeFinder.transform(ExpectedTypeFinder.java:140)
	at io.ballerina.compiler.syntax.tree.FunctionCallExpressionNode.apply(FunctionCallExpressionNode.java:58)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.expectedType(BallerinaSemanticModel.java:402)
	at org.ballerinalang.langserver.contexts.BallerinaCompletionContextImpl.getContextType(BallerinaCompletionContextImpl.java:129)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.populateBallerinaFunctionCompletionItems(AbstractCompletionProvider.java:475)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.lambda$getCompletionItemList$0(AbstractCompletionProvider.java:189)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getCompletionItemList(AbstractCompletionProvider.java:182)
	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.expressionCompletions(AbstractCompletionProvider.java:534)
	at org.ballerinalang.langserver.completions.providers.context.FunctionCallExpressionNodeContext.getCompletions(FunctionCallExpressionNodeContext.java:57)
	at org.ballerinalang.langserver.completions.providers.context.FunctionCallExpressionNodeContext.getCompletions(FunctionCallExpressionNodeContext.java:40)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:129)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:85)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:65)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:40)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:124)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:149)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

### Steps to Reproduce

```Ballerina
public function test() {
    int[] vals = [1, 2, 3];
    add(<cursor>)
}

function add(int... vals) {

}
```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject

Fixes #39407 
Fixes #39597 

## Samples
image

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 1]
```diff
@@ -1040,32 +1061,39 @@ private static TypeSymbol getRawType(TypeSymbol typeDescriptor) {
...
-                    return Optional.ofNullable(typesFactory.getTypeDescriptor
-                            (((BArrayType) bLangInvocation.expr.expectedType).eType));
-                }
+        if (size == 0 && !langLibInvocation) {
+            return getParamType(bLangInvocation, 0, Collections.emptyList());
+        }
 
-                if (size == 1) {
-                    return getParamType(bLangInvocation);
+        //func(arg1, arg<cursor>, 10)
```
Comment (IMS94) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:1069]:
```suggestion
        // func(arg1, arg<cursor>, 10)
```

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 2]
```diff
@@ -1040,32 +1061,39 @@ private static TypeSymbol getRawType(TypeSymbol typeDescriptor) {
...
+        int argumentIndex = 0;
+        List<String> namedArgs = new ArrayList<>();
+        for (BLangNode nodeInst : bLangInvocation.argExprs) {
+            //only offset is considered
```
Comment (IMS94) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:1073]:
```suggestion
            // only offset is considered
```

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 3]
```diff
@@ -1040,32 +1061,39 @@ private static TypeSymbol getRawType(TypeSymbol typeDescriptor) {
...
 
-                return getExpectedType(bLangInvocation.argExprs.get(argumentIndex - 1));
+        if (langLibInvocation) {
+            if (bLangInvocation.expr.getBType().getKind() == TypeKind.ARRAY) {
+                return Optional.ofNullable(typesFactory.getTypeDescriptor
+                        (((BArrayType) bLangInvocation.expr.expectedType).eType));
             }
 
-            return getExpectedType((bLangInvocation.argExprs.get(argumentIndex)));
+            //First argExpr is the expr of the BLangInvocationNode. Therefore, it should not be considered
```
Comment (IMS94) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:1088]:
```suggestion
            // First argExpr is the expr of the BLangInvocationNode. Therefore, it should not be considered 
```

**Review by IMS94 — CHANGES_REQUESTED** [review]
Changes look good to me. Added several minor comments around documentation/comments

**Review by IMS94 — APPROVED** [review]
