### PR TITLE
Generate Interactions using semantic modal

### LINKED ISSUE #38814: [Bug][Component Model Generator]: Relationships are not generated when the Client initialization is not in the same bal file
### Description

Currently in the Application Architecture Diagram, only the relationship of the services that have been declared in the same bal file are displayed. Please refer to the below example([original location](https://github.com/avinyafoundation/global-data/blob/0cf21a8838432a4fad8603e8a967e7f62da54529/api/main.bal#L38)).

```bal
    isolated resource function get student_applicant(string? jwt_sub_id) returns PersonData|error? {
        AvinyaType avinya_type_raw = check db_client -> queryRow(
            `SELECT *
            FROM avinya_db.avinya_type
            WHERE global_type = "applicant" AND  foundation_type = "student";`
        );

        Person|error? applicantRaw = db_client -> queryRow(
            `SELECT *
            FROM avinya_db.person
            WHERE jwt_sub_id = ${jwt_sub_id} AND 
            avinya_type_id = ${avinya_type_raw.id};`
        );
        
        if(applicantRaw is Person) {
            return new ((), applicantRaw.id);
        }

        return error("Applicant does not exist for given sub id: " + (jwt_sub_id?:""));
        
    }
```

The `db_client` is initialized in a different bal file ([see here](https://github.com/avinyafoundation/global-data/blob/0cf21a8838432a4fad8603e8a967e7f62da54529/api/util.bal#L17)) . Therefore the relationship between Global-Data-API and mysql has not been rendered in the diagram. 

**Solution**
Without using the syntax tree, try to identify the initialization of a client using the semantic module. Please Refer to the current implementation in [here](https://github.com/ballerina-platform/ballerina-lang/blob/d80337e2d2e66fd3f57cf4dc07aaf966bfcbe80f/misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/service/nodevisitors/ActionNodeVisitor.java#L96).

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Other Area

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by AzeemMuzammil**
Fixes #38814

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java [hunk 1]
```diff
@@ -88,4 +99,48 @@ public static ServiceAnnotation getServiceAnnotation(NodeList<AnnotationNode> an
...
+                String annotName = annotSymbol.getName().orElse("");
+                elementLocation = annotSymbol.getLocation().isPresent() ?
+                        getElementLocation(filePath, annotSymbol.getLocation().get().lineRange()) : null;
+                if (!(annotName.equals(DISPLAY_ANNOTATION) || annotAttachmentSymbol.attachmentValue().isEmpty()) ||
+                        !(annotAttachmentSymbol.attachmentValue().get().value() instanceof LinkedHashMap)) {
+                    continue;
+                }
+                LinkedHashMap attachmentValue = (LinkedHashMap) annotAttachmentSymbol.attachmentValue().get().value();
+                if (attachmentValue.containsKey(ID)) {
+                    id = (String) ((ConstantValue) attachmentValue.get(ID)).value();
```
Comment (NipunaRanasinghe) [inline misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java:124]:
```suggestion
                    id = ((ConstantValue) attachmentValue.get(ID)).value().toString();
```

File: misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java [hunk 2]
```diff
@@ -88,4 +99,48 @@ public static ServiceAnnotation getServiceAnnotation(NodeList<AnnotationNode> an
...
+                }
+                if (attachmentValue.containsKey(LABEL)) {
+                    label = (String) ((ConstantValue) attachmentValue.get(LABEL)).value();
```
Comment (NipunaRanasinghe) [inline misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java:127]:
```suggestion
                    label = ((ConstantValue) attachmentValue.get(LABEL)).value().toString();
```

File: misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java (hunk 1 above)
Comment (NipunaRanasinghe) [reply misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java:124]: Also better to check if the `ID` and `label` are constant values before casting

File: misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java [hunk 3]
```diff
@@ -88,4 +99,48 @@ public static ServiceAnnotation getServiceAnnotation(NodeList<AnnotationNode> an
...
+    public static String getClientModuleName(Node clientNode, SemanticModel semanticModel) {
+
+        String clientModuleName = null;
+        Optional<TypeSymbol> clientTypeSymbol = semanticModel.typeOf(clientNode);
+        if (clientTypeSymbol.isPresent()) {
+            clientModuleName = clientTypeSymbol.get().signature().trim().replace(CLIENT, "");
+        }
+
+        return clientModuleName;
+    }
```
Comment (NipunaRanasinghe) [inline misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java:145]: better if we can return an `Optional<String>` in here, to avoid NPEs if the client name can't be extracted

File: misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java [hunk 4]
```diff
@@ -88,4 +99,48 @@ public static ServiceAnnotation getServiceAnnotation(NodeList<AnnotationNode> an
...
+        List<AnnotationAttachmentSymbol> annotAttachmentSymbols = annotableSymbol.annotAttachments();
+        if (annotSymbols.size() == annotAttachmentSymbols.size()) {
+            for (int i = 0; i < annotSymbols.size(); i++) {
+                AnnotationSymbol annotSymbol = annotSymbols.get(i);
+                AnnotationAttachmentSymbol annotAttachmentSymbol = annotAttachmentSymbols.get(i);
+                String annotName = annotSymbol.getName().orElse("");
+                elementLocation = annotSymbol.getLocation().isPresent() ?
+                        getElementLocation(filePath, annotSymbol.getLocation().get().lineRange()) : null;
+                if (!(annotName.equals(DISPLAY_ANNOTATION) || annotAttachmentSymbol.attachmentValue().isEmpty()) ||
+                        !(annotAttachmentSymbol.attachmentValue().get().value() instanceof LinkedHashMap)) {
```
Comment (aneeshafedo) [inline misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java:119]:
```suggestion
                        annotAttachmentSymbol.attachmentValue().isPresent() && !(annotAttachmentSymbol.attachmentValue().get().value() instanceof LinkedHashMap)) {
```

Shall we address this possible NPE using `isPresent()` before getting the valus ?

Comment (AzeemMuzammil) [reply misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java]: I did a minor change to the syntax, as the braces I have already added were wrong. BTW, since I am checking `annotAttachmentSymbol.attachmentValue().isEmpty()` with `||` operator which do short circuit evaluation, there would not be a possibility for NPE right?

File: misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java (hunk 3 above)
Comment (AzeemMuzammil) [reply misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/GeneratorUtils.java:146]: This method is a replica of https://github.com/ballerina-platform/ballerina-lang/blob/9066508d48c262064c2db956b0959a1b0c325897/misc/ls-extensions/modules/project-design-service/src/main/java/io/ballerina/projectdesign/generators/service/nodevisitors/StatementNodeVisitor.java#L113-L133 which also returns a null if the conditions fail, and I guess the only place this method is being used is to get the `connectorType`. and having null value for connector type is acceptable I guess.

Looping @aneeshafedo

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM

**Review by aneeshafedo — APPROVED** [review]
