### PR TITLE
Fix passing tables with byte array to an union type parameter 

### LINKED ISSUE #39242: [Bug]: Attempting to use base16 and base64 byte array literals in tables with `println` give compilation errors
### Description

Attempting to do: 

```
io:println(table [{ id:1, byteArray: base16 `abcd`}]);
io:println(table [{ id:1, byteArray: base64 `Cake`}]);
```

gives the below errors respectively: 

> 
>  incompatible types: expected 'ballerina/io:1.3.1:Printable', found 'table<record {| int id; byte[2] byteArray; |}>' 
>  incompatible types: expected 'ballerinai/io:0.0.0:Printable', found 'table<record {| int id; byte[3] byteArray; |}>']

Even though this is the case in master branch, in update 3, this gives the respective expected outputs: 
```
[{"id":1,"byteArray":[171,205]}]
[{"id":1,"byteArray":[9,169,30]}]
```

### PR DESCRIPTION
**Pull request by ushirask**
Fixes #39242 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -860,8 +860,9 @@ public BType setLiteralValueAndGetType(BLangLiteral literalExpr, BType expType,
                 }
             }
         }
-
-        if (Types.getReferredType(literalExpr.getBType()).tag == TypeTags.BYTE_ARRAY) {
+        BType referedType = Types.getReferredType(literalExpr.getBType());
+        if (referedType.tag == TypeTags.BYTE_ARRAY ||
+                (referedType.tag == TypeTags.ARRAY && ((BArrayType) referedType).eType.tag == TypeTags.BYTE)) {
             // check whether this is a byte array
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:866]: ```io:println(table [{ id:1, byteArray: base16 `abcd`}]);``` for an example like this, the array literal ```base16 `abcd` ``` comes two times to this place. The first time, the type of that literal is not set, the correct type is set at this point. But the second time, the type is set to literal properly. Therefore it is not correct to go inside this if-statement and create a new type again.

Comment (hasithaa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:870]: @KavinduZoysa Apparently `io:println(table [{ id:1, byteArray: base16 `abcd`}]);` gives me a compile time error. It should be a bug, isn't it?

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-test.bal [hunk 2]
```diff
@@ -256,6 +257,11 @@ function testArrayTupleType() {
     test:assertEquals("typedesc [string[2],int,float[3][4]][][]", t.toString());
 }
 
+function testPrintByteArrayInTable() {
+    io:println(table [{ id:1, byteArray: base16 `abcd`}]);
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-test.bal:261]: This will not test the full functionality. In order to validate full semantics we have to take the type and compare it.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-test.bal [hunk 3]
```diff
@@ -256,6 +256,22 @@ function testArrayTupleType() {
     test:assertEquals("typedesc [string[2],int,float[3][4]][][]", t.toString());
 }
 
+function testPrintableByteArrayInTable() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-test.bal:259]: Shall we update the PR title and the name of the test to reflect what's actually being fixed/tested?

Comment (ushirask) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array-test.bal]: Updated.

**Review by hasithaa — APPROVED** [review]

**Review by hasithaa — APPROVED** [review]
