### PR TITLE
Fix handling of "\" escape character in identifier names

### LINKED ISSUE #41507: [Bug]: "\" escape in identifer not working as expected
### Description

$subject.
Internally all 3 identifiers `a3`, `a\3`, `a\u{0033}` should evaluate to the same symbol. 

```bal
public function main() {
    int a3 = 1;
    int a\u{0033} = 2; // gives redeclared symbol error
}

public function main() {
    int a3 = 1;
    int a\3 = 2; // no error
}

public function main() {
    int a\3 = 1;
    int a\u{0033} = 2; // no error
}
```

In summary at the `BLangNodeBuilder` we escape the unicode code points. However, we seem to not escape the "`\`".

### LINKED ISSUE #41635: [Bug]: Can't use a string literal key in a mapping constructor for a field with a name that has an identifier escape
### Description

$title.

### Steps to Reproduce

```ballerina
type R1 record {|
    int first_index;
|};

type R2 record {|
    int first\-index;
|};

public function main() {
    R1 _ = {first_index: 1}; // OK
    R1 _ = {"first_index": 1}; // OK

    R2 _ = {first\-index: 1}; // OK
    R2 _ = {"first-index": 1}; // error
}
```

### Affected Version(s)

2201.8.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by poorna2152**
Fixes #41507 
Fixes #41635 

## Remarks
Note that unescaping **more than once** would break the code for some scenarios.
e.g.  consider: `a\\3`. (Here user intends to escape the backslash using backslash)
After first unescape: `a\3` (Correct)
After second unescape `a3` (Wrong)
After third unescape `a3` (Wrong)

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/NamedCompoundVariable.java [hunk 1]
```diff
@@ -66,6 +66,12 @@ public Value getChildByName(String name) throws DebugVariableException {
         }
 
         if (!namedChildVariables.containsKey(name)) {
+            for (Map.Entry<String, Value> childVariable : namedChildVariables.entrySet()) {
+                String escaped = childVariable.getKey().replaceAll("\\$0092(\\$0092)?", "$1");
```
Comment (SasinduDilshara) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/NamedCompoundVariable.java:70]: imo, using a constant fro `$0092` will improve the readability of the code.
It is not mandatory because it is using only in here.

File: tests/jballerina-integration-test/src/test/resources/profiler/profiler_single_file.bal [hunk 2]
```diff
@@ -17,9 +17,9 @@
 import ballerina/test;
 import ballerina/jballerina.java;
 
-public function '\.\<init\>() returns string {
-    return "this is a user defined function";
-}
+// public function '\.\<init\>() returns string {
+//     return "this is a user defined function";
+// }
```
Comment (SasinduDilshara) [inline tests/jballerina-integration-test/src/test/resources/profiler/profiler_single_file.bal:22]: if we don't need lets remove it.
if we need, lets add a comment

File: tests/jballerina-integration-test/src/test/resources/profiler/profiler_single_file.bal [hunk 3]
```diff
@@ -60,7 +60,7 @@ public function main() {
     Person person = new("John", "Doe");
     test:assertEquals("John", person.firstName);
     test:assertEquals("John Doe", person.'\$init\$());
-    test:assertEquals("this is a user defined function", '\.\<init\>());
+    // test:assertEquals("this is a user defined function", '\.\<init\>());
```
Comment (SasinduDilshara) [inline tests/jballerina-integration-test/src/test/resources/profiler/profiler_single_file.bal:63]: Similar, https://github.com/ballerina-platform/ballerina-lang/pull/41540/files#r1527823270

Comment (poorna2152) [reply tests/jballerina-integration-test/src/test/resources/profiler/profiler_single_file.bal:63]: Similar to above comment

**Review by gimantha — APPROVED** [review]
