### PR TITLE
[Master] Fix compiler crashes when a union is used within multiple wait

### LINKED ISSUE #34821: Compiler crashes when a union is used within multiple wait
**Description:**
Consider the below code.
```ballerina
import ballerina/log;

type WaitResult record {|
    boolean|error producer;
    boolean consumer;
|};

public function main() {
    log:printInfo("initializing app...");

    // Producer 1
    worker Producer1 returns boolean|error {
        int i = 100;
        i -> Consumer;
        error? unionResult = flush Consumer;
        log:printInfo("Sent item", i = i);
        return true;
    }

    worker Producer2 returns boolean|error {
        int i = 100;
        i -> Consumer;
        error? unionResult = flush Consumer;
        log:printInfo("Sent item", i = i);
        return true;
    }

    // Consumer
    worker Consumer returns boolean {
        int i = <- Producer;
        log:printInfo("Received item", i = i);
        return false;
    }

    WaitResult res = wait {producer: Producer1|Producer2, consumer: Consumer};
    log:printInfo("Worker execution finished", result = res);
}
```
Note the syntactically incorrect line `WaitResult res = wait {producer: Producer1|Producer2, consumer: Consumer};`. When compiled, this gives the following crash log:
```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-01-25 13:39:10,008] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType (org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType and org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType (org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType and org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.setEventualTypeForExpression(TypeChecker.java:4095)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkWaitKeyValExpr(TypeChecker.java:4083)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkTypesForRecords(TypeChecker.java:4044)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.setResultTypeForWaitForAllExpr(TypeChecker.java:3935)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.setResultTypeForWaitForAllExpr(TypeChecker.java:3960)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:3924)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangWaitForAllExpr.accept(BLangWaitForAllExpr.java:52)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:380)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:354)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1052)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4020)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1907)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:4024)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:524)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:500)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4020)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:349)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:309)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:436)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:103)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:141)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:271)
	at org.ballerinalang.langserver.util.LSClientUtil.chekAndRegisterCommands(LSClientUtil.java:78)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:556)
	at jdk.internal.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**
See description

**Affected Versions:**
SL 2201 RC2

### PR DESCRIPTION
**Pull request by SasinduDilshara**
Fixes #34821

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by SasinduDilshara** [comment]
Create a spec issue for this.
https://github.com/ballerina-platform/ballerina-spec/issues/1171

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -4648,6 +4648,12 @@ private void setEventualTypeForExpression(BLangExpression expression,
         if (isSimpleWorkerReference(expression, data)) {
             return;
         }
+        if (expression.expectedType.tag != TypeTags.FUTURE) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4651]: I don't think this is the correct fix. 
1. We should give a better error if possible: indicating alternate wait action cannot be used as a wait-future-expr. 

Right now, the error for 

```ballerina
type WaitResult record {|
    boolean|error producer;
|};

function fn() {
    worker Producer1 returns boolean|error {
        return true;
    }

    worker Producer2 returns boolean|error {
        return true;
    }

    WaitResult _ = wait {producer: Producer1|Producer2};
}
```

is

```
ERROR [x.bal:(14:36,14:55)] incompatible types: expected 'future<(any|error)>', found eventual type '(future<(boolean|error)>|future<(boolean|error)>)' for wait future expression 'Producer1 | Producer2'
```

which doesn't quite make sense.

Here, `Producer1|Producer2` seems to actually be type-checked as an alternate wait action, which shouldn't be the case according to the current spec.

2. This will also disallow something like

```ballerina
type WaitResult record {|
    boolean|error producer;
|};

function fn() {
    worker Producer1 returns boolean|error {
        return true;
    }

    worker Producer2 returns boolean|error {
        return true;
    }

    future<boolean|error>|future<boolean|error> x = Producer1;
    WaitResult r2 = wait {producer: x};
}
```

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4651]: Created a spec issue for this. https://github.com/ballerina-platform/ballerina-spec/issues/1174

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 2]
```diff
@@ -1953,3 +1953,6 @@ error.module.generated.for.client.decl.must.have.a.client.object.type=\
 
 error.module.generated.for.client.decl.cannot.have.mutable.state=\
   a module generated for a client declaration cannot have mutable state
+
+error.unsupported.alternative.wait.action.in.multiple.wait.expr=\
+  alternative wait action not yet support inside multiple wait expressions
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1958]:
```suggestion
  cannot use an alternate wait action within a multiple wait action
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1958]: alternative -> alternate

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1958]: We say "not yet supported" only for stuff that is in the spec, but not in the implementation yet. Since this isn't in the spec yet, let's just give the error according to the current spec.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4686]: Can we improve the error here? We basically need to say we expect an expression of a future type, right?

Right now we say

> incompatible types: expected 'future<(any|error)>', found eventual type '(future<(boolean|error)>|future<(boolean|error)>)' for wait future expression 'x'

which actually doesn't seem to be correct anyway. Eventual type with `future<T>` is `T`, but here we seem to be saying the eventual type is a future.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4686]: Updated. Please check. 48185375e60cb5de6a89b97882502483cc1aea9c

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -4615,7 +4615,13 @@ private void checkTypesForRecords(BLangWaitForAllExpr waitExpr, AnalyzerData dat
 
         for (BLangWaitForAllExpr.BLangWaitKeyValue keyVal : rhsFields) {
             String key = keyVal.key.value;
-            if (!lhsFields.containsKey(key)) {
+            BLangExpression valueExpr = keyVal.valueExpr;
+            if (valueExpr instanceof BLangBinaryExpr
```
[the remark this answers is not in the document]
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated. Please check. 48185375e60cb5de6a89b97882502483cc1aea9c

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 2 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: Updated. Please check. 48185375e60cb5de6a89b97882502483cc1aea9c

**Comment by MaryamZi** [comment]
@SasinduDilshara, please resolved the conflicts.

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 4]
```diff
@@ -1961,3 +1961,9 @@ error.module.generated.for.client.decl.cannot.have.mutable.state=\
 
 error.cannot.import.module.generated.for.a.client.decl=\
   a module generated for a client declaration cannot be imported
+
+error.cannot.use.alternate.wait.action.within.multiple.wait.action=\
+  cannot use an alternate wait action within a multiple wait action
+
+error.future.expression.expected=\
+  expression of future type is expected
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1969]:
```
expected an expression of type ''future'', found ''{0}''
```

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: Updated

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java [hunk 5]
```diff
@@ -143,9 +142,30 @@ public void testNegativeWorkerActions() {
...
+        BAssertUtil.validateError(resultNegative, index++,
+                "cannot use an alternate wait action within a multiple wait action",
+                124, 48);
+        BAssertUtil.validateError(resultNegative, index++,
+                "cannot use an alternate wait action within a multiple wait action",
+                125, 27);
+        BAssertUtil.validateError(resultNegative, index++,
+                "cannot use an alternate wait action within a multiple wait action",
+                125, 58);
+        BAssertUtil.validateError(resultNegative, index++,
```
[the remark this answers is not in the document]
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java]: Updated

**Review by MaryamZi — COMMENTED** [review]
Please update the last commit message to start with an uppercase letter.

File: tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-actions-negative.bal [hunk 6]
```diff
@@ -90,6 +90,59 @@ function waitForAllTest() {
...
+type WaitResult record {|
+    boolean|error producer;
+    boolean consumer;
+|};
+
+function waitForAllTest2() {
+    worker Producer1 returns boolean|error {
+        int i = 100;
+        i -> Consumer;
+        error? unionResult = flush Consumer1;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-actions-negative.bal:102]: Do we really need all of this logic? Not required for the test, right? Shall we simplify?

File: tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-actions-negative.bal [hunk 7]
```diff
@@ -90,6 +90,59 @@ function waitForAllTest() {
...
+    res = wait {producer: Producer1|Producer2, consumer: Consumer1|Consumer2};
+}
+
+function waitActionWithInvalidType() {
+    worker Producer1 returns boolean|error {
+        return true;
+    }
+
+    worker Consumer1 returns boolean {
+        int i = <- Producer;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-actions-negative.bal:134]: This isn't valid code, right? If L141 onward weren't there, this will still result in an error. Shall we fix/simplify?

**Comment by KavinduZoysa** [comment]
@SasinduDilshara, let's resolve the conflicts

File: tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-actions-negative.bal [hunk 8]
```diff
@@ -90,6 +90,50 @@ function waitForAllTest() {
...
+
+    worker Consumer1 returns boolean {
+        return false;
+    }
+
+    worker Consumer2 returns boolean {
+        return false;
+    }
+
+    WaitResult res = wait {producer: Producer1|Producer2, consumer: Consumer1};
```
Comment (KavinduZoysa) [inline tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-actions-negative.bal:115]: If we introduce `&` here(Producer1&Producer2), it gives compile time error as shown below. I think both cases should give the same error, either the current error or the new error introduced in this PR. @MaryamZi WDYT?

`operator '&' not defined for 'future<(boolean|error)>' and 'future<(boolean|error)>'`

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-actions-negative.bal:115]: `Producer1|Producer2` is a special case because it is similar to the alternate wait action (https://ballerina.io/spec/lang/master/#section_7.7.3), which is why that is special-cased.

**Comment by SasinduDilshara** [comment]
> @SasinduDilshara, let's resolve the conflicts

resolved

**Comment by pcnfernando** [comment]
@SasinduDilshara Please resolve the conflicts

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 9]
```diff
@@ -799,7 +799,13 @@ public enum DiagnosticErrorCode implements DiagnosticCode {
     EMPTY_REGEXP_STRING_DISALLOWED(
             "BCS4044", "empty.regexp.string.disallowed"),
     UNSUPPORTED_EMPTY_CHARACTER_CLASS(
-            "BCS4045", "unsupported.empty.character.class")
+            "BCS4045", "unsupported.empty.character.class"),
+    INCOMPATIBLE_QUERY_CONSTRUCT_TYPE("BCE4046", "invalid.error.query.construct.type"),
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:803]: Why do we need these changes here?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 10]
```diff
@@ -4677,7 +4677,13 @@ private void checkTypesForRecords(BLangWaitForAllExpr waitExpr, AnalyzerData dat
 
         for (BLangWaitForAllExpr.BLangWaitKeyValue keyVal : rhsFields) {
             String key = keyVal.key.value;
-            if (!lhsFields.containsKey(key)) {
+            BLangExpression valueExpr = keyVal.valueExpr;
+            if (valueExpr != null && valueExpr.getKind() == NodeKind.BINARY_EXPR
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4681]: Can the valueexpr be nested inside a grouped-expr?

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java (hunk 9 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java]: Updated. be5c24b99d52094b2e79940c0395b2e0732d401e

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 10 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4696]: According to the spec, https://ballerina.io/spec/lang/master/#section_7.7.2
It can be.
Will update the PR with necessary changes

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated. 8e11173274edb73476af9ec35407f2553d8a3c89

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 11]
```diff
@@ -798,18 +798,22 @@ public enum DiagnosticErrorCode implements DiagnosticCode {
             "BCE4042", "worker.send.action.not.allowed.in.lock.statement"),
     WORKER_RECEIVE_ACTION_NOT_ALLOWED_IN_LOCK_STATEMENT(
             "BCE4043", "worker.receive.action.not.allowed.in.lock.statement"),
-    EMPTY_REGEXP_STRING_DISALLOWED("BCE4044", "empty.regexp.string.disallowed"),
-    UNSUPPORTED_EMPTY_CHARACTER_CLASS("BCE4045", "unsupported.empty.character.class"),
+    EMPTY_REGEXP_STRING_DISALLOWED(
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:801]: I don't see a requirement bring these short errors into a new line

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 12]
```diff
@@ -4717,6 +4722,17 @@ private void checkTypesForRecords(BLangWaitForAllExpr waitExpr, AnalyzerData dat
         }
     }
 
+    private boolean checkBinaryBitwiseOperations(BLangExpression valueExpr) {
+        if (valueExpr.getKind() == NodeKind.BINARY_EXPR
+                && ((BLangBinaryExpr) valueExpr).opKind == OperatorKind.BITWISE_OR) {
+            return true;
+        }
+        if (valueExpr.getKind() == NodeKind.GROUP_EXPR) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4730]: Shall we bring this to the top so nested expression check will be done first

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java (hunk 11 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java]: Updated. 893363cdd2b81d5e911d9169b575eeef3c0ac6ce

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 12 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated. 893363cdd2b81d5e911d9169b575eeef3c0ac6ce

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 13]
```diff
@@ -4717,6 +4722,17 @@ private void checkTypesForRecords(BLangWaitForAllExpr waitExpr, AnalyzerData dat
         }
     }
 
+    private boolean checkBinaryBitwiseOperations(BLangExpression valueExpr) {
```
Comment (LakshanWeerasinghe) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4725]:
```suggestion
    private boolean isBinaryBitwiseOperatorExpr(BLangExpression valueExpr) {
```
Shall we change the method signature in this way since it returns a boolean.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated. 3fca4a007e04efc7f97e82ca8c73f38adca29def

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 14]
```diff
@@ -798,18 +798,20 @@ public enum DiagnosticErrorCode implements DiagnosticCode {
             "BCE4042", "worker.send.action.not.allowed.in.lock.statement"),
     WORKER_RECEIVE_ACTION_NOT_ALLOWED_IN_LOCK_STATEMENT(
             "BCE4043", "worker.receive.action.not.allowed.in.lock.statement"),
-    EMPTY_REGEXP_STRING_DISALLOWED("BCE4044", "empty.regexp.string.disallowed"),
-    UNSUPPORTED_EMPTY_CHARACTER_CLASS("BCE4045", "unsupported.empty.character.class"),
+    EMPTY_REGEXP_STRING_DISALLOWED("BCS4044", "empty.regexp.string.disallowed"),
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:801]: Seems error codes has been mistakenly updated for BCE to BCS

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 15]
```diff
@@ -4717,6 +4722,17 @@ private void checkTypesForRecords(BLangWaitForAllExpr waitExpr, AnalyzerData dat
         }
     }
 
+    private boolean isBinaryBitwiseOperatorExpr(BLangExpression valueExpr) {
+        if (valueExpr.getKind() == NodeKind.GROUP_EXPR) {
+            return isBinaryBitwiseOperatorExpr(((BLangGroupExpr) valueExpr).expression);
+        }
+        if (valueExpr.getKind() == NodeKind.BINARY_EXPR
```
Comment (LakshanWeerasinghe) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4729]: I would move the termination condition for top.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4729]: Refer to https://github.com/ballerina-platform/ballerina-lang/pull/37832#discussion_r1257730501

**Review by LakshanWeerasinghe — APPROVED** [review]
