### PR TITLE
Set attached functions to the `BObjectTypeSymbol` in bir symbol enter

### LINKED ISSUE #37306: Readonly Service Object doesn't Validate at Compile time
**Description:**
Consider the following record:
```ballerina
public type GraphqlServiceConfig record {|
    readonly readonly & Interceptor[] interceptors = [];
|};

public type Interceptor distinct service object {
    isolated remote function execute(Context context, Field 'field) returns anydata|error;
};
```
GraphQL module uses a similar record as the GraphQL ServiceConfig. But, when passing an invalid value into `interceptors` field, It's not validated at the compile time. Consider the following GraphQL service.

```ballerina
readonly service class PersonInterceptor {
}

@graphql:ServiceConfig {
    interceptors: [new PersonInterceptor()]
}
service /graphql on new graphql:Listener(9000) {
    isolated resource function get name() returns string {
        return "Ballerina";
    }
}
```
Since `PersonInterceptor` is an invalid value, ideally this should be invalidated at compile time. But currently, it returns the following error at runtime.
```shell
Compiling source
        interceptors_with_records.bal

Running executable

error: {ballerina/lang.array}InherentTypeViolation {"message":"incompatible types: expected '(graphql:Interceptor & readonly)', found 'PersonInterceptor'"}
        at interceptors_with_records:$annot_func$_0(interceptors_with_records.bal:12)
```

**Affected Versions:**
`2201.2.0`

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fixes #37306

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/RecordInBalaTest.java [hunk 1]
```diff
@@ -45,6 +47,16 @@ public void testRestFieldTypeDefAfterRecordDef() {
         BRunUtil.invoke(result, "testCRRestFieldInCR");
     }
 
+    @Test
+    public void negativeTests() {
+        CompileResult result = BCompileUtil.compile("test-src/record/record_negative_bala.bal");
+        Assert.assertEquals(result.getErrorCount(), 2);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/RecordInBalaTest.java:53]: Let's use a variable for the error index and assert at the end against the error count instead.

File: tests/jballerina-unit-test/src/test/resources/test-src/record/record_negative_bala.bal [hunk 2]
```diff
@@ -0,0 +1,11 @@
+import testorg/foo.records;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/record_negative_bala.bal:1]: Need to add the licence header.

**Review by MaryamZi — COMMENTED** [review]
We need a PR for the update 2 stage branch.

**Comment by chiranSachintha** [comment]
> We need a PR for the update 2 stage branch.

https://github.com/ballerina-platform/ballerina-lang/pull/37339

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java [hunk 3]
```diff
@@ -1752,9 +1752,9 @@ private void populateIntersectionTypeReferencedFunctions(DataInputStream inputSt
             String attachedFuncName = getStringCPEntryValue(inputStream);
             String attachedFuncOrigName = getStringCPEntryValue(inputStream);
             var attachedFuncFlags = inputStream.readLong();
+            BInvokableType attachedFuncType = (BInvokableType) readTypeFromCp();
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:1755]: What's this change about? We anyway use the read function only within the if check

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:1755]: Do we need to skip some part of the byte stream for some cases?

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:1755]: In BIRTypeWriter we didn't use such kind of logic(check whether symbol contains `interface` or `attached` flags).
https://github.com/ballerina-platform/ballerina-lang/blob/05522577aeae55e6974938886ee10842c1f4ade1/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java#L446

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java [hunk 4]
```diff
@@ -1619,11 +1619,12 @@ public BType readType(int cpI) throws IOException {
                         ignoreAttachedFunc();
                     }
                     int funcCount = inputStream.readInt();
-                    for (int i = 0; i < funcCount; i++) {
-                        //populate intersection type object functions
-                        if (isImmutable(objectSymbol.flags) && Symbols.isFlagOn(flags, Flags.ANONYMOUS)) {
+                    if (isImmutable(objectSymbol.flags)) {
+                        for (int i = 0; i < funcCount; i++) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:1623]: Redundant loop here. Assuming the change was to avoid multiple flag checks; move the flag check to a var instead and use it in the if/else

**Review by pcnfernando — DISMISSED** [review]
LGTM

**Review by pcnfernando — APPROVED** [review]
