### PR TITLE
[IntelliJ Plugin] Add fix for debugger breakpoints

### LINKED ISSUE #10584: Issue in setting debug points
**Description:**

Cannot set debug points if the line contains a comment.

```ballerina
public function main(string ... args) {
    io:println(reflect:equals(x, y));   //returns TRUE
}
```

### PR DESCRIPTION
**Pull request by NipunaRanasinghe**
## Purpose
Fixes #10584.

### CODE REVIEW

File: tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/debugger/breakpoint/BallerinaBreakPointType.java [hunk 1]
```diff
@@ -63,6 +62,13 @@ private static boolean isLineBreakpointAvailable(@NotNull VirtualFile file, int
         }
         Checker canPutAtChecker = new Checker();
         XDebuggerUtil.getInstance().iterateLine(project, document, line, canPutAtChecker);
+
+        // Used to identify line comments, which cannot be correctly processed by the checker.
+        if (document.getText(new TextRange(document.getLineStartOffset(line), document.getLineEndOffset(line)))
```
Comment (Shan1024) [inline tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/debugger/breakpoint/BallerinaBreakPointType.java]: I think this will not match if the comment has leading spaces.

Eg -

```ballerina
    // some comment
```

Comment (NipunaRanasinghe) [reply tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/debugger/breakpoint/BallerinaBreakPointType.java]: Fixed it by trimming whitespaces before the check.
