### PR TITLE
Fix CSV reading with double quoted values

### LINKED ISSUE #19819: [CSV] Quotes should be omitted when reading
**Description:**
Currently, when reading composite CSV records i.e "foo,1986","CC24" the composite fields return "foo,1986" with the quotes included.

Ideally, this should be transparent to the caller.

**Steps to reproduce:**
Read from CSV file with quoted values.

**Affected Versions:**
1.0.0-1.0.3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by wggihan**
## Purpose
Fixes #19819

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: stdlib/io/src/main/java/org/ballerinalang/stdlib/io/channels/base/DelimitedRecordChannel.java [hunk 1]
```diff
@@ -304,8 +306,13 @@ private String processIdentifiedRecord(String[] delimitedRecords) {
         Pattern reg = Pattern.compile(regex);
         String[] split = reg.split(record);
         for (int i = 0; i < split.length; i++) {
-            if (split[i].isEmpty()) {
+            String filed = split[i];
```
Comment (ldclakmal) [inline stdlib/io/src/main/java/org/ballerinalang/stdlib/io/channels/base/DelimitedRecordChannel.java]:
```suggestion
            String field = split[i];
```

File: stdlib/io/src/main/java/org/ballerinalang/stdlib/io/channels/base/DelimitedRecordChannel.java [hunk 2]
```diff
@@ -304,8 +306,13 @@ private String processIdentifiedRecord(String[] delimitedRecords) {
...
+            if (filed.isEmpty()) {
                 split[i] = null;
+                continue;
+            }
+            if (filed.matches(DOUBLE_QUOTE_REGEX)) {
+                split[i] = filed.substring(filed.indexOf('\"') + 1, filed.lastIndexOf('\"'));
             }
```
Comment (ldclakmal) [inline stdlib/io/src/main/java/org/ballerinalang/stdlib/io/channels/base/DelimitedRecordChannel.java]:
```
            String field = split[i];
            if (field.isEmpty()) {
                split[i] = null;
                continue;
            }
            if (field.matches(DOUBLE_QUOTE_REGEX)) {
                split[i] = field.substring(field.indexOf('\"') + 1, field.lastIndexOf('\"'));
            }
```
