### PR TITLE
Fix unreachability with `while-stmt` not completed normally

### LINKED ISSUE #33725: Unnecessarily expect an explicit return
Following gives `this function should explicitly return a value` warning when it shouldn't.

```ballerina
const SOME_CONST = ...;

function f() returns boolean? {
    int i = 0;
    while true {
        if i == SOME_CONST {
            return false;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by lasinicl**
## Purpose
$titlle

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/33730
Fixes #33725

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java [hunk 1]
```diff
@@ -357,6 +357,8 @@ public void visit(BLangForkJoin forkJoin) {
 
     @Override
     public void visit(BLangMatchStatement matchStatement) {
+        checkStatementExecutionValidity(matchStatement);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:360]: Shall we add another match test too (other than the change in the existing test)?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java [hunk 2]
```diff
@@ -582,6 +584,8 @@ public void visit(BLangWhile whileNode) {
             this.statementReturnsPanicsOrFails = prevStatementReturnsPanicsOrFails;
             this.continueAsLastStatement = prevContinueAsLastStatement;
             this.breakAsLastStatement = prevBreakAsLastStatement;
+        } else {
+            this.statementReturnsPanicsOrFails = true;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:588]: Not related to this PR, but what do we mean by "Fails" here?

Comment (lasinicl) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:588]: when there's a `fail-stmt`

**Review by MaryamZi — APPROVED** [review]
