### PR TITLE
Send worker changes to master

### LINKED ISSUE #41699: [New Feature]: Add parsing support for new worker related syntax
### Description

$subject.

New Syntax:
- named-worker-decl := [annots] [transactional-qual] worker worker-name return-type-descriptor statement-block **[on-fail-clause]**
- receive-action := single-receive-action | multiple-receive-action | **alternate-receive-action**
- **alternate-receive-action := <- peer-worker ( | peer-worker)***

### LINKED ISSUE #41953: [Improvement]: Improve error message when there is a mismatch in worker send and recevie pairing
### Description

$subject.

```bal
function foo() {
    boolean foo = true;

    worker w1 {
        20 -> w2;
    }

    worker w2 {
    }

}
```

This above code gives,
```
ERROR [test_parser.bal:(21:15,23:6)] worker send/receive interactions are invalid; worker(s) cannot move onwards from the state: '[20 -> w2, FINISHED, FINISHED]'
```

We need to give a meaningful error message.

### LINKED ISSUE #41968: [Bug]: Add `error:NoMessage` only if it is there in the all the receive types in `alternative-receive-action`
### Description

$subject.

Consider the below code,

```bal
function foobar() {
    boolean foo = true;

    worker w1 {
        if foo {
            10 -> w2;
        }
        20 -> w2;
    }

    worker w2 {
        int|error:NoMessage a = <- w1 | w1; // We should not enforce the `error:NoMessage` here.
    }

    _ = wait {a: w1, b: w2};
}
```

### LINKED ISSUE #42004: [Task]: Add tests for worker related changes to fix the all uncovered lines
### Description

$subject.

### Describe your task(s)

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject. This PR adds support for the following features,
- Alternate receive action support
- Multiple receive action support
- Conditional send support
- Named workers with on-fail-clause support

Fixes #41699 Fixes #41953 Fixes #41968 Fixes #42004

This PR includes collective changes from the subsequent PRs.
- #41683
- #41767
- #41741
- #41754
- #41791
- #41797
- #41913
- #41939
- #41880
- #41922
- #41925
- #41944
- #41999
- #42050
- #42084
- #41857

## Approach
n/a

## Samples
n/a

## Remarks
Sequence diagram behavior: https://github.com/ballerina-platform/ballerina-lang/issues/42151#issuecomment-1975830280

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java [hunk 1]
```diff
@@ -28,11 +41,14 @@
...
+    private final List<ErrorValue> errors = new ArrayList<>();
 
-    //TODO try to generalize this to a normal data channel, in that case we won't need these classes.
-    public WDChannels() {
+    // A worker receive field for multiple receive action.
+    public record ReceiveField(String fieldName, String channelName) {
     }
 
+    //TODO try to generalize this to a normal data channel, in that case we won't need these classes.
+
```
Comment (SasinduDilshara) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java:51]:
```suggestion
```

File: docs/bir-spec/src/main/resources/kaitai/bir.ksy [hunk 2]
```diff
@@ -1216,6 +1216,8 @@ types:
             'instruction_kind_enum::instruction_kind_new_re_flag_on_off': instruction_new_re_flag_on_off
             'instruction_kind_enum::instruction_kind_new_re_quantifier': instruction_new_re_quantifier
             'instruction_kind_enum::instruction_kind_record_default_fp_load': instruction_record_default_fp_load
+            'instruction_kind_enum::instruction_kind_wk_alt_receive': instruction_wk_alt_receive
```
Comment (lochana-chathura) [inline docs/bir-spec/src/main/resources/kaitai/bir.ksy:1219]: @HindujaB We need to bump the bir version with these change right?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java [hunk 3]
```diff
@@ -44,4 +59,117 @@ public synchronized WorkerDataChannel getWorkerDataChannel(String name) {
...
+            WorkerDataChannel channel = getWorkerDataChannel(field.channelName());
+            if (!channel.isClosed()) {
+                Object result = channel.tryTakeData(strand, true);
+                checkAndPopulateResult(strand, field, result, channel);
+            } else {
+                if (channel.getState() == WorkerDataChannel.State.AUTO_CLOSED) {
+                    checkAndPopulateResult(strand, field, ErrorUtils.createNoMessageError(field.channelName()),
+                            channel);
+                }
+            }
```
Comment (lochana-chathura) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java:78]: HBT? can avoid the nested if and duplicate lines.
```suggestion
            WorkerDataChannel.State state = channel.getState();

            Object result = null;
            if (state == WorkerDataChannel.State.OPEN) {
                result = channel.tryTakeData(strand, true);
            } else if (state == WorkerDataChannel.State.AUTO_CLOSED) {
                result = ErrorUtils.createNoMessageError(field.channelName());
            }

            if (result != null) {
                checkAndPopulateResult(strand, field, result, channel);
            }
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java [hunk 4]
```diff
@@ -44,4 +59,117 @@ public synchronized WorkerDataChannel getWorkerDataChannel(String name) {
...
+        }
+        return clearResultCache(strand, receiveFields);
+    }
+
+    private void checkAndPopulateResult(Strand strand, ReceiveField field, Object result, WorkerDataChannel channel) {
+        if (result != null) {
```
Comment (lochana-chathura) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java:84]: can invert the condition and exit early. this would make code more readable by reducing the level of indentation

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java [hunk 5]
```diff
@@ -44,4 +59,117 @@ public synchronized WorkerDataChannel getWorkerDataChannel(String name) {
...
+            if (!channel.isClosed()) {
+                allChannelsClosed = false;
+                result = channel.tryTakeData(strand, true);
+                if (result != null) {
+                    result = handleNonNullResult(channels, result, channel);
+                }
+            } else {
+                if (channel.getState() == WorkerDataChannel.State.AUTO_CLOSED) {
+                    errors.add((ErrorValue) ErrorUtils.createNoMessageError(channelName));
+                }
```
Comment (lochana-chathura) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java:119]:
```suggestion
            if (state == WorkerDataChannel.State.OPEN) {
                allChannelsClosed = false;
                result = channel.tryTakeData(strand, true);
                if (result != null) {
                    result = handleNonNullResult(channels, result, channel);
                }
            } else if (state == WorkerDataChannel.State.AUTO_CLOSED) {
                errors.add((ErrorValue) ErrorUtils.createNoMessageError(channelName));
            }
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java [hunk 6]
```diff
@@ -44,4 +59,117 @@ public synchronized WorkerDataChannel getWorkerDataChannel(String name) {
...
+            WorkerDataChannel channel = getWorkerDataChannel(channelName);
+            channel.close();
+            channel.setRemovable();
+        }
+    }
+
+    public synchronized void removeCompletedChannels(Strand strand, String channelName) {
+        if (this.wDChannels != null) {
+            WorkerDataChannel channel = this.wDChannels.get(channelName);
+            if (channel != null && (channel.callCount == 2 || channel.isRemovable)) {
```
Comment (LakshanWeerasinghe) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java:168]: why do we specifically check for call count 2?

Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java:168]: We keep an integer variable to check for the completion of the send and receive action (for both positive and negative completions) to verify that the message passing is completed. So that, we can remove that channel from the cache. I will slightly change the implementation to rely only on `callCount` and remove the `isRemovable` variable.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java (hunk 3 above)
Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java:78]: We can't depend on the `result != null` for handling the result because the strand yielding is managed based on it inside the `checkAndPopulateResult` method. I can still refactor it like this.
```suggestion
            WorkerDataChannel.State state = channel.getState();
            Object result = null;
            switch (state) {
                case OPEN:
                    result = channel.tryTakeData(strand, true);
                    break;
                case CLOSED:
                    continue;
                case AUTO_CLOSED:
                    result = ErrorUtils.createNoMessageError(field.channelName());
                    break;
            }
            checkAndPopulateResult(strand, field, result, channel);
```

Comment (lochana-chathura) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/WDChannels.java:78]: ah yes. +1 on your suggestion.

**Review by HindujaB — APPROVED** [review]
LGTM
