### PR TITLE
Fix rest parameter types of record binding patterns

### LINKED ISSUE #13459: [Spec Deviation] Record Typed Binding Pattern should work with a single rest parameter
**Description:**
A record typed binding pattern should work with a single rest parameter as shown below:
```ballerina
BindingPattern { ...restParam } = getRecord();
```

### PR DESCRIPTION
**Pull request by Anoukh**
## Purpose
This PR fixes the following
1. Closes #13459 
2. The type of the rest parameter in record binding pattern will be set as `map<anydata>` or `map<any>` depending on the the context

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 1]
```diff
@@ -1208,19 +1214,33 @@ private void checkRecordVarRefEquivalency(DiagnosticPos pos, BLangRecordVarRef l
...
+                    rhsField.type, variableReference.type, DiagnosticCode.INCOMPATIBLE_TYPES);
+        }
+
+        if (lhsVarRef.restParam != null) {
+            boolean hasAnyTypeField = rhsRecordType.fields.stream()
+                    .map(field -> field.type)
+                    .anyMatch(fieldType -> !types.isAnydata(fieldType));
+            types.checkType(((BLangSimpleVarRef) lhsVarRef.restParam).pos, new BMapType(TypeTags.MAP, hasAnyTypeField ?
+                            symTable.anyType : types.isAnydata(rhsRecordType.restFieldType) ?
+                            symTable.anydataType : symTable.anyType, null),
```
Comment (Kishanthan) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: Shall we move this filter logic to a method for better readability ?

Comment (Anoukh) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: Addressed in 417c6e1

**Comment by Kishanthan** [comment]
LGTM, lets merge once build passes
