### PR TITLE
Restrict `never` type usage

### LINKED ISSUE #29057: Compiler crashes for foreach statement with empty closed record
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Foo record{|
|};

public function main() {
    Foo f = {
    };
    foreach var x in f {
    }
}
```
```
[2021-03-08 16:32:14,827] SEVERE {b7a.log.crash} - null 
java.util.NoSuchElementException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.inferRecordFieldType(Types.java:1905)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.setForeachTypedBindingPatternType(Types.java:1547)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2855)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForeach.accept(BLangForeach.java:105)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3218)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3186)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:3182)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:443)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3218)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:415)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3218)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3186)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3178)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:310)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:275)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:217)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:115)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:374)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:141)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:127)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:103)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:129)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:102)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:257)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
 
```

### LINKED ISSUE #29165: Restrict Never type usage
Incorporate latest changes in https://github.com/ballerina-platform/ballerina-spec/issues/510

### PR DESCRIPTION
**Pull request by lasinicl**
Fixes #29165
Fixes #29057

## Approach
Copied from the original spec issue
```
1. Kinds of expression permitted to be `never` are:
- function call
- method call (but not client remote method call)

2. Context where expression of type `never` is permitted:
- call-stmt
- start-action
- trap-expr

3. never disallowed as type-descriptor as follows:
- parameters: required-param and defaultable-param
- local variable declaration without initializer
- module variable declaration without initializer
- module const declaration
- typed-binding-pattern (includes variables with initializers)

4. Not to disallow `never` as a required member. If you have a structure type with a required never member, that structure type will be equivalent to `never`.

5. In typed binding patterns - prohibition on variables having type `never` to apply only in the single use case

6. For `map<never>` (or `xml<never>` or `[]`)

- the return type of the iterator is `record {| never value; |}?` which is equivalent to `never?`, which is `never|()`, which is `()`
- this means the iterator is known at compile time to iterate zero times
- the inferred type of the variable is `never`, but the no value is ever bound to the typed-binding-pattern
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by KRVPerera** [comment]
Did we look at trap-expr
```Ballerina
function bye() returns never {
   panic error("bye, bye");
}

public function main() returns error? {
   error err = trap bye();
   return err;
}
```
This should be allowed right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 1]
```diff
@@ -222,6 +222,9 @@
     private static final String DEPRECATION_ANNOTATION = "deprecated";
     private static final String ANONYMOUS_RECORD_NAME = "anonymous-record";
 
+    private boolean simpleVarInIterativeUse;
+    private boolean simpleVarInFunctionParam;
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:226]: Instead of a SymbolEnter level state variable better to use a flag. Better to move the logic to type checker to a place we analyze function parameters?

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 2]
```diff
@@ -381,8 +381,9 @@
 
     OPERATOR_NOT_SUPPORTED("BCE2642", "operator.not.supported"),
     OPERATOR_NOT_ALLOWED_VARIABLE("BCE2643", "operator.not.allowed.variable"),
-    NEVER_TYPE_NOT_ALLOWED_FOR_REQUIRED_FIELDS("BCE2644", "never.type.not.allowed.for.required.fields"),
-    INVALID_NEVER_RETURN_TYPED_FUNCTION_INVOCATION("BCE2645", "invalid.never.return.typed.function.invocation"),
+    NEVER_TYPE_NOT_ALLOWED_FOR_REQUIRED_DEFAULTABLE_PARAMS("BCE2644",
+            "never.type.not.allowed.for.required.and.defaultable.params"),
+    INVALID_NEVER_RETURN_TYPED_CLIENT_REMOTE_FUNCTION("BCE2645", "invalid.never.return.typed.client.remote.function"),
```
[the remark this answers is not in the document]
Comment (lasinicl) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:385]: Added in https://github.com/ballerina-platform/ballerina-lang/pull/29361/files#diff-734d51a0e3f42dea4afbd4743936669f55eae97e5f97dd2871cae4c7d7a78b5dR342

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -5392,7 +5396,13 @@ private BSymbol getLangLibMethod(BLangInvocation iExpr, BType bType) {
 
     private void checkInvocationParamAndReturnType(BLangInvocation iExpr) {
         BType actualType = checkInvocationParam(iExpr);
-        resultType = types.checkType(iExpr, actualType, this.expType);
+        // iExpr contain NEVER_ALLOWED flag if it's in a trap expression
+        if (iExpr.flagSet != null && iExpr.flagSet.contains(Flag.NEVER_ALLOWED) &&
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5400]: IMO, the better approach would be to type check the invocation expression as a normal expression and then do the never validation in the relevant parent expressions/statements. If we can sort out the foreach/from usage we can get rid of the flag too.

File: langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachRecordTypedBindingPatternsTests.java [hunk 4]
```diff
@@ -87,4 +87,11 @@ public void testEmptyRecordIteration() {
         Assert.assertEquals(returns.length, 1);
         Assert.assertEquals(returns[0].stringValue(), "");
     }
+
+    @Test
+    public void testForeachWithClosedRecordWithNoFields() {
+        BValue[] returns = BRunUtil.invoke(program, "testForeachWithClosedRecordWithNoFields");
+        Assert.assertEquals(returns.length, 1);
+        Assert.assertEquals(returns[0].stringValue(), "ABC");
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachRecordTypedBindingPatternsTests.java:95]: Can do this validation in b7a itself?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java [hunk 5]
```diff
@@ -144,21 +144,135 @@ public void testNeverTypeNegative() {
...
+                "cannot be of type 'never' or equivalent to type 'never'", 186, 16);
+        BAssertUtil.validateError(negativeCompileResult, i++, "a required parameter or a defaultable parameter " +
+                "cannot be of type 'never' or equivalent to type 'never'", 189, 25);
+        BAssertUtil.validateError(negativeCompileResult, i++, "The return type of a remote method of a " +
+                "client object cannot be of type 'never'", 193, 47);
+        BAssertUtil.validateError(negativeCompileResult, i, "cannot define a variable of type 'never' " +
+                "or equivalent to type 'never'", 200, 5);
+    }
+
+    @Test(expectedExceptions = BLangRuntimeException.class,
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/never/NeverTypeTest.java:188]: These assertions can also be done in b7a using trap.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal [hunk 6]
```diff
@@ -142,3 +127,241 @@ function testNeverAsFutureTypeParam() {
...
+    assertEquality(0, y.length());
+}
+
+type RestRecord record {|
+    string someName;
+    never...;
+|};
+
+function testNeverWithRestParamsAndFields() {
+    RestRecord x = {someName:"ABC"};
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal:334]:
```suggestion
    RestRecord x = {someName: "ABC"};
```

File: tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal [hunk 7]
```diff
@@ -142,3 +127,241 @@ function testNeverAsFutureTypeParam() {
...
+type NeverTable table<map<never>>;
+
+function testNeverWithIterator5() {
+    NeverTable x = table [
+    ];
+    record {| map<never> value; |}? y = x.iterator().next();
+    assertEquality((), y);
+}
+
+type Bunny record{|
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal:201]:
```suggestion
type Bunny record {|
```

File: tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal [hunk 8]
```diff
@@ -142,3 +127,241 @@ function testNeverAsFutureTypeParam() {
...
+}
+
+function testNeverWithTrapExpr() returns error? {
+    error err = trap foo();
+    return err;
+}
+
+function testNeverWithMethodCallExpr() {
+    Bar bar = new (12);
+    _ = bar.barFunc();
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/never/never-type.bal:147]: Shall we test trap and start for a method call too?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 9]
```diff
@@ -550,6 +550,12 @@ private void analyzeClassDefinition(BLangClassDefinition classDefinition) {
 
         // Visit functions as they are not in the same scope/env as the object fields
         for (BLangFunction function : classDefinition.functions) {
+            if (classDefinition.flagSet.contains(Flag.CLIENT) && function.flagSet.contains(Flag.REMOTE) &&
+                    function.returnTypeNode != null &&
+                    types.isNeverTypeOrStructureTypeWithARequiredNeverMember(function.returnTypeNode.type)) {
+                dlog.error(function.returnTypeNode.pos,
+                        DiagnosticErrorCode.INVALID_NEVER_RETURN_TYPED_CLIENT_REMOTE_FUNCTION);
```
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:557]: As discussed offline, please send a separate PR for this.

**Review by MaryamZi — APPROVED** [review]

**Comment by lasinicl** [comment]
Created https://github.com/ballerina-platform/ballerina-lang/issues/29663 to address the suggested changes
