### PR TITLE
Fix incorrect behaviour of xml:setName 

### LINKED ISSUE #30983: Incorrect behavior of xml:setName method
**Description:**
Consider below shell output
```

=$ 'xml:Element x = xml `<e/>`                                                                                                                                         took 0 ms

=$ x.setName("{http://www.ballerina-schema.io/schema}Elem")                                                                                                          took 557 ms

=$ x                                                                                                                                                                 took 191 ms
xml`<Ele xmlns="{http://www.ballerina-schema.io/schema"/>`
```
Notice that curly brace in the namespace, and last letter is missing in the local name.
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by rpjayasekara**
Fixes #30983

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java [hunk 1]
```diff
@@ -141,6 +141,7 @@ public void testGetNameOfElement() {
     public void testSetElementName() {
         BValue[] returns = BRunUtil.invoke(compileResult, "testSetElementName");
         assertEquals(((BXML) returns[0]).stringValue(), "<el2 attr=\"attr1\">content</el2>");
+        assertEquals(((BXML) returns[1]).stringValue(), "<Elem xmlns=\"{http://www.ballerina-schema.io/schema}\"/>");
```
Comment (rdhananjaya) [inline langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibXMLTest.java:144]: This shold be `<Elem xmlns="http://www.ballerina-schema.io/schema" />`

**Review by rdhananjaya — CHANGES_REQUESTED** [review]

**Review by rdhananjaya — APPROVED** [review]

**Review by rdhananjaya — APPROVED** [review]
