### PR TITLE
Fix compiler crash in regex with back-tick

### LINKED ISSUE #39395: [Bug]: Compiler crash in regex
### Description

Following code crash the Ballerina Compiler

```
public function main() {
  string:RegExp x1 = re `[AB\p{gc=Lu}]+`?`;
}
```

```
Compiling source
       test.bal
ballerina: Oh no, something really went wrong. Bad. Sad.


We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.


We thank you for helping make us better.


[2023-01-26 10:43:56,719] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
       at io.ballerina.compiler.internal.parser.utils.ConditionalExprResolver.getQualifiedNameRefNode(ConditionalExprResolver.java:55)

```

### Steps to Reproduce

_No response_

### Affected Version(s)

Master

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by SasinduDilshara**
Fixes #39395 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/utils/ConditionalExprResolver.java [hunk 1]
```diff
@@ -52,15 +52,15 @@ private ConditionalExprResolver() {
     }
 
     public static STNode getQualifiedNameRefNode(STNode parentNode, boolean leftMost) {
+        if (parentNode == null || (parentNode.kind == SyntaxKind.LIST && ((STNodeList) parentNode).isEmpty())) {
```
Comment (LakshanWeerasinghe) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/utils/ConditionalExprResolver.java:55]:
```suggestion
        if (parentNode == null || parentNode.kind == SyntaxKind.LIST && ((STNodeList) parentNode).isEmpty()) {
```

File: compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_44.bal [hunk 2]
```diff
@@ -0,0 +1,3 @@
+function foo() {
+    string:RegExp x1 = re `[AB\p{gc=Lu}]+` ? `;
```
Comment (LakshanWeerasinghe) [inline compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_44.bal:2]:
```suggestion
    _ = re `[AB\p{gc=Lu}]+` ? `;
```

File: compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_45.bal [hunk 3]
```diff
@@ -0,0 +1,3 @@
+function foo() {
+    string:RegExp x1 = re `[AB\p{gc=Lu}]+` ? `aa` ? `;
```
Comment (LakshanWeerasinghe) [inline compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_45.bal:2]:
```suggestion
    _ = re `[AB\p{gc=Lu}]+` ? `aa` ? `;
```

File: tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_negative_test.bal [hunk 4]
```diff
@@ -26,4 +26,5 @@ function testRegExpNegative() {
     var _ = re `(?s-ism:A)`;
     var _ = re `(?s-ism:[z-a]{5,2})`;
     var _ = re `[z-a]A{4,2}[a-bf-F]{1,}(?im-ms:[c-a](?ixmx:[z-a](?ixm-xs:[r-m])))`;
+    string:RegExp _ = re `[AB\p{gc=Lu}]+` ? `;
```
Comment (LakshanWeerasinghe) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_negative_test.bal:29]:
```suggestion
    _ = re `[AB\p{gc=Lu}]+` ? `;
```

Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_negative_test.bal:29]: Will update

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/utils/ConditionalExprResolver.java (hunk 1 above)
Comment (SasinduDilshara) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/utils/ConditionalExprResolver.java:55]: Will update

File: compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_44.bal (hunk 2 above)
Comment (SasinduDilshara) [reply compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_44.bal:2]: I think for the parser tests it is ok to keep this like this.
Because we want the context of the code to check the recovery.

File: compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_45.bal (hunk 3 above)
Comment (SasinduDilshara) [reply compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_45.bal:2]: https://github.com/ballerina-platform/ballerina-lang/pull/39517#discussion_r1098169658

File: compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_44.bal (hunk 2 above)
Comment (LakshanWeerasinghe) [reply compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_44.bal:2]: we can get the context from the expression. @pcnfernando what would be the better approach?

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/utils/ConditionalExprResolver.java (hunk 1 above)
Comment (SasinduDilshara) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/utils/ConditionalExprResolver.java]: Updated. 3b6ad9fcc5c54d96978a6c09d8cce801793d3adb

File: compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_44.bal (hunk 2 above)
Comment (pcnfernando) [reply compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_44.bal:2]: Yes, the context will be resolved from the expression. Can use `_`

Comment (SasinduDilshara) [reply compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_44.bal]: Updated e6734830a35de2ff3157c33eeb7e784b8706fa40

File: compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_45.bal (hunk 3 above)
Comment (SasinduDilshara) [reply compiler/ballerina-parser/src/test/resources/expressions/regexp-constructor-expr/regexp_constructor_source_45.bal]: Updated e6734830a35de2ff3157c33eeb7e784b8706fa40

File: tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_negative_test.bal (hunk 4 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/regexp/regexp_value_negative_test.bal]: Updated e6734830a35de2ff3157c33eeb7e784b8706fa40

**Review by mohanvive — DISMISSED** [review]

**Comment by SasinduDilshara** [comment]
Conflicts are resolved now.

**Review by mohanvive — APPROVED** [review]
