### PR TITLE
FIx code coverage when the original code is split across multiple source files

### LINKED ISSUE #42754: [Task]:  Analyse the test failures related to coverage from `TestReportTest`
### Description

$subject
https://scans.gradle.com/s/ai6jjdo5giyiu/tests/task/:testerina-integration-test:test/details/org.ballerinalang.testerina.test.TestReportTest?top-execution=1

### Describe your task(s)

_No response_

### Related area

-> Test Framework

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
Fixes #42754

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/ModuleCoverage.java [hunk 1]
```diff
@@ -72,23 +73,29 @@ public boolean containsSourceFile(String fileName) {
     /**
      * Update coverage information for a given source file.
      *
-     * @param document     Document
-     * @param coveredLines List<Integer>
-     * @param missedLines  List<Integer>
-     * @param updatedMissedLineCount  int
+     * @param document               Updated source file
+     * @param coveredLines           latest covered lines
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/ModuleCoverage.java:77]:
```suggestion
     * @param coveredLines           Latest covered lines
```

**Review by Dilhasha — APPROVED** [review]
