### PR TITLE
Remove language server compiler module

### LINKED ISSUE #27212: Remove DocumentManager and LSCompiler from LangServer
**Description:**
Need to remove DocumentManager and LSCompiler and their related classes from language server. WorkspaceManager is the central access point for all related alternative methods. 

Need to verify the removal with the external langserver-extension developers.

**Steps to reproduce:**

**Affected Versions:**
2.0.0-SLP6-SNAPSHOT

### PR DESCRIPTION
**Pull request by nadeeshaan**
Fixes #27212 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/service/spi/ExtendedLanguageServerService.java [hunk 1]
```diff
@@ -35,10 +34,9 @@
     /**
      * Initialize callback for the service.
      *
-     * @param documentManager document manager
-     * @param langServer      language server
+     * @param langServer language server
      */
-    default void init(WorkspaceDocumentManager documentManager, LanguageServer langServer) {
+    default void init(LanguageServer langServer) {
```
Comment (rasika) [inline language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/service/spi/ExtendedLanguageServerService.java:39]: Earlier `WorkspaceDocumentManager` was the access point for the document. Thus, we had this parameter. Since now `WorkspaceManager` is the access point; shall we pass `WorkspaceManager` instead.

**Review by rasika — APPROVED** [review]

File: language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/service/spi/ExtendedLanguageServerService.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/service/spi/ExtendedLanguageServerService.java:39]: Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/27600
