### PR TITLE
Fix XML serialization of namespace prefix of an Element

### LINKED ISSUE #33464: XML serialization of namespace prefix of a element is wrong after attribute map manipulation
**Description:**
```ballerina
import ballerina/io;
import ballerina/lang.'xml;

public function main() returns error? {
    // the createElement should take a second param that is a attribute map, we dont have that at the moment
    // so I'd suggest to get the attribute map from `e` and add stuff into that.
    xml:Element eNs = xml:createElement("{namespace_URL}elem");
    map<string> atMap = eNs.getAttributes();
    // set the namesapce prefix
    atMap["{http://www.w3.org/2000/xmlns/}ns0"] = "namespace_URL";

    // we also need to delete the default namespace entry
    _ = atMap.remove("{http://www.w3.org/2000/xmlns/}xmlns");
    


    io:println(eNs); // this should print `<ns0:elem xmlns:ns0="namespace_URL" />`, 
    io:println(eNs.getAttributes());
    io:println(eNs.getName());

    io:println();

    // using template literal
    xml:Element fromT = xml `<ns0:elem xmlns:ns0="namespace_URL" />`;
    io:println(fromT);
    io:println(fromT.getAttributes());
    io:println(fromT.getName());
}
```

output:
```
<elem xmlns:ns0="namespace_URL"/>
{"{http://www.w3.org/2000/xmlns/}ns0":"namespace_URL"}
{namespace_URL}elem

<ns0:elem xmlns:ns0="namespace_URL"/>
{"{http://www.w3.org/2000/xmlns/}ns0":"namespace_URL"}
{namespace_URL}elem
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by SandaruJayawardana**
Fixes #33464

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlQName.java [hunk 1]
```diff
@@ -81,6 +81,19 @@ public XmlQName(BString localName, BString uri, BString prefix) {
         }
     }
 
+    @Deprecated
+    public XmlQName(String qNameStr, String prefix) {
+        int parenEndIndex = qNameStr.indexOf('}');
```
Comment (rdhananjaya) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlQName.java:86]: 1. I think what we need in the `lastIndexOf('}')`, we need to change in line:63 too.
2. We can just to `this(qNameStr); this.prefix = prefix;` right

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java [hunk 2]
```diff
@@ -459,6 +459,17 @@ public static BXml createXmlValue(BXmlQName startTagName, BString defaultNsUriVa
         return XmlFactory.createXMLElement(startTagName, defaultNsUriVal, readonly);
     }
 
+    /**
+     * Create attribute map with an XML.
```
Comment (rdhananjaya) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java:463]: Is this doc comment correct?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java [hunk 3]
```diff
@@ -258,10 +258,15 @@ private void writeStartElement(QName qName, Map<String, String> nsPrefixMap, Has
             throws XMLStreamException {
         String defaultNamespaceUri = setDefaultNamespace(nsPrefixMap, qName, currentNSLevel);
 
-        if (qName.getPrefix() == null || qName.getPrefix().isEmpty()) {
+        if (qName.getNamespaceURI() == defaultNamespaceUri) {
```
Comment (rdhananjaya) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java:261]:
```suggestion
        if (qName.getNamespaceURI().equals(defaultNamespaceUri)) {
```

File: langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java [hunk 4]
```diff
@@ -38,19 +43,53 @@
...
+    private static final String XML = "xml";
+    private static final String XML_NS_URI_PREFIX = "{" + XMLConstants.XML_NS_URI + "}";
+    private static final String XMLNS_NS_URI_PREFIX = "{" + XMLConstants.XMLNS_ATTRIBUTE_NS_URI + "}";
 
-    public static BXml createElement(BString name, BXml children) {
-        BXmlQName xmlqName = ValueCreator.createXmlQName(name);
+    public static BXml createElement(BString name, BMap<BString, BString> attributes, BXml children) {
+        String prefix = getPrefix(name.getValue(), attributes);
+        BXmlQName xmlqName;
+        if (prefix == "") {
```
Comment (rdhananjaya) [inline langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java:53]: `.equals()`

File: langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java [hunk 5]
```diff
@@ -38,19 +43,53 @@
...
+        }
         String temp = null;
         BXml xmlElement = XmlFactory.createXMLElement(xmlqName, temp);
+        xmlElement.setAttributes(attributes);
         xmlElement.setChildren(getChildren(children));
         return xmlElement;
     }
 
+    private static String getPrefix(String name, BMap<BString, BString> attributes) {
+        int parenEndIndex = name.indexOf('}');
```
Comment (rdhananjaya) [inline langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java:66]: Let's change these to curly bracket and let's use the `lastIndexOf` too.

Comment (SandaruJayawardana) [reply langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java:66]: will update.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlQName.java (hunk 1 above)
Comment (SandaruJayawardana) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlQName.java:86]: Yes. Will update.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java (hunk 2 above)
Comment (SandaruJayawardana) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java:463]: Did you mean something like `Create attribute map with a qualified name string and namespace prefix.`?

Comment (rdhananjaya) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java]: No, why would this create a map? We are just creating an xml qualified name right.

Comment (rdhananjaya) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java]: Am I missing something here?

Comment (SandaruJayawardana) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java]: I took the doc comment from existing overloaded methods of `createXmlQName`. That's why I didn't change this method topic. I will update this. Anyway, do I have to change the others too (e.g. L474) ?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attribute-access-syntax.bal [hunk 6]
```diff
@@ -24,3 +24,23 @@ function usePredefinedXMLNamespace() returns string|error? {
     xml x = xml `<root xmlns="the-url" attr="the attr" xml:space="preserve"></root>`;
     return x.'xml:space;
 }
+
+function testXMLAfterRemoveAttribute() {
+    map<string> attributes = {"{http://www.w3.org/2000/xmlns/}ns0":"http://sample.com/test","status":"online"};
+    xml:Element element = xml:createElement("{http://sample.com/test}bookStore", attributes, xml ``);
+    assert(element.toString(), "<ns0:bookStore xmlns:ns0=\"http://sample.com/test\" status=\"online\"></ns0:bookStore>");
```
Comment (SandaruJayawardana) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attribute-access-syntax.bal:31]: @rdhananjaya there is some deviation compared to io:println().
```
io:println(element) -> <ns0:bookStore xmlns:ns0="http://sample.com/test" status="online"/>
```
any specific reason for this?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java (hunk 2 above)
Comment (rdhananjaya) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/creators/ValueCreator.java]: Yes.
Yes please.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attribute-access-syntax.bal (hunk 6 above)
Comment (rdhananjaya) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attribute-access-syntax.bal:31]: This is because the the stax implementation we have with jBallerina-uniut-test module is different from the one we have when we build a distribution pack.
Both of these are valid, just different serializations.

Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-attribute-access-syntax.bal:31]: Ah okay. Thanks.

File: langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java [hunk 7]
```diff
@@ -38,19 +43,53 @@
...
 
+    private static String getPrefix(String name, BMap<BString, BString> attributes) {
+        int curlyBracketEndIndex = name.lastIndexOf('}');
+        if (name.startsWith("{") && curlyBracketEndIndex > 0) {
+            String uri = name.substring(1, curlyBracketEndIndex);
+            for (Map.Entry<BString, BString> entry : attributes.entrySet()) {
+                if (entry.getValue().getValue().equals(uri)) {
+                    String key = entry.getKey().getValue();
+                    if (key.startsWith(XMLNS_NS_URI_PREFIX)) {
+                        String prefix = key.substring(key.indexOf('}') + 1);
```
Comment (rdhananjaya) [inline langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java:73]: curlyBracketEndIndex

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-with-namespaces.bal [hunk 8]
```diff
@@ -166,3 +166,32 @@ function testXmlLiteralUsingXmlNamespacePrefix() {
         panic error("Assertion error", expected = expectedStr, found=s);
     }
 }
+
```
Comment (rdhananjaya) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-with-namespaces.bal:169]: I think this test cases should be in xmllib_test.bal as this is about `xml:createElement` rather than xml literal.

File: langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java (hunk 7 above)
Comment (SandaruJayawardana) [reply langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java:73]: I have missed it. Thanks.

Comment (rdhananjaya) [reply langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/CreateElement.java]: yah sorry my bad.

**Review by rdhananjaya — APPROVED** [review]

**Review by gimantha — APPROVED** [review]
