### PR TITLE
Avoid byte[] key inequality with byte buffer

### LINKED ISSUE #29671: Transaction:getInfo() does not return the past transaction information
Consider the following code.

```ballerina
transaction {
        readonly d = 123;
        transactions:setData(d);
        transactions:Info transInfo = transactions:info();
        transactions:Info? newTransInfo = transactions:getInfo(transInfo.xid);
        if(newTransInfo is transactions:Info) {
            test:assertEquals(transInfo.xid, newTransInfo.xid);
        } else {
            panic error AssertionError(ASSERTION_ERROR_REASON, message = "unexpected output from getInfo");
        }
        transactions:onRollback(rollbackFunc);
        str += "In Trx";
        test:assertEquals(d === transactions:getData(), true);
        check commit;
        str += " commit";
    }

```
Above code should have executed successfully, but instead it prints "unexpected output from getInfo".
Cause is the output of Info() andd getInfo() are not the same.

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #29671

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java [hunk 1]
```diff
@@ -605,4 +606,8 @@ public void notifyLocalParticipantFailure(String gTransactionId, String blockId)
             failedLocalParticipantSet.add(gTransactionId);
         }
     }
+
+    public Object getTransactionRecord(BArray xid) {
+        return transactionInfoMap.get(ByteBuffer.wrap(xid.getBytes().clone()));
```
Comment (grainier) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java:611]: Why `clone()` here?

**Review by grainier — DISMISSED** [review]

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java (hunk 1 above)
Comment (pcnfernando) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java:611]: Yes we don't need to clone here

**Review by grainier — APPROVED** [review]
