### PR TITLE
[2201.3.0-stage] Fix reference type check for object and table

### LINKED ISSUE #38103: [Task]: Check for possible regressions after #37793
### Description

We need to revisit all `TypeTags.OBJECT` and `TypeTags.TABLE` equality checks that we do on a `TypeChecker. checkExpr(...)` result and check whether we unwrap the reference type before type tag checking.

This is to identify whether we have missed such cases and fix them proactively.
Such a case was identified and reported https://github.com/ballerina-platform/ballerina-lang/issues/38100

### Describe your task(s)

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by prakanth97**
## Purpose

Fixes #38103 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java [hunk 1]
```diff
@@ -254,6 +254,8 @@ private static boolean containsTypeParam(BType type, HashSet<BType> resolvedType
                 return containsTypeParam(errorType.detailType, resolvedTypes);
             case TypeTags.TYPEDESC:
                 return containsTypeParam(((BTypedescType) type).constraint, resolvedTypes);
+            case TypeTags.TYPEREFDESC:
+                return containsTypeParam(Types.getReferredType(type), resolvedTypes);
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java:258]: We can do `type = Types.getReferredType(type)` at the top and remove this case. Please update similar cases if any

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -4077,12 +4078,13 @@ private boolean isDefiniteObjectType(BType bType, Set<BTypeIdSet> typeIdSets) {
     }
 
     private boolean collectObjectTypeIds(BType type, Set<BTypeIdSet> typeIdSets, Set<BType> visitedTypes) {
-        if (type.tag == TypeTags.OBJECT) {
+        BType referredType = Types.getReferredType(type);
+        if (referredType.tag == TypeTags.OBJECT) {
             var objectType = (BObjectType) type;
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4083]:
```suggestion
        if (referredType.tag == TypeTags.OBJECT) {
            var objectType = (BObjectType) referredType;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 3]
```diff
@@ -1620,7 +1620,7 @@ private void checkForExportableType(BTypeSymbol symbol, Location pos, HashSet<BT
         if (!visitedSymbols.add(symbol)) {
             return;
         }
-        switch (symbol.type.tag) {
+        switch (Types.getReferredType(symbol.type).tag) {
             case TypeTags.ARRAY:
                 checkForExportableType(((BArrayType) symbol.type).eType.tsymbol, pos, visitedSymbols);
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1625]: Need to pass referred type for casting

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 4]
```diff
@@ -3895,6 +3895,10 @@ private BTypeIdSet getTypeIds(BType type) {
     }
 
     private void flatMapAndGetObjectTypes(Set<BType> result, BType type) {
+        if (type.tag == TypeTags.TYPEREFDESC) {
+            flatMapAndGetObjectTypes(result, Types.getReferredType(type));
+            return;
+        }
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:3901]:
```suggestion
        type = Types.getReferredType(type);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java (hunk 1 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java]: Updated b94a3ac3618939988d528db9ce32b01cc3d02fa9

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 5]
```diff
@@ -1680,12 +1681,12 @@ private void checkForExportableType(BTypeSymbol symbol, Location pos, HashSet<BT
...
                 return;
             case TypeTags.PARAMETERIZED_TYPE:
-                BTypeSymbol parameterizedType = ((BParameterizedType) symbol.type).paramValueType.tsymbol;
+                BTypeSymbol parameterizedType = ((BParameterizedType) symbolType).paramValueType.tsymbol;
                 checkForExportableType(parameterizedType, pos, visitedSymbols);
                 return;
             case TypeTags.ERROR:
                 if (Symbols.isFlagOn(symbol.flags, Flags.ANONYMOUS)) {
-                    checkForExportableType((((BErrorType) symbol.type).detailType.tsymbol), pos, visitedSymbols);
+                    checkForExportableType((((BErrorType) symbolType).detailType.tsymbol), pos, visitedSymbols);
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1689]: Wouldn't it be easier to add a case for the reference type?

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1689]: I will update that

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 6]
```diff
@@ -4528,79 +4530,80 @@ private boolean equalityIntersectionExistsForComplexTypes(Set<BType> lhsTypes, S
...
-                            jsonEqualityIntersectionExists(expandAndGetMemberTypesRecursive(lhsMemberType))) {
+                            jsonEqualityIntersectionExists(expandAndGetMemberTypesRecursive(refLhsMemberType))) {
                         return true;
                     }
 
                     if (rhsTypes.stream().anyMatch(
                             rhsMemberType -> rhsMemberType.tag == TypeTags.MAP &&
                                     mapRecordEqualityIntersectionExists((BMapType) rhsMemberType,
-                                                                        (BRecordType) lhsMemberType))) {
+                                            (BRecordType) refLhsMemberType))) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4606]: Instead, may be a reference type case here?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java [hunk 7]
```diff
@@ -983,6 +983,7 @@ private boolean refersInferableParamName(List<String> paramsWithInferredTypedesc
 
     private boolean refersInferableParamName(List<String> paramsWithInferredTypedescDefault, BType type,
                                              Set<BType> unresolvedTypes) {
+        type = Types.getReferredType(type);
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java:986]: case here as well?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/typereftype/type_reference.bal [hunk 8]
```diff
@@ -355,6 +355,67 @@ function testUnionTypeRefWithMap() {
     assertEqual(map3.toString(), "{\"c\":3}");
 }
 
+public class Student {
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/typereftype/type_reference.bal:358]: Add few negative test cases to check whether the errors has changed?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 5 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1689]: Since the method parameter is `BTypeSymbol` no need to get the referred type.

`private void checkForExportableType(BTypeSymbol symbol, Location pos, HashSet<BTypeSymbol> visitedSymbols)`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java [hunk 9]
```diff
@@ -123,6 +123,11 @@ static String getFrameClassName(String pkgName, String funcName, BType attachedT
     }
 
     private static boolean isValidType(BType attachedType) {
-        return attachedType != null && (attachedType.tag == TypeTags.OBJECT || attachedType.tag == TypeTags.RECORD);
+        if (attachedType != null) {
+            BType referredAttachedType = JvmCodeGenUtil.getReferredType(attachedType);
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGenUtils.java:127]: Lets update `JvmCodeGenUtil.getReferredType()` to return `null` if the type is null

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java [hunk 10]
```diff
@@ -217,7 +218,7 @@ private int createTypesInstanceSplits(ClassWriter cw, List<BIRTypeDefinition> ty
         // Create the type
         for (BIRTypeDefinition optionalTypeDef : typeDefs) {
             String name = optionalTypeDef.internalName.value;
-            BType bType = optionalTypeDef.type;
+            BType bType = JvmCodeGenUtil.getReferredType(optionalTypeDef.type);
             if (bType.tag != TypeTags.RECORD && bType.tag != TypeTags.OBJECT && bType.tag != TypeTags.ERROR &&
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java:222]: Lets extractout `bType.tag` since it has many usages

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java [hunk 11]
```diff
@@ -270,7 +271,7 @@ private Map<String, String> populateTypes(ClassWriter cw, List<BIRTypeDefinition
         Map<String, String> funcTypeClassMap = new HashMap<>();
         String fieldName;
         for (BIRTypeDefinition optionalTypeDef : typeDefs) {
-            BType bType = optionalTypeDef.type;
+            BType bType = JvmCodeGenUtil.getReferredType(optionalTypeDef.type);
             if (!(bType.tag == TypeTags.RECORD || bType.tag == TypeTags.ERROR || bType.tag == TypeTags.OBJECT
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java:275]: Here as well, lets extract out bType.tag since it has many usages

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 12]
```diff
@@ -3684,6 +3684,7 @@ public boolean isSelfReferencedStructuredType(BType source, BType s) {
         if (source == s) {
             return true;
         }
+        s = getReferredType(s);
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3687]:
```suggestion

        s = getReferredType(s);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 13]
```diff
@@ -4507,7 +4508,8 @@ private boolean tupleIntersectionExists(BTupleType lhsType, BTupleType rhsType)
 
     private boolean equalityIntersectionExistsForComplexTypes(Set<BType> lhsTypes, Set<BType> rhsTypes) {
         for (BType lhsMemberType : lhsTypes) {
-            switch (lhsMemberType.tag) {
+            BType refLhsMemberType = Types.getReferredType(lhsMemberType);
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4511]:
```suggestion
            lhsMemberType = Types.getReferredType(lhsMemberType);
```

File: tests/jballerina-unit-test/src/test/resources/test-src/types/typereftype/type_reference.bal (hunk 8 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/typereftype/type_reference.bal:358]: Updated 601419e96ce753db7d28cdeaca9a809fc8935162

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 6 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Updated 904dc9232bd074b2a44a5e941b55d4f5302bb85b

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java (hunk 7 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java]: Updated 904dc9232bd074b2a44a5e941b55d4f5302bb85b

**Review by rdulmina — APPROVED** [review]
LGTM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 5 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1689]: But it should. Even the `tsymbol.type` can be a reference type
eg
```ballerina
type Foo int;
type Bar Foo;

public function foo() returns Bar {
  return 1;
}
```

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1689]: Updated 30af85e995258ddfb1e9ebe306d5c35c46c35054

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 14]
```diff
@@ -3232,7 +3232,8 @@ private void checkFieldBasedAccess(BLangFieldBasedAccess fieldAccessExpr, boolea
             if (actualType != symTable.semanticError &&
                     (fieldAccessExpr.isLValue || fieldAccessExpr.isCompoundAssignmentLValue)) {
                 if (isAllReadonlyTypes(varRefType)) {
-                    if (varRefType.tag != TypeTags.OBJECT || !isInitializationInInit(varRefType, data)) {
+                    if (Types.getReferredType(varRefType).tag != TypeTags.OBJECT
+                            || !isInitializationInInit(varRefType, data)) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3236]: `isInitializationInInit` does a `BObjectType` cast. Hence, need the referred type there

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 15]
```diff
@@ -4507,104 +4509,113 @@ private boolean tupleIntersectionExists(BTupleType lhsType, BTupleType rhsType)
...
+            case TypeTags.JSON:
+                if (jsonEqualityIntersectionExists(rhsTypes)) {
+                    return true;
+                }
+                break;
+            // When expanding members for tuples, arrays and maps, set isValueDeepEquality to true, to allow
+            // comparison between JSON lists/maps and primitive lists/maps since they are all reference types
+            case TypeTags.TUPLE:
+                if (rhsTypes.stream().anyMatch(
+                        rhsMemberType -> rhsMemberType.tag == TypeTags.TUPLE &&
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4540]: rhsMemberType can be referencedType

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4540]: Check other places as well eg. TypeTagds.Array

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 16]
```diff
@@ -1680,14 +1681,19 @@ private void checkForExportableType(BTypeSymbol symbol, Location pos, HashSet<BT
...
                     return;
                 }
+                break;
+            case TypeTags.TYPEREFDESC:
+                symbolType = Types.getReferredType(symbolType);
+                checkForExportableType(Types.getReferredType(symbolType).tsymbol, pos, visitedSymbols);
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1695]: You can directly use `symbolType` here

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 17]
```diff
@@ -5091,8 +5091,9 @@ private boolean validateFuncReceiver(BLangFunction funcNode) {
             return true;
         }
 
-        if (funcNode.receiver.getBType().tag == TypeTags.OBJECT
-                && !this.env.enclPkg.symbol.pkgID.equals(funcNode.receiver.getBType().tsymbol.pkgID)) {
+        BType referredReceiverType = Types.getReferredType(funcNode.receiver.getBType());
+        if (referredReceiverType.tag == TypeTags.OBJECT
+                && !this.env.enclPkg.symbol.pkgID.equals(referredReceiverType.tsymbol.pkgID)) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:5096]: The referredType can have a different pkgId

**Review by pcnfernando — APPROVED** [review]

**Comment by rdulmina** [comment]
@prakanth97 we need to send this to master as well
