### PR TITLE
Throw error when field access is used with a map of `xml`

### LINKED ISSUE #39341: [Bug]: No error when field access is used with a map of XML
### Description

$title. Seems like `xml` is considered lax.

### Steps to Reproduce

```ballerina
import ballerina/io;

public function main() returns error? {
    map<xml> m = {a: xml `foo`};
    xml x = check m.a; // no error
    io:println(x); // prints `foo`
}
```

### Affected Version(s)

2201.3.2

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by ushirask**
Fixes #39341 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -275,7 +275,7 @@ public BType checkType(Location pos,
     public boolean isLax(BType type) {
         Set<BType> visited = new HashSet<>();
         int result = isLaxType(type, visited);
-        if (result == 1) {
+        if (result == 1 || type.tag == TypeTags.XML || type.tag == TypeTags.XML_ELEMENT) {
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:278]: This seems wrong. this will return XML as lax, which is wrong.

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:278]: The `isLax` function is used when checking for field based access, and since XML maps won't give 1 for `isLaxType` now only XML attribute access will be allowed. Maybe the function name `isLax` is misleading here and can be changed to something like `isLaxFieldAccessAllowed` ?

Comment (hasithaa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:278]: Please rename this.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal [hunk 2]
```diff
@@ -376,3 +376,8 @@ function testInvalidBoundMethodAccessWithRemoteMethod(ServiceClass a,
 
     _ = e.ser.fn;
 }
+
+function testInvalidXMLMapFieldAccess() {
+    map<xml> m = {a: xml `foo`};
+    xml x = check m.a; // error
+}
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal:383]: Add more test cases, in different contexts.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal [hunk 3]
```diff
@@ -376,3 +376,25 @@ function testInvalidBoundMethodAccessWithRemoteMethod(ServiceClass a,
 
     _ = e.ser.fn;
 }
+
+function testInvalidXMLMapFieldAccess1() {
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal:380]: One minor change, add `returns error?` here. Because you have used check in the function.

Comment (hasithaa) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal:380]: Do the same for other places.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 4]
```diff
@@ -272,10 +272,10 @@ public BType checkType(Location pos,
         return symTable.semanticError;
     }
 
-    public boolean isLax(BType type) {
+    public boolean isLaxFieldAccessAllowed(BType type) {
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:275]: Please add positive test cases too.

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:275]: The refactored changes are still covered with `XMLAccessTest` and `XMLAttributeAccessTest`, shall we add them elsewhere too?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 5]
```diff
@@ -272,10 +272,10 @@ public BType checkType(Location pos,
...
         Set<BType> visited = new HashSet<>();
         int result = isLaxType(type, visited);
-        if (result == 1) {
+        if (result == 1 || type.tag == TypeTags.XML || type.tag == TypeTags.XML_ELEMENT) {
             return true;
         }
         return false;
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:281]:
```suggestion
        return result == 1 || type.tag == TypeTags.XML || type.tag == TypeTags.XML_ELEMENT;
```
Simplify this

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:281]: variable `result` is redundant

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal [hunk 6]
```diff
@@ -376,3 +376,25 @@ function testInvalidBoundMethodAccessWithRemoteMethod(ServiceClass a,
...
+    map<xml> m = {};
+    m["a"] = xml `foo`;
+    xml x = check m.a; // error
+}
+
+function testInvalidXMLMapFieldAccess4() returns error? {
+    map<xml|json> m = {};
+    m["a"] = xml `foo`;
+    xml|json x = check m.a; // error
+}
```
Comment (prakanth97) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal:400]: Do we have tests for optional field access like
```

function testInvalidXMLMapFieldAccess1() returns error? {
    map<xml> m = {a: xml `foo`};
    _ = m?.a;
}
```

if not shall we few tests?

**Comment by prakanth97** [comment]
Do we have test like this ?
```
function testInvalidXMLMapFieldAccess1() returns error? {
    map<xml> m = {a: xml `foo`};
    xml? x = m["a"];
}
```

**Comment by prakanth97** [comment]
Add a complex test like this as well,
```
function testInvalidXMLMapFieldAccess5() returns error? {
    record {|map<xml> a; xml c;|} m = {a: {b: xml `foo`}, c: xml `bar`};
    xml? x = m["a"]?.b.c;
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal (hunk 6 above)
Comment (ushirask) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal:400]: added.

**Review by prakanth97 — APPROVED** [review]
LGTM

**Review by hasithaa — APPROVED** [review]
