### PR TITLE
Remove invalid `variable assignment is required` error for certain function invocations without variable assignments

### LINKED ISSUE #36238: Different behaviours in `null` and `()` in function call
**Description:**
Check this example.
```ballerina
public function main() returns error? {
    bar(); // error: variable assignment is required, but error is not expected
    baz();
}

function baz() returns () {
    return ();
}

function bar() returns null {
    return null;
}
```

**Steps to reproduce:**

**Affected Versions:**
Ballerina 2201.1.0

### LINKED ISSUE #39000: [Bug]: Invalid "variable assignment is required" error when calling `close` on a stream with nil completion type
### Description

$title.

### Steps to Reproduce

```ballerina
public function main() {
    stream<string> str = new;
    str.close(); // error: variable assignment is required

    () close = str.close(); // OK
}
```

### Affected Version(s)

2201.3.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by suleka96**
Fixes #39000
Fixes #36238

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 1]
```diff
@@ -2713,6 +2714,42 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
         }
     }
 
+    private boolean isFiniteWithNilMember(BType bType) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2717]: Is this name accurate? The check is for a finite type with all `null` members, right? Right now it kinda implies the check is for a finite type with at least one `null` member?

Let's use `null` here because it's specifically the null literal.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 2]
```diff
@@ -2713,6 +2714,42 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
...
+        if (!(bType.getKind() == TypeKind.FINITE)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2718]:
```suggestion
        if (bType.getKind() != TypeKind.FINITE) {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 3]
```diff
@@ -2713,6 +2714,42 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
...
+            return false;
+        }
+        BFiniteType finiteType = (BFiniteType) bType;
+        Set<BLangExpression> finiteMembers = finiteType.getValueSpace();
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2722]:
```suggestion
        Set<BLangExpression> finiteMembers = ((BFiniteType) bType).getValueSpace();
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 4]
```diff
@@ -2713,6 +2714,42 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
...
+        for (BLangExpression finiteMemberType : finiteMembers) {
+            if (finiteMemberType.getBType() != null && finiteMemberType.getBType().tag != TypeTags.NIL) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2724]: Can you share a scenario for then `finiteMemberType.getBType()` is null?

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2724]: Can extract `finiteMemberType.getBType()` out to a variable if the null check is needed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 5]
```diff
@@ -2713,6 +2714,42 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
...
+                return false;
+            }
+        }
+        return true;
+    }
+
+    private boolean isUnionWithSingleNilTypeMember(BType bType) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2731]: Again, please reconsider the name. For me, this implies a union with only one member that is nil.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 6]
```diff
@@ -2713,6 +2714,42 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
...
+        if (!(bType.getKind() == TypeKind.UNION)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2732]:
```suggestion
        if (bType.getKind() != TypeKind.UNION) {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 2 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2718]: Let's use type tag instead.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 6 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2732]: Let's use type tag instead.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 7]
```diff
@@ -2713,6 +2714,42 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
...
+            return false;
+        }
+        BUnionType unionType = (BUnionType) bType;
+        LinkedHashSet<BType> members = unionType.getMemberTypes();
+        LinkedHashSet<BType> originalMembers = unionType.getOriginalMemberTypes();
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2737]: Move closer to where used. If we return before L2746, this is not used.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 8]
```diff
@@ -2713,6 +2714,42 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
...
+        if (members.size() >= 1) {
+            for (BType memberType : members) {
+                if (memberType.getKind() != TypeKind.NIL) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2740]: Use type tag instead of kind wherever applicable.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 9]
```diff
@@ -2713,6 +2714,42 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
...
+                    return false;
+                }
+            }
+            return true;
+        }
+        // To bypass `function f3() returns never|never` kind of scenarios, referencing error: #39797
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2746]: Let's just say this is a special case to handle return types like `never|never`, since they are not handled correctly at the moment and add the link to the issue (instead of just #39797).

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 10]
```diff
@@ -2723,7 +2760,8 @@ public void visit(BLangExpressionStmt exprStmtNode, AnalyzerData data) {
         BType bType = typeChecker.checkExpr(expr, stmtEnv, data.prevEnvs, data.commonAnalyzerData);
         if (bType != symTable.nilType && bType != symTable.semanticError &&
                 expr.getKind() != NodeKind.FAIL &&
-                !types.isNeverTypeOrStructureTypeWithARequiredNeverMember(bType)) {
+                !types.isNeverTypeOrStructureTypeWithARequiredNeverMember(bType) &&
+                !isUnionWithSingleNilTypeMember(bType) && !isFiniteWithNilMember(bType)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2764]: I would extract the type check for nil type here to a separate method (which in turn will call the other methods). E.g., `isSubTypeOfNil`

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal [hunk 11]
```diff
@@ -354,6 +354,46 @@ function testTypeRefTypedRestArg() {
...
     b.reduce(function (int tot, string str) returns int => tot + str.length(), a);
 
+function testFuncWithNilReturnTypeWithoutVariableAssignment() {
+    stream<string> testStream = new;
+    testStream.close(); // No error
+    f1(); // No error
+    f2(); // No error
+    f4(); // No error
+    f5(); // No error
+    f6(); // No error
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal:364]: I don't think we need the "No error" comments here since they are applicable to all and are in a positive test.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal [hunk 12]
```diff
@@ -354,6 +354,46 @@ function testTypeRefTypedRestArg() {
...
+
+function testFuncWithNeverReturnTypeWithoutVariableAssignment2() {
+    f7();
+}
+
+function f6() {}
+
+function f7() returns never {
+    panic error("Invalid");
+}
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal:379]: Why are f6 and f7 before f1 and the rest?

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal:379]: I would maintain the order across the tests too.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java [hunk 13]
```diff
@@ -146,6 +147,23 @@ public Object[][] invocationWithArgVarargMixTestFunctions() {
...
+        BRunUtil.invoke(funcInvocationExpResult, "testFuncWithNeverReturnTypeWithoutVariableAssignment1");
+    }
+
+    @Test(expectedExceptions = {BLangRuntimeException.class},
+            expectedExceptionsMessageRegExp = "error: Invalid.*")
+    public void testFuncWithNeverReturnTypeWithoutVariableAssignment2() {
+        BRunUtil.invoke(funcInvocationExpResult, "testFuncWithNeverReturnTypeWithoutVariableAssignment2");
+    }
+
+    @Test(description = "Test function invocation without variable assignment")
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java:162]: IMO, the description is not required. Or we need to improve it. The test name already provides more details in a way.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java [hunk 14]
```diff
@@ -146,6 +147,23 @@ public Object[][] invocationWithArgVarargMixTestFunctions() {
...
+            expectedExceptionsMessageRegExp = "error: Invalid.*")
+    public void testFuncWithNeverReturnTypeWithoutVariableAssignment1() {
+        BRunUtil.invoke(funcInvocationExpResult, "testFuncWithNeverReturnTypeWithoutVariableAssignment1");
+    }
+
+    @Test(expectedExceptions = {BLangRuntimeException.class},
+            expectedExceptionsMessageRegExp = "error: Invalid.*")
+    public void testFuncWithNeverReturnTypeWithoutVariableAssignment2() {
+        BRunUtil.invoke(funcInvocationExpResult, "testFuncWithNeverReturnTypeWithoutVariableAssignment2");
+    }
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java:160]: Panics can be tested in Ballerina itself. Trap in the test function and assert. You'll need an additional function in between.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal [hunk 15]
```diff
@@ -354,6 +354,46 @@ function testTypeRefTypedRestArg() {
...
+
+function f1() returns ()|() => ();
+
+function f2() returns never? => ();
+
+function f3() returns never|never {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal:385]: Let's add with `null|null` also.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 5 above)
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2731]: We need to add a few negative test including return types such as 

- `()|int|()`
- `1|null`
- `null|1|null`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 16]
```diff
@@ -2713,6 +2714,42 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
...
+        if (members.size() >= 1) {
+            for (BType memberType : members) {
+                if (memberType.getKind() != TypeKind.NIL) {
+                    return false;
+                }
+            }
+            return true;
+        }
+        // To bypass `function f3() returns never|never` kind of scenarios, referencing error: #39797
+        if (members.size() == 0 && originalMembers.size() == 1) {
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2747]: Why do we need `members.size() == 0` check? It is always true, right?

Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2747]: Ideally, for a `union` type the  `unionType.getMemberTypes()` should not be empty. This needs to be fixed, so this check was to bypass the current status of the specific scenario.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 10 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2764]: Also, can't we use isAssignable with symTable.nilType instead of these individual checks?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 5 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: [5bfff30](https://github.com/ballerina-platform/ballerina-lang/pull/39819/commits/5bfff3057a80394569bda7a41c4fbb5414d07e9b)

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 10 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: > Also, can't we use isAssignable with symTable.nilType instead of these individual checks?

@suleka96, any update on this?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 17]
```diff
@@ -2713,6 +2714,46 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
...
+            }
+            return true;
+        }
+        LinkedHashSet<BType> originalMembers = unionType.getOriginalMemberTypes();
+        // Special cased to handle return types like never|never` as they are not correctly handled at the moment.
+        // https://github.com/ballerina-platform/ballerina-lang/issues/39797
+        if (members.size() == 0 && originalMembers.size() == 1) {
+            return originalMembers.iterator().next().tag == TypeTags.NEVER;
+        }
+        return false;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2750]: Codecov warning?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 18]
```diff
@@ -2713,6 +2714,46 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
         }
     }
 
+    private boolean checkIfFiniteTypeHasNullMembers(BType bType) {
+        if (bType.tag != TypeTags.FINITE) {
+            return false;
+        }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2720]: If we write the type as a type definition, we are still getting a "variable assignment is required" error
Example
```ballerina
function vlaue() {
    f1();

}

type Foo null;
function f1() returns Foo => null;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 16 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2747]: No need to create a special case for this scenario. If we modify the logic as I suggested, this case will handle correctly as well. Even after fixing this issue(https://github.com/ballerina-platform/ballerina-lang/issues/39797), there is no possibility of failure. (Please ensure that a test is added for this. Once the issue is resolved, we can verify if it has been fixed or not)
```java
 for (BType memberType : members) {
    if (memberType.tag != TypeTags.NIL) {
        return false;
    }
}
return true;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 19]
```diff
@@ -2713,6 +2714,46 @@ private void checkConstantAssignment(BLangExpression varRef, AnalyzerData data)
...
+        LinkedHashSet<BType> originalMembers = unionType.getOriginalMemberTypes();
+        // Special cased to handle return types like never|never` as they are not correctly handled at the moment.
+        // https://github.com/ballerina-platform/ballerina-lang/issues/39797
+        if (members.size() == 0 && originalMembers.size() == 1) {
+            return originalMembers.iterator().next().tag == TypeTags.NEVER;
+        }
+        return false;
+    }
+
+    private boolean isSubTypeOfNil(BType bType) {
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2753]: We can refactor overall logic as this(need to verify whether it is okay to use streams in Java.)
```java
private boolean hasNullMembers(BType bType) {
    switch (bType.tag) {
        case TypeTags.UNION:
            BUnionType unionType = (BUnionType) bType;
            return unionType.getMemberTypes().stream()
                    .allMatch(memberType -> memberType.tag == TypeTags.NIL);
        case TypeTags.FINITE:
            Set<BLangExpression> finiteMembers = ((BFiniteType) bType).getValueSpace();
            return finiteMembers.stream()
                    .allMatch(finiteMemberType -> finiteMemberType.getBType().tag == TypeTags.NIL);
        default:
            return false;
    }
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal [hunk 20]
```diff
@@ -354,6 +354,57 @@ function testTypeRefTypedRestArg() {
 function testFn(int a, string... b) returns int =>
     b.reduce(function (int tot, string str) returns int => tot + str.length(), a);
 
+function testFuncWithNilReturnTypeWithoutVariableAssignment() {
```
Comment (chiranSachintha) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal:357]: Please add some additional test cases for scenarios where the return type is used as a type reference.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 16 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2747]: The issue is how are we going to get the member type tag with `memberType.tag` by iterating `members` when `members` for cases where the return types is  like `never|never` is empty. In that case we need to iterate `getOriginalMemberTypes()`, that is why I cased it.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal (hunk 20 above)
Comment (suleka96) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal:357]: what do we hope to test with this... can you provide an example

Comment (chiranSachintha) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal:357]: I mean to add a test for [this](https://github.com/ballerina-platform/ballerina-lang/pull/39819#discussion_r1134903418) kind of scenario

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 21]
```diff
@@ -2799,7 +2799,8 @@ public void visit(BLangExpressionStmt exprStmtNode, AnalyzerData data) {
         BType bType = typeChecker.checkExpr(expr, stmtEnv, data.prevEnvs, data.commonAnalyzerData);
         if (bType != symTable.nilType && bType != symTable.semanticError &&
                 expr.getKind() != NodeKind.FAIL &&
-                !types.isNeverTypeOrStructureTypeWithARequiredNeverMember(bType)) {
+                !types.isNeverTypeOrStructureTypeWithARequiredNeverMember(bType)
+                && !types.isAssignable(bType, symTable.nilType)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2803]: We don't need `bType != symTable.nilType` separately with this? Let's make this the first check instead.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 19 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: As we use `isAssignable`, we can ignore this.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal [hunk 22]
```diff
@@ -354,6 +354,77 @@ function testTypeRefTypedRestArg() {
...
+
+function intermediateFunction1() returns error? {
+    f3();
+}
+
+function intermediateFunction2() returns error? {
+    f7();
+}
+
+function intermediateFunction3() returns error? {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal:389]:
```suggestion
    error err = <error>trap intermediateFunction1();
    assertValueEquality("Invalid", err.message());

    err = <error>trap intermediateFunction2();
    assertValueEquality("Invalid", err.message());

    err = <error>trap intermediateFunction3();
    assertValueEquality("Invalid", err.message());
}

function intermediateFunction1() returns error? {
    f3();
}

function intermediateFunction2() returns error? {
    f7();
}

function intermediateFunction3() returns error? {
```

Can you local anonymous functions instead.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal [hunk 23]
```diff
@@ -354,6 +354,77 @@ function testTypeRefTypedRestArg() {
...
+
+function testFuncWithNeverReturnTypeWithoutVariableAssignment() {
+    error err = <error>trap intermediateFunction1();
+    assertValueEquality("Invalid", err.message());
+
+    err = <error>trap intermediateFunction2();
+    assertValueEquality("Invalid", err.message());
+
+    err = <error>trap intermediateFunction3();
+    assertValueEquality("Invalid", err.message());
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/invocations/function-invocation-expr.bal:378]: I would use different error messages in the different cases.

**Review by MaryamZi — APPROVED** [review]

**Review by chiranSachintha — APPROVED** [review]
