### PR TITLE
Fix "undefined symbol" error for captured variable after an if check

### LINKED ISSUE #34591: Invalid "undefined symbol" error for captured variable after an if check
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() returns error? {
    string username = "";

    // Works when this is commented out.
    if username == "" {
    }

    int x = 1;

    int _ = x; // OK

    worker w {
        int _ = x; // error: undefined symbol 'x'
    }

    function _ = function () {
        int _ = x; // error: undefined symbol 'x'
    };
}
```

**Affected Versions:**
stage-swan-lake

### PR DESCRIPTION
**Pull request by lasinicl**
## Purpose
$title

Fixes #34591

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 1]
```diff
@@ -1535,21 +1535,32 @@ public BLangNode transform(FunctionBodyBlockNode functionBodyBlockNode) {
...
+            NodeList<StatementNode> workerInitStmts = namedWorkerDeclarator.workerInitStatements();
+            generateAndAddBLangStatements(workerInitStmts, statements, 0, functionBodyBlockNode);
+
+            int stmtSize = statements.size();
+            int workerInitStmtSize = workerInitStmts.size();
+            // If there's a worker defined after an `if` statement without an `else`, need to add it to the
+            // newly created block statement.
+            if (stmtSize > 1 && workerInitStmtSize > 0 && statements.get(stmtSize - 1).getKind() == NodeKind.BLOCK &&
+                    statements.get(stmtSize - 2).getKind() == NodeKind.IF &&
+                    workerInitStmts.get(workerInitStmtSize - 1).kind() != SyntaxKind.BLOCK_STATEMENT) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:1550]: Shall we extract this check out to a method instead of the comment?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerTest.java [hunk 2]
```diff
@@ -109,6 +109,19 @@ public void testSimpleSyncSendFunctions(String funcName) {
         };
     }
 
+    @Test(dataProvider = "basicWorkerFunctions")
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/BasicWorkerTest.java:112]: I'm not sure if this is the correct place for these tests given that we are testing something that is impacted by an implementation decision.  Also, just looking at the test names, it is not clear what we are testing.

**Review by MaryamZi — APPROVED** [review]
Suggestions can be addressed separately.
