### PR TITLE
Fix symbol type of `Constants`

### LINKED ISSUE #32513: Assigning an incorrect value to `int:MIN_VALUE` type variable does not give a compilation error
**Description:**
$title

**Steps to reproduce:**
```ballerina
public function main() {
    int:MAX_VALUE b = -10; // gives compilation error as expected
    int:MIN_VALUE a = -10; // no error
}
```

**Affected Versions:**
slbeta2

### LINKED ISSUE #32995: Invalid type checking for user-defined subtypes when it contains `int:MIN_VALUE`
**Description:**
Consider the following program,
```ballerina
import ballerina/io;

type Ints -1|int:MIN_VALUE;

public function main() {
    int a = 128;
    Ints b = 2; // Compiler should throw an error here

    var x1 = a << b;
    Ints y1 = x1; // Compiler should throw an error here
    io:println(y1);
}
```
Compiler output:
```
512
```
Even though above program contains 2 errors, compiler doesn't throw any error. This happens when we use `int:MIN_VALUE` as a value in user-defined subtypes.

### LINKED ISSUE #33405: Incorrect type checking with `float:NaN` and `float:Infinity`
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    float a = 1;

    // Produces incorrect output and also invalid "always true" warnings.
    io:println(a is float:NaN); // true!
    io:println(a is float:Infinity); // true!

    float:NaN b = a; // no compilation error!
    float:Infinity c = a; // no compilation error!

    // Correct output.
    io:println(a is float:PI); // false
    io:println(a is float:E); // false

    // float:PI d = a; // compilation error, as expected.
    // float:E e = a; // compilation error, as expected.
}
```

**Affected Versions:**
slbeta3

### PR DESCRIPTION
**Pull request by SandaruJayawardana**
Fixes #33405
Fixes #32995
Fixes #32513

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by SandaruJayawardana** [comment]
There is a `not implemented` error for `RECORD_LITERAL_EXPR`. Therefore, we cannot update the symbol type to Finite type for map type constants (58cdea6). This fix also causes to break some current test-cases. @hasithaa @gimantha  

Error:
```
java.lang.AssertionError: Type serialization is not implemented for finite type with value: RECORD_LITERAL_EXPR
	at org.wso2.ballerinalang.compiler.bir.writer.BIRTypeWriter.visit(BIRTypeWriter.java:171)
	at org.wso2.ballerinalang.compiler.semantics.model.types.BFiniteType.accept(BFiniteType.java:69)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRTypeWriter.visitType(BIRTypeWriter.java:105)
	at org.wso2.ballerinalang.compiler.bir.writer.ConstantPool.writeToStream(ConstantPool.java:128)
	at org.wso2.ballerinalang.compiler.bir.writer.ConstantPool.serialize(ConstantPool.java:68)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.serialize(BIRBinaryWriter.java:96)
	at io.ballerina.projects.ModuleContext.cacheBIR(ModuleContext.java:459)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:429)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:353)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137) 
...
```

**Comment by SandaruJayawardana** [comment]
There are some related issues (#33890, #32804) which are difficult to fix with current implementation (Resolving constants at `SemanticAnalyzer` stage).

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 1]
```diff
@@ -83,6 +95,7 @@ public void resolve(List<BLangConstant> constants, PackageID packageID) {
         constants.forEach(constant -> constant.accept(this));
         constantMap.clear();
         constants.forEach(constant -> checkUniqueness(constant));
+        constants.forEach(constant -> updateSymbolType(constant));
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:98]: Can't we set the type when visiting the constant(in L95)? 
In L105(`this.currentConstSymbol.value = visitExpr(constant.expr);`) we set the value. IMO after doing that we can set the type of the constant expr. 

Another thing is we set the type of constant expr in the `SymbolEnter`. As an example for the following program, we set the type as `int` in the symbol enter and then updated that type to a finite type in here. Is there any reason to do that? If not we can directly set the type after resolving the value of constant expr. 
Example
```ballerina
const int x = 3;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 2]
```diff
@@ -468,4 +481,86 @@ private void checkUniqueness(BLangConstant constant) {
...
+        }
+    }
+
+    private BLangExpression createExpression(Object value, BType type, Location pos) {
+        switch (type.getKind()) {
+            case INT:
+            case BYTE:
+            case FLOAT:
+            case DECIMAL:
+                return createConstantNumericLiteralExpression(value, type, pos);
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:507]: We can use `createConstantLiteralExpression` function. Instead of creating new function.

Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:507]: If we do so, there type checking phase will log errors for numeric literals.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 1 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:98]: > Can't we set the type when visiting the constant(in L95)?

We can. But in L97, we are removing duplicate constants. We can do the type updating process after that step to reduce the cost.

> Another thing is we set the type of constant expr in the SymbolEnter. As an example for the following program, we set the type as int in the symbol enter and then updated that type to a finite type in here. Is there any reason to do that? 

Ah no. For this scenario, the `symbolEnter` will update the symbol type to a finite type (since it is a numeric literal rather than an expression). In the constantValueResolver, we are updating the types of the `constants` which couldn't be resolved at the `symbolEnter` phase. Anyway, I think we need to move the `constantValueResolving` logic into the `symbolEnter` to do this in the proper way.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:98]: > > Can't we set the type when visiting the constant(in L95)?
> 
> We can. But in L97, we are removing duplicate constants. We can do the type updating process after that step to reduce the cost.

IMO, the chances of someone duplicating a constant definition (or any definition for that matter) are quite low. I think it'll help with readability to do this when visiting the constant itself. It may also help when resolving constant references since the type is already set.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 3]
```diff
@@ -474,4 +487,58 @@ private void checkUniqueness(BLangConstant constant) {
...
+                constant.symbol.value != null) {
+            BFiniteType finiteType = checkType(constant, constant.symbol.value.value, constant.symbol.type,
+                    constant.symbol.pos);
+            if (finiteType != null) {
+                constant.symbol.type = finiteType;
+            }
+        }
+    }
+
+    public BFiniteType createFiniteType(BLangConstant constant, BLangExpression expr) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:502]: Can be private?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 4]
```diff
@@ -474,4 +487,58 @@ private void checkUniqueness(BLangConstant constant) {
             }
         }
     }
+
+    private void updateSymbolType(BLangConstant constant) {
+        if (constant.symbol.kind == SymbolKind.CONSTANT && constant.symbol.type.getKind() != TypeKind.FINITE &&
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:492]: Shall we extract `constant.symbol` out to a variable?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 5]
```diff
@@ -474,4 +487,58 @@ private void checkUniqueness(BLangConstant constant) {
...
+                constant.symbol.value != null) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:493]: We can check the inverse and return early.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 4 above)
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:492]: Can you give an example for when the kind is not CONSTANT?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 6]
```diff
@@ -474,4 +487,58 @@ private void checkUniqueness(BLangConstant constant) {
...
+            BFiniteType finiteType = checkType(constant, constant.symbol.value.value, constant.symbol.type,
+                    constant.symbol.pos);
+            if (finiteType != null) {
+                constant.symbol.type = finiteType;
+            }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:498]:
```suggestion
        BConstantSymbol symbol = constant.symbol;

        if (symbol.kind != SymbolKind.CONSTANT || symbol.type.getKind() == TypeKind.FINITE || symbol.value == null) {
            return;
        }

        BFiniteType finiteType = checkType(constant, symbol.value.value, symbol.type, symbol.pos);
        if (finiteType != null) {
            symbol.type = finiteType;
        }
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 7]
```diff
@@ -474,4 +487,58 @@ private void checkUniqueness(BLangConstant constant) {
...
+        BTypeSymbol finiteTypeSymbol = Symbols.createTypeSymbol(SymTag.FINITE_TYPE,
+                Flags.asMask(EnumSet.noneOf(Flag.class)), Names.EMPTY, constant.symbol.pkgID, null,
+                constant.symbol.owner, constant.symbol.pos, VIRTUAL);
+        BFiniteType finiteType = new BFiniteType(finiteTypeSymbol);
+        finiteType.addValue(expr);
+        return finiteType;
+    }
+
+    private BFiniteType checkType(BLangConstant constant, Object value, BType type, Location pos) {
+        switch (type.getKind()) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:512]: Shall we check by tag instead?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:512]: Need to also include subtypes of these types.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 8]
```diff
@@ -474,4 +487,58 @@ private void checkUniqueness(BLangConstant constant) {
...
+        return literal;
+    }
+
+    private BLangLiteral createConstantLiteralExpression(Object value, BType type, Location pos) {
+        BLangLiteral literal = (BLangLiteral) TreeBuilder.createLiteralExpression();
+        literal.value = value;
+        literal.isConstant = true;
+        literal.setBType(type);
+        literal.pos = pos;
+        return literal;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:542]: Common logic can be extracted out to a separate method?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 3 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:502]: Yeah. Will update.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 4 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:492]: Sure. Will update.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 8 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:542]: Yeah. I have missed it. Thanks.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 4 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:492]: My bad. It is a kind of unnecessary condition. Will remove. Thanks.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 9]
```diff
@@ -474,4 +488,67 @@ private void checkUniqueness(BLangConstant constant) {
...
+
+    private BLangNumericLiteral createConstantNumericLiteralExpression(Object value, BType type, Location pos) {
+        BLangNumericLiteral literal = (BLangNumericLiteral) TreeBuilder.createNumericLiteralExpression();
+        return (BLangNumericLiteral) updateLiteral(literal, value, type, pos);
+    }
+
+    private BLangLiteral createConstantLiteralExpression(Object value, BType type, Location pos) {
+        BLangLiteral literal = (BLangLiteral) TreeBuilder.createLiteralExpression();
+        return updateLiteral(literal, value, type, pos);
+    }
```
[the remark this answers is not in the document]
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:545]: +1. Will update.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 10]
```diff
@@ -63,6 +75,7 @@
     private Location currentPos;
     private Map<BConstantSymbol, BLangConstant> unresolvedConstants = new HashMap<>();
     private Map<String, BLangConstantValue> constantMap = new HashMap<String, BLangConstantValue>();
+    private Map<BConstantSymbol, BType> updatedTypes = new HashMap<>();
```
[the remark this answers is not in the document]
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:78]: We will need it when we add support for constant maps (to reuse the resolved types). Do we need to remove the type field here and introduce it there?

[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:78]: Yes please, let's introduce if and when needed.

[the remark this answers is not in the document]
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:78]: My bad. We can reuse the resolved types in scenario as follows,
```ballerina
const int A = 1;
const int B = A;
```
Here, we can take the symbol type of `B` from the symbol `A` without creating a new type based on resolved value like done in L520 (in ConstantValueResolver). Is there any issue with this approach?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-expression-negative.bal [hunk 11]
```diff
@@ -35,3 +35,22 @@ const int CONST1 =  ~~false; // operator '~' not defined for 'boolean'
...
+const string CS2 = "1" + "2";
+
+function userDefinedTypeTests() {
+    CI6 ci6 = 4; // expected '3', found 'int'
+    CF1 cf1 = 4.0; // expected '3.0f', found 'float'
+    CD1 cd1 = 4.0; // expected '3.0d', found 'float'
+//  CBT3 cbt3 = 4; // expected '3', found 'int'
+    CB2 cb2 = true; // expected 'false', found 'boolean'
+    CS2 cs2 = "4"; // expected '12', found 'string'
+}
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-expression-negative.bal:55]: Similar to https://github.com/ballerina-platform/ballerina-lang/pull/33898/files#diff-f7b80acafb6a5c9b42be1aea1acfa78b59911c59f6a479ac5cc5265b47e1a213R319, shall we add some negative tests with all of these constants as expressions also? i.e., when the constant reference is the RHS expression.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantExpressionTest.java [hunk 12]
```diff
@@ -59,6 +59,14 @@ public void constExpressionNegative() {
         BAssertUtil.validateError(compileResult1, i++, "operator '~' not defined for 'boolean'", 33, 22);
         BAssertUtil.validateError(compileResult1, i++, "operator '-' not defined for 'boolean'", 35, 21);
         BAssertUtil.validateError(compileResult1, i++, "operator '~' not defined for 'boolean'", 37, 22);
+        BAssertUtil.validateError(compileResult1, i++, "incompatible types: expected '3', found 'int'", 49, 15);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantExpressionTest.java:62]: Shall we move all of these newly added tests to a separate test class? Like `ConstantTypeTest`? The existing tests in the current tests seem to be testing something else, right?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-expression-negative.bal (hunk 11 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-expression-negative.bal:55]: Like

```ballerina
const int THREE = 1 + 2;
type Foo 3|4;

Foo f = THREE;
```

and similarly negative tests.

**Comment by MaryamZi** [comment]
@SandaruJayawardana, can you please resolve the conflicts also?

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/EnumDeclSymbolTest.java [hunk 13]
```diff
@@ -146,7 +146,7 @@ public void testEnumMemberDeclarations(int line, int col, String expName, String
 
         // check type
         assertEquals(symbol.typeKind(), TypeDescKind.SINGLETON);
-        assertEquals(symbol.typeDescriptor().typeKind(), typeDescKind);
+        assertEquals(symbol.typeDescriptor().typeKind(), TypeDescKind.SINGLETON);
```
Comment (MaryamZi) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/EnumDeclSymbolTest.java:149]: @pubudu91, FYI.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 14]
```diff
@@ -86,16 +98,20 @@ public void resolve(List<BLangConstant> constants, PackageID packageID) {
         constants.forEach(constant -> this.unresolvedConstants.put(constant.symbol, constant));
         constants.forEach(constant -> constant.accept(this));
         constantMap.clear();
-        constants.forEach(constant -> checkUniqueness(constant));
     }
 
     @Override
     public void visit(BLangConstant constant) {
+        if (!unresolvedConstants.containsKey(constant.symbol)) {
+            return; // Already visit
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:106]:
```suggestion
            return; // Already visited.
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 15]
```diff
@@ -494,4 +510,53 @@ private void checkUniqueness(BLangConstant constant) {
...
+    }
+
+    private BType checkType(BLangExpression expr, BLangConstant constant, Object value, BType type, Location pos) {
+        if (expr != null && expr.getKind() == NodeKind.SIMPLE_VARIABLE_REF &&
+                ((BLangSimpleVarRef) expr).symbol.type.getKind() == TypeKind.FINITE) {
+            return ((BLangSimpleVarRef) expr).symbol.type; // Reference is already resolved.
+        }
+        switch (type.tag) {
+            case TypeTags.INT:
+            case TypeTags.BYTE:
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:540]: For byte constants (and other int subtypes when we support them), IMO we should create int finite types.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java [hunk 16]
```diff
@@ -0,0 +1,66 @@
...
+import org.ballerinalang.test.BAssertUtil;
+import org.ballerinalang.test.BCompileUtil;
+import org.ballerinalang.test.BRunUtil;
+import org.ballerinalang.test.CompileResult;
+import org.testng.Assert;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Test;
+
+/**
+ * Constant type test cases.
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java:29]:
```suggestion
 * Constant type test cases.
 *
 * @since 2.0.0
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java [hunk 17]
```diff
@@ -0,0 +1,66 @@
...
+
+    private CompileResult compileResult;
+
+    @BeforeClass
+    public void setup() {
+        compileResult = BCompileUtil.compile("test-src/types/constant/constant-type.bal");
+    }
+
+    @Test
+    public void testBitwiseConstExpressions() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java:41]: Incorrect method name?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 18]
```diff
@@ -494,4 +510,53 @@ private void checkUniqueness(BLangConstant constant) {
             }
         }
     }
+
+    private void updateSymbolType(BLangConstant constant) {
+        BConstantSymbol symbol = constant.symbol;
+        if (symbol.type.getKind() != TypeKind.FINITE && symbol.value != null) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:516]: Do we still need this check? Isn't a constant only visited once now? Even if not, is it possible for something that was visited previously to resolve to a finite type only in subsequent visits?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 19]
```diff
@@ -494,4 +510,53 @@ private void checkUniqueness(BLangConstant constant) {
...
+            BType singletonType = checkType(constant.expr, constant, symbol.value.value, symbol.type, symbol.pos);
+            if (singletonType != null) {
+                symbol.type = singletonType;
+            }
+        }
+    }
+
+    private BFiniteType createFiniteType(BLangConstant constant, BLangExpression expr) {
+        BTypeSymbol finiteTypeSymbol = Symbols.createTypeSymbol(SymTag.FINITE_TYPE,
+                Flags.asMask(EnumSet.noneOf(Flag.class)), Names.EMPTY, constant.symbol.pkgID, null,
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:526]:
```suggestion
                0, Names.EMPTY, constant.symbol.pkgID, null,
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java (hunk 17 above)
Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/ConstantTypeTest.java:41]: My bad. Will update. Thanks.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 18 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:516]: For example `const int X = 1;`, symbol type is already set to finite type by the `SymbolEnter`. Therefore, IMO we still need this check in here to avoid unnecessary type updates.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 15 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:540]: Then, shall I remove that case?

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/EnumDeclSymbolTest.java (hunk 13 above)
Comment (pubudu91) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/EnumDeclSymbolTest.java:149]: Ack. Shall we properly update this test case by getting rid of the `typeDescKind` param and updating the data provider as well?

**Review by MaryamZi — APPROVED** [review]

**Review by hasithaa — APPROVED** [review]

**Comment by MaryamZi** [comment]
@SandaruJayawardana, can you please sync the PR with master?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type-negative.bal [hunk 20]
```diff
@@ -0,0 +1,47 @@
+// Copyright (c) 2021 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type-negative.bal:1]: We use underscores for bal file names.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal [hunk 21]
```diff
@@ -314,3 +314,10 @@ const Byte V1 = 256;
 type Ints int;
 
 const Ints V2 = 1.0;
+
+// Test the types of Langlib constants
+type Ints2 -1|int:MIN_VALUE;
+Ints2 ints2 = 2;
+
+float:NaN floatNan = 1.0;
+float:Infinity floatInf = 1.0;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal:323]: These should also be moved, right?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type-negative.bal [hunk 22]
```diff
@@ -0,0 +1,47 @@
...
+// software distributed under the License is distributed on an
+// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+// KIND, either express or implied.  See the License for the
+// specific language governing permissions and limitations
+// under the License.
+
+const int CI6 = 1 + 2;
+const float CF1 = 1.0 + 2.0;
+const decimal CD1 = 1.0 + 2.0;
+// const byte CBT1 = 1; // Uncomment after fixing #33889
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/constant/constant-type-negative.bal:20]: For when the expression is a literal we can still add tests, right? Without waiting for `33889` to be fixed?

**Review by MaryamZi — COMMENTED** [review]
Please send a separate PR addressing the suggestions.

**Comment by MaryamZi** [comment]
We need to add this to the release note also.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal (hunk 21 above)
Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/constant/simple-literal-constant-negative.bal:323]: Yes.
