### PR TITLE
Fix several issues related to unary expression

### LINKED ISSUE #29976: Complement of integer literal
In slalpha4, I type:

```
~0
```

in the shell, it prints

```
0
```

which is of course wrong.  If I type

```
~(0)
```

it correctly print

```
-1
```

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fix the following issues with this PR.
1. Issue with the complement of integer literals.
2. Using the `not` operator with an integer literal. (https://github.com/ballerina-platform/ballerina-lang/issues/29976#issuecomment-820283605) 

Fixes #29976 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 1]
```diff
@@ -1878,9 +1878,10 @@ public BLangNode transform(ListConstructorExpressionNode listConstructorExprNode
     public BLangNode transform(UnaryExpressionNode unaryExprNode) {
         Location pos = getPosition(unaryExprNode);
         SyntaxKind expressionKind = unaryExprNode.expression().kind();
-        if (expressionKind == SyntaxKind.NUMERIC_LITERAL) {
-            BLangNumericLiteral numericLiteral = (BLangNumericLiteral) createSimpleLiteral(unaryExprNode);
-            return numericLiteral;
+        SyntaxKind unaryOperatorKind = unaryExprNode.unaryOperator().kind();
+        if (expressionKind == SyntaxKind.NUMERIC_LITERAL &&
+                         (unaryOperatorKind == SyntaxKind.MINUS_TOKEN || unaryOperatorKind == SyntaxKind.PLUS_TOKEN)) {
+            return createSimpleLiteral(unaryExprNode);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:1884]: Do we need to do this at all?

+(1) and -(1) would not satisfy the if condition, so the path would be different for them vs +1 and -1?

Can you please create an issue for this?

**Review by MaryamZi — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 1 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:1884]: Created(https://github.com/ballerina-platform/ballerina-lang/issues/30020)
