### PR TITLE
Fix issues in the bindgen mappings generated

### LINKED ISSUE #29454: Compile errors in generated bal files using bindgen
**Description:**
$subject.

**Steps to reproduce:**
`bal bindgen java.util.zip.ZipEntry java.util.zip.ZipInputStream`, please run below command.
`bal build` command throws below compile errors.

bindgen

**Affected Versions:**
slpalpha3

### PR DESCRIPTION
**Pull request by IrushiL**
## Purpose
Fixes the following issues in the bindgen mappings generated.
*  Fix issues in the mapping of direct throwable classes.
* Fix a documentation warning for method optional error returns.
* Escape reserved words in project package names.
* Check the access modifier of Java resources before bindgen (only public resources need to be generated).
* Fix the access modifier of the `jObj` field in mapping classes created. The access modifier is now made `public` since it should reflect the exact handle field in the `JObject` for it to be considered as a type of `JObject`. This is needed for the casting functionalities.
* Fix a minor formatting issue that is occurring during the `Ballerina.toml` file update.

Fixes #29454
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/29772
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/29911

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JClass.java [hunk 1]
```diff
@@ -91,7 +98,9 @@ private String getExceptionName(Class exception, String name) {
             // Append the prefix "J" in front of bindings generated for Java exceptions.
             if (this.getClass().getClassLoader().loadClass(Exception.class.getCanonicalName())
                     .isAssignableFrom(exception)) {
-                return "J" + name;
+                String shortClassName = "J" + name;
```
Comment (keizer619) [inline misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JClass.java:101]: @IrushiL As "J" letter has been used in several places, can't we use a constant for that?

File: misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenFileGenerator.java [hunk 2]
```diff
@@ -53,23 +53,19 @@ public BindgenFileGenerator(BindgenEnv env) {
...
-            return generateFromTemplate(jErrorTemplatePath);
-        } else if (!env.isDirectJavaClass()) {
+        if (!env.isDirectJavaClass()) {
             // Generate Ballerina empty class bindings for dependent Java classes.
-            return generateFromTemplate(jEmptyClassTemplatePath);
+            return generateFromTemplate(jEmptyClassTemplatePath, null);
         } else {
             // Generate Ballerina class bindings for Java classes.
-            syntaxTree = generateFromTemplate(jClassTemplatePath);
+            syntaxTree = generateFromTemplate(jClassTemplatePath, null);
```
Comment (keizer619) [inline misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenFileGenerator.java:68]: @IrushiL Instead of passing `null` and check it internally, can't we overload a `generateFromTemplate` method to get alias from `env.getAlias`

File: misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenEnv.java [hunk 3]
```diff
@@ -128,7 +128,7 @@ String getAliasClassName(String alias) {
         return aliases.get(alias);
     }
 
-    void setAlias(String alias, String className) {
+    public void setAlias(String alias, String className) {
```
Comment (keizer619) [inline misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenEnv.java:131]: @IrushiL Now since its public shall we include method comments?

File: misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JClass.java (hunk 1 above)
Comment (IrushiL) [reply misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/model/JClass.java]: Done

File: misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenFileGenerator.java (hunk 2 above)
Comment (IrushiL) [reply misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenFileGenerator.java]: Done

File: misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenEnv.java (hunk 3 above)
Comment (IrushiL) [reply misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenEnv.java:137]: Done

**Review by keizer619 — DISMISSED** [review]

**Review by keizer619 — APPROVED** [review]
