### PR TITLE
Fix native system libraries not getting copied to target classpath

### LINKED ISSUE #19364: Getting CLASS_NOT_FOUND error when running multi-module project which uses a module which provides interoperability with Java
**Description:**
When I try to run one of the modules of a multi-module project which builds successfully (of which the sources are attached in this github issue) I get class not CLASS_NOT_FOUND error.

**Steps to reproduce:**
Download and extract the attached zip file ([blockchain-iam-group-chat.zip](https://github.com/ballerina-platform/ballerina-lang/files/3716150/blockchain-iam-group-chat.zip)) , change directory to "blockchain-iam-group-chat" folder, and issue `ballerina build -a --skip-tests`. You may also have to change the path of the platform.libraries entry of the Ballerina.toml file to match with your environment. The corresponding "utils.jar" is located on the directory "utils-dir".

The project should get build successfully. Next, try to run the module "holder" with the following command.

`ballerina run holder`

Then an error gets thrown as follows,

`error: wso2:utils:main.bal:5:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.ballerina.utils.HexToChar
error: wso2:utils:main.bal:10:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.ballerina.utils.DecToChar
error: wso2:utils:main.bal:15:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.ballerina.utils.EncryptRSAWithPublicKey
error: wso2:utils:main.bal:20:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.ballerina.utils.EncryptRSAWithPublicKeyPlainText
error: wso2:utils:main.bal:25:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.ballerina.utils.EncryptAES
error: wso2:utils:main.bal:30:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.ballerina.utils.DecryptAES
error: wso2:utils:main.bal:35:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.ballerina.utils.BlockChainInterface
error: wso2:utils:main.bal:42:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.ballerina.utils.HashSHA256
error: wso2:utils:main.bal:47:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.ballerina.utils.FileExists
error: wso2:utils:main.bal:52:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.ballerina.utils.StringToBinaryString
error: wso2:utils:main.bal:57:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.ballerina.utils.BinaryStringToString
`

**Affected Versions:**
Ballerina 1.0.2-SNAPSHOT

**OS, DB, other environment details and versions:**
Ubuntu 16.04

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Kishanthan**
Fixes #19364

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyNativeLibTask.java [hunk 1]
```diff
@@ -138,7 +144,35 @@ private void copyImportedLib(BuildContext buildContext, BPackageSymbol importz,
             }
         }
 
-        // If balo cannot be found from target or cache, get dependencies from distribution toml.
+        // If platform libs are defined, copy them to target
+        List<Library> libraries = manifest.getPlatform().libraries;
+        if (libraries != null && libraries.size() > 0) {
+            List<Path> libs = libraries.stream()
```
Comment (lankavitharana) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyNativeLibTask.java]: shall we use the same for loop? instead of streams?

Comment (Kishanthan) [reply cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CopyNativeLibTask.java]: ack, done
