### PR TITLE
Fix syntax API for receive-action

### LINKED ISSUE #26376: Exception thrown when applying a node transformation through the parser
**Description:**

**1.** The following code snippet, which is a parser test [1] throws an exception when applying a node transformation.

```ballerina
function foo() {
    <- default;
    <- b;
    a = <- b;
    a = <- {a};
    a = <- {a, b:c, d};
    <- {default, b:default, d};
}
```
**Exception:**
```sh
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.ReceiveFieldsNode cannot be cast to class io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode (io.ballerina.compiler.syntax.tree.ReceiveFieldsNode and io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode are in unnamed module of loader 'app')
```

**2.** The following `FieldMatchPatternNode` code snippet throws an exception when applying a node transformation.

```ballerina
    match t1 {
        {x: "a"} => {
            int c = 1;
        }
    }
```
**Exception:**
```sh
class io.ballerina.compiler.syntax.tree.IdentifierToken cannot be cast to class io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode (io.ballerina.compiler.syntax.tree.IdentifierToken and io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode are in unnamed module of loader 'app')
```

**3.** The following `ErrorMatchPatternNode` code snippet throws an exception when applying a node transformation.

```ballerina
    match err1 {
        error(var reason) => {
            return reason;
        }
    }
```
**Exception:**
```sh
class io.ballerina.compiler.syntax.tree.Token cannot be cast to class io.ballerina.compiler.syntax.tree.TypeDescriptorNode (io.ballerina.compiler.syntax.tree.Token and io.ballerina.compiler.syntax.tree.TypeDescriptorNode are in unnamed module of loader 'app')
```

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_source_01.bal

**Steps to reproduce:**

**Affected Versions:**
Swan Lake Preview 4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #26420: Exception thrown when the parser traverses through an indexed expression
**Description:**
The exception given below is thrown when the following code snippet is traversed through the TreeModifier of the parser. This seems to happen only when the statement resides inside a block node.

```ballerina
function foo() {
    { 
        foo:bar[a] -> y;
    }
}
```
```sh
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode cannot be cast to class io.ballerina.compiler.syntax.tree.IdentifierToken (io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode and io.ballerina.compiler.syntax.tree.IdentifierToken are in unnamed module of loader 'app')
```

**Steps to reproduce:**

**Affected Versions:**
Swan Lake Preview 4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #26376

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 1]
```diff
@@ -2203,7 +2203,18 @@ public BLangNode transform(TrapExpressionNode trapExpressionNode) {
...
+        Node receiveWorkers = receiveActionNode.receiveWorkers();
+        Token workerName;
+        if (receiveWorkers.kind() == SyntaxKind.SIMPLE_NAME_REFERENCE) {
+            workerName = ((SimpleNameReferenceNode) receiveWorkers).name();
+        } else {
+            // TODO: implement multiple-receive-action support
+            Location receiveFieldsPos = getPosition(receiveWorkers);
+            dlog.error(receiveFieldsPos, DiagnosticErrorCode.MULTIPLE_RECEIVE_ACTION_NOT_YET_SUPPORTED);
+            workerName = NodeFactory.createMissingToken(SyntaxKind.IDENTIFIER_TOKEN,
+                    NodeFactory.createEmptyMinutiaeList(), NodeFactory.createEmptyMinutiaeList());
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:2215]: use `createIdentifier(Location pos, Token token)` method to give a name to the missing identifier. otherwise will cause a null pointer exception at the later process.

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 2]
```diff
@@ -1610,3 +1610,5 @@ error.invalid.isolated.qualifier.on.module.no.init.var.decl=\
 
 error.binding.pattern.not.yet.supported.in.module.var.decl=\
   ''{0}'' binding pattern not yet supported in module variable declaration
+
+error.multiple.receive.action.not.yet.supported=multiple receive action not yet supported
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1614]: Can we add a jballerina-unit-test case to check this error

File: compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json [hunk 3]
```diff
@@ -3297,7 +3297,7 @@
                 },
                 {
                     "name": "receiveWorkers",
-                    "type": "SimpleNameReferenceNode"
+                    "type": "Node"
```
Comment (rdulmina) [inline compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json:3300]: Don't we have parser test cases for multiple receive action?

**Review by rdulmina — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 4]
```diff
@@ -2203,7 +2203,18 @@ public BLangNode transform(TrapExpressionNode trapExpressionNode) {
     @Override
     public BLangNode transform(ReceiveActionNode receiveActionNode) {
         BLangWorkerReceive workerReceiveExpr = (BLangWorkerReceive) TreeBuilder.createWorkerReceiveNode();
-        workerReceiveExpr.setWorkerName(createIdentifier(receiveActionNode.receiveWorkers().name()));
+        Node receiveWorkers = receiveActionNode.receiveWorkers();
+        Token workerName;
+        if (receiveWorkers.kind() == SyntaxKind.SIMPLE_NAME_REFERENCE) {
+            workerName = ((SimpleNameReferenceNode) receiveWorkers).name();
+        } else {
+            // TODO: implement multiple-receive-action support
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:2211]: Any issue to track this?

**Review by rdulmina — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 1 above)
Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:2215]: I see. Then we have to do the same here also? 
https://github.com/ballerina-platform/ballerina-lang/blob/67c6af3df6e9df4db76e2d3300111ca3d0199221/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java#L583-L584

File: compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json (hunk 3 above)
Comment (lochana-chathura) [reply compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json:3300]: We do have. https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-parser/src/test/resources/actions/receive-action/receive_action_source_01.bal

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 4 above)
Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:2211]: yes. #18163

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 1 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:2215]: Ah you are calling `createIdentifier(Token token)` method at the end which will call `createIdentifier(Location pos, Token token)`. So its fine no changes needed

**Review by rdulmina — APPROVED** [review]
