### PR TITLE
Disallow named-args that specify field of included-record which is an arg

### LINKED ISSUE #34566: Compiler crashes when arguments are provided for both the parameter and the individual fields of an included record parameter
**Description:**
$title. Should result in a compilation error.

**Steps to reproduce:**
```ballerina
type Configuration record {|
    int id?;
    string name?;
|};

function fn(*Configuration config) {

}

public function main() {
    fn(id = 1, config = {name: "default"}); // no compilation error
}
```

**Affected Versions:**
slbeta6, 2201.0.0 snapshot build 1

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose

Fixes #34566

### CODE REVIEW

**Comment by MaryamZi** [comment]
@KavinduZoysa, please resolve the conflict.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -18,6 +18,7 @@
 package org.wso2.ballerinalang.compiler.semantics.analyzer;
 
 import io.ballerina.identifier.Utils;
+import io.ballerina.runtime.api.flags.SymbolFlags;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:21]: Why are we importing a runtime class? Please fix.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -7006,6 +7012,27 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
         }
     }
 
+    private void addToIncRecords(BVarSymbol param, List<BRecordType> incRecords) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7015]: We can say 
```suggestion
    private void populateIncludedRecordParams(BVarSymbol param, List<BRecordType> incRecords) {
```

I don't see why we need to shorten `Included` to `Inc`.

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 3]
```diff
@@ -1902,3 +1902,6 @@ error.cannot.infer.type.from.spread.op=\
 
 error.tuple.and.expression.size.does.not.match=\
   tuple and expression size does not match
+
+error.named.arg.not.allowed.with.included.record.param=\
+  named-arg ''{0}'' not allowed with included-record-param ''{1}''
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1907]: We shouldn't directly use productions from the grammar, these aren't things we expect the user to know.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1907]: This error currently doesn't describe the actual issue anyway. It reads like we can't specify a named argument when there is an included record parameter in the function.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Changed, 
`Inc` is used in order to align with other usages of this file.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Changed

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 3 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: Changed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 4]
```diff
@@ -7024,6 +7029,28 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
...
+        }
+    }
+
+    // If there is a named-arg or positional-arg corresponding to an included-record-param,
+    // it is an error for a named-arg to specify a field of that included-record-param.
+    private void checkSameNamedArgsInIncRecords(List<BLangExpression> namedArgs, List<BRecordType> incRecords) {
+        for (BLangExpression namedArg : namedArgs) {
+            String argName = ((NamedArgNode) namedArg).getName().value;
+            for (BRecordType record : incRecords) {
+                if (record.fields.containsKey(argName)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7044]: This check isn't correct. It disallows the following also, but it should work.

```ballerina
type Rec record {|
    never a?;
    int b;
|};

function fn(string a, *Rec rec) {

}

public function main() {
    fn(a = "", rec = {b: 2});
}
```

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 5]
```diff
@@ -1905,3 +1905,6 @@ error.tuple.and.expression.size.does.not.match=\
 
 error.infer.size.only.supported.in.the.first.dimension=\
   inferred array size is only allowed in the first dimension of an array type descriptor
+
+error.named.arg.not.allowed.included.in.included.record.param=\
+  named arg ''{0}'' is not allowed since it is a filed in ''{1}'' which is an arg
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1910]: Typo - filed -> field.

Like I mentioned previously, error messages need to be as complete and clear as possible, since these are for users. We should use the full form `argument`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 4 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7044]: Please add a test also.

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 5 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1910]: The error is still not clear IMO. It is not that the named argument is not allowed, it's that you can only specify one of the two.

I would use something like

```suggestion
  duplicate argument for ''{0}'' via named argument and argument for included record parameter
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 4 above)
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7044]: Alternatively you can collect all the field names in a list first, to avoid retrieving and iterating through all the fields per named argument.

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 5 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1910]: Please update the diagnostic and the key also to better reflect the error.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 6]
```diff
@@ -6788,6 +6788,8 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
             }
         }
 
+        List<BRecordType> incRecords = new ArrayList<>();
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6791]: Let's use `included` in whatever new construct you're adding.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 4 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7044]: Can probably update `populateIncludedRecordParams` to do this.

**Review by MaryamZi — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 6 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6791]: Here we can use `incRecordParams` list instead of creating a new list.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 7]
```diff
@@ -6834,6 +6837,8 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
                     dlog.error(arg.pos, DiagnosticErrorCode.UNDEFINED_PARAMETER, argName);
                     break;
                 }
+                populateIncludedRecordParams(varSym, incRecords);
+                namedArgs.add(arg);
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6841]: Without creating a separate list for named arguments can't we refactor the overall logic as follows,
- When visiting a named arg we can check whether the symbol of that argument in the `incRecordParams` list or not

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 8]
```diff
@@ -7024,6 +7029,28 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
...
+    // If there is a named-arg or positional-arg corresponding to an included-record-param,
+    // it is an error for a named-arg to specify a field of that included-record-param.
+    private void checkSameNamedArgsInIncRecords(List<BLangExpression> namedArgs, List<BRecordType> incRecords) {
+        for (BLangExpression namedArg : namedArgs) {
+            String argName = ((NamedArgNode) namedArg).getName().value;
+            for (BRecordType record : incRecords) {
+                if (record.fields.containsKey(argName)) {
+                    dlog.error(namedArg.pos,
+                            DiagnosticErrorCode.NAMED_ARG_NOT_ALLOWED_INCLUDED_IN_INCLUDED_RECORD_PARAM, argName,
+                            record.tsymbol.name);
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7047]: Consider the below example
```ballerina
type Configuration record {|
    int id?;
    string name = "";
|};

function fn(*Configuration config) {

}

public function main() {
    fn(id = 1, config = {name: "default"});
    // fn(id = 1, name = "");
    // fn({name: "default"}, id = 1);
}

```
With the current approach, we give the error to `id=1`. IMO actual error with the ` config = {name: "default"}`.
Any thoughts @MaryamZi

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 5 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: Changed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 6 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: This won't work, we need to get the included record params from caller, but `incRecordParams` is created using function signature.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 7 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6843]: Changed the logic, please check

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 4 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Added

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Changed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 9]
```diff
@@ -7024,6 +7029,28 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
...
 
+    private void populateIncludedRecordParams(BVarSymbol param, List<BRecordType> incRecords) {
+        if (Symbols.isFlagOn(param.flags, Flags.INCLUDED)) {
+            incRecords.add((BRecordType) Types.getReferredType(param.type));
+        }
+    }
+
+    // If there is a named-arg or positional-arg corresponding to an included-record-param,
+    // it is an error for a named-arg to specify a field of that included-record-param.
+    private void checkSameNamedArgsInIncRecords(List<BLangExpression> namedArgs, List<BRecordType> incRecords) {
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Changed

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal [hunk 10]
```diff
@@ -194,3 +194,67 @@ function functionWithIncludedRecordParam14(int a, *Options options, int c = 10)
...
+    int id?;
+    string name?;
+|};
+
+function fn2(*Record2 record2) {
+
+}
+
+function functionWithIncludedRecordParam16() {
+    fn1(id = 2, record1 = {id: 2, name: ""}); // error
```
Comment (rdulmina) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:217]: Shouldn't we be using `{id: 2, name: ""}` 's pos for the error pos since value for field `id` is actually duplicated there?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 8 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: @chiranSachintha, is your concern the same as https://github.com/ballerina-platform/ballerina-lang/pull/35800#discussion_r874452262? That we need to try and fix to give for the second occurrence onward.

I think your particular example is an interesting case, because the argument for `config` doesn't actually specify a value for `id`. But we don't always know this since the argument for `config` may be a variable reference.

```ballerina
    Configuration config = {name: "default"};
    fn(id = 1, config = config);
```

I think it's OK for it to be an error, but may be we should reword the error for optional fields. E.g.,
```cmd
duplicate arguments may have been specified for 'id' via the named argument and the argument for the included record parameter
```

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: If the argument for `config` doesn't actually specify a value for `id` then the value for `id` will be nil right? so it's anyway going to duplicate `id=1`?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: No, `id` is an optional field (rather than a nilable field with nil as the default value, in which case the value will be nil).

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 11]
```diff
@@ -6782,12 +6782,16 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
             requiredParams.add(nonRestParam);
         }
 
+        List<String> includedRecordParamNames = new ArrayList<>();
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6785]: Shall we try to populate data structures with the initial sizes? This will improve performance. I believe java already has set this to 16 which is not accurate for our code. It is fine if it is not the exact amount but setting it to the original list size will prevent using extra memory and processor usage shift elements in arrays,

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 12]
```diff
@@ -7024,6 +7031,27 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
...
+    }
+
+    // If there is a named-arg or positional-arg corresponding to an included-record-param,
+    // it is an error for a named-arg to specify a field of that included-record-param.
+    private void checkSameNamedArgsInIncludedRecords(List<BLangExpression> namedArgs, List<String> incRecordFields,
+                                                     List<String> includedRecordParamNames) {
+        incRecordFields.removeIf(field -> !includedRecordParamNames.contains(field));
+        for (BLangExpression namedArg : namedArgs) {
+            String argName = ((NamedArgNode) namedArg).getName().value;
+            if (incRecordFields.contains(argName)) {
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7048]: Since we do searching here I believe a hash set is the more accurate data structure here. Searching on array list is O(n) where we are doing lots of searching here inside another loop making it O(n<sup>2</sup>).

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 8 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Changed the error message

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal (hunk 10 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:217]: I think it is matched with the error message we use,
`duplicate arguments may have been specified for ''{0}'' via the named argument and the argument for the \
  included record parameter`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 11 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Changed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 12 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7048]: Changed, thank you for the comment

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 8 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Seems like you have changed it for the non-optional case also.

```ballerina
type Foo record {
    int id;
    string name;
};

function fn(*Foo record1) {

}

public function main() {
    fn(id = 2, record1 = {id: 2, name: ""});
}
```

Here, `id` is definitely duplicated. So saying "duplicate arguments may have been specified" isn't quite right.

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Both optional case and non-optional case both fall into the following sentence in the spec right?
```
If there is a named-arg or positional-arg corresponding to an included-record-param, it is an error for a named-arg to specify a field of that included-record-param. 
```
Therefore error messages should be same right?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Not necessarily. We need to make sure we are properly communicating what the issue is to the user.

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Okay, For this case, you mean having the word `may` is not necessary in `duplicate arguments may have been specified` right?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Yes. Basically have two different errors for the optional and non-optional case.

Or we can actually say something like

```
cannot specify a named argument for a field of an included record parameter when an argument is specified for the included record parameter
```

This is more in-line with the spec. The errors have to be for the arguments for the fields.

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Changed

**Comment by MaryamZi** [comment]
As discussed, let's include the fix for https://github.com/ballerina-platform/ballerina-lang/issues/35691 also.

**Comment by KavinduZoysa** [comment]
> As discussed, let's include the fix for #35691 also.

```ballerina
public type Condition record {|
    never 'table?;
    never rowType?;
    anydata...;
|};
isolated function getRecord(*Condition condition) {};

public function main() {
    getRecord({"id":3}, id = 1);
}
```
@MaryamZi, For the above example mentioned in #3569, I think the error message we should get is, `too many arguments in call to 'getRecord()'`.
Because spec says, 
```
The result of evaluating the i-th positional-arg becomes the i-th member of the argument list. 
The static type of the expression for the i-th positional-arg must be a subtype of the type declared for the i-th parameter 
that is not a rest-param, if there is such a parameter; otherwise, there must be a rest-param and 
the static type must be a subtype of the type declared for the rest-param.
```
The 1st arg which is a positional arg `{"id":3}` matches the includes record param `*Condition condition` and there is not a param for 2nd arg. 
WDYT?

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 13]
```diff
@@ -178,6 +178,8 @@ public enum DiagnosticErrorCode implements DiagnosticCode {
     INVALID_SPREAD_OP_FIXED_MEMBER_EXPECTED("BCE2134", "invalid.spread.operator.fixed.member.expected"),
     CANNOT_INFER_TYPE_FROM_SPREAD_OP("BCE2135", "cannot.infer.type.from.spread.op"),
     TUPLE_AND_EXPRESSION_SIZE_DOES_NOT_MATCH("BCE2136", "tuple.and.expression.size.does.not.match"),
+    CANNOT_SPECIFY_NAMED_ARG_FOR_FIELD_OF_INCLUDED_RECORD_PARAM("BCE2137",
+            "cannot.specify.named.argument.for.field.of.included.record.parameter"),
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:182]: This isn't comprehensive and kinda misleading, right? Shall we update this to reflect the actual error?

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java]: Changed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 14]
```diff
@@ -6783,12 +6783,16 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
             requiredParams.add(nonRestParam);
         }
 
+        List<String> includedRecordParamNames = new ArrayList<>(incRecordParams.size());
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6786]: Aren't these actually `includedRecordParamFieldNames`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 15]
```diff
@@ -7025,6 +7037,30 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
         }
     }
 
+    private void populateIncludedRecordParams(BVarSymbol param, HashSet<String> includedRecordFields,
+                                              List<String> includedRecordParamNames) {
+        Set<String> fields = ((BRecordType) Types.getReferredType(param.type)).fields.keySet();
+        fields.removeIf(field -> !includedRecordParamNames.contains(field));
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7043]: This will remove the field from the underlying `BRecordType` also since we are operating on the keys returned by `keySet()`.

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/LinkedHashMap.html#keySet()

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7043]: What's an example for when this will be true?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 14 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Changed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 15 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7043]: Changed.

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7043]: Ex:
```ballerina
type Foo record {
    never a?;
    int b;
};

function callFoo(int a, *Foo foo) returns int {
    return a + foo.b;
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 16]
```diff
@@ -7025,6 +7037,30 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
         }
     }
 
+    private void populateIncludedRecordParams(BVarSymbol param, HashSet<String> includedRecordFields,
+                                              List<String> includedRecordParamNames) {
+        Set<String> fields = new HashSet<>(((BRecordType) Types.getReferredType(param.type)).fields.keySet());
+        fields.removeIf(field -> !includedRecordParamNames.contains(field));
+        includedRecordFields.addAll(fields);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7044]: Why aren't we just iterating over `((BRecordType) Types.getReferredType(param.type)).fields.keySet()` and directly adding to `includedRecordFields`? We don't need the extra set?
