### PR TITLE
Propagate XMLNS to query scope

### LINKED ISSUE #34024: Namespace issue in XML template and query
**Description:**
Please see the code snippet below.

**Steps to reproduce:**

```
$ cat test.bal 
import ballerina/io;
public function main() {
    // xml`<a>${a}</a>` works as expected
    // but
    // xml`<ns:a>${a}</ns:a>` gives a compilation error

    xmlns "namespace" as ns;
    final xml x = xml`<ns:root xmlns:ns="namespace">
        ${from string a in ["A1", "A2"] select xml`<ns:a>${a}</ns:a>`}
    </ns:root>`;

    io:println("----------");
    io:println(x);
}

$ bal build test.bal 
Compiling source
        test.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2021-11-26 17:17:34,107] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:164)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:443)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:126)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:126)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:401)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:103)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:103)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:82)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:268)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:416)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:353)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:280)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [.:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```

**Affected Versions:**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

$ bal version
Ballerina Swan Lake Beta 4
Language specification 2021R1
Update Tool 1.3.6
$ 
```

### LINKED ISSUE #35653: BIR Optimiser throughs NPE for xml templating through query expression
**Description:**
$subject
```
 var processedEmployees = from var {employeeId, gasFillUpCount, totalFuelCost, totalGallons, totalMilesAccrued} in processedEntries
                            select xml `<s:employeeFuelRecord employeeId="${employeeId}">
                                            <s:gasFillUpCount>${gasFillUpCount}</s:gasFillUpCount>
                                            <s:totalFuelCost>${totalFuelCost}</s:totalFuelCost>
                                            <s:totalGallons>${totalGallons}</s:totalGallons>
                                            <s:totalMilesAccrued>${totalMilesAccrued}</s:totalMilesAccrued>
                                        </s:employeeFuelRecord>`;
```

Stack trace
```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:164)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:445)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:126)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:126)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:403)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:103)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:103)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:82)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:271)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:265)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 ```

**Steps to reproduce:**

**Affected Versions:**
2201.0.2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #36014: NPE during BIR generation when local XMLNS used within query expression
**Description:**
```ballerina
function dummyTest() {
    xmlns "http://www.so2w.org" as localNS;
    xml x5 = from int i in 1 ... 3
        select xml `<empRecord employeeId="${i}"><localNS:id>${i}</localNS:id></empRecord>`;
}
```

**Steps to reproduce:**

**Affected Versions:**
SL 2201.0.3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #36091: NPE when trying to build a xml payload.
Below is the code snippet that I was trying.

EmployeeFillUpSummary[] perEmployeeRecordArray = [];

xml processedPayload = xml `<s:employeeFuelRecords xmlns:s="http://www.so2w.org">
    ${from var {employeeId, gasFillUpCount, totalFuelCost, totalGallons, totalMilesAccrued} in perEmployeeRecordArray
           select xml`<s:employeeFuelRecord employeeId="${employeeId}">
           <s:gasFillUpCount>${gasFillUpCount}</s:gasFillUpCount>
           <s:totalFuelCost>${totalFuelCost}</s:totalFuelCost>
           <s:totalGallons>${totalGallons}</s:totalGallons>
           <s:totalMilesAccrued>${totalMilesAccrued}</s:totalMilesAccrued>
           </s:employeeFuelRecord>
           `}
    </s:employeeFuelRecords>`;

type EmployeeFillUpSummary record {
    int employeeId;
    int gasFillUpCount;
    float totalFuelCost;
    float totalGallons;
    int totalMilesAccrued;
};

Stack trace:

[2022-05-11 12:59:14,529] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:164)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:445)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:126)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:126)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:403)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:103)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:103)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:82)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:273)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:166)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:135)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:123)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:265)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [problem_1_4:(1:1,1:1)] Compilation failed due to an unhandled exception

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #35653 
Fixes #36014
Fixes #34024
Fixes #36091

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 1]
```diff
@@ -408,11 +413,12 @@ BLangVariableReference buildStream(List<BLangNode> clauses, BType resultType, Sy
                     addStreamFunction(block, initPipeline, orderFunc);
                     break;
                 case SELECT:
-                    BLangVariableReference selectFunc = addSelectFunction(block, (BLangSelectClause) clause);
+                    BLangVariableReference selectFunc = addSelectFunction(block, (BLangSelectClause) clause,
+                            stmtsToBePropagated);
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:417]: Why do we have to inject namespaces explicitly into these block? How is it different from a local variable declaration declared in the same scope?

Since we have injected it only to select and do cases. If we use it in another clause, the compiler still crashes.
e.g.
```bal
public function main() {
    xmlns "http://www.so2w.org" as localNS;
    xml x = from int i in 1 ... 3 let xml y = xml `<empRecord employeeId="${i}"><localNS:id>${i}</localNS:id></empRecord>`
        select xml `<record>${y}</record>`;
}
```

Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:417]: Why do we have to inject namespaces explicitly into these block? How is it different from a local variable declaration declared in the same scope?

Since we have injected it only to select and do cases. If we use it in another clause, the compiler still crashes.
e.g.
```bal
public function main() {
    xmlns "http://www.so2w.org" as localNS;
    xml x = from int i in 1 ... 3 let xml y = xml `<empRecord employeeId="${i}"><localNS:id>${i}</localNS:id></empRecord>`
        select xml `<record>${y}</record>`;
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 2]
```diff
@@ -3380,6 +3383,8 @@ public void visit(BLangPanic panicNode) {
     @Override
     public void visit(BLangXMLNSStatement xmlnsStmtNode) {
         xmlnsStmtNode.xmlnsDecl = rewrite(xmlnsStmtNode.xmlnsDecl, env);
+        //need to propagate the local namespace to be used at the select clause
+        this.stmtsToBePropagatedToQuery.add(xmlnsStmtNode);
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:3387]: Here we are just blindly adding xmlns declaration without taking the scope into account. Therefore, namespaces declared outside the scope also get declared in the query.  If shadowing takes place could this be problem?

e.g.
```bal
xmlns "x.org" as localNS;

function foo() {
    xmlns "y.org" as localNS;
}

function bar() {
    xmlns "z.org" as localNS;
    foo();
    xml x = from int i in 1 ... 3
        select xml `<empRecord employeeId="${i}"><localNS:id>${i}</localNS:id></empRecord>`;
}
```

Here `localNS` in query refers to whatever last visited `BLangXMLNSStatement` I guess. But, visiting order should not be matter. Scope should matter.

Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:3387]: Here we are just blindly adding xmlns declaration without taking the scope into account. Therefore, namespaces declared outside the scope also get declared in the query.  If shadowing takes place could this be problem?

e.g.
```bal
xmlns "x.org" as localNS;

function foo() {
    xmlns "y.org" as localNS;
}

function bar() {
    xmlns "z.org" as localNS;
    foo();
    xml x = from int i in 1 ... 3
        select xml `<empRecord employeeId="${i}"><localNS:id>${i}</localNS:id></empRecord>`;
}
```

Here `localNS` in query refers to whatever last visited `BLangXMLNSStatement` I guess. But, visiting order should not be matter. Scope should matter.

Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:3387]: Maybe we can do the following. 
Keep this as it is here. At the place we call query desugar, we filter the list and only propagate the once declared in the scope. For filtering, we can use `env.scope.entries`

**Review by gimantha — APPROVED** [review]

**Review by lochana-chathura — APPROVED** [review]
