### PR TITLE
Change the formatter implementation to use the new parser

### LINKED ISSUE #24602: Complete the Ballerina formatter implementation
**Description:**
Complete the Ballerina formatter implementation using the new (Swan Lake) parser. The following needs to be completed.

- [x] Move current implementation residing inside the `language-server-compiler` to a different module which is only dependent on the parser.
- [x] The API should be finalized.
- [x] Formatter options should be defined, this will be part of the API.
- [x] Test FW should be implemented.
- [x] Support full and partial formatting.
- [x] Util to parse a string and format.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by IrushiL**
## Purpose

Fixes #24602

## Check List 
- [X] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatCmd.java [hunk 1]
```diff
@@ -0,0 +1,64 @@
+/*
+ * Copyright (c) 2019, WSO2 Inc. (http://wso2.com) All Rights Reserved.
```
Comment (keizer619) [inline misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatCmd.java:2]: @IrushiL ; Does this have to be 2020?

**Comment by anupama-pathirage** [comment]
@IrushiL This pr topic does not adhere to our guidelines. Refer https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md for details.
We follow https://chris.beams.io/posts/git-commit/ for commit messages and PR topics.
Pls change the PR topic accordingly.
Basically a properly formatted Git commit subject line/PR topic should always be able to complete the following sentence:
If applied, this commit will your subject line here

File: misc/formatter/modules/formatter-cli/src/test/java/org/ballerinalang/formatter/cli/FormatCmdTest.java [hunk 2]
```diff
@@ -0,0 +1,183 @@
...
+    private static final Path RES_DIR = Paths.get("src/test/resources/").toAbsolutePath();
+
+    @Test(description = "Test to check the exception for too many argument provided.")
+    public void formatCLITooManyArgumentsTest() {
+        Path sourceRoot = RES_DIR.resolve("notAProject");
+        List<String> argList = new ArrayList<>();
+        argList.add("pkg2");
+        argList.add("asd");
+        try {
+//            FormatUtil.execute(argList, false, false, sourceRoot);
```
Comment (suganyasuven) [inline misc/formatter/modules/formatter-cli/src/test/java/org/ballerinalang/formatter/cli/FormatCmdTest.java:42]: Why this is commented everywhere?

Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/test/java/org/ballerinalang/formatter/cli/FormatCmdTest.java:42]: This is still under implementation.

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatCmd.java (hunk 1 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatCmd.java:2]: Thanks, will change this.

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java [hunk 3]
```diff
@@ -0,0 +1,358 @@
...
+    }
+
+    private static void formatAndWrite(BLangCompilationUnit compilationUnit, Path sourceRootPath,
+                                       List<String> formattedFiles, boolean dryRun) throws IOException {
+        String fileName = sourceRootPath.toString() + File.separator
+                + "src"
+                + File.separator
+                + compilationUnit.getPosition().getSource().getPackageName()
+                + File.separator
+                + compilationUnit.getPosition().getSource().getCompilationUnitName();
```
Comment (hemikak) [inline misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java:223]: If there a bal files inside nested directories of the module directory, do they get visited ?

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatCmd.java [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+    private static final String USER_DIR = "user.dir";
+    private static final String NOT_SUPPORTED_MESSAGE = "user.dir";
+
+    @CommandLine.Parameters
+    private List<String> argList;
+
+    @CommandLine.Option(names = {"-h", "--help"}, hidden = true)
+    private boolean helpFlag;
+
+    @CommandLine.Option(names = {"-d", "--dry-run"}, hidden = true)
```
Comment (hemikak) [inline misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatCmd.java:40]: Dry run is hidden ? Why ?

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java [hunk 5]
```diff
@@ -0,0 +1,358 @@
...
+                    // If file is a regular file but not a ballerina source file
+                    // throw the following exception.
+                    throw LauncherUtils.createLauncherException(Messages.getNotABallerinaFile());
+                } else {
+                    moduleName = argList.get(0);
+
+                    // Check whether the module dir exists.
+                    if (!FormatUtil.isModuleExist(moduleName, sourceRootPath)) {
+                        // If module directory doesn't exist and contains a "."
+                        // throw a exception to say file or module doesn't exist.
```
Comment (azinneera) [inline misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java:123]:
```suggestion
                        // throw an exception to say file or module doesn't exist.
```

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java [hunk 6]
```diff
@@ -0,0 +1,358 @@
...
+     */
+    private static CompilerContext getCompilerContext(Path sourceRootPath) {
+        CompilerPhase compilerPhase = CompilerPhase.DEFINE;
+        CompilerContext context = new CompilerContext();
+        CompilerOptions options = CompilerOptions.getInstance(context);
+        options.put(PROJECT_DIR, sourceRootPath.toString());
+        options.put(OFFLINE, Boolean.toString(false));
+        options.put(COMPILER_PHASE, compilerPhase.toString());
+        options.put(SKIP_TESTS, Boolean.toString(false));
+        options.put(TEST_ENABLED, "true");
```
Comment (hemikak) [inline misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java:271]: Should tests run ?

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java [hunk 7]
```diff
@@ -0,0 +1,358 @@
...
+        return modulePath.toFile().isDirectory();
+    }
+
+    /**
+     * Check whether the given path isn't a source root of a ballerina project.
+     *
+     * @param path - path where the command is executed from
+     * @return {@link boolean} true or false
+     */
+    private static boolean notABallerinaProject(Path path) {
```
Comment (hemikak) [inline misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java:304]: Better function name would be `isBallerinaProject` instead of negative reply.

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java [hunk 8]
```diff
@@ -0,0 +1,358 @@
...
+                List<String> formattedFiles = new ArrayList<>();
+                // Iterate and format all the ballerina packages.
+                for (BLangPackage bLangPackage : packages) {
+                    formattedFiles.addAll(iterateAndFormat(bLangPackage, sourceRootPath, dryRun));
+                }
+
+                generateChangeReport(formattedFiles, dryRun);
+            }
+        } catch (IOException | NullPointerException e) {
+            throw LauncherUtils.createLauncherException(Messages.getException());
```
Comment (azinneera) [inline misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java:155]: Shall we append the original exception `e` as well? That would  give more information on the error.

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java [hunk 9]
```diff
@@ -0,0 +1,358 @@
...
+            }
+            fileWriter.write(content);
+        } finally {
+            if (fileWriter != null) {
+                fileWriter.close();
+            }
+        }
+    }
+
+    private static boolean doChangesAvailable(String originalSource, String formattedSource) {
```
Comment (hemikak) [inline misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java:330]: Does `areChangesAvailable` makes sense instead of `doChangesAvailable` ?

File: misc/formatter/modules/formatter-cli/src/main/resources/META-INF/services/org.ballerinalang.tool.BLauncherCmd [hunk 10]
```diff
@@ -0,0 +1 @@
+
```
Comment (hemikak) [inline misc/formatter/modules/formatter-cli/src/main/resources/META-INF/services/org.ballerinalang.tool.BLauncherCmd:1]: Should there be an entry in this ?

File: misc/formatter/modules/formatter-cli/src/test/java/org/ballerinalang/formatter/cli/FormatCmdTest.java [hunk 11]
```diff
@@ -0,0 +1,184 @@
...
+import java.nio.file.Path;
+import java.nio.file.Paths;
+import java.util.ArrayList;
+import java.util.List;
+
+/**
+ * Format CLI tool test suit for testing tool's exceptions.
+ */
+public class FormatCmdTest {
+    private static final Path RES_DIR = Paths.get("src/test/resources/").toAbsolutePath();
```
Comment (hemikak) [inline misc/formatter/modules/formatter-cli/src/test/java/org/ballerinalang/formatter/cli/FormatCmdTest.java:33]: Will this work in windows ? Using `resolve` function would help. `Paths.get("src").resolve("test").resolve("resources").toAbsolutePath()

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java [hunk 12]
```diff
@@ -0,0 +1,115 @@
...
+import io.ballerinalang.compiler.text.LineRange;
+import io.ballerinalang.compiler.text.TextDocument;
+import io.ballerinalang.compiler.text.TextDocuments;
+
+/**
+ * Class that exposes the formatting APIs.
+ */
+public class Formatter {
+
+    // TODO: Add test cases for syntax error scenarios as well
```
Comment (hemikak) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java:29]: Is this TODO still valid ?

File: misc/formatter/modules/formatter-cli/src/test/java/org/ballerinalang/formatter/cli/FormatCmdTest.java (hunk 11 above)
Comment (hemikak) [reply misc/formatter/modules/formatter-cli/src/test/java/org/ballerinalang/formatter/cli/FormatCmdTest.java:33]: Check for other similar places

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java [hunk 13]
```diff
@@ -0,0 +1,358 @@
...
+        CompilerContext context = getCompilerContext(sourceRoot);
+        Compiler compiler = Compiler.getInstance(context);
+        // Set an EmptyPrintStream to hide unnecessary outputs from compiler.
+        compiler.setOutStream(emptyPrintStream);
+        return compiler.compile(moduleName);
+    }
+
+    private static void formatAndWrite(BLangCompilationUnit compilationUnit, Path sourceRootPath,
+                                       List<String> formattedFiles, boolean dryRun) throws IOException {
+        String fileName = sourceRootPath.toString() + File.separator
```
Comment (hemikak) [inline misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java:218]: You can use `Paths.get().resolve()....` instead of using File.separator

Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java]: Done

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java (hunk 12 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java]: Yes, but moved it into `FormatterTest` class since it is more applicable there.

File: misc/formatter/modules/formatter-cli/src/test/java/org/ballerinalang/formatter/cli/FormatCmdTest.java (hunk 11 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/test/java/org/ballerinalang/formatter/cli/FormatCmdTest.java]: Done

File: misc/formatter/modules/formatter-cli/src/main/resources/META-INF/services/org.ballerinalang.tool.BLauncherCmd (hunk 10 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/main/resources/META-INF/services/org.ballerinalang.tool.BLauncherCmd]: This was done to keep the previous ballerina-formatter CLI working instead of this one which is for the new parser. But now the previous ballerina-formatter CLI tool is removed and this one is enabled.

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java (hunk 9 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java]: Done

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java (hunk 8 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java]: Done

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java (hunk 7 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java]: Done

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java (hunk 6 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java]: Since this is for the formatting purpose, running tests is not required.

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java (hunk 5 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java]: Done

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatCmd.java (hunk 4 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatCmd.java]: Removed the hidden attribute.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java [hunk 14]
```diff
@@ -0,0 +1,113 @@
...
+
+    /**
+     * Formats a line range of the provided SyntaxTree. All the nodes falling within the line range
+     * specified will be formatted.
+     *
+     * @param syntaxTree The complete SyntaxTree, of which a part is to be formatted
+     * @param range LineRange which specifies the range to be formatted
+     * @return The modified SyntaxTree after formatting changes
+     */
+    public static SyntaxTree format(SyntaxTree syntaxTree, LineRange range) {
```
Comment (pramodya1994) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java:47]: Method never used

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java [hunk 15]
```diff
@@ -0,0 +1,113 @@
...
+    }
+
+    /**
+     * Formats the provided source string while using the formatting options provided.
+     *
+     * @param source A Ballerina source in string form
+     * @param options Formatting options that are to be used when formatting
+     * @return A modified source string after formatting changes
+     */
+    public static String format(String source, FormattingOptions options) {
```
Comment (pramodya1994) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java:68]:
```suggestion
    private static String format(String source, FormattingOptions options) {
```

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java [hunk 16]
```diff
@@ -0,0 +1,113 @@
...
+    /**
+     * Formats a line range of the provided SyntaxTree while using the formatting options provided. All the
+     * nodes falling within the line range provided will be formatted.
+     *
+     * @param syntaxTree The complete SyntaxTree, of which a part is to be formatted
+     * @param range LineRange which needs to be formatted
+     * @param options Formatting options that are to be used when formatting
+     * @return The modified SyntaxTree after formatting changes
+     */
+    public static SyntaxTree format(SyntaxTree syntaxTree, LineRange range, FormattingOptions options) {
```
Comment (pramodya1994) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java:88]:
```suggestion
    private static SyntaxTree format(SyntaxTree syntaxTree, LineRange range, FormattingOptions options) {
```

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java [hunk 17]
```diff
@@ -0,0 +1,113 @@
...
+    }
+
+    /**
+     * Formats the provided SyntaxTree while using the formatting options provided.
+     *
+     * @param syntaxTree The SyntaxTree which is to be formatted
+     * @param options Formatting options that are to be used when formatting
+     * @return The modified SyntaxTree after formatting changes
+     */
+    public static SyntaxTree format(SyntaxTree syntaxTree, FormattingOptions options) {
```
Comment (pramodya1994) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java:105]:
```suggestion
    private static SyntaxTree format(SyntaxTree syntaxTree, FormattingOptions options) {
```

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java (hunk 14 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java:47]: This is an API exposed by the formatter core.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java (hunk 15 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java:68]: This is an API exposed by the formatter core, it is to be used by other modules such as the lang-sever and the formatter CLI.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java (hunk 16 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java:88]: This is an API exposed by the formatter core, it is to be used by other modules such as the lang-sever and the formatter CLI.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java (hunk 17 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/Formatter.java:105]: This is an API exposed by the formatter core, it is to be used by other modules such as the lang-sever and the formatter CLI.

File: misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java (hunk 3 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-cli/src/main/java/org/ballerinalang/formatter/cli/FormatUtil.java]: This `formatAndWrite` function is called iteratively for each `BLangCompilationUnit`. The `getCompilationUnits()` function used to obtain the compilation units resolves the `.bal` files residing inside subdirectories as well.

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/expressions/StringTemplateExpressionsTest.java [hunk 18]
```diff
@@ -0,0 +1,54 @@
...
+import java.nio.file.Paths;
+import java.util.Collections;
+import java.util.List;
+
+/**
+ * Test the formatting of string template expressions.
+ *
+ * @since 2.0.0
+ */
+public class StringTemplateExpressionsTest extends FormatterTest {
```
Comment (hevayo) [inline misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/expressions/StringTemplateExpressionsTest.java:32]: Why do we have a test class for each expression or construct type. Can we simply rely on a file structure to organize the test cases and run from a single test runner.

Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/expressions/StringTemplateExpressionsTest.java:32]: Here the test classes extend a single test runner but there are test classes added for each subcategory since some of these subcategories contain a lot of test cases. But since this results in a large number of test classes, I will try to refactor this in the future.
