### PR TITLE
Fix `typeOf()` working for the whole named-arg node

### LINKED ISSUE #33944: [Semantic API] `typeOf()` works for the whole named-arg node
Consider the following:
```ballerina
foo(name, <1>age = <2>val<3>);
```
Currently `typeOf()` works for `(1, 3)` as well. But it should only work for `(2, 3)`.

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #33944 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by nadeeshaan — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java [hunk 1]
```diff
@@ -293,7 +294,7 @@ private BSymbol findSymbolAtCursorPosition(Document sourceDocument, LinePosition
         NodeFinder nodeFinder = new NodeFinder(false);
         BLangNode node = nodeFinder.lookup(compilationUnit, range);
 
-        if (!(node instanceof BLangExpression) && !isObjectConstructorExpr(node) && !isAnonFunctionExpr(node)) {
+        if (!isNonNamedArgExprNode(node) && !isObjectConstructorExpr(node) && !isAnonFunctionExpr(node)) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java:297]: This will skip named args entirely. What we need is to disallow the behaviour illustrated in #33944

**Review by mohanvive — APPROVED** [review]
