### PR TITLE
Install GraalVM in Windows pipeline and enable/fix tests on Windows

### LINKED ISSUE #41150: [Task]: Enable Cli tests on Windows
### Description

$Subject

### Describe your task(s)

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Shadow-Devil**
## Purpose
Currently the windows pipeline in `master_push.yml` fails.

This is fixed via:
- Installing GraalVM also for windows
- Fixing a testcase in cli, where the path would contain `\`, but the expected output uses `/`.

It also enables the cli testcases to be run for pull requests so any failure is caught directly in the PR.

See run: https://github.com/ballerina-platform/ballerina-lang/actions/runs/9680086263/job/26707447916
Build Scan: https://gradle.com/s/dryxkslqfonx4

Other notable changes:
- Fix Shell-cli testcases on windows and enable them in both PR and master pipelines
- Fixes links in the shell-cli README.md

Fixes #41150

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by Shadow-Devil** [comment]
@warunalakshitha could you please take a look at this PR? This is a continuation of #42797 and #42970 and should fix the remaining failing test cases on Windows. Thank you in advance :)

File: cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BuildCommandTest.java [hunk 1]
```diff
@@ -917,15 +917,13 @@ public void testBuildWithCorruptedDependenciesToml() throws IOException {
         BuildCommand buildCommand = new BuildCommand(projectPath, printStream, printStream, false);
         new CommandLine(buildCommand);
         buildCommand.execute();
-        String buildLog = readOutput(true);
-        Assert.assertEquals(
-                buildLog.replaceAll("\r", ""),
-                getOutput("corrupted-dependencies-toml.txt").replaceAll("\r", ""));
+        String buildLog = readOutput(true).replace("\r", "").replace("\\", "/");
```
Comment (azinneera) [inline cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BuildCommandTest.java:920]: We maintain separate test output files for Windows and Unix. We can simply fix the corresponding file here without changing the code. The file related to this test is https://github.com/ballerina-platform/ballerina-lang/blob/master/cli/ballerina-cli/src/test/resources/test-resources/command-outputs/windows/corrupted-dependencies-toml.txt

Comment (Shadow-Devil) [reply cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BuildCommandTest.java]: Fixed in [842b3ee](https://github.com/ballerina-platform/ballerina-lang/pull/42990/commits/842b3ee056646b88a73ff9b672185f3c868e8e55)

**Comment by Shadow-Devil** [comment]
Could someone please review this? (also commenting to remove stale status)

**Comment by azinneera** [comment]
CLI changes LGTM

**Review by azinneera — APPROVED** [review]
CLI changes LGTM

**Comment by azinneera** [comment]
> Could someone please review this? (also commenting to remove stale status)

@Shadow-Devil Sorry for the delay in reviewing. We will review and merge at our earliest.

File: ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java [hunk 2]
```diff
@@ -117,9 +116,7 @@ private String readResponse(BufferedReader stream) throws IOException {
      * Send the data given to the specific stream.
      */
     private void sendRequest(PrintStream stream, String string) throws InterruptedException {
-        stream.append(string);
-        stream.println(System.lineSeparator());
-        stream.flush();
+        stream.append(string).append("\n\n").flush();
```
Comment (nipunayf) [inline ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java:119]: Why are replacing `System.lineSeparator` with `\n\n`?

Comment (Shadow-Devil) [reply ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java:119]: It also sent 2 newlines beforehand (one, since it is a `println` and one from the argument). This change actually fixed the testcases on windows, since jline would not detect `\r\n\r\n` as two newlines (I dont know why) but only `\n\n` on Windows and Linux. This code is only used inside testing, so I dont see any compatibility issues.

**Review by NipunaRanasinghe — APPROVED** [review]
Debugger tests related changes LGTM

File: ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java (hunk 2 above)
Comment (nipunayf) [reply ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java:119]: Ack. Shall we include a comment explaining why we decided to keep "\n\n", noting that it is an issue on the JLine side. We can update this later once the issue is resolved.

Comment (Shadow-Devil) [reply ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java]: After revisiting this part, I noticed that it works on windows if there is only a single newline instead of two. There is probably a different handling of double newline at the end of the command between windows/linux by jline. I updated the code to just `stream.println(string);` which worked locally for me (on windows). Let's see if this also passes the Linux pipeline.

Comment (Shadow-Devil) [reply ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/base/TestIntegrator.java:120]: Since the Ubuntu pipeline timed out twice, I reverted it to `\n\n` and added the comment.

**Review by nipunayf — APPROVED** [review]
Shell related changes LGTM

**Comment by Shadow-Devil** [comment]
@azinneera This should be ready to be merged now. I reran the pipe and now all tests are passing.

**Review by azinneera — APPROVED** [review]

**Comment by Shadow-Devil** [comment]
@azinneera thank you very much! Unfortunatly now the Windows pipeline on master timed out, (see also [here](https://github.com/ballerina-platform/ballerina-lang/actions/runs/10254583813/job/28369685316)). It would be great if the limit could be increased, similar to #43195 but for the windows master branch pipeline.

**Comment by azinneera** [comment]
> @azinneera thank you very much! Unfortunatly now the Windows pipeline on master timed out, (see also [here](https://github.com/ballerina-platform/ballerina-lang/actions/runs/10254583813/job/28369685316)). It would be great if the limit could be increased, similar to #43195 but for the windows master branch pipeline.

Thank you for pointing it out @Shadow-Devil. I have opened a PR [1] to increase the timeout.

[1] https://github.com/ballerina-platform/ballerina-lang/pull/43246
