### PR TITLE
Fix several issues with object type reference

### LINKED ISSUE #13822: Referencing two abstract objects which both have a method with the same signature does not cause a compilation error
**Description:**
$title. Fails for fields with the same name (and type though).

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Foo abstract object { 
     function name();
};

type Baz abstract object { 
     function name();
};


type Bar object { 
     *Foo;
     *Baz;

     function name() {
          io:println("name");
     }
};
```

**Affected Versions:**
0.990.3

### LINKED ISSUE #17920: [Spec Deviation] Referencing objects with fields/methods with module level visibility is not restricted across modules
**Description:**
According to the 2019r3 spec
```
If a non-abstract object type To has a type reference to an abstract object type 
Ta, then each method declared in Ta must be defined in To using a method-defn 
with the same visibility. If Ta has a method or field with module-level visibility, 
then To must be in the same module.
```

**Steps to reproduce:**
Create a project with two modules `foo` and `bar`.

In `foo`, define an abstract object with fields/methods with module level visibility.
```ballerina
public type Foo abstract object {
    string s;

    function printS();
};
```

In `bar`, define an object referencing `foo:Foo`
```ballerina
import foo;

type Bar object {
    *foo:Foo;

    function __init(string s) {
        self.s = s;
    }

    function printS() {
        io:println(self.s);
    }
};

public function main() {
    Bar b = new("test");
    b.printS();
}
```

This works atm, but should fail at compile time.

Referencing `foo:Foo` should only work if the referring object is also in `foo`.

**Affected Versions:**
1.0.0-beta-SNAPSHOT - 15th August build

### LINKED ISSUE #18370: [Spec Deviation] No validation for function param visibility match when referencing objects
**Description:**
$title.

The following doesn't fail

**Steps to reproduce:**
```ballerina
type Foo abstract object {
    function xyz(public int i);
};

type Baz object {
    *Foo;

    function xyz(int i) {
        // `i` is not public, but does not fail
    }
};
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-alpha3
Language specification 2019R2
Ballerina tool 1.0.0
```

### LINKED ISSUE #18402: Object type reference attempts copying methods of invalid references
**Description:**
$title.

**Steps to reproduce:**
e.g. 1 - duplicate references result in duplicate errors for incompatible signatures
```ballerina
type Foo abstract  object {
    int i;
    function xyz();
};


type Bar object {
    *Foo;
    *Foo;

    public function __init() {
        self.i = 1;
    }

    function xyz(string s) {
        
    }
};
```

```cmd
$ ballerina run test.bal 
error: .::test.bal:9:6: redeclared type reference 'Foo'
error: .::test.bal:15:5: mismatched function signatures: expected 'function xyz()', found 'function xyz(string s)'
error: .::test.bal:15:5: mismatched function signatures: expected 'function xyz()', found 'function xyz(string s)'
``` 

e.g. 2 - function signatures are validated against invalid non-abstract object references too
```ballerina
type Foo abstract  object {
    int i;
    function xyz();
};

type Bar object {
    int i = 1;
    
    function pqr(string s) {

    }
};

type Baz object {
    *Foo;
    *Bar;

    public function __init() {
        self.i = 1;
    }

    function xyz() {
        
    }

    function pqr() {
        
    }
};
```

```cmd
$ ballerina run test.bal 
error: .::test.bal:16:6: incompatible types: 'Bar' is not an abstract object
error: .::test.bal:26:5: mismatched function signatures: expected 'function pqr(string s)', found 'function pqr()'
``` 

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-alpha3
Language specification 2019R2
Ballerina tool 1.0.0
```

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$title.

Fixes #17920 Referencing objects with fields/methods with module level visibility is not restricted across modules
Fixes #18370 No validation for function param visibility match when referencing objects
Fixes #13822 Referencing two abstract objects which both have a method with the same signature does not cause a compilation error
Fixes #18402 Object type reference attempts copying methods of invalid references

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 1]
```diff
@@ -1688,6 +1690,7 @@ private void createDummyTypeDefSymbol(TypeDefinition typeDefNode, SymbolEnv env)
 
     private void resolveReferencedFields(BLangStructureTypeNode structureTypeNode, SymbolEnv typeDefEnv) {
         List<BSymbol> referencedTypes = new ArrayList<>();
+        List<BLangType> invalidTypeRefs = new ArrayList<>();
         // Get the inherited fields from the type references
         structureTypeNode.referencedFields = structureTypeNode.typeRefs.stream().flatMap(typeRef -> {
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: Btw, This is not a good stream implementation. we should refactor this later.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 2]
```diff
@@ -1698,13 +1701,28 @@ private void resolveReferencedFields(BLangStructureTypeNode structureTypeNode, S
...
+            if (structureTypeNode.type.tag == TypeTags.OBJECT) {
+                if (referredType.tag != TypeTags.OBJECT ||
+                        !Symbols.isFlagOn(referredType.tsymbol.flags, Flags.ABSTRACT)) {
+                    dlog.error(typeRef.pos, DiagnosticCode.INCOMPATIBLE_TYPE_REFERENCE, typeRef);
+                    invalidTypeRefs.add(typeRef);
+                    return Stream.empty();
+                }
+
+                BObjectType objectType = (BObjectType) referredType;
+                if (structureTypeNode.type.tsymbol.owner != referredType.tsymbol.owner) {
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: There can be scenario, this logic fails, Like, local type def. Better to validate pkg, instated.
