### PR TITLE
Fix FP value `===` expression for functions with parameters

### LINKED ISSUE #37379: Function pointers are not equal when the same pointer is passed as two different parameters
**Description:**
If the same function pointer is passed as two different parameters to a function, then there are not equal under the `===` operator.

**Steps to reproduce:**
The output of the following program returns false where it should be true.
```ballerina
function func() {}
function twoFunctionsEqual(function f, function g) returns boolean => f === g;

public function main() {
    io:println(twoFunctionsEqual(func, func));
}
```

**Affected Versions:**
2201.2.0-RC1

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject

Fixes #37379 

## Approach
The issue happens due to an internal call to the `equals` method for `Parameter` instances which returns false.
Overriding the `equals()` resolves the error

## Samples
```ballerina
import ballerina/io;

function func_with_param(string param) {
}

function funcParam = func_with_param;

public function main() {
    io:println(funcParam === funcParam); // returns false - should be true
}
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/Parameter.java [hunk 1]
```diff
@@ -33,4 +35,24 @@ public Parameter(String name, Boolean isDefault, Type type) {
...
+            return false;
+        }
+
+        Parameter that = (Parameter) o;
+        return this.name.equals(that.name) && this.type.equals(that.type) && this.isDefault == that.isDefault;
+    }
+
+    @Override
+    public int hashCode() {
+        return Objects.hash(name, type, isDefault);
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/Parameter.java:55]: Shall we move to constructor

**Comment by Nadeeshan96** [comment]
LGTM

**Review by Nadeeshan96 — APPROVED** [review]

**Review by warunalakshitha — APPROVED** [review]
LGTM
