### PR TITLE
Add fix to handle tests outside tests directory

### LINKED ISSUE #20359: [Testerina] BAD SAD When tests are defined outside the tests directory.
**Description:**
When I define a test outside the test directory, and do ballerina test <module_name>, ballerina crashes.

**Steps to reproduce:**
**Main.bal**
import ballerina/test;

@test:Config{}
function testAssertIntEquals() {
int answer = 8;
test:assertEquals(answer, 8, msg = "int values not equal");
}

**Command**
ballerina test test_module

**LOG**
[2019-12-12 14:01:22,638] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
at org.ballerinalang.testerina.core.BTestRunner.lambda$null$26(BTestRunner.java:745)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$28(BTestRunner.java:673)
at java.lang.Iterable.forEach(Iterable.java:75)
at org.ballerinalang.testerina.core.BTestRunner.execute(BTestRunner.java:630)
at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:160)
at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:132)
at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:90)
at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
at org.ballerinalang.packerina.cmd.TestCommand.execute(TestCommand.java:282)
at java.util.Optional.ifPresent(Optional.java:159)
at org.ballerinalang.tool.Main.main(Main.java:57)

**Affected Versions:**
ballerina -v
jBallerina 1.1.0-alpha
Language specification 2019R3
Command 1.1.0-alpha

**OS, DB, other environment details and versions:**
MacOSX(10.15.1)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
@Kishanthan

### PR DESCRIPTION
**Pull request by Dilhasha**
- When there are tests defined outside the tests directory, a Null pointer exception is thrown.
- When there is at least one test defined inside the tests directory, tests outside the tests directory are also executed.

Fixes #20359 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BaseTestCase.java [hunk 1]
```diff
@@ -78,6 +79,11 @@ public void initialize() throws BallerinaTestException, IOException {
                 Paths.get("src", "test", "resources", "project-based-tests/test-report-tests").toAbsolutePath();
         reportTestProjectPath = tempProjectDirectory.resolve("test-report");
         FileUtils.copyFolder(originalReportTestProj, reportTestProjectPath);
+
+        Path outsideTestsProj =
+                Paths.get("src", "test", "resources", "project-based-tests/outside-tests").toAbsolutePath();
```
Comment (parkavi11) [inline tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BaseTestCase.java:84]: Won't this break in Windows? Why don't we have something like this?
```suggestion
                Paths.get("src", "test", "resources", "project-based-tests", "outside-tests").toAbsolutePath();
```

File: tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/PathVerificationTest.java [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+    public void setup() throws BallerinaTestException {
+        balClient = new BMainInstance(balServer);
+        projectPath = outsideTestsProjectPath.toString();
+    }
+
+    @Test
+    public void verifyTestsOutsidePath() throws BallerinaTestException {
+        LogLeecher passingLeecher = new LogLeecher("1 passing");
+        LogLeecher failingLeecher = new LogLeecher("0 failing");
+        balClient.runMain("test", new String[]{"pathVerification.tests"}, null, new String[0],
```
Comment (azinneera) [inline tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/PathVerificationTest.java:44]: Why do we give it as `pathVerification.tests`? Looks like the module structure is wrong. The path to test files seems to be `outside-tests/src/pathVerification.tests` but the correct path should be `outside-tests/src/pathVerification/tests`.

Comment (Dilhasha) [reply tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/PathVerificationTest.java:44]: @azinneera The path to tests is not wrong. I have both source files and test files since this check is to see whether tests defined in source files are being executed.
I guess the module name is confusing, I will get rid of the ".tests" part.

File: tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BaseTestCase.java (hunk 1 above)
Comment (Dilhasha) [reply tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BaseTestCase.java:84]: Thanks for the pointer @parkavi11 
You are correct. We should either use "File.separator" or use the approach you suggested. I'll correct it,
