### PR TITLE
[Master] Restrict field binding inside list binding pattern in the parser

### LINKED ISSUE #37283: CCE in BLangNodeBuilder around field binding pattern
**Description:**

Consider the following source code:
```ballerina
import ballerina/jwt;
import ballerina/http;

service / on new http:Listener(9090) {

    resource function get data(@http:Header {name: "Authorization"} string token) returns error? {
        i<cursor>
        [jwt:Header, jwt:Payload] [_, payload] = check jwt:decode(token);
    }
}
```
Here at cursor, I'm trying to add a `io:println()` line. This happens when the println line is partially written.

It gives the following error in vscode:
```
[Error - 7:22:23 PM] Operation 'text/hover' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/test_project/test.bal', [1:15], error: 'class io.ballerina.compiler.syntax.tree.FieldBindingPatternFullNode cannot be cast to class io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode (io.ballerina.compiler.syntax.tree.FieldBindingPatternFullNode and io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.FieldBindingPatternFullNode cannot be cast to class io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode (io.ballerina.compiler.syntax.tree.FieldBindingPatternFullNode and io.ballerina.compiler.syntax.tree.CaptureBindingPatternNode are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.getBLangVariableNode(BLangNodeBuilder.java:5060)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.getBLangVariableNode(BLangNodeBuilder.java:4990)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createBLangVarDef(BLangNodeBuilder.java:2835)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2824)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:476)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.generateAndAddBLangStatements(BLangNodeBuilder.java:5115)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1572)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:476)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.populateFunctionNode(BLangNodeBuilder.java:1475)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createResourceFunctionNode(BLangNodeBuilder.java:734)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1436)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:476)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transformObjectCtorExpressionBody(BLangNodeBuilder.java:1182)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:3919)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:476)
	at io.ballerina.compiler.syntax.tree.ServiceDeclarationNode.apply(ServiceDeclarationNode.java:83)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:610)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:476)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.accept(BLangNodeBuilder.java:509)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:111)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:415)
	at io.ballerina.projects.ModuleCompilationState$3.compile(ModuleCompilationState.java:100)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:377)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:183)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:144)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:272)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:283)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:251)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentSemanticModel(AbstractDocumentServiceContext.java:238)
	at org.ballerinalang.langserver.hover.HoverUtil.getHover(HoverUtil.java:62)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$hover$1(BallerinaTextDocumentService.java:170)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**
See description

**Affected Versions:**
2201.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by prakanth97**
Fixes  #37283

## Samples
```
type arr [int, int];
public function testListBindingPatternWithInvalidMember() {
    arr[jwt:Header, jwt:Payload] = [1, 2];
    arr[a, b] = [1, 2];
}
```
This code sample will give `field binding patterns are not allowed inside the list binding pattern` error instead of CCE.
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/parser/ResilientParserTest.java [hunk 1]
```diff
@@ -214,4 +214,16 @@ public void testResilientParsingError() {
         BAssertUtil.validateError(result, 1, "missing equal token", 2, 12);
         BAssertUtil.validateError(result, 2, "missing identifier", 2, 12);
     }
+
+    @Test
+    public void testListBindingPatternWithInvalidMember() {
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/parser/ResilientParserTest.java:219]: As the name implies `ResilientParserTest` class is to add tests for the parser resiliency.
Since this test is not related to resiliency and the fix is within the parser, shall we add a parser test case to `TypedBindingPatternsTest` class?

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 2]
```diff
@@ -17623,6 +17623,14 @@ private STNode parseAsListBindingPattern(STNode openBracket, List<STNode> member
 
     private STNode parseAsListBindingPattern(STNode openBracket, List<STNode> memberList) {
         memberList = getBindingPatternsList(memberList);
+        STNode firstMember = memberList.get(0);
+        if (firstMember.kind == SyntaxKind.FIELD_BINDING_PATTERN) {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:17627]: It is confusing we are doing this check only on the first member where we have a list. We need to do this for all the members. Also, we seem to have several places where we call ` getBindingPatternsList()` and create a list-binding-pattern on top of that. We need to handle this in a single place.

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:17627]: Maybe we can pass a flag `isListBP` to  `getBindingPatternsList()` and `getBindingPattern()` and execute the default case if the node is not compatible member of `list-binding-pattern`.

File: compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties [hunk 3]
```diff
@@ -331,3 +331,5 @@ error.missing.object.constructor.expression=missing object constructor expressio
 error.rest.parameter.cannot.be.included.record.parameter=rest parameter cannot be an included record parameter
 error.resource.access.segment.is.not.allowed.after.rest.segment=\
   resource access path segment is not allowed after resource access rest segment
+error.field.binding.patterns.not.allowed.inside.list.binding.pattern=\
+  field binding patterns are not allowed inside the list binding pattern
```
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties]: Not used this error msg

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/parser/ResilientParserTest.java (hunk 1 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/parser/ResilientParserTest.java]: Updated

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 2 above)
Comment (prakanth97) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java]: Updated

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 4]
```diff
@@ -18932,7 +18939,8 @@ private STNode getBindingPattern(STNode ambiguousNode) {
             case BRACKETED_LIST:
             case LIST_BP_OR_LIST_CONSTRUCTOR:
                 STAmbiguousCollectionNode innerList = (STAmbiguousCollectionNode) ambiguousNode;
-                STNode memberBindingPatterns = STNodeFactory.createNodeList(getBindingPatternsList(innerList.members));
+                STNode memberBindingPatterns = STNodeFactory.createNodeList(
+                        getBindingPatternsList(innerList.members, true));
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:18943]:
```suggestion
                STNode memberBindingPatterns =
                        STNodeFactory.createNodeList(getBindingPatternsList(innerList.members, true));
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 5]
```diff
@@ -18897,10 +18897,17 @@ private STNode getTypeDescFromExpr(STNode expression) {
         }
     }
 
-    private List<STNode> getBindingPatternsList(List<STNode> ambibuousList) {
+    private List<STNode> getBindingPatternsList(List<STNode> ambibuousList, boolean isListBP) {
         List<STNode> bindingPatterns = new ArrayList<>();
         for (STNode item : ambibuousList) {
-            bindingPatterns.add(getBindingPattern(item));
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:18903]: Shall we bring `isListBP` flag inside the `getBindingPattern()`? there you can check the flag = true in `QUALIFIED_NAME_REFERENCE` case and if so `break` and then execute the error reporting we do under the default case.

File: compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_27.bal [hunk 6]
```diff
@@ -0,0 +1,6 @@
+type Arr [int, int];
+
+public function testListBindingPatternWithInvalidMember() {
+    Arr [jwt:Header, jwt:Payload] = [1, 2];
+    Arr [a, b] = [1, 2];
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_27.bal:5]: L5 is not invalid right?
We can have combinations similar to L4.
e.g.
```bal
Arr [foo, jwt:Payload] = [];
Arr [jwt:Header, foo] = [];
Arr [jwt:Header, foo, jwt:Header ] = [];
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 5 above)
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:18903]: I think the error given at the default case is okay to use for this as well.

**Comment by prakanth97** [comment]
Do we need to remove this as well? 
https://github.com/ballerina-platform/ballerina-lang/blob/0c173ed40f96d7f8fb0b00b6e85c1624600c1b36/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java#L16923

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 7]
```diff
@@ -18925,21 +18925,28 @@ private STNode getBindingPattern(STNode ambiguousNode) {
                 STNode varName = ((STSimpleNameReferenceNode) ambiguousNode).name;
                 return createCaptureOrWildcardBP(varName);
             case QUALIFIED_NAME_REFERENCE:
+                if (isListBP) {
+                    STNode identifier = SyntaxErrors.createMissingTokenWithDiagnostics(SyntaxKind.IDENTIFIER_TOKEN,
+                            ParserRuleContext.BINDING_PATTERN_STARTING_IDENTIFIER);
+                    identifier = SyntaxErrors.cloneWithLeadingInvalidNodeMinutiae(identifier, ambiguousNode);
+                    return createCaptureOrWildcardBP(identifier);
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:18932]: Instead of doing the validation here, can't we execute the same validation done at the default?
You can take the default case logic out of the switch and `break` here?
```suggestion
                    break;
```

Comment (prakanth97) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java]: Updated 8361199b43b0120ab8d1bf3af49d9c97d51289be

File: compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_27.bal [hunk 8]
```diff
@@ -0,0 +1,9 @@
+type Arr [int, int];
+type Arr2 [int, int, int];
+
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/resources/misc/typed-binding-patterns/typed_binding_patterns_source_27.bal:3]: the above three lines are irrelevant since we are only testing the syntax here.

**Review by lochana-chathura — DISMISSED** [review]

**Review by rdulmina — APPROVED** [review]

**Review by KavinduZoysa — APPROVED** [review]
