### PR TITLE
Add toString to object and Fix tests

### LINKED ISSUE #17003: Can't call `.toString()` on an object
**Description:**
$title.

`io:println(objectValue)` works, but prints an invalid representation.

According to the spec, `.toString()` for an object is as follows:
```
# - if `v` is an object, then
#     - if `v` provides a toString method with a string return type and no required methods,
#       then the result of calling that method on `v`
#     - otherwise, `object` followed by some implementation-dependent string
```

**Steps to reproduce:**
```ballerina
import ballerina/io;

public type Foo object {
    public string s = "xyz";
};

public function main() {
    Foo f = new Foo();

    io:println(f);
    io:println(f.toString());
}
```

**Affected Versions:**
0.992.0-m8

### PR DESCRIPTION
**Pull request by gimantha**
## Purpose
This PR adds toString() method to ballerina objects. For more details about the behavior of toString on object, refer to https://raw.githubusercontent.com/ballerina-platform/ballerina-spec/v2019R2/lang/lib/value.bal
Fixes #17003, #17001

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [x] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java [hunk 1]
```diff
@@ -67,7 +69,16 @@ public ErrorValue(BType type, String reason, Object details) {
 
     @Override
     public String stringValue() {
-        return "error " + reason + Optional.ofNullable(details).map(details -> " " + details).orElse("");
+        BType type = TypeChecker.getType(details);
+        return "error " + reason + Optional.ofNullable(details).map(details -> " " + StringUtils.getStringValue(null,
```
Comment (hasithaa) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java]: This can be replaced with return stringValue(null);

Comment (gimantha) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ErrorValue.java]: fixed
