### PR TITLE
Preserve intersection type through the compiler phases insted of passing effective type

### LINKED ISSUE #38505: [Bug]: Incorrect type name for immutable types in error messages
### Description

```bal
function testInvalidReaodOnlyRecordUpdates() {
    Student & readonly b = {};
    b["details"] = 3;
}

public type Student record {|
    int details = 5;
|};

public type ReadOnlyStudent readonly & Student;
```
Gives `cannot update 'readonly' value of type 'ReadOnlyStudent'` ideally it should give `cannot update 'readonly' value of type '(Student & readonly)'`. This is because we maintain `symTable.immutableTypeMaps`. Need to revisit this

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39414: [Bug]: Inconsistent return type for `.typeDescriptor()` API for `TypeReferenceTypeSymbol` when it is `IntersectionTypeSymbol`
### Description

When I try to access the type descriptor for the intersection type faces inconsistent behaviour for the below scenarios:
Scenario 01:
```ballerina
public type ReturnValue02 readonly & string;
```
Accesse via:  **TypeSymbol typeSymbol = typeRef.typeDescriptor()**
Return value :  TypeSymbol is  `StringTypeSymbol`

Scenario 02
```ballerina
public type ReturnValue03 readonly & map<json>;

public type ReturnValue04 readonly & json;

public type ReturnValue05 readonly & xml;

public type ReturnValue06 readonly & error;

public type ReturnValue07 readonly & string[];
```
Accesse via:  **TypeSymbol typeSymbol = typeRef.typeDescriptor()**
Return value :  TypeSymbol is  `IntersectionTypeSymbol`

### Steps to Reproduce

Try to access the type descriptor for the below intersection types 
```ballerina
public type ReturnValue02 readonly & string;

public type ReturnValue03 readonly & map<json>;

public type ReturnValue04 readonly & json;

public type ReturnValue05 readonly & xml;

public type ReturnValue06 readonly & error;

public type ReturnValue07 readonly & string[];
```
Accesse via:  **TypeSymbol typeSymbol = typeRef.typeDescriptor()**

### Affected Version(s)

Ballerina 2201.3.2 (Swan Lake Update 3)

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

This issue is a blocker for the fix to this issue https://github.com/ballerina-platform/openapi-tools/issues/1151

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #40960: [Bug]: No error for assigning non-readonly `anydata` value for readonly `anydata` variable
### Description

Bellow programs compile without error and produces a wrong output

```bal
import ballerina/io;
public function main() {
    anydata a = [];
    anydata & readonly b = a; // Should be a compilation error.
    anydata[] array = <anydata[]>a;
    array.push(1);
    io:println(b);
}
```

Prints `[1]`

### Steps to Reproduce

_No response_

### Affected Version(s)

U7

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #41009: Preserve intersection type through the compiler
Preserve intersection type through the compiler

1. Remove `IntersectableReferenceType.java`.
2. Preserve intersection type through the compiler phases.
3. Handle intersection type via `getReferredType()`.
4. Add missing `getReferredType()` cases before type operations in compiler and runtime.

### LINKED ISSUE #41175: [Bug]: No error when referencing service object inside non serveice object
### Description

```bal
public type FooObj readonly & distinct service object {
    isolated remote function execute(string aVar, int bVar) returns int;
};

readonly client class FooClass {
    *FooObj;

    isolated remote function execute(string aVar, int bVar) returns int {
        return bVar;
    }
}
```

Including the service object `FooObj` inside `FooClass` does not give any error. If we remove `readonly` from the `FooObj` it gives the error `invalid object type inclusion: missing 'service' qualifier(s) in the referencing object`

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
This PR will

1. Remove `IntersectableReferenceType.java`.
2. Preserve intersection type through the compiler phases.
3. Handle intersection type via `getReferredType()`.
4. Add missing `getReferredType()` cases before type operations in compiler and runtime.
5. Fix several existing bugs

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java [hunk 1]
```diff
@@ -55,19 +56,32 @@ public class BIntersectionType extends BType implements IntersectionType {
...
 
-    private BIntersectionType(Module pkg, Type[] constituentTypes, int typeFlags, boolean readonly) {
-        super(null, pkg, Object.class);
+    public BIntersectionType(String typeName, Module pkg, Type[] constituentTypes, Type effectiveType,
+                             int typeFlags, boolean readonly) {
+        this(typeName, pkg, constituentTypes, typeFlags, readonly);
+        this.effectiveType = effectiveType;
+    }
+
+    public BIntersectionType(String typeName, Module pkg, Type[] constituentTypes,
```
Comment (lochana-chathura) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:76]: Seems no usage of these new two constructors?

Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:76]: Those are used by generated bytecode

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java [hunk 2]
```diff
@@ -143,19 +144,35 @@ public static Type getType(Object value) {
...
         return TypeChecker.isSameType(sourceType, targetType);
     }
-
     /**
      * Retrieve the referred type if a given type is a type reference type.
      *
      * @param type type to retrieve referred
      * @return the referred type if provided with a type reference type, else returns the original type
      */
     public static Type getReferredType(Type type) {
```
[the remark this answers is not in the document]
Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java:153]: There are cases where one still needs to use `getReferredType`. ie: if someone wants just to unwrap the referred type, not the effective type

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java [hunk 3]
```diff
@@ -151,11 +152,28 @@ public static boolean isSameType(Type sourceType, Type targetType) {
...
     }
 
+    /**
+     * Retrieve the conclusive type if a given type is a type reference type or an intersection.
+     *
+     * @param type type to retrieve referred
+     * @return the conclusive type if provided with a type reference type or an intersection,
+     * else returns the original type
+     */
+    public static Type getConclusiveType(Type type) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java:168]: Do we need to expose this method? Can we add this to internal package?

Comment (warunalakshitha) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java:168]: Do we need to dereprecate getReferredType method?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java [hunk 4]
```diff
@@ -188,6 +202,11 @@ public void setImmutableType(IntersectionType immutableType) {
         this.immutableType = immutableType;
     }
 
+    @Override
+    public Type getReferredType() {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:206]: Isn't this meant for type reference types? Is it correct to override it this way?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/JsonUtils.java [hunk 5]
```diff
@@ -307,7 +306,7 @@ private static Object convertToJsonType(Object value, List<TypeValuePair> unreso
             return null;
         }
         Type sourceType = TypeChecker.getType(value);
-        if (TypeUtils.getReferredType(sourceType).getTag() <= TypeTags.BOOLEAN_TAG && TypeChecker.checkIsType(value,
+        if (TypeUtils.getConclusiveType(sourceType).getTag() <= TypeTags.BOOLEAN_TAG && TypeChecker.checkIsType(value,
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/JsonUtils.java:309]: What about a name like `getRepresentedType`? Or implied type. Does conclusive really mean what we want to convey?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java (hunk 3 above)
Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java:168]: `getConclusiveType` is useful for the consumer to handle intersection types. Otherwise, they have to manually get the effective type. We are not going to deprecate `getReferredType` since the purpose of `getReferredType` and `getConclusiveType` is different

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/JsonUtils.java (hunk 5 above)
Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/JsonUtils.java:309]: +1 for `getRepresentedType`

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java (hunk 4 above)
Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BIntersectionType.java:206]: will have to change this thanx.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java [hunk 6]
```diff
@@ -735,10 +734,23 @@ public static boolean needNoTypeGeneration(int bTypeTag) {
     }
 
     public static BType getReferredType(BType type) {
+        return getReferredType(type, true);
+    }
+    
+    public static BType getReferredType(BType type, boolean effectiveType) {
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java:740]:
```suggestion
    public static BType getReferredType(BType type, boolean onEffectiveType) {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/errors/errors.bal [hunk 7]
```diff
@@ -0,0 +1,41 @@
+// Copyright (c) 2023 WSO2 LLC.
+//
+// WSO2 LLC. licenses this file to you under the Apache License,
+// Version 2.0 (the "License"); you may not use this file except
+// in compliance with the License.
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/errors/errors.bal:5]:
``` suggestion
// Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
```

File: tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java [hunk 8]
```diff
@@ -194,8 +194,8 @@ public void globalVariableVisibilityTest() throws BallerinaTestException {
         // global constants
         debugTestRunner.assertVariable(globalVariables, "nameWithoutType", "\"Ballerina\"", "string");
         debugTestRunner.assertVariable(globalVariables, "nameWithType", "\"Ballerina\"", "string");
-        debugTestRunner.assertVariable(globalVariables, "nameMap", "(debug_test_resources/variable_tests" +
-                ":0:$anonType$nameMap$_0 & readonly)", "record");
+//        debugTestRunner.assertVariable(globalVariables, "nameMap", "(debug_test_resources/variable_tests" +
```
Comment (HindujaB) [inline tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java:197]: Do we have any issues created to track this change? We need to uncomment it once it is fixed

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java [hunk 9]
```diff
@@ -151,11 +152,28 @@ public static boolean isSameType(Type sourceType, Type targetType) {
...
         if (type.getTag() == TypeTags.TYPE_REFERENCED_TYPE_TAG) {
-            constraint = getReferredType(((ReferenceType) type).getReferredType());
+            return getReferredType(((ReferenceType) type).getReferredType());
         }
-        return constraint;
+        return type;
     }
 
+    /**
+     * Retrieve the represented type if a given type is a type reference type or an intersection.
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java:162]:
``` suggestion
     * Retrieve the represented type if a given type is a type-reference type or an intersection type.
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java [hunk 10]
```diff
@@ -151,11 +152,28 @@ public static boolean isSameType(Type sourceType, Type targetType) {
...
+     *
+     * @param type type to retrieve referred
+     * @return the represented type if provided with a type reference type or an intersection,
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java:165]:
```suggestion
     * @return the represented type if provided with a type-reference type or an intersection type,
```

File: tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/errors/errors.bal (hunk 7 above)
Comment (rdulmina) [reply tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/errors/errors.bal:5]: We don't add this part now right?

File: tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java (hunk 8 above)
Comment (rdulmina) [reply tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java:197]: Yes we have  #40896, will put the issue in the test file also thanx.

File: tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/errors/errors.bal (hunk 7 above)
Comment (lochana-chathura) [reply tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/values/modules/errors/errors.bal:5]: The license header for the open-source repos should not include "All Rights Reserved" part.
Can refer to the "Re: License Header for WSO2 code" mail.

**Review by lochana-chathura — DISMISSED** [review]
LGTM

**Review by HindujaB — DISMISSED** [review]

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/IntersectableReferenceType.java [hunk 11]
```diff
@@ -25,6 +25,7 @@
  *
  * @since 2.0.0
  */
+@Deprecated
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/IntersectableReferenceType.java:28]: Can we remove this next update?

Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/IntersectableReferenceType.java:28]: We usually deprecate the API right. We can keep this in the next update as well?

**Review by warunalakshitha — COMMENTED** [review]
RuntimeChange

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 12]
```diff
@@ -762,9 +754,6 @@ private static boolean checkIsRecursiveType(Type sourceType, Type targetType, Li
                 return checkTypeDescType(sourceType, (BTypedescType) targetType, unresolvedTypes);
             case TypeTags.XML_TAG:
                 return checkIsXMLType(sourceType, targetType, unresolvedTypes);
-            case TypeTags.TYPE_REFERENCED_TYPE_TAG:
-                return checkIsRecursiveType(sourceType, ((ReferenceType) targetType).getReferredType(),
```
[the remark this answers is not in the document]
Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:766]: It is still used in https://github.com/ballerina-platform/ballerina-lang/blob/f2af7c9fee0ead0cc585e1646f3b2050c271b9c4/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java#L663

**Review by lochana-chathura — APPROVED** [review]

**Review by gimantha — APPROVED** [review]
