### PR TITLE
Fix runtime error in optional field access

### LINKED ISSUE #22451: Unexpected behaviour in optional field access of union of record types
**Description:**
$subject. Please refer language spec https://ballerina.io/spec/lang/2020R1/#section_6.15.

**Steps to reproduce:**
Below program throws an error.

```
import ballerina/io;

type Foo record {
    string s;
};

type Bar record {
    int i;
};

public function main(string... args) {
    Foo f = { s: "hello" };
    Bar b= { i: 1 };

    Bar|Foo v = f;
    string? str = v?.s;
    int? x = v?.i;
    io:println(str);
    io:println(x);
}

```
But below program works.

```
import ballerina/io;

type Foo record {
    string s;
};

type Bar record {
    int i;
};

public function main(string... args) {
    Foo f = { s: "hello" };
    Bar b= { i: 1 };

    Bar|Foo v = b;
    string? str = v?.s;
    int? x = v?.i;
    io:println(str);
    io:println(x);
}
```

**Affected Versions:**
1.2.0

### LINKED ISSUE #22676: Error in optional field access of union of records with nil
**Description:**
$subject

**Steps to reproduce:**
```
type Foo record {|
    string s;
|};

type Bar record {|
    int i;
|};

public function main() {
    Foo f = {s: "str"};
    Bar b = {i: 1};
    Foo|Bar? fn1 = f;

    string|int? a1 = fn1?.i; // error: {ballerina}TypeCastError message=incompatible types: '()' cannot be cast to 'int'
}
 ```

**Affected Versions:**
1.2.0

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose
$subject

Fixes #22451 
Fixes #22676 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -4381,16 +4381,23 @@ private BType checkOptionalRecordFieldAccessExpr(BLangFieldBasedAccess fieldAcce
...
             if (individualFieldType == symTable.semanticError) {
+                nonMatchedRecordExists = true;
                 continue;
             }
 
             fieldTypeMembers.add(individualFieldType);
         }
 
+        if (nonMatchedRecordExists) {
+            fieldTypeMembers.add(symTable.nilType);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4398]: Shall we rename https://github.com/ballerina-platform/ballerina-lang/blob/8b26828e30589512d938031ecc115c03a1a57800/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L4255 and use that instead?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 2]
```diff
@@ -5856,31 +5856,92 @@ private void handleSafeNavigation(BLangAccessExpression accessExpr, BType type,
 
         BLangMatch matchStmt = ASTBuilderUtil.createMatchStatement(accessExpr.pos, accessExpr.expr, new ArrayList<>());
 
+        boolean allRecords = false;
+        BUnionType errorLiftedType = BUnionType.create(null, new LinkedHashSet<>());
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5860]: Can we work with a `LinkedHashSet` instead? We don't need the union type right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 3]
```diff
@@ -5856,31 +5856,92 @@ private void handleSafeNavigation(BLangAccessExpression accessExpr, BType type,
...
+        if (accessExpr.expr.type.tag == TypeTags.UNION) {
+            LinkedHashSet<BType> memTypes = new LinkedHashSet<>(((BUnionType) accessExpr.expr.type).getMemberTypes());
+            errorLiftedType = BUnionType.create(null, memTypes);
+            allRecords = checkForRecords(memTypes);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5864]: IMO the method name does not say much about what the method actually does, and the variable name kinda implies the check returns if all the members are records, which from the impl. doesn't seem to be the case. Can we rename?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 4]
```diff
@@ -5856,31 +5856,92 @@ private void handleSafeNavigation(BLangAccessExpression accessExpr, BType type,
...
             matchStmt.type = type;
             matchStmt.pos = accessExpr.pos;
+            errorLiftedType.remove(symTable.errorType);
+        }
+
+        BLangMatchTypedBindingPatternClause successPattern = null;
+        Name field = getFieldName(accessExpr);
+        if (field == Names.EMPTY) {
+            successPattern = getSuccessPattern(accessExpr, tempResultVar,
+                    accessExpr.errorSafeNavigation);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5886]:
```suggestion
            successPattern = getSuccessPattern(accessExpr, tempResultVar, accessExpr.errorSafeNavigation);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 5]
```diff
@@ -5856,31 +5856,92 @@ private void handleSafeNavigation(BLangAccessExpression accessExpr, BType type,
...
+            matchStmt.patternClauses.add(successPattern);
+            pushToMatchStatementStack(matchStmt, accessExpr, successPattern);
+            return;
+        }
 
+        if (allRecords) {
+            for (BType memberType : errorLiftedType.getMemberTypes()) {
+                BSymbol fieldSymbol = symResolver.resolveStructField(accessExpr.pos, this.env, field,
+                        memberType.tsymbol);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5895]: Do we need to do this? Can we not just iterate through the fields of the `BRecordType` and figure out if the field exists? 

`symResolver.resolveStructField` could log errors right, even thought it may not atm?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5895]: @pubudu91 thoughts?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 6]
```diff
@@ -5939,6 +6000,25 @@ private BLangMatchTypedBindingPatternClause getMatchNullPattern(BLangExpression
         return nullPattern;
     }
 
+    private BLangMatchStaticBindingPatternClause getMatchAllPattern(BLangExpression expr,
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:6003]: Shall we rename this to indicate it returns `()` on match all?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 7]
```diff
@@ -5939,6 +6000,25 @@ private BLangMatchTypedBindingPatternClause getMatchNullPattern(BLangExpression
...
+                                                                    BLangSimpleVariable tempResultVar) {
+
+        BLangVariableReference tempResultVarRef = ASTBuilderUtil.createVariableRef(expr.pos, tempResultVar.symbol);
+        BLangAssignment assignmentStmt =
+                ASTBuilderUtil.createAssignmentStmt(expr.pos, tempResultVarRef, createLiteral(expr.pos,
+                        symTable.nilType, Names.NIL_VALUE), false);
+        BLangBlockStmt patternBody = ASTBuilderUtil.createBlockStmt(expr.pos, Lists.of(assignmentStmt));
+
+        BLangMatchStaticBindingPatternClause c =
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:6012]: Variable name. :)

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 8]
```diff
@@ -5987,6 +6067,62 @@ private BLangMatchTypedBindingPatternClause getSuccessPattern(BLangAccessExpress
         return successPattern;
     }
 
+    private BLangMatchTypedBindingPatternClause getSuccessPatternRecordMatch(BType type,
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:6070]: This seems to be duplicating quite a bit of code from `getSuccessPattern`. Can we try and refactor `getSuccessPattern` instead to handle the record scenario?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 5 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5895]: This would log an error if at least one record type doesn't have the field name given by `field` right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 9]
```diff
@@ -5856,31 +5856,92 @@ private void handleSafeNavigation(BLangAccessExpression accessExpr, BType type,
...
+                field = new Name(((BLangLiteral) indexBasedExpression).value.toString());
+            }
+        }
+        return field;
+    }
+
+    private boolean checkForRecords(LinkedHashSet<BType> memTypes) {
+        for (BType memType : memTypes) {
+            int typeTag = memType.tag;
+            if (typeTag != TypeTags.RECORD && typeTag != TypeTags.ERROR && typeTag != TypeTags.NIL) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5937]: What's this condition about?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 5 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5894]: And yeah, we don't usually use this to lookup whether the a record has a field by the specified name.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 8 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Done

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/optional_field_access.bal [hunk 10]
```diff
@@ -331,3 +333,41 @@ function testJsonOptionalFieldAccessOnInvocation() returns boolean {
...
+type Bar1 record {|
+    string s2;
+    int i2;
+|};
+
+function testOptionalFieldAccessInUnionType1() {
+    Foo1 f = { s1: "s", i1: 1};
+    Foo1|Bar1? fb = f;
+
+    string|int? x1 = fb["s1"];
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/optional_field_access.bal]: Done

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/optional_field_access.bal [hunk 11]
```diff
@@ -331,3 +333,41 @@ function testJsonOptionalFieldAccessOnInvocation() returns boolean {
...
+    string|int? x4 = fb["i2"];
+
+    if !(x1 == "s" && x2 == 1 && x3 == () && x4 == ()) {
+        panic error(ASSERTION_ERROR_REASON, message = "expected 'true', found 'false'");
+    }
+}
+
+function testOptionalFieldAccessInUnionType2() {
+    Bar1 b = { s2: "s", i2: 1};
+    Foo1|Bar1? fb = b;
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/optional_field_access.bal]: Done

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal [hunk 12]
```diff
@@ -272,3 +274,41 @@ function testJsonFieldAccessOnInvocation() returns boolean {
 function getJson() returns json {
     return { x: { y: 1 } };
 }
+
+type Foo1 record {
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal]: Done

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 2 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Done

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Done

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 9 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5951]: This method check whether all types are records except error type and nil type.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 5 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Done

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal [hunk 13]
```diff
@@ -14,6 +14,8 @@
 // specific language governing permissions and limitations
 // under the License.
 
+const ASSERTION_ERROR_REASON = "AssertionError";
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:17]: Is this used?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 14]
```diff
@@ -5969,25 +6057,36 @@ private BLangMatchTypedBindingPatternClause getSuccessPattern(BLangAccessExpress
         BLangSimpleVariable successPatternVar = ASTBuilderUtil.createVariable(accessExpr.pos, successPatternVarName,
                 type, null, successPatternSymbol);
 
-        // Create x.foo, by replacing the varRef expr of the current expression, with the new temp var ref
-        accessExpr.expr = ASTBuilderUtil.createVariableRef(accessExpr.pos, successPatternVar.symbol);
-        accessExpr.errorSafeNavigation = false;
-        accessExpr.nilSafeNavigation = false;
+        BLangAccessExpression tempAccessExpr = nodeCloner.clone(accessExpr);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:6060]: Why do we need a clone?
