### PR TITLE
Source prune implementation for Ballerina Language Server

### LINKED ISSUE #14216: Source Pruning for Language Sever Completion
**Description:**
Auto-completion is provided most of the time, while the user is typing. During the typing, ballerina source is incorrect with syntax errors. Therefore, when trying to parse the source (in the sense, current package) compiler fails to build the correct source. In order to avoid the compiler failures, either grammar or parser has to optimize for fallback and recover the error. This approach can be error-prone and performance intensive due to the inline context recovery.
In order to avoid complexity,  another approach is to prune the source/ remove the erroneous tokens and inject a valid source to the parser.

- [x] Finalize the terminating tokens
- [x] Finalize the token removal rules for grammar
- [ ] Implement Token Removal strategy
- [ ] Implement Source inject through document manager and Completion context

**Affected Versions:**
v0.990.3.0

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/contextproviders/FunctionDefinitionContextProvider.java [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+//                    .filter(symbolInfo -> symbolInfo.getScopeEntry().symbol instanceof BObjectTypeSymbol)
+//                    .map(symbolInfo -> {
+//                        BSymbol symbol = symbolInfo.getScopeEntry().symbol;
+//                        String symbolName = symbol.getName().getValue();
+//                        CompletionItem completionItem = BTypeCompletionItemBuilder.build((BTypeSymbol) symbol,
+//                                symbolName);
+//                        completionItem.setInsertText(symbolName + ".");
+//                        return completionItem;
+//                    }).collect(Collectors.toList());
+//        }
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/contextproviders/FunctionDefinitionContextProvider.java]: Shall we remove commented code?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/contextproviders/FunctionDefinitionContextProvider.java [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+        List<CompletionItem> completionItems = new ArrayList<>();
+        Optional filtered = context.get(CompletionKeys.VISIBLE_SYMBOLS_KEY)
+                .stream()
+                .filter(symbolInfo -> {
+                    BSymbol symbol = symbolInfo.getScopeEntry().symbol;
+                    return symbol instanceof BObjectTypeSymbol && symbol.getName().getValue().equals(objectName);
+                }).findFirst();
+
+        if (!(filtered.isPresent()
+                && ((SymbolInfo) filtered.get()).getScopeEntry().symbol instanceof BObjectTypeSymbol)) {
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/contextproviders/FunctionDefinitionContextProvider.java]: Use `Optional<SymbolInfo> filtered` in [line 163](https://github.com/ballerina-platform/ballerina-lang/pull/15128/files#diff-ca442fc9d89ebcabc664b64b7b7856c4R163), then you don't need to cast it.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/scopeproviders/ServiceScopeProvider.java [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+        ParserRuleContext parserRuleContext = ctx.get(CompletionKeys.PARSER_RULE_CONTEXT_KEY);
+
+        if (parserRuleContext != null && this.getProvider(parserRuleContext.getClass()) != null) {
+            return this.getProvider(parserRuleContext.getClass()).getCompletions(ctx);
+        }
+
+        completionItems.addAll(this.getBasicTypes(ctx.get(CompletionKeys.VISIBLE_SYMBOLS_KEY)));
+        completionItems.addAll(this.getPackagesCompletionItems(ctx));
+        completionItems.add(Snippet.KW_PUBLIC.get().build(ctx));
+        Optional<List<CompletionItem>> resourceSnippets = this.getResourceSnippets(ctx);
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/scopeproviders/ServiceScopeProvider.java]: if `getResourceSnippets(ctx)` returns a `List<CompletionItem>`; we can return an empty list when there's no resource snippets. Then we don't need `.ifPresent()` check for the list since `.addAll()` internally does it. WDYT?

```java
List<CompletionItem> resourceSnippets = this.getResourceSnippets(ctx);
completionItems.addAll(resourceSnippets);
```

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/scopeproviders/TopLevelScopeProvider.java [hunk 4]
```diff
@@ -0,0 +1,90 @@
+/*
+ * Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/scopeproviders/TopLevelScopeProvider.java]: Check for license headers in this file and other places

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/subproviders/ServiceCompletionProvider.java [hunk 5]
```diff
@@ -17,88 +17,100 @@
...
-            completionItems.addAll(this.getBasicTypes(ctx.get(CompletionKeys.VISIBLE_SYMBOLS_KEY)));
-            completionItems.addAll(this.getPackagesCompletionItems(ctx));
-            getResourceFunction(ctx).map(completionItems::addAll);
-            completionItems.add(Snippet.DEF_FUNCTION.get().build(ctx));
+//        ParserRuleContext parserRuleContext = ctx.get(CompletionKeys.PARSER_RULE_CONTEXT_KEY);
+        List<CommonToken> lhsTokens = ctx.get(CompletionKeys.LHS_TOKENS_KEY);
+        if (lhsTokens.get(lhsTokens.size() - 1).getType() == BallerinaParser.AT) {
+            return this.getProvider(AnnotationAttachmentContextProvider.class).getCompletions(ctx);
         }
+//        ParserRuleContext parserRuleContext = ctx.get(CompletionKeys.PARSER_RULE_CONTEXT_KEY);
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/subproviders/ServiceCompletionProvider.java]: Shall we remove commented code?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/contextproviders/FunctionDefinitionContextProvider.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/contextproviders/FunctionDefinitionContextProvider.java]: resolved

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/scopeproviders/ServiceScopeProvider.java (hunk 3 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/scopeproviders/ServiceScopeProvider.java]: resolved

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/subproviders/ServiceCompletionProvider.java (hunk 5 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/subproviders/ServiceCompletionProvider.java]: resolved

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/scopeproviders/TopLevelScopeProvider.java (hunk 4 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/scopeproviders/TopLevelScopeProvider.java]: Class has been moved to a new module.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/contextproviders/FunctionDefinitionContextProvider.java (hunk 2 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/contextproviders/FunctionDefinitionContextProvider.java]: Fixed
