### PR TITLE
Check `never` fields when inferring `readonly` record

### LINKED ISSUE #39933: [Bug]: `never` type is not incorporated to inferring `readonly`-ness of a record
### Description

$title.

### Steps to Reproduce

```ballerina
public function main() {
    record {| |} a = {};
    readonly b = a; // Allowed.

    record {| 
        never x?;
        never y?;
    |} c = {};
    readonly d = c; // error: incompatible types: expected 'readonly', found 'record {| never x?; never y?; |}'
}
```

### Affected Version(s)

2201.4.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by ushirask**
Fixes #39933

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 1]
```diff
@@ -934,7 +934,7 @@ public void visit(BLangRecordTypeNode recordTypeNode, AnalyzerData data) {
         for (BLangSimpleVariable field : recordFields) {
             if (field.flagSet.contains(Flag.READONLY)) {
                 handleReadOnlyField(isRecordType, fields, field, data);
-            } else {
+            } else if (field.getBType().getKind() != TypeKind.NEVER) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:937]: Won't work for effectively `never` structures?

A better check would be to check if assignable to `never` IMO. Alternatively, could use `Types#isNeverTypeOrStructureTypeWithARequiredNeverMember` too, but the assignability check would be better.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:937]:
```ballerina
type NeverRecord record {|
    record {|
        never a;
    |} x?;
|};

public function main() {
    NeverRecord a = {};
    readonly b = a; // still an error
}
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:937]: And 

```ballerina
type NeverRecord record {|
    never|never x?;
|};
```

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal [hunk 2]
```diff
@@ -284,3 +284,20 @@ type RecordWithReadOnlyFields record {|
 
 RecordWithReadOnlyFields & readonly r1 = {x: []};
 readonly & RecordWithReadOnlyFields & readonly r2 = 1;
+
+type openNeverRecord record {
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal:288]: Fix names here as well.

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal [hunk 3]
```diff
@@ -924,6 +924,61 @@ function assertTrue(any|error actual) {
     assertEquality(true, actual);
 }
 
+type RecordWithNeverField record {|
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal:927]: Shall we add these before the `const ASSERTION_ERROR_REASON = "AssertionError";` declaration? Let's keep the assertion helper functions at the end of the file as before.

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal [hunk 4]
```diff
@@ -924,6 +924,61 @@ function assertTrue(any|error actual) {
...
+    readonly g1 = g;
+    RecordWithNeverWithoutReadonly h = {y: "abc"};
+    RecordWithNeverFieldRecord i = {};
+    readonly i1 = i;
+    RecordWithNeverUnion j = {};
+    readonly j1 = j;
+
+    assertTrue(d is record {|never x?; never y?;|} & readonly);
+    assertTrue(e1 is record {|never x?;|} & readonly);
+    assertTrue(f is record {|never x?; anydata...;|});
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal:975]: To make sure f is not readonly. 
```suggestion
    assertFalse(f is record {|never x?; anydata...;|} & readonly);
```

Otherwise,  defining `record { never x?; } f` and checking`f is record {| never x?; anydata...; |}` is a obviously known `true`.

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal [hunk 5]
```diff
@@ -924,6 +924,61 @@ function assertTrue(any|error actual) {
...
+    assertTrue(g1 is record {|never x?; int y;|} & readonly);
+    assertTrue(h is record {|never x?; string y;|});
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal:977]:
```suggestion
    assertFalse(h is record {|never x?; string y;|} & readonly);
```

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal [hunk 6]
```diff
@@ -924,6 +924,61 @@ function assertTrue(any|error actual) {
...
+       record {|
+           never a;
+       |} x?;
+   |};
+
+type RecordWithNeverUnion record {|
+    never|never x?;
+|};
+
+function testNeverFieldRecord() {
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal:955]:
```suggestion
function testRecordReadonlynessWithNeverFields() {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal [hunk 7]
```diff
@@ -924,6 +924,61 @@ function assertTrue(any|error actual) {
     assertEquality(true, actual);
 }
 
+type RecordWithNeverField record {|
+    never x?;
+|};
+
+type OpenRecordWithNever record {
```
[the remark this answers is not in the document]
Comment (ushirask) [reply tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal:931]: Will go with arbitrary names.

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal (hunk 2 above)
Comment (lochana-chathura) [reply tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal:288]: @ushirask seems you have missed updating this file.

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal [hunk 8]
```diff
@@ -284,3 +284,20 @@ type RecordWithReadOnlyFields record {|
...
+    never x?;
+};
+
+type neverRecordWithNotReadonly record {|
+    never x?;
+    string y;
+|};
+
+function testNeverFieldRecord() {
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal:297]:
```suggestion
function testRecordReadonlynessWithNeverFields() {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal (hunk 2 above)
Comment (ushirask) [reply tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal]: Updated.

**Review by lochana-chathura — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal [hunk 9]
```diff
@@ -284,3 +284,20 @@ type RecordWithReadOnlyFields record {|
...
+    never x?;
+    string y;
+|};
+
+function testRecordReadonlynessWithNeverFields() {
+    R1 r1 = {};
+    R2 r2 = {y: "hello"};
+
+    readonly x = r1;
+    readonly y = r2;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal:302]:
```suggestion
    readonly x = r1;
    
    R2 r2 = {y: "hello"};
    readonly y = r2;
```

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal [hunk 10]
```diff
@@ -284,3 +284,20 @@ type RecordWithReadOnlyFields record {|
...
+}
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal:303]: Shall we add one with an an anonymous record also?

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal [hunk 11]
```diff
@@ -918,6 +918,61 @@ function testDefaultValueFromCETBeingUsedWithReadOnlyFieldsInTheMappingConstruct
...
+    R2 f = {};
+    R3 g = {y: 1};
+    readonly g1 = g;
+    R4 h = {y: "abc"};
+    R5 i = {};
+    readonly i1 = i;
+    R6 j = {};
+    readonly j1 = j;
+
+    assertTrue(d is record {|never x?; never y?;|} & readonly);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal:967]: Reorganize so that variables and declarations are together. Helps with readability.

Comment (ushirask) [reply tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal:968]: Fixed.

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal (hunk 10 above)
Comment (ushirask) [reply tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal:309]: Added.

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal (hunk 11 above)
Comment (lochana-chathura) [reply tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields.bal:968]: I think what @MaryamZi meant was something like this. Since relevant declarations and assertions are together it improves the readability.

```bal
record {|
        never x?;
        never y?;
    |} c = {};
readonly c1 = c;
assertTrue(d is record {|never x?; never y?;|} & readonly);

R1 e = {};
readonly e1 = e;
assertTrue(e1 is record {|never x?;|} & readonly);
```

Let's change d to c1 similar to how we have assigned rest.

**Review by lochana-chathura — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ReadonlyRecordFieldTest.java [hunk 12]
```diff
@@ -117,6 +118,12 @@ public void testReadonlyRecordFieldsNegative() {
         validateError(result, index++, "incompatible types: expected 'readonly', found 'Unauthorized?'", 273, 18);
         validateError(result, index++, "missing non-defaultable required record field 'y'", 285, 42);
         validateError(result, index++, "incompatible types: expected 'RecordWithReadOnlyFields', found 'int'", 286, 53);
+        validateError(result, index++, "incompatible types: expected 'readonly', found 'R1'",
+                299, 18);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/ReadonlyRecordFieldTest.java:122]: Can be on the same line?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/assign/LValueTest.java [hunk 13]
```diff
@@ -95,7 +95,8 @@ public void testSemanticsNegativeCases() {
         validateError(semanticsNegativeResult, i++, "cannot update 'readonly' value of type 'record {| |} & " +
                 "readonly'", 110, 5);
         // https://github.com/ballerina-platform/ballerina-lang/issues/39933
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/assign/LValueTest.java:97]: This comment can be removed now?

File: tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal [hunk 14]
```diff
@@ -284,3 +284,26 @@ type RecordWithReadOnlyFields record {|
...
+type R1 record {
+    never x?;
+};
+
+type R2 record {|
+    never x?;
+    string y;
+|};
+
+function testRecordReadonlynessWithNeverFields() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/readonly_record_fields_negative.bal:297]: We usually include `Negative` in error tests.

**Review by MaryamZi — APPROVED** [review]
