### PR TITLE
Fix issues with tuple type conversion

### LINKED ISSUE #31747: `cloneWithType` does not work with Tuple types properly
**Description:**
Conversion with `cloneWithType` is not working as expected for Tuple type conversions. 

**Steps to reproduce:**
Following should succeed but currently fails. 
```
type T1 record {
    int x = 1;
    int y = 2;
};
type T2 record {|
    int x = 5;
    int y = 6;
    int z = 7;
|};
type T1_T2 [T1, T2]; 
public function main() {
    T1 a = {};
    T1 b = {};
    [T1, T1] x = [a, b];
    anydata y = x;
    var result = y.cloneWithType(T1_T2);
    io:println(result);
}
```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Team/jBallerina

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #31747

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 1]
```diff
@@ -463,6 +469,51 @@ private static boolean isConvertibleToArrayType(Object sourceValue, BArrayType t
...
+        for (int i = 0; i < targetTypeSize; i++) {
+            convertibleTypes = getConvertibleTypes(source.getRefValue(i), targetTypes.get(i), unresolvedValues);
+            if (convertibleTypes.isEmpty()) {
+                return false;
+            }
+            if (convertibleTypes.size() > 1 && !convertibleTypes.contains(TypeChecker.getType(source.getRefValue(i)))
+                    && !hasIntegerSubTypes(convertibleTypes)) {
+                return false;
+            }
+        }
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:502]: Shall we move this logic to a separate method?
Since we the only difference is the `targetTypes.get(i)` part, we can pass it as a parameter

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion.bal [hunk 2]
```diff
@@ -855,14 +857,22 @@ public class O1 {
   public int y = 0;
 }
 
-function testTupleConversion1() returns [T1, T1]|error {
+function testTupleConversion1() {
     T1 a = {};
     T2 b = {};
-    [T1, T2] x = [a, b];
+    [T1, T2] x1 = [a, b];
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion.bal:863]: Shall we use the already defined types `T1_T1` & `T1_T2` here and similar cases?
We can re-use the type.

File: langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal [hunk 3]
```diff
@@ -919,6 +919,74 @@ function testCloneWithTypeIntArrayToUnionArray() {
...
+
+    [float|decimal, int|byte...]|error e = arr.cloneWithType();
+    assert(e is error, true);
+    err = <error> e;
+    message = err.detail()["message"];
+    messageString = message is error ? message.toString() : message.toString();
+    assert(err.message(), "{ballerina/lang.typedesc}ConversionError");
+    assert(messageString, "'int[]' value cannot be converted to '[(float|decimal),(int|byte)...]'");
+
+    [string, string:Char, string|string:Char]|error f = arr.cloneWithType();
```
Comment (HindujaB) [inline langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal:955]: Shall we also have some tests with structured type as a member type?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 4]
```diff
@@ -463,6 +469,51 @@ private static boolean isConvertibleToArrayType(Object sourceValue, BArrayType t
...
+
+        for (int i = 0; i < targetTypeSize; i++) {
+            convertibleTypes = getConvertibleTypes(source.getRefValue(i), targetTypes.get(i), unresolvedValues);
+            if (convertibleTypes.isEmpty()) {
+                return false;
+            }
+            if (convertibleTypes.size() > 1 && !convertibleTypes.contains(TypeChecker.getType(source.getRefValue(i)))
+                    && !hasIntegerSubTypes(convertibleTypes)) {
+                return false;
+            }
```
Comment (riyafa) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:501]: we can combine the if the two if statements using an `||` and move the boolean checks to a separate method

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 5]
```diff
@@ -463,6 +469,51 @@ private static boolean isConvertibleToArrayType(Object sourceValue, BArrayType t
         return true;
     }
 
+    private static boolean isConvertibleToTupleType(Object sourceValue, BTupleType targetType,
```
Comment (riyafa) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:472]: Most of the code in this function seems to be similar to the previous function `isConvertibleToArrayType`. Shall we try to reduce duplication by reusing code?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion.bal (hunk 2 above)
Comment (gabilang) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion.bal]: Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/31779/commits/93a63a8b643f9e14f56219f8cc2aba8a54280939

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java (hunk 5 above)
Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:467]: Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/31779/commits/93a63a8b643f9e14f56219f8cc2aba8a54280939

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java (hunk 1 above)
Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java]: Following part has been moved to a separate method where we can reuse the code for the method `isConvertibleToArrayType` also. 
```
convertibleTypes = getConvertibleTypes(source.getRefValue(i), targetTypes.get(i), unresolvedValues);
if (convertibleTypes.isEmpty()) {
    return false;
}
if (convertibleTypes.size() > 1 && !convertibleTypes.contains(TypeChecker.getType(source.getRefValue(i)))
        && !hasIntegerSubTypes(convertibleTypes)) {
    return false;
}
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java (hunk 4 above)
Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:489]: The both `if` checks have been moved to a separate method and `convertibleTypes.isEmpty()` has been kept as an early separate check to prevent generating multiple instructions on this particular failing case.

File: langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal [hunk 6]
```diff
@@ -919,6 +919,82 @@ function testCloneWithTypeIntArrayToUnionArray() {
     assert(messageString, "'float[]' value cannot be converted to '(lang.int:Signed16|lang.int:Unsigned8|decimal)[]'");
 }
 
+function testCloneWithTypeArrayToTuple() {
```
Comment (riyafa) [inline langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal:922]: can we split this test to multiple functions so that it is more readable? We can make the array  `arr` to be a global variable if needed. Also it would be better if we can move the newly created tests to a separate file as this file seems to have become really long

File: langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal [hunk 7]
```diff
@@ -919,6 +919,82 @@ function testCloneWithTypeIntArrayToUnionArray() {
...
+    [map<int>, [string, int]...]|error g = arr.cloneWithType();
+    assert(g is error, true);
+    err = <error> g;
+    message = err.detail()["message"];
+    messageString = message is error ? message.toString() : message.toString();
+    assert(err.message(), "{ballerina/lang.typedesc}ConversionError");
+    assert(messageString, "'int[]' value cannot be converted to '[map<int>,[string,int]...]'");
+}
+
+function testCloneWithTypeTuple() {
```
Comment (riyafa) [inline langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal:972]: We can split this function also.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 8]
```diff
@@ -449,20 +455,61 @@ private static boolean isConvertibleToArrayType(Object sourceValue, BArrayType t
...
+    private static boolean isConvertibleToArrayInstance(Object sourceElement, Type targetType,
+                                                        List<TypeValuePair> unresolvedValues) {
+        Set<Type> convertibleTypes = getConvertibleTypes(sourceElement, targetType, unresolvedValues);
+        if (convertibleTypes.isEmpty()) {
+            return false;
+        }
+        if (convertibleTypes.size() > 1 && !convertibleTypes.contains(TypeChecker.getType(sourceElement))
+                && !hasIntegerSubTypes(convertibleTypes)) {
+            return false;
+        }
```
Comment (riyafa) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:509]: I think the following is possible
```suggestion
        if (convertibleTypes.isEmpty() || (convertibleTypes.size() > 1 && !convertibleTypes.contains(TypeChecker.getType(sourceElement))
                && !hasIntegerSubTypes(convertibleTypes))) {
            return false;
        }
```
We can move the boolean checks to a separate function. I mean what is inside the brackets of the `if` statement

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 9]
```diff
@@ -449,20 +455,61 @@ private static boolean isConvertibleToArrayType(Object sourceValue, BArrayType t
...
+        int sourceTypeSize = source.size();
+        int targetTypeSize = targetTypes.size();
+        Type targetRestType = targetType.getRestType();
+
+        if (sourceTypeSize < targetTypeSize) {
+            return false;
+        }
+        if (targetRestType == null && sourceTypeSize > targetTypeSize) {
+            return false;
+        }
```
Comment (riyafa) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:484]: we can combine these if statements as well:
```suggestion
        if (sourceTypeSize < targetTypeSize || (targetRestType == null && sourceTypeSize > targetTypeSize)) {
            return false;
        }
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java (hunk 8 above)
Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:509]: Yeah, it is possible, but we are going to create too many instructions for a failing case right? I was just thinking about for an early return when the convertible types set is empty. WDYT?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 10]
```diff
@@ -449,20 +455,62 @@ private static boolean isConvertibleToArrayType(Object sourceValue, BArrayType t
...
+            if (!isConvertibleToArrayInstance(source.get(i), targetTypeElementType, unresolvedValues)) {
+                return false;
+            }
+        }
+        return true;
+    }
+
+    private static boolean isConvertibleToTupleType(Object sourceValue, BTupleType targetType,
+                                                    List<TypeValuePair> unresolvedValues) {
+        if (!(sourceValue instanceof ArrayValue)) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:469]: Do we need this line. I think it will be always ArrayValue

Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:469]: When the target type is tuple type, the execution will reach to this place and we can't guarantee the source type here is always an instance of `ArrayValue`. This check will ensure the success of `Object` to `ArrayValue` casting. So, IMO we need this check here.

**Review by warunalakshitha — APPROVED** [review]
LGTM
