### PR TITLE
Fix type checking for error binding pattern type ref

### LINKED ISSUE #31853: No compilation error given for undefined type reference
**Description:**
The bellow program compiles and run without any error. Note `myError` is not defined.
```bal
public function main() {
   error error myError(b) = error("1");
}
```

### PR DESCRIPTION
**Pull request by KRVPerera**
## Purpose

Fixes #31853

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 1]
```diff
@@ -2851,8 +2851,12 @@ private void initializeBLangVariable(BLangVariable var, TypeDescriptorNode type,
             }
         }
 
+        boolean typeAvailable = false;
+        if (var.getKind() == NodeKind.ERROR_VARIABLE) {
+           typeAvailable = var.typeNode != null;
+        }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:2857]: Can't we do

```suggestion
        boolean typeAvailable = var.getKind() == NodeKind.ERROR_VARIABLE && var.typeNode != null;
```

Also wondering if we can have the name reflect that it is an error binding pattern with an error type reference? Like a version of `errorBindingPatternWithTypeRef` maybe?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ErrorBindingPatternTest.java [hunk 2]
```diff
@@ -42,6 +50,16 @@ public void setup() {
                 "/error_binding_pattern_negative.bal");
     }
 
+    @Test
+    public void testNegativeSemantics() {
+        CompileResult buildError = BCompileUtil.compile("test-src/statements/matchstmt/" +
+                "varbindingpatternmatchpattern/error_type_ref_negative.bal");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ErrorBindingPatternTest.java:56]:
```suggestion
        CompileResult buildError = BCompileUtil.compile(
                "test-src/statements/matchstmt/varbindingpatternmatchpattern/error_type_ref_negative.bal");
```

Just to help with navigating to the file.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ErrorBindingPatternTest.java [hunk 3]
```diff
@@ -42,6 +50,16 @@ public void setup() {
...
+        int i = -1;
+        BAssertUtil.validateError(buildError, ++i, "invalid error binding pattern with type 'other'", 18, 11);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ErrorBindingPatternTest.java:58]: If it is a straightforward fix, shall we stop logging this error with "other"? Errors with "other" are usually because of other errors and don't add value to the user?

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/error_type_ref_negative.bal [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+//
+// Unless required by applicable law or agreed to in writing,
+// software distributed under the License is distributed on an
+// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+// KIND, either express or implied.  See the License for the
+// specific language governing permissions and limitations
+// under the License.
+
+function testNegative2() {
+    error error myError(b) = error("1");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/varbindingpatternmatchpattern/error_type_ref_negative.bal:18]: Although not related to this fix, shall we add a test with `var` also?

```ballerina
var error myError(b) = error("1");
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ErrorBindingPatternTest.java (hunk 3 above)
Comment (KRVPerera) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/varbindingpatternmatchpattern/ErrorBindingPatternTest.java]: done

**Review by MaryamZi — APPROVED** [review]

**Review by hasithaa — APPROVED** [review]
