### PR TITLE
[Debugger] Add conditional breakpoint support

### LINKED ISSUE #28565: Ballerina debugger support for conditional breakpoints
**Description:**
Currently Ballerina debugger does not seems to support conditional breakpoints. Since now we are supporting evaluate expressions, how about working on conditional breakpoints support. This would be really useful as we used to do the same for other languages and IDEs.

We can implement it even without runtime support; for instance runtime sees a conventional breakpoint. When the breakpoint got hit; debugger implementation evaluate the current condition against runtime values. if it is evaluated as true, we break; or else auto resume the breakpoint. BTW performance will be further improved if the runtime natively support conditional breakpoints.

conditiona-bp

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by praveennadarajah**
This PR will add conditional breakpoint support for Ballerina.

Fixes #28565

https://user-images.githubusercontent.com/11292766/109760854-70967c80-7c15-11eb-9233-2a80d75b3ced.mov

### CODE REVIEW

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java [hunk 1]
```diff
@@ -179,7 +179,7 @@ ClientConfigHolder getClientConfigHolder() {
         // Todo - Implement
         capabilities.setSupportsCompletionsRequest(false);
         capabilities.setSupportsRestartRequest(false);
-        capabilities.setSupportsConditionalBreakpoints(false);
+        capabilities.setSupportsConditionalBreakpoints(true);
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java:182]: Lets move up this line to the `supported capabilities` list.

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java [hunk 2]
```diff
@@ -464,6 +472,19 @@ public void sendOutput(String output, String category) {
...
+            SuspendedContext ctx = new SuspendedContext(project, context.getDebuggeeVM(),
+                    getAllThreads().get(threadReference.uniqueID()), frame);
+            ExpressionEvaluator evaluator = new ExpressionEvaluator(ctx);
+            return evaluator.evaluate(expression);
+        } catch (JdiProxyException e) {
+            LOGGER.error(e.getMessage(), e);
+            return null;
+        }
+    }
+
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java:487]: Shall we make this package-private + static?

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java [hunk 3]
```diff
@@ -478,6 +499,15 @@ private Breakpoint toBreakpoint(SourceBreakpoint sourceBreakpoint, Source source
...
     }
 
+    private BalBreakpoint toBalBreakpoint(SourceBreakpoint sourceBreakpoint, Source source) {
+        BalBreakpoint balBreakpoint = new BalBreakpoint();
+        balBreakpoint.setLine(sourceBreakpoint.getLine());
+        balBreakpoint.setSource(source);
+        balBreakpoint.setVerified(true);
+        balBreakpoint.setCondition(sourceBreakpoint.getCondition());
+        return balBreakpoint;
+    }
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java:509]: Why cant we use the `SourceBreakpoint` instances itself instead of creating a custom breakpoint type, as it seems like `BalBreakpoint` is used only to hold a subset of information of the `SourceBreakpoint`?

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java [hunk 4]
```diff
@@ -103,11 +104,31 @@ private boolean processEvent(EventSet eventSet, Event event) {
...
-            stoppedEventArguments.setThreadId(((BreakpointEvent) event).thread().uniqueID());
-            stoppedEventArguments.setAllThreadsStopped(true);
-            context.getClient().stopped(stoppedEventArguments);
+            Value value = null;
+            String qualifiedClassName =
+                getQualifiedClassName(context, ((BreakpointEvent) event).location().declaringType());
+            Map<Integer, BalBreakpoint> balBreakpoints = this.balBreakpoints.get(qualifiedClassName);
+            int lineNumber = ((BreakpointEvent) event).location().lineNumber();
+
+            if (balBreakpoints != null && balBreakpoints.containsKey(lineNumber)) {
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java:113]: Is this null check for `balBreakpoints` necessary in here?

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java [hunk 5]
```diff
@@ -103,11 +104,31 @@ private boolean processEvent(EventSet eventSet, Event event) {
...
+                value = context.getAdapter().evaluateExpression(balBreakpoints.get(lineNumber).getCondition(),
+                    ((BreakpointEvent) event).thread());
+            }
+            if (balBreakpoints != null && balBreakpoints.containsKey(lineNumber)
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java:117]: Is this null check for `balBreakpoints` necessary in here?

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java [hunk 6]
```diff
@@ -103,11 +104,31 @@ private boolean processEvent(EventSet eventSet, Event event) {
...
+                && balBreakpoints.get(lineNumber).getCondition() != null
+                && !Boolean.parseBoolean(Objects.requireNonNull(value).toString())) {
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java:119]: Directly trying to parse into boolean is unsafe, as we cannot guarantee about the type of conditional expression result (can be non-boolean)

**Review by NipunaRanasinghe — CHANGES_REQUESTED** [review]

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java [hunk 7]
```diff
@@ -464,6 +472,19 @@ public void sendOutput(String output, String category) {
         }
     }
 
+    public Value evaluateExpression(String expression, ThreadReference threadReference) {
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java:475]: How about using a name like `evaluateBreakpointCondition`, as this util function is specifically written of that purpose? Also, Shall we modify the method to return a `boolean` instead of returning the direct result (which is a JDI value instance)?

**Comment by NipunaRanasinghe** [comment]
@praveennadarajah Are we planning add some integration tests to cover conditional break point scenarios?

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java (hunk 3 above)
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java]: Removed custom `balBreakpoint` class and used `SourceBreakpoint` information

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/BalBreakpoint.java [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+
+package org.ballerinalang.debugadapter;
+
+import org.eclipse.lsp4j.debug.Source;
+
+/**
+ * Information about ballerina breakpoint (Properties).
```
[the remark this answers is not in the document]
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/BalBreakpoint.java]: Refer [this](https://github.com/ballerina-platform/ballerina-lang/pull/28968#discussion_r586286907) comment.

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/BalBreakpoint.java [hunk 9]
```diff
@@ -0,0 +1,64 @@
...
+ */
+public class BalBreakpoint {
+
+    private Long line;
+    private Source source;
+    private Boolean verified;
+    private String condition;
```
[the remark this answers is not in the document]
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/BalBreakpoint.java]: Refer [this](https://github.com/ballerina-platform/ballerina-lang/pull/28968#discussion_r586286907) comment.

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java (hunk 1 above)
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java]: Done.

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java (hunk 2 above)
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java]: Cannot make to `static` as this method is using non-static members. This method is written in `JBallerinaDebugServer` class to get the maximum use of its class variable and used in `JDIEventProcessor` class. Therefore it cannot be made `private`. Therefore keeping it as `public`

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java (hunk 4 above)
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java]: There are instances where `balBreakpoints` can be null. In that case `balBreakpoints.containsKey(lineNumber)` throwing a NPE. Therefore this check is required.

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java (hunk 5 above)
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java]: Refer to [this](https://github.com/ballerina-platform/ballerina-lang/pull/28968#discussion_r586292855) comment.

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java (hunk 6 above)
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java]: Fixed

**Comment by praveennadarajah** [comment]
> @praveennadarajah Are we planning add some integration tests to cover conditional breakpoints related scenarios?

@NipunaRanasinghe Current debug framework does not support conditional breakpoints. We need to implement that first and then need to add possible integration tests.

I have created https://github.com/ballerina-platform/ballerina-lang/issues/28981 to track this issue.

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java (hunk 7 above)
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java]: Done

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java (hunk 2 above)
Comment (NipunaRanasinghe) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java]: @praveennadarajah I meant, `package-private` :slightly_smiling_face: Also, whats the reason for keeping this util inside `JballerinaDebugServer`, since this is used only within `JDIEventProcessor`? (If your intention is to use the state variables of `JBallerinaDebugServer`, those are already accessible from the `JDIEventProcessor`)

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java (hunk 4 above)
Comment (NipunaRanasinghe) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java]: I'm still not sure how it can be null, given that its declared as final and already initialized as an empty map :slightly_smiling_face:

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java [hunk 10]
```diff
@@ -103,11 +105,30 @@ private boolean processEvent(EventSet eventSet, Event event) {
...
+                continuedEventArguments.setThreadId(((BreakpointEvent) event).thread().uniqueID());
+                continuedEventArguments.setAllThreadsContinued(true);
+                context.getClient().continued(continuedEventArguments);
+            } else {
+                StoppedEventArguments stoppedEventArguments = new StoppedEventArguments();
+                stoppedEventArguments.setReason(StoppedEventArgumentsReason.BREAKPOINT);
+                stoppedEventArguments.setThreadId(((BreakpointEvent) event).thread().uniqueID());
+                stoppedEventArguments.setAllThreadsStopped(true);
+                context.getClient().stopped(stoppedEventArguments);
+            }
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java:131]: Can't we simplify the logic in here as follows?
```java
if (condition) {
   // suspend
} else {
  // continue
} 
```

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java (hunk 4 above)
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java]: According to the recent,
`Map<Integer, SourceBreakpoint> sourceBreakpoints = this.sourceBreakpoints.get(qualifiedClassName);` 

Here `sourceBreakpoints` can be null when `this.sourceBreakpoints` doesn't contain any values for key `qualifiedClassName`

Comment (NipunaRanasinghe) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java]: Sorry I've missed it since you've used the same variable name locally. +1

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java [hunk 11]
```diff
@@ -464,6 +469,20 @@ public void sendOutput(String output, String category) {
...
     }
 
+    public boolean evaluateBreakpointCondition(String expression, ThreadReference threadReference) {
+        try {
+            StackFrameProxyImpl frame = getAllThreads().get(threadReference.uniqueID()).frame(0);
+            SuspendedContext ctx = new SuspendedContext(project, context.getDebuggeeVM(),
+                    getAllThreads().get(threadReference.uniqueID()), frame);
+            ExpressionEvaluator evaluator = new ExpressionEvaluator(ctx);
+            String condition = evaluator.evaluate(expression).toString();
+            return condition.equalsIgnoreCase(CONDITION_TRUE);
```
[the remark this answers is not in the document]
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java:479]: Here if the expression returns a boolean `true`, then String `condition` will get the value `"true"`, and
if the expression returns String `"true"`, the String `condition` will get the value `""true""`. 
Therefore this logic might not cause false positive.

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java (hunk 2 above)
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java]: Moved the util method to `JDIEventProcess` class and made it private.

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java (hunk 10 above)
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java]: Done

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java [hunk 12]
```diff
@@ -144,6 +166,20 @@ private boolean processEvent(EventSet eventSet, Event event) {
...
+            SuspendedContext ctx = new SuspendedContext(context.getSourceProject(), context.getDebuggeeVM(),
+                    context.getAdapter().getAllThreads().get(threadReference.uniqueID()), frame);
+            ExpressionEvaluator evaluator = new ExpressionEvaluator(ctx);
+            String condition = evaluator.evaluate(expression).toString();
+            return condition.equalsIgnoreCase(CONDITION_TRUE);
+        } catch (JdiProxyException e) {
+            LOGGER.error(e.getMessage(), e);
+            return false;
+        }
+    }
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java:181]: In here, Your logic returns `false` for the expressions which produces a non-boolean results as well. Shall we improve this behavior by notifying the user that it is an invalid expression instead?

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (NipunaRanasinghe) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JBallerinaDebugServer.java]: Refer https://github.com/ballerina-platform/ballerina-lang/pull/28968#discussion_r587085780

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java (hunk 12 above)
Comment (praveennadarajah) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java:181]: Yes, we can notify the user when they add an invalid expression. 
I have created https://github.com/ballerina-platform/ballerina-lang/issues/28992 to track this.

**Review by NipunaRanasinghe — DISMISSED** [review]

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/BalBreakpoint.java [hunk 13]
```diff
@@ -0,0 +1,75 @@
...
+
+    public void setCondition(String condition) {
+        this.condition = condition;
+    }
+
+    public Breakpoint getBreakpoint() {
+        Breakpoint breakpoint = new Breakpoint();
+        breakpoint.setLine(line);
+        breakpoint.setSource(source);
+        breakpoint.setVerified(true);
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/BalBreakpoint.java:72]:
```suggestion
        breakpoint.setVerified(verified);
```

**Review by NipunaRanasinghe — APPROVED** [review]
