### PR TITLE
Fix CCE in Function Calls with Future Return Types

### LINKED ISSUE #34270: [Semantic API] CCE when checking the type of a function call which returns a future
Consider the following:
```ballerina
public function test() {
    future<int> futureResult = <1>foo()<2>;
}

function foo() returns future<int> {
    return start bar();
}

function bar() returns int {
    return 10;
}
```
When trying using `typeOf()` to get the type in the above illustrated case, it fails with a CCE. Related issue #33016.

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #34270

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTestNew.java [hunk 1]
```diff
@@ -321,6 +321,15 @@ public void testStartAction() {
...
 
+    @Test
+    public void testFutureResultType() {
+        TypeSymbol type = getExprType(350, 31, 350, 38);
+        assertEquals(type.typeKind(), FUTURE);
+        Optional<TypeSymbol> typeParameter = ((FutureTypeSymbol) type).typeParameter();
+        assertTrue(typeParameter.isPresent());
+        assertEquals(typeParameter.get().typeKind(), INT);
+    }
+
```
Comment (pubudu91) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ExpressionTypeTestNew.java:332]: Let's add another test case to cover the type of `barFn()` within the start action. i.e., `(354, 17, 354, 24)`

**Comment by pubudu91** [comment]
Please tag the PR and the issue with the relevant milestone.

**Review by mohanvive — DISMISSED** [review]

**Comment by mohanvive** [comment]
@sanjana can you please change the base to patch branch?

**Review by mohanvive — APPROVED** [review]
