### PR TITLE
Fix create function in return statement and fail expression

### LINKED ISSUE #34767: Incorrect create function code action
**Description:**

In the first two scenarios we do not give the expected return type and its default value in the created function even though we identify the return type by the compiler. In the 3rd scenario, the number of parameters are doubled and has changed its name and type.

1) 
Screenshot 2022-01-21 at 11 22 10

2)
Screenshot 2022-01-21 at 11 23 16

3)
Screenshot 2022-01-21 at 11 24 23

**Steps to reproduce:**
1)
```
function test1() {
    fail getFail();
}
```
2)
```
function test2() returns int {
    return getReturn();
}
```
3)
```
function test3() {
    boolean a = true;
    a = getBool(boolean q, boolean w);
}
```

**Affected Versions:**
SL 2201.0.0 RC1

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
$subject

Fixes #34767

## Approach
Overridden required methods in the `FunctionCallExpressionTypeFinder`.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java [hunk 1]
```diff
@@ -345,6 +349,35 @@ public void visit(ImplicitNewExpressionNode implicitNewExpressionNode) {
...
+        this.semanticModel.typeOf(returnStatementNode).ifPresent(this::checkAndSetTypeResult);
+        if (resultFound) {
+            return;
+        }
+
+        // Get function type symbol and get return type descriptor from it
+        returnStatementNode.parent().accept(this);
+        if (resultFound && returnTypeSymbol.typeKind() == TypeDescKind.FUNCTION) {
+            FunctionTypeSymbol functionTypeSymbol = (FunctionTypeSymbol) returnTypeSymbol;
+            functionTypeSymbol.returnTypeDescriptor().ifPresentOrElse(this::checkAndSetTypeResult, this::resetResult);
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java:375]: Isn't it better if we move this logic to the function definition node itself.  As the return type  of function represents  the particular  function, I feel that this logic does not belong here.

**Review by malinthar — CHANGES_REQUESTED** [review]
Minor change request

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java (hunk 1 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java:375]: I thought of having this logic in the `FunctionDefinitionNode` visit method. Then decided not to. 
```ballerina
function myFunction(int x = fn1()) returns int {
   return undefinedFunction();
}
```
Can we guarantee that the `visit(FunctionDefinitionNode)` is being called by via `function call expr -> return statement -> function body -> function definition` hierarchy only?
What if we wanted to find the return type of `fn1()`? (For the case of `fn1()`, I think it is covered by a function parameter node visit method. Not sure. But it's the idea.) Therefore, to keep the logic clean, I thought of going with the current approach. WDYT?

**Review by malinthar — APPROVED** [review]
LGTM!
