### PR TITLE
Fix taint analysis not working with raw templates generated from a query

### LINKED ISSUE #25318: Taint Analysis Not Working with Raw Templates Generated from a Query
Following code:-

```ballerina
    resource function addEmployeeBatch(http:Caller caller, http:Request req,
                                       Employee[] payload) returns error? {
        sql:ParameterizedQuery[] batchQuery = from var emp in payload
            select `INSERT INTO Employee VALUES (${emp.id}, ${emp.name},
            ${emp.age}, ${emp.team})`;
        _ = check empDB->batchExecute(batchQuery);
    }
```

The tainted values passed in from "payload", it's data is transferred to "batchQuery" and this compiles without untainiting the input.

### PR DESCRIPTION
**Pull request by lasinicl**
Fixes #25318

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/utils/SQLDBUtils.java [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+    }
+
+    private static String readFileToString(String path) {
+        // The name of a resource is a '/'-separated path name that identifies the resource.
+        // Hence regardless of the separator corresponding to the OS forward slash should be used.
+        URL fileResource = BCompileUtil.class.getClassLoader().getResource(path.replace("\\", "/"));
+        try {
+            return FileUtils.readFileToString(new File(fileResource.toURI()), StandardCharsets.UTF_8);
+        } catch (IOException | URISyntaxException e) {
+            log.error("File reading failed", e);
```
Comment (mohanvive) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/utils/SQLDBUtils.java:140]: Please provide the path with the error message.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryTaintAnalysisNegativeTests.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
+/*
```
Comment (mohanvive) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryTaintAnalysisNegativeTests.java:1]: Can you please write a testcase for happy path as well.

**Review by mohanvive — CHANGES_REQUESTED** [review]

**Review by mohanvive — APPROVED** [review]
