### PR TITLE
Parser changes related to `on fail check` node

### LINKED ISSUE #40324: [New Feature]: Make it easier to check and return a new error with additional context #1197
### Description

This Issue created to track https://github.com/ballerina-platform/ballerina-spec/issues/1197 implenetation

### Describe your problem(s)

_No response_

### Describe your solution(s)

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by DamithaSenevirathne**
Fixes #40324 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -9065,7 +9073,18 @@ private STNode parseResourceAccessSegmentRhs(boolean isRhsExpr, boolean isInMatc
                 return parseResourceAccessSegmentRhs(isRhsExpr, isInMatchGuard);
         }
     }
-    
+    private STNode parseOnFailCheck() {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:9076]: Let's document the grammar parsed by this method smilar to other methods. Also, need to update `parseCheckExpression()` doc to reflect the new grammar.  e.g. `checking-expr := checking-keyword expression [on-fail-check]`

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STOnFailCheckNode.java [hunk 2]
```diff
@@ -0,0 +1,130 @@
+/*
+ *  Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STOnFailCheckNode.java:2]: Although this is an auto-generated code, we update the license header year manually and commit. This is a lacking requirement in treegen.

File: compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json [hunk 3]
```diff
@@ -693,6 +693,11 @@
                 {
                     "name": "expression",
                     "type": "ExpressionNode"
+                },
+                {
+                    "name": "onFailClause",
```
Comment (lochana-chathura) [inline compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json:698]:
```suggestion
                    "name": "onFailCheck",
```
As per our last discussion.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 4]
```diff
@@ -9065,7 +9073,18 @@ private STNode parseResourceAccessSegmentRhs(boolean isRhsExpr, boolean isInMatc
...
+        startContext(ParserRuleContext.CHECK_ON_FAIL);
+        STNode onKeyword = parseOnKeyword();
+        STNode failKeyword = parseFailKeyword();
+        STNode varName = parseVariableName();
+        STNode rightDoubleArrow = parseDoubleRightArrow();
+        STNode errConstructor = parseErrorConstructorExpr(false);
+        endContext();
+        return STNodeFactory.createOnFailCheckNode(null, onKeyword,
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:9084]: We can't parse `null` for the kind. node.kind is called most of the time. 
Need to add `"kind": "ON_FAIL_CHECK"` property in the `syntax_tree_descriptor.json`
Also, an entry in `SyntaxKind.java`

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 5]
```diff
@@ -7179,10 +7179,18 @@ private STNode parseCheckExpression(boolean isRhsExpr, boolean allowActions, boo
         STNode checkingKeyword = parseCheckingKeyword();
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:7179]: Now that we have an optional `on-fail-check` at the end of `check-expr`, we need to add a new path as the next rule in the `seekMatchInExpressionRhs()`  for `check-expr`. In order to distinguish it at that method we need to a context to identify whether we are in the `check-expr`. 
```suggestion
        startContext(ParserRuleContext.CHECK_EXPRESSION);
        STNode checkingKeyword = parseCheckingKeyword();
```

**Review by lochana-chathura — CHANGES_REQUESTED** [review]

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 5 above)
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:7179]: 1. Once we have the context, we can add the following in `seekMatchInExpressionRhs()` to point the next rule as `ParserRuleContext.ON_FAIL_CHECK`.
```java
        } else if (parentCtx == ParserRuleContext.CHECK_EXPRESSION) {
            STToken nextToken = this.tokenReader.peek(lookahead);
            if (nextToken.kind == SyntaxKind.ON_KEYWORD) {
                nextContext = ParserRuleContext.ON_FAIL_CHECK;
            } else {
                nextContext = ParserRuleContext.CHECK_EXPR_END;
            }
```

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:7179]: 2. Need to define the next rule for `ParserRuleContext.ON_FAIL_CHECK` as `ParserRuleContext.ON_KEYWORD`.
3. The next rule for `ParserRuleContext.CHECK_EXPR_END` will be,
```java
endContext();
ParserRuleContext.EXPRESSION_RHS;
```

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:7179]: 4. We need to continue the path created under 2 in the following manner. ON_KEYWORD -> FAIL_KEWORD -> VARIABLE_NAME -> RIGHT_ARROW -> ERROR_CONSTRUCTOR

**Comment by lochana-chathura** [comment]
@DamithaSenevirathne We need to enable the build (Ubuntu build at least) via workflows for this branch.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 6]
```diff
@@ -3441,6 +3443,17 @@ protected ParserRuleContext getNextRule(ParserRuleContext currentCtx, int nextLo
                 return getNextRuleForBindingPattern();
             case TUPLE_MEMBERS:
                 return ParserRuleContext.TUPLE_MEMBER;
+            case ON_FAIL_CHECK:
+                return ParserRuleContext.ON_KEYWORD;
+            case ON_KEYWORD:
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3448]: We already have an entry for next rule for `ON_KEYWORD` here
https://github.com/ballerina-platform/ballerina-lang/blob/217853c58bfb1aef5b069c716a2dfcff5c88d129/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java#L3857-L3867

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 7]
```diff
@@ -3441,6 +3443,17 @@ protected ParserRuleContext getNextRule(ParserRuleContext currentCtx, int nextLo
...
+                return ParserRuleContext.FAIL_KEYWORD;
+            case FAIL_KEYWORD:
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3450]: We have this under `getNextRuleForKeywords()` too. Need do the change there. Not here.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 8]
```diff
@@ -3441,6 +3443,17 @@ protected ParserRuleContext getNextRule(ParserRuleContext currentCtx, int nextLo
...
+                return ParserRuleContext.VARIABLE_NAME;
+            case RIGHT_DOUBLE_ARROW:
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3452]: this too has a previously added entry. Please add the next rule there.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java [hunk 9]
```diff
@@ -724,6 +724,7 @@ public enum ParserRuleContext {
     OPTIONAL_TOP_LEVEL_SEMICOLON("optional-top-level-semicolon"),
     TUPLE_MEMBERS("tuple-members"),
     TUPLE_MEMBER("tuple-member"),
+    ON_FAIL_CHECK("check-on-fail")
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java:727]:
```suggestion
    ON_FAIL_CHECK("on-fail-check")
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 10]
```diff
@@ -3441,6 +3443,17 @@ protected ParserRuleContext getNextRule(ParserRuleContext currentCtx, int nextLo
...
+                return ParserRuleContext.ERROR_CONSTRUCTOR;
+            case CHECK_EXPRESSION_END:
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3454]: Seems this new enum entry is not committed in `ParserRuleContext.java`

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 11]
```diff
@@ -3833,6 +3846,8 @@ private ParserRuleContext getNextRuleInternal(ParserRuleContext currentCtx, int
                     endContext();
                 }
                 return getNextRuleForAction();
+            case CHECKING_KEYWORD:
+                return ParserRuleContext.EXPRESSION;
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3850]: We already do have defined this under `getNextRuleForKeywords()`.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 12]
```diff
@@ -4971,6 +4986,11 @@ private ParserRuleContext getNextRuleForVarName() {
                 return ParserRuleContext.ERROR_FIELD_MATCH_PATTERN_RHS;
             case RELATIVE_RESOURCE_PATH:
                 return ParserRuleContext.CLOSE_BRACKET;
+            case CHECKING_EXPRESSION:
+                parentCtx = getParentContext();
+                if (!(parentCtx == ParserRuleContext.QUERY_EXPRESSION)) {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:4991]:
```suggestion
                if (parentCtx != ParserRuleContext.QUERY_EXPRESSION) {
```
btw, why do we need to check the query ctx here? Any sample?

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 5 above)
Comment (DamithaSenevirathne) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:7180]: Updated

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java (hunk 12 above)
Comment (DamithaSenevirathne) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java]: Removed this statement from the `BallerinaParserErrorHandler` and handled the failing case in the `BallerinaParser`

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 1 above)
Comment (DamithaSenevirathne) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:9089]: Updated

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxKind.java [hunk 13]
```diff
@@ -331,6 +331,7 @@ public enum SyntaxKind {
     ASTERISK_LITERAL(1343),
     REQUIRED_EXPRESSION(1344),
     ERROR_CONSTRUCTOR(1345),
+    ON_FAIL_CHECK(4510),
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxKind.java:334]:
```suggestion
    ON_FAIL_CHECK(1346),
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java [hunk 14]
```diff
@@ -633,6 +633,8 @@ public enum ParserRuleContext {
     END_OF_PARAMS_OR_NEXT_PARAM_START("end-of-params-or-next-param-start"),
     BRACED_EXPRESSION("braced-expression"),
     ACTION("action"),
+    CHECKING_EXPRESSION("checking-expr"),
+    CHECK_EXPRESSION_END("query-expr-end"),
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/ParserRuleContext.java:637]:
```suggestion
    CHECKING_EXPRESSION_END("checking-expr-end"),
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 15]
```diff
@@ -3924,6 +3922,9 @@ private ParserRuleContext getNextRuleForKeywords(ParserRuleContext currentCtx, i
                 if (getParentContext() == ParserRuleContext.ON_FAIL_CLAUSE) {
                     return ParserRuleContext.ON_FAIL_OPTIONAL_BINDING_PATTERN;
                 }
+                if (getParentContext() == ParserRuleContext.CHECKING_KEYWORD) {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3925]: Since it is calling twice, Let's extract `getParentContext()` to a variable

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 16]
```diff
@@ -3877,7 +3874,8 @@ private ParserRuleContext getNextRuleForKeywords(ParserRuleContext currentCtx, i
                     return ParserRuleContext.CONFLICT_KEYWORD;
                 } else if (parentCtx == ParserRuleContext.ON_CLAUSE) {
                     return ParserRuleContext.EXPRESSION;
-                } else if (parentCtx == ParserRuleContext.ON_FAIL_CLAUSE) {
+                } else if (parentCtx == ParserRuleContext.ON_FAIL_CLAUSE ||
+                            parentCtx == ParserRuleContext.ON_FAIL_CHECK) {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3878]: We don't start a context for `ON_FAIL_CHECK`. We do for `CHECK_EXPRESSION`
```suggestion
                            parentCtx == ParserRuleContext.CHECK_EXPRESSION) {
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 17]
```diff
@@ -7167,22 +7167,32 @@ private STNode parsePanicKeyword() {
...
+     * checking-expr := checking-keyword expression [on-fail-check]
+     * checking-action := checking-keyword action [on-fail-check]
      * </code>
      *
      * @param allowActions Allow actions
      * @param isRhsExpr    Is rhs expression
      * @return Check expression node
      */
     private STNode parseCheckExpression(boolean isRhsExpr, boolean allowActions, boolean isInConditionalExpr) {
+        startContext(ParserRuleContext.CHECKING_EXPRESSION);
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:7179]: Now that, we start a context here, we need do the same in the errorhandler as well. 
Need add a entry for `CHECKING_EXPRESSION` in `startContextIfRequired()` at errorhandler.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 18]
```diff
@@ -7167,22 +7167,32 @@ private STNode parsePanicKeyword() {
...
         STNode checkingKeyword = parseCheckingKeyword();
         STNode expr =
                 parseExpression(OperatorPrecedence.EXPRESSION_ACTION, isRhsExpr, allowActions, isInConditionalExpr);
+        STToken onKeyword = peek();
+        STToken failKeyword = getNextNextToken();
+        STNode onFailCheck = STNodeFactory.createEmptyNode();
+        if (onKeyword.kind == SyntaxKind.ON_KEYWORD && failKeyword.kind == SyntaxKind.FAIL_KEYWORD) {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:7186]: Since we do not know whether `peek()` and `getNextNextToken()` are `onKeyword` and `failKeyword` naming it like that is misleading. Also, the usage of those variables are only once.

```suggestion
        STNode onFailCheck = STNodeFactory.createEmptyNode();
        if (peek().kind == SyntaxKind.ON_KEYWORD && getNextNextToken().kind == SyntaxKind.FAIL_KEYWORD) {
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 19]
```diff
@@ -7167,22 +7167,32 @@ private STNode parsePanicKeyword() {
...
+            onFailCheck = parseOnFailCheck();
+        }
+        endContext();
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:7189]:
```suggestion

        endContext();
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 20]
```diff
@@ -9065,7 +9075,26 @@ private STNode parseResourceAccessSegmentRhs(boolean isRhsExpr, boolean isInMatc
                 return parseResourceAccessSegmentRhs(isRhsExpr, isInMatchGuard);
         }
     }
-    
+
+    /**
+     * This method is used to parse on-fail-check node.
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:9080]:
```suggestion
     * Parse on-fail-check node.
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 21]
```diff
@@ -3040,6 +3040,8 @@ private Result seekMatchInExpressionRhs(int lookahead, int currentDepth, int cur
             nextContext = ParserRuleContext.EQUALS_KEYWORD;
         } else if (parentCtx == ParserRuleContext.CLIENT_RESOURCE_ACCESS_ACTION) {
             nextContext = ParserRuleContext.CLOSE_BRACKET;
+        } else if (parentCtx == ParserRuleContext.CHECKING_EXPRESSION) {
+            nextContext = ParserRuleContext.ON_KEYWORD;
```
[the remark this answers is not in the document]
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java]: @DamithaSenevirathne Seems this comment is not addressed. Now that we look at two tokens at the ballerina parser, we need to do the same in the error handler for the consistency. 
```java
            STToken nextToken = this.tokenReader.peek(lookahead);
            STToken nextNextToken = this.tokenReader.peek(lookahead + 1);
            if (nextToken.kind == SyntaxKind.ON_KEYWORD && nextNextToken.kind == SyntaxKind.FAIL_KEYWORD) {
                nextContext = ParserRuleContext.ON_FAIL_CHECK;
            } else {
                nextContext = ParserRuleContext.CHECK_EXPR_END;
            }
```
Having a separate variable is fine here for the readability. Otherwise, `this.tokenReader.peek(lookahead + 1)` could be confusing.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 22]
```diff
@@ -7167,22 +7167,31 @@ private STNode parsePanicKeyword() {
...
+        endContext();
         if (isAction(expr)) {
-            return STNodeFactory.createCheckExpressionNode(SyntaxKind.CHECK_ACTION, checkingKeyword, expr);
+            return STNodeFactory.createCheckExpressionNode(SyntaxKind.CHECK_ACTION, checkingKeyword, expr,
+                    onFailCheck);
         } else {
-            return STNodeFactory.createCheckExpressionNode(SyntaxKind.CHECK_EXPRESSION, checkingKeyword, expr);
+            return STNodeFactory.createCheckExpressionNode(SyntaxKind.CHECK_EXPRESSION, checkingKeyword, expr,
+                    onFailCheck);
         }
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:7195]: Can refactor this 7 lines to,
```java
        SyntaxKind kind = isAction(expr) ? SyntaxKind.CHECK_ACTION : SyntaxKind.CHECK_EXPRESSION;
        return STNodeFactory.createCheckExpressionNode(kind, checkingKeyword, expr, onFailCheck);
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 23]
```diff
@@ -9065,7 +9074,26 @@ private STNode parseResourceAccessSegmentRhs(boolean isRhsExpr, boolean isInMatc
...
+     * on-fail-check := on-keyword fail-keyword variable-name => error-constructor
+     * </code>
+     *
+     * @return on-fail-check node
+     */
+    private STNode parseOnFailCheck() {
+        STNode onKeyword = parseOnKeyword();
+        STNode failKeyword = parseFailKeyword();
+        STNode varName = parseVariableName();
+        STNode rightDoubleArrow = parseDoubleRightArrow();
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:9092]: Seems we call `recover(token, ParserRuleContext.EXPR_FUNC_BODY_START);` inside the `parseDoubleRightArrow()`. 
However, in this case the recovery context has to be `ParserRuleContext.RIGHT_DOUBLE_ARROW`.

Let's convert `parseDoubleRightArrow()` to `parseDoubleRightArrow(ParserRuleContext ctx)` and call,
`recover(token, ctx);`

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java (hunk 11 above)
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3853]: @DamithaSenevirathne seems this is not addressed. We can remove this.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 24]
```diff
@@ -3733,6 +3746,9 @@ private ParserRuleContext getNextRuleInternal(ParserRuleContext currentCtx, int
             case RIGHT_DOUBLE_ARROW:
                 // Assumption: RIGHT_DOUBLE_ARROW is only occurs in match clauses
                 // in expr-func-body, it is used by a different alias.
+                if (getParentContext() == ParserRuleContext.CHECKING_EXPRESSION) {
+                    return ParserRuleContext.ERROR_CONSTRUCTOR;
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3750]: At the end of error constructor we need to end our current context.
 
Since we can have error constructor in two places in the below grammar(bold places), there's ambiguity. So in order to distinguish at which point we are at, seems we need to start context for `on-fail-check` as well. 

checking-keyword **expression** [on-keyword fail-keyword variable-name double-right-arrow **error-constructor**]

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3750]: Need to end those context at the end of error-constructor. 
i.e. here:
https://github.com/ballerina-platform/ballerina-lang/blob/b965b48532f098d2b3d322253b057a109ca0532b/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java#L3566-L3567

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STOnFailCheckNode.java [hunk 25]
```diff
@@ -0,0 +1,124 @@
+/*
+ *  Copyright (c) 2023, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STOnFailCheckNode.java:2]:
```suggestion
 *  Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com).
```

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STOnFailCheckNode.java:2]: Update in the other files as well.

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/CheckExpressionTest.java [hunk 26]
```diff
@@ -36,15 +36,25 @@ public void testCheckExprPrecedence() {
...
+    public void testSimpleCheckOnFail() {
+        testFile("check-on-fail/check_on_fail_source_01.bal",  "check-on-fail/check_on_fail_assert_01.json");
+    }
 
     @Test
     public void testCheckWithMissingExpr() {
         testFile("check-expr/check_expr_source_03.bal", "check-expr/check_expr_assert_03.json");
     }
 
+    // Recovery test
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/CheckExpressionTest.java:49]: Need to move this comment before the `testCheckWithMissingExpr()` as it is a recovery test

File: compiler/ballerina-parser/src/test/resources/expressions/check-on-fail/check_on_fail_source_02.bal [hunk 27]
```diff
@@ -0,0 +1,3 @@
+function foo() {
+    check doA() on fail e error("Something happened", e, c1 = c1, c2 = c2);
+}
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/resources/expressions/check-on-fail/check_on_fail_source_02.bal:3]: Add a newline at EOF

File: compiler/ballerina-parser/src/test/resources/expressions/check-on-fail/check_on_fail_assert_02.json [hunk 28]
```diff
@@ -0,0 +1,330 @@
...
+            }
+          ]
+        },
+        {
+          "kind": "CLOSE_BRACE_TOKEN"
+        }
+      ]
+    }
+  ]
+}
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/resources/expressions/check-on-fail/check_on_fail_assert_02.json:330]: same here

File: compiler/ballerina-parser/src/test/resources/expressions/check-on-fail/check_on_fail_source_01.bal [hunk 29]
```diff
@@ -0,0 +1,3 @@
+function foo() {
+    check doA() on fail e => error("Something happened", e, c1 = c1, c2 = c2);
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/resources/expressions/check-on-fail/check_on_fail_source_01.bal:2]: this is actually check-expr within a call-stmt. Let's add direct expression usage here as well. Also, with `checkpanic` keyword.
e.g.
```bal
check doA() on fail e => error("Something happened", e, c1 = c1, c2 = c2);
checkpanic doA() on fail e => error("Something happened", e, c1 = c1, c2 = c2);
_ = check expr on fail err error E("Oops!");
_ = checkpanic expr on fail err error E("Oops!");
```

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/test/resources/expressions/check-on-fail/check_on_fail_source_01.bal:2]: Also add a separate test to test if following can be parsed, as they have ambiguity if we consider only `on-keyword` when parsing `on-fail-check`.

```bal
_ = from int a in b select check c on conflict d;
_ = check from int a in b select check c on conflict d on fail e => error("ERROR!");
_ = from int a in b join C d in e on f equals g select h;
_ = checkpanic from int a in b join C d in e on f equals g select h on fail e => error("Errr!");
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 30]
```diff
@@ -11489,6 +11514,16 @@ private STNode parseDoubleRightArrow() {
         }
     }
 
+    private STNode parseDoubleRightArrow(ParserRuleContext parserRuleContext) {
+        STToken token = peek();
+        if (token.kind == SyntaxKind.RIGHT_DOUBLE_ARROW_TOKEN) {
+            return consume();
+        } else {
+            recover(token, parserRuleContext);
+            return parseDoubleRightArrow();
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:11523]:
```suggestion
            return parseDoubleRightArrow(parserRuleContext);
```

Also, Let's get rid of the other `parseDoubleRightArrow()` method.

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/CheckExpressionTest.java [hunk 31]
```diff
@@ -47,4 +67,34 @@ public void testCheckWithMissingExpr() {
     public void testCheckWithMissingBinaryOp() {
         testFile("check-expr/check_expr_source_04.bal", "check-expr/check_expr_assert_04.json");
     }
+
+    @Test
+    public void testOnFailCheckWithMissingFail() {
+        testFile("on-fail-check/on_fail_check_source_02.bal", "on-fail-check/on_fail_check_assert_02.json");
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/CheckExpressionTest.java:73]: Shall we move these tests to `check-expr` directroy? We keep one directory for each test class. Since this is CheckExpressionTest class let's add the new tests under the same directory. We can use the name (`on_fail_check_`) to distinguish.

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/CheckExpressionTest.java [hunk 32]
```diff
@@ -47,4 +67,34 @@ public void testCheckWithMissingExpr() {
     public void testCheckWithMissingBinaryOp() {
         testFile("check-expr/check_expr_source_04.bal", "check-expr/check_expr_assert_04.json");
     }
+
+    @Test
+    public void testOnFailCheckWithMissingFail() {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/CheckExpressionTest.java:72]:
```suggestion
    public void testOnFailCheckWithoutDoubleArrow() {
```

File: compiler/ballerina-parser/src/test/resources/expressions/on-fail-check/on_fail_check_source_09.bal [hunk 33]
```diff
@@ -0,0 +1,5 @@
+function foo() {
+    _ = from int a in b
+        join C d in e on f equals g
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/resources/expressions/on-fail-check/on_fail_check_source_09.bal:3]: My bad.
``` suggestion
        join C d in check e on f equals g
```

Change file name to `check_expr_source` and move out of recovery section

File: compiler/ballerina-parser/src/test/resources/expressions/on-fail-check/on_fail_check_source_10.bal [hunk 34]
```diff
@@ -0,0 +1,6 @@
+function foo() {
+    _ = checkpanic from int a in b
+        join C d in e on f equals g
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/resources/expressions/on-fail-check/on_fail_check_source_10.bal:3]:
```suggestion
        join C d in check e on f equals g
```

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/CheckExpressionTest.java [hunk 35]
```diff
@@ -47,4 +67,34 @@ public void testCheckWithMissingExpr() {
...
+    @Test
+    public void testOnFailWithJoin() {
+        testFile("on-fail-check/on_fail_check_source_09.bal", "on-fail-check/on_fail_check_assert_09.json");
+    }
+
+    @Test
+    public void testOnFailCheckPanicWithEquals() {
+        testFile("on-fail-check/on_fail_check_source_10.bal", "on-fail-check/on_fail_check_assert_10.json");
+    }
 }
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/CheckExpressionTest.java:100]: Let's also add a test with extra tokens to check recovery.
e.g. `    _ = check x on fail % e & => /error("Error!");`

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 36]
```diff
@@ -814,10 +815,39 @@ public ExpressionStatementNode transform(ExpressionStatementNode expressionState
...
+            expressionNode = formatNode(checkExpressionNode.expression(), 1, 0);
+        } else {
+            expressionNode = formatNode(checkExpressionNode.expression(), env.trailingWS, env.trailingNL);
+            return checkExpressionNode.modify()
+                    .withCheckKeyword(checkKeyword)
+                    .withExpression(expressionNode)
+                    .apply();
+        }
+
+        OnFailCheckNode onFailCheckNode = formatNode(checkExpressionNode.onFailCheck().get(),  0, 0);
```
Comment (lochana-chathura) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:829]: Single return preferred.
```suggestion
        OnFailCheckNode onFailCheckNode  = null;
        if (checkExpressionNode.onFailCheck().isPresent()) {
            expressionNode = formatNode(checkExpressionNode.expression(), 1, 0);
            onFailCheckNode = formatNode(checkExpressionNode.onFailCheck().get(),  0, 0);
        } else {
            expressionNode = formatNode(checkExpressionNode.expression(), env.trailingWS, env.trailingNL);
        }

```

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 37]
```diff
@@ -814,10 +815,35 @@ public ExpressionStatementNode transform(ExpressionStatementNode expressionState
     @Override
     public CheckExpressionNode transform(CheckExpressionNode checkExpressionNode) {
         Token checkKeyword = formatToken(checkExpressionNode.checkKeyword(), 1, 0);
-        ExpressionNode expressionNode = formatNode(checkExpressionNode.expression(), env.trailingWS, env.trailingNL);
+        ExpressionNode expressionNode;
+        OnFailCheckNode onFailCheckNode  = null;
```
Comment (lochana-chathura) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:819]:
```suggestion
        OnFailCheckNode onFailCheckNode = null;
```

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 38]
```diff
@@ -814,10 +815,35 @@ public ExpressionStatementNode transform(ExpressionStatementNode expressionState
...
+        if (checkExpressionNode.onFailCheck().isPresent()) {
+            expressionNode = formatNode(checkExpressionNode.expression(), 1, 0);
+            onFailCheckNode = formatNode(checkExpressionNode.onFailCheck().get(),  env.trailingWS, env.trailingNL);
```
Comment (lochana-chathura) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:822]:
```suggestion
            onFailCheckNode = formatNode(checkExpressionNode.onFailCheck().get(), env.trailingWS, env.trailingNL);
```

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/CheckExpressionTest.java [hunk 39]
```diff
@@ -36,6 +36,41 @@ public void testCheckExprPrecedence() {
...
+        testFile("check-expr/on_fail_check_source_06.bal", "check-expr/on_fail_check_assert_06.json");
+    }
+
+    @Test
+    public void testOnFailCheckNextToAnOnConflictClause() {
+        testFile("check-expr/on_fail_check_source_08.bal", "check-expr/on_fail_check_assert_08.json");
+    }
+
+    @Test
+    public void testOnFailWithJoin() {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/CheckExpressionTest.java:70]:
```suggestion
    public void testCheckExprWithJoinClause() {
```

Also, move it next to the `testCheckExprWithOnConflictClause()` as they are similar tests.

**Comment by lochana-chathura** [comment]
Checked the `testMatchStmtRecoveryInvalidErrorMatchPatterns()` failure. New recovery is okay. Let's update the json file.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 40]
```diff
@@ -3662,7 +3680,7 @@ private ParserRuleContext getNextRuleInternal(ParserRuleContext currentCtx, int
             case METHOD_NAME:
                 return ParserRuleContext.OPTIONAL_RESOURCE_ACCESS_ACTION_ARG_LIST;
             case DEFAULT_WORKER_NAME_IN_ASYNC_SEND:
-                return ParserRuleContext.SEMICOLON;
+                return ParserRuleContext.EXPRESSION_RHS;
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3683]:
```suggestion
                return ParserRuleContext.ACTION_END;
```

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/actions/ClientResourceAccessActionTest.java [hunk 41]
```diff
@@ -48,23 +48,23 @@ public void testResourceMethodCallActionInDifferentContexts() {
...
-    @Test
-    public void testRecoveryForResourceMethodCallActionSlashToken() {
-        testFile("client-resource-access-action/client_resource_access_action_source_04.bal",
-                "client-resource-access-action/client_resource_access_action_assert_04.json");
-    }
+//    @Test
+//    public void testRecoveryForResourceMethodCallActionSlashToken() {
+//        testFile("client-resource-access-action/client_resource_access_action_source_04.bal",
+//                "client-resource-access-action/client_resource_access_action_assert_04.json");
+//    }
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/actions/ClientResourceAccessActionTest.java:55]:
```suggestion
    @Test
    public void testRecoveryForResourceMethodCallActionSlashToken() {
        testFile("client-resource-access-action/client_resource_access_action_source_04.bal",
                "client-resource-access-action/client_resource_access_action_assert_04.json");
    }
```

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/actions/ClientResourceAccessActionTest.java [hunk 42]
```diff
@@ -48,23 +48,23 @@ public void testResourceMethodCallActionInDifferentContexts() {
...
-    @Test
-    public void testRecoveryForResourceMethodCallActionRhsInDifferentContexts() {
-        testFile("client-resource-access-action/client_resource_access_action_source_06.bal",
-                "client-resource-access-action/client_resource_access_action_assert_06.json");
-    }
+//    @Test
+//    public void testRecoveryForResourceMethodCallActionRhsInDifferentContexts() {
+//        testFile("client-resource-access-action/client_resource_access_action_source_06.bal",
+//                "client-resource-access-action/client_resource_access_action_assert_06.json");
+//    }
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/actions/ClientResourceAccessActionTest.java:67]:
```suggestion
    @Test
    public void testRecoveryForResourceMethodCallActionRhsInDifferentContexts() {
        testFile("client-resource-access-action/client_resource_access_action_source_06.bal",
                "client-resource-access-action/client_resource_access_action_assert_06.json");
    }
```

**Review by lochana-chathura — APPROVED** [review]
