### PR TITLE
Sort documents of a module

### LINKED ISSUE #31082: Dependency order between packages are not consistent.
**Description:**
We found out that dependency resolution between packages is not consistent between compilations while fixing https://github.com/ballerina-platform/ballerina-lang/issues/31009.

The dependency order is correct but different. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by nipunayf**
## Purpose
The order of the documents is not consistent at project creation or when adding a new module. This list should retain the sort at each build.

Fixes #31082 

## Approach
Sort the `DocumentId`s based on the document path when extracting the keyset from the context map.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java [hunk 1]
```diff
@@ -556,6 +558,15 @@ ModuleContext duplicate(Project project) {
                 this.moduleDescDependencies, this.resourceContextMap, this.testResourceContextMap);
     }
 
+    private Collection<DocumentId> sortDocuments(Map<DocumentId, DocumentContext> docContextMap) {
```
Comment (azinneera) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java:561]: We create a new ModuleContext for every document edit. I think this would affect the LS since it will sort for every edit request. IMO, we can specifically sort the map when we create a package and when a document is added. @sameerajayasoma WDYT?

Comment (nipunayf) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java]: Addressed this in db53c289c2f4ec33ec8d539e58b4877ffdf0a0f7

**Review by azinneera — APPROVED** [review]
LGTM

**Review by sameerajayasoma — APPROVED** [review]
