### PR TITLE
Load 'lang.value' dependent module before 'lang.error'

### LINKED ISSUE #31118: NPE at Runtime type checking with error:Retriable
**Description:**

Error type's detail type constraint becomes null

[2021-06-11 12:17:35,553] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerina.runtime.internal.types.BMapType.equals(BMapType.java:137)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:555)
	at io.ballerina.runtime.internal.TypeChecker.checkIsErrorType(TypeChecker.java:2553)
	at io.ballerina.runtime.internal.TypeChecker.checkIsRecursiveType(TypeChecker.java:739)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:648)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:549)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:673)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:272)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:260)
	at ballerinai.transaction.1_0_14.tests.retry_transaction_stmt.customRetryTrxManager(tests/retry_transaction_stmt.bal:239)
	at ballerinai.transaction.1_0_14.tests.retry_transaction_stmt.testCustomRetryTrxManager(tests/retry_transaction_stmt.bal:226)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Steps to reproduce:**
```ballerina
public function main() returns error? {
    var bV = error error:Retriable("TransactionError");
    if (bV is transaction:Error) {
        io:println("transaction error");
    }
}
```

**Affected Versions:**
ballerinaLangVersion=2.0.0-beta.2-20210610-094800-31640cd2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #31118

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java [hunk 1]
```diff
@@ -133,11 +133,12 @@ void loadLangLib(CompilerContext compilerContext, PackageID langLib) {
             symbolTable.updateStringSubtypeOwners();
         }
 
+        symResolver.bootstrapCloneableType();
+
         if (langLib.equals(ERROR)) {
             symbolTable.langValueModuleSymbol = loadLangLibFromBala(VALUE, compilerContext);
         }
 
-        symResolver.bootstrapCloneableType();
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java:140]: 👎🏽

**Review by KRVPerera — APPROVED** [review]
Shall we create an issue to track this problem?
Basically a architecture change or at least some comments here and there needed to avoid considerable amount of debug time for these issues.
