### PR TITLE
Fix compiler crashes when arguments are provided for both the parameter and the rest field of an included record parameter

### LINKED ISSUE #39067: [Bug]: Compiler crashes when arguments are provided for both the parameter and the rest field of an included record parameter
### Description

$title. Similar to https://github.com/ballerina-platform/ballerina-lang/issues/34566 but for the rest descriptor.

### Steps to Reproduce

```ballerina
type Rec record {}; 

function fn(*Rec r) {

}

public function main() {
    // fn({"i": 1, "j": 2}); // OK
    // fn(i = 1, j = 2); // OK
    fn(r = {"i": 1}, j = 2); // should be a compilation error
}
```

```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.Desugar.createAndAddRecordFieldForIncRecordLiteral(Desugar.java:9330)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.setFieldsForIncRecordLiterals(Desugar.java:9319)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.reorderNamedArgs(Desugar.java:9297)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.reorderArguments(Desugar.java:9025)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteInvocation(Desugar.java:6690)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6327)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:128)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8867)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3509)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:51)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8880)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8886)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1374)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1420)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:826)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:469)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:451)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:165)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:213)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### Affected Version(s)

2201.3.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fixes #39067 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -6857,15 +6857,25 @@ private BType checkInvocationParam(BLangInvocation iExpr, AnalyzerData data) {
...
         boolean foundNamedArg = false;
+        boolean isIncRecordAllowExtraFields = incRecordParamAllowAdditionalFields != null;
         for (BLangExpression expr : iExpr.argExprs) {
             switch (expr.getKind()) {
                 case NAMED_ARGS_EXPR:
                     foundNamedArg = true;
-                    if (i < parameterCountForNamedArgs || incRecordParamAllowAdditionalFields != null) {
+                    BLangNamedArgsExpression namedArg = (BLangNamedArgsExpression) expr;
+                    boolean isNamedArgForIncRecordParam =
+                                  isNamedArgForIncRecordParam(namedArg.name.value, incRecordParamAllowAdditionalFields);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6867]: For 

```ballerina
type Foo record {|
    int r;
|}; 

function fn(int r, *Foo x) {

}
```

we are getting `redeclared symbol 'r'`. While the error isn't the ideal error, shouldn't we get a similar error for

```ballerina
type Foo record {|
    int r;
|}; 

function fn(*Foo r) {

}
```

which may have resulted in special checks not being needed?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -6857,15 +6857,25 @@ private BType checkInvocationParam(BLangInvocation iExpr, AnalyzerData data) {
         int i = 0;
         BLangExpression vararg = null;
         boolean foundNamedArg = false;
+        boolean isIncRecordAllowExtraFields = incRecordParamAllowAdditionalFields != null;
```
[the remark this answers is not in the document]
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Are you stating that this scenario is a compile-time error?
```ballerina
type Foo record {|
    int r;
|}; 

function fn(*Foo r) {

}
```

**Review by dulajdilshan — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: If we are getting an error for

```ballerina
type Foo record {|
    int r;
|}; 

function fn(int r, *Foo x) {

}
```

shouldn't it be the same for

```ballerina
type Foo record {|
    int r;
|}; 

function fn(*Foo r) {

}
```
?

Why do we give an error for the first, btw? It makes sense, but I'm not sure if the spec mentions it.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -6857,15 +6857,25 @@ private BType checkInvocationParam(BLangInvocation iExpr, AnalyzerData data) {
         int i = 0;
         BLangExpression vararg = null;
         boolean foundNamedArg = false;
+        boolean isIncRecordAllowAdditionalFields = incRecordParamAllowAdditionalFields != null;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6860]: Can we rename the variable to not have the `is` prefix here also?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: IIMO, giving an error for the first scenario is a bug because it can be invoked using position arguments. Therefore, if we try to invoke it with named arguments,error should be raised in that instance.
```ballerina
type Foo record {|
    int r;
|}; 

function fn(int r, *Foo x) {

}
public function main() {
    Foo f = {r: 1};
    fn(1, f);
}
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: But then one can argue, `x` shouldn't be an included record parameter, right? Is this error specified in the spec? Assuming you were the one who added the error, do you recall why it was done that way?

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: As  I remember, we consider fields of the record parameter as parameters of the function. I have made both scenarios into error cases.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Is there anything in the spec (or spec repo issue) requiring these to be disallowed?

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: The specification mentions that `the field names of all the parameter field descriptors whose type is not never must be distinct from each other and from the names of the parameters`

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: This becomes a backward-incompatible change then, though. Please make a note to include it in the release note.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 4]
```diff
@@ -6894,6 +6904,10 @@ private BType checkInvocationParam(BLangInvocation iExpr, AnalyzerData data) {
                                     incRecordParamAllowAdditionalFields, data);
     }
 
+    private boolean isNamedArgForIncRecordParam(String namedArgName, BVarSymbol incRecordParam) {
```
[the remark this answers is not in the document]
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6907]: This is to check whether we provide a named argument for the included parameter.

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal [hunk 5]
```diff
@@ -279,3 +279,21 @@ function testInvokingFunctionContainingIncludedRecordParamOfTypeOtherThanRecordO
...
+type Record5 record {};
+
+function fn5(*Record5 record5) {
+}
+
+function testInvokingFunctionWithNamedArgForIncludedRecordParam() {
+    fn5(record5 = {}, j = 2); // error
+    fn5(j = 2, record5 = {}); // error
+}
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:292]: Shall we also add a test for when there are more than one open records as included record parameters?

Comment (chiranSachintha) [reply tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:302]: Updated.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 6]
```diff
@@ -6857,15 +6857,25 @@ private BType checkInvocationParam(BLangInvocation iExpr, AnalyzerData data) {
...
         boolean foundNamedArg = false;
+        boolean incRecordAllowAdditionalFields = incRecordParamAllowAdditionalFields != null;
         for (BLangExpression expr : iExpr.argExprs) {
             switch (expr.getKind()) {
                 case NAMED_ARGS_EXPR:
                     foundNamedArg = true;
-                    if (i < parameterCountForNamedArgs || incRecordParamAllowAdditionalFields != null) {
+                    BLangNamedArgsExpression namedArg = (BLangNamedArgsExpression) expr;
+                    boolean namedArgForIncRecordParam =
+                                  isNamedArgForIncRecordParam(namedArg.name.value, incRecordParamAllowAdditionalFields);
```
Comment (suleka96) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6867]: This is the only place where `namedArg` is used right, shall we do the casting here instead of having a variable assignment.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/identifiers/IdentifierTest.java [hunk 7]
```diff
@@ -64,6 +64,7 @@ public void testInvalidImportOnMultipleFiles() {
         validateError(result, index++, "redeclared symbol 'error'", 19, 18);
         validateError(result, index++, "redeclared symbol 'error'", 30, 11);
         validateError(result, index++, "redeclared symbol 'error'", 37, 73);
+        validateError(result, index++, "redeclared symbol 'error'", 39, 39);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/identifiers/IdentifierTest.java:67]: Please create an issue to improve this error. Ideally we should give a more descriptive error.

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal [hunk 8]
```diff
@@ -279,3 +279,31 @@ function testInvokingFunctionContainingIncludedRecordParamOfTypeOtherThanRecordO
...
+function fn6(*Record5 record5, *Record6 record6) {
+}
+
+function testInvokingFunctionWithNamedArgForIncludedRecordParam() {
+    fn5(record5 = {}, j = 2); // error
+    fn5(j = 2, record5 = {}); // error
+    fn6(record5 = {}, j = 2); // error
+    fn6(record5 = {}, record6 = {}, j = 2); // error
+    fn6(j = 2, record5 = {}, record6 = {}); // error
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:300]: We can remove `// error` since all are error-ing lines.

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal [hunk 9]
```diff
@@ -279,3 +279,38 @@ function testInvokingFunctionContainingIncludedRecordParamOfTypeOtherThanRecordO
...
+
+function fn6(*Record5 record5, *Record6 record6) {
+}
+
+function testInvokingFunctionWithNamedArgForIncludedRecordParam() {
+    fn5(record5 = {}, j = 2);
+    fn5(j = 2, record5 = {});
+    fn6(record5 = {}, j = 2);
+    fn6(record5 = {}, record6 = {}, j = 2);
+    fn6(j = 2, record5 = {}, record6 = {});
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:300]: Do we have tests for scenarios that are OK like
```suggestion
    fn5(j = 2);
    fn6(record5 = {}, record6 = {});
```
?

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal [hunk 10]
```diff
@@ -279,3 +279,38 @@ function testInvokingFunctionContainingIncludedRecordParamOfTypeOtherThanRecordO
...
+type Record5 record {
+};
+
+type Record6 record {
+};
+
+function fn5(*Record5 record5) {
+}
+
+function fn6(*Record5 record5, *Record6 record6) {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:292]: Shall we add tests with one open and one closed also?

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal [hunk 11]
```diff
@@ -279,3 +279,38 @@ function testInvokingFunctionContainingIncludedRecordParamOfTypeOtherThanRecordO
...
+
+function fn7(*Baz r) {
+}
+
+function fn8(string k, *Record5 record5) {
+}
+
+function testInvokingFunctionWithPositionArgForIncludedRecordParam() {
+    fn8("abc", {}, j = 2);
+    fn8("abc", {}, j = 2, i = 10);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:315]: Can we add a few more tests similar to the named ones (with multiple included record params)?

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal [hunk 12]
```diff
@@ -279,3 +279,38 @@ function testInvokingFunctionContainingIncludedRecordParamOfTypeOtherThanRecordO
...
+    int r;
+|};
+
+function fn7(*Baz r) {
+}
+
+function fn8(string k, *Record5 record5) {
+}
+
+function testInvokingFunctionWithPositionArgForIncludedRecordParam() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:313]:
```suggestion
function testInvokingFunctionWithPositionalArgForIncludedRecordParam() {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal (hunk 11 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:315]: We can reuse the same functions.

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal (hunk 9 above)
Comment (chiranSachintha) [reply tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:300]: Add a few more tests to cover this.

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal (hunk 10 above)
Comment (chiranSachintha) [reply tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:292]: Updated

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal (hunk 11 above)
Comment (chiranSachintha) [reply tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters_negative.bal:316]: Added test cases

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters.bal [hunk 13]
```diff
@@ -195,6 +199,10 @@ function functionOfFunctionTypedParamWithIncludedRecordParam22(*Pairs values) re
     return <float[]>values["a"];
 }
 
+function functionOfFunctionTypedParamWithIncludedRecordParam23(*Baz baz, *Baz2 baz2) returns [anydata, anydata] {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters.bal:202]: What does `functionOfFunctionTypedParam` here mean?

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters.bal [hunk 14]
```diff
@@ -224,11 +232,23 @@ function testFuctionWithIncludedRecordParameters4() {
 
 function testFuctionWithIncludedRecordParameters5() {
     [anydata, anydata, anydata, anydata, anydata] details = functionOfFunctionTypedParamWithIncludedRecordParam5(a = 30, b = 400.0, value = "Integer", isCorrect = true, path = "c/usr/filename");
+    [anydata, anydata, anydata, anydata, anydata] details1 = functionOfFunctionTypedParamWithIncludedRecordParam5({"a": 30, "b": 400.0, "value": "Integer", "isCorrect": true, "path": "c/usr/filename"});
+    [anydata, anydata] details2 = functionOfFunctionTypedParamWithIncludedRecordParam23({"a": 10}, {"b": 20});
+    [anydata, anydata] details3 = functionOfFunctionTypedParamWithIncludedRecordParam23(baz = {"a": 10}, baz2 = {"b": 20});
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters.bal:237]: Can we move these closer to where the assertions are done?

**Review by MaryamZi — DISMISSED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters.bal (hunk 13 above)
Comment (chiranSachintha) [reply tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_included_record_parameters.bal]: I have renamed this. I used this because I used a similar name for previous functions. I think we need to rename all of those function names.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 15]
```diff
@@ -4610,6 +4610,7 @@ private List<BVarSymbol> defineParameters(List<BLangSimpleVariable> params, Symb
                 }
             }
             if (varNode.flagSet.contains(Flag.INCLUDED)) {
+                requiredParamNames.add(symbol.name.value);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:4613]: We need to add this as a breaking change.

**Review by MaryamZi — APPROVED** [review]

**Comment by MaryamZi** [comment]
@chiranSachintha please resolve the conflict.

**Comment by MaryamZi** [comment]
@chiranSachintha please fix the build - checkstyle failures.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 15 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:4619]: Create PR(https://github.com/ballerina-platform/ballerina-dev-website/pull/6559) for this

**Review by MaryamZi — APPROVED** [review]
