### PR TITLE
Fix errors thrown from query clauses other than from/join being propagated to query result

### LINKED ISSUE #35311: [Query Action] Variable assignment should not be needed when query completes normally
**Description:**
Atm, the static type of query action is considered to be `error?` which is not correct. This inturn requires the user to assign the result to a variable even when the return type is actually `()`. 

```ballerina
public type MetaData record{|
    string absPath;
|};

function foo() returns string[] {
    string[] files = [];
    MetaData[] listResult = [];
    from var md in listResult // variable assignment is required
        do {
            files.push(md.absPath);
        };
    return files;
}
```

**Steps to reproduce:**

**Affected Versions:**
SL GA

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #36631: [Query action] Fail/error-returns and check-fail behaviour is not differentiated
**Description:**
```ballerina
public function main() returns error? {
    io:println("at main ", bar());
}

function foo() returns error? {
    return ();
}

function bar() returns error? {
    error? res = from int i in 1 ... 3
        do {
            check foo();
            if (2 / 2 == 1) {
                fail error("dummy");
            } 
        };
    io:println("at bar() end ", res);
}
```
```ballerina
public function main() returns error? {
    io:println("at main ", bar());
}

function foo() returns error? {
    return ();
}

function bar() returns error? {
    error? res = from int i in 1 ... 3
        do {
            check foo();
            if (2 / 2 == 1) {
                return error("dummy");
            } 
        };
    io:println("at bar() end ", res);
}

```

For both cases prints
```
at bar() end error("dummy")
at main 
```
**Steps to reproduce:**

**Affected Versions:**
2201.1.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/35383

This behavior is because the do clause gets wrapped within a lambda function. Hence, cannot differentiate fail/error-returns. Need a way to support this.

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #36698: [Query expression] On-conflict expression evaluated to an error; panics
**Description:**
```ballerina
type TT record {|
    readonly int id;
|};

type TableT table<TT> key (id);

function f1() returns error? {
    return error("Key Conflict");
}

function dummyTest() {
       TableT|error tt = table key(id) from var i in [1, 2, 3]
                          select {
                              id: i
                          }
                          on conflict (check f1());
}
```

When we pass the check-expression as an argument to [`addToTable()`](https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.query/src/main/ballerina/helpers.bal#L131)  function; the expression is evaluated and the error is thrown out. 
To solve this; we need to nest this function inside a separate function or with-in on-fail and handle the error gracefully.
 
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #37310: Only query-pipeline clause can complete early
**Description:**
Ref https://github.com/ballerina-platform/ballerina-spec/issues/871#issuecomment-1191459657

Query expression/action result can have `error` only if a clause in the query pipeline completes early with an error.
If the evaluation of an expression within the query-expr/action completes abruptly with a check-fail, then the query-expr/action completes abruptly with a check-fail.

**Steps to reproduce:**

**Affected Versions:**
2201.1.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #37473: Clauses of stream constructing query-exp should not check for enclosing failure handling statement
**Description:**
Clause completing abruptly for a query expression constructing a stream, should not check for enclosing failure handling statement.

**Steps to reproduce:**

```ballerina
class NumberGeneratorWithError {
    int i = 0;
    public isolated function next() returns record {|int value;|}|error? {
        return error("Custom error thrown explicitly.");
    }
}

function getError() returns int|error {
    return error("Dummy error");
}

public function main(){
    NumberGeneratorWithError gen = new ();
    stream<int, error?> streamName = new (gen);

    stream<int, error?> strm = stream from int i in streamName
        let int _ = check getError() // @error no matching error return type(s) in the enclosing invokable. error will not be thrown from here since the query will be invoked lazily
        select i;

    record {|int value;|}|error? r = strm.next(); //error is propagated here
}
```

**Affected Versions:**
SL 2201.2.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #37612: [Bug]: Runtime hangs when nested from/join collection throws an error
### Description

When the expression used for nested from/join collection returns an error, the query hangs indefinitely

### Steps to Reproduce

```ballerina
import ballerina/io;
function getArrOrErr() returns int[]|error {
    return error("Dummy error");
}

public function main() returns error? {
    int[]|error res = from int i in 1...3
        from int j in check getArrOrErr()
        select i;

    io:println(res);    
}

```

```ballerina
import ballerina/io;
function getArrOrErr() returns int[]|error {
    return error("Dummy error");
}

public function main() returns error? {
    int[]|error res = from int i in 1...3
        from int j in check getArrOrErr()
        do {
        };

    io:println(res);    
}

```

### Affected Version(s)

2201.1.0

### OS, DB, other environment details and versions

_No response_

### Labels

CompilerFE

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #37310
Fixes #37612
Fixes #37473
Fixes #36698
Fixes #35311
Fixes #36631

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -7176,6 +7173,14 @@ private BLangStatementExpression createStmtExprForNullableBinaryExpr(BLangBinary
         return stmtExpr;
     }
 
+    BLangTypeTestExpr getNilTypeTestExpr(Location pos, BLangExpression expr) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:7176]: should be `private`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 2]
```diff
@@ -7176,6 +7173,14 @@ private BLangStatementExpression createStmtExprForNullableBinaryExpr(BLangBinary
...
+        return createTypeCheckExpr(pos, expr, getNillTypeNode());
+    }
+
+    BLangTypeTestExpr getErrorTypeTestExpr(Location pos, BLangExpression expr) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:7180]: Do we need a separate method for this, because there is only one usage?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 3]
```diff
@@ -318,20 +317,11 @@ BLangStatementExpression desugar(BLangQueryExpr queryExpr, SymbolEnv env,
...
-                streamStmtExpr = ASTBuilderUtil.createStatementExpression(queryBlock, checkedExpr);
-                streamStmtExpr.setBType(checkedExpr.getBType());
-            } else {
-                streamStmtExpr = ASTBuilderUtil.createStatementExpression(queryBlock,
-                        addTypeConversionExpr(result, queryExpr.getBType()));
-                streamStmtExpr.setBType(queryExpr.getBType());
-            }
         }
+        handleErrorReturnsFromQuery(pos, result, queryBlock, false, resultType);
+        streamStmtExpr = ASTBuilderUtil.createStatementExpression(queryBlock,
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:322]: Shall we define the variable `streamStmtExpr` at this place?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 4]
```diff
@@ -3180,8 +3181,8 @@ public void visit(BLangCheckedExpr checkedExpr, AnalyzerData data) {
             return;
         }
 
-        if (!data.failureHandled && !types.isAssignable(errorType, exprType) &&
-                !types.isNeverTypeOrStructureTypeWithARequiredNeverMember(checkedExprType)) {
+        if (!data.failureHandled && !ignoreErrForCheckExpr && !types.isAssignable(errorType, exprType)
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:3184]: Can't we define `ignoreErrForCheckExpr` just above this check?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 5]
```diff
@@ -1954,6 +1906,56 @@ public void setInputClauseTypedBindingPatternType(BLangInputClause bLangInputCla
...
+                                collectionTypesInSymTable.add(symTable.xmlElementType);
+                                break;
+                            case TypeTags.XML_COMMENT:
+                                collectionTypesInSymTable.add(symTable.xmlCommentType);
+                                break;
+                            case TypeTags.XML_TEXT:
+                                collectionTypesInSymTable.add(symTable.xmlTextType);
+                                break;
+                            case TypeTags.XML_PI:
+                                collectionTypesInSymTable.add(symTable.xmlPIType);
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1948]: It seems this case is not checked

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 6]
```diff
@@ -388,32 +377,91 @@ BLangStatementExpression desugar(BLangQueryAction queryAction, SymbolEnv env,
...
+                desugar.addConversionExprIfRequired(getRootCauseErrorInvo, symTable.errorType));
+        ifErrorBody.stmts.add(unwrapDistinctError);
+        if (ifStatement.expr == null) {
+            ifStatement.expr = queryErrorUnionTypeTestExpr;
+            ifStatement.body = ifErrorBody;
+        } else {
+            BLangIf elseIfStmt = ASTBuilderUtil.createIfStmt(pos, queryBlock);
+            elseIfStmt.expr = queryErrorUnionTypeTestExpr;
+            elseIfStmt.body = ifErrorBody;
+            ifStatement.elseStmt = elseIfStmt;
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:461]: Let's inline first and last line

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:461]: Please ignore this comment.

**Review by KavinduZoysa — APPROVED** [review]
