### PR TITLE
Fix ConcurrentModificationException due to the usage of TreeMap#computeIfAbsent 

### LINKED ISSUE #37236: Crash on basic service template
Because #37180 has not received any response, I decided to re-install the OS and Ballerina.
1. Clean installed and updated Rocky Linux
2. Installed OpenJDK 17 with `sudo dnf install java-17-openjdk`, set JAVA_HOME environment variable
3. Installed Ballerina from ZIP
    1. Downloaded and unzipped
    2. Put extracted director in /usr/lib64/
    3. Created symlink to /usr/bin/ with `ln -s /usr/lib64/ballerina/bin/bal /usr/bin`
4. Tested the installation
```
bal --version
Ballerina 2201.1.1 (Swan Lake Update 1)
Language specification 2022R2
Update Tool 1.3.9
```

Afterwards, following the page [Write a RESTful API with Ballerina](https://ballerina.io/learn/write-a-restful-api-with-ballerina/) I have created the default service template

```
bal new testService -t service
```

Then tested is the default template would run

```
bal run
Compiling source
	myuser/testService:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-08-03 09:56:39,859] SEVERE {b7a.log.crash} - null 
java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap.callMappingFunctionWithCheck(TreeMap.java:750)
	at java.base/java.util.TreeMap.computeIfAbsent(TreeMap.java:604)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.constants.JvmUnionTypeConstantsGen.add(JvmUnionTypeConstantsGen.java:94)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmConstantsGen.getTypeConstantsVar(JvmConstantsGen.java:111)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTypeGen.loadType(JvmTypeGen.java:438)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTypeGen.loadIntersectionType(JvmTypeGen.java:791)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTypeGen.loadType(JvmTypeGen.java:442)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmCreateTypeGen.createField(JvmCreateTypeGen.java:645)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmCreateTypeGen.splitAddFields(JvmCreateTypeGen.java:607)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.types.JvmRecordTypeGen.addRecordFields(JvmRecordTypeGen.java:121)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.types.JvmRecordTypeGen.populateRecord(JvmRecordTypeGen.java:102)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmCreateTypeGen.populateTypes(JvmCreateTypeGen.java:283)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmCreateTypeGen.generateCreateTypesMethod(JvmCreateTypeGen.java:173)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmCreateTypeGen.generateTypeClass(JvmCreateTypeGen.java:159)
	at org.wso2.ballerinalang.compiler.bir.codegen.split.JvmMethodsSplitter.generateMethods(JvmMethodsSplitter.java:56)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:808)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:96)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:71)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:309)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:473)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:381)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:169)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:122)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

If using the RPM package instead of zip, the error I get is the same as #37180

```
bal run
Compiling source
	myuser/testService:0.1.0

Running executable

ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-08-03 10:17:08,596] SEVERE {b7a.log.crash} - Cannot find the generated jar library for module: auth 
java.lang.IllegalStateException: Cannot find the generated jar library for module: auth
	at io.ballerina.projects.JBallerinaBackend.lambda$codeGeneratedLibrary$4(JBallerinaBackend.java:515)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:514)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:282)
	at io.ballerina.projects.JarResolver.addCodeGeneratedLibraryPaths(JarResolver.java:124)
	at io.ballerina.projects.JarResolver.lambda$getJarFilePathsRequiredForExecution$3(JarResolver.java:83)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.ballerina.projects.JarResolver.getJarFilePathsRequiredForExecution(JarResolver.java:81)
	at io.ballerina.cli.task.RunExecutableTask.getAllClassPaths(RunExecutableTask.java:117)
	at io.ballerina.cli.task.RunExecutableTask.runGeneratedExecutable(RunExecutableTask.java:96)
	at io.ballerina.cli.task.RunExecutableTask.execute(RunExecutableTask.java:76)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

Creating a new service, weirdly gives a similar error, but instead of being unable to find auth, it is now unable to find jwt.

```
bal run
Compiling source
	myuser/testService2:0.1.0

Running executable

ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-08-03 10:53:49,996] SEVERE {b7a.log.crash} - Cannot find the generated jar library for module: jwt 
java.lang.IllegalStateException: Cannot find the generated jar library for module: jwt
	at io.ballerina.projects.JBallerinaBackend.lambda$codeGeneratedLibrary$4(JBallerinaBackend.java:515)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:514)
	at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:282)
	at io.ballerina.projects.JarResolver.addCodeGeneratedLibraryPaths(JarResolver.java:124)
	at io.ballerina.projects.JarResolver.lambda$getJarFilePathsRequiredForExecution$3(JarResolver.java:83)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.ballerina.projects.JarResolver.getJarFilePathsRequiredForExecution(JarResolver.java:81)
	at io.ballerina.cli.task.RunExecutableTask.getAllClassPaths(RunExecutableTask.java:117)
	at io.ballerina.cli.task.RunExecutableTask.runGeneratedExecutable(RunExecutableTask.java:96)
	at io.ballerina.cli.task.RunExecutableTask.execute(RunExecutableTask.java:76)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)

```

Running TestService2 a second time, the error becomes exactly as the previous with auth

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #37236

## Approach
We can avoid CME by using `ConcurrentSkipListMap` instead of `TreeMap`, but the code generation happen sequentially we actually do not need a concurrent approach to solve this problem and using `ConcurrentSkipListMap` may bring some performance issues. 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmTupleTypeConstantsGen.java [hunk 1]
```diff
@@ -83,7 +83,10 @@ public void setJvmTupleTypeGen(JvmTupleTypeGen jvmTupleTypeGen) {
     }
 
     public String add(BTupleType type, SymbolTable symbolTable) {
-        return tupleTypeVarMap.computeIfAbsent(type, str -> generateBTupleInits(type, symbolTable));
+        if (!tupleTypeVarMap.containsKey(type)) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmTupleTypeConstantsGen.java:86]: We can invert if condition with true case

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmUnionTypeConstantsGen.java [hunk 2]
```diff
@@ -86,7 +86,10 @@ public void setJvmUnionTypeGen(JvmUnionTypeGen jvmUnionTypeGen) {
     }
 
     public String add(BUnionType type, SymbolTable symbolTable) {
-        return unionTypeVarMap.computeIfAbsent(type, str -> generateBUnionInits(type, symbolTable));
+        if (!unionTypeVarMap.containsKey(type)) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmUnionTypeConstantsGen.java:89]: Lets invert if condition

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmArrayTypeConstantsGen.java [hunk 3]
```diff
@@ -85,7 +85,10 @@ private void visitArrayTypeInitMethod() {
     }
 
     public String add(BArrayType arrayType) {
-        return arrayTypeVarMap.computeIfAbsent(arrayType, str -> generateBArrayInits(arrayType));
+        if (!arrayTypeVarMap.containsKey(arrayType)) {
+            arrayTypeVarMap.put(arrayType, generateBArrayInits(arrayType));
+        }
+        return arrayTypeVarMap.get(arrayType);
     }
```
Comment (Nadeeshan96) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmArrayTypeConstantsGen.java:92]: Since `generateBArrayInits(arrayType)`, `generateTypeRefInits(type)`, `generateBTupleInits(type, symbolTable)`, and `generateBUnionInits(type, symbolTable)` do not return `null`, you can write like this.
```java
public String add(BArrayType arrayType) {
        String arrayTypeVarName  = arrayTypeVarMap.get(arrayType);
        if (arrayTypeVarName == null) {
            arrayTypeVarName = generateBArrayInits(arrayType);
            arrayTypeVarMap.put(arrayType, arrayTypeVarName);
        }
        return arrayTypeVarName;
    }
```
Same for the other changes also.

**Review by warunalakshitha — APPROVED** [review]
LGTM
