### PR TITLE
Fix int subtype union typecast and is-expr

### LINKED ISSUE #31857: Checking byte_value is int:Unsigned8 gives wrong result
**Description:**

$subject

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    byte a = 0x4;    
    io:println(a is int:Unsigned8); //gives false, correct answer is true
}
```

**Affected Versions:**
Ballerina Swan Lake Beta 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

Team/jBallerina

**Suggested Assignees (optional):**

### LINKED ISSUE #31864: Type cast produces incorrect results when casting to builtin sub-type in union
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    int i = -1;

    // int:Unsigned8 j = <int:Unsigned8> i; // panics
    
    int:Unsigned8|boolean k = <int:Unsigned8|boolean> i; // doesn't panic

    io:println(k); // -1
    io:println(k is int:Unsigned8); // false
    io:println(k is boolean); // false
}
```

**Affected Versions:**
slbeta2

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title

Fixes #31857
Fixes #31864

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 1]
```diff
@@ -117,13 +123,19 @@ public static Object convertValues(Type targetType, Object inputValue) {
...
-            case TypeTags.INT_TAG:
             case TypeTags.SIGNED32_INT_TAG:
+                return anyToSigned32(inputValue);
             case TypeTags.SIGNED16_INT_TAG:
+                return anyToSigned16(inputValue);
             case TypeTags.SIGNED8_INT_TAG:
+                return anyToSigned8(inputValue);
             case TypeTags.UNSIGNED32_INT_TAG:
+                return anyToUnsigned32(inputValue);
             case TypeTags.UNSIGNED16_INT_TAG:
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:134]: Can we cover these with few mote tests

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal [hunk 2]
```diff
@@ -1242,3 +1242,73 @@ function assertEquality(anydata expected, anydata actual) {
...
+    int val8 = 0;
+    assertTrue(val8 is byte);
+    assertTrue(val8 is int:Unsigned8);
+    assertTrue(val8 is int:Unsigned16);
+    assertTrue(val8 is int:Unsigned32);
+    assertTrue(val8 is int:Signed8);
+    assertTrue(val8 is int:Signed16);
+    assertTrue(val8 is int:Signed32);
+    assertTrue(val8 is int);
+}
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal:1314]: missing empty line

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java (hunk 1 above)
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:134]: I pulled and pushed, now the patch coverage is 22%, Now also the above lines are not covered by tests are shown. However I set the breakpoints and debugged the tests. In `testCastingToIntSubtypesInUnionNegative` tests these lines are getting hit. So this may be a bug with the patch tool.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal (hunk 2 above)
Comment (Nadeeshan96) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal]: Added it.

**Review by warunalakshitha — APPROVED** [review]
