### PR TITLE
Ignore package symbols that are not imported to the current file

### LINKED ISSUE #34753: Completions are not accurate in qualifed identifier context
**Description:**
As depicted below, there are two bal files in the same module. One has an import statement which imports the `io` module.

Case 1
completion-issue

The completions in the `io:<cursor>` context is not accurate as the `io` module is not imported in the current bal file.

Case 2
completion-issue2

When I select the completion item suggested for importing the `io` module it adds an alias in the import statement though there is no clashing module names in the file. Moreover, no completions are provided for qualified name reference context as depicted above. 

**Steps to reproduce:**
Create a module in a ballerina project. And add the following files. 

file 1
```ballerina
import ballerina/io;

public function main() {
        io:print("Hello")
}
```
file2

```ballerina
function test() {
    io:<cursor>
}
```

**Affected Versions:**
SL-GA-rc1

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #34753

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java [hunk 1]
```diff
@@ -532,9 +534,15 @@ private void addToCompiledSymbols(Set<Symbol> compiledSymbols, Scope.ScopeEntry
                 }
             }
 
-            compiledSymbols.add(compiledSymbol);
+            if (symbol.getKind() == SymbolKind.PACKAGE) {
+                if (((BPackageSymbol) symbol).compUnit.getValue().equals(compUnitName)) {
```
Comment (malinthar) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java:538]: We can merge the two if conditions

**Review by malinthar — COMMENTED** [review]
Changes look good. Better if we can add another test case covering the case mentioned in the issue (`io:<cursor>`) to ensure that we do not provide symbol completions from the un-imported module at the depicted cursor position.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java [hunk 2]
```diff
@@ -532,9 +534,12 @@ private void addToCompiledSymbols(Set<Symbol> compiledSymbols, Scope.ScopeEntry
                 }
             }
 
-            compiledSymbols.add(compiledSymbol);
+            if (!(symbol.getKind() == SymbolKind.PACKAGE
+                    && !((BPackageSymbol) symbol).compUnit.getValue().equals(compUnitName))) {
```
Comment (nadeeshaan) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java:538]: Since this condition is somewhat hard to understand, shall we move this to a a private util method? WDYT?

**Review by mohanvive — DISMISSED** [review]

**Review by malinthar — APPROVED** [review]
LGTM!

**Review by mohanvive — APPROVED** [review]
