### PR TITLE
[beta4] Fix blocked scheduler items not getting reschedule

### LINKED ISSUE #33827: Blocked scheduler items intermittently not getting reschedule
**Description:**
In the Jballerina runtime scheduler, we have scheduler groups and group items. The scheduler group contains a stack of scheduler items.

As an example, if you have 3 workers (except strand annotation with any) those will be added to the same scheduler group.

Each scheduler group is added to the runnable queue. Each os thread in scheduler there pool will assign a group( removed from runnable queue) and execute items.

Once execute each item can be done or blocked on another event like i/o operation, sleep. Then we will execute the next item in the group. If all items are done or blocked we will mark the group "scheduled" flag to be false. Then os thread will assign another group.

Same time blocked items can be done and once done the i/o thread will reschedule the given item. First, it will check the items' group "scheduled" flag and if it is still true means the given group is still running another thread. So we just added to the group items stack so the currently running scheduler thread will execute the item continue the next instructions.

If the group is already done ("scheduled flag false) i/o thread will add that group to the runnable queue.

The group scheduled status change is not an atomic operation. Hence there is a possibility i/o thread might think it is already an executable state and same time scheduler thread change the status to false, so that item gets lost without rescheduling.

So the item will be not done. This will make either program stuck or service requests time out.

### PR DESCRIPTION
**Pull request by warunalakshitha**
## Purpose
Fixes #33827

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java [hunk 1]
```diff
@@ -168,17 +168,7 @@ public FutureValue scheduleToObjectGroup(Object[] params, Function function, Str
         SchedulerItem item = new SchedulerItem(function, params, future);
         future.strand.schedulerItem = item;
         totalStrands.incrementAndGet();
-        ItemGroup group = objectGroup.get();
-        if (group == null) {
-            group = new ItemGroup(item);
-            objectGroup.set(group);
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java:174]: For nonisolated methods, we use this method. But we can initialize the object group during scheduler init. This is a minor improvemnt

**Review by HindujaB — DISMISSED** [review]
LGTM

**Review by HindujaB — APPROVED** [review]
LGTM
