### PR TITLE
Handle array size greater than 2,147,483,637 issue

### LINKED ISSUE #13158: Array size greater than 2,147,483,647 causes error
**Description:**
Defining an array with fixed length greater than 2,147,483,647 produces an error message and a file called `ballerina-internal.log`.

Error message:
```
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

`ballerina-internal.log`:
```
[2019-01-11 16:45:17,208] ERROR {org.ballerinalang.launcher.Main} - For input string: "2147483648" 
java.lang.NumberFormatException: For input string: "2147483648"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:587)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.wso2.ballerinalang.compiler.parser.BLangParserListener.exitArrayTypeNameLabel(BLangParserListener.java:644)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser$ArrayTypeNameLabelContext.exitRule(BallerinaParser.java:3038)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser.compilationUnit(BallerinaParser.java:491)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnit(Parser.java:126)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:99)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:434)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:304)
	at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$3(Compiler.java:153)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:155)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:355)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:112)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
 ```

**Steps to reproduce:**
```ballerina
public function main() {
    int[2147483648] a;
}
```

**Affected Versions:**
- Ballerina version: 0.990.2

**OS, DB, other environment details and versions:**
- Operating System: elementaryOS 5.0 Juno (Ubuntu-based)

### LINKED ISSUE #31707: Compiler throws number format exception
**Description:**
Consider the following screen capture. 

https://user-images.githubusercontent.com/1329674/125588184-ec372b47-435a-46f9-95b8-dfa0e2e6ac28.mp4

```
Following Exception is thrown
java.lang.NumberFormatException: For input string: "9223372036854775807"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.visit(SymbolResolver.java:1082)
	at org.wso2.ballerinalang.compiler.tree.types.BLangArrayType.accept(BLangArrayType.java:60)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:491)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:482)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:2060)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:275)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeVarNode(SemanticAnalyzer.java:1039)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:792)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3599)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3567)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3559)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1559)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3599)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3567)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:3563)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:471)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3599)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:441)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3599)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3567)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3559)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:328)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:293)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:204)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:112)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:398)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:343)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:179)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:135)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:219)
	at org.ballerinalang.langserver.diagnostic.DiagnosticsHelper.getLatestDiagnostics(DiagnosticsHelper.java:115)
	at org.ballerinalang.langserver.diagnostic.DiagnosticsHelper.compileAndSendDiagnostics(DiagnosticsHelper.java:80)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:512)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Affected Versions:**
Swanlake beta2 at least

### LINKED ISSUE #31822: Array size given in hexadecimal breaks the compiler
**Description:**
```ballerina
public function main() {
    int[0x10] l = [];
}
```

```out
[2021-07-21 09:42:52,979] SEVERE {b7a.log.crash} - For input string: "0x10" 
java.lang.NumberFormatException: For input string: "0x10"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:3441)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
        at io.ballerina.compiler.syntax.tree.ArrayTypeDescriptorNode.apply(ArrayTypeDescriptorNode.java:59)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:5343)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2750)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2717)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
        at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:4872)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1507)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
        at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.populateFunctionNode(BLangNodeTransformer.java:1414)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1394)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1372)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
        at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:590)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
        at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:503)
        at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:113)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:365)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:174)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
        at io.ballerina.projects.Package.getCompilation(Package.java:135)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:64)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:163)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by SandaruJayawardana**
Fixes #31707
Fixes #31822 
Fixes #13158

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 1]
```diff
@@ -152,6 +152,8 @@
             "BCE2114", "defaultable.param.not.allowed.after.included.record.param"),
     REQUIRED_PARAM_DEFINED_AFTER_INCLUDED_RECORD_PARAM(
             "BCE2115", "required.param.not.allowed.after.included.record.param"),
+    GREATER_THAN_2147483647_ARRAY_SIZES_NOT_YET_SUPPORTED(
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:155]: Here we have to use the specific error we used earlier to inform the user that, even the feature is explained in the spec, implementation is not yet completed. It is already there i guess

Comment (rdhananjaya) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:155]: Just a idea on top of Gimantha's comment, I don't think using the number make sense to a reader; I think it's better to say `singned int32 max`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 2]
```diff
@@ -3436,11 +3436,28 @@ public BLangNode transform(ArrayTypeDescriptorNode arrayTypeDescriptorNode) {
             } else {
                 Node keyExpr = arrayTypeDescriptorNode.arrayLength().get();
                 if (keyExpr.kind() == SyntaxKind.NUMERIC_LITERAL) {
+                    int length;
                     Token literalToken = ((BasicLiteralNode) keyExpr).literalToken();
                     if (literalToken.kind() == SyntaxKind.DECIMAL_INTEGER_LITERAL_TOKEN) {
-                        sizes.add(new BLangLiteral(Integer.parseInt(literalToken.text()), symTable.intType));
+                        long lengthCheck = Long.parseLong(literalToken.text());
+                        if (lengthCheck > Integer.MAX_VALUE - 10) { // due to the JVM limitations
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:3443]: Let's extract `Integer.MAX_VALUE - 10` into a `final static long` field, and add a comment explaining why you choose  `- 10`

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java (hunk 1 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:155]: Yes, but there are specific diagnostic codes for each 'not yet support features'. For the array size, there wasn't specific code.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 2 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:3443]: okay. I'll change it.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 3]
```diff
@@ -3436,11 +3436,28 @@ public BLangNode transform(ArrayTypeDescriptorNode arrayTypeDescriptorNode) {
             } else {
                 Node keyExpr = arrayTypeDescriptorNode.arrayLength().get();
                 if (keyExpr.kind() == SyntaxKind.NUMERIC_LITERAL) {
+                    int length;
                     Token literalToken = ((BasicLiteralNode) keyExpr).literalToken();
                     if (literalToken.kind() == SyntaxKind.DECIMAL_INTEGER_LITERAL_TOKEN) {
-                        sizes.add(new BLangLiteral(Integer.parseInt(literalToken.text()), symTable.intType));
+                        long lengthCheck = Long.parseLong(literalToken.text());
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:3442]: What if the long is so long that this method throws `NumberFormatException`
https://docs.oracle.com/javase/7/docs/api/java/lang/Long.html#parseLong(java.lang.String)

**Comment by rdhananjaya** [comment]
@SandaruJayawardana can you please check if https://github.com/ballerina-platform/ballerina-lang/issues/31822 can be fixed in the same PR. It looks related.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 3 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:3442]: I'll change it into double instead of long.

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 4]
```diff
@@ -646,6 +646,9 @@ error.annotation.invalid.type=\
   annotation declaration requires a subtype of ''true'', ''map<value:Cloneable>'' or ''map<value:Cloneable>[]'', but \
   found ''{0}''
 
+error.greater.than.signed.int32.max.array.sizes.not.yet.supported=\
+  greater than signed int32 max array sizes not yet supported
```
Comment (lasinicl) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:650]: Shall we change the error message a bit? 
`array size greater than int:Signed32 max is not yet supported`
@gimantha @rdhananjaya WDYT?

Comment (rdhananjaya) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:650]: We also have this https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/int.bal#L59 [1]
But one thing to keep in mind is largest supported size is 10 less than the [1], I'm not sure how to word that though.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 5]
```diff
@@ -3436,11 +3437,38 @@ public BLangNode transform(ArrayTypeDescriptorNode arrayTypeDescriptorNode) {
             } else {
                 Node keyExpr = arrayTypeDescriptorNode.arrayLength().get();
                 if (keyExpr.kind() == SyntaxKind.NUMERIC_LITERAL) {
+                    int length = 0;
                     Token literalToken = ((BasicLiteralNode) keyExpr).literalToken();
                     if (literalToken.kind() == SyntaxKind.DECIMAL_INTEGER_LITERAL_TOKEN) {
-                        sizes.add(new BLangLiteral(Integer.parseInt(literalToken.text()), symTable.intType));
+                        double lengthCheck = Double.parseDouble(literalToken.text());
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:3443]: Can't we use long instead and catch exceptions instead? Then we probably won't need the custom logic from L3455 also.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 6]
```diff
@@ -1074,7 +1075,15 @@ public void visit(BLangArrayType arrayTypeNode) {
                         continue;
                     }
 
-                    int length = Integer.parseInt(sizeConstSymbol.type.toString());
+                    int length;
+                    long lengthCheck = Long.parseLong(sizeConstSymbol.type.toString());
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1079]: Thinking out loud, one other approach we can take to avoid duplicating the logic is to maybe maintain the size maybe as a string at node transformer level and do the parsing and checking here.

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 4 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:650]: Just saw the other comment re: mentioning the exact number, but IMO it is OK since it conveys the exact value that can be used as the maximum.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:650]: Btw, even when we did support this, wouldn't the maximum size that can be specified as the size be `9223372036854775807`? 

We should give a different (invalid size) error for such scenarios, right? Since they will never be allowed?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArraySizeDefinitionTest.java [hunk 7]
```diff
@@ -36,6 +36,7 @@
     private String incompatibleTypeError = "incompatible types: expected 'int', found 'string'";
     private String undefinedSymbolError = "undefined symbol 'length'";
     private String invalidArrayLengthError = "invalid array length";
+    private String sizeLimitError = "greater than signed int32 max array sizes not yet supported";
```
[the remark this answers is not in the document]
Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArraySizeDefinitionTest.java:39]: Since this is a test, do we really need to define it as a constant?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 5 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:3443]: okay. I will use that.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArraySizeDefinitionTest.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArraySizeDefinitionTest.java:39]: The goal is for test code to be of the same quality as the core logic. :) Any reason to not make this a constant?

[the remark this answers is not in the document]
Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArraySizeDefinitionTest.java:39]: No. I told that because of the previous implementation in the test. I will change it to constant :).

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 8]
```diff
@@ -649,6 +649,12 @@ error.annotation.invalid.type=\
   annotation declaration requires a subtype of ''true'', ''map<value:Cloneable>'' or ''map<value:Cloneable>[]'', but \
   found ''{0}''
 
+error.array.size.greater.that.2147483637.not.yet.supported=\
+  array size greater that ''2147483637'' not yet supported
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:653]: Shall we use length instead of size?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 9]
```diff
@@ -649,6 +649,12 @@ error.annotation.invalid.type=\
...
+
+error.invalid.array.length=\
+  invalid array length
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:656]: Shall we say something like

```suggestion
  invalid array length: array length should be a positive integer
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 6 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1113]: I created an issue for this. #32034

**Comment by MaryamZi** [comment]
@SandaruJayawardana, can you please resolve the conflict and update the PR?

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array_size_test.bal [hunk 10]
```diff
@@ -21,4 +21,6 @@ function arraySizeTest() {
     int[2][constLength] f = [[1,2],[1,2]];
     int[constLength][2] k = [[1,2],[1,2]];
     int[2][constLength][2] p = [[[1,2],[1,2]],[[1,2],[1,2]]];
-}
\ No newline at end of file
+    int[0x2] q = [1,2];
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array_size_test.bal:24]:
```suggestion
    int[0x2] q = [1, 2];
```

Shall we also add some tests assigning to an array of the exact size with the size specified as a decimal number. Just to assert correctly parsing.

**Comment by MaryamZi** [comment]
There seems to be another conflict. 

We can also close https://github.com/ballerina-platform/ballerina-lang/issues/13158.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array_size_test.bal (hunk 10 above)
Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/arrays/array_size_test.bal]: I'll add.

**Review by MaryamZi — DISMISSED** [review]

**Review by MaryamZi — DISMISSED** [review]

**Review by MaryamZi — APPROVED** [review]
