### PR TITLE
Fix addition of xml with strings

### LINKED ISSUE #32976: Invalid additive-expr static type when concatenating an XML sequence and a user-defined subtype of string
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    xml<xml:Element|xml:Comment> a = xml `<foo/>`;
    string b = "foo";
    xml<xml:Element|xml:Comment> x1 = a + b; // error: incompatible types: expected 'xml<(xml:Element|xml:Comment)>', found 'xml'
    
    "foo"|"bar" c = "foo";
    xml<xml:Element|xml:Comment> x2 = a + c; // no error!
}
```

**Affected Versions:**
slbeta3-rc3

### LINKED ISSUE #33066: Invalid static type for xml<T> and string concatenation
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    string a = "foo";
    xml<xml:Element> b = xml `<bar/>`;

    xml<xml:Element|xml:Text> c = a + b; // error: incompatible types: expected 'xml<(xml:Element|xml:Text)>', found 'xml'
}
```

But the following evaluates to true
```ballerina
import ballerina/io;

public function main() {
    string a = "foo";
    xml<xml:Element> b = xml `<bar/>`;

    xml c = a + b;
    io:println(c is xml<xml:Element|xml:Text>); // true
}
```

May depend on https://github.com/ballerina-platform/ballerina-spec/issues/937.

**Affected Versions:**
slbeta3-rc5

### PR DESCRIPTION
**Pull request by poorna2152**
## Purpose
Fixes #33066
Fixes #32976

## Approach
Allow addition of xml values and a variable which is assignable to string type.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -5359,6 +5359,15 @@ public void visit(BLangBinaryExpr binaryExpr, AnalyzerData data) {
                 if (leftConstituent != null && rightConstituent != null) {
                     actualType = new BXMLType(BUnionType.create(null, leftConstituent, rightConstituent), null);
                     break;
+                } else if (leftConstituent != null || rightConstituent != null) {
+                    if (leftConstituent != null && types.isAssignable(rhsType, symTable.stringType)) {
+                        actualType = new BXMLType(BUnionType.create(null, leftConstituent, symTable.xmlTextType), null);
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5364]: IMO, creating this kind of union type for the actual type is not correct. For example, consider the following case: it creates a union type with the same type twice, which is incorrect.
```ballerina
type Foo xml<xml:Element|xml:Comment>;
public function main() {
    xml<xml:Element|xml:Text> a = xml `<foo/>`;
    string b = "foo";
    ("foo"|"bar") c = "foo";
    Foo x2 = a + c; 
}
```
This example gives error as
```
incompatible types: expected 'Foo', found 'xml<(xml:Element|xml:Text|xml:Text)>
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -5359,6 +5359,15 @@ public void visit(BLangBinaryExpr binaryExpr, AnalyzerData data) {
                 if (leftConstituent != null && rightConstituent != null) {
                     actualType = new BXMLType(BUnionType.create(null, leftConstituent, rightConstituent), null);
                     break;
+                } else if (leftConstituent != null || rightConstituent != null) {
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5362]: In this case, you can update the `getXMLConstituents` method to check whether the type is assignable to a string or not. Also, change the function name accordingly to reflect the new logic. By doing this, we can eliminate this logic.

Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5362]: I dont think its possible to do this because both types can be string in that case and this only handles xml types

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -5367,6 +5367,15 @@ public void visit(BLangBinaryExpr binaryExpr, AnalyzerData data) {
...
+                    Location pos = binaryExpr.pos;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5371]: Can be extracted in-line.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 4]
```diff
@@ -5420,6 +5429,20 @@ public void visit(BLangBinaryExpr binaryExpr, AnalyzerData data) {
         data.resultType = types.checkType(binaryExpr, actualType, data.expType);
     }
 
+    private BType getXmlBinaryOpResultType(BType opType, BType constituentType, SymbolEnv env, Location pos) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5432]: This is meant to be called only when the other operand is of a type that is a subtype of string, right? Shall we make sure the method name reflects what happens here?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 5]
```diff
@@ -5420,6 +5429,20 @@ public void visit(BLangBinaryExpr binaryExpr, AnalyzerData data) {
...
+        if (types.isAssignable(symTable.xmlTextType, constituentType)) {
+            return opType;
+        }
+
+        BTypeSymbol typeSymbol =
+                Symbols.createTypeSymbol(SymTag.UNION_TYPE, 0, Names.EMPTY, env.enclPkg.symbol.pkgID, null,
+                        env.scope.owner, pos, VIRTUAL);
+        BType type = new BXMLType(BUnionType.create(typeSymbol, constituentType, symTable.xmlTextType),
+                symTable.xmlType.tsymbol);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5441]: I think symbol should be null here.

**Review by MaryamZi — APPROVED** [review]
