### PR TITLE
[Shell] Provide a mechanism for auto importing modules

### LINKED ISSUE #30915: [Shell] Provide a mechanism for auto importing modules used in a snippet
Consider the simple case of using `io:println()` to print something. Currently, I have to explicitly import the `io` module before using it. If I attempt to use it without importing, I get the following error:
```
=$ io:println("hello world")                                                                                                                                                                                         
| error: undefined function 'println'
| 	io:println("hello world")
| 	^-----------------------^
| Compilation aborted due to errors.
```
Instead of doing this, it'd be great if we can automatically add an import for `io` in this. At least maybe do this for standard libraries that are available OOTB in the distribution?

### PR DESCRIPTION
**Pull request by DamithaSenevirathne**
## Purpose

Fixes #30915
Provides functionality to notify unavailable modules and import them if modules are available in the distribution. 

Screenshot from 2021-11-30 12-28-11

In this PR
 - `evaluator.evaluate()` breaks into two separate APIs `evaluator.getCompilation() `and `evaluator.getValue(`).
 - Used `Enum ExceptionStatus` instead of throwing the error.
 - Test were updated related to throwing errors.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+     */
+    private List<Package> getPackagesFromDistRepo() {
+        DefaultEnvironment environment = new DefaultEnvironment();
+        // Creating a Ballerina distribution instance
+        BallerinaDistribution ballerinaDistribution = BallerinaDistribution.from(environment);
+        PackageRepository packageRepository = ballerinaDistribution.packageRepository();
+        Map<String, List<String>> pkgMap = packageRepository.getPackages();
+
+        List<io.ballerina.projects.Package> packages = new ArrayList<>();
+        List<String> skippedLangLibs = Arrays.asList("lang.annotations", "lang.__internal", "lang.query");
```
Comment (dulajdilshan) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java:130]: Why don't we keep this outside of the method? We could keep this as a `final` list right?

Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java]: Updated in e17fcf134c2456d78b8f384f5f92fc44b14b264d

File: ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java [hunk 2]
```diff
@@ -235,4 +265,81 @@ public void reset() {
...
+    public boolean isContainsUndefinedModules(Collection<Diagnostic> diagnostics) {
+        boolean isContainsUndefinedModules = false;
+        for (Diagnostic diagnostic : diagnostics) {
+            if (diagnostic.toString().contains("undefined module")) {
+                isContainsUndefinedModules = true;
+                break;
+            }
+        }
+
+        return isContainsUndefinedModules;
```
Comment (mohanvive) [inline ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java:343]: Let's 
```suggestion
        for (Diagnostic diagnostic : diagnostics) {
            if (diagnostic.toString().contains("undefined module")) {
                return true;
            }
        }

        return false;
```

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java [hunk 3]
```diff
@@ -0,0 +1,156 @@
+/*
```
Comment (mohanvive) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java:1]: This class should move to utils.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java [hunk 4]
```diff
@@ -0,0 +1,156 @@
...
+    }
+
+    /**
+     * Check module availability in the distribution.
+     *
+     * @param module module name.
+     * @return availability of the module.
+     */
+    public boolean isModuleInDistRepo(String module) {
+        boolean isModuleInDistRepo = false;
```
Comment (mohanvive) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java:66]: This logic could be improved without this variable.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+        String langModule = LANG + "." + module;
+        for (Package pkg : packageList) {
+            if (module.equals(pkg.packageName().value()) || langModule.equals(pkg.packageName().value())) {
```
Comment (mohanvive) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java:69]: It is not mandatory to import lang modules, right? Then why are we covering this case?

**Review by mohanvive — CHANGES_REQUESTED** [review]

File: ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java (hunk 2 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java]: Updated in 7206767a98cd266b722f016fca60ecf1fac9aec7

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java (hunk 3 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java]: Updated in 7206767a98cd266b722f016fca60ecf1fac9aec7

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java (hunk 4 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java]: Updated in 7206767a98cd266b722f016fca60ecf1fac9aec7

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java (hunk 5 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ModuleImporter.java]: if we consider this example https://ballerina.io/learn/by-example/json-type user should be notified to import related Lang module.

**Comment by mohanvive** [comment]
@DamithaSenevirathne sync with the master and resolve the conflicts.

File: ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java [hunk 6]
```diff
@@ -235,4 +265,79 @@ public void reset() {
...
+     *
+     * @param moduleImporter moduleImporter.
+     * @param modules        available modules.
+     */
+    public void importModules(ModuleImporter moduleImporter, List<String> modules) {
+        List<String> missingModules = new ArrayList<>();
+        List<String> requiredModules = new ArrayList<>();
+        terminal.info("Found following undefined module(s).");
+        for (String module : modules) {
+            module = module.replaceAll("'", "");
```
Comment (nadeeshaan) [inline ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java:280]: If you are trying to replace the single quote here, let's use `replace` instead of `replaceAll` since the latter accepts a regex.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/Evaluator.java [hunk 7]
```diff
@@ -58,17 +60,30 @@ protected Evaluator(Preprocessor preprocessor, TreeParser treeParser,
...
+     * An input line may contain one or more statements separated by semicolons.
+     * The result will be written via the {@code ShellResultController}.
+     * <p>
+     * If the execution failed, an error will be thrown instead.
+     *
+     * @param compilation compilation.
      * @return String output from the evaluator. This will be the last output.
      */
-    public abstract String evaluate(String source) throws BallerinaShellException;
+    public abstract String getValue(Optional<PackageCompilation> compilation) throws BallerinaShellException;
```
Comment (nadeeshaan) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/Evaluator.java:86]: Since this is a public API, without changing the signature, let's add a newAPI for `getValue` keeping `evaluate` API as well

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/EvaluatorImpl.java [hunk 8]
```diff
@@ -63,35 +63,26 @@ public void initialize() throws BallerinaShellException {
...
+            exceptionStatus = ExceptionStatus.SUCCESS;
+            clearDiagnostics(exceptionStatus);
+            return new ShellCompilation(compilation, exceptionStatus);
         } catch (TreeParserException e) {
-            addAllDiagnostics(treeParser.diagnostics());
-            treeParser.resetDiagnostics();
-            return new ShellCompilation(Optional.empty(), ExceptionStatus.TREE_PARSER_FAILED);
+            exceptionStatus = ExceptionStatus.TREE_PARSER_FAILED;
+            clearDiagnostics(exceptionStatus);
+            return new ShellCompilation(null, exceptionStatus);
```
Comment (nadeeshaan) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/EvaluatorImpl.java:77]: Without passing null, add a constructor with the status argument.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ExceptionStatus.java [hunk 9]
```diff
@@ -0,0 +1,42 @@
...
+ *
+ * @since 2.0.0
+ */
+public enum ExceptionStatus {
+    SUCCESS("success"),
+    TREE_PARSER_FAILED("tree_parser_failed"),
+    SNIPPET_FAILED("snippet_failed"),
+    INVOKER_FAILED("invoker_failed");
+
+    String status;
```
Comment (nadeeshaan) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ExceptionStatus.java:32]: Better make the field private

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/ShellSnippetsInvoker.java [hunk 10]
```diff
@@ -221,6 +229,7 @@ protected Project getProject(String source, boolean isOffline) throws InvokerExc
      * @throws InvokerException If compilation failed.
      */
     protected PackageCompilation compile(Project project) throws InvokerException {
+        boolean isContainsErrors = false;
```
Comment (nadeeshaan) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/ShellSnippetsInvoker.java:232]: make the variable name be `containErrors`

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java [hunk 11]
```diff
@@ -104,13 +110,36 @@ public void run() {
...
+                    ShellCompilation shellCompilation = evaluator.getCompilation(source);
+                    Optional<PackageCompilation> compilation = shellCompilation.getPackageCompilation();
+                    if (ExceptionStatus.SUCCESS == shellCompilation.getExceptionStatus()) {
+                        String result = evaluator.getValue(compilation);
+                        terminal.result(result);
+                    }
+                    if (ExceptionStatus.INVOKER_FAILED == shellCompilation.getExceptionStatus()) {
+                        if (isContainsUndefinedModules(evaluator.diagnostics())) {
+                            ModuleImporter moduleImporter = new ModuleImporter();
+                            List<String> modules = moduleImporter.undefinedModules(evaluator.diagnostics());
```
[the remark this answers is not in the document]
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java]: Updated in 9f270db8b7259fb63e77545e8454623db4d6c3a7

File: ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java (hunk 6 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java]: Updated in 9f270db8b7259fb63e77545e8454623db4d6c3a7

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/Evaluator.java (hunk 7 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/Evaluator.java:99]: Updated in 9f270db8b7259fb63e77545e8454623db4d6c3a7

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/EvaluatorImpl.java (hunk 8 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/EvaluatorImpl.java]: Updated in 9f270db8b7259fb63e77545e8454623db4d6c3a7

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ExceptionStatus.java (hunk 9 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/ExceptionStatus.java]: Updated in 9f270db8b7259fb63e77545e8454623db4d6c3a7

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/ShellSnippetsInvoker.java (hunk 10 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/ShellSnippetsInvoker.java]: Updated in 9f270db8b7259fb63e77545e8454623db4d6c3a7

**Review by nadeeshaan — DISMISSED** [review]
LGTM

**Review by dulajdilshan — APPROVED** [review]
LGTM

**Review by mohanvive — APPROVED** [review]
