### PR TITLE
Fix converting json to immutable open record type

### LINKED ISSUE #33149: Conversion to an immutable open record type fails when the value has extra fields
**Description:**
I have tried to map a payload to a JSON which have nested structures and I have used an open record to omit that and gives and `{ballerina/lang.map}InherentTypeViolation` error.

**Steps to reproduce:**
```bal
type Foo record {|
    readonly Bar w;
|};

public type Bar record {
    string x;
    // Baz y; // Works when uncommented.
};

public type Baz record {
    string z;
};



public function main() returns error? {
    json j = {
        w: {
            x: "",
            y: {
                z: ""
            }
        }
    };

    Foo f = check j.cloneWithType();
}
```

**Affected Versions:**
swan-lake-beta3 

**Slack Channel**
https://ballerina-platform.slack.com/archives/C47EAELR1/p1633840690132500

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes #33149 

## Approach
The `readonly` part of `anydata & readonly` type is not passed correctly when creating the type. Therefore, it resulted in type conversion errors.
This PR fixes it. 

## Samples
```ballerina
type Foo record {
};

public function main() returns error? {
    json j = {
        a: {
        }
    };

    Foo & readonly f = check j.cloneWithType();
}
```
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java [hunk 1]
```diff
@@ -325,42 +325,43 @@ public void testCloneWithType(String function) {
...
-                { "testCloneWithTypeWithFiniteArrayTypeFromIntArray" },
-                { "testCloneWithTypeWithFiniteType" },
-                { "testCloneWithTypeWithUnionOfFiniteType" },
-                { "testCloneWithTypeWithFiniteArrayTypeFromIntArray" },
-                { "testCloneWithTypeWithUnionOfFiniteTypeArraysFromIntArray" },
-                { "testCloneWithTypeWithUnionTypeArrayFromIntArray" },
-                { "testCloneWithTypeWithFiniteTypeArrayFromIntArrayNegative" },
-                { "testConvertJsonToNestedRecordsWithErrors" },
-                { "testCloneWithTypeNestedStructuredTypesNegative"}
+        return new Object[][]{
```
Comment (gabilang) [inline langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java:328]: Can we return `String[]` instead of `Object[][]` since we are passing strings as function names?

**Review by warunalakshitha — APPROVED** [review]
LGTM
