### PR TITLE
Fix issues with accessing a function using field access within the init function of same class

### LINKED ISSUE #28457: Bad-Sad error when function is accessed using field access within the init method of same class
**Description:**
```ballerina
class A {
    function foo(int i) returns int {
        return i+1;
    }

    function (int i) returns int bar;

    function init() {
        self.bar = self.foo;
    }

    // This works
    function baz() returns function (int) returns int {
        self.bar = self.foo;
        return self.bar;
    }
}

public function main() {
    A a = new A();
    var x = a.baz();
    panic error(x(1).toString());
}
```

[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/5931625/ballerina-internal.log)
**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Alpha.

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #28457 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java [hunk 1]
```diff
@@ -1429,29 +1429,36 @@ void generateObjectLoadIns(BIRNonTerminator.FieldAccess objectLoadIns) {
     }
 
     void generateObjectStoreIns(BIRNonTerminator.FieldAccess objectStoreIns) {
+        if (objectStoreIns.onInitialization) {
+            // visit object_ref
+            this.loadVar(objectStoreIns.lhsOp.variableDcl);
```
Comment (Nadeeshan96) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:1434]: Shall we move these before the `if` block as they are common?

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object_function_pointer.bal [hunk 2]
```diff
@@ -41,9 +43,31 @@ public class SampleWindow {
     }
 }
 
-function testObjectFunctionPointer() returns int {
+function testObjectFunctionPointer() {
     Window win = new LengthWindow();
     (function () returns int) pointer = () => win.process();
     win = new SampleWindow();
-    return pointer();
+    test:assertTrue(pointer() is int);
```
Comment (Nadeeshan96) [inline tests/jballerina-unit-test/src/test/resources/test-src/object/object_function_pointer.bal:50]: No need for this assertion because `pointer` is a function which returns an int anyway.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java [hunk 3]
```diff
@@ -371,14 +371,18 @@ public void testObjectSelfreferenceWithDefaultable() {
         Assert.assertEquals(returns, 89L);
     }
 
-    @Test(description = "Test function references from an object")
-    public void testFunctionReferencesFromObjects() {
+    @Test(description = "Test function references from an object", dataProvider = "functionReferencesFromObjectTests")
+    public void testFunctionReferencesFromObjects(String functionName) {
         CompileResult compileResult = BCompileUtil.compile("test-src/object/object_function_pointer.bal");
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java:376]: Shall we move `compileResult` inside the `setup()` method? It will compile multiple times for each call from the data provider.

**Review by warunalakshitha — APPROVED** [review]

**Review by warunalakshitha — COMMENTED** [review]
LGTM
