### PR TITLE
[Master] Fix inherent type of byte-array-literal

### LINKED ISSUE #32542: The inherent type of the array value of `byte-array-literal` created is not `byte[N]`
**Description:**
Spec says,
> The static type of byte-array-literal is byte[N], where N is the number of bytes encoded by the Base16Literal or Base64Literal. The inherent type of the array value created is also byte[N]. 

Consider following sample
```bal
io:println(base16 `aa bb` is byte[2]);  // output should be true
byte[2] byteArray1 = base16 `aa bb`; // gives the error incompatible types: expected 'byte[2]', found 'byte[]'
byte[*] byteArray2 = base16 `aa bb`; // gives the error incompatible types: expected 'byte[*]', found 'byte[]'
```

### PR DESCRIPTION
**Pull request by prakanth97**
Fixes #32542 

```
byte[2] a = base16 `aa bb`;
byte[3] b = base16 `aa bb`;             // error

byte[2] f = base64 `aa bb`;             // error
byte[3] g = base64 `aa bb`;
```
here b and f will give errors.

```
byte[] & readonly arr1 = <byte[] & readonly>base16`aa bb`;
int[2] & readonly arr2 = <int[2] & readonly>base16`aa bb`;
```
Casting the byte-array-literal to readonly type is allowed.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -868,12 +875,72 @@ public BType setLiteralValueAndGetType(BLangLiteral literalExpr, BType expType,
...
+            dlog.error(literalExpr.pos, DiagnosticErrorCode.MISMATCHING_ARRAY_LITERAL_VALUES, arrayType.size,
+                    byteArray.length);
+            return symTable.semanticError;
+        }
+
+        if (Symbols.isFlagOn(arrayType.flags, Flags.READONLY)) {
+            boolean isValidType =
+                        types.checkType(literalExpr.pos, symTable.byteType, arrayType.eType,
+                                DiagnosticErrorCode.INCOMPATIBLE_TYPES) != symTable.semanticError;
+            return isValidType ? arrayType : symTable.semanticError;
```
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:939]: I wonder if we have to verify if this is valid in the spec, since it explicitly says

> The inherent type of the array value created is also byte[N].

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java [hunk 2]
```diff
@@ -556,7 +556,7 @@ public void addRefValue(long index, Object value) {
             case TypeTags.UNSIGNED16_INT_TAG:
             case TypeTags.UNSIGNED8_INT_TAG:
                 prepareForAdd(index, value, type, intValues.length);
-                this.intValues[(int) index] = (Long) value;
+                this.intValues[(int) index] = Long.parseLong(String.valueOf(value));
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java:559]: Why is this needed?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -868,12 +875,72 @@ public BType setLiteralValueAndGetType(BLangLiteral literalExpr, BType expType,
...
+                    literalExpr, (BArrayType) literalExpr.expectedType, (BArrayType) literalType, byteArray, data);
+        }
+        return types.checkType(literalExpr, literalType, data.expType);
+    }
+
+    private BType checkByteArrayCompatibility(BLangLiteral literalExpr, BArrayType arrayType, BArrayType literalType,
+                                              byte[] byteArray, AnalyzerData data) {
+        if (arrayType.state == BArrayState.INFERRED) {
+            arrayType.size = byteArray.length;
+            arrayType.state = BArrayState.CLOSED;
```
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:926]: https://github.com/ballerina-platform/ballerina-lang/blob/eac8c96aa024c308022b55c059e78532f19b30b9/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L1829 

I followed the list constructor, it is updated same as this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 4]
```diff
@@ -868,12 +875,72 @@ public BType setLiteralValueAndGetType(BLangLiteral literalExpr, BType expType,
...
-            literalType = new BArrayType(symTable.byteType);
+            byte[] byteArray = convertToByteArray(literalExpr);
+            literalType = new BArrayType(symTable.byteType, null, byteArray.length,
+                    BArrayState.CLOSED);
         }
 
         return literalType;
     }
 
+    private byte[] convertToByteArray(BLangLiteral literalExpr) {
```
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated 1a3dab6fd10d46f567ffda32f6d2ab9540fe73d1

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:911]: [#1150](https://github.com/ballerina-platform/ballerina-spec/issues/1150)

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 5]
```diff
@@ -868,12 +875,72 @@ public BType setLiteralValueAndGetType(BLangLiteral literalExpr, BType expType,
...
+                                              byte[] byteArray, AnalyzerData data) {
+        if (arrayType.state == BArrayState.INFERRED) {
+            arrayType.size = byteArray.length;
+            arrayType.state = BArrayState.CLOSED;
+        }
+
+        if (arrayType.state != BArrayState.OPEN && byteArray.length != arrayType.size) {
+            dlog.error(literalExpr.pos, DiagnosticErrorCode.MISMATCHING_ARRAY_LITERAL_VALUES, arrayType.size,
+                    byteArray.length);
+            return symTable.semanticError;
```
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated 9ca236f9b33629771fe31bb774ba45a57df4a7cb

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 6]
```diff
@@ -5695,7 +5695,8 @@ public void visit(BLangForkJoin forkJoin) {
     @Override
     public void visit(BLangLiteral literalExpr) {
         if (literalExpr.getBType().tag == TypeTags.ARRAY
-                && ((BArrayType) literalExpr.getBType()).eType.tag == TypeTags.BYTE) {
+                && (((BArrayType) literalExpr.getBType()).eType.tag == TypeTags.BYTE
+                || ((BArrayType) literalExpr.getBType()).eType.tag == TypeTags.INT)) {
```
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Updated 9ca236f9b33629771fe31bb774ba45a57df4a7cb

Made this change in `desugar`

https://github.com/ballerina-platform/ballerina-lang/pull/37326/commits/9ca236f9b33629771fe31bb774ba45a57df4a7cb#diff-a5961a28254babde0aa44e4c1cb05126b5ee68494baccca1c76879dec267b8aeR5695

Only `byte-array-literal` can be an array in the `literalExpr`. Right?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java (hunk 2 above)
Comment (prakanth97) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java]: Removed d759431e4a477acf23fed76b56fef739bb264967

**Comment by SasinduDilshara** [comment]
Codecov shows some lines i8n the `TypeChecker` not covered from tests.
Add necessary tests for them or remove those lines

File: tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-array-value-negative.bal [hunk 7]
```diff
@@ -17,3 +17,17 @@ function base64InvalidLiteralTest() {
     byte[] f = base64 `afcd341a4bdfaaabmcfccadabcd89 12df ss==`;
     byte[] g = base64 `afcd34abcdef123aGc2?>><*&*^&34bcd1a4bdfABbadaBCd892s3as==`;
 }
+
+function byteArrayLiteralTypeTest() {
+    byte[2] a = base16 `aa bb`;
+    byte[3] b = base16 `aa bb`;             // error
+    int[3] c = base16 `aa bb`;              // error
+    byte[*] d = base16 `aa bb`;
```
Comment (SasinduDilshara) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-array-value-negative.bal:25]: Do we need this lines for the negative tests, because of there is no error

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 8]
```diff
@@ -452,7 +453,11 @@ public void visit(BLangLiteral literalExpr, AnalyzerData data) {
         if (literalType == symTable.semanticError || literalExpr.isFiniteContext) {
             return;
         }
-        data.resultType = types.checkType(literalExpr, literalType, data.expType);
+        if (literalType.tag == TypeTags.ARRAY) {
+            data.resultType = checkByteArrayType(literalExpr, literalType, data);
+        } else {
+            data.resultType = types.checkType(literalExpr, literalType, data.expType);
+        }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:460]: Why do we need to special case like this? Since the expected type is available when we call `setLiteralValueAndGetType`, isn't it enough to update `setLiteralValueAndGetType` to handle byte array literals when the applicable contextually-expected type is immutable?

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:460]: If we do that according to this logic it will return type mismatch error https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L828-#L831. 

if the contextual expected type is immutable then we check the compatibility of individual member as `list-constructor-expr` logic. Compare to the other literals they are `inherently immutable` but `byte-array-literal` is considered as `array-type` which is `selectively immutable`, that's why we special case that.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-array-value-negative.bal (hunk 7 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-array-value-negative.bal:25]: Can't we have positive cases in negative test? @MaryamZi @pcnfernando

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 8 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:460]: When it fails, what is `literalType`? Isn't it a subtype of `readonly`? It should be a subtype of `readonly`, right? Which should make checkType pass.

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated 1ea491f08f4d803a466d7804eb8973e3c84b0eb5

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 9]
```diff
@@ -6573,4 +6576,31 @@ public static class CommonAnalyzerData {
...
         boolean nonErrorLoggingCheck = false;
     }
+
+    public static byte[] convertToByteArray(String literalExpr) {
+        String[] elements = getLiteralTextValue(literalExpr);
+        if (elements[0].contains(BASE_16)) {
+            return hexStringToByteArray(elements[1]);
+        }
+        return Base64.getDecoder().decode(elements[1].getBytes(StandardCharsets.UTF_8));
+    }
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:6586]: Warning is false negative

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 10]
```diff
@@ -6573,4 +6576,31 @@ public static class CommonAnalyzerData {
...
+
+    private static byte[] hexStringToByteArray(String base16String) {
+        int arrayLength = base16String.length();
+        byte[] byteArray = new byte[arrayLength / 2];
+        for (int i = 0; i < arrayLength; i += 2) {
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:6591]: Warning is false negative

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 11]
```diff
@@ -6573,4 +6576,31 @@ public static class CommonAnalyzerData {
...
+            byteArray[i / 2] = (byte) ((Character.digit(base16String.charAt(i), 16) << 4)
+                    + Character.digit(base16String.charAt(i + 1), 16));
+        }
+        return byteArray;
+    }
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:6596]: Warning is false negative

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 12]
```diff
@@ -6573,4 +6576,31 @@ public static class CommonAnalyzerData {
...
+
+    private static String[] getLiteralTextValue(String literalExpr) {
+        String nodeText = literalExpr.replace("\t", "").replace("\n", "").replace("\r", "")
+                .replace(" ", "");
+        String[] result = new String[2];
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:6601]: Warning is false negative

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 13]
```diff
@@ -1739,7 +1739,8 @@ private boolean isValidInferredArray(BLangNode node) {
             case VARIABLE:
                 BLangSimpleVariable varNode = (BLangSimpleVariable) node;
                 BLangExpression expr = varNode.expr;
-                return expr != null && expr.getKind() == NodeKind.LIST_CONSTRUCTOR_EXPR &&
+                return expr != null && (expr.getKind() == NodeKind.LIST_CONSTRUCTOR_EXPR ||
+                        expr.getKind() == LITERAL) &&
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1743]: For below expr kind will be group-expr. Hence, the logic will break
```ballerina
 byte[*] _ = (base16 `aa bb`);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 14]
```diff
@@ -242,6 +242,7 @@ public class TypeChecker extends SimpleBLangNodeAnalyzer<TypeChecker.AnalyzerDat
     private static final String FUNCTION_NAME_SHIFT = "shift";
     private static final String FUNCTION_NAME_UNSHIFT = "unshift";
     private static final String FUNCTION_NAME_ENSURE_TYPE = "ensureType";
+    private static final String BASE_16 = "base16";
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:245]: This is unused

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 15]
```diff
@@ -5704,13 +5701,7 @@ public void visit(BLangLiteral literalExpr) {
     }
 
     private BLangNode rewriteBlobLiteral(BLangLiteral literalExpr) {
-        String[] result = getBlobTextValue((String) literalExpr.value);
-        byte[] values;
-        if (BASE_64.equals(result[0])) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5709]: Remove the Base_64 constant at desugar as well

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 13 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Updated 97e8d52b62113bda3abb212078e222f001bea4f3

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 16]
```diff
@@ -5694,8 +5691,7 @@ public void visit(BLangForkJoin forkJoin) {
 
     @Override
     public void visit(BLangLiteral literalExpr) {
-        if (literalExpr.getBType().tag == TypeTags.ARRAY
-                && ((BArrayType) literalExpr.getBType()).eType.tag == TypeTags.BYTE) {
+        if (literalExpr.getBType().tag == TypeTags.ARRAY) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5694]: With https://github.com/ballerina-platform/ballerina-lang/pull/37307, literalExpr.getBType() can be a typeReference. 
```suggestion
        if (Types.getReferredType(literalExpr.getBType()).tag == TypeTags.ARRAY) {
```

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5694]: Is this applicable for this https://github.com/ballerina-platform/ballerina-lang/blob/97e8d52b62113bda3abb212078e222f001bea4f3/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L869 as well ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 17]
```diff
@@ -6573,4 +6576,31 @@ public static class CommonAnalyzerData {
         int letCount = 0;
         boolean nonErrorLoggingCheck = false;
     }
+
+    public static byte[] convertToByteArray(String literalExpr) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:6580]: Do these have to be static methods? The pattern we have followed (for most) is to call the methods via a types instance.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayInitializerExprTest.java [hunk 18]
```diff
@@ -154,6 +154,20 @@ public void testFloatArrayInitWithIntExpr() {
...
+        Object[] args = {};
+        Object returns = BRunUtil.invoke(compileResult, "testInferredArrayInitWithInGrpExpr", args);
+
+        Assert.assertTrue(returns instanceof BArray);
+
+        BArray arrayValue = (BArray) returns;
+        Assert.assertEquals(arrayValue.size(), 3);
+        Assert.assertEquals(arrayValue.getInt(0), 1);
+        Assert.assertEquals(arrayValue.getInt(1), 2);
+        Assert.assertEquals(arrayValue.getBString(2).getValue(), "a");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayInitializerExprTest.java:168]: Why aren't we doing the assertions in Ballerina?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte_as_int_test.bal [hunk 19]
```diff
@@ -186,6 +189,22 @@ function testDowncastOfByteArrayCastToIntArray() {
...
+    int[2] & readonly arr2 = <int[2] & readonly>base16 `aa bb`;
+    assertTrue(arr2.isReadOnly());
+
+    byte[2] & readonly arr3 = <readonly>base16 `aa bb`;
+    assertTrue(arr3.isReadOnly());
+
+    anydata[] & readonly arr4 = <anydata[] & readonly>base16 `aa bb`;
+    assertTrue(arr4.isReadOnly());
+
+    any[] arr5 = <any[] & readonly>base16 `aa bb`;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte_as_int_test.bal:205]: Not asserted/used?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte_array_value.bal [hunk 20]
```diff
@@ -33,6 +36,26 @@ function base64ByteArrayLiteralWithWS() {
     assertEquality(byteArray1, byteArray3);
 }
 
+function testByteArrayLiteralInherentType() {
+    var byteArray1 = base16 `aa bb`;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte_array_value.bal:40]: Do we have compile-time tests like
```ballerina
    byte[2] _ = byteArray1;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 21]
```diff
@@ -1760,6 +1760,18 @@ private boolean isValidContextForInferredArray(BLangNode node) {
         }
     }
 
+    private boolean isValidVariableForInferredArray(BLangNode node) {
+        switch (node.getKind()) {
+            case LITERAL:
```
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1765]: `byte-array-literal` is the only array type within the literal types, So it is sufficient to check for `Literal` here. This method is called within the `BLangArrayType` visitor.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayInitializerExprTest.java (hunk 18 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayInitializerExprTest.java:168]: I followed the same pattern used for other test cases in this specific test

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayInitializerExprTest.java:168]: We can do the assertions in Ballerina for new tests we add. Eventually we will migrate most of the assertions in Java to Ballerina anyway.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 22]
```diff
@@ -5694,8 +5691,7 @@ public void visit(BLangForkJoin forkJoin) {
 
     @Override
     public void visit(BLangLiteral literalExpr) {
-        if (literalExpr.getBType().tag == TypeTags.ARRAY
-                && ((BArrayType) literalExpr.getBType()).eType.tag == TypeTags.BYTE) {
+        if (Types.getReferredType(literalExpr.getBType()).tag == TypeTags.ARRAY) {
```
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5694]: I will add tests .
```
type ByteArr  base16 `aa bb`;
``` 
This is not allowed in the spec, right? Do we need to get the referred type from `literalExpr.getBType()`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 17 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Updated 9bc02e498c2314a3ddd5b48eb66ac7117ec63844

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayInitializerExprTest.java (hunk 18 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/arrays/ArrayInitializerExprTest.java]: Updated a41828e66acf222373ef93deff481bde6310fd77

File: tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte_as_int_test.bal (hunk 19 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte_as_int_test.bal:205]: Updated a41828e66acf222373ef93deff481bde6310fd77

File: tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte_array_value.bal (hunk 20 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte_array_value.bal:40]: Updated a41828e66acf222373ef93deff481bde6310fd77

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 23]
```diff
@@ -866,9 +866,23 @@ public BType setLiteralValueAndGetType(BLangLiteral literalExpr, BType expType,
...
         }
 
-        if (literalExpr.getBType().tag == TypeTags.BYTE_ARRAY) {
+        if (Types.getReferredType(literalExpr.getBType()).tag == TypeTags.BYTE_ARRAY) {
             // check whether this is a byte array
-            literalType = new BArrayType(symTable.byteType);
+            byte[] byteArray = Types.convertToByteArray((String) literalExpr.value);
+            literalType = new BArrayType(symTable.byteType, null, byteArray.length,
+                    BArrayState.CLOSED);
+            if (Symbols.isFlagOn(expectedType.flags, Flags.READONLY)) {
```
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:874]: Updated a41828e66acf222373ef93deff481bde6310fd77

**Comment by rdulmina** [comment]
```bal
public function main() {
    var x = <readonly> base16 `aa`; 
}
```

This gives error `unused variable 'x' with inferred type including error` can u have a look?

**Comment by MaryamZi** [comment]
> ```ballerina
> public function main() {
>     var x = <readonly> base16 `aa`; 
> }
> ```

This is most probably because the static type of `x` is `readonly` atm, and that includes `error`. Once https://github.com/ballerina-platform/ballerina-lang/issues/24559 is fixed, this would go away.

**Comment by rdulmina** [comment]
```bal
public function main() {
    var y = base16 `aa`;
    io:println(typeof y);
}
```
Gives 

```
java.lang.NoSuchMethodError: io.ballerina.runtime.internal.types.BFunctionType.<init>([Lio/ballerina/runtime/api/types/Parameter;Lio/ballerina/runtime/api/types/Type;Lio/ballerina/runtime/api/types/Type;JLjava/lang/String;Lio/ballerina/runtime/api/Module;)V
        at ballerina.io.1.types.$_object_types.$populate$type$ReadableTextRecordChannel(Unknown Source)
        at ballerina.io.1.types.$_types.$createTypes(Unknown Source)
        at ballerina.io.1.$_init.$currentModuleInit(io)
        at ballerina.io.1.$configurationMapper.$initAndPopulateConfigData(Unknown Source)
        at $configurationMapper.$configureInit(Unknown Source)
        at $_init.main(.)
```

**Comment by rdulmina** [comment]
> 

This was an issue with my machine. Please ignore this

**Comment by rdulmina** [comment]
> ```ballerina
> public function main() {
>     var y = base16 `aa`;
>     io:println(typeof y);
> }
> ```
> 
> Gives
> 
> ```
> java.lang.NoSuchMethodError: io.ballerina.runtime.internal.types.BFunctionType.<init>([Lio/ballerina/runtime/api/types/Parameter;Lio/ballerina/runtime/api/types/Type;Lio/ballerina/runtime/api/types/Type;JLjava/lang/String;Lio/ballerina/runtime/api/Module;)V
>         at ballerina.io.1.types.$_object_types.$populate$type$ReadableTextRecordChannel(Unknown Source)
>         at ballerina.io.1.types.$_types.$createTypes(Unknown Source)
>         at ballerina.io.1.$_init.$currentModuleInit(io)
>         at ballerina.io.1.$configurationMapper.$initAndPopulateConfigData(Unknown Source)
>         at $configurationMapper.$configureInit(Unknown Source)
>         at $_init.main(.)
> ```
This was an issue with my machine. Please ignore this

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 22 above)
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:5694]: I have added the tests https://github.com/ballerina-platform/ballerina-lang/pull/37326/commits/a41828e66acf222373ef93deff481bde6310fd77#diff-89e951111e34a1e3e40867f8a556b114058af07b90a1b14449a4936b82f8d991R59

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 24]
```diff
@@ -1760,6 +1760,17 @@ private boolean isValidContextForInferredArray(BLangNode node) {
...
+            case LIST_CONSTRUCTOR_EXPR:
+                return true;
+            case GROUP_EXPR:
+                return isValidVariableForInferredArray(((BLangGroupExpr) node).expression);
+        }
```
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1770]: I will check that

[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1774]: Updated cde499c34356392cb2d153ab027c89ed38d376f9

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 21 above)
[the remark this answers is not in the document]
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1765]: Updated cde499c34356392cb2d153ab027c89ed38d376f9

File: tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-array-value-negative.bal [hunk 25]
```diff
@@ -17,3 +17,24 @@ function base64InvalidLiteralTest() {
...
+    int[*] e = base16 `aa bb`;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-array-value-negative.bal:26]: Where are the positive tests for code like this?

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-array-value-negative.bal:26]: Because `int[*] e = base16 `aa bb`;` wasn't allowed previously we need to add tests both compile-time and runtime.

```ballerina
    int[*] a = base16 `aa bb`;
    int[2] _ = a; // valid

    int[] c = a;
    assertTrue(c is int[2]);
    assertEquals([170, 187], c);
```

Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/byte/byte-array-value-negative.bal:26]: Added 2f291be6edca1a2f2fe039e7a7c1b302f16a2ebe

**Review by pcnfernando — APPROVED** [review]
LGTM
