### PR TITLE
Start listening phase even when listeners are only in imported modules

### LINKED ISSUE #41667: [Bug]: Listening phase does not start when listeners are available only in imported modules
### Description

Listening phase does not start when listeners are available only in imported modules.

With https://github.com/ballerina-platform/ballerina-lang/pull/41510/commits/7aff2ff2827b3cb8ffeacec428dd72b48a7c4877 it will work when the code is compiled for the first time (without using BIR cache). But the problem will exist when the code is compiled using the BIR cache because both the `packageSymbol.bir` and `importPkgSymbol` will be `null`.

### Steps to Reproduce

Without using any Ballerina libraries, the issue can be reproduced as follows.
1. Clean `.Ballerina` folder.
2. Extract the Ballerina package. 
[test_listener_non_default.zip](https://github.com/ballerina-platform/ballerina-lang/files/13304159/test_listener_non_default.zip)
3. Run `bal clean`, `bal pack`, and `bal push --repository local` for the above package.
4. Extract the Ballerina package. 
[use_listener.zip](https://github.com/ballerina-platform/ballerina-lang/files/13304168/use_listener.zip)
5. Run `bal run`  for the above package. It should hang in the listening phase until `SIGINT` is received.

### Issue with http listeners is illustrated below.
1. Run `bal clean`, `bal pack`, and `bal push --repository local` for a Ballerina package with below service.
```bal
import ballerina/http;

listener http:Listener httpListener = new (8080);

service / on httpListener {
    resource function get greeting() returns string { 
        return "Hello, World!"; 
    }
}
```
Ballerina.toml
```
[package]
org = "nadeeshand"
name = "httpservice"
version = "0.1.0"

[build-options]
observabilityIncluded = true
```
2. Create another bal package with below code and run it. It does not go to the listening phase when the code is compiled from BIR cache. If the listener is in a non-default module I think it will not work in the first time compilation also.
```bal
import nadeeshand/httpservice as _;
```
Ballerina.toml
```
[package]
org = "nadeeshand"
name = "usehttpservice"
version = "0.1.0"


[[dependency]]
org = "nadeeshand"
name = "httpservice"
version = "0.1.0"
repository = "local"

[build-options]
observabilityIncluded = true
```

### Affected Version(s)

2201.7.3

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #41667

Created https://github.com/ballerina-platform/ballerina-library/issues/5836 to add a test.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by HindujaB — APPROVED** [review]
LGTM

**Review by gabilang — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java [hunk 1]
```diff
@@ -810,8 +811,17 @@ private BIRFunction getFunction(BIRPackage module, String funcName) {
...
-        if (packageSymbol.bir != null && packageSymbol.bir.isListenerAvailable) {
-            return true;
+        if (packageSymbol.bir == null) {
+            for (Scope.ScopeEntry entry : packageSymbol.scope.entries.values()) {
+                BSymbol symbol = entry.symbol;
+                if (symbol != null && Symbols.isFlagOn(symbol.flags, Flags.LISTENER)) {
+                    return true;
+                }
+            }
+        } else {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmPackageGen.java:821]: Shall we merge else and if

**Review by warunalakshitha — APPROVED** [review]
LGTM
