### PR TITLE
Fix references in test resources and doc generation issues

### LINKED ISSUE #9862: VSCode plugin doesn't infer the correct value for named parameter, when showing the function call skeleton
**Description:**
$subject

**Steps to reproduce:**
I spotted this issue while testing the db clients.

1. Define a db endpoint
```ballerina
endpoint jdbc:Client testDB {
    url: "jdbc:mysql://localhost:3306/testdb",
    username: "root",
    password: "root",
    poolOptions: { maximumPoolSize:5 }
};
```

type following manually,
```ballerina
var ret = testDB1->
```
and choose the ```select``` operation from the VSCode plugin suggestions.

Following will be added
```ballerina
var ret = testDB1->select(sqlQuery, recordType, loadToMemory = recordType)
```
where as the correct statement should have been as follows.
```ballerina
var ret = testDB1->select(sqlQuery, recordType, loadToMemory = false)
```

**Affected Versions:**
0.980.2-SNAPSHOT
**OS, DB, other environment details and versions:**
Ubuntu 14.04

### LINKED ISSUE #11197: Missing namespace declaration suggestion in Service body scope
**Description:**
According to the Ballerina Grammar, Namespace declaration is allowed within the service body. Currently, the LS does not suggest the xml namespace snippet

**Affected Versions:**
v0.983.0 at least

### LINKED ISSUE #11265: References, Go to Definition and Rename does not work in test sources
**Description:**
Try to execute the operations of references, rename and go to definition from test sources ad you'll see the operations are not working.

**Affected Versions:**
v0.983.0 at least

### PR DESCRIPTION
**Pull request by nadeeshaan**

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/references/ReferencesTreeVisitor.java [hunk 1]
```diff
@@ -101,11 +103,15 @@ public ReferencesTreeVisitor(LSServiceOperationContext context) {
 
     @Override
     public void visit(BLangPackage pkgNode) {
-        if (pkgNode.topLevelNodes.isEmpty()) {
+        List<TopLevelNode> topLevelNodes = new ArrayList<>(pkgNode.topLevelNodes);
+        if (!pkgNode.testablePkgs.isEmpty()) {
```
Comment (NatashaWso2) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/references/ReferencesTreeVisitor.java]: Instead of checking if the testable package list is empty shall we use the method already used to check if a testable package exist or not 'containsTestablePkg()' given in  https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangPackage.java#L226?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/references/ReferencesTreeVisitor.java [hunk 2]
```diff
@@ -101,11 +103,15 @@ public ReferencesTreeVisitor(LSServiceOperationContext context) {
...
+            topLevelNodes.addAll(pkgNode.testablePkgs.get(0).topLevelNodes);
```
Comment (NatashaWso2) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/references/ReferencesTreeVisitor.java]: Even when getting the testable package we can reuse this method: https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangPackage.java#L217?

File: language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/definition/DefinitionTest.java [hunk 3]
```diff
@@ -48,74 +51,34 @@ public void init() throws Exception {
...
-                        + " and position line:" + position.getLine() + " character:" + position.getCharacter());
-    }
-
-    @Test(description = "Test goto definition for records", dataProvider = "recordPositions")
-    public void definitionForRecordsTest(Position position, DefinitionTestDataModel dataModel)
-            throws InterruptedException, IOException {
-        Assert.assertEquals(TestUtil.getDefinitionResponse(dataModel.getBallerinaFilePath(), position, serviceEndpoint),
-                getExpectedValue(dataModel.getExpectedFileName(), dataModel.getDefinitionFileURI()),
+    
+    @Test(description = "Test Go to Definitions", dataProvider = "definitionsDataProvider")
```
Comment (NatashaWso2) [inline language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/definition/DefinitionTest.java]: Shall we make "Go to Definitions" lowercase as "goto definitions"?

File: language-server/modules/langserver-core/src/test/resources/definition/test.definition.pkg/tests/test1.bal [hunk 4]
```diff
@@ -0,0 +1,33 @@
+import ballerina/io;
```
Comment (NatashaWso2) [inline language-server/modules/langserver-core/src/test/resources/definition/test.definition.pkg/tests/test1.bal]: Shall we add the license header?

File: language-server/modules/langserver-core/src/test/resources/references/project/pkg1/tests/test1.bal [hunk 5]
```diff
@@ -0,0 +1,33 @@
+import ballerina/io;
```
Comment (NatashaWso2) [inline language-server/modules/langserver-core/src/test/resources/references/project/pkg1/tests/test1.bal]: Shall we add the license header?

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/test/resources/references/project/pkg1/tests/test1.bal]: This is only a test source since we neglect the license header

File: language-server/modules/langserver-core/src/test/resources/definition/test.definition.pkg/tests/test1.bal (hunk 4 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/test/resources/definition/test.definition.pkg/tests/test1.bal]: Only a test source
