### PR TITLE
Fix a compound assignment issue in function calling

### LINKED ISSUE #15459: A bug in compound operator implementation
Consider the following code snippet:

```ballerina
a[f(i)] += y;
```
Here `f(i)` is not a side-effect free function. When I run this code, `f(i)` is executed twice. That is a bug.

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose
Fixes #15459

## Approach
If my compound assignment is ```a[f(1, foo)][3][2] += y```, index expressions should be extracted and evaluated them separately. Finally, create a block statement as follows.
```
var $temp3$ = a[f(1, foo)];
var $temp2$ = 3;
var $temp1$ = 2;
a[$temp3$][$temp2$][$temp1$] = a[$temp3$][$temp2$][$temp1$] + y;
```
## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -2328,21 +2328,77 @@ public void visit(BLangXMLNS xmlnsNode) {
...
+                statements.add(tempIndexVarDef);
+                varRef.add(tempVarRef);
+                type.add(indexBasedAccess.type);
+
+                if (indexBasedAccess.expr.getKind() == NodeKind.INDEX_BASED_ACCESS_EXPR) {
+                    indexBasedAccess = (BLangIndexBasedAccess) indexBasedAccess.expr;
+                    continue;
+                }
+                break;
+            } while (true);
```
Comment (irshadnilam) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Is there a workaround for us to not use `while(true)`?
How about something as follows?
```
do {
// do the casting somewhere here

} while(indexBasedAccess.expr.getKind() == NodeKind.INDEX_BASED_ACCESS_EXPR);
```

@MaryamZi  thoughts? is it okay using `while(true)` here?

**Comment by KavinduZoysa** [comment]
> Shall we add a test case (jballerina-unit-tests) for this scenario?

Yes, unit tests are added.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 1 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Yes, the condition to check is whether the current var ref is a index based access expr. No need for a do-while.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 2]
```diff
@@ -2328,21 +2328,78 @@ public void visit(BLangXMLNS xmlnsNode) {
...
-            varRef = ASTBuilderUtil.createVariableRef(compoundAssignment.varRef.pos, varRef.symbol);
-            varRef.lhsVar = true;
-        }
+            // Create the index access expression. ex: c[$temp3$][$temp2$][$temp1$]
+            BLangVariableReference var = (BLangVariableReference) indexBasedAccess.expr;
+            for (int ref = varRef.size() - 1; ref >= 0; ref--) {
+                var = ASTBuilderUtil.createIndexAccessExpr(var, varRef.get(ref));
+                var.type = type.get(ref);
+            }
+            var.type = compoundAssignment.varRef.type;
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: What's the purpose of the above code block? The variable `var` seems to be used as a temporary placeholder. Only the final value assigned to `var` seems to be significant?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 3]
```diff
@@ -2328,21 +2328,78 @@ public void visit(BLangXMLNS xmlnsNode) {
...
+            // var $temp1$ = 2;
+            // var $temp2$ = 3;
+            // var $temp3$ = a[f(1, foo)];
+            do {
+                indexExprNumber += 1;
+                BLangSimpleVariableDef tempIndexVarDef = createVarDef("$temp" + indexExprNumber + "$",
+                        indexBasedAccess.indexExpr.type, indexBasedAccess.indexExpr, compoundAssignment.pos);
+                BLangSimpleVarRef tempVarRef = ASTBuilderUtil.createVariableRef(tempIndexVarDef.pos,
+                        tempIndexVarDef.var.symbol);
+                statements.add(tempIndexVarDef);
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: If we keep adding to the 0-th index, we won't have to reverse the list at the end.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment.bal [hunk 4]
```diff
@@ -290,3 +290,65 @@ function testCompoundAssignmentAdditionWithRecordAccess() returns int {
     x += (ibm["count"] + arr[0]);
     return x;
 }
+
+function testCompoundAssignmentAdditionArrayElementFunctionInvocation() returns [int, int, int] {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment.bal]: Can we also add tests where the execution order of the nested indices matter?

For example, for something like
```ballerina
i[foo()][bar()] += 3
```

a test where we validate that foo() is executed first and then bar() ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 5]
```diff
@@ -2328,21 +2328,78 @@ public void visit(BLangXMLNS xmlnsNode) {
...
+            List<BLangSimpleVarRef> varRef = new ArrayList<>();
+            List<BType> type = new ArrayList<>();
+
+            BLangIndexBasedAccess indexBasedAccess = (BLangIndexBasedAccess) compoundAssignment.varRef;
+            // Extract the index Expressions from compound assignment and create variable definitions. ex:
+            // var $temp1$ = 2;
+            // var $temp2$ = 3;
+            // var $temp3$ = a[f(1, foo)];
+            do {
+                indexExprNumber += 1;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Even though this works atm, shouldn't this be a global variable instead? We might be reusing the same variable names with compound assignments if there are multiple being rewritten within the same block.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Instead of L2358-L2362 can we do something like
- `BLangExpression expr = compoundAssignment.varRef;` at the very beginning 
- `expr = compoundAssignment.varRef;` instead of L2358-L2362
- update the check in while to `while (expr.getKind() == NodeKind.INDEX_BASED_ACCESS_EXPR);`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 2 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Sorry, ignore the above comment. Misread the code block here :D

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment.bal (hunk 4 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment.bal]: Fixed

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java [hunk 6]
```diff
@@ -154,6 +154,59 @@ public void testCompoundAssignmentDivisionArrayElement() {
         Assert.assertEquals(((BInteger) returns[0]).intValue(), 10);
     }
 
+    @Test(description = "Test compound assignment with addition on array element where the index is an invocation.")
+    public void testCompoundAssignmentAdditionArrayElementFunctionInvocation() {
+        BValue[] returns = BRunUtil.invoke(result,
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java]: Fixed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 7]
```diff
@@ -2328,21 +2328,78 @@ public void visit(BLangXMLNS xmlnsNode) {
...
-        BLangAssignment assignStmt = (BLangAssignment) TreeBuilder.createAssignmentNode();
-        assignStmt.pos = compoundAssignment.pos;
-        BLangVariableReference varRef = compoundAssignment.varRef;
+        // If compound Assignment is an index based expression such as a[f(1, foo)][3][2] += y,
+        // should return a block statement which is equivalent to
+        // var $temp1$ = 2;
+        // var $temp2$ = 3;
+        // var $temp3$ = a[f(1, foo)];
+        // a[$temp3$][$temp2$][$temp1$] = a[$temp3$][$temp2$][$temp1$] + y;
+        if (compoundAssignment.varRef.getKind() == NodeKind.INDEX_BASED_ACCESS_EXPR) {
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: It is changed according to the suggestion.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 8]
```diff
@@ -2328,21 +2328,78 @@ public void visit(BLangXMLNS xmlnsNode) {
     }
 
     public void visit(BLangCompoundAssignment compoundAssignment) {
-        BLangAssignment assignStmt = (BLangAssignment) TreeBuilder.createAssignmentNode();
-        assignStmt.pos = compoundAssignment.pos;
-        BLangVariableReference varRef = compoundAssignment.varRef;
+        // If compound Assignment is an index based expression such as a[f(1, foo)][3][2] += y,
+        // should return a block statement which is equivalent to
+        // var $temp1$ = 2;
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Fixed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 3 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Fixed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 1 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: If we change the code according to the above suggestion, the last expression does not go through the logic.
ex: Let's consider the first expression is `c[f(1, foo)][1][2]`. After two iterations, according to this `expr = compoundAssignment.varRef;` the expression becomes `c[f(1, foo)]`. According to the check inside the **while**, execution exits from the loop and `c[f(1, foo)]` does not execute. But `c[f(1, foo)]` should go through the loop.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 9]
```diff
@@ -2328,21 +2328,78 @@ public void visit(BLangXMLNS xmlnsNode) {
...
+            BLangAssignment assignStmt = ASTBuilderUtil.createAssignmentStmt(compoundAssignment.pos, var,
+                    rhsExpression);
+
+            statements.add(assignStmt);
+            // Create block statement. ex: var $temp3$ = a[f(1, foo)];var $temp2$ = 3;var $temp1$ = 2;
+            // a[$temp3$][$temp2$][$temp1$] = a[$temp3$][$temp2$][$temp1$] + y;
+            BLangBlockStmt bLangBlockStmt = ASTBuilderUtil.createBlockStmt(compoundAssignment.pos, statements);
+            result = rewrite(bLangBlockStmt, env);
+        } else {
+            BLangVariableReference varRef = compoundAssignment.varRef;
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Fixed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 5 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Fixed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 1 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Please ignore the above comment. Misread the suggestion. Changed the code according to the suggestion.

**Comment by SupunS** [comment]
@MaryamZi 
> Wondering if we should avoid doing this, and define a variable only for non-literal and non-var ref scenarios?

+1 if possible. But can be a bit tricky. eg:
```ballerina 
a[index][getSecondIndex()] += 1;

function getSecondIndex() returns int {
    index +=1;
    return index;
}
```

**Comment by MaryamZi** [comment]
> @MaryamZi
> 
> > Wondering if we should avoid doing this, and define a variable only for non-literal and non-var ref scenarios?
> 
> +1 if possible. But can be a bit tricky. eg:
> 
> ```ballerina
> a[index][getSecondIndex()] += 1;
> 
> function getSecondIndex() returns int {
>     index +=1;
>     return index;
> }
> ```

Yeah, this would be an issue. 

I guess we can go ahead with the current implementation, unless we want to do this at least for literals. Not sure how much of a gain that would be.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 10]
```diff
@@ -286,6 +286,7 @@
     private int errorCount = 0;
     private int annonVarCount = 0;
     private int initFuncIndex = 0;
+    private int indexExprNumber = 0;
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Changed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 11]
```diff
@@ -2328,21 +2329,71 @@ public void visit(BLangXMLNS xmlnsNode) {
...
+        // var $temp3$ = a[f(1, foo)];
+        // var $temp2$ = 3;
+        // var $temp1$ = 2;
+        // a[$temp3$][$temp2$][$temp1$] = a[$temp3$][$temp2$][$temp1$] + y;
+        List<BLangStatement> statements = new ArrayList<>();
+        List<BLangSimpleVarRef> varRefs = new ArrayList<>();
+        List<BType> types = new ArrayList<>();
+
+        // Extract the index Expressions from compound assignment and create variable definitions. ex:
+        // var $temp1$ = 2;
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: I think we need a comment here because it explains the purpose of loop and corrected the comment.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 12]
```diff
@@ -2328,21 +2329,71 @@ public void visit(BLangXMLNS xmlnsNode) {
...
+        // var $temp2$ = 3;
+        // var $temp3$ = a[f(1, foo)];
+        do {
+            indexExprNumber += 1;
+            BLangSimpleVariableDef tempIndexVarDef = createVarDef("$temp" + indexExprNumber + "$",
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Changed.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment.bal [hunk 13]
```diff
@@ -290,3 +290,90 @@ function testCompoundAssignmentAdditionWithRecordAccess() returns int {
...
+}
+
+function testCompoundAssignmentSubtractionArrayElementFunctionInvocation() returns [int, int, int] {
+    var x = 5;
+    Girl girl = {};
+    Boy boy = {};
+    int[][][] b = [[[1, 2, 3], [3, 2, 1], [3, 2, 1]], [[10, 20, 30], [30, 20, 10], [30, 20, 10]],
+    [[5, 6, 7], [7, 6, 5], [7, 6, 5]]];
+
+    b[f(1, girl)][2][g(0, boy)] -= x;
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/compoundassignment/compound_assignment.bal]: Changed.
