### PR TITLE
Fix issues in bal init command

### LINKED ISSUE #38473: [Bug]: "bal init ." can result in invalid package name
### Description

When I run `bal init .` it will create a package with "." as the package name. This will result in a package where most of the tooling will not work. We should probably validate this and not allow "." as the package name for bal init. 

Also suggest to change the help text to "Initialize a Ballerina package inside the current directory" instead of  "Create a new Ballerina package inside the current  directory" which gives a different meaning.
```
NAME
       ballerina-init - Initialize a Ballerina package inside the current directory

``` 

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Other Area

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by ShammiL**
Fixes #38473

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java [hunk 1]
```diff
@@ -721,7 +722,9 @@ public static void checkExecutePermission(Path path) {
 
     private static boolean validateDotSeparatedIdentifiers(String identifiers) {
         Matcher m = separatedIdentifierPattern.matcher(identifiers);
-        return m.matches();
+        Matcher mm = onlyDotsPattern.matcher(identifiers);
```
Comment (Dilhasha) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java:725]: Have we verified whether this change has no impact on other places where this util is being used?

Comment (ShammiL) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java:725]: Other places where this is used validates either the package names or the module names. So this change will prevent `.` from being used as a package name or a module name.

**Review by Dilhasha — APPROVED** [review]
