### PR TITLE
Avoid trying to obtain generated keys in Oracle/SQL Server batch update / Remove BallerinaException usages

### LINKED ISSUE #18434: Oracle Batch update fails when multiple batches are present
**Description:**
$Subject. 

This seems to be because Oracle does not support using getGeneratedKeys() in conjunction with addBatch()/executeBatch(). [1] [2].

This is a regression issue of https://github.com/ballerina-platform/ballerina-lang/pull/17056/ which resolves https://github.com/ballerina-platform/ballerina-lang/issues/16986

[1] https://arstechnica.com/civis/viewtopic.php?f=20&t=1425043
[2] https://docs.oracle.com/database/121/JJDBC/jdbcvers.htm#JJDBC28099

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Manuri**
## Purpose
Fixes #18434

Replace BallerinaExeception with ErrorValue in table/json related source.

### CODE REVIEW

File: stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java [hunk 1]
```diff
@@ -84,7 +84,13 @@ public BatchUpdateStatement(ObjectValue client, SQLDatasource datasource, String
         String errorMessagePrefix = "Failed to execute batch update";
         try {
             conn = getDatabaseConnection(strand, client, datasource);
-            stmt = conn.prepareStatement(query, PreparedStatement.RETURN_GENERATED_KEYS);
+            boolean returningGeneratedKeys = false;
```
Comment (anupama-pathirage) [inline stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java]:
```suggestion
            boolean generatedKeyReturningSupported = isGeneratedKeyReturningSupported();
```

File: stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java [hunk 2]
```diff
@@ -141,6 +149,15 @@ public BatchUpdateStatement(ObjectValue client, SQLDatasource datasource, String
         }
     }
 
+    // It has been identified that Oracle does not support returning generated keys along with batch update.
```
Comment (anupama-pathirage) [inline stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java]:
```suggestion
    // It has been identified that Oracle and MS SQL Server does not support returning generated keys along with batch update.
```
