### PR TITLE
Fix never frame assignment throwing `NoSuchField` error

### LINKED ISSUE #42408: [Bug]: Test failure with `NoSuchFieldError` for latest lang master in `kafka`
### Description

The following exception is thrown when running the kafka module tests using GraalVM. 
```
[2024-03-26 04:34:00,580] SEVERE {b7a.log.crash} - ballerinax.kafka$test.3.frames.$frame$transactionalProducerWithAbortTest._371 
java.lang.NoSuchFieldError: ballerinax.kafka$test.3.frames.$frame$transactionalProducerWithAbortTest._371
	at ballerinax.kafka$test.3.tests.producer_client_tests.transactionalProducerWithAbortTest(tests/producer_client_tests.bal:268)
	at ballerinax.kafka$test.3.tests.test_execute-generated_1.transactionalProducerWithAbortTest$lambda142$(tests/test_execute-generated_1.bal:146)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:320)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:287)
	at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
 

	transactionalProducerWithAbortTest has failed.
```
Failed workflow - https://github.com/ballerina-platform/module-ballerinax-kafka/actions/runs/8425199587/job/23070739985#step:10:940

Related test case - https://github.com/ballerina-platform/module-ballerinax-kafka/blob/master/ballerina/tests/producer_client_tests.bal#L221

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes #42408

## Approach
The bug is introduced from https://github.com/ballerina-platform/ballerina-lang/pull/42150 PR. This loads the `never` type frame value into an XML variable. This causes the runtime failure. This PR corrects it by loading `never` typed variable differently.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java [hunk 1]
```diff
@@ -754,6 +754,9 @@ private void generateFrameClassFieldLoad(List<BIRVariableDcl> localVars, MethodV
                 mv.visitFieldInsn(GETFIELD, frameName, localVar.jvmVarName,
                         GET_BSTRING);
                 mv.visitVarInsn(ASTORE, index);
+            } else if (bType.tag == TypeTags.NEVER) {
+                mv.visitFieldInsn(GETFIELD, frameName, localVar.jvmVarName, GET_OBJECT);
+                mv.visitVarInsn(ASTORE, index);
```
Comment (gabilang) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:759]: Shall we move this into `generateFrameClassFieldLoadByTypeTag` method?

Comment (HindujaB) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:759]: We already had such an implementation. The issue happens when we call `isAssignable()` on the XML type tag which returns true to the `never` type. Therefore I moved the `never` check before the XML check.

**Review by gabilang — APPROVED** [review]
