### PR TITLE
Fix http import package as alias

### LINKED ISSUE #9614: Issue in importing http package with alias name
**Description:**
Can not import the `ballerina/http` package with an alias name

**Steps to reproduce:**
Run the following ballerina service
```ballerina
import ballerina/http as network;

service<network:Service> hello bind { port:9090 } {

    // The 'Request' object comes from the imported package.
    sayHello (endpoint caller, network:Request req) {

    }
}
```

### PR DESCRIPTION
**Pull request by Anoukh**
This PR will fix an issue in using an alias to import http package.
Fixes #9614

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/HttpFiltersDesugar.java [hunk 1]
```diff
@@ -201,6 +206,21 @@ private BLangVariable addFilterContextCreation(BLangResource resourceNode, Symbo
...
 
+    /**
+     * Get the alias name of the http import
+     *
+     * @param env the symbol environment.
+     * @return the alias name.
+     */
+    private String getPackageAlias(SymbolEnv env) {
+        AtomicReference<String> aliasName = new AtomicReference<>(PACKAGE_NAME);
+        Optional<BLangImportPackage> importPackage = ((BLangPackage) env.enclEnv.node).imports.stream()
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/HttpFiltersDesugar.java]: we should get, env.enclPkg instated of env.enclEnv.node
