### PR TITLE
 Port bdd diff fixes to JBallerina #34358 

### LINKED ISSUE #34358: Port bdd diff fixes to JBallerina
Port the fix for https://github.com/ballerina-platform/nballerina/issues/757
https://github.com/ballerina-platform/nballerina/commit/431467607feb484f585263984c6362dcba2eb3f2 and https://github.com/ballerina-platform/nballerina/commit/a1bacb4381005e6bccc8593b8660a892ee5edf61

### PR DESCRIPTION
**Pull request by ushirask**
Fixes #34358 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: semtypes/src/main/java/io/ballerina/types/typeops/BddCommonOps.java [hunk 1]
```diff
@@ -119,12 +119,16 @@ public static Bdd bddDiff(Bdd b1, Bdd b2) {
...
-                // but correct in the Castagna paper
+                // There is an error in the Castagna paper for this formula.
+                // The union needs to be materialized here.
+                // The original formula does not work in a case like (a0|a1) - a0.
+                // Castagna confirms that the following formula is the correct one.
                 return bddCreate(((BddNode) b1).atom,
-                        bddDiff(((BddNode) b1).left, ((BddNode) b2).left),
-                        bddDiff(((BddNode) b1).middle, ((BddNode) b2).middle),
-                        bddDiff(((BddNode) b1).right, ((BddNode) b2).right));
+                        bddDiff(bddUnion(((BddNode) b1).left, ((BddNode) b1).middle),
```
Comment (ushirask) [inline semtypes/src/main/java/io/ballerina/types/typeops/BddCommonOps.java:127]: @rdhananjaya should we use bddNode local variables here (and in other bdd common ops) to avoid multiple casts and improve readability?

Comment (rdhananjaya) [reply semtypes/src/main/java/io/ballerina/types/typeops/BddCommonOps.java:127]: +1, can we all them `bdd1`, `bdd2`

**Comment by rdhananjaya** [comment]
Can we also port the test using subtype relationship tests https://github.com/ballerina-platform/nballerina/commit/431467607feb484f585263984c6362dcba2eb3f2#diff-77e9f7903827c34fe73d2d03eb24457b467b7edc8b986c3e90c58e06b66b6ee4R3
