### PR TITLE
[WebSub] Make the subscriber path optional and fix issues with custom subscriber services

### LINKED ISSUE #17261: Invalid parameter type error is thrown for a valid type
**Description:**
`error: invoking main method failed due to org.ballerinalang.util.exceptions.BallerinaException: Invalid parameter type tharindu/githubwebhook3:0.1.0:PushEvent in resource onPush. Requires githubwebhook3:PushEvent`

Above error occurs when running the following code.

```
import githubwebhook3;
import ballerina/http;
import ballerina/io;
import ballerina/oauth2;
import ballerina/websub;

githubwebhook3:Listener githubListener = new (8080);

// following globle variables are added as a workaround until annotaions can take local variables
string _topic = "";
boolean isStarted = false;

oauth2:OutboundOAuth2Provider _oauth2Provider = new ({
    accessToken: ""
});
http:BearerAuthHandler _oauth2Handler = new (_oauth2Provider);

public function startWebhook(string topic, string secret, string token) {

    _topic = topic;

    oauth2:OutboundOAuth2Provider oauth2Provider = new ({
        accessToken: token
    });
    http:BearerAuthHandler oauth2Handler = new (oauth2Provider);

    _oauth2Handler = oauth2Handler;

    service ss = @websub:SubscriberServiceConfig {
        path: "/",
        subscribeOnStartUp: true,
        target: [githubwebhook3: HUB, _topic],
        secret: "<SECRET>",
        callback: "https://00025cd0.ngrok.io",

        hubClientConfig: {
            auth: {
                authHandler: _oauth2Handler
            }
        }
    }
    @websub:SpecificSubscriber
    service {
        resource function onPush(websub:Notification notification, githubwebhook3:PushEvent event) {
            io:println("[onPush] pushed by: ", event.sender);
        }
    };

    checkpanic githubListener.__attach(ss);
    if (isStarted == false) {
        isStarted = true;
        checkpanic githubListener.__start();
    }

}

public function main() {
    startWebhook("https://github.com/my/myrepo/events/*.json", "", "mytoken");
}
```

The error is thrown from `validateStructType` method in `org.ballerinalang.net.websub.WebSubSubscriberServiceValidator` class in `ballerina-lang`.

**Affected Versions:**
0.992.0-m2-SNAPSHOT

### LINKED ISSUE #17388: [WebSub] Optional path in SubscriberServiceConfiguration
**Description:**
Atm, the `path` field in the WebSub SubscriberServiceConfiguration annotation is a required field. Instead, we could do something like we've done for HTTP (default path, service name).

**Affected Versions:**
1.0-alpha

### LINKED ISSUE #17563: Cannot define an `onIntentVerification` resource in custom subscriber services
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/http;
import ballerina/io;
import ballerina/websub;
import ballerina/'lang\.object as lang;

const string MOCK_HEADER = "MockHeader";

public type WebhookListenerConfiguration record {
    string host = "";
};

public type MockActionEvent record {
    string action;
};

public type MockDomainEvent record {
    string domain;
};

@websub:SubscriberServiceConfig {
    path:"/key"
}
service keyWebhook on new WebhookServerForPayload(23585) {
    resource function onIntentVerification (websub:Caller caller, websub:IntentVerificationRequest verRequest) {
    }

    resource function onCreated(websub:Notification notification, MockActionEvent event) {
        io:println("Created Notification Received, action: ", event.action);
    }

    resource function onFeature(websub:Notification notification, MockDomainEvent event) {
        io:println("Feature Notification Received, domain: ", event.domain);
    }

    resource function onStatus(websub:Notification notification, MockActionEvent event) {
        // do nothing - test start up
    }
}

/////////////////// Specific Webhook for dispatching by key ///////////////////
public type WebhookServerForPayload object {

    *lang:AbstractListener;

    private websub:Listener websubListener;

    public function __init(int port, WebhookListenerConfiguration? config = ()) {
        websub:ExtensionConfig extensionConfig = {
            topicIdentifier: websub:TOPIC_ID_PAYLOAD_KEY,
            payloadKeyResourceMap: {
                "action" : {
                    "created" : ["onCreated", MockActionEvent],
                    "deleted" : ["onDeleted", MockActionEvent],
                    "statuscheck" : ["onStatus", MockActionEvent]
                },
                "domain" : {
                    "issue" : ["onIssue", MockDomainEvent],
                    "feature" : ["onFeature", MockDomainEvent]
                }
            }
        };
        string host = config is () ? "" : config.host;
        websub:SubscriberServiceEndpointConfiguration sseConfig = {
            host: host,
            extensionConfig: extensionConfig
        };
        self.websubListener = new(port, sseConfig);
    }

    public function __attach(service s, string? name = ()) returns error? {
        return self.websubListener.__attach(s, name);
    }

    public function __start() returns error? {
        return self.websubListener.__start();
    }

    public function __stop() returns error? {
        return self.websubListener.__stop();
    }
};
```

```cmd
$ ballerina run test.bal 
error: invoking main method failed due to error Invalid parameter type ballerina/websub:Caller in resource onIntentVerification. Requires ballerina/websub:Notification
```

**Affected Versions:**
1.0.0-alpha

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$title. 

Fixes #17261
Fixes #17388
Fixes #17563

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java [hunk 1]
```diff
@@ -108,63 +149,98 @@ static void validateCustomResources(List<HttpResource> resources, WebSubServices
...
         }
-        return true;
     }
 
-    private static void validateCustomParamNumber(List<BType> paramTypes, String resourceName) {
-        if (paramTypes == null || paramTypes.size() < CUSTOM_RESOURCE_PARAM_COUNT) {
-            throw BallerinaErrors.createError(String.format("Invalid param count for WebSub Resource \"%s\"",
-                                                            resourceName));
+    private static void validateCallerParam(BType paramVarType) {
+        boolean validIntentVerificationParam;
```
Comment (chamil321) [inline stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java]:
```suggestion
        boolean validCallerParam;
```

File: stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java [hunk 2]
```diff
@@ -108,63 +149,98 @@ static void validateCustomResources(List<HttpResource> resources, WebSubServices
...
+
+        if (paramVarType.getTag() != TypeTags.OBJECT_TYPE_TAG) {
+            validIntentVerificationParam = false;
```
Comment (chamil321) [inline stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java]:
```suggestion
            validCallerParam = false;
```

File: stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java [hunk 3]
```diff
@@ -108,63 +149,98 @@ static void validateCustomResources(List<HttpResource> resources, WebSubServices
...
+        } else {
+            BObjectType objectType = (BObjectType) paramVarType;
+            validIntentVerificationParam = objectType.getPackage().org.equals(BALLERINA) &&
```
Comment (chamil321) [inline stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java]:
```suggestion
            validCallerParam = objectType.getPackage().org.equals(BALLERINA) &&
```

File: stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java [hunk 4]
```diff
@@ -108,63 +149,98 @@ static void validateCustomResources(List<HttpResource> resources, WebSubServices
...
+                    objectType.getPackage().name.equals(WEBSUB) &&
+                    objectType.getName().equals(WEBSUB_SERVICE_CALLER);
+        }
+
+        if (!validIntentVerificationParam) {
```
Comment (chamil321) [inline stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java]:
```suggestion
        if (!validCallerParam) {
```

File: stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java [hunk 5]
```diff
@@ -108,63 +149,98 @@ static void validateCustomResources(List<HttpResource> resources, WebSubServices
...
-    private static void validateStructType(String resourceName, BLangSimpleVariable paramDetail, String packageName,
-                                           String structuralTypeName, String paramPosition, DiagnosticLog dlog) {
-        if (!(packageName.concat(":").concat(structuralTypeName)).equals((paramDetail.type).toString())) {
-            dlog.logDiagnostic(Diagnostic.Kind.ERROR, paramDetail.pos, "invalid resource signature for '" + resourceName
-                    + "', expected '" + packageName.concat(":").concat(structuralTypeName) + "' as " + paramPosition
-                    + " parameter");
+    private static void validateIntentVerificationParam(BType paramVarType) {
+        boolean validIntentVerificationParam;
+
+        if (paramVarType.getTag() != TypeTags.OBJECT_TYPE_TAG) {
```
Comment (chamil321) [inline stdlib/websub/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java]: Shall we move this param check in to a separate method and reuse in validation?

```
boolean validIntentVerificationParam = isValidSignatureParam(paramVarType, WEBSUB_INTENT_VERIFICATION_REQUEST);
```
