### PR TITLE
Fix `BAL_CONFIG_DATA` toml parsing not throwing parsing errors 

### LINKED ISSUE #40220: [Bug]: Fix `BAL_CONFIG_DATA` toml parsing not throwing parsing errors
### Description

$subject

### Steps to Reproduce

Currently, if we provide invalid TOML content through the Environment Variable, it throws `value not provided` errors for configurable instead of an `Invalid TOML content` error. 
This is deviant from the TOML file passing behavior. 

This is because we ignore the diagnostic logs from the Toml parser if we receive a valid toml node. 

### Affected Version(s)

current master

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject

Fixes #40220 

## Approach
Used the same logic we use to handle the toml parser errors.

## CheckList 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java [hunk 1]
```diff
@@ -127,15 +127,43 @@ public void testFileEnvVariableBasedConfigurable() throws BallerinaTestException
...
+        errorLeecher3.waitForText(5000);
+        errorLeecher4.waitForText(5000);
+        errorLeecher5.waitForText(5000);
+        errorLeecher6.waitForText(5000);
+        errorLeecher7.waitForText(5000);
+        errorLeecher8.waitForText(5000);
+        errorLeecher9.waitForText(5000);
+        errorLeecher10.waitForText(5000);
+        errorLeecher11.waitForText(5000);
+        errorLeecher12.waitForText(5000);
```
Comment (gabilang) [inline tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java:166]: Do we need 5s here for each? Can we reduce and see?

Comment (HindujaB) [reply tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java:166]: sure.
Even though, it says to wait for 5s, it will execute further once the log is received.

Comment (Nadeeshan96) [reply tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java:166]: I think then we can keep it like this because this will not get delayed due to the `5000` value, and we will have less intermittent failures due to high timeouts.

Comment (HindujaB) [reply tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java:166]: +1

**Review by warunalakshitha — APPROVED** [review]
Lets add these changes to breaking change in Release note.

**Review by Nadeeshan96 — APPROVED** [review]
LGTM

**Review by gabilang — APPROVED** [review]
