### PR TITLE
Preserve intersection type through the compiler phases insted of passing effective type

### LINKED ISSUE #38505: [Bug]: Incorrect type name for immutable types in error messages
### Description

```bal
function testInvalidReaodOnlyRecordUpdates() {
    Student & readonly b = {};
    b["details"] = 3;
}

public type Student record {|
    int details = 5;
|};

public type ReadOnlyStudent readonly & Student;
```
Gives `cannot update 'readonly' value of type 'ReadOnlyStudent'` ideally it should give `cannot update 'readonly' value of type '(Student & readonly)'`. This is because we maintain `symTable.immutableTypeMaps`. Need to revisit this

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39414: [Bug]: Inconsistent return type for `.typeDescriptor()` API for `TypeReferenceTypeSymbol` when it is `IntersectionTypeSymbol`
### Description

When I try to access the type descriptor for the intersection type faces inconsistent behaviour for the below scenarios:
Scenario 01:
```ballerina
public type ReturnValue02 readonly & string;
```
Accesse via:  **TypeSymbol typeSymbol = typeRef.typeDescriptor()**
Return value :  TypeSymbol is  `StringTypeSymbol`

Scenario 02
```ballerina
public type ReturnValue03 readonly & map<json>;

public type ReturnValue04 readonly & json;

public type ReturnValue05 readonly & xml;

public type ReturnValue06 readonly & error;

public type ReturnValue07 readonly & string[];
```
Accesse via:  **TypeSymbol typeSymbol = typeRef.typeDescriptor()**
Return value :  TypeSymbol is  `IntersectionTypeSymbol`

### Steps to Reproduce

Try to access the type descriptor for the below intersection types 
```ballerina
public type ReturnValue02 readonly & string;

public type ReturnValue03 readonly & map<json>;

public type ReturnValue04 readonly & json;

public type ReturnValue05 readonly & xml;

public type ReturnValue06 readonly & error;

public type ReturnValue07 readonly & string[];
```
Accesse via:  **TypeSymbol typeSymbol = typeRef.typeDescriptor()**

### Affected Version(s)

Ballerina 2201.3.2 (Swan Lake Update 3)

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

This issue is a blocker for the fix to this issue https://github.com/ballerina-platform/openapi-tools/issues/1151

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #40960: [Bug]: No error for assigning non-readonly `anydata` value for readonly `anydata` variable
### Description

Bellow programs compile without error and produces a wrong output

```bal
import ballerina/io;
public function main() {
    anydata a = [];
    anydata & readonly b = a; // Should be a compilation error.
    anydata[] array = <anydata[]>a;
    array.push(1);
    io:println(b);
}
```

Prints `[1]`

### Steps to Reproduce

_No response_

### Affected Version(s)

U7

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #41009: Preserve intersection type through the compiler
Preserve intersection type through the compiler

1. Remove `IntersectableReferenceType.java`.
2. Preserve intersection type through the compiler phases.
3. Handle intersection type via `getReferredType()`.
4. Add missing `getReferredType()` cases before type operations in compiler and runtime.

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
This PR will

1. Remove `IntersectableReferenceType.java`.
2. Preserve intersection type through the compiler phases.
3. Handle intersection type via `getReferredType()`.
4. Add missing `getReferredType()` cases before type operations in compiler and runtime.
5. Fix several existing bugs

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java [hunk 1]
```diff
@@ -154,8 +155,13 @@ public static boolean isSameType(Type sourceType, Type targetType) {
...
         if (type.getTag() == TypeTags.TYPE_REFERENCED_TYPE_TAG) {
-            constraint = getReferredType(((ReferenceType) type).getReferredType());
+            return getReferredType(((ReferenceType) type).getReferredType());
         }
+        
+        if (type.getTag() == TypeTags.INTERSECTION_TAG) {
+            return getReferredType(((IntersectionType) type).getEffectiveType());
+        }
+
         return constraint;
```
Comment (KavinduZoysa) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java:165]: This is not needed now.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 2]
```diff
@@ -1466,26 +1457,30 @@ public boolean isInherentlyImmutableType(BType type) {
...
             case TypeTags.XML:
-                return ((BXMLType) type).constraint.tag == TypeTags.NEVER;
-            case TypeTags.TYPEREFDESC:
-                return isInherentlyImmutableType(((BTypeReferenceType) type).referredType);
+                return getReferredType(((BXMLType) type).constraint).tag == TypeTags.NEVER;
         }
         return false;
     }
 
     public static BType getReferredType(BType type) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1465]: Is this name still accurate? It's no longer just referred type?

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1465]: any suggestions?

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Replaced with `getConclusiveType`

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 3]
```diff
@@ -2799,15 +2806,17 @@ private static boolean checkFiniteTypeAssignable(Object sourceValue, Type source
     protected static boolean isFiniteTypeValue(Object sourceValue, Type sourceType, Object valueSpaceItem,
                                                boolean allowNumericConversion) {
         Type valueSpaceItemType = getType(valueSpaceItem);
-        if (valueSpaceItemType.getTag() > TypeTags.DECIMAL_TAG) {
-            return valueSpaceItemType.getTag() == sourceType.getTag() &&
+        sourceType = TypeUtils.getReferredType(sourceType);
```
Comment (ushirask) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2809]: since `sourceType` is not directly used anywhere in this function shall we make a variable for `int sourceTypeTag = TypeUtils.getReferredType(sourceType).getTag();

Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2809]: Updated thanx

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/configschema/TypeConverter.java [hunk 4]
```diff
@@ -173,14 +182,13 @@ private JsonObject generateRecordType(BRecordType effectiveType) {
...
         // Get record type and set the type name as a property
-        if (effectiveType.getIntersectionType().isPresent()) {
-            for (BType bType : effectiveType.getIntersectionType().get().getConstituentTypes()) {
-                // Does not consider anonymous records
-                if (bType instanceof BTypeReferenceType) {
-                    typeNode.addProperty("name", bType.toString().trim());
-                }
+        for (BType bType : intersectionType.getConstituentTypes()) {
+            // Does not consider anonymous records
+            if (bType instanceof BTypeReferenceType) {
```
Comment (ushirask) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/configschema/TypeConverter.java:187]: Can't we check `TYPE_REFERENCED_TYPE_TAG` here?

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/configschema/TypeConverter.java]: Updated

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java [hunk 5]
```diff
@@ -143,19 +144,35 @@ public static Type getType(Object value) {
...
+    public static Type getConclusiveType(Type type) {
+        if (type.getTag() == TypeTags.TYPE_REFERENCED_TYPE_TAG) {
+            return getConclusiveType(((ReferenceType) type).getReferredType());
+        }
+        
+        if (type.getTag() == TypeTags.INTERSECTION_TAG) {
+            return getConclusiveType(((IntersectionType) type).getEffectiveType());
+        }
+
+        return type;
```
Comment (LakshanWeerasinghe) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/TypeUtils.java:176]:
```suggestion        
        if (type.getTag() == TypeTags.INTERSECTION_TAG) {
            return getConclusiveType(((IntersectionType) type).getEffectiveType());
        }

        return getReferredType(type);
```

**Review by gimantha — APPROVED** [review]
Merging to check if there are any build failures in downstream. We will be reviewing before merging to the master
