### PR TITLE
Fix minor issues with transaction log creation

### LINKED ISSUE #27920: Remove/Hide Atomikos startup message
**Description:**
$title

### PR DESCRIPTION
**Pull request by lasinicl**
Fixes #27920

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java [hunk 1]
```diff
@@ -126,7 +128,7 @@ public static TransactionResourceManager getInstance() {
      *
      */
     private void setLogProperties() {
-        final Path projectRoot = findProjectRoot(Paths.get(System.getProperty("user.dir")));
+        final Path projectRoot = Paths.get(System.getProperty(USER_DIR));
         if (projectRoot != null) {
             String logDir = getTransactionLogDirectory();
             String logPath = projectRoot.toAbsolutePath().toString() + File.separatorChar + logDir;
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java:134]: Better check !isAbsolute() and append else set the abosolute path

**Review by pcnfernando — CHANGES_REQUESTED** [review]

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java (hunk 1 above)
Comment (lasinicl) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java]: Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/27960/commits/720dd6d64bc0f6387f7ea1102ab8e848fe134718

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java [hunk 2]
```diff
@@ -74,8 +74,10 @@
             TRANSACTION_PACKAGE_VERSION, "onRollback");
     private static final String ATOMIKOS_LOG_BASE_PROPERTY = "com.atomikos.icatch.log_base_dir";
     private static final String ATOMIKOS_LOG_NAME_PROPERTY = "com.atomikos.icatch.log_base_name";
+    private static final String ATOMIKOS_REGISTERED_PROPERTY = "com.atomikos.icatch.registered";
     private static final String CONFIG_TRANSACTION_MANAGER_ENABLED = "b7a.transaction.manager.enabled";
     private static final String CONFIG_TRANSACTION_LOG_BASE = "b7a.transaction.log.base";
+    private static final String USER_DIR = "user.dir";
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java:80]: This property name should be available in runtime constants. Can you check. This is to avoid changes in multiple places

Comment (lasinicl) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java:81]: Fixed in 3d0adf2

Comment (pcnfernando) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java:81]: You don't need this const isn't it

Comment (lasinicl) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java]: yes. removed

**Review by pcnfernando — APPROVED** [review]
