### PR TITLE
Validate module name with regex

### LINKED ISSUE #18466: Error on invalid `ballerina pull` module could improve
**Description:**
$title.

**Steps to reproduce:**
```cmd
$ ballerina pull twitter
error: no module-name provided
```

The issue here is that the org name is missing. Would be better if we could say what the expected format is.

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-beta
Language specification 2019R3
Ballerina tool 1.0.0
```

### PR DESCRIPTION
**Pull request by suganyasuven**
Fixes #18466

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/UtilsTest.java [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+ * under the License.
+ */
+
+package org.ballerinalang.packerina.cmd;
+
+import org.testng.Assert;
+import org.testng.annotations.DataProvider;
+import org.testng.annotations.Test;
+
+/**
```
Comment (pramodya1994) [inline cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/UtilsTest.java]: Shall we add `@since` annotation?

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/PullCommand.java [hunk 2]
```diff
@@ -147,4 +153,12 @@ public void printUsage(StringBuilder out) {
     @Override
     public void setParentCmdParser(CommandLine parentCmdParser) {
     }
+
+    private String getPullCommandRegex() {
+        return MODULE_NAME_REGEX;
+    }
+
+    public boolean validateModuleName(String str) {
```
Comment (pramodya1994) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/PullCommand.java]:
```suggestion
    public boolean validModuleName(String str) {
```

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/PullCommand.java [hunk 3]
```diff
@@ -81,28 +83,32 @@ public void execute() {
...
-            orgName = resourceName.substring(0, orgNameIndex);
-            if (orgName.equals("ballerina")) {
-                throw LauncherUtils.createLauncherException("`Ballerina` is the builtin organization and its modules"
-                                                                    + " are included in the runtime.");
-            }
-        } else {
-            throw LauncherUtils.createLauncherException("no module-name provided");
+        if (!validateModuleName(resourceName)) {
+            CommandUtil.printError(outStream,
+                    "invalid module name. Provide the module name with the org name ",
```
Comment (pramodya1994) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/PullCommand.java]:
```suggestion
                    "invalid module name. provide the module name with the org name ",
```
Can you please check whether we are using Capital letters for warning commands.

Comment (suganyasuven) [reply cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/PullCommand.java]: Generally, the convention is to start with capital letters followed by a full stop for error messages.
