### PR TITLE
Fix issue when an object constructor is part of a type cast expression

### LINKED ISSUE #31646: Compiler crashes for anonymous record in a field initializer of an object constructor that is part of a type cast expression
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    var v = <object {}> object {
                function a = function () returns error? {
                    record {|
                        any x = 1;
                    |} r = {};
                };
    };    
}
```

```log
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:3651)
        at org.wso2.ballerinalang.compiler.tree.types.BLangRecordTypeNode.accept(BLangRecordTypeNode.java:42)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:394)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeTypeNode(CodeAnalyzer.java:404)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2519)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:394)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2616)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:394)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:574)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:394)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visitFunction(CodeAnalyzer.java:542)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:3616)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangLambdaFunction.accept(BLangLambdaFunction.java:59)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3983)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2521)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:394)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:422)
        at org.wso2.ballerinalang.compiler.tree.BLangClassDefinition.accept(BLangClassDefinition.java:106)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:394)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeTopLevelNodes(CodeAnalyzer.java:382)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:374)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyze(CodeAnalyzer.java:363)
        at io.ballerina.projects.internal.CompilerPhaseRunner.codeAnalyze(CompilerPhaseRunner.java:212)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:117)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:383)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:174)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
        at io.ballerina.projects.Package.getCompilation(Package.java:135)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:64)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:163)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Affected Versions:**
slbeta2

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fixes #31646 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [x] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -390,6 +390,13 @@ public BType checkExpr(BLangExpression expr, SymbolEnv env, BType expType, Diagn
         return resultType;
     }
 
+    private void analyzeNode(BLangNode node, SymbolEnv env) {
+        boolean prevNonErrorLoggingCheck = this.nonErrorLoggingCheck;
+        this.nonErrorLoggingCheck = false;
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:395]: Do we know why this fixes the issue when we set `this.nonErrorLoggingCheck = false;`?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:395]: Seems like this was done to make the lambda function be added in https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L4340 in the initial (non-logging) iteration. IMO, this is not correct. We shouldn't have to special case this.

Everywhere we do a non-error logging check, we eventually do an actual error logging check against some type. For the original issue with the cast, this should happen at https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L4319. And that is when the lambda function should get added.

But during that iteration, we don't seem to get to the point where the lambda function is added because we return at https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L360, which shouldn't be the case because in the previous (non-error logging) iterations we use a clone, so `expr.typeChecked` should be false here. This usually happens when the expression is not properly cloned. IMO, the correct fix is to fix that.

@chiranSachintha, can you please recheck?

**Review by MaryamZi — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:395]: In here https://github.com/ballerina-platform/ballerina-lang/blob/bab02a8fb3cfd11794e2394e1460b23ec0dfe115/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L8128 we are getting the class definitions from the pkg node. So when visiting exprs within that class definitions non-error logging check can be true due to previous expr. Due to that we need to set that variable(non-error logging) to false before visiting those class definitions. Isn't it?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:395]: If we are doing a check with `nonErrorLoggingCheck` set to true, until that check completes we don't/shouldn't set it to false. If we do, we are going against the expected behaviour. e.g., you set `nonErrorLoggingCheck` to true and do a compatibility check, but somewhere along the way if `nonErrorLoggingCheck` is changed to false, it will end up logging errors.

If you check the usage/assignments to `org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker#nonErrorLoggingCheck`, we don't explicitly set false to this anywhere (except in the changes in this PR), which guarantees the above.

 

> In here
> 
> https://github.com/ballerina-platform/ballerina-lang/blob/bab02a8fb3cfd11794e2394e1460b23ec0dfe115/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L8128
> 
> we are getting the class definitions from the pkg node. So when visiting exprs within that class definitions non-error logging check can be true due to previous expr. Due to that we need to set that variable(non-error logging) to false before visiting those class definitions. Isn't it?

I don't get why we need this. If someone sets `nonErrorLoggingCheck` to true they are expected to 
1. eventually do an error logging check
2. reset it to the previous state after the check (may be true or false)

File: tests/jballerina-unit-test/src/test/resources/test-src/types/var/var-type-assign-stmt.bal [hunk 2]
```diff
@@ -190,4 +190,32 @@ function testInCompatibleStructForceCasting() returns A|error {
     var a = check trap <A> b;
 
     return a;
-}
\ No newline at end of file
+}
+
+function testObjectToVarAssignment() returns boolean {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/var/var-type-assign-stmt.bal:195]: Let's also add a negative test with something like

```ballerina
    var v = <object {function a;}> object {
                function a = 1;
    };
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -390,6 +390,12 @@ public BType checkExpr(BLangExpression expr, SymbolEnv env, BType expType, Diagn
         return resultType;
     }
 
+    private void analyzeObjectConstructor(BLangNode node, SymbolEnv env) {
+        if (!nonErrorLoggingCheck) {
+            semanticAnalyzer.analyzeNode(node, env);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:395]: We need to handle other places where we call the semantic analyzer from the type checker too. Please check and create an issue.

**Review by MaryamZi — APPROVED** [review]
