### PR TITLE
Fix gRPC gzip compression issue

### LINKED ISSUE #21276: gRPC gzip compression is not supported in Ballerina
**Description:**
gzip compression is not supported in both grpc client and server.

**Steps to reproduce:**
Add gRPC compression header is client request.

**Affected Versions:**
1.1.3

### PR DESCRIPTION
**Pull request by daneshk**
## Purpose
This is to add gRPC gzip compression support.

Fixes #21276

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/UnaryGZipEncodingTestCase.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+import org.testng.Assert;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Test;
+
+import java.nio.file.Path;
+import java.nio.file.Paths;
+
+/**
+ * Test class for gzip communication between client and server.
+ */
```
Comment (pramodya1994) [inline tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/sample/UnaryGZipEncodingTestCase.java]: Shall we add @since

File: stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/InboundMessage.java [hunk 2]
```diff
@@ -135,11 +135,8 @@ public Decompressor getMessageDecompressor() {
         String contentEncodingHeader = httpCarbonMessage.getHeader(MESSAGE_ENCODING);
         if (contentEncodingHeader != null) {
             httpCarbonMessage.removeHeader(HttpHeaderNames.CONTENT_ENCODING.toString());
-            Decompressor decompressor = DecompressorRegistry.getDefaultInstance().lookupDecompressor
+            return DecompressorRegistry.getDefaultInstance().lookupDecompressor
                     (contentEncodingHeader);
```
Comment (pramodya1994) [inline stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/InboundMessage.java]:
```suggestion
            return DecompressorRegistry.getDefaultInstance().lookupDecompressor(contentEncodingHeader);
```
