### PR TITLE
Fix type descriptor as an expression parsing

### LINKED ISSUE #26537: NullPointerException for mapping constructor key with built in type names
**Description:**
note $subject

#### Ballerina code
```Ballerina
public function main() {
    var x = {
        never: 65,
    };
} 
```

#### Output
```LogTalk

[2020-10-22 21:03:15,478] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1690)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangRecordVariableDef.accept(BLangRecordVariableDef.java:48)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2798)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2766)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:2762)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:381)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2798)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:353)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2798)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2766)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2758)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:269)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:243)
        at org.wso2.ballerinalang.compiler.CompilerDriver.typeCheck(CompilerDriver.java:339)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:268)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:260)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
        at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:55)
        at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
        at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:296)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at org.ballerinalang.tool.Main.main(Main.java:57)
```
**Steps to reproduce:**
Compile above code

**Affected Versions:**
Swan Lake

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #28415: Error Handler fail safe mechanism doesn't work as expected
**Description:**
If an invalid token is recovered as a missing token parser will end up in an infinite loop calling recovery.

**Related Issues (optional):**
#24242

### LINKED ISSUE #29700: Compiler crash for `typedesc-type-descriptor`in expression context
**Description:**
Consider following code sample.

```bal
public function main() {
    var a = typedesc;
}
```

</details>
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
Caused by: java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.tree.types.BLangBuiltInRefTypeNode cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangExpression (org.wso2.ballerinalang.compiler.tree.types.BLangBuiltInRefTypeNode and org.wso2.ballerinalang.compiler.tree.expressions.BLangExpression are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:4905)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2722)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2682)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:4806)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1456)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.populateFunctionNode(BLangNodeTransformer.java:1363)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1343)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1321)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:590)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:473)

```
</details>

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose

- Fix type descriptor as an expression parsing
- Fix some error handler rules 
- Fix fail-safe mechanism issues

Fixes #29700
Fixes #26537
Fixes crashing at #23127
Fixes #28415

## Approach
N/A

## Samples
N/A

## Remarks
With this PR, only the following types are allowed in expression context:
(as per the https://github.com/ballerina-platform/ballerina-spec/issues/797#issuecomment-810917172)

- boolean
- int
- byte
- float
- decimal
- string
- handle
- json
- anydata
- any
- never

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java [hunk 1]
```diff
@@ -47,13 +47,10 @@ public void test(String fileName, String path) {
...
-        // Following should be fixed
-        // TODO: categorize and create issues
+        // Compiler should be able to compile any user input.
+        // Therefore, when adding an item to the skip list, please create an issue.
         hashSet.add("func_def_source_08.bal");
-        hashSet.add("find_node_test_1.bal");
-        hashSet.add("minutiae_test_05_with_no_newlines.bal");
-        hashSet.add("import_decl_source_13.bal");
-        hashSet.add("do_stmt_source_07.bal");
+        hashSet.add("match_stmt_source_13.bal");
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java:53]: Created #29944 for this.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParser.java [hunk 2]
```diff
@@ -106,6 +106,10 @@ protected Solution recover(STToken token, ParserRuleContext currentCtx, Object..
         Solution sol = this.errorHandler.recover(currentCtx, token, args);
         // If the action is to remove, then re-parse the same rule.
         if (sol.action == Action.REMOVE) {
+            if (sol.isFailSafe) {
+                // Clean up the inserted token, which cannot be parsed.
+                this.insertedToken = null;
+            }
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParser.java:112]: We don't need this check right?. If the solution is `REMOVE` then we need to clean `this.insertedToken` anyway

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParser.java:112]: +1

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java [hunk 3]
```diff
@@ -112,13 +112,14 @@ public Solution recover(ParserRuleContext currentCtx, STToken nextToken, Object.
         }
 
         // Fail safe. This means we can't find a path to recover.
+        // TODO: Enable fail safe assert
+//        assert false : "fail safe reached";
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java:116]: @rdulmina Apparently, we do have some parser tests reaching the fail-safe in the **master**. Created an issue to enable this assertion.

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java:116]: I think we can't have an assert here because we reach here for `bestMatch.matches = 0` as well which can be a correct execution.

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java:116]: Else lets have an assert with checking `itterCount == ITTER_LIMIT`

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java:116]: my bad. +1

**Comment by lochana-chathura** [comment]
@sanjana Updated the range tests having invalid syntax with 24bdbe8.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java (hunk 3 above)
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java]: Some LS tests are hitting this assertion. Hence re-opened the issue #29947

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 4]
```diff
@@ -9240,6 +9244,16 @@ private boolean isTypeStartingToken(SyntaxKind nodeKind) {
         }
     }
 
+    private boolean isSimpleTypeInExpression(SyntaxKind nodeKind) {
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:9247]: Can we add some documentation to type desc as an expression

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 5]
```diff
@@ -4823,6 +4837,9 @@ private ParserRuleContext getNextRuleForIdentifier() {
             case TYPE_REFERENCE:
                 endContext();
                 return getNextRuleForTypeReference();
+            case SIMPLE_NAME_REFERENCE_IN_TYPE_DESC:
+                endContext();
+                return ParserRuleContext.TYPEDESC_RHS;
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:4842]: I think we can remove starting a context of `SIMPLE_NAME_REFERENCE_IN_TYPE_DESC`. using `SIMPLE_NAME_REF_IDENTIFIER` alias will be sufficient

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:4842]: `IDENTIFIER` has `MISSING IDENTIFIER` diagnostics right? We need to give `MISSING TYPE DESC`.
Problem with not having `SIMPLE_NAME_REFERENCE_IN_TYPE_DESC` ctx is; in `getNextRuleForIdentifier()` it may or may not go for the  `TYPEDESC_RHS`?

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:4842]: I c we need to use alias `SIMPLE_NAME_REF_IDENTIFIER`. but still not clear about using `SIMPLE_NAME_REFERENCE_IN_TYPE_DESC`. what do u mean by may or may not go for the `TYPEDESC_RHS`?

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java]: Addressed in d40178f :P

**Comment by sanjana** [comment]
> @sanjana Updated the range tests having invalid syntax with [24bdbe8](https://github.com/ballerina-platform/ballerina-lang/commit/24bdbe8b22bc0e3a1432444ab27e22ed907fc717).

@lochana-chathura the range formatting-related test cases look good to me. +1.

**Review by rdulmina — APPROVED** [review]
