### PR TITLE
Fix non-isolated method scheduling to be sequential - part 2

### LINKED ISSUE #29322: Support runtime api for non isolated function scheduling
Provide an API such as `invokeMethodAsync` but to schedule functions with an exclusive way. That is, functions from the same object never run in parallel.

### PR DESCRIPTION
**Pull request by manuranga**
Fixes #29322
Part of the fix was missing in #30374 this pr address that

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java [hunk 1]
```diff
@@ -81,8 +81,8 @@ public Object invokeMethodAsync(BObject object, String methodName, String strand
          if (isIsolate) {
              return scheduler.schedule(new Object[1], func, null, callback, strandName, metadata).result;
          } else {
-             return scheduler.scheduleToObjectGroup(object, new Object[1], func, null, callback, strandName, metadata)
-                     .result;
+             return scheduler.scheduleToObjectGroup(object, new Object[1], func, null, callback, null,
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java:84]: Shall we call the this invokeMethodAsync method with other function.

ex
      */
     public Object invokeMethodAsync(BObject object, String methodName, String strandName, StrandMetadata metadata,
                                     Callback callback, Object... args) {
         return invokeMethodAsync(object, methodName, strandName, metadata, callback, null,
                           PredefinedTypes.TYPE_NULL, args).getResult();

     }

Comment (warunalakshitha) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java:84]: Maybe we can do as a separate PR to master. Then we do not need to duplicate  if (isIsolate) { logic .

Comment (manuranga) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/Runtime.java:84]: I think two functions are duplicates, shall we remove one of them altogether ?
