### PR TITLE
[master] Fix testerina-integration-test

### LINKED ISSUE #39561: [Bug]: Testerina-integration-test passes for `GroupingTest.beforeGroupsAfterGroups1` but corresponding `bal test` command fails
### Description

$subject
Related to [#39556](https://github.com/ballerina-platform/ballerina-lang/issues/39556)

### Steps to Reproduce

_No response_

### Affected Version(s)

master 

### OS, DB, other environment details and versions

_No response_

### Related area

-> Test Framework

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
Fixes #39561

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BMainInstance.java [hunk 1]
```diff
@@ -586,26 +606,21 @@ public String runMainAndReadStdOut(String command, String[] args, Map<String, St
...
             addJavaAgents(envProperties);
             Map<String, String> env = processBuilder.environment();
             env.putAll(envProperties);
 
+            ByteArrayOutputStream baos = new ByteArrayOutputStream();
+            PrintStream out = new PrintStream(baos);
             Process process = processBuilder.start();
-
-            // Give a small timeout so that the output is given.
-            Thread.sleep(5000);
```
Comment (azinneera) [inline tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BMainInstance.java:597]: Is this not required now?

File: tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/GroupingTest.java [hunk 2]
```diff
@@ -172,15 +172,15 @@ public void beforeGroupsAfterGroups2() throws BallerinaTestException {
...
-    @Test
-    public void afterGroupsWithDisabledTest() throws BallerinaTestException {
-        String[] args = mergeCoverageArgs(new String[]{"--groups", "g1", "after-groups-with-disabled-test.bal"});
-        String output = balClient.runMainAndReadStdOut("test", args,
-                new HashMap<>(), projectPath, true);
-        if (output.contains("[fail] afterSuiteFunc")) {
-            Assert.fail("Test failed due to assertion failure in after suite function");
-        }
-    }
+//    @Test
```
Comment (azinneera) [inline tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/GroupingTest.java:175]: We can use the `enabled = false` property

File: tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BMainInstance.java (hunk 1 above)
Comment (Thevakumar-Luheerathan) [reply tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BMainInstance.java:597]: It seems like not needed.. It increases test time much

**Review by Dilhasha — CHANGES_REQUESTED** [review]
We discussed and decided to maintain the expected output in files and compare the actual output with the expected when running the tests.

File: tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BMainInstance.java [hunk 3]
```diff
@@ -51,6 +52,25 @@ public class BMainInstance implements BMain {
...
+        private PrintStream printStream;
+
+        public StreamGobbler(InputStream inputStream, PrintStream printStream) {
+            this.inputStream = inputStream;
+            this.printStream = printStream;
+        }
+
+        @Override
+        public void run() {
+            Scanner sc = new Scanner(inputStream, StandardCharsets.UTF_8);
```
Comment (Dilhasha) [inline tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/context/BMainInstance.java:66]: Shall we use a BufferedReader instead of Scanner as it is more efficient as it buffers data.

File: tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java [hunk 4]
```diff
@@ -45,138 +46,141 @@ public void setup() throws BallerinaTestException, IOException {
...
     @Test
-    public void testAnnotationAccess() throws BallerinaTestException {
+    public void testAnnotationAccess() throws BallerinaTestException, IOException {
+        String endString = " SEVERE {b7a.log.crash} - ";
+        String firstString = "We thank you for helping make us better.";
         String[] args = mergeCoverageArgs(new String[]{"annotation-access"});
         String output = balClient.runMainAndReadStdOut("test", args,
                 new HashMap<>(), projectPath, true);
-        AssertionUtils.assertForTestFailures(output, "test annotation access failure");
+        output = CommonUtils.replaceVaryingString(firstString, endString, output);
```
Comment (Dilhasha) [inline tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java:103]: What is usually a varying string? The project path ? 
Can you please share an example?

Comment (Thevakumar-Luheerathan) [reply tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java:103]:
```[2023-02-22 16:38:10,019] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BAnnotationSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BAnnotationSymbol are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BAnnotationSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BAnnotationSymbol are in unnamed module of loader 'app')
``` Here `[2023-02-22 16:38:10,019]` varies with time.

Comment (Thevakumar-Luheerathan) [reply tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java:103]: Temporary directory Paths where test resource packages are copied to

**Review by Dilhasha — APPROVED** [review]
