### PR TITLE
Fix original-name not getting assigned a value

### LINKED ISSUE #33721: Compiler Plugin failes for error return types
**Description:**
In the compile plugin of ballerina websub module, we have used `signature()` method of `TypeReferenceTypeSymbol` to get the full type description of error return types. 

With the `SL Beta4` RC pack, return type validation of websub compiler plugin has broken due to a change in `signature()` method of `TypeReferenceTypeSymbol`.  

Even though this validation fails with the RC pack, all the compiler plugin test cases are passing with the latest lang version. 

**Steps to reproduce:**
* Write a simple `websub:SubscriberService` and try to build this program using latest `SL Beta4 RC1` pack.
```ballerina
import ballerina/websub;

@websub:SubscriberServiceConfig {
    target: ["http://0.0.0.0:9090/hub", "test"],
    leaseSeconds: 36000
}
service on new websub:Listener(9091) {
    remote function onEventNotification(websub:ContentDistributionMessage event) 
                                        returns websub:Acknowledgement|websub:SubscriptionDeletedError? {
        return websub:ACKNOWLEDGEMENT;
    }
}
```

**Affected Versions:**
* SL Beta4 RC1

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #33721

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by sanjana — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java [hunk 1]
```diff
@@ -1322,6 +1322,7 @@ public BType readType(int cpI) throws IOException {
                     errorSymbol.type = errorType;
                     errorSymbol.pkgID = pkgId;
                     errorSymbol.name = names.fromString(errorName);
+                    errorSymbol.originalName = names.fromString(errorName);
```
Comment (sanjana) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:1325]: Could use `errorSymbol.name` as well.

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java]: changed

**Review by sanjana — APPROVED** [review]
