### PR TITLE
Fix accessing resource-path-name with escaped dot characters

### LINKED ISSUE #41878: [Bug]: Fail to capture the preceding part of the backslash in resource functions
### Description

When using resource methods in Ballerina services, it seems that the preceding part of the backslash in the resource path is not being properly captured.

### Steps to Reproduce

Run the following code.
```ballerina
public client class Client {

    resource function get v1\.2/greeting() returns string {
        return "Hello World!";
    }
}

public function main() {
    Client clientEP = new;
    string greeting = clientEP->/v1\.2/greeting;
    io:println(greeting);
}
```

The error output as follows
```bash
error: No such method: 1$accounts$^$users$^$signatures
        at nuvindu.docuSign.0:main(main.bal:9)
```

### PR DESCRIPTION
**Pull request by LakshanWeerasinghe**
Fixes #41878

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by HindujaB — DISMISSED** [review]
LGTM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java [hunk 1]
```diff
@@ -521,7 +521,9 @@ public static String generateReturnType(BType bType) {
     static String cleanupObjectTypeName(String typeName) {
         int index = typeName.lastIndexOf("."); // Internal type names can contain dots hence use the `lastIndexOf`
         int typeNameLength = typeName.length();
-        if (index > 0 && index != typeNameLength - 1) { // Resource method name can contain . at the end 
+        if (index - 1 > 0 && typeName.charAt(index - 1) == '\\') { // Methods can contain escaped characters
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java:524]:
```suggestion
        if (index > 1 && typeName.charAt(index - 1) == '\\') { // Methods can contain escaped characters
```

**Review by KavinduZoysa — APPROVED** [review]
