### PR TITLE
Fix redeclaration error for field named error

### LINKED ISSUE #23045: error can not be used as a filed name in a record
**Description:**
Refering https://ballerina-platform.slack.com/archives/C47EAELR1/p1588155489154500

> I get redeclared builtin symbol 'error' when I have a record with field as string 'error; . But I can have string 'int;

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by KRVPerera**
Fixes #23045

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 1]
```diff
@@ -217,6 +217,8 @@
     private SymbolEnv env;
     private final boolean projectAPIInitiatedCompilation;
 
+    private boolean isField = false;
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:220]: Shall we add a `flag` in the NodeTransformer indicating that this is a `field` and ditch this?

**Comment by MaryamZi** [comment]
This isn't just an issue with record fields, right? See https://github.com/ballerina-platform/ballerina-lang/issues/23045#issuecomment-782871888.

**Comment by KRVPerera** [comment]
> This isn't just an issue with record fields, right? See [#23045 (comment)](https://github.com/ballerina-platform/ballerina-lang/issues/23045#issuecomment-782871888).

Fixed for record and object fields. Did not check and expand the fix to a larger scope. Shall we merge this PR first?

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/Flag.java [hunk 2]
```diff
@@ -164,5 +164,9 @@
     /**
      * Indicates flagged node is a rest parameter.
      */
-    REST_PARAM
+    REST_PARAM,
+    /**
+     * Indicates flagged variable is a field.
+     */
+    FIELD,
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/Flag.java:171]:
```suggestion
    FIELD
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 3]
```diff
@@ -3689,10 +3689,19 @@ public BVarSymbol defineVarSymbol(Location pos, Set<Flag> flagSet, BType varType
...
-            varSymbol.type = symTable.semanticError;
+        if (flagSet.contains(Flag.FIELD)) {
+            if (!symResolver.checkForUniqueMemberSymbol(pos, env, varSymbol)) {
+                varSymbol.type = symTable.semanticError;
+            }
+        } else if (flagSet.contains(Flag.REQUIRED_PARAM) || flagSet.contains(Flag.DEFAULTABLE_PARAM) ||
+                flagSet.contains(Flag.REST_PARAM)) {
+            if (!symResolver.checkForUniqueMemberSymbol (pos, env, varSymbol)) {
+                varSymbol.type = symTable.semanticError;
+            }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:3700]: Can't we combine these two? We are doing the same thing in both blocks, right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 4]
```diff
@@ -3689,10 +3689,19 @@ public BVarSymbol defineVarSymbol(Location pos, Set<Flag> flagSet, BType varType
...
-        // Add it to the enclosing scope
-        if (!symResolver.checkForUniqueSymbol(pos, env, varSymbol)) {
-            varSymbol.type = symTable.semanticError;
+        if (flagSet.contains(Flag.FIELD)) {
+            if (!symResolver.checkForUniqueMemberSymbol(pos, env, varSymbol)) {
+                varSymbol.type = symTable.semanticError;
+            }
+        } else if (flagSet.contains(Flag.REQUIRED_PARAM) || flagSet.contains(Flag.DEFAULTABLE_PARAM) ||
+                flagSet.contains(Flag.REST_PARAM)) {
+            if (!symResolver.checkForUniqueMemberSymbol (pos, env, varSymbol)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:3698]:
```suggestion
            if (!symResolver.checkForUniqueMemberSymbol(pos, env, varSymbol)) {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 5]
```diff
@@ -3689,10 +3689,19 @@ public BVarSymbol defineVarSymbol(Location pos, Set<Flag> flagSet, BType varType
...
+                varSymbol.type = symTable.semanticError;
+            }
+        } else {
+            if (!symResolver.checkForUniqueSymbol(pos, env, varSymbol)) {
+                varSymbol.type = symTable.semanticError;
+            }
         }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:3705]: Can't we do
```suggestion
        } else if (!symResolver.checkForUniqueSymbol(pos, env, varSymbol)) {
            varSymbol.type = symTable.semanticError;
        }
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDefNegativeTest.java [hunk 6]
```diff
@@ -41,6 +41,14 @@ public void duplicateKeyTest() {
                 43, 10);
     }
 
+    @Test(description = "Test duplicate fields")
+    public void duplicateFieldTest() {
+        CompileResult compileResult = BCompileUtil.compile("test-src/record/negative/duplicate-field-negative.bal");
+        int errorIndex = 0;
+        BAssertUtil.validateError(compileResult, errorIndex++, "redeclared symbol 'error'", 19, 11);
+        BAssertUtil.validateError(compileResult, errorIndex++, "redeclared symbol 'name'", 24, 12);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDefNegativeTest.java:49]: Shall we assert errorIndex vs diagnostic count also?

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object-field-defaultable.bal [hunk 7]
```diff
@@ -16,3 +31,37 @@ class Person {
...
+    public error 'error;
+    public int 'int;
+
+    function init (error er, int value = 20) {
+        self.'error = er;
+        self.'int = value;
+    }
+}
+
+public function testErrorAsObjectField () {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/object/object-field-defaultable.bal:45]: Is this the best file to add this test?

```suggestion
public function testErrorAsObjectField() {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 3 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:3700]: Shouldn't this be a generic fix anyway? For example, even with this change, the following wouldn't work, right?

```ballerina
public function main() {
    int 'error;
}
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:3700]: IMO, it will be better if we can fix this in `org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver#isSymbolDefinedInRootPkgLvl`.

I think we can even consider special casing the types such as json and error that we know will cause this conflict since this package is totally under our control.

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: Are you suggesting to return false to `error`, `json` and `anydata` like symbols?

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object-field-defaultable.bal (hunk 7 above)
Comment (KRVPerera) [reply tests/jballerina-unit-test/src/test/resources/test-src/object/object-field-defaultable.bal]: Suggestions?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 8]
```diff
@@ -201,6 +201,11 @@ public boolean checkForUniqueSymbol(Location pos, SymbolEnv env, BSymbol symbol)
             return true;
         }
 
+        // if a symbol is found, then check whether it is unique
+        if (!isDistinctSymbol(pos, symbol, foundSym)) {
+            return false;
+        }
+
         if (isRedeclaredSymbol(symbol, foundSym)) {
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:209]: It seems like we are doing a similar check here. Can't we merge it?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 3 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: Yeah, either that or if we can change the `(foundSym.tag & SymTag.VARIABLE_NAME) == SymTag.VARIABLE_NAME` check to return the result we want here.

`json`, `anydata`, `error` etc. here should be similar to other built-in types, right?

File: tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal [hunk 9]
```diff
@@ -389,6 +389,16 @@ function testErrorBindingPattern() {
...
+type ErrorDataWithErrorField record {
+    error 'error;
+};
+
+function testErrorDataWithErrorField() {
+    error newError = error("bam", message = "new error");
+    ErrorDataWithErrorField ef = {'error: newError};
+    assertEquality(ef.toString(), "{\"error\":error(\"bam\",message=\"new error\")}");
+}
+
```
Comment (rdhananjaya) [inline tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal:401]: Shall we add a test case with error constructor with `error` as the arg name. Something like this `error e = error("msg", 'error = error("e"));`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 10]
```diff
@@ -3689,9 +3689,12 @@ public BVarSymbol defineVarSymbol(Location pos, Set<Flag> flagSet, BType varType
         // Create variable symbol
         Scope enclScope = env.scope;
         BVarSymbol varSymbol = createVarSymbol(flagSet, varType, varName, env, pos, isInternal);
-
-        // Add it to the enclosing scope
-        if (!symResolver.checkForUniqueSymbol(pos, env, varSymbol)) {
+        if (flagSet.contains(Flag.FIELD) || flagSet.contains(Flag.REQUIRED_PARAM) ||
+                flagSet.contains(Flag.DEFAULTABLE_PARAM) || flagSet.contains(Flag.REST_PARAM)) {
+            if (!symResolver.checkForUniqueMemberSymbol(pos, env, varSymbol)) {
```
Comment (Kishanthan) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:3694]: Can these two nested if merged?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 11]
```diff
@@ -1390,7 +1397,7 @@ public void visit(BLangUserDefinedType userDefinedTypeNode) {
                     errored = true;
                 }
 
-                if (tempSymbol.type.tag != TypeTags.TYPEDESC) {
+                if (tempSymbol.type != null && tempSymbol.type.tag != TypeTags.TYPEDESC) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1400]: Can you share the scenario for which this now becomes null?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java [hunk 12]
```diff
@@ -771,4 +773,12 @@ public void testObjectAttachFuncReturningTuple() {
         Assert.assertEquals(result[0].stringValue(), "firstValue");
         Assert.assertEquals(result[1].stringValue(), "secondValue");
     }
+
+    @Test(description = "Negative test to test duplicate fields")
+    public void testDuplicateFields() {
+        CompileResult result = BCompileUtil.compile("test-src/object/object_field_negative.bal");
+        BAssertUtil.validateError(result, 0, "redeclared symbol 'error'",
+                20, 18);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java:781]: Can merge these two lines?

File: tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal [hunk 13]
```diff
@@ -389,6 +389,16 @@ function testErrorBindingPattern() {
...
 }
 
+type ErrorDataWithErrorField record {
+    error 'error;
+};
+
+function testErrorDataWithErrorField() {
+    error newError = error("bam", message = "new error");
+    ErrorDataWithErrorField ef = {'error: newError};
+    assertEquality(ef.toString(), "{\"error\":error(\"bam\",message=\"new error\")}");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal:399]: IMO, better to assert the field rather than toString(). In this case we can test field access too.

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object-field-defaultable.bal (hunk 7 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/object/object-field-defaultable.bal]: Maybe under `org.ballerinalang.test.types` or quoted identifier tests?

**Review by MaryamZi — APPROVED** [review]
@KRVPerera, as discussed let's merge this PR since using error as a param name is a blocker for the standard library. Please send a separate PR addressing the changes suggested here.

**Comment by KRVPerera** [comment]
I'll be fixing all minor code review suggestions on a separate PR as std lib is blocked by this issue.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 3 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: Don't think all built-in types share the same issue. Many will have SymTag as `TYPE`. This starts with `TYPE_DEF` which also has `VARIABLE_NAME` flag. `ERROR` is also a `TYPE_DEF`

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: Sorry, what I meant was that the behaviour or rather the contexts in which they can be used should be the same.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 11 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1400]: In that situation, we have already issued the previous error for this code segment (errored variable is true).
 Below example.
```Ballerina
 function Listener (string x, Listener e){
    e.message = x;
}
```

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1400]: Sorry, this is related to the PR because I am enabling an old removed test case.
builtin-symbol-negative.bal
