### PR TITLE
Fix map configurable variable clashing with modules

### LINKED ISSUE #29923: Fix module name & record variable name conflicts for configurable TOML
**Description:**
https://github.com/ballerina-platform/ballerina-spec/blob/master/configurable/spec.md#toml-keys
A configurable variable can be specified in a TOML file in the following format,
```
    key:= [[orgName .] moduleName .] varName
```

At the same time, currently a record variable can be specified in the following format,

```
 key:= [[orgName .] moduleName .] varName [.fieldName ]*
```
This can cause conflicts, if the org/module name which can be optional and the variable/field name have the same name in a project. 

**Steps to reproduce:**

**Affected Versions:**
alpha4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#28999 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #30383: Fix clash between record type configurable variable and module have the same name
**Description:**
If we have a record configurable variable with the same name as it's module name, currently it doesn't retrieve the value from toml file

**Steps to reproduce:**
If the record configurable variable and module have the same name as `record_test`

```ballerina
type Person record {|
    string name;
|};

configurable Person & readonly record_test = ?;
```
In `Config.toml`

```toml
[record_test]
name = "Hinduja"
```
error:
```
error: value not provided for required configurable variable 'record_test'
        at hinduja/record_test:0.1.0(main.bal:7)
warning: [Config.toml:(2:1,2:17)] unused configuration value 'record_test.name'
```

**Affected Versions:**
beta-1 SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #30571: Fix ambiguities between map type configurable variables and org/module names
**Description:**
As mapping values are supported by `configurable` variables through the TOML syntax as follows
```toml
[orgName.moduleName.varName]
field1 = "value"
```
And the simple type variables also can be supported through the TOML syntax of TOML tables
```toml
[orgName.moduleName]
varName = "value"
```
There is a possibility of ambiguity between modules and map/record typed configurable variables. 

We need to resolve such ambiguities at compile time as per [#800](https://github.com/ballerina-platform/ballerina-spec/issues/800#issuecomment-811587356)

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**
#30389 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject

Fixes #30571 
Fixes #30383  
Fixes #29923 

## Approach
Adding a compile time check for a map type variable and  it's immediate child module to not to have same name.
The error message will be
```
ERROR [main.bal:(2:26,2:30)] configurable variable name 'test' creates an ambiguity with module 'testOrg/moduleClash.test:0.1.0'
```

## Samples
**Case 1: A map variable & a sub-module have the same name**

Default Module name : foo
Code: In module foo
```ballerina
configurable map<string> foo = ?;
```
In module foo.foo
```ballerina
configurable string a = ?;
```
This can be represented in `Config.toml` as the following
```toml
foo.name = "abc" #this is the map value in foo
foo.foo.a = "a" #this is the string value in foo.foo
```

**Case 2: A map variable from default module & a non sub-module from same org**

Default Module org-name : p
Default Module name : q 
Non sub module name : r 
In module p/q
```ballerina
configurable map<string> r = ?;
```
In module p/r
```ballerina
configurable anydata a = ?;
```
This can be represented in `Config.toml` as the following
```toml
r.any = "a"  #this is the map value in p/q
r.a = "b"  #this is the string value in p/r
```

**Case 3: A map variable from sub-module & another sub-module**

Default Module name : a
Non sub module 1 name : b 
Non sub module 2 name : b.c 
In module b
```ballerina
configurable map<string> c = ?;
```
In module b.c
```ballerina
configurable anydata key = ?;
```
This can be represented in `Config.toml` as the following
```toml
a.b.c.any = "a"  #this is the map value in a.b
a.b.c.key = "b"  #this is the string value in a.b.c
```

## Remarks
**Case 4: The map variable and its module having same name by mandating the TOML header with its module name**

In `foo.bal` from root module `foo`

```ballerina
configurable map<string> foo = ?;
```
Can be represented as the following
```toml
foo.a = "aaa"
```
It can clash with its module name `foo`.

   - This case is handled in https://github.com/ballerina-platform/ballerina-lang/pull/31277

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by warunalakshitha** [comment]
Lets have a code review since there are some changes to compiler FE too.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 1]
```diff
@@ -872,6 +882,47 @@ public void visit(BLangSimpleVariable varNode) {
...
+
+    private void validateMapConfigVariable(String configKey, BVarSymbol variable) {
+        if (configKeys.contains(configKey) && isSubTypeOfMapping(variable.type) && !invalidVars.contains(variable)) {
+            invalidVars.add(variable);
+            dlog.error(variable.pos, DiagnosticErrorCode.CONFIGURABLE_VARIABLE_MODULE_AMBIGUITY_FOUND,
+                    variable.name.value);
+        }
+    }
+
+   private boolean isSubTypeOfMapping(BType type) {
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:919]: This has to be part of the types.isSubTypeOfMapping itself. So we can remove this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 2]
```diff
@@ -872,6 +882,47 @@ public void visit(BLangSimpleVariable varNode) {
...
+                break;
+            }
+            configKeys.add(variable.pkgID.name.value);
+        }
+    }
+
+    private void validateMapConfigVariable(String configKey, BVarSymbol variable) {
+        if (configKeys.contains(configKey) && isSubTypeOfMapping(variable.type) && !invalidVars.contains(variable)) {
+            invalidVars.add(variable);
+            dlog.error(variable.pos, DiagnosticErrorCode.CONFIGURABLE_VARIABLE_MODULE_AMBIGUITY_FOUND,
```
Comment (manuranga) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:914]: let's provide position of both conflicted locations.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 3]
```diff
@@ -255,11 +256,14 @@
     private DiagnosticCode diagCode;
     private BType resType;
     private Unifier unifier;
+    private PackageID rootPackage;
 
     private Map<BVarSymbol, BType.NarrowedTypes> narrowedTypeInfo;
     // Stack holding the fall-back environments. fall-back env is the env to go back
     // after visiting the current env.
     private Stack<SymbolEnv> prevEnvs = new Stack<>();
+    private Set<String> configKeys = new HashSet<>();
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:265]: Let's move this to the method local variable since sub modules with unimported modules can cause issues.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 4]
```diff
@@ -290,11 +294,16 @@ public SemanticAnalyzer(CompilerContext context) {
...
     public BLangPackage analyze(BLangPackage pkgNode) {
+        this.rootPackage = getRootPackage(pkgNode.moduleContextDataHolder.descriptor());
         this.dlog.setCurrentPackageId(pkgNode.packageID);
         pkgNode.accept(this);
         return pkgNode;
     }
 
+    private PackageID getRootPackage(ModuleDescriptor moduleDesc) {
+        return new PackageID(names.fromString(moduleDesc.org().value()),
+                names.fromString(moduleDesc.packageName().value()), names.fromString(moduleDesc.version().toString()));
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:305]: Instead of creating a new `PackageID`, we can just extract the information we need, right? Given that this analysis happens only via the package node, if we can extract the entire analysis out to a single method, I don't think we need a class field for this too.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 5]
```diff
@@ -17,6 +17,7 @@
  */
 package org.wso2.ballerinalang.compiler.semantics.analyzer;
 
+import io.ballerina.runtime.api.flags.SymbolFlags;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:20]: We shouldn't use runtime classes here. 

You can use org.wso2.ballerinalang.compiler.semantics.model.symbols.Symbols#isFlagOn and org.wso2.ballerinalang.util.Flags#CONFIGURABLE instead.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 6]
```diff
@@ -2165,6 +2166,25 @@ private boolean isModuleLevelVar(BSymbol symbol) {
...
+        analyseAndAddConfigVar(packageSymbol, configVars);
+        if (!packageSymbol.imports.isEmpty()) {
+            for (BPackageSymbol importSymbol : packageSymbol.imports) {
+                analyseAndAddConfigVar(importSymbol, configVars);
+            }
+        }
+        return configVars;
+    }
+
+    private void analyseAndAddConfigVar(BPackageSymbol pkgSymbol, Set<BVarSymbol> configVars) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2180]: How about

```suggestion
    private void populateConfigurableVars(BPackageSymbol pkgSymbol, Set<BVarSymbol> configVars) {
```

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 7]
```diff
@@ -1758,6 +1758,9 @@ error.unsupported.type.intersection=\
 error.wild.card.binding.pattern.only.supports.type.any=\
   a wildcard binding pattern can be used only with a value that belong to type ''any''
 
+error.configurable.variable.module.ambiguity.found=\
+  configurable variable name ''{0}'' creates ambiguity with a module
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1762]:
```suggestion
  configurable variable name ''{0}'' creates an ambiguity with a module
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1762]: And this is always from an imported module, right? How about

```suggestion
  configurable variable name ''{0}'' creates an ambiguity with an imported module
```

or if we are adding the name
```suggestion
  configurable variable name ''{0}'' creates an ambiguity with imported module ''{1}''
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 2 above)
Comment (HindujaB) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:913]: addressed with latest commit

**Review by warunalakshitha — COMMENTED** [review]
LGTM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 8]
```diff
@@ -871,6 +872,45 @@ public void visit(BLangSimpleVariable varNode) {
...
+                }
+            }
+        }
+    }
+
+    private void populateModuleKeys(Set<BVarSymbol> configVars, ModuleDescriptor rootModule,
+                                    Map<String, PackageID> configKeys) {
+        for (BVarSymbol variable : configVars) {
+            configKeys.put(variable.pkgID.orgName.value + "." + variable.pkgID.name.value, variable.pkgID);
+            if (!variable.pkgID.getOrgName().value.equals(rootModule.org().value())) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:900]: `rootModule.org().value()` can be extracted out to a variable outside the for loop. Better yet, the org name can be accepted as the param, instead of `ModuleDescriptor`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 9]
```diff
@@ -871,6 +872,45 @@ public void visit(BLangSimpleVariable varNode) {
...
+                break;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:901]: There seems to be some codecov comments, shall we verify and add tests where/if necessary?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 10]
```diff
@@ -2168,6 +2168,25 @@ private boolean isModuleLevelVar(BSymbol symbol) {
         return symbol.getKind() == SymbolKind.VARIABLE && symbol.owner.getKind() == SymbolKind.PACKAGE;
     }
 
+    public Set<BVarSymbol> getConfigVarSymbols(BPackageSymbol packageSymbol) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2171]: Should the method name reflect we're looking up symbols from imported modules also?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 11]
```diff
@@ -2168,6 +2168,25 @@ private boolean isModuleLevelVar(BSymbol symbol) {
...
+                populateConfigurableVars(importSymbol, configVars);
+            }
+        }
+        return configVars;
+    }
+
+    private void populateConfigurableVars(BPackageSymbol pkgSymbol, Set<BVarSymbol> configVars) {
+        for (Scope.ScopeEntry entry : pkgSymbol.scope.entries.values()) {
+            if (entry.symbol.tag == SymTag.VARIABLE && Symbols.isFlagOn(entry.symbol.flags, Flags.CONFIGURABLE)) {
+                configVars.add((BVarSymbol) entry.symbol);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2185]: Shall we extract `entry.symbol` out to a variable?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 12]
```diff
@@ -871,6 +872,45 @@ public void visit(BLangSimpleVariable varNode) {
...
+        ModuleDescriptor rootModule = pkgNode.moduleContextDataHolder.descriptor();
+        Map<String, PackageID> configKeys = new HashMap<>();
+        Set<BVarSymbol> configVars = symResolver.getConfigVarSymbols(pkgNode.symbol);
+        populateModuleKeys(configVars, rootModule, configKeys);
+        for (BVarSymbol variable : configVars) {
+            validateMapConfigVariable(variable.pkgID.orgName.value + "." + variable.pkgID.name.value + "."
+                    + variable.name.value, variable, configKeys);
+            if (variable.pkgID.getOrgName().value.equals(rootModule.org().value())) {
+                validateMapConfigVariable(variable.pkgID.name.value + "." + variable.name.value, variable, configKeys);
+                if (variable.pkgID.getName().value.equals(rootModule.packageName().value()) &&
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:888]: `rootModule.org().value()` and `rootModule.packageName().value()` can be extracted out to variables outside the for loop.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:888]: Same for `variable.pkgID.name.value`, `variable.name.value`, etc.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 13]
```diff
@@ -871,6 +872,45 @@ public void visit(BLangSimpleVariable varNode) {
...
     }
 
+    private void analyzeModuleConfigurableAmbiguity(BLangPackage pkgNode) {
+        if (pkgNode.moduleContextDataHolder == null) {
+            return;
+        }
+        ModuleDescriptor rootModule = pkgNode.moduleContextDataHolder.descriptor();
+        Map<String, PackageID> configKeys = new HashMap<>();
+        Set<BVarSymbol> configVars = symResolver.getConfigVarSymbols(pkgNode.symbol);
+        populateModuleKeys(configVars, rootModule, configKeys);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:882]: Can't `configKeys` be created in `populateModuleKeys` and returned now.

Let's change the name also to `getModuleKeys` or `getModuleConfigKeys` if we are changing this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 9 above)
Comment (HindujaB) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:906]: These lines are already covered in the tests. But the codecov shows as not covered. 
This could be a bug. 
https://github.com/ballerina-platform/ballerina-lang/issues/31348

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 14]
```diff
@@ -2168,6 +2168,26 @@ private boolean isModuleLevelVar(BSymbol symbol) {
         return symbol.getKind() == SymbolKind.VARIABLE && symbol.owner.getKind() == SymbolKind.PACKAGE;
     }
 
+    public Set<BVarSymbol> getConfigVarSymbolsFromImportedModules(BPackageSymbol packageSymbol) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2171]: Shouldn't this be
```suggestion
    public Set<BVarSymbol> getConfigVarSymbolsIncludingImportedModules(BPackageSymbol packageSymbol) {
```

**Review by MaryamZi — APPROVED** [review]

**Review by warunalakshitha — APPROVED** [review]
