### PR TITLE
Fix order dependance on `module-xmlns-decl` access  

### LINKED ISSUE #35452: Order should not be matter for `module-xmlns-decl`
**Description:**
$subject.

```bal
public function main() {
    string exdoc = ex:doc;
    io:println(exdoc);
}

xmlns "http://example.com" as ex; // this does not visible to main.
```

When fixing this, make sure the following line in [module-xmlns-decl](https://ballerina.io/spec/lang/master/#module-xmlns-decl) does work(currently works as expected). If there's no test to test this add one also.
>It applies only to the source part in which it occurs, as with an import-decl.

**Affected Versions:**
2201.0.0

### PR DESCRIPTION
**Pull request by poorna2152**
## Purpose
Fixes #35452 

## Approach
Iterate through the xmlns definitions before iteration of the top level nodes and after the iteration of the constants in the Semantic Analyzer.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 1]
```diff
@@ -328,6 +328,14 @@ public void visit(BLangPackage pkgNode, AnalyzerData data) {
             }
         }
 
+        // Visiting after defining constants due to possible use of constants within xml namespaceURI.
+        for (int i = 0; i < topLevelNodes.size(); i++) {
+            TopLevelNode node = topLevelNodes.get(i);
+            if (node.getKind() == NodeKind.XMLNS) {
+                analyzeNode((BLangNode) node, data);
+            }
+        }
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:337]: Can't we bring this logic into the symbolEnter phase where we define module level constructs?

Consider following case,
```
xmlns CONSTA as ns;
const CONSTA = "example.com"; 
```
If we stick with depth first resolving logic used for other constructs then logic to solve the above will be like, we visit `module-xmlns-decl` to solve that we need to solve `CONSTA` then we solve `CONSTA`(`module-const-decl`) after all we can resolve `module-xmlns-decl`.

We may have to handle it here.
https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java#L226

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xmlns-def.bal [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+    assert(s1, "{http://ballerina.com/a}foo");
+
+    string s2 = ns1:bar;
+    assert(s2, "{http://ballerina.com/b}bar");
+
+    Rec rec = {};
+    assert(rec.a, "{http://ballerina.com/b}baz");
+}
+
+xmlns "http://ballerina.com/a" as ns0;
```
Comment (prakanth97) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xmlns-def.bal:18]: Shall we add few test where, `xmlns [CONST] as ns0;` and

Comment (poorna2152) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xmlns-def.bal:18]: Using const for the namespaceURI does not work at the moment. There is a PR ([41958](https://github.com/ballerina-platform/ballerina-lang/pull/41958)) to address this issue. Once that gets merged we can add a test.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 1 above)
Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:337]: +1 for @prakanth97 suggestion. Since in the future we should support the xml template declaration as well according to the spec. In that case we can have namespaces in the xml template.
```ballerina
xmlns "example.com" as ns;
const CONSTA = xml `</ns:a>`
```

Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:337]: As discussed offline following the approach described in this comment.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java [hunk 3]
```diff
@@ -1974,6 +1980,20 @@ public void resolveConstant(SymbolEnv symEnv, Map<String, BLangNode> modTable, B
...
     }
 
+    public void resolveXMLNS(SymbolEnv symEnv, Map<String, BLangNode> modTable, BLangXMLNS xmlnsNode) {
+        if (xmlnsNode.namespaceURI.getKind() == NodeKind.SIMPLE_VARIABLE_REF) {
+            BLangSimpleVarRef varRef = (BLangSimpleVarRef) xmlnsNode.namespaceURI;
+            BLangNode node = modTable.get(varRef.variableName.value);
+            if (node != null && node.getKind() == NodeKind.CONSTANT) {
+                if (!resolvedConstants.contains((BLangConstant) node)) {
+
+                    resolveConstant(symEnv, modTable, (BLangConstant) node);
```
Comment (heshanpadmasiri) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:1990]:
```suggestion
                    resolveConstant(symEnv, modTable, (BLangConstant) node);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java [hunk 4]
```diff
@@ -1974,6 +1980,18 @@ public void resolveConstant(SymbolEnv symEnv, Map<String, BLangNode> modTable, B
         checkUniqueness(constant);
     }
 
+    public void resolveXMLNS(SymbolEnv symEnv, Map<String, BLangNode> modTable, BLangXMLNS xmlnsNode) {
+        if (xmlnsNode.namespaceURI.getKind() == NodeKind.SIMPLE_VARIABLE_REF) {
+            BLangSimpleVarRef varRef = (BLangSimpleVarRef) xmlnsNode.namespaceURI;
+            BLangNode node = modTable.get(varRef.variableName.value);
+            if (node != null && node.getKind() == NodeKind.CONSTANT &&
+                    !resolvedConstants.contains((BLangConstant) node)) {
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:1988]: IMO, this isn't correct. The reason is, we need to check in the main space as well. Consider the scenario with `xmlns Foo:foo as ex;`, where we didn't add the `modTable` list. In such cases, we need to check in the main space as well.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java [hunk 5]
```diff
@@ -213,10 +214,13 @@ public static TypeResolver getInstance(CompilerContext context) {
     public void defineBTypes(List<BLangNode> moduleDefs, SymbolEnv pkgEnv) {
         this.pkgEnv = pkgEnv;
         typePrecedence = 0;
-        for (BLangNode typeAndClassDef : moduleDefs) {
-            String typeOrClassName = symEnter.getTypeOrClassName(typeAndClassDef);
+        for (BLangNode moduleDef : moduleDefs) {
+            if (moduleDef.getKind() == NodeKind.XMLNS) {
+                continue;
+            }
```
[the remark this answers is not in the document]
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:220]: XMLNS does not have a specific identifier associated with it such as the type name. We dont have to insert the xmlns to modTable

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 6]
```diff
@@ -420,34 +420,35 @@ private void defineConstructs(BLangPackage pkgNode, SymbolEnv pkgEnv) {
         // Treat constants and type definitions in the same manner, since constants can be used as
         // types. Also, there can be references between constant and type definitions in both ways.
         // Thus visit them according to the precedence.
-        List<BLangNode> typeAndClassDefs = new ArrayList<>();
-        pkgNode.constants.forEach(constant -> typeAndClassDefs.add(constant));
-        pkgNode.typeDefinitions.forEach(typDef -> typeAndClassDefs.add(typDef));
+        List<BLangNode> moduleDefs = new ArrayList<>();
+        pkgNode.constants.forEach(constant -> moduleDefs.add(constant));
+        pkgNode.typeDefinitions.forEach(typDef -> moduleDefs.add(typDef));
+        pkgNode.xmlnsList.forEach(xmlns -> moduleDefs.add(xmlns));
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:426]: This doesn't handle the second comment in the [issue](https://github.com/ballerina-platform/ballerina-lang/issues/35452), does it?

> When fixing this, make sure the following line in [module-xmlns-decl](https://ballerina.io/spec/lang/master/#module-xmlns-decl) does work. If there's no test to test this add one also.
>
> > It applies only to the source part in which it occurs, as with an import-decl.

proj

- a.bal

```ballerina
import ballerina/io;

public function f1() {
    string exdoc = ex:doc;
    io:println(exdoc);
}

xmlns "http://example.com" as ex;
```

- b.bal

```ballerina
import ballerina/io;

public function f2() {
    string exdoc = ex:doc;
    io:println(exdoc);
}
```

There's no error for `ex:doc`.

Similarly, when b.bal is instead

```ballerina
xmlns "http://example.com" as ex;
```

there's a redeclared symbol error. This seems to be the case on U8 too, and is incorrect.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java [hunk 7]
```diff
@@ -1974,6 +1980,33 @@ public void resolveConstant(SymbolEnv symEnv, Map<String, BLangNode> modTable, B
...
+        if (pkgAlias == Names.EMPTY && modTable.containsKey(varName.value)) {
+            // modTable contains the available constants in current module.
+            BLangNode node = modTable.get(varName.value);
+            if (node.getKind() == NodeKind.CONSTANT) {
+                if (!resolvedConstants.contains((BLangConstant) node)) {
+                    resolveConstant(env, modTable, (BLangConstant) node);
+                }
+            } else {
+                dlog.error(pos, DiagnosticErrorCode.EXPRESSION_IS_NOT_A_CONSTANT_EXPRESSION);
+                return symTable.notFoundSymbol;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:2002]: Codecov warning?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 8]
```diff
@@ -3649,6 +3650,8 @@ public BLangNode transform(ModuleXMLNamespaceDeclarationNode xmlnsDeclNode) {
         xmlns.namespaceURI = namespaceUri;
         xmlns.prefix = prefixIdentifier;
         xmlns.pos = getPosition(xmlnsDeclNode);
+        xmlns.compUnit = this.createIdentifier(xmlns.pos, currentCompUnitName);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:3653]: Are these the correct pos, btw?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 9]
```diff
@@ -1166,11 +1168,16 @@ public void initPredeclaredModules(Map<Name, BPackageSymbol> predeclaredModules,
...
+    }
+
+    public void defineXMLNS(SymbolEnv symEnv, BLangXMLNS xmlnsNode) {
         String nsURI = "";
         if (xmlnsNode.namespaceURI.getKind() == NodeKind.SIMPLE_VARIABLE_REF) {
             BLangSimpleVarRef varRef = (BLangSimpleVarRef) xmlnsNode.namespaceURI;
             if (Symbols.isFlagOn(varRef.symbol.flags, Flags.CONSTANT)) {
-                nsURI = ((BConstantSymbol) varRef.symbol).value.toString();
+                BLangConstantValue constantValue = ((BConstantSymbol) varRef.symbol).value;
+                nsURI = constantValue != null ? constantValue.toString() : "";
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1180]: When can this be null now?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/declarations/XMLNSTest.java [hunk 10]
```diff
@@ -65,9 +67,24 @@ public void testXMLNSDefinitionNegative() {
...
+        BAssertUtil.validateError(negativeResult, i++, "cannot bind prefix 'ns' to the empty namespace name", 37, 1);
         Assert.assertEquals(negativeResult.getErrorCount(), i);
     }
 
+    @Test
+    public void testXMLNSPrefixUsage() {
+        CompileResult compileResult = BCompileUtil.compile("test-src/declarations/xmlnsPrefixProject");
+        BRunUtil.invoke(compileResult, "testXMLNSUsage");
+        BRunUtil.invoke(compileResult, "testXMLNSUsageInAnotherFile");
+    }
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/declarations/XMLNSTest.java:80]: Use a data provider instead, or the second one won't run if the first fails.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/declarations/XMLNSTest.java [hunk 11]
```diff
@@ -65,9 +67,24 @@ public void testXMLNSDefinitionNegative() {
...
+
+    @Test
+    public void testXMLNSPrefixUsageNegative() {
+        CompileResult compileResult = BCompileUtil.compile("test-src/declarations/xmlnsPrefixNegativeProject");
+        validateError(compileResult, 0, "undefined module 'ns'", 18, 16);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/declarations/XMLNSTest.java:85]: Can we add more tests? Maybe with namespaces defined in different scopes?

File: tests/jballerina-unit-test/src/test/resources/test-src/declarations/xmlnsPrefixProject/a.bal [hunk 12]
```diff
@@ -0,0 +1,37 @@
...
+}
+
+xmlns "http://exampleA3.com" as ns3;
+
+function assert(anydata actual, anydata expected) {
+    if (expected != actual) {
+        string reason = "expected `" + expected.toString() + "`, but found `" + actual.toString() + "`";
+        error e = error(reason);
+        panic e;
+    }
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/declarations/xmlnsPrefixProject/a.bal:36]: Remove parenthesis in the condition and merger L33-L35.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 9 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1180]: For cases such as this,
```
const X = G;
xmlns X as ns;
```.
Where G is not defined

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 13]
```diff
@@ -649,11 +651,11 @@ public BLangNode transform(ModulePartNode modulePart) {
         this.currentCompilationUnit = compilationUnit;
         compilationUnit.name = currentCompUnitName;
         compilationUnit.setPackageID(packageID);
-        Location pos = getPosition(modulePart);
+        modulePartPos = getPosition(modulePart);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:654]: Can't we avoid maintaining this at class level and instead set it for xmlns decl statements here similar to imports?

Can be an issue with xmlns-decl-stmt (not at module-level), but for those, do we need compUnit?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 14]
```diff
@@ -420,34 +421,35 @@ private void defineConstructs(BLangPackage pkgNode, SymbolEnv pkgEnv) {
         // Treat constants and type definitions in the same manner, since constants can be used as
         // types. Also, there can be references between constant and type definitions in both ways.
         // Thus visit them according to the precedence.
-        List<BLangNode> typeAndClassDefs = new ArrayList<>();
-        pkgNode.constants.forEach(constant -> typeAndClassDefs.add(constant));
-        pkgNode.typeDefinitions.forEach(typDef -> typeAndClassDefs.add(typDef));
+        List<BLangNode> moduleDefs = new ArrayList<>();
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:424]: The preceding comment block is not completely accurate anymore?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 15]
```diff
@@ -420,34 +421,35 @@ private void defineConstructs(BLangPackage pkgNode, SymbolEnv pkgEnv) {
...
+        pkgNode.constants.forEach(constant -> moduleDefs.add(constant));
+        pkgNode.typeDefinitions.forEach(typDef -> moduleDefs.add(typDef));
+        pkgNode.xmlnsList.forEach(xmlns -> moduleDefs.add(xmlns));
         List<BLangClassDefinition> classDefinitions = getClassDefinitions(pkgNode.topLevelNodes);
-        classDefinitions.forEach(classDefn -> typeAndClassDefs.add(classDefn));
+        classDefinitions.forEach(classDefn -> moduleDefs.add(classDefn));
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:429]: Can just do addAll instead of .forEach and adding one by one. Can get rid of the `classDefinitions` variable too.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 9 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1180]: I believe that setting the value to an empty string is not the correct approach. Doing so results in the following errors for above example you mentioned.
```
ERROR [test.bal:(8:11,8:12)] expression is not a constant expression
ERROR [test.bal:(8:11,8:12)] undefined symbol 'G'
ERROR [test.bal:(9:1,9:15)] cannot bind prefix 'ns' to the empty namespace name

```
These errors suggest that the symbol 'G' is undefined. However, the error `cannot bind prefix ns to the empty namespace name` seems to imply that 'G' is defined but as an empty string. Therefore, in my opinion, the only appropriate error message for this scenario should be:
```
ERROR [test.bal:(8:11,8:12)] undefined symbol 'G'
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 16]
```diff
@@ -471,11 +476,12 @@ public BSymbol resolvePrefixSymbol(SymbolEnv env, Name pkgAlias, Name compUnit)
...
             long tag = symbol.tag;
 
-            if ((tag & SymTag.XMLNS) == SymTag.XMLNS) {
+            if ((tag & SymTag.XMLNS) == SymTag.XMLNS &&
+                    ((BXMLNSSymbol) symbol).compUnit.equals(compUnit)) {
                 return symbol;
             }
 
-            if ((tag & SymTag.IMPORT) == SymTag.IMPORT &&
+            if (!((tag & SymTag.XMLNS) == SymTag.XMLNS) && (tag & SymTag.IMPORT) == SymTag.IMPORT &&
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:484]: Do we need `!((tag & SymTag.XMLNS) == SymTag.XMLNS) ` this check here?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 17]
```diff
@@ -225,6 +225,11 @@ public boolean checkForUniqueSymbol(Location pos, SymbolEnv env, BSymbol symbol)
             return true;
         }
 
+        if (symbol.tag == SymTag.XMLNS &&
+                !(((BXMLNSSymbol) foundSym).compUnit.value.equals(((BXMLNSSymbol) symbol).compUnit.value))) {
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:229]: Here, why we need to check whether the compile units are equal?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java [hunk 18]
```diff
@@ -1974,6 +1980,18 @@ public void resolveConstant(SymbolEnv symEnv, Map<String, BLangNode> modTable, B
...
+    public void resolveXMLNS(SymbolEnv symEnv, Map<String, BLangNode> modTable, BLangXMLNS xmlnsNode) {
+        if (xmlnsNode.namespaceURI.getKind() == NodeKind.SIMPLE_VARIABLE_REF) {
+            BLangSimpleVarRef varRef = (BLangSimpleVarRef) xmlnsNode.namespaceURI;
+            BLangNode node = modTable.get(varRef.variableName.value);
+            if (node != null && node.getKind() == NodeKind.CONSTANT &&
+                    !resolvedConstants.contains((BLangConstant) node)) {
+                resolveConstant(symEnv, modTable, (BLangConstant) node);
+            }
+        }
+        symEnter.defineXMLNS(symEnv, xmlnsNode);
```
[the remark this answers is not in the document]
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:1989]: Did we discuss anything related to this offline? I'm asking because it seems we've resolved this conversation

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 9 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1180]: +1 for skipping the error message `cannot bind prefix 'ns' to the empty namespace name`. What about the error message `expression is not a constant expression`. We should emit that right? Its for the line `const X  = G` where G is also not a constant expression.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java (hunk 18 above)
[the remark this answers is not in the document]
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:1989]: I didnt get the question here, this seemed like a statement.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 16 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:484]: In SymTag class we have the following tags for import and xmlns,
```java
public static final long IMPORT = 1;
public static final long XMLNS = 1 << 13 | IMPORT;
```

Thus 
* XMLNS_TAG = 8193
* IMPORT_TAG = 1

Consider a case where `tag` variable is XMLNS tag (8193).

Here 
`tag & SymTag.IMPORT = 8193 & 1 = 1 = SymTag.IMPORT`
Thus when XMLNS is the tag variable doing AND operation with IMPORT tag is making it equal to IMPORT tag.
Thus we first need to ensure that it is not a XMLNS tag.
Otherwise BPackageSymbol cast is going to fail.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 17 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:229]: XMLNS prefix is valid for a single file. Thus we need to ensure that the symbol we retrieved belongs to the same file.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java (hunk 18 above)
[the remark this answers is not in the document]
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:1989]: This looked more like statement than a question to me.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 19]
```diff
@@ -650,16 +650,23 @@ public BLangNode transform(ModulePartNode modulePart) {
...
             compilationUnit.addTopLevelNode(bLangImport);
         }
 
         // Generate other module-level declarations
         for (ModuleMemberDeclarationNode member : modulePart.members()) {
-            compilationUnit.addTopLevelNode((TopLevelNode) member.apply(this));
+            if (member.kind() == SyntaxKind.MODULE_XML_NAMESPACE_DECLARATION) {
+                compilationUnit.addTopLevelNode(
+                        (TopLevelNode) transformModuleXMLNSDeclaration((ModuleXMLNamespaceDeclarationNode) member,
+                                compUnit));
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:666]: Can't we do this similar to the import instead? Without avoiding apply and modifying/getting rid of `transform(ModuleXMLNamespaceDeclarationNode`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 20]
```diff
@@ -417,37 +418,37 @@ private void defineConstructs(BLangPackage pkgNode, SymbolEnv pkgEnv) {
...
-        // types. Also, there can be references between constant and type definitions in both ways.
-        // Thus visit them according to the precedence.
-        List<BLangNode> typeAndClassDefs = new ArrayList<>();
-        pkgNode.constants.forEach(constant -> typeAndClassDefs.add(constant));
-        pkgNode.typeDefinitions.forEach(typDef -> typeAndClassDefs.add(typDef));
-        List<BLangClassDefinition> classDefinitions = getClassDefinitions(pkgNode.topLevelNodes);
-        classDefinitions.forEach(classDefn -> typeAndClassDefs.add(classDefn));
+        // Treat constants, type definitions and xmlns declarations in the same manner, since constants can be
+        // used as types. Also, there can be references between constant, type definitions and xmlns declarations in
+        // both ways. Thus visit them according to the precedence.
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:423]: I would say visit them together since constants are also types and can be referred to in XMLNS declarations. Additionally, types and XMLNS declarations can also be used in constants.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BXMLNSSymbol.java [hunk 21]
```diff
@@ -35,6 +35,7 @@ public class BXMLNSSymbol extends BSymbol implements VariableSymbol {
      * Holds the namespace URI for lookup during semantic validations.
      */
     public String namespaceURI;
+    public Name compUnit;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BXMLNSSymbol.java:38]: Add a comment saying it's applicable only for module XMLNS declaration. 

Maybe we should have a module XMLNS construct representation extending XMLNS, but we can look into this separately.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 20 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:423]: `Additionally, types and XMLNS declarations can also be used in constants.` isn't this part implied by this `Also, there can be references between constant, type definitions and xmlns declarations in
        // both ways`

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:423]: Yeah, either way is OK. The first sentence needs to change though, since only the XMLNS bit is changed and not the rest of the sentence. Thus, the suggestion to change the second one also.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 22]
```diff
@@ -2646,6 +2651,13 @@ public boolean isReAtomNode(NodeKind kind) {
         }
     }
 
+    private boolean isXmlnsInDifferentCompUnit(BXMLNSSymbol symbol, BXMLNSSymbol foundSym) {
+        if (foundSym.compUnit != null && symbol.compUnit != null) {
+            return !foundSym.compUnit.value.equals(symbol.compUnit.value);
+        }
+        return foundSym.compUnit == null ^ symbol.compUnit == null;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2658]: Shall we extract out the repeated access to variables?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 23]
```diff
@@ -2646,6 +2651,13 @@ public boolean isReAtomNode(NodeKind kind) {
         }
     }
 
+    private boolean isXmlnsInDifferentCompUnit(BXMLNSSymbol symbol, BXMLNSSymbol foundSym) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2654]: Is the name accurate? Aren't we checking for more?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 24]
```diff
@@ -2646,6 +2651,13 @@ public boolean isReAtomNode(NodeKind kind) {
...
+        if (foundSym.compUnit != null && symbol.compUnit != null) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2655]: I would extract the `sym.compUnit != null` check out to something like `isModuleXmlns`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 22 above)
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2658]: This can then be something like `foundSymModuleXmlns != symModuleXmlns`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BXMLNSSymbol.java (hunk 21 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BXMLNSSymbol.java:38]: Shall we add the comment here also?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 25]
```diff
@@ -650,16 +650,23 @@ public BLangNode transform(ModulePartNode modulePart) {
...
         // Generate other module-level declarations
         for (ModuleMemberDeclarationNode member : modulePart.members()) {
-            compilationUnit.addTopLevelNode((TopLevelNode) member.apply(this));
+            if (member.kind() == SyntaxKind.MODULE_XML_NAMESPACE_DECLARATION) {
+                BLangXMLNS bLangXMLNS = (BLangXMLNS) member.apply(this);
+                bLangXMLNS.compUnit = compUnit;
+                compilationUnit.addTopLevelNode(bLangXMLNS);
+            } else {
+                compilationUnit.addTopLevelNode((TopLevelNode) member.apply(this));
+            }
```
Comment (heshanpadmasiri) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:669]: Since calling `member.apply` and `compilationUnit.addTopLevelNode` is common, I think you can factor things out to make this more clear
```suggestion
            TopLevelNode node = (TopLevelNode) member.apply(this);
            if (member.kind() == SyntaxKind.MODULE_XML_NAMESPACE_DECLARATION) {
                // If what you are really caring about is node being BLangXMLNS node replace the condition above with a pattern matching instanceOf and get rid of the cast
                BLangXMLNS bLangXMLNS = (BLangXMLNS)node;
                bLangXMLNS.compUnit = compUnit;
            } 
            compilationUnit.addTopLevelNode(node);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 22 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: Meant specifically this line where foundSymModuleXmlns is foundSym.compUnit != null and similarly symModuleXmlns is symbol.compUnit != null.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 26]
```diff
@@ -650,16 +650,22 @@ public BLangNode transform(ModulePartNode modulePart) {
...
             compilationUnit.addTopLevelNode(bLangImport);
         }
 
         // Generate other module-level declarations
         for (ModuleMemberDeclarationNode member : modulePart.members()) {
-            compilationUnit.addTopLevelNode((TopLevelNode) member.apply(this));
+            TopLevelNode node = (TopLevelNode) member.apply(this);
+            if (member.kind() == SyntaxKind.MODULE_XML_NAMESPACE_DECLARATION) {
+                BLangXMLNS bLangXMLNS = (BLangXMLNS) node;
+                bLangXMLNS.compUnit = compUnit;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:666]:
```suggestion
                ((BLangXMLNS) node).compUnit = compUnit;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java (hunk 18 above)
[the remark this answers is not in the document]
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:1989]: Had an offline discussion and decided that it is better to have a check on where it is defined than a null check. Thus updated the check

**Review by MaryamZi — DISMISSED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 27]
```diff
@@ -1185,14 +1193,16 @@ public void visit(BLangXMLNS xmlnsNode) {
 
         Name prefix = names.fromIdNode(xmlnsNode.prefix);
         Location nsSymbolPos = prefix.value.isEmpty() ? xmlnsNode.pos : xmlnsNode.prefix.pos;
-        BXMLNSSymbol xmlnsSymbol = Symbols.createXMLNSSymbol(prefix, nsURI, env.enclPkg.symbol.pkgID, env.scope.owner,
-                                                             nsSymbolPos, getOrigin(prefix));
+        BLangIdentifier compUnit = xmlnsNode.compUnit;
+        BXMLNSSymbol xmlnsSymbol =
+                Symbols.createXMLNSSymbol(prefix, nsURI, symEnv.enclPkg.symbol.pkgID, symEnv.scope.owner,
+                        nsSymbolPos, getOrigin(prefix), compUnit != null ? names.fromIdNode(xmlnsNode.compUnit) : null);
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1199]:
```suggestion
                        nsSymbolPos, getOrigin(prefix), compUnit != null ? names.fromIdNode(compUnit) : null);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 28]
```diff
@@ -471,11 +475,12 @@ public BSymbol resolvePrefixSymbol(SymbolEnv env, Name pkgAlias, Name compUnit)
             BSymbol symbol = entry.symbol;
             long tag = symbol.tag;
 
-            if ((tag & SymTag.XMLNS) == SymTag.XMLNS) {
+            if (symbol instanceof BXMLNSSymbol bxmlnsSymbol &&
+                    (bxmlnsSymbol.compUnit == null || bxmlnsSymbol.compUnit.equals(compUnit))) {
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:479]: May be extract `bxmlnsSymbol.compUnit` into a variable

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java [hunk 29]
```diff
@@ -229,6 +233,8 @@ public void defineBTypes(List<BLangNode> moduleDefs, SymbolEnv pkgEnv) {
                 updateEffectiveTypeOfCyclicIntersectionTypes(pkgEnv);
             } else if (def.getKind() == NodeKind.CONSTANT) {
                 resolveConstant(pkgEnv, modTable, (BLangConstant) def);
+            } else if (def.getKind() == NodeKind.XMLNS) {
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:236]: Shall we replace this block with switch case?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java [hunk 30]
```diff
@@ -1979,6 +1985,33 @@ public void resolveConstant(SymbolEnv symEnv, Map<String, BLangNode> modTable, B
...
+        }
+        symEnter.defineXMLNS(symEnv, xmlnsNode);
+    }
+
+    public BSymbol getSymbolOfVarRef(Location pos, SymbolEnv env, Name pkgAlias, Name varName) {
+        if (pkgAlias == Names.EMPTY && modTable.containsKey(varName.value)) {
+            // modTable contains the available constants in current module.
+            BLangNode node = modTable.get(varName.value);
+            if (node.getKind() == NodeKind.CONSTANT) {
+                if (!resolvedConstants.contains((BLangConstant) node)) {
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:2002]: We can combine these two nested if statement into one & statement

**Review by prakanth97 — APPROVED** [review]
LGTM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 31]
```diff
@@ -418,9 +418,8 @@ public void visit(BLangXMLNS xmlnsNode, AnalyzerData data) {
 
         typeChecker.checkExpr(xmlnsNode.namespaceURI, currentEnv, symTable.stringType, data.prevEnvs,
                 data.commonAnalyzerData);
-        // Namespace node already having the symbol means we are inside an init-function,
-        // and the symbol has already been declared by the original statement.
-        if (xmlnsNode.symbol == null) {
+        // Namespace node already having the symbol means it is defined in the module level.
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:421]: This comment isn't ideal with the change in check, is it?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 32]
```diff
@@ -418,9 +418,8 @@ public void visit(BLangXMLNS xmlnsNode, AnalyzerData data) {
 
         typeChecker.checkExpr(xmlnsNode.namespaceURI, currentEnv, symTable.stringType, data.prevEnvs,
                 data.commonAnalyzerData);
-        // Namespace node already having the symbol means we are inside an init-function,
-        // and the symbol has already been declared by the original statement.
-        if (xmlnsNode.symbol == null) {
+        // Symbol of a XML namespace declaration statement is resolved here.
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:421]:
```suggestion
        // For module-level XML namespace declarations the symbol is already defined at symbol enter.
```

**Review by MaryamZi — APPROVED** [review]

**Review by chiranSachintha — APPROVED** [review]

**Review by prakanth97 — APPROVED** [review]
