### PR TITLE
Handle immutable typedesc within toStream

### LINKED ISSUE #32244: Stream type check is not correct
**Description:**
`stream<byte[] & readonly, io:Error?>` type cannot be checked.

**Steps to reproduce:**
Execute the following code and the `BBBBB` will get printed.

```ballerina
    byte[] firstByteArray = [];
    int i = 0;
    while i < 16390 {
        firstByteArray[i] = 65;
        i = i + 1;
    }
    (byte[])[] & readonly bList = [firstByteArray.cloneReadOnly(), "123456".toBytes().cloneReadOnly(),
        "end.".toBytes().cloneReadOnly()];
    stream<byte[] & readonly, io:Error?> bStream = bList.toStream();
    if (bStream is stream<byte[] & readonly, io:Error?>) {
        log:printInfo("AAAAA");
    } else {
        log:printInfo("BBBBB");
    }
```

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #32244

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetElementType.java [hunk 1]
```diff
@@ -36,13 +38,18 @@
 
     public static BTypedesc getElementType(Object td) {
         BTypedesc bTypedesc = (BTypedesc) td;
-        Type type = bTypedesc.getDescribingType();
+        return getTypeDescValue(bTypedesc.getDescribingType());
+    }
+
+    private static BTypedesc getTypeDescValue(Type type) {
```
Comment (MaryamZi) [inline langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetElementType.java:44]: Should this be something like `getElementTypeDescValue`? Since the "element" type extraction also happens here?

File: langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetElementType.java [hunk 2]
```diff
@@ -36,13 +38,18 @@
...
             return ValueCreator.createTypedescValue(((ArrayType) type).getElementType());
         } else if (type.getTag() == TypeTags.STREAM_TAG) {
             return ValueCreator.createTypedescValue(((StreamType) type).getConstrainedType());
         } else if (type.getTag() == TypeTags.TABLE_TAG) {
             return ValueCreator.createTypedescValue(((TableType) type).getConstrainedType());
+        } else if (type.getTag() == TypeTags.FINITE_TYPE_TAG && ((FiniteType) type).getValueSpace().size() == 1) {
+            return getTypeDescValue(((BValue) (((FiniteType) type).getValueSpace().iterator().next())).getType());
         }
 
         return ValueCreator.createTypedescValue(PredefinedTypes.TYPE_NULL);
```
Comment (MaryamZi) [inline langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetElementType.java:55]: Ideally we shouldn't reach here, right? If so, shouldn't we throw an exception, rather than returning null because the actual issue wouldn't be uncovered until we operate on whatever the construct that was created using this?

**Review by gimantha — APPROVED** [review]

**Review by MaryamZi — APPROVED** [review]
Added minor suggestions. We can introduce any required changes in a separate PR.

File: langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetElementType.java (hunk 1 above)
Comment (pcnfernando) [reply langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetElementType.java:44]: Requested changes in https://github.com/ballerina-platform/ballerina-lang/pull/32257

File: langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetElementType.java (hunk 2 above)
Comment (pcnfernando) [reply langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/GetElementType.java:55]: Requested changes in https://github.com/ballerina-platform/ballerina-lang/pull/32257
