### PR TITLE
Fix signature help for function call expressions

### LINKED ISSUE #27294: Cast exception thrown when typing an arg for a function call
Consider the following program:
```ballerina
import ballerina/io;

public function main() {
    string greet = "Hello";
    io:println(); // This was completed by typing `p`, then `Ctrl + space` to complete the call 
}
```
Just as I complete the `println()` call, I get the following exception in the log:
```
[Error - 2:15:53 PM] Operation 'text/signature' failed! {uri: '/c%3A/Users/Pubudu/Projects/b7a-test/test.bal', [5:16], error: 'class io.ballerina.compiler.syntax.tree.QualifiedNameReferenceNode cannot be cast to class io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode (io.ballerina.compiler.syntax.tree.QualifiedNameReferenceNode and io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.QualifiedNameReferenceNode cannot be cast to class io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode (io.ballerina.compiler.syntax.tree.QualifiedNameReferenceNode and io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode are in unnamed module of loader 'app')
	at org.ballerinalang.langserver.signature.SignatureHelpUtil.getFunctionSymbol(SignatureHelpUtil.java:348)
	at org.ballerinalang.langserver.signature.SignatureHelpUtil.getSignatureInformation(SignatureHelpUtil.java:78)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$signatureHelp$2(BallerinaTextDocumentService.java:213)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by IrushiL — APPROVED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java [hunk 1]
```diff
@@ -344,12 +347,24 @@ private static boolean withinTextRange(int position, NonTerminalNode node) {
...
+                funcName = ((QualifiedNameReferenceNode) nameReferenceNode).identifier().text();
+                filteredContent = QNameReferenceUtil.getModuleContent(context,
+                        (QualifiedNameReferenceNode) nameReferenceNode,
+                        symbolPredicate.and(symbol -> symbol.name().equals(funcName)));
+            } else {
+                funcName = ((SimpleNameReferenceNode) nameReferenceNode).name().text();
+                List<Symbol> visibleSymbols = context.visibleSymbols(context.getCursorPosition());
+                filteredContent = visibleSymbols.stream()
+                        .filter(symbolPredicate.and(symbol -> symbol.name().equals(funcName)))
+                        .collect(Collectors.toList());
```
Comment (pubudu91) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java:364]: Do we have to take the visible symbols and filter? Can't we use `symbol()` for this?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java [hunk 2]
```diff
@@ -440,7 +455,7 @@ private static boolean withinTextRange(int position, NonTerminalNode node) {
             return Optional.empty();
         }
         String name = ((SimpleNameReferenceNode) referenceNode).name().text();
-        List<Symbol> visibleSymbols = context.visibleSymbols(context.getPosition());
+        List<Symbol> visibleSymbols = context.visibleSymbols(context.getCursorPosition());
```
Comment (pubudu91) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java:458]: Same comment regarding the use of `visibleSymbols()` vs. `symbol()`

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java [hunk 3]
```diff
@@ -454,7 +469,7 @@ private static boolean withinTextRange(int position, NonTerminalNode node) {
     private static Optional<? extends TypeSymbol> getTypeDescForFunctionCall(
             SignatureContext context, FunctionCallExpressionNode expr) {
         String fName = ((SimpleNameReferenceNode) expr.functionName()).name().text();
-        List<Symbol> visibleSymbols = context.visibleSymbols(context.getPosition());
+        List<Symbol> visibleSymbols = context.visibleSymbols(context.getCursorPosition());
```
Comment (pubudu91) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java:472]: Same comment regarding the use of `visibleSymbols()` vs. `symbol()`

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java:364]: This particular operation is triggered frequently for the incomplete sources and sometimes the semantic API might not capture the correct symbol because of the resilient parsing. Hence we have to use this particular approach.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java (hunk 2 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java:458]: Replied for the earlier comment

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java (hunk 3 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java:472]: Replied for the earlier comment

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java (hunk 1 above)
Comment (pubudu91) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/SignatureHelpUtil.java:364]: Ack.
