### PR TITLE
[2201.2.x] Fix suggesting completions with invalid prefix for already imported packages

### LINKED ISSUE #37536: Suggesting completions with invalid prefix for already imported packages
### Description

In the following scenario, `lang.array:ASCENDING` should be suggested as `array:ASCENDING`. 

https://user-images.githubusercontent.com/61020198/186852340-173d1e0e-1f7a-41e6-a0ce-e19024a1a593.mov

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
This PR fixes suggesting completions with invalid module prefix for already imported packages.

Fixes #37536

## Samples

https://user-images.githubusercontent.com/61020198/188563623-29624f5f-f868-472c-9a3a-f86b84d6cdc0.mov

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java [hunk 1]
```diff
@@ -302,6 +302,9 @@ private List<LSCompletionItem> getTypeItems(BallerinaCompletionContext context)
                 String label = completionItem.getLabel();
                 String moduleName = importDeclarationNode.prefix().isEmpty() ? moduleSymbol.id().moduleName()
                         : importDeclarationNode.prefix().get().prefix().text();
+                if (moduleName.contains(".")) {
+                    moduleName = moduleName.split("\\.")[1];
+                }
```
Comment (gayalkuruppu) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java:307]: This will break for a scenario where we have more than one `import-identifier`. In that case we should select the later `import-identifier`s as well. WDYT?

**Review by gayalkuruppu — DISMISSED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java (hunk 1 above)
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java:307]: +1

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java [hunk 2]
```diff
@@ -302,6 +302,10 @@ private List<LSCompletionItem> getTypeItems(BallerinaCompletionContext context)
                 String label = completionItem.getLabel();
                 String moduleName = importDeclarationNode.prefix().isEmpty() ? moduleSymbol.id().moduleName()
                         : importDeclarationNode.prefix().get().prefix().text();
+                if (moduleName.contains(".")) {
+                    String[] modNameParts = moduleName.split("\\.");
+                    moduleName = modNameParts[modNameParts.length - 1];
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java:307]: Shall we add a test case covering this

**Review by malinthar — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java (hunk 2 above)
Comment (mohanvive) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java:307]: @mindula can you please check this and comment/fix.

Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java:307]: @malinthar I have already added a test case for this.

Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java:307]: Updated the test case

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java [hunk 3]
```diff
@@ -302,6 +302,10 @@ private List<LSCompletionItem> getTypeItems(BallerinaCompletionContext context)
                 String label = completionItem.getLabel();
                 String moduleName = importDeclarationNode.prefix().isEmpty() ? moduleSymbol.id().moduleName()
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java:303]: What if we did `importDeclarationNode.moduleName(importDeclarationNode.moduleName() - 1).text()` instead of splitting string?

**Review by IMS94 — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java (hunk 3 above)
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java]: +1

**Review by dulajdilshan — APPROVED** [review]
LGTM
