### PR TITLE
Fix completion issue within mapping expressions

### LINKED ISSUE #35061: Missing completions in mapping constructor context
**Description:**
image

As depicted above, visible symbols are not suggested at the cursor position.

**Steps to reproduce:**
```ballerina
type MyType record {|
    string field1;
|};

function testFunction(string name) {
    MyType var1 = {field1: "Hello" + n<cursor>}
}
```

**Affected Versions:**
2201.0.1

### LINKED ISSUE #35124: `Fill required fields` attempts to fill values for fields with default values
Consider the following:
```ballerina
public function main() {
    Foo f = {<cursor>};
}

type Foo record {|
   string s = "foo";
|};
```
When you use the fill required fields action at the given cursor position, it'll fill the fields with default values as well. This may not be intended in all cases. For example, 
```ballerina
http:Ok ok = {<cursor>};
```
Using the fill required fields in above case results in the following:
```ballerina
http:Ok ok = {status: new()};
```
In this particular case, the intention of the library is not at all for the user to fill the `status` field.

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose
Fixes #35061
Fixes #35124 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 1]
```diff
@@ -1895,4 +1888,19 @@ public static String getModifiedUri(WorkspaceManager workspaceManager, String ur
...
 
+    /**
+     * Given a node (currentNode) start looking up the parent ladder until the given predicate is satisfied.
+     *
+     * @param currentNode Node to start looking
+     * @param predicate   to be satisfied
+     * @return {@link Optional}
+     */
+    public static Optional<Node> getMatchingNode(Node currentNode, Predicate<Node> predicate) {
+        Node evalNode = currentNode;
```
Comment (gayalkuruppu) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1899]: In this variable necessary?

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1899]: Created this as a temp variable in order to avoid updating the method parameter

Comment (gayalkuruppu) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1899]: But since we're not using this variable inside the method, do we need to worry about that?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java [hunk 2]
```diff
@@ -187,12 +188,15 @@ protected boolean hasReadonlyKW(NonTerminalNode evalNodeAtCursor) {
         return this.expressionCompletions(context);
     }
 
-    protected NonTerminalNode getEvalNode(BallerinaCompletionContext context) {
+    protected Optional<Node> getEvalNode(BallerinaCompletionContext context) {
         NonTerminalNode nodeAtCursor = context.getNodeAtCursor();
```
Comment (gayalkuruppu) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java:192]: Can we remove this line and return `CommonUtil.getMatchingNode(context.getNodeAtCursor, predicate);`?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java [hunk 3]
```diff
@@ -187,12 +188,15 @@ protected boolean hasReadonlyKW(NonTerminalNode evalNodeAtCursor) {
...
-        NonTerminalNode evalNode = (nodeAtCursor.kind() == SyntaxKind.QUALIFIED_NAME_REFERENCE
-                || nodeAtCursor.kind() == SyntaxKind.SIMPLE_NAME_REFERENCE)
-                ? nodeAtCursor.parent() : nodeAtCursor;
-        return evalNode;
+        Predicate<Node> predicate = node ->
+                node.kind() == SyntaxKind.MAPPING_CONSTRUCTOR
+                        || node.parent().kind() == SyntaxKind.MAPPING_CONSTRUCTOR
+                        || node.kind() == SyntaxKind.MAPPING_MATCH_PATTERN
+                        || node.parent().kind() == SyntaxKind.MAPPING_MATCH_PATTERN
+                        || (node.kind() == SyntaxKind.SPECIFIC_FIELD || node.kind() == SyntaxKind.COMPUTED_NAME_FIELD);
```
Comment (gayalkuruppu) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java:198]: Is there a specific reason to have parenthesis for `(node.kind() == SyntaxKind.SPECIFIC_FIELD || node.kind() == SyntaxKind.COMPUTED_NAME_FIELD)` else we can maintain the consistency

File: language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source63.bal [hunk 4]
```diff
@@ -0,0 +1,7 @@
+type MyType record {|
+    string field1;
+|};
+
+function testFunction(string name) {
+    MyType var1 = {field1: "Hello" + n}
+}
```
Comment (gayalkuruppu) [inline language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_expr_ctx_source63.bal:7]: Shall we add a new line here?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1899]: Basically it is better if we are not going to alter the parameter value, unless it is necessary

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java (hunk 3 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MappingContextProvider.java:198]: Done

**Review by IMS94 — APPROVED** [review]
LGTM! There's a minor suggestions. Fix that if possible.
