### PR TITLE
Fix formatter to work properly with function signatures

### LINKED ISSUE #37098: Formatting doesn't work properly with function signatures
**Description:**
Since, there is no style guidelines defined for function signatures, when the function signature has parameters of type like `type-descriptor` or `object-constructor` the formatting behaves unexpectedly as mentioned in the issue #34961

Since this is not specific to `object-constructors` as mentioned in the issue #34961. Some styling guideline is defined as below for function signatures

Example 1:

```ballerina
 function testFunction(int y,
        record {
            int z;
            int x;
        } rec) {
    // method body
}

```

Example 2:

```ballerina
function testFunction(int y, record {
            int z;
            int x;
        } rec) {
    // method body
}

```

### PR DESCRIPTION
**Pull request by AzeemMuzammil**
Fixes #37098

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 1]
```diff
@@ -4181,22 +4223,40 @@ private List<Minutiae> removeTrailingWS(List<Minutiae> trailingMinutiae) {
...
+    }
+
+    /**
+     * Undo the indentation of the code by the number of white-spaces defined by tab-size.
+     *
+     * @param step Number of tabs.
      */
-    private void unindent() {
-        if (env.currentIndentation < options.getTabSize()) {
+    private void unIndent(int step) {
```
Comment (IrushiL) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:4253]: Shall we leave the method name as `unindent` since it is one word?

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 2]
```diff
@@ -3814,19 +3816,20 @@ protected <T extends Node> SeparatedNodeList<T> formatSeparatedNodeList(Separate
...
-                                                                            int separatorTrailingNL,
-                                                                            int listTrailingWS,
-                                                                            int listTrailingNL) {
+                                                                                int itemTrailingWS,
+                                                                                int itemTrailingNL,
+                                                                                int separatorTrailingWS,
+                                                                                int separatorTrailingNL,
+                                                                                int listTrailingWS,
+                                                                                int listTrailingNL,
+                                                                                boolean allowInAndMultiLine) {
```
Comment (IrushiL) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:3832]: Is this formatting intentional?

Comment (AzeemMuzammil) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:3832]: No i's not, it is accidental. i'll revert it back

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 1 above)
Comment (AzeemMuzammil) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:4253]: will do that

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 3]
```diff
@@ -873,13 +875,13 @@ public AssignmentStatementNode transform(AssignmentStatementNode assignmentState
         Node varRef = formatNode(assignmentStatementNode.varRef(), 1, 0);
         Token equalsToken = formatToken(assignmentStatementNode.equalsToken(), 1, 0);
 
-        boolean previousinLineAnnotation = env.inLineAnnotation;
+        boolean previousInLineAnnotation = env.inLineAnnotation;
```
Comment (NipunaRanasinghe) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:878]:
```suggestion
        boolean previousInlineAnnotation = env.inLineAnnotation;
```

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 4]
```diff
@@ -873,13 +875,13 @@ public AssignmentStatementNode transform(AssignmentStatementNode assignmentState
...
         setInLineAnnotation(true);
 
         ExpressionNode expression = formatNode(assignmentStatementNode.expression(), 0, 0);
         Token semicolonToken = formatToken(assignmentStatementNode.semicolonToken(), env.trailingWS, env.trailingNL);
 
-        setInLineAnnotation(previousinLineAnnotation);
+        setInLineAnnotation(previousInLineAnnotation);
```
Comment (NipunaRanasinghe) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:884]:
```suggestion
        setInLineAnnotation(previousInlineAnnotation);
```

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 5]
```diff
@@ -3865,6 +3877,36 @@ protected <T extends Node> SeparatedNodeList<T> formatSeparatedNodeList(Separate
...
+                                                                            int listTrailingNL) {
+        return formatSeparatedNodeList(nodeList,
+                itemTrailingWS,
+                itemTrailingNL,
+                separatorTrailingWS,
+                separatorTrailingNL,
+                listTrailingWS,
+                listTrailingNL,
+                false);
+    }
```
Comment (NipunaRanasinghe) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:3908]: Shall we move up this method, so that the overloaded methods are sorted based on the complexity (i.e. number of parameters)?

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 4 above)
Comment (AzeemMuzammil) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java]: Since inline is a one word, all places where inline is treated as two words were changed to preserve consistency

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM
