### PR TITLE
[2201.3.0-stage] Fix encoding global variables in imported modules

### LINKED ISSUE #38759: [Bug]: Runtime Error Throws for Generated Client Operation
### Description

I have tried to solve the Ballerina Hackathon problem_3_5. 

I have used the OpenAPI tool to generate the clients and then call the API. When I tried to call the `sales` API, it throws the following error:

```shell
java.lang.ClassFormatError: Illegal field name "$Client_$get$._quarter" in class balHack/problem_3_5/1/main

    at java.lang.ClassLoader:defineClass1(ClassLoader.java:-2)
    java.lang.ClassLoader:defineClass(ClassLoader.java:1017)
    java.security.SecureClassLoader:defineClass(SecureClassLoader.java:174)
    java.net.URLClassLoader:defineClass(URLClassLoader.java:555)
    java.net.URLClassLoader$1:run(URLClassLoader.java:458)
    java.net.URLClassLoader$1:run(URLClassLoader.java:452)
    java.security.AccessController:doPrivileged(AccessController.java:-2)
    java.net.URLClassLoader:findClass(URLClassLoader.java:451)
    java.lang.ClassLoader:loadClass(ClassLoader.java:589)
    java.lang.ClassLoader:loadClass(ClassLoader.java:522)
    balHack.problem_3_5$test.1.tests.tests:testFindTopCustomers(tests-tests:10)
    jdk.internal.reflect.NativeMethodAccessorImpl:invoke0(NativeMethodAccessorImpl.java:-2)
    jdk.internal.reflect.NativeMethodAccessorImpl:invoke(NativeMethodAccessorImpl.java:62)
    jdk.internal.reflect.DelegatingMethodAccessorImpl:invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method:invoke(Method.java:566)
    org.ballerinalang.test.runtime.entity.TesterinaFunction:lambda$runOnSchedule$0(TesterinaFunction.java:109)
    io.ballerina.runtime.internal.scheduling.SchedulerItem:execute(SchedulerItem.java:54)
    io.ballerina.runtime.internal.scheduling.Scheduler:run(Scheduler.java:324)
    io.ballerina.runtime.internal.scheduling.Scheduler:runSafely(Scheduler.java:291)
    java.lang.Thread:run(Thread.java:829)
```

Tried the same code with Ballerina 2201.2.3, it works fine.

### Steps to Reproduce

Generate the clients in the Ballerina Hackathon problem_3_5.

Then use the following code:

```ballerina
import problem_3_5.customers;
import problem_3_5.sales;

function findTopXCustomers(Quarter[] quarters, int x) returns customers:Customer[]|error {
    final sales:Client salesClient = check new ("http://localhost:8080/sales");
    sales:Sales[] sales = check salesClient->/(x);
    return [];
}
```

Check the same code with Ballerina 2201.2.3, it works without this error.

### Affected Version(s)

Ballerina 2201.3.0 (Swan Lake Update 3) RC2
RC1 is also affected by this.

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #38759

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java [hunk 1]
```diff
@@ -419,29 +419,24 @@ public void generateVarLoad(MethodVisitor mv, BIRNode.BIRVariableDcl varDcl, int
...
+            case CONSTANT:
+            case GLOBAL:
                 PackageID moduleId = ((BIRNode.BIRGlobalVariableDcl) varDcl).pkgId;
                 String pkgName = JvmCodeGenUtil.getPackageName(moduleId);
+                String varName = varDcl.name.value;
                 String className = jvmPackageGen.lookupGlobalVarClassName(pkgName, varName);
                 String typeSig = getTypeDesc(bType);
+                boolean samePackage = pkgName.equals(this.currentPackageName);
+                if (!samePackage) {
+                    varName = Utils.encodeNonFunctionIdentifier(varName);
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:434]: The encoding of identifiers is always handled at the JvmDesugar phase. Shall we move this logic to there only for `varLoad` & `varStore` instructions?

Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:434]: Will change the fix.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java [hunk 2]
```diff
@@ -1865,16 +1866,25 @@ public void visit(BLangPackageVarRef astPackageVarRefExpr) {
...
-        if ((symbol.tag & SymTag.CONSTANT) == SymTag.CONSTANT ||
-                !isInSamePackage(astPackageVarRefExpr.varSymbol, env.enclPkg.packageID)) {
-            return new BIRGlobalVariableDcl(astPackageVarRefExpr.pos, symbol.flags, symbol.type, symbol.pkgID,
-                                            symbol.name, symbol.getOriginalName(), VarScope.GLOBAL, VarKind.CONSTANT,
-                                            symbol.name.value, symbol.origin.toBIROrigin());
+        Location pos = astPackageVarRefExpr.pos;
+
+        if (!isInSamePackage(astPackageVarRefExpr.varSymbol, env.enclPkg.packageID)) {
+            BIRGlobalVariableDcl newGlobalVarDcl = getNewGlobalVarDcl(pos, symbol);
+            this.env.enclPkg.importedGlobalVars.add(newGlobalVarDcl);
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java:1873]: Since it is a temporary global variable we can still add to global vars instead of creating new list for imported global vars.

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Review by gabilang — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
