### PR TITLE
[Debugger expression evaluation] Enhance function and object method invocation evaluation support

### LINKED ISSUE #26550: [Debugger] Integrate project API
**Description:**
- [ ] Access and use semantic API to complete rest of the function invocation expression types
- [x] Use diagnostics API to validate and detect semantic errors of the user given expression

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by NipunaRanasinghe**
## Purpose
This PR improves the function and object method invocation evaluation with support for
 - named arguments
 - defaultable parameters
 - rest parameters

This PR also adds integration tests for newly supported scenarios.

Fixes #26550.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [x] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/SuspendedContext.java [hunk 1]
```diff
@@ -112,21 +117,27 @@ public DebugSourceType getSourceType() {
...
     public Path getBreakPointSourcePath() {
-        return Paths.get(breakPointSourcePath);
+        if (breakPointSourcePath == null) {
+            this.breakPointSourcePath = getSourcePath(frame);
+        }
+        return breakPointSourcePath;
     }
 
-    private String getSourcePath(StackFrameProxyImpl frame) {
+    private Path getSourcePath(StackFrameProxyImpl frame) {
```
Comment (hemikak) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/SuspendedContext.java:126]: Since the return value can be `null`, shall we make the return value `Optional<Path>` ?

Comment (NipunaRanasinghe) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/SuspendedContext.java]: +1. Changed in d1a92fb.

**Review by hemikak — APPROVED** [review]
