### PR TITLE
Fix issues in RabbitMQ Connector 

### LINKED ISSUE #14816: Allow close codes and close messages when closing RabbitMQ connections
**Description:**
Allow close codes and close messages when closing the RabbitMQ connection. 

 `close code` : see under reply codes in AMQP specification[1]
 ` close message` : a message indicating the reason for closing the connection

Currently the connection and all its channels are closed with the AMQP.REPLY_SUCCESS close code and message 'OK'.[2] 

[1] https://www.rabbitmq.com/protocol.html
[2] https://www.rabbitmq.com/releases/rabbitmq-java-client/v3.5.4/rabbitmq-java-client-javadoc-3.5.4/com/rabbitmq/client/AMQP.html#REPLY_SUCCESS

**Suggested Assignees:**
Arshika

### LINKED ISSUE #14817: Add abort functionality to RabbitMQ Connection
**Description:**
Allow users to abort connections and all its channels with the AMQP.REPLY_SUCCESS close code and message 'OK'. Which forces the connection to close. Any encountered exceptions in the close operations will be silently discarded.

**Suggested Assignees:**
Arshika

### LINKED ISSUE #14841: Add support for multiple message types in RabbitMQ connector
**Description:**
Allow multiple types of messages to be sent and received through the RabbitMQ connector. 

**Suggested Assignees:**
Arshika

### PR DESCRIPTION
**Pull request by aashikam**
## Purpose
Adds abort functionality to RabbitMQ Connection and Channel, allow close codes and close messages when closing the RabbitMQ connection, add support for multiple message types in RabbitMQ connector. 

Fixes #14841
Fixes #14817
Fixes #14816

## Approach
Add new features to support the requirements mentioned above. 

## Samples

- [Publishing different types of messages](https://gist.github.com/aashikam/4497fa3a7ad2c45f3c4bec6e7bd3b71c)
- [Receiving different types of messages](https://gist.github.com/aashikam/7945359facd1b8e1adf34d24bd155c12)

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [x] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/BasicPublish.java [hunk 1]
```diff
@@ -56,12 +58,12 @@ public void execute(Context context) {
...
-        String message = context.getStringArgument(0);
-        String routingKey = context.getStringArgument(1);
-        // Handle other message types
-        String exchange = context.getStringArgument(2);
+        BValue msgContent = context.getRefArgument(1);
+        String routingKey = context.getStringArgument(0);
+        String exchange = context.getStringArgument(1);
         try {
-            ChannelUtils.basicPublish(channel, routingKey, message, exchange);
+            ChannelUtils.basicPublish(channel, routingKey, msgContent.stringValue().getBytes(Charset.forName("UTF-8")),
```
Comment (Manuri) [inline stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/BasicPublish.java]: You can use the constant for "UTF-8" from StandardCharsets class[1]

[1] https://docs.oracle.com/javase/8/docs/api/index.html?java/nio/charset/StandardCharsets.html

File: examples/rabbitmq-simple-producer/rabbitmq_simple_producer.bal [hunk 2]
```diff
@@ -16,7 +16,7 @@ public function main() {
         io:println("The queue was created successfully");
     }
 
-    // Publishes the message using the routing key named "testing".
+    // Publishes the message using the routing key named "testQueue".
```
Comment (wggihan) [inline examples/rabbitmq-simple-producer/rabbitmq_simple_producer.bal]: Shall we use a proper name for these queues instead of test prefix?

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal [hunk 3]
```diff
@@ -71,8 +71,8 @@ public type Channel client object {
     # + message - The message body.
     # + exchange - The name of the exchange the message is published to.
     # + return - Returns an error if an I/O error is encountered or nil if successful.
-    public remote function basicPublish(string message, string routingKey,
-                                            string exchange = "") returns error? = external;
+    public remote function basicPublish(int | float | byte | boolean | string | map<any> | xml | json | byte[] message,
```
Comment (daneshk) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]: Shall we define a new type, a union of all these types and use it here? So that we reuse it if needed
```bal
type Message int | float | byte | boolean | string | map<any> | xml | json | byte[];
```

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/AbortConnection.java [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+
+    @Override
+    public void execute(Context context) {
+        BMap<String, BValue> connectionBObject = (BMap<String, BValue>) context.getRefArgument(0);
+        BValue closeCode = context.getNullableRefArgument(1);
+        BValue closeMessage = context.getNullableRefArgument(2);
+        BValue timeout = context.getNullableRefArgument(3);
+        Connection connection = RabbitMQUtils.getNativeObject(connectionBObject,
+                RabbitMQConstants.CONNECTION_NATIVE_OBJECT, Connection.class, context);
+        ConnectionUtils.handleAbortConnection(connection, closeCode, closeMessage, timeout);
```
Comment (wggihan) [inline stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/AbortConnection.java]: We need to handle exception here.

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal [hunk 5]
```diff
@@ -92,15 +92,30 @@ public type Channel client object {
     # + queueName - The name of the queue.
     # + return - An error if an I/O error is encountered or nil if successful.
     public remote function queuePurge(string queueName) returns error? = external;
+
+    # Closes the RabbitMQ `Channel`.
+    #
+    # + closeCode - The close code (See under "Reply Codes" in the AMQP specification).
```
Comment (riyafa) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]: shall we mention the AMQP version or provide a link to the spec?

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/AbortChannel.java [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+        packageName = RabbitMQConstants.RABBITMQ,
+        functionName = "abortChannel",
+        receiver = @Receiver(type = TypeKind.OBJECT,
+                structType = RabbitMQConstants.CHANNEL_OBJECT,
+                structPackage = RabbitMQConstants.PACKAGE_RABBITMQ),
+        isPublic = true
+)
+public class AbortChannel extends BlockingNativeCallableUnit {
+
+    private static final Logger LOGGER = LoggerFactory.getLogger(Close.class);
```
Comment (riyafa) [inline stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/AbortChannel.java]: Shall we change the class name in the logger?

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/listener/RegisterListener.java [hunk 7]
```diff
@@ -96,12 +133,101 @@ public void notifyFailure(BError error) {
...
+            };
+            channel.basicConsume(queue, true, deliverCallback, consumerTag -> {
+            });
+        } catch (IOException exception) {
+            throw new BallerinaException(exception);
+        }
+    }
+
+    /**
+     * Returns messages in int format.
```
Comment (riyafa) [inline stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/listener/RegisterListener.java]: This method doesn't return anything

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/listener/RegisterListener.java [hunk 8]
```diff
@@ -96,12 +133,101 @@ public void notifyFailure(BError error) {
...
+     *
+     * @param resource Ballerina resource function.
+     * @param channel  RabbitMQ channel.
+     * @param queue    Name of the queue.
+     */
+    private void getIntMessage(Resource resource, Channel channel, String queue) {
```
Comment (riyafa) [inline stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/listener/RegisterListener.java]: Shall we rename to something like `dispatchIntMessage` since the method doesn't return anything? Shall we check all places?

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java [hunk 9]
```diff
@@ -97,18 +96,68 @@ public static Connection createConnection(BMap<String, BValue> connectionConfig)
...
+     */
+    public static void handleAbortConnection(Connection connection, BValue closeCode, BValue closeMessage,
+                                             BValue timeout) {
+        boolean validTimeout = timeout instanceof BInteger;
+        boolean validCloseCode = (closeCode instanceof BInteger) && (closeMessage instanceof BString);
+        if (!validTimeout && !validCloseCode) {
+            abortConnection(connection);
+        } else if (validTimeout && validCloseCode) {
+            abortConnection(connection,
+                    Math.toIntExact(((BInteger) closeCode).intValue()),
```
Comment (riyafa) [inline stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java]: When this method is called it may throw an `ArithmeticException`, shouldn't we be handling that as well?

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java [hunk 10]
```diff
@@ -97,18 +96,68 @@ public static Connection createConnection(BMap<String, BValue> connectionConfig)
...
+                    closeMessage.stringValue(),
+                    Math.toIntExact(((BInteger) timeout).intValue()));
+        } else if (validTimeout && !validCloseCode) {
```
Comment (chamil321) [inline stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java]:
```suggestion
        } else if (validTimeout) {
```

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java [hunk 11]
```diff
@@ -97,18 +96,68 @@ public static Connection createConnection(BMap<String, BValue> connectionConfig)
...
+            abortConnection(connection,
+                    Math.toIntExact(((BInteger) timeout).intValue()));
+        } else if (!validTimeout && validCloseCode) {
```
Comment (chamil321) [inline stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java]:
```suggestion
        } else if (validCloseCode) {
```

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java [hunk 12]
```diff
@@ -97,18 +96,68 @@ public static Connection createConnection(BMap<String, BValue> connectionConfig)
...
+            abortConnection(connection,
+                    Math.toIntExact(((BInteger) closeCode).intValue()),
+                    closeMessage.stringValue());
+        } else {
```
Comment (chamil321) [inline stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java]: Else scope is never get executed. Either you can remove it or move the content of first `if` condition here

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/BasicPublish.java (hunk 1 above)
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/BasicPublish.java]: Fixed

File: examples/rabbitmq-simple-producer/rabbitmq_simple_producer.bal (hunk 2 above)
Comment (aashikam) [reply examples/rabbitmq-simple-producer/rabbitmq_simple_producer.bal]: Fixed

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal (hunk 3 above)
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]: Fixed

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/AbortChannel.java (hunk 6 above)
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/AbortChannel.java]: Fixed

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal [hunk 13]
```diff
@@ -71,8 +71,8 @@ public type Channel client object {
     # + message - The message body.
```
[the remark this answers is not in the document]
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]: Fixed

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java (hunk 12 above)
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java]: Fixed

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java (hunk 11 above)
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java]: Fixed

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java (hunk 10 above)
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java]: Fixed

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/listener/RegisterListener.java [hunk 14]
```diff
@@ -96,12 +133,101 @@ public void notifyFailure(BError error) {
...
+     *
+     * @param resource Ballerina resource function.
+     * @param channel  RabbitMQ channel.
+     * @param queue    Name of the queue.
+     */
+    private void getFloatMessage(Resource resource, Channel channel, String queue) {
+        try {
+            DeliverCallback deliverCallback = (consumerTag, delivery) -> {
+                Executor.submit(resource, new ResponseCallback(),
+                        null, null,
```
[the remark this answers is not in the document]
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/listener/RegisterListener.java]: Fixed

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/listener/RegisterListener.java (hunk 8 above)
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/listener/RegisterListener.java]: Fixed

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/AbortConnection.java (hunk 4 above)
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/connection/AbortConnection.java]: When aborting the connection any encountered exceptions in the close operations are silently discarded.[client API guide reference here]( https://www.rabbitmq.com/releases/rabbitmq-java-client/v1.4.0/rabbitmq-java-client-javadoc-1.4.0/com/rabbitmq/client/Connection.html#abort())

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal (hunk 5 above)
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]: Added

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java (hunk 9 above)
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ConnectionUtils.java]: Resolved.

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/listener/RegisterListener.java [hunk 15]
```diff
@@ -76,11 +85,39 @@ public void execute(Context context) {
...
+                break;
+            case TypeTags.ARRAY_TAG:
+                if (((BArrayType) dataType).getElementType().getTag() == TypeTags.BYTE_TAG) {
+                    dispatchBytesMessage(onMessageResource, channel, queueName);
+                } else {
+                    throw new BallerinaException("Unsupported data type for array parameter");
+                }
+                break;
+            case TypeTags.INT_TAG:
+                dispatchIntMessage(onMessageResource, channel, queueName);
```
Comment (wggihan) [inline stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/nativeimpl/channel/listener/RegisterListener.java]: Shall we handle the possible exceptions in these methods? Can't we return ballerina errors?

File: stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ChannelUtils.java [hunk 16]
```diff
@@ -52,6 +54,75 @@ public static Channel createChannel(Connection connection) {
...
+     * Aborts the channel.
+     *
+     * @param channel RabbitMQ Channel object.
+     * @param context Context.
+     */
+    public static void abort(Channel channel, Context context) {
+        try {
+            channel.abort();
+        } catch (IOException exception) {
+            RabbitMQUtils.returnError(RabbitMQConstants.ABORT_CHANNEL_ERROR
```
[the remark this answers is not in the document]
Comment (aashikam) [reply stdlib/messaging/rabbitmq/src/main/java/org/ballerinalang/messaging/rabbitmq/util/ChannelUtils.java]: Resolved.

**Comment by riyafa** [comment]
Do you think it would be nice to have an example since we cannot write tests for RabbitMQ at the moment?

File: examples/rabbitmq-simple-consumer/rabbitmq_simple_consumer.bal [hunk 17]
```diff
@@ -6,10 +6,10 @@ rabbitmq:Connection connection = new({ host: "localhost", port: 5672 });
 
 listener rabbitmq:ChannelListener channelListener = new(connection);
 
-// Consumer service listens to the "testQueue" queue.
+// Consumer service listens to the "MyQueue" queue.
```
Comment (praneesha) [inline examples/rabbitmq-simple-consumer/rabbitmq_simple_consumer.bal]:
```suggestion
// The consumer service listens to the "MyQueue" queue.
```

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal [hunk 18]
```diff
@@ -62,17 +57,18 @@ public type Channel client object {
...
+    public remote function queueBind(string queueName, string exchangeName, string bindingKey)
+                                        returns error? = external;
 
     # Publishes a message. Publishing to a non-existent exchange will result in a channel-level
     # protocol exception, which closes the channel.
     #
-    # + routingKey - The routing key.
     # + message - The message body.
+    # + routingKey - The routing key.
     # + exchange - The name of the exchange the message is published to.
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]:
```suggestion
    # + exchange - The name of the exchange to which the message is published.
```

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal [hunk 19]
```diff
@@ -62,17 +57,18 @@ public type Channel client object {
...
     # + return - Returns an error if an I/O error is encountered or nil if successful.
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]:
```suggestion
    # + return - Returns an error if an I/O error is encountered or returns nil if successful.
```

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal [hunk 20]
```diff
@@ -92,15 +88,30 @@ public type Channel client object {
     # + queueName - The name of the queue.
     # + return - An error if an I/O error is encountered or nil if successful.
     public remote function queuePurge(string queueName) returns error? = external;
+
+    # Closes the RabbitMQ `Channel`.
+    #
+    # + closeCode - The close code (See under "Reply Codes" in the AMQP 0-9-1 specification).
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]:
```suggestion
    # + closeCode - The close code (For information, go to the"Reply Codes" section in the [AMQP 0-9-1 specification] (#https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf)).
```
Shall we link the AMQP specification from here?

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal [hunk 21]
```diff
@@ -92,15 +88,30 @@ public type Channel client object {
...
+    # + closeMessage - A message indicating the reason for closing the channel.
+    # + return - An `error` if an I/O problem is encountered.
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]:
```suggestion
    # + return - Returns an `error` if an I/O problem is encountered.
```

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal [hunk 22]
```diff
@@ -92,15 +88,30 @@ public type Channel client object {
...
+    public function close(int? closeCode = (), string? closeMessage = ()) returns error? = external;
+
+    # Aborts the RabbitMQ `Channel`.
+    # Forces the `Channel` to close and waits for all the close operations to complete.
+    # Any encountered exceptions in the close operations are silently discarded.
+    #
+    # + closeCode - The close code (See under "Reply Codes" in the AMQP 0-9-1 specification).
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]:
```suggestion
    # + closeCode - The close code (For information, go to the"Reply Codes" section in the [AMQP 0-9-1 specification] (#https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf)).
```

Shall we link the AMQP spec from here?

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal [hunk 23]
```diff
@@ -92,15 +88,30 @@ public type Channel client object {
...
+    # + closeMessage - A message indicating the reason for closing the channel.
+    # + return - An `error` if an I/O problem is encountered.
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]:
```suggestion
    # + return - Returns an `error` if an I/O problem is encountered.
```

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal [hunk 24]
```diff
@@ -92,15 +88,30 @@ public type Channel client object {
...
 };
 
 # Holds the parameters used to declare a queue.
 #
 # + queueName - The name of the queue, if not specified then autogenerated.
 # + durable - True if declaring a durable queue (the queue will survive a server restart).
 # + exclusive - True if we are declaring an exclusive queue (restricted to this connection).
-# + autoDelete - True if we are declaring an autodelete queue (server will
-# delete it when no longer in use).
+# + autoDelete - True if we are declaring an autodelete queue (server will delete it when no longer in use).
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/channel.bal]:
```suggestion
# + autoDelete - True if we are declaring an autodelete queue (server will delete it when it is no longer in use).
```

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal [hunk 25]
```diff
@@ -28,9 +28,23 @@ public type Connection object {
     # It waits with a provided timeout for all the close operations to complete.
     # When timeout is reached the socket is forced to close.
     #
+    # + closeCode - The close code (See under "Reply Codes" in the AMQP 0-9-1 specification).
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal]:
```suggestion
    # + closeCode - The close code (For information, go to the"Reply Codes" section in the [AMQP 0-9-1 specification] (#https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf)).
```
Shall we link the AMQP spec from here?

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal [hunk 26]
```diff
@@ -28,9 +28,23 @@ public type Connection object {
...
+    # + closeMessage - A message indicating the reason for closing the connection.
     # + timeout - Timeout (in milliseconds) for completing all the close-related operations, use -1 for infinity.
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal]:
```suggestion
    # + timeout - Timeout (in milliseconds) for completing all the close-related operations. Use -1 for infinity.
```

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal [hunk 27]
```diff
@@ -28,9 +28,23 @@ public type Connection object {
...
     # + return - An `error` if an I/O problem is encountered.
-    public function close(int? timeout = ()) returns error? = external;
+    public function close(int? closeCode = (), string? closeMessage = (), int? timeout = ()) returns error? = external;
+
+    # Aborts the RabbitMQ `Connection` and all it's `Channel`s.
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal]:
```suggestion
    # Aborts the RabbitMQ `Connection` and all its `Channel`s.
```

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal [hunk 28]
```diff
@@ -28,9 +28,23 @@ public type Connection object {
...
+    # Forces the `Connection` to close and waits for all the close operations to complete. When timeout is reached
+    # the socket is forced to close.
+    # Any encountered exceptions in the close operations are silently discarded.
+    #
+    # + closeCode - The close code (See under "Reply Codes" in the AMQP 0-9-1 specification).
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal]:
```suggestion
    # + closeCode - The close code (For information, go to the"Reply Codes" section in the [AMQP 0-9-1 specification] (#https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf)).
```
Shall we link the AMQP spec from here?

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal [hunk 29]
```diff
@@ -28,9 +28,23 @@ public type Connection object {
...
+    # + closeMessage - A message indicating the reason for closing the connection.
+    # + timeout - Timeout (in milliseconds) for completing all the close-related operations, use -1 for infinity.
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal]:
```suggestion
    # + timeout - Timeout (in milliseconds) for completing all the close-related operations. Use -1 for infinity.
```

File: stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal [hunk 30]
```diff
@@ -28,9 +28,23 @@ public type Connection object {
...
+    # + return - An `error` if an I/O problem is encountered.
```
Comment (praneesha) [inline stdlib/messaging/rabbitmq/src/main/ballerina/rabbitmq/connection.bal]:
```suggestion
    # + return - Returns an `error` if an I/O problem is encountered.
```
