### PR TITLE
Merge codegen with compile phases

### LINKED ISSUE #21977: Merge CreateJarTask with CompileTask
**Description:**
Currently we have a separate task for codegeneration, which is. CreateJarTask.

But ideally, we don't need a new one. We can merge this with CompileTask to have a single task to run the whole compilation to codegen.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Kishanthan**
## Purpose
This PR will merge the codegen with compile phases and now codegen will run as the final phase in the compile frontend.

Fixes #21977

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java [hunk 1]
```diff
@@ -52,18 +63,31 @@
...
-
-    private CodeGenerator(CompilerContext context) {
-
-        context.put(CODE_GEN, this);
-        symbolTable = SymbolTable.getInstance(context);
-        jvmPackageGen = JvmPackageGen.getInstance(context);
+    private PackageCache packageCache;
+    private BLangDiagnosticLogHelper dlog;
+    private BIREmitter birEmitter;
+    private boolean isBaloGen;
```
Comment (riyafa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java:70]: Shall we rename to `baloGen` or `baloGenerated` and remove `is` prefix to be consistent with other boolean variable names
```suggestion
    private boolean baloGen;
```

Comment (Kishanthan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/CodeGenerator.java]: ack

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/imports/ImportsTests.java [hunk 2]
```diff
@@ -43,42 +39,21 @@
 
     private static final String USER_HOME = "user.home";
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/imports/ImportsTests.java:40]: Why we need to change this test?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/imports/ImportsTests.java [hunk 3]
```diff
@@ -43,42 +39,21 @@
...
-    public void testVersionSupportImportFromSourceFile() throws IOException {
+    public void testVersionSupportImportFromSourceFile() {
         BaloCreator.cleanCacheDirectories();
         BaloCreator.createAndSetupBalo(imports.resolve(Paths.get("test_module1", "test_module")).toString(),
                 "testOrg", "testModule", "1.1.0");
-        birFiles = Files.find(tempBir, Integer.MAX_VALUE, (path, attribute) ->
-                path.toString().contains("testModule.bir")
-                        && !path.toString().contains("imports")).collect(Collectors.toList());
-        birDir = Files.createDirectories(homeBirCache.resolve(Paths.get("testOrg", "testModule", "1.1.0")));
-        BFileUtil.copy(birFiles.get(0), birDir.resolve(Paths.get("testModule.bir")));
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/imports/ImportsTests.java:79]: Why we need these changes in this test?

Comment (Kishanthan) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/balo/imports/ImportsTests.java:79]: Because, in test, we don't write bir binaries anymore, with the new jBallerina java rewrite. So the above lines were not needed.
