### PR TITLE
Fix class cast exception when extern function returns ballerina union type

### LINKED ISSUE #30949: CCE with Java interop
**Description:**
https://stackoverflow.com/questions/67796448/issues-calling-java-from-ballerina

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #30949

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/InstanceMethods.java [hunk 1]
```diff
@@ -151,6 +151,22 @@ public String unionWithErrorReturnHandle() throws InterruptedException {
...
 
+    public byte[] unionWithErrorReturnByteArray() throws InterruptedException {
+        byte[] byteArray = "Byte Test".getBytes();
+        if (false) {
+            throw new InterruptedException();
+        }
+        return byteArray;
+    }
+
+    public String[] unionWithErrorReturnStringArray() throws InterruptedException {
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/InstanceMethods.java:162]: Let's remove the duplicate test since we do not need the same.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/InstanceMethodTest.java [hunk 2]
```diff
@@ -266,6 +267,23 @@ public void testGetCurrentModule() {
...
+        BValue[] args = new BValue[1];
+        args[0] = new BHandleValue(testIns);
+        BRunUtil.invoke(result, function, args);
+    }
+
+    @DataProvider(name = "unionWithErrorTestFunctions")
+    public Object[][] unionWithErrorTestFunctions() {
+        return new Object[][] {
+                { "testUnionWithErrorReturnByteArray" },
+                { "testUnionWithErrorReturnByteArray" }
```
[the remark this answers is not in the document]
Comment (gabilang) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/InstanceMethodTest.java]: Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/31288/commits/d3a4640e53d1125607a5898e6dc0ffdf2b49cb1d

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/InstanceMethods.java (hunk 1 above)
Comment (gabilang) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/InstanceMethods.java]: Actually the return type of the extern function is `any|error`. Changed the function name. Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/31288/commits/d3a4640e53d1125607a5898e6dc0ffdf2b49cb1d

**Review by warunalakshitha — COMMENTED** [review]
LGTM

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/InstanceMethodTest.java [hunk 3]
```diff
@@ -266,6 +267,23 @@ public void testGetCurrentModule() {
...
+    public void testUnionWithErrorReturnArrays(String function) {
+        InstanceMethods testIns = new InstanceMethods();
+        BValue[] args = new BValue[1];
+        args[0] = new BHandleValue(testIns);
+        BRunUtil.invoke(result, function, args);
+    }
+
+    @DataProvider(name = "unionWithErrorTestFunctions")
+    public Object[][] unionWithErrorTestFunctions() {
+        return new Object[][] {
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/InstanceMethodTest.java:280]: Instead of an `Object[][]`, shall we return a `String[]` as we only use this to pass function names?

File: tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal [hunk 4]
```diff
@@ -160,6 +161,20 @@ public function interopWithAnydataReturn() returns boolean {
...
+public function interopWithHandleOrErrorReturn() {
+    handle|error handleOrError = acceptIntReturnIntArrayThrowsCheckedException(1);
+    test:assertEquals(handleOrError is error, false);
+    test:assertEquals(handleOrError is handle, true);
+
+    handleOrError = acceptIntReturnIntArrayThrowsCheckedException(5);
+    test:assertEquals(handleOrError is error, true);
+    error err = <error> handleOrError;
+    var message = err.detail()["message"];
+    string messageString = message is error ? message.toString() : message.toString();
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal:173]: The if and else parts of `is error` check seems to be the same. Do we need this?

Comment (gabilang) [reply tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal:173]: Yes, It is needed right. IIUC this is a part of Ballerina's behaviour of error checking. `err.detail()["message"]` is belongs to `ballerina/lang.value:1.0.0:Cloneable` and and actually we are expecting a string or error here (in our case it would be a string). We can't directly apply `.toString` to a `var` or `string|error` directly. That's why error check is needed. But instead of `string messageString = message is error ? message.toString() : message.toString();`, we can use `string|error messageString = <string|error> message;` also.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/InstanceMethodTest.java (hunk 3 above)
Comment (gabilang) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/InstanceMethodTest.java]: Yes, we can use `String[]` as return type in this case. Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/31288/commits/9a572075396e3bb39a8ea4c8d41cb107dcc44c78

**Review by HindujaB — APPROVED** [review]
LGTM
