### PR TITLE
Fix source pruning when getting ST from expression context

### LINKED ISSUE #32306: Parser not giving an error when parsing valid statements as expressions
**Description:**

If we parse following statement as an expression using `SyntaxTree.asExpression()`,

`int x = 1; `

Parser identifies `int` as a `BuiltinSimpleNameReferenceNode` without giving an error. 

**Affected Versions:**
slbeta2

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose

+ Introduce `io.ballerna.compiler.parser` package to expose parser internals.
+ Fix source pruning when getting ST from expression context.
+ Introduce `BalPartNode`.

Old structure: 
```
io.ballerna.compiler
├── internal
│   ├── diagnostics
│   │   ├── DiagnosticErrorCode.java
│   │   ├── DiagnosticMessageHelper.java
│   │   ├── DiagnosticWarningCode.java
│   │    ---
│   │    ---
│   ├── parser
│   │   ├── BallerinaLexer.java
│   │   ├── BallerinaParser.java
│   │   ├── ParserRuleContext.java
│   │    ---
│   │    ---
├── syntax.tree
```
New structure: 
```
io.ballerna.compiler
├── parser(This is exposed to the outside)
│   ├── diagnostics
│   │   ├── DiagnosticErrorCode.java
│   │   ├── DiagnosticWarningCode.java
│   ├── ParserRuleContext.java
│   ├── SyntaxFact.java(To be implemented in future)
├── internal
│   ├── diagnostics
│   │   ├── DiagnosticMessageHelper.java
│   │    ---
│   │    ---
│   ├── parser
│   │   ├── BallerinaLexer.java
│   │   ├── BallerinaParser.java
│   │    ---
│   │    ---
├── syntax.tree
```

Fixes #32306 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by mohanvive** [comment]
@lochana-chathura can we get this merged, please?

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/parser/ParserRuleContext.java [hunk 1]
```diff
@@ -553,6 +553,7 @@
 
     // Expressions
     EXPRESSION("expression"),
+    EXPRESSIONS("expressions"),
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/parser/ParserRuleContext.java:556]: We don't need this now, right?

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 2]
```diff
@@ -104,15 +105,53 @@ public STNode parse() {
...
      * <li>Top level node</li>
      * <li>Statement</li>
      * <li>Expression</li>
      * </ul>
      *
+     * <i>Note: This API should be limited to parser internal usage only.
+     * <br>
+     * Top level node, Statement and Expression is subject to source pruning.
+     * <br>
+     * Related issue: <a href="https://github.com/ballerina-platform/ballerina-lang/issues/32416">#32416</a>
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:148]: Are we adding TODOs like this?

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxTree.java [hunk 3]
```diff
@@ -65,29 +65,64 @@ public static SyntaxTree from(SyntaxTree oldTree, TextDocumentChange textDocumen
...
+    @Deprecated(forRemoval = true)
     public static SyntaxTree asStatements(TextDocument textDocument) {
-        return from(ParserRuleContext.STATEMENTS, textDocument);
+        return fromInternal(ParserRuleContext.STATEMENTS, textDocument);
     }
 
+    @Deprecated(forRemoval = true)
     public static SyntaxTree asExpression(TextDocument textDocument) {
-        return from(ParserRuleContext.EXPRESSION, textDocument);
+        return fromInternal(ParserRuleContext.EXPRESSION, textDocument);
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxTree.java:85]: This should use `from` right? not `fromInternal`

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxTree.java:85]: We are going to keep the old API/ behavior intact while introducing the new API which has the balPartNode. So that anything wouldn't break. With the old APIs not just asExpression() is subject to pruning. but also asTopLevel(), asStatement(), asStatements().

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/SyntaxTree.java:85]: mmm yeah, I think for #32306 to work they have to use `from` then not `asExpression` right?

**Review by rdulmina — APPROVED** [review]
