### PR TITLE
[Master] Fix Compiler crashes with CCE for int[] [...a] = [1, 2];

### LINKED ISSUE #37408: Compiler crashes with CCE for `int[] [...a] = [1, 2];`
**Description:**
```bal
public function main() {
   int[] [...a] = [1, 2]; // crashes
   io:println(a);

   [int...] [...b] = [1, 2]; // works
   io:println(b);
}
```
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
[2022-08-16 16:37:08,991] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BInvokableSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BInvokableSymbol are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.symbols.BInvokableSymbol (org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol and org.wso2.ballerinalang.compiler.semantics.model.symbols.BInvokableSymbol are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.desugar.Desugar.createLengthInvocation(Desugar.java:2625)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.createRestFieldVarDefStmts(Desugar.java:1670)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1532)
        at org.wso2.ballerinalang.compiler.tree.BLangTupleVariable.accept(BLangTupleVariable.java:57)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8460)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1596)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangTupleVariableDef.accept(BLangTupleVariableDef.java:45)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8460)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8498)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8504)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1353)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8460)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1399)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8460)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8511)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:804)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8460)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:459)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:447)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:381)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:169)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:122)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```        
</details>

**Affected Versions:**
2201.1.1

### PR DESCRIPTION
**Pull request by SasinduDilshara**
Fixes #37408

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 1]
```diff
@@ -2567,10 +2567,13 @@ boolean checkTypeAndVarCountConsistency(BLangTupleVariable varNode, BTupleType t
                 case TypeTags.ARRAY:
                     List<BType> tupleTypes = new ArrayList<>();
                     BArrayType arrayType = (BArrayType) referredType;
+                    tupleTypeNode = new BTupleType(tupleTypes);
+                    if (varNode.restVariable != null) {
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:2571]: Moving this if block after the for loop is more cleaner

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_test.bal [hunk 2]
```diff
@@ -178,6 +178,30 @@ function testSubTypingWithRestDescriptorNegative() {
     assertFalse(v2 is [string, string, string, string]);
 }
 
+function testRestVariablesWithArray() {
+    int[] [...a] = [1, 2];
+    int[] _ = a;
+    assertEquality(a, <int[]>[1, 2]);
```
Comment (KavinduZoysa) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_test.bal:184]: Why do we need this cast?

Comment (KavinduZoysa) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_test.bal:184]: Why do we need this cast?

Comment (rdulmina) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_test.bal:184]: I think this because the CET of `[1, 2]` will be `any` without the cast then the first if of the `assertEquality` method will not be true and the test will fail. We can fix this if we r able to change the param type of `assertEquality` to `anydata`?

Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_test.bal:184]: It is because to verify that the type is exactly same. [1, 2] is a tuple in default I guess, So test will not pass.

Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_test.bal:184]: Please refer to this thread. https://github.com/ballerina-platform/ballerina-lang/pull/37784#discussion_r976019099

Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_test.bal:184]: Then how to use `assertEquality` for types other than `anydata`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 3]
```diff
@@ -2567,10 +2567,13 @@ boolean checkTypeAndVarCountConsistency(BLangTupleVariable varNode, BTupleType t
...
+                        tupleTypeNode.restType = arrayType.eType;
```
[the remark this answers is not in the document]
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: Updated. 6bbd11e31ea08006fe819b0957239a02cacc981b

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 1 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: Updated. 6bbd11e31ea08006fe819b0957239a02cacc981b

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_test.bal (hunk 2 above)
Comment (rdulmina) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_test.bal:184]: If we can't change the param type it will be fine right @KavinduZoysa?

Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_rest_descriptor_test.bal:184]: Yes, let's keep it

**Review by KavinduZoysa — APPROVED** [review]

**Review by rdulmina — APPROVED** [review]
