### PR TITLE
[LS] Add constant symbol completions to enum member context

### LINKED ISSUE #30937: No completions provided for enum member decalaration
**Description:**
$subject

**Steps to reproduce:**

```ballerina
const string superStr = "SUPER";

public enum NodeType {
    # Super
    SUPER_NODE = ,
    # Peer
    PEER_NODE = "PEER"
}
```

**Affected Versions:**
slbeta1-rc8

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject

Fixes #30937 

## Samples
sol

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumMemberNodeContext.java [hunk 1]
```diff
@@ -32,13 +34,17 @@
...
         super(EnumMemberNode.class);
     }
 
     @Override
     public List<LSCompletionItem> getCompletions(BallerinaCompletionContext ctx, EnumMemberNode node)
             throws LSCompletionException {
-        return Collections.emptyList();
+        List<Symbol> visibleSymbols = ctx.visibleSymbols(ctx.getCursorPosition());
+        List<Symbol> filteredSymbols = visibleSymbols.stream()
+                .filter(symbol -> symbol.kind() == SymbolKind.CONSTANT).collect(Collectors.toList());
```
Comment (pubudu91) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumMemberNodeContext.java:47]: Shouldn't this further be filtered to consider only the string constants? Since that's the only valid type of constants for enum members.

Comment (pubudu91) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumMemberNodeContext.java:47]: You can use the `broaderTypeDescriptor()` method in `ConstantSymbol` for this.

**Review by IMS94 — APPROVED** [review]
LGTM!

**Review by pubudu91 — DISMISSED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumMemberNodeContext.java [hunk 2]
```diff
@@ -32,13 +36,19 @@
...
     @Override
     public List<LSCompletionItem> getCompletions(BallerinaCompletionContext ctx, EnumMemberNode node)
             throws LSCompletionException {
-        return Collections.emptyList();
+        List<Symbol> visibleSymbols = ctx.visibleSymbols(ctx.getCursorPosition());
+        List<Symbol> filteredSymbols = visibleSymbols.stream()
+                .filter(symbol -> symbol.kind() == SymbolKind.CONSTANT
+                        && ((ConstantSymbol) symbol).broaderTypeDescriptor().typeKind() == TypeDescKind.STRING)
+                .collect(Collectors.toList());
+        return this.getCompletionItemList(filteredSymbols, ctx);
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumMemberNodeContext.java:52]: We need to add the module suggestions as well as the constants coming from the modules,
Eg:
```
enum Test {
    MEMBER1 = <cursor1>
    MEMBER2 = module1:<cursor2>
}
```

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumMemberNodeContext.java [hunk 3]
```diff
@@ -32,13 +43,42 @@
...
-        return Collections.emptyList();
+        List<LSCompletionItem> completionItems = new ArrayList<>();
+        NonTerminalNode nodeAtCursor = ctx.getNodeAtCursor();
+        List<Symbol> visibleSymbols = new ArrayList<>();
+        if (!inEnumMemberValueContext(ctx, node)) {
+            return completionItems;
+        }
+        if (QNameReferenceUtil.onQualifiedNameIdentifier(ctx, nodeAtCursor)) {
+            QualifiedNameReferenceNode nameRef = (QualifiedNameReferenceNode) nodeAtCursor;
+            Predicate<Symbol> filter = symbol -> symbol.kind() == SymbolKind.CONSTANT
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumMemberNodeContext.java:62]: You can reuse this filter in both cases. Shall we refactor?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumMemberNodeContext.java (hunk 3 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumMemberNodeContext.java]: done!

**Review by nadeeshaan — APPROVED** [review]
LGTM
