### PR TITLE
Fix direct return of byte binary operation in a lambda

### LINKED ISSUE #22168: JVM Bytecode Generation Failure with "Bad type on operand stack"
In Ballerina v1.2.0, the attached program crashes at application startup. I'm attaching here the Ballerina source code, and also the "ballerina-internal.log" that is generated. The error starts with "Bad type on operand stack" in the log. 
[code-and-logs.zip](https://github.com/ballerina-platform/ballerina-lang/files/4379059/code-and-logs.zip)

### PR DESCRIPTION
**Pull request by Kishanthan**
## Purpose
This PR fixes the issue of direct return of byte binary operation in a lambda.

An example :
```ballerina
public function main() {
    var fn = function () returns int {
        byte a = 255;
        return a - a;
    };
}
```

Fixes #22168

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java [hunk 1]
```diff
@@ -792,4 +792,34 @@ private void invokeBitwisePrecedenceTestFunctionForInt(int a, int b, int c, Stri
         BInteger bInteger = (BInteger) returns[0];
         Assert.assertEquals(bInteger.intValue(), expected, "Invalid byte value returned.");
     }
+
+    @Test(description = "Test byte value return as int in lambda 1")
+    public void testByteReturnAsIntInLambda1() {
+        BValue[] returns = BRunUtil.invoke(result, "testByteReturnAsIntInLambda1");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java:798]: With new lang tests we've tried writing the tests in Ballerina itself as much as possible.

For example https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_infer_type.bal#L55

We can rewrite these tests similarly right?

Comment (Kishanthan) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java:798]: looks like you have to repeat the assertEquality method for each new test ?

Comment (Kishanthan) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java:798]: And yes, we can write that in the new style. The thing is all the other methods are written in the old way. May be we have to add a new bal test file with these new tests.

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java:798]: For the time-being yes, the `assertEquality` function has to be repeated in each test file. But once the compiler test suite is done we can directly switch to calling a similar (most-likely the same) function in that particular module.

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java:798]: Yeah, there is some inconsistency when adding tests to an existing file. But even then, IMO it's kinda OK given that we usually add new tests at the end?

I'm OK with either approach.

Comment (Kishanthan) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java]: Updated the tests :)

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/bytetype/BByteValueTest.java]: Great, thanks!
