### PR TITLE
Fix XML serialization issues in 1.2.X branch

### LINKED ISSUE #35404: [1.2.X] XML serialization bug
**Description:**
This seems to be fixed in swanlake track, but present in the 1.2.X track.

```ballerina
import ballerina/io;
import ballerina/lang.'xml;

public function main() returns error? {
    string x = "<A xmlns=\"abc\"><B xmlns=\"\"/><B xmlns=\"\"/><B xmlns=\"\"/></A>";
    xml y = check 'xml:fromString(x);
    io:println(y);
}
```

Expected result: `<A xmlns="abc"><B xmlns=""/><B xmlns=""/><B xmlns=""/></A>`
1.2.25 result.     : `<A xmlns="abc"><B xmlns=""/><B/><B/></A>`

**Steps to reproduce:**

**Affected Versions:**
1.2.x
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by SandaruJayawardana**
Fixes #35404

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by SandaruJayawardana** [comment]
Here, I have fixed the reported issue with updating the `BallerinaXMLSerializer` using the fixes which are already done in SL branch. I have noticed that, there are few more fixes (ex. https://github.com/ballerina-platform/ballerina-lang/pull/33925) had been done in SL branch related to XML serialization. Some are causes to change the current behavior. Shall we add those fixes here also? @rdhananjaya

**Comment by rdhananjaya** [comment]
> Here, I have fixed the reported issue with updating the `BallerinaXMLSerializer` using the fixes which are already done in SL branch. I have noticed that, there are few more fixes (ex. #33925) had been done in SL branch related to XML serialization. Some are causes to change the current behavior. Shall we add those fixes here also? @rdhananjaya

We should port those fixes to `1.2.x` branch, but if we should port them now or separately depends on in which way we going to deliver this fix, if we are just releasing a patch with this fix I don't think we should fix them in this PR.
@hasithaa @gimantha thoughts?

**Comment by gimantha** [comment]
> > Here, I have fixed the reported issue with updating the `BallerinaXMLSerializer` using the fixes which are already done in SL branch. I have noticed that, there are few more fixes (ex. #33925) had been done in SL branch related to XML serialization. Some are causes to change the current behavior. Shall we add those fixes here also? @rdhananjaya
> 
> We should port those fixes to `1.2.x` branch, but if we should port them now or separately depends on in which way we going to deliver this fix, if we are just releasing a patch with this fix I don't think we should fix them in this PR. @hasithaa @gimantha thoughts?

Almost all of them are spec deviation AFAIK. I hope, sending breaking changes with a patch is ok then right?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaXMLSerializer.java [hunk 1]
```diff
@@ -169,24 +178,30 @@ private void writeElement(XMLItem xmlValue) throws XMLStreamException {
     private String setDefaultNamespace(Map<String, String> nsPrefixMap, QName qName, HashSet<String> currentNSLevel)
             throws XMLStreamException {
         boolean elementNSUsageFoundInAttribute = false;
-        String defaultNsUri = (qName.getPrefix() == null || qName.getPrefix().isEmpty()) ? qName.getNamespaceURI() : "";
+//        String defaultNsUri = (qName.getPrefix() == null || qName.getPrefix().isEmpty()) ? qName.getNamespaceURI() : "";
```
Comment (rdhananjaya) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaXMLSerializer.java:181]: Let's remove this line

**Comment by hasithaa** [comment]
@rdhananjaya We discussed including all changes that were done to the XML serializer with this patch.

File: stdlib/jsonutils/src/test/java/org/ballerinalang/stdlib/jsonutils/JsonUtilsTest.java [hunk 2]
```diff
@@ -179,9 +179,9 @@ public void testComplexXMLtoJson() {
                         "\"Count\":\"7\"}}, \"\\n        \"]}, \"\\n        \", {\"Address\":[\"\\n            \", " +
                         "{\"StreetAddress\":\"20, Palm grove, Colombo 3\"}, \"\\n            \", " +
                         "{\"City\":\"Colombo\"}, \"\\n            \", {\"Zip\":\"00300\"}, \"\\n            \", " +
-                        "{\"Country\":\"LK\"}, \"\\n        \"], \"@xmlns:\":\"\", \"@\":\"\"}, \"\\n    \"], " +
-                        "\"@xmlns:ns\":\"ns.com\", \"@xmlns:\":\"example.com\", \"@attr\":\"attr-val\", " +
-                        "\"@ns:attr\":\"ns-attr-val\", \"@ns\":\"ns.com\", \"@\":\"example.com\"}}");
+                        "{\"Country\":\"LK\"}, \"\\n        \"], \"@xmlns\":\"\"}, \"\\n    \"], " +
+                        "\"@xmlns:ns\":\"ns.com\", \"@xmlns\":\"example.com\", \"@attr\":\"attr-val\", " +
+                        "\"@ns:attr\":\"ns-attr-val\", \"@ns\":\"ns.com\"}}");
```
Comment (SandaruJayawardana) [inline stdlib/jsonutils/src/test/java/org/ballerinalang/stdlib/jsonutils/JsonUtilsTest.java:184]: Since this test is failing due to the changes, I have replaced the expected output with current output. @rdhananjaya can you have a look whether this is correct or not?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaXMLSerializer.java [hunk 3]
```diff
@@ -54,14 +55,22 @@
...
     private Deque<Set<String>> parentNSSet;
     private int nsNumber;
+    private boolean withinElement;
 
     static {
         xmlOutputFactory = XMLOutputFactory.newInstance();
         if (xmlOutputFactory.getClass().getName().equals("com.ctc.wstx.stax.WstxOutputFactory")) {
             xmlOutputFactory.setProperty(WstxOutputProperties.P_OUTPUT_VALIDATE_STRUCTURE, false);
+        } else {
+        xmlOutputFactory.setProperty("escapeCharacters", false);
```
Comment (rdhananjaya) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaXMLSerializer.java:72]: need indentation

File: stdlib/jsonutils/src/test/java/org/ballerinalang/stdlib/jsonutils/JsonUtilsTest.java (hunk 2 above)
Comment (rdhananjaya) [reply stdlib/jsonutils/src/test/java/org/ballerinalang/stdlib/jsonutils/JsonUtilsTest.java:184]: Looks like we had a bug and with this change, it's fixed.

**Comment by rdhananjaya** [comment]
Changes to look good to me. Added a comment on minor aesthetic improvement.

File: stdlib/jsonutils/src/test/java/org/ballerinalang/stdlib/jsonutils/JsonUtilsTest.java (hunk 2 above)
Comment (SandaruJayawardana) [reply stdlib/jsonutils/src/test/java/org/ballerinalang/stdlib/jsonutils/JsonUtilsTest.java:184]: Ack. Thanks.

**Review by rdhananjaya — APPROVED** [review]
