### PR TITLE
Fix nested conditional expr ambiguity resolution

### LINKED ISSUE #33215: [Parser] In a chained conditional-expr var ref used as the false-exp parsed incorrectly
**Description:**
```ballerina
    int n = 10;
    int res = 5 == 5 ? 10 < 5 ? 100 : n : -1; // getting undefined module 'n'
    _ = 5 == 5 ? (10 < 5 ? 100 : n) : -1; //works
```

**Steps to reproduce:**

**Affected Versions:**
SL Beta 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #33682: Parser does not support nested ternary expressions
**Description:**
$title.

**Steps to reproduce:**
```ballerina
boolean cond = true;
int x5 = 1;
int y5 = 10;
int b11 = cond? cond? cond? y5 : x5 : x5 : x5; // not support
int b12 = cond? cond? (cond? y5 : x5) : x5 : x5; // support
```
**Affected Versions:**
SL Beta3

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #33215
Fixes #33682 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -12972,52 +12972,85 @@ private STNode parseConditionalExpression(STNode lhsExpr) {
         // parsing conditional expr. That is done by lowering the current precedence.
         STNode middleExpr = parseExpression(OperatorPrecedence.ANON_FUNC_OR_LET, true, false, true);
 
+        // There are special cases when the nextToken is not `:`. Any expression that contains qualified name ref at
+        // the beginning or at the end, is a possible match for conditionalExpr.
         if (peek().kind != SyntaxKind.COLON_TOKEN) {
-            // There are special cases when the nextToken is not `:`. Any expression that contains qualified name ref at
-            // the beginning or at the end, is a possible match for conditionalExpr.
+            if (middleExpr.kind == SyntaxKind.CONDITIONAL_EXPRESSION) {
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:12978]: Can't we simply do this by passing `isInConditionalExpr` argument to `parseConditionalExpression`

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:12979]: No help from `isInConditionalExpr` here. 
But we can use it to replace the 
`boolean isInConditionalExpr = this.errorHandler.getParentContext() == ParserRuleContext.CONDITIONAL_EXPRESSION;`

Updated with b737fab

**Review by rdulmina — APPROVED** [review]

**Review by hasithaa — APPROVED** [review]
