### PR TITLE
[Testerina] Add path fixes for ballerina file code coverage

### LINKED ISSUE #28771: [Testerina] Analyse on the file format to use for code coverage
**Description:**
Do a analysis of lcov and jacoco.xml as the common file format that can be pluggable to CICD tools, VSCode. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Dilhasha**
## Purpose

Add path fixes for ballerina file code coverage to support seamless integration to external tools.

Fixes #28771

## Approach
Add path fixes for ballerina file code coverage to support seamless integration to external tools.

Tested for the following cases:

- Package with only default module
- Package with a single module
- Package with multiple modules
- Package with hierarchical module names

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/NormalizedCoverageClass.java [hunk 1]
```diff
@@ -0,0 +1,143 @@
+package org.ballerinalang.test.runtime.entity;
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/NormalizedCoverageClass.java:1]: Missing license header

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java [hunk 2]
```diff
@@ -162,10 +165,32 @@ private CoverageBuilder analyzeStructure() throws IOException {
...
+     *
+     * @param classesList Collection<IClassCoverage>
+     * @return Collection<IClassCoverage>
+     */
+    private Collection<IClassCoverage> modifyClasses(Collection<IClassCoverage> classesList) {
+        Collection<IClassCoverage> modifiedClasses = new ArrayList<>();
+        for (IClassCoverage classCoverage : classesList) {
+            if (classCoverage.getSourceFileName() != null) {
+                //Normalize package name and class name for classes generated for bal files
+                IClassCoverage modifiedClass = new NormalizedCoverageClass(classCoverage,
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java:183]: Shall we rename this to `modifiedClassCoverage`

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java [hunk 3]
```diff
@@ -355,18 +380,56 @@ private Document getDocumentFromModule(Module moduleInstance, String sourceFileN
...
 
+    private String normalizeFileName(String fileName) {
+        String orgName = IdentifierUtils.encodeNonFunctionIdentifier(
+                this.module.packageInstance().packageOrg().toString());
+        //Get package instance and traverse through all the modules
+        for (Module module : this.module.packageInstance().modules()) {
+            String sourceRoot;
+            String packageName;
+            if (module.isDefaultModule()) {
+                packageName = IdentifierUtils.encodeNonFunctionIdentifier(
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java:407]: This can be taken out of the condition

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java [hunk 4]
```diff
@@ -355,18 +380,56 @@ private Document getDocumentFromModule(Module moduleInstance, String sourceFileN
...
+                        module.packageInstance().packageName().toString());
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java:408]: We can use `module.moduleName()` which will work for both default and non-default module.

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java [hunk 5]
```diff
@@ -355,18 +380,56 @@ private Document getDocumentFromModule(Module moduleInstance, String sourceFileN
...
+                sourceRoot = module.project().sourceRoot().getFileName().toString();
+            } else {
+                packageName = IdentifierUtils.encodeNonFunctionIdentifier(module.descriptor().name().toString());
+                sourceRoot = module.project().sourceRoot().getFileName().toString() + "/modules/" +
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java:412]: `"/modules/"` can be replaced with `ProjectConstants.MODULES_ROOT`

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/NormalizedCoverageClass.java [hunk 6]
```diff
@@ -0,0 +1,160 @@
...
+    }
+
+    @Override
+    public String[] getInterfaceNames() {
+        return oldClassCoverage.getInterfaceNames();
+    }
+
+    @Override
+    public String getPackageName() {
+        if (this.normalizedPackageName != null) {
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/NormalizedCoverageClass.java:72]: Let's add a comment explaining why it can be null.

File: tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/CodeCoverageReportTest.java [hunk 7]
```diff
@@ -0,0 +1,258 @@
...
+import java.util.HashMap;
+import java.util.List;
+
+import javax.xml.parsers.DocumentBuilder;
+import javax.xml.parsers.DocumentBuilderFactory;
+import javax.xml.parsers.ParserConfigurationException;
+
+/**
+ * Test class to test report using a ballerina project.
+ */
```
Comment (azinneera) [inline tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/CodeCoverageReportTest.java:47]: @since 2.0.0

**Review by azinneera — APPROVED** [review]
LGTM

**Review by azinneera — APPROVED** [review]
