### PR TITLE
Fix offline resolution of build tools

### LINKED ISSUE #43914: [Bug]: Offline resolution of build tools fails
### Description

Build tools specified in the `Ballerina.toml` are not resolvable offline. The build has to always be an online one. This is only for tools that are resolved from the Ballerina Central.

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by azinneera**
Fixes #43914 

## Approach

When a tool is resolved for the first time, during an online build, the tool version is recorded in the `~/.ballerina/.config/bal-tools.toml`. The entry contains the package `org`, `name`, and `version` information. 

For offline builds on fresh projects (No `Dependencies.toml`), this entry is used to get the package `org` and the `name`. For other projects, the version recorded in the `Dependencies.toml` is used.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [x] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [x] Added necessary documentation  
  - [x] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by gayaldassanayake** [comment]
Manually tested and it is working as expected.

**Review by gayaldassanayake — APPROVED** [review]

File: cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BaseCommandTest.java [hunk 1]
```diff
@@ -61,6 +68,16 @@ public void setup() throws IOException {
         this.printStream = new PrintStream(this.console);
     }
 
+    @BeforeSuite
+    public void copyBalTools() throws IOException {
+        // copy the bal-tools.toml to <user-home>/.ballerina/.config/
+        Path balToolsTomlSrcPath = Paths.get("src/test/resources/test-resources/" +
```
Comment (keizer619) [inline cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BaseCommandTest.java:74]: @azinneera Shall we use path separator instead of `/`?

Comment (azinneera) [reply cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BaseCommandTest.java:74]: The `Path.get` api takes care of the OS when constructing the path.
