### PR TITLE
Limit constants from using '_' as identifier

### LINKED ISSUE #18157: _ is allowed on const
**Description:**
Following is doesn't give a compiler error. 

**Steps to reproduce:**
```
const _ = 10;

public function main(string... args) {
}
```

Tested on ballerina-1.0.0-Alpha3

### PR DESCRIPTION
**Pull request by irshadnilam**
## Purpose
$title

Fixes #18157

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java [hunk 1]
```diff
@@ -420,6 +420,7 @@
     CANNOT_UPDATE_CONSTANT_VALUE("cannot.update.constant.value"),
     CANNOT_ASSIGN_VALUE_TO_CONSTANT("cannot.assign.value.to.constant"),
     CANNOT_DEFINE_CONSTANT_WITH_TYPE("cannot.define.constant.with.type"),
+    CANNOT_DEFINE_CONSTANT_WITH_IDENTIFIER("cannot.define.constant.with.identifier"),
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java]: We already have a `UNDERSCORE_NOT_ALLOWED` error, how about re-using that instead? The error would be "underscore is not allowed here". @hasithaa 

If we need a separate error shall we change this to
```suggestion
    CANNOT_DEFINE_CONSTANT_WITH_UNDERSCORE("cannot.define.constant.with.underscore"),
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 2]
```diff
@@ -2280,6 +2280,11 @@ public void visit(BLangForever foreverStatement) {
 
     @Override
     public void visit(BLangConstant constant) {
+        Name constantName = names.fromIdNode(constant.name);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: We use this variable only in L2284 right? 

How about we define a variable for `constant.name` instead, since that seems to be used several times.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 3]
```diff
@@ -2280,6 +2280,11 @@ public void visit(BLangForever foreverStatement) {
...
+        if (constantName == Names.IGNORE) {
+            dlog.error(constant.name.pos, DiagnosticCode.CANNOT_DEFINE_CONSTANT_WITH_IDENTIFIER, constant.name);
+            return;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: Do we need the return here? We can allow the next check also right?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 4]
```diff
@@ -1138,6 +1138,9 @@ error.cannot.assign.value.to.constant=\
 error.cannot.define.constant.with.type=\
   constant cannot be defined with type ''{0}'', expected a simple basic types or a map of a simple basic type
 
+error.cannot.define.constant.with.identifier=\
+  constant cannot be defined with identifier ''{0}''
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties]: Again, if we are going with a new error I think we can change this to something like
```suggestion
  constant cannot be defined with ''_''
```

since ''{0}'' will always be ''_''

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java (hunk 1 above)
Comment (hasithaa) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java]: +1, better to use "underscore is not allowed here"

Comment (irshadnilam) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java]: Fixed. Used "Underscore not allowed" message

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 3 above)
Comment (irshadnilam) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: Fixed.
