### PR TITLE
Increase the scope of the `Add isolated qualifier` code action

### LINKED ISSUE #42323: [Bug]: The `Add isolated qualifier` CA does not work within a lock statement
### Description

The respective CA is not provided when we execute a non-isolated function within a lock statement, as shown below.

image

### Steps to Reproduce

```ballerina
isolated int i = 32;

function nonIsolatedFn() returns int => 12;

function name() {
    lock {
        i = nonIsolatedFn<CURSOR>();
    }
}
```

### Affected Version(s)

Ballerina 2201.8.5 (Swan Lake Update 8)

### OS, DB, other environment details and versions

OS: macOS 14.2.1 23C71
JDK: openjdk 17.0.8 2023-07-18

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by nipunayf**
## Purpose
Currently, the respective CA only supports text edits to fix the diagnostics: `BCE3946` and `BCE3947`. With this PR, the CA provides the necessary text edits to solve `BCE3950` and `BCE3961`, i.e.

1. Quick fix for using non-isolated functions within the `lock` statement.
2. Quick fix for using non-isolated initializers within an isolated function.

Fixes #42323

### Fixing non-isolated functions within the `lock` statement
https://github.com/ballerina-platform/ballerina-lang/assets/59343084/76aeaba3-f870-4f56-b720-08e757efa135

### Fixing non-isolated initializers within an isolated function
https://github.com/ballerina-platform/ballerina-lang/assets/59343084/6bdf7a96-d794-4d08-8271-25546c2cd129

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddIsolatedQualifierCodeAction.java [hunk 1]
```diff
@@ -68,56 +75,89 @@ public boolean validate(Diagnostic diagnostic,
...
+        return getCodeAction(context, functionDefinitionNode.functionKeyword(), symbol.get().getName().orElse(""),
+                filePath.get().toUri().toString());
     }
 
-    private List<CodeAction> getExplicitAnonFuncExpressionCodeAction(ExplicitAnonymousFunctionExpressionNode node,
-                                                                     CodeActionContext context) {
-        Position position = PositionUtil.toPosition(node.functionKeyword().lineRange().startLine());
-        Range range = new Range(position, position);
+    private static Optional<Symbol> getReferredSymbol(CodeActionContext context, NonTerminalNode node) {
+        if (node.kind() == SyntaxKind.EXPLICIT_NEW_EXPRESSION || node.kind() == SyntaxKind.IMPLICIT_NEW_EXPRESSION) {
```
Comment (KavinduZoysa) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddIsolatedQualifierCodeAction.java:125]: Let's extract `node.kind()` into a variable.

File: language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/source/isolatedFunctionCodeAction/modules/module2/add_isolated_qualifier_source2.bal [hunk 2]
```diff
@@ -2,3 +2,45 @@ isolated function bar() {
     testFunction();
     return;
 }
+
```
Comment (KavinduZoysa) [inline language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/source/isolatedFunctionCodeAction/modules/module2/add_isolated_qualifier_source2.bal:5]: Is there any perticular reason to only have tests in module?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddIsolatedQualifierCodeAction.java [hunk 3]
```diff
@@ -68,56 +75,90 @@ public boolean validate(Diagnostic diagnostic,
...
     }
 
-    private List<CodeAction> getExplicitAnonFuncExpressionCodeAction(ExplicitAnonymousFunctionExpressionNode node,
-                                                                     CodeActionContext context) {
-        Position position = PositionUtil.toPosition(node.functionKeyword().lineRange().startLine());
-        Range range = new Range(position, position);
+    private static Optional<Symbol> getReferredSymbol(CodeActionContext context, NonTerminalNode node) {
+        SyntaxKind kind = node.kind();
+        if (kind == SyntaxKind.EXPLICIT_NEW_EXPRESSION || kind == SyntaxKind.IMPLICIT_NEW_EXPRESSION) {
+            try {
```
Comment (KavinduZoysa) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddIsolatedQualifierCodeAction.java:127]: Why do we need this try-catch block?

File: language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/source/isolatedFunctionCodeAction/modules/module2/add_isolated_qualifier_source2.bal (hunk 2 above)
Comment (nipunayf) [reply language-server/modules/langserver-core/src/test/resources/codeaction/add-isolated-qualifier/source/isolatedFunctionCodeAction/modules/module2/add_isolated_qualifier_source2.bal:5]: We have the tests in a package so that we can test modifications happening on different files.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddIsolatedQualifierCodeAction.java (hunk 3 above)
Comment (nipunayf) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddIsolatedQualifierCodeAction.java:127]: All the exit paths of the instructions within the block follow the same recovery logic. This approach is more convenient and readable than having to check at each line.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddIsolatedQualifierCodeAction.java [hunk 4]
```diff
@@ -68,56 +75,90 @@ public boolean validate(Diagnostic diagnostic,
...
+                return Optional.of(definition.initMethod().orElseThrow());
+            } catch (RuntimeException e) {
+                assert false : "This line is unreachable because the diagnostic is not produced otherwise.";
+                return Optional.empty();
+            }
+        }
+        return context.currentSemanticModel().flatMap(semanticModel -> semanticModel.symbol(node));
+    }
+
+    private static List<CodeAction> getCodeAction(CodeActionContext context, Token functionKeyword,
```
Comment (KavinduZoysa) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AddIsolatedQualifierCodeAction.java:141]: `context` is not used.

**Review by KavinduZoysa — APPROVED** [review]
