### PR TITLE
Fix locations bugs in Toml Parser AST

### LINKED ISSUE #28762: [TomlParser] Location becomes `null` for nested TOML table nodes
**Description:**
The location of `TomlNode` becomes null for the middle level tables when there's a complex nested TOML table

**Steps to reproduce:**
For toml context 
```toml
[main]
a = 12
```
The following TomlNode is received.
NotNull

But for this context 
```toml
[main]
a.b = 12
```
The TomlNode is as follows.
Null

Please note that the location of TableNode `a` is null. 
We should have the location for all nodes regardless of the TOML structure. 

- In addition, the `toString()` of some Toml nodes returns an NPE. This can be seen in above screenshots.

**Affected Versions:**
alpha1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
blocker for #28711 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by xlight05**
## Purpose
This PR fixes various occasions Location field of AST becomes null. 
This includes dotted keys, Table Array nodes generated tables and key lists.

This PR also few NPEs on toString as well caused by null keys in anonymous tables.

Resolves #28762 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java [hunk 1]
```diff
@@ -457,4 +489,20 @@ public TomlNode transform(BoolLiteralNode boolLiteralNode) {
     public TomlNode transform(IdentifierLiteralNode identifierLiteralNode) {
         return new TomlUnquotedKeyNode(identifierLiteralNode.value().text(), getPosition(identifierLiteralNode));
     }
+
+    private TomlNodeLocation getLocationOfKeyEntryList(List<TomlKeyEntryNode> keys) {
+        if (keys.size() == 0) {
+            return null;
+        }
+        int startOffset = keys.get(0).location().textRange().startOffset();
```
Comment (lochana-chathura) [inline misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java:497]: `keys.get(0).location()` is repeatedly used within the method. Shall we extract it to a variable?

File: misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java [hunk 2]
```diff
@@ -457,4 +489,20 @@ public TomlNode transform(BoolLiteralNode boolLiteralNode) {
...
+        int length = 0;
+        for (TomlKeyEntryNode entryNode : keys) {
+            length += entryNode.location().textRange().length() + 1;
+        }
+        TextRange textRange = TextRange.from(startOffset, length - 1);
+        LineRange lineRange = LineRange
+                .from(keys.get(0).location().lineRange().filePath(), keys.get(0).location().lineRange().startLine(),
+                        keys.get(keys.size() - 1).location().lineRange().endLine());
```
Comment (lochana-chathura) [inline misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java:505]:
```suggestion
        LineRange lineRange = LineRange.from(
                        keys.get(0).location().lineRange().filePath(), 
                        keys.get(0).location().lineRange().startLine(),
                        keys.get(keys.size() - 1).location().lineRange().endLine()
        );
```

File: misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java [hunk 3]
```diff
@@ -74,7 +77,9 @@ public TomlNode transform(DocumentNode documentNode) {
     }
 
     private TomlTableNode createRootTable(DocumentNode modulePartNode) {
-        TomlKeyNode tomlKeyNode = new TomlKeyNode(null);
+        TomlKeyEntryNode root = new TomlKeyEntryNode(new TomlUnquotedKeyNode("__root", getPosition(modulePartNode)));
+        List<TomlKeyEntryNode> tomlKeyEntryNodes = Collections.singletonList(root);
+        TomlKeyNode tomlKeyNode = new TomlKeyNode(tomlKeyEntryNodes, getLocationOfKeyEntryList(tomlKeyEntryNodes));
         return new TomlTableNode(tomlKeyNode, getPosition(modulePartNode));
```
Comment (lochana-chathura) [inline misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java:83]: `getPosition(modulePartNode)` is repeated. 
Also in L82, wouldn't the location is the same as `getPosition(modulePartNode)`? Do we need to calculate it again with `getLocationOfKeyEntryList()`?

File: misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java [hunk 4]
```diff
@@ -114,13 +119,14 @@ private void addChildKeyValueToParent(TomlTableNode rootTable, TomlKeyValueNode
...
-                parentTable = createDottedKeyParentTable(parentTable, tomlKeyEntryNode);
+                parentTable =
+                        createDottedKeyParentTable(parentTable, tomlKeyEntryNode, transformedKeyValuePair.location());
             }
         }
         if (isDottedKey(keys)) {
             List<TomlKeyEntryNode> list = new ArrayList<>();
             list.add(keys.get(keys.size() - 1));
-            TomlKeyNode newKey = new TomlKeyNode(list);
+            TomlKeyNode newKey = new TomlKeyNode(list, getLocationOfKeyEntryList(list));
```
Comment (lochana-chathura) [inline misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java:129]: Here also we only have one member.  Can use getPosition() to get the location.

File: misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java [hunk 5]
```diff
@@ -457,4 +491,22 @@ public TomlNode transform(BoolLiteralNode boolLiteralNode) {
     public TomlNode transform(IdentifierLiteralNode identifierLiteralNode) {
         return new TomlUnquotedKeyNode(identifierLiteralNode.value().text(), getPosition(identifierLiteralNode));
     }
+
+    private TomlNodeLocation getLocationOfKeyEntryList(List<TomlKeyEntryNode> keys) {
```
Comment (lochana-chathura) [inline misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java:495]: I think we can get rid of this method. When getting the locations we can always get them from the syntax tree itself. 
Here what we do is creating locations from the AST nodes. This is prone to error. 

e.g. Suppose the order of the `TomlKeyEntryNode` nodes in the list is wrong. 
Then the new location would be messed up.

In the ST, the user's input order is always preserved whereas in AST it is not the case.

**Review by lochana-chathura — APPROVED** [review]

**Review by lochana-chathura — CHANGES_REQUESTED** [review]
Sorry. Approved by mistake. Shall we address the comments :)

File: misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java (hunk 5 above)
Comment (xlight05) [reply misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java]: Did as we discussed. :)

File: misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java [hunk 6]
```diff
@@ -232,11 +241,12 @@ private void addChildTableToParent(TomlTableNode rootTable, TomlTableNode tableC
         }
     }
 
-    private TomlTableNode generateTable(TomlTableNode parentTable, TomlKeyEntryNode parentString, boolean isGenerated) {
+    private TomlTableNode generateTable(TomlTableNode parentTable, TomlKeyEntryNode parentString, boolean isGenerated
+            , TomlNodeLocation location) {
```
Comment (lochana-chathura) [inline misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java:245]:
```suggestion
    private TomlTableNode generateTable(TomlTableNode parentTable, TomlKeyEntryNode parentString, boolean isGenerated,
                                        TomlNodeLocation location) {
```

File: misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java [hunk 7]
```diff
@@ -321,8 +331,7 @@ private TomlKeyNode getTomlKeyNode(SeparatedNodeList<ValueNode> identifierList)
             TomlBasicValueNode transformedNode = (TomlBasicValueNode) node.apply(this);
             nodeList.add(new TomlKeyEntryNode(transformedNode));
         }
-
-        return new TomlKeyNode(nodeList);
+        return new TomlKeyNode(nodeList, getTomlNodeListLocation(new ArrayList<>(nodeList)));
```
Comment (lochana-chathura) [inline misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java:334]: Shall we avoid copying the list to a new list?
```suggestion
        return new TomlKeyNode(nodeList, getTomlNodeListLocation(nodeList));
```

File: misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java [hunk 8]
```diff
@@ -457,4 +490,32 @@ public TomlNode transform(BoolLiteralNode boolLiteralNode) {
...
     }
+
+    /**
+     * Gives Location of list of TomlNodes
+     * Should only call this method when the execution order is ensured.
+     *
+     * @param keys AST TomlNode key list
+     * @return TomlNodeLocation
+     */
+    private TomlNodeLocation getTomlNodeListLocation(List<TomlNode> keys) {
```
Comment (lochana-chathura) [inline misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java:501]:
```suggestion
    private TomlNodeLocation getTomlNodeListLocation(List<? extends TomlNode> TomlNodeList) {
```
Can use upper bounded wildcard to generalize. 
Also, shall we use a more generic name instead of "keys". Since the method can be used to get the location of any kind of TomlNode list.

File: misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java [hunk 9]
```diff
@@ -457,4 +490,32 @@ public TomlNode transform(BoolLiteralNode boolLiteralNode) {
...
+        if (keys.size() == 0) {
+            return null;
+        }
+        TomlNode firstNode = keys.get(0);
+        if (keys.size() == 1) {
+            return firstNode.location();
+        }
+        TomlNodeLocation locationOfFirstKey = firstNode.location();
```
Comment (lochana-chathura) [inline misc/toml-parser/src/main/java/io/ballerina/toml/semantic/ast/TomlTransformer.java:509]:
```suggestion
        TomlNodeLocation firstKeyLocation = firstNode.location();
```

**Review by lochana-chathura — APPROVED** [review]
