### PR TITLE
Fix typedesc resolving for remote methods return type

### LINKED ISSUE #32836: Invalid type-checking error when calling a dependently-typed method of an object type-descriptor
**Description:**
Consider the following code:

```ballerina
import ballerina/sql;

type Product record {|
    int id?;
    string productName;
    float price;
    string currency;
|};

function sample(sql:Client sqlClient) returns error? {
    stream<Product, sql:Error?> prodStream = sqlClient->query("select id, product_name as productName, price, currency from products", Product);
}
```
When compiled, it prints the following error:
```
ERROR [test.bal:(12:46,12:144)] incompatible types: expected 'stream<Product,ballerina/sql:1.0.0:Error?>', found 'stream<rowType,ballerina/sql:1.0.0:Error?>'
```
Since I pass the `rowType` as a parameter, this should return a stream of type `stream<Product, sql:Error?> prodStream`.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 3 RC3

### PR DESCRIPTION
**Pull request by KRVPerera**
Fixes #32836

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by hasithaa** [comment]
Shall we add a few test cases?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -6407,7 +6407,6 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
 
         BType retType = typeParamAnalyzer.getReturnTypeParams(env, bInvokableType.getReturnType());
         if (restType != symTable.semanticError &&
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6409]: Not related to this PR, but this should probably be retType instead of restType, right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -6407,7 +6407,6 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
...
-                Symbols.isFlagOn(invokableSymbol.flags, Flags.NATIVE) &&
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6410]: Alternatively I guess we can check if it is a method declaration, but I guess this isn't quite necessary since we are checking if the return type is "parameterized".

```java
Symbols.isFlagOn(invokableSymbol.flags, Flags.NATIVE) || 
   Symbols.isFlagOn(invokableSymbol.flags, Flags.INTERFACE) 
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6409]: Yes

**Comment by KRVPerera** [comment]
Need to add test cases

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6410]: Thanks. I think it is better to be expressive in code for anyone to understand. I will check this logic.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -6463,8 +6463,8 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
         }
 
         BType retType = typeParamAnalyzer.getReturnTypeParams(env, bInvokableType.getReturnType());
-        if (restType != symTable.semanticError &&
-                Symbols.isFlagOn(invokableSymbol.flags, Flags.NATIVE) &&
+        if (restType != symTable.semanticError && (Symbols.isFlagOn(invokableSymbol.flags, Flags.INTERFACE)
+                || Symbols.isFlagOn(invokableSymbol.flags, Flags.NATIVE)) &&
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6467]: Shall we extract `` out to a variable?

```suggestion
        long flags = invokableSymbol.flags;
        if (retType != symTable.semanticError &&
                (Symbols.isFlagOn(flags, Flags.INTERFACE) || Symbols.isFlagOn(flags, Flags.NATIVE)) &&
                Symbols.isFlagOn(retType.flags, Flags.PARAMETERIZED)) {
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6467]: Also includes the change from `restType` to `retType`.

File: tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal [hunk 4]
```diff
@@ -823,6 +823,38 @@ function testDependentlyTypedFunctionWithIncludedRecordParam() {
...
+    stream<Person> y = cl->query(studentStream, Person);
+    var rec = y.next();
+    if (rec is record {| Person value; |}) {
+        Person person = rec.value;
+        assert(20, person.age);
+        assert("John Doe", person.name);
+        return;
+    }
+    rec = y.next();
+    assert(true, rec is record {| Person value; |});
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal:855]: Shall we also add a test for inferring

```
stream<Person> z = cl->query(studentStream);
```

In the native code, we will have to assert the argument also.

Maybe something like

```java
assert streamConstraint == strm.getConstraintType();
```
?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/VariableReturnType.java [hunk 5]
```diff
@@ -146,6 +147,11 @@ public static MapValue query(BString query, BTypedesc typedesc) {
         return map;
     }
 
+    public static BStream getStreamOfRecords(ObjectValue objectValue, BStream strm, BTypedesc typedesc) {
+        RecordType streamConstraint = (RecordType) ((BTypedesc) typedesc).getDescribingType();
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/VariableReturnType.java:151]:
```suggestion
        RecordType streamConstraint = (RecordType) typedesc.getDescribingType();
```

**Comment by MaryamZi** [comment]
Shall we update the title to reflect what we are fixing?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 6]
```diff
@@ -6467,8 +6467,9 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
         }
 
         BType retType = typeParamAnalyzer.getReturnTypeParams(env, bInvokableType.getReturnType());
-        if (restType != symTable.semanticError &&
-                Symbols.isFlagOn(invokableSymbol.flags, Flags.NATIVE) &&
+        long invokableSymbolFlags = invokableSymbol.flags;
+        if (restType != symTable.semanticError && (Symbols.isFlagOn(invokableSymbolFlags, Flags.INTERFACE)
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6471]: The `restType` to `retType` break the build. 
Crashes at 
```Unifier::populateParamMapFromRestArg```

```LogTalk
at org.wso2.ballerinalang.compiler.util.Unifier.populateParamMapFromRestArg(Unifier.java:779)
        at org.wso2.ballerinalang.compiler.util.Unifier.createParamMap(Unifier.java:720)
        at org.wso2.ballerinalang.compiler.util.Unifier.build(Unifier.java:94)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvocationArgs(TypeChecker.java:6474)

```

Need to properly identify the logic. Just looking at the overall code there is a pattern to make sure that `restType` is not a semantic error type.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 3 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: regarding `restType`
https://github.com/ballerina-platform/ballerina-lang/pull/33964#discussion_r757252003

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 6 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6471]: Ah, just checked the relevant [commit](https://github.com/ballerina-platform/ballerina-lang/commit/cfce4ee3734bb42eb7c92bb5ebe6d448f86ed4fd). I think the current check is correct, my bad.

File: tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal [hunk 7]
```diff
@@ -823,6 +823,54 @@ function testDependentlyTypedFunctionWithIncludedRecordParam() {
...
+                name: "getStreamOfRecords",
+                paramTypes: ["io.ballerina.runtime.api.values.BStream", "io.ballerina.runtime.api.values.BTypedesc"]
+                } external;
+}
+
+public type ClientObject client object {
+    remote isolated function query(stream<record {}> strm, typedesc<record {}> rowType = <>) returns stream <rowType>;
+};
+
+function testDependentlyTypedFunctionsWithStreams() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal:840]: Shall we rename the functions to reflect what we are testing?

Maybe
```suggestion
function testDependentlyTypedMethodCallOnObjectType() {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal [hunk 8]
```diff
@@ -823,6 +823,54 @@ function testDependentlyTypedFunctionWithIncludedRecordParam() {
...
+    if (rec is record {| Person value; |}) {
+        Person person = rec.value;
+        assert(20, person.age);
+        assert("John Doe", person.name);
+    }
+    rec = y.next();
+    assert(true, rec is record {| Person value; |});
+}
+
+function testDependentlyTypedFunctionsWithInferredStreamType() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/javainterop/dependently_typed_functions_test.bal:857]: Similarly
```suggestion
function testDependentlyTypedMethodCallOnObjectTypeWithInferredArgument() {
```

**Comment by MaryamZi** [comment]
@KRVPerera, can you please resolve the conflicts and sync the PR with master?

**Review by MaryamZi — APPROVED** [review]
