### PR TITLE
Fix conflict of syntax kinds between terminal and non-terminal nodes.

### LINKED ISSUE #23902: Syntax tree has a terminal node in places where a non-terminal is expected
The following test case fails due to the above condition. I've handled this case temporary in `ParserTestUtils.asserNonTerminalNode()` method. I've mentioned this issue there as well. 

```
FunctionDefinitionTest. testExternalFuncDefWithMisingReturnType
IsExpressionTest. testIsExprWithMissingTypeDescriptor
TypeCastExpressionTest. testTypeCastWithMissingParam
TypeCastExpressionTest. testTypeCastWithMissingParamAndExpr
WorkerDeclTest. testMissingReturnTypeDesc
ForEachStatementTest. testForEachStmtwithMissingTypedBindingPattern
ForEachStatementTest. testListBindingPatternInvalidComponentsForEachStmt
TransactionStatementTest. testRetryStatementRecovery
TransactionStatementTest. testRetryTransactionStatementRecovery
ErrorTypeTest. testInValidErrorTypeMissingErrorTypeParams
FunctionTypeTest. testRecoveryInFuncTypeUsagesInTypeDescContexts
IntersectionTypeTest. testInValidLocalLevelIntersectionTypeMissingLeftTypeDesc
IntersectionTypeTest. testInValidLocalLevelIntersectionTypeMissingRightTypeDesc
ParameterizedTypeTest. testInValidModuleLevelMapTypeWithInvalidTokenInside
ParameterizedTypeTest. testInValidModuleLevelMapTypeWithMissingtype
StreamTypeTest. testInValidLocalLevelStreamTypes
StreamTypeTest. testInValidModuleLevelStreamTypeMissingTypeDesc
TableTypeTest. testInValidLocalLevelTableTypes
TupleTypeTest. testLocalLevelInValidTupleTypes
UnionTypeTest. testInValidLocalLevelUnionTypeMissingLeftTypeDesc
UnionTypeTest. testInValidLocalLevelUnionTypeMissingRightTypeDesc
```

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose

- Fix usage of terminal kinds to non-terminal basicLiteralNode.
- Fix node getting `isMissing` attribute with non-terminal kind.
- Use context to decide the diagnostic error message.

Fixes #23902

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java [hunk 1]
```diff
@@ -201,23 +201,43 @@
     PARAMETER_DOC_REFERENCE_TOKEN(907, "parameter"),
     CONST_DOC_REFERENCE_TOKEN(908, "const"),
 
+    //Literal tokens
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java:204]: Usually we keep a space between `//` and the first character in the comment :)

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java [hunk 2]
```diff
@@ -201,23 +201,43 @@
...
+    //-----------------------------------------------non-terminal-kinds-----------------------------------------------
+
+    //Basic literal kinds
+    STRING_LITERAL(1200),
+    NUMERIC_LITERAL(1201),
+    BOOLEAN_LITERAL(1202),
+    NIL_LITERAL(1203),
+    BASIC_LITERAL(1204),
+    BYTE_ARRAY_LITERAL(1205),
+    ASTERISK_LITERAL(1206),
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java:232]: Should we move these under expressions?

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java [hunk 3]
```diff
@@ -201,23 +201,43 @@
...
+    INVALID_TOKEN(1190),
+
+    //-----------------------------------------------non-terminal-kinds-----------------------------------------------
+
+    //Basic literal kinds
+    STRING_LITERAL(1200),
+    NUMERIC_LITERAL(1201),
+    BOOLEAN_LITERAL(1202),
+    NIL_LITERAL(1203),
+    BASIC_LITERAL(1204),
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java:230]: we may no longer need `BASIC_LITERAL`

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java [hunk 4]
```diff
@@ -201,23 +201,43 @@
...
+
+    INVALID_TOKEN(1190),
+
+    //-----------------------------------------------non-terminal-kinds-----------------------------------------------
+
+    //Basic literal kinds
+    STRING_LITERAL(1200),
+    NUMERIC_LITERAL(1201),
+    BOOLEAN_LITERAL(1202),
+    NIL_LITERAL(1203),
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java:229]: Do we need separate kinds for `null` literal and `()` literal?

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 5]
```diff
@@ -7713,12 +7738,16 @@ private STNode parseArrayTypeDescriptorNode(STIndexedExpressionNode indexedExpr)
...
         STNode lengthExpr = lengthExprs.get(0);
         switch (lengthExpr.kind) {
-            case DECIMAL_INTEGER_LITERAL:
-            case HEX_INTEGER_LITERAL:
             case ASTERISK_TOKEN:
             case SIMPLE_NAME_REFERENCE:
             case QUALIFIED_NAME_REFERENCE:
                 break;
+            case NUMERIC_LITERAL:
+                if (lengthExpr.childInBucket(0).kind == SyntaxKind.DECIMAL_INTEGER_LITERAL_TOKEN ||
```
[the remark this answers is not in the document]
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:7746]: Done

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 6]
```diff
@@ -15483,7 +15495,7 @@ private SyntaxKind getBracketedListNodeType(STNode memberNode) {
         }
 
         switch (memberNode.kind) {
-            case ASTERISK_TOKEN:
+            case ASTERISK_LITERAL:
```
[the remark this answers is not in the document]
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:15498]: There is a place where we treat asterisk as a basic literal in line `4894`. So that is why I have used `ASTERISK_LITERAL`.

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java (hunk 1 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java:204]: Thanx will change.

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java (hunk 2 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java:232]: By removing the basic literal kinds section?

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java (hunk 3 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java:230]: `BASIC_LITERAL` is used in error recovery

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java (hunk 4 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java:229]: No, since `null` and `()` are both nil literal I have used a single kind.

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java (hunk 3 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java:230]: Removed

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java (hunk 2 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java]: moved to expressions

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java (hunk 4 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxKind.java]: used seprate kinds

**Review by SupunS — APPROVED** [review]
