### PR TITLE
[IntelliJ Plugin] Fix iterable operation highlighting issue

### LINKED ISSUE #10146: Some iterable operations are highlighted in blue as keywords
**Description:**
In Idea plugin and in VS Code, when you use iterable operations such as map() and foreach(), those are highlighted in blue since the names are keywords as well. It would be great if we can stop highlighting these words are used in the context of iterable operations.

### PR DESCRIPTION
**Pull request by NipunaRanasinghe**
## Purpose
Resolves #10146

### CODE REVIEW

File: tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/codeinsight/daemon/impl/BallerinaAnnotator.java [hunk 1]
```diff
@@ -70,9 +70,20 @@ public void annotate(@NotNull PsiElement element, @NotNull AnnotationHolder hold
...
+                // these keywords can be used as iterable operations as well
+            } else if (elementType == BallerinaTypes.MAP || elementType == BallerinaTypes.FOREACH) {
+                if (parent.getNode().getElementType() == BallerinaTypes.RESERVED_WORD) {
+                    //if the context is an iterable operation, skips highlighting as a keyword
+                    if (parent.getParent() != null
+                            && parent.getParent().getNode().getElementType() == BallerinaTypes.ANY_IDENTIFIER_NAME) {
+                        annotateKeyword(element, holder, BallerinaSyntaxHighlightingColors.DEFAULT, false);
+                    }
+                } else {
+                    annotateKeyword(element, holder, false);
```
Comment (Shan1024) [inline tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/codeinsight/daemon/impl/BallerinaAnnotator.java]: We don't need to highlight the keyword in the else since it shouldn't be highlighted.

Comment (NipunaRanasinghe) [reply tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/codeinsight/daemon/impl/BallerinaAnnotator.java]: **if** condition is used to check whether the context is an iterable operation. so if not, these keywords should be highlighted as keywords.
