### PR TITLE
Mark closure only for var refs that are wrapped within lambda in a on-fail

### LINKED ISSUE #30522: Bad Sad error when we have an respond in on fail block in do statement
**Description:**
  When we have a `caller->respond(req);` statement in `on fail` block of DO statement Ballerina gives a Bad Sad error when running the code. 

**Steps to reproduce:**

1. Use the below code

```
import ballerina/http;
import ballerina/log;

function parse(string num) returns int|error {
   return int:fromString(num);
}

service / on new http:Listener(8090) {
    resource function get .(http:Caller caller, http:Request request) returns error? {
        do {
            int parsedStr = check parse("invalid");
        } on fail error e {
            http:Response defaultErrorResp = new;
            defaultErrorResp.statusCode = 400;
            defaultErrorResp.setPayload("Error occured while processing: " + e.message());
            log:printError("Error occured while processing: " + e.message(), stackTrace = e.stackTrace().callStack);
            check caller->respond(defaultErrorResp);
        }
    }
}
```
2. Run this code.

**Affected Versions:**
Alpha2 and above

**OS, DB, other environment details and versions:**
Mac OS

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #30522

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/BreakableMode.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+ * Mode of transferring control flow across block statements {@code BLangFail}.
+ * Supported Types:
+ * <ul>
+ * <li>NOT_BREAKABLE - Do not transfer control flow</li>
+ * <li>BREAK_WITHIN_BLOCK - Transfer control flow to the end of current block statement</li>
+ * <li>BREAK_TO_OUTER_BLOCK - Transfer control flow to the immediate outer block statement</li>
+ * </ul>
+ * @since Swan Lake
+ */
+public enum BreakableMode {
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/BreakableMode.java:30]: 1. Shouldn't this be a inner class in block node as this always associate with a block node.
2 This only applied to transfer of constrol with ragerds to `on fail` right, I think the name should reflect that.

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/BreakableMode.java]: Refactored in 1963173478da471955eb33f0541d7cc689d94e13

**Review by rdhananjaya — APPROVED** [review]
