### PR TITLE
[Formatter] Align Formatter with Service Changes

### LINKED ISSUE #27133: Align formatter with service changes
**Description:**
We need to align the formatter with the syntax tree changes introduced in service-typing branch.

PR commenting out errors in formatter due to this change: https://github.com/ballerina-platform/ballerina-lang/pull/27132

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by sanjana**
- Fix the formatting tree modifier nodes for the newly introduced service changes at: #27305
- Enable and fix all minor changes in the class definition declaration formatting test cases

Fixes #27133 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 1]
```diff
@@ -596,19 +630,30 @@ public ImportPrefixNode transform(ImportPrefixNode importPrefixNode) {
...
         SeparatedNodeList<ExpressionNode> expressions =
                 formatSeparatedNodeList(serviceDeclarationNode.expressions(), 0, 0, 1, 0);
-        //Node serviceBody = formatNode(serviceDeclarationNode.serviceBody(), env.trailingWS, env.trailingNL);
+        Token openBrace = formatToken(serviceDeclarationNode.openBraceToken(), 0, 1);
+        indent(); // increase the indentation of the following statements.
+        NodeList<Node> members = formatNodeList(serviceDeclarationNode.members(), 0, 1, 0, 1, true);
+        unindent(); // reset the indentation.
+        if (serviceDeclarationNode.members().isEmpty()) {
+            env.preserveNewlines = true;
+        }
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:644]: Do we need to check the empty-ness?

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 2]
```diff
@@ -281,7 +282,14 @@ public FunctionDefinitionNode transform(FunctionDefinitionNode functionDefinitio
         MetadataNode metadata = formatNode(functionDefinitionNode.metadata().orElse(null), 0, 1);
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:282]: No changes required to the `MethodDeclarationNode`?

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 3]
```diff
@@ -281,7 +282,14 @@ public FunctionDefinitionNode transform(FunctionDefinitionNode functionDefinitio
...
         NodeList<Token> qualifierList = formatNodeList(functionDefinitionNode.qualifierList(), 1, 0, 1, 0);
         Token functionKeyword = formatToken(functionDefinitionNode.functionKeyword(), 1, 0);
-        IdentifierToken functionName = formatToken(functionDefinitionNode.functionName(), 0, 0);
+        IdentifierToken functionName;
+        if (functionDefinitionNode.relativeResourcePath().isEmpty() ||
+                functionDefinitionNode.relativeResourcePath().get(0).isMissing()) {
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:287]: Why are we not keeping a space for func-name, if the first component of relative path is missing?

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java [hunk 4]
```diff
@@ -88,6 +88,8 @@ public void test(String fileName, String path) throws IOException {
                 "typed_binding_patterns_source_16.bal", // parser issue for binding patterns #26421
                 "error_binding_pattern_source_02.bal", // issue #26376
 
+                "service_decl_source_02.bal", "service_decl_source_05.bal", "service_decl_source_17.bal",
+
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java:92]: Why do we have to skip these tests?

**Review by SupunS — CHANGES_REQUESTED** [review]

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 5]
```diff
@@ -596,19 +630,30 @@ public ImportPrefixNode transform(ImportPrefixNode importPrefixNode) {
     public ServiceDeclarationNode transform(ServiceDeclarationNode serviceDeclarationNode) {
         MetadataNode metadata = formatNode(serviceDeclarationNode.metadata().orElse(null), 0, 1);
         Token serviceKeyword = formatToken(serviceDeclarationNode.serviceKeyword(), 1, 0);
```
Comment (IrushiL) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:632]: The qualifiers [1] need to be formatted here as well right?

[1] https://github.com/ballerina-platform/ballerina-lang/blob/f919b1d55a84b1d302f188e657cf5155755c0327/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java#L157

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 2 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:282]: This [1] seems to be added in the `MethodDeclarationNode`.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/f919b1d55a84b1d302f188e657cf5155755c0327/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java#L2257

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 6]
```diff
@@ -160,6 +160,7 @@
 import io.ballerina.compiler.syntax.tree.RecordTypeDescriptorNode;
```
Comment (IrushiL) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:160]: Shall we implement the `RequiredExpressionNode` [1] as well in this PR? Seems to be a new node.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/f919b1d55a84b1d302f188e657cf5155755c0327/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java#L3157

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 7]
```diff
@@ -2307,19 +2352,10 @@ public AnnotationDeclarationNode transform(AnnotationDeclarationNode annotationD
...
-//        Token firstIdent;
-//        if (annotationAttachPointNode.secondIdent().isPresent()) {
-//            firstIdent = formatToken(annotationAttachPointNode.firstIdent(), 1, 0);
-//        } else {
-//            firstIdent = formatToken(annotationAttachPointNode.firstIdent(), env.trailingWS, env.trailingNL);
-//        }
-//
-//        Token secondIdent = formatToken(annotationAttachPointNode.secondIdent().orElse(null), env.trailingWS,
-//                env.trailingNL);
+        NodeList<Token> identifiers = formatNodeList(annotationAttachPointNode.identifiers(), 1, 0, 0, 0);
```
Comment (IrushiL) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:2355]: Can we change this to the following?
```suggestion
        NodeList<Token> identifiers = formatNodeList(annotationAttachPointNode.identifiers(), 1, 0, env.trailingWS, env.trailingNL);
```

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 1 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:644]: Since a similar behavior is implemented here in `FunctionBodyBlockNode`, the newline preservation was added here as well. 

https://github.com/ballerina-platform/ballerina-lang/blob/7289b5b33d06787e4ebfa7159d6eab19e5545f80/misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java#L361

Otherwise, the following parser-tests seems to be failing as well. 

https://github.com/ballerina-platform/ballerina-lang/blame/master/compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_18.bal 

https://github.com/ballerina-platform/ballerina-lang/blame/master/compiler/ballerina-parser/src/test/resources/declarations/service-decl/service_decl_source_19.bal

Comment (SupunS) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:644]: Preserving the newline is fine. But do we need to check for the emtpy-ness?
As in, are we not preserving the newlines if the list is not empty?

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 2 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:282]: Fixed it here: 

https://github.com/ballerina-platform/ballerina-lang/blob/28c7bcab80ae1b8988019c7beee6053d04290524/misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java#L2744

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 7 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java]: Fixed.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 6 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:160]: Implemented.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 5 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:630]: Fixed.

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java (hunk 4 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java:92]: Will be addressed at #27490

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 3 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java]: Fixed.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 1 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java]: Fixed in `FunctionBodyBlockNode` and `ServiceDeclarationNode`.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 8]
```diff
@@ -595,20 +626,39 @@ public ImportPrefixNode transform(ImportPrefixNode importPrefixNode) {
...
-                //.withServiceBody(serviceBody)
+                .withOpenBraceToken(openBrace)
+                .withMembers(members)
+                .withCloseBraceToken(closeBrace)
+                .apply();
+    }
+
+    @Override
+    public RequiredExpressionNode transform(RequiredExpressionNode requiredExpressionNode) {
+        Token questionMarkToken = formatToken(requiredExpressionNode.questionMarkToken(), 0, 0);
```
Comment (IrushiL) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:659]:
```suggestion
        Token questionMarkToken = formatToken(requiredExpressionNode.questionMarkToken(), env.trailingWS, env.trailingNL);
```

Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java]: @IrushiL Thanks for pointing this out. :+1: 
Fixed.

**Review by IrushiL — APPROVED** [review]

**Review by SupunS — APPROVED** [review]
