### PR TITLE
Fix invalid completions for a precise resource parameter type

### LINKED ISSUE #37668: [Improvement]: Resource path parameters with singleton string types should be suggested as regular resource path identifiers
### Description

Currently suggestion is given to `cl->/["path"].accessor;` where it should give suggestion for `cl->/path.accessor;`

Screenshot from 2022-09-07 12-54-22

### Describe your problem(s)

_No response_

### Describe your solution(s)

_No response_

### Labels

LanguageServer

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by nipunayf**
## Purpose

The LS server does not provide all applicable completions when the resource parameter type is a subtype of the expression type. For instance, for the resource parameters `singleton` and `string:Char`, completions are not shown since the expression type is `string`, which is a broader type than the former. The PR addresses this problem by providing completions for these cases as well.

Fixes #37668 

## Approach
Since the semantic model assigns the broader type for a node, the expression type will **not always** be a subtype of the resource parameter type, which contradicts our existing implementation. Hence, this PR appends an additional check for those edge cases where the expression type is broader than the resource parameter type.

## Samples
For the below client source code with a singleton resource parameter, we can obtain the following code completions as continuing.

```ballerina
client class MyClient {
    resource function accessor ["A31" a]() {
    }
}
```
image
image

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/ResourcePathCompletionUtil.java [hunk 1]
```diff
@@ -211,19 +212,47 @@ private static ResourceAccessPathPart getResourceAccessPartForSegment(PathSegmen
...
+                resourceAccessPathPart.namedPathSignature = "<path>";
+                resourceAccessPathPart.namedPathInsertText = "${" + placeHolderIndex + ":" + "path" + "}";
+                resourceAccessPathPart.computedPathInsertText = "[${" + placeHolderIndex + ":" + "\"path\"" + "}]";
+            }
+            resourceAccessPathPart.isStringPathParam = true;
         }
         return resourceAccessPathPart;
     }
 
+    private static boolean checkSubtype(TypeSymbol paramType, TypeSymbol stringType) {
```
Comment (LakshanWeerasinghe) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/ResourcePathCompletionUtil.java:236]: We can move this to CommonUtil class.

Comment (nipunayf) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/ResourcePathCompletionUtil.java:236]: Currently, the method is only used within the class.

File: language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config38.json [hunk 2]
```diff
@@ -0,0 +1,40 @@
+{
+  "position": {
+    "line": 8,
+    "character": 9
+  },
+  "source": "action_node_context/source/client_resource_access_action_source31.bal",
+  "description": "",
```
Comment (mindula) [inline language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config38.json:7]: let's add descriptions

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java [hunk 3]
```diff
@@ -324,18 +326,19 @@ private Pair<List<PathSegment>, Boolean> completableSegmentList(ResourceMethodSy
                     return Pair.of(Collections.emptyList(), false);
                 }
                 if (node.kind() == SyntaxKind.COMPUTED_RESOURCE_ACCESS_SEGMENT) {
+                    ExpressionNode exprNode = ((ComputedResourceAccessSegmentNode) node).expression();
                     Optional<TypeSymbol> exprType =
-                            semanticModel.get().typeOf(((ComputedResourceAccessSegmentNode) node).expression());
-                    if (exprType.isEmpty() || !exprType.get().subtypeOf(typeSymbol)) {
+                            semanticModel.get().typeOf(exprNode);
```
Comment (mindula) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java:331]: can be in-lined

**Review by mindula — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java [hunk 4]
```diff
@@ -352,6 +354,27 @@ private Pair<List<PathSegment>, Boolean> completableSegmentList(ResourceMethodSy
         return Pair.of(completableSegments, true);
     }
 
+    private boolean checkSubtype(TypeSymbol paramType, TypeSymbol exprType, String exprValue) {
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java:357]: Lets move this to ResoucePathCompletionUtil class

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java [hunk 5]
```diff
@@ -324,18 +326,18 @@ private Pair<List<PathSegment>, Boolean> completableSegmentList(ResourceMethodSy
...
                     }
                     if (segment.pathSegmentKind() == PathSegment.Kind.PATH_REST_PARAMETER
                             && !ResourcePathCompletionUtil.isInMethodCallContext(accNode, context)) {
                         completableSegmentStartIndex -= 1;
                     }
                     continue;
-                } else if (node.kind() == SyntaxKind.IDENTIFIER_TOKEN
-                        && semanticModel.get().types().STRING.subtypeOf(typeSymbol)) {
+                } else if (node.kind() == SyntaxKind.IDENTIFIER_TOKEN &&
+                        checkSubtype(typeSymbol, semanticModel.get().types().STRING, "\"" + node + "\"")) {
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ClientResourceAccessActionNodeContext.java:340]:
```suggestion
                        checkSubtype(typeSymbol, semanticModel.get().types().STRING, "\"" + ((IdentifierToken)node).text() + "\"")) {
```

**Review by malinthar — CHANGES_REQUESTED** [review]

**Comment by KavinduZoysa** [comment]
@nipunayf, there is a checkstyle failure, please fix.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/ResourcePathCompletionUtil.java [hunk 6]
```diff
@@ -211,19 +242,50 @@ private static ResourceAccessPathPart getResourceAccessPartForSegment(PathSegmen
...
+
+        //  A resource method parameter can be a singleton or a union with a `string`. As the node "text" is always
+        //  resolved to `string`, we need to check if typeSymbol is either a supertype or a subtype  of `string`.
         if (context.currentSemanticModel().isPresent() &&
-                context.currentSemanticModel().get().types().STRING.subtypeOf(typeSymbol)) {
-            resourceAccessPathPart.namedPathSignature = "<path>";
-            resourceAccessPathPart.namedPathInsertText = "${" + placeHolderIndex + ":" + "path" + "}";
-            resourceAccessPathPart.computedPathInsertText = "[${" + placeHolderIndex + ":" + "\"path\"" + "}]";
-            resourceAccessPathPart.isStringPathPram = true;
+                isStringSubtype(typeSymbol, context.currentSemanticModel().get().types().STRING)) {
```
Comment (KavinduZoysa) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/ResourcePathCompletionUtil.java:254]: Do we need to pass the 2nd argument?

Comment (nipunayf) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/ResourcePathCompletionUtil.java:254]: The `context` is only visible within the function body and not across the entire class; that's why I had to pass the `String` type symbol as a parameter. If we can access the `String` type symbol statically, then we do not need to pass this explicitly.

**Review by KavinduZoysa — APPROVED** [review]

**Review by mindula — APPROVED** [review]
