### PR TITLE
Fix several integer related issues

### LINKED ISSUE #14983: Large decimal values using int literals are not supported
**Description:**
```ballerina
decimal d = 10000000000000000123;
```
Results in `Integer '10000000000000000123' too large` error.
This should not be the case since decimal can hold larger numbers than this.

However following does work.
```ballerina
decimal d = 10000000000000000123.0;
```
**Affected Versions:**
0.991

### LINKED ISSUE #32508: Compiler doesn't complain about assigning some invalid values to builtin subtypes of `int`
**Description:**
The criteria for a value `v` to belong to a built-in subtype of `int` is given in [https://ballerina.io/spec/lang/2021R1/#built-in_subtypes](https://ballerina.io/spec/lang/2021R1/#built-in_subtypes). But some invalid values are being allowed to be assigned to some of the subtypes. Consider the following examples 

**Steps to reproduce:**
```ballerina

public function main() {
    // Signed16 -32768 ≤ v ≤ 32767
    //int:Signed16 x1 = 21474803711; // error
    int:Signed16 x2 = 21474803712; // no error
    int:Signed16 x3 = 9223372036854775807; // no error
    //int:Signed16 x4 = 9223372036854775808; // error
}

public function main() {
    // Signed8 -128 ≤ v ≤ 127
    //int:Signed8 x5 = -9223372036854775680; // error
    int:Signed8 x6 = -9223372036854775681; // no error
    int:Signed8 x7 = 9223372036854775807; // no error
    //int:Signed8 x8 = 9223372036854775808; // error
}

public function main() {
    // Unsigned16 0 ≤ v ≤ 65535
    //int:Unsigned16 x9 = -21474770944; // error
    int:Unsigned16 x10 = -21474770945; // no error
    int:Unsigned16 x11 = -21474836480; // no error
    //int:Unsigned16 x12 = -21474836481; // error
}

public function main() { 
    // Unsigned8 0 ≤ v ≤ 255
    //int:Unsigned8 x13 = -9223372036854775552; // error
    int:Unsigned8 x14 = -9223372036854775553; // no error
    int:Unsigned8 x15 = -9223372036854775808; // no error
    //int:Unsigned8 x16 = -9223372036854775809; // error
}
```
**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/32574

**Affected Versions:**
slbeta2

### LINKED ISSUE #32574: Compiler crashes when a too large or too small number is assigned to a builtin subtype of `int`
**Description:**
Compiler crashes when a value > 9223372036854775807 or value < -9223372036854775808 is assigned to a variable of type Signed32, Signed16, Signed8, Unsigned32, Unsigned16, or Unsigned8

**Steps to reproduce:**
```ballerina
public function main() {
    int:Signed8 x = 9223372036854775808; // gives a compilation error, but also crashes
}
```
Error log:
```
SEVERE {b7a.log.crash} - class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap') 
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getIntLiteralType(TypeChecker.java:815)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.setLiteralValueAndGetType(TypeChecker.java:479)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:413)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangLiteral.accept(BLangLiteral.java:50)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:376)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:355)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:871)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3497)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3465)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3457)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1562)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3497)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3465)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:3461)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:470)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3497)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:440)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3497)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3465)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3457)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:327)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:292)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:204)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:112)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:383)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:174)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:135)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:64)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:163)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

The same issue is observed when the value is too small as well. 

```ballerina
public function main() {
    int:Signed16 x = -9223372036854775809;
}
```

**Affected Versions:**
slbeta2

### LINKED ISSUE #32577: Assigning `-9223372036854775808` to an `int` does not overflow
**Description:**
Consider the following line in [lang.int](https://ballerina.io/spec/lang/master/#lang.int) spec
```
# Minimum value of type `int`.
public const MIN_VALUE = -9223372036854775807 - 1; // -9223372036854775808 would overflow
```
Since ballerina doesn't have a concept of positives and negatives,  the positive part here `9223372036854775808` should overflow. 

**Steps to reproduce:**
```ballerina
public function main() {
    int a = -9223372036854775808; //This should overflow, but works ATM
}
```
**Affected Versions:**
slbeta2

### LINKED ISSUE #32686: Can not assign valid value to union of builtin subtypes of `int`
**Description:**
$title. Consider the following examples

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    int:Signed8|int:Unsigned32 a1 = 235262;
    io:println(a1); // prints 235262
    
    int:Signed8 x = -127;
    int:Signed8|int:Unsigned32 a2 = x;
    io:println(a2); // prints -127 

    int:Signed8|int:Unsigned32 a3 = -127; // incompatible types: expected 'int:Unsigned32', found 'int'
}
```
```ballerina
import ballerina/io;

type IntType int:Signed8|int:Unsigned32;

public function main() {
    IntType a1 = 235262;
    io:println(a1); // prints 235262
    
    int:Signed8 x = -127;
    IntType a2 = x;
    io:println(a2); // prints -127 

    IntType a3 = -127; // incompatible types: expected 'int:Unsigned32', found 'int'
}
```
**Affected Versions:**
slbeta2

### LINKED ISSUE #33689: Assignability of valid value to union of builtin subtypes of int depends on the order of definition
**Description:**
$title

**Steps to reproduce:**
```
import ballerina/io;

public function main() {
    int:Signed8|int:Unsigned32 a1 = 235262; // works
    int:Unsigned32|int:Signed8 a2 = 235262; // incompatible types: expected 'int:Signed8', found 'int'
}
```

**Related Issues (optional):**
#32686

### LINKED ISSUE #34624: Cannot assign valid unary value to user defined type
**Description:**
$title

**Steps to reproduce:**
```
type bar 1|2|-45;

public function main() {
   bar b = -(45);
}
```
fails with:
 
> incompatible types: expected 'bar', found 'int

### LINKED ISSUE #35695: Compiler crashes when assigning too large int to a singleton type
**Description:**
```bal
function test() {
    1 dd = 92233720368547758078; // crash
}
```
<details>
  <summary>Stack trace.(Click to expand)</summary>

```
[2022-04-06 17:33:43,823] SEVERE {b7a.log.crash} - class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap') 
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.checkLiteralAssignabilityBasedOnType(Types.java:3517)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.literalAssignableToFiniteType(TypeChecker.java:816)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getFiniteTypeMatchWithIntType(TypeChecker.java:493)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getFiniteTypeMatchWithIntLiteral(TypeChecker.java:512)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getIntegerLiteralType(TypeChecker.java:541)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.setLiteralValueAndGetType(TypeChecker.java:697)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:425)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangLiteral.accept(BLangLiteral.java:55)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:380)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:354)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1052)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4020)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1907)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:4024)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:524)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:500)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4020)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:349)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:309)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:436)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:103)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:141)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:271)
	at org.ballerinalang.langserver.util.LSClientUtil.chekAndRegisterCommands(LSClientUtil.java:78)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:556)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
</details>

With #34622 it gives a runtime error `error: {ballerina}TypeCastError {"message":"incompatible types: 'float' cannot be cast to '1'"}` which is incorrect

### PR DESCRIPTION
**Pull request by suleka96**
Fixes #32577
Fixes #32574
Fixes #32686
Fixes #34624 
Fixes #35695
Fixes #14983
Tests added #32884
Tests added #31826
Tests added #33689

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by MaryamZi** [comment]
Includes the changes from https://github.com/ballerina-platform/ballerina-lang/pull/33742.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -7176,10 +7177,51 @@ public void visit(BLangUnaryExpr unaryExpr) {
...
+            newNumericLiteral.setDeterminedType(exprInUnary.getBType());
+            newNumericLiteral.setBType(exprInUnary.getBType());
+            newNumericLiteral.expectedType = exprInUnary.getBType();
+
+            newNumericLiteral.typeChecked = unaryExpr.typeChecked;
+            newNumericLiteral.constantPropagated = unaryExpr.constantPropagated;
+            newNumericLiteral.isFiniteContext = true;
+
+            result = rewriteExpr(newNumericLiteral);
+            return;
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:7223]: `return;` is not needed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 2]
```diff
@@ -4030,7 +4091,7 @@ public void visit(BLangConstant constant) {
 
         BLangExpression expression = constant.expr;
         if (!(expression.getKind() == LITERAL || expression.getKind() == NUMERIC_LITERAL)
-                && constant.typeNode == null) {
+                && constant.typeNode == null)  {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:4094]: Space is not needed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -572,10 +595,14 @@ private BType getIntegerLiteralType(BLangLiteral literalExpr, Object literalValu
...
                 }
             }
-
             Set<BType> memberTypes = ((BUnionType) expectedType).getMemberTypes();
             return getTypeMatchingFloatOrDecimal(finiteType, memberTypes, literalExpr, (BUnionType) expectedType);
         }
+        if (!(literalValue instanceof Long)) {
+            dlog.error(literalExpr.pos, DiagnosticErrorCode.OUT_OF_RANGE, literalExpr.originalValue);
+            resultType = symTable.semanticError;
+            return resultType;
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:604]: `return symTable.semanticError;`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 4]
```diff
@@ -857,6 +884,12 @@ private BType getFiniteTypeWithValuesOfSingleType(BUnionType unionType, BType ma
     }
 
     private BType getIntLiteralType(BType expType, Object literalValue) {
+        // The literalValue will be a string if it is not within the bounds of what is supported by Java Long,
+        // indicating that it is an overflown Ballerina int
+        if (!(literalValue instanceof Long)) {
+            resultType = symTable.semanticError;
+            return resultType;
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:891]: Why can't we do `return symTable.semanticError;`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 5]
```diff
@@ -4572,7 +4605,75 @@ public void visit(BLangTypedescExpr accessExpr) {
...
+
+    public LinkedHashSet<BType> getBasicNumericTypesInFiniteType(BType referredType) {
+        LinkedHashSet<BType> basicNumericTypes = new LinkedHashSet<>();
+        BFiniteType finiteType = (BFiniteType) referredType;
+
+        for (BLangExpression value : finiteType.getValueSpace()) {
+            BType referredTypeInFiniteType = types.getReferredType(value.getBType());
+            int typeTag = referredTypeInFiniteType.tag;
+            if (TypeTags.isIntegerTypeTag(typeTag) || typeTag == TypeTags.FLOAT
+                    || typeTag == TypeTags.DECIMAL) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4638]: Inline these two lines

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 6]
```diff
@@ -4572,7 +4605,75 @@ public void visit(BLangTypedescExpr accessExpr) {
...
+                break;
+            } else if (typeTag == TypeTags.FINITE) {
+                LinkedHashSet<BType> numericTypes = getBasicNumericTypesInFiniteType(referredTypeInUnionType);
+                basicNumericTypes.addAll(numericTypes);
+            }
+        }
+        return basicNumericTypes;
+    }
+
+        public void visit(BLangUnaryExpr unaryExpr) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4676]: Extra tab

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 7]
```diff
@@ -3505,7 +3506,7 @@ boolean checkLiteralAssignabilityBasedOnType(BLangLiteral baseLiteral, BLangLite
         // (3) float: we can assign int simple literal(Not an int constant) or a float literal/constant with same value.
         // (4) decimal: we can assign int simple literal or float simple literal (Not int/float constants) or decimal
         // with the same value.
-        switch (baseLiteral.getBType().tag) {
+        switch (baseTypeTag) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3509]: Is there any other usage of this `baseTypeTag`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 8]
```diff
@@ -549,10 +569,14 @@ private BType getIntegerLiteralType(BLangLiteral literalExpr, Object literalValu
...
                         memberRefType.tag == TypeTags.ANY) {
+                    if (literalValue instanceof Double) {
+                        return symTable.floatType;
+                    } else if (literalValue instanceof String) {
+                        return symTable.decimalType;
+                    }
                     return symTable.intType;
                 }
             }
-
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:555]: Keeping the newlines are cleaner here, L#564 and L#575

File: langlib/langlib-test/src/test/resources/test-src/subtypes/int_subtype_test_negative.bal [hunk 9]
```diff
@@ -344,4 +344,16 @@ function testInvalidIntSubtypesInLangLibFunctions() {
...
+     int:Signed16 x1 = 21474803712;
+     int:Signed16 x2 = 9223372036854775807;
+     int:Signed8 x3 = -9223372036854775681;
+     int:Signed8 x4 = 9223372036854775807;
+     int:Unsigned16 x5 = -21474770945;
+     int:Unsigned16 x6 = -21474836480;
+     int:Unsigned8 x7 = -9223372036854775553;
+     int:Unsigned8 x8 = -9223372036854775808;
+     int:Signed8 x9 = 9223372036854775808;
+     int:Signed16 x10 = -9223372036854775809;
```
Comment (rdulmina) [inline langlib/langlib-test/src/test/resources/test-src/subtypes/int_subtype_test_negative.bal:357]: Let's use `_` for unused variables

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 4 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:891]: we need to set the result type here first else it is not getting set.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 1 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:7223]: we are creating a literal and rewriting that instead of a unary expression here to the result  because of the unary change we did in the type checker, so if we don't put a return here, the rewritten unary expression will get re-assigned to result right.

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:7222]: This is my mistake. I thought this is the end of the function block.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 10]
```diff
@@ -4572,6 +4606,184 @@ public void visit(BLangTypedescExpr accessExpr) {
...
+            } else if (TypeTags.isIntegerTypeTag(referredType.tag) || referredType.tag == TypeTags.FLOAT
+                    || referredType.tag == TypeTags.DECIMAL) {
+                newExpectedType = BUnionType.create(null,
+                        symTable.intType, symTable.floatType, symTable.decimalType);
+            } else if (referredType.tag == TypeTags.FINITE || referredType.tag == TypeTags.UNION) {
+                if (referredType.tag == TypeTags.FINITE) {
+                    basicNumericTypes = getBasicNumericTypesInFiniteType(referredType);
+                } else {
+                    basicNumericTypes = getBasicNumericTypesInUnionType(referredType);
+                }
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4700]: Let's inline this

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 11]
```diff
@@ -687,9 +689,68 @@ public void visit(BLangTypeConversionExpr conversionExpr) {
...
+
     @Override
     public void visit(BLangFiniteTypeNode finiteTypeNode) {
-        finiteTypeNode.valueSpace.forEach(value -> analyzeNode(value, env));
+        boolean foundUnaryExpr = false;
+        Set<BLangExpression> newValueSpace = new LinkedHashSet<>();
+
+        for (int i = 0; i < finiteTypeNode.valueSpace.size(); i++) {
+            BLangExpression value = finiteTypeNode.valueSpace.get(i);
+//            newValueSpace.add(value);
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:730]: Do we need this comment? Can't we remove it?

**Comment by pcnfernando** [comment]
@suleka96 some semantic API tests are failing. Please check

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 12]
```diff
@@ -4572,6 +4606,262 @@ public void visit(BLangTypedescExpr accessExpr) {
...
+        BLangNumericLiteral numericLiteral = createNumericLiteralFormUnaryExpr(unaryExpr);
+        // To check value with sign against expected type
+        return clonedExprTypeChecker(numericLiteral, referredType);
+    }
+
+    public LinkedHashSet getIntSubtypesInUnionType(BLangUnaryExpr unaryExpr, BUnionType expectedType) {
+        LinkedHashSet<BType> intTypesInUnion = new LinkedHashSet<>();
+        for (BType type : expectedType.getMemberTypes()) {
+            BType referredType = types.getReferredType(type);
+            if (TypeTags.isIntegerTypeTag(referredType.tag) && type.tag != TypeTags.INT) {
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4830]: Shall we add `type.tag != TypeTags.INT` condition first. Also shall we add a comment why we skip `INT` type for int subtype function

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 13]
```diff
@@ -4572,6 +4606,262 @@ public void visit(BLangTypedescExpr accessExpr) {
...
+        for (BType type : expectedType.getMemberTypes()) {
+            compatibleTypeOfUnaryExpression = clonedExprTypeChecker(unaryExpr, types.getReferredType(type));
+            if (compatibleTypeOfUnaryExpression.tag == TypeTags.FINITE) {
+                return true;
+            }
+        }
+        return false;
+    }
+
+    public BType clonedExprTypeChecker(BLangExpression expr, BType referredType) {
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4848]: Something like this is better IMO

```suggestion
    public BType checkClonedExprSilently(BLangExpression expr, BType referredType) {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 14]
```diff
@@ -4572,6 +4606,262 @@ public void visit(BLangTypedescExpr accessExpr) {
...
+                intTypesInUnion.add(referredType);
+            }
+        }
+        return intTypesInUnion;
+    }
+
+    public boolean checkForCompatibleFiniteMembersInUnionType(BLangUnaryExpr unaryExpr, BUnionType expectedType) {
+        BType compatibleTypeOfUnaryExpression;
+        for (BType type : expectedType.getMemberTypes()) {
+            compatibleTypeOfUnaryExpression = clonedExprTypeChecker(unaryExpr, types.getReferredType(type));
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4840]: We are doing lots of `dlog.mute()` and `dlog.unmute()` inside this loop because of `clonedExprTypeChecker`. 
Can we avoid this for the loop and only do those actions once before and after the loop for this method. We may also need to say this is a silent check in the function name.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BFiniteType.java [hunk 15]
```diff
@@ -96,8 +96,12 @@ public boolean isNullable() {
...
         this.valueSpace.add(value);
-        if (!nullable && value.getBType().isNullable()) {
-            nullable = true;
+        if (!this.nullable && value.getBType() != null &&  value.getBType().isNullable()) {
+            this.nullable = true;
         }
     }
+
+    public void setValueSpace(Set<BLangExpression> valueSpace) {
+        this.valueSpace = valueSpace;
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BFiniteType.java:105]: This is okay only if this is done at ctor right. 
Lets say we do this for a `nullable` `BFiniteType` type. But due to the new set now the `BFiniteType` is not nullable but we forgot to change nullable status.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 16]
```diff
@@ -698,9 +700,68 @@ public void visit(BLangTypeConversionExpr conversionExpr) {
...
+                    newValueSpace.add(newNumericLiteral);
+                }
+            } else {
+                analyzeNode(value, env);
+            }
+        }
+        // Modify BType if Unary expressions were found
+        if (foundUnaryExpr) {
+            BFiniteType finiteType = (BFiniteType) finiteTypeNode.getBType();
+            finiteType.setValueSpace(newValueSpace);
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:763]: This function does not take care of other states of the `finiteType`

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 17]
```diff
@@ -1870,11 +1856,8 @@ hint.unnecessary.condition.for.variable.of.type.never=\
 hint.expression.always.false=\
   expression will always evaluate to ''false''
 
-error.float.too.large=\
-  float ''{0}'' too large
-
-error.float.too.small=\
-  float ''{0}'' too small
+error.numeric.literal.out.of.range=\
+  ''{0}'' is out of range
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1860]: Probably better to say out of range for what.

e.g.,
```
'9223372036854775808' is out of range for 'int'
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 18]
```diff
@@ -7169,11 +7170,49 @@ public void visit(BLangUnaryExpr unaryExpr) {
...
+                objectValueInUnary = Long.parseLong(strValueInUnary);
+            } else if (objectValueInUnary instanceof Double) {
+                objectValueInUnary = Double.parseDouble(strValueInUnary);
+            } else if (objectValueInUnary instanceof String) {
+                objectValueInUnary = strValueInUnary;
+            }
+
+            BLangNumericLiteral newNumericLiteral = (BLangNumericLiteral)
+                    TreeBuilder.createNumericLiteralExpression();
+            newNumericLiteral.kind = ((BLangNumericLiteral) unaryExpr.expr).kind;
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:7196]: `exprInUnary` can be used

**Comment by KavinduZoysa** [comment]
@suleka96, please add some tests withing modules

**Comment by MaryamZi** [comment]
@suleka96, please change the base to master and resolve the conflicts.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java [hunk 19]
```diff
@@ -51,6 +51,8 @@ public HashSet<String> skipList() {
         // Therefore, when adding an item to the skip list, please create an issue.
         hashSet.add("func_def_source_08.bal");
         hashSet.add("match_stmt_source_13.bal");
+        hashSet.add("match_stmt_source_13.bal");
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java:54]: seems like a duplicate.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java [hunk 20]
```diff
@@ -51,6 +51,8 @@ public HashSet<String> skipList() {
...
+        hashSet.add("resiliency_source_04.bal");
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java:55]: Shall we add the corresponding lang issue no as a comment when excluding?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/finite/finite_type_negative.bal [hunk 21]
```diff
@@ -118,3 +118,17 @@ function testFiniteTypeWithNumericValues() {
...
+
+function testFiniteTypeWithUnaryMinus() {
+    UnaryType2 x1 = -2;
+    UnaryType3 x2 = -5;
+}
+
+function testFiniteTypeWithOutOfRangeValues() {
+    1|5.4 _ = 92233720368547758078;
+    1 _ = 92233720368547758078;
+}
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/finite/finite_type_negative.bal:134]: missing EOF newline

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 22]
```diff
@@ -2305,6 +2307,16 @@ public void visit(BLangConstant constant) {
                 constantSymbol.type.tsymbol.flags |= constant.associatedTypeDefinition.symbol.flags;
             }
 
+        } else if (nodeKind == NodeKind.UNARY_EXPR && constant.typeNode == null &&
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:2310]: Why are special casing at both node builder and here? Please see the comment for the node builder also.

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:2310]: The following crashes.

```ballerina
const map<int> Y = {
    a: -1
};
```

```log
[2022-05-01 06:43:00,043] SEVERE {b7a.log.crash} - finite type value is not supported for type: map<int> 
java.lang.UnsupportedOperationException: finite type value is not supported for type: map<int>
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeConstValue(BIRBinaryWriter.java:449)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeConstValue(BIRBinaryWriter.java:392)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeConstant(BIRBinaryWriter.java:385)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.lambda$writeConstants$7(BIRBinaryWriter.java:367)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeConstants(BIRBinaryWriter.java:367)
        at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.serialize(BIRBinaryWriter.java:74)
        at io.ballerina.projects.ModuleContext.generateBIR(ModuleContext.java:512)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:475)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:391)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:122)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 23]
```diff
@@ -172,6 +174,7 @@ public static Types getInstance(CompilerContext context) {
     public Types(CompilerContext context) {
         context.put(TYPES_KEY, this);
 
+        this.semanticAnalyzer = SemanticAnalyzer.getInstance(context);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:177]: Types is like a util class. We shouldn't have a semantic analyzer instance here.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:177]: We can move `constructNumericLiteralFromUnaryExpr` here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 24]
```diff
@@ -494,8 +497,16 @@ BType resolvePatternTypeFromMatchExpr(BLangConstPattern constPattern, BLangExpre
             }
             return symTable.noType;
         }
-        // After the above check, according to spec all other const-patterns should be literals.
-        BLangLiteral constPatternLiteral = (BLangLiteral) constPatternExpr;
+        BLangLiteral constPatternLiteral;
+        if (constPatternExpr.getKind() == NodeKind.UNARY_EXPR) {
+            // Construct numeric literal for + and - numeric values in unary expression
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:502]: Please revisit the comments. Add a comment only if not self-explanatory.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 25]
```diff
@@ -3989,8 +4000,14 @@ boolean checkLiteralAssignabilityBasedOnType(BLangLiteral baseLiteral, BLangLite
                 double baseDoubleVal = Double.parseDouble(baseValueStr);
                 double candidateDoubleVal;
                 if (candidateTypeTag == TypeTags.INT && !candidateLiteral.isConstant) {
-                    candidateDoubleVal = ((Long) candidateValue).doubleValue();
-                    return baseDoubleVal == candidateDoubleVal;
+                    if (candidateLiteral.value instanceof Double) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4003]: Please add a comment explaining why/when this can be double.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4003]: And likewise for others.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 26]
```diff
@@ -4028,7 +4055,7 @@ boolean validateFloatLiteral(Location pos, String numericLiteral) {
         }
 
         if (Double.isInfinite(value)) {
-            dlog.error(pos, DiagnosticErrorCode.FLOAT_TOO_LARGE, numericLiteral);
+            dlog.error(pos, DiagnosticErrorCode.OUT_OF_RANGE, numericLiteral, "Float");
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4058]:
```suggestion
            dlog.error(pos, DiagnosticErrorCode.OUT_OF_RANGE, numericLiteral, "float");
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 27]
```diff
@@ -4042,7 +4069,7 @@ boolean validateFloatLiteral(Location pos, String numericLiteral) {
                 break;
             }
             if (numericLiteral.charAt(i) >= '1' && numericLiteral.charAt(i) <= '9') {
-                dlog.error(pos, DiagnosticErrorCode.FLOAT_TOO_SMALL, numericLiteral);
+                dlog.error(pos, DiagnosticErrorCode.OUT_OF_RANGE, numericLiteral, "Float");
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4072]:
```suggestion
                dlog.error(pos, DiagnosticErrorCode.OUT_OF_RANGE, numericLiteral, "float");
```

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/ResiliencyTest.java [hunk 28]
```diff
@@ -43,8 +43,9 @@ public void testInvalidTokensInModuleLevel() {
         testFile("resiliency/resiliency_source_03.bal", "resiliency/resiliency_assert_03.json");
     }
 
-    @Test
-    public void testResiliencyForTokenBufferOverflow() {
-        testFile("resiliency/resiliency_source_04.bal", "resiliency/resiliency_assert_04.json");
-    }
+// Enable once #35795 is fixed
+//    @Test
```
Comment (MaryamZi) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/ResiliencyTest.java:47]: Tests need to be disabled with `enabled = false`, not commenting them out.

File: langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibSubTypeTest.java [hunk 29]
```diff
@@ -273,7 +274,7 @@ public void testNegativeIntSubType() {
         BAssertUtil.validateError(result, err++, "incompatible types: expected 'int:Unsigned16', found 'int'", 352, 25);
         BAssertUtil.validateError(result, err++, "incompatible types: expected 'int:Unsigned16', found 'int'", 353, 25);
         BAssertUtil.validateError(result, err++, "incompatible types: expected 'int:Unsigned8', found 'int'", 354, 24);
-        BAssertUtil.validateError(result, err++, "incompatible types: expected 'int:Unsigned8', found 'int'", 355, 24);
+        BAssertUtil.validateError(result, err++, "'9223372036854775808' is out of range for 'Integer'", 355, 25);
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibSubTypeTest.java:277]: Why are we saying `Integer`? How does this differentiate between `int` and `int` subtypes. Please use the relevant type, instead of an arbitrary name.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 30]
```diff
@@ -287,6 +287,7 @@ public class CodeAnalyzer extends SimpleBLangNodeAnalyzer<CodeAnalyzer.AnalyzerD
             new CompilerContext.Key<>();
 
     private final SymbolResolver symResolver;
+    private SemanticAnalyzer semanticAnalyzer;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:290]: Code analyzer is a phase after semantic analysis. We shouldn't call back.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 31]
```diff
@@ -482,23 +482,56 @@ private BLangConstantValue calculateMod(BLangConstantValue lhs, BLangConstantVal
         return new BLangConstantValue(result, currentConstSymbol.type);
     }
 
+    private Object calculateNegationForInt(BLangConstantValue value) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:485]: Is negation the correct term?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 32]
```diff
@@ -292,6 +294,8 @@ public void visit(BLangPackage pkgNode, AnalyzerData data) {
         }
         SymbolEnv pkgEnv = this.symTable.pkgEnvMap.get(pkgNode.symbol);
         data.env = pkgEnv;
+        int originalTopLevelNodeSize = pkgNode.topLevelNodes.size();
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:297]: Move this closer to where it is used.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 33]
```diff
@@ -304,6 +308,15 @@ public void visit(BLangPackage pkgNode, AnalyzerData data) {
 
         validateEnumMemberMetadata(pkgNode.constants);
 
+        // Then resolve user defined types
+        for (int i = 0; i < pkgNode.topLevelNodes.size(); i++)  {
+            // Prevent analyzing type definitions that get added while analyzing other nodes
+            if (pkgNode.topLevelNodes.get(i).getKind() == NodeKind.TYPE_DEFINITION &&
+                    i <= originalTopLevelNodeSize - 1) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:315]: Why are we doing this instead of using `originalTopLevelNodeSize` in the for loop?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 34]
```diff
@@ -325,6 +338,11 @@ public void visit(BLangPackage pkgNode, AnalyzerData data) {
                 continue;
             }
 
+            // Analyze type definitions that get added while analyzing other nodes
+            if (pkgLevelNode.getKind() == NodeKind.TYPE_DEFINITION && i <= originalTopLevelNodeSize - 1) {
+                continue;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:343]: Why are we special casing here? Why can't analyze all?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 35]
```diff
@@ -325,6 +338,11 @@ public void visit(BLangPackage pkgNode, AnalyzerData data) {
                 continue;
             }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:340]: Aren't you reanalyzing type definitions again here?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 36]
```diff
@@ -700,9 +718,76 @@ public void visit(BLangTypeConversionExpr conversionExpr, AnalyzerData data) {
...
+
     @Override
     public void visit(BLangFiniteTypeNode finiteTypeNode, AnalyzerData data) {
-        finiteTypeNode.valueSpace.forEach(value -> analyzeNode(value, data));
+        boolean foundUnaryExpr = false;
+        Set<BLangExpression> newValueSpace = new LinkedHashSet<>();
+        boolean isErroredExprInFiniteType = false;
+
+        for (int i = 0; i < finiteTypeNode.valueSpace.size(); i++) {
+            BLangExpression value = finiteTypeNode.valueSpace.get(i);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:760]: Please extract the logic out to a method.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 37]
```diff
@@ -514,6 +514,18 @@ private BType getFiniteTypeMatchWithIntType(BLangLiteral literalExpr, BFiniteTyp
         } else if (literalAssignableToFiniteType(literalExpr, finiteType, TypeTags.BYTE)) {
             setLiteralValueForFiniteType(literalExpr, symTable.byteType, data);
             return symTable.byteType;
+        } else if (literalAssignableToFiniteType(literalExpr, finiteType, TypeTags.FLOAT)) {
+            if (!(literalExpr.value instanceof Long)) {
+                // to prevent eg: 1f|1d|2d f2 = 1; from passing
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:519]: `1f|1d|2d f2 = 1` works. Why should this be disallowed anyway?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 38]
```diff
@@ -541,16 +553,84 @@ private BType getFiniteTypeMatchWithIntLiteral(BLangLiteral literalExpr, BFinite
...
         }
-        return symTable.intType;
+
+        if (literalValue instanceof Double) {
+            return symTable.floatType;
+        } else if (literalValue instanceof String) {
+            return symTable.decimalType;
+        } else {
+            return symTable.intType;
+        }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:563]: Can be just ifs.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 39]
```diff
@@ -541,16 +553,84 @@ private BType getFiniteTypeMatchWithIntLiteral(BLangLiteral literalExpr, BFinite
...
+    }
+
+    private BType clonedIntTypeChecker(BLangLiteral literalExpr, Object literalValue, BType expType,
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:566]: This is not an appropriate name for a method.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 40]
```diff
@@ -541,16 +553,84 @@ private BType getFiniteTypeMatchWithIntLiteral(BLangLiteral literalExpr, BFinite
...
+    }
+
+    private BType clonedCheckForCompatibleLiteralType(BFiniteType finiteType, BLangLiteral literalExpr,
+                                                      Object literalValue, AnalyzerData data) {
+        BType resIntType = symTable.semanticError;
+        for (BLangExpression valueExpr : finiteType.getValueSpace()) {
+            BType tempResType = clonedIntTypeChecker(literalExpr, literalValue, valueExpr.getBType(), data);
+            if (tempResType != symTable.semanticError) {
+                resIntType = tempResType;
+                break;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:592]: Why are you breaking instead of returning?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 41]
```diff
@@ -541,16 +553,84 @@ private BType getFiniteTypeMatchWithIntLiteral(BLangLiteral literalExpr, BFinite
...
+                                             AnalyzerData data) {
+        BType originalLiteralType = literalExpr.getBType();
+        BType compatibleType = clonedCheckForCompatibleLiteralType(finiteType, literalExpr, literalValue, data);
+        if (compatibleType == symTable.semanticError) {
+            String literalType;
+            if (originalLiteralType.tag == TypeTags.INT) {
+                literalType = "Integer";
+            } else {
+                literalType = "Float";
+            }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:608]: See comments re: sticking to the actual type name.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 42]
```diff
@@ -4572,6 +4606,262 @@ public void visit(BLangTypedescExpr accessExpr) {
...
+    }
+
+    public BType checkCompatibilityWithConstructedNumericLiteral(BLangUnaryExpr unaryExpr, BType referredType) {
+        BLangNumericLiteral numericLiteral = createNumericLiteralFormUnaryExpr(unaryExpr);
+        // To check value with sign against expected type
+        return clonedExprTypeChecker(numericLiteral, referredType);
+    }
+
+    public LinkedHashSet getIntSubtypesInUnionType(BLangUnaryExpr unaryExpr, BUnionType expectedType) {
+        LinkedHashSet<BType> intTypesInUnion = new LinkedHashSet<>();
```
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5151]: I think we should avoid using `var` where it isn't complicated to use the actual type. Helps with readability. This is something we follow in b7a code also.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 43]
```diff
@@ -7238,11 +7239,49 @@ public void visit(BLangUnaryExpr unaryExpr) {
...
+                strValueInUnary = "-" + strValueInUnary;
+            }
+
+            if (objectValueInUnary instanceof Long) {
+                objectValueInUnary = Long.parseLong(strValueInUnary);
+            } else if (objectValueInUnary instanceof Double) {
+                objectValueInUnary = Double.parseDouble(strValueInUnary);
+            } else if (objectValueInUnary instanceof String) {
+                objectValueInUnary = strValueInUnary;
+            }
```
[the remark this answers is not in the document]
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:7261]: We are extracting the string value of the numeric literal and concatenating '+' or '-'. Then, to covert the string to the correct object type, we need to parse it again

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 44]
```diff
@@ -806,18 +831,30 @@ public BLangNode transform(ConstantDeclarationNode constantDeclarationNode) {
 
         // Check whether the value is a literal. If it is not a literal, it is an invalid case. So we don't need to
         // consider it.
+        // Note - This logic has been special cased for unary expressions as `+` and `-` numeric literals no longer
+        // go on the literal path but as a unary expression.
```
[the remark this answers is not in the document]
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:835]: For constants without a type node like : `const a = -1; ` in master, it is allowed only for literals but since `-1` is a unary expression, In all the places where it was only allowed for literals I updated it to also allow unary expressions with `+` or `-` numeric literals.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 22 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:2310]: Same reason as[ [1]](https://github.com/ballerina-platform/ballerina-lang/pull/34622#discussion_r871193315)

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 31 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:485]: According to the spec [[2]](https://ballerina.io/spec/lang/master/#section_6.24) it is the correct term right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 32 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:297]: We need to get the original number of top level nodes. In some instances nodes were added after evaluating constants so that is why this was put before that.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 34 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:343]: Since we are analyzing the original type nodes before this for loop, there is no point in analyzing the same node twice.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 35 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:340]: No, only the ones that weren't analyzed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 36 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:760]: Since this is the only purpose of the function why is this necessary?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 41 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:608]: This function only gets called if the expected type is finite. So we won't have sub types there right.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 37 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:519]: In master since `1f|1d|2d f1 = 2;` is not allowed. Should this be allowed?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 45]
```diff
@@ -698,9 +700,68 @@ public void visit(BLangTypeConversionExpr conversionExpr) {
...
+        return newNumericLiteral;
+    }
+
     @Override
     public void visit(BLangFiniteTypeNode finiteTypeNode) {
-        finiteTypeNode.valueSpace.forEach(value -> analyzeNode(value, env));
+        boolean foundUnaryExpr = false;
+        Set<BLangExpression> newValueSpace = new LinkedHashSet<>();
+
+        for (int i = 0; i < finiteTypeNode.valueSpace.size(); i++) {
```
[the remark this answers is not in the document]
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:759]: The regular for loop was used because we need the index to replace the unary expression in the value space

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 37 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:519]: `1f|1d|2d f1 = 2;` should fail, not `1f|1d|2d f2 = 1`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BFiniteType.java (hunk 15 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BFiniteType.java:112]: Can you give an example where nullable becomes 'true' in `BFiniteType`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java [hunk 46]
```diff
@@ -152,7 +152,7 @@ static void genJFieldForInteropField(JFieldBIRFunction birFunc, ClassWriter clas
 
         Label paramLoadLabel = labelGen.getLabel("param_load");
         mv.visitLabel(paramLoadLabel);
-        mv.visitLineNumber(birFunc.pos.lineRange().startLine().line(), paramLoadLabel);
+        mv.visitLineNumber(birFunc.pos.lineRange().startLine().line() + 1, paramLoadLabel);
```
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropMethodGen.java:155]: Please sync the PR with master.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 47]
```diff
@@ -898,8 +944,9 @@ public BLangNode transform(UnionTypeDescriptorNode unionTypeDescriptorNode) {
         BLangFiniteTypeNode bLangFiniteTypeNode = (BLangFiniteTypeNode) TreeBuilder.createFiniteTypeNode();
         for (TypeDescriptorNode finiteTypeEl : finiteTypeElements) {
             SingletonTypeDescriptorNode singletonTypeNode = (SingletonTypeDescriptorNode) finiteTypeEl;
-            BLangLiteral literal = createSimpleLiteral(singletonTypeNode.simpleContExprNode(), true);
-            bLangFiniteTypeNode.addValue(literal);
+            BLangExpression literalOrExpression = createLiteralOrExpression(singletonTypeNode.simpleContExprNode(),
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:947]: `literalOrExpression` isn't required?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 48]
```diff
@@ -482,23 +482,39 @@ private BLangConstantValue calculateMod(BLangConstantValue lhs, BLangConstantVal
...
+        return -1 * ((Long) (value.value));
+    }
+
+    private Object calculateNegationForFloat(BLangConstantValue value) {
+        return String.valueOf(-1 * Double.parseDouble(String.valueOf(value.value)));
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:490]: Why do we need to maintain float as string?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 32 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:297]: Why can't we let the analysis happen for those nodes?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 49]
```diff
@@ -700,9 +716,50 @@ public void visit(BLangTypeConversionExpr conversionExpr, AnalyzerData data) {
         validateAnnotationAttachmentCount(conversionExpr.annAttachments);
     }
 
+    private void replaceUnaryExpr() {
+
+    }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:721]: ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 50]
```diff
@@ -700,9 +716,50 @@ public void visit(BLangTypeConversionExpr conversionExpr, AnalyzerData data) {
...
     @Override
     public void visit(BLangFiniteTypeNode finiteTypeNode, AnalyzerData data) {
-        finiteTypeNode.valueSpace.forEach(value -> analyzeNode(value, data));
+        boolean foundUnaryExpr = false;
+        boolean isErroredExprInFiniteType = false;
+
+        for (int i = 0; i < finiteTypeNode.valueSpace.size(); i++) {
+            BLangExpression value = finiteTypeNode.valueSpace.get(i);
+
+            if (value.getKind() == NodeKind.UNARY_EXPR) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:731]: Extract `value.getKind()` out to a variable.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 51]
```diff
@@ -1403,12 +1405,16 @@ public BType transform(BLangFiniteTypeNode finiteTypeNode, AnalyzerData data) {
                 finiteTypeNode.pos, SOURCE);
 
         BFiniteType finiteType = new BFiniteType(finiteTypeSymbol);
-        for (BLangExpression literal : finiteTypeNode.valueSpace) {
-            literal.setBType(symTable.getTypeFromTag(literal.getBType().tag));
-            finiteType.addValue(literal);
+
+        // In case finiteTypeNode has unary expressions in the value space, we need to
+        // convert them into numeric literals first.
+        semanticAnalyzer.analyzeNode(finiteTypeNode, data.env);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1411]: We shouldn't use the semantic analyzer here. Why can't this be done at semantic analysis.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java [hunk 52]
```diff
@@ -435,7 +440,11 @@ private void narrowTypeForEqualOrNotEqual(BLangBinaryExpr binaryExpr, BLangExpre
         }
 
         NodeKind rhsExperKind = rhsExpr.getKind();
-        if (rhsExperKind == NodeKind.LITERAL || rhsExperKind == NodeKind.NUMERIC_LITERAL) {
+        if (rhsExperKind == NodeKind.LITERAL || rhsExperKind == NodeKind.NUMERIC_LITERAL ||
+                (rhsExperKind == NodeKind.UNARY_EXPR &&
+                ((BLangUnaryExpr) rhsExpr).expr.getKind() == NodeKind.NUMERIC_LITERAL &&
+                (OperatorKind.SUB.equals(((BLangUnaryExpr) rhsExpr).operator) ||
+                        OperatorKind.ADD.equals(((BLangUnaryExpr) rhsExpr).operator)))) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java:447]: This check seems to be done often. Let's extract it out to a method.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 53]
```diff
@@ -493,6 +495,38 @@ BType resolvePatternTypeFromMatchExpr(BLangErrorMatchPattern errorMatchPattern,
         return symTable.noType;
     }
 
+    public BLangNumericLiteral constructNumericLiteralFromUnaryExpr(BLangUnaryExpr unaryExpr) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:498]: Same code repeated?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 37 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:520]: Not addressed? If the comment is wrong fix it.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:520]: Also, this is working on master. Which change of yours resulted in requiring this?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 54]
```diff
@@ -542,16 +554,79 @@ private BType getFiniteTypeMatchWithIntLiteral(BLangLiteral literalExpr, BFinite
...
-        return symTable.intType;
+
+        if (literalValue instanceof Double) {
+            return symTable.floatType;
+        }
+        if (literalValue instanceof String) {
+            return symTable.decimalType;
+        } else {
+            return symTable.intType;
+        }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:565]:
```suggestion
        }
        return symTable.intType;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 55]
```diff
@@ -542,16 +554,79 @@ private BType getFiniteTypeMatchWithIntLiteral(BLangLiteral literalExpr, BFinite
...
+        for (BLangExpression valueExpr : finiteType.getValueSpace()) {
+            resIntType = silentIntTypeCheck(literalExpr, literalValue, valueExpr.getBType(), data);
+            if (resIntType != symTable.semanticError) {
+                return resIntType;
+            }
+        }
+        return resIntType;
+    }
+
+    private BType checkIfLiteralIsOutOfRange(BFiniteType finiteType, BLangLiteral literalExpr, Object literalValue,
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:599]: Method name implies a check but you're returning a BType?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 56]
```diff
@@ -4841,8 +4938,272 @@ public void visit(BLangTypedescExpr accessExpr, AnalyzerData data) {
         data.resultType = types.checkType(accessExpr, actualType, data.expType);
     }
 
+    public LinkedHashSet<BType> getBasicNumericTypesInFiniteType(BType referredType) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4941]: Isn't this logic similar to getBasicNumericTypesInUnionType? Please refactor the methods to avoid duplicating code.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 57]
```diff
@@ -4841,8 +4938,272 @@ public void visit(BLangTypedescExpr accessExpr, AnalyzerData data) {
...
+        BFiniteType finiteType = (BFiniteType) referredType;
+        Set<BLangExpression> valueSpace = finiteType.getValueSpace();
+        LinkedHashSet<BType> basicNumericTypes = new LinkedHashSet<>(valueSpace.size());
+
+        for (BLangExpression value : valueSpace) {
+            BType referredTypeInFiniteType = types.getReferredType(value.getBType());
+            int typeTag = referredTypeInFiniteType.tag;
+            if (TypeTags.isIntegerTypeTag(typeTag) || typeTag == TypeTags.FLOAT || typeTag == TypeTags.DECIMAL) {
+                if (TypeTags.isIntegerTypeTag(typeTag)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4950]: `TypeTags.isIntegerTypeTag(typeTag)` is repeated. Why isn't this an if and else if instead?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 58]
```diff
@@ -4841,8 +4938,272 @@ public void visit(BLangTypedescExpr accessExpr, AnalyzerData data) {
...
+                break;
+            } else if (typeTag == TypeTags.FINITE) {
+                LinkedHashSet<BType> numericTypes = getBasicNumericTypesInFiniteType(referredTypeInUnionType);
+                basicNumericTypes.addAll(numericTypes);
+            }
+        }
+        return basicNumericTypes;
+    }
+
+    public BLangNumericLiteral createNumericLiteralFromUnaryExpr(BLangUnaryExpr unaryExpr) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4996]: Duplicate code again?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 59]
```diff
@@ -4841,8 +4938,272 @@ public void visit(BLangTypedescExpr accessExpr, AnalyzerData data) {
...
+        BType referredType = types.getReferredType(data.expType);
+        int referredTypeTag = referredType.tag;
+
+        //Allow subtraction and add (to resolve ex: byte x = +7) operators to get expected type
+        boolean isAddOrSubOperator = OperatorKind.SUB.equals(unaryExpr.operator) ||
+                OperatorKind.ADD.equals(unaryExpr.operator);
+
+        // Set expected type for subtraction operator
+        if (OperatorKind.SUB.equals(unaryExpr.operator)) {
+            if (data.expType == symTable.noType) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5054]: Extract the logic out to a method. Can get rid of the nested if/else ifs.

**Review by MaryamZi — COMMENTED** [review]
Please check on improvement that can be done including
- avoiding duplicating code
- repeated checks
- large methods with nested if/else ifs that can be broken into smaller methods

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java (hunk 47 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:946]: It is added to the created `bLangFiniteTypeNode` in the next line right... Didn't quite get what is meant by this, can you elaborate on this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 48 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:490]: This logic was written by Randika, I just put them into separate functions. But from node builder itself when `TokenKind` is `DECIMAL_FLOATING_POINT_LITERAL_TOKEN` that is how it has been handled. Unlike when `TokenKind` is `INTEGER_LITERAL_TOKEN` or  `HEX_INTEGER_LITERAL_TOKEN` where we parse before assigning  to `value` attribute.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 32 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:292]: Those nodes need to be analysed after analyzing  the original number of nodes to properly resolve. Like in some cases where additionally created nodes were being used inside functions, I got errors when I tried to analyse them before analyzing that function node.

**Comment by SandaruJayawardana** [comment]
Seems https://github.com/ballerina-platform/ballerina-lang/issues/34624 is not fixed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 60]
```diff
@@ -803,41 +854,15 @@ public BLangNode transform(ConstantDeclarationNode constantDeclarationNode) {
...
-            // any of the type def visiting logic in symbol enter.
-            constantNode.associatedTypeDefinition = typeDef;
+        // Check whether the value is a literal or a unary expression with `+` or `-` numeric literal
+        // If it is not any one of the above, it is an invalid case, so we don't need to consider it.
+        if (nodeKind == NodeKind.LITERAL || nodeKind == NodeKind.NUMERIC_LITERAL ||
+                types.isExpressionAnAllowedUnaryType(constantNode.expr, nodeKind)) {
+            // Note - If the RHS is a literal, we need to create an anonymous type definition which can later be used
+            // in type definitions.h
+            createAnonymousTypeDefForConstantDeclaration(constantNode, pos, identifierPos);
         }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:866]: Can't we do these in symbol enter instead?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/multiply-operation-negative.bal [hunk 61]
```diff
@@ -45,3 +45,9 @@ function testImplicitConversion() {
     var y1 = d * e;
     any y2 = d * e;
 }
+
+function overflowByMultiplication() {
+    int num1 = -1;
+    int num2 = -9223372036854775808;
+    int ans = num1 * num2;
```
Comment (SandaruJayawardana) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/multiply-operation-negative.bal:52]: IMO this test will not check overflow of multiplication since already there is a compile error for `int num2 = -9223372036854775808;` and program will fail before the runtime (where the multiplication is happened). We can test multiplication of constants in compile time. BTW currently it gives incorrect results. 
Ex.
```ballerina
const num1 = -2;
const  num2 = -9223372036854775807;
const int ans = num1 * num2; // ans = -2
```
Might be needed to fix separately.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 62]
```diff
@@ -482,23 +482,39 @@ private BLangConstantValue calculateMod(BLangConstantValue lhs, BLangConstantVal
...
+    }
+
     private BLangConstantValue calculateNegation(BLangConstantValue value) {
         Object result = null;
-        switch (this.currentConstSymbol.type.tag) {
+        BType constSymbolValType = value.type;
+        int constSymbolValTypeTag = constSymbolValType.tag;
+
+        switch (constSymbolValTypeTag) {
             case TypeTags.INT:
```
Comment (SandaruJayawardana) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:506]: I think, we have to handle `byte` type also.

Ex:
```ballerina
const byte num1 = -(-2);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java (hunk 47 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:926]: Meant we can just do

```java
bLangFiniteTypeNode.addValue(createLiteralOrExpression(singletonTypeNode.simpleContExprNode(), true));
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 63]
```diff
@@ -781,6 +787,51 @@ private String calculateResourceFunctionName(IdentifierToken accessorName, NodeL
...
+            literal = (BLangLiteral) TreeBuilder.createLiteralExpression();
+        } else {
+            literal = (BLangLiteral) TreeBuilder.createNumericLiteralExpression();
+        }
+        if (nodeKind == NodeKind.LITERAL || nodeKind == NodeKind.NUMERIC_LITERAL) {
+            literal.setValue(((BLangLiteral) constantNode.expr).value);
+            literal.setOriginalValue(((BLangLiteral) constantNode.expr).originalValue);
+            literal.setBType(constantNode.expr.getBType());
+        } else {
+            // Since we only allow literals and unary expressions to come to this point we can straightaway
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:806]: Only unary expressions?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 32 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:292]: The new ones get added at the end, right? Any idea why the newer ones were analyzed before the existing ones?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 64]
```diff
@@ -697,7 +713,45 @@ public void visit(BLangTypeConversionExpr conversionExpr, AnalyzerData data) {
...
+                    continue;
+                }
+                // Replacing unary expression with numeric literal type for + and - numeric values
+                BLangNumericLiteral newNumericLiteral =
+                        Types.constructNumericLiteralFromUnaryExpr((BLangUnaryExpr) value);
+                finiteTypeNode.valueSpace.set(i, newNumericLiteral);
+            } else if ((valueKind == NodeKind.LITERAL || valueKind == NodeKind.NUMERIC_LITERAL) &&
+                    ((BLangLiteral) value).originalValue == null) {
+                // To handle enums
+                continue;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:739]: There's a codecov warning?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 65]
```diff
@@ -4041,6 +4095,16 @@ public void visit(BLangConstant constant, AnalyzerData data) {
...
     }
 
+    private boolean isNodeKindAllowedForConstants(BLangExpression expression, BLangConstant constant) {
+        return ((expression.getKind() == NodeKind.UNARY_EXPR &&
+                ((BLangUnaryExpr) constant.expr).expr.getKind() != NodeKind.NUMERIC_LITERAL) &&
+                (!OperatorKind.SUB.equals(((BLangUnaryExpr) constant.expr).operator) ||
+                        !OperatorKind.ADD.equals(((BLangUnaryExpr) constant.expr).operator)) ||
+                !(expression.getKind() == LITERAL || expression.getKind() == NUMERIC_LITERAL) &&
+                        expression.getKind() != NodeKind.UNARY_EXPR) &&
+                constant.typeNode == null;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:4105]: Can improve readability by breaking into multiple if conditions and returning early.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 66]
```diff
@@ -538,16 +539,78 @@ private BType getFiniteTypeMatchWithIntLiteral(BLangLiteral literalExpr, BFinite
             literalExpr.value = String.valueOf(literalValue);
             return type;
         }
+        // Handle out of range ints
+        if (literalValue instanceof Double) {
+            return symTable.floatType;
+        }
+        if (literalValue instanceof String) {
+            return symTable.decimalType;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:547]: Please check all the codecov warnings. Since this is a significant change, we need to pay extra attention.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java [hunk 67]
```diff
@@ -264,8 +266,13 @@ public void visit(BLangTypeTestExpr typeTestExpr) {
             // Terminate for undefined symbols
             return;
         }
+
         final TypeChecker.AnalyzerData data = new TypeChecker.AnalyzerData();
         data.env = env;
+        // If typeNode has finite types with unary expressions in the value space, we need to
+        // convert them into numeric literals.
+        semanticAnalyzer.analyzeNode(typeTestExpr.typeNode, data.env);
+
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeNarrower.java:275]: Not the correct place IMO. The semantic analyzer/type checker should ideally handle this in their visits.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java (hunk 63 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:806]: yes, the function that leads here, allows only literals to be assigned to constants, however, since we special cased that to allow unary as well, after checking for literals we are only left with unary  expressions

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:806]: Meant that the comment wasn't quite right.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/multiply-operation-negative.bal (hunk 61 above)
Comment (suleka96) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/multiply-operation-negative.bal:52]: Created #36648 to track

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java (hunk 62 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:506]: created #36649 to track

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 32 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:292]: New ones are not exactly getting resolved before the existing ones, but since we are analyzing `NodeKind.TYPE_DEFINITION` after constants before analyzing other nodes in occurrence order, then if there were new nodes that were added at the end that are of type `NodeKind.TYPE_DEFINITION` then without `originalTopLevelNodeSize` those will also get analysed in that for loop. The issue in that is the nodes that get added at the end only gets resolved properly if we first resolve the functions and other nodes that come before them. So I'm using `originalTopLevelNodeSize` to only analyse the original number of `NodeKind.TYPE_DEFINITION` nodes that were present. After the original number of `NodeKind.TYPE_DEFINITION`  are analysed the rest of the nodes will  get analysed as usual in their occurrence order.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 64 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:739]: This was put to handle enums when the visit was called from symbol resolver.

**Comment by MaryamZi** [comment]
Shall we remove https://github.com/ballerina-platform/ballerina-lang/issues/32508 from the fixed issue list since it was fixed separately?

**Comment by MaryamZi** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/33689 also seems to work on 2201.1.0.

**Comment by MaryamZi** [comment]
Re: https://github.com/ballerina-platform/ballerina-lang/issues/34624, the following still doesn't work.

```ballerina
type bar 1|2|-45;

public function main() {
   bar b = -(-(-45));
}
```

**Comment by MaryamZi** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/31826 also works on update 1 (and maybe even 2201.0.0). Please update the descriptions to specify if this PR fixes a particular issue or just adds tests for already fixed issues.

**Comment by MaryamZi** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/32884 is also fixed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 68]
```diff
@@ -698,7 +714,43 @@ public void visit(BLangTypeConversionExpr conversionExpr, AnalyzerData data) {
...
+                if (resultType == symTable.semanticError) {
+                    isErroredExprInFiniteType = true;
+                }
+                // Replacing unary expression with numeric literal type for + and - numeric values
+                BLangNumericLiteral newNumericLiteral =
+                        Types.constructNumericLiteralFromUnaryExpr((BLangUnaryExpr) value);
+                finiteTypeNode.valueSpace.set(i, newNumericLiteral);
+            } else if ((valueKind == NodeKind.LITERAL || valueKind == NodeKind.NUMERIC_LITERAL) &&
+                    ((BLangLiteral) value).originalValue == null) {
+                // To handle enums when the visit is being called from symbol resolver
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:738]: Can't we check for a flag instead? ENUM_MEMBER for example.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 69]
```diff
@@ -4075,6 +4127,20 @@ public void visit(BLangConstant constant, AnalyzerData data) {
...
+    private boolean isNodeKindAllowedForConstants(BLangExpression expression, BLangConstant constant) {
+        if ((expression.getKind() == NodeKind.UNARY_EXPR &&
+                ((BLangUnaryExpr) constant.expr).expr.getKind() != NodeKind.NUMERIC_LITERAL)  &&
+                (!OperatorKind.SUB.equals(((BLangUnaryExpr) constant.expr).operator) ||
+                !OperatorKind.ADD.equals(((BLangUnaryExpr) constant.expr).operator))) {
+            return constant.typeNode == null;
+        }
+        if (!(expression.getKind() == LITERAL || expression.getKind() == NUMERIC_LITERAL) &&
+                expression.getKind() != NodeKind.UNARY_EXPR) {
+            return constant.typeNode == null;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:4139]: Didn't we add util methods for these checks?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 51 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1418]: Did we create an issue for this?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 70]
```diff
@@ -498,6 +501,80 @@ BType resolvePatternTypeFromMatchExpr(BLangErrorMatchPattern errorMatchPattern,
         return symTable.noType;
     }
 
+    public boolean isExpressionInUnaryValid(BLangExpression expr) {
+        if (expr.getKind() == NodeKind.GROUP_EXPR) {
+            // To resolve ex: -(45) kind of scenarios
+            return ((BLangGroupExpr) expr).expression.getKind() == NodeKind.NUMERIC_LITERAL;
+        } else {
+            return expr.getKind() == NodeKind.NUMERIC_LITERAL;
+        }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:510]: Needs to be checked recursively. See https://github.com/ballerina-platform/ballerina-lang/pull/34622#issuecomment-1166823070.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 71]
```diff
@@ -498,6 +501,80 @@ BType resolvePatternTypeFromMatchExpr(BLangErrorMatchPattern errorMatchPattern,
...
+    }
+
+    public static BLangExpression getExpressionInUnary(BLangExpression expr) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:513]: Method name isn't accurate.

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:513]: Why is this public?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 72]
```diff
@@ -498,6 +501,80 @@ BType resolvePatternTypeFromMatchExpr(BLangErrorMatchPattern errorMatchPattern,
...
+        if (expr.getKind() == NodeKind.GROUP_EXPR) {
+            return ((BLangGroupExpr) expr).expression;
+        } else {
+            return expr;
+        }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:518]:
```suggestion
        }
        return expr;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 73]
```diff
@@ -566,17 +629,29 @@ private BType getIntegerLiteralType(BLangLiteral literalExpr, Object literalValu
...
                 if (TypeTags.isIntegerTypeTag(memberRefType.tag) || memberRefType.tag == TypeTags.BYTE) {
-                    BType intLiteralType = getIntLiteralType(memType, literalValue);
+                    BType intLiteralType = getIntLiteralType(memType, literalValue, data);
                     if (intLiteralType == memberRefType) {
                         return intLiteralType;
                     }
                 } else if (memberRefType.tag == TypeTags.JSON || memberRefType.tag == TypeTags.ANYDATA ||
                         memberRefType.tag == TypeTags.ANY) {
+                    if (literalValue instanceof Double) {
+                        return symTable.floatType;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:650]: Please check all codecov warnings.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 74]
```diff
@@ -4851,8 +4936,226 @@ public void visit(BLangTypedescExpr accessExpr, AnalyzerData data) {
...
+        Set<BLangExpression> valueSpace = referredType.getValueSpace();
+        LinkedHashSet<BType> typesInValueSpace = new LinkedHashSet<>(valueSpace.size());
+        for (BLangExpression expr : valueSpace) {
+            typesInValueSpace.add(expr.getBType());
+        }
+        return typesInValueSpace;
+    }
+
+    public BType getNewExpectedTypeForFiniteAndUnion(LinkedHashSet<BType> numericTypes, BType newExpectedType) {
+        LinkedHashSet<BType> basicNumericTypes = getBasicNumericTypes(numericTypes);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4985]: What's the reason to add this new applicable preferred type logic? Don't we have existing logic for numeric literal compatibility? cc @chiranSachintha

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 75]
```diff
@@ -5320,22 +5340,20 @@ private BLangLiteral createEmptyStringLiteral(Location pos) {
...
 
     private BLangLiteral createSimpleLiteral(Node literal) {
+        if (this.isInFiniteContext) {
+            return createSimpleLiteral(literal, true);
+        }
         return createSimpleLiteral(literal, false);
     }
 
-    private BLangLiteral createSimpleLiteral(Node literal, boolean isFiniteType) {
+    private BLangExpression createLiteralOrExpression(Node literal, boolean isFiniteType) {
```
[the remark this answers is not in the document]
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5349]: When it is not inside a finite context it is false, like when creating literals for xml processing instructions and etc.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 70 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:510]: created  #36740 to track

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 68 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:738]: The `flagSet` for the enum member here is empty.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 69 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:4139]: This check is slightly different from the check in util method... since this is for constants.. like with leaving out the check for group expr because we have only special cased constants for unary expr and so on...

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 74 above)
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4985]: With the current logic, for ex: `-1f|-1|-1d|"string" x = -1; ` the type of -1 comes as `int`, which is the expected result. If we replace `getNewExpectedTypeForFiniteAndUnion` with `getPreferredMemberTypeTag` we get `float` as the preferred type, which is not correct for this case

**Comment by MaryamZi** [comment]
@suleka96, can you please sync the PR with master again?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 76]
```diff
@@ -498,6 +501,80 @@ BType resolvePatternTypeFromMatchExpr(BLangErrorMatchPattern errorMatchPattern,
...
+            strValueInUnary = "+" + strValueInUnary;
+        } else if (OperatorKind.SUB.equals(unaryOperatorKind)) {
+            strValueInUnary = "-" + strValueInUnary;
+        }
+
+        if (objectValueInUnary instanceof Long) {
+            objectValueInUnary = Long.parseLong(strValueInUnary);
+        } else if (objectValueInUnary instanceof Double) {
+            objectValueInUnary = Double.parseDouble(strValueInUnary);
+        } else if (objectValueInUnary instanceof String) {
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:535]: Just to be sure. Last condition can be just else right

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 77]
```diff
@@ -7221,11 +7221,17 @@ public void visit(BLangUnaryExpr unaryExpr) {
             return;
         }
 
+        // Since the support for singleton type changes are not complete, continuing with the finite type will require
+        // significant changes, therefore we are constructing a numeric literal.
+        if (types.isExpressionInUnaryValid(unaryExpr.expr) && unaryExpr.expectedType.tag == TypeTags.FINITE) {
```
[the remark this answers is not in the document]
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:7226]: There seems to be instances where the expected type can be null here, so isn't it easier to first check the expression to be sure it won't be null.

**Review by MaryamZi — APPROVED** [review]

**Comment by MaryamZi** [comment]
@suleka96, please tag the milestone for the fixed issues.
