### PR TITLE
Address review suggestions in PR #34371

### LINKED ISSUE #34405: Address suggestions in `PR #34371`
**Description:**
$title.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by SandaruJayawardana**
Fixes #34405

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java [hunk 1]
```diff
@@ -596,26 +596,20 @@ public void visit(BLangConstant astConstant) {
         this.env.enclPkg.constants.add(birConstant);
     }
 
+    private ConstValue getBIRConstantVal(BLangConstantValue constValue, BType type) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java:599]: Why do we need a separate method? Instead of updating the existing method to accept the type?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 2]
```diff
@@ -820,6 +805,25 @@ public void visit(BLangPackage pkgNode) {
         result = pkgNode;
     }
 
+    private void constantRewrite(BLangPackage pkgNode, BLangBlockFunctionBody initFnBody) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:808]:
```suggestion
    private void rewriteConstants(BLangPackage pkgNode, BLangBlockFunctionBody initFnBody) {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 3]
```diff
@@ -820,6 +805,25 @@ public void visit(BLangPackage pkgNode) {
...
+        for (BLangConstant constant : pkgNode.constants) {
+            BType constType = types.getReferredType(constant.symbol.type);
+            if (constType.tag == TypeTags.INTERSECTION) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:811]: You can check the inverse and continue here. That way we can get rid of the indentation in L812-L822.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 4]
```diff
@@ -820,6 +805,25 @@ public void visit(BLangPackage pkgNode) {
...
+                for (BType memberType : ((IntersectionType) constType).getImmutableType().getConstituentTypes()) {
+                    if (memberType.tag == TypeTags.RECORD) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:813]: Same here, check the inverse and continue.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 5]
```diff
@@ -820,6 +805,25 @@ public void visit(BLangPackage pkgNode) {
         result = pkgNode;
     }
 
+    private void constantRewrite(BLangPackage pkgNode, BLangBlockFunctionBody initFnBody) {
+        for (BLangConstant constant : pkgNode.constants) {
+            BType constType = types.getReferredType(constant.symbol.type);
+            if (constType.tag == TypeTags.INTERSECTION) {
+                for (BType memberType : ((IntersectionType) constType).getImmutableType().getConstituentTypes()) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:812]: Why aren't we just casting?

```suggestion
                for (BType memberType : ((BIntersectionType) constType).getConstituentTypes()) {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java [hunk 6]
```diff
@@ -299,4 +307,72 @@ public static String getPackageAlias(SymbolEnv env, String compUnitName, Package
...
+        structureType.fields = fields;
+
+        if (origStructureType.tag == TypeTags.OBJECT) {
+            return;
+        }
+
+        if (isConstant) {
+            ((BLangRecordTypeNode) structureTypeNode).sealed = true;
+            ((BRecordType) structureType).restFieldType = new BNoType(TypeTags.NONE);
+        }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java:364]: This doesn't seem like something that should be done here. Can't we do do this where it is called instead?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java [hunk 7]
```diff
@@ -299,4 +307,72 @@ public static String getPackageAlias(SymbolEnv env, String compUnitName, Package
...
+                                                BStructureType origStructureType, Location pos,
+                                                SymbolEnv env, PackageID pkgID, Set<BType> unresolvedTypes,
+                                                long flag, boolean isImmutable, boolean isConstant) {
+        BTypeSymbol immutableStructureSymbol = structureType.tsymbol;
+        LinkedHashMap<String, BField> fields = new LinkedHashMap<>();
+        for (BField origField : origStructureType.fields.values()) {
+            BType fieldType;
+            if (isImmutable) {
+                fieldType = ImmutableTypeCloner.getImmutableType(pos, types, origField.type, env,
+                        env.enclPkg.packageID, env.scope.owner, symTable, anonymousModelHelper, names, unresolvedTypes);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java:324]: Shouldn't this happen for the const case also?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 8]
```diff
@@ -821,83 +702,88 @@ private BType createRecordType(BLangExpression expr, BLangConstant constant, Obj
...
-        for (RecordLiteralNode.RecordField field : ((BLangRecordLiteral) expr).fields) {
-            String key;
-            BVarSymbol newSymbol;
-
-            if (field.isKeyValueField()) {
-                BLangRecordLiteral.BLangRecordKeyValueField keyValuePair =
-                        (BLangRecordLiteral.BLangRecordKeyValueField) field;
-                BLangExpression exprValueField = keyValuePair.valueExpr;
+        if (constValueMap.size() != 0) {
+            for (RecordLiteralNode.RecordField field : ((BLangRecordLiteral) expr).fields) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:706]: Let's extract this logic out to a method.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java (hunk 6 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java:364]: Will update. Thanks.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java (hunk 7 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java:324]: Yeah. It happens when we are calling `getImmutableIntersectionType`.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java:323]: My point was if we even need the check at L321. But in the const case, this gets called for the mutable record, right? So I guess we still need this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java [hunk 9]
```diff
@@ -299,4 +306,67 @@ public static String getPackageAlias(SymbolEnv env, String compUnitName, Package
...
     }
+
+    public static void populateStructureFields(Types types, SymbolTable symTable,
+                                                BLangAnonymousModelHelper anonymousModelHelper, Names names,
+                                                BLangStructureTypeNode structureTypeNode,
+                                                BStructureType structureType,
+                                                BStructureType origStructureType, Location pos,
+                                                SymbolEnv env, PackageID pkgID, Set<BType> unresolvedTypes,
+                                                long flag, boolean isImmutable) {
+        BTypeSymbol immutableStructureSymbol = structureType.tsymbol;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java:317]: Is using immutable here, correct?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java [hunk 10]
```diff
@@ -299,4 +306,67 @@ public static String getPackageAlias(SymbolEnv env, String compUnitName, Package
...
+            return;
+        }
+
+        BLangUserDefinedType origTypeRef = new BLangUserDefinedType(
+                ASTBuilderUtil.createIdentifier(pos,
+                        TypeDefBuilderHelper.getPackageAlias(env, pos.lineRange().filePath(),
+                                origStructureType.tsymbol.pkgID)),
+                ASTBuilderUtil.createIdentifier(pos, origStructureType.tsymbol.name.value));
+        origTypeRef.pos = pos;
+        origTypeRef.setBType(origStructureType);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java:366]: Also needs to be done only if `isImmutable` is true? IMO, we can move this logic also to where `populateStructureFields` is called since it is only needed in the immutable case.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java (hunk 9 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java:317]: My bad. Will update the name. Thanks.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java (hunk 10 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeDefBuilderHelper.java]: There are some failing tests with this change. Shall I revert the changes to originals?

**Review by gimantha — APPROVED** [review]
