### PR TITLE
Correct the signature of error type symbol in Semantic API

### LINKED ISSUE #28654: Semantic API signature of the error type symbol is invalid
**Description:**
Semantic API signature of the error type symbol is invalid. For instance return type symbol of the below is a union of error member types and it generates an invalid signature;

**Function Invocation**
```ballerina
import ballerina/io;
io:openReadableCsvFile("");
```

**Expected**
```ballerina
import ballerina/io;
io:ReadableCSVChannel|io:GenericError|io:ConnectionTimedOutError|io:AccessDeniedError|io:FileNotFoundError|io:TypeMismatchError|io:EofError|io:ConfigurationError openReadableCsvFile = io:openReadableCsvFile("");
```

**Actual / Current**
```ballerina
import ballerina/io;
io:ReadableCSVChannel|GenericError|ConnectionTimedOutError|AccessDeniedError|FileNotFoundError|TypeMismatchError|EofError|ConfigurationError openReadableCsvFile = io:openReadableCsvFile("");
```

Seems like we are not honoring package prefixes since default `getModule()` always return empty in https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java#L63

**Affected Versions:**
2.0.0-alpha2

### LINKED ISSUE #28684: Code action `Create variable and typeguard` does not consider return type of function
**Description:**

This code has the same problem mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/28663 also.

Since it is reported I tried a different code action for the case. Looks like variable type is correct but the user has not imported those modules here. So I think it is better to go with the return type of the method `sql:Error?`. Next issue is when we have this error another code action to try and cast adds a CompilationError cast `<$CompilationError$?> db:initializeLinksDb();`. May be an internal anonymous type.

Links-1613538000577

Code is available here.
https://github.com/KRVPerera/Links/blob/bcd8767eae2e5bd66f4e2e8a4e2a10a338324f31/main.bal#L11

The project has a release with this issue https://github.com/KRVPerera/Links/releases/tag/0.2

**Steps to reproduce:**

**Affected Versions:**
SL Alpha 2

**OS, DB, other environment details and versions:**
macOS

**Related Issues (optional):**

https://github.com/ballerina-platform/ballerina-lang/issues/28663

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #28654 
Fixes #28684

image
>
>   * Improved Regex pattern:
image

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java [hunk 1]
```diff
@@ -66,7 +98,7 @@ public String signature() {
         }
 
         ModuleID moduleID = this.getModule().get().id();
-        if ("lang.annotations".equals(moduleID.moduleName()) && "ballerina".equals(moduleID.orgName())) {
+        if (moduleID.moduleName().startsWith("lang") && "ballerina".equals(moduleID.orgName())) {
```
Comment (nadeeshaan) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java:101]: Use `lang.` as the `startsWith` parameter.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java [hunk 2]
```diff
@@ -52,7 +52,8 @@
  */
 public class FunctionGenerator {
 
-    public static final Pattern FULLY_QUALIFIED_MODULE_ID_PATTERN = Pattern.compile("([\\w]+)\\/([\\w.]+):(.+):");
+    public static final Pattern FULLY_QUALIFIED_MODULE_ID_PATTERN = Pattern.compile("([\\w]+)\\/([\\w.]+):([^:]+):" +
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java:55]: Try to get the pattern to a single line, otherwise it is bit hard to read

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java (hunk 1 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java]: Corrected.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java (hunk 2 above)
Comment (sanjana) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/FunctionGenerator.java]: Updated.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java [hunk 3]
```diff
@@ -66,7 +98,7 @@ public String signature() {
         }
 
         ModuleID moduleID = this.getModule().get().id();
-        if ("lang.annotations".equals(moduleID.moduleName()) && "ballerina".equals(moduleID.orgName())) {
+        if (moduleID.moduleName().startsWith("lang.") && "ballerina".equals(moduleID.orgName())) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java:101]: Do we need this change? This means for any error type defined in lang libs, it will omit the module prefix. 🤔

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java [hunk 4]
```diff
@@ -1234,14 +1234,20 @@ public BType readType(int cpI) throws IOException {
...
+                    pkgCpIndex = inputStream.readInt();
+                    pkgId = getPackageId(pkgCpIndex);
+                    BPackageSymbol owner = packageCache.getSymbol(pkgId);
+                    BTypeSymbol errorSymbol;
+                    if (owner != null) {
+                        errorSymbol = new BErrorTypeSymbol(SymTag.ERROR, Flags.PUBLIC, Names.EMPTY, owner.pkgID,
+                                null, owner, symTable.builtinPos, COMPILED_SOURCE);
+                    } else {
+                        errorSymbol = new BErrorTypeSymbol(SymTag.ERROR, Flags.PUBLIC, Names.EMPTY,
+                                env.pkgSymbol.pkgID, null, env.pkgSymbol, symTable.builtinPos, COMPILED_SOURCE);
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:1246]: This change looks good. Shall we also add a comment here stating the assumption which leads to this conditional check? Basically the assumption is, if `owner` is `null`, the module this error is defined in is the current module being defined.

**Review by pubudu91 — DISMISSED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java (hunk 4 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:1247]: @pubudu91 thanks for the suggestion. Added the comment.

**Review by pubudu91 — APPROVED** [review]
