### PR TITLE
Revamp completions after isolation keyword

### LINKED ISSUE #26017: Disabled failing LS tests for completion support of isolated/function keyword
**Description:**

Failing isolated/function keyword completion support LS tests were disabled with following commits. 

- ebb4f58 in PR #25778
- 3a29197 in PR #26888

**Summary of disabled tests are as follows.**

org.ballerinalang.langserver.completion.latest.ClassDefContextTest

- config12.json
- config13.json

org.ballerinalang.langserver.completion.latest.TypeDescContextTest

- function_typedesc16.json
- function_typedesc17.json
- function_typedesc18.json
- function_typedesc19.json

org.ballerinalang.langserver.completion.latest.ExpressionContextTest
- anon_func_expr_ctx_config1a.json
- anon_func_expr_ctx_config1b.json
- object_constructor_expr_ctx_config1.json

### LINKED ISSUE #30685: Completions after isolated keyword are not intelligent enough
**Description:**
Consider the following source snippets

`public type  Hello isolated <cursor>`

```
public type  Hello isolated <cursor>

function hello() {}
```

In both of the cases, the particular context identified, is not consistent

### LINKED ISSUE #32438: [LS] Invalid completions in Module Type Definition Context
**Description:**
According to the spec, type-references can't be preceded by qualifiers of any sort. However, LS suggests type references after qualifiers as follows. 
Screenshot from 2021-08-30 12-49-07

Type-references should not be suggested in this context.

**Steps to reproduce:**
```
type FirstType function;

type SecondType isolated object{

};

type FourthType  object{

};


type ThirdType client F<curosr>;
```
try to get the suggestions on the cursor position.

### LINKED ISSUE #32515: [LS]Completions after isolated keyword is not accurate in assignment context
**Description:**
Consider the following source code. 
```ballerina
function testFunction() {
    function testFunction() {
    int value1 = 1;
    function lambda;
    lambda =  isolated <cursor>
}
```
I get completion items that are not applicable at the cursor position as follows.

Screenshot from 2021-09-01 12-40-15

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject to fix several completion issues

Following is the document used to keep track of the contexts that allows isolation qualifier.
https://docs.google.com/document/d/12s0G_CT-buynWlHsa5Ipomy36382Hj0OeoH89H-bzCs/edit?usp=sharing

Fixes #30685 
Fixes #26017 
Fixes #32438 
Fixes #32515

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionTypeDescriptorNodeContext.java [hunk 1]
```diff
@@ -52,10 +55,23 @@ public FunctionTypeDescriptorNodeContext() {
...
+            NodeList<Token> qualifiers = node.qualifierList();
+            List<Token> otherQuals = node.leadingInvalidTokens();
+            Token lastQualifier;
+            if (qualifiers.size() > 0) {
+                lastQualifier = qualifiers.get(qualifiers.size() - 1);
+            } else {
+                lastQualifier = otherQuals.get(otherQuals.size() - 1);
+            }
+            Set<SyntaxKind> qualKinds = qualifiers.stream().map(Token::kind).collect(Collectors.toSet());
+            qualKinds.addAll(otherQuals.stream().map(Token::kind).collect(Collectors.toSet()));
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionTypeDescriptorNodeContext.java:73]: Are we going to handle a generic type definition use-case here? If so why do we route the completion provider to a more generic one (`FunctionTypeDescriptorNodeContext`) here? We have to fix that routing also along with this fix.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/VariableDeclarationNodeContext.java [hunk 2]
```diff
@@ -45,21 +50,42 @@ public VariableDeclarationNodeContext() {
...
+                /*
+                    Covers the following
+                    x = <qualifier(s)> <cursor>
+                    x = <qualifier(s)>  x<cursor>
+                    currently the qualifier can be isolated/transactional.
+                 */
+                List<Token> qualifiers = initializer.leadingInvalidTokens();
+                Token lastQualifier = qualifiers.get(qualifiers.size() - 1);
+                Set<SyntaxKind> qualKinds = qualifiers.stream().map(Node::kind).collect(Collectors.toSet());
+                completionItems.addAll(getCompletionItemsOnQualifiers(qualKinds, lastQualifier, context));
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/VariableDeclarationNodeContext.java:66]: We are duplicating this code segment. Let's clean this if else ladder

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionTypeDescriptorNodeContext.java (hunk 1 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionTypeDescriptorNodeContext.java:73]: Not the generic type I have put `T` for type name. Will refactor this

Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionTypeDescriptorNodeContext.java:73]: desktop

Currently the resolved syntax tree for the respective scenario is as above. The node at cursor becomes the function type descriptor in this case. I suppose we are not able to tackle the problem in the routing approach.

Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionTypeDescriptorNodeContext.java]: The comment I have put may have mislead you. Please take a look at the new comment.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/VariableDeclarationNodeContext.java (hunk 2 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/VariableDeclarationNodeContext.java]: Also removing the routing to the parent node as we have handled the isolation case now. This could take some time, as there are many test cases failing after removing that

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionTypeDescriptorNodeContext.java (hunk 1 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionTypeDescriptorNodeContext.java]: >Are we going to handle a generic type definition use-case here? If so why do we route the completion provider to a more generic one (FunctionTypeDescriptorNodeContext) here? We have to fix that routing also along with this fix.

Added Pre validation logic to fix this

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/VariableDeclarationNodeContext.java (hunk 2 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/VariableDeclarationNodeContext.java]: >We are duplicating this code segment. Let's clean this if else ladder
Done

**Review by IMS94 — CHANGES_REQUESTED** [review]
Added few minor comments

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java [hunk 3]
```diff
@@ -69,6 +69,16 @@ public AssignmentStatementNodeContext() {
...
             completionItems.addAll(this.getCompletionItemList(moduleContent, context));
+        } else if (onSuggestionsAfterQualifiers(context, node.expression())) {
+            /*
+            Captures the following case.
+            (1) TypeName c = <qualifier(s)> <cursor>
+            Currently qualifier can be isolated, transactional, client, service.
+             */
+
+            completionItems.addAll(getCompletionItemsOnQualifiers(node.expression(), context));
+            this.sort(context, node, completionItems);
```
[the remark this answers is not in the document]
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java]: done

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 4]
```diff
@@ -1455,4 +1457,30 @@ public static Boolean withinLockStatementNode(BallerinaCompletionContext context
...
+                        .stream().collect(Collectors.toList());
+                break;
+            default:
+                qualifiers = new ArrayList<>();
+        }
+        if (qualifiers.isEmpty()) {
+            qualifiers.addAll(node.leadingInvalidTokens());
+        }
+        return qualifiers;
+    }
```
[the remark this answers is not in the document]
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1482]: done

**Review by IMS94 — DISMISSED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java [hunk 5]
```diff
@@ -607,4 +608,58 @@ private CompletionItem getModuleCompletionItem(String label, String insertText,
...
+     * returns the possible completion items.
+     * <p>
+     * Currently, isolated, transactional, client, service are considered qualifiers.
+     *
+     * @param node    node of which the qualifiers are checked.
+     * @param context completion context.
+     * @return
+     */
+    protected List<LSCompletionItem> getCompletionItemsOnQualifiers(Node node, BallerinaCompletionContext context) {
+        List<Token> qualifiers = CommonUtil.getQualifiersOfNode(node);
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java:623]: For the safety, check the size before

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModuleVariableDeclarationNodeContext.java [hunk 6]
```diff
@@ -55,9 +59,12 @@ public ModuleVariableDeclarationNodeContext() {
         List<LSCompletionItem> completionItems = new ArrayList<>();
         ResolvedContext resolvedContext;
         TypeDescriptorNode tDescNode = node.typedBindingPattern().typeDescriptor();
-        if (this.withinInitializerContext(ctx, node)) {
-            completionItems.addAll(this.initializerContextCompletions(ctx, tDescNode));
+        if (node.initializer().isPresent() && this.withinInitializerContext(ctx, node)) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ModuleVariableDeclarationNodeContext.java:62]: Get the sorting invocation out of the if clauses. We can enclose the `return CompletionUtil.route(ctx, node.parent());` within the else clause. Also, send all the routing calls through the overridden `route` method. If we want to call a separate the super's `route` method, do that within the overridden method so the implementation will be consistent

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeDefinitionNodeContext.java [hunk 7]
```diff
@@ -52,21 +52,31 @@ public TypeDefinitionNodeContext() {
...
-
+        List<LSCompletionItem> completionItems = new ArrayList<>();
+        if (onSuggestionsAfterQualifiers(context, node.typeDescriptor())) {
+            /*
+             * Covers the following
+             * type T <qualifier(s)> x<cursor>
+             * Currently the qualifier can be isolated/transactional.
+             */
+            completionItems.addAll(getCompletionItemsOnQualifiers(node.typeDescriptor(), context));
+            return completionItems;
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeDefinitionNodeContext.java:75]: no need to return from here. Let it fall through to the end

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeDefinitionNodeContext.java (hunk 7 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeDefinitionNodeContext.java]: Done

**Review by nadeeshaan — APPROVED** [review]
LGTM. Implementation is very good and concise.
