### PR TITLE
Decode record field name value

### LINKED ISSUE #29538: `fromJsonWithType` fails with NPE, but `cloneWithType` works for the same json payload
Here is the same code I’ve used. 

```
type StockQuery record {|
    MetaData 'Meta\ Data;
|};

type MetaData record {|
    string '1\.\ Information;
    string '2\.\ Symbol;
    string '3\.\ Last\ Refreshed;
    string '4\.\ Interval;
    string '5\.\ Output\ Size;
    string '6\.\ Time\ Zone;
|};

public function main() returns error? {
    json jsonPayload = {"Meta Data": {
            "1. Information": "Intraday (5min) open, high, low, close prices and volume",
            "2. Symbol": "IBM",
            "3. Last Refreshed": "2021-03-22 19:40:00",
            "4. Interval": "5min",
            "5. Output Size": "Compact",
            "6. Time Zone": "US/Eastern"
        }};
    StockQuery stockQuery = check jsonPayload.fromJsonWithType(StockQuery);
    // StockQuery stockQuery = check jsonPayload.cloneWithType(StockQuery);
}
```

Here is the output:
```
error: java.lang.NullPointerException
        at ballerina.lang.value.1_0_0:fromJsonWithType(value.bal:214)
           json:main(json.bal:57)
```

### PR DESCRIPTION
**Pull request by KRVPerera**
## Purpose
Fixes #29538

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java [hunk 1]
```diff
@@ -844,7 +844,7 @@ private void createRecordField(MethodVisitor mv, BField field) {
         loadType(mv, field.type);
 
         // Load field name
-        mv.visitLdcInsn(field.name.value);
+        mv.visitLdcInsn(decodeIdentifier(field.name.value));
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java:847]: since we use `putValue()` generated method to initialize fields, this change will not break record value creation. 
+1

**Review by manuranga — APPROVED** [review]
