### PR TITLE
[2201.3.x] Fix NPE in ArrayTypeSymbol

### LINKED ISSUE #38868: [Bug]: "Create variable" code action not suggested for `array:enumerate` usage
### Description

$title. Only "Ignore return value" is suggested.

### Steps to Reproduce

```ballerina
public function main() {
    string[] greetings = ["Hello", "Bonjour", "Hola", "Ciao"];
    greetings.enumerate();
}
```

### Affected Version(s)

2201.3.0-RCs

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject and add unit test for CreateVariableCodeAction

Fixes #38868 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by dulajdilshan — DISMISSED** [review]

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java [hunk 1]
```diff
@@ -364,10 +364,9 @@ public BallerinaVariableSymbol createVariableSymbol(BVarSymbol symbol, String na
     }
 
     private boolean isReadonlyIntersectionArrayType(BType type) {
-        if (type.tag == TypeTags.INTERSECTION && type.tsymbol.getOrigin() == SymbolOrigin.VIRTUAL) {
+        if (type.tag == TypeTags.INTERSECTION && type.tsymbol != null && type.tsymbol.getOrigin() == SymbolOrigin.VIRTUAL) {
```
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java:367]: This may exceed # of chars for the horizontal line. Shall we break this into two lines?

Comment (malinthar) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFactory.java:367]: Will do

**Review by dulajdilshan — APPROVED** [review]
LGTM
