### PR TITLE
Remove ballerina --config option and compile command

### LINKED ISSUE #19455: Cannot pass config to ballerina compile command
**Description:**
This does not work.
```
ballerina compile mod1 --b7a.config.file=conf/ballerina.conf
```
But it work with  build.
```
ballerina compile mod1 --b7a.config.file=conf/ballerina.conf
```

Also we need to remove --config as well. Anyway --config also does not work.

### PR DESCRIPTION
**Pull request by warunalakshitha**
## Purpose

Fixes #19455 and #19428

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/TestCommand.java [hunk 1]
```diff
@@ -292,7 +289,8 @@ public void printLongDesc(StringBuilder out) {
 
     @Override
     public void printUsage(StringBuilder out) {
-        out.append("  ballerina test [<module-name>] \n");
+        out.append(" ballerina test [--offline] [--sourceroot <path>] [--experimental] [--skip-lock]\n" +
+                           "[<module-name> | -a | --all]  [--] [(--key=value)...]\n");
```
Comment (hemikak) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/cmd/TestCommand.java]: Extra space between `| --all]  [--]`
