### PR TITLE
Fix cleaning of entire target directory during a single module build

### LINKED ISSUE #20732: Building one module deletes the entire target directory
**Description:**
When we try to build one module it deletes the jar of other independent modules as it deletes the entire directory.

**Steps to reproduce:**

1. Create a ballerina project with two modules.
2. Build one module (jar will be created for that module).
3. Build the other module. Now the previously created jar will not be there.

**Affected Versions:**
jballerina-1.1.0

**Suggested Labels (optional):**
Area/BuildTools

### PR DESCRIPTION
**Pull request by IrushiL**
Fixes #20732

## Check List 
- [X] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [X] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java [hunk 1]
```diff
@@ -717,6 +717,24 @@ public void testTargetCacheDirectory() throws IOException {
...
+        String[] compileArgs = {"mymodule", "--skip-tests"};
+        Path target = this.testResources.resolve("valid-project").resolve(ProjectDirConstants.TARGET_DIR_NAME);
+
+        BuildCommand buildCommand = new BuildCommand(this.testResources.resolve("valid-project"),
+                printStream, printStream, false, true);
+        new CommandLine(buildCommand).parse(compileArgs);
+        buildCommand.execute();
+
+        // Executable of a module that is not built.
+        Path executablePath = target.resolve(ProjectDirConstants.BIN_DIR_NAME).resolve("mytemplate.jar");
```
Comment (warunalakshitha) [inline cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java]: Where we build the mytemplate module. Another test?

Comment (warunalakshitha) [reply cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java]: Also shall we check whether the target directory stuff cleaned ( ex. balo, jar etc)

Comment (IrushiL) [reply cli/ballerina-packerina/src/test/java/org/ballerinalang/packerina/cmd/BuildCommandTest.java]: Yes, the `mytemplate` module is built in the dependent test `testBuildCommand`.

There isn't actually a way to check if the relevant target directory resources are cleaned in the test case since it is an intermediate step and the artifacts will get replaced. However, this was verified when debugging the code.
