### PR TITLE
Fix extract to function code action and CCE in create type code action

### LINKED ISSUE #38850: [Bug]: CCE in CreateTypeCodeAction for partially written record types
### Description

Consider
```ballerina
type FuelEntry re<cursor>

function myFunc() {
    
}
```
At cursor, following exception is thrown:
```java
[Error - 6:44:39 PM] CodeAction 'CreateTypeCodeAction' failed! {, error: 'class java.lang.String cannot be cast to class org.wso2.ballerinalang.compiler.util.Name (java.lang.String is in module java.base of loader 'bootstrap'; org.wso2.ballerinalang.compiler.util.Name is in unnamed module of loader 'app')'}
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.wso2.ballerinalang.compiler.util.Name (java.lang.String is in module java.base of loader 'bootstrap'; org.wso2.ballerinalang.compiler.util.Name is in unnamed module of loader 'app')
	at org.ballerinalang.langserver.codeaction.providers.CreateTypeCodeAction.getCodeActions(CreateTypeCodeAction.java:92)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$4(CodeActionRouter.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$5(CodeActionRouter.java:124)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:120)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:49)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:169)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:334)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Steps to Reproduce

See description

### Affected Version(s)

2201.3.0-rc3

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #38891: [Bug]: Returning invalid result with extract to function code action
### Description

Consider the following scenario,

https://user-images.githubusercontent.com/61020198/204779957-5d91a3af-06e0-449c-8d7f-213ed1683fff.mov

### Steps to Reproduce

```
type TestRecordType record {
    string name;
    int age;
};

public function TestFunc(string[] names, int x) returns string[]|error {
    TestRecordType[] rec = [];
    foreach var item in names {
        TestRecordType[] result = [{name: "hello", age: 20}];
        rec.push(...result);
    }
}
```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
This PR fixes returning an incorrect result with extract to function code action and CCE in create type code action.

Fixes #38891 
Fixes #38850 

## Samples
https://user-images.githubusercontent.com/61020198/205876162-c6198cad-1aed-4c49-95e4-2690cab13f56.mov

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java [hunk 1]
```diff
@@ -298,7 +298,7 @@ public static Map<TypeSymbol, String> getPossibleTypeSymbols(TypeSymbol typeDesc
                                 signature = "(" + newArrType.memberTypeDescriptor().signature() + ")[]";
                                 break;
                             default:
-                                signature = newArrType.signature();
+                                signature = entry.getValue() + "[]";
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java:301]: We have to consider the following case as well. 
extract_to_function

```ballerina

type TestRecordType1 int;

type TestRecordType2 string;

public function TestFunc(string[] names, int x) returns string[]|error {
    (TestRecordType1|TestRecordType2)[] rec = [];
    foreach var item in names {
        TestRecordType1[] result = [1];
        rec.push(...result);
    }
}
```


We must use the `newArrType` instead of `entry`. Let's use FunctionGenerator.processModuleIdsInText() method to get the type name.

**Review by malinthar — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java (hunk 1 above)
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java]: Done

**Review by malinthar — APPROVED** [review]
LGTM!

**Comment by malinthar** [comment]
Shall we add the same fix to 2201.3.x branch as well

**Review by IMS94 — APPROVED** [review]
