### PR TITLE
Fix NPE in lambda functions with check expressions

### LINKED ISSUE #42327: [Bug]: NPE in `BIRBasicBlockOptimizer`
### Description

Getting a null pointer exception when executing the code below.

### Steps to Reproduce

```
import ballerina/io;
import ballerina/http;
import ballerina/lang.runtime;

configurable string environmentId = ?;
configurable string token = ?;

type BuildsItem record {
    string buildId;
    string componentId;
    string mediationComponentId;
    string commitHash;
    string componentName;
    string mediationComponentVersionId;
    string apiId;
    string revisionId;
    string status;
    boolean mediationAttached;
    string startedAt;
    string finishedAt;
};

type BuildArray record {
    BuildsItem[] builds;
    int count;
    int 'limit;
};

public function main() returns error? {

    do {

        stream<string[], io:Error?> csvStream = check io:fileReadCsvAsStream("apiInformation-CRP.csv");

        // Iterates through the stream and prints the content.
        check csvStream.forEach(function(string[] apiInfo) {

            string apiName = apiInfo[0].trim();
            string apiVersion = apiInfo[1].trim();
            string componentID = apiInfo[2].trim();
            string versionID = apiInfo[3].trim();

            json invokeInitiateDeployment = check initiateDeployment(componentID, versionID, environmentId);

            io:println("Initiated interceptor app generation for API: ", apiName, " Version: ", apiVersion, "result: ", invokeInitiateDeployment);

            runtime:sleep(60.0);

            string buildID = check getLatestBuildID(componentID, versionID);

            io:println("Latest build ID for API: ", apiName, " Version: ", apiVersion, " is: ", buildID);

            runtime:sleep(5.0);

            json invokeDeployService = check deployService(componentID, versionID, environmentId, buildID);

            io:println("Initiated deployment for the interceptor app for API: ", apiName, " Version: ", apiVersion, "result: ", invokeDeployService);

            runtime:sleep(20.0);

        });

    } on fail error e {

        io:println("Error occurred while processing: ", e);
        runtime:sleep(5.0);

    }

}

function initiateDeployment(string componentID, string versionID, string environmentID) returns json|error {

    do {

        http:Client httpEp = check new (url = string `https://app.choreo.dev/proxy/deployer/v1/components/${componentID}/versions/${versionID}/initiate-deployment?environmentId=${environmentID}&accessMode=external`, config = {
            auth: {
                token: token
            }
        });

        http:Response returnResponse = check httpEp->/.post({});

        if returnResponse.statusCode == 200 {
            json response = check returnResponse.getJsonPayload();
            return response;
        } else {
            return error(string `Error occurred while deploying Reason ${returnResponse.statusCode}`);
        }

    } on fail error e {
        return error(string `Error occurred while deploying Reaseon = ${e.toString()}`);
    }

}

function deployService(string componentID, string versionID, string environmentID, string buildID) returns json|error {

    do {

        http:Client httpEp = check new (url = string `https://app.choreo.dev/proxy/deployer/v1/components/${componentID}/versions/${versionID}/deploy-service?buildId=${buildID}&environmentId=${environmentID}&accessMode=external`, config = {
            auth: {
                token: token
            }
        });

        http:Response returnResponse = check httpEp->post(message = {}, path = "");

        if returnResponse.statusCode == 200 {
            json response = check returnResponse.getJsonPayload();
            return response;
        } else {
            return error(string `Error occurred while deploying Reason ${returnResponse.statusCode}`);
        }

    } on fail error e {
        return error(string `Error occurred while deploying Reaseon = ${e.toString()}`);
    }

}

function getLatestBuildID(string componentID, string versionID) returns string|error {

    do {

        http:Client httpEp = check new (url = string `https://app.choreo.dev/proxy/deployer/v1/components/${componentID}/versions/${versionID}/builds?limit=1`, config = {
            auth: {
                token: token
            }
        });

        http:Response returnResponse = check httpEp->get("");

        if returnResponse.statusCode == 200 {
            json response = check returnResponse.getJsonPayload();

            BuildArray payloadRecord = check response.cloneWithType();

            string buildID = payloadRecord.builds[0].buildId;

            return buildID;
        } else {

            return error(string `Error occurred while getting build information ${returnResponse.statusCode}`);
        }

    } on fail error e {
        return error(string `Error occurred while deploying Reaseon = ${e.toString()}`);
    }

}
```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
$title
Fixes #42327 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 1]
```diff
@@ -3084,6 +3084,9 @@ public void visit(BLangLambdaFunction bLangLambdaFunction, AnalyzerData data) {
                                                                                   bLangLambdaFunction.function);
             }
         }
+
+        boolean failureHandled = data.failureHandled;
+        data.failureHandled = false;
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:3089]: Move this logic to the `visitFunction` function.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_error_return_type_mismatch_negative.bal [hunk 2]
```diff
@@ -84,3 +84,33 @@ function testCheckedExprWithNoErrorType3() {
     int|error i = error("Error");
     int _ = check i;
 }
+
+function testOnFailWithCheckInLambdaFunction() {
```
Comment (chiranSachintha) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_error_return_type_mismatch_negative.bal:88]: Add a test when the default value of a parameter equals an anonymous function.
```ballerina
function testOnFailWithCheckInLambdaFunction() {
    function _ = function() {
        do {
            function(function m = function () {
                string _ = check getVal("");
            }) k;

        } on fail {
        }

    };
}

function getVal(string str) returns string|error {
    return "";
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_error_return_type_mismatch_negative.bal [hunk 3]
```diff
@@ -84,3 +84,33 @@ function testCheckedExprWithNoErrorType3() {
...
+    return "";
+}
+
+function testOnFailWithCheckInWorkers() {
+    string[] s = [];
+    worker A {
+        s.forEach(function (string k) {
+            string _ = check getVal2();
+        });
+
```
Comment (chiranSachintha) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_error_return_type_mismatch_negative.bal:109]:
```suggestion

```

**Review by LakshanWeerasinghe — COMMENTED** [review]
This fix will only give a compile time error when the return type of the lambda function is incorrect. If we have the correct return type for the lambda function this will still throw an NPE. I think you have to do what you mentioned in this [comment](https://github.com/ballerina-platform/ballerina-lang/issues/42327#issuecomment-2179778621).
```ballerina
function getVal(string s) returns string|error {
    return "";
}
function getVal2(function s = function () {
    do {
        function k = function () returns error? {
            string aa = check getVal("");
        };
    } on fail {}
    }) returns string|error {
    return "";
}
```

**Comment by chiranSachintha** [comment]
> This fix will only give a compile time error when the return type of the lambda function is incorrect. If we have the correct return type for the lambda function this will still throw an NPE. I think you have to do what you mentioned in this [comment](https://github.com/ballerina-platform/ballerina-lang/issues/42327#issuecomment-2179778621).
> 
> ```ballerina
> function getVal(string s) returns string|error {
>     return "";
> }
> function getVal2(function s = function () {
>     do {
>         function k = function () returns error? {
>             string aa = check getVal("");
>         };
>     } on fail {}
>     }) returns string|error {
>     return "";
> }
> ```

This issue is a bit different. The problem lies in the way we desugared this program. During the desugaring phase, we used a global variable(`onFailClause`) to handle the onfail clause. When visiting the do-onfail, we identified the onfail clause and updated the global variable. However, we failed to reset it when visiting the lambda function.

According to the specification, this is incorrect. The spec says, `When execution of a statement fails, control flow transfers to the nearest lexically enclosing failure-handling statement`. Based on this, when we define a new scope with the lambda function, the global variables related to the onfail clause should be reset. We need to perform the desugaring of the lambda function accordingly.

To address this, I updated the visitor for the lambda function during the desugaring phase with the following logic. This will fix the issue. However, we need to check for any other global variables related to the onfail clause. If such variables exist, they should also be reset within the visitor for the function, as mentioned above.
```java
BLangOnFailClause onFailClause = this.onFailClause;
this.onFailClause = null;
bLangLambdaFunction.function = rewrite(bLangLambdaFunction.function, bLangLambdaFunction.capturedClosureEnv);
this.onFailClause = onFailClause;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 4]
```diff
@@ -8075,7 +8075,10 @@ public void visit(BLangTypeConversionExpr conversionExpr) {
 
     @Override
     public void visit(BLangLambdaFunction bLangLambdaFunction) {
+        BLangOnFailClause onFailClause = this.onFailClause;
+        this.onFailClause = null;
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:8079]: It would be better to move this logic to the visitor of the `blangfunction`. Also, @mindula, is this the only global variable we need to reset related to the `onfail` clause?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_error_return_type_mismatch_negative.bal [hunk 5]
```diff
@@ -84,3 +84,32 @@ function testCheckedExprWithNoErrorType3() {
     int|error i = error("Error");
     int _ = check i;
 }
+
+function testOnFailWithCheckInLambdaFunction() {
+    function _ = function() {
+        do {
+            function _ = function () {
```
Comment (chiranSachintha) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_error_return_type_mismatch_negative.bal:91]:
```suggestion
            function _ = function() {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_error_return_type_mismatch_negative.bal [hunk 6]
```diff
@@ -84,3 +84,32 @@ function testCheckedExprWithNoErrorType3() {
...
+}
+
+function getVal(string str) returns string|error {
+    return "";
+}
+
+function testOnFailWithCheckInWorkers() {
+    string[] s = [];
+    worker A {
+        s.forEach(function (string k) {
```
Comment (chiranSachintha) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_error_return_type_mismatch_negative.bal:106]:
```suggestion
        s.forEach(function(string k) {
```

**Comment by chiranSachintha** [comment]
@mindula We have used the `failureHandled` within the reachability analyzer. We need to implement a similar approach in the reachability analyzer as well. Please check it.

**Comment by mindula** [comment]
> @mindula We have used the `failureHandled` within the reachability analyzer. We need to implement a similar approach in the reachability analyzer as well. Please check it.

We're not currently showing the unreachable code error for the onfail clause and created an issue for it.
https://github.com/ballerina-platform/ballerina-lang/issues/43147

**Review by chiranSachintha — APPROVED** [review]

**Review by LakshanWeerasinghe — APPROVED** [review]
