### PR TITLE
Fix cloneWithType issues on ambiguity

### LINKED ISSUE #34082: `cloneWithType` should not panic in some cases with int subtypes
**Description:**

In the below cases `cloneWithType` should not panic because values 1, 2, 3 belong to all the int subtypes and hence `cloneWithType` does not require any conversion. So it should pass and should not panic.
```bal
public function main() {
    int[] x = [1, 2, 3];
    (int|decimal)[] e1 = checkpanic x.cloneWithType(); // does not panic, correct behaviour
    (byte|float)[] e2 = checkpanic x.cloneWithType(); // panics, but should not 
    (int:Unsigned8|float)[] e3 = checkpanic x.cloneWithType(); // panics, but should not 
    (int:Signed8|decimal)[] e4 = checkpanic x.cloneWithType(); // panics, but should not 
    (decimal|int:Signed16)[] e5 = checkpanic x.cloneWithType(); // panics, but should not 

    byte[] y = [1,2,3];
    (byte|float)[] p1 = checkpanic y.cloneWithType(); // does not panic, correct behaviour
    (int|float)[] p2 = checkpanic y.cloneWithType(); // panics, but should not 
    (int:Unsigned8|float)[] p3 = checkpanic y.cloneWithType(); // panics, but should not 

    int:Signed16[] z = [1, 2, 3];
    (int|float)[] q1 = checkpanic z.cloneWithType(); // does not panic, correct behaviour
    (byte|float)[] q2 = checkpanic z.cloneWithType(); // panics, but should not
    (int:Signed32|float)[] q3 = checkpanic z.cloneWithType(); // panics, but should not
}
```
Should also consider the other remaining cases of int subtypes not shown above.

**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Beta 5 - snapshot

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #34377: Incorrect error when `cloneWithType` conversion with a union target type is ambiguous
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public type Organization record {
    string id;
    string login;
    string name;
};

public type User record {
    string id;
    string login;
    string? name?;
};

public type Repository record {
    string orgName;
};

type Baz record {
    (Repository|User|Organization)[] x; // Works if `(Repository|User)[] x;`
};

public function main() {
    json j = {
        x: [
            {id: "0", name: "a", login: "c"},
            {id: "1", name: "b", login: "d"}
        ]
    };
    // Fails.
    Baz|error b = j.cloneWithType();
    io:println(b);
}
```

This fails because the members are convertible to both `User` and `Organization`. But the error is

```
error("{ballerina/lang.value}ConversionError",message="'map<json>' value cannot be converted to 'Baz': 
                missing required field 'x[0].orgName' of type 'string' in record 'Repository'
                missing required field 'x[1].orgName' of type 'string' in record 'Repository'")
```

**Affected Versions:**
slbeta6

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #34377

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 1]
```diff
@@ -260,41 +260,53 @@ static boolean isConvertibleToFloatingPointTypes(Object value) {
...
                     if (TypeChecker.getType(inputValue) == memType
                             || isIntegerSubtypeAndConvertible(inputValue, memType)) {
                         return Set.of(memType);
                     }
                     convertibleTypes.addAll(getConvertibleTypes(inputValue, memType, varName,
-                            isFromJson, unresolvedValues, errors));
+                            isFromJson, unresolvedValues, errors, allowAmbiguity));
+                }
+                if (!allowAmbiguity && (convertibleTypes.size() > 1) &&
+                        !convertibleTypes.contains(TypeChecker.getType(inputValue)) &&
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:287]: TypeChecker.getType(inputValue) is called multiple times in the   case TypeTags.UNION_TAG:. Shall we assign to variable and use without calling method multiple times

**Review by warunalakshitha — APPROVED** [review]
LGTM
