### PR TITLE
[Debugger] Fix additional fields not retrieved for open records

### LINKED ISSUE #36444: [Debugger] Additional fields of open records not shown in variable window
**Description:**
$subject. Refer screenshot below

Screenshot 2022-06-06 at 14 41 52

**Steps to reproduce:**

- Create an open record with additional fields
- Debug the ballerina program and track the variables on the variable window

### PR DESCRIPTION
**Pull request by SumayyaZiyad**
Fixes #36444 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [x] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BRecord.java [hunk 1]
```diff
@@ -55,34 +64,67 @@ public Map<String, Value> computeChildVariables() {
...
-                    .filter(field -> field.toString().contains(RECORD_FIELD_PATTERN_IDENTIFIER))
-                    .count();
-
-            return Long.valueOf(recordFieldCount).intValue();
+            Optional<Method> getKeysMethod = VariableUtils.getMethod(jvmValue,
+                                                                    METHOD_GET_KEYS,
+                                                                    GETKEYS_METHOD_SIGNATURE_PATTERN);
+            Value keyArray = ((ObjectReference) jvmValue).invokeMethod(context.getOwningThread().getThreadReference(),
+                    getKeysMethod.get(), Collections.emptyList(), ObjectReference.INVOKE_SINGLE_THREADED);
+            return ((ArrayReference) keyArray).length();
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BRecord.java:127]: Can we store this `keyArray` in the `loadedKeys` field, so that we can load the keys only if the `loadedKeys` is null inside the `getRecordFields()` method? We can avoid retrieving the same keyset in multiple times in that way.

Comment (NipunaRanasinghe) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BRecord.java:127]: or we can write a `loadAllKeys()` method and re-use it in both places

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BRecord.java [hunk 2]
```diff
@@ -55,34 +64,67 @@ public Map<String, Value> computeChildVariables() {
...
         } catch (Exception ignored) {
             return new LinkedHashMap<>();
         }
     }
 
+    private Map<Value, Value> getRecordFields() {
+        try {
+            Optional<Method> getKeysMethod = VariableUtils.getMethod(jvmValue,
+                                                                    METHOD_GET_KEYS,
+                                                                    GETKEYS_METHOD_SIGNATURE_PATTERN);
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BRecord.java:84]: Do we need to keep separate lines for each argument as we only have 3 args in here? :)

**Comment by NipunaRanasinghe** [comment]
@SumayyaZiyad Shall we also add a test case to cover the child variable visibility for open records with additional fields? 

IMO we can update the existing `org.ballerinalang.debugger.test.adapter.variables.VariableVisibilityTest#localVariableChildrenVisibilityTest()` test case

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BRecord.java [hunk 3]
```diff
@@ -55,34 +64,72 @@ public Map<String, Value> computeChildVariables() {
...
         } catch (Exception ignored) {
             return new LinkedHashMap<>();
         }
     }
 
+    private Map<Value, Value> getRecordFields() {
+        try {
+            if (loadedKeys == null) {
+                loadAllKeys();
+            }
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BRecord.java:84]: Shall we move this check inside to `loadAllKeys()` method instead? Otherwise we'll have to use the check whenever we call this method

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BRecord.java [hunk 4]
```diff
@@ -55,34 +64,72 @@ public Map<String, Value> computeChildVariables() {
...
-            long recordFieldCount = fieldValueMap.keySet()
-                    .stream()
-                    .filter(field -> field.toString().contains(RECORD_FIELD_PATTERN_IDENTIFIER))
-                    .count();
-
-            return Long.valueOf(recordFieldCount).intValue();
+            if (loadedKeys == null) {
+                loadAllKeys();
+            }
+            return loadedKeys.length();
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/variable/types/BRecord.java:132]: Here we may have to use an null check for `loadedKeys` because  the variable can be null if any exception is thrown while loading the keys (L106)

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM
