### PR TITLE
Fix NPE being thrown during cyclic import compilation

### LINKED ISSUE #37395: NPE during package compilation with cyclic imports
**Description:**
`ModuleContext.moduleCompState` becomes null with the following resolution diagnostics

Screenshot 2022-08-15 at 21 22 24

```
[Error - 9:24:45 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/chiran/Desktop/WSO2/nballerina/compiler/modules/front.syntax/ascii.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at io.ballerina.projects.PackageCompilation.getSemanticModel(PackageCompilation.java:144)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:75)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:59)
	at io.ballerina.projects.SyntaxNodeAnalysisTaskRunner.runTasks(SyntaxNodeAnalysisTaskRunner.java:51)
	at io.ballerina.projects.CodeAnalyzerManager.runSyntaxNodeAnalysisTasks(CodeAnalyzerManager.java:108)
	at io.ballerina.projects.CodeAnalyzerManager.runCodeAnalyzerTasks(CodeAnalyzerManager.java:61)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:144)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:272)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:241)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentSemanticModel(AbstractDocumentServiceContext.java:236)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.handleReferences(SemanticTokensVisitor.java:668)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.addSemanticToken(SemanticTokensVisitor.java:654)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:205)
	at io.ballerina.compiler.syntax.tree.ConstantDeclarationNode.accept(ConstantDeclarationNode.java:70)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:862)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.getSemanticTokens(SemanticTokensVisitor.java:107)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensUtils.getSemanticTokens(SemanticTokensUtils.java:64)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$semanticTokensFull$15(BallerinaTextDocumentService.java:624)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**
 Adding below import statement  to `compiler/modules/front.syntax/ascii.bal` file in `nballerina`
`import nballerina.front;`

nballerina_npe

**Affected Versions:**
2201.2.0-rc2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #37395

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java [hunk 1]
```diff
@@ -141,7 +141,8 @@ public SemanticModel getSemanticModel(ModuleId moduleId) {
         // If the states do not match, then this is a illegal state exception.
         if (moduleContext.compilationState() != ModuleCompilationState.COMPILED) {
             throw new IllegalStateException("Semantic model cannot be retrieved when the module is in " +
-                    "compilation state '" + moduleContext.compilationState().name() + "'. " +
+                    "compilation state'" + (moduleContext.compilationState() == null ? ""
+                    : (" " + moduleContext.compilationState().name())) + "'. " +
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java:145]: If `moduleContext.compilationState() == null` shall we just say

```
Semantic model cannot be retrieved.
```

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java:145]: But shouldn't we say that compilation is pending even though the state is not mentioned?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java:145]: If it is null doesn't it just say 

```
Semantic model cannot be retrieved when the module is in''. 
```

with the current change? :thinking:

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java]: It would say,
> Semantic model cannot be retrieved when the module is in compilation state. This is an internal error which will be fixed in a later release.

Just updated to remove `

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java]: Screenshot 2022-08-17 at 12 20 22

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java]: Isn't it incomplete though? The state which is usually specified within the quotes isn't specified here?

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java]: When we are doing a cyclic import, the state won't be set, but a resolution diagnostic will be added. Hence, its actually its compilation is pending. Here what I meant by `compilation state` is `compilation pending`. When the compilation state is set, the enum value will be contacted here. Wouldn't it make sense though?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java]: Yeah, but then shouldn't we say 

```
Semantic model cannot be retrieved when the module is in compilation state 'PENDING'.
```

Right now, it is like an incomplete sentence, right?

**Review by MaryamZi — APPROVED** [review]

**Review by hasithaa — APPROVED** [review]
