### PR TITLE
Fix issue in nil return

### LINKED ISSUE #10317: Ballerina prints last printed value when printing a function with no return value
**Description:**
Ballerina prints last printed value when printing a function with no return type

**Steps to reproduce:**
Create a .bal file.
```
function main(string ... args) {
    io:println("yay");
    io:println(test());
    io:println(test());
}

function test() {
    // io:println("In Test");
}
```
**Output**
yay
yay
yay

**Expected output**
yay

**Affected Versions:**
Ballerina 0.981.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Ubuntu 16.04

### PR DESCRIPTION
**Pull request by Shan1024**
## Purpose
Resolves #10317

### CODE REVIEW

File: bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CallableWorkerResponseContext.java [hunk 1]
```diff
@@ -107,8 +108,11 @@ protected WorkerExecutionContext onHalt(WorkerSignal signal) {
         }
         return runInCallerCtx;
     }
-    
+
     protected boolean isReturnable() {
+        if (this.responseTypes.length == 1 && this.responseTypes[0].getTag() == TypeTags.NULL_TAG) {
```
Comment (SupunS) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CallableWorkerResponseContext.java]: shall we add a comment on why we need this check?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/codegen/CodeGenerator.java [hunk 2]
```diff
@@ -752,25 +752,27 @@ public void visit(BLangStructLiteral structLiteral) {
...
             // call funcRefCPIndex 1 structRegIndex 0
-            Operand[] operands = new Operand[5];
+            Operand[] operands = new Operand[6];
             operands[0] = getOperand(funcRefCPIndex);
             operands[1] = getOperand(false);
             operands[2] = getOperand(1);
             operands[3] = structRegIndex;
-            operands[4] = getOperand(0);
+            operands[4] = getOperand(1);
+            operands[5] = getRegIndex(TypeTags.NIL);
```
Comment (SupunS) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/codegen/CodeGenerator.java]: here also, add a comment as to why a nil is added

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 3]
```diff
@@ -657,7 +657,13 @@ public void visit(BLangBreak breakNode) {
 
     @Override
     public void visit(BLangReturn returnNode) {
-        returnNode.expr = rewriteExpr(returnNode.expr);
+        if (returnNode.expr == null) {
```
Comment (SupunS) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: add comment
