### PR TITLE
Fix visibility of local variables which are inside block statements in debugger view

### LINKED ISSUE #28883: [Debugger] `let` expression inner variables are visible outside the expression
**Description:**
Currently `let` expression variables are visible in debug mode. Those variables should not be visible.

**Steps to reproduce:**
- Consider the code segment:
```
public function main() {
    string greeting = let string hello = "Hello ",
                          string ballerina = "Ballerina!"
                      in hello + ballerina;
}
```
- Run the above program in debbubg mode.
- We can see the `greeting`, `hello` and `ballerina` are visible in the local variables panel.
- Expected behaviour is only `greeting` variable should be visible. Other variables (`hello` and `ballerina`) should not be visible

image

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #28883

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java [hunk 1]
```diff
@@ -882,10 +889,17 @@ private void swapBasicBlockContent(BIRBasicBlock firstBB, BIRBasicBlock secondBB
...
      * @param secondBB The second BB of which terminator should end up in first BB
      */
-    private void swapBasicBlockTerminator(BIRBasicBlock firstBB, BIRBasicBlock secondBB) {
+    private void swapBasicBlockTerminator(BIRFunction func, BIRBasicBlock firstBB, BIRBasicBlock secondBB) {
         BIRTerminator firstBBTerminator = firstBB.terminator;
         firstBB.terminator = secondBB.terminator;
         secondBB.terminator = firstBBTerminator;
+        int firstBBIndex = func.basicBlocks.indexOf(firstBB);
+        if (firstBBTerminator.lhsOp != null) {
+            BIRBasicBlock endBB = firstBBTerminator.lhsOp.variableDcl.endBB;
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:898]: Shall we move this logic to a common method nd reuse? May be passing the `lhsOp` as parameter.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangBlockStmt.java [hunk 2]
```diff
@@ -39,6 +39,8 @@
 
     public FailureBreakMode failureBreakMode = FailureBreakMode.NOT_BREAKABLE;
 
+    public boolean isLetExprStmt = false;
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangBlockStmt.java:42]: Since it is a block statement, we can remove the `stmt` potfix in this variable and keep it as `isLetExpr` only.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java [hunk 3]
```diff
@@ -866,26 +866,51 @@ private BIRBasicBlock insertBasicBlock(BIRFunction func, int insertIndex) {
...
         firstBB.terminator = secondBB.terminator;
         secondBB.terminator = firstBBTerminator;
+        int firstBBIndex = func.basicBlocks.indexOf(firstBB);
+        if (firstBBTerminator.lhsOp != null) {
+            resetEndBasicBlock(func, firstBBTerminator.lhsOp, secondBB, firstBBIndex);
+        }
+    }
+
+    /**
+     * Reset endBBs of local variables after swap basic blocks content.
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:902]:
```suggestion
     * Reset endBBs of local variables after swapping basic blocks content.
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java [hunk 4]
```diff
@@ -110,7 +110,7 @@
     private static final String INVOCATION_INSTRUMENTATION_TYPE = "invocation";
     private static final String FUNC_BODY_INSTRUMENTATION_TYPE = "funcBody";
     private static final Location COMPILE_TIME_CONST_POS =
-            new BLangDiagnosticLocation(null, -1, -1, -1, -1);
+            new BLangDiagnosticLocation(null, -1, -1, -1, -1, 0, 0);
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:113]: Why we need this change?

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:113]: The later one is the new API and the previous one has been deprecated.

File: tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java [hunk 5]
```diff
@@ -151,6 +152,18 @@ public void controlFlowVariableVisibilityTest() throws BallerinaTestException {
         localVariables = debugTestRunner.fetchVariables(debugHitInfo.getRight(), DebugTestRunner.VariableScope.LOCAL);
         Assert.assertEquals(localVariables.size(), 47);
 
+        // visibility test of local variable defined inside `if` statement
+        debugTestRunner.resumeProgram(debugHitInfo.getRight(), DebugTestRunner.DebugResumeKind.NEXT_BREAKPOINT);
+        debugHitInfo = debugTestRunner.waitForDebugHit(10000);
+        localVariables = debugTestRunner.fetchVariables(debugHitInfo.getRight(), DebugTestRunner.VariableScope.LOCAL);
+        Assert.assertEquals(localVariables.size(), 47);
```
Comment (praveennadarajah) [inline tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java:159]: We already have variable visibility test inside `if` statement. Please refer [here](https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java#L121). Is there any specific reason to add again here?

Comment (gabilang) [reply tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/variables/VariableVisibilityTest.java:159]: Yes, it is for demonstrate the visibility of variable which is defined inside an if statement (or any other blocks or loops).

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Review by praveennadarajah — APPROVED** [review]
LGTM
