### PR TITLE
Fix configurable records that refers other variables as default values

### LINKED ISSUE #28966: Configurable record field that refers to another constant/configurable variable returns null value
**Description:**
As we initialize the configurable variables before the module initialization, there can be conflicts when there are record fields which contains default values. This can happen in both record and table type configurable variables. 

**Steps to reproduce:**

We need to consider the following scenarios 
1. Record fields with default values that are initialized at record init
We need to call the record init before the value creation of configurables.
```ballerina
type Person readonly & record {|
    readonly string name;
    string phone = "123456";
|};

configurable Person person = ?;
```
2. Record fields with default values from constants/ other global variables
ATM, the constants/global variables are initialized at the module init. This causes error when we initialize configurables before the module init.

```ballerina
final string number = "123456";

type Person readonly & record {|
    readonly string name;
    string phone = number;
|};

configurable Person person = ?;
```
3. Record fields with default values from other configurable variables.
The initializing order of configurable variables depends on the bal source. This also causes error if the referred configurable variable is not initialized earlier. 
```ballerina
final configurable string number = ?;

type Person readonly & record {|
    readonly string name;
    string phone = number;
|};

configurable Person person = ?;
```

**Affected Versions:**
alpha2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#28676

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #31161: Fix structured, array type configurable variables with defaultable readonly record fields
**Description:**
$subject

**Steps to reproduce:**
The following code produces error for configurables
```ballerina
type Person record {
    string name;
    int id;
    Address address;
};

type Address record {
    string city;
    readonly Country country = {};
};

type Country record {
    string name = "SL";
};

configurable table<Person> key(id) person = ?;
```
error :
```
error: defaultable readonly record field 'country' in configurable variable 'person.address' is not supported
        at testOrg/main:0.1.0(main.bal:32)
```
This is because we can't create a readonly record with mutable values, as the field is a readonly one.
 
Note that, this is handled for top level records, using the `cloneWithType()` with mutable types and `cloneReadonly()` afterwards. 
We may have a similar solution for depper level records like array, table of records. But this could cause a recursive type creation before cloning.

**Affected Versions:**
beta 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#28966 
#31127 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #31683: Improve configurable `ConfigProvider` to not to depend on TOML nodes
**Description:**
$subject

With the fixing of https://github.com/ballerina-platform/ballerina-lang/pull/31624 , the `ConfigProvider` class now returns a TOML value or a bal Value depending on the configurable variable type. 
This makes the `ConfigProvider` APIs inconsistent as it depends on the Provider type (TOML/CLI). 
Therefore, we need to separate out this dependency.
 
**Describe your solution(s)**
Have a common wrapper class that contains the configurable value to be used in `ConfigProvider` APIs. And move the provider type related implementations to this class.

**Related Issues (optional):**
#28966

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes #28966
Fixes #31161
Fixes #31683 

## Approach
- Dividing the `configInit` process into two as TOML validation and value creation. 
- Moving the value creation phase to `moduleInit` where the default values are accessible. 

## Samples
```ballerina
final string number = "123456";

type Person record {|
    string name;
    string phone = number;
|};

configurable Person person = ?;
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigMap.java [hunk 1]
```diff
@@ -28,11 +31,16 @@
  */
 public class ConfigMap {
     private static Map<VariableKey, Object> configurableMap = new HashMap<>();
+    private static ConfigValueCreator valueCreator = new ConfigValueCreator();
```
Comment (pramodya1994) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigMap.java:34]: Can we make this final?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java [hunk 2]
```diff
@@ -196,13 +193,13 @@ public boolean hasConfigs() {
         throw new ConfigException(CONFIG_CLI_TYPE_NOT_SUPPORTED, key.variable, effectiveType);
     }
 
-    public Optional<BMap<BString, Object>> getAsMapAndMark(Module module, VariableKey key) {
+    public Optional<Object> getAsMapAndMark(Module module, VariableKey key) {
```
Comment (pramodya1994) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java:196]: `module` is not used

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java [hunk 3]
```diff
@@ -0,0 +1,305 @@
...
+import java.util.ArrayList;
+import java.util.HashMap;
+import java.util.HashSet;
+import java.util.List;
+import java.util.Map;
+
+import static io.ballerina.runtime.internal.configurable.providers.toml.Utils.isPrimitiveType;
+
+/**
+ * Value creator for structured configurable values.
```
Comment (pramodya1994) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java:63]: Shall we add `@since 2.0.0`?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java (hunk 2 above)
Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/cli/CliProvider.java:196]: This is a overridden method from `ConfigProvider` 
https://github.com/ballerina-platform/ballerina-lang/blob/974b4d45dcc87dbd203a569248b0d1f59fc2eaae/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigProvider.java#L60

The `@Override` will be added in latest commit.

**Comment by warunalakshitha** [comment]
Let's schedule a code review for this PR since there are considerable lines and files changed.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java [hunk 4]
```diff
@@ -244,110 +234,106 @@ public boolean hasConfigs() {
     }
 
     @Override
-    public Optional<BArray> getAsArrayAndMark(Module module, VariableKey key) {
+    public Optional<Object> getAsArrayAndMark(Module module, VariableKey key) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java:237]: Api looks inconsistent where some methods we return bvalue and others toml nodes. We can have a generic wrapper class like ConfigValue and implement getValue method. So two impls can be done as CliConfigValue and TomlConfigValue. We can do that change separately as well.

Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/TomlProvider.java:237]: Created an issue #31683 for this.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java [hunk 5]
```diff
@@ -0,0 +1,307 @@
...
+                return getPrimitiveArray(tomlValue, arrayType);
+            case TypeTags.MAP_TAG:
+            case TypeTags.RECORD_TYPE_TAG:
+                return getMapValueArray(tomlValue, arrayType, elementType);
+            case TypeTags.ANYDATA_TAG:
+            case TypeTags.UNION_TAG:
+                return getUnionValueArray(tomlValue, arrayType, elementType);
+            default:
+                Type effectiveType = ((IntersectionType) elementType).getEffectiveType();
+                switch(effectiveType.getTag()) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java:133]: We can call getNonPrimitiveArray with effective type

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java [hunk 6]
```diff
@@ -0,0 +1,307 @@
...
+                if (effectiveType.getTag() == TypeTags.RECORD_TYPE_TAG) {
+                    return createRecordValue(tomlValue, type);
+                }
+                if (effectiveType.getTag() == TypeTags.TABLE_TAG) {
+                    return createTableValue(tomlValue, type);
+                }
+                return createValue(tomlValue, effectiveType);
+            case TypeTags.ANYDATA_TAG:
+            case TypeTags.UNION_TAG:
+                return createUnionValue(tomlValue, (BUnionType) type);
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java:102]: shall we handle intersection type as default case like getNonPrimitiveArray

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java [hunk 7]
```diff
@@ -0,0 +1,307 @@
...
+            case TypeTags.ARRAY_TAG:
+                return createArrayValue(tomlValue, (ArrayType) type);
+            case TypeTags.RECORD_TYPE_TAG:
+                return createRecordValue(tomlValue, type);
+            case TypeTags.MAP_TAG:
+                return createMapValue(tomlValue, (MapType) type);
+            case TypeTags.TABLE_TAG:
+                return createTableValue(tomlValue, type);
+            case TypeTags.INTERSECTION_TAG:
+                Type effectiveType = ((IntersectionType) type).getEffectiveType();
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/providers/toml/ConfigValueCreator.java:92]: Shall we call createStructuredValue again with effective type

**Review by warunalakshitha — APPROVED** [review]
LGTM
