### PR TITLE
Fix incorrect filler value for decimal

### LINKED ISSUE #29249: Incorrect filler value for decimal
The tracking issue for https://github.com/ballerina-platform/ballerina-spec/issues/778

### PR DESCRIPTION
**Pull request by lasinicl**
## Purpose
$title.

Fixes #29249

## Approach
Filler value for decimal should be **`+0d`**

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueTest.java [hunk 1]
```diff
@@ -268,6 +268,16 @@ public void testDecimalArrayValueLoading() {
...
     }
 
+    @Test(description = "Test decimal filler value")
+    public void testDecimalFillerValue() {
+        BValue[] returns = BRunUtil.invoke(result, "testDecimalFillerValue");
+        Assert.assertEquals(returns.length, 4);
+        Assert.assertEquals(returns[0].stringValue(), "[0.0]");
+        Assert.assertEquals(returns[1].stringValue(), "[0.0]");
+        Assert.assertTrue(((BBoolean) returns[2]).booleanValue());
+        Assert.assertTrue(((BBoolean) returns[3]).booleanValue());
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueTest.java:278]: We can test this in b7a itself, right? Shall we merge this also to https://github.com/ballerina-platform/ballerina-lang/tree/lang-sl-beta-breaking-changes?

Comment (lasinicl) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/decimaltype/BDecimalValueTest.java]: fixed

**Comment by NipunaRanasinghe** [comment]
Debug server related changes look good to me.
