### PR TITLE
Handle hash collisions in the put method in tables

### LINKED ISSUE #41723: [Bug]: The put method does not handle hash-collided keys
### Description

The current implementation of the `put` method in the `table` language library does not handle the case when there are two distinct keys with the same hash code. For instance, the output of the following code is `[{"k":"10"},{"k":5},{"k":0},{"k":-31},{"k":100.05},{"k":30}]` when it should be `[{"k":"10"},{"k":5},{"k":null},{"k":0},{"k":-31},{"k":100.05},{"k":30}]`.

```ballerina
import ballerina/io;

public function main() {
    table<record {readonly int|string|float? k;}> key(k) tbl1 = table [{k: "10"}];

    tbl1.put({k: 5});
    tbl1.put({k: ()});
    tbl1.put({k: -31});
    tbl1.put({k: 0});
    tbl1.put({k: 100.05});
    tbl1.put({k: 30});

    io:println(tbl1);
}
```

However, the `add` method of the `table` language library works as expected. For instance, the following code generates the expected result.
```ballerina
import ballerina/io;

public function main() {
    table<record {readonly int|string|float? k;}> key(k) tbl1 = table [{k: "10"}];

    tbl1.add({k: 5});
    tbl1.add({k: ()});
    tbl1.add({k: -31});
    tbl1.add({k: 0});
    tbl1.add({k: 100.05});
    tbl1.add({k: 30});

    io:println(tbl1);
}
```

### Steps to Reproduce

Run the following Ballerina code.

```ballerina
import ballerina/io;

public function main() {
    table<record {readonly int|string|float? k;}> key(k) tbl1 = table [{k: "10"}];

    tbl1.put({k: 5});
    tbl1.put({k: ()});
    tbl1.put({k: -31});
    tbl1.put({k: 0});
    tbl1.put({k: 100.05});
    tbl1.put({k: 30});

    io:println(tbl1);
}
```

### Affected Version(s)

Ballerina 2201.8.1 (Swan Lake Update 8)

### OS, DB, other environment details and versions

OS: macOS 14.0 23A344
Java: openjdk version "17.0.8" 2023-07-18

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by nipunayf**
## Purpose
The current implementation of the put API does not consider hash-collided keys. Thus, it behaves incorrectly when handling hash-collided keys.

Fixes #41723

## Approach
The PR modifies the put method to handle hash collision scenarios.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java [hunk 1]
```diff
@@ -632,15 +635,39 @@ public V putData(V data) {
...
+                    List<V> valueList = values.get(hash);
+                    valueList.remove(extEntry.getValue());
+                    valueList.add(data);
+                    return data;
+                }
+            }
+            List<Map.Entry<K, V>> extEntries = entries.get(hash);
+            extEntries.add(entry);
+            List<V> extValues = values.get(hash);
+            extValues.add(data);
```
Comment (SasinduDilshara) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java:667]:
```suggestion
            entries.get(hash).add(entry);
            values.get(hash).add(data);
```

File: langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal [hunk 2]
```diff
@@ -379,6 +379,46 @@ function testHashCollisionInQuery() {
...
+
+    tbl1.put({k: 5});
+    tbl1.put({k: ()});
+    tbl1.put({k: -31});
+    tbl1.put({k: 0});
+    tbl1.put({k: 100.05});
+    tbl1.put({k: 30});
+    table<record {|readonly int|string|float? k; anydata...;|}> tbl3 =
+        from var tid in tbl1
+            where tid["k"] == 0
```
Comment (prakanth97) [inline langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal:394]: According to the issue https://github.com/ballerina-platform/ballerina-lang/issues/41723 , seems like `()` case is missing right? Shall we check `()` instead of 0?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java [hunk 3]
```diff
@@ -632,15 +635,39 @@ public V putData(V data) {
...
+                if (TypeChecker.isEqual(key, extEntry.getKey())) {
+                    entryList.remove(extEntry);
+                    entryList.add(entry);
+                    List<V> valueList = values.get(hash);
+                    valueList.remove(extEntry.getValue());
+                    valueList.add(data);
+                    return data;
+                }
+            }
+            List<Map.Entry<K, V>> extEntries = entries.get(hash);
```
Comment (heshanpadmasiri) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java:664]: Is there a reason why we are getting entries with the same `hash` twice (`entryList` and `extEntries`), if the above loop modified `entryList` we shouldn't get here?

File: langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java [hunk 4]
```diff
@@ -123,8 +123,18 @@ public void testHashCollisionHandlingScenarios() {
     }
 
     @Test
-    public void testHashCollisionInQuery() {
-        BRunUtil.invoke(compileResult, "testHashCollisionInQuery");
+    public void testHashCollisionInQueryWithAdd() {
```
Comment (HindujaB) [inline langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibTableTest.java:126]: Shall we use a `DataProvider` for the tests? As we have the same pattern in all these tests.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java [hunk 5]
```diff
@@ -632,15 +635,37 @@ public V putData(V data) {
...
 
             ArrayList<V> newData = new ArrayList<>();
             newData.add(data);
 
-            Map.Entry<K, V> entry = new AbstractMap.SimpleEntry<>(key, data);
-            Long hash = TableUtils.hash(key, null);
             return putData((K) key, data, newData, entry, hash);
         }
 
+        private V handleHashCollisionInPut(K key, V data, Map.Entry<K, V> entry, Long hash) {
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java:651]:
```suggestion
        private V handleHashCollisionForPut(K key, V data, Map.Entry<K, V> entry, Long hash) {
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java [hunk 6]
```diff
@@ -632,13 +632,33 @@ public V putData(V data) {
...
+                    List<V> valueList = values.get(hash);
+                    valueList.remove(extEntry.getValue());
+                    valueList.add(data);
+                    return data;
+                }
+            }
+            entryList.add(entry);
+            values.get(hash).add(data);
+            return data;
         }
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java:662]:
```suggestion
        private V updateExistingEntry(K key, V data, Map.Entry<K, V> entry, Long hash) {
            updateIndexKeyMappings(hash, key, data);
            List<V> valueList = values.get(hash);
            List<Map.Entry<K, V>> entryList = entries.get(hash);
            for (Map.Entry<K, V> extEntry: entryList) {
                // Handle hash-collided entries
                if (TypeChecker.isEqual(key, extEntry.getKey())) {
                    entryList.remove(extEntry);
                    valueList.remove(extEntry.getValue());
                    break;
                }
            }
            entryList.add(entry);
            valueList.add(data);
            return data;
        }
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java [hunk 7]
```diff
@@ -616,10 +610,16 @@ public V putData(K key, V data) {
                         ErrorHelper.getErrorDetails(ErrorCodes.KEY_NOT_FOUND_IN_VALUE, key, data));
             }
 
-            return putData(key, data, newData, entry, hash);
+            if (entries.containsKey(hash)) {
+                return updateExistingEntry(key, data, entry, hash);
+            }
+
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java:616]: shall we remove this newline?

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Review by KavinduZoysa — APPROVED** [review]
