### PR TITLE
Fix langlib Error deviations

### LINKED ISSUE #33403: lang.error module does not have an object called "StackFrame"
The spec says the lang.error / error.bal has a object called `StackFrame` . 

```ballerina
# Type representing a stack frame.
# A call stack is represented as an array of stack frames.
# This type is also present in lang.runtime to avoid a dependency.
public type StackFrame readonly & object {
   # Returns a string representing this StackFrame.
   # This must not contain any newline characters.
   # + return - a string
   public function toString() returns string;
};

```
But in the current master of swanlake implementation, that object is missing. Instead it has a different class

```ballerina
# Represents an error call stack.
#
# + callStack - call stack
public class CallStack {
    public CallStackElement[] callStack = [];
}

```
This affects the following langlib function also. It has to return an array of `StackFrame`, not a `CallStack` object.

```
# Returns an array representing an error's stack trace.
#
# + e - the error value
# + return - an array representing the stack trace of the error value
# The first member of the array represents the top of the call stack.
public isolated function stackTrace(error e) returns CallStack = external;

```
Affect version: slbeta3

### PR DESCRIPTION
**Pull request by gimantha**
Fixes #33403, #33402

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -4289,6 +4289,28 @@ private BType getIntersection(IntersectionContext intersectionContext, BType lhs
...
+                    .map(t -> getIntersection(intersectionContext, t, env, finalType, visitedTypes))
+                    .filter(Objects::nonNull)
+                    .collect(Collectors.toList());
+            if (types.size() == 1) {
+                BType bType = types.get(0);
+                return ImmutableTypeCloner.getImmutableType(null, this, bType, env, env.enclPkg.packageID, null,
+                        symTable, anonymousModelHelper, names,
+                        new LinkedHashSet<>());
+            }
+        }
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4312]: This should be properly handled. Created an issue https://github.com/ballerina-platform/ballerina-lang/issues/33580

File: langlib/lang.error/src/main/ballerina/error.bal [hunk 2]
```diff
@@ -113,3 +110,28 @@ public isolated function toBalString(error e) returns string = @java:Method {
...
+#
+# + callStack - call stack
+class CallStack {
+    public CallStackElement[] callStack = [];
+}
+
+isolated function externGetStackTrace(error e) returns CallStack = @java:Method {
+    name: "stackTrace",
+    'class: "org.ballerinalang.langlib.error.StackTrace"
+} external;
```
Comment (gimantha) [inline langlib/lang.error/src/main/ballerina/error.bal:137]: Should this be moved to ```internal.bal``` as they are not part of the spec?

Comment (gimantha) [reply langlib/lang.error/src/main/ballerina/error.bal]: moved

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java [hunk 3]
```diff
@@ -137,7 +137,7 @@ public void customErrorDetailsTest() {
         BValue[] returns = BRunUtil.invoke(errorTestResult, "testCustomErrorDetails");
         Assert.assertEquals(returns[0].stringValue(), "trxErr {message:\"\", data:\"test\"}");
         Assert.assertEquals(((BError) returns[0]).getDetails().getType().getTag(), TypeTags.RECORD_TYPE_TAG);
-        Assert.assertEquals(((BError) returns[0]).getDetails().getType().getName(), "TrxErrorData & readonly");
+        Assert.assertEquals(((BError) returns[0]).getDetails().getType().getName(), "(TrxErrorData & readonly)");
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java:140]: Is this type name change expected?

Comment (gimantha) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/error/ErrorTest.java:140]: Yes. In previous implementation, the type of the record returned by `detail()` function is not readonly, but in runtime, when the record is created, typeName is generated. That typeName did not have enclosing parenthesis. But now detail() returns a `readonly & DetailType`. So in CodeGen when the recordType is created, the full record name is taken from the tsymbol's name. So it has enclosing parenthesis.

**Review by pcnfernando — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 4]
```diff
@@ -4289,6 +4289,28 @@ private BType getIntersection(IntersectionContext intersectionContext, BType lhs
...
             }
         }
+
+        // TODO: intersections with readonly types are not handled properly. Here, the logic works as follows.
+        // Say we have an intersection called A & readonly and we have another type called B. As per the current
+        // implementation, we cannot easily find the intersection between (A & readonly) and B. Instead, what we
+        // do here is, first find the intersection between A and B then re-create the immutable type out of it.
+
+        if (Symbols.isFlagOn(lhsType.flags, Flags.READONLY) && lhsType.tag == TypeTags.UNION &&
+                ((BUnionType) lhsType).getIntersectionType().isPresent()) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4299]: Shouldn't we check this for `type` also?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 5]
```diff
@@ -4436,7 +4460,7 @@ private boolean isAnydataOrJson(BType type) {
         return false;
     }
 
-    private BMapType getMapTypeForAnydataOrJson(BType type) {
+    private BMapType getMapTypeForAnydataOrJson(BType type, SymbolEnv env) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4463]: Why do we need this change?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java [hunk 6]
```diff
@@ -161,7 +161,7 @@ public static void markFieldsAsImmutable(BLangClassDefinition classDef, SymbolEn
         }
     }
 
-    private static BType getImmutableType(Location pos, Types types, BType type, SymbolEnv env,
+    public static BType getImmutableType(Location pos, Types types, BType type, SymbolEnv env,
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java:164]: Since some arguments passed to this with the changes in this PR are still null, shall we introduce a separate overloaded method instead of making this public?

File: langlib/lang.error/src/main/ballerina/error.bal [hunk 7]
```diff
@@ -54,40 +54,37 @@ public isolated function cause(error e) returns error? = @java:Method {
...
+# The first member of the array represents the top of the call stack.
+public isolated function stackTrace(error e) returns StackFrame[] {
+    StackFrame[] stackFrame = [];
+    int i = 0;
+    CallStack callStackElements = externGetStackTrace(e);
+    foreach var callStackElement in callStackElements.callStack {
+        stackFrame[i] = new java:StackFrameImpl(callStackElement.callableName,
+        callStackElement.fileName, callStackElement.lineNumber, callStackElement?.moduleName);
+        i += 1;
+    }
```
Comment (MaryamZi) [inline langlib/lang.error/src/main/ballerina/error.bal:85]:
```suggestion
    CallStack callStackElements = externGetStackTrace(e);
    foreach var callStackElement in callStackElements.callStack {
        stackFrame.push(new java:StackFrameImpl(callStackElement.callableName,
           callStackElement.fileName, callStackElement.lineNumber, callStackElement?.moduleName));
    }
```

File: langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/TypeParamTest.java [hunk 8]
```diff
@@ -50,7 +50,8 @@ public void testTypeParamNegative() {
         BAssertUtil.validateError(result, err++, "incompatible types: expected 'boolean', found 'string'", 48, 18);
         BAssertUtil.validateError(result, err++, "incompatible types: expected 'Foo', found 'string'", 50, 14);
         BAssertUtil.validateError(result, err++, "incompatible types: expected 'Bar', found 'string'", 51, 14);
-        BAssertUtil.validateError(result, err++, "incompatible types: expected 'boolean', found 'BarDetail'", 65, 18);
+        BAssertUtil.validateError(result, err++, "incompatible types: expected 'boolean', found " +
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/TypeParamTest.java:53]: The bal files error comment also needs to be updated.

https://github.com/ballerina-platform/ballerina-lang/blob/88de76ededb5b0ac6eacfb795fa4e8511d9d0bf8/langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal#L65

File: tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal [hunk 9]
```diff
@@ -412,10 +412,10 @@ function bar2(){
     bar();
 }
 
-function testStackOverFlow() returns [error:CallStackElement[], string]? {
+function testStackOverFlow() returns [error:StackFrame[], string]? {
     error? e = trap bar();
     if (e is error){
-        return [e.stackTrace().callStack, e.message()];
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal:418]: This is also a backward incompatible change, right?

File: tests/jballerina-unit-test/src/test/resources/test-src/error/stacktrace-project/main.bal [hunk 10]
```diff
@@ -17,24 +17,15 @@
...
-    string callableName = callStackElement["callableName"];
-    string? moduleName = callStackElement["moduleName"];
-    string fileName = callStackElement["fileName"];
-    int lineNumber = callStackElement["lineNumber"];
-
-    assertEquality(callableName, "getStackTrace");
-    assertEquality(moduleName, "test_org.stacktrace_project.stacktrace.0");
-    assertEquality(fileName, "stacktrace.bal");
-    assertEquality(lineNumber, 18);
+    error:StackFrame callStackElement = callStackElements[0];
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/error/stacktrace-project/main.bal:28]: Shouldn't we assert something here?

File: tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal (hunk 9 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal:418]: I mean not being able to access `.callStack`?

**Review by MaryamZi — APPROVED** [review]
We can fix what I've suggested separately.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 4 above)
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4299]: Also shouldn't we add new tests for this change?

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java [hunk 11]
```diff
@@ -136,6 +136,7 @@ void loadLangLib(CompilerContext compilerContext, PackageID langLib) {
         }
 
         if (langLib.equals(ERROR)) {
+            symbolTable.langArrayModuleSymbol = loadLangLibFromBala(ARRAY, compilerContext);
```
[the remark this answers is not in the document]
Comment (gimantha) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java:139]: Yeah. we need it, because in `detail()` function we use `foreach` statement and internally it has to call `array:iterator()`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 5 above)
Comment (gimantha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4463]: For certain cases, calling this method causes NPE, because `this.env` becomes null. I believe calling static functions leads to this NPE. Thats why i had to pass env as a parameter

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java [hunk 12]
```diff
@@ -254,7 +254,7 @@ public BString getErrorMessage() {
      */
     public Object getDetails() {
         if (details instanceof RefValue) {
-            return ((RefValue) details).copy(new HashMap<>());
+            return ((RefValue) details).frozenCopy(new HashMap<>());
```
[the remark this answers is not in the document]
Comment (gimantha) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java:257]: Will address with this issue separately: https://github.com/ballerina-platform/ballerina-lang/issues/33598

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 4 above)
Comment (gimantha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4299]: Will address with this issue separately: https://github.com/ballerina-platform/ballerina-lang/issues/33598

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java (hunk 6 above)
Comment (gimantha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java:164]: Will address with this issue separately: https://github.com/ballerina-platform/ballerina-lang/issues/33598

File: langlib/lang.error/src/main/ballerina/error.bal (hunk 7 above)
Comment (gimantha) [reply langlib/lang.error/src/main/ballerina/error.bal:85]: Will address with this issue separately: https://github.com/ballerina-platform/ballerina-lang/issues/33598

File: langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/TypeParamTest.java (hunk 8 above)
Comment (gimantha) [reply langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/TypeParamTest.java:53]: Will address with this issue separately: https://github.com/ballerina-platform/ballerina-lang/issues/33598

File: tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal (hunk 9 above)
Comment (gimantha) [reply tests/jballerina-unit-test/src/test/resources/test-src/error/error_test.bal:418]: yes. we no longer returns CallStack class

File: tests/jballerina-unit-test/src/test/resources/test-src/error/stacktrace-project/main.bal (hunk 10 above)
Comment (gimantha) [reply tests/jballerina-unit-test/src/test/resources/test-src/error/stacktrace-project/main.bal:28]: I should have removed that line. Thats no necessary. Will address with this issue separately: https://github.com/ballerina-platform/ballerina-lang/issues/33598

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 4 above)
Comment (gimantha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4299]: Will address with this issue separately: https://github.com/ballerina-platform/ballerina-lang/issues/33598
