### PR TITLE
Fix table with multiple keys with recursive type-reference type

### LINKED ISSUE #38689: [Bug]: Table multikey scenario fails for recursive type-reference
### Description

$subject

Due to a missed `getREferredType()` call.

### Steps to Reproduce

```ballerina
type Person record {
    readonly int id;
    readonly int depId;
    string name;
};

type PersonRef Person;
type PersonRef2 PersonRef;
type PersonTable table<PersonRef2> key(id, depId);

public function main() {
    PersonTable tab = table [
        {id: 101, depId: 99, name: "aaa"},
        {id: 102, depId: 11, name: "bbb"}
    ];
}
```
gives error: 
```
error: {ballerina/lang.array}IndexOutOfRange {"message":"tuple index out of range: index: 0, size: 0"}
        at hinduja.foo.0:main(main.bal:24)
```

### Affected Version(s)

`type-reference-support` branch.

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes #38689 

## Approach
Issue happens due to the wrong `getReferredType()` API usage.

## Samples
```ballerina
type Person record {
    readonly int id;
    readonly int depId;
    string name;
};

type PersonRef Person;
type PersonRef2 PersonRef;
type PersonTable table<PersonRef2> key(id, depId);

public function main() {
    PersonTable tab = table [
        {id: 101, depId: 99, name: "aaa"},
        {id: 102, depId: 11, name: "bbb"}
    ];
}
```
## CheckList 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/TypeReference.java [hunk 1]
```diff
@@ -316,4 +317,19 @@ public static boolean validateUnionTypeNarrowing(Object value, BTypedesc typedes
         return true;
     }
 
+    public static boolean validateTableKeys(BTable table) {
+        BError error = ErrorCreator.createError(StringUtils.fromString("Table keys does not provide type-reference " +
+                "type."));
+        if (table.getType().getTag() != TypeTags.TYPE_REFERENCED_TYPE_TAG) {
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/TypeReference.java:323]: Shall we have one if condition for throw error case

**Review by Nadeeshan96 — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
