### PR TITLE
Fix stackoverflow error in record field completions when record contains a required field of same type

### LINKED ISSUE #28866: [LS] Stackoverflow error when generating completions for record fields which includes a field of same record type
**Description:**
Consider the following record:
```ballerina
type MyRec record {
    string name;
    int age;
    string country;

    MyRec parent;
};
```
When trying to create a record using the above type:
```
function testRec() {
    MyRec rec = {
        <cursor>
    };
}
```
Completion generation fails with a stack overflow error:
```java
[Error - 2:02:53 PM] Operation 'text/completion' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/TestProject/test.bal', [15:10], error: 'java.lang.StackOverflowError'}
java.lang.StackOverflowError
	at java.base/java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1821)
	at java.base/java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getMandatoryRecordFields(CommonUtil.java:460)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:473)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getRecordFieldCompletionInsertText(CommonUtil.java:482)
```

**Steps to reproduce:**
See description

**Affected Versions:**
SLA2

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
When a record contains a required field of same type as the record,
CommonUtil throws a stackoverflow error. Fixed that by checking
if a field is of same type as the record.

Fixes #28866 

## Approach
See description

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by nadeeshaan — APPROVED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 1]
```diff
@@ -479,9 +479,13 @@ public static String getRecordFieldCompletionInsertText(RecordFieldSymbol bField
...
-                String fieldText = String.join("", Collections.nCopies(tabOffset + 1, "\t")) +
-                        getRecordFieldCompletionInsertText(field, tabOffset + 1);
-                requiredFieldInsertTexts.add(fieldText);
+                // If the field refers to the same type as bField, it results in a stack overflow error.
+                // Avoiding that using the following check
+                if (!bField.equals(field)) {
+                    String fieldText = String.join("", Collections.nCopies(tabOffset + 1, "\t")) +
+                            getRecordFieldCompletionInsertText(field, tabOffset + 1);
+                    requiredFieldInsertTexts.add(fieldText);
+                }
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:488]: I believe this check only saves from single level recursions. This is sufficient for the moment.

**Review by rasika — DISMISSED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 1 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:493]: Yes. As discussed via chat, I did update this method to accept a list of parents and a `tabOffset`

**Review by nadeeshaan — APPROVED** [review]
