### PR TITLE
[Master] Fix issues when there is union type in the select clause

### LINKED ISSUE #40012: [Bug]: Compilation fails when using query expressions to assign values for union typed record fields
### Description

Getting the following compilation error when I'am trying to assign values to union typed record field using query expression.
```
ambiguous type '[org/project:0.1.0:T3, org/project:0.1.0:T3]'
```

### Steps to Reproduce

Sample source:
```ballerina

type T1 record {
    T3[] t3s;
};

type T2 record {
    T3[]|T4[] t3OrT4;
};

type T3 record {
    string str;
};

type T4 record {
    boolean foo;
};

function transform(T1 t1) returns T2 => {
    t3OrT4: from var t3sItem in t1.t3s
        select {
           str: ""
        }
};
```

The error remains even I did a type cast within the select clause
```ballerina
function transform(T1 t1) returns T2 => {
    t3OrT4: from var t3sItem in t1.t3s
        select <T3>{
           str: ""
        }
};
```

### Affected Version(s)

Ballerina `2201.4.0`

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #40013: [Bug]: Compilation fails when using ternary expression within select clauses
### Description

Getting `incompatible types: expected '<TYPE_A>', found '<TYPE_B>'` error when I'am trying to use a ternary expression within a select clause.

### Steps to Reproduce

Sample source:
```ballerina
type T1 record {
    T3[] t3s;
};

type T2 record {
    T3[]|T4[] t3OrT4;
};

type T3 record {
    string str;
};

type T4 record {
    boolean foo;
};

function transform(T1 t1) returns T2 => {
    t3OrT4: from var t3sItem in t1.t3s
        select t3sItem.str == ""
        ? <T3>{
           str: ""
        } : <T4>{
            foo: false
        }
};
```

### Affected Version(s)

Ballerina `2201.4.0`

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by LakshanWeerasinghe**
## Purpose
$subject

Fixes #40013 
Fixes #40012

Related PRs #40271, #40726 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by SasinduDilshara** [comment]
Found the issue https://github.com/ballerina-platform/ballerina-lang/issues/40974, which is related to the focused task in this PR, but this issue not happen with this PR, it is already happen in update 6 as well.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java [hunk 1]
```diff
@@ -322,89 +323,150 @@ public BType resolveQueryType(SymbolEnv env, BLangExpression selectExp, BType ta
         }
     }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:325]: This crashes.

```ballerina
type Foo record {
    Baz[] a;
};

type Bar record {
    (Baz|Qux)[]|int[] b;
};

type Baz record {
    string c;
};

type Qux record {
    string c;
    int d?;
};

function transform(Foo foo) returns Bar => {
    b: from var _ in foo.a
        select {
           c: "str"
        }
};
```

```cmd
[2023-07-11 11:32:18,029] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2251)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:280)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral.accept(BLangRecordLiteral.java:81)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3493)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:3352)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:280)
        at org.wso2.ballerinalang.compiler.tree.clauses.BLangSelectClause.accept(BLangSelectClause.java:58)
        at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:215)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:349)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:3275)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:280)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangQueryExpr.accept(BLangQueryExpr.java:122)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3493)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2239)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:280)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral.accept(BLangRecordLiteral.java:81)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3493)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:549)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:280)
        at org.wso2.ballerinalang.compiler.tree.BLangExprFunctionBody.accept(BLangExprFunctionBody.java:42)
        at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:215)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:349)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visitFunction(CodeAnalyzer.java:513)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:456)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:280)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:81)
        at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:215)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:349)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeTopLevelNodes(CodeAnalyzer.java:338)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:326)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:280)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
        at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:215)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyze(CodeAnalyzer.java:314)
        at io.ballerina.projects.internal.CompilerPhaseRunner.codeAnalyze(CompilerPhaseRunner.java:196)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:119)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:435)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:383)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:208)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:192)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:242)
        at io.ballerina.projects.Package.getCompilation(Package.java:150)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:319)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:142)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:225)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:56)
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:325]: So does

```ballerina
type Foo record {
    Baz[] a;
};

type Bar record {
    (Baz|Qux)[]|Quux[] b;
};

type Baz record {
    string c;
};

type Qux record {
    string c;
    int d?;
};

type Quux record {
    string c;
    int d;
};

function transform(Foo foo) returns Bar => {
    b: from var _ in foo.a
        select {
           c: "str"
        }
};
```

**Comment by LakshanWeerasinghe** [comment]
> Found the issue #40974, which is related to the focused task in this PR, but this issue not happen with this PR, it is already happen in update 6 as well.

Since this has occurred previously will be addressed in another PR.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java (hunk 1 above)
Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:325]: Fixed and added tests.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java [hunk 2]
```diff
@@ -73,14 +73,11 @@ public void testNegativeQueryExprForXML() {
...
-        // issue - #40012
-        // validateError(negativeResult, index++,
-        //         "ambiguous type '[xml:Element, xml:Element]'", 88, 16);
-        // validateError(negativeResult, index++,
-        //         "incompatible types: expected 'xml:Text', found 'xml:Element'", 94, 16);
-        // validateError(negativeResult, index++,
-        //         "ambiguous type '[xml:Element, xml:Element]'", 99, 16);
-        Assert.assertEquals(negativeResult.getErrorCount(), index + 3);
+         validateError(negativeResult, index++,
+                 "ambiguous type '[xml:Element, xml]'", 88, 16);
```
[the remark this answers is not in the document]
Comment (LakshanWeerasinghe) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java:77]: No, these we to be uncommented after this fix.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java [hunk 3]
```diff
@@ -322,89 +323,150 @@ public BType resolveQueryType(SymbolEnv env, BLangExpression selectExp, BType ta
...
+        List<BType> possibleResolvedTypes = new ArrayList<>();
+        LinkedHashSet<BType> errorTypes = new LinkedHashSet<>();
+        for (BType expType : expTypes) {
+            BType selectType, resolvedType;
+            BType type = Types.getReferredType(expType);
+            switch (type.tag) {
+                case TypeTags.ARRAY:
+                    BType elementType = ((BArrayType) type).eType;
+                    selectType = checkExprSilent(selectExp, env, elementType, data);
+                    if (selectType.tag == TypeTags.SEMANTIC_ERROR) {
```
[the remark this answers is not in the document]
Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java]: Fixed.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java:77]: Sorry, I meant these lines can be merged.

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal [hunk 4]
```diff
@@ -915,6 +915,67 @@ function testQueryActionWithQueryExpression() {
...
+    int intakeYear;
+    float gpa;
+};
+
+function calGraduationYear(int year) returns int {
+    return year + 5;
+}
+
+function getBestStudents() returns any|error {
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal:959]: Unnecessary empty lines?

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal [hunk 5]
```diff
@@ -915,6 +915,67 @@ function testQueryActionWithQueryExpression() {
...
+        where student.gpa >= 2.0
+        let string degreeName = "Bachelor of Medicine", int graduationYear = calGraduationYear(student.intakeYear)
+        order by student.gpa descending
+        limit 2
+        select {name: student.firstName + " " + student.lastName, degree: degreeName, graduationYear: graduationYear};
+}
+
+function testQueryActionOrExprWithAnyOrErrResultType() {
+    assertTrue(getBestStudents() is record {|string name; string degree; int graduationYear;|}[]);
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal:976]:
```suggestion
```

Check wherever applicable.

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal [hunk 6]
```diff
@@ -915,6 +915,67 @@ function testQueryActionWithQueryExpression() {
...
+    Student s3 = {firstName: "Michelle", lastName: "Guthrie", intakeYear: 2002, gpa: 3.7};
+    Student s4 = {firstName: "George", lastName: "Fernando", intakeYear: 2005, gpa: 4.0};
+    Student[] studentList = [s1, s2, s3];
+
+    return from var student in studentList
+        where student.gpa >= 2.0
+        let string degreeName = "Bachelor of Medicine", int graduationYear = calGraduationYear(student.intakeYear)
+        order by student.gpa descending
+        limit 2
+        select {name: student.firstName + " " + student.lastName, degree: degreeName, graduationYear: graduationYear};
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal:971]:
```suggestion
        select {name: student.firstName + " " + student.lastName, degree: degreeName, graduationYear};
```

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal [hunk 7]
```diff
@@ -915,6 +915,67 @@ function testQueryActionWithQueryExpression() {
...
+
+type Student record {
+    string firstName;
+    string lastName;
+    int intakeYear;
+    float gpa;
+};
+
+function calGraduationYear(int year) returns int {
+    return year + 5;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr.bal:955]: Can be an expression-bodied function.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java [hunk 8]
```diff
@@ -322,89 +323,149 @@ public BType resolveQueryType(SymbolEnv env, BLangExpression selectExp, BType ta
         }
     }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:325]: For

```ballerina
type Foo record {
    Baz[] a;
};

type Bar record {
    boolean[]|float[] b;
};

type Baz record {
    string c;
};

type Quux record {
    string c;
    int d?;
};

type Qux record {
    string c;
    int d;
};

function transform(Foo foo) returns Bar => {
    b: from var _ in foo.a
        select {
           c: "str"
        }
};
```

there seems to be an extra error now.

```
a type compatible with mapping constructor expressions not found in type 'boolean'
```

Can we avoid this?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java [hunk 9]
```diff
@@ -322,89 +323,149 @@ public BType resolveQueryType(SymbolEnv env, BLangExpression selectExp, BType ta
...
+                case TypeTags.XML_ELEMENT:
+                case TypeTags.XML_PI:
+                case TypeTags.XML_TEXT:
+                    selectType = checkExprSilent(selectExp, env, type, data);
+                    if (selectType == symTable.semanticError) {
+                        errorTypes.add(type);
+                        continue;
+                    }
+
+                    if (Types.getReferredType(selectType).getKind() == type.getKind()
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:394]: Can't we use tag here also?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (LakshanWeerasinghe) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java:77]: Will do that.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java (hunk 8 above)
Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:325]: This error is there even before the fix. This error comes when we try to type check the select clause againsts the expected member type of the query result.

Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:325]: Will try to find a proper solution to remove this misleading diagnostic message.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java (hunk 9 above)
Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:394]: no.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java (hunk 8 above)
Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:325]: Since this error is expected logging is correct. The missing part was the error should be logged for all expected types. In this case `a type compatible with mapping constructor expressions not found in type 'float'` was missing. Added it in [#6a7b01](https://github.com/ballerina-platform/ballerina-lang/pull/40835/commits/6a7b01680f464c9fe8236d7d0f074d384c21e922).

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java (hunk 9 above)
Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:394]: In here we check whether the `selectType` is a subtype of the` type`. To do that we need to have compare it using kinds.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java [hunk 10]
```diff
@@ -141,6 +145,65 @@ public void testQueryActionOrExprSemanticsNegative() {
         validateError(negativeResult, i++, "action invocation as an expression not allowed here", 315, 23);
         validateError(negativeResult, i++, "incompatible types: expected 'int', found 'other'", 316, 21);
         validateError(negativeResult, i++, "action invocation as an expression not allowed here", 320, 50);
+        validateError(negativeResult, i++, "incompatible types: expected '(T3[]|T4[])', found '(T3|T4)[]'",
+                339, 13);
+        validateError(negativeResult, i++, "incompatible types: expected 'T3', " +
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java:150]: Why we should expect this error?
If we consider a normal ternary expression this is allowed
```ballerina
public function foo(string str) {
    T3|T4 _ = str == "" ? <T3>{
            str: ""
        } : <T4>{
            foo: false
        };
}

```

Comment (LakshanWeerasinghe) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryActionOrExprTest.java:150]: In a normal expression this is correct. But In here we log the error inside the select clause. In the L.H.S it is expecting a `T3[]|T4[]`.  So select clause type being a  `T3|T4` is incorrect. 

Initially we agreed to log a single error for the whole query. But when reviewing this PR  @MaryamZi pointed out a [  #case](https://github.com/ballerina-platform/ballerina-lang/pull/40835#discussion_r1259607967) where we needed type check the select clause as well.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java (hunk 9 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:394]: And you can use type tag for that? We usually use type tag instead of kind.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java (hunk 8 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:325]: What are all the errors for this sample now?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java [hunk 11]
```diff
@@ -322,89 +323,161 @@ public BType resolveQueryType(SymbolEnv env, BLangExpression selectExp, BType ta
...
+                possibleSelectTypes.add(selectType);
+                possibleResolvedTypes.add(resolvedType);
             }
-            if (resolvedType.tag == TypeTags.TABLE) {
-                queryExpr.isTable = true;
+        }
+        if (!possibleSelectTypes.isEmpty() && !possibleResolvedTypes.isEmpty()) {
+            selectTypes.addAll(possibleSelectTypes);
+            resolvedTypes.addAll(possibleResolvedTypes);
+        } else if (!errorTypes.isEmpty()) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:457]: Can reduce indentation with early returns.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java [hunk 12]
```diff
@@ -322,89 +323,161 @@ public BType resolveQueryType(SymbolEnv env, BLangExpression selectExp, BType ta
...
+            if (errorTypes.size() > 1) {
+                BType actualQueryType = silentTypeCheckExpr(queryExpr, symTable.noType, data);
+                if (actualQueryType != symTable.semanticError) {
+                    types.checkType(queryExpr, actualQueryType,
+                            BUnionType.create(null, new LinkedHashSet<>(expTypes)));
+                    errorTypes.forEach(expType -> {
+                        if (expType.tag == TypeTags.UNION) {
+                            checkExpr(selectExp, env, expType, data);
+                            selectExp.typeChecked = false;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:466]: Can't we clone and do this instead? Are we sure there's nothing else that needs to be reset?

To avoid such issues and side-effects we usually clone and type check (when checking for compatibility). Check mapping constructor type checking against unions.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java [hunk 13]
```diff
@@ -73,14 +73,9 @@ public void testNegativeQueryExprForXML() {
...
-        // issue - #40012
-        // validateError(negativeResult, index++,
-        //         "ambiguous type '[xml:Element, xml:Element]'", 88, 16);
-        // validateError(negativeResult, index++,
-        //         "incompatible types: expected 'xml:Text', found 'xml:Element'", 94, 16);
-        // validateError(negativeResult, index++,
-        //         "ambiguous type '[xml:Element, xml:Element]'", 99, 16);
-        Assert.assertEquals(negativeResult.getErrorCount(), index + 3);
+         validateError(negativeResult, index++, "ambiguous type '[xml:Element, xml]'", 88, 16);
+         validateError(negativeResult, index++, "ambiguous type '[xml:Element, xml]'", 99, 16);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/XMLQueryExpressionTest.java:77]: Wrong indentation.

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query_ambiguous_type_negative.bal [hunk 14]
```diff
@@ -0,0 +1,45 @@
...
+// under the License.
+
+type Book record {|
+    string title;
+    string author;
+|};
+
+function testQueryExprForAmbiguousTypes() returns error? {
+    string:Char chr = "a";
+    Book[] bookList = [];
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query_ambiguous_type_negative.bal:24]: I would move this closer to where it is used.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java (hunk 9 above)
Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:394]: In here we check whether the selectType is a subtype of the type. To do that we need to have compare it using kinds.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:394]: Is it for subtypes of string and xml? I would use org.wso2.ballerinalang.compiler.util.TypeTags#isXMLTypeTag, org.wso2.ballerinalang.compiler.util.TypeTags#isStringTypeTag.

Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:394]: `ambiguous type '(Baz|Qux)'` will be the only error.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java (hunk 12 above)
Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java]: Updated in [commit](https://github.com/ballerina-platform/ballerina-lang/pull/40835/commits/a587d82d3f1e1e27476f30f7d57d13928129df18).

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java (hunk 8 above)
Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:325]: `ambiguous type '(Baz|Qux)'` will be the only error.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java (hunk 9 above)
Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java]: Yes, this is the correct approach. Thanks for pointing. Updated in [#commit](https://github.com/ballerina-platform/ballerina-lang/pull/40835/commits/c16b3589fdb2c797c993858921bef3f08f49a3ba).

**Review by SasinduDilshara — DISMISSED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java [hunk 15]
```diff
@@ -322,89 +323,162 @@ public BType resolveQueryType(SymbolEnv env, BLangExpression selectExp, BType ta
...
+                BType actualQueryType = silentTypeCheckExpr(queryExpr, symTable.noType, data);
+                if (actualQueryType != symTable.semanticError) {
+                    types.checkType(queryExpr, actualQueryType, 
+                            BUnionType.create(null, new LinkedHashSet<>(expTypes)));
+                    errorTypes.forEach(expType -> {
+                        if (expType.tag == TypeTags.UNION) {
+                            checkExpr(nodeCloner.cloneNode(selectExp), env, expType, data);
+                        }
+                    });
+                    selectExp.typeChecked = true;
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java:470]: At this level selectExp hasn't been typeChecked isn't it? Is it correct to mark it as type-checked?

Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java]: Yes. There are case that can be where selectExpr not being type checked.

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr_semantic_negative.bal [hunk 16]
```diff
@@ -318,3 +318,139 @@ function testQueryActionOrExprWithActionsInJoinClause() {
...
+        select i % 2 == 0 ? <FooType>{foo: "Foo", id: i} : <BarType>{bar: "Bar", id: i};
+}
+
+function testQueryWithAmbiguousType2() {
+    string:Char[]|string _ = from var letter in ["a", "b", "c", "AA"] select letter == "B" ? letter : "L";
+}
+
+function transform(T1 t1) returns T2 => {
+    t3OrT4: from var t3sItem in t1.t3s
+        select t3sItem.str == ""
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query_action_or_expr_semantic_negative.bal:381]: This specific ternary expression is not correct. Just try running just that sample alone

**Review by pcnfernando — APPROVED** [review]
