### PR TITLE
Fix updating return type for func with check expr

### LINKED ISSUE #37153: Not providing union type when there is a check expression when function has an error return type
**Description:**
In below scenario `testReturnType` function has a `error?` return type when we apply change return type CA it gives `string` type as the return type. But it should provide the `string|error?` union type.

https://user-images.githubusercontent.com/46857198/181437521-29ff433c-0ee1-49aa-92ce-83e643254e1f.mov

**Suggested Labels (optional):**
Area/CodeAction, Team/LanguageServer

### PR DESCRIPTION
**Pull request by LakshanWeerasinghe**
## Purpose
$subject

Fixes #37153

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/FixReturnTypeCodeAction.java [hunk 1]
```diff
@@ -142,6 +147,10 @@ public List<CodeAction> getCodeActions(Diagnostic diagnostic,
                 }
             }
 
+            if (checkExprNodeFinder.containCheckExprNode()) {
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/FixReturnTypeCodeAction.java:150]: We can move the execution of the node visitor to the line before this line. No need to run it everytime (except in this else case)

**Review by IMS94 — CHANGES_REQUESTED** [review]

**Review by IMS94 — APPROVED** [review]
