### PR TITLE
Fix rest-binding-pattern with closed records

### LINKED ISSUE #36282: Runtime crashes when `rest-binding-pattern` is used with closed records
**Description:**
$title.

**Steps to reproduce:**
Ex. 1 - Works without an error
```ballerina
type PersonOpen record {
    int id;
    string fname;
    string lname;
    int age;
};

public function main() {
    PersonOpen person1 = {id: 123, fname: "Jhon", lname: "Doe", age: 23};
    PersonOpen {id: personId1, fname: personFname1, lname: personLname1, ...otherDetails1} = person1;
    io:println(otherDetails1);
}
```

Ex. 2 - Runtime crashed
```ballerina
import ballerina/io;

type PersonClosed record {|
    int id;
    string fname;
    string lname;
    int age;
|};

public function main() {
    PersonClosed person2 = {id: 123, fname: "Jhon", lname: "Doe", age: 23};
    PersonClosed {id: personId2, fname: personFname2, lname: personLname2, ...otherDetails2} = person2;
    io:println(otherDetails2);
}
```

Error
```
[2022-05-23 18:07:25,232] SEVERE {b7a.log.crash} - null 
java.lang.ExceptionInInitializerError
        at test3.main(test3.bal:81)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
        at io.ballerina.runtime.internal.types.BUnionType.setFlagsBasedOnMembers(BUnionType.java:251)
        at io.ballerina.runtime.internal.types.BUnionType.setMemberTypes(BUnionType.java:168)
        at constants.$_bunion_type_constants.$populate$unionType0(Unknown Source)
        at constants.$_bunion_type_constants.$union_type_init1(Unknown Source)
        at constants.$_bunion_type_constants.<clinit>(Unknown Source)
        ... 6 more
```
**Affected Versions:**
2201.1.0 (Swan Lake)

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #36282

When `getRestMatchPatternConstraintType` is called a record's rest field type type is passed as the `restVarSymbolMapType`. A record's rest field type can be `BNoType`. When creating a union type with `BNoType`, it can be neglected and in this fix it is done as such.

Newly added test, which is relevant for the fix is only `testRestBindingPatternWithRecords`.
Others are just the commented out tests for the issues which have been already fixed.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 1]
```diff
@@ -3053,7 +3054,8 @@ public BType getRestMatchPatternConstraintType(BRecordType recordType,
 
         if (!recordType.sealed) {
             BType restFieldType = recordType.restFieldType;
-            if (!this.types.isNeverTypeOrStructureTypeWithARequiredNeverMember(restFieldType)) {
+            if (!this.types.isNeverTypeOrStructureTypeWithARequiredNeverMember(restFieldType) &&
+                    (restFieldType.tag != TypeTags.NONE)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:3058]: IIRC, if the record type is closed (sealed) the rest field type is set to other (`TypeTags.NONE`), but an open record cannot have other as the rest type. What's the scenario here? Just wondering if the type isn't set correctly, in which case, this may not be the place to fix.

Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: Actually now due to the changes done in `createRecordTypeForRestField` and `setRestRecordFields` methods, we have correctly set the record type as sealed and hence we do not need this change here. Now, if the record is open, `BNoType` does not come as the rest type. So removed the change done here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 2]
```diff
@@ -3066,7 +3067,8 @@ public BType getRestMatchPatternConstraintType(BRecordType recordType,
         } else {
             restConstraintType = BUnionType.create(null, constraintTypes);
         }
-        return this.types.mergeTypes(restVarSymbolMapType, restConstraintType);
+        return (restVarSymbolMapType.tag == TypeTags.NONE) ?
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:3070]: Shall we remove the parenthesis here?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 3]
```diff
@@ -3081,7 +3083,11 @@ BRecordType createRecordTypeForRestField(Location pos, SymbolEnv env, BRecordTyp
             }
         }};
 
-        setRestRecordFields(pos, env, unMappedFields, variableList, restConstraint, recordVarType);
+        if (recordType.sealed && (restConstraint.tag == TypeTags.NONE)) {
```
[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:3086]: Discussed not to remove.

**Review by warunalakshitha — APPROVED** [review]
LGTM
