### PR TITLE
Align the implicit initial values of types with the spec

### LINKED ISSUE #13166: [Spec Deviation] Implicit initial value of tuple, map, record, table, typedesc, singleton, error, object and union not working as expected
**Description:**
```ballerina
type One 1;
type Union 0|1|2;

@test:Config {}
function testImplicitInitialValuesBroken() {
    // Implicit initial value of a tuple should be a tuple value with its member values taking their respective implicit initial values
    (int, boolean, string)[] tupleArray = [];
    tupleArray[1] = (200, true, "test string");
    test:assertEquals(tupleArray[0], (),
        msg = "expected implicit initial value of (int, boolean, string) to be (0, false, \"\")");

    // Implicit initial value of a map should be an empty map
    map<any>[] mapArray = [];
    mapArray[1] = { fieldOne: "valueOne" };
    map<any> expectedMap = {};
    test:assertEquals(mapArray[0], (), msg = "expected implicit initial value of map to be {}");

    // Implicit initial value of a record should be a record where each field has the implicit initial value for its type
    utils:FooRecord[] fooRecordArray = [];
    fooRecordArray[1] = { fooFieldOne: "valueOne" };
    test:assertEquals(fooRecordArray[0], (),
        msg = "expected implicit initial value of FooRecord to { fooFieldOne: \"\" }");

    // Implicit initial value of a table should be a table with no rows
    table<utils:BarRecord>[] tableArray = [];
    tableArray[1] = table{};
    test:assertEquals(tableArray[0], (), msg = "expected implicit initial value of string to be an empty string");

    // Implicit initial value of typedesc should be ()
    //typedesc[] typedescArray = [];
    //typedescArray[1] = int;
    //test:assertTrue(typedescArray[0], (), msg = "expected implicit initial value of typedesc to be ()");
   
    // Implicit initial value of a singleton type should be the single value
    One[] singletonArray = [];
    singletonArray[1] = 1;
    test:assertEquals(singletonArray[0], (),
        msg = "expected implicit initial value of a singleton to be the singleton value");

    error[] errorArray = []; // should fail at compile time

    // The rules for the implicit initial value of a union type are as follows:
    // 1. if () is in the value space of a union type, then the implicit initial value for the union type is ();
    // 2. otherwise if the value space only contains only values of a single basic type, and one of those values is the implicit initial value of that basic type, then the implicit initial value for the union is the implicit initial value of the basic type of its values (for example, the implicit initial value for 0|1 is 0)
    // 3. otherwise the union type does not have an implicit initial value.
    Union[] unionArray2 = [];
    unionArray2[1] = 2;
    test:assertEquals(unionArray2[0], (), msg = "expected implicit initial value of this union should be 0");
}
```
**Affected Versions:**
0.990.2

### PR DESCRIPTION
**Pull request by pubudu91**

### CODE REVIEW

File: bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BFiniteType.java [hunk 1]
```diff
@@ -35,18 +36,80 @@ public BFiniteType(String typeName, String pkgPath) {
...
+    @Override
+    public boolean equals(Object o) {
+        if (this == o) {
+            return true;
+        }
+        if (!(o instanceof BFiniteType)) {
+            return false;
+        }
+        BFiniteType that = (BFiniteType) o;
+        return valueSpace.containsAll(that.valueSpace) && that.valueSpace.containsAll(valueSpace);
```
Comment (SupunS) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BFiniteType.java]: checking the length, and containsAll() for one way would be faster?

File: bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BRecordType.java [hunk 2]
```diff
@@ -53,12 +54,28 @@ public TypeInfo getTypeInfo() {
...
+                    implicitInitValue.put(entry.getKey(), value);
+                });
+
+        return (V) implicitInitValue;
     }
 
     @Override
     public <V extends BValue> V getEmptyValue() {
-        return (V) new BMap<>(this);
+        BMap<String, BValue> implicitInitValue = new BMap<>(this);
```
Comment (SupunS) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BRecordType.java]: can replace with `return getZeroValue()`

File: bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BTypes.java [hunk 3]
```diff
@@ -111,4 +111,14 @@ public static BType fromString(String typeName) {
         }
         return getTypeFromName(typeName);
     }
+
+    public static boolean isImplicitInitValueNil(BType type) {
```
Comment (SupunS) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BTypes.java]: this is equivalent to checking nillable right? so can we call it `isNillable()` and make it generic?

File: bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BUnionType.java [hunk 4]
```diff
@@ -62,12 +62,20 @@ public boolean isNullable() {
 
     @Override
     public <V extends BValue> V getZeroValue() {
-        return null;
+        if (nullable || memberTypes.stream().anyMatch(BTypes::isImplicitInitValueNil)) {
```
Comment (SupunS) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BUnionType.java]: if we do as my above comment, this will be simply `if(BTypes.isNillable(this))`

File: bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BRecordType.java (hunk 2 above)
Comment (pubudu91) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BRecordType.java]: Can't do it for record type since we are calling `getEmptyValue()` recursively on the fields. But can do this for some of the others like `BTableType`

File: bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BTypes.java (hunk 3 above)
Comment (pubudu91) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/model/types/BTypes.java]: This is in the runtime. The `isNullable()` method is there only in the compile time `BType`. Will have to add it to the runtime `BType` as well
