### PR TITLE
Fix actions being allowed in expressions

### LINKED ISSUE #23037: Actions are allowed inside expressions
**Description:**

Below code parsers without any errors:

```ballerina
function foo() {
    x = a -> b() + c;
}
```

### PR DESCRIPTION
**Pull request by m36dot**
## Purpose
To allow only expression where expressions are expected and add a diagnostic if an action is provided

Fixes #23037

## Approach
Added a check in parseExpression to see if the parsed node is an action or expression and added a diagnostic if action is returned where it isn't supposed to be. Modified existing test asserts to go with the new change.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -4101,9 +4098,34 @@ private STNode parseExpression(OperatorPrecedence precedenceLevel, boolean isRhs
...
+                parseExpressionRhs(precedenceLevel, expr, isRhsExpr, allowActions, isInMatchGuard, isInConditionalExpr);
+        //braced actions are just paranthesis enclosing actions, no need to add a diagnostic there when we have added
+        //diagnostics to its children
+        if (!allowActions && isAction(actionOrExpression) && actionOrExpression.kind != SyntaxKind.BRACED_ACTION) {
+            actionOrExpression = attachErrorExpectedActionFoundDiagnostic(actionOrExpression);
+        }
+        return actionOrExpression;
     }
 
+    private boolean containsDiagnostics(STNode node, DiagnosticErrorCode diagnosticErrorCode) {
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:4111]: Why do we need this check?
Can the same error be logged in two places? If so, Would removing the error from the other place solve the problem?

Comment (m36dot) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:4111]: no I dont think that will work, because there are loops and multiple entry points for the parseExpression method.

Comment (m36dot) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:4111]: I ll try to get it working like that
