### PR TITLE
Change self keyword function invocation 

### LINKED ISSUE #17917: [Spec Deviation] Object __init() allows using self other than to access/modify a field when there are potentially uninitialized fields
**Description:**
$title.

According to the 2019r3 spec,
```
It is a compile error if a __init method:
- accesses a field at a point where it is potentially initialized, or
- at a point where there is any potentially uninitialized field
    - returns nil, or
    - uses the self variable other than to access or modify the value of a field.
```

The last point is not validated in the current implementation.

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Foo object {
    string s;

    public function __init(string s) {
        self.takeFooAndPrintS(self); // should fail since `self.s` is not yet initialized
        self.s = s;
    }

    function takeFooAndPrintS(Foo b) {
        io:println(b.s);
    }
};

public function main() {
    Foo f = new("hello");
}
```

This doesn't fail at runtime either atm.

The following is valid though.
```ballerina
    public function __init(string s) {
        self.s = s;
        self.takeFooAndPrintS(self); // valid since all fields are initialized
    }
```

**Affected Versions:**
1.0.0-beta-SNAPSHOT - 15th August build

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose
All fields in an object should be initialized before to do an invocation using self keyword.

Fixes #17917

## Approach
Check whether all fields are initialized before self invocation.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 1]
```diff
@@ -832,6 +832,9 @@ error.ambiguous.type=\
 error.uninitialized.variable=\
   variable ''{0}'' is not initialized
 
+error.uninitialized.fields=\
+  all fields must be initialized
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/resources/compiler.properties]: Shall we improve the error message? One improvement we can do here is, print all uninitialized fields.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java [hunk 2]
```diff
@@ -254,6 +254,7 @@
     INVALID_PATTERN_CLAUSES_IN_MATCH_STMT("invalid.pattern.clauses.in.match.stmt"),
     STATIC_MATCH_ONLY_SUPPORTS_ANYDATA("static.value.match.only.supports.anydata"),
     UNINITIALIZED_VARIABLE("uninitialized.variable"),
+    CONTAINS_UNINITIALIZED_FIELDS("uninitialized.fields"),
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java]: Shall we make this specific? like `uninitialized .object.fields`?

**Comment by hasithaa** [comment]
@KavinduZoysa Shall we add more test cases, covering branches, and loops in the init method.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 3]
```diff
@@ -604,6 +613,17 @@ public void visit(BLangInvocation invocationExpr) {
         }
     }
 
+    private boolean isValidSelf(BSymbol symbol) {
```
Comment (irshadnilam) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Shall we change the method signature to get the type (BObjectType) instead of symbol? 
Because symbol only used to getting the type here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 4]
```diff
@@ -604,6 +613,17 @@ public void visit(BLangInvocation invocationExpr) {
...
+
+        for (BField field : ((BObjectType) symbol.type).fields) {
+            InitStatus initStatus = this.uninitializedVars.get(field.symbol);
+            if (initStatus != null) {
+                return false;
+            }
```
Comment (irshadnilam) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Can we use `this.uninitializedVars.containsKey(field.symbol)` instead of this?

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 1 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: Improved the error message to print all uninitialized fields.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java (hunk 2 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java]: Changed.

**Comment by KavinduZoysa** [comment]
> @KavinduZoysa Shall we add more test cases, covering branches, and loops in the init method.

Added.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java (hunk 3 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Changed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java (hunk 4 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Changed.

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+public function testSelfKeywordInvocationWithLoopNegative() {
+    Person2 person = new("person2", "city");
+}
+
+type Person3 object {
+    string name;
+    string city;
+
+    public function __init(string name) {
+        if (name == "") {
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal]: Shall we include test-cases like this? Add nested if case scenarios as well. 

```
public function __init(string name) {
  if (name == "") {
    self.name = "tom";
  } else if (name == "tom") { 
    self.city = "London";
  } else {
    self.name = "tom";
    self.city = "London";
  }
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+    Person1 person = new("person1", 32);
+}
+
+type Person2 object {
+    string name;
+    string city;
+
+    public function __init(string name, string city) {
+        int i = 0;
+        while (i < 5) {
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal]: Try to combine scenarios with continue, break statements. Add foreach statement test cases.

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal (hunk 5 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal]: Changed.

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal (hunk 6 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal]: Add more tests to represent continue, break and foreach.

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal [hunk 7]
```diff
@@ -0,0 +1,120 @@
+type Person1 object {
+    string name;
+    int age;
+
+    public function __init(string name, int age) {
+        self.modify(self);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal]: Can we have two additional tests like
```ballerina
        self.modify("foo"); // `self` as the var on which the method is called 
        outerModify(self); // `self` as an argument to a module level function
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 8]
```diff
@@ -579,6 +581,17 @@ public void visit(BLangIndexBasedAccess indexAccessExpr) {
     @Override
     public void visit(BLangInvocation invocationExpr) {
         analyzeNode(invocationExpr.expr, env);
+        if (invocationExpr.expr != null && invocationExpr.expr.getKind() == NodeKind.SIMPLE_VARIABLE_REF
+                && ((BLangSimpleVarRef) invocationExpr.expr).getVariableName().value.equals(Names.SELF.value)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: We've only handled self as the var on which the invocation is do IINM? 

This wouldn't handle `self` as an argument to a function right? That also should be disallowed.

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 9]
```diff
@@ -833,6 +833,9 @@ error.ambiguous.type=\
 error.uninitialized.variable=\
   variable ''{0}'' is not initialized
 
+error.uninitialized.object.fields=\
+  fields ''{0}'' not initialized
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: Changed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java (hunk 8 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: +1, Changed

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal (hunk 7 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal]: Added.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 10]
```diff
@@ -610,6 +618,52 @@ public void visit(BLangInvocation invocationExpr) {
         }
     }
 
+    private boolean isFieldsInitializedForSelfKeyWordExpression(BLangInvocation invocationExpr) {
+        if (invocationExpr.expr != null && invocationExpr.expr.getKind() == NodeKind.SIMPLE_VARIABLE_REF
+                && ((BLangSimpleVarRef) invocationExpr.expr).getVariableName().value.equals(Names.SELF.value)) {
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Better if the literal (Names.SELF.value) is on the left side of the equals comparison to avoid possible NPEs.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 11]
```diff
@@ -610,6 +618,52 @@ public void visit(BLangInvocation invocationExpr) {
...
+                return false;
+            }
+        }
+        return true;
+    }
+
+    private boolean isFieldsInitializedForSelfKeyWordMethodInvocation(BLangInvocation invocationExpr) {
+
+        for (BLangExpression expr : invocationExpr.requiredArgs) {
+            if (expr.getKind() == NodeKind.SIMPLE_VARIABLE_REF && ((BLangSimpleVarRef) expr).getVariableName()
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Shall we extract this check to a method given that it is repeated?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 12]
```diff
@@ -610,6 +618,52 @@ public void visit(BLangInvocation invocationExpr) {
...
+    private StringBuilder getUninitializedFieldsForSelfKeyword(BObjectType objType) {
+        boolean isFirstUninitializedField = true;
+        StringBuilder uninitializedFields = new StringBuilder();
+        for (BField field : objType.fields) {
+            if (this.uninitializedVars.containsKey(field.symbol) && isFirstUninitializedField) {
+                uninitializedFields = new StringBuilder(field.symbol.getName().value);
+                isFirstUninitializedField = false;
+            } else if (this.uninitializedVars.containsKey(field.symbol)) {
+                uninitializedFields.append(", ").append(field.symbol.getName().value);
+            }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Shouldn't this be like
```java
if (this.uninitializedVars.containsKey(field.symbol)) {
    if (isFirstUninitializedField) {
        uninitializedFields = new StringBuilder(field.symbol.getName().value);
        isFirstUninitializedField = false;
    } else {
        uninitializedFields.append(", ").append(field.symbol.getName().value);
    }    
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal [hunk 13]
```diff
@@ -0,0 +1,161 @@
...
+        self.name = name;
+    }
+};
+
+function modify(Person7 person) {
+
+}
+public function testSelfKeywordInvocationWithModuleLevelFunctionInvocation() {
+    Person7 person = new("person");
+}
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal]: Missing a new line.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 14]
```diff
@@ -610,6 +618,52 @@ public void visit(BLangInvocation invocationExpr) {
         }
     }
 
+    private boolean isFieldsInitializedForSelfKeyWordExpression(BLangInvocation invocationExpr) {
+        if (invocationExpr.expr != null && invocationExpr.expr.getKind() == NodeKind.SIMPLE_VARIABLE_REF
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Done

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java (hunk 11 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Done

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java (hunk 12 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: +1

File: tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal (hunk 13 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/object/object_self_function_invocation_negative.bal]: Added

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 15]
```diff
@@ -610,6 +618,61 @@ public void visit(BLangInvocation invocationExpr) {
...
+        return expr.getKind() == NodeKind.SIMPLE_VARIABLE_REF &&
+                Names.SELF.value.equals(((BLangSimpleVarRef) expr).getVariableName().getValue());
+    }
+
+    private StringBuilder getUninitializedFieldsForSelfKeyword(BObjectType objType) {
+
+        boolean isFirstUninitializedField = true;
+        StringBuilder uninitializedFields = new StringBuilder();
+        for (BField field : objType.fields) {
+            if (this.uninitializedVars.containsKey(field.symbol)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Aren't we checking if the fields are initialized? The following should NOT fail.

```ballerina
import ballerina/io;

type Foo object {
    string s;

    public function __init(string s) {
        self.s = s;
        self.printS(); // no problem since self.s is initialized
    }

    function printS() {
        io:println(self.s);
    }
};
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 16]
```diff
@@ -585,6 +587,12 @@ public void visit(BLangIndexBasedAccess indexAccessExpr) {
     @Override
     public void visit(BLangInvocation invocationExpr) {
         analyzeNode(invocationExpr.expr, env);
+        if (!isFieldsInitializedForSelfKeyWordExpression(invocationExpr)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: The method names are a bit misleading IMO :) Shall we say

`isFieldsInitializedForSelfArgument`

and

`isFieldsInitializedForSelfInvocation`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 17]
```diff
@@ -610,6 +618,61 @@ public void visit(BLangInvocation invocationExpr) {
...
+            this.dlog.error(invocationExpr.pos, DiagnosticCode.CONTAINS_UNINITIALIZED_FIELDS,
+                    uninitializedFields.toString());
+            return false;
+        }
+        return true;
+    }
+
+    private boolean isFieldsInitializedForSelfKeyWordMethodInvocation(BLangInvocation invocationExpr) {
+
+        for (BLangExpression expr : invocationExpr.requiredArgs) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: This only handles required args and named args right? Rest args also need to be handled. 

Shall we add tests too?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java (hunk 15 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Since `this.uninitializedVars` only contains uninitialized variables do we need to check that?

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Since `this.uninitializedVars` only contains the uninitilized variables Do we need to check that?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Ah yeah, sorry misread this. This should be enough.

Shall we add a test though, for the same?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java (hunk 16 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Changed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java (hunk 17 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Added.

File: stdlib/grpc/src/main/resources/templates/skeleton/stub.mustache [hunk 18]
```diff
@@ -18,7 +18,12 @@ public type {{serviceName}}{{#equals stubType "blocking"}}Blocking{{/equals}}Cli
 {{#blockingFunctions}}
     public remote function {{methodName}}({{#if inputType}}{{inputType}} req, {{/if}}grpc:Headers? headers = ()) returns ({{#if outputType}}[{{outputType}}, grpc:Headers]{{else}}grpc:Headers{{/if}}|grpc:Error) {
         {{#unless inputType}}Empty req = {};{{/unless}}
-        var payload = check self.grpcClient->blockingExecute("{{methodId}}", req, headers);
+        if !(self.grpcClient is grpc:Client) {
+            error err = error("UninitializedFieldsErrorType", message = "Field(s) are not initialized");
```
Comment (MaryamZi) [inline stdlib/grpc/src/main/resources/templates/skeleton/stub.mustache]: This does not seem consistent with the normal error reasons we have, can we use something like `UninitializedClientError`

Comment (MaryamZi) [reply stdlib/grpc/src/main/resources/templates/skeleton/stub.mustache]: However, I believe the change here should be to the init method itself. 

@daneshk can't we change the init method as 
```ballerina
        checkpanic c.initStub(self, "{{stubType}}", ROOT_DESCRIPTOR, getDescriptorMap());
        self.grpcClient = c;
```

Or at least move `self.grpcClient = c;` out of the else to make it always initialized?

File: stdlib/socket/src/main/ballerina/src/socket/udp_client_socket.bal [hunk 19]
```diff
@@ -35,6 +35,7 @@ public type UdpClient client object {
     # + config - Configure additional details like read timeout etc.
     public function __init(Address? localAddress = (), UdpClientConfig? config = ()) {
         UdpClientConfig configuration = config ?: {};
+        self.localAddress = localAddress;
```
Comment (MaryamZi) [inline stdlib/socket/src/main/ballerina/src/socket/udp_client_socket.bal]: L43-L45 seems redundant after this?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 20]
```diff
@@ -610,6 +622,61 @@ public void visit(BLangInvocation invocationExpr) {
...
+                    uninitializedFields.toString());
+            return false;
+        }
+        return true;
+    }
+
+    private boolean isFieldsInitializedForSelfInvocation(List<BLangExpression> argExpressions, DiagnosticPos pos) {
+
+        for (BLangExpression expr : argExpressions) {
+            if (isSelfKeyWordExpr(expr)) {
```
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: We can do this separately.

File: stdlib/grpc/src/main/resources/templates/skeleton/stub.mustache (hunk 18 above)
Comment (daneshk) [reply stdlib/grpc/src/main/resources/templates/skeleton/stub.mustache]: yes, we can
