### PR TITLE
Stop sending diagnostics when LS in lightweight mode

### LINKED ISSUE #38431: [Bug]: VSCode shows errors for client declaration and usage even after module generation
### Description

$title, consistently reproducible when the Ballerina Compiler Toolkit is installed.

However suggestions work and the code action to generate the module is no longer shown. Which could mean they are based on different compilations. 

### Steps to Reproduce

```yaml
openapi: 3.0.0
info:
  title: Two
  description: Two
  version: 0.1.0

servers:
  - url: http://sampletwo.com

paths:
  /employees:
    get:
      summary: Returns a list of employees.
      responses:
        '200':
          description: A JSON array of employees names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

```ballerina
client "employees.yaml" as employees;

public function main() {
    employees:client c;
}
```

### Affected Version(s)

2201.3.0-RC1

### Related area

-> Editor

### PR DESCRIPTION
**Pull request by LakshanWeerasinghe**
## Purpose
Currently we are not checking weather the LS is in lightweight mode when we are publishing diagnostics. Ballerina compiler toolkit connects to a lightweight language server and it will publish diagnostic messages. Because of this when a user have both plugin and compiler toolkit it shows same diagnostic twice.  

With this PR this incorrect behavior is go away.

Fixes #38431

## Samples
-  how it looks like before the fix.
Screenshot 2022-11-16 at 12 12 16

- how it looks like after the fix.
Screenshot 2022-11-16 at 12 10 36

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java [hunk 1]
```diff
@@ -115,6 +117,9 @@ public synchronized void schedulePublishDiagnostics(ExtendedLanguageClient clien
      * @param context LS context
      */
     public synchronized void compileAndSendDiagnostics(ExtendedLanguageClient client, DocumentServiceContext context) {
+        if (context.languageServercontext().get(LanguageServerLightWeightMode.class) != null) {
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java:120]: Let's add this check to the PublishDiagnoticSubscriber instead https://github.com/ballerina-platform/ballerina-lang/blob/8ccdc067648a303b81e43aa4c67d9a2e96bcfcae/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/eventsync/subscribers/PublishDiagnosticSubscriber.java#L45

**Review by malinthar — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/LanguageServerLightWeightMode.java [hunk 2]
```diff
@@ -0,0 +1,10 @@
+package org.ballerinalang.langserver.commons;
+
+/**
+ * Interface to represent the Language Server is in LightWeightMode.
+ *
+ * @since 2201.4.0
+ */
+public class LanguageServerLightWeightMode {
```
Comment (IMS94) [inline language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/LanguageServerLightWeightMode.java:8]: We don't need a new class like this. The `InitializeParams` already has a parameter called `enableLightWeightMode`. See `org.ballerinalang.langserver.BallerinaLanguageServer#isLightWeightMode()` method for an example usage. However, we have a better approach.

At `BallerinaLanguageServer:88`, we create an instance of `LSClientCapabilitiesImpl` containing an instance of `InitializationOptions`. We should add the light weight mode boolean as a new method to that interface. And in the other places, use that to determine if we are in lightweight mode.

**Review by IMS94 — CHANGES_REQUESTED** [review]

**Review by malinthar — APPROVED** [review]
LGTM!

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java [hunk 3]
```diff
@@ -89,9 +90,10 @@ public class BallerinaLanguageServer extends AbstractExtendedLanguageServer
     private ExtendedLanguageClient client = null;
     private final TextDocumentService textService;
     private final WorkspaceService workspaceService;
+
+    private LSClientCapabilities capabilities;
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java:94]: This is incorrect. We hold everything inside the `LanguageServerContext`. No need to keep anything at instance level unless necessary. We can simply to ` LSClientCapabilities clientCapabilities = serverContext.get(LSClientCapabilities.class);` to get the client capabilities from LS context.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java [hunk 4]
```diff
@@ -112,8 +114,15 @@ public CompletableFuture<InitializeResult> initialize(InitializeParams params) {
         final InitializeResult res = new InitializeResult(new ServerCapabilities());
         res.getCapabilities().setTextDocumentSync(TextDocumentSyncKind.Full);
 
+        Map initializationOptions = null;
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java:117]: We can move the following lines before this line:
```java
        TextDocumentClientCapabilities textDocClientCapabilities = params.getCapabilities().getTextDocument();
        WorkspaceClientCapabilities workspaceClientCapabilities = params.getCapabilities().getWorkspace();
        LSClientCapabilities capabilities = new LSClientCapabilitiesImpl(textDocClientCapabilities,
                workspaceClientCapabilities,
                experimentalClientCapabilities,
                initializationOptions);
        this.serverContext.put(LSClientCapabilities.class, capabilities);
```

And then check 
```
    if (capabilities.getInitializationOptions().isLisghtWeightMode()) {
            return CompletableFuture.supplyAsync(() -> res);
    }
```
And we can remove the `isLightWeightMode()` method as well

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSClientCapabilitiesImpl.java [hunk 5]
```diff
@@ -194,11 +201,14 @@ private void setShowTextDocumentEnabled(boolean showTextDocumentEnabled) {
      * Represents the initialization options the LS client will be sending.
      */
     public static class InitializationOptionsImpl implements InitializationOptions {
+
         private boolean supportBalaScheme = false;
         private boolean enableSemanticTokens = false;
         private boolean supportRenamePopup = false;
         private boolean supportQuickPick = false;
-        
+
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSClientCapabilitiesImpl.java:209]: Remove this additional new line to match the way other fields are defined.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/eventsync/subscribers/PublishDiagnosticSubscriber.java [hunk 6]
```diff
@@ -32,18 +33,22 @@
...
     }
-    
+
     @Override
     public void onEvent(ExtendedLanguageClient client, DocumentServiceContext context,
                         LanguageServerContext languageServerContext) {
-        DiagnosticsHelper diagnosticsHelper = DiagnosticsHelper.getInstance(languageServerContext);
-        diagnosticsHelper.compileAndSendDiagnostics(client, context);
+        LSClientCapabilities lsClientCapabilities = context.languageServercontext().get(LSClientCapabilities.class);
+        if (!lsClientCapabilities.getInitializationOptions().isEnableLSLightWeightMode()) {
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/eventsync/subscribers/PublishDiagnosticSubscriber.java:48]: There's another place where we publish diagnostics, `BallerinaWorkspaceService.didChangeWatchedFiles()` method. Need to add this check there as well.

**Review by IMS94 — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java [hunk 7]
```diff
@@ -419,8 +422,8 @@ private void startListeningFileChanges() {
     private Boolean isLightWeightMode(InitializeParams params) {
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java:422]: We can remove this method now

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java (hunk 3 above)
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java:94]: Can you remove this?

**Review by IMS94 — CHANGES_REQUESTED** [review]

**Review by IMS94 — DISMISSED** [review]

**Review by IMS94 — APPROVED** [review]
