### PR TITLE
Fix http service snippet

### LINKED ISSUE #28204: Improve HTTP service snippet
See the following example: 

stats-1611579249083

Problem cases : 
- Import is already existing, Code action adds another. 
- Instead of adding `methodname`, add a valid HTTP verb. i.e. `get` etc.

### PR DESCRIPTION
**Pull request by nadeeshaan**
1. Modify the http service snippet
2. Add context awareness to modify the default import alias of a snippet

Fixes #28204

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by IMS94 — APPROVED** [review]
LGTM!

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java [hunk 1]
```diff
@@ -1040,7 +1040,7 @@ public static SnippetBlock getReturnStatementSnippet() {
     public static SnippetBlock getServiceDefSnippet() {
         ImmutablePair<String, String> httpImport = new ImmutablePair<>("ballerina", "http");
         String snippet = "service /${1} on new http:Listener(8080) {"
-                + CommonUtil.LINE_SEPARATOR + "\tresource function ${2:methodName} ${3:resourceName}"
+                + CommonUtil.LINE_SEPARATOR + "\tresource function ${2:get} ${3:getResource}"
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java:1043]: @nadeeshaan shall we move `getResource` into `resource` since repeating `get` looks bit weird. wdyt?

`resource function get getResource(...)` vs. `resource function get resource(...)`

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetBlock.java [hunk 2]
```diff
@@ -71,30 +72,33 @@ public SnippetBlock(String label, String snippet, String detail, Kind kind,
...
-                                && importNode.orgName().get().orgName().text().equals(pair.getLeft())
-                                && importNode.prefix().isPresent()
-                                && importNode.prefix().get().prefix().text().equals(pair.getRight()));
-                if (!pkgAlreadyImported) {
+                Optional<ImportDeclarationNode> matchedImport = CommonUtil.matchingImportedModule(ctx, pair.getLeft(),
+                        pair.getRight());
+                if (matchedImport.isEmpty()) {
                     importTextEdits.addAll(CommonUtil.getAutoImportTextEdits(pair.getLeft(), pair.getRight(), ctx));
                 }
+                if (matchedImport.isPresent() && matchedImport.get().prefix().isPresent()) {
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetBlock.java:86]: This can be moved to `else if` of the same if ladder.. Then we can remove redundant `isPresent()` check.

eg. `} else if (matchedImport.get().prefix().isPresent()){...}`

**Review by rasika — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java:1043]: We can't use `resource` because it is a reserved keyword in the language

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetBlock.java (hunk 2 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetBlock.java:86]: Fixed

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java (hunk 1 above)
Comment (rasika) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/SnippetGenerator.java:1043]: Okay then shall we go forward with `resource function get httpResource(http:Caller caller, http:Request req)` ?

**Review by rasika — APPROVED** [review]
