### PR TITLE
Fixes issue in handling error for streams with query expressions

### LINKED ISSUE #21757: [Query Expressions] Issue in handling error for streams
**Description:**
As per the query specification, when querying a stream there is a guideline (below) to handle the errors. 

If i is a stream
call i.next() resulting in a value r;
if r is an error, then complete execution of the from-clause early with error r;

But, there is a spec violation with the current query implementation for streams. As per the current implementation, `from-clause` gets de-sugared to a foreach statement. As per the recent discussion, it seems foreach statements will not work for iterators which could through error (i.e, error). Then, we need to improve/change the de-sugar implementation with `foreach` function of stream lang-lib.

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #21757

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 1]
```diff
@@ -96,78 +106,123 @@ public static QueryDesugar getInstance(CompilerContext context) {
...
-        //      x[x.length()] = {
+        //      $tempDataArray$[$tempDataArray$.length()] = {
         //         firstName: person.firstName,
         //         lastName: person.lastName
         //      };
-
-        BLangInvocation lengthInvocation = createLengthInvocation(selectClause.pos, outputArrayVariable.symbol);
-        lengthInvocation.expr = outputVarRef;
-        BLangIndexBasedAccess indexAccessExpr = ASTBuilderUtil.createIndexAccessExpr(outputVarRef, lengthInvocation);
+        BLangInvocation lengthInvocation = createLengthInvocation(selectClause.pos, tempArrayVariable.symbol);
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java]: Shall we replace this with push()?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -2824,10 +2826,32 @@ public void visit(BLangQueryExpr queryExpr) {
...
+            expSelectType = nilRemovedSet.size() == 1 ? nilRemovedSet.iterator().next() :
+                    BUnionType.create(null, nilRemovedSet);
+            if (expSelectType.tag == TypeTags.ARRAY) {
+                expSelectType = ((BArrayType) expSelectType).eType;
+            }
+        }
         BType selectType = checkExpr(selectClause.expression, whereEnv, expSelectType);
-        resultType = selectType == symTable.semanticError ? selectType : new BArrayType(selectType);
+        BType actualType = new BArrayType(selectType);
+        if ((collectionNode instanceof BLangSimpleVarRef) &&
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: check the tag instead of using instance of

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -2824,10 +2826,32 @@ public void visit(BLangQueryExpr queryExpr) {
...
+                (((BLangSimpleVarRef) collectionNode).type instanceof BStreamType)) {
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: check the type tag instead of instanceof

File: tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal [hunk 4]
```diff
@@ -151,16 +174,16 @@ function testFilteringNullElements() returns Person[] {
     return outputPersonList;
 }
 
-function testMapWithArity () returns string[] {
-    map<any> m = {a:"1A", b:"2B", c:"3C", d:"4D"};
+function testMapWithArity() returns string[] {
+    map<any> m = {a: "1A", b: "2B", c: "3C", d: "4D"};
     string[] val = from var v in m
                    where <string> v == "1A"
```
Comment (gimantha) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal]: What will happen if we remove the cast <string> ?

File: tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-var-type.bal [hunk 5]
```diff
@@ -217,5 +228,15 @@ function testQueryExpressionWithSpreadOperatorV2() returns Teacher[]{
                    teacherId: "TER1200"
             };
 
-    return  outputPersonList;
+    return outputPersonList;
+}
+
+public function testQueryWithStream() returns int[]|error {
+    NumberGenerator numGen = new;
+    var numberStream = new stream<int, error>(numGen);
```
Comment (gimantha) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-var-type.bal]: What will happen if the iterator object next method does not return an error but the stream has the errorType as the completionType?

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-exp-iterable-objects.bal [hunk 6]
```diff
@@ -0,0 +1,61 @@
+type Iterable object {
```
Comment (gimantha) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query-exp-iterable-objects.bal]: Shall we add another test for iterable which returns an error as well?

File: tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal (hunk 4 above)
Comment (pcnfernando) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal]: it will throw error since map is any type map. Isn't that expected?

Comment (mohanvive) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal]: It is a compile time error. (i.e, operator '==' not defined for 'any' and 'string')

Comment (mohanvive) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal]: sorry, just now saw. That is an expected case.

Comment (gimantha) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-defined-type.bal]: ah yes.. sorry didnt see that m is a map<any>

File: tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-var-type.bal (hunk 5 above)
Comment (pcnfernando) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/simple-query-with-var-type.bal]: It passes without throwing any error
