### PR TITLE
Add improvements and bug fixes in IDL implementation

### LINKED ISSUE #38234: [Bug]: [Project API] `document` API is throwing an exception for generated IDL client
### Description

I generated an IDL client and reloaded the VSCode window. When I was trying to make a change in the generated client the following exception was thrown.

image

https://github.com/ballerina-platform/ballerina-lang/blob/656430fde21a51e5c01193a72127baf670bc4efe/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java#L1108

Here we are trying to invoke the `document` method and get the document for the path of the generated idl client. It throws an exception. Due to this the project can't be compiled. 

### Steps to Reproduce

Mentioned above

### Affected Version(s)

2201.3.0-stage

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by azinneera**
Fixes #38234

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/CompletionTest.java [hunk 1]
```diff
@@ -116,7 +116,10 @@ public Object[][] testSubset() {
     }
 
     public List<String> skipList() {
-        return new ArrayList<>();
+        List<String> skipList = new ArrayList<>();
+        // Skipping due to https://github.com/ballerina-platform/ballerina-lang/issues/38234
+        skipList.add("completions_inside_generated_idl_client.json");
+        return skipList;
```
Comment (gayalkuruppu) [inline language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/CompletionTest.java:122]: Shall we do this inside `ClientDeclarationContextTest` WDYT?

Comment (azinneera) [reply language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/CompletionTest.java]: Addressed in 934532e
