### PR TITLE
Infer type for int/float literals in binary expressions

### LINKED ISSUE #13904: [Spec Deviation] Incorrect type inferring for int-literals/floating-point-literals used in equality expressions
**Description:**

The spec defines the types of int-literals and floating-point-literals to be the contextually expected types.

```
The type of an int-literal depends on the contextually expected numeric type, where 
the contextually expected numeric type is the intersection of the contextually 
expected type with int|float|decimal:
● if the contextually expected numeric type is a subtype of float, then the type of the
int-literal is a float
● if the contextually expected numeric type is a subtype of decimal, then the type of 
the int-literal is decimal
● otherwise, the broad type of the int-literal is int, and the narrow type is a 
singleton int type

Similarly the type of a floating-point-literal is determined as follows:
● if the contextually expected numeric type is a subtype of decimal, the type of the
floating-point-literal is a decimal,
● otherwise, the type of the floating-point literal is float
```

Thus even in the equality expression, the type of the int-literal/floating-point-literal used as an operand would depend on the type of the other operand.

The following is the expected behaviour:
```ballerina
public function main(string... args) {
    float f = 1.0;
    _ = f == 2; // 2 should be considered float 2.0

    decimal d = 2.0;
    _ = d == 2; // 2 should be considered decimal 2.0

    int|float|decimal ifd = 1;
    _ = ifd == 1; // already allowed, 1 would be considered int 1, evals to true

    ifd = f; // f is float 1.0
    _ = ifd == 1; // evals to false, since 1 is considered int 1, and ifd is float 1.0
}
```

**Affected Versions:**
0.990.3

### LINKED ISSUE #31305: Infer correct type for int/float numerical literals
**Description:**
Following expressions should be supported 
`float a1 = 10 + 3.0 + 5.0; `
`float a2 = 5 + 3 + 10;`
`decimal a3 = 10.0 + 3 ;`
`decimal a4 = 10 + 5 + 3.0;`

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by rpjayasekara**
Fixes #31305

`float f = 2.0 + 2;`
`decimal d = 2.0 + 2`
`float a = 3 + 5;`

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -4012,15 +4013,56 @@ public void visit(BLangBinaryExpr binaryExpr) {
         checkDecimalCompatibilityForBinaryArithmeticOverLiteralValues(binaryExpr);
 
         SymbolEnv rhsExprEnv;
-        BType lhsType = checkExpr(binaryExpr.lhsExpr, env);
+        BType lhsType;
+        if (binaryExpr.lhsExpr instanceof BLangNumericLiteral) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4017]: We can use the node kind instead.

```suggestion
        if (binaryExpr.lhsExpr.getKind() == NodeKind.NUMERIC_LITERAL) {
```

We usually try to avoid expensive instanceof checks.

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4017]: Shall we extract `binaryExpr.lhsExpr` out to a variable since it is accessed in multiple places?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -4012,15 +4013,56 @@ public void visit(BLangBinaryExpr binaryExpr) {
...
+                    } else {
+                        rhsType = checkExpectedTypeCompatibility(binaryExpr.rhsExpr, lhsType, rhsExprEnv);
+                    }
+                    break;
+                default:
+                    rhsType = checkExpr(binaryExpr.rhsExpr, rhsExprEnv);
+            }
+        } else {
+            rhsType = checkExpr(binaryExpr.rhsExpr, rhsExprEnv);
+        }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4065]: Isn't this similar to L4017-L4035? Shall we check if we can extract this logic out to a method?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/subtract-operation.bal [hunk 3]
```diff
@@ -69,6 +69,18 @@ function testSubtractSingleton() {
     assertEqual(a1 - a7, 8);
 }
 
+function testContextuallyExpectedTypeOfNumericLiteralInSubtract(){
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/subtract-operation.bal:72]:
```suggestion
function testContextuallyExpectedTypeOfNumericLiteralInSubtract() {
```

Please fix wherever applicable.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (rpjayasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4065]: I think it can, I will extract the logic out to a method

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 4]
```diff
@@ -4078,6 +4080,46 @@ public void visit(BLangBinaryExpr binaryExpr) {
         resultType = types.checkType(binaryExpr, actualType, expType);
     }
 
+    private BType checkAndGetType(BLangExpression expr, SymbolEnv env, BLangBinaryExpr binaryExpr) {
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4083]: 1. This function looks too nested. Shall we try to early exit when possible.
2. This function only seems to propagate the contextually expected type one level down. We need to support `float x = 1.0 + 2 + 3` too.

**Comment by MaryamZi** [comment]
@rpjayasekara, as discussed, let's create a new issue for what we are fixing here and link that in the PR.

**Comment by rdhananjaya** [comment]
@rpjayasekara can you please reword commit messages to be within 50 characters

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java [hunk 5]
```diff
@@ -2286,4 +2312,12 @@ public void visit(BLangObjectConstructorExpression source) {
 
         source.cloneRef = clone;
     }
+
+    public int getCloneAttempt() {
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java:2316]: I think we can remove these methods now (both get and set)

Comment (rpjayasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java:2316]: Will remove those

**Review by rdhananjaya — APPROVED** [review]
