### PR TITLE
Fix module ID identification issue with dot in org name

### LINKED ISSUE #30811: RC5 non-functional with multiple package project
I am trying to use Beta1 RC5 with a multi-package project.

https://github.com/ballerina-platform/nballerina/tree/james-bir

After compiling the types package with `bal build -c` and then pushing to local repo, I open the bir folder with VSCode. The output window shows errors like this and no editing functionality is available.

```
Ballerina version: Swan Lake Beta 1
Using Ballerina CLI command 'bal.bat' for Language server.
[Info  - 15:40:50] Operation 'text/didOpen' {project: 'file:///c:/Users/jjc/Documents/GitHub/nballerina/bir/' kind: 'build_project'} created
[Error - 15:40:50] Operation 'text/didOpen' failed! {uri: '/c%3A/Users/jjc/Documents/GitHub/nballerina/bir/bir.bal', error: 'Index 1 out of bounds for length 1'}
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.ballerina.projects.directory.BuildProject.documentId(BuildProject.java:141)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:866)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.updateBalDocument(BallerinaWorkspaceManager.java:764)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.didOpen(BallerinaWorkspaceManager.java:250)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didOpen(BallerinaTextDocumentService.java:507)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[Error - 15:40:50] Operation 'text/foldingRange' failed! {uri: '/c%3A/Users/jjc/Documents/GitHub/nballerina/bir/bir.bal', error: 'Index 1 out of bounds for length 1'}
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.ballerina.projects.directory.BuildProject.documentId(BuildProject.java:141)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:866)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:167)
	at org.ballerinalang.langserver.foldingrange.FoldingRangeProvider.getSyntaxTree(FoldingRangeProvider.java:66)
	at org.ballerinalang.langserver.foldingrange.FoldingRangeProvider.getFoldingRange(FoldingRangeProvider.java:45)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$foldingRange$13(BallerinaTextDocumentService.java:576)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[Error - 15:40:50] Operation 'text/codeLens' failed! {uri: '/c%3A/Users/jjc/Documents/GitHub/nballerina/bir/bir.bal', error: 'Index 1 out of bounds for length 1'}
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.ballerina.projects.directory.BuildProject.documentId(BuildProject.java:141)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:866)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:167)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentDocument(AbstractDocumentServiceContext.java:142)
	at org.ballerinalang.langserver.codelenses.providers.DocsCodeLensesProvider.getLenses(DocsCodeLensesProvider.java:69)
	at org.ballerinalang.langserver.codelenses.CodeLensUtil.getCodeLenses(CodeLensUtil.java:48)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeLens$9(BallerinaTextDocumentService.java:374)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[Error - 15:40:50] Operation 'text/codeLens' failed! {uri: '/c%3A/Users/jjc/Documents/GitHub/nballerina/bir/bir.bal', error: 'Index 1 out of bounds for length 1'}
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.ballerina.projects.directory.BuildProject.documentId(BuildProject.java:141)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:866)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.document(BallerinaWorkspaceManager.java:167)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentDocument(AbstractDocumentServiceContext.java:142)
	at org.ballerinalang.langserver.codelenses.providers.DocsCodeLensesProvider.getLenses(DocsCodeLensesProvider.java:69)
	at org.ballerinalang.langserver.codelenses.CodeLensUtil.getCodeLenses(CodeLensUtil.java:48)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeLens$9(BallerinaTextDocumentService.java:374)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose
Fixes #30811

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java [hunk 1]
```diff
@@ -136,7 +136,9 @@ public DocumentId documentId(Path file) {
             Path parent = Optional.of(file.toAbsolutePath().getParent()).get();
             for (ModuleId moduleId : this.currentPackage().moduleIds()) {
                 String moduleDirName;
-                if (moduleId.moduleName().contains(DOT)) {
+                // Check for the module name contains a dot and not being the default module
+                if (moduleId.moduleName().contains(DOT)
```
Comment (azinneera) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java:140]: We can remove the check for `DOT` here and keep just the condition to check if it is a non-default module.

Comment (nadeeshaan) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java]: Done

**Review by azinneera — APPROVED** [review]
