### PR TITLE
Assign  xml<xml:Text> to a xml:Text 

### LINKED ISSUE #28929: Cannot assign xml<xml:Text> to a xml:Text
**Description:**
xml<xml:Text> and xml:Text is the same thing.

```ballerina
xml<xml<xml<'xml:Text>>> f = xml ``;
xml:Text t = f; // incompatible types: expected 'xml:Text', found 'xml<xml<xml<xml:Text>>>'(BCE2066)
xml<xml:Text> t1 = f; // incompatible types: expected 'xml<xml:Text>', found 'xml<xml<xml<xml:Text>>>'(BCE2066)
f = t; // this works 
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by rpjayasekara**
Fixes #28929

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -1005,16 +1005,20 @@ private boolean isXMLTypeAssignable(BType sourceType, BType targetType, Set<Type
...
             BXMLType source = (BXMLType) sourceType;
             if (targetTag == TypeTags.XML_TEXT) {
                 if (source.constraint != null) {
-                    return source.constraint.tag == TypeTags.NEVER ||
-                            source.constraint.tag == TypeTags.XML_TEXT;
+                    if (source.constraint.tag == TypeTags.NEVER ||
+                            source.constraint.tag == TypeTags.XML_TEXT) {
+                        return true;
+                    } else {
+                        return isAssignable(targetType, source.constraint, unresolvedTypes);
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1020]: public function main() {
    xml e = xml `<e/>`;
    xml:Text t = e; // this should not be allowed
}

**Review by rdhananjaya — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 1 above)
Comment (rdhananjaya) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1022]: Still not right, consider following code.

```ballerina
public function main() {
    xml<xml> e = xml `<elem/>`;
    xml:Text t = e; // this should not be allowed 
}
```

Comment (rdhananjaya) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1022]: Please add negative test cases too

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal [hunk 2]
```diff
@@ -110,3 +110,16 @@ function testIncompatibleTypesInTemplates() {
...
+    xml:Element e2 = e1;
+    xml<xml<xml<'xml:Comment>>> c1 = xml `<!--some comment--><!--some comment-->`;
+    xml:Comment c2 = c1;
+    xml<xml<xml<'xml:ProcessingInstruction>>> p1 = xml `<?foo?><?faa?>`;
+    xml:ProcessingInstruction p2 = p1;
+    xml x1 = xml `<e/>/`;
+    xml:Text t1 = x1;
+    xml<xml> x2 = xml `<elem/>`;
+    xml:Text t2 = x2;
+}
```
Comment (rdhananjaya) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal:125]:
```suggestion
}

```

**Review by rdhananjaya — APPROVED** [review]
