### PR TITLE
Warn about corruption in Dependencies.toml.

### LINKED ISSUE #42106: [Bug]: Building a project with a corrupted Dependencies.toml causes a bad sad error for some cases
### Description

When there's corrupted Dependencies.toml file in a Ballerina package(this could be a missing field or an invalid value in a field), and the project is built, the build will fail with the following bad sad error.
```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2024-02-02 14:49:07,734] SEVERE {b7a.log.crash} - Cannot find the generated jar library for module: module_sample 
java.lang.IllegalStateException: Cannot find the generated jar library for module: module_sample
        at io.ballerina.projects.JBallerinaBackend.lambda$codeGeneratedLibrary$5(JBallerinaBackend.java:531)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:530)
        at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:298)
        at io.ballerina.projects.JBallerinaBackend.createManifest(JBallerinaBackend.java:429)
        at io.ballerina.projects.JBallerinaBackend.emitExecutable(JBallerinaBackend.java:536)
        at io.ballerina.projects.JBallerinaBackend.emit(JBallerinaBackend.java:219)
        at io.ballerina.cli.task.CreateExecutableTask.execute(CreateExecutableTask.java:114)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:288)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

At the end, the Dependencies.toml is generated again correcting the fields that were missing/invalid.

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Other Area

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
Fixes #42106

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BuildCommandTest.java [hunk 1]
```diff
@@ -872,6 +872,27 @@ public void testBuildBalProjectWithDumpRawGraphsFlag() throws IOException {
...
+        Path projectPath = this.testResources.resolve("corrupted-dependecies-toml-file");
+        cleanTarget(projectPath);
+        Path sourcePath = projectPath.resolve("Dependencies-corrupt.toml");
+        Path destinationPath = projectPath.resolve("Dependencies.toml");
+        Files.copy(sourcePath, destinationPath);
+        BuildCommand buildCommand = new BuildCommand(projectPath, printStream, printStream, false);
+        new CommandLine(buildCommand);
+        buildCommand.execute();
+        String buildLog = readOutput(true);
+        Assert.assertTrue(buildLog.contains("WARNING [Dependencies.toml:(6:1,18:1)] " +
```
Comment (gayaldassanayake) [inline cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/BuildCommandTest.java:886]: Can we check for an exact match here with the expected log written in a file? AFAIR we did this for most of the existing tests.

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/DependencyManifestBuilder.java [hunk 2]
```diff
@@ -84,7 +84,19 @@ private DependencyManifestBuilder(TomlDocument dependenciesToml,
         this.dependenciesToml = Optional.ofNullable(dependenciesToml);
         this.packageDescriptor = packageDescriptor;
         this.diagnosticList = new ArrayList<>();
-        this.dependencyManifest = parseAsDependencyManifest();
+        DependencyManifest parsedDependecyManifest = parseAsDependencyManifest();
+        if (parsedDependecyManifest.diagnostics().hasErrors()) {
+            var diagnosticInfo = new DiagnosticInfo(
+                    ProjectDiagnosticErrorCode.CORRUPTED_DEPENDENCIES_TOML.diagnosticId(),
+                    "Detected corrupted 'Dependencies.toml' file. This will be updated to latest dependencies.",
```
Comment (gayaldassanayake) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/DependencyManifestBuilder.java:91]:
```suggestion
                    "Detected corrupted 'Dependencies.toml' file. This will be updated to the latest dependencies.",
```

also IMO, it's better to say something like,
`Detected corrupted 'Dependencies.toml' file. Dependencies will be updated to the latest versions ignoring the 'Dependencies.toml'.`

Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/DependencyManifestBuilder.java:91]: `Detected corrupted 'Dependencies.toml' file. Dependencies will be updated to the latest versions.`

**Review by gayaldassanayake — APPROVED** [review]
