### PR TITLE
Fix issue with associating symbols being type narrowed with envs 

### LINKED ISSUE #34366: Wrong type of the variable showed when hovering
**Description:**
Peek 2021-12-16 16-11

**Steps to reproduce:**
Hover the cursor to the `b` in the line `20 c = b` in the following ballerina code
```ballerina
function testReachableCodeWithBinaryCondition4() returns int {
    10|20 b = 10;

    if b == 10 {
        return 10;
    }

    20 c = b;

    if b  == 20 {
        return 20;
    }
}
```

**Affected Versions:**
Swan Lake beta 6

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #34369: Local variables don't get defined under the correct environment
**Description:**
```ballerina
function testRun(string name) returns int {
    if !(name is "") {
        return 1;
    }

    string testvar = "toyota";
   <cursor>
}
```
Try getting the completions at the `<cursor>` position.

Here `testvar` will be visible if we remove `return 1` line

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lasinicl**
## Purpose
$title

Fixes #34369

## Approach
```ballerina
public function main() {
    int? a = 10;
    if a is () {
        return;
    }
   // Types are narrowed following an `if` statement without an `else`, which is not completed normally. Therefore `a` should be 
   // `int` in this context. 
   int b = a;
   <curser> // here `b` should be suggested. As per #34369 this is not getting suggested ATM.
}
```
To fix this I have followed the following approach.
A new block is created internally to store the statements following an `if` statement without an `else`. This block's environment is updated with the narrowed symbols. 
```ballerina
public function main() {
    int? a = 10;
    if a is () {
        return;
    }
    {
        // Narrowing is applied to this block.
        int b = a;
        <curser> // `b` is being suggested here.
    }
}
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by pcnfernando** [comment]
Didn't get unreachable error for return.
```ballerina
function dummyTest() {
    int? a = 10;
    if a is () && !(a is ()) {
        return;
    }
    int b = a; //expected 'int', found 'int?'
}

```

**Comment by lasinicl** [comment]
In the first example `int b = a;` this line results in an incompatible types error. Unreachability analysis is carried out after semantic analysis. If you comment out that line or correct it, you would see the unreachable error for the `return`.
```ballerina
function dummyTest() {
    int? a = 10;
    if a is () && !(a is ()) {
        return; //unreachable code
    }
    int? b = a; 
}
```
The second one is a bug. I haven't done any changes in the unreachability analysis in this PR. Can you create a separate issue? Will address it separately.

**Comment by pcnfernando** [comment]
> * The second one is a bug. I haven't done any changes in the unreachability analysis in this PR. Can you create a separate issue? Will address it separately.

This is also due to the error at `int b = a;` If we remove the line, getting "string will not be matched to ()" at inner if.

**Comment by lasinicl** [comment]
> This is also due to the error at `int b = a;` If we remove the line, getting "string will not be matched to ()" at inner if.

Ah yes. That's also a sematic error. :)

**Comment by pcnfernando** [comment]
Shouldn't we narrow the else if cases?

```ballerina
public function dummyTest() {
    int|string? a = 10;
    if a is string {
        return;
    } else if a is () {
        return;
    }
    int x = a; // expected 'int', found '(int|string)?']
}
```

**Comment by lasinicl** [comment]
> Shouldn't we narrow the else if cases?
> 
> ```ballerina
> public function dummyTest() {
>     int|string? a = 10;
>     if a is string {
>         return;
>     } else if a is () {
>         return;
>     }
>     int x = a; // expected 'int', found '(int|string)?']
> }
> ```

We should. Related issue https://github.com/ballerina-platform/ballerina-lang/issues/34307.

**Comment by pcnfernando** [comment]
We'll have to add few visible symbol tests to test the behaviour. Are we handling it separately?

**Comment by pcnfernando** [comment]
This should not be narrowed. Seems introduced with the PR
```ballerina
public function dummyTest() {
      int? a = 10;
      string? b = "100";
      if a is int {
          if (a == 5) {
              return;
          }
      }
      b = a;
}
```

**Comment by lasinicl** [comment]
> We'll have to add few visible symbol tests to test the behaviour. Are we handling it separately?

Will add the tests separately.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 1]
```diff
@@ -4950,26 +4951,98 @@ BLangValueType addValueType(Location pos, TypeKind typeKind) {
...
                 statements.add((BLangStatement) statement.apply(this));
             }
         }
         return statements;
     }
 
+    private void createBlockStatement(StatementNode currentStatement, int position,
+                                      NodeList<StatementNode> statementNodes,
+                                      List<BLangStatement> statements, Node endNode) {
+        for (int j = position; j < statementNodes.size(); j++) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5006]: Can you check whether merging the logics in the two methods is feasible since we are doing the same thing.

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5006]: suggestions in generateAndAddBLangStatements() are applicable here as well

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 2]
```diff
@@ -508,7 +508,24 @@ public void visit(BLangFunction funcNode) {
...
+        int stmtCount = -1;
         for (BLangStatement stmt : body.stmts) {
+            stmtCount++;
+            BLangStatement prevStatement = null;
+            if (stmtCount > 0) {
+                prevStatement = body.stmts.get(stmtCount - 1);
+            }
+            if (stmt.getKind() == NodeKind.BLOCK && prevStatement != null &&
+                    prevStatement.getKind() == NodeKind.IF && ((BLangIf) prevStatement).elseStmt == null &&
+            this.notCompletedNormally) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:520]: code not formatted

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 3]
```diff
@@ -1823,7 +1840,26 @@ private void recursivelySetFinalFlag(BLangVariable variable) {
 
     public void visit(BLangBlockStmt blockNode) {
         env = SymbolEnv.createBlockEnv(blockNode, env);
-        blockNode.stmts.forEach(stmt -> analyzeStmt(stmt, env));
+        int stmtCount = -1;
+        for (BLangStatement stmt : blockNode.stmts) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:1844]: Extract out the common logic in func body and block node

**Review by pcnfernando — APPROVED** [review]
LGTM

**Review by hasithaa — APPROVED** [review]

**Comment by hasithaa** [comment]
@pubudu91, @lasinicl is still working on the improvement we discussed. But let's go ahead with this PR since this will address the original issue.
