### PR TITLE
Present the Original Value Symbols for Quoted Identifiers of Reserved Keywords

### LINKED ISSUE #29462: For variables named with ' prefix; ' is missed during suggestion
**Description:**
Screenshot 2021-03-23 at 15 42 10

Sample code:

```ballerina
function rate(Currency 'from, Currency to) {
    string fromCurrency = 'from;
    string toCurrency = to;
    string responseKey = fr
}
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #29462

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by hasithaa** [comment]
Please add some test cases

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaMethodSymbol.java [hunk 1]
```diff
@@ -60,7 +60,7 @@ public FunctionTypeSymbol typeDescriptor() {
 
     @Override
     public Optional<String> getName() {
-        return this.functionSymbol.getName();
+        return this.functionSymbol.getName().map(this::escapeReservedKeyword);
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaMethodSymbol.java:63]: This is not necessary right? IINM, the name would already be escaped in the result returned by `functionSymbol.getName()`.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java [hunk 2]
```diff
@@ -65,7 +66,16 @@ protected BallerinaSymbol(String name, SymbolKind symbolKind, BSymbol symbol, Co
...
     @Override
     public Optional<String> getName() {
-        return Optional.ofNullable(this.name);
+        // In the langlib context, reserved keywords can be used as regular identifiers. Therefore, they will not be
+        // escaped.
+        if (getModule().isPresent() && getModule().get().id() != null &&
+                !getModule().get().id().moduleName().isEmpty() &&
+                getModule().get().id().moduleName().startsWith("lang.") &&
+                !getModule().get().id().orgName().isEmpty() &&
+                getModule().get().id().orgName().startsWith("ballerina")) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java:75]: Shall we refactor this a bit? Assign the returned value to a var and use, so that all these `getModule().get().id()` calls are simplified?

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaMethodSymbol.java (hunk 1 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaMethodSymbol.java]: Fixed.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java (hunk 2 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java]: Updated.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java [hunk 3]
```diff
@@ -65,7 +67,16 @@ protected BallerinaSymbol(String name, SymbolKind symbolKind, BSymbol symbol, Co
...
+        // In the langlib context, reserved keywords can be used as regular identifiers. Therefore, they will not be
+        // escaped.
+        if (getModule().isPresent()) {
+            ModuleID moduleID = getModule().get().id();
+            if (moduleID != null && !moduleID.moduleName().isEmpty() && moduleID.moduleName().startsWith("lang.") &&
+                    !moduleID.orgName().isEmpty() && moduleID.orgName().startsWith("ballerina")) {
+                return Optional.ofNullable(this.name);
+            }
+        }
+        return Optional.ofNullable(escapeReservedKeyword(this.name));
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java:79]: The 2 conditions `moduleID != null && !moduleID.moduleName().isEmpty()` are unnecessary IINM. If there's a module symbol, there should always be a module ID. And since we are checking `startsWith()`, checking for an empty string is irrelevant right?

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java:79]: Another small point, shall we cache the escaped name? So that we don't have to compute it each time `getName()` is called. A symbol is immutable. So it won't change after creation. Refer to some of the other methods for examples of where this has been done.

Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java]: @pubudu91 thanks for the suggestion. 

Sure, that'd be a great idea to cache it.

Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java]: @pubudu91 used a caching mechanism. Also implemented it in the `BallerinaRecordFieldSymbol` and `BallerinaObjectFieldSymbol` classes as well.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java [hunk 4]
```diff
@@ -65,7 +68,21 @@ protected BallerinaSymbol(String name, SymbolKind symbolKind, BSymbol symbol, Co
...
     public Optional<String> getName() {
-        return Optional.ofNullable(this.name);
+        // In the langlib context, reserved keywords can be used as regular identifiers. Therefore, they will not be
+        // escaped.
+        if (this.escapedName != null) {
+            return Optional.of(this.escapedName);
+        }
+        if (getModule().isPresent()) {
+            ModuleID moduleID = getModule().get().id();
+            if (moduleID != null && moduleID.moduleName().startsWith("lang")
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java:78]: The `moduleID != null` check is also unnecessary since it's expected to be not null.

Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java]: Removed it.

**Review by pubudu91 — APPROVED** [review]
