### PR TITLE
Fix Error Message for Accessing Incorrect Field Name of Closed Records

### LINKED ISSUE #30873: Misleading error message for incorrect field name of closed record
In beta1 rc5, this

```
type R record {|
  int x;
|};

function foo(R r) returns int {
  return r.y; // wrong field name
}
```

gets the error message: ` type 'R' does not support field access for non-required field 'y'`.

The error message should be ` type 'R' does not have a field 'y'`.

I run into this ALL the time.

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #30873

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -7031,6 +7045,27 @@ private BType checkFieldAccessExpr(BLangFieldBasedAccess fieldAccessExpr, BType
         return actualType;
     }
 
+    private boolean checkRecordFieldExistence(BRecordType recordVarRefType, Name fieldName) {
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7048]: Shall we re-name this to something like `isRecordFieldExists` or something?

**Comment by rdhananjaya** [comment]
I think we need to rethink the error message.
```ballerina
type R record {
    int i;
};

public function main() {
    R r = {i: 0, "j": 22};
    anydata jr = r["j"];
    anydata ir = r["i"]; 
    anydata j = r.j; // undefined field 'j' in record 'R' // this is wrong: this field is defined.
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -6970,6 +6970,20 @@ private BType checkFieldAccessExpr(BLangFieldBasedAccess fieldAccessExpr, BType
...
+                dlog.error(fieldAccessExpr.pos, DiagnosticErrorCode.UNDEFINED_FIELD_IN_RECORD, fieldName, varRefType);
+                return actualType;
+            }
+
+            // Check if the field accessed is present in the fields of a record which is a member of a union type.
+            if (varRefType.tag == TypeTags.UNION &&
+                    !checkFieldExistenceInUnionRecordMembers(((BUnionType) varRefType).getMemberTypes(), fieldName)) {
+                dlog.error(fieldAccessExpr.pos, DiagnosticErrorCode.UNDEFINED_FIELD_IN_RECORD, fieldName, varRefType);
+                return actualType;
+            }
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6985]: Is this the best way to handle this? These 2 fixes placed here seem rather ad-hoc. The logic related to this is in the `checkRecordFieldAccessExpr()` method. Shouldn't this logic be incorporated somewhere in that method?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6985]: I also think we can improve how we handle this. But `checkRecordFieldAccessExpr` doesn't log errors. I think we can let this go on the original path and handle the errors from L6994 onward.

If we do it this way we'll be doing some checks unnecessarily. For example where the field is valid, both the introduced checks and  `checkRecordFieldAccessExpr` will check for existence.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6985]: Basically if `!fieldAccessExpr.isLValue` iin L6994, do these checks and use the relevant message.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -7031,6 +7045,27 @@ private BType checkFieldAccessExpr(BLangFieldBasedAccess fieldAccessExpr, BType
...
     }
 
+    private boolean checkRecordFieldExistence(BRecordType recordVarRefType, Name fieldName) {
+        return recordVarRefType.fields.containsKey(fieldName.getValue());
+    }
+
+    private boolean checkFieldExistenceInUnionRecordMembers(LinkedHashSet<BType> memberTypes, Name fieldName) {
+        boolean membersHaveRecordsTypes = false;
+        for (BType memberType : memberTypes) {
+            if (memberType.tag == TypeTags.RECORD) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7055]: Given that for the record tag, isSubTypeOfBaseType specifically checks for records, does this become false for any case atm?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java [hunk 4]
```diff
@@ -52,8 +52,7 @@ public void testNegativeCases() {
         int i = 0;
         validateError(negativeResult, i++, "invalid operation: type 'Employee' does not support field access " +
                               "for non-required field 'id'", 32, 9);
-        validateError(negativeResult, i++, "invalid operation: type 'Employee' does not support field access " +
-                              "for non-required field 'salary'", 33, 9);
+        validateError(negativeResult, i++, "undefined field 'salary' in record 'Employee'", 33, 9);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java:55]: Shall we add negative tests for unions if we don't have them already.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 5]
```diff
@@ -7031,6 +7045,27 @@ private BType checkFieldAccessExpr(BLangFieldBasedAccess fieldAccessExpr, BType
         return actualType;
     }
 
+    private boolean checkRecordFieldExistence(BRecordType recordVarRefType, Name fieldName) {
+        return recordVarRefType.fields.containsKey(fieldName.getValue());
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7049]: Do we need a method for this? IMO we can do this in-line since it's straightforward, self-explanatory, and the only place this is used.

**Comment by sanjana** [comment]
The types of scenarios where the Record Field Access Expression may log diagnostics, are listed down here: 
https://docs.google.com/document/d/16tQz2zM3BwU2RKt3i_jSD1puLET-rDDcS1ocLtiiZBo/edit?usp=sharing 

The solution would align accordingly.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated the approach.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 3 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java (hunk 4 above)
Comment (sanjana) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/FieldAccessTest.java]: Added negative test cases for union of records as well.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 5 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Removed with the new approach.

**Comment by sanjana** [comment]
> I think we need to rethink the error message.
> 
> ```ballerina
> type R record {
>     int i;
> };
> 
> public function main() {
>     R r = {i: 0, "j": 22};
>     anydata jr = r["j"];
>     anydata ir = r["i"]; 
>     anydata j = r.j; // undefined field 'j' in record 'R' // this is wrong: this field is defined.
> }
> ```

@rdhananjaya 

With the new approach, the error message for this would be: `invalid field access: 'j' is not a required field in record 'R', use member access to access a field that may have been specified as a rest field`.

**Review by rdhananjaya — APPROVED** [review]
