### PR TITLE
Fix semantic changes related to numeric literals

### LINKED ISSUE #33316: Type of floating-point-literal when contextually expected type is int|decimal
Please refer to the discussion of https://github.com/ballerina-platform/ballerina-spec/issues/943.

### LINKED ISSUE #33318: an out of range float  should be a compile-time error
Please refer to discussion https://github.com/ballerina-platform/ballerina-spec/issues/939

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fixes #33316
Fixes #33318

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -467,6 +467,24 @@ private void checkXMLNamespacePrefixes(List<BLangXMLElementFilter> filters) {
         }
     }
 
+    private int targetMemberTypeTag(BFiniteType finiteType) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:470]: may be?

```suggestion
    private int getPreferredMemberTypeTag(BFiniteType finiteType) {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -467,6 +467,24 @@ private void checkXMLNamespacePrefixes(List<BLangXMLElementFilter> filters) {
...
+            }
+        }
+        for (int i = TypeTags.INT; i <= TypeTags.DECIMAL; i++) {
+            for (BLangExpression valueExpr : finiteType.getValueSpace()) {
+                if (valueExpr.getBType().tag == i) {
+                    return i;
+                }
+            }
+        }
+        return 0;
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:485]: Below failing at runtime
```ballerina
type Mat 1d|"dummy";

function dummyTest() {
     Mat f1 = 1;
     boolean res = f1 is 1d;
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -561,38 +579,43 @@ private BType setLiteralValueAndGetType(BLangLiteral literalExpr, BType expType)
...
-                    return setLiteralValueAndGetType(literalExpr, symTable.floatType);
-                }
-
-                finiteType = getFiniteTypeWithValuesOfSingleType((BUnionType) expType, symTable.floatType);
-                if (finiteType != symTable.semanticError) {
-                    BType setType = setLiteralValueAndGetType(literalExpr, finiteType);
-                    if (literalExpr.isFiniteContext) {
-                        // i.e., a match was found for a finite type
-                        return setType;
+                if (finiteType == symTable.semanticError) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:593]: Can we try to move out the common logic so that we can check int, byte, and so on in order?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:485]: Shall I create a separate issue for this?. Because this issue does not relate to the type. right?
```
[2021-11-05 08:37:12,785] SEVERE {b7a.log.crash} - Character d is neither a decimal digit number, decimal point, nor "e" notation exponential mark. 
java.lang.NumberFormatException: Character d is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:518)
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:852)
        at io.ballerina.runtime.internal.values.DecimalValue.<init>(DecimalValue.java:71)
        at test3.dummyTest(test3.bal:5)
        at test3.main(test3.bal:10)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:323)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 

```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 4]
```diff
@@ -3466,6 +3466,28 @@ boolean checkLiteralAssignabilityBasedOnType(BLangLiteral baseLiteral, BLangLite
...
 
+    boolean isFloatLiteralValue(Location pos, String numericLiteral) {
+        double value = Double.parseDouble(String.valueOf(numericLiteral));
+        if (Double.isInfinite(value)) {
+            dlog.error(pos, DiagnosticErrorCode.FLOAT_TOO_LARGE, numericLiteral);
+            return false;
+        }
+
+        if (value == 0.0) {
+            for (int i = 0; i < numericLiteral.length(); i++) {
```
[the remark this answers is not in the document]
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3477]: Currently, we represent float values not included in the float range as `infinity`(value > Max_Value) and `0.0`(value < Min_Value). With this change, we give an error for those values.

[the remark this answers is not in the document]
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3477]: I was wondering when the parsed value will be "0.0" but not small. The user-provided "0.0" literal case. Shall we try to handle this using a regex maybe?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (gimantha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:485]: @chiranSachintha https://github.com/ballerina-platform/ballerina-lang/issues/33266 Can you check with Hinduja regarding this? Seems related issue d been fixed earlier

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 5]
```diff
@@ -467,6 +467,24 @@ private void checkXMLNamespacePrefixes(List<BLangXMLElementFilter> filters) {
         }
     }
 
+    private int targetMemberTypeTag(BFiniteType finiteType) {
+        for (int i = TypeTags.SIGNED32_INT; i <= TypeTags.UNSIGNED8_INT; i++) {
+            for (BLangExpression valueExpr : finiteType.getValueSpace()) {
+                if (valueExpr.getBType().tag == i) {
+                    return i;
```
[the remark this answers is not in the document]
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:474]: Yeah. In this instance, didn't need this  because we didn't allow `const` declaration with int subtypes(except byte)

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 6]
```diff
@@ -467,6 +467,17 @@ private void checkXMLNamespacePrefixes(List<BLangXMLElementFilter> filters) {
         }
     }
 
+    private int getPreferredMemberTypeTag(BFiniteType finiteType) {
+        for (BLangExpression valueExpr : finiteType.getValueSpace()) {
+            for (int i = TypeTags.INT; i <= TypeTags.DECIMAL; i++) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:472]: let's continue to next `valueExpr` if `valueExpr.getBType().tag` not within Int/Decimal range.
If not all cases would have to loop through inner loop as well

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 7]
```diff
@@ -3466,6 +3466,28 @@ boolean checkLiteralAssignabilityBasedOnType(BLangLiteral baseLiteral, BLangLite
         return false;
     }
 
+    boolean isFloatLiteralValue(Location pos, String numericLiteral) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3469]: This isn't simply a boolean check?

```suggestion
    BType validateFloatLiteral(Location pos, String numericLiteral) {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 8]
```diff
@@ -3466,6 +3466,28 @@ boolean checkLiteralAssignabilityBasedOnType(BLangLiteral baseLiteral, BLangLite
...
+        double value = Double.parseDouble(String.valueOf(numericLiteral));
+        if (Double.isInfinite(value)) {
+            dlog.error(pos, DiagnosticErrorCode.FLOAT_TOO_LARGE, numericLiteral);
+            return false;
+        }
+
+        if (value == 0.0) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3476]: Can check the inverse and return early.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3477]: Also, it would be clearer to do this check at the very beginning anyway? IMO, at compile time `0.0` can be quite a common case for floating point literals so we won't be losing much by doing this check directly on `numericLiteral`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 9]
```diff
@@ -467,6 +467,17 @@ private void checkXMLNamespacePrefixes(List<BLangXMLElementFilter> filters) {
...
+                if (valueExpr.getBType().tag == i) {
+                    return i;
+                }
+            }
+        }
+        return 0;
+    }
+
     private BType setLiteralValueAndGetType(BLangLiteral literalExpr, BType expType) {
```
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:481]: We may be able to use type intersection computation too.

Basically the intersection of the expected type and (int, float, decimal) or (float, decimal).

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 10]
```diff
@@ -467,6 +467,17 @@ private void checkXMLNamespacePrefixes(List<BLangXMLElementFilter> filters) {
...
 
+    private int getPreferredMemberTypeTag(BFiniteType finiteType) {
+        for (BLangExpression valueExpr : finiteType.getValueSpace()) {
+            for (int i = TypeTags.INT; i <= TypeTags.DECIMAL; i++) {
+                if (valueExpr.getBType().tag == i) {
+                    return i;
+                }
+            }
+        }
+        return 0;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:478]: Probably clearer to return something like `org.wso2.ballerinalang.compiler.util.TypeTags#NONE`.

**Comment by chiranSachintha** [comment]
Example - 1
```ballerina
public function main() {
    byte b = 0x7F & 10;
}
```
Example - 2
```ballerina
public function main() {
    byte b2 = 10 & 10;
}
```
We allow `Example - 1` and disallow `Example - 2` in the current implementation. With this fix, I have disallowed both cases.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 8 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Changed the logic related to this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 11]
```diff
@@ -467,175 +468,239 @@ private void checkXMLNamespacePrefixes(List<BLangXMLElementFilter> filters) {
...
-                if (intOrIntCompatibleTypeFound) {
-                    return setLiteralValueAndGetType(literalExpr, symTable.intType);
-                }
-                if (intSubType != null) {
-                    return setLiteralValueAndGetType(literalExpr, intSubType);
+    private int getPreferredMemberTypeTag(BFiniteType finiteType) {
+        for (BLangExpression valueExpr : finiteType.getValueSpace()) {
+            int typeTag = valueExpr.getBType().tag;
+            if (typeTag > TypeTags.DECIMAL) {
+                continue;
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:475]: Add a test to cover this, if not already added

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 12]
```diff
@@ -467,175 +468,239 @@ private void checkXMLNamespacePrefixes(List<BLangXMLElementFilter> filters) {
...
+            return symTable.decimalType;
+        } else if (expType.tag == TypeTags.FINITE) {
+            BFiniteType finiteType = (BFiniteType) expType;
+            return getFiniteTypeMatchWithIntLiteral(literalExpr, finiteType, literalValue);
+        } else if (expType.tag == TypeTags.UNION) {
+            Set<BType> memberTypes = ((BUnionType) expType).getMemberTypes();
+            for (BType memType : memberTypes) {
+                if (TypeTags.isIntegerTypeTag(memType.tag) || memType.tag == TypeTags.BYTE) {
+                    BType intLiteralType = getIntLiteralType(memType, literalValue);
+                    if (intLiteralType == memType) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:543]: Since you do TypeTags.isIntegerTypeTag(memType.tag) in top, can intLiteralType != memType ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 13]
```diff
@@ -467,175 +468,239 @@ private void checkXMLNamespacePrefixes(List<BLangXMLElementFilter> filters) {
...
+            }
 
-                finiteType = getFiniteTypeWithValuesOfSingleType((BUnionType) expType, symTable.floatType);
-                if (finiteType != symTable.semanticError) {
-                    BType setType = setLiteralValueAndGetType(literalExpr, finiteType);
-                    if (literalExpr.isFiniteContext) {
-                        // i.e., a match was found for a finite type
-                        return setType;
-                    }
+            BType finiteTypeMatchWithByteType =
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:561]:
```suggestion
            BType finiteTypeMatchingByte =
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 14]
```diff
@@ -686,30 +751,41 @@ private BType setLiteralValueAndGetType(BLangLiteral literalExpr, BType expType)
         return literalType;
     }
 
+    private BType getFiniteTypeMatchWithFloatOrDecimalType(BType finiteType, Set<BType> memberTypes,
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:754]:
```suggestion
    private BType getTypeMatchingFloatOrDecimal(BType finiteType, Set<BType> memberTypes,
```

shall we stick to this convention else where also

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 15]
```diff
@@ -3466,6 +3467,23 @@ boolean checkLiteralAssignabilityBasedOnType(BLangLiteral baseLiteral, BLangLite
...
 
+    boolean validateFloatLiteral(Location pos, String numericLiteral) {
+        double value = Double.parseDouble(numericLiteral);
+        if (Double.isInfinite(value)) {
+            dlog.error(pos, DiagnosticErrorCode.FLOAT_TOO_LARGE, numericLiteral);
+            return false;
+        }
+
+        Pattern floatLiteral = Pattern.compile("[1-9]");
+        Pattern floatLiteralWithExpIndicator = Pattern.compile("([1-9])(.*)([eEpP])");
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3478]: Why we had to check two patterns?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 16]
```diff
@@ -3466,6 +3467,23 @@ boolean checkLiteralAssignabilityBasedOnType(BLangLiteral baseLiteral, BLangLite
         return false;
     }
 
+    boolean validateFloatLiteral(Location pos, String numericLiteral) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3470]:
```suggestion
    boolean isValidFloatLiteral(Location pos, String numericLiteral) {
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3470]: Since we are logging errors also in this method (as opposed to just a check), we can use `validateFloatLiteral` right?

**Comment by hasithaa** [comment]
Shall we add refracting suggestions as a sperate PR ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 17]
```diff
@@ -467,175 +468,239 @@ private void checkXMLNamespacePrefixes(List<BLangXMLElementFilter> filters) {
...
-                    return setLiteralValueAndGetType(literalExpr, symTable.byteType);
-                }
+    private BType getFiniteTypeMatchWithIntLiteral(BLangLiteral literalExpr, BFiniteType finiteType,
+                                                   Object literalValue) {
+        BType intLiteralType = getFiniteTypeMatchWithIntType(literalExpr, finiteType);
+        if (intLiteralType != symTable.noType) {
+            return intLiteralType;
+        }
+        int typeTag = getPreferredMemberTypeTag(finiteType);
+        for (int tag = TypeTags.FLOAT; tag <= TypeTags.DECIMAL; tag++) {
```
[the remark this answers is not in the document]
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33643/commits/9bbbbca4ecc7024babad55bd017218112653240f

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 15 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Removed the regex and refactor the previous logic

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 12 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:540]: Yes. because in the `getIntLiteralType` function we check whether  value match to the  range of the subtype.  
Example 
``` ballerina
int:Signed8|int:Unsigned32 i = 510;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 18]
```diff
@@ -3466,6 +3466,31 @@ boolean checkLiteralAssignabilityBasedOnType(BLangLiteral baseLiteral, BLangLite
...
+        double value = Double.parseDouble(numericLiteral);
+        if (Double.isInfinite(value)) {
+            dlog.error(pos, DiagnosticErrorCode.FLOAT_TOO_LARGE, numericLiteral);
+            return false;
+        }
+        if (value != 0.0) {
+            return true;
+        }
+
+        var exponentIndicator = List.of('e', 'E', 'p', 'P');
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3479]: Don't use var in here

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 19]
```diff
@@ -3466,6 +3466,31 @@ boolean checkLiteralAssignabilityBasedOnType(BLangLiteral baseLiteral, BLangLite
...
+        for (int i = 0; i < numericLiteral.length(); i++) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3480]: This doesn't seems to be efficient. Let's handle it in a regex as we discussed before. Let's handle it seperately

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3480]: Create an issue(https://github.com/ballerina-platform/ballerina-lang/issues/33795)

**Review by pcnfernando — APPROVED** [review]
Refactoring suggestions should be addressed in https://github.com/ballerina-platform/ballerina-lang/issues/33795

**Review by gimantha — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 20]
```diff
@@ -467,175 +468,235 @@ private void checkXMLNamespacePrefixes(List<BLangXMLElementFilter> filters) {
...
+    private int getPreferredMemberTypeTag(BFiniteType finiteType) {
+        for (BLangExpression valueExpr : finiteType.getValueSpace()) {
+            int typeTag = valueExpr.getBType().tag;
+            if (typeTag > TypeTags.DECIMAL) {
+                continue;
+            }
+            for (int i = TypeTags.INT; i <= TypeTags.DECIMAL; i++) {
+                if (typeTag == i) {
+                    return i;
                 }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:480]: Can't we just use an if check or a switch statement here instead? Would help with readability also, IMO.
