### PR TITLE
[Shell] Fix incorrect error about isolated

### LINKED ISSUE #28268: Ballerina shell gives incorrect error about isolated
```
=$ var obj = object { function demo() returns int => 42; };  

=$ obj                                                                                         
| invalid access of an 'isolated' variable outside a 'lock' statement
|         obj
|         ^
| Compilation aborted because of errors.
```

I didn't declare obj as isolated...

### PR DESCRIPTION
**Pull request by DamithaSenevirathne**
Fixes #28268 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java [hunk 1]
```diff
@@ -246,8 +246,9 @@ public void reset() {
         Collection<GlobalVariableSymbol> globalVariableSymbols = globalVariableSymbols(project, compilation);
         Map<QuotedIdentifier, GlobalVariable> allNewVariables = new HashMap<>();
         for (VariableDeclarationSnippet snippet : variableDeclarations.keySet()) {
+            String type = snippet.getRootNode().typedBindingPattern().typeDescriptor().kind().name();
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java:249]: No need to use its name. Can just directly use the kind enum.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java [hunk 2]
```diff
@@ -452,12 +453,14 @@ private ClassLoadContext createVariablesExecutionContext(
...
      * @param globalVarSymbols      All global variable symbols.
+     * @param type                  type of the variables.
      * @return Exported found variable information (name and type)
      */
     private Map<QuotedIdentifier, GlobalVariable> createGlobalVariables(
             String qualifiersAndMetadata,
             Set<QuotedIdentifier> definedVariables,
-            Collection<GlobalVariableSymbol> globalVarSymbols) {
+            Collection<GlobalVariableSymbol> globalVarSymbols,
+            String type) {
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java:463]: May not matter once the above comment is addressed. But `type` would be a misleading name to give this. Since this is just really the syntax node kind.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java [hunk 3]
```diff
@@ -480,9 +483,8 @@ private ClassLoadContext createVariablesExecutionContext(
             Set<QuotedIdentifier> requiredImports = new HashSet<>();
             String variableType = importsManager.extractImportsFromType(typeSymbol, requiredImports);
             this.newImports.put(variableName, requiredImports);
-
-            // Create a global variable
-            GlobalVariable globalVariable = new GlobalVariable(variableType, variableName,
+            String kind = typeSymbol.typeKind().getName();
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java:486]: Again, directly use the enum itself.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java [hunk 4]
```diff
@@ -31,20 +31,37 @@
...
-    public GlobalVariable(String type, QuotedIdentifier variableName,
+    private static final String VAR_TYPE_DESC = "VAR_TYPE_DESC";
+
+    public GlobalVariable(String type, String typeLHS, String kind, QuotedIdentifier variableName,
                           boolean isAssignableToAny, String qualifiersAndMetadata) {
         this.type = Objects.requireNonNull(type);
         this.isAssignableToAny = isAssignableToAny;
         this.qualifiersAndMetadata = Objects.requireNonNull(qualifiersAndMetadata);
         this.variableName = variableName;
+        isAssignedWithVar = typeLHS.equals(VAR_TYPE_DESC) ? true : false;
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java:48]: Unnecessary string comparison. Can be fixed by using the enum itself.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java (hunk 1 above)
Comment (pubudu91) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java:249]: Further, this can just be a simple boolean value. We are only interested in knowing whether the var was declared using `var` or not.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java [hunk 5]
```diff
@@ -31,20 +31,37 @@
...
+    public String getKind() {
+        return this.kind;
+    }
+
+    public String getTypeLHS() {
+        if (isAssignedWithVar) {
+            return VAR_TYPE_DESC;
+        }
+        return this.type;
     }
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java:65]: Isn't this separate method unnecessary? Why can't `getType()` itself be used for this?

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/VariableContext.java [hunk 6]
```diff
@@ -80,7 +93,14 @@ public String encodedName() {
...
 
     public String type() {
-        return type;
+        return this.type;
+    }
+
+    public String typeLHS() {
+        String returnType = this.typeLHS.equals(VAR_TYPE_DESC) &&
+                this.kind.equals(OBJECT) ?
+                VAR : this.type;
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/VariableContext.java:102]: Similar comment to the above one. Plus what's the need to special case objects?

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java (hunk 1 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java]: Updated in 3fc03c0dee2d7091929456e76b603ab332cb786e

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java (hunk 2 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java]: Updated in 3fc03c0dee2d7091929456e76b603ab332cb786e

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java (hunk 3 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java]: Updated in 3fc03c0dee2d7091929456e76b603ab332cb786e

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java (hunk 4 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java]: Updated in 3fc03c0dee2d7091929456e76b603ab332cb786e

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java (hunk 5 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java]: Removed in 3fc03c0dee2d7091929456e76b603ab332cb786e

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/VariableContext.java (hunk 6 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/VariableContext.java]: Updated in 3fc03c0dee2d7091929456e76b603ab332cb786e

Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/VariableContext.java]: As an example in the issue, var type need to assign to the left side of the assignment
var obj = object { function demo() returns int => 42; };  

But when considering function assignments as follows
var add = function (int v1, int v2) returns int { return v1 + v2; };

if we assign var to the left side of the assignment we cant use add variable in later stages
following line raise an error
`>> add(5, 10)`

Because of this reason objects and functions were considered as two different cases.

Comment (pubudu91) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/VariableContext.java]: Ah I see. That doesn't sound like a proper solution to the problem. Need to check and figure out why `add()` is not working and then address that. If the user specified the variable using `var`, then it needs to be there in the final generated code as a variable declared using `var`. i.e., remove use of the actual type in LHS for all instances where `var` is used.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java [hunk 7]
```diff
@@ -246,8 +248,10 @@ public void reset() {
         Collection<GlobalVariableSymbol> globalVariableSymbols = globalVariableSymbols(project, compilation);
         Map<QuotedIdentifier, GlobalVariable> allNewVariables = new HashMap<>();
         for (VariableDeclarationSnippet snippet : variableDeclarations.keySet()) {
+            boolean isVarAssigned = snippet.getRootNode().typedBindingPattern()
+                    .typeDescriptor().kind().equals(SyntaxKind.VAR_TYPE_DESC);
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java:252]: No need to use `equals()` with enum. Can just use `==`. Also, do we need to be exposing this root node out of the var decl snippet? IINM, this is the only place it's used in right? Should we consider encapsulating this logic within the var decl snippet itself? 🤔

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java [hunk 8]
```diff
@@ -452,12 +456,14 @@ private ClassLoadContext createVariablesExecutionContext(
      * @param qualifiersAndMetadata Variable snippet qualifiers.
      * @param definedVariables      Variables that were defined.
      * @param globalVarSymbols      All global variable symbols.
+     * @param isAssignedWithVar     type of the variables.
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java:459]: Need to update the doc comment as well

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java [hunk 9]
```diff
@@ -480,10 +486,9 @@ private ClassLoadContext createVariablesExecutionContext(
             Set<QuotedIdentifier> requiredImports = new HashSet<>();
             String variableType = importsManager.extractImportsFromType(typeSymbol, requiredImports);
             this.newImports.put(variableName, requiredImports);
-
-            // Create a global variable
-            GlobalVariable globalVariable = new GlobalVariable(variableType, variableName,
-                    isAssignableToAny, qualifiersAndMetadata);
+            boolean isDefinedObject = typeSymbol.typeKind().equals(TypeDescKind.OBJECT);
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java:489]: Again, no need for `equals()`

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java [hunk 10]
```diff
@@ -34,17 +34,30 @@
     private final QuotedIdentifier variableName;
     private final boolean isAssignableToAny;
     private final String qualifiersAndMetadata;
+    private final boolean isAssignedWithVar;
+    private final boolean isDefinedObject;
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java:38]: As mentioned below, shouldn't be special casing anything.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java (hunk 7 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java]: Updated in d3e7d2d557259712428f4f178b8d6bfd67325435

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java (hunk 10 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java]: Updated in d3e7d2d557259712428f4f178b8d6bfd67325435

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java (hunk 9 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java]: d3e7d2d557259712428f4f178b8d6bfd67325435

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java (hunk 8 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ClassLoadInvoker.java]: Updated in d3e7d2d557259712428f4f178b8d6bfd67325435

**Comment by DamithaSenevirathne** [comment]
Following testcases was disabled due to a bug in the compiler 
(related issue https://github.com/ballerina-platform/ballerina-lang/issues/31850)

Disabled testcases (From both shell-cli-tests and shell-core-tests)

```
 {
    "description": "Define anonymous function with var.",
    "code": "var add = function (int v1, int v2) returns int { return v1 + v2; };"
  },

  {
    "description": "Use add function.",
    "code": "add(5, 10)",
    "expr": "15"
  }
```

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java (hunk 10 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/GlobalVariable.java]: Removed in d3e7d2d557259712428f4f178b8d6bfd67325435

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/VariableContext.java (hunk 6 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/context/VariableContext.java]: Removed in d3e7d2d557259712428f4f178b8d6bfd67325435

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/types/VariableDeclarationSnippet.java [hunk 11]
```diff
@@ -106,4 +107,12 @@ private void addIdentifier(Token token) {
             foundVariableIdentifiers.add(new QuotedIdentifier(unescapedIdentifier));
         }
     }
+
+    /**
+     * Returns syntax node kind.
+     */
+    public SyntaxKind getSyntaxKind() {
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/types/VariableDeclarationSnippet.java:114]: This is somewhat misleading. Since the syntax kind returned here is not the syntax kind of the variable decl itself. Instead of doing this, how about changing this method to return whether this var decl is declared using `var` or not? e.g., `isDeclaredWithVar()`

Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/types/VariableDeclarationSnippet.java]: Updated in a67b26d2ae21b4ddcd565b9584468933ead64dc1

**Review by pubudu91 — APPROVED** [review]
