### PR TITLE
Fix the nodes which have incorrect field in node transformer

### LINKED ISSUE #23905: Some nodes have incorrect field in node transformer
**Description:**
Some nodes which are transformed by the NodeTransformer have incorrect fields or some fields are missing.

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose
$subject

Fixes #23905 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STTreeModifier.java [hunk 1]
```diff
@@ -2257,6 +2238,7 @@ protected STNode transformSyntaxNode(STNode node) {
         if (node == null) {
             return null;
         }
+        // TODO
         return (T) node.apply(this);
```
Comment (KavinduZoysa) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STTreeModifier.java:2242]: The diff shown in this file is generated automatically

**Comment by KavinduZoysa** [comment]
> I have added the wait actions in a different way in this pr #23969. I also enabled the tests so its guaranteed that approach works.
> 
> Shall we go ahead with that?

+1, I will discard that change and update the PR
