### PR TITLE
[Master] Fix Incomplete code sample causes CCE in VariableDeclarationNode.java

### LINKED ISSUE #34486: Incomplete code sample causes CCE in `VariableDeclarationNode.java`
**Description:**
Below sample causes CCE in `VariableDeclarationNode.java` (Note the extra comma after `g` int the error binding pattern)
```bal
public function main() {
    [error, boolean...] [error(g,), ...j] = [error("error!"), true];
}
```
<details>
  <summary>Stack trace.(Click to expand)</summary>

```
[Error - 10:52:46 AM] Operation 'ballerinaDocument/executorPositions' failed! {uri: '/home/dulmina/Documents/test.bal', error: 'class io.ballerina.compiler.syntax.tree.IndexedExpressionNode cannot be cast to class io.ballerina.compiler.syntax.tree.TypedBindingPatternNode (io.ballerina.compiler.syntax.tree.IndexedExpressionNode and io.ballerina.compiler.syntax.tree.TypedBindingPatternNode are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.IndexedExpressionNode cannot be cast to class io.ballerina.compiler.syntax.tree.TypedBindingPatternNode (io.ballerina.compiler.syntax.tree.IndexedExpressionNode and io.ballerina.compiler.syntax.tree.TypedBindingPatternNode are in unnamed module of loader 'app')
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.typedBindingPattern(VariableDeclarationNode.java:45)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2770)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:472)
	at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.generateAndAddBLangStatements(BLangNodeBuilder.java:4960)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1541)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:472)
	at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.populateFunctionNode(BLangNodeBuilder.java:1448)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createFunctionNode(BLangNodeBuilder.java:1428)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1406)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:472)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:606)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:472)
	at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.accept(BLangNodeBuilder.java:505)
	at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:111)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:424)
	at io.ballerina.projects.ModuleCompilationState$3.compile(ModuleCompilationState.java:100)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:103)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:141)
	at org.ballerinalang.langserver.extensions.ballerina.document.ExecutorPositionsUtil.getExecutorPositions(ExecutorPositionsUtil.java:75)
	at org.ballerinalang.langserver.extensions.ballerina.document.BallerinaDocumentService.lambda$executorPositions$15(BallerinaDocumentService.java:392)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
</details>

### PR DESCRIPTION
**Pull request by SasinduDilshara**
Fixes #34486
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/38148

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by KavinduZoysa — DISMISSED** [review]

**Comment by rdulmina** [comment]
Due to some reason Files Changed page is unresponsive hence adding the comment here. The fix is not correct we need to check why we not getting a binding pattern from `parseTypedBindingPatternOrMemberAccess`. The error handler should insert a variable name after the `,`

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -16843,7 +16843,18 @@ private STNode parseTypedBindingPatternTypeRhs(STNode typeDesc, ParserRuleContex
             case OPEN_BRACKET_TOKEN:
                 // T[..] ..
                 STNode typedBindingPattern = parseTypedBindingPatternOrMemberAccess(typeDesc, true, true, context);
-                assert typedBindingPattern.kind == SyntaxKind.TYPED_BINDING_PATTERN;
+                if (typedBindingPattern.kind != SyntaxKind.TYPED_BINDING_PATTERN) {
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:16846]: The fix is not correct we need to check why we not getting a binding pattern from `parseTypedBindingPatternOrMemberAccess`. The error handler should insert a variable name after the `,`

**Review by rdulmina — CHANGES_REQUESTED** [review]

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 1 above)
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:16846]: Yes. The current fix is not appropriate. We need to fix two places. 
1. https://github.com/ballerina-platform/ballerina-lang/blob/6b312cf275684f538aaed692d83c85937dd5b788/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java#L17442-L17446
Here when the `isTypedBindingPattern = true`, the member cannot be an expression for sure. 
So we need to do following check in `ERROR_CONSTRUCTOR` switch case immediately. 
```java
if (isTypedBindingPattern) {
    return SyntaxKind.LIST_BINDING_PATTERN;
}
```

2. https://github.com/ballerina-platform/ballerina-lang/blob/6b312cf275684f538aaed692d83c85937dd5b788/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java#L17847-L17848
Here getBindingPattern() validation seem to be missing. It has to be `memberList.add(getBindingPattern(member, true));`

**Review by lochana-chathura — CHANGES_REQUESTED** [review]

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 1 above)
Comment (SasinduDilshara) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java]: Updated

File: compiler/ballerina-parser/src/test/resources/statements/assignment-stmt/assignment_stmt_source_15.bal [hunk 2]
```diff
@@ -0,0 +1,3 @@
+function foo() {
+    [error, boolean...] [error(g, ), ...j] = [error("error!"), true];
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/resources/statements/assignment-stmt/assignment_stmt_source_15.bal:2]: This is not an [assignment-stmt](https://ballerina.io/spec/lang/master/#assignment-stmt). This is a [local-var-decl-stmt](https://ballerina.io/spec/lang/master/#local-var-decl-stmt). Since the problem was in the binding pattern recovery shall we move those test cases to `TypedBindingPatternsTest`?

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal [hunk 3]
```diff
@@ -152,3 +152,10 @@ function testOptionalFieldAssignment() {
     Topt t = {a: 2, c: [{b: 4}]};
     (t.c)[0].b = (); // error
 }
+
+function testInvalidErrorConstructorAssignment() {
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal:156]: Let's move this to a relevant class.

File: compiler/ballerina-parser/src/test/resources/statements/assignment-stmt/assignment_stmt_source_15.bal (hunk 2 above)
Comment (SasinduDilshara) [reply compiler/ballerina-parser/src/test/resources/statements/assignment-stmt/assignment_stmt_source_15.bal]: Updated

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal (hunk 3 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal]: Updated

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypedBindingPatternsTest.java [hunk 4]
```diff
@@ -116,6 +116,14 @@ public void testErrorBindingPatternInLetVarDecl() {
                 "typed-binding-patterns/typed_binding_patterns_assert_21.json");
     }
 
+    @Test
+    public void testErrorBindingPatternInLocalVarDecl() {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypedBindingPatternsTest.java:120]: Since this is an invalid syntax test, we need to add it under the "// Recovery tests" section. Let's add the new test at the very end. Since this is not directly an error binding pattern test, shall we make the test case name, `testErrorBindingPatternInsideListBindingPatternRecovery()`?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java [hunk 5]
```diff
@@ -439,7 +439,21 @@ public void testNegativeTupleVariables() {
                 "but found 'Ints'", 128, 5);
         BAssertUtil.validateError(resultNegative, ++i, "invalid list binding pattern: expected an array or a tuple, " +
                 "but found 'IntsOrStrings'", 129, 5);
-
+        BAssertUtil.validateError(resultNegative, ++i, "invalid list binding pattern; " +
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java:442]: Since syntax errors have a lot of diagnostics better not to mix them with negative semantic tests. (to mitigate readability and maintainability issues)
Shall we add this as a separate test. Say `testTupleVarDefnSyntaxNegative()`?

Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java]: Updated. cdc2ba9492ac40f5768731f83dd248276af7bf08

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypedBindingPatternsTest.java (hunk 4 above)
Comment (SasinduDilshara) [reply compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypedBindingPatternsTest.java]: Updated cdc2ba9492ac40f5768731f83dd248276af7bf08.

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypedBindingPatternsTest.java [hunk 6]
```diff
@@ -181,4 +181,14 @@ public void testListBindingPatternWithFieldBidingPatternMembers() {
         testFile("typed-binding-patterns/typed_binding_patterns_source_27.bal",
                 "typed-binding-patterns/typed_binding_patterns_assert_27.json");
     }
+
+    // Recovery tests
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypedBindingPatternsTest.java:185]: We have this in L125.
```suggestion
```

Comment (SasinduDilshara) [reply compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/misc/TypedBindingPatternsTest.java]: Updated

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java [hunk 7]
```diff
@@ -38,12 +38,14 @@
...
 public class TupleVariableDefinitionTest {
 
-    private CompileResult result, resultNegative;
+    private CompileResult result, resultNegative, tupleVarDefnSyntaxNegative;
 
     @BeforeClass
     public void setup() {
         result = BCompileUtil.compile("test-src/statements/variabledef/tuple-variable-definition.bal");
         resultNegative = BCompileUtil.compile("test-src/statements/variabledef/tuple-variable-definition-negative.bal");
+        tupleVarDefnSyntaxNegative = BCompileUtil
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java:47]: Please reassign this to null at @AfterClass. We once had an OOM issue as we holding the references

**Comment by lochana-chathura** [comment]
Please sync the PR with the master since the last sync was done in February.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java (hunk 7 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/variabledef/TupleVariableDefinitionTest.java:47]: Will update

**Comment by SasinduDilshara** [comment]
> Please re-sync the PR with the master since the last sync was done in February.

updated.

**Review by lochana-chathura — APPROVED** [review]

**Review by rdulmina — APPROVED** [review]
