### PR TITLE
Fix issue in BLangIsLikeExpr

### LINKED ISSUE #25346: Misbehavior in BLangIsLikeExpr
**Description:**
BLangIsLikeExpr is evaluated as false for tuple type with rest type.

ex:
v = [1,2,3,4,5];
v isLike [int, int, ...any] => false;

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose
Fixes #25346 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java [hunk 1]
```diff
@@ -1982,26 +1982,41 @@ private static boolean checkIsLikeTupleType(Object sourceValue, BTupleType targe
...
 
+        List<BType> targetTypes = new ArrayList<>(targetType.getTupleTypes());
+        if (targetType.getRestType() != null) {
+            if (source.size() <= targetTypes.size()) {
+                return false;
+            } else {
+                int targetTypeSize = source.size() - targetTypes.size();
+                for (int i = 0; i < targetTypeSize; i++) {
+                    targetTypes.add(targetType.getRestType());
+                }
```
Comment (pubudu91) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:1997]: Instead of doing this, how about just setting the bound size to the target type and then later, check the remainder of the source type members against the rest type?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java [hunk 2]
```diff
@@ -1982,26 +1982,41 @@ private static boolean checkIsLikeTupleType(Object sourceValue, BTupleType targe
...
+        if (targetType.getRestType() == null && source.size() != targetType.getTupleTypes().size()) {
             return false;
         }
 
+        List<BType> targetTypes = new ArrayList<>(targetType.getTupleTypes());
+        if (targetType.getRestType() != null) {
+            if (source.size() <= targetTypes.size()) {
+                return false;
+            } else {
+                int targetTypeSize = source.size() - targetTypes.size();
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:1994]: We can remove the else block and move this out?

```suggestion
            }
            
            int targetTypeSize = source.size() - targetTypes.size();
```

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java [hunk 3]
```diff
@@ -1982,26 +1982,41 @@ private static boolean checkIsLikeTupleType(Object sourceValue, BTupleType targe
...
+                for (int i = 0; i < targetTypeSize; i++) {
+                    targetTypes.add(targetType.getRestType());
+                }
+            }
+        } else {
+            if (source.size() != targetType.getTupleTypes().size()) {
+                return false;
+            }
+        }
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:2003]:
```suggestion
        } else if (source.size() != targetType.getTupleTypes().size()) {
            return false;            
        }
```

File: tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal [hunk 4]
```diff
@@ -131,3 +131,29 @@ function testAnyJsonTypes() returns [boolean, boolean, boolean, boolean] {
 
     return [aa is json, bb is json, dd is json, ff is json];
 }
+
+function testIsLike1() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal:135]: Can we rename this to reflect what's being tested?

e.g.,
```suggestion
function testIsLikeForTupleWithRestDescriptor() {
```

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java (hunk 1 above)
Comment (KavinduZoysa) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java]: Changed

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java (hunk 2 above)
Comment (KavinduZoysa) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java]: Changed

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java (hunk 3 above)
Comment (KavinduZoysa) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java]: Changed

File: tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal (hunk 4 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal]: Done

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java [hunk 5]
```diff
@@ -1982,26 +1982,43 @@ private static boolean checkIsLikeTupleType(Object sourceValue, BTupleType targe
...
-        if (source.size() != targetType.getTupleTypes().size()) {
+        List<BType> targetTypes = new ArrayList<>(targetType.getTupleTypes());
+        int sourceTypeSize = source.size();
+        int targetTypeSize = targetTypes.size();
+        BType targetRestType = targetType.getRestType();
+
+        if (targetRestType == null && sourceTypeSize != targetTypeSize) {
+            return false;
+        }
+        if (targetRestType != null && sourceTypeSize <= targetTypeSize) {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:1993]: Why do we return false when sourceTypeSize == targetTypeSize ?

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:1993]: The following shouldn't panic.

```ballerina
public function main() {
    [anydata, anydata] x = [1, 2];
    any a = x.cloneReadOnly();

    if !(a is [int, int, int...]) {
        panic error("didn't match");
    }
}
```

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java [hunk 6]
```diff
@@ -1982,26 +1982,43 @@ private static boolean checkIsLikeTupleType(Object sourceValue, BTupleType targe
...
-                if (!checkIsType(elementType, targetType.getTupleTypes().get(i), new ArrayList<>())) {
-                    return false;
-                }
-            } else {
-                if (!checkIsLikeType(source.getRefValue(i), targetType.getTupleTypes().get(i), unresolvedValues,
-                        allowNumericConversion)) {
-                    return false;
-                }
+        for (int i = 0; i < targetTypeSize; i++) {
+            if (!checkTupleElementType(getArrayElementType(source, i), targetTypes.get(i), source.getRefValue(i),
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:1998]: Why do we have to use special methods `checkTupleElementType` and `getArrayElementType` here and in the next for loop? 

Can't (shouldn't) we directly call 
`checkIsLikeType(source.getRefValue(i), targetTypes.get(i), unresolvedValues, allowNumericConversion)`?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java [hunk 7]
```diff
@@ -1982,26 +1982,43 @@ private static boolean checkIsLikeTupleType(Object sourceValue, BTupleType targe
...
+                return false;
             }
         }
         return true;
+    }
 
+    private static boolean checkTupleElementType(BType sourceElementType, BType targetElementType,
+                                                 Object sourceRefValue, List<TypeValuePair> unresolvedValues,
+                                                 boolean allowNumericConversion) {
+        if (BTypes.isValueType(sourceElementType)) {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:2016]: There's also an issue with this check that results in calling `checkIsType`.

The following panics even though it shouldn't because the immutable list `[1, 2]` belongs to `[byte, byte]`.

```ballerina
public function main() {
    [int, int] x = [1, 2];
    any a = x.cloneReadOnly();

    if !(a is [byte, byte]) {
        panic error("didn't match");
    }
}
```

Comment (KavinduZoysa) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java]: Fixed.

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java (hunk 6 above)
Comment (KavinduZoysa) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java]: Changed.

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java (hunk 5 above)
Comment (KavinduZoysa) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java]: Changed.

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java [hunk 8]
```diff
@@ -1982,26 +1982,43 @@ private static boolean checkIsLikeTupleType(Object sourceValue, BTupleType targe
         }
 
         ArrayValue source = (ArrayValue) sourceValue;
-        if (source.size() != targetType.getTupleTypes().size()) {
+        List<BType> targetTypes = new ArrayList<>(targetType.getTupleTypes());
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:1985]: It is added, because `targetType.getTupleTypes()` is used several times in the method.

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java [hunk 9]
```diff
@@ -1982,41 +1982,29 @@ private static boolean checkIsLikeTupleType(Object sourceValue, BTupleType targe
...
+        int sourceTypeSize = source.size();
+        int targetTypeSize = targetTypes.size();
+        BType targetRestType = targetType.getRestType();
+
+        if (targetRestType == null && sourceTypeSize != targetTypeSize) {
+            return false;
+        }
+        if (targetRestType != null && sourceTypeSize < targetTypeSize) {
             return false;
         }
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:1995]: Isn't it definitely an error if `sourceTypeSize < targetTypeSize` irrespective of whether or not there is a rest descriptor? Shouldn't we check that and return false as the first check?

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:1995]: I guess we can then do 
```suggestion
        if (sourceTypeSize < targetTypeSize) {
            return false;
        }
        
        if (targetRestType == null && sourceTypeSize > targetTypeSize) {
            return false;
        }
```

File: tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal [hunk 10]
```diff
@@ -131,3 +131,37 @@ function testAnyJsonTypes() returns [boolean, boolean, boolean, boolean] {
...
+
+    anydata k7 = [1, "str", true, "str"];
+    anydata k8 = k7.cloneReadOnly();
+    assertEquals(k8 is [int, int, anydata...], false);
+
+    [anydata, anydata] k9 = [1, 2];
+    anydata k10 = k9.cloneReadOnly();
+    assertEquals(k10 is [int, int, int...], true);
+
+    [int, int] k11 = [1, 2];
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal:156]: Shouldn't this be in a different test since there's no rest descriptor here?

File: tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal [hunk 11]
```diff
@@ -131,3 +131,37 @@ function testAnyJsonTypes() returns [boolean, boolean, boolean, boolean] {
 
     return [aa is json, bb is json, dd is json, ff is json];
 }
+
+function testIsLikeForTupleWithRestDescriptor() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal:135]: Shall we also add tests for where the source size is less than the target tuple member size?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java]: Yes, changed

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java (hunk 9 above)
Comment (KavinduZoysa) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java]: That is correct, changed.

File: tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal (hunk 11 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal:135]: Added

File: tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal (hunk 10 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/jvm/type-test-expr.bal]: Yes, changed

**Review by MaryamZi — APPROVED** [review]
