### PR TITLE
Fix incorrect formatting with BlockStatementNodes

### LINKED ISSUE #32963: If clause indentation is not context sensitive
**Description:**
$title. Consider the following screen capture.

https://user-images.githubusercontent.com/1329674/135229100-0b04b902-64c9-4b76-ad6b-44fbab230503.mp4

Being aware of the context, the formatter should not always preserve the user's indentation. This can be seen for all the block based nodes. For example, `foreach`, `while` and etc.

**Steps to reproduce:**

**Affected Versions:**
SwanLake-Beta3 at least

### PR DESCRIPTION
**Pull request by AzeemMuzammil**
Fixes #32963

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [x] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 1]
```diff
@@ -4261,6 +4267,15 @@ private int getPreservedIndentation(Token token) {
         return position;
     }
 
+    /**
+     * Set the flag for setting preserve new line for currently formatting token.
+     *
+     * @param value boolean true for setting new line.
+     */
+    private void preserveNewline(boolean value) {
```
Comment (NipunaRanasinghe) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:4275]: How about `setPreserveNewline()` as this seems more like a setter method? WDYT?

**Review by NipunaRanasinghe — APPROVED** [review]
Approved with a minor suggestion

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM
