### PR TITLE
Disable multi-module code coverage

### LINKED ISSUE #26431: NoSuchFileException when generating code coverage
**Description:**
$subject, module name with a dot

https://github.com/ballerina-platform/module-ballerina-java.jdbc/runs/1280724516

### PR DESCRIPTION
**Pull request by Ibaqu**
## Purpose
Disable multi-module coverage for modules with 'dot .'
Fixes 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java [hunk 1]
```diff
@@ -131,7 +131,8 @@ private void createReport(final IBundleCoverage bundleCoverage) {
                     // Extract the Module name individually for each source file
                     // This is done since some source files come from other modules
                     // sourceFileCoverage : "<orgname>/<moduleName>:<version>
-                    String sourceFileModule = sourceFileCoverage.getPackageName().split("/")[1];
+                    String sourceFileModule = sourceFileCoverage.getPackageName().split("/")[1]
+                            .replace("_", ".");
```
Comment (Dilhasha) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java:135]: What's the behavior if the module name contains "_"?

**Review by Dilhasha — APPROVED** [review]
Approved as a temporary fix
