### PR TITLE
Fix use of binding patterns in closures

### LINKED ISSUE #40615: [Bug]: Destructured value becomes nil when used as captured variable to function-typed argument
### Description

$title.

### Steps to Reproduce

Compared

```ballerina
import ballerina/io;

public function main() {
    f1();
    f2();
}

function f1() {
    string[] values = ["a", "b", "c"];
    map<int> data = {
        a: 1
    };

    foreach var [k, _] in data.entries() {
        string name = k;
        io:println(<any> k is ()); // becomes true
        io:println(k.toBalString());
        io:println(name.toBalString());
        io:println(values.filter(item => item == k));
    }
}

function f2() {
    string[] values = ["a", "b", "c"];
    map<int> data = {
        a: 1
    };

    foreach var [k, _] in data.entries() {
        string name = k;
        io:println(<any> k is ()); // false
        io:println(k.toBalString());
        io:println(name.toBalString());
        io:println(values.filter(item => item == name));
    }
}
```

The only difference in code is `values.filter(item => item == k)` vs `values.filter(item => item == name)`.

Output is

```cmd
true
()
()
[]
false
"a"
"a"
["a"]
```

### Affected Version(s)

2201.6.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #41236: [Bug]: NPE when a variable from a structured binding pattern is used in an anonymous function expression
### Description

$title.

### Steps to Reproduce

```ballerina
type Doctor record {
    string name;
    string category;    
};

function addDoctor(Doctor doctor, string[] categories) returns error? {
    var {category} = doctor; // also getting an unused variable warning
    if !categories.some(
        existingCategory => existingCategory == category) {
        
    }
}
```

or

```ballerina
type Doctor record {
    string name;
    string category;    
};

function addDoctor(Doctor doctor, string[] categories) returns error? {
    var {category} = doctor; // also getting an unused variable warning
    if !some(categories, existingCategory => existingCategory == category) {
        
    }
}

function some(string[] arr, function (string s) returns boolean func) returns boolean {
    foreach string item in arr {
        if func(item) {
            return true;
        }
    }
    return false;
}
```

```cmd
[2023-08-18 09:22:48,015] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.getJVMIndexOfVarRef(JvmInstructionGen.java:1323)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.loadVar(JvmInstructionGen.java:2141)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateFPLoadIns(JvmInstructionGen.java:1760)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateInstructions(JvmInstructionGen.java:2336)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmCodeGenUtil.getLastScopeFromBBInsGen(JvmCodeGenUtil.java:591)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:558)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:274)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:175)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:433)
        at java.base/java.util.HashMap.forEach(HashMap.java:1337)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:388)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:800)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:101)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:72)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:321)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:480)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:173)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:142)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:120)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:172)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:119)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:288)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:56)
```

### Affected Version(s)

2201.7.1

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #41832: [Bug]: Compilation Error about query expressions, tuple arrays and spread operator
### Description

While doing day 3 of the advent of code in Ballerina I got a compile error:
```
Compiling source
        fschn/aoc2023:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-12-05 19:45:08,526] SEVERE {b7a.log.crash} - Cannot read field "name" because "varDcl" is null 
java.lang.NullPointerException: Cannot read field "name" because "varDcl" is null
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.getJVMIndexOfVarRef(JvmInstructionGen.java:1369)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.loadVar(JvmInstructionGen.java:2184)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateFPLoadIns(JvmInstructionGen.java:1803)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateInstructions(JvmInstructionGen.java:2385)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmCodeGenUtil.getLastScopeFromBBInsGen(JvmCodeGenUtil.java:596)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:623)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:341)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:182)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:425)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:384)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:793)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:101)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:72)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:325)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:480)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:174)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:143)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:121)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:176)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:120)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:288)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

### Steps to Reproduce

```ballerina
import ballerina/regex;

public function main() {
    [int, int][] points = [];
    foreach [int, string] [y,line] in ["abc", "def"].enumerate() {
        [int, int][] tmp = from [int, string] [x, char] in regex:split(line, "").enumerate() select [x, y];
        points.push(...tmp);
    }
}
```

### Affected Version(s)

Swan Lake Update 7 and Swan Lake Update 8.4

### OS, DB, other environment details and versions

Docker image "ballerina/ballerina-devcontainer:2201.7.0" on Windows

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #41858: [Bug]: NPE when a variable from a list binding pattern is used in an anonymous function expression
### Description

$title.
```ballerina
public function main() {
    [int, string] [id, name] = getDetails();
    var addCategory = function() {
        _ = id;
    };
}

function getDetails() returns [int, string] {
    return [1234, "chiranS"];
}

```

Compiler crash with 
```
Compiling source
        test.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-12-11 11:56:10,235] SEVERE {b7a.log.crash} - Cannot read field "name" because "varDcl" is null 
java.lang.NullPointerException: Cannot read field "name" because "varDcl" is null
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.getJVMIndexOfVarRef(JvmInstructionGen.java:1368)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.loadVar(JvmInstructionGen.java:2183)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateFPLoadIns(JvmInstructionGen.java:1802)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateInstructions(JvmInstructionGen.java:2384)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmCodeGenUtil.getLastScopeFromBBInsGen(JvmCodeGenUtil.java:591)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:554)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:273)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:174)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:424)
        at java.base/java.util.HashMap.forEach(HashMap.java:1429)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:383)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:792)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:101)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:72)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:321)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:480)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:387)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:173)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:142)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:120)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:176)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:119)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:201)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:223)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

### Steps to Reproduce

_No response_

### Affected Version(s)

2201.8.4

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/41236

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by poorna2152**
## Purpose
Fixes #41236 
Fixes #41832 
Fixes #41858 
Fixes #40615 

## Approach
For mapping/tuple binding patterns a block is created in the desugar phase and the variable definitions by the are defined inside this newly created block. Thus these variables are omitted from the map that is passed to the lambda function created from the closure. In the fix when a generated block from the desugar phase is identified using the `internal` flag and when the internal flag is present the variable definitions are attached to the parent of the block node created. 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java [hunk 1]
```diff
@@ -746,7 +748,13 @@ public void visit(BLangSimpleVariableDef varDefNode) {
...
      */
     private BLangAssignment createAssignmentToClosureMap(BLangSimpleVariableDef varDefNode) {
-        BVarSymbol mapSymbol = createMapSymbolIfAbsent(env.node, blockClosureMapCount);
+        BVarSymbol mapSymbol;
+        BLangNode node = env.node;
+        if (node.getKind() == NodeKind.BLOCK && node.internal) {
+            mapSymbol = createMapSymbolIfAbsent(node.parent, blockClosureMapCount);
+        } else {
+            mapSymbol = createMapSymbolIfAbsent(node, blockClosureMapCount);
+        }
```
Comment (nipunayf) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:757]:
```suggestion
        BLangNode inputNode = node.getKind() == NodeKind.BLOCK && node.internal ? node.parent : node;
        mapSymbol = createMapSymbolIfAbsent(inputNode, blockClosureMapCount);
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithBindingPatternVarTest.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
+/*
+ *  Copyright (c) 2023, WSO2 Inc. (http://www.wso2.org).
```
Comment (nipunayf) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithBindingPatternVarTest.java:2]:
```suggestion
 *  Copyright (c) 2023, WSO2 LLC. (http://www.wso2.org).
```

**Comment by chiranSachintha** [comment]
```ballerina
type Doctor record {
    string name;
    string category;
};

function addDoctor(Doctor doctor, string[] categories) {
    var {category} = doctor;
    var addCategory = function() {
        _ = category;
    };
}
```
@poorna2152 I think it's better to resolve this in the `BIRGEN` phase. When we consider the example above, it is desugared into a block statement. Due to that, the closure map is generated within that block statement as follows
```ballerina
type Doctor record {
    string name;
    string category;
};

function addDoctor(Doctor doctor, string[] categories) {
    {. 
        map<(any|error)> $map$block$_4 =  {}
        map<(any|error)> recordVar_1 = <map<(any|error)>> doctor;
        $map$block$_4[category] = <(any|error)> <> $recordVar$_1[category]
    }
    
    var addCategory = function() {
        _ = category;
    };
}
```

In the `collectClosureMapSymbols` function(in the closure desugar), we collect the closure maps required for load lambda functions. In this case, those closure maps exist within the block statement. So we cannot identify the closure map required to load the above lambda function in the closure desugar phase.

Since we flatten the block statement in the `BIRGEN` phase, we have access to the closure map within the function scope. With that, we can use it for creating the `fpload` instruction in the `BIRGEN` phase.

**Comment by KavinduZoysa** [comment]
@poorna2152, can you resolve the conflicts and address comments?

**Comment by poorna2152** [comment]
> ```ballerina
> type Doctor record {
>     string name;
>     string category;
> };
> 
> function addDoctor(Doctor doctor, string[] categories) {
>     {
>         map<(any|error)> $map$block$_4 =  {}
>         map<(any|error)> recordVar_1 = <map<(any|error)>> doctor;
>         $map$block$_4[category] = <(any|error)> <> $recordVar$_1[category]
>     }
>     
>     var addCategory = function() {
>         _ = category;
>     };
> }
> ```

Current fix is done in the closure desugar level and this fix moves the category variable to the map defined in the function scope

```ballerina
addDoctor (Doctor doctor, string[] categories) {
    map<(any|error)> $map$block$_3 =  {}; 
    {
        map<(any|error)> $recordVar$_1 = <map<(any|error)>> doctor; 
        $map$block$_3[category] = <(any|error)> <> $recordVar$_1[category]; 
    }
    function () returns () f = LambdaRef:$lambda$_0; Return: ()
}
```

**Comment by MaryamZi** [comment]
> Since we flatten the block statement in the `BIRGEN` phase, we have access to the closure map within the function scope. With that, we can use it for creating the `fpload` instruction in the `BIRGEN` phase.

IMO, this results in the BIR gen phase having to know more about how exactly desugaring is done for these constructs and reduces independence between the phases. Additionally, ideally, code that we have after desugaring should be code that is generally valid if a user wrote it, so I would fix this at (closure) desugar itself.

**Comment by chiranSachintha** [comment]
We need to fix this for error binding pattern as well. When consider the following example it is crashed
```ballerina
type SampleErrorData record {|
    int code;
    string reason;
|};

type SampleError error<SampleErrorData>;

function getSampleError() returns SampleError {
    return error("Transaction Failure", error("Database Error"), code = 20,
                            reason = "deadlock condition");
}

public function main() {
    var error(_, cause, code = code, reason = reason) = getSampleError();
    var addCategory = function() {
        _ = code;
    };
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java [hunk 3]
```diff
@@ -691,7 +691,9 @@ private void addToFunctionMap(BLangFunction funcNode, SymbolEnv symbolEnv, int p
     @Override
     public void visit(BLangBlockStmt blockNode) {
         SymbolEnv blockEnv = SymbolEnv.createBlockEnv(blockNode, env);
-        blockClosureMapCount++;
+         if (!blockNode.internal) {
+            blockClosureMapCount++;
+         }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:696]: Is there any specific reason for doing this check? I don't think it's necessary to handle it as a special case by verifying whether that block-stmt is an internal node or not.

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query_with_binding_pattern.bal [hunk 4]
```diff
@@ -0,0 +1,144 @@
...
+    Result[][] results = from var {name, age, grades} in students
+        where age > ageLimit
+        select from var grade in grades
+            where grade < mx
+            select {
+                name: name,
+                grade: grade + bonus
+            };
+
+    assertEquality([[{"name": "Alice", "grade": 80.2}], [{"name": "Bob", "grade": 65.2}, {"name": "Bob", "grade": 75.3}], [{"name": "Charlie", "grade": 60.5}]], results);
```
Comment (heshanpadmasiri) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query_with_binding_pattern.bal:108]: Nit: Lets keep line widths roughly consistent 
```suggestion
    assertEquality([[{"name": "Alice", "grade": 80.2}],
                    [{"name": "Bob", "grade": 65.2}, {"name": "Bob", "grade": 75.3}],
                    [{"name": "Charlie", "grade": 60.5}]],
                   results);

```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/AnonymousClosedRecordTest.java [hunk 5]
```diff
@@ -75,6 +75,11 @@ public void anonymousRecordWithTypeInclusion() {
         BRunUtil.invoke(compileResult, "anonymousRecordWithTypeInclusion");
     }
 
+    @Test(description = "Test record type with binding pattern var in default value", enabled = false)
```
Comment (nipunayf) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/AnonymousClosedRecordTest.java:78]: Do we have a comment and a separate issue to track on why this test being disabled?

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query_with_binding_pattern.bal [hunk 6]
```diff
@@ -0,0 +1,144 @@
...
+        name: result.name,
+        grade: newMarks
+    };
+
+    assertEquality([{"name": "Alex", "grade": 85.0}, {"name": "Ranjan", "grade": 95.0}], topList);
+}
+
+const ASSERTION_ERROR_REASON = "AssertionError";
+
+function assertEquality(anydata expected, anydata actual) {
```
Comment (nipunayf) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query_with_binding_pattern.bal:137]: Please double-check the usages of this function since in some cases, the parameters are swapped. IMO, it's better to use the following function signature.

```suggestion
function assertEquality(anydata actual, anydata expected) {
```

 I know there are inconsistencies in how we define this function signature, but this notation is more prevalent as it is used in both TestNG and Testerina.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java (hunk 3 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:696]: We no longer need to create a blockClosureMap for an internal block that we created. In the case of a internal block node we created the closure variables would be attached to the parent of the created block.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/AnonymousClosedRecordTest.java (hunk 5 above)
Comment (poorna2152) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/AnonymousClosedRecordTest.java]: It was a mistake

File: tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal [hunk 7]
```diff
@@ -667,6 +667,17 @@ public function testWorkerWithQuery() {
...
+    record {|string name;|} rec = {name: "name"};
+    [string] [colon] = [";"];
+    var {name} = rec;
+
+    worker A returns string {
+        return name + colon;
+    }
+    string _ = wait A;
+}
+
```
Comment (SasinduDilshara) [inline tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal:680]: It is better to add a test with destructuring nested records.
(example- destructuring B)
```
type A record {
     string a = "";
};

type B record {
    A a1;
    string a2 = "";
};
```

Comment (poorna2152) [reply tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal:680]: Have added such a test [here](https://github.com/poorna2152/ballerina-lang/blob/fix_-41236/tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal#L830).

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java (hunk 3 above)
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:696]: Formatting seems off.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java [hunk 8]
```diff
@@ -746,7 +748,9 @@ public void visit(BLangSimpleVariableDef varDefNode) {
      * @return assignment statement created
      */
     private BLangAssignment createAssignmentToClosureMap(BLangSimpleVariableDef varDefNode) {
-        BVarSymbol mapSymbol = createMapSymbolIfAbsent(env.node, blockClosureMapCount);
+        BLangNode node = env.node;
+        BLangNode inputNode = node.getKind() == NodeKind.BLOCK && node.internal ? node.parent : node;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:752]: Will this work for the nested generated block case?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithBindingPatternVarTest.java [hunk 9]
```diff
@@ -0,0 +1,65 @@
...
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.DataProvider;
+import org.testng.annotations.Test;
+
+/**
+ * This contains methods to test query expressions and query actions which uses variables defined in binding patterns.
+ *
+ * @since 2201.9.0
+ */
+public class QueryWithBindingPatternVarTest {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithBindingPatternVarTest.java:34]: StructuredBindingPattern?

File: tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal [hunk 10]
```diff
@@ -813,6 +813,116 @@ function test30() {
...
+    string name;
+|};
+
+type Doctor record {
+    string name;
+    string category;
+    School school;
+};
+
+function testClosureWithStructuredBindingTypeParams() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal:826]: TypeParams mean something else in b7a, so may be confusing. Also it is not the param itself that is the reference?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 11]
```diff
@@ -1482,7 +1482,8 @@ public void visit(BLangTupleVariable varNode) {
 
         // Create tuple destruct block stmt
         final BLangBlockStmt blockStmt = ASTBuilderUtil.createBlockStmt(varNode.pos);
-
+        blockStmt.parent = env.node;
+        blockStmt.internal = true;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:1486]: I assume internal was already used in other cases and/or should be used in other cases. Did we verify and add tests for these different scenarios?

File: tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal (hunk 10 above)
Comment (poorna2152) [reply tests/jballerina-unit-test/src/test/resources/test-src/closures/closure.bal:826]: Updated to `testClosureWithStructuredBindingVars`

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithBindingPatternVarTest.java [hunk 12]
```diff
@@ -0,0 +1,65 @@
+/*
+ *  Copyright (c) 2023, WSO2 LLC. (http://www.wso2.org).
+ *
+ *  WSO2 Inc. licenses this file to you under the Apache License,
```
Comment (dulajdilshan) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithBindingPatternVarTest.java:4]:
```suggestion
 *  WSO2 LLC. licenses this file to you under the Apache License,
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java [hunk 13]
```diff
@@ -746,8 +746,11 @@ public void visit(BLangSimpleVariableDef varDefNode) {
      * @return assignment statement created
      */
     private BLangAssignment createAssignmentToClosureMap(BLangSimpleVariableDef varDefNode) {
-        BVarSymbol mapSymbol = createMapSymbolIfAbsent(env.node, blockClosureMapCount);
-
+        int absoluteLevel = findResolvedLevel(env, varDefNode.var.symbol);
+        BVarSymbol mapSymbol = findClosureMapSymbol(absoluteLevel);
+        if (mapSymbol == null) {
+            mapSymbol = createMapSymbolIfAbsent(env.node, blockClosureMapCount);
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:752]: No need of this as we check this in the L772

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java [hunk 14]
```diff
@@ -760,6 +763,20 @@ private BLangAssignment createAssignmentToClosureMap(BLangSimpleVariableDef varD
         return ASTBuilderUtil.createAssignmentStmt(varDefNode.pos, accessExpr, varDefNode.var.expr);
     }
 
+    private BVarSymbol findClosureMapSymbol(int absoluteLevel) {
+        SymbolEnv symbolEnv = env;
+        NodeKind nodeKind = symbolEnv.node.getKind();
+        BVarSymbol mapSymbol = null;
+        while (symbolEnv != null && nodeKind != NodeKind.PACKAGE) {
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:770]: In this context, the check for `symbolEnv != null` is unnecessary. In line 768, we obtain the node from `symbolEnv`. Therefore, if `symbolEnv` is null, we are unable to perform that as well.

**Review by chiranSachintha — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java [hunk 15]
```diff
@@ -760,6 +763,20 @@ private BLangAssignment createAssignmentToClosureMap(BLangSimpleVariableDef varD
...
+            if (symbolEnv.envCount == absoluteLevel) {
+                mapSymbol = createMapSymbolIfAbsent(symbolEnv.node, symbolEnv.envCount);
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:772]: Once we have assigned a value to `mapSymbol`, we can terminate the while loop.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java [hunk 16]
```diff
@@ -760,6 +760,19 @@ private BLangAssignment createAssignmentToClosureMap(BLangSimpleVariableDef varD
...
+    private BVarSymbol findClosureMapSymbol(int absoluteLevel) {
+        SymbolEnv symbolEnv = env;
+        NodeKind nodeKind = symbolEnv.node.getKind();
+        while (nodeKind != NodeKind.PACKAGE) {
+            if (symbolEnv.envCount == absoluteLevel) {
+                return createMapSymbolIfAbsent(symbolEnv.node, symbolEnv.envCount);
+            }
+            symbolEnv = symbolEnv.enclEnv;
+            nodeKind = symbolEnv.node.getKind();
+        }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:772]: Better to refactor as follows
```java
    private BVarSymbol findClosureMapSymbol(int absoluteLevel) {
        SymbolEnv symbolEnv = env;
        while ( symbolEnv.node.getKind() != NodeKind.PACKAGE) {
            if (symbolEnv.envCount == absoluteLevel) {
                return createMapSymbolIfAbsent(symbolEnv.node, symbolEnv.envCount);
            }
            symbolEnv = symbolEnv.enclEnv;
        }
        throw new IllegalStateException("Failed to find the closure symbol defined scope");
    }
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithBindingPatternVarTest.java [hunk 17]
```diff
@@ -0,0 +1,65 @@
+/*
+ *  Copyright (c) 2023, WSO2 LLC. (http://www.wso2.org).
```
Comment (chiranSachintha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryWithBindingPatternVarTest.java:2]: Please update license header as well.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java [hunk 18]
```diff
@@ -760,6 +760,19 @@ private BLangAssignment createAssignmentToClosureMap(BLangSimpleVariableDef varD
...
+        throw new IllegalStateException("Failed to find the closure symbol defined scope");
```
[the remark this answers is not in the document]
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:771]: As per the offline discussion decided to stick with the `IllegalStateException`

**Review by chiranSachintha — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/closures/ClosureTest.java [hunk 19]
```diff
@@ -271,6 +271,32 @@ public void errorConstructorWithClosureTest() {
...
+
+    @Test(description = "Test closure with a referenced variable of error binding type")
+    public void testClosureWithErrorBindingPatterns() {
+        BRunUtil.invoke(compileResult, "testClosureWithErrorBindingPatterns");
+    }
+
+    @Test(description = "Test closure with closure variable of binding patterns of foreach loop")
+    public void testClosureWithBindingPatternsInForEach() {
+        BRunUtil.invoke(compileResult, "testClosureWithBindingPatternsInForEach");
+    }
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/closures/ClosureTest.java:298]: Shall we use a data provider instead?

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/closures/ClosureTest.java:298]: Only for the new tests we are adding.

File: tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal [hunk 20]
```diff
@@ -667,6 +667,17 @@ public function testWorkerWithQuery() {
...
 
+function testBindingPatternVariablesInWorker() {
+    record {|string name;|} rec = {name: "name"};
+    [string] [colon] = [";"];
+    var {name} = rec;
+
+    worker A returns string {
+        return name + colon;
+    }
+    string _ = wait A;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal:678]: Why aren't we asserting anything?

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/workers/workers.bal:678]: Let's change the value given to the field in L671 also.

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query_with_binding_pattern.bal [hunk 21]
```diff
@@ -0,0 +1,147 @@
...
+}
+
+const ASSERTION_ERROR_REASON = "AssertionError";
+
+function assertEquality(anydata actual, anydata expected) {
+    if expected == actual {
+        return;
+    }
+
+    panic error(ASSERTION_ERROR_REASON,
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query_with_binding_pattern.bal:145]: ASSERTION_ERROR_REASON is not required. Make the description the error message.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/AnonymousClosedRecordTest.java [hunk 22]
```diff
@@ -75,6 +75,11 @@ public void anonymousRecordWithTypeInclusion() {
         BRunUtil.invoke(compileResult, "anonymousRecordWithTypeInclusion");
     }
 
+    @Test(description = "Test record type with binding pattern var in default value")
+    public void testRecordWithDefaultsFromBindingPatternVar() {
+        BRunUtil.invoke(compileResult, "recordWithDefaultsFromBindingPatternVar");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/AnonymousClosedRecordTest.java:80]: Name the test function the same as this method. Start with `test`.

**Review by chiranSachintha — APPROVED** [review]
