### PR TITLE
Fix proto tool issue when there are dependent proto files

### LINKED ISSUE #17681: [gRPC][Tool] Error when proto file contains dependent proto
**Description:**
When we try to generate ballerina code for the following proto file, It failed. 

```proto 
syntax = "proto3";

import "message.proto";

service helloWorldWithDependency {
    rpc hello(HelloRequest) returns (HelloResponse);
    rpc bye(ByeRequest) returns (ByeResponse);
}
```

Below exception occurs
```
[2019-08-12 14:55:52,521] ERROR {org.ballerinalang.launcher.Main} - String index out of range: -1 
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1960)
at org.ballerinalang.protobuf.cmd.DescriptorsGenerator.generateDependentDescriptor(DescriptorsGenerator.java:62)
at org.ballerinalang.protobuf.cmd.GrpcCmd.execute(GrpcCmd.java:171)
at java.util.Optional.ifPresent(Optional.java:159)
at org.ballerinalang.launcher.Main.main(Main.java:63)
```

### PR DESCRIPTION
**Pull request by daneshk**
## Purpose
Fix proto tool issue when there are dependent proto files

Fixes #17681

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/cmd/DescriptorsGenerator.java [hunk 1]
```diff
@@ -56,10 +58,20 @@
                 if (isWindows()) {
                     dependentFilePath = dependentFilePath.replaceAll("/", "\\\\");
                 }
+                Path protoFilePath = Paths.get(dependentFilePath).getFileName();
+                String protoFilename = protoFilePath != null ? protoFilePath.toString() : null;
```
Comment (wggihan) [inline misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/cmd/DescriptorsGenerator.java]:
```suggestion
                String protoFilename = protoFilePath == null ? null : protoFilePath.toString();
```

File: misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/cmd/DescriptorsGenerator.java [hunk 2]
```diff
@@ -56,10 +58,20 @@
...
+                if (protoFilename == null) {
```
Comment (wggihan) [inline misc/protobuf-ballerina/src/main/java/org/ballerinalang/protobuf/cmd/DescriptorsGenerator.java]: Can't we check protoFilePath is null or not and toString?

File: tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/tool/StubGeneratorTestCase.java [hunk 3]
```diff
@@ -56,24 +58,51 @@ private void setup() throws Exception {
...
+        assertEquals(((BLangPackage) compileResult.getAST()).constants.size(), 1);
+        assertEquals(((BLangPackage) compileResult.getAST()).imports.size(), 2);
+    }
+
+    @Test(description = "Test service stub generation for service definition with dependency")
+    public void testUnaryHelloWorldWithDependency() throws IllegalAccessException, ClassNotFoundException,
+            InstantiationException {
+        CompileResult compileResult = getStubCompileResult("helloWorldWithDependency.proto",
+                "helloWorldWithDependency_pb.bal");
+        assertEquals(compileResult.getDiagnostics().length, 12);
```
Comment (wggihan) [inline tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/grpc/tool/StubGeneratorTestCase.java]: Shall we add assert fail descriptions?
