### PR TITLE
[master] Fix adding strand annotation to isolated workers

### LINKED ISSUE #38483: [Bug]: Named worker strands do not run on separate threads even if the function is isolated
### Description

$title

The spec says in https://ballerina.io/spec/lang/master/#section_7.3.2
> Each named worker runs on its own new strand. The strand can run on a separate thread from the default worker if the function is isolated.

We see the `BIRFunction.annotAttachments` is empty in the functions created for the named workers even if they are inside the isolated functions.

### Steps to Reproduce

```bal
import ballerina/io;

type Person record {|
    string name;
    boolean employed;
|};

isolated function process(Person[] & readonly members, int[] & readonly quantities) {
    worker w1 {
        Person[] employedMembers = from Person p in members
            where p.employed
            select p;
        int count = employedMembers.length();
        count -> function;
    }

    int totalMemberCount = members.length();

    int memberCount = <- w1;
    io:println(string `Employed Members: ${memberCount}`);

    future<int> avgFuture = start get_average(quantities, memberCount);

    int unemployedCount = totalMemberCount - memberCount;
    io:println(string `Unemployed Members: ${unemployedCount}`);

    int avg = checkpanic wait avgFuture;
    io:println(string `Average: ${avg}`);
}

isolated function get_average(int[] & readonly quantities, int employedCount) returns int {
    int total = int:sum(...quantities);
    int avg = employedCount == 0 ? 0 : total / employedCount;
    return avg;
}

public function main() {
    Person[] & readonly members = [{name: "aaa", employed: false}, {name: "aaa", employed: true}, {name: "aaa", employed: true}];
    int[] & readonly quantities = [10, 20, 30];
    process(members, quantities);
}
```

We see though the `get_average` function contains the annotation, the `$lambda$0` function for worker `w1` does not have the annotation.

### Affected Version(s)

Ballerina 2201.2.2 (Swan Lake Update 2)

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #38483
Duplicate PR of https://github.com/ballerina-platform/ballerina-lang/pull/38652

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by lasinicl — DISMISSED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -7722,9 +7721,23 @@ public void visit(BLangTypeConversionExpr conversionExpr) {
...
+            addStrandAnnotationWithThreadAny(function.pos);
+            function.addAnnotationAttachment(this.strandAnnotAttachement);
+            BInvokableSymbol funcSymbol = function.symbol;
+            funcSymbol.addAnnotation(this.strandAnnotAttachement.annotationAttachmentSymbol);
+            funcSymbol.schedulerPolicy = SchedulerPolicy.ANY;
+        }
         result = bLangLambdaFunction;
     }
 
+    private boolean isIsolated(long flags) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:7737]: Do we need separate function here since it is used only one time and one line code?

Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:7737]: Will fix this.
