### PR TITLE
 Fix rest params in main method

### LINKED ISSUE #15597: ArrayIndexOutOfBoundsException for main function with var-args
**Description:**
$subject
**Steps to reproduce:**
Run the below main program.
```ballerina
public function main(string... args) {
}
```

Following error can be observed
```
error: invoking main method failed due to java.lang.ArrayIndexOutOfBoundsException: 0
```

### PR DESCRIPTION
**Pull request by vinok88**
Fixes #15597 

Reported https://github.com/ballerina-platform/ballerina-lang/issues/15683

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/RuntimeUtils.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+
+
+ import org.ballerinalang.jvm.TypeConverter;
+ import org.ballerinalang.jvm.types.BArrayType;
+ import org.ballerinalang.jvm.types.BType;
+ import org.ballerinalang.jvm.types.TypeTags;
+ import org.ballerinalang.jvm.values.ArrayValue;
+
+ /**
+  * Util methods required for jBallerina runtime.
```
Comment (Kishanthan) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/RuntimeUtils.java]: Version ?

Comment (vinok88) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/RuntimeUtils.java]: Fixed. Thanks.
