### PR TITLE
Fix warning msg for deprecated constructs

### LINKED ISSUE #24335: Deprecation error throws in full expression rather than actual type
**Description:**

This is reflected in Deprecation BBE. Check the error messages for line 78 and line 81.

```Logtalks
warning: .::deprecation.bal:35:5: usage of construct 'Address' is deprecated
warning: .::deprecation.bal:39:22: usage of construct 'LKA' is deprecated
warning: .::deprecation.bal:65:76: usage of construct 'Person' is deprecated
warning: .::deprecation.bal:68:5: usage of construct 'Person' is deprecated
warning: .::deprecation.bal:78:5: usage of construct 'Person' is deprecated
warning: .::deprecation.bal:78:16: usage of construct 'createPerson(Jane, Doe, Castro Street, Mountain View, USA)' is deprecated
warning: .::deprecation.bal:81:16: usage of construct 'p.getFullName()' is deprecated
```

Refer to PR: https://github.com/ballerina-platform/ballerina-distribution/pull/577
Changes introduced by this PR needs to be amended after the proper fix.

**Steps to reproduce:**
Please run Deprecation BBE in new parser.

**Affected Versions:**
jBallerina 2.0.0-Preview1-M6

**OS, DB, other environment details and versions:**
macOS Cataline

**Suggested Labels (optional):**
Area/Language,Type/Bug

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
Fix warning msg for deprecated constructs using full expressions

Fixes  #24335

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by KavinduZoysa** [comment]
Can you check whether [this line](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java#L3137) is correct or wrong?

**Comment by rdulmina** [comment]
> @rdulmina, can you check whether [this line](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java#L3137) is correct or wrong?

Yes, that line is correct. It is for deprecated var refs eg: `usage of deprecated constants`. I basically went through all the usages and updated the places where it can give wrong warning msgs.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java [hunk 1]
```diff
@@ -597,8 +597,8 @@ public void testDeprecatedWarningForIsReadOnly() {
         CompileResult result = BCompileUtil.compile(
                 "test-src/expressions/builtinoperations/is_readonly_deprecated_warning.bal");
         int index = 0;
-        validateWarning(result, index++, "usage of construct 'x.isReadOnly(x)' is deprecated", 22, 9);
-        validateWarning(result, index++, "usage of construct 'value:isReadOnly(x)' is deprecated", 24, 17);
+        validateWarning(result, index++, "usage of construct 'isReadOnly' is deprecated", 22, 9);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java:600]: Can we include more information about the construct here? Like a qualified name instead of just the name?

e.g., `ballerina/lang.value:isReadOnly`

For object methods it may have to be like `Obj.method`.

For anonymous object methods we can probably give only the method name though.

Comment (rdulmina) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java]: Updated

**Review by gimantha — APPROVED** [review]
LGTM
