### PR TITLE
Fix "NPE in 2201.3.0 SNAPSHOT when building nballerina"

### LINKED ISSUE #38350: [Bug]: NPE in 2201.3.0 SNAPSHOT when building nballerina
### Description

```
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.LambdaGen.genNonVirtual(LambdaGen.java:122)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.LambdaGen.handleFpLambda(LambdaGen.java:233)
	at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.LambdaGen.generateLambdaMethod(LambdaGen.java:109)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:453)
	at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1040)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:399)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:810)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:96)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:71)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:310)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:500)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:408)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:168)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:278)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### Steps to Reproduce

Download ballerina pack from https://github.com/ballerina-platform/ballerina-distribution/actions/runs/3295221634
Checkout nballerina repo (current commit is 0c99501)
Try to build nballerina with above pack

### Affected Version(s)

ballerina-2201.3.0-SNAPSHOT-swan-lake

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by gimantha**
Fixes #38350

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by chiranSachintha — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ParameterDesugar.java [hunk 1]
```diff
@@ -516,7 +516,7 @@ private BLangExpression createClosureForDefaultValue(String closureName, String
                                                          BLangSimpleVariable varNode) {
         BSymbol owner = getOwner(env);
         BInvokableTypeSymbol symbol = (BInvokableTypeSymbol) env.node.getBType().tsymbol;
-        BLangFunction function = createFunction(closureName, varNode.pos, symbol.pkgID, owner, varNode.getBType());
+        BLangFunction function = createFunction(closureName, varNode.pos, owner.pkgID, owner, varNode.getBType());
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ParameterDesugar.java:519]: This change is. not required, but as a workaround for https://github.com/ballerina-platform/ballerina-lang/issues/38412, this change was done
