### PR TITLE
Fix native build for single files

### LINKED ISSUE #37608: GraalVM Native Image Compilation for Build Command
### Description

Improve the build command with a new flag `--native` to the `build` command that takes the built jar file and uses the GraalVM's Native Image command to generate a lightweight counterpart.

### Describe your problem(s)

_No response_

### Describe your solution(s)

_No response_

### Labels

DevTools

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Ibaqu**
Fixes #37608 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CreateNativeImageTask.java [hunk 1]
```diff
@@ -62,35 +61,23 @@ public void execute(Project project) {
...
             Path sourceRootParent = Optional.of(project.sourceRoot().toAbsolutePath().getParent()).orElseThrow();
             nativeDirectoryPath = sourceRootParent.resolve("native");
             nativeImageName = Optional.of(sourceRootParent.getFileName()).orElseThrow().toString();
+            executablePath = getExecutablePath(project);
         } else {
-            nativeDirectoryPath = target.path().toAbsolutePath().resolve("native");
-            nativeImageName = project.currentPackage().packageName().toString();
+            Target target;
+            try {
+                target = new Target(project.targetDir());
```
Comment (azinneera) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CreateNativeImageTask.java:74]: Are we creating the native image in a temporary location?

Comment (Ibaqu) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CreateNativeImageTask.java:74]: No this section is not for the single file projects.  We are special casing the Single file project so that the naitve image is generated into a 'native' directory in the source root

**Review by TharmiganK — APPROVED** [review]
