### PR TITLE
Fix appending additional newline after formatting

### LINKED ISSUE #26002: A extra newline gets added every-time the code is formatted
**Description:**
Sample code
```ballerina
public function main() {
}
```
Output after formatting the code for five (5) times: 
```ballerina
public function main() {

}





```

Note the extra 5 newlines at the end of the file.

### PR DESCRIPTION
**Pull request by SupunS**
## Purpose

Fixes #26002

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java [hunk 1]
```diff
@@ -528,7 +528,7 @@ void setClientCapabilities(LSClientCapabilities clientCapabilities) {
                 String formattedSource = Formatter.format(syntaxTree).toSourceCode();
 
                 LinePosition eofPos = syntaxTree.rootNode().lineRange().endLine();
-                Range range = new Range(new Position(0, 0), new Position(eofPos.line(), eofPos.offset()));
+                Range range = new Range(new Position(0, 0), new Position(eofPos.line() + 1, eofPos.offset()));
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java:531]: is this the correct place to `+1` the range? Are we getting expected result when formatted through CLI?

Comment (SupunS) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java:531]: Yes. 
`Formatter.format(syntaxTree)` returns the same result.

**Review by nadeeshaan — APPROVED** [review]
