### PR TITLE
Fix `PackageID` inside `BTypeSymbol` of User defined `BTableTypes` being incorrectly set as `ballerina/lang.annotations:0.0.0`

### LINKED ISSUE #42167: [Bug]: `PackageID` inside `BTypeSymbol` of User defined `BTableType`s are incorrectly set as `ballerina/lang.annotations:0.0.0`
### Description

Even though every other user defined type sets its `PackageID` as the user defined module it was defined in, `BTableType` user defined types set their `PackageID`s as `ballerina/lang.annotations:0.0.0`.

Following is a comparison depicting the inconsistency between `BTypeSymbols`,

image

### Steps to Reproduce

Remote debug the following code with ballerina-lang and check the `PackageID` of `tableA`.

```
type TableA table<RecA> key(a);

type RecA record {
    readonly int a;
    int b;
};

public function main() {
    TableA tableA = table [{a: 10, b: 9}];
}
```

### Affected Version(s)

Ballerina 2201.9.0 (Swan Lake Update 9)

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Thushara-Piyasekara**
## Purpose
$subject
With this PR, user defined types of following types will have the correct PackageID in their BTypeSymbol,

- BTableType
- BXMLType
- BFutureType
- BStreamType
- BTypeDescType

Fixes #42167

## Approach
Changed the TypeResolver to generate BTypeSymbols for above Types using the PackageIDs of their enclosing packages.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java [hunk 1]
```diff
@@ -1734,7 +1734,7 @@ private BType resolveTypeDesc(BLangTableTypeNode td, ResolverData data) {
         BTableType tableType = new BTableType(TypeTags.TABLE, symTable.empty, null);
         BTypeSymbol typeSymbol = type.tsymbol;
         tableType.tsymbol = Symbols.createTypeSymbol(SymTag.TYPE, Flags.asMask(EnumSet.noneOf(Flag.class)),
-                typeSymbol.name, typeSymbol.originalName, typeSymbol.pkgID,
+                typeSymbol.name, typeSymbol.originalName, data.env.enclPkg.symbol.pkgID,
```
Comment (nipunayf) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:1737]:
```suggestion
                typeSymbol.name, typeSymbol.originalName, symEnv.enclPkg.symbol.pkgID,
```

When there are multiple usages of `data.env`, as in this case, we have extracted it to `symEnv` and used that instead. Apply this in other areas where it is applicable.

**Review by nipunayf — COMMENTED** [review]
It appears that there are multiple instances of type symbols that don't have the `pkgID` set correctly. Can we have tests for each such case?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java (hunk 1 above)
Comment (Thushara-Piyasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:1737]: Thank you for the helpful suggestions. Will work on these changes and let you know

**Comment by Thushara-Piyasekara** [comment]
> It appears that there were multiple instances of type symbols that didn't have the `pkgID` set correctly. Can we have tests for each such case?

@nipunayf Added test cases in e3fd6420cf999be065716b3a943e7ac557bb8c5b

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/Ballerina.toml [hunk 2]
```diff
@@ -0,0 +1,4 @@
+[package]
+org = "sample_package_id"
+name = "symbol_package_id"
+version = "0.1.0"
```
Comment (nipunayf) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/Ballerina.toml:4]:
```suggestion
version = "0.1.0"

```

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+type UserFuture future<int>;
+
+// xml type
+type UserXml xml;
+
+// stream type
+type UserStream stream<int>;
+
+// typedesc type
+type UserTypedesc typedesc<int>;
```
Comment (nipunayf) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal:37]:
```suggestion
type UserTypedesc typedesc<int>;

```

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+import java.util.Optional;
+
+import static io.ballerina.semantic.api.test.util.SemanticAPITestUtils.assertBasicsAndGetSymbol;
+import static io.ballerina.semantic.api.test.util.SemanticAPITestUtils.getDefaultModulesSemanticModel;
+import static io.ballerina.semantic.api.test.util.SemanticAPITestUtils.getDocument;
+import static org.testng.Assert.assertEquals;
+
+/**
+ * Test cases for user defined builtinType type definition packageIDs
+ *
```
Comment (nipunayf) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:42]:
```suggestion
 *
 * @since 2201.9.0
```

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+    protected Project project;
+
+    @BeforeClass
+    public void setup() {
+        project = BCompileUtil.loadProject("test-src/symbols/symbol-package-id");
+        model = getDefaultModulesSemanticModel(project);
+    }
+
+    @Test(dataProvider = "TypeDefPackageID")
+    public void testTypeDefPackageId(int line, int offset, String name,String srcFile, String packageID) {
```
Comment (nipunayf) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:56]:
```suggestion
    public void testTypeDefPackageId(int line, int offset, String name, String srcFile, String packageID) {
```

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+        Optional<Document> srcDocument = getDocument(project, null, srcFile);
```
Comment (nipunayf) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:57]:
```suggestion
        Optional<Document> srcDocument = getDocument(project, null, srcFile);
        assertTrue(srcDocument.isPresent()
```

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+        TypeDefinitionSymbol symbol = (TypeDefinitionSymbol) assertBasicsAndGetSymbol(model, srcDocument.get(), line, offset, name, SymbolKind.TYPE_DEFINITION);
```
Comment (nipunayf) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:58]: You can directly cast it in here, and opt out the subsequent casting

```suggestion
        TypeDefinitionSymbol symbol = (BallerinaTypeDefinitionSymbol) assertBasicsAndGetSymbol(model, srcDocument.get(), line, offset, name, SymbolKind.TYPE_DEFINITION);
```

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java [hunk 8]
```diff
@@ -0,0 +1,74 @@
...
+
+        PackageID actualPackageID = ((BallerinaTypeDefinitionSymbol) symbol).getInternalSymbol().pkgID;
+        assertEquals(actualPackageID.toString(), packageID);
+    }
+
+    @DataProvider(name = "TypeDefPackageID")
```
Comment (nipunayf) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:64]:
```suggestion
    @DataProvider(name = "TypeDefPackageIDPosProvider")
```

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/Ballerina.toml [hunk 9]
```diff
@@ -0,0 +1,4 @@
+[package]
+org = "sample_package_id"
```
Comment (nipunayf) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/Ballerina.toml:2]:
```suggestion
org = "sample_org"
```

**Review by nipunayf — COMMENTED** [review]
It appears that your tests are passing despite the changes. It would be better if you could verify that your tests are failing when your changes are

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java (hunk 1 above)
Comment (Thushara-Piyasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java]: Fixed with be8c54dffd2c10afe0dab61cdf0d91f5fb702ff2. Found one more similar case in `BLangStreamType` and applied it there as well.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/Ballerina.toml (hunk 2 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/Ballerina.toml]: Fixed with be8c54dffd2c10afe0dab61cdf0d91f5fb702ff2.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal (hunk 3 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal]: Fixed with be8c54dffd2c10afe0dab61cdf0d91f5fb702ff2.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java (hunk 4 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:43]: Fixed with be8c54dffd2c10afe0dab61cdf0d91f5fb702ff2.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java (hunk 6 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:59]: Fixed with be8c54dffd2c10afe0dab61cdf0d91f5fb702ff2.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java (hunk 7 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java]: Fixed with be8c54dffd2c10afe0dab61cdf0d91f5fb702ff2.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java (hunk 8 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java]: Fixed with be8c54dffd2c10afe0dab61cdf0d91f5fb702ff2.

**Comment by Thushara-Piyasekara** [comment]
> > It appears that your tests are passing despite the changes. It would be better if you could verify that your tests are failing when your changes are not present.
> 
> @nipunayf Found the issue and fixed it with [c69a20a](https://github.com/ballerina-platform/ballerina-lang/commit/c69a20aaf2449dee2b74d91a4534b4bb50e3ccc9). But seems like the `type UserXml xml;` is giving `ballerina/lang.annotations:0.0.0` as its `PackageID` regardless of our changes. The problem seems to be in compiler side. I will look into it and update here.

Fixed the issue with BXML Type test case with 3367eda69f16aaf7e38a0fed9930162b19b050e4.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java [hunk 10]
```diff
@@ -0,0 +1,80 @@
...
+    @Test(dataProvider = "TypeDefPackageIDPosProvider")
+    public void testTypeDefPackageId(int line, int offset, String name, String srcFile, String packageID) {
+        Optional<Document> srcDocument = getDocument(project, null, srcFile);
+        assertTrue(srcDocument.isPresent());
+
+        BallerinaTypeDefinitionSymbol symbol =
+                (BallerinaTypeDefinitionSymbol) assertBasicsAndGetSymbol(model, srcDocument.get(), line, offset, name,
+                        SymbolKind.TYPE_DEFINITION);
+        PackageID actualPackageID = ((AbstractTypeSymbol) (symbol).typeDescriptor()).getBType().tsymbol.pkgID;
+
```
Comment (prakanth97) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:66]:
```suggestion
```

File: tests/ballerina-compiler-api-test/src/test/resources/testng.xml [hunk 11]
```diff
@@ -176,6 +176,7 @@
             <class name="io.ballerina.semantic.api.test.symbols.SymbolsInXMLNavigationExprsTest" />
             <class name="io.ballerina.semantic.api.test.symbols.SymbolsWithinExprTest" />
             <class name="io.ballerina.semantic.api.test.symbols.TypeDefSymbolTest" />
+            <class name="io.ballerina.semantic.api.test.symbols.TypeDefPackageIdTest" />
```
Comment (prakanth97) [inline tests/ballerina-compiler-api-test/src/test/resources/testng.xml:179]:
```suggestion
            <class name="io.ballerina.semantic.api.test.symbols.TypeDefPackageIdTest" />
            <class name="io.ballerina.semantic.api.test.symbols.TypeDefSymbolTest" />
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java [hunk 12]
```diff
@@ -795,7 +795,7 @@ private BType resolveTypedescTypeDesc(BLangConstrainedType td, ResolverData data
         BTypedescType constrainedType = new BTypedescType(symTable.empty, null);
         BTypeSymbol typeSymbol = type.tsymbol;
         constrainedType.tsymbol = Symbols.createTypeSymbol(typeSymbol.tag, typeSymbol.flags, typeSymbol.name,
-                typeSymbol.originalName, typeSymbol.pkgID, constrainedType, typeSymbol.owner,
+                typeSymbol.originalName, data.env.enclPkg.symbol.pkgID, constrainedType, typeSymbol.owner,
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java:798]: shall we create a local var 
```
SymbolEnv symEnv = data.env;
 ```
 replace it in other places, seems it used in several places, pls check other places as well.

**Comment by prakanth97** [comment]
> > It appears that your tests are passing despite the changes. It would be better if you could verify that your tests are failing when your changes are not present.
> 
> @nipunayf Found the issue and fixed it with [c69a20a](https://github.com/ballerina-platform/ballerina-lang/commit/c69a20aaf2449dee2b74d91a4534b4bb50e3ccc9). But seems like the `type UserXml xml;` is giving `ballerina/lang.annotations:0.0.0` as its `PackageID` regardless of our changes. The problem seems to be in compiler side. I will look into it and update here.

As we discussed in the offline. The behaviour is correct for the xml

> > It appears that your tests are passing despite the changes. It would be better if you could verify that your tests are failing when your changes are not present.
> 
> @nipunayf Found the issue and fixed it with [c69a20a](https://github.com/ballerina-platform/ballerina-lang/commit/c69a20aaf2449dee2b74d91a4534b4bb50e3ccc9). But seems like the `type UserXml xml;` is giving `ballerina/lang.annotations:0.0.0` as its `PackageID` regardless of our changes. The problem seems to be in compiler side. I will look into it and update here.

As we discussed in the offline, the behaviour for the `type XML xml` is correct since type node is build-in type hence it us belongs to the `annotation` pkg. If you check the pkgID of the type definition symbol, it will give expected result. 

In the tests, shall we validate the symbol pkgID as well?

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java [hunk 13]
```diff
@@ -0,0 +1,80 @@
...
+import java.util.Optional;
+
+import static io.ballerina.semantic.api.test.util.SemanticAPITestUtils.assertBasicsAndGetSymbol;
+import static io.ballerina.semantic.api.test.util.SemanticAPITestUtils.getDefaultModulesSemanticModel;
+import static io.ballerina.semantic.api.test.util.SemanticAPITestUtils.getDocument;
+import static org.testng.Assert.assertEquals;
+import static org.testng.Assert.assertTrue;
+
+/**
+ * Test cases for user defined builtinType type definition packageIDs
```
Comment (prakanth97) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:42]:
```suggestion
 * Test cases for user defined builtinType type definition packageIDs.
```
Build failed due to this.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal [hunk 14]
```diff
@@ -0,0 +1,37 @@
...
+type UserFuture future<int>;
+
+// xml type
+type UserXml xml<xml:Element>;
+
+// stream type
+type UserStream stream<int>;
+
+// typedesc type
+type UserTypedesc typedesc<int>;
```
Comment (SasinduDilshara) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal:37]: Shall we add a test with structural types as well

ex:- `type UserTypedesc typedesc<Employee>;`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java (hunk 12 above)
Comment (Thushara-Piyasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java]: Fixed in c5ad5f9dc0d36e45baa2a28b1a138d3104c18d4a. Applied the change for other places as well.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java [hunk 15]
```diff
@@ -0,0 +1,80 @@
...
+
+    @Test(dataProvider = "TypeDefPackageIDPosProvider")
+    public void testTypeDefPackageId(int line, int offset, String name, String srcFile, String packageID) {
+        Optional<Document> srcDocument = getDocument(project, null, srcFile);
+        assertTrue(srcDocument.isPresent());
+
+        BallerinaTypeDefinitionSymbol symbol =
+                (BallerinaTypeDefinitionSymbol) assertBasicsAndGetSymbol(model, srcDocument.get(), line, offset, name,
+                        SymbolKind.TYPE_DEFINITION);
+        PackageID actualPackageID = ((AbstractTypeSymbol) (symbol).typeDescriptor()).getBType().tsymbol.pkgID;
```
[the remark this answers is not in the document]
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java]: Added the assertion in c5ad5f9dc0d36e45baa2a28b1a138d3104c18d4a.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal (hunk 14 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal]: Added in c5ad5f9dc0d36e45baa2a28b1a138d3104c18d4a.

**Comment by Thushara-Piyasekara** [comment]
> > > It appears that your tests are passing despite the changes. It would be better if you could verify that your tests are failing when your changes are not present.
> > 
> > 
> > @nipunayf Found the issue and fixed it with [c69a20a](https://github.com/ballerina-platform/ballerina-lang/commit/c69a20aaf2449dee2b74d91a4534b4bb50e3ccc9). But seems like the `type UserXml xml;` is giving `ballerina/lang.annotations:0.0.0` as its `PackageID` regardless of our changes. The problem seems to be in compiler side. I will look into it and update here.
> 
> As we discussed in the offline, the behaviour for the `type XML xml` is correct since type node is build-in type hence it us belongs to the `annotation` pkg. If you check the pkgID of the type definition symbol, it will give expected result.
> 
> In the tests, shall we validate the symbol pkgID as well?

Updated the test accordingly in c5ad5f9dc0d36e45baa2a28b1a138d3104c18d4a.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java [hunk 16]
```diff
@@ -0,0 +1,161 @@
...
+import java.util.Optional;
+
+import static io.ballerina.semantic.api.test.util.SemanticAPITestUtils.assertBasicsAndGetSymbol;
+import static io.ballerina.semantic.api.test.util.SemanticAPITestUtils.getDefaultModulesSemanticModel;
+import static io.ballerina.semantic.api.test.util.SemanticAPITestUtils.getDocument;
+import static org.testng.Assert.assertEquals;
+import static org.testng.Assert.assertTrue;
+
+/**
+ * Test cases for user defined builtinType type definition packageIDs.
```
Comment (prakanth97) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:42]:
```suggestion
 * Test cases for user defined type packageIDs.
```
WDYT?

Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java]: I also think its better. Changed in 674b30fdfb428de902755274b12716fab968fe37.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal [hunk 17]
```diff
@@ -0,0 +1,72 @@
...
+//
+// Unless required by applicable law or agreed to in writing,
+// software distributed under the License is distributed on an
+// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+// KIND, either express or implied. See the License for the
+// specific language governing permissions and limitations
+// under the License.
+
+// Simple types
+type UserNil null;
```
Comment (prakanth97) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal:18]:
```suggestion
type UserNil ();
```

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal [hunk 18]
```diff
@@ -0,0 +1,72 @@
...
+type UserBoolean boolean;
+type UserInt int;
+type UserFloat float;
+type UserDecimal decimal;
+
+// Sequence types
+type UserString string;
+type UserXml_1 xml;
+type UserXml_2 xml<xml:Element>;
```
Comment (prakanth97) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal:27]: Shall we add tests for sub type of xml such as `xml:Element`, `xml:Text`, `xml:ProcessingInstruction`, `xml:Comment`

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal [hunk 19]
```diff
@@ -0,0 +1,72 @@
...
+
+// Other types
+type UserAny any;
+type UserAnydata anydata;
+type UserNever never;
+type UserReadonly readonly;
+type UserJson json;
+type UserByte byte;
+type UserUnion_1 int|float|null;
```
Comment (prakanth97) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal:36]:
```suggestion
type UserUnion_1 int|float|();
```

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal [hunk 20]
```diff
@@ -0,0 +1,72 @@
...
+type UserString string;
+type UserXml_1 xml;
+type UserXml_2 xml<xml:Element>;
+
+// Other types
+type UserAny any;
+type UserAnydata anydata;
+type UserNever never;
+type UserReadonly readonly;
+type UserJson json;
```
Comment (prakanth97) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal:34]: Add tests for `json[]` and `map<json>`

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal [hunk 21]
```diff
@@ -0,0 +1,72 @@
...
+type UserClient client object {
+    int userInt;
+};
+type UserService service object {
+    int userInt;
+};
+type UserFuture future<int>;
+type UserTypedesc_1 typedesc<int>;
+type UserTypedesc_2 typedesc<UserRecord>;
+type UserStream stream<int>;
```
Comment (prakanth97) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal:72]: - Add a test for singleton type such as `type UserSingleton 5`.
- Add tests for built-in subtype of int.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal (hunk 17 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal]: Fixed in f20d0cbd1e0c6cd4d6b5714b31f5d81e88bf4fde.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java [hunk 22]
```diff
@@ -0,0 +1,161 @@
...
+        assertEquals(actualInternalPackageID.toString(), internalPackageID);
+    }
+
+    @DataProvider(name = "TypeDefPackageIDPosProvider")
+    public Object[][] getTypeDefPackageIDPos() {
+        return new Object[][]{
+
+                // Simple types
+                {17, 5, "UserNil", "main.bal", "sample_org/symbol_package_id:0.1.0",
+                        "sample_org/symbol_package_id:0.1.0"},
```
[the remark this answers is not in the document]
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java]: Fixed in f20d0cbd1e0c6cd4d6b5714b31f5d81e88bf4fde.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal (hunk 18 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal:32]: Added test cases in f20d0cbd1e0c6cd4d6b5714b31f5d81e88bf4fde.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal (hunk 20 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal:42]: Added test cases f20d0cbd1e0c6cd4d6b5714b31f5d81e88bf4fde.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal (hunk 21 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal:86]: Added test cases in f20d0cbd1e0c6cd4d6b5714b31f5d81e88bf4fde.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal (hunk 19 above)
Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/symbol-package-id/main.bal]: Fixed in 52976acc8b722e505c48db1b95c4370b271d5b7d.

**Review by prakanth97 — APPROVED** [review]
LGTM

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java [hunk 23]
```diff
@@ -0,0 +1,191 @@
...
+        PackageID actualTypeDescPackageID = ((AbstractTypeSymbol) (symbol).typeDescriptor()).getBType().tsymbol.pkgID;
+        PackageID actualInternalPackageID = symbol.getInternalSymbol().pkgID;
+        assertEquals(actualTypeDescPackageID.toString(), typeDescPackageID);
+        assertEquals(actualInternalPackageID.toString(), internalPackageID);
+    }
+
+    @DataProvider(name = "TypeDefPackageIDPosProvider")
+    public Object[][] getTypeDefPackageIDPos() {
+        return new Object[][]{
+
```
Comment (MaryamZi) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:76]: Can we add some tests referring to builtin types also?

Also will the behaviour now be different for

```ballerina
type T1 future;
```

vs 

```ballerina
type T1 future<any|error>;
```

?

In a way, that's OK I guess. The first is more like an alias.

As discussed with @prakanth97 also though, I think when we have

```
type T some-typedesc;
```

only `T` should have an owner, not `some-typedesc` generally. But we don't have the ideal separation atm to do this.

Comment (Thushara-Piyasekara) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/TypeDefPackageIdTest.java:76]: Added test case for `future` builtin type in d63b2090d7d94931913c1329c4dfc5784e5d5164.

The behavior is different for the given scenario,

```ballerina
type T1 future;
type T2 future<any|error>;
```

For T1, the `PackageID` is still `ballerina/lang.annotations:0.0.0`. But for T2, it is `sample_org/symbol_package_id:0.1.0`. Please let me know if this is not the expected behavior.

**Review by prakanth97 — APPROVED** [review]
