### PR TITLE
Validate expr with check keyword in call stmt

### LINKED ISSUE #28769: Conflicting error messages using check inside a type guard
Observed with SL-Alpha2 packs. 

```ballerina
import ballerina/file;

function test1() returns error? {
    var result = file:remove("somePath");
    if !(result is file:FileNotFoundError) && !(result is ()) {
        check result; 
        // Error 1: variable assignment is required(BCE2526)
        // Error 2: invalid usage of the 'check' expression operator: all expression types are equivalent to error type
    }
}

function test2() returns error? {
    var result = file:remove("somePath");
    if !(result is file:FileNotFoundError) && !(result is ()) {
        var x = check result; // Error: invalid usage of the 'check' expression operator: all expression types are equivalent to error type(BCE3031)
    }

}
```

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fix the issue mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/28769#issuecomment-791130489 also.

Fixes #28769 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java [hunk 1]
```diff
@@ -320,7 +320,8 @@
     ERROR_COMPLEX_VARIABLE_MUST_BE_INITIALIZED("BCE667", "error.complex.variable.must.be.initialized"),
     ERROR_ISOLATED_VAR_CANNOT_BE_DECLARED_AS_PUBLIC("BCE668", "error.isolated.var.cannot.be.declared.as.public"),
     ERROR_VARIABLE_DECLARED_WITH_VAR_CANNOT_BE_PUBLIC("BCE669", "error.variable.declared.with.var.cannot.be.public"),
-    ERROR_FIELD_BP_INSIDE_LIST_BP("BCE670", "error.field.binding.pattern.inside.list.binding.pattern")
+    ERROR_FIELD_BP_INSIDE_LIST_BP("BCE670", "error.field.binding.pattern.inside.list.binding.pattern"),
+    ERROR_EXPRESSION_EXPECTED_CALL_EXPRESSION("BCE671", "error.expression.expected.call.expression")
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java:324]: `EXPRESSION_EXPECTED_CALL_EXPRESSION` is not making sense as a sentence.
How about simply `CALL_EXPRESSION_EXPECTED`?

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 2]
```diff
@@ -6601,6 +6601,19 @@ private STNode parseCheckExpression(boolean isRhsExpr, boolean allowActions, boo
...
+            }
+            checkingKeyword = SyntaxErrors.cloneWithTrailingInvalidNodeMinutiae(checkingKeyword, expr,
+                                                        DiagnosticErrorCode.ERROR_EXPRESSION_EXPECTED_CALL_EXPRESSION);
+            STNode funcName = SyntaxErrors.createMissingToken(SyntaxKind.IDENTIFIER_TOKEN);
+            funcName = STNodeFactory.createSimpleNameReferenceNode(funcName);
+            STNode openParenToken = SyntaxErrors.createMissingToken(SyntaxKind.OPEN_PAREN_TOKEN);
+            STNode arguments = STNodeFactory.createEmptyNodeList();
+            STNode closeParenToken = SyntaxErrors.createMissingToken(SyntaxKind.CLOSE_PAREN_TOKEN);
+            expr = STNodeFactory.createFunctionCallExpressionNode(funcName, openParenToken, arguments,
+                    closeParenToken);
```
[the remark this answers is not in the document]
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:6616]: +1

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java (hunk 1 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java:324]: `INVALID_EXPRESSION_EXPECTED_CALL_EXPRESSION` WDYT?

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java [hunk 3]
```diff
@@ -321,7 +321,7 @@
     ERROR_ISOLATED_VAR_CANNOT_BE_DECLARED_AS_PUBLIC("BCE668", "error.isolated.var.cannot.be.declared.as.public"),
     ERROR_VARIABLE_DECLARED_WITH_VAR_CANNOT_BE_PUBLIC("BCE669", "error.variable.declared.with.var.cannot.be.public"),
     ERROR_FIELD_BP_INSIDE_LIST_BP("BCE670", "error.field.binding.pattern.inside.list.binding.pattern"),
-    ERROR_EXPRESSION_EXPECTED_CALL_EXPRESSION("BCE671", "error.expression.expected.call.expression")
+    INVALID_EXPRESSION_EXPECTED_CALL_EXPRESSION("BCE671", "error.expression.expected.call.expression")
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java:324]: Should be prefixed with `ERROR_`

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 4]
```diff
@@ -8220,9 +8208,34 @@ private STNode parseCallStatement(STNode expression) {
         // This is not a must because this expression is validated in the semantic analyzer.
         STNode semicolon = parseSemicolon();
         endContext();
+        if (expression.kind == SyntaxKind.CHECK_EXPRESSION) {
+            STNode callExpr = parseCallExpression((STCheckExpressionNode) expression);
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:8212]: lets assign this to `expression`
`validateCallExpression` is appropriate than `parseCallExpression`
lets do the casting inside the method

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 5]
```diff
@@ -8207,9 +8208,34 @@ private STNode parseCallStatement(STNode expression) {
...
+            STNode funcName = SyntaxErrors.createMissingToken(SyntaxKind.IDENTIFIER_TOKEN);
+            funcName = STNodeFactory.createSimpleNameReferenceNode(funcName);
+            STNode openParenToken = SyntaxErrors.createMissingToken(SyntaxKind.OPEN_PAREN_TOKEN);
+            STNode arguments = STNodeFactory.createEmptyNodeList();
+            STNode closeParenToken = SyntaxErrors.createMissingToken(SyntaxKind.CLOSE_PAREN_TOKEN);
+            STNode funcCallExpr = STNodeFactory.createFunctionCallExpressionNode(funcName, openParenToken, arguments,
+                                                                                 closeParenToken);
+            return STNodeFactory.createCheckExpressionNode(SyntaxKind.CHECK_EXPRESSION, checkingKeyword, funcCallExpr);
+        }
+        return callExpr;
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:8236]: we can simplify this by returning `callExpr` if the `expr` is func call or method call at the beginning of the method

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 6]
```diff
@@ -8207,9 +8208,35 @@ private STNode parseCallStatement(STNode expression) {
...
+        }
         return STNodeFactory.createExpressionStatementNode(SyntaxKind.CALL_STATEMENT, expression, semicolon);
     }
 
+    private STNode validateCallExpression(STNode callExpr) {
+        STCheckExpressionNode checkExpr = (STCheckExpressionNode) callExpr;
+        STNode expr = checkExpr.expression;
+        if (expr.kind == SyntaxKind.FUNCTION_CALL || expr.kind == SyntaxKind.METHOD_CALL) {
+            return callExpr;
+        }
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:8222]:
```suggestion
        }
        
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 7]
```diff
@@ -8207,9 +8208,35 @@ private STNode parseCallStatement(STNode expression) {
...
+        STNode checkKeyword = checkExpr.checkKeyword;
+        if (expr.kind == SyntaxKind.CHECK_EXPRESSION) {
+            expr = validateCallExpression(expr);
+            return STNodeFactory.createCheckExpressionNode(SyntaxKind.CHECK_EXPRESSION, checkKeyword, expr);
+        }
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:8227]:
```suggestion
        }
        
```

**Review by rdulmina — COMMENTED** [review]
Parser changes LGTM

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java [hunk 8]
```diff
@@ -320,7 +320,8 @@
     ERROR_COMPLEX_VARIABLE_MUST_BE_INITIALIZED("BCE667", "error.complex.variable.must.be.initialized"),
     ERROR_ISOLATED_VAR_CANNOT_BE_DECLARED_AS_PUBLIC("BCE668", "error.isolated.var.cannot.be.declared.as.public"),
     ERROR_VARIABLE_DECLARED_WITH_VAR_CANNOT_BE_PUBLIC("BCE669", "error.variable.declared.with.var.cannot.be.public"),
-    ERROR_FIELD_BP_INSIDE_LIST_BP("BCE670", "error.field.binding.pattern.inside.list.binding.pattern")
+    ERROR_FIELD_BP_INSIDE_LIST_BP("BCE670", "error.field.binding.pattern.inside.list.binding.pattern"),
+    ERROR_INVALID_EXPRESSION_EXPECTED_CALL_EXPRESSION("BCE671", "error.expression.expected.call.expression")
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java:324]: Usually, we have the msg key as the same dotted version of the enum name. Other than that LGTM!.  
```suggestion
    ERROR_INVALID_EXPRESSION_EXPECTED_CALL_EXPRESSION("BCE671", "error.invalid.expression.expected.call.expression")
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java [hunk 9]
```diff
@@ -35,15 +35,14 @@
...
                 "test-src/expressions/checkedexpr/checked_expr_semantics_negative.bal");
-        Assert.assertEquals(compile.getErrorCount(), 4, compile.toString());
+        Assert.assertEquals(compile.getErrorCount(), 5, compile.toString());
         BAssertUtil.validateError(compile, 0, "invalid usage of the 'check' expression " +
                 "operator: no expression type is equivalent to error type", 11, 25);
-        BAssertUtil.validateError(compile, 1, "invalid usage of the 'check' expression " +
-                "operator: all expression types are equivalent to error type", 16, 25);
-        BAssertUtil.validateError(compile, 2, "invalid usage of the 'check' expression " +
-                "operator: all expression types are equivalent to error type", 30, 25);
+        BAssertUtil.validateError(compile, 1, "incompatible types: expected 'string', found 'never'", 16, 19);
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java:41]: Example is here is 
```
function testCheckedExprSemanticErrors2() returns error? {
    string line = checkpanic readLineError();
}
```

The diagnostic is correct, But I think we can improve this.

File: compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties [hunk 10]
```diff
@@ -305,3 +305,4 @@ error.complex.variable.must.be.initialized=complex variable must be initialized
 error.isolated.var.cannot.be.declared.as.public=isolated variable cannot be public
 error.variable.declared.with.var.cannot.be.public=variable declared with var cannot be public
 error.field.binding.pattern.inside.list.binding.pattern=field binding pattern inside list binding pattern
+error.expression.expected.call.expression = invalid expression, expected call expression
```
Comment (MaryamZi) [inline compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties:308]: I think this should be 
```suggestion
error.expression.expected.call.expression = invalid expression, expected a call expression
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java (hunk 8 above)
Comment (hasithaa) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java:324]: @chiranSachintha Shall we fix this in a separate PR ?

Comment (chiranSachintha) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java]: Fixed here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 11]
```diff
@@ -4853,17 +4854,10 @@ private void visitCheckAndCheckPanicExpr(BLangCheckedExpr checkedExpr) {
             return;
         }
 
-        if (nonErrorTypes.isEmpty()) {
-            // All member types in the union are equivalent to the error type.
-            // Checked expression requires at least one type which is not equivalent to the error type.
-            dlog.error(checkedExpr.expr.pos,
-                    DiagnosticErrorCode.CHECKED_EXPR_INVALID_USAGE_ALL_ERROR_TYPES_IN_RHS, operatorType);
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4860]: Shall we remove this diagnostic? All the usages have been removed with this PR.

**Review by hasithaa — APPROVED** [review]
Looks good to me

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java (hunk 9 above)
Comment (chiranSachintha) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java:41]: @hasithaa Shall I fix this in a separate PR?

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 12]
```diff
@@ -431,7 +431,6 @@
 
     // Checked expression related errors
     CHECKED_EXPR_INVALID_USAGE_NO_ERROR_TYPE_IN_RHS("BCE3030", "checked.expr.invalid.usage.no.error.type.rhs"),
-    CHECKED_EXPR_INVALID_USAGE_ALL_ERROR_TYPES_IN_RHS("BCE3031", "checked.expr.invalid.usage.only.error.types.rhs"),
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:434]: Shall we fix the subsequent diagnostic IDs?

File: langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal [hunk 13]
```diff
@@ -229,10 +229,14 @@ function testXMLCycleDueToChildrenOfChildren() returns xml|error {
     var cds = cat.getChildren().strip();
     'xml:Element fc = <'xml:Element> cds[0];
     error? er = trap fc.setChildren(subRoot);
-    check trap fc.setChildren(subRoot);
+    check setChildren(fc, subRoot);
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal:232]: `check fc.setChildren(subRoot)` also works, right?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java (hunk 9 above)
Comment (hasithaa) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java:41]: yes. Please create an issue, we can fix this later.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java (hunk 12 above)
Comment (hasithaa) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:434]: Shall we update this later, This might conflict with other PRs.

File: langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal (hunk 13 above)
Comment (MaryamZi) [reply langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal:232]: Ah nvm, misread the change!

**Review by MaryamZi — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java (hunk 9 above)
Comment (chiranSachintha) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/checkedexpr/CheckedExprNegativeTest.java:41]: Created.(https://github.com/ballerina-platform/ballerina-lang/issues/29696)
