### PR TITLE
Fix completions in the field access expressions when the type is narrowed

### LINKED ISSUE #38457: [Bug]: Completions not working for a record type in the RHS of an && op
### Description

See the following. Notice how the field names are missing in the completions list. Expected to see `name` in the completions. 

image

```ballerina
function foo(PathSegment[] segments, map<anydata> pathParams) {
    foreach var item in segments {
        if item is PathParam && pathParams.hasKey(item.)
    }
}

public type PathSegment string|PathParam;

type PathParam record {|
    string name;
|};
```

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by gayalkuruppu**
Fixes #38457

Screenshot 2022-11-11 at 09 04 27

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java [hunk 1]
```diff
@@ -82,6 +83,25 @@ public Optional<TypeSymbol> transform(SimpleNameReferenceNode node) {
...
+                    .typeOf(((FieldAccessExpressionNode) node.parent()).expression());
+            if (typeSymbol.isEmpty()) {
+                if (symbol.isEmpty()) {
+                    return Optional.empty();
+                }
+
+                return SymbolUtil.getTypeDescriptor(symbol.get());
+            }
+
+            return SymbolUtil.getTypeDescriptor(typeSymbol.get());
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java:102]: This can be simplified as follows.
```suggestion
            if (typeSymbol.isPresent()) {
                   return SymbolUtil.getTypeDescriptor(typeSymbol.get());
            }
```

**Review by malinthar — CHANGES_REQUESTED** [review]

**Review by malinthar — APPROVED** [review]
LGTM!

**Review by TharushiJay — APPROVED** [review]
