### PR TITLE
Fix resource function not getting mapped correctly in architecture design tool

### LINKED ISSUE #39196: [Bug]: [Component Model Generator] service-id for http resource function mappings set to be null
### Description

Even though the client declaration is annotated with `display` annotation, the service id for the interactions set to be null when the client declaration is initialized withing `init` function of a service.

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Other Area

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by AzeemMuzammil**
Fixes  #39196

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/architecture-model-generator/src/main/java/io/ballerina/architecturemodelgenerator/generators/service/nodevisitors/ActionNodeVisitor.java [hunk 1]
```diff
@@ -86,7 +86,18 @@ public List<Interaction> getInteractionList() {
...
-        ExpressionNode clientNode = clientResourceAccessActionNode.expression();
+        SimpleNameReferenceNode clientNode = null;
+        if (clientResourceAccessActionNode.expression() instanceof FieldAccessExpressionNode) {
+            NameReferenceNode fieldName = ((FieldAccessExpressionNode)
+                    clientResourceAccessActionNode.expression()).fieldName();
+            if (fieldName instanceof SimpleNameReferenceNode) {
+                clientNode = (SimpleNameReferenceNode) fieldName;
+            }
+            // todo : Other combinations
+        } else if (clientResourceAccessActionNode.expression() instanceof SimpleNameReferenceNode) {
```
Comment (NipunaRanasinghe) [inline misc/architecture-model-generator/src/main/java/io/ballerina/architecturemodelgenerator/generators/service/nodevisitors/ActionNodeVisitor.java:97]: @AzeemMuzammil shouldn't we ideally make this field access expression logic as recursive, to handle field access expressions with chain access?

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM
