### PR TITLE
Fix lang-server breaks for --std-libs param for old SDKs

### LINKED ISSUE #21705: VSCode plugin breaks for old SDKs less than 1.2.0
**Description:**
VSCode plugin breaks for old SDKs less than 1.2.0

**Steps to reproduce:**
Error log
```
ballerina: unknown option: '--stdlib-definition'
Run 'ballerina help' for usage.
[Info  - 1:34:44 PM] Connection to server got closed. Server will restart.
```

**Affected Versions:**
1.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by rasika**
Fixes #21705

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java [hunk 1]
```diff
@@ -131,8 +131,13 @@ public void didChangeConfiguration(DidChangeConfigurationParams params) {
...
         }
-        configHolder.updateConfig(GSON.fromJson(((JsonObject) params.getSettings()).get("ballerina"),
-                                                LSClientConfig.class));
+        if (((JsonObject) params.getSettings()).get("ballerina") != null) {
+            configHolder.updateConfig(GSON.fromJson(((JsonObject) params.getSettings()).get("ballerina"),
+                                                    LSClientConfig.class));
+        } else {
+            // To support old plugins versions
+            configHolder.updateConfig(GSON.fromJson(((JsonObject) params.getSettings()), LSClientConfig.class));
+        }
```
Comment (NipunaRanasinghe) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaWorkspaceService.java]:
```suggestion
        JsonObject settings = (JsonObject) params.getSettings();
        if (settings.get("ballerina") != null) {
            configHolder.updateConfig(GSON.fromJson(settings.get("ballerina"), LSClientConfig.class));
        } else {
            // To support old plugins versions
            configHolder.updateConfig(GSON.fromJson(settings, LSClientConfig.class));
        }
```
