### PR TITLE
Fix spec deviations lang libs

### LINKED ISSUE #23360: Use distinct object type for Iterable
Refer Commit https://github.com/ballerina-platform/ballerina-spec/commit/54725c33fa7afdb203c4175e06070d900c042c2b

### LINKED ISSUE #25446: Set return types of `fromJsonFloatString` and `fromJsonDecimalString` as `JsonFloat` and `JsonDecimal` respectively
**Description:**
```ballerina
public type JsonDecimal ()|boolean|string|decimal|JsonDecimal[]|map<JsonDecimal>;
public function fromJsonDecimalString(string str) returns JsonDecimal|error = external;

public type JsonFloat ()|boolean|string|float|JsonFloat[]|map<JsonFloat>;
public function fromJsonFloatString(string str) returns JsonFloat|error = external;
```
To fix this issue need to allow cyclic reference in unions typedefs.

### LINKED ISSUE #27899: Align lang libs in the compiler with the ones in the spec.
**Description:**
We need to go through and update langlibs with the spec.

Things to consider:
- Addition or removal of functions.
- Signature or data type changes.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by KRVPerera**
Fixes #27899
Fixes #25446
Fixes #23360

RawTemplate type is now a distinct type
`indexOf` and `lastIndexOf` lang.array now work only on pure types (anydata|error).
Object iterators must be a subtype of `object:Iterable`

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [x] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java [hunk 1]
```diff
@@ -81,8 +81,8 @@ public void test(String config, String source) throws IOException, WorkspaceDocu
                 {"variableAssignmentRequiredCodeAction35.json", "createVariable5.bal"},
 //                {"variableAssignmentRequiredCodeAction36.json", "createVariable5.bal"}, //disabled need isAssignable
                 {"variableAssignmentRequiredCodeAction37.json", "createVariable5.bal"},
-                {"variableAssignmentRequiredCodeAction38.json", "createVariable5.bal"},
-                {"variableAssignmentRequiredCodeAction39.json", "createVariable5.bal"},
+//                {"variableAssignmentRequiredCodeAction38.json", "createVariable5.bal"},
```
Comment (KRVPerera) [inline language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java:84]: Code action `createVariable` affected for integer ranges

Comment (KRVPerera) [reply language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java:84]: Fixed by e083d32a914df32ee445c85984f081901fa1b1f8

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 2]
```diff
@@ -967,6 +946,20 @@ public void bootstrapIntRangeType() {
         throw new IllegalStateException("built-in Integer Range type not found ?");
     }
 
+    public void bootstrapIteratorType() {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:949]: or 
```suggestion
    public void bootstrapIterableType() {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 3]
```diff
@@ -967,6 +946,20 @@ public void bootstrapIntRangeType() {
...
+        ScopeEntry entry = symTable.langObjectModuleSymbol.scope.lookup(Names.OBJECT_ITERABLE);
+        while (entry != NOT_FOUND_ENTRY) {
+            if ((entry.symbol.tag & SymTag.TYPE) != SymTag.TYPE) {
+                entry = entry.next;
+                continue;
+            }
+            symTable.iterableType = (BObjectType) entry.symbol.type;
+            return;
+        }
+        throw new IllegalStateException("built-in distinct Iterator type not found ?");
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:960]:
```suggestion
        throw new IllegalStateException("built-in distinct Iterable type not found ?");
```

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 4]
```diff
@@ -676,8 +676,8 @@ error.iterable.not.supported.collection=\
   incompatible types: ''{0}'' is not an iterable collection
 
 error.incompatible.iterator.function.signature=\
-  iterable objects must have a __iterator function with signature, ' \
-  public function __iterator() returns (object { public function next () returns (record {| T value; |}?); })';
+  iterable objects must have a iterator function with signature, ' \
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:679]:
```suggestion
  iterable objects must have an iterator method with signature, ' \
```

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 5]
```diff
@@ -1671,3 +1671,9 @@ error.invalid.readonly.field.type=\
 error.continue.not.allowed=continue not allowed here
 
 error.break.not.allowed=break not allowed here
+
+error.invalid.iterable.type=\
+  invalid iterable type ''{1}'': an iterable object must be subtypes of ''{0}''
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1676]:
```suggestion
  invalid iterable type ''{1}'': an iterable object must be a subtype of ''{0}''
```

File: langlib/lang.object/src/main/ballerina/object.bal [hunk 6]
```diff
@@ -13,3 +13,56 @@
...
+        public isolated function next() returns record {| any|error value; |}|error?;
+    };
+};
+
+# Integer range expression is represented using `IntRange` object.
+#
+# + iStart - start expression of range expression
+# + iEnd - second expression on range expression
+# + iCurrent - current cursor
+public class IntRange {
```
Comment (MaryamZi) [inline langlib/lang.object/src/main/ballerina/object.bal:34]: Didn't we decide to have this in the internal package?

Comment (KRVPerera) [reply langlib/lang.object/src/main/ballerina/object.bal:34]: Need to discuss this. According to spec **Range expression** should be available to be used anywhere and not just in `foreach`. Therefore users should be able to assign range expression to a variable. If I hide this in the internal package we have a type for integer range but it is a hidden type. 
Basically, code action creates a variable for integer range will create type defined in the internal package.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 7]
```diff
@@ -6860,6 +6860,12 @@ private BLangClassDefinition desugarTemplateLiteralObjectTypedef(List<BLangLiter
         BObjectType objectClassType = new BObjectType(classTSymbol, classTSymbol.flags);
         objectClassType.fields = objectType.fields;
         classTSymbol.type = objectClassType;
+        if (!objectType.typeIdSet.primary.isEmpty()) {
```
[the remark this answers is not in the document]
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: fixed e5f87d90f72db8a52f9ef620e598a4b7fd4e1622

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java [hunk 8]
```diff
@@ -247,4 +250,36 @@
...
+        members.add(TYPE_NULL);
+        members.add(TYPE_BOOLEAN);
+        members.add(TYPE_STRING);
+        members.add(TYPE_DECIMAL);
+        var valueModule = new Module(BALLERINA_BUILTIN_PKG_PREFIX, VALUE_LANG_LIB, null);
+        BUnionType jsonDecimal = new BUnionType(TypeConstants.JSON_DECIMAL_TNAME, valueModule, members);
+        jsonDecimal.isCyclic = true;
+        MapType internaljsonDecimalMap = new BMapType(TypeConstants.MAP_TNAME, jsonDecimal, valueModule);
+        ArrayType internaljsonDecimalArray = new BArrayType(jsonDecimal);
+        jsonDecimal.addMembers(internaljsonDecimalArray, internaljsonDecimalMap);
```
[the remark this answers is not in the document]
Comment (KRVPerera) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java]: fixed 660874e704fddf894020d6598f4a57ee43c9d21e

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java [hunk 9]
```diff
@@ -247,4 +250,36 @@
...
+        members.add(TYPE_NULL);
+        members.add(TYPE_BOOLEAN);
+        members.add(TYPE_STRING);
+        members.add(TYPE_FLOAT);
+        var valueModule = new Module(BALLERINA_BUILTIN_PKG_PREFIX, VALUE_LANG_LIB, null);
+        BUnionType jsonFloat = new BUnionType(TypeConstants.JSON_FLOAT_TNAME, valueModule, members);
+        jsonFloat.isCyclic = true;
+        MapType internaljsonFloatMap = new BMapType(TypeConstants.MAP_TNAME, jsonFloat, valueModule);
+        ArrayType internaljsonFloatArray = new BArrayType(jsonFloat);
+        jsonFloat.addMembers(internaljsonFloatArray, internaljsonFloatMap);
```
[the remark this answers is not in the document]
Comment (KRVPerera) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java]: fixed 660874e704fddf894020d6598f4a57ee43c9d21e

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java [hunk 10]
```diff
@@ -95,32 +95,41 @@ void loadLangLib(CompilerContext compilerContext, PackageID langLib) {
         symbolTable.langJavaModuleSymbol = loadLangLibFromBala(JAVA, compilerContext);
 
         if (langLib.equals(INTERNAL)) {
+            symbolTable.langObjectModuleSymbol = loadLangLibFromBala(OBJECT, compilerContext);
+            symResolver.bootstrapIteratorType();
             return; // Nothing else to load.
         }
 
         // load internal
```
[the remark this answers is not in the document]
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/Bootstrap.java:103]: remvoed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 3 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: fixed e9e5565f93fa4d5e93b52521047496f55b0f0e23

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 2 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: fixed e9e5565f93fa4d5e93b52521047496f55b0f0e23

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 4 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: fixed e9e5565f93fa4d5e93b52521047496f55b0f0e23

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 5 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: fixed e9e5565f93fa4d5e93b52521047496f55b0f0e23

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java [hunk 11]
```diff
@@ -413,16 +413,22 @@ private static BIntersectionType setImmutableType(Location pos, Types types,
...
-                BType immutableEffectiveType;
                 LinkedHashSet<BType> originalMemberList = origUnionType.getMemberTypes();
-                LinkedHashSet<BType> readOnlyMemTypes = new LinkedHashSet<>(originalMemberList.size());
-                immutableEffectiveType = BUnionType.create(origUnionType.tsymbol);
+                if (unresolvedTypes.contains(origUnionType) && origUnionType.immutableType != null) {
+                    return origUnionType.immutableType;
+                } else {
+                    BIntersectionType immutableUnionIntersectionType = createImmutableIntersectionType(env,
+                            origUnionType, BUnionType.create(origUnionType.tsymbol), symTable);
+                    origUnionType.immutableType = immutableUnionIntersectionType;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java:422]:
```suggestion
                    origUnionType.immutableType = createImmutableIntersectionType(env,
                            origUnionType, BUnionType.create(origUnionType.tsymbol), symTable);
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java:422]: We don't need the else block right? We can move the logic out since we're returning in the if block?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 12]
```diff
@@ -1678,3 +1678,9 @@ error.invalid.readonly.field.type=\
 error.continue.not.allowed=continue not allowed here
 
 error.break.not.allowed=break not allowed here
+
+error.invalid.iterable.type=\
+  invalid iterable type ''{1}'': an iterable object must be a subtype of ''{0}''
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1683]: Do we have tests with these error messages?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java (hunk 11 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java:422]: Remove else condition

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 12 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1683]: Added one 4d3bafa3ac1fffc61878c0261883119cbe5ad9bc

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java [hunk 13]
```diff
@@ -136,9 +136,17 @@ public BallerinaObjectTypeSymbol(CompilerContext context, ModuleID moduleID, BOb
 
     @Override
     public String signature() {
+        /*
+            When the object type is distinct we need generate the actual finite type as the signature. To avoid this for
+            anonymous types currently returns `var`
+         */
+        if (Symbols.isFlagOn(getBType().flags, Flags.ANONYMOUS)) {
+            return "var";
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java:144]: @pubudu91 @nadeeshaan Is this okay.

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java]: I have reverted LS changes and created an issue 
https://github.com/ballerina-platform/ballerina-lang/issues/29092

File: language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json [hunk 14]
```diff
@@ -16,7 +16,7 @@
                             "character": 4
                         }
                     },
-                    "newText": "object {public isolated function __iterator() returns object {public isolated function next() returns record {| int value; |}? ;} ;} objectResult = "
+                    "newText": "object {int iStart;int iEnd;int iCurrent;public isolated function iterator() returns object {public isolated function next() returns record {| int value; |}? ;} ;} objectResult = "
```
Comment (rasika) [inline language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json:19]: Are these fields expected for iterator object ? `int iStart;int iEnd;int iCurrent;`

Comment (KRVPerera) [reply language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json:19]: We don't actually need to show fields. Spec does not define an exact implementation for iterator object that we must return for int range expression.
>The result of a range-expr is a new object belonging to the object type Iterable<int,()>

I am returning an object from `createIntRange` method which includes internal `__IntRange` class. If the class has private fields I cannot make the object including the class. I cannot return the `__IntRange` class itself since it is internal.

Comment (KRVPerera) [reply language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json:19]: Looks like this code does not compile. Let me check this again?

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java [hunk 15]
```diff
@@ -147,7 +147,7 @@ public BallerinaObjectTypeSymbol(CompilerContext context, ModuleID moduleID, BOb
     public String signature() {
         StringBuilder signature = new StringBuilder();
         StringJoiner qualifierJoiner = new StringJoiner(" ");
-        StringJoiner fieldJoiner = new StringJoiner(";");
+        StringJoiner fieldJoiner = new StringJoiner("");
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java:150]: Not requesting to change, but just wondering why is this changed, this string joiner looks like a string builder.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java [hunk 16]
```diff
@@ -779,7 +780,7 @@ private void defineCloneableCyclicTypeAndDependentTypes() {
         cloneableType = BUnionType.create(null, readonlyType, xmlType);
         addCyclicArrayMapTableOfMapMembers(cloneableType);
 
-        cloneableType.tsymbol = new BTypeSymbol(SymTag.TYPE, Flags.PUBLIC, Names.CLONEABLE, rootPkgSymbol.pkgID,
+        cloneableType.tsymbol = new BTypeSymbol(SymTag.TYPE, Flags.PRIVATE, Names.CLONEABLE, rootPkgSymbol.pkgID,
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java:783]: We might want to add a comment here saying why this is private, I was confused for a bit

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java [hunk 17]
```diff
@@ -413,16 +413,22 @@ private static BIntersectionType setImmutableType(Location pos, Types types,
...
+                }
 
-                BUnionType unionEffectiveImmutableType = (BUnionType) immutableEffectiveType;
+                LinkedHashSet<BType> readOnlyMemTypes = new LinkedHashSet<>(originalMemberList.size());
+                BUnionType unionEffectiveImmutableType = (BUnionType) origUnionType.immutableType.effectiveType;
                 unionEffectiveImmutableType.name = origUnionType.name;
                 unionEffectiveImmutableType.isCyclic = origUnionType.isCyclic;
                 unionEffectiveImmutableType.setMemberTypes(readOnlyMemTypes);
 
+
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java:431]: extra line

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java (hunk 16 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java:786]: added a comment

File: language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json (hunk 14 above)
Comment (KRVPerera) [reply language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json]: I changed fields qualifiers to public fields because LHS cannot have private fields for object assignability.

Comment (rasika) [reply language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json]: Even exposing these as public fields looks not so nice imo. I feel we need to omit private fields when generating signature for [ObjectTypeSymbols](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java#L162). WDYT @pubudu91 @KRVPerera ?

Comment (KRVPerera) [reply language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json]: I agree that we should omit private field descriptors and method descriptors. This solves the problem of having to expose the fields to support code action.
@pubudu91 Please confirm if this is okay.

Comment (KRVPerera) [reply language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json]: I prevented non-public fields from contributing to the signature.
b4a1efd330fe21c60de8cab91eaee70f95b37144

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java (hunk 15 above)
Comment (rdhananjaya) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java:150]: `new StringJoiner(";", "", ";")`

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaObjectTypeSymbol.java:150]: This is the first thing I tried. The problem is prefix gets added to an empty joiner too. Can add this and only add the joiner conditionally to the signature.

File: language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json (hunk 14 above)
Comment (KRVPerera) [reply language-server/modules/langserver-core/src/test/resources/codeaction/create-variable/config/variableAssignmentRequiredCodeAction38.json]: I will be adding https://github.com/ballerina-platform/ballerina-spec/commit/723b2e0ac26233d77f37e722f2cd74e4205cd92b changes to this PR as well.

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 18]
```diff
@@ -1695,3 +1695,9 @@ error.break.not.allowed=\
 
 error.unused.variable.with.inferred.type.including.error=\
   unused variable ''{0}'' with inferred type including error
+
+error.invalid.iterable.type=\
+  invalid iterable type ''{1}'': an iterable object must be a subtype of ''{0}''
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1700]: Any reason to have ``{1}`` before ``{0}``?

File: langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachIterableObjectTest.java [hunk 19]
```diff
@@ -84,33 +84,55 @@ public void testNestedIterableObject() {
...
+    @Test
+    public void testIterableDistinctObjectReturnedByRangeExpression() {
+        BValue[] returns = BRunUtil.invoke(program, "testIterableDistinctObjectReturnedByRangeExpression");
+
+        BValueArray arr = (BValueArray) returns[0];
+        Assert.assertEquals(arr.size(), 3);
+        int i = 0;
+        Assert.assertEquals(arr.getInt(i++), 1);
+        Assert.assertEquals(arr.getInt(i++), 2);
+        Assert.assertEquals(arr.getInt(i++), 3);
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachIterableObjectTest.java:108]: Shall we do the assertions in ballerina itself?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 20]
```diff
@@ -686,8 +686,8 @@ error.iterable.not.supported.collection=\
   incompatible types: ''{0}'' is not an iterable collection
 
 error.incompatible.iterator.function.signature=\
-  iterable objects must have a __iterator function with signature, ' \
-  public function __iterator() returns (object { public function next () returns (record {| T value; |}?); })';
+  iterable objects must have an iterator method with signature, ' \
+  public function iterator() returns (object { public function next () returns (record {| T value; |}?); })';
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:690]: Do we have tests for this?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 21]
```diff
@@ -4069,21 +4068,21 @@ private void defineReferencedFunction(Location location, Set<Flag> flagSet, Symb
...
             if (!hasSameFunctionSignature((BInvokableSymbol) matchingObjFuncSym, referencedFunc.symbol)) {
                 BLangFunction matchingFunc = findFunctionBySymbol(declaredFunctions, matchingObjFuncSym);
                 Location methodPos = matchingFunc != null ? matchingFunc.pos : typeRef.pos;
                 dlog.error(methodPos, DiagnosticErrorCode.REFERRED_FUNCTION_SIGNATURE_MISMATCH,
                            getCompleteFunctionSignature(referencedFunc.symbol),
                            getCompleteFunctionSignature((BInvokableSymbol) matchingObjFuncSym));
             }
+
+            if (Symbols.isFunctionDeclaration(matchingObjFuncSym) && Symbols.isFunctionDeclaration(
+                    referencedFunc.symbol) && !types.isAssignable(matchingObjFuncSym.type, referencedFunc.type)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:4080]: Have we added tests for when the type is a subtype?

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 20 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: Removed this as being distinct function signature is anyway tested.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 22]
```diff
@@ -698,7 +698,10 @@
 
     INTERSECTION_NOT_ALLOWED_WITH_TYPE("BCE3991", "intersection.not.allowed.with.type"),
     ASYNC_SEND_NOT_YET_SUPPORTED_AS_EXPRESSION("BCE3992", "async.send.action.not.yet.supported.as.expression"),
-    UNUSED_VARIABLE_WITH_INFERRED_TYPE_INCLUDING_ERROR("BCE3993", "unused.variable.with.inferred.type.including.error")
+    UNUSED_VARIABLE_WITH_INFERRED_TYPE_INCLUDING_ERROR("BCE3993", "unused.variable.with.inferred.type.including.error"),
+    INVALID_ITERABLE_OBJECT_TYPE("BCE3994", "invalid.iterable.type"),
+    INVALID_ITERABLE_COMPLETION_TYPE_IN_NEXT_FUNCTION("BCE3995",
+            "invalid.iterable.completion.type.in.foreach.next.function")
```
[the remark this answers is not in the document]
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java]: done

File: langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachIterableObjectTest.java (hunk 19 above)
Comment (KRVPerera) [reply langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/statements/foreach/ForeachIterableObjectTest.java]: Done
3ad22b602be3ec6627c2fb16664d805e50e39b57

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 21 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:4080]: Done e1351dd048c3acbf683c7fc39a8a829262287bea

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 23]
```diff
@@ -2701,6 +2702,12 @@ private boolean isAssignableToUnionType(BType source, BType target, Set<TypePair
             return true;
         }
 
+        if (source.tag == TypeTags.UNION && ((BUnionType) source).isCyclic) {
+            if (!unresolvedTypes.add(pair)) {
```
[the remark this answers is not in the document]
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: I changed the logic and added a comment

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 24]
```diff
@@ -698,7 +697,10 @@
 
     INTERSECTION_NOT_ALLOWED_WITH_TYPE("BCE3991", "intersection.not.allowed.with.type"),
     ASYNC_SEND_NOT_YET_SUPPORTED_AS_EXPRESSION("BCE3992", "async.send.action.not.yet.supported.as.expression"),
-    UNUSED_VARIABLE_WITH_INFERRED_TYPE_INCLUDING_ERROR("BCE3993", "unused.variable.with.inferred.type.including.error")
+    UNUSED_VARIABLE_WITH_INFERRED_TYPE_INCLUDING_ERROR("BCE3993", "unused.variable.with.inferred.type.including.error"),
+    INVALID_ITERABLE_OBJECT_TYPE("BCE3994", "invalid.iterable.type"),
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:701]:
```suggestion
    INVALID_ITERABLE_TYPE("BCE3994", "invalid.iterable.type"),
```

**Review by MaryamZi — APPROVED** [review]
