### PR TITLE
Fix type inclusions for class symbols and add BIR tests 

### LINKED ISSUE #27035: Add BIR tests for type inclusions in Semantic API
Need to $subject after the test utils are updated to support BIRs of modules.

### LINKED ISSUE #29204: [Semantic API] Type inclusions not working for class symbols
Currently `typeInclusions()` return an empty list for classes which have type inclusions. It seems that info is not getting added to the object type of the class.

### PR DESCRIPTION
**Pull request by pubudu91**
## Purpose
This PR fixes an issue with type inclusions for class symbols and adds BIR tests for type inclusions.

Fix #27035
Fix #29204 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java [hunk 1]
```diff
@@ -616,6 +616,9 @@ public void visit(BLangLiteral literalExpr) {
 
     @Override
     public void visit(BLangConstRef constRef) {
+        if (constRef.symbol != null && setEnclosingNode(constRef.symbol.owner, constRef.pkgAlias.pos)) {
+            return;
+        }
         this.symbolAtCursor = constRef.symbol;
```
Comment (Kishanthan) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java:622]: If 619 fails, then at 622 we will assign a null value?

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java:622]: Yes, that would be fine. If `symbolAtCursor` is `null` at the end it'll result in `Optional.empty()` being returned to the user.

**Review by nadeeshaan — APPROVED** [review]
LGTM
