### PR TITLE
Make objects a selectively immutable type and add tests

### LINKED ISSUE #23420: Objects should be a selectively immutable type
**Description:**
$title.

See https://github.com/ballerina-platform/ballerina-spec/commit/0784fc0c985d73836fed750d27e1540a0a4dac7f

### LINKED ISSUE #23464: If all the fields in a closed record typedesc are `readonly` the record type itself should be a subtype of `readonly`
**Description:**
$title.

The spec says

> If a record type descriptor is closed and every individual-type-descriptor specifies readonly, then it describes a type that is a subtype of readonly: a shape belongs to the type only if its read-only bit is set.

**Steps to reproduce:**
```ballerina
type Person record {|
    string name;
    int id;
|};

type Student record {|
    readonly string name;
    readonly int id;
|};


public function main() {
    Student st = {
        name: "Maryam",
        id: 1234
    };

    Person & readonly pr = st; // Should work

    readonly rd = st; // Should work
}
```

### LINKED ISSUE #23587: Fix missing flags in BIRPackageSymbolEnter and add balo tests for immutable types and readonly fields
**Description:**
$title.

For immutable types (`T & readonly`) the read-only flag is set in both the type symbol and the type.

But for BIRPackageSymbolEnter, some types
- the symbol flags aren't even written at BIRTypeWriter
- the type flags are not set, even though [read](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java#L775)

Since the read-only logic depends on the flag it may not work as expected for imported modules.

Need to fix and add balo tests for the types and for readonly record/object fields.

Can duplicate
- org.ballerinalang.test.types.readonly.SelectivelyImmutableTypeTest
- org.ballerinalang.test.record.ReadonlyRecordFieldTest
- org.ballerinalang.test.object.ReadonlyObjectFieldTest (will be introduced in https://github.com/ballerina-platform/ballerina-lang/pull/23586)

### LINKED ISSUE #23815: visitMaxs error for `T & readonly` where `T` is `anydata`, `any`, or `json`
**Description:**
@hasithaa pointed outed the following.

Compiler crashes for `json & readonly x = 1;`. With the current changes in https://github.com/ballerina-platform/ballerina-lang/pull/23795 also the same happens due to a `visitMaxs` error.

Happens with `any` and `anydata` too.

### LINKED ISSUE #23864: Implement the `readonly object`
**Description:**
See https://github.com/ballerina-platform/ballerina-spec/issues/535

### LINKED ISSUE #23901: Defaults values are not set for immutable typed fields of an immutable-typed record/object
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/http;
import ballerina/io;

type Foo record {|
    int i = 10;
    Bar b;
    http:Versioning c;
|};

type Bar record {|
    string s = "hello";
|};

public function main() {
    Foo & readonly f = {b: {}, c: {}};
    io:println(f.toJsonString());
}
```

expected `i=10 b=s=hello c=pattern=v{major}.{minor} allowNoVersion=false matchMajorVersion=false`
but prints `i=10 b=s= c=pattern= allowNoVersion=false matchMajorVersion=false`.

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$title.

Fixes #23864 - Implement the `readonly object`
Fixes #23420 - (Abstract) Objects should be a selectively immutable type
Fixes #23464 - If all the fields in a closed record typedesc are `readonly` the record type itself should be a subtype of `readonly`. Similarly objects that have all `readonly` fields are made a subtype of `readonly`.
Fixes #23587 - Fix missing flags in BIRPackageSymbolEnter and add balo tests for immutable types and readonly fields
Fixes #23901 - Defaults values are not set for immutable typed fields of an immutable-typed record/object 
Fixes  #23815 - visitMaxs error for `T & readonly` where `T` is `anydata`, `any`, or `json`

## Remarks
https://github.com/ballerina-platform/ballerina-spec/issues/535

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java [hunk 1]
```diff
@@ -1295,6 +1291,21 @@ public static boolean isSelectivelyImmutableType(BType type, Set<BType> unresolv
...
+            case TypeTags.OBJECT_TYPE_TAG:
+                BObjectType objectType = (BObjectType) type;
+
+                if (!Flags.isFlagOn(objectType.flags, Flags.ABSTRACT)) {
+                    return false;
+                }
+
+                for (BField field : objectType.getFields().values()) {
+                    BType fieldType = field.type;
+                    if (!isInherentlyImmutableType(fieldType) &&
```
Comment (rdhananjaya) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:1303]: IMO using !(A || B) is much readable than (!A && !B)

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmMethodGen.java [hunk 2]
```diff
@@ -1207,7 +1207,8 @@ private static String getFrameClassName(String pkgName, String funcName, BType a
      * @return cleaned name
      */
     static String cleanupTypeName(String name) {
-
+        name = name.replace("/", "_");
+        name = name.replace(".", "_");
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmMethodGen.java:1211]: @Kishanthan, this PR introduces some changes to support object/record intersection types, where for something like

```ballerina
import ballerina/http;

public function main() {
    http:Versioning & readonly v = {};
}
```

the name of the type of `v` has a name like `(ballerina/http:1.0.0:Versioning & readonly)`, with `/` and `.` in the name, which results in errors. So I've replaced them with `_` too.

I also had to call this method when [calculating the type field name](https://github.com/ballerina-platform/ballerina-lang/pull/23795/files#diff-49b683e4ffeab2be6da4ab1331bc3087R1455) (org.wso2.ballerinalang.compiler.bir.codegen.JvmTypeGen#getTypeFieldName), since that too would have these characters.

Do you see any issue with this change?

**Comment by KRVPerera** [comment]
Check this example too.
## Code
```Ballerina
public type ServiceAuth record {|
    readonly boolean enabled = true;
    |};

public type HttpServiceConfig record {|
    string basePath = "";
    ServiceAuth & readonly auth?;
    |};

function getServiceAuthConfig() returns ServiceAuth? {
    HttpServiceConfig serviceConfig = {
        auth : {
            enabled : false
        }
    }; 
    return serviceConfig?.auth;
}

public function main() {
    HttpServiceConfig s = {
        auth :    getServiceAuthConfig() // line number 21
    };
}
```

## Output
```LogTalk
error: .::t6_simple.bal:21:19: incompatible types: expected '(ServiceAuth & readonly)', found 'ServiceAuth?'
```

**Comment by MaryamZi** [comment]
> There is a crash here
> https://github.com/ballerina-platform/ballerina-lang/blob/3f7da3c5e89916dad69df1432e183b78ede2b992/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L1598
> 
> 
> Here `typePosPair.type` is null.
> For this example.
> 
> ```ballerina
> import ballerina/http;
> 
> public type Annot record {|
>     string foo = "";
>     (WebSocketUpgradeConfig & readonly)? webSocketUpgrade = ();
>     |};
> 
> public type WebSocketUpgradeConfig record {|
>     string upgradePath = "";
>     service upgradeService?;
>     |};
> 
> service wsService = service {
> 
>     resource function onOpen(http:WebSocketCaller caller) {
>     }
> 
> };
> 
> public function main() {
>     Annot a = {
>         webSocketUpgrade : {
>             upgradeService: wsService
>         }
>     };
> }
> ```
> 
> This is probably an earlier PR code.

Fixed in f2f98cf. Thanks!

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java (hunk 1 above)
Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java:1307]: I personally find `!A && !B` more readable, especially when there are few conditions. :D I find it easier to read "if fieldType is not inherently immutable and is not selectively immutable".
