### PR TITLE
Fix workspace manger proxy to update cloned workspace manager

### LINKED ISSUE #42910: [Bug]: Datamapper doesn't show the types defined in another file.
### Description

$title.

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
We have `BallerinaWorkspaceManager` which includes a set of methods to manage projects. It maintains two managers, `BaseWorkspaceManager` for file scheme based documents and `ClonedWorkspaceManager` for expr file scheme based documents. Currently, changes made in the editor do not update the ClonedWorkspaceManager. With this change, the ClonedWorkspaceManager will be updated whenever the BaseWorkspaceManager is updated.

Fixes #42910

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManagerProxyImpl.java [hunk 1]
```diff
@@ -84,6 +84,7 @@ public void didChange(DidChangeTextDocumentParams params) throws WorkspaceDocume
             return;
         }
         this.baseWorkspaceManager.didChange(path.get(), params);
+        this.clonedWorkspaceManager.didChange(path.get(), params);
     }
```
Comment (KavinduZoysa) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManagerProxyImpl.java:88]: Shall we change from L:82 to L:87 as shown below.
```java
        if (!this.isExprScheme(uri)) {
            this.baseWorkspaceManager.didChange(path.get(), params);
        }
        this.clonedWorkspaceManager.didChange(path.get(), params);
```

**Review by LakshanWeerasinghe — COMMENTED** [review]
Better to update the `didClose` implementation as well.

**Comment by mindula** [comment]
> Better to update the `didClose` implementation as well.

Updating `didChange` is fine for now IMO. So let's keep the `didClose` implementation as it is.

**Review by LakshanWeerasinghe — APPROVED** [review]
