### PR TITLE
Fix getting langlib methods for intersection types

### LINKED ISSUE #39292: [Bug]: LS suggests some invalid completions for Regex constructs
### Description

Consider below image, it suggests methods such as `toString` and `toBalString`. But compiler gives error when those methods are added. 

Screenshot 2023-01-18 at 12 30 42

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39485: [Bug]: Behaviour of langLibMethods() api is incorrect for intersection types
### Description

Consider the following code

```ballerina
import ballerina/lang.regexp;

public function main() {
    regexp:RegExp reg = re ``;

    regexp:Span? sp = reg.matchAt("");

    if sp is regexp:Span {
        sp.<cursor>
    } 
}

```

Here the `Span` type is defined as an `intersection` type of `readonly` and `object{}`
https://github.com/ballerina-platform/ballerina-lang/blob/6f50c2c3484c3e3d6f912c0aaa1a7cb63d70e447/langlib/lang.regexp/src/main/ballerina/regexp.bal#L27

The langLibMethods() method of the `Span` type returns langlib methods of both `readonly` type and `object` type. 
image

Ideally, the method list should contain the langLib methods of the effective type(`object` type). 
image

Since the `object` type does not have any associated langlib methods, `Span.langLibMethods()`
 should be an empty list. 

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by LakshanWeerasinghe**
## Purpose
$subject

Fixes #39485 
Fixes #39292

## Samples
Screenshot 2023-02-06 at 18 08 54

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java [hunk 1]
```diff
@@ -73,18 +73,22 @@ public TypeSymbol effectiveTypeDescriptor() {
...
     }
 
     @Override
     public List<FunctionSymbol> langLibMethods() {
         if (this.langLibFunctions == null) {
-            LangLibrary langLibrary = LangLibrary.getInstance(this.context);
-            List<FunctionSymbol> functions = langLibrary.getMethods(
-                    ((AbstractTypeSymbol) this.effectiveTypeDescriptor()).getBType());
-            this.langLibFunctions = filterLangLibMethods(functions, this.getBType());
+            if (this.effectiveTypeDescriptor().typeKind() == TypeDescKind.OBJECT) {
```
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java:84]: Why do we have to special-case here? Can't we add a case in `LangLibrary.getAssociatedLangLibName(TypeKind typeKind)` to evaluate for OBJECT?

**Review by dulajdilshan — CHANGES_REQUESTED** [review]
Please see the comment

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java (hunk 1 above)
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java:84]: Ah okay. Make sense.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java [hunk 2]
```diff
@@ -288,11 +289,11 @@ public void testRecordLangLib() {
...
-        List<String> expFunctions = List.of("length", "iterator", "get", "entries", "'map", "forEach", "filter",
-                                            "reduce", "removeIfHasKey", "remove", "removeAll", "hasKey", "keys",
-                                            "toArray", "clone", "cloneReadOnly", "cloneWithType", "isReadOnly",
-                                            "toString", "toBalString", "toJson", "toJsonString", "fromJsonWithType",
-                                            "mergeJson", "ensureType");
+        List<String> expFunctions = List.of("length", "iterator", "get", "entries", "'map", "forEach",
+                "filter", "reduce", "removeIfHasKey", "remove", "removeAll", "hasKey", "keys",
+                "toArray", "clone", "cloneReadOnly", "cloneWithType", "isReadOnly",
+                "toString", "toBalString", "toJson", "toJsonString", "fromJsonWithType",
+                "mergeJson", "ensureType");
```
Comment (dulajdilshan) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java:296]: Unnecessary formatting change is included

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java [hunk 3]
```diff
@@ -303,11 +304,11 @@ public void testTupleLangLib() {
...
-        List<String> expFunctions = List.of("length", "iterator", "enumerate", "'map", "forEach", "filter", "reduce",
-                                            "slice", "remove", "removeAll", "setLength", "indexOf", "lastIndexOf",
-                                            "reverse", "sort", "pop", "push", "shift", "unshift", "toStream", "clone",
-                                            "cloneReadOnly", "cloneWithType", "isReadOnly", "toString", "toBalString",
-                                            "toJson", "toJsonString", "fromJsonWithType", "mergeJson", "ensureType");
+        List<String> expFunctions = List.of("length", "iterator", "enumerate", "'map", "forEach", "filter",
+                "reduce", "slice", "remove", "removeAll", "setLength", "indexOf", "lastIndexOf",
+                "reverse", "sort", "pop", "push", "shift", "unshift", "toStream", "clone",
+                "cloneReadOnly", "cloneWithType", "isReadOnly", "toString", "toBalString",
+                "toJson", "toJsonString", "fromJsonWithType", "mergeJson", "ensureType");
```
Comment (dulajdilshan) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java:311]: ditto

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java [hunk 4]
```diff
@@ -330,8 +331,8 @@ public void testUnionType() {
         assertEquals(type.typeKind(), UNION);
 
         List<String> expFunctions = List.of("clone", "cloneReadOnly", "cloneWithType", "isReadOnly",
-                                            "toString", "toBalString", "toJson", "toJsonString",
-                                            "fromJsonWithType", "mergeJson", "ensureType");
+                "toString", "toBalString", "toJson", "toJsonString",
+                "fromJsonWithType", "mergeJson", "ensureType");
```
Comment (dulajdilshan) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java:335]: ditto

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java [hunk 5]
```diff
@@ -389,24 +390,35 @@ public void testIntersectionType() {
...
-                                            "setLength", "slice", "enumerate", "unshift", "'map", "indexOf",
-                                            "cloneWithType", "cloneReadOnly", "toBalString", "toJson", "isReadOnly",
-                                            "fromJsonWithType", "mergeJson", "clone", "ensureType", "toString",
-                                            "toJsonString", "some", "every");
+        List<String> expFunctions = List.of("reduce", "forEach", "shift", "length", "sort", "reverse",
+                "toStream", "remove", "push", "filter", "pop", "lastIndexOf", "iterator", "removeAll",
+                "setLength", "slice", "enumerate", "unshift", "'map", "indexOf",
+                "cloneWithType", "cloneReadOnly", "toBalString", "toJson", "isReadOnly",
+                "fromJsonWithType", "mergeJson", "clone", "ensureType", "toString",
+                "toJsonString", "some", "every");
```
Comment (dulajdilshan) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java:398]: ditto

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java [hunk 6]
```diff
@@ -343,7 +344,7 @@ public void testErrorLangLib() {
         assertEquals(type.typeKind(), ERROR);
 
         List<String> expFunctions = List.of("message", "cause", "detail", "stackTrace", "toString", "toBalString",
-                                            "ensureType", "clone", "cloneReadOnly");
+                "ensureType", "clone", "cloneReadOnly");
```
Comment (dulajdilshan) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java:348]: ditto

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java [hunk 7]
```diff
@@ -355,7 +356,7 @@ public void testStreamLangLib() {
         assertEquals(type.typeKind(), STREAM);
 
         List<String> expFunctions = List.of("filter", "next", "'map", "reduce", "forEach", "iterator", "close",
-                                            "toString", "toBalString", "ensureType");
+                "toString", "toBalString", "ensureType");
```
Comment (dulajdilshan) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java:359]: ditto

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java (hunk 2 above)
Comment (dulajdilshan) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java:296]: > Unnecessary formatting change is included

Had got opinions from a few developers. It is okay to stick with the default formatting the code-editor does

**Review by dulajdilshan — DISMISSED** [review]
LGTM

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java (hunk 2 above)
Comment (LakshanWeerasinghe) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/LangLibFunctionTest.java:296]: Got it.

**Review by IMS94 — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java (hunk 1 above)
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java:84]: if `this.effectiveTypeDescriptor().typeKind()` becomes a type reference, it will go to else part wouldn't it?
Can you try with a test
```ballerina
type FooObj object { string target; };

FooObj & readonly readonlyObjIntersec = ...
```

Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java:85]: Fixed this.

**Comment by LakshanWeerasinghe** [comment]
Screenshot 2023-02-14 at 09 37 32

Screenshot 2023-02-14 at 09 38 03

Screenshot 2023-02-14 at 10 08 16

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java [hunk 8]
```diff
@@ -73,18 +74,25 @@ public TypeSymbol effectiveTypeDescriptor() {
...
+                this.langLibFunctions = this.effectiveTypeDescriptor().langLibMethods();
+            } else if (this.effectiveTypeDescriptor().typeKind() == TypeDescKind.TYPE_REFERENCE) {
+                TypeReferenceTypeSymbol typeRef = (TypeReferenceTypeSymbol) this.effectiveTypeDescriptor();
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java:88]: This wouldn't work if it's a deeply nested type reference right? Shall we make it a recursive call to unwrap until its no longer a type ref?

Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java:88]: In here the effectiveTypeDescriptor method gives the correct result. We are using that type symbol to get the langlibs. So this is not an issue right?

```
type Type1 object {

};

type Type2 readonly & Type1;

type Type3 Type2;

type Type4 Type3;

function name() {
  Type4 t =  object {};
  t.<cursor>
}
```
I tried with the above example.

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java:88]: We are creating type symbol for each reference. But if it works you might be calling it recursively in an underlying method. Add tests as such which has more 2 references

Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java:88]: It works fine.

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java:88]: Commit those tests

Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaIntersectionTypeSymbol.java:88]: Added [166d2dce2e0d3f10338a2bd4b976c5894c4ed58d](https://github.com/ballerina-platform/ballerina-lang/pull/39520/commits/166d2dce2e0d3f10338a2bd4b976c5894c4ed58d)

**Review by malinthar — APPROVED** [review]
