### PR TITLE
Fix 'function not defined' error

### LINKED ISSUE #20871: Compiler gives an error saying the attached function is not defined even it is defined
Consider the following code.

```ballerina
stream<Person> personStream = personList.toStream();
var iterator = personStream.iterator();
record {|Person value;|}? filteredPerson = iterator.next();
```
Compiling the above code gives the below error.

`undefined function 'next' in object 'object { public function next () returns (record {| Person value; |}?); }'`

### PR DESCRIPTION
**Pull request by gimantha**
## Purpose

Fixes #20871

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java [hunk 1]
```diff
@@ -606,9 +608,8 @@ private BInvokableType getMatchingFunctionBoundType(BInvokableType expType, Symb
 
     private BType getMatchingObjectBoundType(BObjectType expType, SymbolEnv env, HashSet<BType> resolvedTypes) {
 
-        BObjectTypeSymbol actObjectSymbol = (BObjectTypeSymbol) Symbols.createObjectSymbol(0, expType.tsymbol.name,
-                                                                                           expType.tsymbol.pkgID, null,
-                                                                                           expType.tsymbol.scope.owner);
+        BObjectTypeSymbol actObjectSymbol = (BObjectTypeSymbol) Symbols.createObjectSymbol(expType.tsymbol.flags,
+                expType.tsymbol.name,expType.tsymbol.pkgID, null, expType.tsymbol.scope.owner);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java]:
```suggestion
                expType.tsymbol.name, expType.tsymbol.pkgID, null, expType.tsymbol.scope.owner);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java [hunk 2]
```diff
@@ -626,11 +627,14 @@ private BType getMatchingObjectBoundType(BObjectType expType, SymbolEnv env, Has
             BInvokableType matchType = getMatchingFunctionBoundType(expFunc.type, env, resolvedTypes);
             BInvokableSymbol invokableSymbol = new BInvokableSymbol(expFunc.symbol.tag, expFunc.symbol.flags,
                     expFunc.symbol.name, env.enclPkg.packageID, matchType, env.scope.owner);
+            invokableSymbol.retType = invokableSymbol.getType().retType;
             matchType.tsymbol = Symbols.createTypeSymbol(SymTag.FUNCTION_TYPE, invokableSymbol.flags, Names.EMPTY,
                                                          env.enclPkg.symbol.pkgID, invokableSymbol.type,
                                                          env.scope.owner);
             actObjectSymbol.attachedFuncs.add(new BAttachedFunction(expFunc.funcName, invokableSymbol, matchType));
-            actObjectSymbol.methodScope.define(expFunc.funcName, invokableSymbol);
+            String funcName = Symbols.getAttachedFuncSymbolName(actObjectSymbol.type.tsymbol.name.value,
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java]: Do we need a separate variable for this?

Comment (gimantha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java]: seems bit lengthy... otherwise can put in the same line

File: langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java [hunk 3]
```diff
@@ -49,16 +59,34 @@
     //TODO: refactor hard coded values
     public static Object next(Strand strand, ObjectValue m) {
         IteratorValue arrIterator = (IteratorValue) m.getNativeData("&iterator&");
-
+        ArrayValue arr = (ArrayValue) m.get("m");
```
Comment (MaryamZi) [inline langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java]: `get(String fieldName)` seems to be deprecated?

File: langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java [hunk 4]
```diff
@@ -49,16 +59,34 @@
...
+                if (types.size() == 1) {
+                    unionType = types.iterator().next();
+                } else {
+                    unionType = new BUnionType(new ArrayList<>(types));
+                }
+                fields.put("value", new BField(unionType, "value", Flags.PUBLIC + Flags.REQUIRED));
+            }
+
+            BRecordType recordType = new BRecordType("$$returnType$$", null, 0, fields,
+                    null, true, TypeFlags.PURETYPE);
```
Comment (MaryamZi) [inline langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java]: IIUC, the last parameter `typeFlags` indicates if the record is `anydata`, `pure` (and although irrelevant here, if nillable) right? Since this method can be called with any array/tuple, I guess we have to iterate through the member type(s) and figure out the flags here?

May have to update wherever applicable.

File: langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/Next.java [hunk 5]
```diff
@@ -20,9 +20,8 @@
 
 import org.ballerinalang.jvm.BallerinaValues;
 import org.ballerinalang.jvm.scheduling.Strand;
-import org.ballerinalang.jvm.types.BFunctionType;
-import org.ballerinalang.jvm.types.BRecordType;
-import org.ballerinalang.jvm.types.BUnionType;
+import org.ballerinalang.jvm.types.*;
```
Comment (MaryamZi) [inline langlib/lang.map/src/main/java/org/ballerinalang/langlib/map/Next.java]: * import?

File: langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java (hunk 3 above)
Comment (gimantha) [reply langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java]: will fix it.

File: langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Next.java [hunk 6]
```diff
@@ -50,14 +57,17 @@ public static Object next(Strand strand, ObjectValue m) {
         IteratorValue xmlIterator = (IteratorValue) m.getNativeData("&iterator&");
 
         if (xmlIterator == null) {
-            xmlIterator = ((XMLValue) m.get("m")).getIterator();
+            xmlIterator = ((XMLValue) m.get(new BmpStringValue("m"))).getIterator();
```
Comment (MaryamZi) [inline langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Next.java]: Should we use https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/StringUtils.java#L112 instead?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/TypeFlags.java [hunk 7]
```diff
@@ -53,4 +53,18 @@ public static int addToMask(int mask, int... flags) {
         }
         return mask;
     }
+
+    public static int getAnydataTypeFlag(BType type) {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/TypeFlags.java]: Still not sure if this belongs here. IMO, we rarely create a type at runtime. Since the type creation logic is iterator specific, shall we move this somewhere else? We can maybe combine both methods then to have a single method that does both checks.

File: langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java [hunk 8]
```diff
@@ -49,16 +60,35 @@
...
+                }
+                if (types.size() == 1) {
+                    type = types.iterator().next();
+                } else {
+                    type = new BUnionType(new ArrayList<>(types));
+                }
+            }
+
+            fields.put("value", new BField(type, "value", Flags.PUBLIC + Flags.REQUIRED));
+            BRecordType recordType = new BRecordType("$$returnType$$", null, 0, fields, null, true,
```
Comment (MaryamZi) [inline langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java]: With this approach, every time `next()` is called all these checks are done and a new type is created right? Can't we refactor this logic to maybe have the type be part of the iterator or at least add it as native data?

File: langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Next.java (hunk 6 above)
Comment (gimantha) [reply langlib/lang.xml/src/main/java/org/ballerinalang/langlib/xml/Next.java]: fixed

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/TypeFlags.java (hunk 7 above)
Comment (gimantha) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/TypeFlags.java]: Added a new jvm class IteratorUtils and added thos two methods

File: langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java (hunk 8 above)
Comment (gimantha) [reply langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Next.java]: Can we make the type be part of the iterator, because the type is always a typeParam?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+
+package org.ballerinalang.jvm;
+
+import org.ballerinalang.jvm.types.BType;
+import org.ballerinalang.jvm.types.TypeFlags;
+
+/**
+ * This class contains all the utility methods related to iterators.
+ *
+ * @since 1.2
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java]:
```suggestion
 * @since 1.2.0
```

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java [hunk 10]
```diff
@@ -0,0 +1,43 @@
...
+        }
+        return 0;
+    }
+
+    public static int getPureTypeTypeFlag(BType type) {
+        if (type.isPureType()) {
+            return TypeFlags.PURETYPE;
+        }
+        return 0;
+    }
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java]: Since we have a separate class now, shall we combine these and move the masking logic also here to a single method?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java [hunk 11]
```diff
@@ -62,6 +63,11 @@
     public static BType typePureType = new BUnionType(Arrays.asList(typeAnydata, typeError));
     public static BType typeAllType = new BUnionType(Arrays.asList(typeAny, typeError));
     public static BType typeHandle = new BHandleType(TypeConstants.HANDLE_TNAME, new BPackage(null, null, null));
+    public static BRecordType stringItrNextReturnType = new BRecordType(TypeConstants.ITERATOR_NEXT_RETURN_TYPE,
+            new BPackage(null, null, null), 0, true, TypeFlags.asMask(TypeFlags.ANYDATA,
+            TypeFlags.PURETYPE));
+    public static BRecordType xmlItrNextReturnType = new BRecordType(TypeConstants.ITERATOR_NEXT_RETURN_TYPE,
+            new BPackage(null, null, null), 0, true, 0);
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java]: Why are we setting 0 for type flags here? XML and string are both anydata and pure?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java [hunk 12]
```diff
@@ -149,4 +160,11 @@ public static BType fromString(String typeName) {
         }
         return getTypeFromName(typeName);
     }
+
+    private static Map<String, BField> createIteratorValueField(BType fieldType) {
+        HashMap<String, BField> valueFields = new HashMap<>();
+        valueFields.put("value", new BField(fieldType, "value",
+                Flags.PUBLIC + Flags.REQUIRED));
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java]: Can be combined?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java [hunk 13]
```diff
@@ -149,4 +160,11 @@ public static BType fromString(String typeName) {
         }
         return getTypeFromName(typeName);
     }
+
+    private static Map<String, BField> createIteratorValueField(BType fieldType) {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java]: Shouldn't this be in IteratorUtils?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractArrayValue.java [hunk 14]
```diff
@@ -309,6 +321,37 @@ public void setLength(long length) {
...
+            }
+            if (types.size() == 1) {
+                type = types.iterator().next();
+            } else {
+                type = new BUnionType(new ArrayList<>(types));
+            }
+        }
+
+        fields.put("value", new BField(type, "value", Flags.PUBLIC + Flags.REQUIRED));
+        iteratorNextReturnType = new BRecordType("$$returnType$$", null, 0, fields, null, true,
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractArrayValue.java]: Can't we use the constant for "$$returnType$$" here?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java (hunk 10 above)
Comment (gimantha) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java]: moved to a single method.

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java (hunk 11 above)
Comment (gimantha) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java]: fixed

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java (hunk 13 above)
Comment (gimantha) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java]: moved

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java (hunk 12 above)
Comment (gimantha) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BTypes.java]: fixed

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractArrayValue.java (hunk 14 above)
Comment (gimantha) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/AbstractArrayValue.java]: fixed

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java [hunk 15]
```diff
@@ -0,0 +1,63 @@
...
+        boolean isPureType = type.isPureType();
+        boolean isAnydata = type.isAnydata();
+
+        if (isPureType && isAnydata) {
+            return TypeFlags.asMask(TypeFlags.PURETYPE, TypeFlags.ANYDATA);
+        }
+
+        if (isAnydata) {
+            return TypeFlags.ANYDATA;
+        }
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java]: Something that's anydata is always pure right? I guess we can combine this as 

```java
        if (isAnydata) {
            return TypeFlags.asMask(TypeFlags.PURETYPE, TypeFlags.ANYDATA);
        }
```

We can then remove the `isPureType` and `isAnydata` variables too, since we won't be reusing them?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java [hunk 16]
```diff
@@ -0,0 +1,63 @@
...
+import java.util.Map;
+
+/**
+ * This class contains all the utility methods related to iterators.
+ *
+ * @since 1.2.0
+ */
+public class IteratorUtils {
+
+    public static int getTypeFlags(BType type) {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java]: Shall we add documentation for this method, since this is an iterator specific scenario? (e.g., for an ordinary scenario we would have to check the nillable flag too)

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java (hunk 15 above)
Comment (gimantha) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java]: fixed

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java (hunk 16 above)
Comment (gimantha) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java]: sure.. added

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java [hunk 17]
```diff
@@ -0,0 +1,61 @@
...
+ */
+public class IteratorUtils {
+
+    /**
+     * Returns the pure type and anydata type flags if they are available, otherwise 0. This is only used to check if
+     * the record type returned fro the next function of an iterator, is a pure type or anydata.
+     * @param type The type being checked
+     * @return The type flags
+     */
+    public static int getTypeFlags(BType type) {
```
Comment (hasithaa) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/IteratorUtils.java]: the function name is a generic one and doesn't explain what it does.

**Comment by hasithaa** [comment]
We need to add more test cases for other types. Please create an issue to track this.
