### PR TITLE
Fix compiler crash on lang lib xml iterable operations on union types

### LINKED ISSUE #42771: [Bug]: Compiler crash when using `xml:map` with an xml union type
### Description

Consider the following code,

```ballerina
public function main() {
    xml<xml:Element>|xml<xml:Comment> x1 = xml `<a><b><c><e>foo</e></c></b><d><g>bar</g></d></a>`;
    xml x2 = <xml> x1;
    _ = xml:map(xml:elements(x2), v => xml:getChildren(v));
}
```

When run this program crashes with the following log, 

```
[2024-05-17 15:01:15,937] SEVERE {b7a.log.crash} - _1 
java.lang.NoSuchFieldError: _1
        at poorna.xmlns_def.0.main.main(main.bal:183)
        at poorna.xmlns_def.0.$_init.$moduleExecute(xmlns_def)
        at poorna.xmlns_def.0.$_init.$lambda$$moduleExecute$(xmlns_def)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:320)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:287)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to Reproduce

_No response_

### Affected Version(s)

2201.9.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by poorna2152**
## Purpose
Fixes #42771

## Approach
The xml lang lib functions does not support union types. The union types are represented in the runtime as Objects. The runtime change done [here](https://github.com/ballerina-platform/ballerina-lang/pull/42150/files) caused using the XMLValue class for union types in the runtime instead of the Object class. This change is wrong. And in order to support the union types in the indexed based access in the desugar phase the variable are cast into the xml type.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -6664,8 +6664,11 @@ public void visit(BLangIndexBasedAccess indexAccessExpr) {
             targetVarRef = new BLangArrayAccessExpr(indexAccessExpr.pos, indexAccessExpr.expr,
                                                     indexAccessExpr.indexExpr);
         } else if (types.isAssignable(varRefType, symTable.xmlType)) {
-            targetVarRef = new BLangXMLAccessExpr(indexAccessExpr.pos, indexAccessExpr.expr,
-                    indexAccessExpr.indexExpr);
+            BLangExpression indexAccessExprExpr = indexAccessExpr.expr;
+            if (Types.getImpliedType(indexAccessExprExpr.getBType()).tag == TypeTags.UNION) {
+                indexAccessExprExpr = createTypeCastExpr(indexAccessExprExpr, symTable.xmlType);
+            }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:6670]: Why do we need to create a type cast here only for XML? For other types, if the expression type is a union, we do not create any type cast. Is there any reason to special-case this scenario?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java [hunk 2]
```diff
@@ -757,7 +757,7 @@ private void generateFrameClassFieldLoad(List<BIRVariableDcl> localVars, MethodV
             } else if (bType.tag == TypeTags.NEVER) {
                 mv.visitFieldInsn(GETFIELD, frameName, localVar.jvmVarName, GET_OBJECT);
                 mv.visitVarInsn(ASTORE, index);
-            } else if (types.isAssignable(bType, symbolTable.xmlType)) {
+            } else if (TypeTags.isXMLTypeTag(bType.tag)) {
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:760]: By doing this, if the `btype` is a union type, we cannot identify whether it is an XML type or not.
As I understand, the reason to do a cast in desugar is to avoid btype becoming a union. If that's the case, I think that cast is unnecessary. Can't we fix this issue here for union types instead of relying on the cast in desugar?

File: langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal [hunk 3]
```diff
@@ -1013,3 +1013,117 @@ function testNamespaces() {
     xml:Element element4 = xml:createElement("{http://sample.com/test}bookStore", attributes4, xml ``);
     assertEquals(element4.toString(), "<bookStore xmlns=\"http://sample.com/test\" status=\"online\"/>");
 }
+
+function testIterableOperationsOnUnionType() {
```
Comment (chiranSachintha) [inline langlib/langlib-test/src/test/resources/test-src/xmllib_test.bal:1017]:
```ballerina
public function main() {
    xml<xml:Element>|xml<xml:Comment> x1 = xml `<a><b><c><e>foo</e></c></b><d><g>bar</g></d></a>`;
    _ = xml:map(xml:elements(<xml> x1), v => xml:getChildren(v));
}
```
It's better to add a test case similar to the above, where you directly use the cast variable without assigning it to another variable first, and then use it.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 1 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:6670]: We do not support invocation of langlib functions on xml union types. https://github.com/ballerina-platform/ballerina-lang/issues/28697. Thus when we get a union type in order to support the indexed based access we need to type cast it to `xml`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java (hunk 2 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:760]: In the runtime we represent union types using the OBJECT type in the frame class. Thus for an xml union type it is wrong here to go inside this if condition. This was an invalid fix introduced here. https://github.com/ballerina-platform/ballerina-lang/pull/42150/files.

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:760]: My suggestion is that we do not cast here. Instead, in the `MethodGen`, if the type is a union and a subtype of XML, we can update the logic accordingly.

My concern with creating the cast here is that it is not included in the generated bytecode. Isn't that correct?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 1 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:6670]: My suggestion is that we do not cast here. Instead, in the `MethodGen`, if the type is a union and a subtype of XML, we can update the logic accordingly.

My concern with creating the cast here is that it is not included in the generated bytecode. Isn't that correct?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java (hunk 2 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:760]: Yes, for union types, we need to handle them separately.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 1 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:6670]: Had an offline chat and decided to keep this as it and remove the cast once this is addressed. https://github.com/ballerina-platform/ballerina-lang/issues/28697

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:6670]: Shall we add a comment (to-do) on the code, by mentioning the issue? If not, we can miss this

**Review by chiranSachintha — APPROVED** [review]
