### PR TITLE
Fix compiler crashes when a constant reference expression is used in an annotation

### LINKED ISSUE #42934: [Bug]: Compiler crashes when a constant reference expression is used in an annotation
### Description

$title.

Was trying this as a workaround for https://github.com/ballerina-platform/ballerina-lang/issues/42933.

### Steps to Reproduce

```ballerina
public type AnnotationRecord record {|
    string summary?;
    Examples examples?;
|};

public type Examples record {|
    map<ExampleItem> response;
|};

public type ExampleItem record {
    map<string> headers?;
};

const annotation AnnotationRecord annot on type;

const Examples EXAMPLES = {
    response: {

    }
};

@annot {
    examples: EXAMPLES
}
type Employee record {|
    int id;
    string name;
|};
```

```cmd
[2024-06-15 07:47:27,357] SEVERE {b7a.log.crash} - Cannot read field "isTestPkg" because "packageID" is null 
java.lang.NullPointerException: Cannot read field "isTestPkg" because "packageID" is null
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getPackageIdString(Types.java:6727)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getImmutableType(Types.java:6710)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSelectivelyImmutableType(Types.java:1611)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSelectivelyImmutableType(Types.java:1594)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSelectivelyImmutableType(Types.java:1589)
        at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.getImmutableType(ImmutableTypeCloner.java:173)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.updateRecordFields(ConstantValueResolver.java:872)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.createRecordType(ConstantValueResolver.java:863)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.checkType(ConstantValueResolver.java:743)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.updateConstantType(ConstantValueResolver.java:679)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.ConstantValueResolver.constructBLangConstantValueWithExactType(ConstantValueResolver.java:593)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.populateAnnotationAttachmentSymbol(SymbolResolver.java:2564)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1098)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:253)
        at org.wso2.ballerinalang.compiler.tree.BLangAnnotationAttachment.accept(BLangAnnotationAttachment.java:81)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$6(SemanticAnalyzer.java:646)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:640)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:253)
        at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:124)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4371)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4345)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:336)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:253)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
        at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:217)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:304)
        at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:184)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:110)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:435)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:383)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:211)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:195)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:102)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:97)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:244)
        at io.ballerina.projects.Package.getCompilation(Package.java:150)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:323)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:153)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:258)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

### Affected Version(s)

2201.9.1

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by LakshanWeerasinghe**
## Purpose
$subject

Fixes #42934

## Approach
Previously, when creating the `ConstantValueResolver`, the pkgId was not set, which caused the mentioned issue. This fix involves setting the pkgId when visiting the bLangPackage node in the Semantic Analyzer.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java [hunk 1]
```diff
@@ -130,6 +130,10 @@ public static ConstantValueResolver getInstance(CompilerContext context) {
         return constantValueResolver;
     }
 
+    public void setCurrentPackageId(PackageID packageID) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:133]: Instead of doing this can we see if we can enforce passing the package ID where resolve methods are called? That way we can ensure it works wherever it is called.

Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:133]: I also thought that I approach first. But the null pointer occurring place is getting invoked from [here](https://github.com/ballerina-platform/ballerina-lang/blob/7d6951bf42d40fb80482dabc30b58fb8739c9abb/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java#L874).
In this place we are passing the class level variable.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java:133]: We can have that method (overloaded probably) also accept package ID?

Comment (LakshanWeerasinghe) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java]: Updated with [commit](https://github.com/ballerina-platform/ballerina-lang/pull/43163/commits/0da8682df69d8d5409897a2a6ce40c998f1a523c).

File: tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal [hunk 2]
```diff
@@ -403,6 +403,18 @@ type Student record {|
     string name;
 |};
 
+const Examples EXAMPLES = {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal:406]: Can we add bala tests when the 
1. const referred to is from a different module
2. the type used in the const is from a different module

Comment (LakshanWeerasinghe) [reply tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal:406]: Added in [commit](https://github.com/ballerina-platform/ballerina-lang/pull/43163/commits/1453b9364a07f0a63af97c228c2774767e9bdba7).

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/annotations/annotation.bal [hunk 3]
```diff
@@ -116,6 +116,52 @@ function testAnnotationsOnTypeRefTypes() {
...
+    foo:AnnotationRecord config1 = <foo:AnnotationRecord> annot1;
+    assertEquality({"response":{}}, config1.examples);
+    assertTrue(config1.examples is readonly);
+
+    foo:Teacher teacher = {id: 1, name: "James"};
+    typedesc<any> t1 = typeof teacher;
+    foo:AnnotationRecord? annot2 = t1.@foo:annot;
+    assertTrue(annot2 is foo:AnnotationRecord);
+    foo:AnnotationRecord config2 = <foo:AnnotationRecord> annot2;
+    assertEquality({"response":{}}, config2.examples);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/annotations/annotation.bal:161]: At least for one of these shall we add a field or two in response?

Comment (LakshanWeerasinghe) [reply tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/annotations/annotation.bal:166]: Updated in [commit](https://github.com/ballerina-platform/ballerina-lang/pull/43163/commits/7d7035e087f093e437262a77f6b46597519d622e).

**Review by MaryamZi — APPROVED** [review]
