### PR TITLE
Fix runtime hangs

### LINKED ISSUE #26187: Runtime hangs when trying to use AsyncUtils invoke functions inside a for loop.
Consider the following ballerina code

```ballerina
function(transactions:Info) xx = function(transactions:Info info) {
        io:println("FFFFF");
    };
transactions:testFunc(xx);
```

The implementation of testFunc is as follows

```java
@BallerinaFunction(
        orgName = "ballerina", packageName = "lang.transaction", version = TRANSACTION_VERSION,
        functionName = "testFunc",
        args = {@Argument(name = "foo", type = TypeKind.FUNCTION)},
        returnType = {@ReturnType(type = TypeKind.NIL)},
        isPublic = true
)
public class TestFunc {

    private static final StrandMetadata METADATA = new StrandMetadata(BALLERINA_BUILTIN_PKG_PREFIX, TRANSACTION_LANG_LIB,
            TRANSACTION_VERSION, "testFunc");
    public static void testFunc(Strand strand, FPValue func) {

        for (int i = 0; i < 2;i++) {

            AsyncUtils
                    .invokeFunctionPointerAsyncIteratively(func, null, METADATA, 1,
                            () -> new Object[]{strand, null},
                            result -> {
                            }, () -> null, Scheduler.getStrand().scheduler);

        }
    }
}
```

When I execute the above ballerina code snippet runtime hangs.

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #26187 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/AsyncUtils.java [hunk 1]
```diff
@@ -157,6 +159,55 @@ public void notifyFailure(BError error) {
         invokeFunctionPointerAsync(func, strand, strandName, metadata, argsSupplier.get(), callback, scheduler);
     }
 
+    public static FutureValue invokeAndForgetFunctionPointerAsync(BFunctionPointer<?, ?> func, Strand parent,
+                                                                  String name, StrandMetadata metadata, Object[] args,
+                                                                  AsyncFunctionCallback callback,
+                                                                  Scheduler scheduler) {
+
+        final FutureValue future = scheduler.createFuture(parent, null, null,
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/AsyncUtils.java:167]: `   final FutureValue future = scheduler.createFuture(parent, null, null, ((BFunctionType) func.getType()).retType,
                                                          name, metadata);`

Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/AsyncUtils.java:167]:
```suggestion
         final FutureValue future = scheduler.createFuture(parent, null, null, ((BFunctionType) func.getType()).retType,
                                                          name, metadata);
```

**Review by warunalakshitha — APPROVED** [review]

**Comment by pcnfernando** [comment]
@gabilang  This change seems to be causing the transaction handlers not get executed. Furthermore, the https://github.com/ballerina-platform/module-ballerinai-transaction build hangs during test execution.
