### PR TITLE
Fix errors with non-capturing group runtime parsing

### LINKED ISSUE #39767: [Bug]: Regex cannot identify invalid flags for runtime error messages in runtime
### Description

```
public function main() {
    // var regExpr16 = re `(?g:ABC)`; // invalid flag in regular expression
    string:RegExp|error x1 = regexp:fromString(string `${"(?g:ABC)"}`);
    if (x1 is error) {
        io:println(<string> checkpanic x1.detail()["message"]); // Failed to parse regular expression: Invalid character ''
    }
}
```

The runtime error message should be `Failed to parse regular expression: Invalid character 'g'`.
But seems like, in runtime regex cannot identify the invalid flag

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39768: [Bug]: No proper runtime error for duplicate flags in regex
### Description

```
public function main() {
    // var regExpr16 = re `(?mi-si:ABC)`; // duplicate flag 'i'
    string:RegExp|error x1 = regexp:fromString(string `${"(?mi-si:ABC)"}`);
    if (x1 is error) {
        io:println("Error found!");
        io:println(<string> checkpanic x1.detail()["message"]);
    } else {
        io:println("No error found!");
    }
}
```

The output of the above code is `No error found!`
But it should be `duplicate flag 'i'`

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39769: [Task]: Fix the difference in parsing regular expressions in compiler time and runtime
### Description

- [x] #39768
- [x] #39767

### Describe your task(s)

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by LakshanWeerasinghe**
## Purpose
$subject

Fixes #39769 
Fixes #39768 
Fixes #39767

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java [hunk 1]
```diff
@@ -35,14 +35,17 @@
...
 import java.util.List;
+import java.util.Set;
 
 /**
  * Regular expression tree builder for Ballerina regular expression node.
  *
  * @since 2201.3.0
  */
 public class TreeBuilder {
+
```
Comment (SasinduDilshara) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:48]: Please refer to https://github.com/ballerina-platform/ballerina-lang/pull/39727#discussion_r1134956518

**Review by SasinduDilshara — CHANGES_REQUESTED** [review]

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java [hunk 2]
```diff
@@ -106,6 +109,7 @@ private RegExpTerm readRegTerm() {
             default:
                 // Read chars in ReLiteralChar, . or ReEscape.
                 reAtom = readRegChars();
+                break;
```
Comment (SasinduDilshara) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:112]: We don't need a break statement in here, since it is the last check in the switch case.

File: langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal [hunk 3]
```diff
@@ -101,3 +102,42 @@ public function testInvalidRegexpPatternSyntax5() returns error? {
...
+}
+
+function assertEqualMessage(anydata|error actual, anydata|error expected) returns error? {
+    anydata expectedValue = (expected is error)? check (<error> expected).detail().get("message").ensureType() : expected;
+    anydata actualValue = (actual is error)? check (<error> actual).detail().get("message").ensureType() : actual;
+    if expectedValue == actualValue {
+        return;
+    }
+    panic error(string `expected '${expectedValue.toBalString()}', found '${actualValue.toBalString()}'`);
+}
```
Comment (SasinduDilshara) [inline langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal:143]: Need a new line in here

File: langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal [hunk 4]
```diff
@@ -101,3 +102,42 @@ public function testInvalidRegexpPatternSyntax5() returns error? {
...
+
+public function testNegativeInvalidFlags1() returns error? {
+    anydata|error result = trap re `${"(?i-mk:ABC))"}`;
+    check assertEqualMessage(result, "Invalid insertion in regular expression: invalid flag in regular expression");
+}
+
+public function testNegativeInvalidFlags2() returns error? {
+    anydata|error result = trap re `ABC${"(?lms-xi:ABC))"}(?-:)`;
+    check assertEqualMessage(result, "Invalid insertion in regular expression: invalid flag in regular expression");
+}
```
Comment (SasinduDilshara) [inline langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal:129]: Shall we add two more tests with only `FlagOn` and only `FlagOff`.
ex:- 
```
* (?imi:(ABC))
* (?-imi:(ABC))
```

**Review by SasinduDilshara — CHANGES_REQUESTED** [review]

File: langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal [hunk 5]
```diff
@@ -101,3 +102,52 @@ public function testInvalidRegexpPatternSyntax5() returns error? {
...
+
+public function testNegativeInvalidFlags1() returns error? {
+    anydata|error result = trap re `${"(?i-mk:ABC))"}`;
+    check assertEqualMessage(result, "Invalid insertion in regular expression: invalid flag in regular expression");
+}
+
+public function testNegativeInvalidFlags2() returns error? {
+    anydata|error result = trap re `ABC${"(?lms-xi:ABC))"}(?-:)`;
+    check assertEqualMessage(result, "Invalid insertion in regular expression: invalid flag in regular expression");
```
Comment (SasinduDilshara) [inline langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal:138]: Small suggestion: Shall we add a one test that include both errors.
anydata|error result = trap re `${"(?ii-mk:ABC))"}`;

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeTraverser.java [hunk 6]
```diff
@@ -747,11 +747,11 @@ private Token readTokenInFlagsExpression() {
      * <p>
      * <code>
      * ReEscape :=
-     *    NumericEscape
-     *    | ControlEscape
```
Comment (SasinduDilshara) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeTraverser.java:751]: This formatting changes are initiated by IntelliJ setting in the local machine.
Imo, We need to remove these

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java [hunk 7]
```diff
@@ -119,7 +121,7 @@ private RegExpTerm readRegTerm() {
         }
         return new RegExpAtomQuantifier(reAtom, quantifier);
     }
-    
+
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:124]: Revert these formatings

**Review by mohanvive — APPROVED** [review]

**Review by pcnfernando — APPROVED** [review]

**Review by SasinduDilshara — APPROVED** [review]
