### PR TITLE
Fix incorrect results for the equality of floating points with non-simple types

### LINKED ISSUE #32173: Wrong float `==` behavior when type is not simple
```
import ballerina/io;

type Num float|int;

public function main() {
    Num n1 = 0.0;
    Num n2 = -0.0;
    io:println(n1 == n2);
}
```

### PR DESCRIPTION
**Pull request by gabilang**
```
import ballerina/io;

type Num float|int;

public function main() {
    Num n1 = 0.0;
    Num n2 = -0.0;
    Num n3 = 0.0/0.0;
    Num n4 = -0.0/0.0;
    Num n5 = 2.0;
    Num n6 = 2;

    io:println(n1 == n2);  // true
    io:println(n3 == n4);  // true
    io:println(n5 == n6);  // false

    io:println(n1 === n2);  // false
    io:println(n3 === n4);  // true
    io:println(n5 === n6);  // false
}
```

Fixes #32173

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 1]
```diff
@@ -467,8 +467,30 @@ public static boolean isReferenceEqual(Object lhsValue, Object rhsValue) {
         Type lhsType = getType(lhsValue);
         Type rhsType = getType(rhsValue);
 
-        if (isSimpleBasicType(lhsType) && isSimpleBasicType(rhsType)) {
-            return isEqual(lhsValue, rhsValue);
+        switch(lhsType.getTag()) {
+            case TypeTags.INT_TAG:
+                if (rhsType.getTag() != TypeTags.BYTE_TAG || rhsType.getTag() != TypeTags.INT_TAG) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:472]: What happen if we have integer sub types

Comment (warunalakshitha) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:472]: what is the difference between isReferenceEqual and isEqual for simple basic types?

Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:472]: We have used `getType` method to get the types of values. So the types of integer sub types also will be given as the type integer. Equality and exact equality checks are not same for `float` and `decimal` types. So we can't simply use `isEqual()` check of simple basic types for `isReferenceEqual()` check. Or else we need to exclude the `float` and `decimal` cases and we can handle them separately.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 2]
```diff
@@ -467,8 +467,30 @@ public static boolean isReferenceEqual(Object lhsValue, Object rhsValue) {
...
+                    return false;
+                }
+                return lhsValue.equals(((Number) rhsValue).longValue());
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:475]: Shall we have some tests for both values with same type, in order to cover these lines?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java (hunk 1 above)
Comment (warunalakshitha) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java]: Lets handle float and decimal diffrently and other types use same isEqual which will minimise code duplication.

**Review by warunalakshitha — APPROVED** [review]
