### PR TITLE
Fix few issues in diagnostics related to `readonly` and mapping/list constructor expressions

### LINKED ISSUE #23816: Issues in diagnostics for `T & readonly`
**Description:**
$title.

**Issue I**
Attempting to update an immutable value via member/field access lvexprs result in an additional error.

```ballerina
public function main() {
    readonly & string[] x = ["int"];
    x[2] = ["abc"]; // cannot update 'readonly' value of type 'string[] & readonly'
                          // incompatible types: expected 'other', found '[string]'
}  
```

**Issue II**
Errors related to anonymous records/objects print `$anonType$n`.

```ballerina
public function main() {
    readonly & record {int i;} x = {i: 1}; 
    x.i = 2; // cannot update 'readonly' value of type '($anonType$0 & readonly)'
} 
```

### LINKED ISSUE #24564: Additional error when there are issues with the applicable CET for a constructor expression
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    Foo f = {
        i: 1
    };
}
```

```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
error: .::qwe.bal:2:5: unknown type 'Foo'
error: .::qwe.bal:2:13: a type compatible with mapping constructor expressions not found in type 'other'
```

**Affected Versions:**
slp1

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$title.

These changes have been introduced on top of the changes in https://github.com/ballerina-platform/ballerina-lang/pull/24484. Need to merge that first.

Fixes #24564 - Additional error when there are issues with the applicable CET for a constructor expression
Fixes #23816 - Issues in diagnostics for `T & readonly`

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BStructureType.java [hunk 1]
```diff
@@ -49,4 +54,22 @@ public BStructureType(int tag, BTypeSymbol tSymbol, int flags) {
...
+
+        if (value.isEmpty() || value.startsWith(DOLLAR)) {
+            return true;
+        }
+
+        if (!(Symbols.isFlagOn(this.tsymbol.flags, Flags.READONLY))) {
+            return false;
+        }
+
+        return value.startsWith("($");
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BStructureType.java:73]: We have already checked part of this condition above L65. Should we return `false` here?

Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BStructureType.java:73]: Just curious what this check does?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BStructureType.java:73]: For immutable record/object types the name is something like `(T & readonly)`. So in the anonymous case it will be something like `($anonType$n & readonly)`.

We should clean this up in general though, to look at a flag maybe, instead of the name. https://github.com/ballerina-platform/ballerina-lang/issues/24471 tracks that.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -1280,7 +1280,16 @@ private BType checkListConstructorCompatibility(BType bType, BLangListConstructo
             this.dlog.setNonConsoleDLog();
 
             List<BType> compatibleTypes = new ArrayList<>();
+            boolean erroredExpType = false;
             for (BType memberType : ((BUnionType) bType).getMemberTypes()) {
+                if (memberType == symTable.semanticError) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:1285]: How can there be a semantic error in a union type?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:1285]: One example is when there's a member type that is not defined.

```ballerina
public function main() {
    Foo|int[] x = [1, 2];
}
```

We seem to be logging an `unknown type 'Foo'` error, and using semantic error as the member type.
