### PR TITLE
Fix issue with wildcard match pattern when the type of the matched `action-or-expr` includes `error`

### LINKED ISSUE #28779: Wildcard match pattern does not work as expected when the type of the matched action-or-expr includes error
**Description:**
$title.

**Steps to reproduce:**
"Matched" is not printed below. Works if the type of the variable `x` is `any` instead.

```ballerina
import ballerina/io;

public function main() {
    any|error x = 1;
    match x {
        _ => {
            io:println("Matched");
        }
    }
}
```

**Affected Versions:**
slalpha2

### PR DESCRIPTION
**Pull request by lasinicl**
## Purpose
$title

Fixes #28779

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -3489,6 +3489,11 @@ private BLangExpression createConditionForMatchPattern(BLangMatchPattern matchPa
     }
 
     private BLangExpression createConditionForWildCardMatchPattern(BLangWildCardMatchPattern wildCardMatchPattern) {
+        BLangExpression expr = wildCardMatchPattern.matchExpr;
+        if (!wildCardMatchPattern.isLastPattern && expr != null) {
+            return createIsAssignableExpression(wildCardMatchPattern.pos,
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:3494]: Shall we use `createTypeCheckExpr` instead of this. I think this is an old construct we used to have before the type-test expression. In the BirGen phase this construct is also  converted into a type-test expression.

**Review by rdhananjaya — APPROVED** [review]
