### PR TITLE
Fix issue in validating duplicate fields in record literal

### LINKED ISSUE #33046: Mapping constructor expression with duplicate fields does not give any compilation error
**Description:**
Consider the bellow sample
```bal 
function init() {
    map<any> _ = {a\\: 454, "a\\": false}; // @error Duplicate key `a\`
}
```
No error given at compile time

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$title

Fixes #33046

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/StringUtils.java [hunk 1]
```diff
@@ -125,7 +125,7 @@ public static String highlightDiagnostic(TextDocument textDocument,
      * @return modified identifier with unicode character
      */
     public static String unescapeUnicodeCodepoints(String identifier) {
-        return IdentifierUtils.unescapeUnicodeCodepoints(identifier);
+        return IdentifierUtils.unescapeBallerina(identifier);
```
Comment (lochana-chathura) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/StringUtils.java:128]: Why do we call `unescapeBallerina()` inside `unescapeUnicodeCodepoints()`? Those two methods are supposed to two different things.  
In fact, `unescapeBallerina()` calls `unescapeUnicodeCodepoint()` inside.

Comment (lochana-chathura) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/StringUtils.java:128]: ah. This seems to be a different utils class. Method names are confusing.

Comment (rdulmina) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/utils/StringUtils.java:128]: Yes will change the method names thanx

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 2]
```diff
@@ -17,6 +17,7 @@
 */
 package org.wso2.ballerinalang.compiler.semantics.analyzer;
 
+import io.ballerina.runtime.api.utils.IdentifierUtils;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:20]: I'm not sure if we should be importing something from the runtime API here. 

@warunalakshitha, @HindujaB, thoughts and/or any alternatives?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 3]
```diff
@@ -3015,8 +3016,14 @@ public void visit(BLangRecordLiteral recordLiteral) {
                 }
 
                 LinkedHashMap<String, BField> fieldsInRecordType = spreadExprRecordType.fields;
+                List<String> unescapedSpreadExprFiledNameList = new ArrayList<>();
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:3019]:
```suggestion
                List<String> unescapedSpreadExprFieldNameList = new ArrayList<>();
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 4]
```diff
@@ -3025,8 +3032,8 @@ public void visit(BLangRecordLiteral recordLiteral) {
                 }
 
                 for (BField bField : fieldsInRecordType.values()) {
-                    String name = bField.name.value;
-                    if (names.contains(name)) {
+                    String unescapedSpreadExprFiledName = IdentifierUtils.unescapeJava(bField.name.value);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:3035]:
```suggestion
                    String unescapedSpreadExprFieldName = IdentifierUtils.unescapeJava(bField.name.value);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 5]
```diff
@@ -3037,17 +3044,17 @@ public void visit(BLangRecordLiteral recordLiteral) {
                     }
 
                     if (bField.type.tag == TypeTags.NEVER) {
-                        neverTypedKeys.add(name);
+                        neverTypedKeys.add(unescapedSpreadExprFiledName);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:3047]: Can you check the codecov warning please?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 3 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:3019]: Updated thanx

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 5 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:3047]: Sure will check

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 2 above)
Comment (rdhananjaya) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:20]: I think we use this in so many places, agreed that it's better to be in a commonplace.

Comment (warunalakshitha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:20]: Yes. We already discussed moving to the new common module. Please create an issue for this.

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:20]: Created issue #33769

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 6]
```diff
@@ -3015,8 +3016,14 @@ public void visit(BLangRecordLiteral recordLiteral) {
                 }
 
                 LinkedHashMap<String, BField> fieldsInRecordType = spreadExprRecordType.fields;
+                List<String> unescapedSpreadExprFieldNameList = new ArrayList<>();
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:3019]: Do we need another list for this? Can't we update `fieldsInRecordType` to have the unescaped names instead?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java [hunk 7]
```diff
@@ -391,6 +391,26 @@ public void testReadOnlyFieldsCodeAnalysisNegative() {
         Assert.assertEquals(compileResult.getErrorCount(), index);
     }
 
+    @Test
+    public void testDuplicateFieldWithEscapeSequence() {
+        CompileResult compileResult = BCompileUtil.compile(
+                "test-src/expressions/mappingconstructor/mapping_constructor_code_analysis_negative.bal");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java:397]: Shall we rename the file to reflect that we are testing duplicate fields?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor_code_analysis_negative.bal [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+// specific language governing permissions and limitations
+// under the License.
+
+type myRecord record {|
+    int field\[ = 5;
+    never field\{?;
+|};
+
+function testDuplicateFieldWithEscapeSequence() {
+    map<int> _ = {a\\: 454, "a\\": 543};
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/mapping_constructor_code_analysis_negative.bal:23]: Shall we also add some tests for positive cases like

```ballerina
map<int> _ = {a\\: 454, "a\\\\": 543}; // error on beta3
map<int> _ = {a\\: 454, "b\\": 543};

string s = "a\\";
map<int> m = {a\\: 454, [s]: 543}; // assert that it is `{"a\":543}`
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 6 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:3019]: The thing is there is no easy way to update the keys of a `LinkedHashMap`. Also changing the original value may cause other issues in other stages.

**Review by hasithaa — APPROVED** [review]

**Review by HindujaB — APPROVED** [review]
LGTM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 6 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:3019]: Rather than updating, what I meant was creating `fieldsInRecordType` here with the unescaped names as the keys instead of directly using `spreadExprRecordType.fields`.

**Review by MaryamZi — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 6 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Updated
