### PR TITLE
Fix incorrect convertible types resolved from type-value pair set for union of records

### LINKED ISSUE #42402: [Bug]: Performance degradation observed in Ballerina version 2201.8.5 compared to 2201.8.4
### Description

A slowness is observed in the version 2201.8.5 when using `fromJsonWithType()` for binding a large json to a record. It's taking much time for conversion than 2201.8.4

### Steps to Reproduce
```ballerina
import ballerina/io;
import ballerina/time;


public type Person record {
    int id;
    string name;
    int age;
    string address;
    string? email;
    string? contact;
    string qualification;
    boolean isEmployed;
    decimal salary;
    boolean married;
    string? spouse;
    string[]? children;
};

public function main() returns error? {
    json responseJson = check io:fileReadJson("./random_data.json");
    time:Utc startTime = time:utcNow();
    Person[] _ = check responseJson.fromJsonWithType();
    time:Utc endTime = time:utcNow();
    time:Seconds difference = time:utcDiffSeconds(endTime, startTime);
    io:println("Time taken to parse the JSON: ", difference);
}
```
Output with 2201.8.5 -> 
```
Time taken to parse the JSON: 7.038689
```
Output with 2201.8.4 ->
```
Time taken to parse the JSON: 0.235574
```
[random_data.json](https://github.com/ballerina-platform/ballerina-lang/files/14758175/random_data.json)

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #42402

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by ThisaruGuruge** [comment]
Shall we link this to the internal-issue as well?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 1]
```diff
@@ -519,9 +518,13 @@ private static boolean isConvertibleToRecordType(Object sourceValue, BRecordType
             }
 
             if ((!returnVal) && (errors.size() >= MAX_CONVERSION_ERROR_COUNT + 1)) {
+                unresolvedValues.remove(typeValuePair);
                 return false;
             }
         }
+        if (!returnVal) {
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:525]: We can move this logic to a separate function (`removeTypeValuePair()`) and call it in both places. For positive and negative returns.

Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:525]: If we move it to a separate method, the check `!returnVal` will be called twice for the cases where the error message count is passing 20.

**Comment by warunalakshitha** [comment]
@gabilang Will this fix both issues?

**Comment by gabilang** [comment]
> @gabilang Did we verify this fix for both issues?

Yes, tested the fix with both https://github.com/ballerina-platform/ballerina-lang/issues/41930 and https://github.com/wso2-enterprise/internal-support-ballerina/issues/626

**Review by warunalakshitha — APPROVED** [review]
LGTM
