### PR TITLE
Fix OpenApi plugin issues

### LINKED ISSUE #17834: Cannot give relative paths to the OpenAPI file in the @openapi:ServiceInfo attribute
Refer to the image below
Screenshot from 2019-08-15 21-33-17

### LINKED ISSUE #20346: [OpenAPI] client generation doesn't generate the specify module dir for names like "module-one"
**Description:**
OpenAPI gen-client tool doesn't generate a module dir for a given module name with special characters instead generate the module name as "client" without any warnings.

ex:
```bash
ballerina openapi gen-client module-one:Client openapi_contract.yaml
```

**Suggestion**:

If the given module name contradicts with Ballerina's best practices better to provide a warning so the user knows what happened and why the name user gave didn't apply to the generated module dir.

**Affected Versions:**
1.1.0-alpha

### PR DESCRIPTION
**Pull request by gigara**
## Purpose
 Fixes the following issue.
- Cannot give relative paths to the OpenAPI file in the openapi:ServiceInfo attribute

Fixes #17834

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenServiceCmd.java [hunk 1]
```diff
@@ -112,6 +112,7 @@ public void execute() {
         final File openApiFile = new File(argList.get(0));
         final String openApiFilePath = openApiFile.getPath();
         Path resourcePath = Paths.get(resourcesDirectory + "/" + openApiFile.getName());
+        Path relativeResourcePath = Paths.get( "resources", openApiFile.getName());
```
Comment (NipunaMarcus) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenServiceCmd.java]: remove unnecessary space in front of "resources" literal.

Comment (gigara) [reply misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiGenServiceCmd.java]: Fixed efaff44cdb0fb731ba76f610f9ead17266326de2
