### PR TITLE
Remove `io.ballerina.runtime.internal.util.exceptions.BallerinaException`

### LINKED ISSUE #39256: [Task]: Remove `io.ballerina.runtime.internal.util.exceptions.BallerinaException` from the codebase
### Description

$title

### Describe your task(s)

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #39256

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by warunalakshitha — DISMISSED** [review]
Changes discussed during the syncup already addressed. LGTM

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/errors/ErrorHelper.java [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+
+    public static BString getErrorMessage(String messageFormat, Object... params) {
+        return StringUtils.fromString(MessageFormat.format(messageBundle.getString(messageFormat), params));
+    }
+
+    /**
+     * Handle any XML related exception.
+     *
+     * @param operation Operation that executed
+     * @param e Throwable to handle
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/errors/ErrorHelper.java:79]:
```suggestion
     * Handle any XML related exception.
     *
     * @param operation Operation that executed
     * @param e Throwable to handle
```
``` suggestion
     * Handle any XML related exceptions.
     *
     * @param operation Operation that is executed
     * @param e Throwable to handle
```

**Review by warunalakshitha — APPROVED** [review]
