### PR TITLE
Change run command implementation

### LINKED ISSUE #42358: [Improvement]: Improve the consistency in bal run and bal build behavior
### Description

Currently, the bal run does not generate the executable which is not consistent with the behavior in bal build + java -jar execution flow. This resulted in unexpected behaviors for manual tests (e.g https://github.com/ballerina-platform/ballerina-lang/issues/40253 is not reproducible with bal run). Also, LifeCycle compiler plugins are not executed in bal run since it is executed only after the executable is generated.

### Describe your problem(s)

_No response_

### Describe your solution(s)

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
Fixes #42358

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CreateExecutableTask.java [hunk 1]
```diff
@@ -53,29 +53,31 @@ public class CreateExecutableTask implements Task {
...
         }
     }
 
     @Override
     public void execute(Project project) {
-        this.out.println();
-
-        if (!project.buildOptions().nativeImage()) {
-            this.out.println("Generating executable");
+        if (!isHideTaskOutput) {
```
Comment (azinneera) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CreateExecutableTask.java:70]: Why do we need this flag?

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/RunCommand.java [hunk 2]
```diff
@@ -234,6 +240,19 @@ public void execute() {
...
+        Target target;
+        try {
+            if (project.kind().equals(ProjectKind.BUILD_PROJECT)) {
+                target = new Target(project.targetDir());
+            } else {
+                target = new Target(Files.createTempDirectory("ballerina-cache" + System.nanoTime()));
+                target.setOutputPath(target.getBinPath());
+            }
+        } catch (IOException e) {
+            throw createLauncherException("unable to resolve target path:" + e.getMessage());
```
Comment (azinneera) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/RunCommand.java:252]:
```suggestion
            throw createLauncherException("unable to resolve the target path:" + e.getMessage());
```

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/RunCommand.java [hunk 3]
```diff
@@ -234,6 +240,19 @@ public void execute() {
...
+        } catch (ProjectException e) {
+            throw createLauncherException("unable to create executable:" + e.getMessage());
```
Comment (azinneera) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/RunCommand.java:254]:
```suggestion
            throw createLauncherException("unable to create the executable:" + e.getMessage());
```

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CreateExecutableTask.java (hunk 1 above)
Comment (Thevakumar-Luheerathan) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CreateExecutableTask.java:70]: To maintain the consistency between the old output and the current output. I mean, to avoid printing the `Generating executable` message on the console.

**Review by azinneera — APPROVED** [review]
