### PR TITLE
[LS] Fix CCE and several bugs in function call paramater context completion provider

### LINKED ISSUE #30649: [LS] Bugs in function call expression node context completions
**Description:**

Following bugs were encountered with the respective code segments
1. CCE when there is a  visible parameter symbol
```ballerina
function getString(string myStr) returns string {
    return "hello";
}

function myFunction(function () returns string func, string city) {
    int myInt = 10;
    string mystr = "myStr";
    getString(<cursor>)
}
```

2. NoSuchElementException when the context type resolved for function call expression is empty.
```ballerina
function getString(string myStr) returns string {
    return "hello";
}

function myFunction(function () returns string func, string city) {
    int myInt = 10;
    string mystr = "myStr";
    
    myStr(<cursor>)

}
```

**Steps to reproduce:**
Try above code segments in VSCode

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject

Fixes #30649 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java [hunk 1]
```diff
@@ -258,15 +258,21 @@ public ContextTypeResolver(PositionedOperationContext context) {
...
             Predicate<Symbol> qNamePredicate =
-                    predicate.and(symbol -> symbol.getName().get().equals(qNameRef.identifier().text()));
+                    predicate.and(symbol -> symbol.getName().isPresent()
+                            && symbol.getName().get().equals(qNameRef.identifier().text()));
             funcSymbol = this.getTypeFromQNameReference(qNameRef, qNamePredicate);
         } else if (nameRef.kind() == SyntaxKind.SIMPLE_NAME_REFERENCE) {
             funcSymbol = getSymbolByName(((SimpleNameReferenceNode) nameRef).name().text());
         } else {
             return Optional.empty();
         }
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:268]: Remove this else clause now. Line 270 satisfies the empty return

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java (hunk 1 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java]: Done!

**Review by nadeeshaan — APPROVED** [review]
LGTM
