### PR TITLE
Fix wrong owner of the symbols in user-defined stream types

### LINKED ISSUE #31884: Module ID for the Stream Type Definitions are identified as `lang.annotations`
**Description:**
$title.

Consider the following source snippet, which is defined within a multi-module project. (Not in default module)

```
type ClassType Class1;

type StreamType1 stream<int>;

type StreamType2 StreamType1;

type TestRecord record {|
    
|};
```

- Consider `TestRecord` and `ClassType` where the module ID is captured as the current module's module ID - which is expected
- When we consider `StreamType1` and `StreamType2`, the module ID captured is `lang.annotations` - which is expected to capture the current module. 
When checked, the `BSymbol` itself has this wrong information captured when we access `symbol.owner` within the semantic API.

**Affected Versions:**
SwanLake-Beta2 at least

### PR DESCRIPTION
**Pull request by dulajdilshan**
Fixes #31884

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java [hunk 1]
```diff
@@ -867,6 +876,125 @@ public void testFlattenedUnionMembers() {
...
+            if (!srcFile.equals(that.srcFile)) {
+                return false;
+            }
+            if (symbolKind != that.symbolKind) {
+                return false;
+            }
+            if (!name.equals(that.name)) {
+                return false;
+            }
+            return moduleOwner.equals(that.moduleOwner);
```
Comment (pubudu91) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java:966]: Shall we combine these comparisons in to a single expression?

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java [hunk 2]
```diff
@@ -867,6 +876,125 @@ public void testFlattenedUnionMembers() {
...
+        }
+
+        @Override
+        public int hashCode() {
+            return Objects.hash(this.line,
+                                this.column,
+                                this.srcFile.hashCode(),
+                                this.symbolKind.hashCode(),
```
Comment (pubudu91) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java:974]: We are hashing the hash codes here. Can simply just pass the 2 instances right?

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java [hunk 3]
```diff
@@ -867,6 +876,125 @@ public void testFlattenedUnionMembers() {
...
+            assertTrue(actualValues.stream()
+                            .anyMatch(sym -> {
+                                LineRange lineRange = sym.getLocation().get().lineRange();
+                                LinePosition linePosition = lineRange.startLine();
+                                return val.equals(
+                                        new SymbolInfo(linePosition.line(), linePosition.offset(),
+                                                lineRange.filePath(), sym.kind(), sym.getName().get(),
+                                                ((BallerinaSymbol) sym).getInternalSymbol().owner.toString()));
+                            }),
+                    "Symbol not found: " + val);
```
Comment (pubudu91) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java:993]: `toString()` is not overridden in `SymbolInfo` right?

**Review by pubudu91 — APPROVED** [review]
