### PR TITLE
Fix `symbol()` API for Computed Keys in Mapping Constructors

### LINKED ISSUE #31803: `symbol()` not working for computed keys in mapping constructors
Consider the following where `foo` is a function. 
```ballerina
function test(string name, int age) {
    Address adrs = {city: "Colombo 3", country: "Sri Lanka"};

    Person p = {
        name: name,
        age,
        [<cursor>foo()]: "FOO",
        ...adrs
    };
}
```
If I use `symbol()` at the illustrated position, it returns empty.

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #31803

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by mohanvive — APPROVED** [review]
LGTM

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java [hunk 1]
```diff
@@ -1532,7 +1532,7 @@ public void visit(BLangRecordLiteral.BLangRecordKeyValueField recordKeyValue) {
 
     @Override
     public void visit(BLangRecordLiteral.BLangRecordKey recordKey) {
-        if (setEnclosingNode(recordKey.fieldSymbol, recordKey.pos)) {
+        if (recordKey.fieldSymbol != null && setEnclosingNode(recordKey.fieldSymbol, recordKey.pos)) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java:1535]: Why is this null check needed?

Comment (mohanvive) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java:1535]: Yes, I also wanted to check from Anjana. Do we need this change with other fix you have done here. @sanjana

Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java:1535]: @pubudu91 @mohanvive 

The null check here is essential. 

If the field has a computed key, the `fieldSymbol` is set to `null`.

https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L6556-L6570

Therefore, this null check is required to bypass this `if` condition.

Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java:1535]: Another possible approach would be as following: 

`if (!recordKey.computedKey && setEnclosingNode(recordKey.fieldSymbol, recordKey.pos))`

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java:1535]: Ah I see. I think the second approach you suggested would be better since it's more clear as to what we are checking there.

Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java]: Updated.

**Review by mohanvive — APPROVED** [review]
