### PR TITLE
Fix issue in doc analyzer

### LINKED ISSUE #10294: Issue in documenting defaultable params
**Description:**
```
# description
#
# + anInt - value of param1
function insert (int anInt = 1) {

}
```

If the parameter has a default value, it is not identified as documented.

### PR DESCRIPTION
**Pull request by Shan1024**
## Purpose
Resolves #10294

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java [hunk 1]
```diff
@@ -134,28 +137,30 @@ public void visit(BLangTypeDefinition typeDefinition) {
...
                     DiagnosticCode.NO_SUCH_DOCUMENTABLE_FIELD, DiagnosticCode.FIELD_ALREADY_DOCUMENTED);
             validateReturnParameter(typeDefinition, null, false);
         }
     }
 
     @Override
     public void visit(BLangResource resourceNode) {
-        validateParameters(resourceNode, resourceNode.getParameters(), DiagnosticCode.UNDOCUMENTED_PARAMETER,
-                DiagnosticCode.NO_SUCH_DOCUMENTABLE_PARAMETER, DiagnosticCode.PARAMETER_ALREADY_DOCUMENTED);
+        validateParameters(resourceNode, resourceNode.getParameters(), resourceNode.getDefaultableParameters(),
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java]: should we consider rest parameters as well?

Comment (Shan1024) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java]: Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/10298/commits/124252c01db7a58f2630339f2a2678a61bc27078.

Comment (hasithaa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java]: Ack.
