### PR TITLE
[master] Add support for map -> record assignment

### LINKED ISSUE #17202: Compatible map to record assignment is not allowed
**Description:**
$subject.

**Steps to reproduce:**
```ballerina
// works
record {| string...; |} x = {"a":"aaa", "b":"bbb"};
map<any> y = x;

// doesn't work. However, this should also work.
map<string> y = {"a":"aaa", "b":"bbb"};
record {| string...; |} x = y;
```

### PR DESCRIPTION
**Pull request by pubudu91**
## Samples
```ballerina
import ballerina/io;

public function main() {
    map<string> m = {"a":"aaa", "b":"bbb"};
    record {| string...; |} r = m;

    io:println(r);
} 
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -631,6 +627,21 @@ private boolean recordFieldsAssignableToMap(BRecordType recordType, BMapType tar
         return recordType.fields.stream().allMatch(field -> isAssignable(field.type, targetMapType.constraint));
     }
 
+    private boolean isAssignableMapType(BMapType sourceMapType, BRecordType targetRecType) {
+        if (targetRecType.sealed) {
+            return false;
+        }
+
+        for (BField field : targetRecType.fields) {
+            if (!Symbols.isFlagOn(field.symbol.flags, Flags.OPTIONAL) ||
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: !(isOptional && isAsignable)
Shall we refactor this use use `and` instead of `or`

File: tests/jballerina-unit-test/src/test/resources/test-src/record/negative/map_to_record_negative.bal [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+    record {|
+        Bar...;
+    |} r1 = m1;
+
+    map<Bar> m2 = {"bb": {a: 10}, "x": {a: 20}};
+    record {|
+        Baz x?;
+        Foo...;
+    |} r2 = m2;
+}
```
Comment (rdhananjaya) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/negative/map_to_record_negative.bal]: missing new line
