### PR TITLE
Fix few issues in annot processing in testerina TestProcessor

### LINKED ISSUE #34488: the `enable: false` fails to work if there is a comment on the line before it
Consider the following code. 
```ballerina
import ballerina/test;
@test:Config {
    //comment
    enable: false
}
public function testMe() {
    test:assertEquals("E", "E");
}
```

I have set `enable` as `false`. but for some reason, if I put a comment before that line inside the annotation, test will run.

SL-beta 6

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #34488 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java [hunk 1]
```diff
@@ -518,4 +528,27 @@ private void processTestAnnotation(AnnotationNode annotationNode, String functio
...
+
+        if (fieldNameNode.kind() != SyntaxKind.STRING_LITERAL) {
+            return ((Token) fieldNameNode).text();
+        }
+
+        String fieldName = ((BasicLiteralNode) fieldNameNode).literalToken().text();
+        if (fieldName.length() > 1 && fieldName.charAt(fieldName.length() - 1) == '"') {
+            fieldName = fieldName.substring(1, fieldName.length() - 1);
+        } else {
+            // Missing end quote case
```
Comment (Dilhasha) [inline misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java:548]: A missing end quote would give a compilation error. So, I think we can simply omit this else block. WDYT?

Comment (lochana-chathura) [reply misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java:548]: +1

**Review by rdulmina — APPROVED** [review]
