### PR TITLE
Set textRange information to BLangNode

### LINKED ISSUE #32176: [Semantic API] function symbols do not contain text range information
**Description:**
All the function symbols retrieved using the semantic API seem to be missing text range information, although the line range information is correct. Therefore, apparently there's no way to resolve the corresponding syntax tree node for a given symbol, as the `io.ballerina.compiler.syntax.tree.NonTerminalNode.findNode()` method of the syntax API only accept a text range.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$title

Fixes #32176

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 1]
```diff
@@ -545,8 +549,10 @@ private Location getPosition(Node startNode, Node endNode) {
         }
         LinePosition startPos = startNode.lineRange().startLine();
         LinePosition endPos = endNode.lineRange().endLine();
+        TextRange startNodeTextRange = startNode.textRange();
+        int length = startNodeTextRange.length() + endNode.textRange().length();
         return new BLangDiagnosticLocation(currentCompUnitName, startPos.line(), endPos.line(),
-                                           startPos.offset(), endPos.offset());
+                startPos.offset(), endPos.offset(), startNodeTextRange.startOffset(), length);
```
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:555]: Shall we keep the previous formating here

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:555]: Seems like we can't wrap it within the length of a line. so, please ignore this

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java [hunk 2]
```diff
@@ -42,6 +42,13 @@ public BLangDiagnosticLocation(String filePath, int startLine, int endLine, int
         this.textRange = TextRange.from(0, 0);
     }
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java:43]: Do we need this previous constructor? Will this end up confusing users/making things error prone?

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java:43]: There are places where the `TextRange` information is not available when constructing `BLangDiagnosticLocation`. But we can pass `0`s as the values to TextRange for those cases and remove the old constructor. Should we proceed with that?

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java:43]: @dulajdilshan WDYT? Is `BLangDiagnosticLocation` only used in ballerina-lang?

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java:43]: Yes, there are places we use `BlangDiagnosticLocation` outside of ballerina-lang. If we remove the previous one, the extensions also needed to be changed suddenly.  I think it would be better if we can have both constructors for now. Let's deprecate the previous one.

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java:44]: Updated

**Review by dulajdilshan — APPROVED** [review]
LGTM

**Review by pubudu91 — APPROVED** [review]
