### PR TITLE
[2201.2.0-stage] Fix type checking issue for objects with resource methods

### LINKED ISSUE #37490: No compilation error when implementation not provided for a resource function
**Description:**
In the below code, Teacher class can be instantiated even without providing the implementation for `get name()` resource function. Instantiating Teacher class should result in a compilation error  but this code complies just fine

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Person distinct service object {
    resource function get name() returns string;
};

distinct service class Teacher {
    *Person;

    resource function get salary() returns decimal {
        return 1000.00;
    }
}

public function main() returns error? {
    Person p = getPerson();
    if p is Teacher {
        io:println("Teacher");
    }
}

function getPerson() returns Person {
    Teacher t = new;
    return t;
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$title

Fixes #37490

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 1]
```diff
@@ -4546,14 +4546,11 @@ private void validateReferencedFunction(Location pos, BAttachedFunction func, Sy
             return;
         }
 
-        // Service typing does not consider resource methods when type checking.
-        if (Symbols.isResource(func.symbol)) {
-            return;
-        }
-
         // There must be an implementation at the outer level, if the function is an interface.
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:4549]: Not related to your change, but this comment isn't quite correct. Let's remove/update separately.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 2]
```diff
@@ -4546,14 +4546,11 @@ private void validateReferencedFunction(Location pos, BAttachedFunction func, Sy
...
         if (!env.enclPkg.objAttachedFunctions.contains(func.symbol)) {
-            dlog.error(pos, code, func.funcName, func.symbol.receiverSymbol.type);
+            // Here we use the whole function in the error msg since resource function name will contain `$`s if 
+            // we use the func.funcName
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:4552]: Shall we do this only for resource methods? It complicates/lengthens error messages for normal methods (the common case) and remote methods.

**Review by MaryamZi — COMMENTED** [review]
I think we need to add a significant number of tests since typing is a bit different from other methods.

e.g.,
```ballerina
type Foo client object {
    resource function get foo() returns string;
};

client class Bar {
    *Foo;
    resource function post foo() returns string => "";
}
```

And resource methods aren't the same as what they used to be in early days. 

Given the time constraints, let's try to cover as many different scenarios as possible in this PR, and create an issue if necessary to track adding more tests.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 2 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:4552]: But that will give inconsistent error messages for resource functions and other functions?

File: tests/jballerina-unit-test/src/test/resources/test-src/klass/class-def-negative.bal [hunk 3]
```diff
@@ -13,3 +13,26 @@ type C object {
     *A;
 };
 
+type ServiceObject service object {
+     resource function get name() returns string;
```
Comment (SasinduDilshara) [inline tests/jballerina-unit-test/src/test/resources/test-src/klass/class-def-negative.bal:17]: indentation is wrong.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 4]
```diff
@@ -5055,9 +5055,8 @@ private void defineReferencedFunction(Location location, Set<Flag> flagSet, Symb
             return;
         }
 
-        if (Symbols.isPrivate(referencedFuncSymbol) || Symbols.isResource(referencedFuncSymbol)) {
-            // we should not copy private functions. And we ignore the resource functions as they are not part of the
-            // type.
+        if (Symbols.isPrivate(referencedFuncSymbol)) {
+            // we should not copy private functions
```
Comment (SasinduDilshara) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:5059]: Do we have tests case for private functions in this PR

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:5059]: No that is existing code

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 2 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:4552]: That is better than complicating error messages for the common case IMO.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:4552]: And they are different from other methods anyway. Even for resource methods, we can see if we can improve the error to not include stuff that doesn't actually help to identify the method specifically (like params), and make them more uniform with other methods.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 5]
```diff
@@ -4546,14 +4546,14 @@ private void validateReferencedFunction(Location pos, BAttachedFunction func, Sy
...
-
-        // There must be an implementation at the outer level, if the function is an interface.
         if (!env.enclPkg.objAttachedFunctions.contains(func.symbol)) {
-            dlog.error(pos, code, func.funcName, func.symbol.receiverSymbol.type);
+            if (Symbols.isResource(func.symbol)) {
+                // Use the function signature in the error msg since resource function name will contain `$`s if
+                // we use the func.funcName
+                dlog.error(pos, code, func, func.symbol.receiverSymbol.type);
+            } else {
+                dlog.error(pos, code, func.funcName, func.symbol.receiverSymbol.type);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:4555]: Let's extract `func.symbol` out to a variable.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/klass/ServiceClassTest.java [hunk 6]
```diff
@@ -43,8 +43,12 @@ public void testBasicStructAsObject() {
 
     @Test
     public void testResourceMethodsDoesNotAffectAssignability() {
-        CompileResult compileResult = BCompileUtil.compile("test-src/klass/resource-method-assignability-test.bal");
-        BRunUtil.invoke(compileResult, "testServiceObjectValue");
+        CompileResult result = BCompileUtil.compile("test-src/klass/resource-method-assignability-negative.bal");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/klass/ServiceClassTest.java:46]: We usually include `test` in the file.
```suggestion
        CompileResult result = BCompileUtil.compile("test-src/klass/resource-method-assignability-negative-test.bal");
```

Not introduced by this PR, but we use underscores in bal file names.

File: tests/jballerina-unit-test/src/test/resources/test-src/klass/class-def-negative.bal [hunk 7]
```diff
@@ -13,3 +13,26 @@ type C object {
...
+    *ClientObject;
+}
+
+type ClientObject2 client object {
+    *ClientObject;
+};
+
+client class ClientClass2 {
+    *ClientObject2;
+}
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/klass/class-def-negative.bal:38]: We can also include tests where what's included is a class, rather than just an object typedesc.

**Review by MaryamZi — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/klass/ServiceClassTest.java (hunk 6 above)
Comment (rdulmina) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/klass/ServiceClassTest.java:46]: Yes, will update

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 8]
```diff
@@ -3608,11 +3609,34 @@ private boolean isInvalidNeverField(BField lhsField, BRecordType rhsType) {
...
                                                        Set<TypePair> unresolvedTypes) {
-        return rhsFuncList.stream()
+        BAttachedFunction matchingFunction = rhsFuncList.stream()
                 .filter(rhsFunc -> lhsFunc.funcName.equals(rhsFunc.funcName))
                 .filter(rhsFunc -> isFunctionTypeAssignable(rhsFunc.type, lhsFunc.type, unresolvedTypes))
                 .findFirst()
                 .orElse(null);
+        
+        // Todo: We could include this logic in `isFunctionTypeAssignable` if we have `resourcePathType` information in
+        // `BInvokableType`
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3619]: Let's create an issue.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 9]
```diff
@@ -3608,11 +3609,34 @@ private boolean isInvalidNeverField(BField lhsField, BRecordType rhsType) {
...
+        if (matchingFunction == null || 
+                !Symbols.isResource(matchingFunction.symbol) || !Symbols.isResource(lhsFunc.symbol)) {
+            return matchingFunction;
+        }
+
+        List<BType> lhsFuncResourcePathTypes = ((BResourceFunction) lhsFunc).resourcePathType.tupleTypes;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3625]: Don't we need these changes at runtime too?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 8 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3619]: #37502

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 9 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3642]: added in [64953a6](https://github.com/ballerina-platform/ballerina-lang/pull/37494/commits/64953a6b9690cf3ea747fc453cb01bc1b176428c)

**Comment by rdulmina** [comment]
Will add is exper tests

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ClientType.java [hunk 10]
```diff
@@ -0,0 +1,26 @@
...
+ *  Unless required by applicable law or agreed to in writing, software
+ *  distributed under the License is distributed on an "AS IS" BASIS,
+ *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ *  See the License for the specific language governing permissions and
+ *  limitations under the License.
+ */
+package io.ballerina.runtime.api.types;
+
+/**
+ * {@code BServiceType} represents a client object in Ballerina.
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ClientType.java:20]: Should be Client Type?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/NetworkObjectType.java [hunk 11]
```diff
@@ -0,0 +1,29 @@
...
+ *  Unless required by applicable law or agreed to in writing, software
+ *  distributed under the License is distributed on an "AS IS" BASIS,
+ *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ *  See the License for the specific language governing permissions and
+ *  limitations under the License.
+ */
+package io.ballerina.runtime.api.types;
+
+/**
+ * {@code BServiceType} represents a network object in Ballerina.
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/NetworkObjectType.java:20]: java doc needs to be corrected

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 12]
```diff
@@ -1902,6 +1950,15 @@ private static boolean checkIsServiceType(Type sourceType, Type targetType, List
         return false;
     }
 
+    private static boolean checkIsClientType(Type sourceType, Type targetType, List<TypePair> unresolvedTypes) {
+        if (sourceType.getTag() == TypeTags.CLIENT_TAG) {
+            return checkObjectEquivalency(sourceType, (BObjectType) targetType, unresolvedTypes);
+        }
+
+        // TODO: Check for client in the flags
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:1958]: Do we need this? Shall we directly  return sourceType.getTag() == TypeTags.CLIENT_TAG && checkObjectEquivalency(sourceType, (BObjectType) targetType, unresolvedTypes)

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java [hunk 13]
```diff
@@ -61,7 +61,8 @@ public class TypeTags {
     public static final int ANY_TAG = INVOKABLE_TAG + 1;
     public static final int ENDPOINT_TAG = ANY_TAG + 1;
     public static final int SERVICE_TAG = ENDPOINT_TAG + 1;
-    public static final int ARRAY_TAG = SERVICE_TAG + 1;
+    public static final int CLIENT_TAG = SERVICE_TAG + 1;
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java:64]: Since this is part of the public API, shouldn't we avoid changes like this? The value of the subsequent tags changes with this, so we should probably add CLIENT_TAG at the end.

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java:64]: Do we need CLIENT_TAG anyway? This will also break existing code if someone has checked for the object tag for clients, right?

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java:64]: It is cleaner to have CLIENT_TAG, but I'm not sure if we should do it in an update release. cc @warunalakshitha

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java:64]: On further thought, we probably should have only OBJECT_TAG, and use flags to differentiate between non-networks objects vs service objects vs client objects. We can't remove `SERVICE_TAG` now either though.

Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java:64]: We dont hardcode the values right, so changing the value of subsequent tags is ok WDYT?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java (hunk 12 above)
Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:1957]: `checkIsServiceType` uses this approach. Not sure we need this for `checkIsClientType`

https://github.com/ballerina-platform/ballerina-lang/blob/a1af3b4c1c72ca713a827fb2716346fff08b3116/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java#L1939-L1950

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java (hunk 13 above)
Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java:64]: Irrespective of how the value is assigned, what type tags are is an integer value associated with each tag. While it is not the ideal way to do it, a user may have checked for equality by the value of the tag.

For example, to check for an array they could have done
```java
type.getTag() == 32 
```

So this can be a breaking change.

Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java]: Updated with [fb79ee8](https://github.com/ballerina-platform/ballerina-lang/pull/37494/commits/fb79ee83ea126476bbc3ec0fe32f3fe952e6b081)

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java [hunk 14]
```diff
@@ -85,6 +85,7 @@ public class TypeTags {
 
     public static final int PARAMETERIZED_TYPE_TAG = READONLY_TAG + 1;
     public static final int TYPE_REFERENCED_TYPE_TAG = PARAMETERIZED_TYPE_TAG + 1;
+    public static final int CLIENT_TAG = TYPE_REFERENCED_TYPE_TAG + 1;
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java:88]: Do we really need a separate tag? Related to https://github.com/ballerina-platform/ballerina-lang/pull/37494#discussion_r955892840.

Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java:88]: Yes, for cases like https://github.com/ballerina-platform/ballerina-lang/blob/a326d859d7b74f3143307a476b234ee175712ca7/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java#L1697-L1700

We cannot use `OBJECT_TYPE_TAG` for clients.

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java:88]: Why can't we check for object tag and the client flag?

Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java:88]: We don't have a client flag in `TypeFlags.java`

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java:88]: We have it at and use it at compile-time, right? We can add use it at runtime and add it to the flags. Should be `io.ballerina.runtime.api.flags.SymbolFlags` btw.

Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/TypeTags.java]: Updated with [1f3ba1f](https://github.com/ballerina-platform/ballerina-lang/pull/37494/commits/1f3ba1fa2403bfd99c0dd830d9003032a86ba40b)

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 15]
```diff
@@ -1685,17 +1687,29 @@ private static boolean checkObjectEquivalency(Object sourceVal, Type sourceType,
...
+                (targetType.flags & SymbolFlags.CLIENT) == SymbolFlags.CLIENT) {
+            BNetworkObjectType targetNetworkObj = (BNetworkObjectType) targetType;
+            Collections.addAll(targetFuncs, targetNetworkObj.getResourceMethods());
+        }
+
+        if (sourceType.getTag() == TypeTags.SERVICE_TAG || 
+                (sourceObjectType.flags & SymbolFlags.CLIENT) == SymbolFlags.CLIENT) {
+            BNetworkObjectType sourceNetworkObj = (BNetworkObjectType) sourceObjectType;
+            Collections.addAll(sourceFuncs, sourceNetworkObj.getResourceMethods());
+        }
```
Comment (KavinduZoysa) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:1703]: I think that it will be clearer if we can write a small method and call two times with passing arguments appropriately.

Comment (rdulmina) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java]: Updated in [c7f4e52](https://github.com/ballerina-platform/ballerina-lang/pull/37494/commits/c7f4e52017b2fe3dbcede63d7fbe387cbeca5ea8)

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 16]
```diff
@@ -1816,15 +1828,46 @@ private static boolean isInSameVisibilityRegion(String lhsTypePkg, String rhsTyp
...
                                                                           unresolvedTypes))
-                .findFirst()
-                .orElse(null);
+                .findFirst();
+
+        if (matchingFunction.isEmpty()) {
+            return matchingFunction;
+        }
+        
+        MethodType matchingFunc = matchingFunction.get();
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:1844]: shall we adda a comment here for finding matching function.

**Review by warunalakshitha — APPROVED** [review]
LGTM
