### PR TITLE
Verify and Fix XML related Formatter test case scenarios

### LINKED ISSUE #25347: [Formatter] Verify and fix the XML related formatting scenarios
**Description:**
The XML scenarios in the new formatter implementation have to be verified with the Ballerina specification and fixed there are any formatting issues. The XML related tests in the formatter test suite should then be enabled.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #25347

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 1]
```diff
@@ -1186,12 +1186,16 @@ public XMLNamespaceDeclarationNode transform(XMLNamespaceDeclarationNode xMLName
         Token asKeyword = getToken(xMLNamespaceDeclarationNode.asKeyword().orElse(null));
         IdentifierToken namespacePrefix = this.modifyNode(xMLNamespaceDeclarationNode.namespacePrefix().orElse(null));
         Token semicolonToken = getToken(xMLNamespaceDeclarationNode.semicolonToken());
+        if (asKeyword != null || namespacePrefix != null) {
```
Comment (IrushiL) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:1189]: Shouldn't this be an AND expression here? Since both the `namespacePrefix` and the `asKeyword` should not be null.

File: misc/formatter/modules/formatter-core/src/test/resources/testng.xml [hunk 2]
```diff
@@ -29,6 +29,7 @@ under the License.
         <packages>
             <package name="org.ballerinalang.formatter.core.types.*" />
             <package name="org.ballerinalang.formatter.core.expressions.*" />
+            <package name="org.ballerinalang.formatter.core.statements.*" />
```
Comment (IrushiL) [inline misc/formatter/modules/formatter-core/src/test/resources/testng.xml:32]: We might have to leave this out until fixes for the rest of the statement tests are merged, if there are failing statement tests.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 1 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:1189]: The purpose of using the `OR` is, if either one of `asKeyword` or `namespacePrefix` is available (not null), then the _if_ condition would be true and both of them should be present when applying the modifications. 
Otherwise if even a single one out of them is null, there would be an assertion error generated when checking in the `Objects.requireNonNull()` methods of _tree node modifier utility_. 

And, even if the `asKeyword` is `null`, still the parser would be returning a `MISSING[as]` token if the `namespacePrefix` is present. 

Is this approach correct, or, are there any other suggestions?

File: misc/formatter/modules/formatter-core/src/test/resources/testng.xml (hunk 2 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/test/resources/testng.xml]: Fixed by limiting to `org.ballerinalang.formatter.core.statements.XMLNSDeclarationStatementsTest` only.

**Review by SupunS — COMMENTED** [review]
Are we only adding formatting support for XML namespaces? Any plans for other XML related stuff like XML literal etc?

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 1 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java]: @IrushiL, Thank you for pointing out the issue here. Fixed the logical error.

File: misc/formatter/modules/formatter-core/src/test/resources/testng.xml (hunk 2 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/test/resources/testng.xml]: Removed the `statement` package and added the `XMLNSDeclarationStatementsTest` class separately.

**Comment by IrushiL** [comment]
> Are we only adding formatting support for XML namespaces? Any plans for other XML related stuff like XML literal etc?

@SupunS XML literals are already covered under the following test cases.

https://github.com/ballerina-platform/ballerina-lang/tree/master/misc/formatter/modules/formatter-core/src/test/resources/types/sequence/assert

**Review by IrushiL — DISMISSED** [review]

**Review by IrushiL — APPROVED** [review]
