### PR TITLE
Handle casting errors

### LINKED ISSUE #27352: Static `FieldSet` interop returns error for boolean type
**Description:**
An interop function written for setting the value of a public static field of boolean type returns the following error.
```
error: casting is not supported from 'boolean' to 'java other'
```

The error seems to be thrown from the following code segment.
https://github.com/ballerina-platform/ballerina-lang/blob/2811322600380756c0804448324d7e634637e3c3/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java#L154

**Steps to reproduce:**
```java
package org.sample;
public class App {
    public static boolean testBoolean;
}
```

```ballerina
function testFunction(boolean arg) = @java:FieldSet {
    name: "testBoolean",
    class: "org.sample.App"
} external;
```

**Affected Versions:**
1.2.x and SLP5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #27352 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java [hunk 1]
```diff
@@ -372,6 +375,26 @@ private void generateCheckCastBToJDouble(MethodVisitor mv, BType sourceType) {
...
+    private void generateCheckCastBToJBoolean(MethodVisitor mv, BType sourceType) {
+
+        switch (sourceType.tag) {
+            case TypeTags.BOOLEAN:
+                break;
+            case TypeTags.HANDLE:
+                mv.visitMethodInsn(INVOKEVIRTUAL, HANDLE_VALUE, GET_VALUE_METHOD,
+                        String.format("()L%s;", OBJECT), false);
+                break;
+            case TypeTags.FINITE:
```
Comment (manuranga) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCastGen.java:387]: please add unit tests for each case.

**Review by manuranga — CHANGES_REQUESTED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/field_access_mutate_tests.bal [hunk 2]
```diff
@@ -16,6 +16,19 @@ function testStaticPrimitiveFieldMutate(int shortValue) {
...
+    boolean bool = true;
+    setBoolean(bool);
+    assertValueEquality(getBoolean(), true);
+}
+
+public type bool true|false|5;
+function testBFiniteToJBooleanCast() {
+    bool arg = true;
+    setFiniteToBoolean(arg);
+    assertValueEquality(getBoolean(), true);
```
Comment (riyafa) [inline tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/field_access_mutate_tests.bal:29]: Shall we use `test:assertEquals` from the `ballerina/test` package

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/FieldAccessMutateTest.java [hunk 3]
```diff
@@ -80,6 +80,16 @@ public void testStaticPrimitiveFieldMutate() {
         Assert.assertEquals(JavaFieldAccessMutate.aShort, 345);
     }
 
+    @Test(description = "Test static boolean field mutate")
+    public void testStaticPrimitiveFieldMutate2() {
+        BRunUtil.invoke(result, "testStaticPrimitiveFieldMutate2");
```
Comment (riyafa) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/FieldAccessMutateTest.java:85]: Shall we have a better name that gives the meaning rather than have a `2` in the method name? Probably like `testStaticBooleanFieldMutate`

Comment (gabilang) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/FieldAccessMutateTest.java:85]: I named it as `testStaticPrimitiveFieldMutate2` because already a test is available for primitive types static field. I thought it would be better to name it as 2nd test for static primitive field mutate rather than specially mention it as boolean test. That's why I gave it in the description. Furthermore, I've seen, this kind of naming habit has been used in some other tests also. WDYT?

Comment (riyafa) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/FieldAccessMutateTest.java:85]: If we could be more specific that is better IMHO. Numbering is used when we cannot be more specific. It is usually better to avoid numbers in names if we could help it.

File: tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/field_access_mutate_tests.bal (hunk 2 above)
Comment (riyafa) [reply tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/field_access_mutate_tests.bal:29]: Example usage can be seen in static_method_tests.bal : https://github.com/ballerina-platform/ballerina-lang/blob/c0d7162adc2840aa79db18464623656248cf5117/tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/static_method_tests.bal#L19

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/FieldAccessMutateTest.java (hunk 3 above)
Comment (gabilang) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/FieldAccessMutateTest.java]: Sure. resolved

File: tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/field_access_mutate_tests.bal [hunk 4]
```diff
@@ -16,6 +17,19 @@ function testStaticPrimitiveFieldMutate(int shortValue) {
     return setShortValue(shortValue);
 }
 
+function testStaticBooleanFieldMutate() {
+    boolean bool = true;
+    setBoolean(bool);
+    test:assertEquals(getBoolean(), true);
+}
+
+public type bool true|false|5;
```
Comment (riyafa) [inline tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/field_access_mutate_tests.bal:26]: It is a good practice to declare the variable before its use for vertical clarity.

**Review by riyafa — APPROVED** [review]

**Review by manuranga — APPROVED** [review]
