### PR TITLE
[Master] Allow underscore as valid XML element name

### LINKED ISSUE #36163: Valid XML in XML template gives a compilation error
**Description:**

`_` (underscore) is a valid XML element name but it can't be used in XML template.

**Steps to reproduce:**

```
$ cat issue.bal 
import ballerina/io;

public function main() {
    xml x = xml`<_/>`;
    io:println(x);
}
$ bal build issue.bal
Compiling source
	issue.bal
ERROR [issue.bal:(4:18,4:19)] '_' is a keyword, and may not be used as an identifier
error: compilation contains errors
```

**Affected Versions:**
```
$ bal version
Ballerina 2201.0.3 (Swan Lake)
Language specification 2022R1
Update Tool 1.3.9
```

### PR DESCRIPTION
**Pull request by prakanth97**
## Purpose

Fixes #36163

## Approach
`_` (underscore) is disallowed for identifier because it is a reserved keyword but it is valid for XML element name. This PR will allow it for XML. 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 1]
```diff
@@ -5427,18 +5427,22 @@ private boolean isDeclaredWithVar(Node typeNode) {
     }
 
     private BLangIdentifier createIdentifier(Token token) {
-        return createIdentifier(getPosition(token), token);
+        return createIdentifier(getPosition(token), token, false);
     }
 
-    private BLangIdentifier createIdentifier(Location pos, Token token) {
+    private BLangIdentifier createIdentifier(Token token, boolean isXML) {
```
Comment (lasinicl) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5433]: Since the `isXML` value is `false` in most cases, won't it be better if we have another overloaded method that takes just the `Location` and `Token` and use that in all other places?

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5433]: Logic change in the method `createIdentifier(Location pos, Token token, boolean isXML)` is minimal, So, is it kind a duplicating the most of the same logic into a separate overloaded method?

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5433]: Updated bf0a9741b71414b86cb2390b41aa910659db6d44

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 2]
```diff
@@ -5430,15 +5430,23 @@ private BLangIdentifier createIdentifier(Token token) {
         return createIdentifier(getPosition(token), token);
     }
 
+    private BLangIdentifier createIdentifier(Token token, boolean isXML) {
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:5433]: We don't need this method right? We can directly call `createIdentifier(Location pos, Token token, boolean isXML)` from `transform(XMLSimpleNameNode xmlSimpleNameNode)`

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java]: Corrected 234ff29a48d70dff3c6c5992ff72a7873ed7113a

**Review by rdulmina — APPROVED** [review]

**Review by lasinicl — APPROVED** [review]

**Review by hasithaa — APPROVED** [review]
Looks good to me.

**Review by pcnfernando — APPROVED** [review]
