### PR TITLE
Fix order of static listener, StopHandler shutdown

### LINKED ISSUE #40973: [Bug]: `StopHandler` functions are called before calling `gracefulStop` on all registered listeners
### Description

$title

Only `gracefulStop` on dynamic listeners are called before calling `StopHandler`s. Need to call all the module listeners `gracefulStop`.

But the spec says this
> Registers a function that will be called during graceful shutdown.
A call to `onGracefulStop` will result in one call to the handler function
that was passed as an argument; **the handler functions will be called
after calling `gracefulStop` on all registered listeners,
in reverse order of the corresponding calls to `onGracefulStop`**.

https://ballerina.io/spec/lang/master/#lang.runtime

Note that the order of `gracefulStop` function call of dynamic listeners and static listeners are different. Need to make it consistent also.

### Steps to Reproduce

```bal
import ballerina/io;
import ballerina/lang.runtime;

Listener dynamicListener1 = check new Listener("dynamic listener1");
Listener dynamicListener2 = check new Listener("dynamic listener2");
listener Listener staticListener1 = check new Listener("static listener1");
listener Listener staticListener2 = check new Listener("static listener2");


public function main() returns error? {
    io:println("main called");
    runtime:registerListener(dynamicListener1);
    runtime:registerListener(dynamicListener2);
    check dynamicListener1.'start();
    check dynamicListener2.'start();
}

public class Listener {

    *runtime:DynamicListener;
    private string name = "";

    public isolated function init(string name) returns error? {
        io:println("Calling init for " + name);
        self.name = name;
    }

    public isolated function attach(service object {} s, string[]|string? name = ()) returns error? {
        io:println("Calling attach for " + self.name);
    }

    public isolated function detach(service object {} s) returns error? {
        io:println("Calling detach for " + self.name);
    }

    public isolated function 'start() returns error? {
        io:println("Calling start for " + self.name);
    }

    public isolated function gracefulStop() returns error? {
        io:println("Calling stop for " + self.name);
    }

    public isolated function immediateStop() returns error? {
        io:println("Calling immediateStop for " + self.name);
    }
}

function init() {
   runtime:onGracefulStop(stopHandler1);
   runtime:onGracefulStop(stopHandler2);
}




public function stopHandler1() returns error? {
    io:println("stopHandler1 called");
}

public function stopHandler2() returns error? {
    io:println("stopHandler2 called");
}
```
gives
```
Running executable

Calling init for dynamic listener1
Calling init for dynamic listener2
Calling init for static listener1
Calling init for static listener2
main called
Calling start for dynamic listener1
Calling start for dynamic listener2
Calling start for static listener1
Calling start for static listener2
^CCalling stop for dynamic listener2
Calling stop for dynamic listener1
stopHandler2 called
stopHandler1 called
Calling stop for static listener1
Calling stop for static listener2
```

### Affected Version(s)

2201.6.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #40976: [Bug]: `StopHandler` errors are ignored
### Description

$title

After fixing check the behavior of stophandlers with listeners also.

https://github.com/ballerina-platform/ballerina-spec/issues/730#issuecomment-1146543367 says to be consistent with listeners.

### Steps to Reproduce

```bal
import ballerina/io;
import ballerina/lang.runtime;

// listener Listener dynamicListener2 = check new Listener("module listener");

// public class Listener {

//     *runtime:DynamicListener;
//     private string name = "";

//     public isolated function init(string name) returns error? {
//         io:println("Calling init for " + name);
//         self.name = name;
//     }

//     public isolated function attach(service object {} s, string[]|string? name = ()) returns error? {
//         io:println("Calling attach for " + self.name);
//     }

//     public isolated function detach(service object {} s) returns error? {
//         io:println("Calling detach for " + self.name);
//     }

//     public isolated function 'start() returns error? {
//         io:println("Calling start for " + self.name);
//     }

//     public isolated function gracefulStop() returns error? {
//         io:println("Calling stop for " + self.name);
//     }

//     public isolated function immediateStop() returns error? {
//         io:println("Calling immediateStop for " + self.name);
//     }
// }


function init() {
   runtime:onGracefulStop(stopHandler1);
   runtime:onGracefulStop(stopHandler2);
}

public function main() {
    io:println("main called");
}

public function stopHandler1() returns error? {
    io:println("stopHandler1 called");
    return error("error1!!!");
}

public function stopHandler2() returns error? {
    io:println("stopHandler2 called");
    return error("error2!!!");
}
```
gives
```
Running executable

main called
stopHandler2 called
stopHandler1 called
```

### Affected Version(s)

2201.6.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #40973 
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/40978
Fixes #40976

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/RuntimeRegistry.java [hunk 1]
```diff
@@ -114,6 +115,9 @@ public class ListenerCallback implements Callback {
 
         @Override
         public void notifySuccess(Object result) {
+            if (result instanceof ErrorValue errorValue) {
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/RuntimeRegistry.java:118]: we can call `RuntmUtils.handleRuntimeErrorReturns()` here and other places

File: tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/ModuleExecutionFlowTests.java [hunk 2]
```diff
@@ -212,26 +212,39 @@ public void testStopHandlerExecutionOrder() throws BallerinaTestException {
...
         serverInstance.startServer(projectPath.toAbsolutePath().toString(), projectPath.getFileName().toString(), null,
                 null, null);
-        LogLeecher logLeecherD = new LogLeecher("StopHandler2 of current module");
-        LogLeecher logLeecherE = new LogLeecher("StopHandler1 of current module");
-        LogLeecher logLeecherF = new LogLeecher("StopHandler2 of moduleA");
-        LogLeecher logLeecherG = new LogLeecher("StopHandler1 of moduleA");
-        LogLeecher logLeecherH = new LogLeecher("graceful stop of current module", LogLeecher.LeecherType.ERROR);
-        LogLeecher logLeecherI = new LogLeecher("graceful stop of ModuleA", LogLeecher.LeecherType.ERROR);
-        serverInstance.addLogLeecher(logLeecherD);
+        LogLeecher logLeecherA = new LogLeecher("Calling stop for static listener");
```
Comment (HindujaB) [inline tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/ModuleExecutionFlowTests.java:222]: Shall we add tests for panic cases as well? in `stop-handler`, `static listeners` , and `dynamic listeners`?

Comment (gabilang) [reply tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/ModuleExecutionFlowTests.java:222]: If there a panic or error return inside any call of gracefulStop() or stopHandler(), then the program terminates unsuccessfully by panicking or returning the error value. Already a test case available to cover this case https://github.com/ballerina-platform/ballerina-lang/blob/c7c5ee4745f702532c6f24821e2e9fa093de676a/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/ModuleExecutionFlowTests.java#L105

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/RuntimeUtils.java [hunk 3]
```diff
@@ -150,13 +150,18 @@ private static void printToConsole(ErrorValue throwable) {
...
-        if (returnValue instanceof ErrorValue) {
-            ErrorValue errorValue = (ErrorValue) returnValue;
+        if (returnValue instanceof ErrorValue errorValue) {
             errStream.println("error: " + errorValue.getPrintableError());
             Runtime.getRuntime().exit(1);
         }
     }
 
+    public static void handleRuntimeErrorReturns(Object returnValue) {
+        if (returnValue instanceof ErrorValue errorValue) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/RuntimeUtils.java:160]: Can we have any other value than ErrorValue. What happen if we have any other value?

Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/RuntimeUtils.java]: Removed this unused code block since when there is a error return we need to terminate the program execution by returning the error value.

Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/RuntimeUtils.java:160]: Restored this method since it's needed for give the console output when errors are returned from the `gracefulStop()` methods of dynamic listeners and the functions registered with the `runtime:onGracefulStop`. 



> Can we have any other value than ErrorValue. What happen if we have any other value?

Yes, it's actually the return values of the functions. If there a error return from the main, the error message will be added to the console output and exit the program gracefully. If an error returns from any function which is a part of the shutdown sequence (where the user do not have the control to handle the error returns from their end), the error message also needed to be logged into the console similar to the error returns of main.

**Review by warunalakshitha — COMMENTED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
