### PR TITLE
Fix Cloneable and readonly assignability to any and any|error

### LINKED ISSUE #27944: `value:Cloneable` can be assigned to `any`
**Description:**
$title. Shouldn't be allowed since `value:Cloneable` contains `error`.

**Steps to reproduce:**
```ballerina
import ballerina/lang.value;

public function main() {
    value:Cloneable x = error("x");
    any y = x; // Should fail since `value:Cloneable` includes `error` and `x` can hold an error.
}
```

**Affected Versions:**
slp9-SNAPSHOT

### PR DESCRIPTION
**Pull request by KRVPerera**
## Purpose
1. Now we cannot assign `readonly` to `any`. As a side effect `value:Cloneable` is also not assignable to `any`. 
2. We can assign `readonly` to `any|erorr` now.

Fixes #27944
part of https://github.com/ballerina-platform/ballerina-lang/issues/24319

Message:

Breaking Changes

With the changes introduced in this PR. Now ballerina compiler does not allow programmers to assign `readonly` type `any`. This change propagates to any unions created using `readonly`.
As an example, this affects `value:Cloneable` type which is used in methods `clone` and `cloneReadonly` methods. Therefore if you are using `value:Cloneable` directly you will now start seeing errors for assignment to `any` type.

```Ballerina
import ballerina/lang.'value;

public function main() {
    value:Cloneable cloneableValue = 45;
    // any anyValue = cloneableValue;      // not allowed
    any|error anyOrErrorValue = cloneableValue;

    readonly readonlyValue = 45;
    // anyValue = readonlyValue;  // not allowed
    anyOrErrorValue = readonlyValue;

    readonly|any anyOrReadonly = 45;
    // anyValue = anyOrReadonly; // not allowed
    anyOrErrorValue = anyOrReadonly;
}
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by MaryamZi** [comment]
Need to fix runtime checks too.

```ballerina
public function main() {
    any a = foo;
    boolean x = a is function () returns any; // currently true, should be false
}

function foo() returns readonly => 1;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -812,8 +816,17 @@ private boolean isAssignable(BType source, BType target, Set<TypePair> unresolve
             }
         }
 
-        if (targetTag == TypeTags.READONLY &&
-                (isInherentlyImmutableType(source) || Symbols.isFlagOn(source.flags, Flags.READONLY))) {
+        if (targetTag == TypeTags.READONLY) {
+            if ((isInherentlyImmutableType(source) || Symbols.isFlagOn(source.flags, Flags.READONLY))) {
+                return true;
+            }
+            // TODO: check this will make `any|error is readonly` always true
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:823]: Is this comment still valid? The following doesn't give an error and compiles, as expected.

```ballerina
public function main() {
    any|error x = 1;
    boolean b = x is readonly;
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 2]
```diff
@@ -2216,9 +2233,14 @@ public boolean isTypeCastable(BLangExpression expr, BType sourceType, BType targ
             return true;
         }
 
+
+        if (sourceType.tag == TypeTags.ANY && targetType.tag == TypeTags.READONLY) {
+            return true;
+        }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:2239]: Need to allow source - readonly and target - any too, right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 3]
```diff
@@ -2216,9 +2233,14 @@ public boolean isTypeCastable(BLangExpression expr, BType sourceType, BType targ
...
         boolean validTypeCast = false;
 
-        if (sourceType.tag == TypeTags.UNION) {
+        // support anydata and json
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:2242]: Shall we say something along the lines of 

```suggestion
        // Use instanceof to check for anydata and json.
```

Or it may not be clear why we are doing an instanceof check.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 4]
```diff
@@ -2227,7 +2249,8 @@ public boolean isTypeCastable(BLangExpression expr, BType sourceType, BType targ
             }
         }
 
-        if (targetType.tag == TypeTags.UNION) {
+        // support anydata and json
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:2252]:
```suggestion
        // Use instanceof to check for anydata and json.
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 5]
```diff
@@ -3614,11 +3647,22 @@ public BType getRemainingType(BType originalType, BType typeToRemove) {
...
             case TypeTags.FINITE:
                 return getRemainingType((BFiniteType) originalType, getAllTypes(typeToRemove));
+            case TypeTags.READONLY:
+                return getRemainingType((BReadonlyType) originalType, typeToRemove);
             default:
                 return originalType;
         }
     }
 
+    // TODO: now only works for error. Probably we need to properly define readonly types here.
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3657]: Should we create an issue for this?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 6]
```diff
@@ -3895,9 +3939,35 @@ private BType validateOverlappingFields(BRecordType recordType, BField origField
         return symTable.semanticError;
     }
 
+    private void removeErrorFromCompoundTypes(List<BType> remainingTypes) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3942]: This only removes error from readonly right? Shall we update the name of the method to reflect this?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 7]
```diff
@@ -3895,9 +3939,35 @@ private BType validateOverlappingFields(BRecordType recordType, BField origField
...
+        Iterator<BType> remainingIterator = remainingTypes.listIterator();
+        boolean needToAddAnyAndReadonly = false;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3944]: Can't we just call this
```suggestion
        boolean addAnyAndReadonly = false;
```

File: docs/bir-spec/src/test/resources/test-src/values.bal [hunk 8]
```diff
@@ -220,15 +232,21 @@ function testMappingJsonWithIntersectionMergeFailure1() returns boolean {
...
-            mj.detail()[MESSAGE].toString() != "JSON Merge failed for key 'two'") {
-        return false;
+    if (mj is error) {
+        var mjDetail = mj.detail()[MESSAGE];
+        string detailString = mjDetail is error ? mjDetail.toString() : mjDetail.toString();
+        if (mj.message() != MERGE_JSON_ERROR_REASON ||
+                detailString != "JSON Merge failed for key 'two'") {
+            return false;
+        }
     }
```
Comment (MaryamZi) [inline docs/bir-spec/src/test/resources/test-src/values.bal:242]: Should we have an else block that returns false here?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 2 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:2239]: Not sure. We cannot cast out error type. 
```Java
public boolean isTypeCastable(BLangExpression expr, BType sourceType, BType targetType, SymbolEnv env) {
        if (getTypeIntersection(sourceType, symTable.errorType, env) != symTable.semanticError
                && getTypeIntersection(targetType, symTable.errorType, env) == symTable.semanticError) {
            return false;
        }
```

This condition is false.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal [hunk 9]
```diff
@@ -192,18 +196,22 @@ function testSimpleInitializationForSelectivelyImmutableMappingTypes() {
...
-    assertEquality(<Details> {name: "Jo", id: 4567}, stVal.details);
-
-    assertTrue(stVal["math"] is [RESULT, int] & readonly);
-    assertTrue(stVal["math"].isReadOnly());
-    assertEquality(<[RESULT, int]> ["P", 75], stVal["math"]);
-
-    assertTrue(stVal["science"] is [RESULT, int] & readonly);
-    assertTrue(stVal["science"].isReadOnly());
-    assertEquality(<[RESULT, int]> ["P", 65], stVal["science"]);
+    if (val is error) {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal:199]: I think we can do 

```
assertFalse(val is error);
```

and move the logic in the else block also out.

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal:199]: Applicable in other places too.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 1 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Yes no need of this now.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 2 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:2232]: Yes, my bad!

The following works.
```ballerina
public function main() {
    readonly x = 1;
    any y = <any> checkpanic x;
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal (hunk 9 above)
Comment (KRVPerera) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal:199]: I changed val to `any|error` type. Because of this cannot cast out error from this right?
incompatible types: '(any|error)' cannot be cast to 'Employee'
incompatible types: '(any|error)' cannot be cast to 'Student'

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java [hunk 10]
```diff
@@ -185,6 +185,10 @@
     public static final RecordType XML_ITR_NEXT_RETURN_PI_TYPE =
             IteratorUtils.createIteratorNextReturnType(TYPE_PROCESSING_INSTRUCTION);
 
+    public static final Type ANY_AND_READONLY_TYPE =
+            ReadOnlyUtils.setImmutableTypeAndGetEffectiveType(new BUnionType(Arrays.asList(TYPE_READONLY, TYPE_ANY)));
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java:189]: Why are we passing the union? Only any is enough, right?

```suggestion
            ReadOnlyUtils.setImmutableTypeAndGetEffectiveType(TYPE_ANY);
```

Comment (KRVPerera) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java:189]: Oh yes.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java [hunk 11]
```diff
@@ -242,5 +246,8 @@
         TYPE_DETAIL = new BMapType(TypeConstants.MAP_TNAME, TYPE_CLONEABLE, EMPTY_MODULE);
         TYPE_ERROR_DETAIL = ReadOnlyUtils.setImmutableTypeAndGetEffectiveType(TYPE_DETAIL);
         TYPE_ERROR = new BErrorType(TypeConstants.ERROR, EMPTY_MODULE, TYPE_DETAIL);
+        ANY_AND_READONLY_OR_ERROR_TYPE =
+        ReadOnlyUtils.setImmutableTypeAndGetEffectiveType(new BUnionType(Arrays.asList(ANY_AND_READONLY_TYPE,
+                TYPE_ERROR)));
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/PredefinedTypes.java:251]: We don't have to call `setImmutableTypeAndGetEffectiveType` here right? We just need the union. The union initialization logic will actually mark this as an immutable union, so IINM this call is unnecessary anyway.

```suggestion
        new BUnionType(Arrays.asList(ANY_AND_READONLY_TYPE, TYPE_ERROR));
```

Let's also fix the indentation here.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal (hunk 9 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/readonly/test_selectively_immutable_type.bal:199]: We can do `Employee rec = <Employee> checkpanic val;`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java [hunk 12]
```diff
@@ -283,6 +284,12 @@ private SymbolTable(CompilerContext context) {
                 ImmutableTypeCloner.getImmutableIntersectionType((SelectivelyImmutableReferenceType) this.anyType,
                         this, names);
         initializeType(this.anyAndReadonly, this.anyAndReadonly.effectiveType.name.getValue(), BUILTIN);
+
+        defineReadonlyCompoundType();
+    }
+
+    private void defineReadonlyCompoundType() {
+        anyAndReadonlyOrError = BUnionType.create(null, anyAndReadonly, errorType);
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java:292]: WDYT of inlining this method?

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java:292]: I was thinking we need to move more of the code into appropriate functions to keep the constructor clean and easy to read.

File: docs/bir-spec/src/test/resources/test-src/values.bal [hunk 13]
```diff
@@ -175,26 +175,38 @@ function testNonNilNonMappingJsonMerge() returns boolean {
...
 function testMappingJsonAndNonMappingJsonMerge1() returns boolean {
     json j1 = { one: "hello", two: "world", three: 1 };
     json j2 = "string value";
 
     json|error mj = j1.mergeJson(j2);
+    var mjDetail = mj is error ? mj.detail()[MESSAGE] : ();
+    string detailString = mjDetail is error ? mjDetail.toString() : mjDetail.toString();
     return mj is error && mj.message() == MERGE_JSON_ERROR_REASON &&
-        mj.detail()[MESSAGE].toString() == "Cannot merge JSON values of types 'map<json>' and 'string'";
+        detailString == "Cannot merge JSON values of types 'map<json>' and 'string'";
```
Comment (MaryamZi) [inline docs/bir-spec/src/test/resources/test-src/values.bal:195]: In these scenarios `mj.detail()[MESSAGE]` is most probably a `string` value.

So we can probably just do

```ballerina
return mj is error && mj.message() == MERGE_JSON_ERROR_REASON &&
        <string> checkpanic mj.detail()[MESSAGE] == "Cannot merge JSON values of types 'map<json>' and 'string'";
```

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/readonly/test_selectively_immutable_type.bal [hunk 14]
```diff
@@ -137,52 +137,61 @@ function testImmutableMappings() {
...
+                id: 4567
+            },
+            department: "IT"
+        };
+
+        assertFalse(d is se:Employee & readonly);
+        assertTrue(d is se:Employee);
+
+        assertEquality(emp2, d);
+    }
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/readonly/test_selectively_immutable_type.bal:167]: Can't we do

```ballerina
assertFalse(val is error);
// Logic in else blocl
```

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/readonly/test_selectively_immutable_type.bal [hunk 15]
```diff
@@ -137,52 +137,61 @@ function testImmutableMappings() {
...
+    any val2 = d;
+    se:Employee rec = <se:Employee> val2;
+    //assertFalse(rec is se:Employee & readonly);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/readonly/test_selectively_immutable_type.bal:170]: Why are we commenting this out?

**Review by MaryamZi — COMMENTED** [review]
@KRVPerera, let's introduce the suggested changes in a separate PR.

**Review by MaryamZi — APPROVED** [review]
