### PR TITLE
Use same symbol within type definition type and reference type

### LINKED ISSUE #34102: Compilation error when casting a `Cloneable` to 'string'
**Description:**
When updated to the latest Ballerina version, the WebSocket module fails giving the error,
` incompatible types: 'ballerina/lang.value:0.0.0:Cloneable' cannot be cast to 'string'
`
Related workflow run: https://github.com/ballerina-platform/module-ballerina-websocket/runs/4391319180?check_suite_focus=true

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #34102

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java [hunk 1]
```diff
@@ -378,6 +378,7 @@ public void testFromJsonWithType(String function) {
     @Test
     public void testAssigningCloneableToAnyOrError() {
         BRunUtil.invokeFunction(compileResult, "testAssigningCloneableToAnyOrError");
+        BRunUtil.invokeFunction(compileResult, "testUsingCloneableReturnType");
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/LangLibValueTest.java:381]: This should be a separate test?

**Review by MaryamZi — APPROVED** [review]
