### PR TITLE
Change completion item order for qualified name reference and cache current document

### LINKED ISSUE #30378: Incomplete suggestions in some cases
**Description:**
$title. For constructs from an imported module.

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Foo record {|
    xml x;
|};

public function main() returns error? {
    Foo foo = {x: xml `<foo>hello</foo>`};

    json j = foo.toJson();
    io:p<cursor>

    Foo|error r1 = j.cloneWithType(); 
    io:println(r1);

    // doesn't work here

    Foo|error r2 = j.fromJsonWithType();
    io:println(r2);

    // works here
}
```

Note how the functions aren't suggested.

suggestions

**Affected Versions:**
slalpha5

### LINKED ISSUE #32555: Prioritise methods when showing completions for module
**Description:**
Check the below figure. It would be great if we optimise the completions to show the methods before the variables.

Screenshot 2021-08-30 at 13 41 40

### LINKED ISSUE #32753: Cache current document at DocumentServiceContext level
**Description:**
Cache the `currentDocument()` at `AbstractDocumentServiceContext` to have better performance for LS features.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose
Fixes #32555
Fixes #32753
Fixes #30378

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by mohanvive — DISMISSED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java [hunk 1]
```diff
@@ -143,7 +143,7 @@ void setClientCapabilities(LSClientCapabilities clientCapabilities) {
                     position.getPosition());
             try {
                 return LangExtensionDelegator.instance()
-                        .completion(position, context, this.serverContext, cancelChecker);
+                        .completion(position, context, this.serverContext, null);
```
Comment (mohanvive) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java:146]: @nadeeshaan can you please verify this change again? Looks incorrect.

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java]: Rectified.

**Review by mohanvive — DISMISSED** [review]

**Review by mohanvive — APPROVED** [review]
