### PR TITLE
Move native image implementation to JBallerinaBackend class

### LINKED ISSUE #38379: [Bug]: Execute compiler plugins after the native image generation
### Description

Compiler plugins must be executed after the native image gets generated. Currently the plugins are notified during the test execution task. 

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> ProjectAPI

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Ibaqu**
Fixes #38379 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by Ibaqu** [comment]
Please note there is a slight change to the output printed on the console. 

```
~/Documents/projects/issues/38379 ❯ /Users/ibaqu/Documents/repositories/work/ballerina-lang/distribution/zip/jballerina-tools/build/distributions/jballerina-tools-2201.3.0-rc2-SNAPSHOT/bin/bal build --native
WARNING : Native image generation is an experimental feature, which supports only a limited set of functionality.
Compiling source
        ibaqu/app38379:0.1.0
WARNING [main.bal:(4:5,4:17)] unused variable 'a'

Generating executable with Native image
============================================================================================
GraalVM Native Image: Generating 'app38379' (executable)...
============================================================================================
[1/7] Initializing...                                                                                    (3.9s @ 0.26GB)
[2/7] Performing analysis...  [********]                                                                (17.3s @ 2.92GB)
[3/7] Building universe...                                                                               (4.3s @ 0.83GB)
[4/7] Parsing methods...      [**]                                                                       (2.0s @ 3.71GB)
[5/7] Inlining methods...     [***]                                                                      (1.5s @ 1.34GB)
[6/7] Compiling methods...    [****]                                                                    (17.8s @ 3.98GB)
[7/7] Creating image...                                                                                  (3.3s @ 1.71GB)
  24.16MB (59.13%) for code area:    32,892 compilation units
  16.14MB (39.51%) for image heap:  183,626 objects and 10 resources
 568.30KB ( 1.36%) for other data
  40.85MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
1009.59KB java.lang.invoke                                     4.27MB byte[] for code metadata
...
------------------------------------------------------------------------------------------------------------------------
                        4.5s (8.4% of total time) in 27 GCs | Peak RSS: 4.15GB | CPU load: 4.66
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /Users/ibaqu/Documents/projects/issues/38379/target/bin/app38379 (executable)
 /Users/ibaqu/Documents/projects/issues/38379/target/bin/app38379.build_artifacts.txt (txt)
========================================================================================================================
Finished generating 'app38379' in 53.2s.
        target/bin/app38379.jar
```

As we cannot print the executable paths within the JBallerina backend class, I have changed the output to include `Generating executable with Native image`

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java [hunk 1]
```diff
@@ -530,6 +534,63 @@ private Path emitExecutable(Path executableFilePath) {
...
+        Manifest manifest = createManifest();
+        Collection<JarLibrary> jarLibraries = jarResolver.getJarFilePathsRequiredForExecution();
+
+        try {
+            assembleExecutableJar(executableFilePath, manifest, jarLibraries);
+        } catch (IOException e) {
+            throw new ProjectException("error while creating the executable jar file for package '" +
+                    this.packageContext.packageName().toString() + "' : " + e.getMessage(), e);
+        }
+
```
Comment (xlight05) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java:548]: Can't we call the `emitExecutable` method instead of repeating this code?

Comment (Ibaqu) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java]: I called the emitExecutable method

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java [hunk 2]
```diff
@@ -530,6 +535,56 @@ private Path emitExecutable(Path executableFilePath) {
...
+                throw new ProjectException("unable to create native image");
+            }
+        } catch (IOException e) {
+            throw new ProjectException("unable to create native image:" + e.getMessage());
+        } catch (InterruptedException e) {
+            Thread.currentThread().interrupt();
+        }
+
+        Path graalexectablepath = Path.of(FilenameUtils.removeExtension(executableFilePath.toString()));
+        System.out.println(graalexectablepath);
```
Comment (xlight05) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java:584]: Do we need this?

**Review by azinneera — APPROVED** [review]
