### PR TITLE
Fix issue in expression string value created for value with cycles

### LINKED ISSUE #26490: 0-based index not correctly given for values with cycles in expression style string
**Description:**
When cycles are detected, the expression style string value is `...[N]` where N is a 0-based index down the path from root object to object where the cycle is detected. The value of `N` is not correctly given ATM. This affects fromBalString() as well.

### PR DESCRIPTION
**Pull request by lasinicl**
Fixes #26490

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/BalStringUtils.java [hunk 1]
```diff
@@ -168,12 +195,12 @@ public static Object parseMapExpressionStringValue(String exprValue) {
...
      * @return table value
      */
-    public static Object parseTableExpressionStringValue(String exprValue) {
+    public static Object parseTableExpressionStringValue(String exprValue, BLink parent) {
         String[] keys = exprValue.substring
                 (exprValue.indexOf('(') + 1, exprValue.indexOf(')')).split(",");
         ArrayValue fieldNames = (ArrayValue) ValueCreator.createArrayValue(StringUtils.fromStringArray(keys));
         ArrayValueImpl data = (ArrayValueImpl) StringUtils.parseExpressionStringValue(exprValue.substring
-                (exprValue.indexOf(')') + 2));
+                (exprValue.indexOf(')') + 2), parent);
```
Comment (gimantha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/BalStringUtils.java:203]: shall we put a comment what this "2" means?

**Review by gimantha — APPROVED** [review]

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/BalStringUtils.java [hunk 2]
```diff
@@ -36,46 +38,60 @@
...
         for (int i = 0; i < list.size(); i++) {
             String e = list.get(i);
-            Object val = StringUtils.parseExpressionStringValue(e);
+            Object val = StringUtils.parseExpressionStringValue(e, node);
             Type type = TypeChecker.getType(val);
             typeSet.add(type);
-            arrayElements[i] = val;
+            arr.add(i, val);
+        }
+        int size = arr.size();
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/BalStringUtils.java:84]: Have this after the returning check. No need to initialize if you return
