### PR TITLE
Disallow optional fields in record binding pattern

### LINKED ISSUE #33389: No error when binding patterns bind optional fields of a record
**Description:**
$title, see https://github.com/ballerina-platform/ballerina-spec/issues/445.

Additionally the type used is also incorrect.

Need to follow up on the spec discussion before we fix this (to decide if we are disallowing this or making the type `T?`).

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Employee record {
    string name;
    int id;
    Employee lead?;
};

public function main() {
    Employee e = {name: "Jo", id: 1234};

    string eName;
    int eId;
    Employee eLead;
    {name: eName, id: eId, lead: eLead} = e; // Allowed!
    io:println(eLead is Employee); // false
    io:println(<any> eLead is ()); // true

    var {name, id, lead} = e;

    Employee ld = lead; // Allowed!
    io:println(ld is Employee); // false
    io:println(<any> ld is ()); // true
}
```

**Affected Versions:**
slbeta3

### LINKED ISSUE #33538: No error when a mapping binding pattern binds rest fields
**Description:**
$title. Where the field is of type `T`, the type seems to be considered `T?`. I don't think this is inline with the spec.

**Steps to reproduce:**
```ballerina
public function main() {
    record {| int i; int...; |} a = {i: 1};
    record {| int i; int...; |} {i: _, j} = a; // no error

    // int x = j; // incompatible types: expected 'int', found 'int?'
}
```

**Affected Versions:**
slbeta4-rc1

### PR DESCRIPTION
**Pull request by rpjayasekara**
Fixes #33389 
Fixes #33538

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 1]
```diff
@@ -1983,39 +1983,10 @@ private void checkRecordVarRefEquivalency(Location pos, BLangRecordVarRef lhsVar
...
-                    break;
-                default:
-                    expectedType = BUnionType.create(null, new LinkedHashSet<BType>() {{
-                        add(rhsMapType.constraint);
-                        add(symTable.nilType);
-                    }});
-                    break;
+            for (BLangRecordVarRefKeyValue field: lhsVarRef.recordRefFields) {
+                dlog.error(field.variableName.pos,
+                        DiagnosticErrorCode.INVALID_FIELD_BINDING_PATTERN_WITH_NON_REQUIRED_FIELD);
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:1988]: We can improve the error message including the field name. Create an issue for this.

**Review by hasithaa — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 1 above)
Comment (rpjayasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:1988]: Created and issue https://github.com/ballerina-platform/ballerina-lang/issues/34375
