### PR TITLE
Fix named arg completions for included record params in function call expressions

### LINKED ISSUE #34440: Code suggestions for included record params are not available
**Description:**
Check the following example with an included record param.

```ballerina
import ballerina/io;

type Config record {
    string host;
    int port;
};

function foo(*Config c) {
    io:println(`Port: ${c.port}`);
    io:println(`Host: ${c.host}`);
}
public function main() returns error? {
   foo(host = "localhost", port = 80);
}
```
VSCode doesn’t give proper suggestions for these included record params. See below.

Screenshot 2021-12-22 at 11 19 31

Since many standard libraries use these included record params in their APIs (see below), it is crucial to have these suggestions. 

- [HTTP usage](https://github.com/ballerina-platform/module-ballerina-http/blob/f89d96e8938def142519c596a6654bb8bf2540e2/ballerina/http_service_endpoint.bal#L32)
- [gRPC usage](https://github.com/ballerina-platform/module-ballerina-grpc/blob/2880a9c71bc31ec7ba70243efa33520a2d388989/ballerina/service_endpoint.bal#L87)
- [GraphQL usage](https://github.com/ballerina-platform/module-ballerina-graphql/blob/0aca1e4b7026f87d86afd59af2975ca616f668ce/ballerina/listener.bal#L29)

**Environment Details**
- Ballerina Swan Lake Beta 6
- Ballerina VSCode plugin `2.1.1`
- macOS

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
$subject

Fixes #34440

## Approach
The case for `included record params` wasn't handled earlier. Handled that.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java [hunk 1]
```diff
@@ -110,18 +111,40 @@ public void sort(BallerinaCompletionContext context, T node, List<LSCompletionIt
...
-                return;
+        for (ParameterSymbol parameterSymbol : params.get()) {
+            if (parameterSymbol.paramKind() == ParameterKind.REQUIRED ||
+                    parameterSymbol.paramKind() == ParameterKind.DEFAULTABLE) {
+                Optional<String> paramName = parameterSymbol.getName();
+                TypeSymbol paramType = parameterSymbol.typeDescriptor();
+                String defaultValue = CommonUtil.getDefaultValueForType(paramType).orElse("");
+                if (paramName.isEmpty() || paramName.get().isEmpty() || existingNamedArgs.contains(paramName.get())) {
+                    continue;
+                }
```
Comment (TharushiJay) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java:122]: Can we move this check to line 118, since `paramType` and `defaultValue` need not be calculated if this check fails?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java [hunk 2]
```diff
@@ -110,18 +111,40 @@ public void sort(BallerinaCompletionContext context, T node, List<LSCompletionIt
...
+                RecordTypeSymbol includedRecordType = (RecordTypeSymbol) typeSymbol;
+                List<RecordFieldSymbol> recordFields = CommonUtil.getMandatoryRecordFields(includedRecordType);
+                recordFields.forEach(recordFieldSymbol -> {
+                    Optional<String> fieldName = recordFieldSymbol.getName();
+                    TypeSymbol fieldType = recordFieldSymbol.typeDescriptor();
+                    String defaultValue = CommonUtil.getDefaultValueForType(fieldType).orElse("");
+                    if (fieldName.isEmpty() || fieldName.get().isEmpty() ||
+                            existingNamedArgs.contains(fieldName.get())) {
+                        return;
+                    }
```
Comment (TharushiJay) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java:141]: This can also be moved to 136 to avoid calculating `fieldType` and `defaultValue`, if it fails.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java [hunk 3]
```diff
@@ -110,18 +111,40 @@ public void sort(BallerinaCompletionContext context, T node, List<LSCompletionIt
...
-            TypeSymbol paramType = parameterSymbol.typeDescriptor();
-            String defaultValue = CommonUtil.getDefaultValueForType(paramType).orElse("");
-            if (paramName.isEmpty() || paramName.get().isEmpty() || existingNamedArgs.contains(paramName.get())) {
-                return;
+        for (ParameterSymbol parameterSymbol : params.get()) {
+            if (parameterSymbol.paramKind() == ParameterKind.REQUIRED ||
+                    parameterSymbol.paramKind() == ParameterKind.DEFAULTABLE) {
+                Optional<String> paramName = parameterSymbol.getName();
+                TypeSymbol paramType = parameterSymbol.typeDescriptor();
+                String defaultValue = CommonUtil.getDefaultValueForType(paramType).orElse("");
```
Comment (TharushiJay) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java:119]: Since we don't have any other usages for `paramType`, can we use it straightaway in the default value generation without assigning to a variable?

**Review by TharushiJay — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java (hunk 2 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java]: +1

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java (hunk 1 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java:120]: Done

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java (hunk 3 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java]: Done

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java [hunk 4]
```diff
@@ -82,8 +84,7 @@ public void sort(BallerinaCompletionContext context, T node, List<LSCompletionIt
             super.sort(context, node, completionItems);
             return;
         }
-        for (
-                LSCompletionItem completionItem : completionItems) {
+        for (LSCompletionItem completionItem : completionItems) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java:87]: With this, shall we refactor lines 72-80 as well? The logic can be combined

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java (hunk 4 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java:84]: Done. Can you check if that was what you expected as well?

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/InvocationNodeContextProvider.java:84]: Yes, this is what I had in mind (y)

**Review by nadeeshaan — APPROVED** [review]
LGTM

**Review by gayalkuruppu — APPROVED** [review]
LGTM

**Review by mohanvive — APPROVED** [review]
