### PR TITLE
Fix lang lib content suggestions

### LINKED ISSUE #25983: Suggestions support for predeclared modules.
With https://github.com/ballerina-platform/ballerina-lang/issues/25463, all lang lib module which ends with a keyboard now Predeclare as module prefixes. 

This has to support in code suggestions in Language Server implementation. 
vscode-1600689355121

### PR DESCRIPTION
**Pull request by nadeeshaan**
Fixes #25983 and add few more test cases.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java [hunk 1]
```diff
@@ -67,7 +68,8 @@ public AssignmentStatementNodeContext() {
             (2) [module:]TypeName c = module:a<cursor>
              */
             QualifiedNameReferenceNode qNameRef = (QualifiedNameReferenceNode) node.expression();
-            Predicate<Symbol> filter = symbol -> symbol.kind() == SymbolKind.VARIABLE;
+            Predicate<Symbol> filter = symbol -> symbol instanceof VariableSymbol
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java:71]: Can't we use `SymbolKind.VARIABLE` instead?

**Review by rasika — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java:71]: No, if we use the VARIABLE symbol kind, then it will not capture the constants as per the current model. In order to avoid having two check with constant and variable kinds, added the instance of check

Comment (rasika) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java:71]: If the intention is to address both constants and variables I would still prefer two checks; since `==` comparison is far efficient  compared to `instanceOf` and for the better readability of allowing constants and variables.

**Review by rasika — APPROVED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java:71]: Yes, agreed. This will be addressed along with the newly proposed model
