### PR TITLE
Embed rest match pattern to match pattern list in SyntaxAPI

### LINKED ISSUE #28281: Issue when modifying ListMatchPatternNode and MappingMatchPatternNode
**Description:**
The match pattern nodes `ListMatchPatternNode` and `MappingMatchPatternNode` contain a `RestMatchPatternNode` attribute which could be included inside the separated node list of match pattern nodes itself.

When modifying a match pattern node of this sort, there exists a difficulty in handling the `,` separator which is after the list of binding pattern nodes and before the rest match pattern node.

Fixes: https://github.com/ballerina-platform/ballerina-lang/issues/28154

**Steps to reproduce:**

ListMatchPatternNode:
```bal
function test1(any v) {
    match v {
        [var a , ...var b] => { // Bug
            return;
        }
    }
}
```
**Affected Versions:**
Ballerina Swan Lake Alpha 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$subject

Fixes #28281

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 1]
```diff
@@ -4175,19 +4175,23 @@ private BLangMatchPattern transformMatchPattern(Node matchPattern) {
                     (BLangListMatchPattern) TreeBuilder.createListMatchPattern();
             bLangListMatchPattern.pos = matchPatternPos;
 
-            for (Node memberMatchPattern : listMatchPatternNode.matchPatterns()) {
-                BLangMatchPattern bLangMemberMatchPattern = transformMatchPattern(memberMatchPattern);
+            SeparatedNodeList<Node> matchPatterns = listMatchPatternNode.matchPatterns();
+            int matchPatternListSize = matchPatterns.size();
+            for (int i = 0; i < matchPatternListSize - 1; i++) {
```
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:4180]: Is it intended to iterate only up to `matchPatternListSize - 1`, eliminating the last one? 
How about having a `foreach` instead of  `for (int i = 0; i < matchPatternListSize - 1; i++)` ?

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 2]
```diff
@@ -13390,25 +13389,23 @@ private STNode parseListMatchPattern() {
...
-            restMatchPattern = SyntaxErrors.cloneWithTrailingInvalidNodeMinutiae(restMatchPattern, invalidField);
-            restMatchPattern = SyntaxErrors.addDiagnostic(restMatchPattern,
-                    DiagnosticErrorCode.ERROR_MORE_MATCH_PATTERNS_AFTER_REST_MATCH_PATTERN);
-            listMatchPatternMemberRhs = parseListMatchPatternMemberRhs();
-        }
+            updateLastNodeInListWithInvalidNode(matchPatternList, listMatchPatternMemberRhs, null);
+
+            if (peek().kind == SyntaxKind.CLOSE_BRACKET_TOKEN) {
+                break;
+            }
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:13396]: Why do we need this block?  
`parseListMatchPatternMemberRhs` returns `null` for `]`
Therefore, we should not reach inside the while loop for `]`

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 3]
```diff
@@ -13510,25 +13506,23 @@ private STNode parseMappingMatchPattern() {
         // Try to parse them and mark as invalid.
         STNode fieldMatchPatternRhs = parseFieldMatchPatternRhs();
         while (isEndOfFields && fieldMatchPatternRhs != null) {
+            updateLastNodeInListWithInvalidNode(fieldMatchPatternList, fieldMatchPatternRhs, null);
+
+            if (peek().kind == SyntaxKind.CLOSE_BRACKET_TOKEN) {
+                break;
+            }
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:13513]: Similar case here also. Plus `mapping-match-pattern` ends with a `}`

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 4]
```diff
@@ -13390,25 +13389,23 @@ private STNode parseListMatchPattern() {
...
 
-        if (restMatchPattern == null) {
-            restMatchPattern = STNodeFactory.createEmptyNode();
+            STNode invalidField = parseListMatchPatternMember();
+            updateLastNodeInListWithInvalidNode(matchPatternList, invalidField,
+                    DiagnosticErrorCode.ERROR_MATCH_PATTERN_AFTER_REST_MATCH_PATTERN);
+            listMatchPatternMemberRhs = parseFieldMatchPatternRhs();
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:13401]: shouldn't we call `parseListMatchPatternMemberRhs()` here?

**Review by lochana-chathura — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 5]
```diff
@@ -4175,19 +4175,23 @@ private BLangMatchPattern transformMatchPattern(Node matchPattern) {
...
-            if (listMatchPatternNode.restMatchPattern().isPresent()) {
-                RestMatchPatternNode restMatchPatternNode = listMatchPatternNode.restMatchPattern().get();
-                bLangListMatchPattern.setRestMatchPattern(
-                        (BLangRestMatchPattern) transformMatchPattern(restMatchPatternNode));
+            BLangMatchPattern lastMember = transformMatchPattern(matchPatterns.get(matchPatternListSize - 1));
+            if (lastMember.getKind() == NodeKind.REST_MATCH_PATTERN) {
+                bLangListMatchPattern.setRestMatchPattern((BLangRestMatchPattern) lastMember);
+            } else {
+                bLangListMatchPattern.addMatchPattern(lastMember);
             }
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:4193]: Seems we can move this logic inside to the  `for (Node memberMatchPattern : listMatchPatternNode.matchPatterns()) { }`?

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 2 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:13396]: It is to handle `[a, b, ]` cases. by that, it will invalidate only the comma without inserting another binding pattern.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 3 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:13513]: Will uptade thanx.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 4 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:13401]: thanx will update

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 5 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:4193]: This is done to prevent an if condition inside for loop. Since we know if rest bp exists, it will be at the last, we should get the advantage of that without checking the if for each loop.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 1 above)
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:4180]: Here, we have a bug. When there are no members in the `matchPatterns`, this may give `IndexOutOfBoundsException` for `index = -1`. Better, if we can early-return if `matchPatternListSize < 1`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 6]
```diff
@@ -4207,13 +4211,18 @@ private BLangMatchPattern transformMatchPattern(Node matchPattern) {
                     (BLangMappingMatchPattern) TreeBuilder.createMappingMatchPattern();
             bLangMappingMatchPattern.pos = matchPatternPos;
 
-            for (FieldMatchPatternNode fieldMatchPatternNode : mappingMatchPatternNode.fieldMatchPatterns()) {
+            SeparatedNodeList<FieldMatchPatternNode> fieldMatchPatterns = mappingMatchPatternNode.fieldMatchPatterns();
+            int fieldMatchPatternListSize = fieldMatchPatterns.size();
+            for (int i = 0; i < fieldMatchPatternListSize - 1; i++) {
```
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:4216]: Check here too for `IndexOutOfBoundsException`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 1 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:4180]: Thanx will update

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 7]
```diff
@@ -4207,13 +4211,18 @@ private BLangMatchPattern transformMatchPattern(Node matchPattern) {
...
             }
-            if (mappingMatchPatternNode.restMatchPattern().isPresent()) {
-                bLangMappingMatchPattern.restMatchPattern =
-                        (BLangRestMatchPattern) transformMatchPattern(mappingMatchPatternNode.restMatchPattern().get());
+
+            BLangMatchPattern lastMember = transformMatchPattern(fieldMatchPatterns.get(fieldMatchPatternListSize - 1));
+            if (lastMember.getKind() == NodeKind.REST_MATCH_PATTERN) {
+                bLangMappingMatchPattern.restMatchPattern = (BLangRestMatchPattern) lastMember;
+            } else {
+                bLangMappingMatchPattern.fieldMatchPatterns.add((BLangFieldMatchPattern) lastMember);
```
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:4225]: We have a duplicate code of `L4188 - L4192`. WDT of extracting this out to a method (if possible)?

**Review by dulajdilshan — CHANGES_REQUESTED** [review]
commented

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 7 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java]: When extracting out it introduces more checks to the logic. IMO its better to keep it as it is.

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java]: I mean introducing a new method and have this logic inside it. Then, you can call that method in both place.

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java]: Yes, when extracting out to a separate method it causes more type checks and casting since they are two different types.

Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java]: yeah. Seems extracting would require type checking and casting.

**Review by lochana-chathura — APPROVED** [review]
LGTM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 8]
```diff
@@ -4175,19 +4175,28 @@ private BLangMatchPattern transformMatchPattern(Node matchPattern) {
                     (BLangListMatchPattern) TreeBuilder.createListMatchPattern();
             bLangListMatchPattern.pos = matchPatternPos;
 
-            for (Node memberMatchPattern : listMatchPatternNode.matchPatterns()) {
-                BLangMatchPattern bLangMemberMatchPattern = transformMatchPattern(memberMatchPattern);
+            SeparatedNodeList<Node> matchPatterns = listMatchPatternNode.matchPatterns();
+            int matchPatternListSize = matchPatterns.size();
+
+            if (matchPatternListSize < 1) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:4181]: Isn't this just 
```suggestion
            if (matchPatternListSize == 0) {
```

IMO, it's better to have the exact check, or it could get us wondering if it can be anything other than 0.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 9]
```diff
@@ -4207,13 +4216,23 @@ private BLangMatchPattern transformMatchPattern(Node matchPattern) {
                     (BLangMappingMatchPattern) TreeBuilder.createMappingMatchPattern();
             bLangMappingMatchPattern.pos = matchPatternPos;
 
-            for (FieldMatchPatternNode fieldMatchPatternNode : mappingMatchPatternNode.fieldMatchPatterns()) {
+            SeparatedNodeList<Node> fieldMatchPatterns = mappingMatchPatternNode.fieldMatchPatterns();
+            int fieldMatchPatternListSize = fieldMatchPatterns.size();
+
+            if (fieldMatchPatternListSize < 1) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:4222]:
```suggestion
            if (fieldMatchPatternListSize == 0) {
```

**Review by dulajdilshan — DISMISSED** [review]
LGTM

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java [hunk 10]
```diff
@@ -267,10 +267,10 @@
     ERROR_INVALID_METADATA("BCE0621", "error.invalid.metadata"),
     ERROR_INVALID_QUALIFIER("BCE0622", "error.invalid.qualifier"),
     ERROR_ANNOTATIONS_ATTACHED_TO_STATEMENT("BCE0623", "error.annotations.attached.to.statement"),
-    ERROR_MORE_FIELD_MATCH_PATTERNS_AFTER_REST_FIELD("BCE0624", "error.more.field.match.patterns.after.rest.field"),
+    ERROR_FIELD_MATCH_PATTERN_AFTER_REST_FIELD("BCE0624", "error.field.match.pattern.after.rest.field"),
     ERROR_ACTION_AS_A_WAIT_EXPR("BCE0625", "error.action.as.a.wait.expr"),
     ERROR_INVALID_USAGE_OF_VAR("BCE0626", "error.invalid.usage.of.var"),
-    ERROR_MORE_MATCH_PATTERNS_AFTER_REST_MATCH_PATTERN("BCE0627", "error.more.match.patterns.after.rest.match.pattern"),
+    ERROR_MATCH_PATTERN_AFTER_REST_MATCH_PATTERN("BCE0627", "error.match.pattern.after.rest.match.pattern"),
```
Comment (MaryamZi) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java:273]: Do we need both this and `ERROR_FIELD_MATCH_PATTERN_AFTER_REST_FIELD`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java (hunk 8 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:4181]: Okay

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java (hunk 10 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java:273]: +1 let's keep only one

**Review by IrushiL — COMMENTED** [review]
Formatting changes LGTM

**Review by MaryamZi — APPROVED** [review]

**Review by lochana-chathura — APPROVED** [review]
