### PR TITLE
Fix incorrect results in bitwise OR and XOR expressions with user defined types

### LINKED ISSUE #35247: Incrrect output in bitwise expression when user defined types as operands
**Description:**
Bit-wise expression gives incorrect outputs when operands as user defined finite types

**Steps to reproduce:**

```
type MyType int;

type MyType2 int:Signed32|int:Unsigned16;

type MyType3 int:Unsigned32|int:Signed8;

type MyType4 byte|int:Signed8;

type MyUnionType MyType2|MyType4;

function init() {
    MyType2 d = 4344;
    MyType3 e = -34;
    MyType4 f = -76;
    MyUnionType g = 75;

    printResult(d ^ e); // @output -4314
    printResult(d ^ f); // @output -4276
    printResult(d ^ g); // @output 4275

    printResult(e ^ e); // @output 0
    printResult(e ^ f); // @output 106
    printResult(e ^ g); // @output -107

    printResult(f ^ f); // @output 0
    printResult(f ^ g); // @output -1
}

function printResult(int result) {
    io:println(result);
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by rpjayasekara**
Fixes #35247

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java [hunk 1]
```diff
@@ -1210,7 +1211,8 @@ private void generateBitwiseXorIns(BIRNonTerminator.BinaryOp binaryIns) {
 
         this.mv.visitInsn(LXOR);
 
-        if (!TypeTags.isSignedIntegerTypeTag(opType1.tag) && !TypeTags.isSignedIntegerTypeTag(opType2.tag)) {
+        if (!TypeTags.isSignedIntegerTypeTag(opType1.tag) && !TypeTags.isSignedIntegerTypeTag(opType2.tag) &&
+            opType1.tag != TypeTags.UNION && opType2.tag != TypeTags.UNION) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:1215]: This will be false for `type MyType2 int:Unsigned16|int:Unsigned32;` as well. Not sure how this will have an effect. Thoughts @warunalakshitha ?

Comment (warunalakshitha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:1215]: Should we check all member types in the union and if all member types are unsigned this should be true.

Comment (rpjayasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:1215]: I don't this that we need to check all the member types as if the operand type is union type the result of the expression is `int`

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Review by lochana-chathura — APPROVED** [review]

**Review by pcnfernando — APPROVED** [review]
