### PR TITLE
Fix NPE from daemon strand for record value creation

### LINKED ISSUE #42027: [Bug]: Simple POST request from a cURL client fails with NPE for a Ballerina service ran using lang master
### Description

When we invoke a Ballerina service which runs with lang master, then the a simple POST request fails with the following error:
```
java.lang.NullPointerException: Cannot invoke "io.ballerina.runtime.internal.scheduling.Scheduler.createFuture(io.ballerina.runtime.internal.scheduling.Strand, io.ballerina.runtime.api.async.Callback, java.util.Map, io.ballerina.runtime.api.types.Type, String, io.ballerina.runtime.api.async.StrandMetadata)
```

**Note:** This is not happening if we invoke the service by adding a Ballerina test in the same package. This might be the reason for **not identifying this issue in the full build pipeline PR check**

### Steps to Reproduce

Service code used to reproduce this issue:
```bal
import ballerina/http;

type Album readonly & record {|
    string title;
    string artist;
|};

final table<Album> key(title) albums = table [
    {title: "Blue Train", artist: "John Coltrane"},
    {title: "Sarah Vaughan and Clifford Brown", artist: "Sarah Vaughan"}
];

service / on new http:Listener(9090) {
    resource function get albums() returns Album[] {
        return albums.toArray();
    }

    resource function post albums(Album album) returns Album|http:Conflict {
        if albums.hasKey(album.title) {
            return http:CONFLICT;
        }
        albums.add(album);
        return album;
    }
}
```

Steps to reproduce this issue:
1. I have used the following timestamped version of lang - `2201.9.0-20240120-003700-f65e7994`. This is also reproducible when we build the lang master and use it in the http module

2. Clone the ballerina-http repository and update the lang version in the `gradle.properties` file

3. Run `./gradlew clean build -x test -x check`. This will create a temporary distribution in the `target` path in the repo root.

4. Use the `bal` command in that `target` directory to run the above Ballerina service

5. Make a cURL request: `curl -v "http://localhost:9090/albums" -d '{"title": "test", "artist": "test"}' -H "content-type: application/json"`

### Affected Version(s)

Ballerina SwanLake Update 9

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$Subject 
Fixes #42027

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java [hunk 1]
```diff
@@ -455,7 +456,9 @@ public void unblockStrand(Strand strand) {
     }
 
     private void cleanUp(Strand justCompleted) {
-        justCompleted.scheduler = null;
```
Comment (Nadeeshan96) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java:458]: Shall we just remove this line and do not make any other changes? Since we only create one Scheduler object to run the Ballerina program (and another one for module stop), the Scheduler object will not get garbage collected anyway. Hence, we do not have a reason to make this `null`. @warunalakshitha WDYT?

Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java:458]: If we are not making the reference of `justCompleted.scheduler` null, will that strand object be eligible for garbage collection even though it doesn't have no live references to other objects?

**Review by Nadeeshan96 — APPROVED** [review]
LGTM

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java (hunk 1 above)
Comment (warunalakshitha) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java:458]: AFAIK it will eligible to grabage collection since it is not reachable.

File: tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/no_strand/main.bal [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+public class Listener {
+
+    private string name = "";
+
+    public function init(string name){
+        self.name = name;
+    }
+
+    public function 'start() returns error? {
+
```
Comment (gabilang) [inline tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/no_strand/main.bal:28]:
```suggestion
```

File: tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/no_strand/main.bal [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+    public function init(string name){
+        self.name = name;
+    }
+
+    public function 'start() returns error? {
+      
+    }
+
+    public function gracefulStop() returns error? {
+
```
Comment (gabilang) [inline tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/no_strand/main.bal:32]:
```suggestion
```

File: tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/no_strand/main.bal [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+    }
+
+    public function detach(service object {} s) returns error? {
+    }
+}
+
+public function main() {
+    Listener l = new("TestListener");
+    runtime:registerListener(l);
+
```
Comment (gabilang) [inline tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/no_strand/main.bal:48]:
```suggestion
```

File: tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/no_strand/main.bal [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+public type MutualSslHandshake record {|
+    MutualSslStatus status = PASSED;
+    string? base64EncodedCert = ();
+|};
+
+# Defines the possible values for the mutual ssl status.
+#
+# `passed`: Mutual SSL handshake is successful.
+# `failed`: Mutual SSL handshake has failed.
```
Comment (gabilang) [inline tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/no_strand/main.bal:59]: We can remove these comments since they seem not necessary for this test case.

**Review by gabilang — APPROVED** [review]

**Review by Nadeeshan96 — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM
