### PR TITLE
Fix issue in recovering var decl statement with complex binding pattern

### LINKED ISSUE #29926: Parser does not identify the correct context
**Description:**
Consider the following source snippet,

```
function name() {
    int[<cursor>]
}
```

Current parser does not identify the context in the source as an `array-type-descriptor` and instead it identifies as `type-binding-pattern`

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$title

Fixes #29926

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by lochana-chathura — APPROVED** [review]

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 1]
```diff
@@ -457,7 +457,7 @@
             { ParserRuleContext.REST_BINDING_PATTERN, ParserRuleContext.BINDING_PATTERN };
 
     private static final ParserRuleContext[] LIST_BINDING_PATTERN_MEMBER_END =
-            { ParserRuleContext.COMMA, ParserRuleContext.CLOSE_BRACKET };
+            { ParserRuleContext.CLOSE_BRACKET, ParserRuleContext.COMMA };
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:460]: This was needed because of  #28256
