### PR TITLE
Revamped mapping expression context completions

### LINKED ISSUE #28610: Suggestions are not working for record types mapping constructor
**Description:**
Check the below image.

Screen Shot 2021-02-12 at 12 32 31 AM

**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Alpha 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose
With this, revamped the mapping context completions by introducing a common context type resolver.

Fixes #28610

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java [hunk 1]
```diff
@@ -0,0 +1,262 @@
...
+    private final BallerinaCompletionContext context;
+    private final List<Node> visitedNodes = new ArrayList<>();
+
+    public ContextTypeResolver(BallerinaCompletionContext context) {
+        this.context = context;
+    }
+
+    @Override
+    public Optional<TypeSymbol> transform(SimpleNameReferenceNode node) {
+        Optional<Symbol> variableSymbol = this.getSymbolByName(node.name().text());
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:93]: Can't we use `SemanticModel.symbol(node)` instead of this. Then we can cover  `transform(QualifiedNameReferenceNode node)` without ambiguity as well ?

**Review by rasika — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/mapping_expr_ctx_config20.json [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+    {
+      "label": "Add All Attributes",
+      "kind": "Property",
+      "detail": "none",
+      "sortText": "Q",
+      "insertText": "rec1f1: {},\nrec1f2: 0",
+      "insertTextFormat": "Snippet"
+    }
+  ]
+}
```
Comment (rasika) [inline language-server/modules/langserver-core/src/test/resources/completion/new/expression_context/config/mapping_expr_ctx_config20.json:41]: Shall we add line feeds for these places as well?

**Review by rasika — APPROVED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:93]: The qualified name reference is implemented to capture the type definitions specifically, we bypass the ambiguity of the annotation symbol in the particular node visitor. For the fall back if in any case there are two members we return empty until we handle it properly. Also, the variable name based capturing is used to skip capturing the type reference type symbol instead of the type definition.

**Review by rasika — APPROVED** [review]
