### PR TITLE
Fix CCE when using a foreach statement with xml<T> when T is not a BXMLType

### LINKED ISSUE #35473: CCE when using a foreach statement with `xml<T>` when `T` is not a `BXMLType`
**Description:**
$title

**Steps to reproduce:**

```ballerina
public function main() {
    xml<xml:Element & readonly> elements = xml ``;

    foreach var element in elements {
        
    }
}
```

```
[2022-03-15 16:01:21,097] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.types.BIntersectionType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType (org.wso2.ballerinalang.compiler.semantics.model.types.BIntersectionType and org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BIntersectionType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType (org.wso2.ballerinalang.compiler.semantics.model.types.BIntersectionType and org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.setForeachTypedBindingPatternType(Types.java:1711)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:3627)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangForeach.accept(BLangForeach.java:111)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:4024)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:524)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:500)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4057)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4028)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4020)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:349)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:309)
        at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:436)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:145)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:249)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Affected Versions:**

### PR DESCRIPTION
**Pull request by SasinduDilshara**
Fixes #35473, #36550

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by SasinduDilshara** [comment]
Currently, the task of writing test cases for this PR is blocked due to the issue #https://github.com/ballerina-platform/ballerina-lang/issues/36550

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 1]
```diff
@@ -1548,11 +1548,24 @@ private void validateXMLConstraintType(BType type, Location pos) {
             return;
         }
 
+        if (constrainedTag == TypeTags.INTERSECTION) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1551]: Still won't work for something like

```ballerina
xml<(xml:Element|xml:Comment) & readonly> _ = xml ``;
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1551]: IMO, this isn't where we should check for intersection type. After L1543, you can check if the constraint is an intersection type and set the effective type to `constraintType`. That way the union logic will also work as is and you wouldn't need to special case like this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 2]
```diff
@@ -1739,6 +1739,13 @@ public void setForeachTypedBindingPatternType(BLangForeach foreachNode) {
                     case TypeTags.NEVER:
                         varType = symTable.neverType;
                         break;
+                    case TypeTags.ARRAY:
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1742]: How can the constraint be an array?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 1 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1551]: Yes. I will change it.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 2 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1742]: Its happen when `xml<xml:Element[]> element = xml ``;`

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1742]: But this is invalid, yeah? So we don't have to handle foreach for it.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1742]: yes. but if we didn't handle it. It will throw a runtime error.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1742]: https://github.com/ballerina-platform/ballerina-lang/blob/03275ec1c2e80c558adeb78165eaf534519b40c2/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L1744

If we didn't handle it, It will go to the default case. Then it will throw a class cast exception.
Because `BArrayType` can't convert into a `BUnionType`.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1742]: Then it will still fail for things like

```ballerina
public function main() {
    xml<[int, string]> x = xml ``;

    foreach var item in x {
        
    }
}
```

So, IMO the fix should be to add a case for UNION instead of considering it to be the default, and make the default case do something like L1818-L1822.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1742]: Yes, That will be the better option. I will update that.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1742]:
```
public function main() {
    xml<xmL:Element[] & readonly> x = xml ``;

    foreach var item in x {
        
    }
}
```
There are two possible error messages we can display to user.
* incompatible types: 'xml' cannot be constrained with '(xml:Element[] & readonly)' 
* incompatible types: 'xml<xml:Element[]>' is not an iterable collection

IMO, first one is better because ballerina didn't support `xml:Element[] & readonly`.
WDYT?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1742]: Don't these correspond to the two different statements? The first error we must definitely log. The second one is not required IMO, and is only noise since it will go away when the user fixes the first issue anyway.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1742]: Yes. I will add first message.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Updated - 92b1e95bcd91c8dc89775d0f23f3a91ef0236f75

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 1 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: Updated -  92b1e95bcd91c8dc89775d0f23f3a91ef0236f75

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal [hunk 3]
```diff
@@ -308,6 +308,40 @@ function testSequenceOfSequenceOfXmlElementIteration() {
...
+
+    xml<xml:Element & readonly> elements2 = xml `<foo/><bar>value</bar><baz>1</baz>`;
+    arr = [];
+    foreach var e2 in elements2 {
+        arr.push(e2);
+    }
+    validateValues(arr);
+}
+
+function testSequenceOfXmlReadonlyUnionIteration() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal:327]: Maybe
```suggestion
function testSequenceOfReadOnlyXmlSubTypeUnionIteration() {
```

Kinda reads like a union of xml and readonly atm.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal [hunk 4]
```diff
@@ -308,6 +308,40 @@ function testSequenceOfSequenceOfXmlElementIteration() {
...
+    xml<(xml:Element|xml:Comment) & readonly> elements = xml `<foo/><bar>value</bar><baz>1</baz>`;
+    xml:Element[] arr = [];
+    foreach (xml:Element|xml:Comment) & readonly e1 in elements {
+        arr.push(<xml:Element> e1);
+    }
+    validateValues(arr);
+}
+
+function testSequenceOfXmlReadonlyUnionIteration2() {
+    xml<(xml:Element & readonly | xml:Comment & readonly)> elements = xml `<foo/><bar>value</bar><baz>1</baz>`;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal:337]:
```suggestion
    xml<(xml:Element & readonly|xml:Comment & readonly)> elements = xml `<foo/><bar>value</bar><baz>1</baz>`;
```

**Review by MaryamZi — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal (hunk 3 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal]: Updated - 162c9db61a2443f5e02a97993461b5f6b88bc530

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal (hunk 4 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml_iteration.bal]: Updated - 162c9db61a2443f5e02a97993461b5f6b88bc530

**Review by KavinduZoysa — APPROVED** [review]

**Review by MaryamZi — APPROVED** [review]
