### PR TITLE
Fix resource visiting and position util issues

### LINKED ISSUE #27482: Lang server is not suggesting existing variables inside a resource funtion
Screenshot 2020-12-14 at 15 59 20

### PR DESCRIPTION
**Pull request by nadeeshaan**
Fixes #27482

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by pubudu91 — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/PositionUtil.java [hunk 1]
```diff
@@ -30,6 +30,12 @@
 class PositionUtil {
 
     static boolean withinBlock(LinePosition cursorPos, Location symbolPosition) {
+        /*
+        Temporary null check added
+         */
+        if (symbolPosition == null) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/PositionUtil.java:36]: In what sort of scenarios was this null?

Comment (nadeeshaan) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/PositionUtil.java:36]: This is being null when we are going to use the semantic API after the Desugar phase.
