### PR TITLE
Fix SO for equality check with cyclic union

### LINKED ISSUE #29739: Stack overflow error for equality check with cyclic union
**Description:**
$title. Seems like org.wso2.ballerinalang.compiler.semantics.analyzer.Types#expandAndGetMemberTypesRecursive hasn't been updated for cyclic unions, We may have to revisit the entire check for equality.

**Steps to reproduce:**
```ballerina
public type CyclicDecimal decimal|CyclicDecimal[];

public function main() returns error? {
    CyclicDecimal x = 1.0;
    boolean bool = x == 1.23f;
}
```

**Affected Versions:**
slalpha4-SNAPSHOT, reproducible on previous versions too

### PR DESCRIPTION
**Pull request by KRVPerera**
## Purpose
Fixes #29739

## Remarks
[ ] - we have to add the intersection between operands to fix this area properly.
[ ] - this will also help to remove the pure type (anydata|error) concept from lang

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -3288,6 +3288,12 @@ private boolean equalityIntersectionExists(Set<BType> lhsTypes, Set<BType> rhsTy
      * @return  a set containing all the retrieved member types
      */
     public Set<BType> expandAndGetMemberTypesRecursive(BType bType) {
+        LinkedHashSet<BType> visited = new LinkedHashSet<>();
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3291]: Any specific reason to use a linked hashset here?

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Thank you for the suggestion.

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Fixed by b662fb58db3762fd4bfc3811605bcf6d70f53c7e

**Review by pcnfernando — APPROVED** [review]

**Review by MaryamZi — APPROVED** [review]
