### PR TITLE
[LS]Fix renaming NPE

### LINKED ISSUE #32216: NPE when performing a rename operation
**Description:**
Try renaming anything (identifiers) in vscode and the following NPE is printed in vscode plugin output.
```
[Error - 8:33:12 PM] Operation 'text/rename' failed! {uri: '/home/imesha/Documents/WSO2/Ballerina/Projects/test_project/projects/pull_mod_test/main.bal', [5:10], error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at org.ballerinalang.langserver.contexts.RenameContextImpl.<init>(RenameContextImpl.java:49)
	at org.ballerinalang.langserver.contexts.RenameContextImpl$RenameContextBuilder.build(RenameContextImpl.java:70)
	at org.ballerinalang.langserver.contexts.RenameContextImpl$RenameContextBuilder.build(RenameContextImpl.java:57)
	at org.ballerinalang.langserver.contexts.ContextBuilder.buildRenameContext(ContextBuilder.java:175)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$rename$13(BallerinaTextDocumentService.java:473)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Seems like the `clientCapabilities.getTextDocCapabilities().getRename().getHonorsChangeAnnotations()` returns null in `RenameContextImpl` constructor causing boolean unboxing to throw an NPE.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 3 Snapshot

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$Subject

Fixes #32216

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/RenameContextImpl.java [hunk 1]
```diff
@@ -45,8 +45,9 @@
         super(operation, fileUri, wsManager, cursorPos, serverContext);
         this.clientCapabilities = clientCapabilities;
         this.params = params;
-        this.honorsChangeAnnotations = clientCapabilities.getTextDocCapabilities().getRename() != null &&
-                clientCapabilities.getTextDocCapabilities().getRename().getHonorsChangeAnnotations();
+        this.honorsChangeAnnotations = clientCapabilities.getTextDocCapabilities().getRename() != null
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/RenameContextImpl.java:48]: What if we keep `honorsChangeAnnotations` in `boolean` primitive type instead of `Boolean` as well?

**Review by IMS94 — APPROVED** [review]
