### PR TITLE
Deprecate `parseStatements` and introduce `parseBlockStatement` instead

### LINKED ISSUE #33323: `lineRange` is not set when parsing multiple statements with syntax API
**Description:**
When I parse multiple statements using `parseStatements()`, The `lineRange` hasn't been set in each `StatementNode` except the first `StatementNode`.

eg:
```java
String x = "string fName = \"Ted\"; string lName = \"Mosby\";";
NodeList<StatementNode> s = NodeParser.parseStatements(x);
s.get(1).lineRange();
```
Above will throws the below IOOB exception.
```
java.lang.IndexOutOfBoundsException: Index: '36', Size: '19'
```

**Affected Versions:**
2.0.0-beta.4-SNAPSHOT

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #33323 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [x] Added necessary documentation  
  - [x] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -127,6 +128,22 @@ public STNode parseAsStatement() {
...
+    /**
+     * Completely parses a given input as a block statement.
+     *
+     * @return Parsed node
+     */
+    public STNode parseAsBlockStatement() {
+        startContext(ParserRuleContext.COMP_UNIT);
+        startContext(ParserRuleContext.FUNC_DEF);
+        startContext(ParserRuleContext.FUNC_BODY_BLOCK);
+        startContext(ParserRuleContext.WHILE_BLOCK);
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:140]: Any reason for starting `ParserRuleContext.WHILE_BLOCK`?

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:140]: if we check all places where `parseBlockNode()` is called. There's a parent context. `WHILE_BLOCK`, `IF_BLOCK`, `FOREACH_STMT`, `LOCK_STMT` etc. We can keep `FUNC_BODY_BLOCK` only since inside parseFunctionBodyBlock() we don't call `parseBlockNode() ` directly right

**Review by hasithaa — APPROVED** [review]
