### PR TITLE
Fix use of wrong constructor in `BMethodType`

### LINKED ISSUE #43874: [Bug]: `BMethodType` object doesn't return the rest type properly
### Description

A `BMethodType` object returns `null` instead of the rest type of the argument when using the `getRestType()` method.

Ex:
```
public function getInfo(string title, string vehicle = "car", string... other) returns string
```
A method with the above definition should have `string[]` as the rest type. But when `getRestType()` is used, `null` is returned during runtime.

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by ravinperera00**
Fixes #43874 

## Check List 
- [X] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BMethodType.java [hunk 1]
```diff
@@ -76,11 +70,11 @@ public ObjectType getParentObjectType() {
 
     @Override
     public FunctionType getType() {
-        return type;
+        return this;
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BMethodType.java:73]: Shall we remove the keeping type as well.

Comment (ravinperera00) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BMethodType.java:72]: Fixed in 25b11156ff9ec06949a1ad0d68a0c017f380d79a. The `getType` method cannot be remove altogether because Standard libraries depend on it.

**Review by warunalakshitha — APPROVED** [review]
