### PR TITLE
Reset `unknownTypeRefs` after silent type checking

### LINKED ISSUE #43286: [Bug]: Compiler crashed when running bal build
### Description

I'm currently developing a Ballerina connector for the [OpenAI Fine-tunes API](https://github.com/ballerina-platform/module-ballerinax-openai.finetunes). While writing the examples, I attempted to use the connector by pushing it to my repository and then running the examples. However, when I tried to run bal build on the project, I encountered the following error:

> ballerina: Oh no, something really went wrong. Bad. Sad.
> 
> We appreciate it if you can report the code that broke Ballerina in 
> https://github.com/ballerina-platform/ballerina-lang/issues with the
> log you get below and your sample code.
> 
> We thank you for helping make us better.
> 
> [2024-08-14 16:53:56,078] SEVERE {b7a.log.crash} - Cannot read field "flags" because "type.tsymbol" is null 
> java.lang.NullPointerException: Cannot read field "flags" because "type.tsymbol" is null
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2809)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:286)
>         at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:70)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3605)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:3296)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:286)
>         at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckedExpr.accept(BLangCheckedExpr.java:70)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:3605)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:1707)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:286)
>         at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:59)
>         at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:217)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:355)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeTopLevelNodes(CodeAnalyzer.java:344)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:332)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:286)
>         at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
>         at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:217)
>         at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyze(CodeAnalyzer.java:320)
>         at io.ballerina.projects.internal.CompilerPhaseRunner.codeAnalyze(CompilerPhaseRunner.java:192)
>         at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:115)
>         at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:435)
>         at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
>         at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:383)
>         at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:97)
>         at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:244)
>         at io.ballerina.projects.Package.getCompilation(Package.java:151)
>         at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:324)
>         at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:156)
>         at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:295)
>         at java.base/java.util.Optional.ifPresent(Optional.java:178)
>         at io.ballerina.cli.launcher.Main.main(Main.java:58)
> 
> ERROR [Sarcastic_bot:(1:1,1:1)] Compilation failed due to: Cannot read field "flags" because "type.tsymbol" is null

**main.bal:**
 
> import ballerina/io;
> import ballerina/lang.runtime;
> import ballerinax/openai.finetunes;
> 
> configurable string token = ?;
> const SERVICE_URL = "https://api.openai.com/v1";
> const TRAINING_FILENAME = "training.jsonl";
> const VALIDATION_FILENAME = "validation.jsonl";
> const TRAINING_FILEPATH = "./data/" + TRAINING_FILENAME;
> const VALIDATION_FILEPATH = "./data/" + VALIDATION_FILENAME;
> 
> final finetunes:ConnectionConfig config = {auth: {token}};
> final finetunes:Client openAIFinetunes = check new finetunes:Client(config, SERVICE_URL);
> 
> public function main() returns error? {
> 
>     byte[] trainingFileContent = check io:fileReadBytes(TRAINING_FILEPATH);
>     byte[] validationFileContent = check io:fileReadBytes(VALIDATION_FILEPATH);
> 
>     finetunes:CreateFileRequest trainingFileRequest = {
>         file: {fileContent: trainingFileContent, fileName: TRAINING_FILENAME},
>         purpose: "fine-tune"
>     };
>     finetunes:CreateFileRequest validationFileRequest = {
>         file: {fileContent: validationFileContent, fileName: VALIDATION_FILENAME},
>         purpose: "fine-tune"
>     };
> 
>     finetunes:OpenAIFile trainingFileResponse =
>         check openAIFinetunes->/files.post(trainingFileRequest);
>     finetunes:OpenAIFile validationFileResponse =
>         check openAIFinetunes->/files.post(validationFileRequest);
> 
>     string trainingFileId = trainingFileResponse.id;
>     string validationFileId = validationFileResponse.id;
>     io:println("Training file id: " + trainingFileId);
>     io:println("Validation file id: " + validationFileId);
> 
>     finetunes:CreateFineTuningJobRequest fineTuneRequest = {
>         model: "gpt-3.5-turbo",
>         training_file: trainingFileId,
>         validation_file: validationFileId,
>         hyperparameters: {
>             n_epochs: 15,
>             batch_size: 3,
>             learning_rate_multiplier: 0.3
>         }
>     };
> 
>     finetunes:FineTuningJob fineTuneResponse =
>         check openAIFinetunes->/fine_tuning/jobs.post(fineTuneRequest);
>     string fineTuneJobId = fineTuneResponse.id;
>     io:println("Fine-tuning job id: " + fineTuneJobId);
> 
>     finetunes:FineTuningJob fineTuneJob =
>         check openAIFinetunes->/fine_tuning/jobs/[fineTuneJobId].get();
> 
>     io:print("Validating files...");
>     while fineTuneJob.status == "validating_files" {
>         io:print(".");
>         fineTuneJob = check openAIFinetunes->/fine_tuning/jobs/[fineTuneJobId].get();
>         runtime:sleep(1);
>     }
> 
>     io:print("\nFiles validated successfully.");
>     while fineTuneJob.status == "queued" {
>         io:print(".");
>         fineTuneJob = check openAIFinetunes->/fine_tuning/jobs/[fineTuneJobId].get();
>         runtime:sleep(1);
>     }
> 
>     io:println("\nTraining...");
>     finetunes:ListFineTuningJobEventsResponse eventsResponse;
>     while fineTuneJob.status == "running" {
>         fineTuneJob = check openAIFinetunes->/fine_tuning/jobs/[fineTuneJobId].get();
>         eventsResponse = check openAIFinetunes->/fine_tuning/jobs/[fineTuneJobId]/events.get();
>         io:println(eventsResponse.data[0].message);
>         runtime:sleep(1);
>     }
> 
>     if fineTuneJob.status != "succeeded" {
>         io:println("Fine-tuning job failed.");
>         return;
>     }
> 
>     io:println("\nFine-tuning job details: ");
>     io:println("Fine-tuned Model: ", fineTuneJob.fine_tuned_model);
>     io:println("Model: ", fineTuneJob.model);
>     io:println("Fine-tuning job completed successfully.");
> }

`bal pack` and `bal push --repository local` were used to push the connector to the local repository and used the below config in the Ballerina.toml
> [[dependency]]
> org = "ballerinax"
> name = "openai.finetunes"
> version = "1.0.5"
> repository = "local"

Finally, after deleting the local cache (.ballerina\repositories\local) and repeating the entire process, the issue did not occur again. It seems like there was a conflict with the local cache when pushing to it. 

### Steps to Reproduce

1. **Set Up the Environment**:
   - Ensure you have Ballerina installed on your system.
   - Clone or download the Ballerina connector for the OpenAI Fine-tunes API from [this repository](https://github.com/ballerina-platform/module-ballerinax-openai.finetunes).

2. **Write the Example Code**:
   - Create a new Ballerina project.
   - Use the provided example code (`main.bal`) in your project.
   - Ensure you have the required files, such as `training.jsonl` and `validation.jsonl`, in the appropriate directories.

3. **Build and Push the Connector**:
   - Run `bal pack` in the connector project to create a `.bala` file.
   - Push the connector to the local repository using the command:
     ```bash
     bal push --repository local
     ```
   - Update your `Ballerina.toml` file in your example project with the following dependency:
     ```toml
     [[dependency]]
     org = "ballerinax"
     name = "openai.finetunes"
     version = "1.0.5"
     repository = "local"
     ```

4. **Attempt to Build the Project**:
   - Run `bal build` on your project where you are using the connector.
   - This should trigger the error you described.

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$title

Fixes #43286

## Approach
Compiler error at L#1749 was not reached because the field `unknownTypeRefs` was populated at the silent typechecking and does not reset after.
https://github.com/ballerina-platform/ballerina-lang/blob/a6e4f994cd4746b11e5a8eb77c2f971bf26ff22b/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java#L1749
Introduced `GlobalStateData` inner class to make the solution scalable for such fields may occur in future

## Samples
The following sample should give unknown type error of unknown types `I` and `J`
```bal
class H {};

H res = check new I();

int[] a = [1, 2, 3, 4, 5];

int[] b = from var i in a select <I> i;

float result = <J>1 + 2.0;

int result2 = true? <J>1 : 2;

var result3 = <H> new J();
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -9933,4 +9947,12 @@ public static class AnalyzerData {
         QueryTypeChecker.AnalyzerData queryData = new QueryTypeChecker.AnalyzerData();
         Set<String> queryVariables;
     }
+
+    /**
+     * @since 2201.12.0
+     */
+    public static class GlobalStateData {
```
Comment (SasinduDilshara) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:9954]: Cant we use a Java record

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -9918,6 +9914,24 @@ String recordsToString(Set<BRecordType> recordTypeSet) {
         }
     }
 
+    public GlobalStateData getGlobalStateSnapshotAndResetGlobalState() {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:9917]: Can't we do this via analyzer data instead of introducing a new data holder?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:9954]: Good suggestion. This is updated

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:9917]: `AnalyzerData` act like set of global fields where we pass through the functions. `GlobalStateData` is used as a snapshot of several fields where we will be creating multiple of objects of it. However, we can still use the `AnalyzerData` for the same purpose. The issue is it will introduce unwanted object creations of the `AnalyzerData` which is not clean

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -9933,4 +9945,10 @@ public static class AnalyzerData {
         QueryTypeChecker.AnalyzerData queryData = new QueryTypeChecker.AnalyzerData();
         Set<String> queryVariables;
     }
+
+    /**
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:9949]: Add documentation (if we continue to keep this).

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:9917]: The addition is basically resetting unknown type refs, right? Can we just do it inline instead of introducing `GlobalStateData`? The name is ambiguous and can be confusing with analyzer data IMO.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java [hunk 4]
```diff
@@ -164,7 +164,7 @@ public class TypeResolver {
     private final HashSet<BLangClassDefinition> resolvedClassDef = new HashSet<>();
     private final Map<String, BLangNode> modTable = new LinkedHashMap<>();
     private final Map<String, BLangConstantValue> constantMap = new HashMap<>();
-    private final HashSet<LocationData> unknownTypeRefs;
+    public HashSet<LocationData> unknownTypeRefs;
```
[the remark this answers is not in the document]
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeResolver.java]: Added

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 3 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:9950]: Added

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Writing this inline is not a good idea in terms of scalability. We already have two fields that needs to be reset. There is a high chance of more fields require this in future. I have renamed the class name to `GlobalStateSnapshot`

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: The only additional thing we've done is changing unknown type refs, right? Error count logic was already there? It makes sense to extract out repeated logic to a function, but IMO, here we are just doing it for part of it. I would rather refactor the whole thing properly or just reset type refs in line (similar to the others). With just what we have now, I also don't think GlobalStateSnapshot is an ideal name here, since it doesn't include all "global state" and can be confusing with analyzer data.

I would introduce the change in a way that makes it readable and clear at the moment, rather than anticipating future changes (when we can refactor everything properly).

Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: I don't think this approach is less readable than the inline one. If we write this inline the code becomes messy, not scalable, and the same code will duplicate at every place where we do silent type checking. 

> It makes sense to extract out repeated logic to a function

Yes, to extract out repeated logic we need some kind of a object or  a record to get the previous data available at the caller function

**Review by gimantha — APPROVED** [review]
