### PR TITLE
Fix crash when analyzing exportable types

### LINKED ISSUE #32725: Ballerina project build fails throwing `StackOverflowError` exception
**Description:**
Following error was thrown while building Ballerina Jira connector which was generated using Ballerina Open API tool.

```
java.lang.StackOverflowError
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.lambda$checkForExportableType$21(CodeAnalyzer.java:2485)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.checkForExportableType(CodeAnalyzer.java:2485)
```

Please find the connector code [here](https://github.com/aneeshafedo/jira). 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by rpjayasekara**
Fixes #32725

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModulePublicVariableTest.java [hunk 1]
```diff
@@ -54,6 +54,7 @@ public void testModulePublicVariableAccess(String functionName) {
                 "testPublicVisibilityInComplexVar",
                 "testPublicWithIsolatedFuncType",
                 "testPublicWithIsolatedObjectType",
+                "testPublicFunctionWithRecordType"
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModulePublicVariableTest.java:57]: Is this the correct place for this test? There are no module-level variables in the test.

IMO, we don't need a test with modules here. We can add a simple test in a single bal file.

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModulePublicVariableTest.java:57]: Maybe a new `org.ballerinalang.test.access.AccessLevelsTest` at the same level as `org.ballerinalang.test.access.AccessLevelsNegativeTest`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 2]
```diff
@@ -2340,74 +2340,88 @@ private void analyzeExportableTypeRef(BSymbol owner, BTypeSymbol symbol, boolean
...
             // This is a built-in symbol or a type Param.
             return;
         }
+        if (visitedSymbols.contains(symbol)) {
+            return;
+        }
         switch (symbol.type.tag) {
             case TypeTags.ARRAY:
-                checkForExportableType(((BArrayType) symbol.type).eType.tsymbol, pos);
+                visitedSymbols.add(symbol);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:2359]: Why are we adding these here and not before the switch statement?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:2359]: Can also do 

```java
        if (!visitedSymbols.add(symbol)) {
            return;
        }
```

there instead.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModulePublicVariableTest.java (hunk 1 above)
Comment (rpjayasekara) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/vardeclr/ModulePublicVariableTest.java:57]: Added because Record type is defined in module level. Will Change it

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 2 above)
Comment (rpjayasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:2359]: +1, no need of doing it separately. Will fix it

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/access/AccessLevelTest.java [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+
+    CompileResult result;
+
+    @BeforeClass
+    public void setup() {
+        result = BCompileUtil.compile("test-src/access/access_level.bal");
+    }
+
+    @Test
+    public void testPublicFunctionWithRecordTypeParam() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/access/AccessLevelTest.java:39]:
```suggestion
    public void testPublicFunctionWithRecursiveArrayTypedParam() {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/access/access_level.bal [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+// under the License.
+
+public type Foo record {
+    string name;
+    Foo[] x?;
+}[];
+
+public function getFooName(Foo f) returns string{
+    return f[0].name;
+}
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/access/access_level.bal:24]:
```suggestion
public function getFooName(Foo f) returns string => f[0].name;
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/access/SymbolExposureTest.java [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+ */
+package org.ballerinalang.test.access;
+
+import org.ballerinalang.test.BCompileUtil;
+import org.ballerinalang.test.BRunUtil;
+import org.ballerinalang.test.CompileResult;
+import org.testng.annotations.Test;
+
+/**
+ * Positive tests for symbol exposure via public constructs.
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/access/SymbolExposureTest.java:26]:
```suggestion
 * Positive tests for symbol exposure via public constructs.
 * 
 * @since 2.0.0 
```

**Review by MaryamZi — APPROVED** [review]
