### PR TITLE
Fix clone() for array fields

### LINKED ISSUE #33706: value:clone returns same reference for different arrays
**Description:**
```ballerina
import ballerina/io;

type BddPath record {|
    int[] pos = [];
    int[] neg = [];
|};

public function main() {
    BddPath path = {};
    BddPath clone = path.clone();

    if path.pos === path.neg {
        panic error("Pos and Neg of original path");
    }

    // `pos` and the `neg` are not === in the original `path`.
    // After the clone they are === on cloned value.
    if clone.pos === clone.neg {
        io:println("t");
    }
    else {
        io:println("f");
    }

    clone.pos.push(1);
    io:println(clone.neg);
}
```

This is the same behavior when arrays have the same values (`==`), but when they have different values I didn't observe this.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject

Fixes #33706

## Approach
Fix the `equals()` method of Array Value to identify the value object when cloning a value.

## Samples
```ballerina
import ballerina/test;

type BddPath record {|
    int[] pos = [];
    int[] neg = [];
|};

public function main() {
    BddPath path = {};
    BddPath clone = path.clone();

    test:assertFalse(path.pos === path.neg);
    test:assertFalse(clone.pos === clone.neg);
    test:assertTrue(path.pos == path.neg);
    test:assertTrue(clone.pos == clone.neg);

    clone.pos.push(1);
    clone.pos.push(2);
    clone.pos.push(3);
    test:assertEquals(clone.pos, [1, 2, 3]);
    test:assertEquals(clone.neg, []);
    test:assertFalse(clone.pos == clone.neg);
}
```
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java [hunk 1]
```diff
@@ -1284,7 +1284,8 @@ public boolean equals(Object o) {
                 Arrays.equals(booleanValues, that.booleanValues) &&
                 Arrays.equals(byteValues, that.byteValues) &&
                 Arrays.equals(floatValues, that.floatValues) &&
-                Arrays.equals(bStringValues, that.bStringValues);
+                Arrays.equals(bStringValues, that.bStringValues) &&
+                typedesc.equals(that.typedesc);
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java:1288]: Shall we add typedesc.equals(that.typedesc) as first conditiion?

**Review by warunalakshitha — APPROVED** [review]
LGTM

File: bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java [hunk 2]
```diff
@@ -634,13 +631,6 @@ public void testTomlProviderUnions(String variableName, Type type, Object expect
                                                                 ValueCreator.createKeyFieldEntry(fromString("age"),
                                                                                                  14L),
                                                         })},
-                // union variable with array value
-                {"arrayUnionVar", TypeCreator.createUnionType(List.of(TYPE_INT, arrayType), true),
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java:638]: Any reason why we remove union test?

Comment (HindujaB) [reply bvm/ballerina-runtime/src/test/java/io/ballerina/runtime/test/config/TomlProviderTest.java:638]: This test checks the returning Array value with the expected Array value (which are two different objects). Since we removed the `equals` method for the fix, this will fail. Therefore, I moved this test to the configurable integration test.

**Review by warunalakshitha — APPROVED** [review]
LGTM
