### PR TITLE
Desugar transaction & retry without lambda wrapping

### LINKED ISSUE #26562: [Transaction] Panics caught from transaction body should trigger transaction to rollback
**Description:**
As per the spec,
image

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #26653: Bad Sad error using transaction with MySQL
The following code connects to the MySQL database and update the table information.
```
import ballerina/io;
import ballerina/sql;
import ballerinax/mysql;
string dbUser = "xxx";
string dbPassword = "xxx";
public function main() returns error? {
        mysql:Client|sql:Error mysqlClient = 
            check new (user = dbUser, password = dbPassword);
    if (mysqlClient is sql:Error) {
        io:println("Sample data initialization failed!");
        io:println(mysqlClient);
    } else {
        transaction {
            sql:ExecutionResult|sql:Error result = 
                mysqlClient->execute("UPDATE DB.Orders SET Status = 'Done' WHERE OrderId = 2"); 
            var commitResult = commit;
            if commitResult is () {
                io:println("Transaction committed");
            } else {
                io:println("Transaction failed");
            }
        }
        check mysqlClient.close();
        io:println("MySQL Client initialization for querying data successed!");
    }
}
```
This generates a Bad Sad error with the following stack trace for Swan Lake preview 4 version.
```
[2020-10-28 13:13:41,096] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:158)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:402)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:120)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:120)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:361)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:97)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:97)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:85)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:76)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:257)
	at org.wso2.ballerinalang.compiler.CompilerDriver.birGen(CompilerDriver.java:365)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:308)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:250)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:142)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:220)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:65)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:297)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 ```

The same code works fine for the MySQL JDBC connector.  Also if the connection initialization part moved into the transaction block it works as expected.

### LINKED ISSUE #26853: Using check  expression inside transaction does not return the error the invoking method
**Description:**
$subject

**Steps to reproduce:**
```

import ballerina/io;
import ballerina/sql;
import ballerina/java.jdbc;

public function main() returns error? {

    jdbc:Client dbClient = checkpanic new ("jdbc:mysql://localhost:3306/DEMO", "test", "Test#123");

    // Insert a record into the candidates table and get the inserted ID back.
    // Insert a set of candidate ID and Skill ID into the candidate_skills table.
    // If all above operations are successfully, commit the transaction, otherwise roll it back.

    string firstName = "John";
    string lastName = "Doe";
    sql:DateValue dob = new ("1990-01-04");
    int skill = 10;

    transaction {

        sql:ParameterizedQuery candidateInsert = `INSERT INTO candidates (first_name,last_name, dob) VALUES (${firstName}, ${
        lastName}, ${dob})`;
        sql:ExecutionResult execResult = check dbClient->execute(candidateInsert);

        int candidateId = <int>execResult.lastInsertId;
        io:println("Newly inserted Candidate Id : " + candidateId.toString());

        sql:ParameterizedQuery candidateSkillInsert = `INSERT INTO candidate_skills VALUES (${candidateId}, ${skill})`;
        sql:ExecutionResult skillUpdateResult = check dbClient->execute(candidateSkillInsert);

        var commitResult = commit;
        if commitResult is () {
            io:println("Transaction committed");
        } else {
            io:println("Transaction failed");
        }
    }

    io:println("Finished executing the samples");
    check dbClient.close();
}
```

Here the error is not logged, even though check exits transaction after rollback and continues

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #26562
Fixes #26853
Fixes #26653

Addresses #27260 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [x] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -3757,28 +3996,203 @@ public void visit(BLangUnLockStmt unLockStmt) {
...
     public void visit(BLangTransaction transactionNode) {
-        BLangOnFailClause currentOnFailClause = this.onFailClause;
-        BLangSimpleVariableDef currentOnFailCallDef = this.onFailCallFuncDef;
-        analyzeOnFailClause(transactionNode.onFailClause, transactionNode.transactionBody);
-        BLangStatementExpression transactionStmtExpr = transactionDesugar.rewrite(transactionNode, env,
-                onFailClause != null);
-        result = createExpressionStatement(transactionNode.pos, transactionStmtExpr,
-                transactionNode.statementBlockReturns, env);
-        swapAndResetEnclosingOnFail(currentOnFailClause, currentOnFailCallDef);
+        if (transactionNode.onFailClause != null) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:4042]: add more comments with desugaring
