### PR TITLE
[2201.9.0] Suppress the warnings from imports

### LINKED ISSUE #32985: Bal build is showing compilation warnings for external modules
**Description:**
$title. For example, if we use an external module that does not have documented fields, we get `undocumented field` warnings when we compile the original project. Since the developer doesn't have any control over these warnings, it is better to remove these warnings from getting printed in the current project.

**Steps to reproduce:**

Build a project with an external module that has compilation warnings.

Example code:

```
import ballerinax/covid19;
import ballerina/http;

service / on new http:Listener(8090) {
    resource function get .(http:Request req) returns json|error? {

        covid19:Client covid19Endpoint = check new ();
    }
}
```

This will produce the following warnings 

```
Compiling source
        mirajabeysekara/sandbox12:0.1.0
ballerinax/covid19:1.0.0 [central.ballerina.io -> home repo]  100% [=======================================================================] 12/12 KB (0:00:00 / 0:00:00) 
        ballerinax/covid19:1.0.0 pulled from central successfully
WARNING [ballerinax/covid19/1.0.0::types.bal:(163:5,163:27)] undocumented field 'cases'
WARNING [ballerinax/covid19/1.0.0::types.bal:(164:5,164:28)] undocumented field 'deaths'
WARNING [ballerinax/covid19/1.0.0::types.bal:(165:5,165:31)] undocumented field 'recovered'
WARNING [ballerinax/covid19/1.0.0::types.bal:(367:5,367:18)] undocumented field 'cases'
WARNING [ballerinax/covid19/1.0.0::types.bal:(368:5,368:28)] undocumented field 'deaths'
WARNING [ballerinax/covid19/1.0.0::types.bal:(369:5,369:31)] undocumented field 'recovered'

Running Tests

        sandbox12

                No tests found


Generating executable
Language telemetry service is disabled.
        target/bin/sandbox12.jar
```

**Affected Versions:**
SL Beta3 RC4

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
Fixes #32985 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java [hunk 1]
```diff
@@ -155,6 +155,10 @@ public BuildCommand() {
     @CommandLine.Option(names = "--cloud", description = "Enable cloud artifact generation")
     private String cloud;
 
+@CommandLine.Option(names = "--showAllWarnings", description = "Show all the warnings including the " +
```
Comment (nipunayf) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java:158]: Apply for other applicable areas as well.

```suggestion
    @CommandLine.Option(names = "--showAllWarnings", description = "Show all the warnings including the " +
```

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java [hunk 2]
```diff
@@ -173,8 +173,12 @@ private void performCodeGen(boolean shrink) {
                 moduleContext.generatePlatformSpecificCode(compilerContext, this);
             }
             for (Diagnostic diagnostic : moduleContext.diagnostics()) {
-                moduleDiagnostics.add(
-                        new PackageDiagnostic(diagnostic, moduleContext.descriptor(), moduleContext.project()));
+                if (this.packageContext.project().buildOptions().showAllWarnings() ||
+                        !ProjectKind.BALA_PROJECT.equals(moduleContext.project().kind()) ||
+                        !(diagnostic.diagnosticInfo().severity() == DiagnosticSeverity.WARNING)) {
```
Comment (nipunayf) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java:178]: Why are we only suppressing warnings? What about hints and info?

**Comment by sameerajayasoma** [comment]
The compiler option `--showAllWarnings` is too generic. We need an option to see only the dependent package warnings right?

**Comment by azinneera** [comment]
> The compiler option `--showAllWarnings` is too generic. We need an option that shows only the dependent package warnings, right?
> 
> We already show current package warnings. So `--showAllWarnings` doesn't make sense.

Considering the above comment and @nipunayf's suggestion to hide INFO and HINT diagnostics also by default, how about `--showDependencyDiagnostics`?

**Comment by Thevakumar-Luheerathan** [comment]
> We need an option that shows only the dependent package warnings
> 


It means, that when the user gives `bal build --<option-we-introduce>, should we print only the diagnostics from the dependent package? shouldn't we print the current package diagnostics?

File: cli/ballerina-cli/src/main/resources/cli-help/ballerina-build.help [hunk 3]
```diff
@@ -63,6 +63,10 @@ OPTIONS
            Include the dependencies that are required to enable remote package
            management service.
 
+       --show-dependency-diagnostics
+           Print the diagnostics which are related to the dependencies. Normally, these
```
Comment (azinneera) [inline cli/ballerina-cli/src/main/resources/cli-help/ballerina-build.help:67]:
```suggestion
           Print the diagnostics that are related to the dependencies. By default, these
```

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java [hunk 4]
```diff
@@ -209,8 +210,12 @@ private void compileModulesInternal() {
             for (ModuleContext moduleContext : packageResolution.topologicallySortedModuleList()) {
                 moduleContext.compile(compilerContext);
                 for (Diagnostic diagnostic : moduleContext.diagnostics()) {
-                    diagnostics.add(new PackageDiagnostic(diagnostic, moduleContext.descriptor(),
-                            moduleContext.project()));
+                    if (!ProjectKind.BALA_PROJECT.equals(moduleContext.project().kind()) ||
+                            (diagnostic.diagnosticInfo().severity() == DiagnosticSeverity.ERROR) ||
+                            (diagnostic.diagnosticInfo().severity() == DiagnosticSeverity.INTERNAL)) {
```
Comment (azinneera) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java:215]: Why do we need the INTERNAL diagnostics?

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java [hunk 5]
```diff
@@ -209,8 +210,12 @@ private void compileModulesInternal() {
             for (ModuleContext moduleContext : packageResolution.topologicallySortedModuleList()) {
                 moduleContext.compile(compilerContext);
                 for (Diagnostic diagnostic : moduleContext.diagnostics()) {
-                    diagnostics.add(new PackageDiagnostic(diagnostic, moduleContext.descriptor(),
-                            moduleContext.project()));
+                    if (!ProjectKind.BALA_PROJECT.equals(moduleContext.project().kind()) ||
```
Comment (azinneera) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java:213]: The condition to check if the build option is set is missing here.

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java (hunk 4 above)
Comment (Thevakumar-Luheerathan) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java:215]: I mistakenly took it as an error.. I think we can remove it.

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java [hunk 6]
```diff
@@ -155,6 +155,10 @@ public BuildCommand() {
     @CommandLine.Option(names = "--cloud", description = "Enable cloud artifact generation")
     private String cloud;
 
+    @CommandLine.Option(names = "--show-dependency-diagnostics", description = "Show the diagnostics " +
+            "generated by the dependencies")
```
Comment (NipunaRanasinghe) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java:159]: The new command option name `--show-dependency-diagnostics` could imply that errors are also being suppressed if it's not enabled. So, I'm thinking whether `--show-dependency-warnings` would be a clearer choice. @azinneera thoughts?

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java (hunk 5 above)
Comment (Thevakumar-Luheerathan) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java:213]: This is required for the LS. As we discussed offline, we don't pass it here because build options/ compilation options can't be passed up to this point.

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java (hunk 6 above)
Comment (Thevakumar-Luheerathan) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java:159]: It could imply the warnings only right... we need suppress info, hint as well..

Comment (sameerajayasoma) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java:159]: We discussed this fact earlier @NipunaRanasinghe.  We are showing hints, info, and warnings at the moment. But there is plan to suppress errors in the future as well: hide actual errors show a user-friendly version. If a user wants to see actual errors, this option needs to be given. 

With that, I think `--show-dependency-diagnostics` is good.

**Review by azinneera — APPROVED** [review]

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java (hunk 6 above)
Comment (NipunaRanasinghe) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/BuildCommand.java:159]: @sameerajayasoma got it :) yeah that makes sense
