### PR TITLE
Resolve TypeParams in ExpectedTypeFinder

### LINKED ISSUE #38338: [Improvement]: Improve snippet completion item of dependently typed functions
### Description

Currently the language server suggest the genetic completion item snippet for function parameters of the dependency typed functions. As example for the `map` function in the `array` module we suggest.

```
string[] arr = [];

arr.'map(function (array:Type t) returns array:Type1 {
        return ;
    })
```

### Describe your solution(s)

Here we know the type of this array so we can improve the completion item with the correct type. So the final result would be like this.

```
string[] arr = [];

arr.'map(function (string  item) returns string {
        return item;
    })
```

### LINKED ISSUE #41685: [Bug]: IndexOutOfBoundsException in ExpectedTypeFinder
### Description

An IndexOutOfBoundsException is thrown at the following cursor position,

Screenshot 2023-11-13 at 14 04 05

### Steps to Reproduce

```
type User record {|
    string name;
    string age;
|};

type Payload record {|
    record {|
        *User;
    |} patient;
|};

function foo(Payload payload) {
    Payload {patient: {name: b, ...a}} = payload;
    log:printInfo("Appointment reservation successful", name = <cursor>);
}
```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by nipunayf**
## Purpose

The current completions for lang lib functions do not resolve the type params, and thus, private lang lib types such as `array:Type` are exposed to the user with the completions. The current PR improves the completion to return the resolved lang lib functions to the user.

Fixes #38338
Fixes #41685

## Approach
The implemented approach intercepts the `ExpectedTypeFinder` by integrating a `resolveType` method that has the cohesion to resolve the type params where applicable. If there are type params, it determines the bound type by visiting the parent nodes.

## Samples
Code completion now provides:
```ballerina
_ = arr.forEach(function (string s) {
        
    });
```

instead of:
```ballerina
_ = arr.forEach(function (array:Type t) {
        
    });
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamBoundFinder.java [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+import java.util.Iterator;
+
+/**
+ * A visitor class to determine the bound type of the type param.
+ *
+ * @since 2201.8.0
+ */
+public class TypeParamBoundFinder extends NodeVisitor {
+
+    private ExpressionNode expressionNode;
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamBoundFinder.java:39]: Let's rename this to indicate that this is the expression in function call expr.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamBoundFinder.java [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+        Node childNode;
+
+        while (it.hasNext()) {
+            childNode = it.next();
+            if (childNode.equals(this.positionalArgumentNode)) {
+                this.position = (positionIndex - 4) / 2;
+                break;
+            }
+            positionIndex++;
+        }
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamBoundFinder.java:76]: Can't we use `methodCallExpressionNode.arguments()` here?

Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamBoundFinder.java:76]: Can't we use `methodCallExpressionNode.arguments()` here?

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamBoundFinder.java [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+import io.ballerina.compiler.syntax.tree.NodeVisitor;
+import io.ballerina.compiler.syntax.tree.PositionalArgumentNode;
+import io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode;
+
+import java.util.Iterator;
+
+/**
+ * A visitor class to determine the bound type of the type param.
+ *
+ * @since 2201.8.0
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamBoundFinder.java:35]:
```suggestion
 * @since 2201.9.0
```

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java [hunk 4]
```diff
@@ -129,6 +131,16 @@ private List<FunctionSymbol> getMethods(String langLibName, BType type) {
...
 
+    private String getLangLibName(BType type) {
+        String langLibName;
+        if (type.getKind() == TypeKind.UNION && types.isAllErrorMembers((BUnionType) type)) {
+            langLibName = TypeKind.ERROR.typeName();
+        } else {
+            langLibName = getAssociatedLangLibName(type.getKind());
+        }
+        return langLibName;
+    }
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java:142]:
```suggestion
    private String getLangLibName(BType type) {
        if (type.getKind() == TypeKind.UNION && types.isAllErrorMembers((BUnionType) type)) {
            return TypeKind.ERROR.typeName();
        }
        return getAssociatedLangLibName(type.getKind());
    }
```

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 5]
```diff
@@ -161,6 +163,45 @@ public ExpectedTypeFinder(SemanticModel semanticModel, BLangCompilationUnit bLan
...
+        BVarSymbol firstParam = originalLangLibMethod.params.get(0);
+        BType typeParam = new TypeParamFinder().find(firstParam.getType());
+
+        if (typeParam == null) {
+            return node.apply(this);
+        }
+
+        BInvokableSymbol langLibMethod =
+                this.langLibFunctionBinder.cloneAndBind(originalLangLibMethod, langNode.getBType(),
+                        SymbolUtils.getTypeParamBoundType(langNode.getBType()));
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:197]: Let's extract `langNode.getBType()` into a seperate variable.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibFunctionBinder.java [hunk 6]
```diff
@@ -43,8 +43,8 @@ public class LangLibFunctionBinder {
     private final Types types;
     private final CompilerContext context;
 
-    public LangLibFunctionBinder(Types types, CompilerContext context) {
-        this.types = types;
+    public LangLibFunctionBinder(CompilerContext context) {
```
Comment (malinthar) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibFunctionBinder.java:46]: This is a breaking change right? We should deprecate the existing constructor and introduce a new one.  Let's omit this change as this is not related to our changes.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java [hunk 7]
```diff
@@ -70,7 +66,7 @@ private LangLibrary(CompilerContext context) {
         this.symbolFactory = SymbolFactory.getInstance(context);
         this.langLibMethods = new HashMap<>();
         this.types = Types.getInstance(context);
-        this.methodBinder = new LangLibFunctionBinder(this.types, context);
+        this.methodBinder = new LangLibFunctionBinder(context);
```
Comment (malinthar) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java:69]: Let's remove this change. It's not necessary.

**Review by malinthar — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamBoundFinder.java [hunk 8]
```diff
@@ -0,0 +1,98 @@
...
+            positionIndex++;
+        }
+    }
+
+    @Override
+    protected void visitSyntaxNode(Node node) {
+    }
+
+    private void visitParentNode(Node node) {
+        node.parent().accept(this);
```
[the remark this answers is not in the document]
Comment (nipunayf) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamBoundFinder.java:82]: Since all the methods call the `visitSyntaxNode` by default, it has been made the termination condition. Thus, all the nodes that are not relevant to finding the type parameter bound terminate the visitor. In contrast,`visitParentNode` moves up the tree to determine the bound type where it is relevant.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 9]
```diff
@@ -161,6 +163,45 @@ public ExpectedTypeFinder(SemanticModel semanticModel, BLangCompilationUnit bLan
         this.typesFactory = TypesFactory.getInstance(context);
         this.linePosition = linePosition;
         this.document = srcDocument;
+        this.langLibrary = LangLibrary.getInstance(context);
+        this.langLibFunctionBinder = new LangLibFunctionBinder(context);
+    }
+
+    public Optional<TypeSymbol> resolveType(Node node) {
+        TypeParamBoundFinder typeParamVisitor = new TypeParamBoundFinder();
```
[the remark this answers is not in the document]
Comment (nipunayf) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:171]: This was my implementation. However, I couldn't cover the case when the cursor is immediately after the separator (`,`). For instance, consider the following case.
```ballerina
string[] arr = ["a", "aa", "abb"];
arr.sort(array:ASCENDING, <cursor>);
```
Both `string var1 = <cursor>` and the one above return `BallerinaStringTypeSymbol` as the expected type.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/util/SymbolUtils.java [hunk 10]
```diff
@@ -79,4 +86,26 @@ public static Optional<TypeSymbol> getTypeDescriptor(Symbol symbol) {
                 return Optional.empty();
         }
     }
+
+     public static BType getTypeParamBoundType(BType type) {
```
Comment (mindula) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/util/SymbolUtils.java:90]: Let's add a java doc

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java [hunk 11]
```diff
@@ -96,27 +92,33 @@ public static LangLibrary getInstance(CompilerContext context) {
...
+    /**
+     * Returns the lang library method of the given type descriptor kind and the method name.
+     *
+     * @param type Type descriptor kind
+     * @param methodName Name of the lang library function
+     * @return The associated lang library function
+     */
+    public BInvokableSymbol getLangLibMethod(BType type, String methodName) {
+        Map<String, BInvokableSymbol> methods = langLibMethods.get(getLangLibName(type));
+        return methods.get(methodName);
```
Comment (mindula) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java:104]:
```suggestion
        return langLibMethods.get(getLangLibName(type)).get(methodName);
```

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 12]
```diff
@@ -333,6 +347,57 @@ public Optional<TypeSymbol> transform(MethodCallExpressionNode node) {
             return Optional.empty();
         }
 
+//        TODO: Need to implement code to detect the position when the `PositionalArgumentNode`is null.
+//        (e.g. `arr.sort(array:ASCENDING, <cursor >`). Since sort is the only lang lib function that accepts a
+//        @typeParam function in the second parameter and it is yet to be supported, this should be implemented
+//        along with https://github.com/ballerina-platform/ballerina-lang/issues/41498.
```
Comment (mindula) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:353]: No need to include the entire link of the issue, we can just add the issue number (#41498).

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java [hunk 13]
```diff
@@ -96,27 +92,33 @@ public static LangLibrary getInstance(CompilerContext context) {
         return langLib;
     }
 
+    /**
+     * Returns the lang library method of the given type descriptor kind and the method name.
+     *
+     * @param type Type descriptor kind
+     * @param methodName Name of the lang library function
```
Comment (mindula) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java:99]: We can align the javadoc comments for consistency and readability

```suggestion
     * @param type                Type descriptor kind
     * @param methodName Name of the lang library function
```

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 14]
```diff
@@ -333,6 +347,57 @@ public Optional<TypeSymbol> transform(MethodCallExpressionNode node) {
...
+//        along with #41498.
+        int position = 1;
+        if (this.positionalArgNodeAtCursor != null) {
+            for (FunctionArgumentNode argNode : node.arguments()) {
+                if (argNode.equals(this.positionalArgNodeAtCursor)) {
+                    break;
+                }
+                position++;
+            }
+        }
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:362]: Can we do this just before the `position` is used?

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 15]
```diff
@@ -333,6 +347,57 @@ public Optional<TypeSymbol> transform(MethodCallExpressionNode node) {
...
+
+        ExpressionNode functionCallExpressionNode = node.expression();
+        if (functionCallExpressionNode == null) {
+            return transformDefaultMethodCallExprNode(bLangNode, node);
+        }
+
+        BLangNode langNode = nodeFinder.lookup(this.bLangCompilationUnit,
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:369]:
```suggestion
        BLangNode bLangFuncCallExpr = nodeFinder.lookup(this.bLangCompilationUnit,
```

**Comment by KavinduZoysa** [comment]
```ballerina
import ballerina/lang.array;

public function main() {
    string[] arr = ["a", "b", "c"];
    array:'map(arr, function (array:Type t) returns array:Type1 {
        return ;
    })
}
```

@nipunayf, I think this case is not working, please have a look.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 16]
```diff
@@ -1188,4 +1236,46 @@ private boolean isWithinParenthesis(Token openParen, Token closeParen) {
         return !isParenthesisMissing(openParen, closeParen) &&
                 isPosWithinOpenCloseLineRanges(linePosition, openParen.lineRange(), closeParen.lineRange());
     }
+
+    private Optional<TypeSymbol> transformFunctionOrMethod(BLangNode bLangNode, BType variableType,
+                                                           BInvokableSymbol bLangOriginalLangLib,
```
Comment (malinthar) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:1241]: This is not always a langLib. Can be a method or even a function defined in the source. So shall we use something like `originalInvokable` as the parameter name?

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 17]
```diff
@@ -1188,4 +1236,46 @@ private boolean isWithinParenthesis(Token openParen, Token closeParen) {
         return !isParenthesisMissing(openParen, closeParen) &&
                 isPosWithinOpenCloseLineRanges(linePosition, openParen.lineRange(), closeParen.lineRange());
     }
+
+    private Optional<TypeSymbol> transformFunctionOrMethod(BLangNode bLangNode, BType variableType,
```
Comment (malinthar) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:1240]:
```suggestion
    private Optional<TypeSymbol> transformFunctionOrMethod(BLangNode bLangNode, BType parameterType,
```

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 18]
```diff
@@ -1188,4 +1236,46 @@ private boolean isWithinParenthesis(Token openParen, Token closeParen) {
...
+
+        if (typeParam == null) {
+            return getExpectedTypeFromFunction(bLangNode, openParenToken, closeParenToken);
+        }
+
+        BInvokableSymbol langLibMethod =
+                this.langLibFunctionBinder.cloneAndBind(bLangOriginalLangLib, variableType,
+                        SymbolUtils.getTypeParamBoundType(variableType));
+
+        if (langLibMethod.getParameters().size() < 2) {
```
Comment (malinthar) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:1260]: Shall we put a comment specifying why  `size >=2 ` condition should be satisfied (Just add a sample langlib method with parameters in the comment)

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 19]
```diff
@@ -1188,4 +1236,46 @@ private boolean isWithinParenthesis(Token openParen, Token closeParen) {
...
+    private Optional<TypeSymbol> transformFunctionOrMethod(BLangNode bLangNode, BType variableType,
+                                                           BInvokableSymbol bLangOriginalLangLib,
+                                                           SeparatedNodeList<FunctionArgumentNode> arguments,
+                                                           Token openParenToken, Token closeParenToken,
+                                                           boolean hasFirstArg) {
+        if (bLangOriginalLangLib == null || bLangOriginalLangLib.params.size() == 0) {
+            return getExpectedTypeFromFunction(bLangNode, openParenToken, closeParenToken);
+        }
+
+        BVarSymbol firstParam = bLangOriginalLangLib.params.get(0);
```
Comment (malinthar) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java:1249]: Are we certain that the the first param will aways be of type `function` with type params. If so shall we specify that using a comment.

**Review by malinthar — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java [hunk 20]
```diff
@@ -333,14 +347,19 @@ public Optional<TypeSymbol> transform(MethodCallExpressionNode node) {
...
         }
 
-        BLangInvocation bLangInvocation = (BLangInvocation) bLangNode;
-        Token openParen = node.openParenToken();
-        Token closeParen = node.closeParenToken();
-        if (isWithinParenthesis(openParen, closeParen)) {
-            return getExpectedTypeFromFunction(bLangInvocation);
+        ExpressionNode functionCallExpressionNode = node.expression();
+        if (functionCallExpressionNode == null) {
+            return getExpectedTypeFromFunction(bLangNode, node.openParenToken(), node.closeParenToken());
```
[the remark this answers is not in the document]
Comment (nipunayf) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java]: There cannot be a case where the expression node can be null since the method call expression node's existence depends on the expression node. Thus, removing this condition.

**Review by malinthar — CHANGES_REQUESTED** [review]
Let's add test cases for the ExpectedTypeFinder as well. See https://github.com/ballerina-platform/ballerina-lang/tree/master/tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype

**Review by KavinduZoysa — APPROVED** [review]
