### PR TITLE
Fix toJson() conversion of table with rest type records

### LINKED ISSUE #32524: `toJson()` provides incorrect results for table to Json conversion
**Description:**

For tables contains records with rest fields as constrained type, the conversion to json using `toJson` provides incorrect results. 
Consider the following code snippets 
```
type Foo record {|
   int id;
   float math;
   float ...;
|};

public function main() {

    table<Foo> tb = table [
         {id: 1001, math: 99.0, "physics": 91.5}
    ];
    json j = tb.toJson();
}
```
The current output is `[{"id":1001,"math":99.0}]`
But the expected output should be `[{"id":1001,"math":99.0,"physics": 91.5}]`

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #32524

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TableJsonDataSource.java [hunk 1]
```diff
@@ -106,131 +101,76 @@ public Object build() {
...
-                        }
-                        structError = false;
-                    }
-                }
-            }
-            if (structError) {
-                throw new BallerinaException("error in constructing the json object from struct type data");
-            }
-            return jsonData;
+                throw new BallerinaException("cannot construct the json object from '" + type + "' type data");
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TableJsonDataSource.java:169]:
```suggestion
                throw new BallerinaException("cannot construct json object from '" + type + "' type data");
```
A small suggestion on the error message.

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Review by HindujaB — APPROVED** [review]
LGTM
