### PR TITLE
Fix Compilation error when function has a function typed param with only rest params

### LINKED ISSUE #20919: Compilation error when function has a function typed param with only rest param
**Description:**
The sample code is as below.
```ballerina
function foo(int x, function (int...) returns float bar) returns int {
    return x ;
}

public function main() {
    
}
```

When this is compiled the compiler complains that the `x` variable in the return is an undefined symbol.

```bash
error: .::main.bal:2:12: undefined symbol 'x'
```

This only happens when the function typed param has only a rest param. So if we have another param in function type this issue isn't there.

```ballerina
function foo(int x, function (int, int...) returns float bar) returns int {
    return x ;
}

public function main() {
    
}
```

**Affected Versions:**
Ballerina 1.1.1

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #20919 

## Approach
Var list stack pops out the empty list added to the var list stack if function typed param has only rest param

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java [hunk 1]
```diff
@@ -574,6 +574,9 @@ void addFunctionType(DiagnosticPos pos, Set<Whitespace> ws, boolean paramsAvail,
         if (paramsAvail) {
             functionTypeNode.addWS(commaWsStack.pop());
             functionTypeNode.params.addAll(this.varListStack.pop());
+        } else if (restParamAvail) {
+            // VarListStack pops when function typed param has only rest params, Fix for: 20919
```
Comment (irshadnilam) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java]: We normally don't mention the issue number on fixes. Shall we remove the issue number?

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal [hunk 2]
```diff
@@ -177,3 +177,27 @@ type Person object {
...
+
+function testInvokeFunctionWithFunctionTypedParamWithOnlyRestParam1() returns [int,int]{
+    int[] x = [4];
+    return functionWithFunctionTypedParamWithOnlyRestParam(x, sampleFunctionTypedParam);
+}
+
+function testInvokeFunctionWithFunctionTypedParamWithOnlyRestParam2() returns [int,int]{
+    int[] x = [10, 20, 30];
+    return functionWithFunctionTypedParamWithOnlyRestParam(x, sampleFunctionTypedParam);
+}
```
Comment (irshadnilam) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal]: Line break

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java (hunk 1 above)
Comment (dulvinw) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java]: +1

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java]: Okay. Thanks!

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal [hunk 3]
```diff
@@ -177,3 +177,27 @@ type Person object {
...
+
+function sampleFunctionTypedParam(int... a) returns int{
+    if (a.length() > 0) {
+        return a[0];
+    } else {
+        return 0;
+    }
+}
+
+function testInvokeFunctionWithFunctionTypedParamWithOnlyRestParam1() returns [int,int]{
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal]: Shall we shorten the function name?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java [hunk 4]
```diff
@@ -574,6 +574,9 @@ void addFunctionType(DiagnosticPos pos, Set<Whitespace> ws, boolean paramsAvail,
         if (paramsAvail) {
             functionTypeNode.addWS(commaWsStack.pop());
             functionTypeNode.params.addAll(this.varListStack.pop());
+        } else if (restParamAvail) {
+            // VarListStack pops when function typed param has only rest params
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java]: Do we need this comment? Shall we maybe improve it to indicate popping out the empty list added to the var list stack if no non-rest params are available?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureTest.java [hunk 5]
```diff
@@ -444,4 +444,30 @@ public static ArrayValue mockedNativeFuncWithOptionalParams(long a, double b, St
         tuple.add(4, (Object) e);
         return tuple;
     }
+
+    @Test(description = "Test1: function signature which has a function typed param with only rest param")
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureTest.java]: Since recently, we've been trying to write the tests more in Ballerina. For example, https://github.com/ballerina-platform/ballerina-lang/blob/133d9010951cf306ffc708243a18bc3e9f111c22/tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal#L31.
Shall we try and do the same for the newly added tests?

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal [hunk 6]
```diff
@@ -177,3 +177,27 @@ type Person object {
         return [intVal, val];
     }
 };
+
+// ------------------- Test function signature which has a function typed param with only rest param ------------------
+
+function functionOfFunctionTypedParamWithRest(int[] x, function (int...) returns int bar) returns [int,int] {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal]:
```suggestion
function functionOfFunctionTypedParamWithRest(int[] x, function (int...) returns int bar) returns [int, int] {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal [hunk 7]
```diff
@@ -177,3 +177,27 @@ type Person object {
...
+    return [x[0], bar(x[0])] ;
+}
+
+function sampleFunctionTypedParam(int... a) returns int{
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal]:
```suggestion
function sampleFunctionTypedParam(int... a) returns int {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal [hunk 8]
```diff
@@ -177,3 +177,27 @@ type Person object {
...
+    if (a.length() > 0) {
+        return a[0];
+    } else {
+        return 0;
+    }
+}
+
+function testFunctionOfFunctionTypedParamWithRest1() returns [int,int]{
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal]:
```suggestion
function testFunctionOfFunctionTypedParamWithRest1() returns [int, int] {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal [hunk 9]
```diff
@@ -177,3 +177,27 @@ type Person object {
...
+    int[] x = [4];
+    return functionOfFunctionTypedParamWithRest(x, sampleFunctionTypedParam);
+}
+
+function testFunctionOfFunctionTypedParamWithRest2() returns [int,int]{
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/different-function-signatures.bal]:
```suggestion
function testFunctionOfFunctionTypedParamWithRest2() returns [int, int] {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java (hunk 4 above)
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java]: Thanks. Resolved

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureTest.java (hunk 5 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionSignatureTest.java]: Thanks. Changed made
