### PR TITLE
Fix type reference for readonly record fields

### LINKED ISSUE #37109: Dependant module initialization for test suite failed when building the WebSub module after updating the dependencies
**Description:**
Compiling WebSub module after updating the lang version and the dependent versions compatible with the latest lang gives a Dependant module initialization for test suite failed error.

**Steps to reproduce:**

Fails for this dependency update PR,
https://github.com/ballerina-platform/module-ballerina-websub/pull/546

Delete the `Dependancies.toml` files and run the gradle build with tests.

The following logs were printed :
```
Running Tests with Coverage

        websub
error: Dependant module initialization for test suite failed due to java.lang.ClassCastException 
{"message":"class io.ballerina.runtime.internal.types.BTypeReferenceType cannot be cast to class
 io.ballerina.runtime.api.types.SelectivelyImmutableReferenceType (io.ballerina.runtime.internal.types.
BTypeReferenceType and io.ballerina.runtime.api.types.SelectivelyImmutableReferenceType are in 
unnamed module of loader 'app')"}
        at ballerina.lang.value.0:cloneReadOnly(value.bal:58)
           ballerina.websub$test.2.tests.additional_external_error_data_test:$annot_func$_235
          (tests/additional_external_error_data_test.bal:24)
```

This is pointing to `additional_external_error_data_test` file and when the tests in this file is removed, again this error occurred pointing to the next test file 

```
Running Tests with Coverage

        websub
error: Dependant module initialization for test suite failed due to java.lang.ClassCastException 
{"message":"class io.ballerina.runtime.internal.types.BTypeReferenceType cannot be cast to class
 io.ballerina.runtime.api.types.SelectivelyImmutableReferenceType (io.ballerina.runtime.internal.types.
BTypeReferenceType and io.ballerina.runtime.api.types.SelectivelyImmutableReferenceType are in 
unnamed module of loader 'app')"}
        at ballerina.lang.value.0:cloneReadOnly(value.bal:58)
           ballerina.websub$test.2.tests.basic_subscriber_test:$annot_func$_235
           (tests/basic_subscriber_test.bal:24)
```

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes #37109

## Approach
Added cases for the type reference type fields.

## Remarks
The web-sub tests were passing locally.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java [hunk 1]
```diff
@@ -124,6 +126,10 @@ private static Type getAvailableImmutableType(Type type) {
             return ((BIntersectionType) type).getEffectiveType();
         }
 
+        if (type.getTag() == TypeTags.TYPE_REFERENCED_TYPE_TAG) {
+            return getAvailableImmutableType(((ReferenceType) type).getReferredType());
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java:130]: Should this be call before checking the intersection type?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java [hunk 2]
```diff
@@ -351,8 +357,9 @@ private static BIntersectionType createAndSetImmutableIntersectionType(Module pk
      */
     public static Type getMutableType(BIntersectionType intersectionType) {
         for (Type type : intersectionType.getConstituentTypes()) {
-            if (intersectionType.getEffectiveType().getTag() == type.getTag()) {
-                return type;
+            Type referredType = TypeUtils.getReferredType(type);
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java:360]: Shall we create an issue to add a test

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java (hunk 1 above)
Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java:130]: Since this is a recursive call to the same method, it will not affect the `IntersectionType` related logic.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java (hunk 2 above)
Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java:360]: created https://github.com/ballerina-platform/ballerina-lang/issues/37112

**Review by warunalakshitha — APPROVED** [review]
