### PR TITLE
Fix `IllegalArgumentException` in type-narrowed symbols with singleton type

### LINKED ISSUE #34708: IllegalArgumentException when hover is expr inside if condition context
**Description:**
Below sample causes `IllegalArgumentException` when I hover result var ref in RHS of the logical expression.

```bal
function testUnreachabilityWithIfStmtWithUnaryNot() {
    1|2 result = 2;

    if result is 1 || result is 2 {
    }
}
```

<details>
  <summary>Stack trace.(Click to expand)</summary>

```
[Error - 2:54:14 PM] Operation 'text/hover' failed! {uri: '/home/dulmina/Documents/test2.bal', [4:23], error: 'Symbol is 'null''}
java.lang.IllegalArgumentException: Symbol is 'null'
	at io.ballerina.compiler.api.impl.SymbolFactory.getBCompiledSymbol(SymbolFactory.java:129)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.definition(BallerinaTypeReferenceTypeSymbol.java:104)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.getModule(BallerinaTypeReferenceTypeSymbol.java:122)
	at io.ballerina.compiler.api.impl.symbols.BallerinaTypeReferenceTypeSymbol.signature(BallerinaTypeReferenceTypeSymbol.java:157)
	at org.ballerinalang.langserver.hover.HoverUtil.getVariableHoverMarkupContent(HoverUtil.java:422)
	at org.ballerinalang.langserver.hover.HoverUtil.getHoverForSymbol(HoverUtil.java:127)
	at org.ballerinalang.langserver.hover.HoverUtil.getHover(HoverUtil.java:103)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$hover$1(BallerinaTextDocumentService.java:170)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
</details>

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #34708

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typedescriptors/TypeNarrowedTypeDescriptorTest.java [hunk 1]
```diff
@@ -0,0 +1,82 @@
+/*
+ * Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (gimantha) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/typedescriptors/TypeNarrowedTypeDescriptorTest.java:2]:
```suggestion
 * Copyright (c) 2022, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/typedescriptors/type_narrrowed_type_desc_test.bal [hunk 2]
```diff
@@ -0,0 +1,30 @@
+// Copyright (c) 2021 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (gimantha) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/typedescriptors/type_narrrowed_type_desc_test.bal:1]:
```suggestion
// Copyright (c) 2022 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```

**Review by mohanvive — APPROVED** [review]
