### PR TITLE
Fix xml equals check in TypeChecker

### LINKED ISSUE #25709: java.lang.ClassCastException thrown during equality check for XML
**Description:**

When trying to check anydata type values(xml and a string) for equality check, the following error is thrown.

SEVERE {b7a.log.crash} - **org.ballerinalang.jvm.values.BmpStringValue cannot be cast to org.ballerinalang.jvm.values.XMLValue** 

The exception occurs when trying to convert xml to string.
This impacts the behavior of "test:assertEquals" when an xml and a string is compared.

Workaround:
Switch the sides of the expression. (xmlValue == xmlString) fails, but (xmlString == xmlValue) does not fail.

**Steps to reproduce:**

Include the following code block in main function.
```
    anydata xmlValue = xml `<book>The Lost World</book>` + xml `Hello, world!` + xml `<!--I am a comment-->` + xml `<?target data?>`;
    anydata xmlString = "<book>The Lost World</book>Hello, world!<!--I am a comment--><?target data?>";
    if(xmlValue == xmlString){
        //doNothing
    }
```

Stacktrace is as follows.

[2020-09-10 12:17:36,752] SEVERE {b7a.log.crash} - **org.ballerinalang.jvm.values.BmpStringValue cannot be cast to org.ballerinalang.jvm.values.XMLValue** 
java.lang.ClassCastException: org.ballerinalang.jvm.values.BmpStringValue cannot be cast to org.ballerinalang.jvm.values.XMLValue
	at org.ballerinalang.jvm.TypeChecker.isEqual(TypeChecker.java:2047)
	at org.ballerinalang.jvm.TypeChecker.isEqual(TypeChecker.java:374)
	at dilhashanazeer.assertions.0_1_0.main.main(main.bal:7)
	at dilhashanazeer.assertions.0_1_0.___init.$lambda$main$(assertions)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
	at java.lang.Thread.run(Thread.java:748)

**Affected Versions:**
slp-3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes #25709 

## Approach
Fix unchecked casting to `XmlValue`

## Samples
```ballerina 
anydata xmlValue = xml `<book>The Lost World</book>`;
anydata xmlString = "<book>The Lost World</book>";
if (xmlValue == xmlString) {
   io:println("xmlValue");
}
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java [hunk 1]
```diff
@@ -1110,4 +1110,12 @@ public void testEqualAndNotEqualNegativeCases() {
     public void testTableEquality() {
         BRunUtil.invoke(result, "testTableEquality");
     }
+
+    @Test
+    public void testXmlStringNegative() {
+        BValue[] returns = BRunUtil.invoke(result, "testXmlStringNegative");
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/EqualAndNotEqualOperationsTest.java:1116]: Can we move the assert into bal file it self.

**Review by warunalakshitha — APPROVED** [review]
