### PR TITLE
[Shell] Fix shell diagnostics not showing issue

### LINKED ISSUE #34562: Compiler not complaining about undefined vars after using auto import
Consider the following:
```
> bal shell
Welcome to Ballerina Shell REPL.
Type /exit to exit and /help to list available commands.

=$ foo                                                                                                                                                                                                             
| error: undefined symbol 'foo'
| 	foo
| 	^-^
| Compilation aborted due to errors.

=$ exit                                                                                                                                                                                                            
| error: undefined symbol 'exit'
| 	exit
| 	^--^
| Compilation aborted due to errors.

=$ io:println("Hello")                                                                                                                                                                                             
| Found following undefined module(s).
| io
| 
| Following undefined modules can be imported.
| 1. io
Do you want to import mentioned modules (yes/y) (no/n)? y
| 
| Adding import: import ballerina/io
| Import added: import ballerina/io

Hello

=$ exit                                                                                                                                                                                                           took 

=$ foo                                                                                                                                                                                                             

=$
```
After using the auto import feature, evaluating the undefined symbols `exit` and `foo` doesn't give any compile error.

### PR DESCRIPTION
**Pull request by DamithaSenevirathne**
Fixes #34562 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java [hunk 1]
```diff
@@ -148,8 +151,13 @@ public void run() {
...
             } finally {
                 end = Instant.now();
-                if (!isRequiredModules) {
-                    evaluator.diagnostics().forEach(this::outputDiagnostic);
+                if (!isMissingModule) {
+                    evaluator.diagnostics().forEach(this::outputDebugDiagnostic);
+                    outputDistinctErrorDiagnostics(evaluator.diagnostics());
+                } else {
+                    if (isContainsError) {
+                        terminal.error("\nCompilation aborted due to errors.");
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java:159]: Shouldn't we be printing the diagnostics in this case as well?

Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/BallerinaShell.java]: Updated in 4e40545aa33a23cffff5f809782bdf9266d51921

**Review by pubudu91 — APPROVED** [review]
