### PR TITLE
Add completion engine bug fixes

### LINKED ISSUE #29102: Revisit worker receive and worker send action completions
**Description:**
$subject needs to be done with the spec changes

### LINKED ISSUE #29395: public enum types are not listed in code suggestions in VSCode
**Description:**
In the `IO` module, we have public enum called [`FileWriteOption`](https://github.com/ballerina-platform/module-ballerina-io/blob/master/io-ballerina/options.bal#L21-L24). but in VScode, this type is not appeared as a suggestion, please check the screenshot attached below,

Screen Shot 2021-03-23 at 11 35 11 AM

### LINKED ISSUE #29599: Code completion template for annotations updates all fields with the same value
**Description:**
The code completion template for annotations updates all the fields with the same value. 

**Steps to reproduce:**
Typing the value for the `id` field updates the `name` and `address` fields also with the same value.
Screen Shot 2021-03-25 at 2 36 28 PM

**Affected Versions:**
SLA3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #29747: Rollback statement not suggested
**Description:**
rollback

**Steps to reproduce:**

```ballerina
public function main() {
    transaction {
        var res = getError();
        if(res is error) {
            rollba
        } else {
            checkpanic commit;
        }
    }
}

function getError() returns error? {
    return error("Custom error");
}
```

**Affected Versions:**
SL Alpha 4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #29799: Language Server throws error when goto definition invoked for bala sources
**Description:**
Screenshot 2021-04-02 at 15 05 24

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose
Fixes #29799
Fixes #29395 
Fixes #29747
Fixes #29102 
Fixes #29599 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/BlockNodeContextProvider.java [hunk 1]
```diff
@@ -196,6 +199,18 @@ private boolean withinLoopConstructs(T node) {
         return withinLoops;
     }
 
+    private boolean withinTransactionStatement(T node) {
+        Node evalNode = node;
+        boolean withinTransaction = false;
+
+        while (!withinTransaction && evalNode != null && evalNode.kind() != SyntaxKind.MODULE_PART) {
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/BlockNodeContextProvider.java:206]: Out of curiosity, can't we simplify this? Like removing the `MODULE_PART` check because the parent of a module part node is anyway `null`?

**Review by IMS94 — CHANGES_REQUESTED** [review]
Overall looks good. There's a check style failure due to an unused import. And I added a minor comment asking a question regarding simplifying a logic. 

Ready to be be merged once the checkstyle issue is fixed.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/BlockNodeContextProvider.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/BlockNodeContextProvider.java]: Fixed

**Review by IMS94 — APPROVED** [review]
LGTM! Including the annotation text tab index fix.

**Review by mohanvive — APPROVED** [review]

**Review by prabushi — APPROVED** [review]

**Review by dulajdilshan — APPROVED** [review]
