### PR TITLE
Remove printing DOT when testing single bal file

### LINKED ISSUE #29266: Avoid printing . for module name when testing single bal file
**Description:**
Avoid printing '.' for module name when running tests using single bal file

**Steps to reproduce:**

Run a single bal file with tests.

```
Compiling source
        testerina_test.bal

Running Tests

        .
I'm the before suite function!
I'm in test function 1!
I'm in test function 2!
I'm the after suite function!

                [pass] testFunction1
                [pass] testFunction2

                2 passing
                0 failing
                0 skipped
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Ibaqu**
## Purpose
Removes printing just `.` when testing single bal files

Output for single bal files now looks like this.

```
Compiling source
	main_test.bal

Running Tests

	main_test.bal

		[pass] test1
		[pass] test2
		[pass] test3

		3 passing
		0 failing
		0 skipped
```

Fixes #29266

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java [hunk 1]
```diff
@@ -199,6 +199,9 @@ public void execute(Project project) {
             if (isSingleTestExecution || isRerunTestExecution) {
                 suite.setTests(TesterinaUtils.getSingleExecutionTests(suite, singleExecTests));
             }
+            if (project.kind() == ProjectKind.SINGLE_FILE_PROJECT) {
```
Comment (Dilhasha) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java:202]:
```suggestion
            if (project.kind() == ProjectKind.SINGLE_FILE_PROJECT && project.sourceRoot() != null) {
```

Comment (Ibaqu) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java:202]: Ive tried this. However it still doesnt seem to stop the spotbugs from throwing warnings

**Review by Dilhasha — APPROVED** [review]
