### PR TITLE
[Semantic API] Add NoneType symbol

### LINKED ISSUE #30419: [Semantic API] `listenerTypes()` potentially adds `null` to the list
The `listenerTypes()` method in the service symbol will add `null` elements to the list if it encounters unexpected internal types. I think we may need to consider skipping such `null` elements.

### PR DESCRIPTION
**Pull request by DamithaSenevirathne**
## Purpose

Fixes #30419 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaNoneTypeSymbol.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+package io.ballerina.compiler.api.impl.symbols;
+
+import io.ballerina.compiler.api.ModuleID;
+import io.ballerina.compiler.api.symbols.NoneTypeSymbol;
+import io.ballerina.compiler.api.symbols.TypeDescKind;
+import org.wso2.ballerinalang.compiler.semantics.model.types.BNoType;
+import org.wso2.ballerinalang.compiler.util.CompilerContext;
+
+/**
+ * Represents the none type descriptor.
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaNoneTypeSymbol.java:27]: Not exactly accurate. This doesn't represent a type desc. This is actually for representing the absence of a type desc.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/NoneTypeSymbol.java [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.ballerina.compiler.api.symbols;
+
+/**
+ * Represents the none type descriptor.
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/NoneTypeSymbol.java:21]: Same comment as above.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaNoneTypeSymbol.java (hunk 1 above)
Comment (DamithaSenevirathne) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaNoneTypeSymbol.java]: Updated in 01e598a85a4cc5ae1d5e43d8096d643dd9032dfa

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/NoneTypeSymbol.java (hunk 2 above)
Comment (DamithaSenevirathne) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/NoneTypeSymbol.java]: Updated in 01e598a85a4cc5ae1d5e43d8096d643dd9032dfa

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaNoneTypeSymbol.java [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+ */
+public class BallerinaNoneTypeSymbol extends AbstractTypeSymbol implements NoneTypeSymbol {
+
+    public BallerinaNoneTypeSymbol(CompilerContext context, ModuleID moduleID, BNoType bNoType) {
+        super(context, TypeDescKind.NONE, bNoType);
+    }
+
+    @Override
+    public String signature() {
+        return null;
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaNoneTypeSymbol.java:37]: Shall we return an empty string instead of returning `null`?

Comment (DamithaSenevirathne) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaNoneTypeSymbol.java]: Updated in e44f7d5745e607bd8a098a5063f2fc39ad909daa

**Review by pubudu91 — APPROVED** [review]
