### PR TITLE
Fix incorrect behaviour of member access in xml with negative index

### LINKED ISSUE #35980: Incorrect behavior of member access on xml with key value < 0
**Description:**
$title. 
As per the spec when the evaluated value of the container expression is an `xml` and `and k is < 0, then the evaluation completes abruptly with a panic`
(i.e. key-expression is evaluated to get a value k)

But ATM, this result is an empty xml value.

**Steps to reproduce:**
```ballerina
function init() {
    xml v = xml `This is an xml`;
    io:println(v[-1].toBalString()); // prints xml``, but should panic
}
```

**Affected Versions:**
Ballerina 2201.0.2

### PR DESCRIPTION
**Pull request by SasinduDilshara**
Fixes #35980 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java [hunk 1]
```diff
@@ -141,6 +144,9 @@ public BXml descendants() {
     public XmlValue getItem(int index) {
         if (index == 0) {
```
Comment (ushirask) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java:145]: Shall we do the `index > 0` here similar to in `XmlItem` to keep the functions consistent?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java [hunk 2]
```diff
@@ -522,10 +522,12 @@ public Object copy(Map<Object, Object> refs) {
      */
     @Override
     public XmlValue getItem(int index) {
-        if (index != 0) {
+        if (index > 0) {
             return new XmlSequence();
+        } else if (index < 0) {
```
Comment (suleka96) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java:527]: Shall we put the error case as the first case to facilitated early fail.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal [hunk 3]
```diff
@@ -88,6 +88,83 @@ function testLengthOfXMLSequence() returns [int, int, int, int] {
     return [x1.length(), x2.length(), x2[2].length(), x3.length()];
 }
 
+const i = -1;
+
+function testInvalidXMLAccessWithNegativeIndex() returns error? {
```
Comment (suleka96) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal:93]: Shall we also add several  xm subtype as sequence tests. `eg: xml<xml:Comment>` and so on

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java (hunk 1 above)
Comment (KavinduZoysa) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java:145]: It will be more readable to arrange it like this,
```
if (index = 0) {
    return ...;
}
if (index > 0) {
    return ...;
}
throw Error...;
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java [hunk 4]
```diff
@@ -141,6 +144,9 @@ public BXml descendants() {
...
             return this;
+        } else if (index < 0) {
+            throw ErrorCreator.createError(BallerinaErrorReasons.XML_OPERATION_ERROR,
+                    StringUtils.fromString("xml index out of range: index " + index));
```
Comment (LakshanWeerasinghe) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java:149]: Move this error message to `MessageBundle.properties`.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal [hunk 5]
```diff
@@ -88,6 +88,83 @@ function testLengthOfXMLSequence() returns [int, int, int, int] {
...
+
+    xml x9 = xml `<names><name>Sherlock Holmes</name><name>Sherlock Holmes</name></names>`;
+    e = trap x9[1][-1];
+    check assertErrorMessage(e, "Index -1 out of bounds for length 0");
+    e = trap x9[1][a];
+    check assertErrorMessage(e, "Index -1 out of bounds for length 0");
+    e = trap x9[0][i];
+    check assertErrorMessage(e, "xml index out of range: index -1");
+}
+
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal:167]: Add few tests with indexes larger than the length and asserting empty xml

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java [hunk 6]
```diff
@@ -522,11 +524,13 @@ public Object copy(Map<Object, Object> refs) {
      */
     @Override
     public XmlValue getItem(int index) {
-        if (index != 0) {
+        if (index == 0) {
+            return this;
+        } else if (index > 0) {
```
Comment (sanjana) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java:529]: Can we get rid off the `else` here like this?
```suggestion
        } 
        
        if (index > 0) {
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java [hunk 7]
```diff
@@ -141,8 +146,11 @@ public BXml descendants() {
     public XmlValue getItem(int index) {
         if (index == 0) {
             return this;
+        } else if (index > 0) {
```
Comment (sanjana) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java:149]: Can get rid off the else.
```suggestion
        } 
        
        if (index > 0) {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal [hunk 8]
```diff
@@ -88,6 +88,362 @@ function testLengthOfXMLSequence() returns [int, int, int, int] {
...
+    assert((<error> e).message(), errorMessage3);
+    e = trap x14[a];
+    assertTrue(e is error);
+    assert((<error> e).message(), errorMessage3);
+    e = trap x14[i];
+    assertTrue(e is error);
+    assert((<error> e).message(), errorMessage3);
+
+    xml x15 = xml `<name>Sherlock Holmes</name><name>Sherlock Holmes</name>`;
+    e = trap x15[-1];
```
Comment (sanjana) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal:265]: Better add test cased for `-2`, `-3` as well.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java (hunk 6 above)
Comment (SasinduDilshara) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java:529]: I think it is better to use if and else if rather than using two ifs

Comment (SasinduDilshara) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java:529]: are you suggesting to remove `else if` and add `if`?.
I think using `if` and `else if` will be better rather than using to `if`s.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java (hunk 7 above)
Comment (SasinduDilshara) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java:146]: https://github.com/ballerina-platform/ballerina-lang/pull/40114/files#r1191913089

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal (hunk 8 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal:265]: the check is `<0`, because of that isn't it ok to add only one negative number.
wdyt?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java (hunk 6 above)
Comment (SasinduDilshara) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlItem.java]: updated. 5ff4ac52aa7ec017f6582c9daaf91208f3566c3c

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java (hunk 7 above)
Comment (SasinduDilshara) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/XmlNonElementItem.java]: Updated. 5ff4ac52aa7ec017f6582c9daaf91208f3566c3c

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal (hunk 3 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal:93]: Added

Comment (suleka96) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal:93]: You have added `xml:Comment` which is xml singelton type tests not `xml<xml:Comment>` which is xml  sub type sequence tests.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal [hunk 9]
```diff
@@ -88,6 +88,362 @@ function testLengthOfXMLSequence() returns [int, int, int, int] {
     return [x1.length(), x2.length(), x2[2].length(), x3.length()];
 }
 
+const i = -1;
+
+function testInvalidXMLAccessWithNegativeIndex() returns error? {
+    int a = -1;
```
Comment (suleka96) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal:94]: Can we add some xml sub type sequence tests as well. eg: `xml<xml:Comment>`

Comment (pcnfernando) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal:94]: I believe there is https://github.com/ballerina-platform/ballerina-lang/pull/40114/files/5ff4ac52aa7ec017f6582c9daaf91208f3566c3c#diff-d48872f73bc16a73f08f8f39ee2ac3554cfff305bb4fa861a222befe454e4147R209

**Comment by pcnfernando** [comment]
@suleka96 Merging due to code freeze. @SasinduDilshara  Please check up on https://github.com/ballerina-platform/ballerina-lang/pull/40114#discussion_r1197678589

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal (hunk 9 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-indexed-access.bal:94]: yes.
