### PR TITLE
Fix completion issues

### LINKED ISSUE #28665: Suggest only record types as the type of an included record parameter
**Description:**
The type reference in an included record parameter can only refer to a record type defined by a record typedesc. Can we suggest only record types after the `*` in a parameter?

**Steps to reproduce:**
```ballerina
function foo(*F<cursor>) {
    
}

type Foo record {|
    int id;
    string name;
|};
```

Currently doesn't seem to have any filtering.

included_record_param_1

**Affected Versions:**
slalpha2

### LINKED ISSUE #29070: Invalid context identified for suggestions
**Description:**
Consider the following source snippets

```
while true {
} <cursor>

foreach ... {
} <cursor>

do {
} <cursor>

lock {
} <cursor>

match ... {
} <cursor>
```

For all the cursor positions, the contexts are identified incorrectly, hence the `on fail ` clause is not suggested

**Affected Versions:**
sl-alpha2 at least

### PR DESCRIPTION
**Pull request by nadeeshaan**
1. Add a new common service snippet
2. Use the semantic API to capture the type of a field access expression

Fixes #29070 
Fixes #28665 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RightArrowActionNodeContext.java [hunk 1]
```diff
@@ -55,34 +50,14 @@ public RightArrowActionNodeContext(Class<T> attachmentPoint) {
...
-                return completionItems;
-        }
-
-        Optional<Symbol> filteredEntry = visibleSymbols.stream().filter(predicate).findAny();
-
-        if (filteredEntry.isEmpty()) {
-            return completionItems;
-        }
-        if (SymbolUtil.isClient(filteredEntry.get())) {
+        Optional<TypeSymbol> expressionType = context.currentSemanticModel().orElseThrow().type(node);
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/RightArrowActionNodeContext.java:53]: Instead of throwing, we can do `flatMap()` as below:
```suggestion
        Optional<TypeSymbol> expressionType = context.currentSemanticModel().flatMap(semanticModel -> semanticMode.type(node));
```
WDYT? IMO, this approach is much cleaner.

**Review by IMS94 — APPROVED** [review]
LGTM! Except for a minor suggestion.

**Review by rasika — APPROVED** [review]
