### PR TITLE
Remove restrictions of using `null`

### LINKED ISSUE #28342: Restriction of null to json type
In alpha1, this gets a compile-error:

```
int? x = null;
```

This is a correct program according to the spec, since the spec says:

> the use of null should be restricted to JSON-related contexts

Note this is **should**, and it does not say `json` type.

This is not a helpful restriction. For example, I wanted to copy and paste some data from a JSON file and use it as the initializer of a user-defined record type (to see whether my data-binding would work), but I couldn't because of this.

### PR DESCRIPTION
**Pull request by lasinicl**
Fixes #28342

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -225,17 +225,31 @@ public BType checkType(Location pos,
     }
 
     public boolean isJSONContext(BType type) {
-        if (type.tag == TypeTags.UNION) {
-            return ((BUnionType) type).getMemberTypes().stream().anyMatch(memType -> memType.tag == TypeTags.JSON);
+        switch (type.tag) {
+            case TypeTags.MAP:
+                return isJSONContext(((BMapType) type).constraint);
+            case TypeTags.ARRAY:
+                return isJSONContext(((BArrayType) type).eType);
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:232]: Shouldn't this only be applicable for `map<json>` and JSON arrays? For example, with this check, types such as `map<json|Foo>` (where `Foo` is an object) would also be considered as a JSON context right?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 2]
```diff
@@ -1449,7 +1449,7 @@ error.invalid.use.of.experimental.feature=\
   using experimental feature ''{0}''. use ''--experimental'' flag to enable the experimental features
 
 error.invalid.use.of.null.literal=\
-''null'' literal is only supported for ''json''
+''null'' literal is only allowed in a json-related context
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1452]: `json-related` -> `JSON-related`. The lower case is only used when referring to the `json` type.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:232]: I think we should clarify what JSON context means. I guess one could argue that even `map<json|Foo>` can be considered a JSON context since it still allows JSON, and similarly something like `map<int|Foo>`.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/nullable/NullableTypeTest.java [hunk 3]
```diff
@@ -78,6 +78,51 @@ public void testNilableTypeArrayIteration() {
         validateError(result, 0, "incompatible types: expected '(()|any)', found '(()|any)?'", 33, 19);
     }
 
+    @Test(description = "Test null with basic types")
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/nullable/NullableTypeTest.java:81]: Shall we do these assertions in b7a itself?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 1 above)
Comment (lasinicl) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:232]: Refer https://github.com/ballerina-platform/ballerina-lang/issues/28342#issuecomment-806403455 for clarification regarding the JSON-related context

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:232]: My concern is not cases where we add elements to maps such as `map<json|Foo>`. I think those count as JSON context. But the above makes the following case to be considered as a JSON context too right? 
```ballerina
map<json|Foo>? m = null;
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:232]: If we consider `map<json|Foo>` as a JSON context isn't this similar to the original example `int?`?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/nullable/NullableTypeTest.java [hunk 4]
```diff
@@ -78,6 +79,22 @@ public void testNilableTypeArrayIteration() {
         validateError(result, 0, "incompatible types: expected '(()|any)', found '(()|any)?'", 33, 19);
     }
 
+    @Test(dataProvider = "dataToTestNullInJSONRelatedContext", description = "Test null in JSON related context")
+    public void testNullInJSONRelatedContext(String functionName) {
+        BRunUtil.invoke(result, functionName);
+    }
+
+    @DataProvider
+    public Object[] dataToTestNullInJSONRelatedContext() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/nullable/NullableTypeTest.java:88]: We don't need to say "JSON context" anymore, right?

**Review by MaryamZi — COMMENTED** [review]
Shall we also update the PR title?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/nullable/NullableTypeTest.java (hunk 4 above)
Comment (lasinicl) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/nullable/NullableTypeTest.java:88]: Ah my bad! missed this. Will fix :)

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 1 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Ah now only I saw that @lasinicl has already raised this in the issue. So according to that, use of `null` anywhere is allowed by the compiler I guess? 🤔

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: ^ Ah nvm my bad, ignore the above. Really should start checking before commenting 😅

**Review by pubudu91 — APPROVED** [review]

**Review by MaryamZi — APPROVED** [review]
