### PR TITLE
Limit service functions from invoking outside self and having access modifiers

### LINKED ISSUE #17903: Bad, Sad error when invoking a service method via a service object
**Description:**
$title.

Happens for both normal methods and resources.

Works for service declarations (an attempt to invoke a resource function also gives an error).

**Steps to reproduce:**
```ballerina
import ballerina/io;

service s = service {
    resource function foo() {
        io:println("foo");
    }

    function bar() {
        io:println("bar");        
    }
};

public function main() {
    s.foo();
    s.bar();
}
```

ballerina-internal.log
```
[2019-08-17 11:04:33,471] ERROR {org.ballerinalang.tool.Main} - org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BObjectTypeSymbol 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.semantics.model.symbols.BTypeSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BObjectTypeSymbol
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkObjectFunctionInvocationExpr(TypeChecker.java:3050)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:1528)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:123)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:248)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:215)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1846)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:47)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2249)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2214)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:2210)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$42(SemanticAnalyzer.java:1375)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1375)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:56)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2249)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2214)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:2210)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:313)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:71)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2249)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2214)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2206)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$4(SemanticAnalyzer.java:232)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:232)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:160)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:211)
	at org.wso2.ballerinalang.compiler.CompilerDriver.typeCheck(CompilerDriver.java:313)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:270)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:262)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:127)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:175)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:180)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:93)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:101)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:51)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:298)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT - 15th August build

### PR DESCRIPTION
**Pull request by irshadnilam**
## Purpose
$title

Fixes #17903

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 1]
```diff
@@ -542,6 +542,12 @@ error.service.object.type.required=\
 error.service.invalid.object.type=\
   given type ''{0}'' does not match with service type interface
 
+error.service.function.invalid.modifier=\
+  function defined in services cannot have an explicit visibility qualifier
```
Comment (irshadnilam) [inline compiler/ballerina-lang/src/main/resources/compiler.properties]: Is this error message okay?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 2]
```diff
@@ -542,6 +542,12 @@ error.service.object.type.required=\
...
+
+error.service.function.invalid.invocation=\
+  service functions cannot be invoked outside service descriptor
```
Comment (irshadnilam) [inline compiler/ballerina-lang/src/main/resources/compiler.properties]: Is this error message okay?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -3059,6 +3059,10 @@ private BRecordType createErrorDetailRecordType(BLangInvocation iExpr, boolean r
     }
 
     private void checkObjectFunctionInvocationExpr(BLangInvocation iExpr, BObjectType objectType) {
+        if (Names.SERVICE.value.equals(objectType.tsymbol.name.value)) {
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Shall we check flag here.? instead of the name.

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 2 above)
Comment (rdhananjaya) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: How about "invalid service function invocation"?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 4]
```diff
@@ -554,9 +560,6 @@ error.remote.function.in.non.client.object=\
 error.resource.function.in.non.service.object=\
   a resource function allowed in services only
 
-error.resource.function.with.visibility.qualifier=\
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties]: We'll have to remove the DiagnosticCode and usage of the same for this error. 

https://github.com/ballerina-platform/ballerina-lang/blob/f8d7bc4b05a086b4ef01ca0988829624e37ce16b/compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java#L165

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 3 above)
Comment (irshadnilam) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: The `objectType` is of type built in service type and does not have any flags or tags.

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 1 above)
Comment (irshadnilam) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: Fixed.

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 2 above)
Comment (irshadnilam) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: Fixed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 3 above)
Comment (irshadnilam) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: `objectType` is of builtin type service, there is no flags/tags on it, but I have refactored to use the `getKind()` function instead of name.

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 4 above)
Comment (irshadnilam) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: Fixed.

**Comment by irshadnilam** [comment]
> This should be disallowed even for service declarations right?
> 
> The following does not fail atm.
> 
> ```ballerina
> import ballerina/lang.'object;
> 
> type Listener object {
>     *'object:Listener;
> 
>     public function __attach(service s, string? name = ()) returns error? {
>         
>     }
> 
>     public function __start() returns error? {
>         
>     }
> 
>     public function __gracefulStop() returns error? {
>         
>     }
> 
>     public function __immediateStop() returns error? {
>         
>     }
> 
>     public function __detach(service s) returns error? {
>         
>     }
> };
> 
> service def on new Listener() {
>     resource function tuv() {
>     }
> 
>     function xyz() {
>     }
> }
> 
> public function main() {
>     _ = def.xyz();   // does not fail
>     // _ = def.tuv(); // resource function can not be invoked with in a service
> }
> ```
> 
> The error when trying to invoke a resource method from outside the service is also a bit misleading, shall we check that also if time permits?

@MaryamZi This is working now, added the test cases as well.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 5]
```diff
@@ -1596,16 +1596,16 @@ private void validateRemoteFunctionAttachedToObject(BLangFunction funcNode, BObj
     }
 
     private void validateResourceFunctionAttachedToObject(BLangFunction funcNode, BObjectTypeSymbol objectSymbol) {
+        if (Symbols.isFlagOn(objectSymbol.flags, Flags.SERVICE)
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: This doesn't seem like the right place for this check, given that the name is `validateResourceFunctionAttachedToObject`.

Shall we move this to `validateFunctionsAttachedToObject` or introduce a new method `validateServiceMethodQualifiers` and call it there?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 6]
```diff
@@ -3059,6 +3059,12 @@ private BRecordType createErrorDetailRecordType(BLangInvocation iExpr, boolean r
     }
 
     private void checkObjectFunctionInvocationExpr(BLangInvocation iExpr, BObjectType objectType) {
+        if (objectType.getKind() == TypeKind.SERVICE &&
+                !(iExpr.expr.getKind() == NodeKind.SIMPLE_VARIABLE_REF &&
+                (Names.SELF.equals(((BLangSimpleVarRef) iExpr.expr).symbol.name)))) {
+            dlog.error(iExpr.pos, DiagnosticCode.SERVICE_FUNCTION_INVALID_INVOCATION);
+            return;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Do we have to return here? Can we integrate this with the object init check https://github.com/ballerina-platform/ballerina-lang/pull/18616/files#diff-1f0acc81bd72ee2f8368b0a25cd59e9cR3085

Comment (irshadnilam) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: As we discussed offline, this is not possible due to services using buit-in type. Created an issue to track this.
https://github.com/ballerina-platform/ballerina-lang/issues/18717
