### PR TITLE
Fix function mocking runtime warning

### LINKED ISSUE #27176: [Testerina] Function Mocking uses Illegal Reflective Access
**Description:**
The current implementation of Function mocking makes use of reflection to access some classes, which throws a Warning when Function mocking is used. 

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.ballerinalang.testerina.natives.mock.FunctionMock (file:/Users/mohamedaquibzulfikar/Desktop/TESTING_SLP6/ballerina-swan-lake-preview6-SNAPSHOT/distributions/ballerina-slp6/repo/balo/ballerina/test/0.0.0/platform/java11/testerina-core-2.0.0-Preview6-SNAPSHOT.jar) to field java.lang.ClassLoader.classes
WARNING: Please consider reporting this to the maintainers of org.ballerinalang.testerina.natives.mock.FunctionMock
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The reflection is used when accessing the class name for the Mock method. This implementation needs to be improved. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Ibaqu**
Fixes #27176

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/MockDesugar.java [hunk 1]
```diff
@@ -317,6 +318,23 @@ private BLangFunctionBody generateBody() {
                 generateFieldBasedAccess("functionToMockPackage"),
                 generateRHSExpr(functionToMockPackageVal));
 
+        BLangTestablePackage bLangTestablePackage = this.bLangPackage.getTestablePkg();
+        List<BLangCompilationUnit> compUnitList = bLangTestablePackage.getCompilationUnits();
+
+        String mockFunctionClassList = "";
```
Comment (Dilhasha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/MockDesugar.java:324]: What if we collect the class list to a List object instead of a string and construct the string before assigning it? WDYT?

Comment (Ibaqu) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/MockDesugar.java:324]: Yes. Initially, the idea I had was to include it in a list because it is a more straightforward and cleaner approach. 

However, I ran into problems creating the equivalent desugar code to include the various source files into the list. I also tried arrays but was running into compilation problems. 

This is why I resorted to passing a simple string and handling it at the `FunctionMock` class. Im looking into improving this.

Comment (Ibaqu) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/MockDesugar.java]: As discussed, I have passed an array instead of a string. This is cleaner than the previous approach

**Review by azinneera — APPROVED** [review]

**Review by Dilhasha — APPROVED** [review]
