### PR TITLE
Fix reading params incorrectly in attach-functions in BIR

### LINKED ISSUE #39900: [Bug]: BIR reads params incorrectly in attached functions
### Description

GraphQL module has defined `Interceptor` type as follows:
```ballerina
public type Interceptor readonly & distinct service object {
    isolated remote function execute(Context context, Field 'field) returns anydata|error;
};
```

In GraphQL service config, It accepts an array or single Interceptor:
```ballerina
public type GraphqlServiceConfig record {|
    readonly Interceptor|Interceptor[] interceptors = [];
|};
```
Consider the following GraphQL service:
```ballerina
import ballerina/graphql;
import ballerina/log;

readonly service class LogInterceptor {
    *graphql:Interceptor;

 isolated remote function execute(graphql:Context context, graphql:Field 'field)
    returns anydata|error {
        string fieldName = 'field.getName();
        log:printInfo(string `Field "${fieldName}" execution started!`);
        var data = context.resolve('field);
        log:printInfo(string `Field "${fieldName}" execution completed!`);
        return data;

    }
}

@graphql:ServiceConfig {
    interceptors: new LogInterceptor()
}
service /graphql on new graphql:Listener(9090) {
    isolated resource function get name() returns string {
        log:printInfo("Executing the field \"name\"");
        return "GraphQL Interceptors";
    }
}
```
When running the above service, it returns the following compilation error.
```shell
ERROR [main.bal:(14:5,36:6)] mismatched function signatures: expected 'public function execute(ballerina/graphql:1.7.0:Context , ballerina/graphql:1.7.0:Field ) returns (anydata|error)', found 'public function execute(ballerina/graphql:1.7.0:Context context, ballerina/graphql:1.7.0:Field field) returns (anydata|error)'
error: compilation contains errors
```
But there is no difference between these function signatures. 

### Steps to Reproduce

1. Clone this GraphQL branch https://github.com/DimuthuMadushan/module-ballerina-graphql/tree/interceptor and build using `./gradlew clean build -x test`
2. Use the intermediate pack generated at the `root/target` directory to run the above sample GraphQL service.

### Affected Version(s)

2201.4.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #39900

## TODO

- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/41105

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java [hunk 1]
```diff
@@ -614,13 +614,6 @@ private void setInvokableTypeSymbol(BInvokableType invokableType) {
         }
         BInvokableTypeSymbol tsymbol = (BInvokableTypeSymbol) invokableType.tsymbol;
         List<BVarSymbol> params = new ArrayList<>(invokableType.paramTypes.size());
-        for (BType paramType : invokableType.paramTypes) {
-            BVarSymbol varSymbol = new BVarSymbol(paramType.flags, Names.EMPTY, //TODO: should be written/read to BIR
-                                                  this.env.pkgSymbol.pkgID, paramType, null, symTable.builtinPos,
-                                                  COMPILED_SOURCE);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:620]: Did we verify all of the fields in the existing param symbols are the same? Package ID, origin, etc.? Shall we add a test also?

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_objects.bal [hunk 2]
```diff
@@ -466,6 +466,14 @@ function testSubTypingForDifferentOrgNameAndVersionWithAllPublicFields() {
...
 }
 
+readonly service class FooClass {
+    *foo2:FooObj;
+
+    isolated remote function execute(string aVar, int bVar) {
+
+    }
+}
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_objects.bal:476]: Please add negative tests too. For mismatched names for example.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java [hunk 3]
```diff
@@ -614,13 +614,6 @@ private void setInvokableTypeSymbol(BInvokableType invokableType) {
         }
         BInvokableTypeSymbol tsymbol = (BInvokableTypeSymbol) invokableType.tsymbol;
         List<BVarSymbol> params = new ArrayList<>(invokableType.paramTypes.size());
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:616]: No longer used?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectIncludeOverrideBalaTest.java [hunk 4]
```diff
@@ -74,6 +95,8 @@ public void testIsolationNegative() {
                 "a referenced type across modules cannot have non-public fields or methods", 42, 6);
         validateError(negativeRes, index++, "incompatible type reference 'foo:Employee5': " +
                 "a referenced type across modules cannot have non-public fields or methods", 48, 6);
+        validateError(negativeRes, index++, "mismatched function signatures: expected 'public function " +
+                "execute(string aVar, int bVar)', found 'public function execute(int aVar, int bVar)'", 58, 5);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectIncludeOverrideBalaTest.java:99]: This is different types, right? Isn't testing different names more relevant?

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectIncludeOverrideBalaTest.java:99]: Let's keep this also.

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_objects.bal [hunk 5]
```diff
@@ -466,6 +466,14 @@ function testSubTypingForDifferentOrgNameAndVersionWithAllPublicFields() {
     assertTrue((<any> ob3) is foo2:ObjectWithPublicFieldsAndMethods);
 }
 
+readonly service class FooClass {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_objects.bal:469]: Can we actually test something here? By creating a `FooClass` value and calling the method. May have to change service to client or have a normal method.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectIncludeOverrideBalaTest.java [hunk 6]
```diff
@@ -54,6 +63,18 @@ public void testObjectWithOverriddenFieldsAndMethods() {
...
+    @Test
+    public void testOverriddenFunctionInformation() {
+        BPackageSymbol fooPackage = (BPackageSymbol) packageSymbol.scope.lookup(new Name("foo")).symbol;
+        BSymbol fooObj = fooPackage.scope.lookup(new Name("FooObj")).symbol;
+        PackageID pkgID = fooObj.pkgID;
+        assertEquals(fooObj.kind, SymbolKind.TYPE_DEF);
+        assertEquals(fooObj.origin, SymbolOrigin.COMPILED_SOURCE);
+        assertEquals(pkgID.orgName.getValue(), "testorg");
+        assertEquals(pkgID.pkgName.getValue(), "foo");
+        assertEquals(pkgID.name.getValue(), "foo");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectIncludeOverrideBalaTest.java:75]: Need to actually look at parameter details?

**Comment by MaryamZi** [comment]
Please fix the build, seems to be checkstyle failures.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java [hunk 7]
```diff
@@ -546,6 +546,11 @@ public void testObjectReferingTypeFromBalaNegative() {
                 "no implementation found for the method 'toString' of class 'FrameImpl'", 53, 1);
     }
 
+    @Test(description = "Test invoking remote function in client object with inclusion")
+    public void testRemoteFunctionInvocationInClientObject() {
+        BRunUtil.invoke(result, "testRemoteFunctionReturnForObjectInclusion");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java:551]: I would use the same name.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java [hunk 8]
```diff
@@ -546,6 +546,11 @@ public void testObjectReferingTypeFromBalaNegative() {
                 "no implementation found for the method 'toString' of class 'FrameImpl'", 53, 1);
     }
 
+    @Test(description = "Test invoking remote function in client object with inclusion")
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java:549]: Although we are using the invocation to test, we are not testing the invocation? We are testing inclusion and param names. I would use a name/description that describes what we are actually testing.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectIncludeOverrideBalaTest.java [hunk 9]
```diff
@@ -32,11 +45,13 @@
 public class ObjectIncludeOverrideBalaTest {
 
     private CompileResult result;
+    private BPackageSymbol packageSymbol;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectIncludeOverrideBalaTest.java:48]: Only used in testOverriddenFunctionInformation? Make it a local variable.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java (hunk 8 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java:549]: Ah yeah, Thats correct. Will change

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java [hunk 10]
```diff
@@ -546,6 +546,11 @@ public void testObjectReferingTypeFromBalaNegative() {
                 "no implementation found for the method 'toString' of class 'FrameImpl'", 53, 1);
     }
 
+    @Test(description = "Test the result of the remote function in client object with inclusion")
+    public void testRemoteFunctionReturnForObjectInclusion() {
+        BRunUtil.invoke(result, "testRemoteFunctionReturnForObjectInclusion");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java:551]: IMO, still doesn't indicate what exactly we are trying to test? We are just trying to test an included method?

Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java:551]: Isn't this same as https://github.com/ballerina-platform/ballerina-lang/pull/40386/files#diff-971027c88ba42c746eff5667d7c9fe8d8f4b4acdd0b3c2da66b9fd12b78026a9R519-R521?

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/object/ObjectInBalaTest.java:551]: Aren't we trying to test that it's valid if parameter names are the same? While we need the returned value, we aren't really testing the value? If for some reason we are updating the tests some day, it would be better to indicate that the parameters are required for the test.

I would use something like `testObjectInclusionWithMethodWithParameters`.

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_objects.bal [hunk 11]
```diff
@@ -466,6 +466,20 @@ function testSubTypingForDifferentOrgNameAndVersionWithAllPublicFields() {
     assertTrue((<any> ob3) is foo2:ObjectWithPublicFieldsAndMethods);
 }
 
+readonly client class FooClass {
+    *foo2:FooObj;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_objects.bal:470]: Missed this earlier. But shall we add a test where the included object is an intersection with a class too?

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_objects.bal:470]: e.g., `x:T` where `T` is `readonly & Class`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java [hunk 12]
```diff
@@ -476,7 +476,10 @@ private void defineFunction(DataInputStream dataInStream) throws IOException {
                     }
 
                     resourceFunction.pathSegmentSymbols = pathSegmentSymbols;
-                    objectTypeSymbol.attachedFuncs.add(resourceFunction);
+
+                    if (!isImmutable(this.currentStructure.flags)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:480]: Do we know why we need to special case like this?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:480]: May be related to https://github.com/ballerina-platform/ballerina-lang/blob/v2201.7.0/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java#L1712

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:480]: Yeah, In here https://github.com/ballerina-platform/ballerina-lang/blob/v2201.7.0/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java#L1712, here we are adding immutable functions first and we don't need another round to add the functions again. That's why I ignore adding immutable functions again

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:480]: So can't we get rid of that instead?

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:480]: This seems like a known [issue (#30051)](https://github.com/ballerina-platform/ballerina-lang/issues/30051) that needs a proper workaround separately. I have added a TODO comment

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_objects.bal (hunk 11 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/object/test_objects.bal:470]: Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/40386/commits/28a13d2b701110fcf68600a89f504a54ea56f252

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java (hunk 12 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java:480]: But if the function is now available, maybe that was fixed somehow? Did you check if that is still needed?

**Review by MaryamZi — APPROVED** [review]
