### PR TITLE
Address review Suggestions

### LINKED ISSUE #39881: [Bug]: Compiler crashing when using specific fields with record literals as default parameter values
### Description

$title.
```ballerina
import ballerina/io;

public function main() {
    int a = 10;
    function (record {| int a;|} x = {a}) returns int y = value;
    io:println(y());
}

function value(record {| int a;|} x) returns int {
    return x.a;
}
```

Crash with
```
[2023-03-15 09:41:04,412] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:159)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:467)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$3(BIROptimizer.java:121)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:121)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:425)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:107)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:107)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:89)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:83)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:286)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:451)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:165)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:221)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
```

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fixes #39881

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java [hunk 1]
```diff
@@ -910,7 +914,10 @@ public void visit(BLangRecordLiteral recordLiteral) {
                                                                     (BLangRecordLiteral.BLangRecordKeyValueField) field;
                 keyValueField.key.expr = rewriteExpr(keyValueField.key.expr);
                 keyValueField.valueExpr = rewriteExpr(keyValueField.valueExpr);
-            } else if (field.getKind() != NodeKind.SIMPLE_VARIABLE_REF) {
+            } else if (field.getKind() == NodeKind.SIMPLE_VARIABLE_REF) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java:917]: Test for this?

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java:917]: A field can be a variable reference when the static type of the expression becomes a map. right? In this case, it is not possible to write a test related to the annotation. And also this reference is to a global variable, thus it cannot also become a closure variable. 
```
const int x = 10;

function value() {
    map<int> k = {x};
}
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java:917]: If we think we won't get here, why do we have this check.

What about

```ballerina
annotation record {| int max; |} constraints on field;

public function main() {
    int max = 1;

    record {|
        @constraints {
            max
        }
        string f;
    |} r;

    r = {f: ""};
}
```

Also this isn't just annotations, right?

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java:917]: In your example, we create a `BLangRecordLiteral.BLangStructLiteral` and define its fields using key-value pairs. 
I added this check because without restricting it here, it will go to the `variable ref` visitor and check whether it is a closure variable or not. (IMO based on the current implementation, the kind of field can only be a simplevarref in the above scenario, which cannot be a closure variable anyway)

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java:917]: Do we always get here after the constructs have been desugared? If so, yes, variable name fields will have been rewritten as key-value pairs, and as mentioned previously, we won't need this check.

We will need tests though, for this, spread fields, and computed keys, especially given that we may change where the closures are generated in the future.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java:917]: Any update on this?

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java]: Yes, from the annotation desugar phase, we desugar the annotation attachments.  For now, I have removed this check

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java]: Do we have tests with the different field kinds?

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java]: Different field kinds are spread field, key-value field, and var named field. right? We have tests for key-value fields but cannot add an annotation for a spread field.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java]: https://ballerina.io/spec/lang/master/#field

> We have tests for key-value fields but cannot add annotations for a spread field.

Why do we have the subsequent check `field.getKind() != NodeKind.SIMPLE_VARIABLE_REF` then? 

```ballerina
annotation annot on field;

record {| int b; int c; |} r = {b: 1, c: 2};

int a = 0;

record {| int a; int b; int c; |} x = {a, ...<record {| @annot int b; int c; |}> r};
```

When the visit gets called here, the field kind is variable-name field.

Doesn't this visit have to be called for annotation values, btw?

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureGenerator.java:918]: Added a test case for scenarios where a record literal is used as a default value

**Comment by MaryamZi** [comment]
@chiranSachintha there are test failures.

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal [hunk 2]
```diff
@@ -270,6 +270,29 @@ public function sleep(int millis) = @java:Method {
     'class: "org.ballerinalang.test.utils.interop.Utils"
 } external;
 
+function testFuncWithComputedNameFieldInRecordLiteralForDefaultValue() {
+    int a = 10;
+    function (record {| int a;|} x = {a}) returns int y = value1;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal:275]: This is not a computed field?

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal:275]: Please keep this (with the correct name) and add a separate test for variable name fields.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TypedescValueImpl.java [hunk 3]
```diff
@@ -92,10 +92,6 @@ public Object instantiate(Strand s) {
         return instantiate(s, new BInitialValueEntry[0]);
     }
 
-    public MapValue getAnnotations() {
-        return annotations;
-    }
-
```
Comment (dulajdilshan) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TypedescValueImpl.java:98]: This is okay since there are no usages we exposed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java [hunk 4]
```diff
@@ -2229,21 +2213,19 @@ public void visit(BLangSimpleVarRef.BLangTypeLoad typeLoad) {
...
     private void visitTypedesc(Location pos, BType type, List<BIROperand> varDcls) {
-        visitTypedesc(pos, type, varDcls, null);
-    }
-
-    private void visitTypedesc(Location pos, BType type, List<BIROperand> varDcls, BIROperand annotations) {
         BIRVariableDcl tempVarDcl = new BIRVariableDcl(symTable.typeDesc, this.env.nextLocalVarId(names),
                                                        VarScope.FUNCTION, VarKind.TEMP);
-        this.env.enclFunc.localVars.add(tempVarDcl);
+        BIRGenEnv env = this.env;
+        env.enclFunc.localVars.add(tempVarDcl);
```
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java:2219]: Here, are we assuming that `encFunc` is not getting `null`?

**Review by dulajdilshan — DISMISSED** [review]
LGTM

File: tests/jballerina-unit-test/src/test/resources/test-src/annotations/anonymous_tuple_annotation_test.bal [hunk 5]
```diff
@@ -116,6 +116,16 @@ function testTupleMemberAnnotations2() returns [@annotOne {value: gVar1} @annotT
     return [1];
 }
 
+function testTupleMemberAnnotations() {
+    map<any> m1 = getAnonymousTupleAnnotations(typeof testTupleMemberAnnotations1(), "$field$.0");
+    map<any> m2 = getAnonymousTupleAnnotations(typeof testTupleMemberAnnotations1(), "$field$.1");
+    map<any> m3 = getAnonymousTupleAnnotations(typeof testTupleMemberAnnotations2(), "$field$.0");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/annotations/anonymous_tuple_annotation_test.bal:122]: Move closer to assertion.

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal [hunk 6]
```diff
@@ -270,6 +270,36 @@ public function sleep(int millis) = @java:Method {
     'class: "org.ballerinalang.test.utils.interop.Utils"
 } external;
 
+function testFuncWithSpecificFieldInRecordLiteralForDefaultValue() {
+    int a = 10;
+    function (record {| int a;|} x = {a}) returns int y = value1;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal:275]:
```suggestion
    function (record {| int a; |} x = {a}) returns int y = value1;
```

or

```suggestion
    function (record {|int a;|} x = {a}) returns int y = value1;
```

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal [hunk 7]
```diff
@@ -270,6 +270,36 @@ public function sleep(int millis) = @java:Method {
     'class: "org.ballerinalang.test.utils.interop.Utils"
 } external;
 
+function testFuncWithSpecificFieldInRecordLiteralForDefaultValue() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal:273]: Specific field is both key-value pair and variable name field. I would use VariableNameField instead.

https://ballerina.io/spec/lang/master/#specific-field

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal (hunk 6 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal:275]: Fix in other functions and tests too.

File: tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal (hunk 7 above)
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/functions/functions_with_default_parameters.bal:273]: Also RecordLiteral -> MappingConstructor.

**Review by MaryamZi — APPROVED** [review]

**Review by dulajdilshan — APPROVED** [review]
LGTM
