### PR TITLE
Fix several issues with mapping and list constructor expression type checking

### LINKED ISSUE #20773: Issue in inferred type for list constructor with any, anydata, etc.
**Description:**
The "List constructor" section of the spec says 

"(1) If there is a contextually expected type, then the inherent type of the newly created list is derived from the applicable contextually expected type.

(2) If there is no contextually expected type, then the inherent type will be T[], where T is the union of the broad types of the expressions in expr-list."

The spec also says regarding contextually expected type, "Note the language provides a way to say that the type of a variable is to be inferred from the static type of the expression used to initialize the variable. In this case, there is no contextually expected type for the evaluation of the expression. **Not having a contextually expected type is different from having a contextually expected type that allows all values.**"

However, in the current implementation, the type set in `any`, `anydata` scenarios is (2) even though it has to be (1).

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    any a = [1, 2]; // CET - `any`, ACET - `any[]`
    typedesc<any> t1 = typeof a; // `any[]`
    io:println(t1); // currently `int[]`, but should be an `any[]`
}
```

**Affected Versions:**
1.1.0

### LINKED ISSUE #21222: Fix inferred type for mapping and list constructors when there is no contextually expected type
**Description:**
$title. 

See https://github.com/ballerina-platform/ballerina-spec/issues/401#issuecomment-590184065.

Currently infers maps and arrays, should infer records and tuples instead.

**Affected Versions:**
1.2.0-SNAPSHOT

### LINKED ISSUE #21247: Array length validation does not happen for union expected types
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type NoFillerObject object {
    public function __init(any arg) {
        
    }
};

public function main() {
    NoFillerObject[2] x = [];   // size mismatch in sealed array. expected '2', but found '0'

    int|NoFillerObject[2] y = [];   // no compilation error!
}
```

**Affected Versions:**
1.1.3

### LINKED ISSUE #21281: Issue with tuples with union-typed tuple rest descriptors
**Description:**
$title. Panics at runtime.

**Steps to reproduce:**
```ballerina
public function main() {
    [int, string|boolean...] x = [1, "hi", true];
}
```

```cmd
$ ballerina run test.bal 
Compiling source
        test.bal
Running executables

error: {ballerina/lang.array}InherentTypeViolation message=incompatible types: expected 'boolean', found 'string'
        at test:main(test.bal:3)
```

**Affected Versions:**
```cmd
$ ballerina -v
jBallerina 1.1.3
Language specification 2019R3
Ballerina tool 0.8.0
```

### LINKED ISSUE #21282: Ambiguous type error when using a mapping constructor expression with a union of maps expected type
**Description:**
$title, even when it is not ambiguous.

**Steps to reproduce:**
```ballerina
public function main() {
    map<string>|map<int> m = {a: 1}; // ambiguous type '(map<string>|map<int>)'
}
```

**Affected Versions:**
1.1.3

### LINKED ISSUE #21338: Creating a tuple by specifying less members than the expected type is not allowed even when FillMember is applicable
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    [string, int, float] t = ["Hello", 34]; // error: tuple and expression size does not match
}
```

**Affected Versions:**
1.2.0-SNAPSHOT with #20749

### LINKED ISSUE #21345: Issues in type-checking for mapping and list constructors
**Description:**
Creating an issue to track the following issues related to $title.

- [ ] Issue in inferred type for list constructor with any, anydata, etc. #20773
- [ ] Issue with tuples with union-typed tuple rest descriptors #21281
- [ ] Array length validation does not happen for union expected types #21247
- [ ] Creating a tuple by specifying less members than the expected type is not allowed even when FillMember is applicable #21338

- [ ] Ambiguous type error when using a mapping constructor expression with a union of maps expected type #21282 

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/21222

### LINKED ISSUE #21413: Runtime fill member check does not consider closed array types with element types that have a filler value as fillable
**Description:**
$title - see https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TypeChecker.java#L1759

**Steps to reproduce:**
Results in the following causing a bad, sad error at runtime.

```ballerina
import ballerina/io;

public function main() {
    int[2][3] x = [];
    io:println(x[0].length());
}
```

```cmd
[2020-03-02 21:37:39,921] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinalang.langlib.array.Length.length(Length.java:42)
	at ballerina.lang_array.array.length(array.bal:40)
	at abc.main(abc.bal:5)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:745)
 
[2020-03-02 21:37:39,927] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinalang.langlib.array.Length.length(Length.java:42)
	at ballerina.lang_array.array.length(array.bal:40)
	at abc.main(abc.bal:5)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

**Affected Versions:**
Current master - probably 1.2.0-m2

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$title.

**Compile Time**
- Fixes #21222 - Fix inferred type for mapping and list constructors when there is no contextually expected type
- Fixes #21338 - Creating a tuple by specifying less members than the expected type is not allowed even when FillMember is applicable
- Fixes #21345 - Issues in type-checking for mapping and list constructors
- Fixes #20773 - Issue in inferred type for list constructor with any, anydata, etc.
- Fixes  #21282 - Ambiguous type error when using a mapping constructor expression with a union of maps expected type
- Fixes #21281 Issue with tuples with union-typed tuple rest descriptors
- Fixes #21247 Array length validation does not happen for union expected types

**Runtime**
- Fixes #21413 - Runtime fill member check does not consider closed array types with element types that have a filler value as fillable

## Approach
Compile time type checking for list and mapping constructor expressions, where the contextually expected type (CET) is a union, has been updated in a way that type checking against the different candidate types happens in the same path as when a single type is the CET.

This is done by switching the diagnostic log to one that does not log to the console, when type checking is done for a union, just to check compatibility.  

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java [hunk 1]
```diff
@@ -238,7 +238,7 @@ public void testCodeActionWithQuickFixes(String config, String source)
         log.info("Test textDocument/codeAction QuickFixes");
         return new Object[][]{
                 {"fixReturnType1.json", "fixReturnType.bal"},
-                {"fixReturnType2.json", "fixReturnType.bal"},
+//                {"fixReturnType2.json", "fixReturnType.bal"},
```
Comment (hasithaa) [inline language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java]: Please create an issue for this and assign @nadeeshaan

Comment (MaryamZi) [reply language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CodeActionTest.java]: Yeah, I've created https://github.com/ballerina-platform/ballerina-lang/issues/21509.
