### PR TITLE
Fix intermittent WebSocketMetricsTestCase failure

### LINKED ISSUE #20595: Intermittent Failure WebSocketMetricsTestCase.testMetrics()
**Description:**
Test testMetrics() fails intermittently on WebSocketMetricsTestCase

### PR DESCRIPTION
**Pull request by kaneeldias**
## Purpose
Issue was the test client attempting to connect to the WebSocket server before it was started.

Fixes #20595

## Approach
Added a timeout to wait up to 10 seconds to connect to the WebSocket server

## Remarks
PR to 1.1.x - #20645

### CODE REVIEW

File: tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/WebSocketMetricsTestCase.java [hunk 1]
```diff
@@ -171,4 +179,4 @@ private String generateNewKey(String metric, String[] tags) {
         key = key + "}";
         return key;
     }
-}
+}
```
Comment (kalaiyarasiganeshalingam) [inline tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/WebSocketMetricsTestCase.java]: Missing new line

File: tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/WebSocketMetricsTestCase.java [hunk 2]
```diff
@@ -82,24 +84,30 @@ private void setup() throws Exception {
...
-        client.sendText(MESSAGE);
-        client.sendText(MESSAGE);
-        client.sendText(MESSAGE);
-        client.sendPing(SENDING_BYTE_BUFFER);
-        client.sendPong(SENDING_BYTE_BUFFER);
-        client.sendBinary(SENDING_BYTE_BUFFER);
-        client.sendText(CLOSE_MESSAGE);
+        // Test Service
+        final WebSocketTestClient[] client = new WebSocketTestClient[1];
+        await().atMost(20, TimeUnit.SECONDS)
```
Comment (kalaiyarasiganeshalingam) [inline tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/WebSocketMetricsTestCase.java]: Why we can't use setCountDownLatch()[https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/util/websocket/client/WebSocketTestClient.java#L101]  instead of this?

File: tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/WebSocketMetricsTestCase.java [hunk 3]
```diff
@@ -82,7 +86,9 @@ private void setup() throws Exception {
      */
     @Test
     public void testMetrics() throws Exception {
-        WebSocketTestClient client = new WebSocketTestClient("ws://localhost:9090/basic/ws");
+        WebSocketTestClient client = new WebSocketTestClient(SERVER_URL);
+        CountDownLatch countDownLatch = new CountDownLatch(1);
+        countDownLatch.await(10, TimeUnit.SECONDS);
```
Comment (kalaiyarasiganeshalingam) [inline tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/observability/metrics/WebSocketMetricsTestCase.java]: No need to create the countDownLatch to handshake because we already set it in the implementation. Please refer the [test](https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/SimpleProxyTestCommons.java#L65).
