### PR TITLE
Fix Testerina module init for sourceless module tests

### LINKED ISSUE #29898: [Testerina] Test Suite initialization for modules fails when there are more than one non default modules with only test sources
**Description:**
$subject

Fails at the test initialization phase. This can affect the default module as well since having a singular test folder without any source files causes the issue
**Steps to reproduce:**
Create modules with only test folders and test files and execute the test command

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Ibaqu**
## Purpose
Remove all instances of the project jar files in the path

Fixes #29898

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java [hunk 1]
```diff
@@ -522,18 +520,19 @@ private String getClassPath(JBallerinaBackend jBallerinaBackend, Package current
...
         for (ModuleId moduleId : currentPackage.moduleIds()) {
             Module module = currentPackage.module(moduleId);
-
-            // Skip adding the path if the module doesnt contain a generated module jar
-            if (!module.documentIds().isEmpty()) {
+            try {
                 PlatformLibrary generatedJarLibrary = jBallerinaBackend.codeGeneratedLibrary(
                         currentPackage.packageId(), module.moduleName());
                 exclusionPathList.add(generatedJarLibrary.path());
+            } catch (IllegalStateException e) {
```
Comment (azinneera) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java:527]: Why do we have to catch the `IllegalStateException` here?

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java [hunk 2]
```diff
@@ -522,18 +520,19 @@ private String getClassPath(JBallerinaBackend jBallerinaBackend, Package current
...
+                continue;
             }
-            // Skip adding the path if the module doesnt contain a generated testable jar
-            if (!module.testDocumentIds().isEmpty()) {
```
Comment (azinneera) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java:533]: I think we can have this check as is it because a testable jar will be created only if there are test documents.

File: tests/testerina-integration-test/src/test/resources/project-based-tests/sourceless-test-execution-tests/Ballerina.toml [hunk 3]
```diff
@@ -0,0 +1,7 @@
+[package]
+org = "wso2"
+name = "sourcelessTest"
+version = "0.0.0"
+
+[build-options]
+observabilityIncluded = true
```
Comment (azinneera) [inline tests/testerina-integration-test/src/test/resources/project-based-tests/sourceless-test-execution-tests/Ballerina.toml:7]: Missing new line. Please correct other places as well.

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java (hunk 1 above)
Comment (Ibaqu) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java]: In retrospect, since the source jar is created regardless of whether there is a source file or not, I suppose the exception will not be thrown and can be safely added to the list

Comment (Ibaqu) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java]: I have removed the try/catch block

File: tests/testerina-integration-test/src/test/resources/project-based-tests/sourceless-test-execution-tests/Ballerina.toml (hunk 3 above)
Comment (Ibaqu) [reply tests/testerina-integration-test/src/test/resources/project-based-tests/sourceless-test-execution-tests/Ballerina.toml]: Removed new lines

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java (hunk 2 above)
Comment (Ibaqu) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java:533]: This check wasnt working when dealing with multiple modules. I removed it and used the try/catch since it would handle the exception if the jar file didnt exist.

Comment (Dilhasha) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java:533]: Shall we check why the testable jar was generated even when there were are no test files found rather than catching the exception and continuing?

File: tests/testerina-integration-test/src/test/resources/testng.xml [hunk 4]
```diff
@@ -46,6 +46,7 @@ under the License.
             <class name="org.ballerinalang.testerina.test.ImportTest" />
             <class name="org.ballerinalang.testerina.test.ModuleExecutionTest" />
             <class name="org.ballerinalang.testerina.test.CodeCoverageReportTest" />
+            <class name="org.ballerinalang.testerina.test.SourcelessTestExecutionTests"/>
```
Comment (Dilhasha) [inline tests/testerina-integration-test/src/test/resources/testng.xml:49]: I think the 'SourcelessTestExecutionTests' file isn't committed.

**Comment by Dilhasha** [comment]
Shall we also add test cases for the following scenarios with this effort?

1. Two non-default modules with only test sources and default module has source file, without any tests. (I think this is the initial issue faced by user)

image

2. Two non-default modules with one module having source file and the default module doesn't have sources. All modules have tests.

image

File: tests/testerina-integration-test/src/test/resources/testng.xml (hunk 4 above)
Comment (Ibaqu) [reply tests/testerina-integration-test/src/test/resources/testng.xml:49]: Added SourcelessTestExecutionTests

**Comment by Ibaqu** [comment]
> Shall we also add test cases for the following scenarios with this effort?
> 
> 1. Two non-default modules with only test sources and default module has source file, without any tests. (I think this is the initial issue faced by user)
> 2. Two non-default modules with one module having source file and the default module doesn't have sources. All modules have tests.

Added test cases for these

File: tests/testerina-integration-test/src/test/resources/project-based-tests/sourceless-test-execution-tests/sourceless-project-test/tests/main_test.bal [hunk 5]
```diff
@@ -0,0 +1,6 @@
+import ballerina/test;
+
+@test:Config { }
+public function test7() {
+    test:assertTrue(true);
+}
```
Comment (Dilhasha) [inline tests/testerina-integration-test/src/test/resources/project-based-tests/sourceless-test-execution-tests/sourceless-project-test/tests/main_test.bal:6]: Missing new line

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java (hunk 2 above)
Comment (Ibaqu) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java:533]: Changed the implementation back to checking the testDocuementIds instead of catching the exception.

File: tests/testerina-integration-test/src/test/resources/project-based-tests/sourceless-test-execution-tests/sourceless-project-test/tests/main_test.bal (hunk 5 above)
Comment (Ibaqu) [reply tests/testerina-integration-test/src/test/resources/project-based-tests/sourceless-test-execution-tests/sourceless-project-test/tests/main_test.bal]: Added new line

**Review by Dilhasha — DISMISSED** [review]

**Review by Dilhasha — APPROVED** [review]
