### PR TITLE
Fix and enable tests - take I

### LINKED ISSUE #30037: Enable test failing due to changes to supported types of main function
**Description:**
The test MappingConstructorExprTest.testSpreadOpFieldTaintAnalysisNegative is disabled in the master because of the recent compilation checks added to the master to limit the supported types of the main parameters.

**Describe your task(s)**
Fix or replace the test https://github.com/ballerina-platform/ballerina-lang/blob/3f186a7d32e828ee2d27c2d771c4b3ee4ef18f54/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java#L218
**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/29829

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
Initial changes to address #28770 - Check and enable disabled tests.

This PR removes some obsolete tests that were disabled.

Also fixes #30037 - Enable test failing due to changes to supported types of main function

## Remarks
Issues identified:
- CCE with nested error binding pattern in destructuring assignment statement #30275
- Can't use an error binding pattern in a mapping binding pattern with a destructuring assignment #30276
- Error with map<value:Cloneable> created for the rest binding pattern of an error detail #30277
- No errors logged when an error binding pattern attempts to assign to final variables via detail named arg patterns #30278
- Runtime future type's string representation does not contain the type parameter #30279
- `io.ballerina.runtime.internal.types.BFutureType#equals` is incorrect #30280

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java [hunk 1]
```diff
@@ -174,17 +174,19 @@ public void testObjectLevelXML() {
...
         BValue[] returns = BRunUtil.invoke(compileResult, "testFieldBasedAccess");
         Assert.assertEquals(returns[0].stringValue(),
                 "<fname><foo>1</foo><bar>2</bar></fname><lname1><foo>3</foo><bar>4</bar></lname1><fname><foo>5</foo>" +
                         "<bar>6</bar></fname><lname2><foo>7</foo><bar>8</bar></lname2>apple");
         Assert.assertEquals(returns[1].stringValue(), "<fname><foo>1</foo><bar>2</bar></fname>");
-        Assert.assertEquals(returns[2].stringValue(), "<foo>5</foo>");
-        Assert.assertEquals(returns[3].stringValue(), "<foo>5</foo>");
-        Assert.assertEquals(returns[4].stringValue(), "<bar>4</bar>");
-        Assert.assertEquals(returns[5].stringValue(),
+        Assert.assertEquals(returns[2].stringValue(), "<foo>1</foo><foo>5</foo>");
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java:184]: @rdhananjaya, can you please verify the fixes for this XML test?

Comment (rdhananjaya) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java:184]: changes and the results looks good, shall we also change the function name.

**Review by hasithaa — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java (hunk 1 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/XMLTest.java:184]: Thanks, fixed in af0de38.
