### PR TITLE
Encode function parameter identifiers at runtime

### LINKED ISSUE #39770: [Bug]: HTTP Path parameters are not unescaped from the parser level
### Description

```
import ballerina/http;

type Account record {
    string id;
    string name;
    string email;
    string phone;
};

service /account2\-id on new http:Listener(9090) {

    resource function get account/[string account\-id]() returns Account {
        return {
            id: account\-id,
            name: "John Doe",
            email: "john.doe@email.com",
            phone: "1234567890"
        };
    }
}
```

I have a code like the above which is using the HTTP standard library. When reading path param variables at the HTTP level, `account\-id` has to be read as `account-id`. But currently, it is coming as  `account\-id`.

### Steps to Reproduce

Run the above code in the Ballerina version 2201.4.0 which will give the error `error: service registration failed: Invalid character: '\' in expression`. 

### Affected Version(s)

2201.4.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject

Fixes #39770

## Approach
This happens because the parameter symbol names are not encoded at the JvmDesugar phase. But they are used to create runtime `Parameter` objects.

## Samples
```ballerina
import ballerina/http;

type Account record {
    string id;
    string name;
    string email;
    string phone;
};

service /account2\-id on new http:Listener(9090) {

    resource function get account/[string account\-id]() returns Account {
        return {
            id: account\-id,
            name: "John Doe",
            email: "john.doe@email.com",
            phone: "1234567890"
        };
    }
}
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java [hunk 1]
```diff
@@ -237,6 +238,15 @@ private static void encodeFunctionIdentifiers(List<BIRFunction> functions,
                 parameter.name = Names.fromString(encodeNonFunctionIdentifier(parameter.name.value,
                                                                               encodedVsInitialIds));
             }
+            if (function.type.tsymbol != null) {
+                for (BVarSymbol parameter : ((BInvokableTypeSymbol) function.type.tsymbol).params) {
+                    if (parameter.name == null) {
+                        continue;
+                    }
```
Comment (Nadeeshan96) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmDesugarPhase.java:245]: Can `parameter.name` be `null`? If it can't be shall we remove this in both the places?

File: tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/identifier_utils/main.bal [hunk 2]
```diff
@@ -21,6 +21,11 @@ public function main() {
     testIdentifierDecoding();
     testEscapeSpecialCharacters();
     testUnescapeSpecialCharacters();
+    testFunctionParameters();
+}
+
+function testFunctionParameters() {
+    test:assertEquals(getParameterName(function (string account\-id){}), "account-id");
```
Comment (Nadeeshan96) [inline tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/identifier_utils/main.bal:28]: Shall we also add a test having path parameters with such identifiers?

File: tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/identifier_utils/main.bal [hunk 3]
```diff
@@ -17,10 +17,35 @@
...
 public function main() {
     testIdentifierDecoding();
     testEscapeSpecialCharacters();
     testUnescapeSpecialCharacters();
+    testFunctionParameters();
+}
+
+function testFunctionParameters() {
+    test:assertEquals(getParameterName(function(string account\-id) {
+    }), "account-id");
```
Comment (Nadeeshan96) [inline tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/identifier_utils/main.bal:47]:
```suggestion
    test:assertEquals(getParameterName(function(string account\-id) {}), "account-id");
```

File: tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/identifier_utils/main.bal [hunk 4]
```diff
@@ -17,10 +17,35 @@
...
+
+service class AccountService {
+    resource function get account/[string account\-id]() returns Account {
+        return {
+            id: account\-id,
+            name: "John Doe",
+            email: "john.doe@email.com",
+            phone: "1234567890"
+        };
+    }
```
Comment (Nadeeshan96) [inline tests/jballerina-unit-test/src/test/resources/test-src/runtime/api/identifier_utils/main.bal:35]: Shall we use the expression-oriented style here with `=>`?

**Review by Nadeeshan96 — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM
