### PR TITLE
Fix RunExecutable task to reflect actual status of program execution

### LINKED ISSUE #26084: Ballerina program panics with exit code 0
**Description:**
When a Ballerina program panics, the exit code returns `0`. This should be `1` since the program did not exit normally. 

This is a serious issue since we use ballerina (1.2.8) for the standard library release pipeline processes, where the release is failed in the middle, the ballerina program panics, but the pipeline is marked as passed.

**Steps to reproduce:**
Try the following code:

```ballerina
public function main() {
    error err = error("Sample", message = "Sample Error");
    panic err;
}
```

```shell
$ ballerina run sample.bal
$ echo $?
```
This prints `0`.

**Affected Versions:**

jBallerina: 1.2.8
Ballerina Tool: 0.8.8

** Related Issues:**
#20967, #21624

### PR DESCRIPTION
**Pull request by Dilhasha**
## Purpose
Fix exit code to reflect actual status of task

Fixes #26084 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java [hunk 1]
```diff
@@ -130,6 +130,10 @@ private void runGeneratedExecutable(BLangPackage executableModule, BuildContext
             ProcessBuilder pb = new ProcessBuilder(commands).inheritIO();
             Process process = pb.start();
             process.waitFor();
+            int exitValue = process.exitValue();
+            if (exitValue != 0) {
+                Runtime.getRuntime().exit(exitValue);
+            }
         } catch (IOException | InterruptedException e) {
```
Comment (warunalakshitha) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java:137]: Don't we need to exit if get exception while running the command?

Comment (Dilhasha) [reply cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java:137]: The thrown exceptions are handled and exits are covered at the main class at https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/cli/ballerina-tool/src/main/java/org/ballerinalang/tool/Main.java

But when there is no exception thrown as in the case when the ballerina program panics with an error, the exit code does not reflect the actual status. That's why I am suggesting this fix.

Comment (Dilhasha) [reply cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java:137]: I realised, we can throw an exception when exit code is not zero and let the main class handle it to keep it consistent. I'll fix it.

File: cli/ballerina-tool/src/main/java/org/ballerinalang/tool/Main.java [hunk 2]
```diff
@@ -68,6 +68,9 @@ public static void main(String... args) {
         } catch (BLauncherException e) {
             LauncherUtils.printLauncherException(e, errStream);
             Runtime.getRuntime().exit(1);
+        } catch (BLangPanicException e) {
+            errStream.println(e.getMessage());
```
Comment (warunalakshitha) [inline cli/ballerina-tool/src/main/java/org/ballerinalang/tool/Main.java:72]: I think the e.getMessage will not have any useful info as always print "Execution exited with the exit code <some non 0 value>". Runtime already print the actual cause when panic. Therefore we do not need to print the error.  Also this will miss the exit code when we print the echo $? which will be always 1. So we can save the exitValue in PanicException and set in here without printing any thing.

catch (BLangPanicException e) {
Runtime.getRuntime().exit(((BlangPanicException).getExitValue())
}

File: cli/ballerina-tool/src/main/java/org/ballerinalang/tool/BLangPanicException.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+ *   under the License.
+ */
+package org.ballerinalang.tool;
+
+/**
+ * Thrown to indicate a non zero exit code from Ballerina executable.
+ *
+ * @since 1.2.10
+ */
+public class BLangPanicException extends RuntimeException {
```
Comment (warunalakshitha) [inline cli/ballerina-tool/src/main/java/org/ballerinalang/tool/BLangPanicException.java:25]: Since actuall runtime gets panic shall we rename RuntimePanicException

**Comment by warunalakshitha** [comment]
Also send a PR to master as well.

**Review by warunalakshitha — APPROVED** [review]

**Review by hevayo — APPROVED** [review]
