### PR TITLE
[Master] Improve error message to convey proper meaning when the typedesc argument cannot be inferred for a dependently-typed function

### LINKED ISSUE #37864: [Bug]:  Diagnostics are not meaningful
### Description

Consider the attached screen capture where the shown diagnostic contains `returnType` variable name which is not available in the code. Also the shown diagnostic is not meaningful

Screenshot 2022-09-22 at 9 57 51 PM

### Steps to Reproduce

_No response_

### Affected Version(s)

```
Ballerina 2201.2.0 (Swan Lake Update 2)
Language specification 2022R3
Update Tool 1.3.10
```

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by prakanth97**
## Purpose

Fixes #37864

## Approach
Updated the error messages to convey proper meaning.

## Remarks
#36347

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/InferredDependentlyTypeFunctionTest.java [hunk 1]
```diff
@@ -158,9 +166,12 @@ public void testDependentlyTypedFunctionWithInferredTypedescValueNegative() {
...
                 "(readonly|stream<int>|handle)'", 146, 34);
-        validateError(negativeResult, index++, "cannot infer type for parameter 'td'", 147, 25);
-        validateError(negativeResult, index++, "cannot infer type for parameter 'td'", 151, 13);
-        validateError(negativeResult, index++, "cannot infer type for parameter 'td'", 152, 13);
+        validateError(negativeResult, index++, "cannot infer the 'typedesc' argument for parameter 'td': " +
+                "expected a contextually-expected type or an argument for the parameter", 147, 25);
+        validateError(negativeResult, index++, "cannot infer the 'typedesc' argument for parameter 'td': " +
+                "expected a contextually-expected type or an argument for the parameter", 151, 13);
+        validateError(negativeResult, index++, "cannot infer the 'typedesc' argument for parameter 'td': " +
+                "expected a contextually-expected type or an argument for the parameter", 152, 13);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/InferredDependentlyTypeFunctionTest.java:174]: There are tests with var, but there don't seem to be tests for non-var scenarios when there is no contextually-expected type? Like in the original issue?

```ballerina
fn();
```

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 2]
```diff
@@ -1601,7 +1601,7 @@ error.invalid.dependently.typed.return.type.with.inferred.typedesc.param=\
   disjoint basic types
 
 error.cannot.infer.type.for.param=\
-  cannot infer type for parameter ''{0}''
+  cannot infer the ''{0}'' argument for parameter ''{1}'': expected a contextually-expected type or an argument for the parameter
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1604]: This new error should be only for when there is no argument AND no contextually-expected type (CET).

With the changes in this PR, we log the new error for something like

```ballerina
function fn(typedesc td = <>) returns td[] = external;

public function main() {
    map<int> _ = fn();
}
```

The new error is not correct here, because there is a CET.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1604]: While we are at it, we can improve the error for this scenario (there is a CET, but the argument cannot be inferred) too.

E.g.,
> cannot infer the ''typedesc'' argument for parameter ''{0}'' with ''{1}'' as the contextually-expected type
mapping to return type ''{2}''

> cannot infer the 'typedesc' argument for parameter 'td' with 'map\<int\>' as the contextually-expected type
mapping to return type 'td[]'

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java [hunk 3]
```diff
@@ -549,7 +550,8 @@ public BType visit(BParameterizedType originalType, BType expType) {
                     if (!paramValueTypes.containsKey(paramVarName)) {
                         // Log an error only if the user has not explicitly passed an argument. If the passed
                         // argument is invalid, the type checker will log the error.
-                        dlog.error(invocation.pos, DiagnosticErrorCode.CANNOT_INFER_TYPE_FOR_PARAM, paramVarName);
+                        dlog.error(invocation.pos,
+                                DiagnosticErrorCode.CANNOT_INFER_TYPE_FOR_PARAM, paramType, paramVarName);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java:554]: Let's change the diagnostic code also.

E.g.,
```
CANNOT_INFER_TYPEDESC_ARGUMENT
```

**Review by MaryamZi — CHANGES_REQUESTED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature_negative.bal [hunk 4]
```diff
@@ -185,3 +185,9 @@ function testInvalidUsageWithCasts() {
     var a = <function (function, boolean)> getFunctionWithAnyFunctionParamType(function (function x, int y) { });
     BooleanStream|handle b = <BooleanStream> check funcReturningUnionWithBuiltInRefType(());
 }
+
+function fooFn(typedesc td = <>) returns td[] = external;
+
+function testWithoutContextuallyExpType() {
+    fooFn();
```
[the remark this answers is not in the document]
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature_negative.bal]: Updated ae0fc43f75748cba2123e6c258861a8953017581

**Review by KavinduZoysa — DISMISSED** [review]

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 5]
```diff
@@ -625,7 +625,7 @@ public enum DiagnosticErrorCode implements DiagnosticCode {
     MULTIPLE_INFER_TYPEDESC_PARAMS("BCE3932", "multiple.infer.typedesc.params"),
     INVALID_DEPENDENTLY_TYPED_RETURN_TYPE_WITH_INFERRED_TYPEDESC_PARAM(
             "BCE3933", "invalid.dependently.typed.return.type.with.inferred.typedesc.param"),
-    CANNOT_INFER_TYPE_FOR_PARAM("BCE3934", "cannot.infer.type.for.param"),
+    CANNOT_INFER_TYPEDESC_ARGUMENT("BCE3934", "cannot.infer.typedesc.argument"),
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:628]: Shall we use `CANNOT_INFER_TYPEDESC_ARGUMENT_FROM_CET`?

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 6]
```diff
@@ -796,7 +796,9 @@ public enum DiagnosticErrorCode implements DiagnosticCode {
     MODULE_GENERATED_FOR_CLIENT_DECL_CANNOT_HAVE_MUTABLE_STATE(
             "BCE4044", "module.generated.for.client.decl.cannot.have.mutable.state"),
     CANNOT_IMPORT_MODULE_GENERATED_FOR_CLIENT_DECL(
-            "BCE4045", "cannot.import.module.generated.for.a.client.decl")
+            "BCE4045", "cannot.import.module.generated.for.a.client.decl"),
+    CANNOT_INFER_TYPEDESC_ARGUMENT_OR_EXPECTED_CONTEXTUALLY_EXPECTED_TYPE("BCE4046",
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:800]: How is OR correct here? Shall we say `CANNOT_INFER_TYPEDESC_ARGUMENT_WITHOUT_CET`?

**Review by MaryamZi — COMMENTED** [review]
Shall we change the title to say "Improve error message to convey proper meaning" instead of "Correct"?

Let's also include more details. E.g., mention that this is for when the typedesc argument cannot be inferred for a dependently-typed function.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java (hunk 5 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java]: Updated add0886cbda0a9bdb4d6e1c43292943d414352f4

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java (hunk 6 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java]: Updated add0886cbda0a9bdb4d6e1c43292943d414352f4

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java [hunk 7]
```diff
@@ -606,6 +606,18 @@ public BType visit(BParameterizedType originalType, BType expType) {
         return type;
     }
 
+    private void logErrorForCannotInferTypedescArgument(String paramVarName) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java:609]:
```suggestion
    private void logCannotInferTypedescArgumentError(String paramName) {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature_negative.bal [hunk 8]
```diff
@@ -185,3 +185,15 @@ function testInvalidUsageWithCasts() {
...
+function fooFn1(typedesc td = <>) returns td[] = external;
+
+function fooFn2(typedesc<int|string> td1, typedesc td2 = <>) returns [td1, td2] = external;
+
+function fooFn3(typedesc t, typedesc<boolean> td = <>) returns int|t|td = external;
+
+function testInvalidUsageWithoutContextuallyExpectedTypeAndArgument() {
+    fooFn1();
+    fooFn2(int);
+    fooFn3(float);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature_negative.bal:198]: I know we already have tests, but for completeness shall we add a test with var also here?

Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/javainterop/inferred_dependently_typed_func_signature_negative.bal:198]: Added tests 905aecbe4006052e3602df03d55026660556f8b6

**Review by MaryamZi — APPROVED** [review]
