### PR TITLE
Fix erroneous readonly assignability

### LINKED ISSUE #35847: Erroneous readonly assignability
**Description:**
```ballerina
    readonly readonlyVal = 1;
    error? errOrNil = readonlyVal; //should be a compile time assignability error
    io:println(errOrNil);//prints 1 atm
```

**Steps to reproduce:**

**Affected Versions:**
2202.0.2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by ushirask**
Fixes #35847

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -3689,7 +3689,7 @@ private boolean isAssignableToUnionType(BType source, BType target, Set<TypePair
                     }
                 }
                 // readonly can match to a union similar to any|error
-                if (sMember.tag == TypeTags.READONLY) {
+                if (sMember.tag == TypeTags.READONLY && isAssignable(symTable.anyOrErrorType, targetUnion)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: While this will work, I'm not sure if this is the best fix. The original issue is because true is returned incorrectly because there is an entry in unresolvedTypes, right? May be related to https://github.com/ballerina-platform/ballerina-lang/issues/36069 in a way too.

@KRVPerera, thoughts please? Since you're familiar with the union type checking logic also.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: Also, `any|error` isn't what is equivalent to `readonly`. It is `(any & readonly)|error`. Any specific reason to check with `symTable.anyOrErrorType`?

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: Assigning to `(any & readonly)|error` is checked prior to this, this code snippet is only used for assigning `readonly` to `any|error` unions right?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: I don't think this check is correct. If `any|error` is a subtype of `targetUnion`, any type is a subtype of `targetUnion`. But, since the value space represented by `readonly` is a proper subset of that of `any|error`, just because `symTable.anyOrErrorType` is not a subtype of `targetUnion`, doesn't mean `readonly` isn't a subtype of `targetUnion`.

Why do we need this block anyway? What was the reason to check specifically with `symTable.anyOrErrorType`?

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: Would it make sense to directly return `true` here if the `targetUnion` is `(any|error)` (regardless of the source type) ?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: That's a check we do in `isAssignable` anyway. I would have thought the check we need to do here is if `sMember.tag == TypeTags.READONLY` check if `(any & readonly)|error` is assignable to `targetUnion`.

@KRVPerera, would you happen to recall what we were trying to address here?

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: We only check in `isAssignable` if `sourceType` doesn't contain an error type right? Without this check 
```
readonly x = 2;
any|error y = x;
```
will fail.

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: Since readonly is also a complex union it may not match individual members of the target union but may be assignable to the whole target union as a whole. This is similar to the previous lines checking JSON.

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: Didn't we discuss to use `(any & readonly)|error` instead of using `readonly` in that case? The newly added check wouldn't completely fix the original issue, right? Since we'll only be allowing `readonly` with target unions that are `any|error`?

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: Yes, Ushira said the original problem is that code is adding readonly, target union pair. Yes, I remember but I think we had a discussion not for this code but for some change after this may be runtime. Need to fix the logic too.

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: Yes looks like I have added it in runtime type checker. @ushirask Check runtime type checker too. There is `ANY_AND_READONLY_OR_ERROR_TYPE`

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: I think chiran has adde `anyAndReadonlyOrError` to typeChecker too

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 2]
```diff
@@ -3689,7 +3689,7 @@ private boolean isAssignableToUnionType(BType source, BType target, Set<TypePair
                     }
                 }
                 // readonly can match to a union similar to any|error
-                if (sMember.tag == TypeTags.READONLY) {
+                if (sMember.tag == TypeTags.READONLY && isAssignable(symTable.anyAndReadonlyOrError, targetUnion)) {
                     unresolvedTypes.add(new TypePair(sMember, targetUnion));
                     if (isAssignable(sMember, targetUnion, unresolvedTypes)) {
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3694]: We can remove this second `isAssignable ` check if condition. Keep the logic inside the if block.

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Fixed.

**Review by KRVPerera — COMMENTED** [review]
LGTM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 3]
```diff
@@ -3689,12 +3689,10 @@ private boolean isAssignableToUnionType(BType source, BType target, Set<TypePair
                     }
                 }
                 // readonly can match to a union similar to any|error
-                if (sMember.tag == TypeTags.READONLY) {
+                if (sMember.tag == TypeTags.READONLY && isAssignable(symTable.anyAndReadonlyOrError, targetUnion)) {
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: The following program should be a compile-time error. right?
```
public function main() {
    readonly readonlyVal = 1;
    error? errOrNil = <readonly>readonlyVal; 
}

```

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: I believe so. It's currently giving a runtime error, I'll check.

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: In a case like
```
readonly x = 2;
int? y = <readonly>x;
```
```
incompatible types: 'readonly' cannot be cast to '(int? & readonly)'
```
, the error is in casting and not assignment, since the casting target type is changed to `int? & readonly`
In the `error` case this cast is currently considered castable, therefore since the type is taken as `error? & readonly`, the assignment is also passing. Should this be a cast error or a assignment error in compiler-time?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: This seems to be a bug. Shall we create a separate issue? The assignment is what should result in an error.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 4]
```diff
@@ -3689,12 +3689,10 @@ private boolean isAssignableToUnionType(BType source, BType target, Set<TypePair
...
                     unresolvedTypes.add(new TypePair(sMember, targetUnion));
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3693]: Do we still need to add this to unresolvedTypes?

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3693]: @KRVPerera mentioned that if we just remove that line, it may cause problems with cyclic types. I'm not sure if that's still the case, I'll check.

**Review by MaryamZi — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 3 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: Please mention the issue here.

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3692]: Created in #36580
