### PR TITLE
Split testerina BasicCasesTest

### LINKED ISSUE #25438: testAllExceptAssertTrue testcase is passed even some ballerina tests are actually failed
**Description:**
testAllExceptAssertTrue in BasicCasesTest in testerina integrations tests is having some intermittent failures.
This might be happen due to having same log leecher text. We might need to separate out each module test.

### PR DESCRIPTION
**Pull request by Ibaqu**
## Purpose
Split the one test case into multiple test cases to prevent console logging errors.

Fixes #25438

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java [hunk 1]
```diff
@@ -55,31 +55,68 @@ public void testJavaInterops() throws BallerinaTestException {
...
+    public void testAssertions() throws BallerinaTestException {
+        String msg = "87 passing";
+        LogLeecher clientLeecher = new LogLeecher(msg);
+        balClient.runMain("test", new String[]{"--disable-groups", "p1", "assertions", "--user.name=waruna"}, null,
+                new String[]{}, new LogLeecher[]{clientLeecher}, projectPath);
+        clientLeecher.waitForText(40000);
+    }
+
+    @Test()
+    public void testBeforeAfter() throws BallerinaTestException {
```
Comment (azinneera) [inline tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java:86]: Assertions are used in all tests. So the order of test execution should be as follows:
1. testAssertTrue
2. testAssertions (the assertions other than assertTrue)
3. rest of the tests 

Therefore, this and the rest of the tests should depend on `testAssertions`

Comment (Dilhasha) [reply tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java:86]: +1

Comment (Ibaqu) [reply tests/testerina-integration-test/src/test/java/org/ballerinalang/testerina/test/BasicCasesTest.java:77]: Addressed requested changes.

**Review by Dilhasha — APPROVED** [review]

**Review by azinneera — APPROVED** [review]
