### PR TITLE
Make `strings` field of `RawTemplate` a readonly field

### LINKED ISSUE #24140: Make the strings field of RawTemplate readonly
PR #23705 introduced raw templates. Need to $subject to align with the spec.

### LINKED ISSUE #24268: Raw templates not working with unions
Consider the following example:
```ballerina
    import ballerina/lang.'object as ob;

    public function main() {
        any|error ae = `INSERT INTO Details VALUES (${"Foo"}, ${20})`;
    }
```
The following compile error is given for the above:
```
error: .::test2.bal:5:24: invalid literal for type '(any|error)': raw templates can only be assigned to abstract subtypes of 'ballerina/lang.object:1.0.0:RawTemplate'
```

### PR DESCRIPTION
**Pull request by pubudu91**
Fixes #24140
Fixes #24268

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -3827,6 +3829,22 @@ private boolean evaluateRawTemplateExprs(List<? extends BLangExpression> exprs,
...
+    private BType getResolvedIntersectionType(BType type) {
+        return type.tag != TypeTags.INTERSECTION ? type : ((BIntersectionType) type).effectiveType;
+    }
+
+    private boolean containsAnyType(BType type) {
+        if (type == symTable.anyType) {
+            return true;
+        }
+
+        if (type.tag == TypeTags.UNION) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3841]: What if the union has `any` and one or more compatible object types? In that case it should be an ambiguous type error right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -3750,7 +3751,7 @@ public void visit(BLangRawTemplateLiteral rawTemplateLiteral) {
     private BType determineRawTemplateLiteralType(BLangRawTemplateLiteral rawTemplateLiteral, BType expType) {
         // Contextually expected type is NoType when `var` is used.
         // Therefore consider the literal as of type RawTemplate
-        if (expType == symTable.noType || expType == symTable.anyType) {
+        if (expType == symTable.noType || containsAnyType(expType)) {
             return symTable.rawTemplateType;
         }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3757]: Btw, the following union as the CET should also work right?

```ballerina
type Foo abstract object {
    public string[] strings;
    public any[] insertions;
};

public function main() {
    string x = "World";
    Foo|int f = `"Hello ${x}`;
}
```

Currently (slp1) fails

```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
error: .::qwe.bal:8:17: invalid literal for type '(Foo|int)': raw templates can only be assigned to abstract subtypes of 'ballerina/lang.object:1.0.0:RawTemplate'
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3757]: And the following union, where only one is compatible.

```ballerina
type Foo abstract object {
    public string[] strings;
    public int[] insertions;
};

type Bar abstract object {
    public string[] strings;
    public string[] insertions;
};

public function main() {
    string x = "World";
    Foo|Bar f = `"Hello ${x}`;
}
```

Fails with
```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
error: .::qwe.bal:13:17: invalid raw template assignment: '(Foo|Bar)' should be an abstract object
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/rawtemplate/RawTemplateLiteralTest.java [hunk 3]
```diff
@@ -118,6 +122,13 @@ public void testIndirectAssignmentToConcreteType() {
         BRunUtil.invoke(result, "testIndirectAssignmentToConcreteType");
     }
 
+    @Test(expectedExceptions = BLangRuntimeException.class,
+          expectedExceptionsMessageRegExp =
+                  ".*InvalidUpdate message=modification not allowed on readonly value.*")
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/rawtemplate/RawTemplateLiteralTest.java:127]: Shall we test this also in Ballerina itself?

For example, https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview1/tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal#L149.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangAnonymousModelHelper.java [hunk 4]
```diff
@@ -106,6 +110,12 @@ public String getNextDistinctErrorId(PackageID packageID) {
         return ANON_TYPE_ID + String.valueOf(nextValue);
     }
 
+    public String getNextRawTemplateTypeKey(PackageID packageID, Name rawTemplateTypeName) {
+        Integer nextValue = Optional.ofNullable(rawTemplateTypeCount.get(packageID)).orElse(0);
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangAnonymousModelHelper.java:114]: Wonder why doesn't anyone use `getOrDefault` method here.
```Java
Integer nextValue = rawTemplateTypeCount.getOrDefault(packageID, 0);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3757]: Fixed the first case with ce3ad42. The second case is a bit tricky. Looks like the whole type checking logic for raw templates will have to be refactored to support it. I think for now better to defer this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3842]: Shouldn't a union of `any` and any other type (except error) simplify to just `any` (currently it doesn't it seems)? In which case it should just be considered a `RawTemplate`

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3842]: Shouldn't we handle this scenario for the time-being though?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3757]: Shall we create an issue for this then? And should we consider giving a different error for now, something along the lines of "not yet supported" maybe?

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3757]: Even to give an error like that, I think we'll have to separately identify that particular case, which is the issue with the way currently it's type checked.

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3757]: Created #24766 to track this

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3842]: This behaviour is correct for the scenario right? Considering that `any|Foo|Bar` (where `Foo` and `Bar` are raw template types) is the same as `any`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 5]
```diff
@@ -585,14 +585,15 @@ private BType setLiteralValueAndGetType(BLangLiteral literalExpr, BType expType)
                 types.isCharLiteralValue((String) literalValue)) {
             return symTable.charStringType;
         } else {
-            if (this.expType.tag == TypeTags.FINITE) {
-                boolean foundMember = types.isAssignableToFiniteType(this.expType, literalExpr);
+            BType expected = getResolvedIntersectionType(this.expType);
```
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:588]: Shall we create an issue for this? You can assign it to me. :smile:

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/rawtemplate/raw_template_literal_test.bal [hunk 6]
```diff
@@ -203,19 +203,20 @@ function testUseWithVar() {
     var rt = `Hello ${name}!`;
     typedesc<any> td = typeof rt;
 
-    assert("typedesc $anonType$21 {\n\tstrings : string[],\n\tinsertions : (any|error)[]\n}", td.toString());
+    assert("typedesc $rawTemplate$RawTemplate$12",
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/rawtemplate/raw_template_literal_test.bal:206]: Do we have tests that assert the strings and insertions? Asserting the typedesc doesn't quite validate behaviour IMO.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 7]
```diff
@@ -3827,6 +3830,48 @@ private boolean evaluateRawTemplateExprs(List<? extends BLangExpression> exprs,
...
+
+    private BType getCompatibleRawTemplateType(BType expType, DiagnosticPos pos) {
+        if (expType.tag != TypeTags.UNION) {
+            return expType;
+        }
+
+        BUnionType unionType = (BUnionType) expType;
+        List<BType> compatibleTypes = new ArrayList<>();
+
+        for (BType type : unionType.getMemberTypes()) {
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3857]: Should we call `getEffectiveMemberTypes` here instead of `getMemberTypes` ?
https://github.com/ballerina-platform/ballerina-lang/blob/1cbfd04db73a9f36a46bdb47e8298bc5c4f39374/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L2336

This is currently used in 
https://github.com/ballerina-platform/ballerina-lang/blob/1cbfd04db73a9f36a46bdb47e8298bc5c4f39374/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L2297

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3857]: I guess the `isAssignable` check will handle this for us.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java [hunk 8]
```diff
@@ -553,6 +553,7 @@
     INVALID_TYPEDESC_PARAM("invalid.typedesc.param"),
 
     INVALID_RAW_TEMPLATE_TYPE("invalid.raw.template.type"),
+    MULTIPLE_COMPATIBLE_RAW_TEMPLATE_TYPES("multiple.compatiple.raw.template.types"),
```
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java:556]:
```suggestion
    MULTIPLE_COMPATIBLE_RAW_TEMPLATE_TYPES("multiple.compatible.raw.template.types"),
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:588]: Ah sure.. will do

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 7 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3857]: This is just to iterate through the union members to see if there are compatible raw template types. No need to call `getEffectiveMemberTypes()` for that right?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/rawtemplate/raw_template_literal_test.bal (hunk 6 above)
Comment (pubudu91) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/rawtemplate/raw_template_literal_test.bal:206]: Yeah, those are the normal tests. This one is just to test if a type was desugared for this properly.

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 9]
```diff
@@ -1395,6 +1395,9 @@ error.invalid.typedesc.param=\
 error.invalid.raw.template.type=\
   invalid literal for type ''{1}'': raw templates can only be assigned to abstract subtypes of ''{0}''
 
+error.multiple.compatiple.raw.template.types=\
```
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1398]:
```suggestion
error.multiple.compatible.raw.template.types=\
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 7 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3857]: 👍
