### PR TITLE
Log enhancement and fix intermittent test failures

### LINKED ISSUE #14794: Ballerina testStreamingStatePersistence testcase fails intermittently
**Description:**
```bash
[ERROR] testStreamingStatePersistence(org.ballerinalang.stdlib.streams.BallerinaStreamsV2StatePersistenceTest)  Time elapsed: 12.032 s  <<< FAILURE!
java.lang.AssertionError: expected [60] but found [30]
	at org.ballerinalang.stdlib.streams.BallerinaStreamsV2StatePersistenceTest.testStreamingStatePersistence(BallerinaStreamsV2StatePersistenceTest.java:89)

[ERROR] testTimeLengthQuery2(org.ballerinalang.stdlib.streams.BallerinaStreamsV2TimeLengthWindowTest)  Time elapsed: 0.028 s  <<< FAILURE!
org.ballerinalang.util.exceptions.BLangRuntimeException: 
error: {ballerina/task}TaskError {message:"Cannot initialize the Task Listener/Scheduler."}
	at ballerina/task:init(<native>)
	   ballerina/task:__init(listener.bal:30)
	   ballerina/task:__init(scheduler.bal:22)
	   ballerina/streams:__init(scheduler.bal:35)
	   ballerina/streams:__init(windows.bal:1448)
	   ballerina/streams:timeLength(windows.bal:1613)
	   testTimeLengthwindow(streamingv2-time-length-window-test2.bal:78)
	   startTimeLengthwindowTest2(streamingv2-time-length-window-test2.bal:55)
	at org.ballerinalang.stdlib.streams.BallerinaStreamsV2TimeLengthWindowTest.testTimeLengthQuery2(BallerinaStreamsV2TimeLengthWindowTest.java:66)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BallerinaStreamsV2StatePersistenceTest.testStreamingStatePersistence:89 expected [60] but found [30]
[ERROR]   BallerinaStreamsV2TimeLengthWindowTest.testTimeLengthQuery2:66 Â» BLangRuntime ...
[INFO] 

```

### PR DESCRIPTION
**Pull request by ThisaruGuruge**
Fixes #14794

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by riyafa** [comment]
@pubudu91 at the present stdlib is not a module. It is only a directory

File: stdlib/test-common/src/test/java/org/ballerinalang/stdlib/common/TestLogHandler.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+import java.util.logging.ConsoleHandler;
+
+/**
+ * A Console Log Handler to log developer level logs during unit tests.
+ *
+ * @since 0.94.1
+ */
+public class TestLogHandler extends ConsoleHandler {
+}
```
Comment (riyafa) [inline stdlib/test-common/src/test/java/org/ballerinalang/stdlib/common/TestLogHandler.java]: Can we also mention why we are creating a class with an empty body?

**Comment by ThisaruGuruge** [comment]
@pubudu91 Yes, stdlib-test-common is a common module. Let's change this that way then.

File: stdlib/test-common/src/test/java/org/ballerinalang/stdlib/common/TestLogHandler.java (hunk 1 above)
Comment (pubudu91) [reply stdlib/test-common/src/test/java/org/ballerinalang/stdlib/common/TestLogHandler.java]: This is so that we can set different log levels to console logging based on the source.

Comment (ThisaruGuruge) [reply stdlib/test-common/src/test/java/org/ballerinalang/stdlib/common/TestLogHandler.java]: Done

File: stdlib/task/src/main/java/org/ballerinalang/stdlib/task/utils/Utils.java [hunk 2]
```diff
@@ -69,11 +68,9 @@ public static void setError(Context context, String message) {
         context.setReturnValues(createError(context, message));
     }
 
-    public static String getCronExpressionFromAppointmentRecord(BValue record)
-            throws SchedulingException {
-
+    public static String getCronExpressionFromAppointmentRecord(BValue record) throws SchedulingException {
         String cronExpression;
-        if (record instanceof BMap && RECORD_APPOINTMENT_DATA.equals(record.getType().getName())) {
+        if (record instanceof BMap) {
```
Comment (pubudu91) [inline stdlib/task/src/main/java/org/ballerinalang/stdlib/task/utils/Utils.java]: What you need to check here is whether this is a record right? Ideally you should be getting the type of `record` and checking its type tag to see if it's a record. BMap is used for JSON and objects as well.

Comment (ThisaruGuruge) [reply stdlib/task/src/main/java/org/ballerinalang/stdlib/task/utils/Utils.java]: Done.
