### PR TITLE
[L1] Type Checking Improvements

### LINKED ISSUE #16458: Type params not working properly when invoked as a normal function
Consider the following program:
```ballerina
import ballerina/lang.array as arrs;

function test() returns int {
    int[] arr = [10, 20, 30, 40];
    return arrs:reduce(arr, function (int acc, int val) returns int { return acc + val; }, 0);
}
```
The above fails with the following compile error.
`incompatible types: expected 'int', found '(any|error)'`

### LINKED ISSUE #18152: Review Experimental features and restrict their usage

### LINKED ISSUE #18344: Fix version for langLib

### PR DESCRIPTION
**Pull request by hasithaa**
Fixes #16458
Fixes #18152
Fixes #18344

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 1]
```diff
@@ -1157,72 +1178,76 @@ public void visit(BLangResource resourceNode) {
     }
 
     public void visit(BLangForever foreverStatement) {
+
+        checkExperimentalFeatureValidity(ExperimentalFeatures.STREAMING_QUERIES, foreverStatement.pos);
         this.checkStatementExecutionValidity(foreverStatement);
         this.lastStatement = true;
     }
 
-    public void visit(BLangObjectTypeNode objectTypeNode) {
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: These are moved to one place

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 2]
```diff
@@ -1157,72 +1178,76 @@ public void visit(BLangResource resourceNode) {
...
+                    checkForExportableType(tableType.constraint.tsymbol, pos);
+                }
+                return;
+            case TypeTags.STREAM:
+                BStreamType streamType = (BStreamType) symbol.type;
+                if (streamType.constraint != null) {
+                    checkForExportableType(streamType.constraint.tsymbol, pos);
+                }
+                return;
+            // TODO : Add support for other types. such as union and objects
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Created issue to track this. : https://github.com/ballerina-platform/ballerina-lang/issues/18342

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 3]
```diff
@@ -1672,11 +1716,18 @@ public void visit(BLangTupleVarRef varRefExpr) {
 
     public void visit(BLangFieldBasedAccess fieldAccessExpr) {
         /* ignore */
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: We can remove this comment now?
