### PR TITLE
Fix transaction validating if rollback is used with if condition

### LINKED ISSUE #26854: Transaction validates if rollback command is used with if condition, commit should happen in else block
**Description:**
$subject
This becomes an issue when we try to use statements within the loop, we have to wait till loop exit to commit, however, the transaction compiler does not allow that

### PR DESCRIPTION
**Pull request by lasinicl**
Fixes #26854

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 1]
```diff
@@ -817,19 +808,25 @@ public void visit(BLangIf ifStmt) {
...
+        }
         if (ifStmt.elseStmt != null) {
-            if (independentBlocks) {
-                commitRollbackAllowed = true;
-                withinTransactionScope = true;
-            }
             analyzeNode(ifStmt.elseStmt, env);
-            if ((prevCommitCount != commitCount) || prevRollbackCount != rollbackCount) {
-                commitRollbackAllowed = false;
+            boolean hasVisitedCommitOrRollback = false;
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:819]: Can you check this fix instead for the else part against the tests
          
           analyzeNode(ifStmt.elseStmt, env);
            boolean elseWithinTrxMode = this.withinTransactionScope;
            this.statementReturns = ifStmtReturns && this.statementReturns;
            this.errorThrown = currentErrorThrown && this.errorThrown;
            this.withinTransactionScope = (!prevTxMode || ifWithinTrxMode || elseWithinTrxMode) && prevTxMode;

Comment (lasinicl) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: updated in 0135c17 . fixed the tests in https://github.com/ballerina-platform/module-ballerinai-transaction/pull/8/commits/cd53c3a2fe5faa1caf8f0015697371e59dfb0dfd

**Review by pcnfernando — APPROVED** [review]
