### PR TITLE
[master] Add Type compltion items to named arg context

### LINKED ISSUE #37562: [Bug]: Types not suggested in dependently-typed function signature scenarios
### Description

Refer to the following. Expected to see the type `http:Response` in the completions. However it works for regular assignment cases as the following shows. 

https://user-images.githubusercontent.com/6260009/187254212-c41b7bcb-8e24-4819-b93b-7b190921cdd8.mov

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Labels

LanguageServer

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject

Fixes #37562

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/CompletionTest.java [hunk 1]
```diff
@@ -77,7 +77,7 @@ public void test(String config, String configPath) throws WorkspaceDocumentExcep
         boolean result = CompletionTestUtil.isSubList(testConfig.getItems(), responseItemList);
         if (!result) {
             // Fix test cases replacing expected using responses
-//            updateConfig(configJsonPath, testConfig, responseItemList);
+            updateConfig(configJsonPath, testConfig, responseItemList);
```
Comment (mindula) [inline language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/CompletionTest.java:80]: let's comment out this line

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java [hunk 2]
```diff
@@ -542,8 +543,8 @@ public Optional<TypeSymbol> transform(NamedArgumentNode namedArgumentNode) {
                 }
 
                 for (ParameterSymbol parameterSymbol : parameterSymbols.get()) {
-                    if (parameterSymbol.getName().stream()
-                            .anyMatch(name -> name.equals(namedArgumentNode.argumentName().name().text()))) {
+                    if (parameterSymbol.getName()
+                            .map(name -> name.equals(namedArgumentNode.argumentName().name().text())).orElse(false)) {
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:547]: We can rewrite this as:
```
if (parameterSymbol.getName()
                            .filter(name -> name.equals(namedArgumentNode.argumentName().name().text()))
                            .isPresent()) {
```

**Review by IMS94 — CHANGES_REQUESTED** [review]
LGTM! Added minor suggestion. And please address Mindula's comment

**Review by mohanvive — APPROVED** [review]
