### PR TITLE
[Master] Add tests for incompatible type errors in json types

### LINKED ISSUE #32377: Getting incompatible types error when using (int population = (resp.population?.value ?: 0) / 1000000;)
**Description:**

Screenshot from 2021-08-26 11-24-07

Getting this error when using this compound if statement,

**Steps to reproduce:**

1. Create a new ballerina file
2. Add this code
```
import ballerinax/covid19;
import ballerina/http;

type Stats record {|
    string country;
    decimal totalCasesPerMillion;
|};

service / on new http:Listener(8090) {
    isolated resource function get stats/[string country]() returns Stats|error {
        covid19:Client covid19Client = check new ();
        covid19:CovidCountry statusByCountry = check covid19Client->getStatusByCountry(country);
        decimal totalCases = statusByCountry?.cases ?: 0;
        // Added a http client
        http:Client clientEndpoint = check new ("url");
        json resp = check clientEndpoint->get("/countrypop",targetType=json);
        int population = (resp.population?.value ?: 0) / 1000000;

        decimal totalCasesPerMillion = totalCases / <decimal> population;
        Stats payload = {country: country, totalCasesPerMillion: totalCasesPerMillion};
        return payload;
    }
}
```

**Affected Versions:**

Ballerina Swan Lake Alpha5

### PR DESCRIPTION
**Pull request by SasinduDilshara**
Fixes #32377

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/assign/AssignStmtTest.java [hunk 1]
```diff
@@ -209,6 +209,20 @@ public void testAssignmentNegativeCases() {
         BAssertUtil.validateError(resultNegative, i++,
                 "incompatible types: expected 'function ((any|error)...) returns ()', found " +
                         "'function (any...) returns ()'", 123, 47);
+        BAssertUtil.validateError(resultNegative, i++,
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/assign/AssignStmtTest.java:212]: I don't think this is the correct file for these tests. Shall we add them in org.ballerinalang.test.expressions.elvis.ElvisExpressionTest?

Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/assign/AssignStmtTest.java:212]: Yes. I will add.

Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/assign/AssignStmtTest.java]: Added. b70cbfef6ca3cfccbad57d8164f0ad5a4b62b134

**Review by MaryamZi — APPROVED** [review]
