### PR TITLE
Handle nullable types and fields in API doc generation

### LINKED ISSUE #43191: [Bug]: API Docs json doesn't contain nullable and field information
### Description

$Subject.

We generate code in AI impls based on this. So this is kinda blocker for libraries which uses nilable fields.

Ref:
https://central.ballerina.io/ballerinax/newsapi/1.5.1#WSNewsArticle
https://github.com/ballerina-platform/openapi-connectors/blob/bd0a79a010f374ef8241739509a8baa385dbc0c9/openapi/newsapi/types.bal#L101

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> API Docs

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by NipunaMadhushan**
## Purpose
This will handle the nullable types and fields properly. 
Boolean types will be handled along with this PR as well.

Fixes #43191

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by sm1990 — APPROVED** [review]

File: misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java [hunk 1]
```diff
@@ -326,12 +327,208 @@ public static void addTypeDefinition(TypeDefinitionNode typeDefinition, Module m
...
         // TODO: handle built in ref type
         // TODO: handle constrained types
     }
 
+    public static void addNullableTypeModel(OptionalTypeDescriptorNode typeDescriptorNode, String typeName,
+                                            Optional<MetadataNode> metaDataNode, Module module,
+                                            SemanticModel semanticModel) {
+        SyntaxKind syntaxKind = typeDescriptorNode.typeDescriptor().kind();
+
+        if (syntaxKind.equals(SyntaxKind.RECORD_TYPE_DESC)) {
```
Comment (LakshanWeerasinghe) [inline misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java:347]: Use switch case instead of if-else

File: misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java [hunk 2]
```diff
@@ -326,12 +327,183 @@ public static void addTypeDefinition(TypeDefinitionNode typeDefinition, Module m
...
+                            getDescSectionsDocFromMetaDataList(metaDataNode), isDeprecated(metaDataNode), refType));
+                } else {
+                    BType bType = getUnionTypeModel(typeDescriptorNode.typeDescriptor(), typeName,
+                            metaDataNode, semanticModel, module);
+                    bType.isNullable = true;
+                    module.simpleNameReferenceTypes.add(bType);
+                }
+                break;
+            case DISTINCT_TYPE_DESC:
+                if (((DistinctTypeDescriptorNode) (typeDescriptorNode.typeDescriptor())).typeDescriptor().kind()
```
Comment (LakshanWeerasinghe) [inline misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java:390]: Extract `DistinctTypeDescriptorNode` and `kind` to two variables and use in other places.

Comment (LakshanWeerasinghe) [reply misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java:390]: And better to move this switch case to another method.

File: misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java (hunk 1 above)
Comment (NipunaMadhushan) [reply misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java]: Addressed the suggestions

**Review by LakshanWeerasinghe — APPROVED** [review]

**Review by keizer619 — DISMISSED** [review]

**Review by azinneera — APPROVED** [review]

**Review by keizer619 — APPROVED** [review]
