### PR TITLE
Fix issues with package name in bal new

### LINKED ISSUE #38957: [Bug]: 'bal new' gives an empty string as package name for non-alphanumeric characters.
### Description

When only non-alphanumeric characters are given as the package name for `bal new`, a directory is created with the given name but all characters are replaced with `''`, resulting in an empty string as the package name in the `ballerina.toml` file. 

This gives the two errors, `"invalid 'name' under [package]: 'name' cannot have initial numeric characters"` and `"invalid 'name' under [package]: 'name' cannot have initial underscore characters"`.

### Steps to Reproduce

run `bal new` with only non-alphanumeric characters as the package name. eg: `_`

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Other Area

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by ShammiL**
Fixes #38957

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/NewCommandTest.java [hunk 1]
```diff
@@ -721,6 +721,31 @@ public void testNewCommandWithInvalidPackageNames1(String packageName, String ou
...
+    @DataProvider(name = "PackageNameHasOnlyAlphanumeric")
+    public Object[][] providePackageNameHasOnlyAlphanumeric() {
+        return new Object[][] {
+                { "#", "my_package" },
+                { "_", "my_package" }
+        };
+    }
+    @Test(description = "Test init command with package name has alpha-numeric characters",
+            dataProvider = "PackageNameHasOnlyAlphanumeric")
+    public void testInitCommandWithPackageNameHasOnlyAlphanumeric(String pkgName, String derivedPkgName)
```
Comment (azinneera) [inline cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/NewCommandTest.java:733]:
```suggestion
    public void testInitCommandWithPackageNameHasOnlyNonAlphanumeric(String pkgName, String derivedPkgName)
```

Comment (azinneera) [reply cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/NewCommandTest.java:733]: Applies to other places having a similar pattern

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java [hunk 2]
```diff
@@ -143,6 +144,16 @@ && validateUnderscoresOfName(packageName)
                 && validateInitialNumericsOfName(packageName);
     }
 
+    /**
+     * Validates the package name.
+     *
+     * @param packageName The package name.
+     * @return True if valid package name, else false.
+     */
+    public static boolean validatePackageNameForNewCommand(String packageName) {
```
Comment (azinneera) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/util/ProjectUtils.java:153]: Can we make this a part of ProjectUtils.validatePackageName without having to introduce a new API?

**Review by azinneera — APPROVED** [review]

File: cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/NewCommandTest.java (hunk 1 above)
Comment (ShammiL) [reply cli/ballerina-cli/src/test/java/io/ballerina/cli/cmd/NewCommandTest.java]: Applied
