### PR TITLE
Fix impConversionExpr type for checking-expr with no error type

### LINKED ISSUE #35150: Runtime crashes for check-expr
**Description:**
$title.

**Steps to reproduce:**
```ballerina
function fn2() returns error? {
    boolean b = true;
    error err = error("a");
    error a1 = check b? err:err;
}
```

Output:
```
[2022-02-21 17:23:37,992] SEVERE {b7a.log.crash} - Bad type on operand stack
Exception Details:
  Location:
    test2.fn2(Lio/ballerina/runtime/internal/scheduling/Strand;)Ljava/lang/Object; @249: ifgt
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @249
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', integer, 'io/ballerina/runtime/internal/values/ErrorValue', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/ErrorValue', null, 'io/ballerina/runtime/internal/values/TypedescValueImpl', 'java/lang/Object', 'java/lang/Object', 'io/ballerina/runtime/internal/values/ErrorValue', 'io/ballerina/runtime/internal/values/ErrorValue', 'java/lang/Object', 'java/lang/Object', integer }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 2ab4 0011 9900 07b8 0017 bf03 3c01 4d01
    0000010: 4e01 3a04 013a 0501 3a06 013a 0701 3a08
    0000020: 013a 0901 3a0a 013a 0b01 3a0c 0336 0d2a
    0000030: b400 1b9d 0101 150d ab00 0000 0000 0150
    0000040: 0000 0008 0000 0000 0000 004c 0000 0001
    0000050: 0000 008c 0000 0002 0000 00ba 0000 0003
    0000060: 0000 00ca 0000 0004 0000 00d5 0000 0005
    0000070: 0000 00e4 0000 0006 0000 00ec 0000 0007
    0000080: 0000 00f4 1100 0036 0d12 1c3c b200 224e
    0000090: 013a 0519 05c0 0024 3a04 bb00 2659 bb00
    00000a0: 2859 b200 2e03 b700 3110 00bd 0033 b700
    00000b0: 363a 0619 062a 1400 3788 bd00 3ab9 0040
    00000c0: 0300 3a07 1100 0136 0d2a 1907 04b8 0046
    00000d0: 3a08 2ab6 004a 9a00 b2a7 0003 bb00 2459
    00000e0: b200 502d 1904 1908 b700 534d 1bb8 0059
    00000f0: 3a0b 1100 0236 0d19 0b9d 0006 a700 0e2c
    0000100: 3a0a 1100 0336 0da7 000e 2c3a 0a11 0004
    0000110: 360d a700 0319 0a3a 0901 3a0c 1100 0536
    0000120: 0da7 000b 1100 0636 0da7 0003 1100 0736
    0000130: 0d19 0cb0 2ab4 005d 2a59 b400 1b04 645a
    0000140: b500 1b32 c000 5f59 b400 633a 0c59 b400
    0000150: 663c 59b4 006a 4d59 b400 6d4e 59b4 0070
    0000160: 3a04 59b4 0074 3a07 59b4 0077 3a08 59b4
    0000170: 007a 3a09 59b4 007d 3a0a 59b4 0080 3a0b
    0000180: b400 8336 0da7 feb1 bb00 5f59 b700 8459
    0000190: 190c b500 6359 1bb5 0066 592c b500 6a59
    00001a0: 2db5 006d 5919 04b5 0070 5919 07b5 0074
    00001b0: 5919 08b5 0077 5919 09b5 007a 5919 0ab5
    00001c0: 007d 5919 0bb5 0080 5915 0db5 0083 3a0e
    00001d0: 2ab4 005d 2a59 b400 1b5a 0460 b500 1b19
    00001e0: 0e53 190c b0                           
  Stackmap Table:
    same_frame(@11)
    full_frame(@54,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Null,Object[#51],Object[#51],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})
    same_frame_extended(@132)
    full_frame(@196,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Object[#38],Object[#4],Object[#51],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})
    full_frame(@220,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Object[#38],Object[#4],Object[#4],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})
    same_frame(@242)
    same_frame(@255)
    same_frame(@258)
    same_frame(@266)
    same_frame(@269)
    same_frame(@277)
    same_frame(@284)
    full_frame(@292,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Null,Object[#51],Object[#51],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})
    full_frame(@300,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Object[#38],Object[#4],Object[#4],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})
    full_frame(@308,{Object[#13],Integer,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Integer},{})
    full_frame(@392,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Object[#38],Object[#4],Object[#4],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})
 
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    test2.fn2(Lio/ballerina/runtime/internal/scheduling/Strand;)Ljava/lang/Object; @249: ifgt
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @249
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', integer, 'io/ballerina/runtime/internal/values/ErrorValue', 'io/ballerina/runtime/api/values/BString', 'io/ballerina/runtime/internal/values/ErrorValue', null, 'io/ballerina/runtime/internal/values/TypedescValueImpl', 'java/lang/Object', 'java/lang/Object', 'io/ballerina/runtime/internal/values/ErrorValue', 'io/ballerina/runtime/internal/values/ErrorValue', 'java/lang/Object', 'java/lang/Object', integer }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 2ab4 0011 9900 07b8 0017 bf03 3c01 4d01
    0000010: 4e01 3a04 013a 0501 3a06 013a 0701 3a08
    0000020: 013a 0901 3a0a 013a 0b01 3a0c 0336 0d2a
    0000030: b400 1b9d 0101 150d ab00 0000 0000 0150
    0000040: 0000 0008 0000 0000 0000 004c 0000 0001
    0000050: 0000 008c 0000 0002 0000 00ba 0000 0003
    0000060: 0000 00ca 0000 0004 0000 00d5 0000 0005
    0000070: 0000 00e4 0000 0006 0000 00ec 0000 0007
    0000080: 0000 00f4 1100 0036 0d12 1c3c b200 224e
    0000090: 013a 0519 05c0 0024 3a04 bb00 2659 bb00
    00000a0: 2859 b200 2e03 b700 3110 00bd 0033 b700
    00000b0: 363a 0619 062a 1400 3788 bd00 3ab9 0040
    00000c0: 0300 3a07 1100 0136 0d2a 1907 04b8 0046
    00000d0: 3a08 2ab6 004a 9a00 b2a7 0003 bb00 2459
    00000e0: b200 502d 1904 1908 b700 534d 1bb8 0059
    00000f0: 3a0b 1100 0236 0d19 0b9d 0006 a700 0e2c
    0000100: 3a0a 1100 0336 0da7 000e 2c3a 0a11 0004
    0000110: 360d a700 0319 0a3a 0901 3a0c 1100 0536
    0000120: 0da7 000b 1100 0636 0da7 0003 1100 0736
    0000130: 0d19 0cb0 2ab4 005d 2a59 b400 1b04 645a
    0000140: b500 1b32 c000 5f59 b400 633a 0c59 b400
    0000150: 663c 59b4 006a 4d59 b400 6d4e 59b4 0070
    0000160: 3a04 59b4 0074 3a07 59b4 0077 3a08 59b4
    0000170: 007a 3a09 59b4 007d 3a0a 59b4 0080 3a0b
    0000180: b400 8336 0da7 feb1 bb00 5f59 b700 8459
    0000190: 190c b500 6359 1bb5 0066 592c b500 6a59
    00001a0: 2db5 006d 5919 04b5 0070 5919 07b5 0074
    00001b0: 5919 08b5 0077 5919 09b5 007a 5919 0ab5
    00001c0: 007d 5919 0bb5 0080 5915 0db5 0083 3a0e
    00001d0: 2ab4 005d 2a59 b400 1b5a 0460 b500 1b19
    00001e0: 0e53 190c b0                           
  Stackmap Table:
    same_frame(@11)
    full_frame(@54,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Null,Object[#51],Object[#51],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})
    same_frame_extended(@132)
    full_frame(@196,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Object[#38],Object[#4],Object[#51],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})
    full_frame(@220,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Object[#38],Object[#4],Object[#4],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})
    same_frame(@242)
    same_frame(@255)
    same_frame(@258)
    same_frame(@266)
    same_frame(@269)
    same_frame(@277)
    same_frame(@284)
    full_frame(@292,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Null,Object[#51],Object[#51],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})
    full_frame(@300,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Object[#38],Object[#4],Object[#4],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})
    full_frame(@308,{Object[#13],Integer,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Integer},{})
    full_frame(@392,{Object[#13],Integer,Object[#36],Object[#139],Object[#36],Null,Object[#38],Object[#4],Object[#4],Object[#36],Object[#36],Object[#4],Object[#4],Integer},{})

        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:611)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:317)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:284)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Affected Versions:**
SL 2201.0.0

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #35150 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -5961,6 +5961,14 @@ private void visitCheckAndCheckPanicExpr(BLangCheckedExpr checkedExpr, AnalyzerD
                         DiagnosticWarningCode.CHECKED_EXPR_INVALID_USAGE_NO_ERROR_TYPE_IN_RHS,
                         operatorType);
                 data.resultType = checkedExpr.expr.getBType();
+
+                BLangTypeConversionExpr impConversionExpr = checkedExpr.expr.impConversionExpr;
+                if (impConversionExpr != null) {
+                    // Exclude any manually added error type, by reassigning
+                    BType expType = Types.getReferredType(data.expType);
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5968]: Why did you have to take the actual type here?

Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5968]: We do that when we set the `ImplicitCastExpr`. I'm sticking to the same behavior to avoid any inconsistency. 

https://github.com/ballerina-platform/ballerina-lang/blob/39d844eb7ee4f780584be4ad0d9f7322bb7e4def/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L2408-L2409

Comment (lasinicl) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5968]: I think it's okay to use the `data.expType` here instead of the actual type, since it's the expected type of the expression.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_with_no_error_type.bal [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+    panic error("You are not supposed to reach this line");
+}
+
+function testCheckingExprWithNoErrorType2() {
+    boolean b = true;
+    error err = error("Error!");
+    error err1 = check b ? err : err;
+    assertEquality(err1.message(), "Error!");
+}
+
```
[the remark this answers is not in the document]
Comment (lochana-chathura) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/checkedexpr/checked_expr_with_no_error_type.bal:52]: Thanks!. Fixed now

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Please check with the new changes. Needed if-check located inside `setImplicitCastExpr()` also. Without duplicating logic called `setImplicitCastExpr()` here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -5961,6 +5961,14 @@ private void visitCheckAndCheckPanicExpr(BLangCheckedExpr checkedExpr, AnalyzerD
...
+                    impConversionExpr.setBType(expType);
```
[the remark this answers is not in the document]
Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: We do. Consider `T  _ = check expr`,

Here when we do the type checking for the `expr`, the contextually excepted type is `T|error`.
Only after the type-checking, we know whether the actual type includes an error type or not. If it does not include an error type, usage of checking keyword is redundant. i.e. `T  _ = check expr` is equivalent to `T _ = expr`. Because we did the type checking with expected type being `T|error` earlier, `impConversionExpr` is not correct. So we have reset  it with the type `T`.

[the remark this answers is not in the document]
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Thank you for the details. I only have a small concern about why we do this twice. Why can't we add the implicit conversion here or at desugar when we have all the details. Otherwise, all looks good.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 4]
```diff
@@ -5960,7 +5960,12 @@ private void visitCheckAndCheckPanicExpr(BLangCheckedExpr checkedExpr, AnalyzerD
                 dlog.warning(checkedExpr.expr.pos,
                         DiagnosticWarningCode.CHECKED_EXPR_INVALID_USAGE_NO_ERROR_TYPE_IN_RHS,
                         operatorType);
+                checkedExpr.isRedundantChecking = true;
                 data.resultType = checkedExpr.expr.getBType();
+
+                // Reset impConversionExpr as it was previously based on default error added union type
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5966]: Shall we create a method for duplicate code segments for resetting implicit cast

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Had a discussion I will look at this logic more and reply.

**Review by KRVPerera — APPROVED** [review]

**Comment by pcnfernando** [comment]
@lochana-chathura shall we change the branch to 2201.1.x

**Review by KRVPerera — APPROVED** [review]

**Review by pcnfernando — APPROVED** [review]
