### PR TITLE
[Master] Fix tuple related issues

### LINKED ISSUE #34954: NPE for `cloneReadOnly()` when it is used with tuples
**Description:**
$title.
```ballerina
type FloatBooleanTuple [float, boolean];

public function main() {
    anydata a1 = [1.2, true];
    boolean x = a1.cloneReadOnly() is FloatBooleanTuple;
}
```
Output:
```
[2022-02-07 12:24:02,438] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.util.ImmutableTypeCloner.getEffectiveImmutableType(ImmutableTypeCloner.java:95)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getArrayTypeForAnydataOrJson(Types.java:4863)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getIntersection(Types.java:4803)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getTypeIntersection(Types.java:4633)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getTypeIntersection(Types.java:4624)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.intersectionExists(CodeAnalyzer.java:3994)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:3977)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeTestExpr.accept(BLangTypeTestExpr.java:75)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:4023)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2468)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:377)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:2562)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:377)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:559)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:377)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visitFunction(CodeAnalyzer.java:533)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:481)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:377)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeTopLevelNodes(CodeAnalyzer.java:365)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:357)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyze(CodeAnalyzer.java:346)
        at io.ballerina.projects.internal.CompilerPhaseRunner.codeAnalyze(CompilerPhaseRunner.java:196)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:119)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:436)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:386)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:145)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Affected Versions:**
Swan Lake 2201.0.0

### LINKED ISSUE #36852: Compile time error when matching on a recursive type
```ballerina
public type Type ["list", Type[]]|"int";

function g() {
    Type x =  ["list", ["int"]];
    match x {
        "int" => {
            io:println(x);
        }
        ["list", var y] => {
            io:println(y);
        }
    }
}
```

Give compile time error:
```
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:613)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangIndexBasedAccess.accept(BLangIndexBasedAccess.java:60)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1707)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:79)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1211)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1118)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1582)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:60)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1118)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1270)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:53)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1563)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:60)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1118)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1270)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:53)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:1563)
 ```

### LINKED ISSUE #37049: semantics analyzer stack overflows
```ballerina
public type Type ["|", Type, Type...] | "int" ; 
public type TypeList Type[];
```
Above gives compile time error

```
java.lang.StackOverflowError
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:533)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.hasFillerValue(Types.java:6081)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.checkFillerValue(Types.java:6170)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.hasFillerValue(Types.java:6071)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.lambda$hasFillerValue$43(Types.java:6081)
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:533)
```
Surprisingly below is Ok.

 ```ballerina
public type Type ["|", Type...] | "int" ; 
public type TypeList Type[];
```

### LINKED ISSUE #37136: Compiler crashes with IndexOutOfBoundsException for match statment with recursive types
**Description:**
$subject. 

Consider the below code. 
```bal
import ballerina/io;

public function main() returns error? {
    Atom a = ["cell", "int", "inf"];
    match a {
        ["cell", var x, var y] => {
            io:println(x);
            io:println(y);
        }
    }
}

public type Atom ["array", Type]|["cell", Type, string];

public type Type ["|", Type]|"int";
```

<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
[2022-07-27 12:47:48,194] SEVERE {b7a.log.crash} - Index 2 out of bounds for length 2 
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.assignTypesToMemberPatterns(SemanticAnalyzer.java:2922)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.assignTypesToMemberPatterns(SemanticAnalyzer.java:2886)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:3449)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
        at org.wso2.ballerinalang.compiler.tree.matchpatterns.BLangListMatchPattern.accept(BLangListMatchPattern.java:69)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4156)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4132)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2691)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
        at org.wso2.ballerinalang.compiler.tree.clauses.BLangMatchClause.accept(BLangMatchClause.java:65)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4156)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4132)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2661)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatchStatement.accept(BLangMatchStatement.java:82)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4156)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4132)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:4117)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:515)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:65)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4156)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:495)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:81)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4156)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4132)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4113)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:328)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
        at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:201)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:282)
        at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:428)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:377)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:200)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:185)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:101)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:96)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:147)
        at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:254)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:95)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
</details>

**Affected Versions:**
2201.1.1

### LINKED ISSUE #37145: Can't expose a public tuple type with a singleton via a public function
```ballerina
public type X ["x"];
public function func() returns X {
    return ["x"];
}
```
above gives following compile time error
`ERROR [main.bal:(4:32,4:33)] attempt to expose non-public symbol ''`

### LINKED ISSUE #37176: Member accessing a tuple within match statement block not working with resursive types
**Description:**
$subect.

Consider the below code:
```bal
public function main() {
    Atom atom = ["cell", "int"];
    match atom {
        ["list", var _] => {
            Type _ = atom[1]; // Works
        }
        ["array", var _] => {
            Type _ = atom[1]; // Gives "invalid operation: type 'other' does not support member access"
        }
        ["cell", var _] => {
            Type _ = atom[1]; // "Gives invalid operation: type 'other' does not support member access"
        }
    }
}

public type Atom ["array", Type]|["cell", Type];

public type Type ["|", Type]|"int";
````

**Affected Versions:**
2201.1.1

### LINKED ISSUE #37294: Invalid `Uninitialise Variable Error` for List match Pattern
**Description:**
Invalid `Uninitialise Variable Error` for List match Pattern

**Steps to reproduce:**
```
public type T5 [string, int];

public function test() returns string {
    T5 a = ["string", 1];
    string b;
    match a {
        [_, var x] => {
            _ = x;
            b = "string";
        }
    }
    return b; // Error: variable 'b' may not have been initialized
}
```
This error should not occured, because the match expression will always true for the above match pattern.

### LINKED ISSUE #37295: Compiler crash for list match patterns
**Steps to reproduce:**

```
public type T [string]|[int, string]|[int, int, string];

function test(T t) returns string? {
    match t {
        [var p, var x, var y, ...var z] => {
            return "match 1";
        }
        [var p, var x, ...var z] => {
            return "match 2";
        }
        [var p, ...var z] => {
            return "match 3";
        }
    }
}
```
Compiler crash for above code with following output

```
We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-08-08 13:44:40,150] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getReferredType(Types.java:1341)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.createVarSymbol(SymbolEnter.java:4617)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.createVarSymbol(SymbolEnter.java:4611)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineVarSymbol(SymbolEnter.java:4585)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineVarSymbol(SymbolEnter.java:4578)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.resolveMatchClauseVariableTypes(SemanticAnalyzer.java:2728)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2692)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
        at org.wso2.ballerinalang.compiler.tree.clauses.BLangMatchClause.accept(BLangMatchClause.java:65)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4156)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4132)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2661)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatchStatement.accept(BLangMatchStatement.java:82)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4156)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4132)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:4117)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:515)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:65)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4156)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:495)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:81)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4156)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4132)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4113)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:328)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
        at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:201)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:282)
        at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:428)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:377)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:200)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:185)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:101)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:96)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:147)
        at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:254)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:95)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### PR DESCRIPTION
**Pull request by SasinduDilshara**
Fixes #36852
Fixes #37136
Fixes #37176
Fixes #37049
Fixes #37145
Fixes #34954
Fixes #37294
Fixes #37295

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 1]
```diff
@@ -2958,7 +2958,6 @@ private void assignTypesToMemberPatterns(BLangMatchPattern matchPattern, BType b
                     for (BType type : ((BUnionType) patternType).getMemberTypes()) {
                         assignTypesToMemberPatterns(listMatchPattern, type, data);
                     }
-                    listMatchPattern.setBType(patternType);
```
Comment (SasinduDilshara) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2961]: This change leads o fail three test cases. Currently looking into it. Therefore mark this PR as draft

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 2]
```diff
@@ -6088,6 +6095,13 @@ private boolean checkFillerValue(BUnionType type) {
                     hasFillerValue = true;
                 }
             } else {
+                if (member.tag == TypeTags.TUPLE) {
+                    for (BType tupleType: ((BTupleType) member).tupleTypes) {
+                        if (tupleType.tsymbol.getName().equals(type.tsymbol.getName())) {
+                            return false;
+                        }
+                    }
+                }
```
Comment (SasinduDilshara) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:6104]: This change done for https://github.com/ballerina-platform/ballerina-lang/issues/37049

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 3]
```diff
@@ -5207,7 +5214,7 @@ private BMapType getMapTypeForAnydataOrJson(BType type, SymbolEnv env) {
         return mapType;
     }
 
-    private BArrayType getArrayTypeForAnydataOrJson(BType type) {
+    private BArrayType getArrayTypeForAnydataOrJson(BType type, SymbolEnv env) {
```
Comment (SasinduDilshara) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:5217]: This change done for https://github.com/ballerina-platform/ballerina-lang/issues/34954

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 4]
```diff
@@ -5791,6 +5798,10 @@ private boolean checkFillerValue(BUnionType type) {
             return true;
         }
 
+        if (type.isCyclic) {
+            return false;
+        }
+
```
Comment (SasinduDilshara) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:5804]: This change done for resolve #37049.

**Comment by MaryamZi** [comment]
@SasinduDilshara, what is the test added for #37145?

File: tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal [hunk 5]
```diff
@@ -316,6 +316,28 @@ function testBinaryExprAssignments() {
...
+}
+
+function returnTupleWithSingletonType() returns X1 {
+    return ["x"];
+}
+
+function returnTupleWithSingletonType2() returns X2 {
+    return ["x", 2, ()];
+}
+
```
Comment (SasinduDilshara) [inline tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal:340]: These are the tests for #37145

**Comment by SasinduDilshara** [comment]
> @SasinduDilshara, what is the test added for #37145?

Please refer this comment. https://github.com/ballerina-platform/ballerina-lang/pull/37235/files#r944117499

File: tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal (hunk 5 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal:340]: These work for me on 2201.1.1 also. Shouldn't `returnTupleWithSingletonType` and `returnTupleWithSingletonType2` be `public` to be the same scenario as https://github.com/ballerina-platform/ballerina-lang/issues/37145?

**Comment by MaryamZi** [comment]
> > @SasinduDilshara, what is the test added for #37145?
> 
> Please refer this comment. https://github.com/ballerina-platform/ballerina-lang/pull/37235/files#r944117499

Please see https://github.com/ballerina-platform/ballerina-lang/pull/37235/files#r944119256.

File: tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal (hunk 5 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal:340]: Yes. I will update.

Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions.bal:340]: Updated. bca1c000ddcdef0dc7360bf8b70d4faf1077d9c5

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 6]
```diff
@@ -906,9 +906,16 @@ private boolean isAssignable(BType source, BType target, Set<TypePair> unresolve
             return isFiniteTypeAssignable((BFiniteType) source, target, unresolvedTypes);
         }
 
-        if ((targetTag == TypeTags.UNION || sourceTag == TypeTags.UNION) &&
-                isAssignableToUnionType(source, target, unresolvedTypes)) {
-            return true;
+        if ((targetTag == TypeTags.UNION || sourceTag == TypeTags.UNION)) {
+            boolean isAssignableToUnion = isAssignableToUnionType(source, target, unresolvedTypes);
+            if (isAssignableToUnion) {
```
[the remark this answers is not in the document]
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:911]: https://github.com/ballerina-platform/ballerina-lang/pull/37270 PR needs to merge before this PR. Then it will contains this changes.

**Comment by SasinduDilshara** [comment]
Since this PR and https://github.com/ballerina-platform/ballerina-lang/pull/37270 PR has overlapping changes, 
We need to merge https://github.com/ballerina-platform/ballerina-lang/pull/37270 before this PR.

**Comment by SasinduDilshara** [comment]
> Since this PR and #37270 PR has overlapping changes, We need to merge #37270 before this PR.

#37270 got merged. This PR can review.

**Review by gimantha — APPROVED** [review]
LGTM
