### PR TITLE
Fix function names in class symbol hover and hover over new expressions

### LINKED ISSUE #33670: Missing Hover for function initialisation after code completion
**Description:**

Screenshot 2021-11-05 at 21 03 38

Here there was a hovering object with the function definition, with the latest version this is missing.

Also, this hover object does not include default values.

### LINKED ISSUE #33671: Missing details in hover such as function name and stream completion type
**Description:**
Function names are not visible for object hover
Screenshot 2021-11-05 at 21 02 56

Stream completion type is incomplete `sql:Error?` is seen as `sql:?`
Screenshot 2021-11-05 at 21 04 07

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
$subject

Fixes #33670
Fixes #33671

## Approach
1. Updated `HoverUtil` to provide hover for expressions when a symbol is not found. 
2. Updated hover of class symbols to use function symbols' signature instead of function type symbols' signature.

Screenshot from 2021-12-06 10-14-05

Screenshot from 2021-12-06 10-14-11

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by gayalkuruppu — DISMISSED** [review]
LGTM

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java [hunk 1]
```diff
@@ -81,6 +87,16 @@ public static Hover getHover(HoverContext context) {
         // Check for the cancellation after the time consuming operation
         context.checkCancelled();
         if (symbolAtCursor.isEmpty()) {
+            Range nodeRange = new Range(context.getCursorPosition(), context.getCursorPosition());
+            NonTerminalNode nodeAtCursor = CommonUtil.findNode(nodeRange, srcFile.get().syntaxTree());
+            if (nodeAtCursor != null) {
+                MatchedExpressionNodeResolver expressionResolver = new MatchedExpressionNodeResolver(nodeAtCursor);
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java:93]: I see that we are reusing the Code Action's node finder util here. Shall we make a note to introduce a common API/ visitor in the future?

**Review by nadeeshaan — DISMISSED** [review]
LGTM

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java [hunk 2]
```diff
@@ -120,6 +136,52 @@ private static Hover getHoverForSymbol(Symbol symbol, HoverContext context) {
...
 
+    /**
+     * Get hover for expression nodes. Note that we are supplying hover for a selected set of expressions.
+     *
+     * @param context  Context
+     * @param exprNode Expression node
+     * @return Hover
+     */
+    private static Hover getHoverForExpression(HoverContext context, Node exprNode) {
+        switch (exprNode.kind()) {
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java:147]: missing default case

Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java:147]: I did not add a default case to keep the code simple. If we add a default case, we will have to return the default hover object in the default case and at the end of the method both. Wdyt?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java (hunk 1 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java:93]: I think this visitor is useful for us for use cases like this. Rather than checking each expression kind (via syntax kind), this is clean. Is it ok if we use it everywhere?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java (hunk 2 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java:147]: We can leave the default case empty.(`default:`) I thought it is best to add it

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/hover/HoverUtil.java:93]: The best option would be now, to take this out to a common place. Please create a separate task to refactor this.

**Review by nadeeshaan — APPROVED** [review]
LGTM
