### PR TITLE
Provide completions after a variable resource path parameter in a resource access action

### LINKED ISSUE #41623: [Bug]: Completions are not provided after providing a variable for a resource path
### Description

$subject

### Steps to Reproduce

Obtain the completions for the given cursor position.

```ballerina
client class MyClient {
    resource function get first/[string second]/third() {}
}

public function main() {
    string someVar = "check";
    MyClient cl = new;
    cl->/first/[someVar]/<cursor>;
}
```

### Affected Version(s)

Ballerina 2201.8.1 (Swan Lake Update 8)

### OS, DB, other environment details and versions

OS - macOS 14.0 23A344

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/41563

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by nipunayf**
## Purpose
$title.

Fixes #41623

## Approach
The current implementation of the type checker does not resolve the variable types of the path parameters if it encounters an error. The PR resolves the variable types despite the error conditions.

## Samples

Completions are now shown after a resource path parameter with a variable, as shown below.

image

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -3833,10 +3834,12 @@ public void visit(BLangInvocation.BLangResourceAccessInvocation resourceAccessIn
...
         int targetResourceFuncCount = resourceFunctions.size();
         if (targetResourceFuncCount == 0) {
+            checkExpr(resourceAccessInvocation.resourceAccessPathSegments, data);
             dlog.error(resourceAccessInvocation.name.pos,
                     DiagnosticErrorCode.UNDEFINED_RESOURCE_METHOD, resourceAccessInvocation.name, lhsExprType);
             data.resultType = symTable.semanticError;
         } else if (targetResourceFuncCount > 1) {
+            checkExpr(resourceAccessInvocation.resourceAccessPathSegments, data);
             dlog.error(resourceAccessInvocation.pos, DiagnosticErrorCode.AMBIGUOUS_RESOURCE_ACCESS_NOT_YET_SUPPORTED);
             data.resultType = symTable.semanticError;
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3844]: I would like to rearrange this to call checkExpr once.

**Review by KavinduZoysa — APPROVED** [review]

File: language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config44.json [hunk 2]
```diff
@@ -0,0 +1,40 @@
+{
+  "position": {
+    "line": 7,
+    "character": 25
+  },
+  "source": "action_node_context/source/client_resource_access_action_source37.bal",
+  "description": "",
```
Comment (mindula) [inline language-server/modules/langserver-core/src/test/resources/completion/action_node_context/config/client_resource_access_action_config44.json:7]: Let's not keep empty descriptions

**Review by KavinduZoysa — APPROVED** [review]
