### PR TITLE
Fix several issues with `ensureType` function

### LINKED ISSUE #29219: Weird error with value:ensureType
**Description:**
$title. Observed when changing the return type of `ensureType` to be dependently-typed.

**Steps to reproduce:**
Consider the following example.
```ballerina
json p = {};

function foo() returns error? {
    int age = check p.name;
}

public function main() {
    any a = <string[]> ["hello", "world"];
    string[]|error strArray = a.ensureType(StringArray);
}

type StringArray string[];
```

Since the return type on master/alpha2 for `ensureType` is not dependently-typed we can expect an`incompatible types: expected '(string[]|error)', found '(any|error)'` error here. But the actual error logged is 

```
incompatible types: expected '(string[]|error)', found '(int|error)'
```

But when the `foo` function is commented out the expected error is logged!

**Affected Versions:**
slalpha2

### LINKED ISSUE #29368: ensureType doesn't works well with built-in subtypes
```ballerina
function test1() {
    int number1= 10;
    int:Unsigned32|error x = number1.ensureType(int:Signed32));
}
```

Gives 

`incompatible types: expected '(int:Unsigned32|error)', found '(any|error)'`

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fixes #29219 
Fixes #29368 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -4821,21 +4819,21 @@ private void visitCheckAndCheckPanicExpr(BLangCheckedExpr checkedExpr) {
...
-            invocation.pkgAlias = (BLangIdentifier) TreeBuilder.createIdentifierNode();
-            checkedExpr.expr = invocation;
+            BType varRefType = getTypeOfExprInFieldAccess(((BLangFieldBasedAccess) exprWithCheckingKeyword).expr);
+            if (types.isLax(varRefType)) {
+                ArrayList<BLangExpression> argExprs = new ArrayList<>();
+                BType typedescType = new BTypedescType(expType, null);
+                BLangTypedescExpr typedescExpr = new BLangTypedescExpr();
+                typedescExpr.resolvedType = expType;
+                typedescExpr.type = typedescType;
+                argExprs.add(typedescExpr);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4829]: Can't we move this to desugar like we discussed?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4829]: Created https://github.com/ballerina-platform/ballerina-lang/issues/29932.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -2178,6 +2175,9 @@ public void visit(BLangSimpleVarRef varRefExpr) {
                     actualType = symTable.semanticError;
                     dlog.error(varRefExpr.pos, DiagnosticErrorCode.CANNOT_UPDATE_CONSTANT_VALUE);
                 }
+            } else if ((symbol.tag & SymTag.TYPE_DEF) == SymTag.TYPE_DEF || (symbol.tag & SymTag.TYPE) == SymTag.TYPE) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2178]: I'm not sure if adding a check for SymTag.TYPE here is correct. IINM, SymTag.TYPE_DEF should have been set for the problem cases here.

@pubudu91 thoughts please?

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2178]: What prompted to make this change? I also don't feel like checking for the `TYPE` sym tag here is correct.

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2178]:
```ballerina
function testEnsureTypeFunction() {
    int number = 10;
    int:Unsigned32|error number1 = number.ensureType(int:Unsigned32);
}
```
The expected type for the parameter of `ensureType` is `typedesc`. Here `int:Unsigned32` is a simple variable reference. I used above change to set `actualType` as `typedesc<int:Unsigned32>`

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2178]: The original issue was that we couldn't refer to a builtin-subtype in a context where a typedesc is expected.

e.g.,
```ballerina
typedesc td = int:Unsigned32; // undefined symbol 'Unsigned32'
```

I just checked this with a user-defined type in a different module and it works without an issue. I think this can be an issue with the symbols defined specifically for builtin-subtypes (we create the symbol manually even though the type is defined in the langlib). Ideally, the symbol should have had the TYPE_DEF tag. 

@chiranSachintha, can you please check?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2178]: This isn't an issue only via the BIR btw. Trying to refer to the type within the relevant langlib also fails with the same error.

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2178]: `builtin-subtypes` only contains the TYPE tag. Should it have a `TYPE_DEF` tag though it is not a type definition?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2178]: Right now, I believe for types associated with a type definition, we also use the TYPE_DEF tag. You can check this with something like

```ballerina
type Foo record {|
    
|};

Foo f = {}; // check the tag for Foo's type symbol here
```

I think we'll have to do the same here at least for now.

File: langlib/langlib-test/src/test/resources/test-src/valuelib_test_negative.bal [hunk 3]
```diff
@@ -30,3 +30,12 @@ function testCloneWithTypeWithInvalidInferredType() {
...
     MyClass|error z = value:cloneWithType(x);
 }
+
+type Person record {
+    int name;
+};
+
+function testEnsureTypeFunction() returns error? {
+    Person p = {name: 12};
+    int age = check p.name;
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/resources/test-src/valuelib_test_negative.bal:40]: These tests should ideally go in a separate file, rather than in the langlib tests, since we're aren't directly testing the langlib. ensureType should have its own tests.

**Review by MaryamZi — APPROVED** [review]

File: langlib/langlib-test/src/test/resources/test-src/valuelib_test_negative.bal (hunk 3 above)
Comment (MaryamZi) [reply langlib/langlib-test/src/test/resources/test-src/valuelib_test_negative.bal:40]: We can do this separately.

Comment (chiranSachintha) [reply langlib/langlib-test/src/test/resources/test-src/valuelib_test_negative.bal:40]: Created an issue to track this(https://github.com/ballerina-platform/ballerina-lang/issues/30009)
