### PR TITLE
Revoke implicit conversion from xml:Text to string

### LINKED ISSUE #28546: Revert the implicit conversion from xml:Text to string
**Description:**
As per the spec issue https://github.com/ballerina-platform/ballerina-spec/issues/717 we need to remove this implicit conversion. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by suleka96**
Fixes  #28546

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by rdhananjaya** [comment]
Is there a reason why this PR depends on https://github.com/ballerina-platform/ballerina-lang/pull/28556

**Comment by suleka96** [comment]
There were few minor changes in #28556  that I would have had to repeat in this so I did these changes on top of it

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLTextToStringConversionNegativeTest.java [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+import org.ballerinalang.test.BCompileUtil;
+import org.ballerinalang.test.CompileResult;
+import org.testng.Assert;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Test;
+
+/**
+ * Test cases to check invalid XML Text to String conversion.
+ *
+ * @since 1.3.0
```
Comment (rdhananjaya) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/xml/XMLTextToStringConversionNegativeTest.java:30]: 2.0.0

**Review by rdhananjaya — APPROVED** [review]
