### PR TITLE
Sync RegExp runtime and compile time parsers

### LINKED ISSUE #39888: [Task]: Sync regexp runtime parser and compile time parser
### Description

$subject

### Describe your task(s)

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39932: [Bug]: No runtime error for invalid character range in regex
### Description

Consider following code

```
import ballerina/lang.regexp;

public function main() returns error? {
    // regexp:RegExp _ = re `[z-a]`; // compile error: start char code is greater than end char code(BCE4035)
    regexp:RegExp _ = check regexp:fromString("[z-a]"); // no error
}
```
This should be a runtime error because `z-a` is a invalid range.

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #40141: [Bug]: Multiple range character class patterns defined in runtime crashes
### Description

```ballerina
import ballerina/lang.regexp;

public function main() returns error? {
    string:RegExp pattern = check regexp:fromString("[a-zA-Z]");
    _ = pattern.find("Ballerina");
}
```

```
error: java.lang.ClassCastException {"message":"class io.ballerina.runtime.internal.values.RegExpCharSet cannot be cast to class java.lang.String (io.ballerina.runtime.internal.values.RegExpCharSet is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')"}
        at ballerina.lang.regexp.0:findImpl(regexp.bal:81)
           ballerina.lang.regexp.0:find(regexp.bal:71)
           regexp_bbe:main(regexp_bbe.bal:5)
```

### Steps to Reproduce

_No response_

### Affected Version(s)

2201.5.0 rc1

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #40142: [Bug]: Creation of nested character classes in regex patterns at runtime
### Description

According to our spec nested character class defining should not be allowed. Following program execution should result in runtime error.

```ballerina
import ballerina/lang.regexp;

public function main() returns error? {
    string:RegExp pattern = check regexp:fromString("[a-z[a-z]]");
}
```

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by LakshanWeerasinghe**
## Purpose
$subject

Fixes #39888
Fixes #39932
Fixes #40142
Fixes #40141

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [x] Added necessary documentation  
  - [x] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/RegExpFactory.java [hunk 1]
```diff
@@ -111,11 +111,11 @@ public static RegExpValue parse(String regExpStr) {
             TreeBuilder treeBuilder = new TreeBuilder(tokenReader);
             return treeBuilder.parse();
         } catch (BallerinaException e) {
-            throw ErrorCreator.createError(StringUtils.fromString("Failed to parse regular expression: " +
-                    e.getMessage()));
+            throw ErrorCreator.createError(StringUtils.fromString(e.getMessage() 
+                    + " in '" + regExpStr + "' RegExp pattern"));
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/RegExpFactory.java:115]:
```suggestion
    throw ErrorCreator.createError(StringUtils.fromString("Failed to parse regular expression: " + e.getMessage() 
                    + " in '" + regExpStr));
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/RegExpFactory.java [hunk 2]
```diff
@@ -124,7 +124,8 @@ public static void parseInsertion(String regExpStr) {
             treeBuilder.parseInsertion();
         } catch (BallerinaException e) {
             throw ErrorCreator.createError(BallerinaErrorReasons.REG_EXP_PARSING_ERROR,
-                    StringUtils.fromString("Invalid insertion in regular expression: " + e.getMessage()));
+                    StringUtils.fromString(e.getMessage() + " in insertion substring '"
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/RegExpFactory.java:127]: Pass the original pattern here and use it in the error msg. 
What was the reason for wrapping the inclusion inside a non-capturing group?

Comment (LakshanWeerasinghe) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/RegExpFactory.java:127]: We do not have the original full pattern. We only have the inclusion part.

Comment (LakshanWeerasinghe) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/RegExpFactory.java:127]: AFIK, an inclusion should be in a place where it is a `ReDisjunction`. In a non-capturing group there is a `ReDisjunction` part after the colon. That's why we have modeled it in that way.

File: langlib/langlib-test/src/test/resources/test-src/regexp_test.bal [hunk 3]
```diff
@@ -1266,6 +1280,231 @@ function testRuntimeRegexpParser() {
...
+
+function testRegexpInterpolationNegative() {
+    string pattern1 = "(ABC)+\\k";
+    string:RegExp|error reg1 = trap re `${pattern1}`;
+    assertTrue(reg1 is error);
+    if (reg1 is error) {
+        assertEquality("{ballerina}RegularExpressionParsingError", reg1.message());
+        assertEquality("invalid character 'k' after backslash in insertion substring '(ABC)+\\k'", 
+            <string>checkpanic reg1.detail()["message"]);
+    }
```
Comment (sanjana) [inline langlib/langlib-test/src/test/resources/test-src/regexp_test.bal:1361]: Wouldn't it better to use it like this? 
In other relevant places as well.
```suggestion
    assertEquality("{ballerina}RegularExpressionParsingError", (<error>reg1).message());
    assertEquality("invalid character 'k' after backslash in insertion substring '(ABC)+\\k'", 
        <string>checkpanic (<error>reg1).detail()["message"]);
```

**Review by sanjana — COMMENTED** [review]
Check if this would be possible.

**Comment by pcnfernando** [comment]
@LakshanWeerasinghe there's a conflict

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java [hunk 4]
```diff
@@ -197,6 +259,28 @@ private String readRegUnicodeGeneralCategory() {
...
+     *
+     * @return '}' character
+     */
+    private String readCloseBrace() {
+        try {
+            Token nextToken = peek();
+            if (nextToken.kind == TokenKind.CLOSE_BRACE_TOKEN) {
+                return consume().value;
+            }
+        } catch (BallerinaException ignored) {
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:273]: Since we are ignoring the exception here, the actual reason will be hidden and will be hard to debug when an issue arises, isn't it?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java [hunk 5]
```diff
@@ -268,7 +359,15 @@ private RegExpCharSet readCharSetNoDash(Token nextToken) {
         if (nextToken.kind == TokenKind.MINUS_TOKEN) {
             Token minus = consume();
             nextToken = peek();
+            if (isCharacterClassEnd(nextToken.kind)) {
+                return new RegExpCharSet(new Object[]{startReCharSetAtomNoDash, minus.value});
+            }
             String rhsReCharSetAtom = readCharSetAtom(nextToken);
+            if (isIncorrectCharRange(startReCharSetAtomNoDash, rhsReCharSetAtom)) {
+                throw new BallerinaException(BLangExceptionHelper.getErrorMessage(
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:367]: Add a test to validate the range error being thrown

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java [hunk 6]
```diff
@@ -279,11 +378,24 @@ private RegExpCharSet readCharSetNoDash(Token nextToken) {
...
+                if (token.kind == TokenKind.MINUS_TOKEN) {
+                    return consume().value + consume().value;
+                }
+                return readRegEscape(consume());
+            default:
+                Token next = peek();
+                if (isReCharSetLiteralChar(next.value)) {
+                    return consume().value;
+                }
+                throw new BallerinaException(getErrorMsg(next));
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:397]: Cover this invalid character case adding a test

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java [hunk 7]
```diff
@@ -292,7 +404,21 @@ private String readCharacterClassEnd() {
...
+    private RegExpQuantifier readOptionalQuantifier() {
+        Token nextToken = peek();
+        switch (nextToken.kind) {
+            case QUESTION_MARK_TOKEN:
+            case ASTERISK_TOKEN:
+            case PLUS_TOKEN:
+            case OPEN_BRACE_TOKEN:
+                return readReQuantifier();
+            default:
+                return new RegExpQuantifier("", "");
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:420]: Why we have to return a default case here?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java [hunk 8]
```diff
@@ -446,6 +568,17 @@ private boolean isCharacterClassEnd(TokenKind kind) {
         }
     }
 
+    private boolean isReCharSetLiteralChar(String tokenText) {
+        switch (tokenText) {
+            case "\\":
+            case "-":
+            case "]":
+                return false;
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:576]: Add a test to cover this

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java (hunk 4 above)
Comment (LakshanWeerasinghe) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:273]: Yes. I'll refactor the method.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java (hunk 7 above)
Comment (LakshanWeerasinghe) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:420]: For cases where we do not have quantifier.

The return of this method is used to create a `ReAtomQuantifier`. We need to have a empty string if there is no quantifier present. Returning a null won't help. So that I have return `RegExpQuanifier` with empty value.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java (hunk 4 above)
Comment (LakshanWeerasinghe) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:273]: Yes. But since this is runtime parsing I think it is ok to ignore that error an throw the `missing close brace token error`.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java [hunk 9]
```diff
@@ -106,22 +132,16 @@ private RegExpTerm readRegTerm() {
                 reAtom = readRegCapturingGroups();
                 break;
             default:
-                // Read chars in ReLiteralChar, . or ReEscape.
-                reAtom = readRegChars();
+                // Here the token is a syntax char, which is invalid. A syntax char should have a backslash prior
+                // to the token.
```
Comment (sanjana) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:136]: What if this could be re-written as this?
```suggestion
                // Here the token is a syntax char, which is invalid. Syntax char tokens should be 
                // preceded by backslashes.
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java [hunk 10]
```diff
@@ -182,6 +243,11 @@ private String readRegUnicodeScript() {
         throw new BallerinaException(getErrorMsg(nextToken));
     }
 
+    /**
+     * Read the unicode general category.
+     *
+     * @return gc=category or category
```
Comment (sanjana) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:249]: Is this dock comment correct?

Comment (SasinduDilshara) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:249]:
```suggestion
     * @return gc=category
```

Comment (SasinduDilshara) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:249]: or else
`gc=general category`

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java (hunk 7 above)
Comment (SasinduDilshara) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:437]: Can't we return null in here and handle the null value, in the upper layers

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java [hunk 11]
```diff
@@ -130,7 +130,23 @@ public enum RuntimeErrors implements DiagnosticCode {
...
+    REGEXP_MISSING_CLOSE_BRACKET("regexp.missing.close.bracket", "RUNTIME_0111"),
+    REGEXP_INVALID_CHAR_CLASS_RANGE("regexp.invalid.char.class.range", "RUNTIME_0112"),
+    REGEXP_INVALID_FLAG("regexp.invalid.flag", "RUNTIME_0113"),
+    REGEXP_DUPLICATE_FLAG("regexp.duplicate.flag", "RUNTIME_0114"),
+    REGEXP_INVALID_END_CHARACTER("regexp.invalid.end.character", "RUNTIME_0115"),
+    REGEXP_INVALID_CHARACTER("regexp.invalid.character", "RUNTIME_0116"),
+    REGEXP_INVALID_UNICODE_GENERAL_CATEGORY_VALUE("regexp.invalid.unicode.general.category.value", "RUNTIME_0117"),
+    REGEXP_INVALID_UNICODE_PROPERTY_VALUE("regexp.invalid.unicode.property.value", "RUNTIME_0118"),
+    REGEXP_EMPTY_CHARACTER_CLASS_DISALLOWED("regexp.empty.character.class.disallowed", "RUNTIME_0119");
+
```
Comment (SasinduDilshara) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/util/exceptions/RuntimeErrors.java:148]: Can remove these new lines

File: bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties [hunk 12]
```diff
@@ -245,3 +245,17 @@ invalid.utf8.byte.array.value = array contains invalid UTF-8 byte value
 regexp.match.string.negative.index = start index cannot be less than 0
 regexp.match.string.index.out.of.range = start index ''{0}'' cannot be greater than input string length ''{1}''
 regexp.invalid.pattern = invalid regexp pattern: {0}
+regexp.missing.backslash = missing backslash before ''{0}'' token
+regexp.invalid.char.after.backslash = invalid character ''{0}'' after backslash
+regexp.missing.open.brace = missing open brace '''{''' token
```
Comment (SasinduDilshara) [inline bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties:250]: isn't this `''{'' ?

File: langlib/langlib-test/src/test/resources/test-src/regexp_test.bal [hunk 13]
```diff
@@ -1311,6 +1325,313 @@ function testTranslatingDiffNodesInCharClass() {
...
+        <string>checkpanic (<error>reg16).detail()["message"]);
+
+    string pattern17 = "(?im-s:abc";
+    string:RegExp|error reg17 = trap re `${pattern17}`;
+    assertTrue(reg17 is error);
+    assertEquality("{ballerina}RegularExpressionParsingError", (<error>reg17).message());
+    assertEquality("missing close parenthesis ')' token in insertion substring '(?im-s:abc'", 
+        <string>checkpanic (<error>reg17).detail()["message"]);
+    
+    string pattern18 = "\\p";
```
Comment (SasinduDilshara) [inline langlib/langlib-test/src/test/resources/test-src/regexp_test.bal:1518]: Lets add one test with module level defined string value

File: langlib/langlib-test/src/test/resources/test-src/regexp_test.bal [hunk 14]
```diff
@@ -1311,6 +1325,313 @@ function testTranslatingDiffNodesInCharClass() {
...
+    assertTrue(reg23 is error);
+    assertEquality("{ballerina}RegularExpressionParsingError", (<error>reg23).message());
+    assertEquality("invalid character class range 'Z'-'A' in insertion substring 'abc[a-zZ-A]'", 
+        <string>checkpanic (<error>reg23).detail()["message"]);             
+}
+
+function testCharClassesWithMultipleRangesAndAtoms() returns error? {
+    string:RegExp pattern1 = check regexp:fromString("[a-zA-Z0-9]");
+    assertTrue(pattern1 is string:RegExp);
+    if (pattern1 is string:RegExp) {
```
Comment (SasinduDilshara) [inline langlib/langlib-test/src/test/resources/test-src/regexp_test.bal:1564]: We can remove this check and use a cast, because we check the assertion in L1563

File: langlib/langlib-test/src/test/resources/test-src/regexp_test.bal [hunk 15]
```diff
@@ -1311,6 +1325,313 @@ function testTranslatingDiffNodesInCharClass() {
...
+    assertEquality("a", (<regexp:Span>res7).substring());
+    
+    string:RegExp pattern8 = check regexp:fromString("[\\s]");
+    assertTrue(pattern8 is string:RegExp);
+    if (pattern8 is string:RegExp) {
+        assertTrue(re `[\s]` == pattern8);
+    }
+    regexp:Span? res8 = pattern8.find("abc ");
+    assertTrue(res8 is regexp:Span);
+    assertEquality(" ", (<regexp:Span>res8).substring());
```
Comment (SasinduDilshara) [inline langlib/langlib-test/src/test/resources/test-src/regexp_test.bal:1632]: Lets add a test with unicode property with string if it is posible.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java (hunk 10 above)
Comment (LakshanWeerasinghe) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:249]: This is correct. Lets say we are parsing pattern like `\p{gc=L}` this will return `gc=L`. And if we are parsing a pattern like `\p{L} this will return `L`.

Comment (LakshanWeerasinghe) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:249]: Refer [#commet](https://github.com/ballerina-platform/ballerina-lang/pull/40003#discussion_r1193165349)

File: bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties (hunk 12 above)
Comment (LakshanWeerasinghe) [reply bvm/ballerina-runtime/src/main/resources/MessagesBundle.properties:250]: No. `{` has special meaning.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java (hunk 10 above)
Comment (SasinduDilshara) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:249]: I think both me and @sanjana are suggesting to make that more clear.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java (hunk 7 above)
Comment (LakshanWeerasinghe) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java:437]: Yes, we can. I'll change.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java (hunk 10 above)
Comment (LakshanWeerasinghe) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java]: Fixed.

**Review by SasinduDilshara — APPROVED** [review]

**Comment by SasinduDilshara** [comment]
LGTM

**Review by sanjana — APPROVED** [review]

**Review by pcnfernando — APPROVED** [review]
