### PR TITLE
Fix the error on auth failure in the WebSocket

### LINKED ISSUE #24589: [WebSocket] Error on auth failure
**Description:**
$title, with an HTTP to WebSocket upgrade.

**Steps to reproduce:**

Server
```ballerina
import ballerina/auth;
import ballerina/http;
import ballerina/io;
import ballerina/log;

http:BasicAuthHandler inboundBasicAuthHandler = new (new auth:InboundBasicAuthProvider());

listener http:Listener ln = new (9090, config = {
    auth: {
        authHandlers: [inboundBasicAuthHandler],
        mandateSecureSocket: false
    }
});

service foo on ln {
    @http:ResourceConfig {
        webSocketUpgrade: {
            upgradePath: "/ws",
            upgradeService: wsService
        }
    }
    resource function upgrader(http:Caller caller, http:Request req) {
        log:printInfo("WS upgrade resource");
    }
}
service wsService = @http:WebSocketServiceConfig {} service {    
    
    resource function onOpen(http:WebSocketCaller caller) {
        io:println("onOpen: " + caller.getConnectionId());
    } 
    
    resource function onClose(http:WebSocketCaller caller,int statusCode,string reason) {
        io:println("onClose: " + caller.getConnectionId());
    }
};
```

```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
Running executables

[ballerina/http] started HTTP/WS listener 0.0.0.0:9090
Couldn't complete outbound response
        at ballerina.http.1_0_0:nativeRespond(http_connection.bal:247)
           ballerina.http.1_0_0.Caller:respond(http_connection.bal:56)
           ballerina.http.1_0_0.auth.authn_filter:isAuthnSuccessful(auth/authn_filter.bal:107)
           ballerina.http.1_0_0.AuthnFilter:filterRequest(auth/authn_filter.bal:49)
           $value$foo__service_0:upgrader(qwe.bal:16)
^C[ballerina/http] stopped HTTP/WS listener 0.0.0.0:9090
```

Client
```ballerina
import ballerina/auth;
import ballerina/http;
import ballerina/io;

public function main() {
    auth:OutboundBasicAuthProvider outboundBasicAuthProvider = new ({
            username: "jo",
            password: "1234"
    });

    string token = checkpanic outboundBasicAuthProvider.generateToken();

    http:BasicAuthHandler outboundBasicAuthHandler = new (<auth:OutboundBasicAuthProvider> outboundBasicAuthProvider);
    
    http:OutboundAuthConfig auth = {
        authHandler: outboundBasicAuthHandler
    };

    http:WebSocketClient wsClient = new ("ws://localhost:9090/foo/ws", 
                                            config = {
                                                callbackService: ClientService,
                                                customHeaders: {
                                                    [http:AUTH_HEADER]: string `Basic ${token}`
                                                }
                                            }
                                        );
}

service ClientService = @http:WebSocketServiceConfig {} service {
    resource function onText(http:WebSocketClient conn, string text, boolean finalFrame) {
        io:println(text);
    }
    resource function onError(http:WebSocketClient conn, error err) {
        io:println(err);
    }
};
```

**Affected Versions:**
1.2.4, slp1

### PR DESCRIPTION
**Pull request by kalaiyarasiganeshalingam**
## Purpose
$Subject

Fixes #24589

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketConstants.java [hunk 1]
```diff
@@ -72,6 +72,7 @@
     public static final String RESOURCE_NAME_UPGRADE = "upgrade";
 
     public static final String WEBSOCKET_HANDSHAKER = "WEBSOCKET_MESSAGE";
+    public static final String MESSAGE_DATA_SOURCE = "message_datasource";
```
Comment (daneshk) [inline stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketConstants.java:75]: What is this `message_datasource` for?

File: stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java [hunk 2]
```diff
@@ -108,14 +113,30 @@ public static Object nativeRespond(ObjectValue connectionObj, ObjectValue outbou
             }
         } catch (ErrorValue e) {
             unBlockStrand(strand);
-            log.debug(e.getPrintableStackTrace(), e);
-            return e;
+            if (log.isDebugEnabled()) {
+                log.debug(e.getPrintableStackTrace(), e);
```
Comment (daneshk) [inline stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java:117]: Shall we have a meaningful message instead of `e.getPrintableStackTrace()`, since it is there in the `e`

File: stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketConstants.java (hunk 1 above)
Comment (kalaiyarasiganeshalingam) [reply stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketConstants.java:75]: In the entity, the payload is set by the `message_datasource` key as native data. So, I use it to [get the response's payload](https://github.com/ballerina-platform/ballerina-lang/pull/24843/files#diff-c36bff13846589a8cf5f4454fff28d25R167) from the entity.

File: stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java [hunk 3]
```diff
@@ -108,14 +113,30 @@ public static Object nativeRespond(ObjectValue connectionObj, ObjectValue outbou
...
-            //Exception is already notified by http transport.
-            String errorMessage = "Couldn't complete outbound response";
-            log.debug(errorMessage, e);
-            return HttpUtil.createHttpError(errorMessage, HttpErrorType.GENERIC_LISTENER_ERROR);
+            String errorMessage = "";
+            if (connectionObj.getNativeData(WebSocketConstants.WEBSOCKET_HANDSHAKER) != null) {
+                if (log.isDebugEnabled()) {
+                    log.debug(message, e);
+                }
+                throw getWebSocketException(outboundResponseObj);
```
Comment (chamil321) [inline stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java:131]: Throwing WebSocket exception during the HTTP flow seems incorrect. Still, the upgrade has not happed to WebSocket and this is a response flow to the HTTP request. 401 should go to the client without an exception thrown IMO

Comment (kalaiyarasiganeshalingam) [reply stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java:131]: According to the current implementation, Success and Errors are handled by [OnUpgradeResourceCallback](https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/server/OnUpgradeResourceCallback.java) during the Websocket upgrade connection. So If we will throw the exception, `OnError` can handle that.

File: stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketUtil.java [hunk 4]
```diff
@@ -578,7 +578,7 @@ public static void countDownForHandshake(ObjectValue webSocketClient) {
     public static WebSocketException getWebSocketException(String msg, Throwable throwable, String errorCode,
                                                            ErrorValue cause) {
         WebSocketException exception;
-        String message = errorCode.substring(2) + ": " + msg;
+        String message = "[" + errorCode.substring(2) + "] " + msg;
```
[the remark this answers is not in the document]
Comment (kalaiyarasiganeshalingam) [reply stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketUtil.java:581]: At some places,  colon comes in more than once places. I thought that it is not a good format. So, I have changed it to the bracket. 

- https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/CookieTest.java#L56
- https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/ClientErrorsTest.java#L74

File: stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java [hunk 5]
```diff
@@ -108,14 +113,30 @@ public static Object nativeRespond(ObjectValue connectionObj, ObjectValue outbou
...
             unBlockStrand(strand);
-            log.debug(e.getPrintableStackTrace(), e);
-            return e;
+            if (log.isDebugEnabled()) {
+                log.debug(e.getPrintableStackTrace(), e);
+            }
+            if (connectionObj.getNativeData(WebSocketConstants.WEBSOCKET_HANDSHAKER) != null) {
+                throw getWebSocketException(outboundResponseObj);
+            } else {
+                return e;
```
Comment (niveathika) [inline stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java:122]: Is there a specific use case when `connectionObj.getNativeData(WebSocketConstants.WEBSOCKET_HANDSHAKER)` can be null?

Comment (kalaiyarasiganeshalingam) [reply stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java:122]: Yes. That is indicated this is not a request of the http Websocket upgrade.

File: stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java [hunk 6]
```diff
@@ -108,14 +113,30 @@ public static Object nativeRespond(ObjectValue connectionObj, ObjectValue outbou
...
+            }
```
Comment (niveathika) [inline stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java:123]: TWe dont usually return Exceptions. Use throw. Also add a comment for the specific null check
```suggestion
            if (connectionObj.getNativeData(WebSocketConstants.WEBSOCKET_HANDSHAKER) != null) {
                throw getWebSocketException(outboundResponseObj);
            } 
             throw e;
```

File: stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java (hunk 3 above)
Comment (chamil321) [reply stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java:131]: Had a call with @kalaiyarasiganeshalingam and cleared the flow. (Ignore the above comment)

It seems like from the Auth filter an HTTP response(401) is sent to the WSClient instead of WebSocket response. 
IMO at AuthFilter level, this should be handled not in the Respond method. If the Auth filter can identify the WebSocket upgrade request and respond appropriately then this exception will not have occurred. 

@ldclakmal @daneshk WDYT?

Comment (ldclakmal) [reply stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java:131]: In HTTP filter level, I don't think we have a way to identify whether this is an WS upgrade request. IMO, the transport pipeline should get updated to WS after authentication filters. Then we can simply respond (HTTP responses) with 401 or 403. Seems like, here the transport get updated before engaging filters. Shall we schedule a meeting and discuss this? WDYT?

Comment (daneshk) [reply stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java:131]: +1 Let's have a meeting and discuss

File: stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java (hunk 2 above)
Comment (kalaiyarasiganeshalingam) [reply stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java]: These changes have been reverted in #a30ea6fe66758a2e7ed37f42d6754be0cf37e8c5

File: stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketUtil.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (kalaiyarasiganeshalingam) [reply stdlib/http/src/main/java/org/ballerinalang/net/http/websocket/WebSocketUtil.java]: These changes have been reverted in #a30ea6fe66758a2e7ed37f42d6754be0cf37e8c5

File: stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java [hunk 7]
```diff
@@ -108,14 +113,30 @@ public static Object nativeRespond(ObjectValue connectionObj, ObjectValue outbou
             }
         } catch (ErrorValue e) {
             unBlockStrand(strand);
-            log.debug(e.getPrintableStackTrace(), e);
-            return e;
+            if (log.isDebugEnabled()) {
```
[the remark this answers is not in the document]
Comment (kalaiyarasiganeshalingam) [reply stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java]: These changes have been reverted in #a30ea6fe66758a2e7ed37f42d6754be0cf37e8c5

File: stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java (hunk 6 above)
Comment (kalaiyarasiganeshalingam) [reply stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/connection/Respond.java]: These changes have been reverted in #a30ea6fe66758a2e7ed37f42d6754be0cf37e8c5

File: stdlib/http/src/main/ballerina/src/http/auth/utils.bal [hunk 8]
```diff
@@ -252,6 +252,22 @@ function getResourceAuthConfig(FilterContext context) returns ResourceAuth? {
     }
 }
 
+# Checks whether the `ResourceConfig` has `WebSocketUpgradeConfig` or not.
```
Comment (ldclakmal) [inline stdlib/http/src/main/ballerina/src/http/auth/utils.bal:255]:
```suggestion
# Checks whether the `http:ResourceConfig` has `http:WebSocketUpgradeConfig` or not.
```

File: stdlib/http/src/main/ballerina/src/http/auth/utils.bal [hunk 9]
```diff
@@ -252,6 +252,22 @@ function getResourceAuthConfig(FilterContext context) returns ResourceAuth? {
     }
 }
 
+# Checks whether the `http:ResourceConfig` has `http:WebSocketUpgradeConfig` or not.
+#
+# + context - The `FilterContext` instance
+# + return - Whether the `ResourceConfig` has `WebSocketUpgradeConfig` or not
```
Comment (ldclakmal) [inline stdlib/http/src/main/ballerina/src/http/auth/utils.bal:258]:
```suggestion
# + return - Whether the `http:ResourceConfig` has `http:WebSocketUpgradeConfig` or not
```

File: tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/40_authanticateServer.bal [hunk 10]
```diff
@@ -0,0 +1,58 @@
...
+// KIND, either express or implied.  See the License for the
+// specific language governing permissions and limitations
+// under the License.
+
+import ballerina/auth;
+import ballerina/http;
+import ballerina/io;
+import ballerina/log;
+
+http:BasicAuthHandler inboundBasicAuthHandler = new (new auth:InboundBasicAuthProvider({ tableName: "b7a.users" }));
```
Comment (ldclakmal) [inline tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/40_authanticateServer.bal:22]:
```suggestion
http:BasicAuthHandler inboundBasicAuthHandler = new (new auth:InboundBasicAuthProvider());
```

File: tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/39_authentication.bal [hunk 11]
```diff
@@ -0,0 +1,56 @@
+// Copyright (c) 2020 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (ldclakmal) [inline tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/39_authentication.bal:1]: Shall we rename the file as `39_authentication_success_client.bal`?

File: tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/40_authanticateServer.bal [hunk 12]
```diff
@@ -0,0 +1,58 @@
+// Copyright (c) 2020 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (ldclakmal) [inline tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/40_authanticateServer.bal:1]: Shall we rename the file as `40_authentication_success_server.bal`

File: tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/42_unauthentication_client.bal [hunk 13]
```diff
@@ -0,0 +1,50 @@
+// Copyright (c) 2020 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (ldclakmal) [inline tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/42_unauthentication_client.bal:1]: Shall we rename the file as `41_authentication_failure_client.bal`

File: tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/41_unauthenticate_server.bal [hunk 14]
```diff
@@ -0,0 +1,51 @@
+// Copyright (c) 2020 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (ldclakmal) [inline tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/41_unauthenticate_server.bal:1]: Shall we rename the file as `42_authentication_failure_server.bal`

File: tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/41_unauthenticate_server.bal [hunk 15]
```diff
@@ -0,0 +1,51 @@
...
+// under the License.
+
+import ballerina/auth;
+import ballerina/http;
+import ballerina/io;
+import ballerina/log;
+
+http:BasicAuthHandler basicAuthHandler = new (new auth:InboundBasicAuthProvider());
+
+listener http:Listener httpServ = new (21041, config = {
```
Comment (ldclakmal) [inline tests/jballerina-integration-test/src/test/resources/websocket/src/wsservices/41_unauthenticate_server.bal:24]: Let's switch the port 21041 and 21042 with client and server, in order to match with file name ordering as well.

File: tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/AuthenticationTest.java [hunk 16]
```diff
@@ -0,0 +1,61 @@
...
+ */
+@Test(groups = {"websocket-test"})
+public class AuthenticationTest {
+
+    private WebSocketTestClient client;
+    private LogLeecher logLeecher;
+    String expectingErrorLog;
+
+    @Test(description = "Tests with correct credential")
+    public void testBasicAuthentication() throws URISyntaxException, InterruptedException, BallerinaTestException {
```
Comment (ldclakmal) [inline tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/AuthenticationTest.java:40]:
```suggestion
    public void testBasicAuthenticationSuccess() throws URISyntaxException, InterruptedException, BallerinaTestException {
```

File: tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/AuthenticationTest.java [hunk 17]
```diff
@@ -0,0 +1,61 @@
...
+        logLeecher = new LogLeecher(expectingErrorLog);
+        WebSocketTestCommons.serverInstance.addLogLeecher(logLeecher);
+        client = new WebSocketTestClient("ws://localhost:21039");
+        client.handshake();
+        logLeecher.waitForText(WebSocketTestCommons.TIMEOUT_IN_SECS * 1000);
+        client.shutDown();
+    }
+
+    @Test(description = "Tests with wrong credential")
+    public void negativeTestcase() throws URISyntaxException, InterruptedException, BallerinaTestException {
```
Comment (ldclakmal) [inline tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/service/websocket/AuthenticationTest.java:51]:
```suggestion
    public void testBasicAuthenticationFailure() throws URISyntaxException, InterruptedException, BallerinaTestException {
```

File: stdlib/http/src/main/ballerina/src/http/auth/utils.bal [hunk 18]
```diff
@@ -252,6 +252,22 @@ function getResourceAuthConfig(FilterContext context) returns ResourceAuth? {
...
 }
 
+# Checks whether the `http:ResourceConfig` has `http:WebSocketUpgradeConfig` or not.
+#
+# + context - The `FilterContext` instance
+# + return - Whether the `http:ResourceConfig` has `http:WebSocketUpgradeConfig` or not
+function isWebSocketUpgradeRequest(FilterContext context) returns boolean {
+    any annData = reflect:getResourceAnnotations(context.getService(), context.getResourceName(), RESOURCE_ANN_NAME,
+                                                 ANN_MODULE);
+    if (!(annData is ())) {
```
Comment (chamil321) [inline stdlib/http/src/main/ballerina/src/http/auth/utils.bal:262]: Shall we check the nilable `annData` and do an early return?
```suggestion
    if (annData is ()) {
        return false;
    }
```
