### PR TITLE
[2201.3.x] Fix hint for native build 

### LINKED ISSUE #39243: [Improvement]: Hint given for graalvm installation can be improved
### Description

Current output: 
```
$ bal build --native
WARNING: GraalVM Native Image generation in Ballerina is an experimental feature
Compiling source
	user/diagFix:0.1.0

Generating executable with Native image
error: GraalVM installation directory not found. Set GRAALVM_HOME as an environment variable
HINT: to install GraalVM follow the below link
https://ballerina.io/learn/build-a-native-executable/#configure-graalvm
```
We can improve the hint as follows:
```
HINT: To install GraalVM, follow the link: https://ballerina.io/learn/build-a-native-executable/#configure-graalvm
```

### Affected Version(s)
2201.3.2

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
Fixes #39243

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java [hunk 1]
```diff
@@ -548,7 +548,7 @@ private Path emitGraalExecutable(Path executableFilePath) {
 
         if (nativeImageCommand == null) {
             throw new ProjectException("GraalVM installation directory not found. Set GRAALVM_HOME as an " +
-                    "environment variable\nHINT: to install GraalVM follow the below link\n" +
+                    "environment variable\nHHINT: To install GraalVM, follow the link: " +
```
Comment (gayaldassanayake) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java:551]:
```suggestion
                    "environment variable\nHINT: To install GraalVM, follow the link: " +
```

**Review by gayaldassanayake — APPROVED** [review]

**Review by Dilhasha — APPROVED** [review]

**Review by Dilhasha — APPROVED** [review]
