### PR TITLE
Fix issue in parseing invalid identifier escape sequence

### LINKED ISSUE #32230: Invalid string escape sequence gives incorrect error message
**Description:**
```bal
public function main() {
    string b = "\Ballerina"; // @error <invalid escape sequence '\B'>
}
```
Gives `invalid escape sequence '\a'` expected `invalid escape sequence '\B'`

**Affected Versions:**
SLBeta2

### LINKED ISSUE #32369: Parser Error Handler in a never ending loop
**Description:**
LS became unresponsive while I was editing the following source code in a multi-module project. I analyzed two subsequent thread dumps. There is a thread running over 222 seconds which causes the unresponsiveness. Please find the thread dumps below. 

```ballerina
import ballerina/http;

type PET record {
    string id;
    string name;
    boolean isAvailable;
};

configurable int port = 8080;
configurable string host = "localhost";

//new expressions default values are not added.
//named argument support not provided.
listener http:Listener petStoreListner = new(port,config={host:host});

service / on petStoreListner {
    private map<Pe<cursor>
    resource function get pet/[string petId]() returns @http:Payload PET | http:BadRequest | http:NotFound {
        
    }
}

var a = myF(a=10,b=20);

function myF(int a, int b) {

}

```

Thread dump 1
tdump1

https://drive.google.com/file/d/11Qj4A2BWTtUJLBE2LppcqIL8KW3ZVcmD/view?usp=sharing

Thread dump 2
tdump2

https://drive.google.com/file/d/11Qj4A2BWTtUJLBE2LppcqIL8KW3ZVcmD/view?usp=sharing

The CPU and Memory usage is normal.
cpu

memory

**Steps to reproduce:**
Try editing the about source code around the indicated cursor position.

**Affected Versions:**
slbeta3 & slbeta4-SNAPSHOT

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$title
For the sample 
```bal
function foo() {
     int \
}
```
Ballerina lexer continues to produce empty identifier tokens which will result in an infinite loop.

Fixes #32369
Fixes #32230

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java [hunk 1]
```diff
@@ -1421,6 +1421,8 @@ private void processIdentifierEnd() {
                 case LexerTerminals.NEWLINE:
                 case LexerTerminals.CARRIAGE_RETURN:
                 case LexerTerminals.TAB:
+                    reader.advance();
+                    reportInvalidEscapeSequence((char) 0);
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java:1425]: The error msg shown to the user should be  `invalid escape sequence '\'`
```suggestion
                    reportLexerError(DiagnosticErrorCode.ERROR_INVALID_ESCAPE_SEQUENCE, "");
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/identifier-literal-wrong-character-negative.bal [hunk 2]
```diff
@@ -1,6 +1,7 @@
 
 function getGlobalVarWithIL() returns string {
     string 'global\ var" = "dfs";
+    int \
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/identifier-literal-wrong-character-negative.bal:4]: Shall we add this as a  parser test as well. since the issue is related to the tokenizing?

**Review by lochana-chathura — COMMENTED** [review]
We have similar identifier processing logic at the documentation lexer as well. Shall we fix that too? https://github.com/ballerina-platform/ballerina-lang/blob/1453bf0126d1cba49c125fbf38763b000b77abfc/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/DocumentationLexer.java#L157

Sample:
```bal
# Hey `\
function foo() {
}
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java (hunk 1 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java:1425]: Will update the documentation lexer. Here `reportInvalidEscapeSequence((char) 0);` gives the expected error right?

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java:1425]: Following is from the test case we have added. 
`BAssertUtil.validateError(resultNeg, i++, "invalid escape sequence '\\\u0000'", 4, 9);`

That string is displayed as below in IntelliJ
Screenshot from 2021-09-13 14-43-53

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java:1425]: Will update

**Comment by mohanvive** [comment]
If this PR is finalised, shall we add it to beta-03 release branch as well?

**Comment by rdulmina** [comment]
> If this PR is finalised, shall we add it to beta-03 release branch as well?
> @rdulmina @lochana-chathura

+1 will update ASAP

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/identifier-literal-wrong-character-negative.bal (hunk 2 above)
Comment (rdulmina) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/identifierliteral/identifier-literal-wrong-character-negative.bal:4]: Added

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java (hunk 1 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java]: Updated

**Review by lochana-chathura — APPROVED** [review]

**Review by hasithaa — APPROVED** [review]
