### PR TITLE
Invalidate the environment in project when the compiler crashes

### LINKED ISSUE #36231: Redesign the compiler context to handle compiler crashes
**Description:**
$subject

Related Issue: https://github.com/ballerina-platform/ballerina-lang/issues/35158

### PR DESCRIPTION
**Pull request by azinneera**
Fixes #36231

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java [hunk 1]
```diff
@@ -212,6 +214,19 @@ ModuleCompilation getModuleCompilation(ModuleContext moduleContext) {
     PackageCompilation getPackageCompilation() {
         if (packageCompilation == null) {
             packageCompilation = PackageCompilation.from(this, this.compilationOptions());
+            
+            // Check if the compiler crashed
+            Collection<Diagnostic> errors = packageCompilation.diagnosticResult().errors();
+            if (errors != null) {
```
Comment (sameerajayasoma) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java:220]: Is this null check required?

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/Project.java [hunk 2]
```diff
@@ -87,6 +92,11 @@ protected void setCurrentPackage(Package currentPackage) {
     }
 
     public ProjectEnvironment projectEnvironmentContext() {
```
Comment (sameerajayasoma) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/Project.java:94]: How do we ensure that this method is invoked right after a compiler crash? 

There can be places where we have cached compilerContext instances. If that's the case, then we will end up having multiple stale instances of compilerContext objects.

**Review by sameerajayasoma — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java (hunk 1 above)
Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java:220]: Yes, the diagnostics in `PackageManifest` are added without a code. 
https://github.com/ballerina-platform/ballerina-lang/blob/4175b5491ca992402a9ff93a47db3899ad7acb31/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ManifestBuilder.java#L438

Will create a separate issue to address that.

Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java:220]: Yes, the diagnostics in `PackageManifest` are added without a code. 
https://github.com/ballerina-platform/ballerina-lang/blob/4175b5491ca992402a9ff93a47db3899ad7acb31/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ManifestBuilder.java#L438

Will create a separate issue to address that.

Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageContext.java]: We can remove it.

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/Project.java (hunk 2 above)
Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/Project.java]: Refactored the implementation as follows:
* Removed the crash recovery part from the Project API (which was added in the initial commit)
* Improved `Project.clearCaches` to reset the entire environment

The API user can call the `Project.clearCaches` method when there is a crash.
