### PR TITLE
Get generated keys only if supported by JDBC

### LINKED ISSUE #20673: HANA DB error for create/update statements - "Invalid argument autoGeneratedKeys"
**Description:**
SQL updates/create statements report an error when interfacing with sap HANA DB - "Invalid arguemnt autoGeneratedKeys". This is reproduced after being reported on slack.

**Steps to reproduce:**

1. CREATE
`CREATE TABLE student(id INT, age INT, name VARCHAR(255), insertedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP`

`Create student table failed: failed to execute update query: Invalid argument autoGeneratedKeys, use NO_GENERATED_KEYS..`

2. INSERT
`INSERT INTO student(age, name) values (?, ?)`

`Insert to student table with variable parameters failed: failed to execute update query: Invalid argument autoGeneratedKeys, use NO_GENERATED_KEYS..`

3. UPDATE statement
`UPDATE student set name = 'jane' WHERE age = ?`

`Update a row in student table failed: failed to execute update query: Invalid argument autoGeneratedKeys, use NO_GENERATED_KEYS..`

4. DELETE statement
`DELETE FROM student WHERE age = ?`

`Delete a row from student table failed: failed to execute update query: Invalid argument autoGeneratedKeys, use NO_GENERATED_KEYS..`

**Affected Versions:**
jBallerina 1.1.0
Language specification 2019R3
Ballerina tool 0.8.0

**OS, DB, other environment details and versions:**
macOS Catalina : v10.15.2(19C57) 
HANA DB : v2.00.040.00.1553674765 (HDB -v)

**Suggested Labels (optional):**
Area/StandardLibs, Component/Data, Type/Bug,

**Suggested Assignees (optional):**
KRVPerera

### PR DESCRIPTION
**Pull request by KRVPerera**
## Purpose
Prevent requesting generated keys from unsupported JDBC drivers.
Fixes #20673

## Approach
Getting generated keys from JDBC driver only if supported by JDBC
driver. This prevents exceptions for statements issued against HANA DB like databases where JDBC driver does not support returning generated keys.

## Remarks
Better to allow the user in the future to query whether the user expects to retrieve generated keys or not.

# Suggested Labels
Area/StandardLibs
Component/Data
Type/Bug 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java [hunk 1]
```diff
@@ -133,7 +136,21 @@ private boolean isDdlStatement() {
...
 
-    private enum DdlKeyword {
-        CREATE, ALTER, DROP, TRUNCATE, COMMENT, RENAME
+    private enum GenKeyStmt {
+        INSERT, DELETE, UPDATE, MERGE
+    }
+
+    /**
+     * Check if the statement is one of INSERT, DELETE, UPDATE or MERGE.
+     * Oracle support INSERT only but does not throw expection on others
```
Comment (anupama-pathirage) [inline stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java]:
```suggestion
     * Oracle support INSERT only but does not throw exception on others
```

File: stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java [hunk 2]
```diff
@@ -133,7 +136,21 @@ private boolean isDdlStatement() {
...
+     * IBM supports all
+     * HANA DB throws exception to all but can be guared by supportsGetGeneratedKeys
```
Comment (anupama-pathirage) [inline stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java]: Typo in `guared`?

File: stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java [hunk 3]
```diff
@@ -152,6 +152,9 @@ public BatchUpdateStatement(ObjectValue client, SQLDatasource datasource, String
     // If such other databases are identified they can be included here.
     // The name of the database is being checked because there is no way to identify through the API.
     private boolean isGeneratedKeyReturningSupported() {
+        if (!datasource.supportsGetGeneratedKeys()) {
+            return false;
+        }
         return !Constants.DatabaseNames.ORACLE.equals(datasource.getDatabaseProductName())
```
Comment (anupama-pathirage) [inline stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java]: Is there a possibility to remove the Check for Oracle and MSSQL server check below? As per the comment `The name of the database is being checked because there is no way to identify through the API.` it seems it was done without knowing the `Connection.getMetaData().supportsGetGeneratedKeys()` API method.

Comment (KRVPerera) [reply stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java]: No. "supportsGetGeneratedKeys" - function if true guarantees at least insert operation is supported. Others are vendor-specific. Oracle official driver returns true for this API but Oracle do not support key generation in the batch operations.

Comment (KRVPerera) [reply stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/BatchUpdateStatement.java]: Docs for supportsGetGeneratedKeys
https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html?is-external=true#supportsGetGeneratedKeys--

File: stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java (hunk 2 above)
Comment (KRVPerera) [reply stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java]: done

File: stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java (hunk 1 above)
Comment (KRVPerera) [reply stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/UpdateStatement.java]: done
