### PR TITLE
Fix JSON to record conversion name conflict

### LINKED ISSUE #38440: [Bug]: LS API to convert record to JSON does not work properly
### Description

Please refer $subject.

### Steps to Reproduce

I am trying to convert below json and create a record. I am giving Person as the name of the Record. (Note there's a nested field with same name).

```
{
    "person":{
        "id": 1001,
        "firstName": "Vinnie",
        "lastName": "Hickman"
    },
    "course": [
        {
            "id": "CS6002",
            "title": "Computation Structures",
            "credits": 4
        },
        {
            "id": "CS6003",
            "title": "Circuits and Electronics",
            "credits": 3
        },
        {
            "id": "CS6004",
            "title": "Signals and Systems",
            "credits": 3
        }
    ]
}
```

### Affected Version(s)

ballerina-2201.2.2

### OS, DB, other environment details and versions

_No response_

### Related area

-> Other Area

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by AzeemMuzammil**
Fixes #38440

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/json-to-record-converter/src/main/java/io/ballerina/jsonmapper/diagnostic/DiagnosticMessage.java [hunk 1]
```diff
@@ -84,4 +84,10 @@ public static DiagnosticMessage jsonToRecordConverter103(Object[] args) {
                 "There is no JSON entry could be found for the field name %s.",
                 DiagnosticSeverity.WARNING, args);
     }
+
+    public static DiagnosticMessage jsonToRecordConverter104(Object[] args) {
+        return new DiagnosticMessage("JSON_TO_RECORD_CONVERTER_104",
+                "Provided Record name is invalid. Please use a meaningful name.",
```
Comment (NipunaRanasinghe) [inline misc/json-to-record-converter/src/main/java/io/ballerina/jsonmapper/diagnostic/DiagnosticMessage.java:90]:
```suggestion
                "Provided record name '<RECORD_NAME>' conflicts with the other generated records. Consider providing a different name.",
```

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM

**Review by tharindulak — APPROVED** [review]

**Comment by tharindulak** [comment]
LGTM
