### PR TITLE
Resolve Testerina Runtime dependencies

### LINKED ISSUE #26261: [Testerina] Code coverage fails with Java 11
**Description:**
After the Java 11 migration, code coverage failed by giving the following error [1].

```sh
Exception in thread "main" java.lang.NoClassDefFoundError: org/jacoco/core/analysis/ICoverageVisitor
        at org.ballerinalang.test.runtime.CoverageMain.main(CoverageMain.java:46)
Caused by: java.lang.ClassNotFoundException: org.jacoco.core.analysis.ICoverageVisitor
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 1 more
error: error while generating test report

> Task :reflect-ballerina:ballerinaTest FAILED
```

[1] https://github.com/ballerina-platform/module-ballerina-reflect/runs/1224023198

**Steps to reproduce:**

Build this commit https://github.com/ballerina-platform/module-ballerina-reflect/tree/5ca48fc1b420e1ea7a0bb00600667770d73f6dad

```sh
$ ./gradlew clean build
```

**OS, DB, other environment details and versions:**
- macOS, Ubuntu
- Java 11
- SLP5

### PR DESCRIPTION
**Pull request by Ibaqu**
## Purpose
Resolve the Testerina runtime dependencies by manually referencing the required jar files in RunTestTask

Fixes #26261

## Approach
Add the Jar files to the `jballerina-tools/lib` folder in distribution. Reference the jars directly when adding dependencies for the code coverage. 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunTestsTask.java [hunk 1]
```diff
@@ -349,6 +349,18 @@ private int runTestSuit(Path jsonPath, BuildContext buildContext, HashSet<Path>
 
         String jacocoAgentJarPath = Paths.get(System.getProperty(BALLERINA_HOME)).resolve(BALLERINA_HOME_BRE)
                 .resolve(BALLERINA_HOME_LIB).resolve(TesterinaConstants.AGENT_FILE_NAME).toString();
+
+        Path jacocoCoreJarPath =  Paths.get(System.getProperty(BALLERINA_HOME)).resolve(BALLERINA_HOME_BRE)
```
Comment (Dilhasha) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunTestsTask.java:353]: Shall we move this set of dependency loading to a separate function?

Comment (Ibaqu) [reply cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunTestsTask.java]: Moved to separate functions

**Review by Dilhasha — APPROVED** [review]
LGTM

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java [hunk 2]
```diff
@@ -54,4 +54,12 @@
     public static final String REPORT_ZIP_NAME = REPORT_DIR_NAME + ".zip";
     public static final String REPORT_DATA_PLACEHOLDER = "__data__";
     public static final String FILE_PROTOCOL = "file://";
+
+    //Coverage dependencies
+    public static final String JACOCO_CORE_JAR = "org.jacoco.core-0.8.5.jar";
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java:59]: Can't we package into the testerina-runtime jar since its the only usage?

Comment (Ibaqu) [reply misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java:59]: When I try to package it into the testerina-runtime.jar, it breaks the module dependency that testerina-core has on testerina-runtime. 

Originally, the jar files were packed into testerina-runtime.jar using `dist` in the build.gradle file :`dist 'org.jacoco:org.jacoco.core:0.8.5'`. When reverting to this and building the distribution, the 'testerina-core' module fails to pick up 'testerina-runtime' module as a dependency and fails to compile.

**Review by azinneera — APPROVED** [review]
