### PR TITLE
Fix resolving return-type of a function which has a type-param

### LINKED ISSUE #36517: [Semantic API] Return type of functions are not resolved properly in `TypeParamResolver`
**Description:**
```ballerina
public isolated function iterator(map<Type> m) returns object {
    public isolated function next() returns record {|
        Type value;
    |}?;
} {
    MapIterator mapIterator = new(m);
    return mapIterator;
}
```
Here return type of the function `next()` is not resolved properly

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #36517

## Remarks
TASK
- https://github.com/ballerina-platform/ballerina-lang/issues/36519

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [x] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamResolver.java [hunk 1]
```diff
@@ -263,14 +263,31 @@ public BType visit(BTableType typeInSymbol, BType boundType) {
...
+        List<BType> newParamTypes = new ArrayList<>();
+        for (BType paramType : typeInSymbol.paramTypes) {
+            BType newType = resolve(paramType, boundType);
+            newParamTypes.add(newType);
+        }
+        BType newRestParamType = null;
+        if (typeInSymbol.restType != null) {
+            newRestParamType = resolve(typeInSymbol.restType, boundType);
+        }
+        BType newReturnType = null;
```
Comment (DamithaSenevirathne) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamResolver.java:275]: Also new line here ?

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamResolver.java [hunk 2]
```diff
@@ -263,14 +263,31 @@ public BType visit(BTableType typeInSymbol, BType boundType) {
...
+        if (typeInSymbol.retType != null) {
+            newReturnType = resolve(typeInSymbol.retType, boundType);
+        }
+        return new BInvokableType(newParamTypes, newRestParamType, newReturnType, typeInSymbol.tsymbol);
```
Comment (DamithaSenevirathne) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamResolver.java:279]: Shall we add a new line here as well ?

**Review by DamithaSenevirathne — APPROVED** [review]
LGTM
