### PR TITLE
Fix Object mocking type validation issue

### LINKED ISSUE #29037: [Testerina] Object mocking throws a validation error on using the when().thenReturn() sequence
**Description:**
For the following sample code, Object mocking throws a validation error

`return value provided does not match the return type of function post()`

mock client :
```
http:Client httpClient = <http:Client>test:mock(http:Client);
test:prepare(httpClient).when("post").thenReturn(getMockResponseInvalidKey());
```

function :
```
function getMockResponseInvalidKey() returns http:Response|http:PayloadType|http:ClientError {}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Ibaqu**
## Purpose
Fix Object mocking type validation issue for HTTP module

Fixes #29037

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/ObjectMock.java [hunk 1]
```diff
@@ -324,6 +326,12 @@ private static boolean validateReturnValue(
                     List<Type> memberTypes =
                             ((UnionType) attachedFunction.getType().getReturnParameterType()).getMemberTypes();
                     for (Type memberType : memberTypes) {
+                        if (memberType.getTag() == TypeTags.PARAMETERIZED_TYPE_TAG) {
+                            Type bObjectType = ((ParameterizedType) memberType).getParamValueType();
+                            if (TypeChecker.checkIsType(returnVal, bObjectType)) {
+                                return true;
+                            }
+                        }
                         if (TypeChecker.checkIsType(returnVal, memberType)) {
```
Comment (azinneera) [inline misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/ObjectMock.java:335]: If the previous conditions result in false, will this still try to compare to the null value? 
Should we we add an if-else within the loop to handle the `ParameterizedTypeTag` case and otherwise?

Comment (Ibaqu) [reply misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/mock/ObjectMock.java]: Implemented the if-else as suggested .

**Review by azinneera — APPROVED** [review]
