### PR TITLE
Fix few issues related to check & return stmts within query expressions and query actions 

### LINKED ISSUE #33473: `check` in `select` results in runtime panic
**Description:**
$subject. As mentioned in this commit,
https://github.com/ballerina-platform/nballerina/commit/c129ef3334fe48279b0621bab7091c8ba889732b#diff-55d6c1329641c5efbc3b2e8501bb7892094329f3c3744e2eb221950976b0d3ffR148

If we replace foreach with from/select, it will print the backtrace as shown below. We can get this by running [this example](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/future/record1-uv.bal), against nballerina 

```
error: type not implemented as member type {"location":{"filename":"test.bal","startPos":[4,4],"endPos":null},"functionName":null}
	at wso2.nballerina.err.0:unimplemented(err.bal:64)
	   wso2.nballerina.front.0:resolveMemberTypeDesc(resolveTypes.bal:258)
	   wso2.nballerina.front.0:$streamLambda$_21(resolveTypes.bal:153)
	   ballerina.lang.query.0._SelectFunction:process(types.bal:590)
	   ballerina.lang.query.0:$annon$method$delegate$0(types.bal:91)
	   ballerina.lang.__internal.0:invokeAsExternal(stream-utils.bal:138)
	   ballerina.lang.query.0._StreamPipeline:next(types.bal:91)
	   ballerina.lang.query.0.IterHelper:next(types.bal:723)
	   ballerina.lang.stream.0:next(stream.bal:67)
	   ballerina.lang.query.0:toArray(helpers.bal:88)
	   wso2.nballerina.front.0:resolveTypeDesc(resolveTypes.bal:153)
	   wso2.nballerina.front.0:resolveTypeDefn(resolveTypes.bal:69)
	   wso2.nballerina.front.0:resolveTypes(resolveTypes.bal:29)
	   wso2.nballerina.front.0:resolveModule(front.bal:140)
	   wso2.nballerina.0:processModule(compile.bal:90)
	   wso2.nballerina.0:compileBalFile(compile.bal:76)
	   wso2.nballerina.0:main(main.bal:51)
```
**Steps to reproduce:**
Still I did not find a simple example to reproduce this. I will try to find a simple example

**Affected Versions:**
swan-lake beta3

### LINKED ISSUE #34894: Compiler crashes when check expressions are used in from queries when the error would be caught by an on fail clause
**Description:**
A from query containing a check expression can trip up the compiler when the error is not directly returned by the surrounding function but caught by an `on fail` clause of a `do` or a `transaction` block.

**Steps to reproduce:**

Try to compile the minimal example below:

```ballerina
import ballerina/io;
public function main() {
    do {
        _ = from string v in []
            select check someFunction(v);
    } on fail var err {
        io:println(err);
    }
}

function someFunction(string input) returns string|error {
    return input;
}
```

<details>

<summary>
Click here to show more information.
</summary>

Stacktrace:
```text
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genGoToTerm(JvmTerminatorGen.java:386)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genTerminator(JvmTerminatorGen.java:329)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:486)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:235)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:161)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:446)
        at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1039)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:397)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:811)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:95)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:70)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:301)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:466)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:389)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:249)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

The following code fails with a different stacktrace:

```ballerina
import ballerina/io;
public function main() {
    transaction { // this leads to a different stacktrace
        _ = check from string v in []
            do { _ = check someFunction(v); }; // just another way to trigger the bug?
        check commit;
    } on fail var err {
        io:println(err);
    }
}

function someFunction(string input) returns string|error {
    return input;
}
```

Stacktrace:
```text
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:164)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:443)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:126)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:126)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:401)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:103)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:103)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:82)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:269)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:452)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:389)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:249)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

The `transaction` block causes the error even when the `on fail` clause is missing:

```ballerina
public function main() returns error? {
    transaction {
        _ = check from string v in []
            do {_ = check someFunction(v);};
    } 
}
```

But changing it to a `do` block will compile just fine.

</details>

Possible Workaround until the issue is resolved:

```ballerina
// trap panic, convert back to error
_ = check trap from string v in []
    select checkpanic someFunction(v); // panic on error
```

**Affected Versions:**

Tested on `slbeta6` but the error probably exists since `slbeta4`. Similar code has compiled fine with `slbeta3`.

**OS, DB, other environment details and versions:**

Ubuntu (on WSL2)

**Related Issues:**

Probably related: #34557 

There are more issues with similar stacktraces of compiler errors.

**Suggested Labels:**

Team/CompilerFE, Area/BIR?

### LINKED ISSUE #34915: `NPE` in `BIRGen` when there is a return statement inside query action
**Description:**

Below sample gives `NPE` at `BIRGen`
```bal
function testReachabilityWithQueryAction() returns string {
    string[] stringArray = ["Hello", " ", "World"];

    error? unionResult = from var item in stringArray
        do {
                return "Hello";
        };
}
```
<details>
  <summary>Stack trace.(Click to expand)</summary>

```
[2022-02-01 11:56:12,678] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$15(BIRGen.java:726)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:726)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$5(BIRGen.java:399)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:399)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:269)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
</details>

**Affected Versions:**
2201.0.0 (Swan Lake)

### LINKED ISSUE #34916: Invalid behaviour of query action
**Description:**

Consider the below sample

```bal

1. function testReachabilityWithQueryAction() returns string {
2.     string[] stringArray = ["Hello", " ", "World"];
3. 
4.     error? unionResult = from var item in stringArray
5.         where item is string
6.         do {
7.             if item == "Hello" {
8.                 return "Hello";
9.             }
10.         };
11. 
12.     if unionResult is error {
13.         return "ballerina";
14.     } else {
15.         return "c#";
16.     }
17. }
18. 
19. public function main() {
20.     io:println(testReachabilityWithQueryAction());
21. }

```

Prints `c#` where it should print `Hello`. Apparently the issue is when the return statement at L#8 is executed it returns to do block, not from the function

**Affected Versions:**
2201.0.0 (Swan Lake)

### PR DESCRIPTION
**Pull request by pcnfernando**
## Purpose
Fixes #34894
Fixes #34915
Fixes #34916
Fixes #33473

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 1]
```diff
@@ -822,8 +845,8 @@ private BLangLambdaFunction createFilterLambda(Location pos) {
      * @return created lambda function.
      */
     private BLangLambdaFunction createActionLambda(Location pos) {
-        // returns ()
-        BLangValueType returnType = getNilTypeNode();
+        // returns any|error
+        BLangUnionTypeNode returnType = getAnyErrorNilTypeNode();
```
Comment (lasinicl) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:849]: `any` includes `nil` right? Do we need to include `Nil` in `getAnyErrorNilTypeNode`? 
Also the `getAnyErrorNilTypeNode()` specifically adds the `nilType` when creating the union, which I think is not required.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java [hunk 2]
```diff
@@ -671,6 +676,8 @@ public void visit(BLangQueryAction queryAction) {
             }
         }
         analyzeReachability(queryAction.getDoClause(), env);
+        queryAction.returnsWithinDoClause = this.returnedWithinQuery;
+        this.returnedWithinQuery = prevReturnedWithinQuery;
```
Comment (lasinicl) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:680]: The behavior for the following program is not correct. Since the condition in the `where` clause will never be satisfied, it doesn't execute the statements in the `do` clause.

```ballerina
public function main() {
    string a = testReachabilityWithQueryAction();
    io:println(a.toBalString()); // prints (), which is wrong
}

function testReachabilityWithQueryAction() returns string {
    string?[] stringArray = [(), (), ()];

    error? unionResult = from var item in stringArray
        where item is string
        do {
                return "Hello";
        };
}
```

I think the function should have a return value if it doesn't return from the query action.
Due to https://github.com/ballerina-platform/ballerina-lang/issues/34914, we are unable to include a statement after the query action ATM. Adding https://github.com/ballerina-platform/ballerina-lang/blob/70ebe0903df9f539bf505c39185a2f1a77f3710b/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java#L701-L702 in the visitor of the `DoClause` would solve the issue (The fix will be added in https://github.com/ballerina-platform/ballerina-lang/pull/35287 ).

And even if we fix this and add a return statement at the end as given below, the result would still be the same.
```ballerina
public function main() {
    string a = testReachabilityWithQueryAction();
    io:println(a.toBalString()); // prints (), which is wrong. should print "World"
}

function testReachabilityWithQueryAction() returns string {
    string?[] stringArray = [(), (), ()];

    error? unionResult = from var item in stringArray
        where item is string
        do {
                return "Hello";
        };

    return "World";
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 1 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:849]: This is an existing method. I just reused it to get `any|error` type. Will update the method

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java (hunk 2 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:680]: Improved with b6e47c0acab3b4f681a06a755a855c8b833c0d9e to handle this. But facing https://github.com/ballerina-platform/ballerina-lang/issues/35383. We'll have to rethink how to handle such a scenario because we consider nil as the successful completion type to continue the loop. Hence created this separate issue https://github.com/ballerina-platform/ballerina-lang/issues/35383

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 1 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java]: Updated in a8c44c045ac7488c7677972fc828e27e3a229a15

**Review by lasinicl — APPROVED** [review]

**Review by gimantha — APPROVED** [review]
