### PR TITLE
[LS] Refactor FunctionCallExpressionNodeContext to provide sorted completion items in paramter context

### LINKED ISSUE #30078: Completion suggestions are not accurate for function pointers
**Description:**
Function pointers as parameters are suggested with "()". This is not a valid scenario. 
 
**Steps to reproduce:**
Apr-19-2021 17-06-49

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
**1. Fix function pointer not rendering issue**

  >Solution: Provide function pointer completion item in addition to the function completion item when the context type of the node at cursor is FUNCTION

Sample: 

**2. Refactor `FunctionCallExpressionNodeContext` to provide sorted completion items  when the cursor is positioned within the parameter (argument) context.**

> With this change the completion items for the parameter context  of a function call expression is sorted in the following precedence depending on the assignability as an argument. 
>   
>   1. Variable symbols with assignable TypeDescriptor ( Function pointers are also considered variables)
>   2. Function symbols with assignable TypeDescriptor
>   3. Other symbols - Default Sorting precedence

Consider the following samples

Sample 1

Sample 2

Fixes #30078, #29748, #30529 

## Approach
Filter out visible symbols based on expected parameter type descriptor.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionCallExpressionNodeContext.java [hunk 1]
```diff
@@ -62,4 +88,155 @@ public boolean onPreValidation(BallerinaCompletionContext context, FunctionCallE
...
+        completionItems.add(new SnippetCompletionItem(context, Snippet.KW_FALSE.get()));
+        completionItems.add(new SnippetCompletionItem(context, Snippet.KW_CHECK.get()));
+        completionItems.add(new SnippetCompletionItem(context, Snippet.KW_CHECK_PANIC.get()));
+        completionItems.add(new SnippetCompletionItem(context, Snippet.KW_IS.get()));
+        completionItems.add(new SnippetCompletionItem(context, Snippet.EXPR_ERROR_CONSTRUCTOR.get()));
+        completionItems.add(new SnippetCompletionItem(context, Snippet.EXPR_OBJECT_CONSTRUCTOR.get()));
+        completionItems.add(new SnippetCompletionItem(context, Snippet.EXPR_BASE16_LITERAL.get()));
+        completionItems.add(new SnippetCompletionItem(context, Snippet.EXPR_BASE64_LITERAL.get()));
+
+        Optional<FunctionCallExpressionNode> exprNode = findFunctionCallExpressionNode(context.getNodeAtCursor());
```
[the remark this answers is not in the document]
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionCallExpressionNodeContext.java:121]: @IMS94 I have actually overridden that method for providing parameter context aware completions

[the remark this answers is not in the document]
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionCallExpressionNodeContext.java:121]: @malinthar Yes, noticed that. My concern is, if there's duplicated logic in parent method and this, we can reuse with the above approach. If that's not possible, no issue.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionCallExpressionNodeContext.java [hunk 2]
```diff
@@ -62,4 +88,155 @@ public boolean onPreValidation(BallerinaCompletionContext context, FunctionCallE
...
+     * @param parameterTypeSymbol expected type symbol corresponding to the current argument position.
+     * @param visibleSymbols      visible function and variable symbols.
+     * @return {@link List<LSCompletionItem>}
+     */
+    private List<LSCompletionItem> getParameterContextCompletionItemList(BallerinaCompletionContext ctx,
+                                                                         TypeSymbol parameterTypeSymbol,
+                                                                         List<Symbol> visibleSymbols) {
+        List<LSCompletionItem> completionItems = new ArrayList<>();
+
+        List<Symbol> processedSymbols = new ArrayList<>();
```
[the remark this answers is not in the document]
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FunctionCallExpressionNodeContext.java]: Done!

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java [hunk 3]
```diff
@@ -82,4 +86,25 @@ public void addResolver(Node node) {
...
+        }
+        ContextTypeResolver contextTypeResolver = new ContextTypeResolver(this);
+        this.contextType = getNodeAtCursor().apply(contextTypeResolver);
+
+        NonTerminalNode node = getNodeAtCursor();
+        while (contextType == null && node.parent() != null) {
+            this.contextType = Optional.ofNullable(node.parent().apply(contextTypeResolver).get());
+        }
+        if (contextType == null) {
+            contextType = Optional.empty();
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java:106]: Revamp this logic according to the above comment

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java [hunk 4]
```diff
@@ -149,7 +150,7 @@ public ContextTypeResolver(PositionedOperationContext context) {
                 && (symbol.kind() == SymbolKind.TYPE_DEFINITION || symbol.kind() == SymbolKind.CLASS)
                 && symbol.getName().get().equals(node.identifier().text());
         List<Symbol> moduleContent = QNameReferenceUtil.getModuleContent(context, node, predicate);
-        if (moduleContent.size() > 1) {
+        if (moduleContent.size() > 1 || moduleContent.isEmpty()) {
```
[the remark this answers is not in the document]
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:153]: > The size check also covers the `isEmpty()` check.

If the the list is empty we would get a IndexOutOfBounds Excepcion here in line 157
https://github.com/ballerina-platform/ballerina-lang/blob/9921e9b89f6f2fb3894299c72667a2981f8babd3/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java#L152-L157

[the remark this answers is not in the document]
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:153]: Then we can check for `size != 1`

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java (hunk 3 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java]: Done

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java [hunk 5]
```diff
@@ -82,4 +87,30 @@ public void addResolver(Node node) {
...
+        }
+
+        this.isContextTypeFound = true;
+        if (this.getNodeAtCursor() == null) {
+            this.contextType = Optional.empty();
+            return this.contextType;
+        }
+
+        NonTerminalNode node = getNodeAtCursor();
+        do {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java:105]: Is there any specific reason to use a loop here? The parent visit should be carry out by the visitor itself. Hence we can avoid using the loop here and depend on the `ContextTypeResolver`'s behaviour

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java [hunk 6]
```diff
@@ -37,6 +40,8 @@
     private final List<Node> resolverChain = new ArrayList<>();
     private Token tokenAtCursor;
     private NonTerminalNode nodeAtCursor;
+    private boolean isContextTypeFound = false;
+    private Optional<TypeSymbol> contextType;
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java:44]: Usually we don't use Optional as a field's type. Shall we change it?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java (hunk 5 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java:105]: There can be instances where the parent is not visited. The ExternalTreeList Node implementation is one such instance. (The apply method does not visit the transformer). Hense, the parent will not be visited. IMO, to handle such scenarios a loop is required since we can't guarantee that the ContextTypeResolver always resolves a context for a given node

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java:105]: +1. Let's proceed with this approach then. Better if we can have a discussion on getting a null value from the `ExternalTreeList`.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java [hunk 7]
```diff
@@ -82,4 +87,32 @@ public void addResolver(Node node) {
...
+        do {
+            ContextTypeResolver contextTypeResolver = new ContextTypeResolver(this);
+            Optional<TypeSymbol> typeSymbol = node.apply(contextTypeResolver);
+            if (typeSymbol == null || typeSymbol.isEmpty()) {
+                this.contextType = null;
+            } else {
+                this.contextType = typeSymbol.get();
+            }
+            node = node.parent();
+        } while (this.contextType == null && node.parent() != null);
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java:114]: Shall we add a null check for the node as well?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java (hunk 6 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java]: Done

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java (hunk 7 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java]: done, Ideally, the null check should be for the node not the  node.parent()

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java (hunk 5 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/BallerinaCompletionContextImpl.java:105]: >  Better if we can have a discussion on getting a null value from the `ExternalTreeList`.
+1

**Review by nadeeshaan — APPROVED** [review]
LGTM
