### PR TITLE
Fix issue in parseing error or const match pattern

### LINKED ISSUE #28244: StackOverflowError in parser
**Description:**
$subject

**Steps to reproduce:**
Please run below code

```
function bar () {
    match start 

    return 1;
}
```

**Affected Versions:**
2.0.0-alpha

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$subject

Fixes #28244

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [x] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 1]
```diff
@@ -604,14 +604,14 @@
...
-            { ParserRuleContext.OPEN_PARENTHESIS, ParserRuleContext.MATCH_PATTERN_END };
+            { ParserRuleContext.OPEN_PARENTHESIS, ParserRuleContext.MATCH_PATTERN_RHS };
 
     private static final ParserRuleContext[] ERROR_MATCH_PATTERN_ERROR_KEYWORD_RHS =
             { ParserRuleContext.OPEN_PARENTHESIS, ParserRuleContext.TYPE_REFERENCE };
 
     private static final ParserRuleContext[] ERROR_ARG_LIST_MATCH_PATTERN_START =
             { ParserRuleContext.CONSTANT_EXPRESSION, ParserRuleContext.VAR_KEYWORD,
-                    ParserRuleContext.ERROR_FIELD_MATCH_PATTERN, ParserRuleContext.CLOSE_PARENTHESIS };
+                    ParserRuleContext.ERROR_FIELD_MATCH_PATTERN };
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:614]: Why we do need to exclude CLOSE_PARENTHESIS here?
According to spec https://ballerina.io/ballerina-spec/spec.html#error-arg-list-match-pattern `error-arg-list-match-pattern` is optional?

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java]: Fixed in  81ed241

**Review by lochana-chathura — APPROVED** [review]
