### PR TITLE
Fix MatchedExpressionNodeResolver returning null

### LINKED ISSUE #34318: NPEs in LS for Invalid Syntax
**Description:**
Consider the following code:

```
type Foo object {
    string name;
};

type A object {
    *Foo;
    int z;
};

A x = object {123, <A>""<B>}
```
Once the `""` within `<A>` and `<B>` is typed, NPEs can be observed in the LS for `TypeCastCodeAction` and `AddCheckCodeAction`. 

**Steps to reproduce:**
NPE-LS-for-object

**Affected Versions:**
SL Beta RC6, [Current Master](https://github.com/ballerina-platform/ballerina-lang/tree/2f32deccc15795a3b0f38e6877e88dc853fcc7af)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
$subject

The `apply()` method of `ExternalTreeNodeList` returns `null` causing the `Optional` to be null in `MatchedExpressionNodeResolver` case. Changed the behavior of `MatchedExpressionNodeResolver` to not expose this behavior to the outside.

Fixes #34318

## Approach
See description

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by malinthar — DISMISSED** [review]
LGTM

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java [hunk 1]
```diff
@@ -46,6 +49,26 @@ public MatchedExpressionNodeResolver(Node matchedNode) {
...
+     * @return Optional enclosing expression node
+     */
+    public Optional<ExpressionNode> findExpression(Node node) {
+        if (node == null) {
+            return Optional.empty();
+        }
+
+        Optional<ExpressionNode> exprNode = node.apply(this);
+        // Due to the way apply() method is implemented in some cases, this can return null
+        if (exprNode == null) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java:65]: Shouldn't we fix this bug in a more higher level? For me this feels like sort of a specific remedy we are trying to provide. This same can lead to the same bug in other places as well. WDYT?

Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java:65]: The issue is, `apply()` method in `Node` has the following signature. 
```
public abstract <T> T apply(NodeTransformer<T> transformer);
```
As per generics, `Optional` is just another type for `T`. That's why I thought we cannot handle this better. WDYT?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java [hunk 2]
```diff
@@ -46,6 +49,26 @@ public MatchedExpressionNodeResolver(Node matchedNode) {
...
+            return Optional.empty();
+        }
+        
+        return exprNode;
```
Comment (sanjana) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java:69]:
```suggestion
        return exprNode.isPresent()? exprNode : Optional.empty();
```

Is this further simplification possible?

**Review by sanjana — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java (hunk 2 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java:69]: This might generate NPE when exprNode is null

Comment (sanjana) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java:69]: Can use `return exprNode == null?  Optional.empty() : exprNode;` instead?

Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java:69]: +1

Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java]: +1. Done!

**Review by sanjana — APPROVED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/MatchedExpressionNodeResolver.java]: Given the implementation, that makes sense. But I think, if we call the accept method inside the at the particular node without returning null, this could have been fixed. But, yeah let's proceed with the fix for this time and let's make sure to check for the proper fix if possible as well.

**Review by nadeeshaan — APPROVED** [review]
LGTM
