### PR TITLE
Fix completions when invoking remote methods for records [Master]

### LINKED ISSUE #38038: [Bug]: Completions not suggesting correctly for record fields when invoking remote methods
### Description

When user invoke a remote method if the method has a record type as a parameter, user cannot get the correct completions.

Screenshot 2022-10-04 at 10 06 51

### Steps to Reproduce

```
type School record {|
    string name;
    string city;
|};

public isolated client class SchoolClient {
    isolated remote function addSchool(School school) {}
}

public function test() {
    SchoolClient school = new();
    school->addSchool({<cursor>});
}
```

### Affected Version(s)

2201.2.0

### Related area

-> Editor

### PR DESCRIPTION
**Pull request by gayalkuruppu**
Fixes #38038

https://user-images.githubusercontent.com/46120162/196155029-daa53600-6782-4fd1-b3d2-8d9599ab8796.mov

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/NamedArgCompletionItemBuilder.java [hunk 1]
```diff
@@ -42,10 +42,11 @@ private NamedArgCompletionItemBuilder() {
      * @return {@link CompletionItem}
      */
     public static CompletionItem build(String argName, TypeSymbol argSymbol) {
-        String defaultValue = DefaultValueGenerationUtil.getDefaultPlaceholderForType(argSymbol).orElse("");
+        String defaultValueToInsert = DefaultValueGenerationUtil.getDefaultPlaceholderForType(argSymbol).orElse("");
+        String defaultValueTooDetail = DefaultValueGenerationUtil.getDefaultValueForType(argSymbol).orElse("");
```
Comment (LakshanWeerasinghe) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/NamedArgCompletionItemBuilder.java:46]:
```suggestion
        String defaultValueToDetail = DefaultValueGenerationUtil.getDefaultValueForType(argSymbol).orElse("");
```

**Review by LakshanWeerasinghe — CHANGES_REQUESTED** [review]

**Review by malinthar — APPROVED** [review]
LGTM!

**Review by LakshanWeerasinghe — APPROVED** [review]
LGTM
