### PR TITLE
 Fix nested map to nested record conversion

### LINKED ISSUE #10402: Map to record conversion fails when the map contains another map corresponding to another record
**Description:**
Map to record conversion can be done as follows:
```bal
import ballerina/io;

type Movie record {
    string title,
    string year,
    string released,
};

public function main() {
    map movieMap = {
        title: "The Revenant",
        year: "2015",
        released: "08 Jan 2016"
    };

    Movie mv = check <Movie>movieMap;
}
```

But when the map contains another map corresponding to a record `Person` as follows, conversion fails.
```bal
import ballerina/io;

type Person record {
    string fname,
    string lname,
    int age,
};

type Movie record {
    string title,
    string year,
    string released,
    Person writer,
};

public function main() {
    map writerMap = {
        fname: "Michael",
        lname: "Punke", age: 30
    };

    map movieMap = {
        title: "The Revenant",
        year: "2015",
        released: "08 Jan 2016",
        writer: writerMap
    };

    Movie mv = check <Movie>movieMap;
}
```

Error:
```
error: error, message: cannot convert 'map' to type 'Movie: error while mapping 'writer': incompatible types: expected 'Person', found 'map'
	at main(test.bal:29)
```

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
This PR fixes the nested map to nested record conversion.

Fixes #10402

### CODE REVIEW

File: bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java [hunk 1]
```diff
@@ -3444,84 +3444,119 @@ private static void convertMapToStruct(WorkerExecutionContext ctx, int[] operand
...
-                                RuntimeErrors.INCOMPATIBLE_FIELD_TYPE_FOR_CASTING, key, fieldType, mapVal.getType());
+                                RuntimeErrors.INCOMPATIBLE_FIELD_TYPE_FOR_CASTING, key, fieldType,
+                                mapValType);
                     }
-                } else {
-                    defaultValAttrInfo = (DefaultValueAttributeInfo) getAttributeInfo(fieldInfo,
-                            AttributeInfo.Kind.DEFAULT_VALUE_ATTRIBUTE);
                 }
+            } else {
+                defaultValAttrInfo = (DefaultValueAttributeInfo) getAttributeInfo(fieldInfo,
```
Comment (Shan1024) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java]: Shall we reformat this line?

File: bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java [hunk 2]
```diff
@@ -3444,84 +3444,119 @@ private static void convertMapToStruct(WorkerExecutionContext ctx, int[] operand
...
+                            }
+                        }
                     }
 
-                    if (mapVal != null && !checkCast(mapVal, fieldType, new ArrayList<TypePair>())) {
+                    if (!checkCast(mapVal, fieldType, new ArrayList<TypePair>())) {
                         throw BLangExceptionHelper.getRuntimeException(
-                                RuntimeErrors.INCOMPATIBLE_FIELD_TYPE_FOR_CASTING, key, fieldType, mapVal.getType());
+                                RuntimeErrors.INCOMPATIBLE_FIELD_TYPE_FOR_CASTING, key, fieldType,
+                                mapValType);
```
Comment (Shan1024) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java]: We can merge this line with the one above.

File: bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java [hunk 3]
```diff
@@ -3444,84 +3444,119 @@ private static void convertMapToStruct(WorkerExecutionContext ctx, int[] operand
...
+                    BType mapValType = mapVal.getType();
+                    if (mapValType.getTag() == TypeTags.MAP_TAG) {
+                        if (fieldType.getTag() == TypeTags.RECORD_TYPE_TAG) {
+                            bStruct.put(key, convertMapToStruct(ctx, (BMap<String, BValue>) mapVal,
+                                                                ((BStructureType) fieldType)));
+                            continue;
+                        } else if (fieldType.getTag() == TypeTags.UNION_TAG) {
+                            boolean conversionDone = false;
+                            for (BType memType : ((BUnionType) fieldType).getMemberTypes()) {
+                                if (memType.getTag() == TypeTags.RECORD_TYPE_TAG) {
```
Comment (Shan1024) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java]: There are 7 nested blocks. Is it possible to reduce the number of nested blocks?

File: bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java [hunk 4]
```diff
@@ -3444,84 +3444,101 @@ private static void convertMapToStruct(WorkerExecutionContext ctx, int[] operand
...
+            boolean containsField = bMap.hasKey(key);
+            DefaultValueAttributeInfo defaultValAttrInfo = null;
+            if (containsField) {
+                mapVal = bMap.get(key);
+                if (mapVal == null && BTypes.isValueType(fieldType)) {
+                    throw BLangExceptionHelper.getRuntimeException(
+                            RuntimeErrors.INCOMPATIBLE_FIELD_TYPE_FOR_CASTING, key, fieldType, null);
+                }
+
+                if (mapVal != null) {
```
Comment (SupunS) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java]: do we need the not-null check here? I think it will be correctly handled by the check cast.

Instead lets move this and merge it with L#3480

File: bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java [hunk 5]
```diff
@@ -3444,84 +3444,101 @@ private static void convertMapToStruct(WorkerExecutionContext ctx, int[] operand
...
-                    defaultValAttrInfo = (DefaultValueAttributeInfo) getAttributeInfo(fieldInfo,
-                            AttributeInfo.Kind.DEFAULT_VALUE_ATTRIBUTE);
                 }
-
-                switch (fieldType.getTag()) {
-                    case TypeTags.INT_TAG:
-                        if (containsField) {
-                            bStruct.put(key, mapVal);
-                        } else if (defaultValAttrInfo != null) {
+            } else {
```
Comment (SupunS) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java]: We can remove the 'else' block, and take it out. It will reduce the indentations..

File: bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java (hunk 4 above)
Comment (MaryamZi) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/CPU.java]: Fixed with 3f25167
