### PR TITLE
Revamp `cloneWithType` and `fromJsonWithType`

### LINKED ISSUE #35141: Provide a runtime API to clone a value to a type
**Description:**

Need to expose cloneWithType as a runtime API. Need to provide the convert method there as an API.

**Describe your task(s)**

**Related Issues (optional):**

https://github.com/ballerina-platform/ballerina-lang/issues/35040

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #37610: Support first match approach for union type configurable variables
### Description

As per the conclusion in spec issue https://github.com/ballerina-platform/ballerina-spec/issues/1158, 
It is expected to create value for configurable variables according to the first-matching member type of the union. 
Currently, we provide an ambiguity error for these cases.

### Describe your problem(s)

In `main.bal`
```ballerina
type Person record {|
    string name;
    string city;
|};

configurable map<string>|Person m = ?;
```
In `Config.toml`
```toml
m = {name = "Jack", city = "Colombo"}
```

This should provide a map value with the type `map<string>`.

### Describe your solution(s)

_No response_

### Labels

jBallerina

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #38715: [Bug]: Cannot convert a value to the `xml` type using `cloneWithType`
### Description

`cloneWithType` can’t be used to convert a value to an XML type or to any structure which has XML type. `fromJsonWithType` can be used for that.

`fromJsonWithType` also only support converting an string to an xml. Conversion of other types to xml also needs to be checked.

### Steps to Reproduce

```bal
type XmlType xml;
 
function testToJsonWithXML() {
   xml x1 = xml `<movie>
                   <title>Some</title>
                   <writer>Writer</writer>
                 </movie>`;
   json j = x1.toJson(); // j is a string now
   xml x2 = checkpanic j.fromJsonWithType(XmlType); // passes
   xml x3 = checkpanic j.cloneWithType(XmlType); //fails
 
  string s1 = "<test>name</test>";
  xml|error xe = s1.cloneWithType(XmlType); // gives error
 
}
```

### Affected Version(s)

2201.2.2

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #38716: [Bug]: Conversion of a value to the `table`, `regexp:RegExp` types in `cloneWithType` is erroneous
### Description

cloneWithType has issues and bugs in the conversion to table type. While fromJsonWithType is okay, fromJsonWithType path should also be checked.

Conversion to recently introduced `ballerina/lang.regexp:0:RegExp` type is only supported with fromJsonWithType, if cloneWithType is used erroneous behaviour is there.

### Steps to Reproduce

```bal
type Foo2 record {|
    int x2 = 1;
    int y3 = 2;
|};

type Foo3 record {
    string x3;
    int y3;
};

type Foo4 record {
    string x3;
    int y3 = 1;
};

type Foo5 record {
    string x3;
    int y3?;
};

type Foo6 record {
    string x3;
};

type TableFoo2 table<Foo2>;
type TableFoo3 table<Foo3>;
type TableFoo4 table<Foo4>;
type TableFoo5 table<Foo5>;
type TableFoo6 table<Foo6>;

function testCloneWithTypeTable() {
    json jj = [
        {x3: "abc"},
        {x3: "abc"}
    ];

    table<Foo2>|error tabJ2 = jj.cloneWithType(TableFoo2);
    assertEquality(tabJ2 is error, true);

    table<Foo3>|error tabJ3 = jj.cloneWithType(TableFoo3);
    assertEquality(tabJ3 is error, true);

    table<Foo4>|error tabJ4 = jj.cloneWithType(TableFoo4);
    assertEquality(tabJ4 is table<Foo4>, true);

    table<Foo5>|error tabJ5 = jj.cloneWithType(TableFoo5);
    assertEquality(tabJ5 is table<Foo5>, true);

    table<Foo6>|error tabJ6 = jj.cloneWithType(TableFoo6);
    test:assertEquals(tabJ6 is table<Foo6>, true);

}
```

```bal
type RegExpType string:RegExp;
string s = "AB+C*D{1,4}";
RegExpType|error x1 = s.cloneWithType(RegExpType);
```

### Affected Version(s)

2201.2.2

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39162: [Task]: Bring `fromJsonWithType` and `cloneWithType` into a common implementation
### Description

According to the spec `fromJsonWithType` works the same as `cloneWithType` except that it also does the inverse of the conversions done by `toJson`. But since we give the type to convert to, we don't have the need to consider about the inverse of the conversions done by `toJson`. The difference is in `fromJsonWithType` the source value should be a subtype of `json`, while in `cloneWithType` the source value should be a subtype of `anydata`.

### Describe your task(s)

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39168: [Bug]: Fix spec deviations in handling ambiguities in `cloneWithType`
### Description

$title

The spec for `cloneWithType` says this.
```
Constructs a value with a specified type by cloning another value.
# + v - the value to be cloned
# + t - the type for the cloned to be constructed
# + return - a new value that belongs to type `t`, or an error if this cannot be done
# 
# When `v` is a structural value, the inherent type of the value to be constructed
# comes from `t`. When `t` is a union that includes more than one type descriptor
# that can be used as the inherent type of values with `v`'s basic type, then
# the inherent type used will be the first (leftmost) such type descriptor such that a value
# belonging to that type can be constructed from `v`.
```
Currently the inherent type is not chosen properly. We need to fix this such that it produces the below examples.

1. First (leftmost) such type descriptor is considered only when `v` is a structural value.
```
json j = { x: 1 };
record { float x; } | record { int x; } v = checkpanic j.cloneWithType(); // should give { x: 1.0 } inherent type is record { float x; }
```
This is recursively applicable for nested fields also.
```
json j = {y: {x: 1}};
record{record {float x;}|record {int x;} y;} v = checkpanic j.cloneWithType(); // should give {y: {x: 1.0}}, if nested field is a structural value, should consider the first match policy
```
```
json j = { x: 1, y: 2 };
record { float x; decimal|int y; } | record { int x; decimal y; } v = check j.cloneWithType(); // should give { x:1.0, y: 2 }  inherent type is record { float x; decimal|int y; }
```

2. If it is not a structural value, the first match policy is not considered.
```
float x = 12.0;
int|float y = checkpanic x.cloneWithType(); // should give 12.0 float
```
This is recursively applicable for nested fields also.
```
json j = { x: 6.0, y: 12 };
record { int|float x; float y; } = j.fromJsonWithType(); // should give { x: 6.0, y: 12.0 } if nested field is not a structural value, the first match policy is not considered.
```
```
json j = { x: 6.0, y: 12 };
record { int|float x; int y; } = j.fromJsonWithType(); // should give { x: 6.0, y: 12 } if nested field is not a structural value, the first match policy is not considered.
```

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39383: [Bug]: `CloneWithType` gives unexpected error when converting table to any data
### Description

$ Subject

### Steps to Reproduce

Run the following code :
```ballerina
import ballerina/constraint;

type ArrayConstraintLengthOnRecordField record {
    @constraint:Array {
        length: 6
    }
    anydata[] value;
};

public function main() returns error? {
    anydata rec = {
        value: [
            (),
            true,
            123,
            123.45,
            123.45d,
            "s3cr3t",
            xml `<book>The Lost World</book>`,
            {foo: "bar"},
            table key('key) [
                {'key: 1, value: "foo"}
                ]
        ]
    };
    ArrayConstraintLengthOnRecordField _ = check rec.cloneWithType();
}
```

```console
$ bal run
Compiling source
        user/test:0.1.0

Running executable

error: {ballerina/lang.value}ConversionError {"message":"'map<anydata>' value cannot be converted to 'test:ArrayConstraintLengthOnRecordField': 
                array element 'value[8]' should be of type 'anydata', found '[{"key":1,"value":"f...'"}
```

### Affected Version(s)

Ballerina SwanLake 2201.3.2

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39385: [Bug]: Table value conversion is failing for union target type
### Description

$subject

### Steps to Reproduce

```ballerina 

type Table1 table<map<int>>;

type Table2 table<map<string>>;

type UnionTable Table1|Table2;


public function main() {
    map<json>[] tab = [{a: "a", b: "b"}];
    Table1|Table2|error t4 = tab.fromJsonWithType(); 
    io:println(t4 is error);  // true - should be false

    UnionTable|error t5 = tab.fromJsonWithType(); 
    io:println(t5 is error); //  true - should be false

    map<json>[] tab2 = [{a: "a", b: "b"}];
    UnionTable|error t10 = tab2.fromJsonWithType();
    io:println(t10 is error); // true - should be false

    table<map<json>> tab3 = table [{a: "a", b: "b"}];
    UnionTable|error t11 = tab3.cloneWithType();
    io:println(t11 is error); // false
}
```

### Affected Version(s)

2201.3.x and the current master

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39610: [Bug]: Cannot convert possible `string` values to `xml` subtypes
### Description

`toJson` converts a given `xml` to `string`. But when `fromJsonWithType` is used it fails to do the conversion. Spec requires for `fromJsonWithType`
```
# Converts a value of type json to a user-specified type.
# This works the same as `cloneWithType`,
# except that it also does the inverse of the conversions done by `toJson`.
```
 

### Steps to Reproduce

```bal
function foo() {
    xml:Element x1 = xml `<book>The Lost World</book>`;
    json j;
    j = x1.toJson();
    io:println(j);
    xml:Element x1_back = checkpanic j.fromJsonWithType();
    io:println(x1_back); // <book>The Lost World</book> - okay

    // An XML processing instruction.
    xml:ProcessingInstruction x2 = xml `<?target data?>`;
    j = x2.toJson();
    io:println(j);
    xml:ProcessingInstruction x2_back = checkpanic j.fromJsonWithType(); //error: {ballerina/lang.value}ConversionError {"message":"'string' value cannot be converted to 'lang.xml:ProcessingInstruction': failed to parse xml: Unexpected EOF in prolog at [row,col {unknown-source}]: [1,15]"}
    io:println(x2_back);


    // An XML comment.
    xml:Comment x3 = xml `<!--I am a comment-->`;
    j = x3.toJson();
    io:println(j);
    xml:Comment x3_back = checkpanic j.fromJsonWithType(); // error: {ballerina/lang.value}ConversionError {"message":"'string' value cannot be converted to 'lang.xml:Comment': failed to parse xml: Unexpected EOF in prolog at [row,col {unknown-source}]: [1,21]"}
    io:println(x3_back);


    // An XML text.
    xml:Text x4 = xml `Hello, world!`;
    j = x4.toJson();
    io:println(j);
    xml:Text x4_back = checkpanic j.fromJsonWithType(); // error: {ballerina/lang.value}ConversionError {"message":"'string' value cannot be converted to 'lang.xml:Text': failed to parse xml: Unexpected character 'H' (code 72) in prolog; expected '<' at [row,col {unknown-source}]: [1,1]"}
    io:println(x4_back);
}
```

### Affected Version(s)

Ballerina 2201.3.2 (Swan Lake Update 3)

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39647: [Bug]: `value:fromBalString` returns incomplete `xml`
### Description

$title

### Steps to Reproduce

```bal
import ballerina/io;
import ballerina/lang.value;
public function main() {
    string a = "xml `<movie>\n\t\t<title>Some</title>\n\t\t<writer>Writer</writer>\n</movie>`";
    anydata b = checkpanic value:fromBalString(a);
    io:println(b);
}
```
gives
```
<title>Some</title>
                <writer>Writer</writer>
```
This should give
```
<movie>
                <title>Some</title>
                <writer>Writer</writer>
</movie>
```

### Affected Version(s)

Ballerina 2201.3.2 (Swan Lake Update 3)

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #39162
Fixes #38716
Fixes #38715
Fixes #35141
Fixes #39168
Fixes #39385
Fixes #39383
Fixes #39610
Fixes #39647
Fixes #37610

Also changed how union of conversion errors are displayed.
For example when running the following Ballerina code
```bal
public function main() {
    foo();
}

type NumberArray int[]|float[];
type StringArray string[]|string:Char[];
type NumberOrStringArray NumberArray|StringArray;

type RecordWithArrayAsAField record {|
    NumberOrStringArray arr;
|};

type RecordWithNumberArrayAsAField record {|
    NumberArray arr;
|};

function foo() {
    json j = {"arr": [1,1.2,"a","aa"]};
    RecordWithArrayAsAField|RecordWithNumberArrayAsAField jCloned = checkpanic j.cloneWithType();
}
```
it gives
```
Running executable

error: {ballerina/lang.value}ConversionError {"message":"'map<json>' value cannot be converted to '(RecordWithArrayAsAField|RecordWithNumberArrayAsAField)': 
                {
                  {
                    array element 'arr[2]' should be of type 'int', found '"a"'
                    array element 'arr[3]' should be of type 'int', found '"aa"'
                  or
                    array element 'arr[2]' should be of type 'float', found '"a"'
                    array element 'arr[3]' should be of type 'float', found '"aa"'
                  or
                    array element 'arr[0]' should be of type 'string', found '1'
                    array element 'arr[1]' should be of type 'string', found '1.2'
                  or
                    array element 'arr[0]' should be of type 'lang.string:Char', found '1'
                    array element 'arr[1]' should be of type 'lang.string:Char', found '1.2'
                    array element 'arr[3]' should be of type 'lang.string:Char', found '"aa"'
                  }
                or
                  {
                    array element 'arr[2]' should be of type 'int', found '"a"'
                    array element 'arr[3]' should be of type 'int', found '"aa"'
                  or
                ..."}
        at ballerina.lang.value.0:cloneWithType(value.bal:114)
           temp:foo(temp.bal:19)
           temp:main(temp.bal:2)
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java [hunk 1]
```diff
@@ -1,7 +1,7 @@
 /*
- * Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
+ * Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
```
Comment (gabilang) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java:2]: Why we are changing this to `2023`? The file is being existed since `2019`

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 2]
```diff
@@ -305,57 +305,77 @@ public static Type getConvertibleType(Object inputValue, Type targetType, String
...
         }
         return null;
     }
 
+    private static boolean isStringConvertibleToXmlType(Object inputValue) {
+        if (TypeChecker.getType(inputValue).getTag() == TypeTags.STRING_TAG) {
+            try {
+                XmlFactory.parse(((BString) inputValue).getValue());
+            } catch (BError e) {
+                return false;
```
Comment (gabilang) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:333]: What would be the error message printed down the line in case the parsing results in a `BError`? Shouldn't we show the actual cause of the error in conversion?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 3]
```diff
@@ -305,57 +305,77 @@ public static Type getConvertibleType(Object inputValue, Type targetType, String
...
+            }
+        } else {
+            return false;
```
Comment (gabilang) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:336]: Shall we add this case as early return?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java (hunk 1 above)
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java:2]: Here I have moved the `CloneUtils` class to another package by deleting the previous file and creating a new file with the same content. In this case do I need to keep the previous year?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java (hunk 2 above)
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:333]: This method returns a boolean which shows whether the provided value is an string that can be parsed as an xml. If it cannot be parsed the `XmlFactory.parse` method will throw an BError. Here we do not need to show the actual cause of the error.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java (hunk 3 above)
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:336]: Will address this.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java (hunk 1 above)
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java]: Changed the year back to 2019.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 4]
```diff
@@ -1201,13 +1205,17 @@ private static boolean isFloatWithinIntRange(double doubleValue) {
     }
 
     public static Type resolveMatchingTypeForUnion(Object value, Type type) {
+        if (value instanceof TableValue && ((TableValue<?, ?>) value).getType().getTag() == TypeTags.TABLE_TAG) {
+            return ((TableValue<?, ?>) value).getType();
```
Comment (Nadeeshan96) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:1209]: Here just can't return the `getType()` because of the readonly status difference between source and target types, will fix and update and add tests

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java [hunk 5]
```diff
@@ -83,17 +86,29 @@ public static BError createConversionError(Object value, Type targetType, List<S
...
-            errors.remove(MAX_CONVERSION_ERROR_COUNT);
-            errors.add("...");
-        }
+    static String getErrorMessage(List<String> errors, int maxErrorCount) {
         StringBuilder errorMsg = new StringBuilder();
-        for (String error : errors) {
-            errorMsg.append("\n\t\t").append(error);
+        int totalErrorCount = errors.size();
+        int tabs = 0;
+        for (int i = 0; i < Math.min(totalErrorCount, maxErrorCount); i++) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java:96]: Why we need this comparison?

Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java:96]: To show only the first 20 (maxErrorCount) error messages.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 6]
```diff
@@ -3266,6 +3300,31 @@ private static boolean isXMLSequenceChildrenEqual(List<BXml> lhsList, List<BXml>
         return true;
     }
 
+    static boolean isRegExpType(Type targetType) {
+        if (targetType.getTag() == TypeTags.TYPE_REFERENCED_TYPE_TAG) {
+            Type referredType = ((ReferenceType) targetType).getReferredType();
+            if (referredType.getQualifiedName().equals("ballerina/lang.regexp:0:RegExp")) {
```
[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:3294]: Will do this or use the tag.

[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java]: Cannot use the tag because the `ballerina/lang.regexp:0:RegExp` type is a type reference type. Hence can't use `TypeUtils.getReferredType` also. Changed this such that the major version is not considered.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 7]
```diff
@@ -1231,58 +1233,33 @@ public static Type resolveMatchingTypeForUnion(Object value, Type type) {
...
-            }
-            return true;
+        Type targetTypeMapType = new BMapType(targetUnionType, readOnlyTargetType);
+        if (checkIsLikeType(value, targetTypeMapType)) {
+            return targetTypeMapType;
         }
-        return true;
-    }
-
-    private static boolean isDeepConversionRequiredForMap(Type sourceType) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:1274]: Why we remove these methods?

Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:1274]: Places which call these methods are redundant. I have removed those. Hence these are not used anymore. 
Eg:
```java
if (value instanceof MapValue && ((MapValue) value).getType().getTag() == TypeTags.MAP_TAG &&
        !isDeepConversionRequiredForMap(((MapValue) value).getType())) {
    return TypeCreator.createMapType(type); // returns map<anydata> when target type is anydata
}
```
The above thing will be now handed in 
```java
Type targetTypeMapType = new BMapType(targetUnionType, readOnlyTargetType);
if (checkIsLikeType(value, targetTypeMapType)) {
    return targetTypeMapType; // returns map<anydata> when target type is anydata
}
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueConverter.java [hunk 8]
```diff
@@ -0,0 +1,283 @@
...
+
+    public static Object convert(Object value, BTypedesc t) {
+        return convert(value, t.getDescribingType());
+    }
+
+    public static Object convert(Object value, Type targetType) {
+        try {
+            return convert(value, targetType, new HashSet<>());
+        } catch (BallerinaException e) {
+            throw createError(BallerinaErrorReasons.BALLERINA_PREFIXED_CONVERSION_ERROR,
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueConverter.java:78]: Why this line is not covered?

**Comment by HindujaB** [comment]
Configurable changes LGTM

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/ValueUtils.java [hunk 9]
```diff
@@ -0,0 +1,47 @@
...
+    /**
+     * Converts the given value which is a subtype of {@link AnydataType} to another subtype of {@link AnydataType}
+     * given by the target type.
+     *
+     * @param   value       value to be converted
+     * @param   targetType  target type
+     * @return              converted value
+     * @throws              BError if the conversion fails.
+     */
+    public static Object convert(Object value, Type targetType) {
```
[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/ValueUtils.java:44]: Created https://github.com/ballerina-platform/ballerina-standard-library/issues/3933.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java [hunk 10]
```diff
@@ -83,17 +86,29 @@ public static BError createConversionError(Object value, Type targetType, List<S
...
-        return ErrorUtils.createConversionError(value, targetType, getErrorMessage(errors));
+        return ErrorUtils.createConversionError(value, targetType, getErrorMessage(errors, MAX_CONVERSION_ERROR_COUNT));
     }
 
-    private static String getErrorMessage(List<String> errors) {
-        if (errors.size() == MAX_CONVERSION_ERROR_COUNT + 1) {
-            errors.remove(MAX_CONVERSION_ERROR_COUNT);
-            errors.add("...");
-        }
+    static String getErrorMessage(List<String> errors, int maxErrorCount) {
```
[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java:92]: Updated the PR description.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java [hunk 11]
```diff
@@ -1,7 +1,7 @@
 /*
- * Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
+ * Copyright (c) 2019, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
  *
- * WSO2 Inc. licenses this file to you under the Apache License,
+ * WSO2 LLC. licenses this file to you under the Apache License,
```
[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/CloneUtils.java:4]: Keeping as discussed.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueConverter.java (hunk 8 above)
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/ValueConverter.java:78]: Will remove the `catch` part after fixing https://github.com/ballerina-platform/ballerina-lang/issues/39256.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 12]
```diff
@@ -370,18 +377,14 @@ public static boolean isSameType(Type sourceType, Type targetType) {
...
-        switch (sourceTypeTag) {
-            case TypeTags.FINITE_TYPE_TAG:
-                for (Object value : ((BFiniteType) sourceType).valueSpace) {
-                    if (!isSameType(getType(value), targetType)) {
-                        return false;
-                    }
+        if (sourceTypeTag == TypeTags.FINITE_TYPE_TAG) {
+            for (Object value : ((BFiniteType) sourceType).valueSpace) {
+                if (!isSameType(getType(value), targetType)) {
+                    return false;
```
[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:383]: Created https://github.com/ballerina-platform/ballerina-lang/issues/39778 to remove the unused code. Regarding uncovered lines in `checkIsLikeUnionType`, according to https://app.codecov.io/gh/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java, they are previously also not covered. When checked, could not find a way to cover those lines.

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
