### PR TITLE
Fix table lookup doesn't check when there is only one candidate issue

### LINKED ISSUE #34712: Table lookup doesn't check equality on keys where there is only one hash candidate
**Description:**
```ballerina
import ballerina/io;
type R record {|
    readonly int|float|decimal|boolean v;
    int code;
|};

type Tab table<R> key(v);

public function main() {
    Tab t = table [
            {v: 0, code: 0}
        ];

    io:println(t);
    io:println(t[0f]);
}
```

The offender seems to be ignoring the `equals` check:
https://github.com/ballerina-platform/ballerina-lang/blob/472454e8fdb97e2568277de407607186f41f91e5/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java#L588

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by rpjayasekara**
Fixes #34712

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java [hunk 1]
```diff
@@ -585,14 +585,14 @@ public V getData(K key) {
             if (entryList == null) {
                 return null;
             }
-            if (entryList.size() > 1) {
+            if (entryList.size() >= 1) {
```
Comment (gimantha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java:588]: Can we not simply remove this `if` condition?

Comment (rpjayasekara) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java:588]: +1

**Review by hasithaa — APPROVED** [review]
