### PR TITLE
Fix large string hard coded values crashing code generation

### LINKED ISSUE #36015: Error when compiling the code with a large hard coded large string
**Description:**
When we hard code a large string (~1MB ) and tries to build the code it gives an error. 

**Steps to reproduce:**

1. Create a ballerina file and include a large string (~ size of 1 MB). 
2. Compile the code.
3. Gives below error
image

**Affected Versions:**

```
Ballerina 2201.0.2 (Swan Lake)
Language specification 2022R1
Update Tool 1.3.9

```

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #36087: Runtime crashes when a hardcoded string contains large surrogates
**Description:**
$subject
Happens when the string contains > 1000 Unicode characters (emoji).

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() returns error? {
    string test1 = "<Add_large_string>";
    io:println(test1 + " ");
}
```
Large string - 
[TestNonBMP1000.txt](https://github.com/ballerina-platform/ballerina-lang/files/8667132/TestNonBMP1000.txt)

Error : 
```
[2022-05-11 11:20:55,861] SEVERE {b7a.log.crash} - null 
java.lang.ExceptionInInitializerError
        at hinduja.foo.0.$_init.$gen$$0046$0060init$0062(foo:0)
        at hinduja.foo.0.$_init.$moduleInit(foo)
        at hinduja.foo.0.$_init.$lambda$$moduleInit$(foo)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NegativeArraySizeException: -40
        at hinduja.foo.0.constants.$_string_constants.$string_init0(Unknown Source)
        at hinduja.foo.0.constants.$_string_constants.<clinit>(Unknown Source)
        ... 7 more
```
**Affected Versions:**
2201.0.3 and previous versions

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#36015

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject

Fixes #36015
Fixes #36087 

## Approach
The issue happens due to the `asm` limitation that only supports loading string values of size lesser than `65535`. This can be fixed by splitting the large string values into smaller string chunks and concatenating them to create the `BString` constants when we generate string constants.

## Remarks
TODO: Fix the method too large issue, when we have large non-Bmp string values.
 
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmBStringConstantsGen.java [hunk 1]
```diff
@@ -101,23 +115,130 @@ public void generateConstantInit(Map<String, byte[]> jarEntries) {
...
+            mv.visitVarInsn(ALOAD, 0);
+            mv.visitMethodInsn(INVOKESTATIC, stringConstantsClass, methodName, "([I)V", false);
+        }
+        mv.visitVarInsn(ALOAD, 0);
+        mv.visitInsn(ARETURN);
+        mv.visitMaxs(0, 0);
+        mv.visitEnd();
+    }
+
+    private List<String> generateSplitGetSurrogateArrayMethod(ClassWriter cw, String varName, int[] values) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/constants/JvmBStringConstantsGen.java:147]: Shall we moved this surrogate split methods to separate class?
