### PR TITLE
Fix invalid error for inaccessible module definitions in mapping constructor

### LINKED ISSUE #41571: [Bug]: Actual issue is not conveyed when a non-accessible symbol is used as a computed key with a union expected type for the mapping constructor
### Description

$title.

### Steps to Reproduce

proj.mod

```ballerina
const string NAME = "name";
```

proj

```ballerina
import proj.mod;

public function main() {
    map<string>? m = {[mod:NAME]: "Amy"};
}
```

```bash
proj$ bal build 
Compiling source
        maryam/proj:0.1.0
ERROR [main.bal:(4:22,4:41)] incompatible mapping constructor expression for type 'map<string>?'
error: compilation contains errors
```

### Affected Version(s)

2201.8.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by poorna2152**
## Purpose
Fixes #41571 

## Approach
When type checking the mapping constructor when the left hand side has a union type use a clone for silent type checking.

When silent type-checking a mapping constructor with a union type on the left-hand side, use a clone. If the types does not match after silent type checking, type check the key expression as well as the value expressions in the mapping constructor.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -2509,8 +2509,9 @@ public BType checkMappingConstructorCompatibility(BType bType, BLangRecordLitera
                 }
 
                 dlog.resetErrorCount();
+                BLangRecordLiteral clonedMappingConstructor = nodeCloner.cloneNode(mappingConstructor);
                 BType memCompatibiltyType = checkMappingConstructorCompatibility(listCompatibleMemType,
-                                                                                 mappingConstructor, data);
+                        clonedMappingConstructor, data);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2514]: Did we consider fixing this by introducing changes similar to that for list constructors? Just to keep things consistent.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java [hunk 2]
```diff
@@ -419,6 +419,30 @@ public void testDuplicateFieldWithEscapeSequence() {
         Assert.assertEquals(compileResult.getErrorCount(), index);
     }
 
+    @Test
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java:422]: We usually add tests with custom module imports as bala tests.

This is also reproducible without an import, right? With an undefined symbol for example. If so, we can stick to a single file test.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -7654,6 +7655,12 @@ private BType checkMappingField(RecordLiteralNode.RecordField field, BType mappi
 
                 fieldType = validMapKey ? ((BMapType) mappingType).constraint : symTable.semanticError;
                 break;
+            case TypeTags.SEMANTIC_ERROR:
+                if (keyValueField) {
+                    BLangRecordKeyValueField keyValField = (BLangRecordKeyValueField) field;
+                    BLangRecordKey key = keyValField.key;
```
Comment (SasinduDilshara) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7661]: We can combine these two lines

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2514]: For list constructor when silent type checking the types in the union type it seems to be setting the `data.commonAnalyzerData.nonErrorLoggingCheck = true;` [[1](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L1740)] and using the function `exprIncompatible`[[2](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L2242-L2245)] which clones the node in the case of `nonErrorLoggingCheck`

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2514]: Yes, what I'm asking is if we can't handle this similarly?

Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated the code

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 4]
```diff
@@ -7779,7 +7784,7 @@ private BType getAllFieldType(BRecordType recordType) {
 
     private boolean checkValidJsonOrMapLiteralKeyExpr(BLangExpression keyExpr, boolean computedKey, AnalyzerData data) {
         if (computedKey) {
-            checkExpr(keyExpr, symTable.stringType, data);
+            exprIncompatible(symTable.stringType, keyExpr, data);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7787]: codecov warning?

Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7899]: Fixed after rebase

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7899]: Is the subsequent logic here (L7901 - L7904) correct? 

I'm not sure if this along with the changes in L7769 - L7773 are correct. Ideally, we should have the same flow, just that on one path we have non-error logging checks.

**Comment by MaryamZi** [comment]
```ballerina
function testMappingConstructorWithUndefinedVars() {
    map<string>? _ = {[NAME] : "Amy"};
}
```

Now we get two errors

```
ERROR [demo.bal:(2:22,2:38)] incompatible mapping constructor expression for type 'map<string>?'
ERROR [demo.bal:(2:24,2:28)] undefined symbol 'NAME
```

I don't think we need the first error anymore. Shall we check if it is straightforward to avoid this?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 5]
```diff
@@ -8025,12 +8023,7 @@ private BType getAllFieldType(BRecordType recordType) {
...
-            checkExpr(keyExpr, symTable.stringType, data);
-
-            if (keyExpr.getBType() == symTable.semanticError) {
-                return false;
-            }
-            return true;
+            return !exprIncompatible(symTable.stringType, keyExpr, data);
         } else if (keyExpr.getKind() == NodeKind.SIMPLE_VARIABLE_REF ||
                 (keyExpr.getKind() == NodeKind.LITERAL && (keyExpr).getBType().tag == TypeTags.STRING)) {
             return true;
```
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8029]: We can drop the `else` key word and directly use only `if` since we have a return in the previous `if`.
(Minor suggestion)

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/expressions/MappingConstructorExprBalaTest.java [hunk 6]
```diff
@@ -0,0 +1,88 @@
...
+                "incompatible mapping constructor expression for type '(map<string>|Rec)'", 28, 25);
+        BAssertUtil.validateError(negativeCompileResult, i++,
+                "attempt to refer to non-accessible symbol 'MAPPING_NAME'", 28, 27);
+        BAssertUtil.validateError(negativeCompileResult, i++, "undefined symbol 'MAPPING_NAME'", 28, 27);
+        BAssertUtil.validateError(negativeCompileResult, i++, "attempt to refer to non-accessible symbol 'MAPPING_C'",
+                28, 46);
+        BAssertUtil.validateError(negativeCompileResult, i++, "undefined symbol 'MAPPING_C'", 28, 46);
+        Assert.assertEquals(negativeCompileResult.getErrorCount(), i);
+    }
+
```
Comment (dulajdilshan) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/expressions/MappingConstructorExprBalaTest.java:87]:
```suggestion
```

unnecessary new line
(Minor suggestion)

**Review by dulajdilshan — COMMENTED** [review]
Minor suggestions

**Review by MaryamZi — APPROVED** [review]

**Comment by MaryamZi** [comment]
Please check library module build failures.

**Comment by poorna2152** [comment]
> incompatible mapping constructor expression for type 'map<string>?'

Decided to handle this separately, created an [issue](https://github.com/ballerina-platform/ballerina-lang/issues/42462) for this.

**Review by chiranSachintha — APPROVED** [review]
