### PR TITLE
Fix inconsistent violation with put/add against inherent table type

### LINKED ISSUE #23241: Check inconsistent violation with put/add against inherent table type
Refer https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/table.bal#L67

### PR DESCRIPTION
**Pull request by lasinicl**
Fixes #23241

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableValueImpl.java [hunk 1]
```diff
@@ -538,6 +542,14 @@ private void updateIndexKeyMappings(Long hash) {
         }
     }
 
+    // This method checks for inherent table type violation
+    private void checkInherentTypeViolation(MapValue dataMap, BTableType type) {
+        if (!TypeChecker.checkIsType(dataMap.getType(), type.getConstrainedType())) {
+            throw BallerinaErrors.createError(VALUE_INCONSISTENT_WITH_TABLE_TYPE_ERROR,
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/TableValueImpl.java:548]: Let's use InherentTypeViolation in https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/exceptions/BallerinaErrorReasons.java#L64 here instead.
Check map/tuple violation check

File: langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal [hunk 2]
```diff
@@ -42,6 +61,14 @@ type CustomerTable table<Customer> key(id);
 
 type CustomerKeyLessTable table<Customer>;
 
+type PersonTable table<Person>;
+
+type EngineerTable table<Engineer>;
+
+type InternTable table<Intern>;
+
+type PersonAnyTable table<map<any>>;
```
Comment (pcnfernando) [inline langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal:70]: Shall we do use a map<string> as table constrained and try to add () as well

Comment (lasinicl) [reply langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal:70]: It's already there. 
https://github.com/ballerina-platform/ballerina-lang/blob/b223b7551f1aa5f3c532a6457e3037f4b4722c6b/langlib/langlib-test/src/test/resources/test-src/tablelib_test.bal#L367
