### PR TITLE
Provide support for multiple connectors

### LINKED ISSUE #35936: [Shell] Provide support for multiple connectors
**Description:**

Ballerina shell produce errors if we use multiple connectors.
For example, if we use googleapis.sheets connector after using github connector shell produces following error.

```shell
panic: java.lang.ClassCastException {"message":"class io.ballerina.stdlib.http.transport.message.HttpCarbonResponse cannot be cast to class io.ballerina.stdlib.http.transport.message.HttpCarbonMessage (io.ballerina.stdlib.http.transport.message.HttpCarbonResponse is in unnamed module of loader java.net.URLClassLoader @72aa6a00; io.ballerina.stdlib.http.transport.message.HttpCarbonMessage is in unnamed module of loader java.net.URLClassLoader @68bef3df)"}
| Execution aborted due to unhandled runtime error.
```

**Steps to reproduce:**
image

### PR DESCRIPTION
**Pull request by DamithaSenevirathne**
Fixes #35936 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/JarResolver.java [hunk 1]
```diff
@@ -117,6 +117,19 @@ public Collection<JarLibrary> getJarFilePathsRequiredForExecution() {
         return jarFiles;
     }
 
+    public ClassLoader getClassLoaderWithRequiredJarFilesForExecutionWithoutMainJar() {
```
Comment (azinneera) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/JarResolver.java:120]: Shall we move this to the shell module without keeping it in the Jar Resolver? 
JarResolver is expected to use by any API user and this method might confuse them since it's specific to the shell implementation.

Comment (DamithaSenevirathne) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/JarResolver.java]: Updated in 0aad905fa9e08d086e402eea84e5cbe83d5f369f

**Review by azinneera — DISMISSED** [review]
LGTM

**Review by mohanvive — APPROVED** [review]
