### PR TITLE
Fix incorrect results with int and string subtypes type test expression

### LINKED ISSUE #30368: `Type Test Expression` provides incorrect results for `int` and `string` subtypes arrays and maps
**Description:**
$Subject

**Steps to reproduce:**
```
public function main() {

    byte[] a = [];
    any b = a;
    boolean c = b is int[];
    io:println(c); //prints true as expected

    int:Signed32[] g = [];
    any h =  g;
    boolean i = h is int[];
    io:println(i); // prints false, expected true

    string:Char[] s = [];
    any k = s;
    boolean l = k is string[];
    io:println(l); // prints false, expected true

    map<string:Char> m = {};
    any n = m;
    boolean p = n is map<string>;
    io:println(p); // prints false, expected true

}
```

**Affected Versions:**
slalpha5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Team/jballerina

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #30368

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 1]
```diff
@@ -629,7 +629,32 @@ public static boolean checkIsType(Type sourceType, Type targetType, List<TypePai
                 if (sourceTypeTag == TypeTags.FINITE_TYPE_TAG) {
                     return isFiniteTypeMatch((BFiniteType) sourceType, targetType);
                 }
-                return sourceTypeTag == TypeTags.BYTE_TAG || sourceTypeTag == TypeTags.INT_TAG;
+                return sourceTypeTag == TypeTags.BYTE_TAG || TypeTags.isIntegerTypeTag(sourceTypeTag);
+            case TypeTags.SIGNED16_INT_TAG:
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:633]: Can we put sourceTypeTag < TypeTags.SIGNED16_INT_TAG

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 2]
```diff
@@ -629,7 +629,32 @@ public static boolean checkIsType(Type sourceType, Type targetType, List<TypePai
...
+                if (sourceTypeTag == TypeTags.FINITE_TYPE_TAG) {
+                    return isFiniteTypeMatch((BFiniteType) sourceType, targetType);
+                }
+                return sourceTypeTag == TypeTags.BYTE_TAG || sourceTypeTag == TypeTags.UNSIGNED8_INT_TAG ||
+                        sourceTypeTag == TypeTags.SIGNED8_INT_TAG || sourceTypeTag == TypeTags.SIGNED16_INT_TAG;
```
Comment (riyafa) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:638]: yes like @warunalakshitha  comment we can replace this return statement with the `sourceTypeTag < TypeTags.SIGNED16_INT_TAG` check. Similarly we can replace in other places as well.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 3]
```diff
@@ -629,7 +629,32 @@ public static boolean checkIsType(Type sourceType, Type targetType, List<TypePai
...
+            case TypeTags.SIGNED32_INT_TAG:
+                if (sourceTypeTag == TypeTags.FINITE_TYPE_TAG) {
+                    return isFiniteTypeMatch((BFiniteType) sourceType, targetType);
+                }
```
Comment (riyafa) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:642]: can we move this check before the switch statement if this is repeating for most of the cases ?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal [hunk 4]
```diff
@@ -27,6 +28,92 @@ function stringtoint(string value) returns int|error {
...
+    any a = arr;
+    test:assertEquals(a is int[], true);
+    int[] intArray = <int[]> a;
+    test:assertEquals(intArray, [1, 128, 255]);
+}
+
+function testSigned32IntArrayToIntArray() {
+    int:Signed32[] arr = [1, 2, 3];
+    any a =  arr;
+    test:assertEquals(a is int[], true);
```
Comment (riyafa) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal:42]: we can use 
```suggestion
    test:assertTrue(a is int[]);
```
Shall we fix in all places?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java (hunk 1 above)
Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:627]: Addresses with https://github.com/ballerina-platform/ballerina-lang/pull/31302/commits/49f13546fca88ec1d4bcfc36d1d6ba6b7de801ce

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java (hunk 2 above)
Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java]: Addressed with the commit https://github.com/ballerina-platform/ballerina-lang/pull/31302/commits/49f13546fca88ec1d4bcfc36d1d6ba6b7de801ce

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java (hunk 3 above)
Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java]: Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/31302/commits/49f13546fca88ec1d4bcfc36d1d6ba6b7de801ce

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal (hunk 4 above)
Comment (gabilang) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal]: Addressed with the commit https://github.com/ballerina-platform/ballerina-lang/pull/31302/commits/b142a5545959805480887f83416b92b994b128bc

**Review by warunalakshitha — COMMENTED** [review]
LGTM

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal [hunk 5]
```diff
@@ -27,6 +28,133 @@ function stringtoint(string value) returns int|error {
     return result;
 }
 
+function testByteArrayToIntArray() {
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal:31]: Shall we add one test case covering all cases. Separate functions are not clear as well.

Comment (warunalakshitha) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal:31]:
```
function testIntArrayCasting() {
    byte[] byteArray = [1, 128, 255];
    int:Signed8[] signed8Array = [-128, 0, 127];
    int:Signed16[] signed16Array = [-128, 0, 127];
    int:Signed32[] signed32Array = [-128, 0, 127];
    int:Unsigned8[] unsigned8Array = [5, 55, 255];
    int:Unsigned16[] unsigned16Array = [5, 5050, 65535];
    int:Unsigned32[] unsigned32Array = [50, 5050, 655355];

    any anyByteArray = byteArray;
    any anySigned8Array = signed8Array;
    any anySigned16Array = signed16Array;
    any anySigned32Array = signed32Array;
    any anyUnsigned8Array = unsigned8Array;
    any anyUsigned16Array = unsigned16Array;
    any anyUsigned32Array = unsigned32Array;

    //byte
    test:assertEquals(<int[]>anyByteArray, [1, 128, 255]);
    test:assertEquals(<int:Signed16[]>anyByteArray, [1, 128, 255]);
    test:assertEquals(<int:Signed16[]>anyByteArray, [1, 128, 255]);
    test:assertEquals(<int:Signed32[]>anyByteArray, [1, 128, 255]);
    test:assertEquals(<int:Unsigned8[]>anyByteArray, [1, 128, 255]);
    test:assertEquals(<int:Unsigned16[]>anyByteArray, [1, 128, 255]);
    test:assertEquals(<int:Unsigned32[]>anyByteArray, [1, 128, 255]);

    //Signed8
    test:assertEquals(<int[]>anySigned8Array, [1, 128, 255]);
    test:assertEquals(<int:Signed16[]>anySigned8Array, [1, 128, 255]);
    test:assertEquals(<int:Signed16[]>anySigned8Array, [1, 128, 255]);
    test:assertEquals(<int:Signed32[]>anySigned8Array, [1, 128, 255]);
    test:assertEquals(<int:Unsigned8[]>anySigned8Array, [1, 128, 255]);
    test:assertEquals(<int:Unsigned16[]>anySigned8Array, [1, 128, 255]);
    test:assertEquals(<int:Unsigned32[]>anySigned8Array, [1, 128, 255]);

    // Signed16, Signed32,Unsigned8, Unsigned16, Unsigned32
}
```

Comment (gabilang) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type-casting.bal]: Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/31302/commits/991078ac38c0c57202f4c1fac46b53e70911080a

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 6]
```diff
@@ -599,37 +599,43 @@ public static boolean checkIsType(Type sourceType, Type targetType, List<TypePai
             return isUnionTypeMatch((BUnionType) sourceType, targetType, unresolvedTypes);
         }
 
+        if (sourceTypeTag == TypeTags.FINITE_TYPE_TAG &&
+                (targetTypeTag <= TypeTags.NULL_TAG || targetTypeTag == TypeTags.XML_TEXT_TAG)) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:603]: should we check only XML_TEXT_TAG here? Should we use TypeTags.isXMLTypeTag?

Comment (warunalakshitha) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:603]: Do we have tests for xml?

Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:603]: `xml:Text` is an inherently immutable type and other `xml` subtypes are selectively immutable. IINM, the finite type is considered as inherently immutable type and the value spaces of finite types should contain inherently immutable types only. So, we do not need to have other `xml` subtypes under this check.

**Review by warunalakshitha — APPROVED** [review]
