### PR TITLE
Fix `TypeChecker.checkIsLikeOnValue` for xml subtypes

### LINKED ISSUE #39650: [Task]: Fix `TypeChecker.checkIsLikeOnValue` for xml subtypes
### Description

Currently we don't consider about xml constraints which may contain combination of xml subtypes and readonly. Hence bugs are possible.
https://github.com/ballerina-platform/ballerina-lang/blob/51be5437ca5400b312019aaff450a5560812b52e/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java#L2284-#L2296

Need to check and rewrite `checkIsLikeXmlValueSingleton` & `checkIsLikeXMLSequenceType` if needed.

### Describe your task(s)

```bal
type JsonUnion xml|json;

public function main() {
    xml a  = xml `<a>1</a>`;
    JsonUnion & readonly j = checkpanic a.cloneWithType(); // checkIsLikeOnValue a on xml becomes false

    'xml:Element elem1 = xml `<hello>xml element 1</hello>`;
    'xml:Element elem2 = xml `<hello>xml element 2</hello>`;
    xml concat = 'xml:concat(elem1, elem2);
    io:println(concat);
    xml<'xml:Comment> & readonly elementSequence = <xml<'xml:Comment> & readonly> concat;

    'xml:Element elem3 = xml `<hello>xml element 1</hello>`;
    'xml:Comment comment = xml `<!-- this is a comment text -->`;
    xml<'xml:Element & readonly|'xml:Text> seq = <xml<'xml:Element & readonly|'xml:Text>> 'xml:concat(elem3, comment);
}
```

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #39650

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 1]
```diff
@@ -2325,73 +2327,83 @@ private static XmlNodeType getXmlNodeType(Type type) {
...
 
-        if (xmlSource.getNodeType() == nodeType) {
-            return true;
+        return false;
+    }
+
+    private static void populateTargetXmlNodeTypes(Set<XmlNodeType> nodeTypes, Type targetType) {
+        // there are only 4 xml subtypes
+        if (nodeTypes.size() == 4) {
+            return;
```
Comment (Nadeeshan96) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2355]: Will add a test to cover this

**Review by warunalakshitha — APPROVED** [review]
LGTM
