### PR TITLE
Fix error on accessing a constant list defined in a module

### LINKED ISSUE #41901: [Bug]: Error when accessing a const array defined in a module
### Description

Compilation error occurs when accessing an array defined in a module

### Steps to Reproduce

Consider the following code with a module `mod`
 proj.mod
```ballerina
public const string[] NAME = ["name"];
```

proj
The main file `main.bal`,
```ballerina
import proj.mod;

public function main() {
    string[] _ = [...mod:NAME];
}
```

This gives the following error, 
```
ERROR [main.bal:(4:22,4:30)] attempt to refer to non-accessible symbol ''
```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by poorna2152**
Fixes #41901

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaTest.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+import org.ballerinalang.test.BRunUtil;
+import org.ballerinalang.test.CompileResult;
+import org.testng.Assert;
+import org.testng.annotations.AfterClass;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.DataProvider;
+import org.testng.annotations.Test;
+
+/**
+ * Test cases for reading list constants.
```
Comment (nipunayf) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaTest.java:30]:
```suggestion
 * Test cases for reading list constants.
 * 
 * @since 2201.9.0
```

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/list-constant.bal [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+
+public const string[] l1 = ["a", "b", "c"];
+public const [int, string] l2 = [1, "d"];
+public const [int, [string, int]] l3 = [1, ["e", 2]];
+public const int[][] l4 = [[1, 2, 3], [4, 5, 6]];
+public const boolean[length] l5 = [true, false, true];
+public const IntArr l6 = [1, 2, 3];
+public const [int, string...] l7 = [1, "f", "g"];
+public const (string|int)[][] l8 = [[1, "2", 3], [4, 5, 6]];
+public const [(string[]|int[])...] l9 = [[1, 2, 3], ["4", "5", "6"]];
```
Comment (prakanth97) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/list-constant.bal:13]: Shall we add negative case as well?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java [hunk 3]
```diff
@@ -1355,8 +1355,9 @@ private BType checkTupleType(BTupleType tupleType, BLangListConstructorExpr list
     }
 
     private BTupleType createNewTupleType(Location pos, List<BType> memberTypes, AnalyzerData data) {
-        BTypeSymbol tupleTypeSymbol = Symbols.createTypeSymbol(SymTag.TUPLE_TYPE, 0, Names.EMPTY,
-                data.env.enclPkg.symbol.pkgID, null, data.env.scope.owner, pos, SOURCE);
+        BTypeSymbol tupleTypeSymbol =
+                Symbols.createTypeSymbol(SymTag.TUPLE_TYPE, data.constantSymbol.flags, Names.EMPTY,
+                        data.env.enclPkg.symbol.pkgID, null, data.env.scope.owner, pos, SOURCE);
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java:1360]: Here, By setting constant symbol flags to `type symbol`, we set the `constant` flag with the same type symbol as well. Is it correct?

**Comment by chiranSachintha** [comment]
In the current implementation, symbol accessibility is verified using the type symbol((https://github.com/ballerina-platform/ballerina-lang/blob/788e1426310fcba84176d93f34b6933ec8ecaf58/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java#L3538)). IMO, this approach is not correct, we should use the symbol of that node, rather than using the symbol of the type linked to that node. @MaryamZi WDYT?

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list-literal-constant.bal
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list-literal-constant.bal:1]: Add the licence header.

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list_constant_negative.bal [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+function testInvalidUpdates() {
+    var a = foo:l1;
+    a[0] = "1";
+    a.push("2");
+
+    var b = foo:l7;
+    b.push("l7");
+}
+
+function testInvalidAccess() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list_constant_negative.bal:17]: Is the name correct? May be confused with member access?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaTest.java [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+        compileResult = BCompileUtil.compile("test-src/bala/test_bala/constant/list-literal-constant.bal");
+    }
+
+    @Test(dataProvider = "listAccessTestDataProvider")
+    public void testConstantListAccess(String testCase) {
+        try {
+            BRunUtil.invoke(compileResult, testCase);
+        } catch (Exception e) {
+            Assert.fail(testCase + " test case failed.");
+        }
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaTest.java:50]: IMO, we don't need to handle like this. From the data provider iteration, we can figure out which test failed.

Also, we loose actual failure info with this, since `e` is not used.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaNegativeTest.java [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+        BAssertUtil.validateError(compileResult, i++, "incompatible types: expected '(1|\"f\"|\"g\")', found 'string'",
+                14, 12);
+        BAssertUtil.validateError(compileResult, i++, "undefined symbol 'l10'", 18, 17);
+        BAssertUtil.validateError(compileResult, i++, "undefined symbol 'l11'", 19, 18);
+        Assert.assertEquals(compileResult.getErrorCount(), i);
+    }
+
+}
+
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaNegativeTest.java:66]: Please check formatting and remove unnecessary lines.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java (hunk 3 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java:1360]: In offline, we discuss use the `public` flag instead of setting all the flags in the `constantSymbol` to type symbol. Here, we need to verify whether the public flag is present in the `constantSymbol`.

Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java:1360]: In the symbol resolver we have a check to find out whether the constant we are accessing is Public or not. Thus at this stage we might not need the check to see if the public flag is present.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaNegativeTest.java [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+import org.testng.Assert;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Test;
+
+/**
+ * Negative Bala test cases for list constants.
+ *
+ * @since 2201.9.0
+ */
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaNegativeTest.java:32]:
```suggestion
```

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list-literal-constant.bal [hunk 8]
```diff
@@ -0,0 +1,37 @@
+import testorg/foo;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list-literal-constant.bal:1]: Missing the licence headers.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java [hunk 9]
```diff
@@ -1355,8 +1355,9 @@ private BType checkTupleType(BTupleType tupleType, BLangListConstructorExpr list
     }
 
     private BTupleType createNewTupleType(Location pos, List<BType> memberTypes, AnalyzerData data) {
-        BTypeSymbol tupleTypeSymbol = Symbols.createTypeSymbol(SymTag.TUPLE_TYPE, 0, Names.EMPTY,
-                data.env.enclPkg.symbol.pkgID, null, data.env.scope.owner, pos, SOURCE);
+        BTypeSymbol tupleTypeSymbol =
+                Symbols.createTypeSymbol(SymTag.TUPLE_TYPE, Flags.PUBLIC, Names.EMPTY,
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java:1359]: Why we set the flag to to always public, don't we need to infer from the `module-const-decl` node?

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list_constant_negative.bal [hunk 10]
```diff
@@ -0,0 +1,36 @@
+// Copyright (c) 2023 WSO2 LLC. (http://www.wso2.com).
```
Comment (prakanth97) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list_constant_negative.bal:1]:
```suggestion
// Copyright (c) 2024 WSO2 LLC. (http://www.wso2.com).
```
check other places as well.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java (hunk 9 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java:1359]: Can you check behaviour of `createNewRecordType` method in the ConstantTypeChecker. Seems like there also we set the flag to 0. 

I checked this case `public const A = {a: "1", b: 2};` and I did not get the mentioned error.

Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java:1359]: The reason we set the flag to public was because we didn't want to set flags in the TypeSymbol using the flags in the variable symbol. And the reason it is always public was that, if the variable was not public it would have been caught in earlier phases. 
In the `createNewRecordType` function, `BRecordTypeSymbol` that we pass is also created [here](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java#L2060) using the flags in the symbol of the variable rather than the type symbol itself. May be we need to address both of these places to have consistent behaviour. Either we set the flags using the flags in the symbol or do a check to see if the public flag is present and set the flag there. WDYT @prakanth97 @chiranSachintha ?

Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java:1359]: As per the offline discussion we had, we decided to set the flag in the type symbol to `public` at this stage for both the occasions. We should ideally be able to remove the check [here](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java#L3538). This [issue](https://github.com/ballerina-platform/ballerina-lang/issues/42300) is created to track the task.

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/list_constant.bal [hunk 11]
```diff
@@ -0,0 +1,29 @@
...
+
+public const string[] l1 = ["a", "b", "c"];
+public const [int, string] l2 = [1, "d"];
+public const [int, [string, int]] l3 = [1, ["e", 2]];
+public const int[][] l4 = [[1, 2, 3], [4, 5, 6]];
+public const boolean[length] l5 = [true, false, true];
+public const IntArr l6 = [1, 2, 3];
+public const [int, string...] l7 = [1, "f", "g"];
+public const (string|int)[][] l8 = [[1, "2", 3], [4, 5, 6]];
+public const [(string[]|int[])...] l9 = [[1, 2, 3], ["4", "5", "6"]];
```
Comment (prakanth97) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/list_constant.bal:29]: Shall we add few negative tests where const is not public?

Comment (poorna2152) [reply tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project/list_constant.bal:29]: Added

**Review by prakanth97 — DISMISSED** [review]
LGTM

**Review by chiranSachintha — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list_constant_negative.bal [hunk 12]
```diff
@@ -0,0 +1,42 @@
...
+function testUndefinedMemberAccess() {
+    float[] _ = foo:l13;
+    string[] _ = foo:l14;
+}
+
+function testNonPublicConstAccess() {
+    int[] _ = foo:l10;
+    [int, int, boolean] _ = foo:l11;
+    string[] _ = foo:l12;
+}
```
Comment (chiranSachintha) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list_constant_negative.bal:42]: When considering this type of scenarios, there's no need to explicitly define the type; we can simply express those as,
`_ = foo:l13;`

Comment (poorna2152) [reply tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list_constant_negative.bal]: Updated

**Review by chiranSachintha — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list_constant_negative.bal [hunk 13]
```diff
@@ -0,0 +1,42 @@
...
+function testInvalidUpdates() {
+    var a = foo:l1;
+    a[0] = "1";
+    a.push("2");
+
+    var b = foo:l7;
+    b.push("l7");
+}
+
+function testUndefinedMemberAccess() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list_constant_negative.bal:33]: Do you mean undefined construct?

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/bala/test_bala/constant/list_constant_negative.bal:33]: Or undefined symbol.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java [hunk 14]
```diff
@@ -2057,7 +2059,7 @@ private BRecordTypeSymbol createRecordTypeSymbol(PackageID pkgID, Location locat
         SymbolEnv env = data.env;
         Name genName = Names.fromString(anonymousModelHelper.getNextAnonymousTypeKey(pkgID,
                 data.anonTypeNameSuffixes));
-        BRecordTypeSymbol recordSymbol = Symbols.createRecordSymbol(data.constantSymbol.flags, genName,
+        BRecordTypeSymbol recordSymbol = Symbols.createRecordSymbol(Flags.PUBLIC, genName,
```
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java]: Alternatively, we can add the public flag to the flag set and set that.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaTest.java [hunk 15]
```diff
@@ -0,0 +1,98 @@
...
+                "test2DTupleAccess",
+                "test2DArrayAccess",
+                "testFixedLengthArrayAccess",
+                "testArrayWithRestAccess",
+                "test2DUnionArrayAccess"
+        };
+    }
+
+    @Test
+    public void testNegativeConstantListAccess() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaTest.java:64]: Generally we add negative at the end

```suggestion
    public void testConstantListAccessNegative() {
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaTest.java [hunk 16]
```diff
@@ -0,0 +1,98 @@
...
+        compileResult = BCompileUtil.compile("test-src/bala/test_bala/constant/list_literal_constant.bal");
+    }
+
+    @Test(dataProvider = "listAccessTestDataProvider")
+    public void testConstantListAccess(String testCase) {
+        BRunUtil.invoke(compileResult, testCase);
+    }
+
+    @DataProvider(name = "listAccessTestDataProvider")
+    public Object[] listAccessTestDataProvider() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/constant/ListConstantInBalaTest.java:51]:
```suggestion
    public Object[] constantListAccessTestDataProvider() {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java]: This change was done to maintain the consistency between the tuple and record types. Not because the tests were failing. Decided to keep this as it is. Since changing this is effectively removing some other flags present.

**Review by MaryamZi — APPROVED** [review]
