### PR TITLE
[Master] Remove re from reserved words

### LINKED ISSUE #38492: [Bug]: Remove `re` from reserved words
### Description

$title

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by prakanth97**
## Purpose

Fixes #38492

## Approach
Check for back tick after `re` keyword and then create syntax token for `re` keyword, instead of consider `re` as reserved keyword.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by rdulmina — APPROVED** [review]

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java [hunk 1]
```diff
@@ -1047,6 +1050,50 @@ private STToken processIdentifierOrKeyword() {
...
+                    return nextChar;
+                default:
+                    return nextChar;
+            }
+            nextChar = reader.peek(lookaheadCount);
+        }
+        return nextChar;
+    }
+
+    private int skipComment(int lookaheadCount) {
```
Comment (gimantha) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaLexer.java:1080]: @rdulmina Can we not reuse the same logic we used to skip similar cases in xml and string templates without using a new method?
