### PR TITLE
Fix issue in parsing tuple type or list constructor

### LINKED ISSUE #33824: ClasscastException in NodeTransformer when compiling incorrect code.
Consider the code below. 

```ballerina
type Foo record {|
    int id;
|};

type Bar record {|
    string name;
|};

function myfunc() returns Foo|[Foo[], Bar]? {

}

public function main() {
    Foo|[open()], Bar]? res = myfunc();
}

function open() {

}
```

Compiling the above code gives below exception.

```
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation cannot be cast to class org.wso2.ballerinalang.compiler.tree.types.BLangType (org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation and org.wso2.ballerinalang.compiler.tree.types.BLangType are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:5446)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:998)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
        at io.ballerina.compiler.syntax.tree.TupleTypeDescriptorNode.apply(TupleTypeDescriptorNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:5446)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:911)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
        at io.ballerina.compiler.syntax.tree.UnionTypeDescriptorNode.apply(UnionTypeDescriptorNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createTypeNode(BLangNodeTransformer.java:5446)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.initializeBLangVariable(BLangNodeTransformer.java:2851)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2811)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2773)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
        at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:4961)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1544)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
        at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.populateFunctionNode(BLangNodeTransformer.java:1451)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1431)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1409)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
        at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:608)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:474)
        at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:507)
        at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:111)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:378)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:341)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:199)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:111)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:100)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
        at io.ballerina.projects.Package.getCompilation(Package.java:140)
        at org.ballerinalang.test.BCompileUtil.jBallerinaBackend(BCompileUtil.java:185)
        at org.ballerinalang.test.BCompileUtil.compile(BCompileUtil.java:80)

```

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$title

Fixes #33824

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by lochana-chathura** [comment]
```
function foo() {
     ([Foo, Person] | () | error) res = wait f;
}
```
Above cannot parse it seems

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -15108,7 +15112,7 @@ private STNode parseTypeDescOrExpr(List<STNode> qualifiers) {
                 return parseTypeDescOrExprRhs(typeOrExpr);
             case OPEN_BRACKET_TOKEN:
                 reportInvalidQualifierList(qualifiers);
-                typeOrExpr = parseTupleTypeDescOrExprStartsWithOpenBracket();
+                typeOrExpr = parseTupleTypeDescOrListConstructor(STNodeFactory.createEmptyNode());
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:15115]:
```suggestion
                typeOrExpr = parseTupleTypeDescOrListConstructor(STNodeFactory.createEmptyNodeList());
```
the other place also.

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 2]
```diff
@@ -18517,7 +18500,9 @@ private STNode getBindingPattern(STNode ambiguousNode) {
     }
 
     private STNode getExpression(STNode ambiguousNode) {
-        if (isEmpty(ambiguousNode)) {
+        if (isEmpty(ambiguousNode) || 
+                isDefiniteExpr(ambiguousNode.kind) && ambiguousNode.kind != SyntaxKind.INDEXED_EXPRESSION ||
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:18504]:
```suggestion
                (isDefiniteExpr(ambiguousNode.kind) && ambiguousNode.kind != SyntaxKind.INDEXED_EXPRESSION) || 
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 1 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java]: Updated thanx

**Review by lochana-chathura — APPROVED** [review]
There are codev warnings. Not sure if we can find test cases for them. Hence approving

**Comment by lochana-chathura** [comment]
> function foo() {
>      ([Foo, Person] | () | error) res = wait f;
> }

shall we add a parser test case for this since it is not covered?

**Comment by rdulmina** [comment]
> > function foo() {
> > ([Foo, Person] | () | error) res = wait f;
> > }
> 
> shall we add a parser test case for this since it is not covered?

Added

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 3]
```diff
@@ -14938,7 +14938,8 @@ private STNode parseTypedBindingPatternOrExprRhs(STNode typeOrExpr, boolean allo
                 }
 
                 // If the next token is an equal, then it is typedBP with union/intersection type and missing var name
-                if (peek().kind == SyntaxKind.EQUAL_TOKEN) {
+                if (peek().kind == SyntaxKind.EQUAL_TOKEN && 
+                        (!isDefiniteExpr(typeOrExpr.kind) && !isDefiniteExpr(rhsTypedBPOrExpr.kind))) {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:14942]: Do we need this change here? since we call,
```
lhsType = getTypeDescFromExpr(lhsType);
rhsType = getTypeDescFromExpr(rhsType);
```
inside `createCaptureBPWithMissingVarName()` ?

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java]: removed

**Review by lochana-chathura — APPROVED** [review]
