### PR TITLE
Fix CCE and NPE for Diagnostics in Anonymous Functions Params

### LINKED ISSUE #33616: Exceptions in `SymbolEnter` and `EnvironmentResolver` for Anonymous Function Expressions
**Description:**
### 1. Case 1
Consider the following code segment: 
```
int y = 10;

var fn1 = function (astring s) {
    int z = y + 1;
};
```
The above code causes the following Exception

<details>
SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.types.BNoType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BInvokableType (org.wso2.ballerinalang.compiler.semantics.model.types.BNoType and org.wso2.ballerinalang.compiler.semantics.model.types.BInvokableType are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BNoType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BInvokableType (org.wso2.ballerinalang.compiler.semantics.model.types.BNoType and org.wso2.ballerinalang.compiler.semantics.model.types.BInvokableType are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveAndSetFunctionTypeFromRHSLambda(SymbolEnter.java:4879)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:396)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:323)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:280)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:273)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:397)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:349)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:201)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:111)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:100)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:214)
	at io.ballerina.projects.Package.getCompilation(Package.java:140)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:284)
	at org.ballerinalang.langserver.util.LSClientUtil.chekAndRegisterCommands(LSClientUtil.java:78)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:551)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
</details>

### 2. Case 2

Change the following code segment to the above-mentioned code at **case 1** (by changing the function parameter from `string s` to `astring s`).
```
int y = 10;

var fn1 = function (string s) {
    int z = y + 1;
};
```
The following exception can be observed:
<details>
Operation 'text/codeAction' failed! {uri: '/path/to/main.bal', [21:22]- [21:22], error: 'java.lang.NullPointerException, org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)'}
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.EnvironmentResolver.visit(EnvironmentResolver.java:144)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at io.ballerina.compiler.api.impl.EnvironmentResolver.acceptNode(EnvironmentResolver.java:624)
	at io.ballerina.compiler.api.impl.EnvironmentResolver.lambda$visit$1(EnvironmentResolver.java:119)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.ballerina.compiler.api.impl.EnvironmentResolver.visit(EnvironmentResolver.java:119)
	at org.wso2.ballerinalang.compiler.tree.BLangCompilationUnit.accept(BLangCompilationUnit.java:101)
	at io.ballerina.compiler.api.impl.EnvironmentResolver.lookUp(EnvironmentResolver.java:111)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.visibleSymbols(BallerinaSemanticModel.java:119)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.visibleSymbols(AbstractDocumentServiceContext.java:149)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getMatchedTypeSymbol(CodeActionRouter.java:142)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:72)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:157)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:328)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
</details>

**Remarks:**
Related to #33493

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #33616

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by pcnfernando — APPROVED** [review]
LGTM

**Comment by pcnfernando** [comment]
Probably we can add some JUnit negative tests as well

**Comment by mohanvive** [comment]
@sanjana Can this be verified with a compiler JUnit test?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 1]
```diff
@@ -4876,12 +4876,18 @@ private boolean isSameImport(BLangImportPackage importPkgNode, BPackageSymbol im
...
+        BType resolvedInvokableType = symResolver.createInvokableType(function.getParameters(),
+                                                                      function.restParam,
+                                                                      function.returnTypeNode,
+                                                                      Flags.asMask(variable.flagSet),
+                                                                      env,
+                                                                      function.pos);
+
+        if (resolvedInvokableType.tag == TypeTags.NONE) {
+            return;
+        }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:4888]: By doing this we set the type of that variable to `other`. If the type of the parameter is not defined we need to set the type of that parameter to `other`. Isn't it?
As an example 
```ballerina
var fn1 = function (astring s) returns int {
    int z = 1;
    return z;
};
```
According to the above change, we set the type of `fn1`as `other`. right? But IMO the type of `fn1` should be `function(other) returns int`
Any thoughts @MaryamZi ?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:4888]: Yeah, ideally the behaviour (errors) for both the following should be the same.

```ballerina
var fn1 = function (astring s) returns int {
    int z = 1;
    return z;
};

boolean _  = fn1("");

function fn2(astring s) returns int => 1;

boolean _  = fn2("");
```

With this change we get `undefined function 'fn1'` and don't get `incompatible types: expected 'boolean', found 'int'`.

This will require changes to `org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver#createInvokableType` though. I think we can fix this separately also since the current fix will prevent a crash.

Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:4888]: Will be addressed in #33836
