### PR TITLE
Fix issue in createFile() error message

### LINKED ISSUE #17795: system createFile error message should be descriptive
**Description:**

`ballerina/system` function `system:createFile()` function returns string or error, but the error message is just the path of the file, the user provided. The error message should be descripive about what went wrong.

### PR DESCRIPTION
**Pull request by aashikam**
Fixes #17795

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/CreateFile.java [hunk 1]
```diff
@@ -58,12 +59,18 @@ public static Object createFile(Strand strand, String path) {
             String msg = "Permission denied. Failed to create the file: " + path;
             log.error(msg, e);
             return SystemUtils.getBallerinaError(SystemConstants.PERMISSION_ERROR, msg);
+        } catch (NoSuchFileException e) {
+            String msg = "The file does not exist in path " + path;
+            log.error(msg, e);
```
Comment (wggihan) [inline stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/CreateFile.java]: We don't need to log this. This is a straight forward issue.

Comment (aashikam) [reply stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/CreateFile.java]: Resolved
