### PR TITLE
Fix position trasformation for all nodes having metadata

### LINKED ISSUE #24916: Fix position trasformation for all nodes having metadata
**Description:**
* For parent nodes having metadata, their line range should not include the metadata. 
It has been fixed for few nodes in the BLangNodeTransformer. Have to fix it in the other places as well. 

* Following method can be used instead of `getPosition()` when transforming positions of top level nodes
https://github.com/ballerina-platform/ballerina-lang/blob/6cd7340fc21d08d996b9eb5703b4e7c5944c415f/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java#L465 . 

**Suggested Labels:**
Component/Parser, Type/Bug

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #24916 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationNegativeTest.java [hunk 1]
```diff
@@ -40,11 +40,11 @@ public void testDeprecationAnnotation() {
         BAssertUtil.validateError(compileResult, i++, "constructs annotated as '@deprecated' must have 'Deprecated' " +
                 "documentation", 4, 1);
         BAssertUtil.validateError(compileResult, i++, "invalid documentation: 'Deprecated' documentation is only " +
-                "allowed on constructs annotated as '@deprecated'", 10, 1);
+                "allowed on constructs annotated as '@deprecated'", 8, 1);
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/DeprecationAnnotationNegativeTest.java:43]: Consider the error msg: 
`invalid documentation: 'Deprecated' documentation is only allowed on constructs annotated as '@deprecated' `
```
# Define a type
# # Deprecated *(new warn line)*
# This type is deprecated
public type Foo CONST1|CONST2; *(old warn line)*
```
