### PR TITLE
Fix native build for native build-option from Ballerina.toml 

### LINKED ISSUE #40717: [Bug]: `bal build/test --native` fail to generate an image when value is configured through Ballerina.toml
### Description

Even though `native=true` is configured via Ballerina.toml. Native image generation fails to generate an image. CLI output is as follows

```
Compiling source
        main.bal

Running Tests

        main.bal
```

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
Related to #40604
Fixes #40717

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by Dilhasha — APPROVED** [review]

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/TestCommand.java [hunk 1]
```diff
@@ -331,6 +321,11 @@ public void execute() {
             this.outStream.println("WARNING: Code coverage generation is not supported with Ballerina native test");
         }
 
+        if (!project.buildOptions().nativeImage() && !project.buildOptions().graalVMBuildOptions().isEmpty()) {
```
Comment (Dilhasha) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/TestCommand.java:324]: Does this cover the case where user passes only the CLI flag?

Comment (Thevakumar-Luheerathan) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/TestCommand.java:324]: This is done after we merge both cli-build-options and ballerina-toml-build-options. So...This condition will be evaluated against the combination

**Review by Dilhasha — APPROVED** [review]
