### PR TITLE
Update stream lib, restrict stream constraint to pure type and fix type param analysis for streams

### LINKED ISSUE #13203: [Spec Deviation] Stream constraint type needs to be a pure type
**Description:**
As per the spec (v0.990:2019-01-16 - page 29), "A value of type stream<T> is a distributor for values of type T: when a value v of type T is put into the stream, a function will be called for each subscriber to the stream with v as an argument. **T must be a pure type**"

Currently, any type is allowed as the constraint type for a stream.

**Affected Versions:**
0.990.2

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$title.

This PR also updates the type param analysis logic for function params to check for contravariance. 

Fixes #13203, #16759

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java [hunk 1]
```diff
@@ -130,6 +129,7 @@
     public BRecordType detailType;
     public BConstructorSymbol errorConstructor;
     public BUnionType pureType;
+    public BType streamType = new BStreamType(TypeTags.STREAM, pureType, null);;
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java]: We don't need an assignment here.
