### PR TITLE
Fix class cast exceptions thrown by runtime

### LINKED ISSUE #31282: Runtime throw Class cast error when interop function return invalid value
**Description:**
Ballerina
```ballerina
public function acceptIntAnydataReturn() returns anydata= @java:Method {
    'class:"xyz",
    name:"acceptIntUnionReturn"
} external;
```

Java
```java

    public static Object acceptIntUnionReturn() {
                return new Module("ww","ww");
        }
    }

```
Error

error: java.lang.ClassCastException {"message":"class io.ballerina.runtime.api.Module cannot be cast to class io.ballerina.runtime.api.values.BValue (io.ballerina.runtime.api.Module and io.ballerina.runtime.api.values.BValue are in unnamed module of loader 'app')"}
        at waruna.project2.0_1_0:acceptIntAnydataReturn(main.bal:15)
           waruna.project2.0_1_0:interopWithAnydataReturn(main.bal:8)
           waruna.project2.0_1_0:main(main.bal:4)
```


```

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #31282

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 1]
```diff
@@ -258,6 +258,10 @@ public static boolean anyToJBoolean(Object sourceVal) {
      * @return true if the value belongs to the given type, false otherwise
      */
     public static boolean checkIsType(Object sourceVal, Type targetType) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:260]: This will impact on all checkIsType calls. Given issue only occurs for interop methods returning union types. Can we handle onlly those.

**Review by warunalakshitha — CHANGES_REQUESTED** [review]

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java [hunk 2]
```diff
@@ -240,11 +240,18 @@ public void testGetInvalidIntegerAsMixType() {
...
     @Test(expectedExceptions = {BLangRuntimeException.class},
-            expectedExceptionsMessageRegExp = "error: java.lang.ClassCastException.*")
+            expectedExceptionsMessageRegExp = "error: 'class java.lang.String' cannot be assigned to type 'anydata'.*")
     public void testInteropWithJavaStringReturn() {
         BRunUtil.invoke(result, "interopWithJavaStringReturn");
     }
 
+    @Test(expectedExceptions = {BLangRuntimeException.class},
+            expectedExceptionsMessageRegExp = "error: 'class io.ballerina.runtime.api.Module' cannot be " +
+                    "assigned to type 'anydata'.*")
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java:250]: Shall we assert full stack trace here.

Comment (gabilang) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java]: Addressed with 1cf6f59

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java [hunk 3]
```diff
@@ -173,6 +174,10 @@ public static Object acceptNothingInvalidAnyReturn() {
         return "invalid java string";
     }
 
+    public static List<String> acceptNothingInvalidAnydataReturn() {
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/StaticMethods.java:177]: shall we add a test which return unions of anydata ( int|string[]) and return int[] )

File: bvm/ballerina-runtime/src/main/resources/MessagesBundle_en_US.properties [hunk 4]
```diff
@@ -160,3 +160,4 @@ tuple.index.out.of.range = tuple index out of range: index: {0}, size: {1}
 illegal.array.insertion = array of length {0} cannot be expanded into array of length {1} without filler values
 java.null.reference = handle refers to Java null
 illegal.tuple.insertion = tuple of length {0} cannot be expanded into tuple of length {1} without filler values
+incompatible.type.assignment = ''{0}'' cannot be assigned to type ''{1}''
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/resources/MessagesBundle_en_US.properties:163]: We do not need to put this in here except any difference to MessagesBundle.properties message.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 5]
```diff
@@ -3087,6 +3087,14 @@ private static boolean containsType(Set<Object> valueSpace, Type type) {
         return true;
     }
 
+    public static Object handleAnydataValues(Object sourceVal, Type targetType) {
+        if (!(sourceVal == null || sourceVal instanceof Number || sourceVal instanceof BString ||
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:3091]: Shall we invert if condition

File: bvm/ballerina-runtime/src/main/resources/MessagesBundle_en_US.properties (hunk 4 above)
Comment (gabilang) [reply bvm/ballerina-runtime/src/main/resources/MessagesBundle_en_US.properties:163]: But most of the previously added messages also same in the both files. We are maintaining two message bundle properties for English and English(US) and they should reflect the native way of expressions of both languages. But US one is not being updated recently for some newly added error messages. Since it is there for a reason (might be for language selection), INS not adding to this is a bug.

Comment (warunalakshitha) [reply bvm/ballerina-runtime/src/main/resources/MessagesBundle_en_US.properties:163]: IMO we need this only if we need change different message to English(US) . If it is not there MessagesBundle.properties will used. Here we have same message in both files then no need.

**Review by warunalakshitha — APPROVED** [review]
LGTM
