### PR TITLE
Make "always evaluate to true" error a hint

### LINKED ISSUE #28285: Incorrect error with 'is'
This correct program:

```
import ballerina/io;

public function main() {
   boolean b = "str" is string;
   io:println(b);
}
```

gets rejected with the error:

```
ERROR [demo8.bal:(4:16,4:31)] unnecessary condition: expression will always evaluate to 'true'
```

### PR DESCRIPTION
**Pull request by gimantha**
Fixes #28285

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+ */
+package org.ballerinalang.util.diagnostic;
+
+import io.ballerina.tools.diagnostics.DiagnosticCode;
+import io.ballerina.tools.diagnostics.DiagnosticSeverity;
+
+/**
+ * This class contains a list of diagnostic hint codes.
+ *
+ * @since Swan Lake
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java:26]: IINM, we use `2.0.0` for this.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+ */
+public enum DiagnosticHintCode implements DiagnosticCode {
+
+    UNNECESSARY_CONDITION("BCE40000", "unnecessary.condition");
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java:30]: @dulajdilshan What does BCE stand for? If it's Ballerina Compiler Error, should we consider a different prefix for other categories of diagnostics?

**Comment by dulajdilshan** [comment]
Shall we add a uniqueness check for `DiagnosticHintCodes`? Just need to add a function. Have a look at this https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/test/java/org/ballerinalang/util/DiagnosticCodeTest.java

https://github.com/ballerina-platform/ballerina-lang/blob/a9e90ceabc096524cd7d962a257931b751dc177d/compiler/ballerina-lang/src/test/java/org/ballerinalang/util/DiagnosticCodeTest.java#L46

**Comment by pubudu91** [comment]
Wasn't there existing negative tests for this particular error? 🤔

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java (hunk 2 above)
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java:30]: Yes. The earlier discussions were only to separate errors/warning/hints from the compiler side and the side of the extensions (having a different prefix for extensions). However, I'm +1 for having a different prefix for hints. (Ex: `BCH`). Also, this can be followed for warning too.

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java:30]: Shall we raise this in Slack and check with others as well?

Comment (gimantha) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticHintCode.java:30]: @dulajdilshan 

> Wasn't there existing negative tests for this particular error? 🤔

Yes. there are.. :) i will fix them.. thats why pr fails

**Comment by gimantha** [comment]
> Wasn't there existing negative tests for this particular error? 🤔

Yes. Thats why the pr fails.. will fix them :)
