### PR TITLE
Use simple foreach instead of unnecessary streamed foreach 

### LINKED ISSUE #18858: Fix the formatting of the `ballerina build` output
Screen Shot 2019-09-07 at 5 09 34 PM

Refer the attached image: The output of Running test should be formatted properly to be consistent with other lines.

### LINKED ISSUE #19353: Use simple foreach instead of unnecessary streamed foreach in build tasks
**Description:**
There are few build tasks (eg : BTestRunner.java) that uses streamed foreach which is unnecessary. This has to be improved to use simple foreach.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Kishanthan**
## Purpose
This will avoid any possible performance issues that can arise when using unnecessary streaming.

Fixes #19353

It will also fix #18858

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/BTestRunner.java [hunk 1]
```diff
@@ -622,7 +614,7 @@ private void execute(boolean buildWithTests) {
         outStream.println("Running tests");
         // Check if the test suite is empty
         if (testSuites.isEmpty()) {
-            outStream.println("    No tests found");
+            outStream.println("\t" + "No tests found");
```
Comment (hasithaa) [inline misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/BTestRunner.java]: I am not sure, using "\t" in CLI is correct. @kaviththiranga @hevayo @NipunaMarcus Could you please comment. ?

Comment (hevayo) [reply misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/BTestRunner.java]: we use \t in other places to indent so this should be fine for consistency. But agree to use spaces instead of /t.
