### PR TITLE
Fix issues with calling `array:sort` with named arguements

### LINKED ISSUE #33300: Getting unordered type error for array:sort
**Description:**
$subject

**Steps to reproduce:**

```
public type T string|int;

public function main() {
    [string, T][] ia1 = [["a", "100"], ["b", "100"], ["d", "10"], ["c", "100"], ["e", "100"]];
    ia1 = ia1.sort(key = isolated function([string, T] e) returns string { // error:invalid member type of the array/tuple to sort: '[string,T][]' is not an ordered type
        return e[0];
    });
}

```
**Affected Versions:**
swan-lake beta3

### PR DESCRIPTION
**Pull request by lasinicl**
## Purpose
$title

Fixes #33300

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -7014,26 +7014,48 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
...
+                dlog.error(arrExpr.pos, DiagnosticErrorCode.INVALID_SORT_ARRAY_MEMBER_TYPE, arrType);
+            }
             return;
         }
 
-        BLangExpression keyFunction = iExpr.argExprs.get(2);
+        if (keyFunction == null) {
+            keyFunction = iExpr.argExprs.get(2);
+        }
+
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7049]: We can remove the local variable `hasKeyFunction` by changing the logic like this.
```ballerina
        BLangExpression keyFunction = null;

        for (int i = 0; i < argExprs.size(); i++) {
            BLangExpression arg = argExprs.get(i);
            if (arg.getKind() == NodeKind.NAMED_ARGS_EXPR) {
                BLangNamedArgsExpression argExpr = (BLangNamedArgsExpression) arg;
                if (argExpr.name.value.equals("key")) {
                    keyFunction = argExpr.expr;
                    break;
                }
            } else if (i == 2) { // last argument, `2` can be defined as a constant
                keyFunction = arg;
                break;
            }
        }

        BLangExpression arrExpr = argExprs.get(0);
        BType arrType = arrExpr.getBType();
        boolean isOrderedType = types.isOrderedType(arrType, false);
        if (keyFunction == null) {
            if (!isOrderedType) {
                dlog.error(arrExpr.pos, DiagnosticErrorCode.INVALID_SORT_ARRAY_MEMBER_TYPE, arrType);
            }
            return;
        }

        BType keyFunctionType = keyFunction.getBType();
```

**Review by KavinduZoysa — APPROVED** [review]

**Review by gimantha — APPROVED** [review]
