### PR TITLE
Fix RunExecutable task to reflect actual status of program execution

### LINKED ISSUE #26084: Ballerina program panics with exit code 0
**Description:**
When a Ballerina program panics, the exit code returns `0`. This should be `1` since the program did not exit normally. 

This is a serious issue since we use ballerina (1.2.8) for the standard library release pipeline processes, where the release is failed in the middle, the ballerina program panics, but the pipeline is marked as passed.

**Steps to reproduce:**
Try the following code:

```ballerina
public function main() {
    error err = error("Sample", message = "Sample Error");
    panic err;
}
```

```shell
$ ballerina run sample.bal
$ echo $?
```
This prints `0`.

**Affected Versions:**

jBallerina: 1.2.8
Ballerina Tool: 0.8.8

** Related Issues:**
#20967, #21624

### PR DESCRIPTION
**Pull request by Dilhasha**
## Purpose
Fix RunExecutable task to reflect actual status of program execution

Fixes #26084

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-tool/src/main/java/org/ballerinalang/tool/RuntimePanicException.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+ *   KIND, either express or implied.  See the License for the
+ *   specific language governing permissions and limitations
+ *   under the License.
+ */
+package org.ballerinalang.tool;
+
+/**
+ * Thrown to indicate a non zero exit code from Ballerina executable.
+ *
+ * @since 1.2.10
```
Comment (warunalakshitha) [inline cli/ballerina-tool/src/main/java/org/ballerinalang/tool/RuntimePanicException.java:23]: version needs to be 2.0.0

**Review by warunalakshitha — APPROVED** [review]
