### PR TITLE
[Master] Recover type reference information for table and object constructor

### LINKED ISSUE #37650: Type reference information is lost when creating a new table
### Description

$subject
Happens at the compiler FE type-checking phase.

### Steps to Reproduce

In ballerina code,
```ballerina
type BTable table<map<anydata>>;

public function main() {
  BTable tab = table [];
}
```
At compilation, it is passed as follows.
Screenshot from 2022-09-06 12-39-46

Note that the expected type is a `BTypeReferenceType` for `BTable` and the result type is `table<map<anydata>>`.

### Affected Version(s)

current master

### OS, DB, other environment details and versions

_No response_

### Labels

CompilerFE

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #37723: [Bug]: Type reference information is lost when creating a new object
### Description

Happens at desugaring the `new ()` statement. 

### Steps to Reproduce

```
public function main() {
    ListenerRef l = new (); 
}

type ListenerRef Listener;

public class Listener {
    boolean initialized = false;

    public function init() {
        self.initialized = true;
    }
}
```
The `new ()` statement is desugared into two expressions at compilation. 
- new type initialisation - `BLangTypeInit` expression
- call to `$init$`

We create new runtime object values for the new type initialization. We need the type-reference information there to create the `ObjectValue` with the type-reference type. 
This information is lost at the BIRGen to pass it to runtime. 

Screenshot from 2022-09-13 16-01-06

### Affected Version(s)

current master

### OS, DB, other environment details and versions

_No response_

### Related area

Compilation

### Related issue(s) (optional)

#36855 

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by prakanth97**
## Purpose

Fixes #37650 
Fixes #37723

## Approach
Use reference type for constructor if it is available.

## Samples
```
type BTable table<map<int>>|Bar3;

type Bar3 table<Bar>key(a);

type Bar record {
    readonly string a;
};

public function main() {
  BTable tab = table key(a) [{a : "a"}];
}
```
Type for the constructor is reference type `Bar3`.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ReferenceTypeTest.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
+package io.ballerina.semantic.api.test;
```
Comment (gimantha) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ReferenceTypeTest.java:1]: Lets add the copyright headers to this file

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ReferenceTypeTest.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+import io.ballerina.projects.Project;
+import org.ballerinalang.test.BCompileUtil;
+import org.testng.annotations.Test;
+import java.util.Optional;
+
+import static org.testng.Assert.assertEquals;
+import static org.testng.Assert.assertTrue;
+/**
+ * This class contains constructor's type reference type related test cases.
+ */
```
Comment (gimantha) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/ReferenceTypeTest.java:19]: @since 2201.3.0 ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java [hunk 3]
```diff
@@ -2192,7 +2192,8 @@ public void visit(BLangTableConstructorExpr tableConstructorExpr) {
 
         BLangArrayLiteral dataLiteral = new BLangArrayLiteral();
         dataLiteral.pos = tableConstructorExpr.pos;
-        dataLiteral.setBType(new BArrayType(((BTableType) tableConstructorExpr.getBType()).constraint));
+        dataLiteral.setBType(
+                new BArrayType(((BTableType) Types.getReferredType(tableConstructorExpr.getBType())).constraint));
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java:2196]: Can't we use `type` variable here defined in L:2178?

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/reference_type_test.bal [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+
+type BarTable table<Bar>key(a);
+
+type Bar record {
+    readonly string a;
+};
+
+function testTypeReferenceOfTableConstructor() {
+    BTable tab = table key(a) [{a : "a"}];
+}
```
Comment (KavinduZoysa) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/reference_type_test.bal:27]: We need to have tests for object scenario.

Comment (prakanth97) [reply tests/ballerina-compiler-api-test/src/test/resources/test-src/reference_type_test.bal:27]: The change is done for `typeInitExpr` but we don't have a node visitor for `typeInitNode`. That's why we skip the test for that.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java [hunk 5]
```diff
@@ -2543,12 +2544,12 @@ private void generateMappingAccess(BLangIndexBasedAccess astIndexBasedAccessExpr
     private BTypeSymbol getObjectTypeSymbol(BType objType) {
         BType type = Types.getReferredType(objType);
         if (type.tag == TypeTags.UNION) {
-            return ((BUnionType) type).getMemberTypes().stream()
-                    .filter(t -> t.tag == TypeTags.OBJECT)
+            return Types.getReferredType(((BUnionType) type).getMemberTypes().stream()
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java:2547]: within the if assign to `type` so that we can use the return for both cases

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 6]
```diff
@@ -1133,7 +1133,14 @@ public void visit(BLangTableConstructorExpr tableConstructorExpr, AnalyzerData d
             if (!expectedTableType.fieldNameList.isEmpty() && tableType.fieldNameList.isEmpty()) {
                 tableType.fieldNameList = expectedTableType.fieldNameList;
             }
-            data.resultType = tableType;
+
+            if (((BTableType) applicableExpType).keyTypeConstraint != symTable.neverType &&
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:1137]: Move `applicableExpType` to a new var and use

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:1137]: May be add this logic under a separate method

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:1137]: I will update that

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated 165b555d0fbe14a18e197de3417f07ef16b30ed3

**Review by KavinduZoysa — DISMISSED** [review]

**Comment by KavinduZoysa** [comment]
Shall we add a one small test to cover bir path?

**Comment by prakanth97** [comment]
> Shall we add a small test to cover bir path?

Updated babbd8c2f1291967884ae370027e5e0e2004a5d1

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java [hunk 7]
```diff
@@ -2197,7 +2197,8 @@ public void visit(BLangTableConstructorExpr tableConstructorExpr) {
 
         BLangArrayLiteral dataLiteral = new BLangArrayLiteral();
         dataLiteral.pos = tableConstructorExpr.pos;
-        dataLiteral.setBType(new BArrayType(((BTableType) tableConstructorExpr.getBType()).constraint));
+        dataLiteral.setBType(
+                new BArrayType(type.constraint));
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java:2201]:
```suggestion
        dataLiteral.setBType(new BArrayType(type.constraint));
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 8]
```diff
@@ -1315,6 +1320,11 @@ private BType inferTableMemberType(List<BType> memTypes, BLangTableConstructorEx
         return createTableConstraintRecordType(inferredFields, restFieldTypes, tableConstructorExpr.pos, data);
     }
 
+    public boolean isSameTableType(BTableType source, BTableType target) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:1323]: Can you check whether `Types.isSameType()` can be used instead?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java (hunk 7 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java]: Updated 2567410abf5e9b87e5412821d85f989886b4cba9

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 8 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:1323]: Sure

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 9]
```diff
@@ -4125,13 +4135,14 @@ public void visit(BLangTypeInit cIExpr, AnalyzerData data) {
     }
 
     private BType checkObjectCompatibility(BType actualType, BLangTypeInit cIExpr, AnalyzerData data) {
-        switch (actualType.tag) {
+        BType referredType = Types.getReferredType(actualType);
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4138]: Since we are calling `checkObjectCompatibility()` recursively unwrapping the referred type if `actualType.tag` is a ReferenceTypeTag; why do we need to unwrap here?

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4138]: In the current master for `object type init`  `BType` is a `referenceType` but `determinedType` is `referred type`. This commit 39ebfdbfdce43615ec06c0d77e481754d5736846 will fix that issue. The `determinedType` is set when we do the type check in https://github.com/ballerina-platform/ballerina-lang/blob/618dc0ef34686f68e273015724d2b45246bd403c/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L4268

if we do not make this change `actualTypeInitType` will be `referred type`. Hence this fix

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 8 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:1323]: We can not use that, since it check for memory equality. Here `tableType` is new type created to get the key specifier which can be available in the rhs or lhs.
https://github.com/ballerina-platform/ballerina-lang/blob/ac3f47fa8fc9918cffc70acf5bb232cc4627c63e/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L2807

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 9 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:4138]: I still don't get it. What if had the old `TypeTags.TYPEREFDESC` case in `checkObjectCompatibility()` and updated `getObjectConstructorReturnType` to a include a `TypeTags.TYPEREFDESC` case

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: I have updated the mentioned change 9a3d2dd17eb2c3d79b31bb12aee715e106d99f0c

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 8 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:1323]:
```suggestion
    private boolean isSameTableType(BTableType source, BTableType target) {
```

**Review by pcnfernando — APPROVED** [review]
