### PR TITLE
Optimize BIR by reusing temporary variables created for observability instrumentation

### LINKED ISSUE #37506: 50 line resource method results in a `method too large` error
Consider the `get hello()` resource method in the service below. When trying to build this, it results in a `method too large` error. The class corresponding to this doesn't decompile. But its size is abnormally large compared to the rest of the classes in the JAR (179KB+). When replacing each of the checks annotated in the comments in the code below with var assignments instead, you can see a considerable drop in the size. 
-  Size of the class when 1 is converted to an assignment: 179KB
-  Size of the class when 1 and 2 are converted to an assignment: 154KB
-  Size when all of the annotated usages are converted to assignments: 92KB

So does this mean using a check is very expensive in terms of the Java method space they take up? Is there anything that can be done to improve this? 
```ballerina
import ballerina/http;
import choreo/mediation;
import choreo/mediation.add_header;

service on new http:Listener(9090) {

    resource function get hello(http:Request req, http:Caller caller, string url) returns error? {
        mediation:Context mediationCtx = {httpMethod: "get", resourcePath: "/greet"};
        http:Response? backendResponse;

        do {
            {
                var x = check add_header:addHeader_In(req, mediationCtx, "foo", "Foo");

                if x is false {
                    check caller->respond(http:INTERNAL_SERVER_ERROR); // 1
                    return;
                } else if x is http:Response {
                    check caller->respond(x); // 2
                    return;
                }
            }

            http:Client ep = checkpanic new (url);
            backendResponse = check ep->execute(mediationCtx.httpMethod, mediationCtx.resourcePath, req, targetType = http:Response);

            {
                var x = check add_header:addHeader_Out(<http:Response>backendResponse, req, mediationCtx, "bar", "Bar");

                if x is false {
                    check caller->respond(http:INTERNAL_SERVER_ERROR); // 3
                    return;
                } else if x is http:Response {
                    check caller->respond(x); // 4
                    return;
                }
            }

            check caller->respond(backendResponse);
        } on fail var e {
            http:Response errFlowResponse = new;
            errFlowResponse.statusCode = http:STATUS_INTERNAL_SERVER_ERROR;

            {
                var v = add_header:addHeader_Fault(errFlowResponse, e, backendResponse, req, mediationCtx, "baz", "Baz");

                if v is false|error {
                    check caller->respond(errFlowResponse); // 5
                    return;
                } else if v is http:Response {
                    check caller->respond(v); // 6
                    return;
                }
            }

            check caller->respond(errFlowResponse);
        }
    }
}

service on new http:Listener(8080) {
    resource function get greet(http:Request req) returns json {
        return {"greeting": "Hello World!"};
    }
}
```
This was observed in both `2201.1.0` and `2201.2.0` RC2.

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #37506

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ObservabilityJMethodCall.java [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import org.wso2.ballerinalang.compiler.bir.model.BIROperand;
+import org.wso2.ballerinalang.compiler.bir.model.BIRVisitor;
+import org.wso2.ballerinalang.compiler.bir.model.InstructionKind;
+
+import java.util.List;
+
+/**
+ * Java method invocation call modeled as BIR NonTerminator Instruction.
+ *
+ * @since 2201.3.0
```
Comment (Nadeeshan96) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ObservabilityJMethodCall.java:31]:
```suggestion
 * @since 2201.4.0
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java [hunk 2]
```diff
@@ -607,6 +615,31 @@ void generatePlatformIns(JInstruction ins) {
...
 
+    void generateObserveJIMethodCallIns(ObservabilityJMethodCall callIns, int localVarOffset) {
+        boolean isInterface = callIns.invocationType == INVOKEINTERFACE;
+        int argIndex = 0;
+        String jMethodVMSig = callIns.jMethodVMSig;
+        boolean hasBalEnvParam = jMethodVMSig.startsWith(BAL_ENV_PARAM);
+        if (hasBalEnvParam) {
+            mv.visitTypeInsn(NEW, BAL_ENV);
+            mv.visitInsn(DUP);
+            this.mv.visitVarInsn(ALOAD, localVarOffset); // load the strand
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:626]:
```suggestion
            // load the strand
            this.mv.visitVarInsn(ALOAD, localVarOffset);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java [hunk 3]
```diff
@@ -607,6 +615,31 @@ void generatePlatformIns(JInstruction ins) {
...
+        }
+
+        while (argIndex < callIns.args.size()) {
+            BIROperand arg = callIns.args.get(argIndex);
+            this.loadVar(arg.variableDcl);
+            argIndex += 1;
+        }
+        String jClassName = callIns.jClassName;
+        String jMethodName = callIns.name;
+        this.mv.visitMethodInsn(callIns.invocationType, jClassName, jMethodName, jMethodVMSig, isInterface);
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:640]:
```suggestion
        this.mv.visitMethodInsn(callIns.invocationType, callIns.jClassName, callIns.name, jMethodVMSig, isInterface);
```
As we use the `jClassName` and `name` fields only once, we can use them directly instead of creating variables.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java [hunk 4]
```diff
@@ -2324,6 +2357,10 @@ void generateInstructions(int localVarOffset, BIRInstruction inst) {
                     generateNegateIns((BIRNonTerminator.UnaryOP) inst);
                     break;
                 case PLATFORM:
+                    if (inst instanceof ObservabilityJMethodCall) {
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:2360]: Shall we move this check inside the `generatePlatformIns` method, because `ObservabilityJMethodCall` is also a platform instruction?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ObservabilityJMethodCall.java [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+import org.wso2.ballerinalang.compiler.bir.model.InstructionKind;
+
+import java.util.List;
+
+/**
+ * Java method invocation call modeled as BIR NonTerminator Instruction.
+ *
+ * @since 2201.4.0
+ */
+public class ObservabilityJMethodCall extends BIRNonTerminator {
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ObservabilityJMethodCall.java:33]: Since we have `JInstruction` implementation for java specific instructions, shouldn't we extend this from `JInstruction`? 
In that way, we can get rid of the `instanceOf` checks and use the `jKind` field. 
https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JInstruction.java

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java [hunk 6]
```diff
@@ -222,66 +231,88 @@ void instrumentPackage(BIRPackage pkg) {
...
             if (desugaredPos != null && desugaredPos.lineRange().startLine().line() >= 0) {
-                BIRBasicBlock newBB = insertBasicBlock(func, i + 1);
-                swapBasicBlockContent(func, currentBB, newBB);
-                injectCheckpointCall(func, currentBB, pkg, desugaredPos);
-                currentBB.terminator.thenBB = newBB;
-                // Fix error entries in the error entry table
-                fixErrorTable(func, currentBB, newBB);
-                i += 1; // Number of inserted BBs
+                List<BIRBasicBlock> predecessors = entry.getValue();
+                boolean desugaredPosAlreadyLoaded = predecessors.stream()
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:248]: Shall we simplify this without using streams

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ObservabilityJMethodCall.java (hunk 5 above)
Comment (warunalakshitha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/ObservabilityJMethodCall.java:33]: +1. Also shall we use general name for class. ex. JMethodCallInstruction

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java (hunk 6 above)
Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:248]: Since it's in compile time, would it affect the performance?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java [hunk 7]
```diff
@@ -222,66 +231,90 @@ void instrumentPackage(BIRPackage pkg) {
...
+        currentBB.instructions.add(offset, recordCheckPointCallIns);
+    }
+
+    private Location getDesugaredPosition(BIRBasicBlock basicBlock) {
+        // First we give the priority to Instructions,
+        // If no instructions are found, then we get the Terminator position
+        Location desugaredPos = basicBlock.terminator.pos;
+        for (BIRNonTerminator instruction : basicBlock.instructions) {
+            if (instruction.pos != null) {
+                desugaredPos = instruction.pos;
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:297]: we can directly return instruction.pos

**Review by warunalakshitha — APPROVED** [review]
