### PR TITLE
Move object method bodies into a separate class when original class is too large

### LINKED ISSUE #41279: [Bug]: File too large error when building ballerina project
### Description

$title

Related issue: https://github.com/wso2-enterprise/internal-support-ballerina/issues/427

### Steps to Reproduce

_No response_

### Affected Version(s)

2201.5.1
2201.7.1

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #41279

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by Nadeeshan96** [comment]
It is not good to always split the Ballerina classes because it will have unnecessary overhead. So we will only split if the jvm class will be too large (if it have more than 100 methods). In the PR, I have temperorily sent a [commit](https://github.com/ballerina-platform/ballerina-lang/pull/41409/commits/1b65578965638b6b0721a426b57262ee61195a24) to always split the class to find whether all the cases are passing for now. @NipunaRanasinghe Now the debugger tests will fail. We can use some criteria such as the class name to find the split classes and fix the failing tests. Then we can revert the [commit](https://github.com/ballerina-platform/ballerina-lang/pull/41409/commits/1b65578965638b6b0721a426b57262ee61195a24) and that should not result in test failures if our fix is right, and we can merge the PR.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java [hunk 1]
```diff
@@ -441,7 +442,7 @@ private Optional<StackTraceElement> filterStackTraceElement(StackTraceElement st
     }
 
     private String cleanupClassName(String className) {
-        return className.replace(GENERATE_OBJECT_CLASS_PREFIX, "");
+        return className.replace(GENERATE_OBJECT_CLASS_PREFIX, "").replaceAll(SPLIT_CLASS_SUFFIX_REGEX, "");
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java:445]: If we generate split classes with object class prefix, we can get rid of this replace all.

**Comment by Nadeeshan96** [comment]
Tested the fix with a service have about 400 resource functions, and it worked fine.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java (hunk 1 above)
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ErrorValue.java:445]: Discussed to keep `replaceAll` since it does not have an impact on the performance.

**Comment by Nadeeshan96** [comment]
Sonarcloud scan is failing due to https://github.com/ballerina-platform/ballerina-lang/issues/41539.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java [hunk 2]
```diff
@@ -606,7 +585,10 @@ private byte[] createObjectValueClass(BObjectType objectType, String className,
         this.createObjectFields(cw, fields);
 
         List<BIRNode.BIRFunction> attachedFuncs = typeDef.attachedFuncs;
-        if (attachedFuncs != null) {
```
Comment (gabilang) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java:609]: Is it safe to remove this check? Will there be any possibilities for the `attachedFuncs` be null?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java [hunk 3]
```diff
@@ -172,14 +180,74 @@ public void generateMethod(BIRFunction birFunc, ClassWriter cw, BIRPackage birMo
...
+            return;
+        } else if (TypeTags.isStringTypeTag(bType.tag) || TypeTags.isXMLTypeTag(bType.tag)
+                || TypeTags.REGEXP == bType.tag) {
+            mv.visitInsn(ARETURN);
+            return;
+        }
+
+        switch (bType.tag) {
+            case TypeTags.BYTE, TypeTags.BOOLEAN -> mv.visitInsn(IRETURN);
+            case TypeTags.FLOAT -> mv.visitInsn(DRETURN);
```
Comment (gabilang) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:241]: Shall we add a test case to cover this case as well?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java [hunk 4]
```diff
@@ -172,14 +180,74 @@ public void generateMethod(BIRFunction birFunc, ClassWriter cw, BIRPackage birMo
...
+            default -> mv.visitInsn(ARETURN);
```
Comment (gabilang) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:242]: Is it correct to use `ARETURN` for all other default cases? Don't we need to specifically check only for the Ballerina supported types.

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:242]: Any other unknown types will not get there as bType. So using `ARETURN` is correct.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java [hunk 5]
```diff
@@ -172,14 +180,74 @@ public void generateMethod(BIRFunction birFunc, ClassWriter cw, BIRPackage birMo
...
+        JvmCodeGenUtil.visitMaxStackForMethod(mv, funcName, moduleClassName);
+        mv.visitEnd();
+    }
+
+    private void generateReturnTermFromType(BType bType, MethodVisitor mv) {
+        bType = JvmCodeGenUtil.getImpliedType(bType);
+        if (TypeTags.isIntegerTypeTag(bType.tag)) {
+            mv.visitInsn(LRETURN);
+            return;
+        } else if (TypeTags.isStringTypeTag(bType.tag) || TypeTags.isXMLTypeTag(bType.tag)
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:233]: Shall we remove this part? I think it will execute through the default of the switch case.

File: tests/jballerina-unit-test/src/test/resources/test-src/jvm/tooLargeFileTest/Ballerina.toml [hunk 6]
```diff
@@ -0,0 +1,7 @@
+[package]
+org = "testorg"
+name = "largefiletest"
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/resources/test-src/jvm/tooLargeFileTest/Ballerina.toml:3]:
```suggestion
name = "large_file_test"
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java (hunk 2 above)
Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java:609]: I could not find any case `attachedFuncs` can be `null`;

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java [hunk 7]
```diff
@@ -78,6 +78,7 @@
 import static io.ballerina.projects.util.ProjectConstants.BIN_DIR_NAME;
 import static io.ballerina.projects.util.ProjectConstants.DOT;
 import static io.ballerina.projects.util.ProjectUtils.getThinJarFileName;
+import static org.wso2.ballerinalang.compiler.bir.codegen.JvmConstants.CLASS_FILE_SUFFIX;
```
[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java:81]: I think it is better to create this constant here because if we see the usages it is used in codegen.
image
and project constants says they are constants related to the project directory.
image
Shall we keep it here?

[the remark this answers is not in the document]
Comment (HindujaB) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java:81]: +1

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java [hunk 8]
```diff
@@ -296,7 +288,6 @@ private void createInstantiateMethod(ClassWriter cw, BRecordType recordType,
             }
         }
```
[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java:290]: These newlines are not added by me. I think they are added by the original author to group the code lines logically to improve clarity since the method is long. Hence I think it is better to keep them and remove only extra blank lines.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java [hunk 9]
```diff
@@ -309,14 +300,12 @@ private void createInstantiateMethod(ClassWriter cw, BRecordType recordType,
...
         mv.visitInsn(POP);
```
[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmValueGen.java:302]: These newlines are not added by me. I think they are added by the original author to group the code lines logically to improve clarity since the method is long. Hence I think it is better to keep them and remove only extra blank lines.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java [hunk 10]
```diff
@@ -384,6 +384,11 @@ public static String getMethodDesc(List<BType> paramTypes, BType retType, BType
                 generateReturnType(retType);
     }
 
+    public static String getMethodDesc(List<BType> paramTypes, BType retType, String attachedTypeClassName) {
```
[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java:387]: Fixed with 48b4ec5e9c15c5feb97cb049d66d66b974039d44.

**Review by warunalakshitha — DISMISSED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
