### PR TITLE
[2201.8.x] Revise the definition API of the `TypeReferenceTypeSymbol` to exclude searching for virtual symbols in the scope

### LINKED ISSUE #42454: [Bug]: Getting `Symbol is 'null'`and fail whenever executes Semantic APIs in compiler extension in package 'ballerina:sql:1.12.0'
### Description

The ballerina source code would not compile.
error: compilation failed: The compiler extension in package 'ballerina:sql:1.12.0' failed to complete. Symbol is 'null'

```
error: compilation failed: The compiler extension in package 'ballerina:sql:1.12.0' failed to complete. Symbol is 'null'
```

### Affected Version(s)

2201.8.4 and 2201.8.6. Probably version 8

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by nipunayf**
## Purpose
$title as virtual symbols are not stored in the scope.

Fixes #42454 

## Approach
The current approach ensures that the `definition` API of the type references does not search for virtual symbols in the current scope.

## Remarks
Although this PR fixed the semantic API issue, the tsymbol set for narrowed type symbols remains invalid, which is being tracked separately.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java [hunk 1]
```diff
@@ -103,7 +104,7 @@ public Symbol definition() {
         if (referredType.tag == TypeTags.PARAMETERIZED_TYPE || bType.tag == TypeTags.PARAMETERIZED_TYPE) {
             this.definition = symbolFactory.getBCompiledSymbol(((BParameterizedType) this.tSymbol.type).paramSymbol,
                                                                this.name());
-        } else if (referredType.tag == TypeTags.INTERSECTION) {
+        } else if (referredType.tag == TypeTags.INTERSECTION || referredType.tsymbol.origin == SymbolOrigin.VIRTUAL) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java:107]: Instead of this approach, can't we check whether readonly flag is set or not?

Comment (nipunayf) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java:107]: It is not clear at which position I should make your change. If you are suggesting replacing the virtual check with readonly, then it breaks the existing cases.

For instance, in the following case, the definition is correct as we are looking for the symbol through its name. However, since this symbol is also readonly, with the mentioned change, it would look for the tsymbol instead, which will produce an incorrect type

```ballerina
type Student string;

function fn() {
    Student student = "A";
}
```

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java:107]: Anyway here, we have to make this change since we should avoid looking for virtual symbols.

**Review by dulajdilshan — APPROVED** [review]
