### PR TITLE
Handle the exception thrown when user lacks permission to bal files

### LINKED ISSUE #9303: Running test while having a directory without permission result in Bad, Sad.
**Description:**
If you have a program directory containing a directory without permission for the given user, if the user runs ballerina test command it will give a bad sad error. See the directory structure and the error response below.

```
.
├── ballerina-internal.log
├── hello_service.bal
├── org.sample
│   ├── mysample.bal
│   └── without_permission [dir without permission]
└── tests
    └── hello_service_test.bal
```
When we run `ballerina test` it will give the following error. 

```
---------------------------------------------------------------------------
    T E S T S
---------------------------------------------------------------------------
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

**Affected Versions:**
0.975.0

**OS, DB, other environment details and versions:**
Ubuntu, Linux

PS. marking this as priority high since this issue affects composer rendering when there are directories without permission in the program path. 
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/2149735/ballerina-internal.log)

### PR DESCRIPTION
**Pull request by azinneera**
Fixes #9303 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ProjectDirs.java [hunk 1]
```diff
@@ -78,14 +80,23 @@ public static BLangCompilerException getPackageNotFoundError(String sourcePackag
...
         try {
             sourceFiles = Files.find(pkgPath, Integer.MAX_VALUE, (path, attrs) ->
                     path.toString().endsWith(ProjectDirConstants.BLANG_SOURCE_EXT)).collect(Collectors.toList());
         } catch (IOException ignored) {
             // Here we are trying to check if there are source files inside the package to be compiled. If an error
             // occurs when trying to visit the files inside the package then we simply return the empty list created.
+        } catch (UncheckedIOException e) {
+            // Files#find returns an UncheckedIOException instead of an AccessDeniedException when there is a file to
+            // which user doesnt have required permission.
+            if (e.getCause() instanceof AccessDeniedException) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ProjectDirs.java]:
```suggestion
         if (e.getCause() instanceof AccessDeniedException) {
            throw new BLangCompilerException("permission denied for path " + 
                                                     pkgPath.toString() + ", cause: " + e.getMessage());
        } else {
            throw e;
        }
```
