### PR TITLE
Fix bad, sad error with error:CallStack

### LINKED ISSUE #30284: Bad, sad error with `error:CallStack`
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    error e = error("error!");
    io:println(e.stackTrace().callStack); // OK

    error:CallStack stackTrace = e.stackTrace(); // OK
    io:println(stackTrace); // Crashes
}
```

```log
[2021-05-02 17:39:25,033] SEVERE {b7a.log.crash} - class org.ballerinalang.langlib.error.StackTrace$CallStack cannot be cast to class io.ballerina.runtime.internal.values.RefValue (org.ballerinalang.langlib.error.StackTrace$CallStack and io.ballerina.runtime.internal.values.RefValue are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.ballerinalang.langlib.error.StackTrace$CallStack cannot be cast to class io.ballerina.runtime.internal.values.RefValue (org.ballerinalang.langlib.error.StackTrace$CallStack and io.ballerina.runtime.internal.values.RefValue are in unnamed module of loader 'app')
	at io.ballerina.runtime.internal.TypeChecker.isMutable(TypeChecker.java:1923)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:284)
	at io.ballerina.runtime.internal.TypeChecker.checkIsType(TypeChecker.java:261)
	at ballerina.io.0_6_0-alpha8.$value$PrintableClassImpl.toString(print.bal:71)
	at ballerina.io.0_6_0-alpha8.$value$PrintableClassImpl.call(print.bal)
	at io.ballerina.runtime.api.utils.StringUtils.getStringValue(StringUtils.java:207)
	at org.ballerinalang.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:57)
	at ballerina.io.0_6_0-alpha8.print.externPrintln(print.bal:112)
	at ballerina.io.0_6_0-alpha8.print.println(print.bal:60)
	at foo.main(foo.bal:8)
	at $_init.$lambda$main$(.)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Affected Versions:**
slalpha5

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #30284

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 1]
```diff
@@ -1918,6 +1918,10 @@ private static boolean isMutable(Object value, Type sourceType) {
             return false;
         }
 
+        if (sourceType.getTag() == TypeTags.OBJECT_TYPE_TAG) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:1921]: IMO correct fix would be to extend BObject with RefValue class

File: langlib/langlib-test/src/test/resources/test-src/errorlib_test.bal [hunk 2]
```diff
@@ -99,3 +100,19 @@ public function testErrorStackTrace() returns [int, string] {
...
+    test:assertFalse(res is error);
+
+    string s = "";
+    if (res is error) {
+        s = "error!";
+    } else {
+        s = res.toString();
+    }
+    test:assertValueEqual("object lang.error:CallStack", s);
+}
```
Comment (warunalakshitha) [inline langlib/langlib-test/src/test/resources/test-src/errorlib_test.bal:118]: Is this missing empty last line?

**Review by warunalakshitha — APPROVED** [review]
LGTM
