### PR TITLE
Skip validation when a custom bala path is provided

### LINKED ISSUE #33910: [ProjectAPI] Skip validation for `bal push <bala-path>`
**Description:**
`Push` command uses the Ballerina.toml to validate if the bala is up to date. When outside the project, executing this command fails to find the associated ballerina.toml and hence the validation fails. 

So for such cases the validation needs to be skipped

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Ibaqu**
## Purpose
There are 2 levels of validation that occurs when attempting to push a bala. 

1. Project validation, which includes checking if the command is called from a valid ballerina project
2. Toml validation, which checks whether the bala org/package/ver is same as that specified in the project ballerina.toml. 

In order to skip the Project validation, we skip loading the project entirely as most of the validation happens during the `BuildProject.load()` phase. Next, we skip the Toml validation entirely by calling the function that pushes the bala directly. 

Fixes #33910

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by Ibaqu** [comment]
Please note that if any discrepancies exist in the bala, such as if the `Package.md` hasnt been created or if the version already exsits, we get an error from central regarding the same.

**Review by azinneera — DISMISSED** [review]

**Review by pramodya1994 — DISMISSED** [review]

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PushCommand.java [hunk 1]
```diff
@@ -165,9 +173,13 @@ public void execute() {
...
                 CentralAPIClient client = new CentralAPIClient(RepoUtils.getRemoteRepoURL(),
                         initializeProxy(settings.getProxy()), getAccessTokenOfCLI(settings));
-
                 try {
-                    pushPackage(project, client);
+                    if (balaPath == null) {
+                        pushPackage(project, client);
+                    } else {
+                        // Skip validation entirely and push to central
+                        pushBalaToRemote(balaPath, client);
```
Comment (azinneera) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PushCommand.java:181]: We shouldn't ignore all the validations. We can still validate the extension and the files inside the bala.

Comment (Ibaqu) [reply cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/PushCommand.java:189]: Added the file validation

**Comment by pramodya1994** [comment]
@Ibaqu After merging this PR we can add a central test to distribution for this case.

**Review by azinneera — APPROVED** [review]
