### PR TITLE
Enclose strings with "" in error messages

### LINKED ISSUE #34361: Strings are not enclosed by `"` in error messages
**Description:**

$title
* In compilation errors:
```bal
public function main() {
    "1" var1 = 1;
    1 var2 = "1";
}
```
gives
```
ERROR [main.bal:(4:16,4:17)] incompatible types: expected '1', found 'int'
ERROR [main.bal:(5:14,5:17)] incompatible types: expected '1', found 'string'
error: compilation contains errors
```

* In runtime errors
```bal
public function main() {
    [1|"1"|"2", 2|"2"|"3"] tupleVal = [1, 2];
    ["1", "2"] ans = checkpanic tupleVal.cloneWithType();
}
```
gives
```
Running executable

error: {ballerina/lang.value}ConversionError {"message":"'[(1|1|2),(2|2|3)]' value cannot be converted to '[1,2]': 
                tuple element '[0]' should be of type '1', found '1'
                tuple element '[1]' should be of type '2', found '2'"}
        at ballerina.lang.value.0:cloneWithType(value.bal:86)
```

**Steps to reproduce:**
Depicted above.

**Affected Versions:**
slbeta6

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #34361

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/optimizer/LargeMethodOptimizer.java [hunk 1]
```diff
@@ -710,7 +710,7 @@ private BIRBasicBlock generateSplitsInSameBB(BIRFunction function, int bbNum, Li
      * @return The generated operand for the variable declaration
      */
     private BIROperand generateTempLocalVariable(BIRFunction func, BType variableType) {
-        Name variableName = new Name("$split$tempVar$" + splitTempVarNum++);
+        Name variableName = new Name("$split$tempVar$_" + splitTempVarNum++);
```
Comment (Nadeeshan96) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/optimizer/LargeMethodOptimizer.java:713]: Done for clarity, as suggested by the PR review comment https://github.com/ballerina-platform/ballerina-lang/pull/34197#discussion_r767459279.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFiniteTypeNode.java [hunk 2]
```diff
@@ -81,12 +81,19 @@ public NodeKind getKind() {
...
         for (BLangExpression memberTypeNode : valueSpace) {
-            if (memberTypeNode.getBType().tag == TypeTags.FLOAT) {
-                stringJoiner.add(memberTypeNode.toString() + NumericLiteralSupport.FLOAT_DISCRIMINATOR);
-            } else if (memberTypeNode.getBType().tag == TypeTags.DECIMAL) {
-                stringJoiner.add(memberTypeNode.toString() + NumericLiteralSupport.DECIMAL_DISCRIMINATOR);
-            } else {
-                stringJoiner.add(memberTypeNode.toString());
+            switch (memberTypeNode.getBType().tag) {
+                case TypeTags.FLOAT:
+                    stringJoiner.add(memberTypeNode + NumericLiteralSupport.FLOAT_DISCRIMINATOR);
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFiniteTypeNode.java:86]: Maybe we could just call the `add` twice.

File: langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal [hunk 3]
```diff
@@ -47,8 +47,8 @@ function testError1() {
     FooError f = error("Foo");
     boolean f1 = f.message();    // incompatible types: expected 'boolean', found 'string'
     string f2 = f.message(); // No error;
-    Foo x1 = f.message(); // incompatible types: expected 'Foo', found 'string'
-    Bar x2 = f.message(); // incompatible types: expected 'Bar', found 'Foo'
+    Foo x1 = f.message(); // incompatible types: expected '"Foo"', found 'string'
+    Bar x2 = f.message(); // incompatible types: expected '"Bar"', found 'Foo'
```
Comment (rdhananjaya) [inline langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal:51]: I think the comment is wrong, this should print `incompatible types: expected '"Bar"', found 'string'`

Shall we add a test case where name of the constant differs from the constant value. IMO the `expected` should be the type-name not the content (when there is a type name).

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFiniteTypeNode.java (hunk 2 above)
Comment (warunalakshitha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFiniteTypeNode.java:86]: We can fix in other places as well.

Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFiniteTypeNode.java:86]: Then won't the outputs look like `12.0 | f | 13.0 | f` instead of `12.0f | 13.0f` and `" | Foo | " | " | Bar | "` instead of `"Foo" | "Bar"`?

Btw I think I need to change `new StringJoiner(" | ");` to `new StringJoiner("|");` as done in other places.

File: langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal (hunk 3 above)
Comment (Nadeeshan96) [reply langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal:51]: Will look into this.

Comment (Nadeeshan96) [reply langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal:51]: It shows the content, not the type-name. As an example
```bal
const Aaa = "Foo";
const Bbb = "Bar";
type FooError error;

function testError1() {
    FooError f = error("Foo");
    boolean f1 = f.message();
    Aaa x1 = f.message();
    Bbb x2 = f.message();
}
```
 will show
```
Compiling source
        ex-finite.bal
ERROR [ex-finite.bal:(7:18,7:29)] incompatible types: expected 'boolean', found 'string'
ERROR [ex-finite.bal:(8:14,8:25)] incompatible types: expected '"Foo"', found 'string'
ERROR [ex-finite.bal:(9:14,9:25)] incompatible types: expected '"Bar"', found 'string'
error: compilation contains errors
```

Comment (rdhananjaya) [reply langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal:51]: I'm not sure if it should do that, we usually display the type reference in error messages.
```ballerina
type A int;

public function main() {
    A a = "hello"; // incompatible types: expected 'A', found 'string'(BCE2066)
}
```

Shall we raise this in slack dev-compiler channel?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFiniteTypeNode.java (hunk 2 above)
Comment (rdhananjaya) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFiniteTypeNode.java:86]: +1

File: langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal (hunk 3 above)
Comment (Nadeeshan96) [reply langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal:51]: Can't the above behaviour is correct because it is declared as a `const` and not as a type, or may I need to raise this in slack dev-compiler channel?
```bal
type A int;
const fruit = "Orange";
const numval = 2;
type unionType "Apple"|"Mango";
const unionconst = "Apple"|"Mango"; //type is required for constants with expressions(BCE3500)

public function main() {
    A a = "hello"; // incompatible types: expected 'A', found 'string'(BCE2066)
    fruit x1 = 4; // incompatible types: expected 'Orange', found 'int'(BCE2066)
    numval x2 = "aa"; // incompatible types: expected '2', found 'string'(BCE2066)
    unionType x3 = 0; // incompatible types: expected 'unionType', found 'int'(BCE2066)
    "number" num = 2; // incompatible types: expected 'number', found 'int'(BCE2066)
}
```

Comment (Nadeeshan96) [reply langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal]: According to the [slack discussion](https://ballerina-platform.slack.com/archives/CAXS256RX/p1641965098001400), it was decided that the error message should display the constant name there. So created issue https://github.com/ballerina-platform/ballerina-lang/issues/34640 for this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFiniteTypeNode.java [hunk 4]
```diff
@@ -79,14 +79,21 @@ public NodeKind getKind() {
...
+                    break;
+                case TypeTags.DECIMAL:
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFiniteTypeNode.java:88]: Shall we write a test to cover these lines?

Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/types/BLangFiniteTypeNode.java:88]: I will look into this.

**Review by warunalakshitha — APPROVED** [review]
LGTM
