### PR TITLE
Fix static type for unary expression when the static type of the expression is a built-in int subtype

### LINKED ISSUE #37540: [Bug]: Invalid static type for unary expression when the static type of the expression is a built-in int subtype
### Description

$title.

The [spec](https://ballerina.io/spec/lang/master/#unary-numeric-expr) says 

> The unary - operator performs negation. The static type of the operand must be a number; **the static type of the result is the basic type of the static type of the operand**, modified by the usual [singleton typing](https://ballerina.io/spec/lang/master/#singleton_typing) rules.

### Steps to Reproduce

```ballerina
public function main() {
    int:Signed8 a = -128;
    int:Signed8 b = -a; // Should result in an error, static type of `-a` is `int`

    panic error((b is int:Signed8).toString()); // false
}
```

### Affected Version(s)

Current master, 2201.3.0-SNAPSHOT

### OS, DB, other environment details and versions

_No response_

### Labels

CompilerFE

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by suleka96**
Fixes #37540

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -5268,6 +5269,13 @@ public BType getActualTypeForOtherUnaryExpr(BLangUnaryExpr unaryExpr, AnalyzerDa
         return actualType;
     }
 
+    public boolean isUnaryCompatibleSingletonForIntSubtype(BLangExpression expr) {
+        if (expr.getKind() == NodeKind.NUMERIC_LITERAL) {
+            return true;
+        }
+        return false;
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5276]: `return expr.getKind() == NodeKind.NUMERIC_LITERAL;`

File: tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value-negative.bal [hunk 2]
```diff
@@ -16,3 +16,27 @@ function test2() {
...
+    int:Signed32 _ = -d;
+    testType2 e = -32768;
+    int:Signed16 _ = -e;
+    testType3 f = -128;
+    int:Signed8 _ = -f;
+
+    int:Signed16 _ = -(-32767);
+    int:Signed8 _ = -(-127);
+    int:Signed32 _ = -(-2147483647);
+}
```
Comment (KavinduZoysa) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value-negative.bal:42]: Let's comment where the error is (// error).

Comment (KavinduZoysa) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value-negative.bal:42]: Shall we add a few test cases for other possibilities as well?

```
unary-numeric-expr :=
   + expression
   | - expression
   | ~ expression```

Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value-negative.bal:42]: Please ignore this, we are considering only `-`

File: tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value.bal [hunk 3]
```diff
@@ -109,3 +109,12 @@ function testIntSubtypeField() {
     test:assertEquals(val?.minutes, 9);
     test:assertEquals(val?.seconds, <decimal>8.555);
 }
+
+function testStaticTypeOfUnaryExpr() {
```
Comment (gimantha) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value.bal:113]: Dont we need to check the static type of the result of unary expr here? We are checking the result of the type-cast expr right?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value-negative.bal (hunk 2 above)
Comment (suleka96) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value-negative.bal:42]: The line from which the error is thrown is reflected in `BAssertUtil.validateError()` right, so do we need to again specify in the `bal` file?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value.bal (hunk 3 above)
Comment (suleka96) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value.bal:113]: we are checking the static type with the error tests right... these tests were actually additional just to see if we can make the scenario work with casting.. will change the function name

Comment (suleka96) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/integer/integer-value.bal]: Since these don't work in update 2 as well I have removed these tests. These should work once the singleton typing is properly implemented.

**Review by gimantha — APPROVED** [review]

**Review by KavinduZoysa — APPROVED** [review]
