### PR TITLE
Fix completion issue within if condition context

### LINKED ISSUE #21923: Completions are not suggested
**Description:**
Consider the following source snippet

```
function countRows(jdbc:Client jdbcClient) {
    
    io:println("------ Start Count Total Rows -------");
    stream<record{}, error> resultStream =  jdbcClient->query("Select count(*) as total from Customers");
    j<cursor>
    record {|record {} value;|}|error? result = resultStream.next();
    if (result is record {|record {} value;|}) {
        io:println("Total rows in customer table : ", result.value["TOTAL"]);
    } else if (result is error) {
        io:println("Next operation on the stream failed. ", result);
    } else {
        io:println("Customer table is empty");
    }
    // Close the stream.
    error? e = resultStream.close();
    io:println("------ End Count Total Rows -------");
}
```

No completions at the cursor

**Affected Versions:**
v1.2.0-rc2 at least

### LINKED ISSUE #21925: No completions within the if condition
**Description:**
Consider the following source snippet,

```
if (jdbcClient is jdbc:<cursor>) {
}
```

No completions are provided at the cursor

**Affected Versions:**
v1.2.0-rc2 at least

### PR DESCRIPTION
**Pull request by nadeeshaan**
Fixes #21925 
Fixes #21923 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/FunctionDefinitionCompletionTest.java [hunk 1]
```diff
@@ -134,6 +134,7 @@ public void test(String config, String configPath) throws WorkspaceDocumentExcep
 //                {"ifWhileConditionContextCompletion3.json", "function"},
```
Comment (NipunaMarcus) [inline language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/FunctionDefinitionCompletionTest.java]: is this an unnecessary test ?

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/definitions/FunctionDefinitionCompletionTest.java]: This was disabled earlier due to a source pruner bug.
