### PR TITLE
Fix showing dependency diagnostics for workspaces

### LINKED ISSUE #44364: [Bug]: Diagnostics of dependent packages are displayed during the compilation of a workspace project
### Description

When `projA` depends on `projB`, executing `bal build` on `projA` also shows the diagnostics of `projB`.

### Steps to Reproduce

1. Create a workspace project where `projA` depends on `projB`.
2. Add diagnostics to `projB`.
3. Run `bal build` in `projA` and observe that diagnostics from `projB` appear in the output.

### Affected Version(s)

2201.13.0.alpha2

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by azinneera**
Fixes #44364

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/DiagnosticResult.java [hunk 1]
```diff
@@ -46,6 +48,22 @@ public Collection<Diagnostic> diagnostics(boolean includeInternal) {
...
 
+    public Collection<Diagnostic> diagnostics(boolean includeInternal, boolean excludeDependencyDiagnostics) {
+        Collection<Diagnostic> diagnostics = includeInternal ? allDiagnostics : getInternalExcluded(allDiagnostics);
+        if (excludeDependencyDiagnostics) {
+            List<Diagnostic> filteredDiagnostics = new ArrayList<>();
+            for (Diagnostic diagnostic : diagnostics) {
+                if (diagnostic.toString().contains("::")) {
+                    // This is a dependency diagnostic, skip it
+                    continue;
+                }
```
[the remark this answers is not in the document]
Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/DiagnosticResult.java:59]: The string representation won't change as it will be a breaking change. Hence this can be ignored.

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/DiagnosticResult.java [hunk 2]
```diff
@@ -46,6 +48,22 @@ public Collection<Diagnostic> diagnostics(boolean includeInternal) {
         return includeInternal ? allDiagnostics : getInternalExcluded(allDiagnostics);
     }
 
+    public Collection<Diagnostic> diagnostics(boolean includeInternal, boolean excludeDependencyDiagnostics) {
```
Comment (nipunayf) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/DiagnosticResult.java]: There's an inconsistency in the provided flags. Can we rename it to `includeDependencyDiagnostics`?

Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/DiagnosticResult.java]: We include it by default. So the flag should be to exclude IMO.

Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/DiagnosticResult.java]: We can rename it to `hideDependencyDiagnostics` maybe. WDYT?

Comment (nipunayf) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/DiagnosticResult.java]: +1 for the change

Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/DiagnosticResult.java]: Fixed in c3df87c

**Review by keizer619 — APPROVED** [review]
