### PR TITLE
[2201.9.x] Add org name to the package metadata response

### LINKED ISSUE #43127: [Bug]: Package metadata passed to the vscode extension does not contain organization details
### Description

The metadata only contains the package name.
https://github.com/ballerina-platform/ballerina-lang/blob/master/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/PackageMetadataResponse.java#L24

The org name is  required to filter out the configurables for the current package from the config schema json after supporting the configurables of the dependencies with https://github.com/wso2-enterprise/internal-support-ballerina/issues/690

### Steps to Reproduce

_No response_

### Affected Version(s)

2201.9.2

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by LakshanWeerasinghe**
## Purpose
$subject

Fixes #43127

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/packages/MetadataTest.java [hunk 1]
```diff
@@ -76,11 +77,21 @@ private void compareResponse(String projectName, String response) {
...
+        JsonPrimitive projectKind = expectedJsonObject.getAsJsonPrimitive(KIND);
+        Assert.assertEquals(responseJsonObject.getAsJsonPrimitive(KIND), projectKind,
                 "Package MetadataTest " + KIND + " fails with " + projectName + " test case.");
         Assert.assertNotNull(responseJsonObject.getAsJsonPrimitive(PATH),
                 "Package MetadataTest " + PATH + " fails with " + projectName + " test case.");
+
+        Assert.assertNotNull(responseJsonObject.getAsJsonPrimitive(ORG_NAME),
+                "Package MetadataTest " + ORG_NAME + " fails with " + projectName + " test case.");
+
+        if (projectKind != null && !projectKind.getAsString().equals("SINGLE_FILE_PROJECT")) {
```
Comment (Dilhasha) [inline language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/packages/MetadataTest.java:90]:
```suggestion
        if (projectKind != null && !"SINGLE_FILE_PROJECT".equals(projectKind.getAsString())) {
```

**Review by mindula — APPROVED** [review]

File: language-server/modules/langserver-core/src/test/resources/packages/metadata/project-services_expected.json [hunk 2]
```diff
@@ -1,4 +1,5 @@
 {
+  "orgName": "bob",
```
Comment (SasinduDilshara) [inline language-server/modules/langserver-core/src/test/resources/packages/metadata/project-services_expected.json:2]: Dont we need to add a test for a scenario with orgName key does not exists

Comment (LakshanWeerasinghe) [reply language-server/modules/langserver-core/src/test/resources/packages/metadata/project-services_expected.json:2]: When `orgName` is not specified in `Ballerina.toml`, the `ProjectAPI` defaults to using the local machine's username as the organization name. Consequently, when the test environment changes, different `orgName` values are generated if `orgName` is absent in `Ballerina.toml`. This inconsistency makes it hard to test this.

**Review by SasinduDilshara — APPROVED** [review]
