### PR TITLE
Fix incorrect behaviour of resulting type in `bitwise-or-expr`

### LINKED ISSUE #32888: Incorrect behaviour in `bitwise-or-expr` when the static types of operands are `int:UnsignedK`
Accroding to spec 

```for XOR or OR, if the type of both operands is a subtype of int:UnsignedK when K is 8, 16 or 32, then the static type of the result is int:UnsignedN where N is the smallest such K; otherwise, the static type of the result is int.```

```bal
public function main() {
    int:Unsigned16 g = 256;
    int:Unsigned8 h = 0;

    int:Unsigned8 i = g | h; // should result in an error since the smallest such K is 16, 
                             // currently gives no error
}
```

Also 
```bal
public function main() {
    int:Unsigned16 g = 256;
    int:Unsigned8 h = 0;

    io:println((g | h) == (256 | 0));  // should give true, currenly gives false since it evaluates `g | h` to `0`
}
```

Related discussion https://github.com/ballerina-platform/ballerina-spec/issues/458#issuecomment-599018950

### PR DESCRIPTION
**Pull request by rpjayasekara**
Fixes #32888

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by MaryamZi** [comment]
@rpjayasekara, shall we change the base to stage-slbeta4?

**Comment by MaryamZi** [comment]
@rpjayasekara, seems like this now includes other commits from master also. Can you please update the PR or send a separate PR with just your changes?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java [hunk 1]
```diff
@@ -546,26 +546,26 @@ public void generateVarStore(MethodVisitor mv, BIRNode.BIRVariableDcl varDcl, in
         }
     }
 
-    private BType getSmallerUnsignedIntSubType(BType lhsType, BType rhsType) {
+    private BType getlargerUnsignedIntSubType(BType lhsType, BType rhsType) {
```
Comment (rdulmina) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:549]:
```suggestion
    private BType getPossibleUnsignedIntSubType(BType lhsType, BType rhsType) {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java [hunk 2]
```diff
@@ -546,26 +546,26 @@ public void generateVarStore(MethodVisitor mv, BIRNode.BIRVariableDcl varDcl, in
         }
     }
 
-    private BType getSmallerUnsignedIntSubType(BType lhsType, BType rhsType) {
+    private BType getPossibleUnsignedIntSubType(BType lhsType, BType rhsType) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:549]: How about something like
```suggestion
    private BType getSmallestBuiltInIntSubTypeContainingTypes(BType lhsType, BType rhsType) {
```

"Possible" doesn't quite imply what we are returning/checking for, right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java [hunk 3]
```diff
@@ -882,11 +882,11 @@ private void defineNilableIntegerBitwiseOperations(OperatorKind opKind) {
         for (int i = 0; i < unsignedNilableIntTypes.length; i++) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java:882]: Should the method name be `defineNilableIntegerBitwiseOrAndXorOperations`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java [hunk 4]
```diff
@@ -882,11 +882,11 @@ private void defineNilableIntegerBitwiseOperations(OperatorKind opKind) {
...
             for (int j = 0; j < unsignedNilableIntTypes.length; j++) {
                 defineBinaryOperator(opKind, unsignedNilableIntTypes[i], unsignedNilableIntTypes[j],
-                        i <= j ? unsignedNilableIntTypes[i] : unsignedNilableIntTypes[j]);
+                        i >= j ? unsignedNilableIntTypes[i] : unsignedNilableIntTypes[j]);
                 defineBinaryOperator(opKind, unsignedNilableIntTypes[i], unsignedIntTypes[j],
-                        i <= j ? unsignedNilableIntTypes[i] : unsignedNilableIntTypes[j]);
+                        i >= j ? unsignedNilableIntTypes[i] : unsignedNilableIntTypes[j]);
                 defineBinaryOperator(opKind, unsignedIntTypes[i], unsignedNilableIntTypes[j],
-                        i <= j ? unsignedNilableIntTypes[i] : unsignedNilableIntTypes[j]);
+                        i >= j ? unsignedNilableIntTypes[i] : unsignedNilableIntTypes[j]);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java:889]: Don't we have tests that cover nilable operands? Shall we add both negative and positive tests?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java (hunk 2 above)
Comment (rpjayasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:549]: It should be largest. How about `getLargestBuiltInIntSubTypeContainingTypes` ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java (hunk 3 above)
Comment (rpjayasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java:882]: Yeah will change it

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java (hunk 4 above)
Comment (rpjayasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java:889]: Only added for bitwise `and`, will add for `or` and `xor`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java (hunk 2 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:549]: +1 to go with smallest since it is the process of selecting `smallest K`

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmInstructionGen.java:549]: By containing types I meant containing lhsType and rhsType.

If lhsType is int:Unsigned8 and rhsType is int:Unsigned16, 
a. int:Unsigned8 contains int:Unsigned8 but not int:Unsigned16
b. int:Unsigned16 contains int:Unsigned8 and int:Unsigned16
c. int:Unsigned32 contains int:Unsigned8 and int:Unsigned16

So a is out anyway. Of b and c we select the smallest.

Maybe we can add in the Unsigned bit too
```suggestion
    private BType getSmallestBuiltInUnsignedIntSubTypeContainingTypes(BType lhsType, BType rhsType) {
```

**Comment by MaryamZi** [comment]
Shall we also add some tests with `byte`?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary_bitwise_operation_negative.bal [hunk 5]
```diff
@@ -55,4 +55,22 @@ function testBinaryBitwiseOperationsNegativeScenarios() {
...
+    int:Unsigned8? x21 = 23;
+    int:Unsigned16? x22 = 1;
+    int:Unsigned8? x23 = x21 | x22;
+
+    int:Unsigned16? x24 = 1;
+    byte? x25 = 1;
+    byte? x26 = x24 | x25;
+
+    int:Unsigned32? x27 = 1;
+    byte? x28 = x27 | x25;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary_bitwise_operation_negative.bal:75]: We need to add negative and positive tests for non-nilable cases too.

```ballerina
byte a = 1;
int:Unsigned16 b = 1;

byte c = a | b; // should be an error now
```

**Review by MaryamZi — APPROVED** [review]
