### PR TITLE
Fix "match statement matches with incorrect error"

### LINKED ISSUE #30484: Match statement matches incorrect errors when there are detail patterns
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    any|error val = error("Error!");

    match val {
        // Matches this even though there are no detail fields.
        error(var message, det = var det) => { // or `var error(message, det = det)`
            io:println("message: ", message);
            io:println("detail field `det`: ", det);            
            io:println((<error> val).detail().length());            
        }
    }
}
```

```cmd
message: Error!
detail field `det`: 
0
```

**Affected Versions:**
slbeta1

### PR DESCRIPTION
**Pull request by gimantha**
Fixes #30484

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -4577,6 +4582,45 @@ private BLangExpression createConditionForErrorFieldMatchPatterns(
         return statementExpression;
     }
 
+    private BType createMatchingRecordType(BLangErrorFieldMatchPatterns errorFieldMatchPatterns) {
+        BRecordTypeSymbol detailRecordTypeSymbol = new BRecordTypeSymbol(
+                SymTag.RECORD,
+                Flags.PUBLIC,
+                names.fromString("$anonErrorType$" + UNDERSCORE + recordCount++ + "$detailType"),
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:4589]: It is better if we can move this `$anon` name gen to `BLangAnonymousModelHelper`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 2]
```diff
@@ -4577,6 +4582,45 @@ private BLangExpression createConditionForErrorFieldMatchPatterns(
...
+                env.enclPkg.symbol.pkgID, null, null, errorFieldMatchPatterns.pos, VIRTUAL);
+
+        detailRecordTypeSymbol.initializerFunc = createRecordInitFunc();
+        detailRecordTypeSymbol.scope = new Scope(detailRecordTypeSymbol);
+        detailRecordTypeSymbol.scope.define(
+                names.fromString(detailRecordTypeSymbol.name.value + "." +
+                        detailRecordTypeSymbol.initializerFunc.funcName.value),
+                detailRecordTypeSymbol.initializerFunc.symbol);
+
+        BRecordType detailRecordType = new BRecordType(detailRecordTypeSymbol);
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:4599]: This segment is duplicated in several places (i.e `createDetailType()`), better if we can refactor that and move it out to a re-usable method.

**Review by grainier — APPROVED** [review]
LGTM

**Review by grainier — APPROVED** [review]
