### PR TITLE
Fix proxy password authentication

### LINKED ISSUE #40659: [Bug]: CLI commands - Ballerina central interaction does not work through a proxy having a password authentication
### Description

CLI commands which interact with central via a proxy(having password authentication) result following error `unexpected error occurred while pulling tool:Failed to authenticate with proxy`

### Steps to Reproduce

1) set up a proxy with username and password(tested with mitmproxy)
2) update the ~/.ballerina/Settings.toml with proxy details
3) `bal pull <package>`

### Affected Version(s)

2201.6.0 and may be lower versions too

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
Fixes #40659 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/central-client/src/main/java/org/ballerinalang/central/client/CentralAPIClient.java [hunk 1]
```diff
@@ -1261,11 +1278,27 @@ public JsonObject getConnector(ConnectorInfo connector, String supportedPlatform
...
      */
     protected OkHttpClient getClient() {
-        return new OkHttpClient.Builder()
+        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                 .followRedirects(false)
                 .retryOnConnectionFailure(true)
                 .proxy(this.proxy)
                 .build();
+
+        if ((!"".equals(this.proxyUsername) && !"".equals(this.proxyPassword))) {
```
Comment (azinneera) [inline cli/central-client/src/main/java/org/ballerinalang/central/client/CentralAPIClient.java:1287]: We can use `String.isEmpty` method here to make it more readable
