### PR TITLE
Handle IndexOutOfBoundException for wrong param count

### LINKED ISSUE #26128: Instance interop method with wrong param count throws an exception.
**Description:**
Instance interop method with wrong param count throws below exception when compiling.
```
[2020-09-25 22:24:27,909] SEVERE {b7a.log.crash} - 0 
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.validateArgumentTypes(JMethodResolver.java:274)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.validateMethodSignature(JMethodResolver.java:214)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.resolve(JMethodResolver.java:125)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropValidator.validateAndGetJMethod(InteropValidator.java:56)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropMethodGen.createJMethodWrapper(InteropMethodGen.java:779)
	at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropMethodGen.createJInteropFunctionWrapper(InteropMethodGen.java:767)
```

**Steps to reproduce:**

```java
package javalibs;
public class App {
    public void getGreeting() {
    }
}
```
```ballerina
import ballerina/java;
public function main() {
    doSomething(3);
}

function doSomething(int i) = @java:Method {
	name: "getGreeting",
	'class: "javalibs.App"
} external;
```

**Affected Versions:**
SLP4

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #26128

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples
[Test cases for Interop Exception.pdf](https://github.com/ballerina-platform/ballerina-lang/files/5611582/Test.cases.for.Interop.Exception.pdf)

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java [hunk 1]
```diff
@@ -859,19 +814,40 @@ private String getParamTypesAsString(ParamTypeConstraint[] constraints) {
...
 
-        return new JInteropException(DiagnosticErrorCode.METHOD_SIGNATURE_DOES_NOT_MATCH,
+        throw new JInteropException(DiagnosticErrorCode.METHOD_SIGNATURE_DOES_NOT_MATCH,
                 "Incompatible param type for method '" + methodName + "' in class '" + declaringClass.getName() +
                         "': Java type '" + jType.getName() + "' will not be matched to ballerina type '" +
                         (bType.tag == TypeTags.FINITE ? bType.tsymbol.name.value : bType) + "'");
     }
 
-    private JInteropException getParamCountMismatchError(JMethodRequest jMethodRequest) {
+    private JInteropException paramCountMismatchError(JMethodRequest jMethodRequest) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:847]:
```suggestion
    private JInteropException throwParamCountMismatchError(JMethodRequest jMethodRequest) {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java [hunk 2]
```diff
@@ -859,19 +814,40 @@ private String getParamTypesAsString(ParamTypeConstraint[] constraints) {
         return stringJoiner.toString();
     }
 
-    private JInteropException getNoSuchMethodError(String methodName, Class<?> jType, BType bType,
+    private JInteropException methodNotFoundError(JMethodRequest jMethodRequest) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:817]:
```suggestion
    private JInteropException throwMethodNotFoundError(JMethodRequest jMethodRequest) {
```

**Review by riyafa — APPROVED** [review]
