### PR TITLE
Fix relational operator related issues

### LINKED ISSUE #37301: Relational expressions give incorrect results for `byte`
**Description:**
$title. Seems this happens when the `byte` type is used with list constructors. In following example, both `byte` and `int:Unsigned8` scenarios should give same results.

```ballerina
import ballerina/io;

type Type17 [int, int]; 
type Type18 [int, byte]; 
type Type19 [int, int:Unsigned8]; 

public function main() {
    Type17 a = [1, 1];
    Type18 b = [1, 1];
    Type19 c = [1, 1];

    int d = 1;
    byte e = 1;

    boolean x0 = a > b;
    boolean x1 = b > a;
    io:println(x0); // false [correct]
    io:println(x1); // false [correct]

    boolean x2 = a >= b;
    boolean x3 = b >= a;
    io:println(x2); // false [incorrect!]
    io:println(x3); // false [incorrect!]

    boolean x4 = a >= c;
    boolean x5 = c >= a;
    io:println(x4); // true [correct]
    io:println(x5); // true [correct]

    boolean x6 = d >= e;
    boolean x7 = e >= d;
    io:println(x6); // true [correct]
    io:println(x7); // true [correct]
}
```

**Steps to reproduce:**
Shown above.

**Affected Versions:**
Current master.

### PR DESCRIPTION
**Pull request by SandaruJayawardana**
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/36104
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/36103
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/36102
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/35195
Fixes #37301

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -3266,7 +3271,9 @@ public Boolean visit(BType target, BType source) {
                 targetTag = getEffectiveTypeForIntersection(targetType).tag;
             }
             if (isSimpleBasicType(sourceTag) && isSimpleBasicType(targetTag)) {
-                return (source == target) || isIntOrStringType(sourceTag, targetTag);
+                // If type T is ordered, then type T? Is also ordered.
+                return (source == target) || sourceTag == TypeTags.NIL || targetTag == TypeTags.NIL ||
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3275]: Do we need nil check here, because we have check `isNil` in `isSameOrderedType` method?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 2]
```diff
@@ -3276,36 +3283,82 @@ public Boolean visit(BType target, BType source) {
...
+                //     [string, (), float, int...] can be taken as the ordered type which the static type of both
+                //     operands belong.
+                BType baseType = sourceTupleTypes.get(targetTupleCount);
+                if (!hasCommonOrderedTypeForTuples(baseType, sourceTupleTypes, targetTupleCount + 1)) {
+                    return false;
+                }
+            } else if (sourceTupleCount < targetTupleCount) {
+                // Target tuple has higher number of member types.
+                BType baseType = targetTupleTypes.get(sourceTupleCount);
+                if (!hasCommonOrderedTypeForTuples(baseType, targetTupleTypes, sourceTupleCount + 1)) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3361]: Can we rearrange this logic in order to match the following pattern?
```ballerina
if (sourceTupleCount == targetTupleCount) {
} else if (sourceTupleCount < targetTupleCount) {
} else {
}
``` 
The else if case and else case are the same, so you can create a separate function for that.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 3]
```diff
@@ -3324,6 +3377,19 @@ public Boolean visit(BTupleType target, BType source) {
                     sourceRestType);
         }
 
+        private boolean hasCommonOrderedTypeForTuples(BType baseType, List<BType> typeList, int startIndex) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3380]: Since the `baseType = typeList.get(startIndex - 1)`, can we create it here, without passing as a param?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 4]
```diff
@@ -3482,27 +3548,55 @@ public Boolean visit(BParameterizedType t, BType s) {
...
+        } else if (referredTypeKind == TypeKind.FINITE) {
+            Set<BLangExpression> valueSpace = ((BFiniteType) referredType).getValueSpace();
+            return valueSpace.size() == 1 && valueSpace.iterator().next().getBType().getKind() == TypeKind.NIL;
+        }
+        return false;
+    }
+
+    private boolean checkUnionHasSameType(BUnionType unionType, BType baseType) {
+        LinkedHashSet<BType> memberTypes = unionType.getMemberTypes();
+        boolean hasSameOrderedType = false;
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3567]: Do we need this variable? 
By looking at whole logic I think we do not need this variable, returning true is enough at the end.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 1 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3275]: But that method will not be called when the both `target`, `source` are simple basic types.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 2 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3361]: I changed the logic into the above pattern. Since each if block contains only 3 method calls, I think we can keep them as it is to improve the readability. WDYT @KavinduZoysa?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 4 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3567]: +1. We can remove that variable.

**Comment by KavinduZoysa** [comment]
@SandaruJayawardana, can you check why Codecov warnings have appeared?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 5]
```diff
@@ -3293,27 +3345,49 @@ public Boolean visit(BParameterizedType t, BType s) {
...
             type = getReferredType(type);
             if (type.tag == TypeTags.FINITE) {
                 for (BLangExpression expr : ((BFiniteType) type).getValueSpace()) {
-                    isSameType = isSameOrderedType(expr.getBType(), baseType);
-                    if (!isSameType) {
+                    if (!isSameOrderedType(expr.getBType(), baseType)) {
                         return false;
                     }
                 }
             } else if (type.tag == TypeTags.UNION) {
```
Comment (SandaruJayawardana) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3372]: This scenario is not covered with unit tests (locally test with commenting out this). I guess, unions cannot be a member type of another union. Therefore, we cannot cover this part with tests. IMO we can remove this condition. But this condition is already available in the master branch. WDYT @KavinduZoysa?

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:3372]: Please check whether tests are passing after removing this test.

Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Tests are passing even without this. (https://github.com/ballerina-platform/ballerina-lang/pull/37047/commits/85848bce6e929fd06d4002aeec1f9351f6ec1634)

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: We can go head.

**Review by KavinduZoysa — APPROVED** [review]
