### PR TITLE
[Formatter] Fix several formatting issues

### LINKED ISSUE #26001: Formatting doesn't work for unions with user-defined types
**Description:**
Sample code
```ballerina
public function main() {
    Person|error x;
}
```
Formatted output:
```ballerina
public function main() {
Person|error x;
}
```

### LINKED ISSUE #26002: A extra newline gets added every-time the code is formatted
**Description:**
Sample code
```ballerina
public function main() {
}
```
Output after formatting the code for five (5) times: 
```ballerina
public function main() {

}





```

Note the extra 5 newlines at the end of the file.

### LINKED ISSUE #26004: Formatting doesn't work properly for type-descriptors with parenthesis
**Description:**
Sample code:
```ballerina
public function main() {
    (int|string) x;
}
```
Formatted output:
```ballerina
public function main() {
(    int|string) x;
}
```

### LINKED ISSUE #26005: Formatting a while-block result in a syntax error
**Description:**
```ballerina
public function main() {
    while true {
    }
}
```
Formatted output:
```ballerina
public function main() {
    whiletrue {
    }
}
```
The whitespace between the 'while' keyword and the 'condition' has been removed, resulting a syntax error.

### PR DESCRIPTION
**Pull request by IrushiL**
## Purpose

Fixes #26002
Fixes #26001
Fixes #26005
Fixes #26004

Disables the formatting of nested if statements and query expressions in order to reduce the priority levels of the following issues.
#25999
#25988

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by sanjana** [comment]
Fixes: #26004

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 1]
```diff
@@ -2996,26 +3005,26 @@ public SelectClauseNode transform(SelectClauseNode selectClauseNode) {
...
+//                    .withQueryConstructType(queryConstructType).apply();
+//        }
+//        if (onConflictClause != null) {
+//            queryExpressionNode = queryExpressionNode.modify()
+//                    .withOnConflictClause(onConflictClause).apply();
+//        }
+//        return queryExpressionNode.modify()
+//                .withQueryPipeline(queryPipeline)
+//                .withSelectClause(selectClause)
+//                .apply();
```
Comment (sanjana) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:3027]: Shall we get rid of these comments?

Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:3027]: I think it's okay to leave it there since we have to enable it again anyway.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 2]
```diff
@@ -912,7 +914,7 @@ public SimpleNameReferenceNode transform(SimpleNameReferenceNode simpleNameRefer
 
     @Override
     public IfElseStatementNode transform(IfElseStatementNode ifElseStatementNode) {
-        if (!isInLineRange(ifElseStatementNode, lineRange)) {
+        if (!isInLineRange(ifElseStatementNode, lineRange) || !nestedIfBlock(ifElseStatementNode).isEmpty()) {
```
Comment (sanjana) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:917]: This will create an impact when formatting the following type of nested-if code. 

```
public function foo() {
    if (true) {
        
        if (1 < 2) {
            int x = 2;
        }
    } else {
        int y = 0;
        return i;
    }
}
```

Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:917]: Yeah, that is added to disable the formatting of nested if blocks, since this fix requires some time. The intention is to leave the nested if block as it is now. The following issue is there to track the fix.
https://github.com/ballerina-platform/ballerina-lang/issues/25999

**Review by SupunS — CHANGES_REQUESTED** [review]
Following seems to still give some malformed output:
```ballerina
public function foo() {
    if (true) {
        (string|error) txt = rp.getTextPayload();
        // hello world
        if (txt is string) {
            io:println("response.../n", txt);
        }
    }
}

function bar() {
    int a;
    // hello
}
```

**Comment by IrushiL** [comment]
@SupunS Fixed the issue pointed and added a test case for it.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 2 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:918]: Since the formatting of nested if blocks are disabled for now if there are formatting errors in the above code snippet, it will not get formatted. 

But if the above code is formatted as it is, then the output will also be the same.

**Review by SupunS — APPROVED** [review]
