### PR TITLE
Fix rest parameter type inference

### LINKED ISSUE #29040: Incorrect inferred type for ...x in binding pattern
This should work:

```
type XY record {
   int x; int y;
};
// any field other than x and y
type NotXY record {
   never x?; never y?;
};

public function extra(XY xy) returns NotXY {
   var {x: _, y: _,...extra} = xy;
   return extra;
}
```

But it gives an error

```
incompatible types: expected 'NotXY', found 'map<anydata>'
```

The type of `extra` should be `NotXY` since it cannot have fields `x` and `y`.

### LINKED ISSUE #29953: Incorrect type considered as the rest type when trying to destructure a record
Consider the following destructuring assignment:
```ballerina
type Person record {|
    string name;
    int mbp2;
    string...;
|};

function test() {
    string mbp1;
    int mbp2;
    map<string> rbp3;
    {name: mbp1, mbp2, ...rbp3} = <Person>{name: "Jane Doe", mbp2: 10, "foo": "bar"};
    {name: mbp1, mbp2, ...rbp3} = getPerson();
}

function getPerson() returns Person => { name: "Jane Doe", mbp2: 10, "foo": "bar" }
```
In the above, get the following error message for the rest binding pattern in both destructuring assignment statements.
```
incompatible types: expected 'map<string>', found 'map<anydata>'
```
Judging by the error message, it seems like the rest type is hardcoded? Didn't check the code, but I think it should be straight forward to get the rest field type and compare it against the constraint of the rest binding pattern.

Related to #17207 as well I think.

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #29953
Fixes #29040

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/evaluator/PatternEvaluatorTest.java [hunk 1]
```diff
@@ -36,7 +36,7 @@ public void testEvaluateTuple() throws BallerinaShellException {
         testEvaluate(TUPLE_EVALUATOR_TESTCASE);
     }
 
-    @Test
+//    @Test
```
Comment (pcnfernando) [inline ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/evaluator/PatternEvaluatorTest.java:39]: Commented due to https://github.com/ballerina-platform/ballerina-lang/issues/30570.

File: tests/jballerina-integration-test/src/test/resources/identifier/ModuleNameClashProject/Dependencies.toml [hunk 2]
```diff
@@ -0,0 +1,4 @@
+[[dependency]]
```
Comment (grainier) [inline tests/jballerina-integration-test/src/test/resources/identifier/ModuleNameClashProject/Dependencies.toml:1]: What is this for?

Comment (pcnfernando) [reply tests/jballerina-integration-test/src/test/resources/identifier/ModuleNameClashProject/Dependencies.toml:1]: When the dependency was version = "0.0.0" in the automatically created file, `IdentifierLiteralTest` was failing. When checked most of the integration tests has the `Dependencies.toml` file commited. (eg:https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/main/Dependencies.toml)
Hence, included it to avoid test ambiguity. Double checked with @HindujaB

File: ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/evaluator/PatternEvaluatorTest.java (hunk 1 above)
Comment (hasithaa) [reply ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/evaluator/PatternEvaluatorTest.java:39]: @pubudu91 Please note.

Comment (pubudu91) [reply ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/evaluator/PatternEvaluatorTest.java:39]: Ack. Will look in to this.

**Review by MaryamZi — COMMENTED** [review]
The following does not result in a compilation error. Fails at runtime instead.

```ballerina
type Person record {|
    string name;
    int age;
    string...;
|};

public function main() {
    string s;
    int age;
    map<string> rest;

    Person p = {name: "Jane Doe", age: 20, "employed": "false"};
    {name: s, ...rest} = p; // no compilation error even though the remaining fields has an `int` field 
}
```

```cmd
error: class java.lang.Long cannot be cast to class io.ballerina.runtime.api.values.BString (java.lang.Long is in module java.base of loader 'bootstrap'; io.ballerina.runtime.api.values.BString is in unnamed module of loader 'app')
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 3]
```diff
@@ -2257,10 +2269,7 @@ public void visit(BLangMatchGuard matchGuard) {
 
     @Override
```
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2270]: Actually the type doesn't seem to be a record in both cases.

```ballerina
type Person record {|
    string name;
    int age;
    string...;
|};

public function main() {
    Person p = {name: "Jane Doe", age: 20, "employed": "false"};

    match p {
        {name: var s, ...var rest} => {
            int x = rest; // ERROR: incompatible types: expected 'int', found 'map<(int|string)>'
        }
    }

    match p {
        var {name: s, ...rest} => {
            int x = rest; // ERROR: incompatible types: expected 'int', found 'map<(int|string)>'
        }
    }
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 4]
```diff
@@ -1771,9 +1774,18 @@ private void checkRecordVarRefEquivalency(Location pos, BLangRecordVarRef lhsVar
...
+            } else {
+                lhsRefType = ((BLangSimpleVarRef) lhsVarRef.restParam).type;
+            }
+            BType rhsConstraintType = symbolEnter.getRestMatchPatternConstraintType(rhsRecordType, unMappedFields,
+                    ((BRecordType) rhsType).restFieldType);
+            BType rhsResType = new BMapType(TypeTags.MAP, rhsConstraintType, null);
             types.checkType(((BLangSimpleVarRef) lhsVarRef.restParam).pos,
-                    this.symbolEnter.getRestParamType(rhsRecordType),
-                    ((BLangSimpleVarRef) lhsVarRef.restParam).type, DiagnosticErrorCode.INCOMPATIBLE_TYPES);
+                    rhsResType, lhsRefType, DiagnosticErrorCode.INCOMPATIBLE_TYPES);
```
[the remark this answers is not in the document]
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: Updated in 0efce22022660b67462de6b96c56766ffc01e440

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDestructuringTest.java [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+import org.ballerinalang.test.CompileResult;
+import org.testng.Assert;
+import org.testng.annotations.AfterClass;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Test;
+
+/**
+ * Test cases for inferring rest filed.
+ */
+public class RecordDestructuringTest {
```
[the remark this answers is not in the document]
Comment (pcnfernando) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/RecordDestructuringTest.java]: Refactored the tests in https://github.com/ballerina-platform/ballerina-lang/issues/29953

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2274]: Updated in 0efce22022660b67462de6b96c56766ffc01e440

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 6]
```diff
@@ -2517,6 +2530,58 @@ BMapType getRestParamType(BRecordType recordType)  {
...
+            unMappedFields.remove(fieldName);
+            BField newField = new BField(names.fromString(fieldName), pos,
+                    new BVarSymbol(Flags.OPTIONAL, names.fromString(fieldName), env.enclPkg.symbol.pkgID,
+                            symTable.neverType, recordSymbol, pos, VIRTUAL));
+            fields.put(fieldName, newField);
+        }
+
+        BRecordType recordVarType = new BRecordType(recordSymbol);
+        recordVarType.fields = fields;
+        BType restType = getRestMatchPatternConstraintType(recordType, unMappedFields, restConstraint);
```
[the remark this answers is not in the document]
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:2582]: This needs to be supported

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java [hunk 7]
```diff
@@ -364,14 +364,13 @@ public void visit(BRecordType bRecordType) {
         BAttachedFunction initializerFunc = tsymbol.initializerFunc;
         if (initializerFunc == null) {
             buff.writeByte(0);
-            return;
```
[the remark this answers is not in the document]
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java:367]: Encountered this while creating a virtual anon record type without the init

[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRTypeWriter.java:367]: Can we add a test?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 8]
```diff
@@ -2095,6 +2119,23 @@ private BLangInvocation generateErrorCauseLanglibFunction(Location pos, BType ca
         return createLangLibInvocationNode(ERROR_CAUSE_FUNCTION_NAME, onExpr, new ArrayList<>(), causeType, pos);
     }
 
+    private BLangInvocation generateCreateRecordValueInvocation(Location pos,
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:2122]: Can we desugar the record creation to a combination of 
1. creating a record value with a mapping constructor expression with the individual (non-rest) fields as members
2. filtering and adding the rest fields to the record value created in 1

This would be ideal.

Alternately you can create a map and call cloneWithType, but then the value has to be created twice.

One of the issues with introducing a separate method is that we would need to re-implement this record creation logic for a different runtime (e.g., nballerina),

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:2122]: Creating a map and calling cloneWithType would not work since `value:cloneWithType` only supports `anydata` https://raw.githubusercontent.com/ballerina-platform/ballerina-spec/master/lang/lib/value.bal

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:2122]: Created an issue to handle the approach without `langlib.internal` method.
https://github.com/ballerina-platform/ballerina-lang/issues/31087

**Comment by MaryamZi** [comment]
@pcnfernando, there seems to be conflicts.

There also seems to be an issue with closed records. We seem to be setting openness incorrectly with an incorrect rest type.

```ballerina
type Person record {|
    string name;
|};

public function main() {
    string s;
    map<string> rest;
    map<never> rest2;

    Person p = {name: "Jane Doe"};
    {name: s, ...rest} = p; // error says `expected 'map<string>', found 'record {| never name?; other...; |}'`


    record {| never name?; |} rec = {};
    rest2 = rec;
    {name: s, ...rest2} = p; // not allowed, even though `rest2 = rec` is allowed
}
```

Here the record should either be closed or should have `never` as the rest type.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: Did we create an issue to change this similarly for lists?

[the remark this answers is not in the document]
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java]: Created an issue https://github.com/ballerina-platform/ballerina-lang/issues/31142

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 9]
```diff
@@ -2514,17 +2570,132 @@ private boolean doesRecordContainKeys(BType varType,
         return !recordVarType.sealed;
     }
 
-    BMapType getRestParamType(BRecordType recordType)  {
-        BType memberType;
+    public BRecordTypeSymbol createAnonRecordSymbol(SymbolEnv env, Location pos) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:2573]: Should this also go in BLangAnonymousModelHelper. We can fix this separately.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 10]
```diff
@@ -2514,17 +2570,132 @@ private boolean doesRecordContainKeys(BType varType,
...
+                    new BVarSymbol(Flags.OPTIONAL, names.fromString(fieldName), env.enclPkg.symbol.pkgID,
+                            symTable.neverType, targetRestRecType.tsymbol, pos, VIRTUAL));
+            fields.put(fieldName, newField);
+        }
+
+        for (BField field : unMappedFields.values()) {
+            if (fields.containsKey(field.name.value)) {
+                BField targetField = fields.get(field.getName().value);
+                targetField.type = types.mergeTypes(targetField.type, field.type);
+            } else {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:2676]: There seems to be a codecov comment? Is this not covered by tests?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternNegativeTest.java [hunk 11]
```diff
@@ -0,0 +1,96 @@
...
+import org.ballerinalang.test.CompileResult;
+import org.testng.Assert;
+import org.testng.annotations.AfterClass;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Test;
+
+/**
+ * Test cases to verify the behaviour of the mapping-match-pattern.
+ *
+ * @since Swan Lake
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternNegativeTest.java:29]:
```suggestion
 * @since 2.0.0
```

**Review by MaryamZi — DISMISSED** [review]
We discussed https://github.com/ballerina-platform/ballerina-lang/pull/30525#discussion_r646482477 offline and decided to fix it separately due to time constraints and the impact of this change.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 9 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:2573]: atm, BLangAnonymousModelHelper only holds the number of constructs that were created so far. not the utils to create specific utils. WDYT?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 10 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:2676]: Not sure why this comment was added. The specific lines are covered from `RecordVariableDefinitionTest` junit test

**Review by MaryamZi — APPROVED** [review]
