### PR TITLE
Fix tuple rest descriptor not recognized with union type

### LINKED ISSUE #26143: Cannot use a tuple with a rest descriptor in a union with an array
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    int[1]|[int, int...] arr = [1, 2, 3];
}
```

```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
error: .::qwe.bal:2:24: invalid token '...'
error: .::qwe.bal:2:32: incompatible types: expected '(int[1]|[int,int])', found '[int,int,int]'
```

**Affected Versions:**
slp4

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$Subject

Fixes #26143

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -12860,7 +12860,14 @@ private STNode parseTypeDescOrExpr() {
                     return parseActionOrExpressionInLhs(STNodeFactory.createEmptyNodeList());
                 }
 
-                return parseTypeDescriptor(ParserRuleContext.TYPE_DESC_IN_TYPE_BINDING_PATTERN);
+                STNode typedesc =  parseTypeDescriptor(ParserRuleContext.TYPE_DESC_IN_TYPE_BINDING_PATTERN);
+                // Tuple type desc can contain rest descriptor which is not a regular type desc,
+                // hence handle it separately.
+                if (peek().kind == SyntaxKind.ELLIPSIS_TOKEN) {
+                    STNode ellipsis = parseEllipsis();
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:12867]: since we check the kind can consume directly. 
Also the method we are in is parseTypeDescOrExpr. Is it only called within a tuple?
Otherwise will have to do an additional check?

Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:12867]: since we check the kind can consume directly. 
Also the method we are in is parseTypeDescOrExpr. Is it only called within a tuple?
Otherwise will have to do an additional check?

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java]: Updated, thanx

**Review by SupunS — APPROVED** [review]
