### PR TITLE
Fix setting immutable type to main module types during test compilation

### LINKED ISSUE #35865: NPE at runtime when an immutable type is created in tests referring a type in main module
**Description:**
NPE is thrown when a type defined in the main module is being used to create an immutable type in the tests.

Stacktrace
```
java.lang.NullPointerException
        at io.ballerina.runtime.internal.types.BIntersectionType.<init>(BIntersectionType.java:66)
        at ballerina.websub.2.types.$_record_types.$populate$type$UnsubscriptionVerification(Unknown Source)
        at ballerina.websub.2.types.$_types.$createTypes(Unknown Source)
        at ballerina.websub.2.$_init.$currentModuleInit(websub)
        at ballerina.websub.2.$configurationMapper.$initAndPopulateConfigData(Unknown Source)
        at ballerina.websub$test.2.$configurationMapper.$configureInit(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.run(TesterinaFunction.java:90)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.directInvoke(TesterinaFunction.java:67)
        at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:288)
        at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:268)
        at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:132)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:92)
        at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:139)
        at org.ballerinalang.test.runtime.Main.main(Main.java:120)
```

**Steps to reproduce:**
[intersection-type-test.zip](https://github.com/ballerina-platform/ballerina-lang/files/8524191/intersection-type-test.zip)

**Affected Versions:**
[v2201.1.0-rc1](https://github.com/ballerina-platform/ballerina-lang/releases/tag/v2201.1.0-rc1)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #35865

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java [hunk 1]
```diff
@@ -324,7 +324,8 @@ private MethodVisitor createPopulateTypeMethod(ClassWriter cw, String methodName
     public void addImmutableType(MethodVisitor mv, BType type) {
         BIntersectionType immutableType = ((SelectivelyImmutableReferenceType) type).getImmutableType();
         if (immutableType == null || type.tsymbol == null || immutableType.tsymbol == null ||
-                !(immutableType.tsymbol.pkgID.equals(type.tsymbol.pkgID))) {
+                !(immutableType.tsymbol.pkgID.equals(type.tsymbol.pkgID))
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java:327]: Had to filter it at the type gen; because if we filter out while setting the immutable type at the ImmutableTypeCloner; multiple calls to `setImmutableType` for the same type would add multiple type definitions. If we are to avoid adding multiple type definitions; we'll have to either iterate through the type defs and check for the original type or maintain the previously created immutable types. Hence; went with this approach

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java:327]: Will this work when the module source doesn't have the intersection type?

e.g.,

Source has a record type `Foo` but no intersection `Foo & readonly`. But the tests have `Foo & readonly`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java [hunk 2]
```diff
@@ -333,6 +334,10 @@ public void addImmutableType(MethodVisitor mv, BType type) {
         mv.visitMethodInsn(INVOKEINTERFACE, TYPE, SET_IMMUTABLE_TYPE_METHOD, SET_IMMUTABLE_TYPE, true);
     }
 
+    private static boolean isReferringToTestPkg(BType type, BIntersectionType immutableType) {
+        return (!type.tsymbol.pkgID.isTestPkg && immutableType.tsymbol.pkgID.isTestPkg);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java:338]:
```suggestion
        return !type.tsymbol.pkgID.isTestPkg && immutableType.tsymbol.pkgID.isTestPkg;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java (hunk 1 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java:327]: Yes. It was the actal issue. I've added tests under testerina tests

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java:327]: In the immutable type cloner we check for package ID atm, right? Wouldn't checking package ID + is testable there, work? I don't get why we have to go through type definitions?

Btw, do we have a test for when `Foo` and `Foo & readonly` are in the tests also? IIRC, we did.

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/split/JvmCreateTypeGen.java:327]: Added a test. Even though we do ID+testable check, we'll need to filter the test pkg references from the main pkg.

**Review by MaryamZi — APPROVED** [review]
