### PR TITLE
Fix unreachable pattern issue in nested match-stmt

### LINKED ISSUE #27341: Getting unreachable pattern for nested match-stmt
**Description:**
$subject

**Steps to reproduce:**
```
public function main() {
    string a = "foo";
    string b = "bar";
    match a {
        "foo" => {
            match b {
                "bar" => {
                }
                _ => {
                }
            }
        }
        _ => {
        }
    }
}
```

**Affected Versions:**
slp5

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose
$subject

Fixes #27341 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 1]
```diff
@@ -864,6 +867,7 @@ public void visit(BLangMatchStatement matchStatement) {
                     containsLastPatternInStatement || (matchClause.matchGuard == null && this.hasLastPatternInClause);
         }
         this.statementReturns = allClausesReturns && containsLastPatternInStatement;
+        resetLastPatternInClause();
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:870]: Don't think we need a method here. If we want a method it is good if we can make [line 850](https://github.com/ballerina-platform/ballerina-lang/pull/27343/files#diff-6b4a8cb1f7bd56d5a95a80500c4febcba531cdde5af59b66a477acd35e8485acR850) to a method call to make things consistent.

**Review by KRVPerera — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal [hunk 2]
```diff
@@ -425,6 +425,38 @@ public function testConstPattern13() {
...
+            }
+        }
+    }
+}
+
+function testConstPattern14() {
+    assertEquals("s2", constPattern14("foo", 2));
+    assertEquals("s1", constPattern14("foo", "bar"));
+    assertEquals("s4", constPattern14(1, 2));
+    assertEquals("s3", constPattern14(1, "bar"));
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal:457]: Where do we get "s3" and "s4" from? Do these tests run?

I seem to be getting a compilation error for `constPattern14` - `this function must return a result` - which again is not correct because the function does return for all scenarios within the match statement.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:870]: IMO, it's OK to have a method, but yeah I agree that we should then change other usage too.

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:870]: Shouldn't we reset `this.hasLastPatternInClause` here to what was there before visiting the match clauses?

The following doesn't fail with this change.

```ballerina
function func(any a, any b) returns string {
    match a {
        _ => {
            match b {
                "bar" => {
                    return "s1";
                }
                _ => {
                    return "s2";
                }
            }
        }
        "foo" => { // should get an error
            
        }
    }
    return "";
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal (hunk 2 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal:457]: Fixed. I tested this with PR https://github.com/ballerina-platform/ballerina-lang/pull/27292. Therefore those changes were moved here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 1 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: This is no longer used.

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Fixed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 3]
```diff
@@ -862,6 +860,7 @@ public void visit(BLangMatchClause matchClause) {
         matchClause.declaredVars.putAll(matchClause.matchPatterns.get(0).declaredVars);
 
         analyzeNode(matchClause.blockStmt, env);
+        this.matchClauseReturns = this.statementReturns;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:863]: Please see https://github.com/ballerina-platform/ballerina-lang/pull/27292#discussion_r542087348.

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Fixed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 4]
```diff
@@ -819,11 +813,13 @@ public void visit(BLangMatchStatement matchStatement) {
             }
             this.resetErrorThrown();
             analyzeNode(matchClause, env);
-            allClausesReturns = allClausesReturns && this.matchClauseReturns;
-            containsLastPatternInStatement =
-                    containsLastPatternInStatement || (matchClause.matchGuard == null && this.hasLastPatternInClause);
+            allClausesReturns = allClausesReturns && this.statementReturns;
+            resetStatementReturns();
+            matchStatement.hasLasPattern = matchStatement.hasLasPattern
+                    || (matchClause.matchGuard == null && matchClause.hasLastPatternInClause);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:819]: I'm not sure if checking `matchGuard == null` will always produce correct results. See https://github.com/ballerina-platform/ballerina-lang/issues/27603

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 5]
```diff
@@ -1022,7 +1019,7 @@ public void visit(BLangConstPattern constMatchPattern) {
 
     @Override
     public void visit(BLangWildCardMatchPattern wildCardMatchPattern) {
-        this.hasLastPatternInClause = wildCardMatchPattern.matchesAll =
+        wildCardMatchPattern.isLastPattern = wildCardMatchPattern.matchesAll =
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Remove `matchesAll`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 4 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:819]: I will check matchGuard related issues separately.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangMatchStatement.java [hunk 6]
```diff
@@ -37,6 +37,7 @@
     public BLangExpression expr; // TODO : replace with new node `action|expression`
     public List<BLangMatchClause> matchClauses = new ArrayList<>();
     public BLangOnFailClause onFailClause;
+    public boolean hasLasPattern;
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangMatchStatement.java]: Fixed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 7]
```diff
@@ -1022,7 +1019,7 @@ public void visit(BLangConstPattern constMatchPattern) {
 
     @Override
     public void visit(BLangWildCardMatchPattern wildCardMatchPattern) {
-        this.hasLastPatternInClause = wildCardMatchPattern.matchesAll =
+        wildCardMatchPattern.isLastPattern =
                 wildCardMatchPattern.matchExpr != null && types.isAssignable(wildCardMatchPattern.matchExpr.type,
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:1023]: If we consider match-stmt, matchExpr cannot be null. 

In every match-pattern, we try keep the matchExpr of match-stmt. If we consider list-match-pattern, we cannot say the matchExpr of list-match-pattern must be same as the matchExpr of member-match-patterns. Consider below example.

```
match v {
    [1, 2] => {} 
}
```

matchExpr of [1,2] (list-match-apttern) is v. But ew cannot apply the same thing to member-match-patterns which means `1` and `2`.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern-negative.bal [hunk 8]
```diff
@@ -124,3 +124,88 @@ function testNegative2(int v) returns string {
...
+    int total = 1;
+    int age = 2;
+    match animal {
+        "Mouse" => {
+            if (total == 2) {
+                if (age > 3) {
+                    return "Age is greater that 3";
+                }
+            }
+            else {
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern-negative.bal]: Fixed

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal [hunk 9]
```diff
@@ -425,6 +425,91 @@ public function testConstPattern13() {
...
+}
+
+public function constPattern15(any animal) returns string {
+    int total = 1;
+    match animal {
+        "Mouse" => {
+            if (total == 2) {
+                return "Total 2";
+            }
+            else {
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal]: Fixed

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal [hunk 10]
```diff
@@ -425,6 +425,91 @@ public function testConstPattern13() {
...
+    match animal {
+        "Mouse" => {
+            if (total == 2) {
+                if (age > 3) {
+                    return "Age is greater that 3";
+                } else {
+                    return "Age is less than 3";
+                }
+            }
+            else {
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal]: Fixed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 11]
```diff
@@ -2614,7 +2614,6 @@ public void visit(BLangWildCardMatchPattern wildCardMatchPattern) {
         }
         BType matchExprType = wildCardMatchPattern.matchExpr.type;
         if (types.isAssignable(matchExprType, symTable.anyType)) {
-            wildCardMatchPattern.matchesAll = true;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2617]: Since we removed `matchesAll` and rely on `isLastPattern` now, shouldn't we set `isLastPattern` to true here?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/clauses/BLangMatchClause.java [hunk 12]
```diff
@@ -89,13 +89,13 @@ public void addMatchPattern(MatchPatternNode matchPattern) {
...
-        return isLastClause;
+    public boolean hasLastPatternInClause() {
+        return hasLastPatternInClause;
     }
 
     @Override
-    public void setLastClause() {
-        this.isLastClause = true;
+    public void setLastPatternInClause() {
+        this.hasLastPatternInClause = hasLastPatternInClause;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/clauses/BLangMatchClause.java:98]: Shouldn't this be
```suggestion
        this.hasLastPatternInClause = true;
```

Is `setLastPatternInClause` not used btw? If it is used, there should have been tests that failed due to this, right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 11 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2617]: It is set in CodeAnalyser because it is related to code analysing.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/clauses/BLangMatchClause.java (hunk 12 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/clauses/BLangMatchClause.java]: Removed that setter

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 13]
```diff
@@ -804,12 +799,11 @@ public void visit(BLangMatchStatement matchStatement) {
         matchExprType = matchStatement.expr.type;
 
         boolean currentErrorThrown = this.errorThrown;
-        this.hasLastPatternInClause = false;
-        boolean containsLastPatternInStatement = false;
+        this.hasLastPatternInStatement = false;
+        matchStatement.hasLastPattern = false;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:803]: Instead of adding a new field `hasLastPattern` to `BLangMatchStatement`, I think we should be able to extract this information based on just `this.hasLastPatternInStatement`.

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Yes, refactored that part

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 14]
```diff
@@ -853,16 +849,19 @@ public void visit(BLangMatchClause matchClause) {
...
-            matchPattern.isLastPattern = this.hasLastPatternInClause;
+            this.hasLastPatternInClause = this.hasLastPatternInClause || matchPattern.isLastPattern;
         }
 
         if (!patternListContainsSameVars) {
             dlog.error(matchClause.pos, DiagnosticErrorCode.MATCH_PATTERNS_SHOULD_CONTAIN_SAME_SET_OF_VARIABLES);
         }
         matchClause.declaredVars.putAll(matchClause.matchPatterns.get(0).declaredVars);
 
+        boolean hasLastPatternInStatement = this.hasLastPatternInStatement;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:860]: We can do this when visiting `BLangMatchStatement`, before L803, right? Or we will be doing this assignment and re-assignment in L864 per clause even if there is no match statement in the clause?

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Yes, changed

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern-negative.bal [hunk 15]
```diff
@@ -124,3 +124,87 @@ function testNegative2(int v) returns string {
...
+                }
+            }
+        }
+        _ => {
+            return "!Mouse";
+        }
+    }
+}
+
+
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern-negative.bal]: Removed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 16]
```diff
@@ -819,24 +814,27 @@ public void visit(BLangMatchStatement matchStatement) {
             }
             this.resetErrorThrown();
             analyzeNode(matchClause, env);
-            allClausesReturns = allClausesReturns && this.matchClauseReturns;
-            containsLastPatternInStatement =
-                    containsLastPatternInStatement || (matchClause.matchGuard == null && this.hasLastPatternInClause);
+            allClausesReturns = allClausesReturns && this.statementReturns;
+            resetStatementReturns();
+            this.hasLastPatternInStatement =
+                    this.hasLastPatternInStatement || (matchClause.matchGuard == null && this.hasLastPatternInClause);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:820]: We can move this logic to the visit of `BLangMatchClause`, right? We can probably get rid of the `hasLastPatternInClause` global variable by doing so.

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Fixed

**Review by MaryamZi — APPROVED** [review]
