### PR TITLE
[Master] Fix CCE for method access on union type

### LINKED ISSUE #26726: Bad, sad error for bound method access on union
**Description:**
$title.

https://github.com/ballerina-platform/ballerina-lang/issues/26667 has an almost similar stacktrace.

**Steps to reproduce:**
```ballerina
class Foo {
    function func(int i) returns int => i;
}

class Bar {
    function func(int i) returns int => i + 1;
}

public function main() {
    Foo|Bar ob = new Foo();
    function (int) returns int func = ob.func;
}
```

```log
[2020-11-03 22:47:19,062] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genStaticCall(JvmTerminatorGen.java:726)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genFuncCall(JvmTerminatorGen.java:689)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCall(JvmTerminatorGen.java:672)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genCallTerm(JvmTerminatorGen.java:432)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmTerminatorGen.genTerminator(JvmTerminatorGen.java:280)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.generateBasicBlocks(JvmMethodGen.java:1283)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.genJMethodForBFunc(JvmMethodGen.java:288)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmMethodGen.generateMethod(JvmMethodGen.java:2220)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.lambda$generateModuleClasses$0(JvmPackageGen.java:505)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generateModuleClasses(JvmPackageGen.java:457)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:445)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:158)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:128)
	at org.wso2.ballerinalang.compiler.CompilerDriver.codeGen(CompilerDriver.java:327)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:323)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:260)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:55)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:296)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
slp5

### PR DESCRIPTION
**Pull request by prakanth97**
## Purpose

Fixes #26726

## Approach
Add switch case for Union type method access.

## Samples
```
class EmployeeR {
    function func(int i) returns int => i;
}

class ManagerR {
    function func(int i) returns int => i+1;
}

class CompanyR {
    function func(int i) returns string => (i+2).toString();
}
```
```
public function main() {
    EmployeeR|ManagerR ob1 = new ManagerR();
    function (int i) returns int func1 = ob1.func;
}
```
```
public function main() {
    ManagerR ob2 = new EmployeeR();
    EmployeeR|ManagerR ob3 = ob2;
    function (int i) returns int func2 = ob3.func;
}
```
```
public function main() {
    CompanyR|ManagerR ob4 = new ManagerR();
    (function (int i) returns string)|function (int i) returns int func3 = ob4.func;
}
```
These test cases gave CCE. This PR will fix those.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by prakanth97** [comment]
I found another issue here
```
class ManagerR {
    function func(int i) returns int => i+1;
}

class CompanyR {
    function func(int i) returns string => (i+2).toString();
}

public function main() {
    ManagerR|CompanyR ob4 = new CompanyR();
    (function (int i) returns string)|function (int i) returns int func3 = ob4.func;
    function (int i) returns string func4 = <function (int i) returns string> func3;
}
```
This is not runtime error. But,
```
public function main() {
    CompanyR|ManagerR ob4 = new CompanyR();
    (function (int i) returns string)|function (int i) returns int func3 = ob4.func;
    function (int i) returns string func4 = <function (int i) returns string> func3;
}
```
if we swap the `CompanyR|ManagerR ob4 = new CompanyR();` union type, then it gave me the 
`Error Output: error: {ballerina}TypeCastError {"message":"incompatible types: 'isolated function (int) returns (int)' cannot be cast to 'function (int) returns (string)'"}`. I will fix and update the PR.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java [hunk 1]
```diff
@@ -733,7 +733,8 @@ private void genCall(BIRTerminator.Call callIns, PackageID packageID, int localV
         }
 
         BIRNode.BIRVariableDcl selfArg = callIns.args.get(0).variableDcl;
-        if (JvmCodeGenUtil.getReferredType(selfArg.type).tag == TypeTags.OBJECT) {
+        BType selfArgRefType = JvmCodeGenUtil.getReferredType(selfArg.type);
+        if (selfArgRefType.tag == TypeTags.OBJECT  || selfArgRefType.tag == TypeTags.UNION) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java:737]: Do we know for what kind of call instructions we get to the else block here? Just wondering if we can get there for non-object unions, in which case this change will evaluate to true here and cause wrong code generation.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal [hunk 2]
```diff
@@ -353,10 +353,45 @@ function testFieldAccessOnMapConstruct() returns boolean {
     return "Sanjiva" == name;
 }
 
+class EmployeeR {
+    function func(int i) returns int => i;
+}
+
+class ManagerR {
+    function func(int i) returns int => i+1;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:361]:
```suggestion
    function func(int i) returns int => i + 1;
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal [hunk 3]
```diff
@@ -353,10 +353,45 @@ function testFieldAccessOnMapConstruct() returns boolean {
...
+}
+
+class CompanyR {
+    function func(int i) returns string => (i+2).toString();
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:365]:
```suggestion
    function func(int i) returns string => (i + 2).toString();
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal [hunk 4]
```diff
@@ -353,10 +353,45 @@ function testFieldAccessOnMapConstruct() returns boolean {
...
+
 isolated function isEqual(anydata|error val1, anydata|error val2) returns boolean {
     if (val1 is anydata && val2 is anydata) {
         return (val1 == val2);
     } else {
         return (val1 === val2);
     }
 }
+
+function assertEqual(anydata actual, anydata expected) {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:392]:
```suggestion
function assertEquals(anydata actual, anydata expected) {
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java (hunk 1 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java:737]: https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java#L746 This line is not reached by any of the unit-tests, Do we need this if else check here? @warunalakshitha @manuranga

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java:737]: It looks like the only possible types reach here are Ballerina objects and union of objects. Compiler won't allow to write a program where the `selfArgRefType` is a non-object union. So IMO, there are no possibilities to a wrong code generation. 
Furthermore, It seems the else part is no longer in use. We can create a separate task to remove unused lines.

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java:737]: @prakanth97 please create a task for this just to track this

**Review by pcnfernando — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java (hunk 1 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTerminatorGen.java:737]: Created https://github.com/ballerina-platform/ballerina-lang/issues/38599

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal [hunk 5]
```diff
@@ -353,10 +353,45 @@ function testFieldAccessOnMapConstruct() returns boolean {
...
+    EmployeeR|ManagerR ob3 = ob2;
+    function (int i) returns int func2 = ob3.func;
+    assertEquals(func2(1), 1);
+
+    CompanyR|ManagerR ob4 = new ManagerR();
+    (function (int i) returns string)|function (int i) returns int func3 = ob4.func;
+    function (int i) returns int func4 = <function (int i) returns int> func3;
+    assertEquals(func4(1), 2);
+}
+
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:383]:
```ballerina
class EmployeeR {
    function func(int i) returns int => i;
}

class ManagerR {
    function func(int i) returns int => i + 1;
}


function dummyTest() {
    EmployeeR|ManagerR p = new ManagerR();
    print(p.func(1)); // @error undefined function 'func' in type '(EmployeeR|ManagerR)']
}

```

Here, the error is not correct because both members have the same func

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal [hunk 6]
```diff
@@ -353,10 +353,45 @@ function testFieldAccessOnMapConstruct() returns boolean {
...
+    ManagerR ob2 = new EmployeeR();
+    EmployeeR|ManagerR ob3 = ob2;
+    function (int i) returns int func2 = ob3.func;
+    assertEquals(func2(1), 1);
+
+    CompanyR|ManagerR ob4 = new ManagerR();
+    (function (int i) returns string)|function (int i) returns int func3 = ob4.func;
+    function (int i) returns int func4 = <function (int i) returns int> func3;
+    assertEquals(func4(1), 2);
+}
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:382]: Below throws an undefined function error
```ballerina
class EmployeeR {
    function func(int i) returns int => i;
}

class ManagerR {
    function func(int i) returns int => i + 1;
}


function dummyTest() {
    EmployeeR|ManagerR p = new ManagerR();
    var func2 = p.func;
    print(func2(1));
}
```

**Review by pcnfernando — CHANGES_REQUESTED** [review]
Added few failing cases

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal (hunk 5 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:383]: Is this error acceptable here `function invocation on type '(function (int) returns (int)|function (int) returns (int))' is not supported` ?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal (hunk 6 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:382]: Is this error acceptable here function invocation on type '(function (int) returns (int)|function (int) returns (int))' is not supported ?

**Comment by prakanth97** [comment]
Holding this until this issue https://github.com/ballerina-platform/ballerina-spec/issues/1187 sorted

**Comment by hasithaa** [comment]
@MaryamZi @prakanth97 I think, we should disable allowing the call-expr on the union of function types, even with the union has the same shape.  This has multiple edge cases, so better to wait until the spec issue to support this in the compiler.

**Comment by MaryamZi** [comment]
> @MaryamZi @prakanth97 I think, we should disable allowing the call-expr on the union of function types, even with the union has the same shape. This has multiple edge cases, so better to wait until the spec issue to support this in the compiler.

This is already disallowed, right?

Related issue from some time ago - https://github.com/ballerina-platform/ballerina-lang/issues/19061.

**Comment by prakanth97** [comment]
> > @MaryamZi @prakanth97 I think, we should disable allowing the call-expr on the union of function types, even with the union has the same shape. This has multiple edge cases, so better to wait until the spec issue to support this in the compiler.
> 
> This is already disallowed, right?
> 
> Related issue from some time ago - #19061.

```
  ManagerR|CompanyR ob4 = new CompanyR();
  _ = ob4.func(1);
```
This is restricted already. But inorder to solve the current NPE issue. We should restrict `ob4.func` variable ref to the function and give error like `undefined function 'func' in type '(ManagerR|CompanyR)'`. WDYT @MaryamZi @hasithaa ?

**Comment by MaryamZi** [comment]
> > > @MaryamZi @prakanth97 I think, we should disable allowing the call-expr on the union of function types, even with the union has the same shape. This has multiple edge cases, so better to wait until the spec issue to support this in the compiler.
> > 
> > 
> > This is already disallowed, right?
> > Related issue from some time ago - #19061.
> 
> ```
>   ManagerR|CompanyR ob4 = new CompanyR();
>   _ = ob4.func(1);
> ```
> 
> This is restricted already. But inorder to solve the current NPE issue. We should restrict `ob4.func` variable ref to the function and give error like `undefined function 'func' in type '(ManagerR|CompanyR)'`. WDYT @MaryamZi @hasithaa ?

What's the NPE issue? `ob4.func` should still work IMO. What shouldn't work is using that in a function/method call expression `ob4.func()`.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal (hunk 6 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:382]: According to the conclusion in this issue https://github.com/ballerina-platform/ballerina-lang/issues/19061, the error msg seems correct.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal (hunk 5 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:383]: According to the conclusion in this issue https://github.com/ballerina-platform/ballerina-lang/issues/19061, the error msg seems correct.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal (hunk 6 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:387]: Added tests 4641678dbfff23698c0bc6fe3221e804d60c6da6. hence resolving

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal [hunk 7]
```diff
@@ -353,10 +353,50 @@ function testFieldAccessOnMapConstruct() returns boolean {
...
+
+class ManagerR {
+    function func(int i) returns int => i + 1;
+}
+
+class CompanyR {
+    function func(int i) returns string => (i + 2).toString();
+}
+
+function testAccessingMethodOnUnionObjectType() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:368]: Where is this invoked from?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal [hunk 8]
```diff
@@ -376,3 +376,32 @@ function testInvalidBoundMethodAccessWithRemoteMethod(ServiceClass a,
...
+    _ = func1(1);
+
+    var func2 = ob1.func;
+    _ = func2(1);
+
+    ManagerR|EmployeeR ob2 = new EmployeeR();
+    _ = ob2.func();
+
+    var func3 = ob1.func;
+    _ = func3(1);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal:406]: These should go in a separate test file IMO. E.g., with tests for method calls, since these are no longer field access.

Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access_negative.bal]: Updated 79d7ed91adf3807fa51e7ae00800fa937d4ea30a

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal (hunk 7 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/field_access.bal:368]: Updated 79d7ed91adf3807fa51e7ae00800fa937d4ea30a

**Review by lasinicl — APPROVED** [review]

**Comment by prakanth97** [comment]
> @prakanth97 there are conflicts.

Updated e5a505e2926782fcca021f5ae7e8267763bf3aa1

**Review by hasithaa — APPROVED** [review]

**Review by pcnfernando — APPROVED** [review]
