### PR TITLE
Fix several issues with dependently-typed functions and type checking

### LINKED ISSUE #28672: Bad sad error when compiling following async call
**Description:**
Occurs after the change mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/28671

```
future<http:Response|http:ClientError> asyncInvo = start clientEP2->get("/httpClientActionBE/greeting");
```

Error:
```
[2021-02-16 19:00:48,967] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType (org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType and org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType are in unnamed module of loader 'app') 
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType cannot be cast to class org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType (org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType and org.wso2.ballerinalang.compiler.semantics.model.types.BFutureType are in unnamed module of loader 'app')
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.rewriteAsyncInvocations(JvmObservabilityGen.java:286)
	at org.wso2.ballerinalang.compiler.bir.codegen.JvmObservabilityGen.instrumentPackage(JvmObservabilityGen.java:165)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:78)
	at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generateTestModule(CodeGenerator.java:71)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:270)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:54)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:326)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:136)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:122)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:135)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:199)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)


```

### LINKED ISSUE #28687: Compiler crashes for dependently-typed function when the arguments are passed via the rest arg
**Description:**
$title.

**Steps to reproduce:**
Crashes for both of the following.
```ballerina
function get(typedesc<int|string> targetType) returns targetType = external;

public function main() {
    string s1 = get(...[string]);

    record {|typedesc<int|string> targetType;|} rec = {targetType: string};
    string s2 = get(...rec);
}
```

```log
[2021-02-17 11:18:17,493] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.wso2.ballerinalang.compiler.util.ResolvedTypeBuilder.createParamMap(ResolvedTypeBuilder.java:417)
	at org.wso2.ballerinalang.compiler.util.ResolvedTypeBuilder.build(ResolvedTypeBuilder.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvocationArgs(TypeChecker.java:5679)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvocationParam(TypeChecker.java:5457)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvocationParamAndReturnType(TypeChecker.java:5344)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkFunctionInvocationExpr(TypeChecker.java:5042)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2667)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:115)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:370)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:349)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:824)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3771)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3739)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3731)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1890)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3771)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3739)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:3735)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:444)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3771)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:416)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3771)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3739)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3731)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:311)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:276)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:217)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:115)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:374)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:53)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:136)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:122)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:129)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:155)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Affected Versions:**
slalpha2-SNAPSHOT

### LINKED ISSUE #28749: Issue in type checking of futures
**Description:**
$title.

**Steps to reproduce:**
`d`, `e`, and `f` do not produce errors.

```ballerina
type IntOrString int|string;

public function main() {
    Client cl = new;

    int|string a = cl.get("", IntOrString); // error: expected '(int|string)', found '(int|string|error)'
    int|string b = cl->remoteGet("", IntOrString); // error: expected '(int|string)', found '(int|string|error)'
    int|string c = get("", IntOrString); // error: expected '(int|string)', found '(int|string|error)'

    // No errors!
    future<int|string> d = start cl.get("", IntOrString);
    future<int|string> e = start cl->remoteGet("", IntOrString);
    future<int|string> f = start get("", IntOrString);

    int g = cl.get("", int); // error: incompatible types: expected 'int', found '(int|error)'
    int h = cl->remoteGet("", int); // error: incompatible types: expected 'int', found '(int|error)'
    int i = get("", int); // error: incompatible types: expected 'int', found '(int|error)'

    future<int> j = start cl.get(""); // error: incompatible types: expected 'future<int>', found 'future<(int|error)>'
    future<int> k = start cl->remoteGet("", int); // error: incompatible types: expected 'future<int>', found 'future<(int|error)>'
    future<int> l = start get("", int); // error: incompatible types: expected 'future<int>', found 'future<(int|error)>'
}

function get(int|string x, typedesc<int|string> y) returns y|error = external;

client class Client {
    function get(int|string x, typedesc<int|string> y = int) returns y|error = external;

    remote function remoteGet(int|string x, typedesc<int|string> y) returns y|error = external;
}
```

**Affected Versions:**
slalpha2

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/28672

### LINKED ISSUE #28766: Issue in type checking for array assignment to tuples at compile time
**Description:**
$title.

**Steps to reproduce:**
The `[int, string...] z = x;` assignment should work.

```ballerina
public function main() {
    int[1] x = [1];
    [int, int...] y = x; // Allowed.
    [int, string...] z = x; // Error! incompatible types: expected '[int,string...]', found 'int[1]'

    // Runtime checks are OK.
    any a = x;
    boolean b1 = a is [int, int...]; // true
    boolean b2 = a is [int, string...]; // true
}
```

**Affected Versions:**
slalpha2

### LINKED ISSUE #28785: Dependently-typed functions don't work for XML via BIRSymbolEnter
**Description:**
$title. Came across this when trying to enable the `testXml` test in [VariableReturnTypesBalaTest](https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/functions/VariableReturnTypesBalaTest.java#L73). Crashes on slalpha2.

Happens because the XML type is not marked as a parameterized type at BIR symbol enter.

**Steps to reproduce:**
Package `bar` containing dependently-typed function with dependently-typed XML type.
```ballerina
import ballerina/jballerina.java;

public type ItemType xml:Element|xml:Comment|xml:ProcessingInstruction|xml:Text;

public function getXML(typedesc<ItemType> td, xml value) returns xml<td> = @java:Method {
    'class: "org.maryam.Test"
} external;
```

Package `foo` in which it is used.
```ballerina
import maryam/bar;

type XmlElement xml:Element;

public function main() {
    xml<xml:Element> x = bar:getXML(XmlElement, xml `foo`);
}
```

Compilation crashes for `foo`.
```log
[2021-02-19 23:00:59,233] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.util.ResolvedTypeBuilder.visit(ResolvedTypeBuilder.java:381)
	at org.wso2.ballerinalang.compiler.util.ResolvedTypeBuilder.visit(ResolvedTypeBuilder.java:65)
	at org.wso2.ballerinalang.compiler.semantics.model.types.BParameterizedType.accept(BParameterizedType.java:65)
	at org.wso2.ballerinalang.compiler.util.ResolvedTypeBuilder.build(ResolvedTypeBuilder.java:77)
	at org.wso2.ballerinalang.compiler.util.ResolvedTypeBuilder.build(ResolvedTypeBuilder.java:83)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isParameterizedTypeAssignable(Types.java:982)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:806)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isXMLTypeAssignable(Types.java:1158)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:814)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:624)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.checkType(Types.java:215)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.checkType(Types.java:194)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.checkType(Types.java:187)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvocationParamAndReturnType(TypeChecker.java:5345)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkFunctionInvocationExpr(TypeChecker.java:5042)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2667)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:115)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:370)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:349)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:824)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3771)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3739)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3731)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1890)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3771)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3739)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:3735)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:444)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3771)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:416)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3771)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:3739)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:3731)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:311)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:276)
	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:217)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:115)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:374)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:323)
	at io.ballerina.projects.PackageCompilation.compileIfRequired(PackageCompilation.java:148)
	at io.ballerina.projects.PackageCompilation.diagnosticResult(PackageCompilation.java:102)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.process(DefaultObservabilitySymbolCollector.java:87)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:118)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:129)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:155)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Affected Versions:**
slalpha2

### LINKED ISSUE #29039: Invalid compilation error for method with included record parameters
**Description:**
I have a remote method which implemented as a Dependently typed function signature in a client class.

```ballerina
public type ClientActionOptions record {|
    string mediaType?;
    map<string|string[]> headers?;
|};

remote function post(@untainted string path, RequestMessage message, *ClientActionOptions options,
        TargetType targetType = Response) returns @tainted targetType|ClientError = @java:Method {
    'class: "org.ballerinalang.net.http.actions.httpclient.HttpClientAction"
} external;
```    

The error occurs only when both the values of `ClientActionOptions` are present. Otherwise works fine.

```ballerina
string payload = checkpanic testMy00TestClient->post("/testHello/foo/goo", "abc", mediaType = "application/json", 
        headers = {"x-type": "hello", "y-type": ["yello", "go"]}, targetType = string);
```

Error 
```
incompatible types: expected '(string|error)', found '(ballerina/http:1.1.0-alpha5:Response|ballerina/http:1.1.0-alpha5:Error
```        

**Affected Versions:**
SL-alpha2

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
This PR fixes the following issues related to dependently-typed functions.
- Fixes #28687 - Compiler crashes for dependently-typed function when the arguments are passed via the rest arg
- Fixes #28672 - Bad sad error when compiling following async call
- Fixes #28785 - Dependently-typed functions don't work for XML via BIRSymbolEnter
- Fixes #29039 - Invalid compilation error for dependently-typed method with included record parameters

This PR also fixes the following type checking issues that had to be fixed in order to fix some of the above issues.
- Fixes #28749 - Issue in type checking of futures
- Fixes #28766 - Issue in type checking for array assignment to tuples at compile time

This PR also enables some disabled tests and renames the dependently-typed function tests.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -7951,15 +7952,26 @@ private void reorderArguments(BLangInvocation iExpr) {
...
+                valueExpr.type = symTable.anyOrErrorType; // Use any|error for tuple since it's a ref array.
+            }
 
             BLangExpression pushExpr = addConversionExprIfRequired(valueExpr, restParamType.eType);
             BLangExpressionStmt expressionStmt = createExpressionStmt(pos, foreachBody);
             BLangInvocation pushInvocation = createLangLibInvocationNode(PUSH_LANGLIB_METHOD, arrayVarRef,
-                                                                         new ArrayList<BLangExpression>() {{
-                                                                             add(pushExpr);
-                                                                         }}, restParamType, pos);
+                                                                         new ArrayList<>() {{ add(pushExpr); }},
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:7973]: Can't `List.of(pushExpr)` be used here?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Fixed in c010048.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -5683,13 +5690,17 @@ private BType checkInvocationArgs(BLangInvocation iExpr, List<BType> paramTypes,
...
+                        restType = this.resultType;
+                    }
                 }
             }
         }
 
         BType retType = typeParamAnalyzer.getReturnTypeParams(env, bInvokableType.getReturnType());
-        if (Symbols.isFlagOn(invokableSymbol.flags, Flags.NATIVE)
-                && Symbols.isFlagOn(retType.flags, Flags.PARAMETERIZED)) {
+        if (restType != symTable.semanticError &&
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5701]: Why do we need this check? If there's an issue in the rest type, shouldn't the type builder handle it? 🤔

**Review by pubudu91 — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5701]: If there is an issue with the rest arg that would mean that the arguments passed are incorrect, right? IINM, the resolved type builder assumes that the arguments are provided correctly. For non rest args we seem to be returning at L5589 itself if there is an error.

Anyway given that the return type depends on the arguments IMO it is OK for the resolved type builder to expect a correct function/method call expression since even a simple change to fix the arguments can affect the return type.
