### PR TITLE
Fix runtime SO related to filler value check with recursive tuples 

### LINKED ISSUE #31417: Compiler crashes when there are two cyclic type definitions with the same name
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Foo [int, Foo[2]];
type Foo [int, map<Foo>];
```

```log
[2021-06-25 09:39:04,210] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.getCyclicDefinedType(SymbolEnter.java:1721)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:1390)
        at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:111)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:275)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$defineTypeNodes$14(SymbolEnter.java:1140)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineTypeNodes(SymbolEnter.java:1140)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:384)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:318)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:275)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:268)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:377)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:174)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:166)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:95)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
        at io.ballerina.projects.Package.getCompilation(Package.java:135)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:64)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:163)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Affected Versions:**
slbeta2-rc3

### LINKED ISSUE #31419: Runtime filler value check results in a SO error with cyclic tuple type definitions
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Foo [int, Foo[2]];
type Bar [int, Foo[]];
```

**Affected Versions:**
slbeta2-rc3

### PR DESCRIPTION
**Pull request by suleka96**
## Purpose
Restricts two `type definitions` with the same name from getting defined and fixes the runtime stack overflow when checking filler values.  

Fixes #31419
Fixes #31417

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 1]
```diff
@@ -1706,6 +1701,16 @@ private BType defineSymbolsForCyclicTypeDefinitions(BLangTypeDefinition typeDef,
         return newTypeNode;
     }
 
+    private BType defineSymbolsForCyclicTypeDefinitions(BLangTypeDefinition typeDef, SymbolEnv env) {
+        BType newTypeNode;
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1705]: You don't need the `newTypeNode`. Return in the if check

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 2]
```diff
@@ -2923,23 +2923,36 @@ private static boolean hasFillerValue(Type type, List<Type> unanalyzedTypes) {
...
             case TypeTags.UNION_TAG:
                 return checkFillerValue((BUnionType) type, unanalyzedTypes);
             default:
                 return false;
         }
     }
 
+    private static boolean checkFillerValue(BTupleType tupleType,  List<Type> unAnalyzedTypes) {
+        if (unAnalyzedTypes.contains(tupleType)) {
+            return true;
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2944]: Shall we add a test to cover this

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 3]
```diff
@@ -1706,6 +1701,16 @@ private BType defineSymbolsForCyclicTypeDefinitions(BLangTypeDefinition typeDef,
...
+        BSymbol foundSym = symResolver.lookupSymbolInMainSpace(env, names.fromIdNode(typeDef.name));
+        if (foundSym != symTable.notFoundSymbol) {
+            newTypeNode = foundSym.type;
+            return newTypeNode;
+        }
+        return createSymbolAndDefineInScope(typeDef, env);
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1711]: When can the symbol be null? Shall we add a test

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 4]
```diff
@@ -1676,16 +1676,11 @@ private void defineTypeInMainScope(BTypeSymbol typeDefSymbol, BLangTypeDefinitio
         }
     }
 
-    private BType defineSymbolsForCyclicTypeDefinitions(BLangTypeDefinition typeDef, SymbolEnv env) {
+    private BType createSymbolAndDefineInScope(BLangTypeDefinition typeDef, SymbolEnv env) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1679]: Shall we rename the two methods? Maybe `defineSymbolForCyclicTypeDefinition` and `getCyclicType`. wdyt?

File: tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions-cyclic-negative.bal [hunk 5]
```diff
@@ -42,3 +42,17 @@ const XAny = "any";
 type XUnion1 "union"|P;
 
 type S [XNil|S[]|XListRef];
+
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/resources/test-src/typedefs/type-definitions-cyclic-negative.bal:45]:
```ballerina
type Foo [int, Foo[2]];
type Foo int|Foo[];
```
causes a class cast exception. We can handle it separately as well

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 6]
```diff
@@ -2923,23 +2923,36 @@ private static boolean hasFillerValue(Type type, List<Type> unanalyzedTypes) {
             case TypeTags.ANY_TAG:
                 return true;
             case TypeTags.ARRAY_TAG:
-                return checkFillerValue((BArrayType) type);
+                return checkFillerValue((BArrayType) type, unanalyzedTypes);
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2926]: Not related to this PR, but we should probably be using a set instead of a list for unanalyzedTypes. Can you please create an issue for this?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 7]
```diff
@@ -2923,23 +2923,36 @@ private static boolean hasFillerValue(Type type, List<Type> unanalyzedTypes) {
...
+            return true;
+        }
+        unAnalyzedTypes.add(tupleType);
+
+        for (Type member : tupleType.getTupleTypes()) {
+            if (!hasFillerValue(member, unAnalyzedTypes)) {
+                return false;
+            }
+        }
+        return true;
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2953]: Can you verify if the codecov comments are false negatives?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 8]
```diff
@@ -1144,7 +1144,19 @@ private void defineTypeNodes(List<BLangNode> typeDefs, SymbolEnv env) {
                 }
             }
             defineAllUnresolvedCyclicTypesInScope(env);
-            unresolvedTypes.forEach(type -> defineNode(type, env));
+
+            Set<BLangIdentifier> reDeclaredCyclicTypeDef = new HashSet<>();
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1148]:
```suggestion
            Set<BLangIdentifier> reDeclaredCyclicTypeDefs = new HashSet<>();
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1148]: Doesn't this set contain non-redeclared typedefs also? Is the name accurate?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java (hunk 6 above)
Comment (suleka96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2926]: #31894

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java (hunk 7 above)
Comment (suleka96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2953]: The flow goes through the 'true' scenario for examples under `testFillerValueCyclicTuple` in  `type-definitions-cyclic-negative`

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java (hunk 2 above)
Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2944]: @suleka96, is this covered? There is still a codecov comment.

**Comment by MaryamZi** [comment]
Need to verify https://github.com/ballerina-platform/ballerina-lang/pull/31546#discussion_r677197152.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java (hunk 2 above)
Comment (suleka96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2990]: done

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 9]
```diff
@@ -1782,8 +1789,9 @@ private BType defineSymbolsForCyclicTypeDefinitions(BLangTypeDefinition typeDef,
     }
 
     private BType getCyclicDefinedType(BLangTypeDefinition typeDef, SymbolEnv env) {
-        //define symbols in main scope
-        BType newTypeNode = defineSymbolsForCyclicTypeDefinitions(typeDef, env);
+        // Get cyclic type reference from main scope
+        BSymbol foundSym = symResolver.lookupSymbolInMainSpace(env, names.fromIdNode(typeDef.name));
```
[the remark this answers is not in the document]
Comment (suleka96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1793]: Didn't quite understand what you meant but `getCyclicDefinedType` method only gets called for cyclic types.

[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1793]: If there are two type definitions of the same name, when and if we get here, will it always be guaranteed that whatever defined is the cyclic type definition? Or if we look up in the main symbol space, we may get the other type definition?

[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1793]: Tried some scenarios locally and didn't run into any issues.

**Review by MaryamZi — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/typedefs/tuple-type-definitions-cyclic.bal [hunk 10]
```diff
@@ -182,6 +185,9 @@ function testIndirectRecursion() {
         test6 = [["nil", [], "&"]];
     }
     assert(test6[0][1][0] is string, true);
+
+    K tempTuple = [1, []];
+    assert(tempTuple[1] is J[], true);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/typedefs/tuple-type-definitions-cyclic.bal:190]: Let's add some filler value usage tests if we don't have already.

e.g.,
```ballerina
type Foo [int, Foo[]];

function testFn() {
    Foo[] f = [[1]];
    f[2] = [10, []];
    // assert f[1] here
}
```

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/typedefs/tuple-type-definitions-cyclic.bal:190]: We can do this in a separate PR.
