### PR TITLE
[Shell] Improve the error message related to reserved functions

### LINKED ISSUE #31880: Improve the error message when defining 'main' function in shell
**Description:**
It would be ideal to change the error message when defining a function with the name "main" .

**Steps to reproduce:**
As of now, it prints the error message as `redeclared symbol 'main'`. But, in user point of view they haven't already declared function with the name "main". IMO, it would be idea to say `function "main" is not allowed in shell`

```ballerina
=$ import ballerina/io;                                                                                                                                                         took 0 ms
 >
 >
 > public function main() {
 >     io:println("hello");
 > }
 >
| error: redeclared symbol 'main'
| 	public function main() {
| 	                ^--^
| Compilation aborted due to errors.
```

### PR DESCRIPTION
**Pull request by DamithaSenevirathne**
## Purpose

Fixes #31880 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java [hunk 1]
```diff
@@ -60,4 +66,18 @@ public Node parseSource(String source) throws ParserTrialFailedException {
         }
         return dclnNode;
     }
+
+    private void validateModuleDeclaration(ModuleMemberDeclarationNode declarationNode) throws InvalidMethodException {
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java:70]: `InvalidMethodException` is not a checked exception.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java [hunk 2]
```diff
@@ -60,4 +66,18 @@ public Node parseSource(String source) throws ParserTrialFailedException {
...
+        if (declarationNode instanceof FunctionDefinitionNode) {
+            String functionName = ((FunctionDefinitionNode) declarationNode).functionName().text();
+            if (RESTRICTED_FUNCTION_NAMES.contains(functionName)) {
+                String message = "Function name " + "'" + functionName + "'" + " not allowed in Ballerina Shell.\n";
+                throw new InvalidMethodException(message);
+            }
+            if (functionName.startsWith("__")) {
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java:77]: What't the reason for this restriction? 🤔

File: ballerina-shell/modules/shell-core/src/test/resources/testcases/treeparser.dclnname.json [hunk 3]
```diff
@@ -0,0 +1,6 @@
+[
+  {
+    "name": "Input invalid function name.",
+    "input": "function main(string value) { };"
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/test/resources/testcases/treeparser.dclnname.json:4]: Not just main. Add for the other case as well.

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java (hunk 1 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java]: Updated in fb1b7b1aa02f28366be706cd2d53dddafb176c76

File: ballerina-shell/modules/shell-core/src/test/resources/testcases/treeparser.dclnname.json (hunk 3 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/test/resources/testcases/treeparser.dclnname.json]: Added testcases in fb1b7b1aa02f28366be706cd2d53dddafb176c76

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java (hunk 2 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java:77]: Current shell `.bal` file template uses function names starting from `__`. Because of that reason it is required to avoid functions starting from `__`

Comment (pubudu91) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java:77]: Shall we create an issue for that? That's something we could look at improving, later on.

File: ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/TrialTreeParserTest.java [hunk 4]
```diff
@@ -90,4 +102,12 @@ private void testParse(String fileName, Class<?> parentClazz) {
             }
         }
     }
+
+    private void testModuleDclnName(String fileName) throws TreeParserException {
+        TestCases testCases = TestUtils.loadTestCases(fileName, TestCases.class);
+        TreeParser treeParser = TestUtils.getTestTreeParser();
+        for (TestCase testCase : testCases) {
+                treeParser.parse(testCase.getInput());
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/TrialTreeParserTest.java:110]: slight formatting issue here

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java [hunk 5]
```diff
@@ -75,6 +76,10 @@ public Node parse(String source) throws TreeParserException {
             } catch (ParserRejectedException e) {
                 errorMessage = "Invalid statement: " + e.getMessage();
                 break;
+            } catch (InvalidMethodException e) {
+                errorMessage = e.getMessage();
+                addErrorDiagnostic(errorMessage);
+                throw new TreeParserException();
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java:82]: What's the reason for throwing another exception here? 🤔

File: ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/TrialTreeParserTest.java [hunk 6]
```diff
@@ -76,6 +78,16 @@ public void testMiscParse() {
...
 
+    @Test(expectedExceptions = TreeParserException.class)
+    public void testModuleDclnNameMainTest() throws TreeParserException {
+        testModuleDclnName(MODULE_DCLN_MAIN_TESTCASE);
+    }
+
+    @Test(expectedExceptions = TreeParserException.class)
+    public void testModuleDclnNameDoubleUnderscoreTest() throws TreeParserException {
+        testModuleDclnName(MODULE_DCLN_UNDERSCORE_TESTCASE);
+    }
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/TrialTreeParserTest.java:89]: BTW, what about a test for the init function?

File: ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/TrialTreeParserTest.java (hunk 4 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/TrialTreeParserTest.java]: Fixed in 5732df29120212bc9c5639fb1901b98d6172d290

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java (hunk 5 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java]: Removed in 5732df29120212bc9c5639fb1901b98d6172d290

File: ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/TrialTreeParserTest.java (hunk 6 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/test/java/io/ballerina/shell/test/unit/TrialTreeParserTest.java]: Added in 5732df29120212bc9c5639fb1901b98d6172d290

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java (hunk 2 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/trials/ModuleMemberTrial.java:77]: https://github.com/ballerina-platform/ballerina-lang/issues/32493

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java (hunk 5 above)
Comment (pubudu91) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java]: No I meant, was that added with a reason? If it was added for a reason, it's ok. Otherwise no point since the same exception is thrown at the end of the method.

**Review by pubudu91 — APPROVED** [review]
