### PR TITLE
Load project to update current package after code generation in build tools

### LINKED ISSUE #42305: [Bug]: Getting a compilation error when Client is generated in the `bal build`
### Description

I am in the process of integrating bal persist client generation into the `bal build` command. The whole purpose of having integrated is that you don't have to commit the generated code. Therefore, if we have code written using the client generated during the bal build, it should function smoothly without any problems.

However, even though the client is generated in the bal build before compiling resources, it results in a compilation error stating "unknown type 'Client'".

### Steps to Reproduce

Screenshot 2024-03-12 at 12 07 15

### Affected Version(s)

Using the lang timestamp version 2201.9.0-20240229-103900-a949e6d4

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by ShammiL**
Fixes #42305

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunBallerinaPreBuildToolsTask.java [hunk 1]
```diff
@@ -121,13 +123,21 @@ public void execute(Project project) {
...
+                outStream.printf("WARNING: Skipping execution of build tool %s(%s) as Ballerina.toml " +
+                        "contains errors%n%n", tool.type(), tool.id() != null ? tool.id() : "");
             }
         }
+        // Load current package to load the generated code
+        loadPackage(project);
         project.setToolContextMap(toolContextMap);
     }
 
+    private void loadPackage(Project project) {
```
Comment (azinneera) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunBallerinaPreBuildToolsTask.java:135]:
```suggestion
    private void reloadProject(Project project) {
```

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunBallerinaPreBuildToolsTask.java [hunk 2]
```diff
@@ -121,13 +123,21 @@ public void execute(Project project) {
                     throw createLauncherException(e.getMessage());
                 }
             } else {
-                outStream.println(String.format("WARNING: Skipping execution of build tool %s(%s) as Ballerina.toml " +
-                        "contains errors%n", tool.type(), tool.id() != null ? tool.id() : ""));
+                outStream.printf("WARNING: Skipping execution of build tool %s(%s) as Ballerina.toml " +
+                        "contains errors%n%n", tool.type(), tool.id() != null ? tool.id() : "");
             }
         }
+        // Load current package to load the generated code
```
Comment (azinneera) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunBallerinaPreBuildToolsTask.java:130]:
```suggestion
        // Reload the project to load the generated code
```

**Review by azinneera — DISMISSED** [review]

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/GraphCommand.java [hunk 3]
```diff
@@ -110,7 +110,7 @@ public void execute() {
 
         TaskExecutor taskExecutor = new TaskExecutor.TaskBuilder()
                 .addTask(new CleanTargetDirTask(true, false), isSingleFileProject())
-                .addTask(new RunBallerinaPreBuildToolsTask(outStream))
+                .addTask(new RunBallerinaPreBuildToolsTask(outStream), isSingleFileProject())
```
Comment (SasinduDilshara) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/GraphCommand.java:113]: Imo, Normaly we use `is` prefix into function. We can avoid using `is` prefix into the variable.
wdyt?

**Review by azinneera — APPROVED** [review]
