### PR TITLE
Fix compiler crash in invalid xml with missing closing tag 

### LINKED ISSUE #41669: [Bug]: Compiler crash in invalid xml
### Description

```
import ballerina/soap.soap11;
import ballerina/io;

public function main() returns error? {
    soap11:Client soapClient = check new("http://localhost:9091/test/path/");

    xml|error y = check soapClient->sendReceive(xml `<a /a>`, "http://www.example.com/receive.cdi");
    io:println(y is xml ? y : y);
}
```

Above code crash the compiler

```
Compiling source
        test_soap-client.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-11-09 13:13:40,113] SEVERE {b7a.log.crash} - Syntax kind is not supported: GT_TOKEN 
java.lang.RuntimeException: Syntax kind is not supported: GT_TOKEN
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2420)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:521)
        at io.ballerina.compiler.syntax.tree.Token.apply(Token.java:114)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5494)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5467)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:3594)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:521)
        at io.ballerina.compiler.syntax.tree.XMLTextNode.apply(XMLTextNode.java:46)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5494)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5467)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createXMLTextLiteral(BLangNodeBuilder.java:3614)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createXmlSequence(BLangNodeBuilder.java:4555)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createXmlTemplateLiteral(BLangNodeBuilder.java:4602)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2471)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:521)
        at io.ballerina.compiler.syntax.tree.TemplateExpressionNode.apply(TemplateExpressionNode.java:59)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5494)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5467)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:3238)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:521)
        at io.ballerina.compiler.syntax.tree.PositionalArgumentNode.apply(PositionalArgumentNode.java:46)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.applyAll(BLangNodeBuilder.java:1871)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:3691)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:521)
        at io.ballerina.compiler.syntax.tree.RemoteMethodCallActionNode.apply(RemoteMethodCallActionNode.java:66)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5494)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5467)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2028)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:521)
        at io.ballerina.compiler.syntax.tree.CheckExpressionNode.apply(CheckExpressionNode.java:50)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5494)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5467)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createBLangVarDef(BLangNodeBuilder.java:3002)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2977)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:521)
        at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.generateAndAddBLangStatements(BLangNodeBuilder.java:5374)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1679)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:521)
        at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:63)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.populateFunctionNode(BLangNodeBuilder.java:1582)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createFunctionNode(BLangNodeBuilder.java:1560)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1538)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:521)
        at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:662)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:521)
        at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.accept(BLangNodeBuilder.java:561)
        at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:116)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:422)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:383)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:208)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:192)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:242)
        at io.ballerina.projects.Package.getCompilation(Package.java:150)
        at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:319)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:142)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:223)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by poorna2152**
Fixes #41669 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParser.java [hunk 1]
```diff
@@ -477,7 +477,13 @@ private STNode parseXMLText() {
      * @return XML char-data token
      */
     private STNode parseCharData() {
-        return consume();
+        STToken token = consume();
+        if (token.kind != SyntaxKind.XML_TEXT_CONTENT) {
+            return STNodeFactory.createLiteralValueToken(SyntaxKind.XML_TEXT_CONTENT, token.text(),
+                    token.leadingMinutiae(), token.trailingMinutiae());
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParser.java:483]: When we create the new token out of the existing one, we have to propagate the diagnostics as well. (In case the the token already had error attached from the lexer).

```suggestion
            return STNodeFactory.createLiteralValueToken(SyntaxKind.XML_TEXT_CONTENT, token.text(),
                    token.leadingMinutiae(), token.trailingMinutiae(), token.diagnostics());
```

Comment (poorna2152) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/XMLParser.java]: Fixed

**Review by lochana-chathura — DISMISSED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal [hunk 2]
```diff
@@ -149,3 +149,8 @@ function textInvalidXmlSequence() {
     xml<'xml:Element>|'xml:Text x39 = xml `<root><foo><foo></foo>3</foo></root>3`;
     xml<xml<'xml:Text>>|xml<xml<'xml:Comment>> x40 = xml `<!--comment-->text1`;
 }
+
+function testMissingClosingGTToken() {
+    xml x1 = xml `<a /a>`;
+    xml x2 = xml `<a n="a" /a>`;
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal:155]: @poorna2152 Shall we add this test case as a  ballerina parser test as well?

Let's add it under the  following class. https://github.com/ballerina-platform/ballerina-lang/blob/bf6b50f6b0c5dca37e978d1e0cbb9b4c4f5cfad0/compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/XMLTemplateExpressionTest.java#L27

The reason is instead of triggering the full compilation flow, we should be able to test this at the parser level alone.

Comment (poorna2152) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/xml/xml-literals-negative.bal:155]: Added

**Review by lochana-chathura — APPROVED** [review]
