### PR TITLE
Flatten type reference union type members

### LINKED ISSUE #34026: Check the necessity to flatten user defined types in a union type
**Description:**
Refer to the below sample,
```ballerina
type Token SingleCharDelim|Keyword;
type SingleCharDelim "+" | "-";
type Keyword  "string" | 100 | "200" ;
```

Before https://github.com/ballerina-platform/ballerina-lang/pull/31845, the `Token` union types' members were flattened as 
`"+" | "-"|"string" | 100 | "200"`.
Now its members are `SingleCharDelim|Keyword`.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/pull/33985#discussion_r756076258

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #34081: `bal build` on the Simple Query BBE for the second time results in compilation failure
**Description:**
$subject with the following output:
```
Compiling source
	test.bal
error: failed to load the module 'ballerina/sql:1.1.0' from its BIR
```

**Steps to reproduce:**
1. Copy the [Simple Query BBE](https://ballerina.io/learn/by-example/jdbc-query-operation.html?is_ref_by_example=true) to a bal file and execute `bal build` command - builds successfully and generates the executable
2. Rerun `bal build` command - compilation failure

**Affected Versions:**
SL Beta.6-SNAPSHOT (51934f8fa305af61241470f7dd4a9de1fafeb60b)

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #34026
Fixes #34081

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTypeReferenceType.java [hunk 1]
```diff
@@ -61,6 +61,6 @@ public TypeKind getKind() {
 
     @Override
     public boolean isNullable() {
-        return this.referredType.isNullable();
+        return this.referredType != null && this.referredType.isNullable();
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BTypeReferenceType.java:64]: Won't need this with the changes in https://github.com/ballerina-platform/ballerina-lang/pull/34137.

**Review by hasithaa — APPROVED** [review]

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java [hunk 2]
```diff
@@ -873,21 +873,10 @@ public void testFlattenedUnionMembers() {
...
-
-        member1 = ((TypeReferenceTypeSymbol) member1).typeDescriptor();
-        expandedMembers = ((UnionTypeSymbol) member1).memberTypeDescriptors();
         assertEquals(expandedMembers.get(0).typeKind(), INT);
         assertEquals(expandedMembers.get(1).typeKind(), STRING);
-
-        member2 = ((TypeReferenceTypeSymbol) member2).typeDescriptor();
-        expandedMembers = ((UnionTypeSymbol) member2).memberTypeDescriptors();
-        assertEquals(expandedMembers.get(0).typeKind(), FLOAT);
-        assertEquals(expandedMembers.get(1).typeKind(), BOOLEAN);
```
Comment (pubudu91) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java:890]: Why were these assertions deleted?

Comment (pubudu91) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java:890]: Judging by the modified behaviour of this test, looks like this change is breaking the `memberTypeDescriptors()` API.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/UnionTypeSymbolTest.java [hunk 3]
```diff
@@ -89,13 +89,14 @@ public void testUnionTypeMemberTypes(int line, int col, String name, List<TypeDe
...
-                        List.of(TypeDescKind.TYPE_REFERENCE, TypeDescKind.TYPE_REFERENCE)},
+                        List.of(TypeDescKind.INT, TypeDescKind.STRING, TypeDescKind.BOOLEAN,
+                                TypeDescKind.TYPE_REFERENCE)},
                 {28, 5, "T7",
                         List.of(TypeDescKind.TUPLE, TypeDescKind.OBJECT)},
                 {35, 5, "T8",
                         List.of(TypeDescKind.MAP, TypeDescKind.TYPE_REFERENCE)},
                 {37, 5, "T9",
-                        List.of(TypeDescKind.ARRAY, TypeDescKind.TYPE_REFERENCE)},
+                        List.of(TypeDescKind.ARRAY, TypeDescKind.MAP, TypeDescKind.TYPE_REFERENCE)},
```
Comment (pubudu91) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/UnionTypeSymbolTest.java:99]: These changes are also a confirmation that the behaviour is broken.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java (hunk 2 above)
Comment (pubudu91) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/TypedescriptorTest.java:890]: Sorry, my bad. Ignore these comments. This is corrects the previously buggy `memberTypeDescriptors()` API since we have defined it to be returning the expanded members.
