### PR TITLE
Look up closure symbols with the original symbol

### LINKED ISSUE #41642: [Bug]: Invalid type narrowing within conditional expr for query
### Description

It seems type narrowing is not working for the query expressions when it is used in conditional expr.

### Steps to Reproduce

```ballerina
public function main() {
    foo();
}

function foo() {
    int? i = 3;
    _ = i is () ? 2 : from var _ in [1, 2]
                        where i + 2 == 3
                        select 2;
}
```

### Affected Version(s)

8.2

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by nipunayf**
## Purpose
For expressions like ternary and binary, the if and else bodies are generated in the desugar phase. As a result, the `TypeNarrower` is unable to set the narrowed scopes for the if and else bodies generated for these expressions since they are not available in the type checker phase. However, the current implementation of the query desugar implementation relies on this narrowed scope to determine if the variable is captured, as it uses the symbol resolver looks for the narrowed symbol in the environment. Although this approach works for user-written if-else bodies (as they are available in the type checker), it cannot identify captured variables for desugared bodies. 

Fixes #41642

## Approach

The proposed approach modifies the query desugar implementation to check the original symbol rather than the narrowed symbol to determine captured variables.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by hasithaa — APPROVED** [review]
Additionally, can you check whether we have similar desugared code?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTernaryExpr.java [hunk 1]
```diff
@@ -33,6 +34,8 @@ public class BLangTernaryExpr extends BLangExpression implements TernaryExpressi
     public BLangExpression expr;
     public BLangExpression thenExpr;
     public BLangExpression elseExpr;
+    public Scope thenScope;
+    public Scope elseScope;
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTernaryExpr.java:38]: IMO this is not the correct fix. Normally we introduce scope to the symbol to keep its child symbols. 

```ballerina
function test() {
  int? i = 3;
  int|int[] thenResult = i is int ?
      from var _ in [1, 2]
      where i + 2 == 5
      select 2 : 2;
}
```
When considering the above scenario, we use the variable `i` within the lambda function created for the `where` clause. So, in the query desugaring logic, it is needed to identify `i` as a closure variable. But with the current approach we didn't mark `i` as a closure variable in the query desugaring logic. Due to this above program fails in the runtime.

The reason for not to identify `i` as closure variable(in query desugaring phase) is in the type narrowing phase we generate new symbol for `i`. But within the new symbol which generated for `i` we keep the `originalsymbol` as well. We can use that symbol to check whether that the `i` is closure variable or not.

Solution for this is to use the `originalsymbol` instead of using the current symbol to check whether it is a closure variable or not when visiting the variable reference in the query desugaring phase. 

Example
```java
if (symbol instanceof BVarSymbol) {
    BVarSymbol originalSymbol = ((BVarSymbol) symbol).originalSymbol;
    if (originalSymbol != null) {
        symbol = originalSymbol;
    }
}
```

Comment (nipunayf) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTernaryExpr.java:38]: Although this solves the problem with the ternary case, the same error now occurs in the if-body case (which was passed with the current implementation).

```ballerina
public function main() {
    testTernaryWithQuery();
}

function testTernaryWithQuery() {
    int? i = 3;

    int|int[] thenResult;
    if i is int {
        thenResult = from var _ in [1, 2]
        where i + 2 == 5
        select 2;
    } else {
        thenResult = 2;
    }
}
```

Since the narrowed environment scope is properly defined for the `if` and `else` bodies, it will return the narrowed symbol rather than the original symbol when invoking `lookupClosureVarSymbol`. As a result, the proposed approach will not identify `i` as a closure since the desugaring symbol and the resolved symbol are now different.

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTernaryExpr.java:38]: The var-ref logic in query desugar is different. Basically it gets the symbol from node and symbol from env and compare. If we change the logic to consider `originalSymbol` as you mentioned, `ifStmt` case can be failed. I don't think it is feasible to do a whole refactoring for var-ref logic in query desugar.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/ternary/ternary-expr.bal [hunk 2]
```diff
@@ -334,6 +334,22 @@ function testTernaryWithLangValueMethodCalls() {
     assertEquals("a", b48);
 }
 
+function testTernaryWithQuery() {
```
Comment (KavinduZoysa) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/ternary/ternary-expr.bal:337]: Shall we add a few more test cases,
1. Get `i` from function param
2. Get `i` from another module
3. Add module-level ternary expression

Comment (nipunayf) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/ternary/ternary-expr.bal:337]: I am not sure if we can add a test for the third case since type narrowing is not supported at the module level.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTernaryExpr.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangTernaryExpr.java:38]: As discussed offline, I also don't think we should keep the scopes in the node. Let's check if there's a different way to identify and mark captured variables correctly.

**Review by MaryamZi — COMMENTED** [review]
The following snippet crashes with this change.

```ballerina
public function main() {
    int? a = 3;
    int? b = ();
    _ = a == b ? 2 : from var _ in [1, 2]
                            select 2 + a;
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 3]
```diff
@@ -815,18 +816,23 @@ public BSymbol lookupLangLibMethod(BType type, Name name, SymbolEnv env) {
...
+            }
             if (symTable.rootPkgSymbol.pkgID.equals(entry.symbol.pkgID) &&
                     (entry.symbol.tag & SymTag.VARIABLE_NAME) == SymTag.VARIABLE_NAME) {
                 return entry.symbol;
             }
-            if ((entry.symbol.tag & expSymTag) == expSymTag && !isFieldRefFromWithinARecord(entry.symbol, env)) {
+            if ((entry.symbol.tag & SymTag.VARIABLE) == SymTag.VARIABLE &&
+                    !isFieldRefFromWithinARecord(entry.symbol, env)) {
                 return entry.symbol;
             }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:837]: Since we are checking with the symbol, we can eliminate these steps. Therefore, we can refactor the function as follows

```java
public BSymbol lookupClosureVarSymbol(SymbolEnv env, BSymbol symbol) {
    ScopeEntry entry = env.scope.lookup(symbol.name);
    while (entry != NOT_FOUND_ENTRY) {
        if (entry.symbol == symbol) {
            return entry.symbol;
        }
        entry = entry.next;
    }

    if (env.enclEnv == null) {
        return symTable.notFoundSymbol;
    }

    return lookupClosureVarSymbol(env.enclEnv, symbol);
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 4]
```diff
@@ -1964,8 +1964,7 @@ public void visit(BLangSimpleVarRef bLangSimpleVarRef) {
             resolvedSymbol.closure = true;
             // When there's a type guard, there can be a enclSymbol before type narrowing.
             // So, we have to mark that as a closure as well.
-            BSymbol enclSymbol = symResolver.lookupClosureVarSymbol(env.enclEnv,
-                    Names.fromString(identifier), SymTag.VARIABLE);
+            BSymbol enclSymbol = symResolver.lookupClosureVarSymbol(env.enclEnv, symbol, Names.fromString(identifier));
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:1967]: Here also, instead of using `Names.fromString(identifier)`, you can simply use `symbol.name`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 5]
```diff
@@ -1905,17 +1905,17 @@ public void visit(BLangSimpleVarRef bLangSimpleVarRef) {
...
         String identifier = bLangSimpleVarRef.variableName == null ? String.valueOf(bLangSimpleVarRef.varSymbol.name) :
                 String.valueOf(bLangSimpleVarRef.variableName);
-        BSymbol resolvedSymbol = symResolver.lookupClosureVarSymbol(env,
-                Names.fromString(identifier), SymTag.VARIABLE);
+        if (symbol instanceof BVarSymbol) {
+            BVarSymbol originalSymbol = ((BVarSymbol) symbol).originalSymbol;
+            if (originalSymbol != null) {
+                symbol = originalSymbol;
+            }
+        }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:1913]: Instead of using `instanceof`, We can use `kind` of the symbol for the this check.
```java
if (symbol.getKind() == SymbolKind.VARIABLE) {
    BVarSymbol originalSymbol = ((BVarSymbol) symbol).originalSymbol;
    if (originalSymbol != null) {
        symbol = originalSymbol;
    }
}
```

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:1913]: Also, make sure to check if the `symbol` is null at the beginning and return if it is.
```java
if (symbol == null) {
    result = bLangSimpleVarRef;
    return;
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 6]
```diff
@@ -1905,17 +1905,17 @@ public void visit(BLangSimpleVarRef bLangSimpleVarRef) {
...
+        BSymbol resolvedSymbol = symResolver.lookupClosureVarSymbol(env, symbol, Names.fromString(identifier));
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:1914]: Instead of using `Names.fromString(identifier)`, you can simply use `symbol.name`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 7]
```diff
@@ -815,18 +816,23 @@ public BSymbol lookupLangLibMethod(BType type, Name name, SymbolEnv env) {
...
+     * @param symbol    symbol to lookup
      * @param name      name of the symbol to lookup
-     * @param expSymTag symbol tag
      * @return closure symbol wrapper along with the resolved count
      */
-    public BSymbol lookupClosureVarSymbol(SymbolEnv env, Name name, long expSymTag) {
+    public BSymbol lookupClosureVarSymbol(SymbolEnv env, Symbol symbol, Name name) {
         ScopeEntry entry = env.scope.lookup(name);
         while (entry != NOT_FOUND_ENTRY) {
+            if (entry.symbol != symbol) {
```
[the remark this answers is not in the document]
Comment (nipunayf) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: Do we need to do this with the latest changes, since there is only one usage of `entry.symbol`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 8]
```diff
@@ -2591,8 +2590,8 @@ public void visit(BLangCollectClause collectClause) {
 
     void updateIdentifiers(SymbolEnv env) {
         for (Map.Entry<String, BSymbol> identifier : identifiers.entrySet()) {
-            BSymbol symbol = symResolver.lookupClosureVarSymbol(env, Names.fromString(identifier.getKey()),
-                    SymTag.SEQUENCE);
+            BSymbol symbol =
+                    symResolver.lookupSymbolInGivenScope(env, Names.fromString(identifier.getKey()), SymTag.SEQUENCE);
```
[the remark this answers is not in the document]
Comment (nipunayf) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:2599]: There is a special case for the collect and group clauses of the query, where the type of the symbol is changed to a sequence (internal type used by queries). In this case, we have to obtain the sequence type symbol from the original symbol, and that's why we are using the name here.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/BinaryExprTest.java [hunk 9]
```diff
@@ -143,6 +143,17 @@ public void bitwiseAndTest() {
...
 
+    @Test(description = "Test binary expression with query")
+    public void binaryExpressionWithQuery() {
+        Object resultAnd = BRunUtil.invoke(result, "binaryANDWithQuery", new Object[]{});
+        Assert.assertSame(resultAnd.getClass(), Boolean.class);
+        Assert.assertTrue((boolean) resultAnd);
+
+        Object resultOr = BRunUtil.invoke(result, "binaryORWithQuery", new Object[]{});
+        Assert.assertSame(resultOr.getClass(), Boolean.class);
+        Assert.assertTrue((boolean) resultOr);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/binaryoperations/BinaryExprTest.java:154]: The assertions can be done in Ballerina itself.

Also use a data provider or different tests so that the second one will run even if the first one fails.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java [hunk 10]
```diff
@@ -49,33 +49,25 @@ public void setup() {
...
-        Assert.assertEquals(ret, 51);
+        Assert.assertEquals((long) returns, 51);
     }
 
     @Test
     public void workerSendFromDefault() {
         Object returns = BRunUtil.invoke(result, "workerSendFromDefault", new Object[0]);
-
-        long ret = (long) returns;
-        Assert.assertEquals(ret, 51);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java:78]: Generally better to avoid unrelated changes and send a separate PR if required.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary-expr.bal [hunk 11]
```diff
@@ -37,3 +37,17 @@ function bitwiseAnd(int a, int b, byte c, byte d) returns [int, byte, byte, byte
     res [3] = b & d;
     return res;
 }
+
+function binaryANDWithQuery() returns boolean {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary-expr.bal:41]: Can be And?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary-expr.bal
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/binary-expr.bal:1]: Can we add tests with different combinations of narrowing and not narrowing, as discussed? E.g., combined with anonymous functions (where narrowing won't happen for captured variables).

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java [hunk 12]
```diff
@@ -350,6 +350,12 @@ public void testMultipleReceiveAction() {
         BAssertUtil.validateError(result, 0, "multiple receive action not yet supported", 23, 25);
     }
 
+    @Test
+    public void testWorkerWithQuery() {
+        Object returns = BRunUtil.invoke(result, "testWorkerWithQuery", new Object[0]);
+        Assert.assertEquals((long) returns, 4);
```
Comment (SasinduDilshara) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerTest.java:356]: It is better if we can add this test as a Ballerina test

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:2599]: When defining a new symbol, we define that symbol within that scope. Could you provide an example where using a symbol fails to determine if the given symbol is within that scope?

[the remark this answers is not in the document]
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:2599]: When reviewing the usages of the `lookupSymbolInGivenScope` function, it is good to use the symbol instead of the name of that symbol. Since this matter is not directly related to this PR, I have created a separate issue to address this improvement.https://github.com/ballerina-platform/ballerina-lang/issues/41886

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 13]
```diff
@@ -6690,14 +6687,24 @@ private boolean searchClosureVariableInExpressions(BSymbol symbol, Location pos,
...
+        if (env.enclType != null && env.enclType.getKind() == NodeKind.RECORD_TYPE) {
+            SymbolEnv encInvokableEnv = findEnclosingInvokableEnv(env, (BLangRecordTypeNode) env.enclType);
+            BSymbol resolvedSymbol = symResolver.lookupClosureVarSymbol(encInvokableEnv, symbol);
+            if (resolvedSymbol != symTable.notFoundSymbol && encInvokable != null &&
+                    !encInvokable.flagSet.contains(Flag.ATTACHED)) {
+                resolvedSymbol.closure = true;
+                ((BLangFunction) encInvokable).closureVarSymbols.add(new ClosureVarSymbol(resolvedSymbol, pos));
+                return true;
+            }
+        }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6707]: What is the reason for having this check? We mark a variable as a closure if it is defined in a function(function that lambda defines) and used within a lambda function.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 14]
```diff
@@ -1960,12 +1965,11 @@ public void visit(BLangSimpleVarRef bLangSimpleVarRef) {
...
+        } else if (resolvedSymbol != symTable.notFoundSymbol) {
             resolvedSymbol.closure = true;
             // When there's a type guard, there can be a enclSymbol before type narrowing.
             // So, we have to mark that as a closure as well.
-            BSymbol enclSymbol = symResolver.lookupClosureVarSymbol(env.enclEnv,
-                    Names.fromString(identifier), SymTag.VARIABLE);
+            BSymbol enclSymbol = symResolver.lookupClosureVarSymbol(env.enclEnv, symbol);
             if (enclSymbol != null && enclSymbol != symTable.notFoundSymbol) {
                 enclSymbol.closure = true;
             }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:1975]: Since we obtain the resolved symbol directly from the original symbol, these checks are no longer necessary. We can remove them.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 15]
```diff
@@ -1960,12 +1965,11 @@ public void visit(BLangSimpleVarRef bLangSimpleVarRef) {
                 bLangSimpleVarRef.symbol = symbol;
                 bLangSimpleVarRef.varSymbol = symbol;
             }
-        } else if (resolvedSymbol != symTable.notFoundSymbol && symbol != null) {
+        } else if (resolvedSymbol != symTable.notFoundSymbol) {
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:1968]: Before performing this check, we should confirm whether the resolved symbol is a closure. 
In the following example, the closure flag of the resolved symbol is set to true when comes to this logic. Therefore, we need to do a check to determine whether it is a closure variable or not.
```ballerina
import ballerina/io;

public function main() {
    foo();
}

function foo() {
    int? i = 3;
    function k = function () {
        int? j = i;
    };
    _ = i is () ? 2 : from var _ in [1, 2]
                        where i + 2 == 3
                        select 2;
    io:println(i);
}
```

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:1968]: Please add a test for this as well.

**Comment by chiranSachintha** [comment]
When considering the following example, it is still crashes at runtime. We need to fix that as well.
```ballerina
import ballerina/io;

public function main() {
    foo();
}

function foo() {
    ()|function(int) returns int i = value;
    _ = i is () ? 2 : from var _ in [1, 2]
                        where i(1) + 2 == 3
                        select 2;
    io:println(i);
}

function value(int a) returns int {
    return a;
}

```

**Review by chiranSachintha — APPROVED** [review]

**Review by KavinduZoysa — APPROVED** [review]
