### PR TITLE
[LS] Refactor `getDefaultValueForType` API

### LINKED ISSUE #31556: SO error with recursive record
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type LinkedList record {|
    string value;
    LinkedList? next;
|};

public function main() {
    LinkedList list = {v<cursor>};
}
```

```log
java.lang.StackOverflowError
	at org.ballerinalang.langserver.common.utils.CommonUtil.getDefaultValueForType(CommonUtil.java:252)
	at org.ballerinalang.langserver.common.utils.CommonUtil.lambda$getDefaultValueForType$3(CommonUtil.java:284)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getDefaultValueForType(CommonUtil.java:285)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getDefaultValueForType(CommonUtil.java:311)
	at org.ballerinalang.langserver.common.utils.CommonUtil.lambda$getDefaultValueForType$3(CommonUtil.java:284)
	......
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getDefaultValueForType(CommonUtil.java:285)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getDefaultValueForType(CommonUtil.java:311)
	at org.ballerinalang.langserver.common.utils.CommonUtil.lambda$getDefaultValueForType$3(CommonUtil.java:284)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getDefaultValueForType(CommonUtil.java:285)
	at org.ballerinalang.langserver.common.utils.CommonUtil.getDefaultValueForType(CommonUtil.java:311)
```

**Affected Versions:**
slbeta2-rc4

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/28866

### PR DESCRIPTION
**Pull request by TharushiJay**
## Purpose
1. Fixes SO errors occurring due to the use of recursive types by introducing a limit on the maximum recursion depth
2. Modifies the default value of optional types to be `()`
3. Adds a default value for decimal types
4. Modifies return use-case to remove the use of `()` when returning

Fixes #31556, #31859

## Samples
1.

2.
ezgif com-gif-maker (2)

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 1]
```diff
@@ -247,7 +248,16 @@ public static Position toPosition(LinePosition linePosition) {
...
      */
     public static String getDefaultValueForType(TypeSymbol bType) {
+        return getDefaultValueForType(bType, 1);
+    }
+    
+    private static String getDefaultValueForType(TypeSymbol bType, int depth) {
         String typeString;
+        
+        if (depth > MAX_DEPTH) {
+            return "";
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:258]: If we don't insert  anything  when the user has asked for a default type, it may be confusing for the users. WDYT?
In In the switch case's default case and when bType is null we have returned `()` as the default value. Wouldn't it be consistent if we use `()` or `""` both cases

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 2]
```diff
@@ -355,6 +372,9 @@ public static String getDefaultValueForType(TypeSymbol bType) {
             case XML:
                 typeString = "xml ``";
                 break;
+            case DECIMAL:
+                typeString = Integer.toString(0);
+                break;
             default:
                 if (typeKind.isIntegerType()) {
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:379]: We can add the DECIMAL case here. Both cases have the same logic

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 1 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:258]: We will insert nothing after `MAX_DEPTH` (10) recursions. So, the chance of getting that deep is low. Rather than handling each special case which can cause stack overflows, returning at a max depth seems safe.
I agree with the 2nd part, where we should insert `""` or `()` consistently. Let's use `""` for the default case as well.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 3]
```diff
@@ -311,7 +321,14 @@ public static String getDefaultValueForType(TypeSymbol bType) {
             case UNION:
                 List<TypeSymbol> members =
                         new ArrayList<>(((UnionTypeSymbol) rawType).memberTypeDescriptors());
-                typeString = getDefaultValueForType(members.get(0));
+                List<TypeSymbol> nilMembers = members.stream().filter(
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:324]: Let's format this line better. Something like:
```
List<TypeSymbol> nilMembers = members.stream()
    .filter(member -> member.typeKind() == TypeDescKind.NIL).collect(Collectors.toList());
```

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 2 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:379]: Will `typeKind.isIntegerType()` be true for decimals?

**Review by IMS94 — CHANGES_REQUESTED** [review]
PR looks good. There's a minor change required to be done. Once done, we can merge.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 2 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:379]: I acutalullay ment addingthe following to line 379
`typeKind.isIntegerType() || typeKind.kind() == TypeDescKind.DECIMAL`. But we can skip the suggestion as it does not have much of an impact

Comment (TharushiJay) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:379]: Handling it in the case clause will be more efficient IMO. Therefore, marking this as resolved.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 1 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:258]: @IMS94 Yes it is safe. However, in the case of recursive types(eg:LinkedList take in the sample), going further after a single step is not required  IMO. We can break the loop from a single step. Going for all 10 steps  causes the above nested default values which kind of not good in terms of user experience. WDYT?

File: language-server/modules/langserver-core/src/test/resources/codeaction/implement-all/config/implementAllObj1.json [hunk 4]
```diff
@@ -16,7 +16,7 @@
                             "character": 0
                         }
                     },
-                    "newText": "\n    public function pushText2(string text) returns error? {\n        return error (\"\");\n    }\n"
+                    "newText": "\n    public function pushText2(string text) returns error? {\n        return ();\n    }\n"
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/test/resources/codeaction/implement-all/config/implementAllObj1.json:19]: For the return use-case, it is not mandatory to return `()`. Instead we can just use return; Shall we fix this?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/test/resources/codeaction/implement-all/config/implementAllObj1.json (hunk 4 above)
Comment (TharushiJay) [reply language-server/modules/langserver-core/src/test/resources/codeaction/implement-all/config/implementAllObj1.json:19]: @nadeeshaan For optional types, the idea was to use `()` as the default value. Do you mean to change it to `""`?
This will also change the default value of optional record fields to be empty.
Eg:
```
type LinkedList record {|
    string value;
    LinkedList? next;
|};

LinkedList l0 = {value: "", next:};
```
Or to fix it in `generateFunction()` to have `return;` whenever a function returns a nil?

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/test/resources/codeaction/implement-all/config/implementAllObj1.json:19]: The best option here is to add the fix to the `generateFunction()` method

**Review by IMS94 — APPROVED** [review]

**Review by nadeeshaan — APPROVED** [review]
LGTM
