### PR TITLE
[Master] Correct error msgs for map constants negative cases

### LINKED ISSUE #40792: [Bug]: Incorrect error msg for map constants
### Description

- ```const person = {name : "Joe", name : "Jack"};```
Currently it gives `invalid usage of finite literal: duplicate key 'name'`, spec did not mention about `finite`. It can be corrected to `invalid usage of record literal: duplicate key 'name'`.

- ```const int|float|string mUnion3 = {a: 1, b: 2};```
It gives `incompatible types: expected ' {a: 1,b: 2}', found '(int|float|string)'` which is wrong.

### Steps to Reproduce

_No response_

### Affected Version(s)

2201.7.0-stage

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by prakanth97**
## Purpose

Fixes #40792 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -7270,4 +7270,9 @@ public boolean isContainSubtypeOfInt(BType type) {
                 return false;
         }
     }
+
+    public boolean isMappingConstructorCompatibleType(BType type) {
+        return Types.getReferredType(type).tag == TypeTags.RECORD
+                || Types.getReferredType(type).tag == TypeTags.MAP;
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:7276]: Can write this inline

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java [hunk 2]
```diff
@@ -549,7 +550,25 @@ private void reportIncompatibleMappingConstructorError(BLangRecordLiteral mappin
...
+        BUnionType unionType = (BUnionType) expType;
+        BType[] memberTypes = types.getAllTypes(unionType, true).toArray(new BType[0]);
+
+        // By this point, we know there aren't any types to which we can assign the mapping constructor. If this is
+        // case where there is at least one type with which we can use mapping constructors, but this particular
+        // mapping constructor is incompatible, we give an incompatible mapping constructor error.
+        for (BType bType : memberTypes) {
+            if (types.isMappingConstructorCompatibleType(bType)) {
+                dlog.error(mappingConstructorExpr.pos, DiagnosticErrorCode.INCOMPATIBLE_MAPPING_CONSTRUCTOR,
+                        unionType);
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java:565]: can write inline I think.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java [hunk 3]
```diff
@@ -2055,7 +2069,7 @@ private boolean addFields(LinkedHashMap<String, BField> fields, BType keyValueTy
                            BRecordTypeSymbol recordSymbol) {
         Name fieldName = Names.fromString(key);
         if (fields.containsKey(key)) {
-            dlog.error(pos, DiagnosticErrorCode.DUPLICATE_KEY_IN_RECORD_LITERAL, keyValueType.getKind().typeName(),
+            dlog.error(pos, DiagnosticErrorCode.DUPLICATE_KEY_IN_RECORD_LITERAL, TypeKind.RECORD.typeName(),
                     key);
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java:2073]:
```suggestion
            dlog.error(pos, DiagnosticErrorCode.DUPLICATE_KEY_IN_RECORD_LITERAL, TypeKind.RECORD.typeName(), key);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 4]
```diff
@@ -7270,4 +7270,8 @@ public boolean isContainSubtypeOfInt(BType type) {
                 return false;
         }
     }
+
+    public boolean isMappingConstructorCompatibleType(BType type) {
+        return Types.getReferredType(type).tag == TypeTags.RECORD || Types.getReferredType(type).tag == TypeTags.MAP;
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:7275]: Since we have moved the method. Can refactor too. 
```suggestion
        int tag = getReferredType(type).tag;
        return tag == TypeTags.RECORD || tag == TypeTags.MAP;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java [hunk 5]
```diff
@@ -549,7 +550,24 @@ private void reportIncompatibleMappingConstructorError(BLangRecordLiteral mappin
...
+            return;
+        }
+
+        BUnionType unionType = (BUnionType) expType;
+        BType[] memberTypes = types.getAllTypes(unionType, true).toArray(new BType[0]);
+
+        // By this point, we know there aren't any types to which we can assign the mapping constructor. If this is
+        // case where there is at least one type with which we can use mapping constructors, but this particular
+        // mapping constructor is incompatible, we give an incompatible mapping constructor error.
+        for (BType bType : memberTypes) {
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java:562]: Why are we duplicating the logic in `reportIncompatibleMappingConstructorError()` in `TypeChecker.java` here?

Can we use the same in the ConstantTypeChecker? 
The only difference is special casing the `T?`. Isn't it useful for constants as well?

Sample:
```bal
type T record {|
    string s;
    int i?;
|};

T? f1 = {s: "foo", invalid: 123}; // [1]
const T? f1 = {s: "foo", invalid: 123}; // [2]
```
For [2] also can give the same diagnostics as [1] which is more user-friendly.

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantTypeChecker.java:562]: Add a comment as we discussed offline https://github.com/ballerina-platform/ballerina-lang/pull/40799/files#diff-b4cd70391128b02ba62b9a69264ea2010300b8dc1abe6e1f80a4c24bd70491e9R543

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 6]
```diff
@@ -331,7 +331,7 @@ public enum DiagnosticErrorCode implements DiagnosticCode {
     INVALID_RECORD_LITERAL("BCE2575", "invalid.record.literal"),
     INVALID_FIELD_IN_RECORD_BINDING_PATTERN("BCE2576", "invalid.field.in.record.binding.pattern"),
     INVALID_RECORD_LITERAL_BINDING_PATTERN("BCE2577", "invalid.record.literal.in.binding.pattern"),
-    DUPLICATE_KEY_IN_RECORD_LITERAL("BCE2578", "duplicate.key.in.record.literal"),
+    DUPLICATE_KEY_IN_RECORD_CONSTRUCTOR("BCE2578", "duplicate.key.in.record.constructor"),
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:334]: Since we use this for both map/record and record is special scenario of the map. Plus in the spec we call it `mapping-constructor`.
```suggestion
    DUPLICATE_KEY_IN_MAPPING_CONSTRUCTOR("BCE2578", "duplicate.key.in.mapping.constructor"),
```

**Review by hasithaa — APPROVED** [review]
