### PR TITLE
Fix compiler crashes for langlib function calls with invalid named argument

### LINKED ISSUE #38600: [Bug]: Compiler crashes for invalid named argument
### Description

$title

### Steps to Reproduce

```
    int[] y = [5,6];
    int res = int:sum(ns=y);
```

> [2022-11-09 15:10:07,413] SEVERE {b7a.log.crash} - null 
> java.lang.NullPointerException
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkInvalidImmutableValueUpdate(TypeChecker.java:3837)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkFunctionInvocationExpr(TypeChecker.java:6900)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:3352)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:227)
> 	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:133)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:401)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:369)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1161)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:232)
> 	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:59)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4144)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4119)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4087)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2089)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:232)
> 	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:55)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4144)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4119)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:4091)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:563)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:232)
> 	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:65)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4144)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:542)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:232)
> 	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:81)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4144)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:4119)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:4087)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:344)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:232)
> 	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
> 	at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:198)
> 	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:281)
> 	at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
> 	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
> 	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:431)
> 	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
> 	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:380)
> 	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:202)
> 	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
> 	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
> 	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
> 	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
> 	at io.ballerina.projects.Package.getCompilation(Package.java:148)
> 	at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:255)
> 	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:126)
> 	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
> 	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:213)
> 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
> 	at io.ballerina.cli.launcher.Main.main(Main.java:51)
>  
> ERROR [.:(1:1,1:1)] Compilation failed due to an unhandled exception
> ERROR [test7.bal:(10:23,10:27)] too many arguments in call to 'sum()'

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by ushirask**
Fixes #38600 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -7049,7 +7049,7 @@ private void checkFunctionInvocationExpr(BLangInvocation iExpr, AnalyzerData dat
         iExpr.symbol = funcSymbol;
         checkInvocationParamAndReturnType(iExpr, data);
 
-        if (langLibPackageID && !iExpr.argExprs.isEmpty()) {
+        if (langLibPackageID && !iExpr.argExprs.isEmpty() && iExpr.argExprs.get(0).getBType() != null) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7052]: This happens because the first arg was not visited. I think we have to check the reason for that and fixing at that point.

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7052]: They are not visited since these are unexpected arguments. We can visit them before creating the errors in `checkInvocationArgs`. If we're doing `checkTypeParamExpr` there, should we have `neverType` as expected type?

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7052]: We have to try and see. We can set the `noType` as the expected type which means call checkExpr without the expected type.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java [hunk 2]
```diff
@@ -195,6 +195,16 @@ public void testFunctionCallNegativeCases() {
                 "incompatible types: expected 'int[]', found '(int|string)[3]'", 73, 29);
         validateError(funcInvocationNegative, i++,
                 "incompatible types: expected 'int[]', found 'anydata[]'", 74, 29);
+        validateError(funcInvocationNegative, i++,
+                "too many arguments in call to 'sum()'", 102, 18);
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java:199]: This seems not right to me. The actual error is we don't accept the name arguments in this function. We should give a proper error for this. Can we fix it in the same PR?

**Review by hasithaa — COMMENTED** [review]
Mentioned one improvement, but logic looks good.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java (hunk 2 above)
Comment (hasithaa) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java:199]: Let's create an issue for the mentioned improvement and send it as a separate PR. I will merge this PR since this is passed checks.

**Review by hasithaa — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java (hunk 2 above)
Comment (ushirask) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/invocations/FuncInvocationExprTest.java:199]: Created in #39818
