### PR TITLE
Fix `typeof` expression for immutable values

### LINKED ISSUE #32531: `typeof` expression returns wrong value for immutable container values
**Description:**
As per the spec, 
```
When v is a reference value,
- For containers, this is the same as the inherent type
- when the container is immutable, it will be a singleton type.  
```

The current implementation deviates from this specifications. 

**Steps to reproduce:**
```ballerina
int[] & readonly arr = [1, 2, 3];
io:println(typeof arr); // typedesc int[] & readonly -  should be typedesc [1,2,3]
```

**Affected Versions:**
beta3

**Remarks:**
related issues - #15278 , #13189

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
This is to complete the fix done on `typeof` implementation for immutable values. 

Fixes #32531

## Approach
The `typeof` will provide a Finite type that contains the immutable value. 
This is to comply with the spec,
```
When v is a reference value,
- For containers, this is the same as the inherent type
- when the container is immutable, it will be a singleton type.  
```
## Samples
```ballerina
int[] & readonly arr = [1, 2, 3];
io:println(typeof arr); // typedesc int[] & readonly -  should be typedesc [1,2,3]
```
## Remarks
This implementation was earlier reverted due to some issues found  in `langlib:value`.  https://github.com/ballerina-platform/ballerina-lang/pull/32530
This PR fixes them and redo the earlier change.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java [hunk 1]
```diff
@@ -2609,7 +2610,16 @@ private static boolean checkIsLikeTableType(Object sourceValue, BTableType targe
         return true;
     }
 
-    private static boolean checkFiniteTypeAssignable(Object sourceValue, Type sourceType, BFiniteType targetType) {
+    private static boolean checkFiniteTypeAssignable(Object sourceValue, Type sourceType, BFiniteType targetType,
+                                                     List<TypeValuePair> unresolvedValues,
+                                                     boolean allowNumericConversion) {
+        Type firstValueType = getType(targetType.valueSpace.iterator().next());
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java:2616]: Should we do this only targetType.valueSpace.size() == 1

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 2]
```diff
@@ -308,7 +310,13 @@ static boolean isConvertibleToFloatingPointTypes(Object value) {
                 convertibleTypes.addAll(getConvertibleTypes(inputValue, effectiveType, unresolvedValues));
                 break;
             case TypeTags.FINITE_TYPE_TAG:
-                for (Object valueSpaceItem : ((BFiniteType) targetType).valueSpace) {
+                BFiniteType finiteType = (BFiniteType) targetType;
+                Type firstValueType = getType(finiteType.valueSpace.iterator().next());
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:314]: IMO first we can check targetType.valueSpace.size() == 1

**Review by warunalakshitha — APPROVED** [review]
