### PR TITLE
Fix default values in fill required fields completions

### LINKED ISSUE #37999: [Bug]: Incorrect default values in fill required fields completions
### Description

https://user-images.githubusercontent.com/46120162/193186306-1c8a861b-f872-4be4-9d8d-2650009d01d0.mov

### Steps to Reproduce

```
type Person1 record {
    string name;
    int age;
};

type Person2 record {
    Person1 person;
    string name1;
};

public function main() {
    Person2 p = {<cur>};
}

```

### Affected Version(s)

2201.2.x

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
This PR fixes the default values in fill required fields completions and adds a new context to track the number of placeholders.

Fixes #37999

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java [hunk 1]
```diff
@@ -292,22 +305,51 @@ private static Optional<String> getDefaultValueForType(TypeSymbol bType, boolean
...
         }
 
         return Optional.of(valueString);
     }
+
+    /**
+     * Represents a context to track the number of placeholders.
+     */
+    public static class SnippetContext {
+        private int placeholderCount;
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java:337]: Let's set the default valaue of `placeholderCount` to `0`
```
private int placeholderCount = 0;
```

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java [hunk 2]
```diff
@@ -292,22 +305,51 @@ private static Optional<String> getDefaultValueForType(TypeSymbol bType, boolean
...
+
+        public SnippetContext() {
+            placeholderCount = 1;
+        }
+
+        public SnippetContext(int placeholderCount) {
+            this.placeholderCount = placeholderCount;
+        }
+
+        public void incrementPlaceholderCount() {
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java:347]: We should rename this to `incrementAndGetPlaceholderCount()` and it will return an `int` representing the placeholder count after incrementing.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java [hunk 3]
```diff
@@ -65,7 +65,7 @@ public static Optional<String> getDefaultPlaceholderForType(TypeSymbol bType) {
      * @return {@link String}   Default value as a String
      */
     public static Optional<String> getDefaultValueForType(TypeSymbol bType) {
-        return getDefaultValueForType(bType, false, -1);
+        return getDefaultValueForType(bType, false, new SnippetContext(-1));
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java:68]: Why do we need to set this to `-1`?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java [hunk 4]
```diff
@@ -59,8 +59,8 @@ public static List<LSCompletionItem> getRecordFieldCompletionItems(BallerinaComp
                                                                        RawTypeSymbolWrapper wrapper) {
         List<LSCompletionItem> completionItems = new ArrayList<>();
         fields.forEach((name, field) -> {
-            String insertText =
-                    getRecordFieldCompletionInsertText(field, 1);
+            DefaultValueGenerationUtil.SnippetContext snippetContext = new DefaultValueGenerationUtil.SnippetContext();
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RecordUtil.java:62]: Here it's correct to create snippet context per iteration since each iteration generates a separate insert text

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java (hunk 1 above)
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java:337]: Should it be set to 0 or 1?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java [hunk 5]
```diff
@@ -292,22 +305,51 @@ private static Optional<String> getDefaultValueForType(TypeSymbol bType, boolean
...
+     * Represents a context to track the number of placeholders.
+     */
+    public static class SnippetContext {
+        private int placeholderCount;
+
+        public SnippetContext() {
+            placeholderCount = 1;
+        }
+
+        public SnippetContext(int placeholderCount) {
```
[the remark this answers is not in the document]
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/DefaultValueGenerationUtil.java:343]: There was a scenario where the count was set to -1 instead of 0, thats why this constructor was added. Changed -1 to 0 and ran the test cases and none of the test cases failed. So will remove this.

File: language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/SnippetContext.java [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+ *
+ * @since 2201.4.0
+ */
+public class SnippetContext {
+    private int placeholderCount = 1;
+
+    public SnippetContext() {
+    }
+
+    public int incrementAndGetPlaceholderCount() {
```
Comment (IMS94) [inline language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/SnippetContext.java:29]: `placeholderCount++` will return the current value of `placeholderCount` and then increcement it's value. But here the method name suggests otherwise. We should set initial value of `placeholderCount` to `0` and then do
```
return ++placeholderCount;
```
or
```
this.placeholderCount++;
return this.placeholderCount;
```

**Review by IMS94 — CHANGES_REQUESTED** [review]
Added one comment related to SnippetContext implementation

**Review by malinthar — COMMENTED** [review]
LGTM! Better if we can refactor the following method as well
https://github.com/ballerina-platform/ballerina-lang/blob/85efbf36af82ef69ad3e27340243b84697c7e18d/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ServiceTemplateGenerator.java#L493

**Comment by mindula** [comment]
> LGTM! Better if we can refactor the following method using the SnippetContext as well.
> 
> https://github.com/ballerina-platform/ballerina-lang/blob/85efbf36af82ef69ad3e27340243b84697c7e18d/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ServiceTemplateGenerator.java#L493

Shall we create an issue for this and address it separately?

**Comment by malinthar** [comment]
> > LGTM! Better if we can refactor the following method using the SnippetContext as well.
> > https://github.com/ballerina-platform/ballerina-lang/blob/85efbf36af82ef69ad3e27340243b84697c7e18d/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ServiceTemplateGenerator.java#L493
> 
> Shall we create an issue for this and address it separately as we will have to do some changes in ListenerMetaData?

Created https://github.com/ballerina-platform/ballerina-lang/issues/38797

**Review by malinthar — APPROVED** [review]
LGTM!

**Review by IMS94 — APPROVED** [review]
