### PR TITLE
Fix inlay hint support when included record params are present

### LINKED ISSUE #40543: [Bug]: Inlay-hint not working
### Description

$subject for the following source code

```ballerina
import ballerina/io;
import ballerina/http;
import ballerinax/openai.audio;
import ballerinax/openai.text;

configurable string openAPIToken = ?;

const string AUDIO_FILE = "german_hello.mp3";
const string AUDIO_FILE_PATH = "./audo_clips/" + AUDIO_FILE;

public function main(string audioURL, string toLanguage) returns error? {
    http:Client audioEP = check new (audioURL);
    http:Response httpResp = check audioEP->/get();
    byte[] audioBytes = check httpResp.getBinaryPayload();
    check io:fileWriteBytes(AUDIO_FILE_PATH, audioBytes);

    // Creates a request to translate the audio file to text (English)
    audio:CreateTranslationRequest translationReq = {
        file: {fileContent: check io:fileReadBytes(AUDIO_FILE_PATH), fileName: AUDIO_FILE},
        model: "whisper-1"
    };

    //Translate the audio file to text
    audio:Client openAIAudio = check new ({auth: {token: openAPIToken}});
    audio:CreateTranslationResponse translationRes = check openAIAudio->/audio/translations.post(translationReq);
    io:println("Audio text in English: ", translationRes);

    // Creates a request to translate the text from English to another language
    text:CreateCompletionRequest completionReq = {
        model: "text-davinci-003",
        prompt: string `Translate the following text from English to ${toLanguage}: ${translationRes.text}`,
        temperature: 0.7,
        max_tokens: 256,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0
    };

    // Translates the text from English to another language
    text:Client openAIText = check new ({auth: {token: openAPIToken}});
    text:CreateCompletionResponse completionRes = check openAIText->/completions.post(completionReq);
    string? translatedText = completionRes.choices[0].text;

    if translatedText is () {
        return error("Failed to translate the given audio.");
    }
    io:println("Translated text: ", translatedText);

    var a = test("sampel", completionReq);
}

function test(string param1, text:CreateCompletionRequest param2) returns string {
    return "string";
}

```

### Steps to Reproduce

_No response_

### Affected Version(s)

2201.6.0-rc1

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #40576: [Bug]: Inlay hints in the VS code are invalid
### Description

For some ballerina code the inlay hints are wrong and misleading see the screenshot below:
Screenshot 2023-06-02 at 10 44 07

### Steps to Reproduce

Write the follwing application in VS code :

```bal
import ballerina/log;
import ballerina/http;

final http:Client clientEP = check new("http://localhost:9090/");

public function main() returns error? {
    http:Response res = check clientEP->/test;
    log:printInfo("response obtained", statuscode = res.statusCode, payload = check res.getTextPayload());
}
```

### Affected Version(s)

Ballerina SwanLake 2201.6.0

### OS, DB, other environment details and versions

MacOS with aarch64 architecture
VS code version - 1.78.2
Ballerina extension version - 4.2.3

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject

Fixes #40576 
Fixes #40543

## Samples
image

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [x] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/inlayhint/InlayHintProvider.java [hunk 1]
```diff
@@ -62,99 +68,120 @@ public static List<InlayHint> getInlayHint(InlayHintContext context) {
...
-                .flatMap(Collection::stream)
-                .collect(Collectors.toList());
+                .map(typeDescriptor -> (FunctionTypeSymbol) typeDescriptor);
+
+        if (functionTypeSymbol.isEmpty()) {
+            return Pair.of(Collections.emptyList(), Optional.empty());
+        }
+
+        Optional<ParameterSymbol> restParam = functionTypeSymbol.get().restParam();
+        return Pair.of(functionTypeSymbol.get().params().orElse(Collections.emptyList()), restParam);
```
Comment (mindula) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/inlayhint/InlayHintProvider.java:184]: Shall we remove the if condition and use,
```
return functionTypeSymbol.map(symbol -> Pair.of(symbol.params().orElse(Collections.emptyList()),
                        symbol.restParam())).orElse(Pair.of(Collections.emptyList(), Optional.empty()));
```

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/inlayhint/InlayHintProvider.java [hunk 2]
```diff
@@ -62,99 +68,120 @@ public static List<InlayHint> getInlayHint(InlayHintContext context) {
...
-            FunctionCallExpressionNode functionCallExpressionNode = (FunctionCallExpressionNode) node;
-            return getFunctionCallParameterSymbols(context, functionCallExpressionNode);
+            FunctionCallExpressionNode functionCallExpressionNode = (FunctionCallExpressionNode) invokableNode;
+            return getParamaterSymbolsForFunctionCall(context, functionCallExpressionNode);
         }
     }
 
-    private static List<ParameterSymbol> getFunctionCallParameterSymbols(InlayHintContext context,
-                                                                         FunctionCallExpressionNode node) {
+    private static Pair<List<ParameterSymbol>, Optional<ParameterSymbol>> getParamaterSymbolsForFunctionCall(
```
Comment (mindula) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/inlayhint/InlayHintProvider.java:137]:
```suggestion
    private static Pair<List<ParameterSymbol>, Optional<ParameterSymbol>> getParameterSymbolsForFunctionCall(
```

**Review by mindula — APPROVED** [review]
LGTM
