### PR TITLE
[master] Recompile crashed source only when the source is updated

### LINKED ISSUE #39012: [Bug] Bad Sad error in nBallerina project
### Description

When investigating https://github.com/ballerina-platform/ballerina-lang/actions/runs/3661779123/jobs/6190319909 figured that a bad, sad error had occurred. 

image

### Steps to Reproduce

Checkout the https://github.com/ballerina-platform/nballerina/commit/6710eabe3f50bdb5105dd319200893e3c110b1ec of  nballerina repo and open in VSCode. 

Add the following exact code snippet to the position (9,0) in the `compiler/modules/types.sexpr/schema.bal` file.

```ballerina
public function fn() returns string {
   	
match t {
    () => {
}    [1, 2] => {
}    [1, 2, 10] => {
}    [int => {
    _ => {
}}
	
float myVar4 = createVar();
	
int myVar5 = createVar();
	return string;
}
```
image

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

Swan Lake Update 3 

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39014: [Bug]: LS does not recover from bad sad error
### Description

Consider https://github.com/ballerina-platform/ballerina-lang/issues/39012.

In the above scenario, although the code snippet that generates the bad, sad error is removed, the subsequent compilation requests keep showing the bad sad error. 

### Steps to Reproduce

_No response_

### Affected Version(s)

Update 3

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #39014 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java [hunk 1]
```diff
@@ -296,20 +296,22 @@ public Optional<SemanticModel> semanticModel(Path filePath, @Nonnull CancelCheck
...
-        if (projectPair.isEmpty()) {
+        if (projectPair.isEmpty() || (projectPair.get().crashed() && !isSourceChange)) {
             return Optional.empty();
         }
 
         // Lock Project Instance
         Lock lock = projectPair.get().lockAndGet();
         try {
             PackageCompilation compilation = projectPair.get().project().currentPackage().getCompilation();
+            projectPair.get().setCrashed(false);
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java:314]:
```suggestion
if(projectPair.get().crashed()) {
     projectPair.get().setCrashed(false);
}
```

**Review by malinthar — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java [hunk 2]
```diff
@@ -190,7 +191,8 @@ public Map<String, List<Diagnostic>> getLatestDiagnostics(DocumentServiceContext
         if (project.get().kind() == ProjectKind.SINGLE_FILE_PROJECT) {
             projectRoot = projectRoot.getParent();
         }
-        PackageCompilation compilation = workspace.waitAndGetPackageCompilation(context.filePath()).orElseThrow();
+        PackageCompilation compilation = workspace.waitAndGetPackageCompilation(context.filePath(),
+                context.operation() == LSContextOperation.TXT_DID_CHANGE).orElseThrow();
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java:195]: Since the probability of reaching `orElseThrow()` is high now, we should check if the returned compilation is empty and, if empty, just return the empty map.

**Review by IMS94 — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java [hunk 3]
```diff
@@ -296,20 +296,22 @@ public Optional<SemanticModel> semanticModel(Path filePath, @Nonnull CancelCheck
      * Returns module compilation from the file path provided.
      *
      * @param filePath file path of the document
+     * @param isSourceChange True if the given file's source is changed
      * @return {@link ModuleCompilation}
      */
     @Override
-    public Optional<PackageCompilation> waitAndGetPackageCompilation(Path filePath) {
+    public Optional<PackageCompilation> waitAndGetPackageCompilation(Path filePath, boolean isSourceChange) {
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java:303]:
```suggestion
    public Optional<PackageCompilation> waitAndGetPackageCompilation(Path filePath, LSOperation operation) {
```

Shall we use the https://github.com/ballerina-platform/ballerina-lang/blob/9ead5e64f7944ca75f93b60ca8abef3b77970627/language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/LSOperation.java#L25 instead and check if the operation is a DidChangeOperation

**Review by malinthar — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java [hunk 4]
```diff
@@ -172,6 +172,15 @@ public interface WorkspaceManager {
...
     Optional<PackageCompilation> waitAndGetPackageCompilation(Path filePath);
 
+    /**
+     * Returns module compilation from the file path provided.
+     *
+     * @param filePath file path of the document
+     * @param isSourceChange True if the given file's source is changed
+     * @return {@link ModuleCompilation}
+     */
+    Optional<PackageCompilation> waitAndGetPackageCompilation(Path filePath, boolean isSourceChange);
```
Comment (pcnfernando) [inline language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java:182]: @IMS94 do we need to change the boolean to LSOperation. If we do so, we'll need a default value for it. thoughts?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java (hunk 3 above)
Comment (pcnfernando) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java:303]: https://github.com/ballerina-platform/ballerina-lang/pull/39190/files#r1064370919

File: language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java (hunk 4 above)
Comment (IMS94) [reply language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java:182]: Agreed. What if we move the common logic into a private method in the BallerinaWorkspaceManager class?

Comment (pcnfernando) [reply language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/workspace/WorkspaceManager.java]: Decided not to proceed with this. Hence resolving

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java (hunk 3 above)
Comment (pcnfernando) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java:302]: https://github.com/ballerina-platform/ballerina-lang/pull/39190#discussion_r1065731649

**Review by IMS94 — APPROVED** [review]

**Review by malinthar — APPROVED** [review]
LGTM!
