### PR TITLE
Fix NPE in `decimal:fromString()`

### LINKED ISSUE #35318: NPE when `decimal:fromString()` is called with an empty string as the argument
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    decimal|error fromString = decimal:fromString("");
}
```

```cmd
error: java.lang.NullPointerException
        at ballerina.lang.decimal.0:fromString(decimal.bal:103)
           test:main(test.bal:2)
```

**Affected Versions:**
2201.0.1

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #35318

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/DecimalValue.java [hunk 1]
```diff
@@ -72,7 +72,8 @@ public DecimalValue(String value) {
                 this.value = new BigDecimal(value, MathContext.DECIMAL128);
             } catch (NumberFormatException exception) {
                 String message = exception.getMessage();
-                if (message.equals("Too many nonzero exponent digits.") || message.equals("Exponent overflow.")) {
+                if ((message != null) && (message.equals("Too many nonzero exponent digits.") ||
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/DecimalValue.java:75]: Should we handle empty string separately instead of replying on message != null

Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/DecimalValue.java:75]: No, If the received exception message is not equal to those two strings it will anyway `throw exception;`. The problem was `exception.getMessage();` sometimes may be null, and then couldn't use `equals` method on `null`.

**Review by warunalakshitha — APPROVED** [review]
LGTM
