### PR TITLE
Fix duplicate declarations in ballerina tests

### LINKED ISSUE #20694: Function with same name can be defined in module and test bal
**Description:**

Sample module as follows.
main bal
```

public function main() {
  testDuplicate();
}

public function testDuplicate() {
  io:println("module");
}

```
 test bal
```
public function testDuplicate() {
  io:println("test");
}


@test:Config {
    before: "beforeFunc",
    after: "afterFunc"
}
function testFunction() {
  testDuplicate();
    main();
}

```

Compilation successful without an issue. When you run the test, prints 'tests' twice.

Correct behavior should be compilation failure.

### LINKED ISSUE #20963: BAD SAD Error during ballerina test when field name is duplicated in test file and source file
**Description:**
 In a Ballerina module, define variables with same name in a test bal file as well as a source bal file as global variables. 
Use 'ballerina test module_name' to execute tests.

**Steps to reproduce:**

Duplicate the following variable in a source bal file as well as a test bal file.

`string var1 = "value";`

Following is the error log.

```
[2020-02-10 18:17:29,098] SEVERE {b7a.log.crash} - Duplicate field name "var1" with signature "Ljava.lang.String;" in class file dilhasha/testmod/___init 
java.lang.ClassFormatError: Duplicate field name "var1" with signature "Ljava.lang.String;" in class file dilhasha/testmod/___init
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.ballerinalang.testerina.util.TestarinaClassLoader.loadClass(TestarinaClassLoader.java:57)
	at org.ballerinalang.testerina.core.BTestRunner.packageProcessed(BTestRunner.java:352)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$processProgramFile$4(BTestRunner.java:311)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.testerina.core.BTestRunner.processProgramFile(BTestRunner.java:308)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$buildSuites$2(BTestRunner.java:285)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.ballerinalang.testerina.core.BTestRunner.buildSuites(BTestRunner.java:273)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:156)
	at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:132)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:90)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.TestCommand.execute(TestCommand.java:282)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```
This needs to be handled during compilation and result in a compilation failure.

**Affected Versions:**
Ballerina 1.1.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by dulvinw**
Fixes #20963
Fixes #20694

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java [hunk 1]
```diff
@@ -37,6 +37,7 @@
     UNDEFINED_SYMBOL("undefined.symbol"),
     UNDEFINED_FUNCTION("undefined.function"),
     UNDEFINED_FUNCTION_IN_OBJECT("undefined.function.in.object"),
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java]: Remove this change.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 2]
```diff
@@ -258,6 +262,14 @@ private boolean hasSameOwner(BSymbol symbol, BSymbol foundSym) {
                 ((foundSym.owner.tag & SymTag.INVOKABLE) == SymTag.INVOKABLE);
     }
 
+    private boolean isDependentTestPackage(BSymbol symbol, BSymbol foundSym) {
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: Shall we rename this? It is not  `isDependentTestPackage`, rather it validates, whether found symbol defined in the parent package. Shall we say 'isRedeclaredInParentModule' ?

**Comment by hasithaa** [comment]
Shall we remove .keep and .gitignore files as well. Those are not needed.

**Comment by hasithaa** [comment]
@dulvinw Can you check the test failure?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 3]
```diff
@@ -258,6 +262,14 @@ private boolean hasSameOwner(BSymbol symbol, BSymbol foundSym) {
                 ((foundSym.owner.tag & SymTag.INVOKABLE) == SymTag.INVOKABLE);
     }
 
+    private boolean isSymbolRedeclaredInTestPackage(BSymbol symbol, BSymbol foundSym) {
+        if (Symbols.isFlagOn(symbol.owner.flags, Flags.TESTABLE) &&
+                !Symbols.isFlagOn(foundSym.owner.flags, Flags.TESTABLE)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: Do we need the check for the found symbol? `hasSameOwner` being false would imply it's not from the same (testable) package?

Comment (hasithaa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: A good suggestion. @dulvinw Can you check this and send a separate PR with this improvement.
