### PR TITLE
Reduce the overhead of dealing with negative atoms in type checker

### LINKED ISSUE #44239: [Bug]: Union Operator Does not Function Properly
### Description

The union operator of ballerina language fails to map the the datatypes whereas when used individually it works properly.

**Case 1:**

```
public type USCoreEthnicityExtension record {|
    *r4:ExtensionExtension;

    string id?;
    r4:uri url = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity";
    (USCoreEthnicityExtensionOmbCategory | USCoreEthnicityExtensionDetailed | USCoreEthnicityExtensionText)[] extension?;
|};
```
Aa project with the above record in the extensions.bal does not even compile.

**Case 2:**

```
public type USCoreEthnicityExtensions (USCoreEthnicityExtensionOmbCategory | USCoreEthnicityExtensionDetailed | USCoreEthnicityExtensionText);

public type USCoreEthnicityExtension record {|
    *r4:ExtensionExtension;

    string id?;
    r4:uri url = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity";
    USCoreEthnicityExtensions[] extension?;
|};
```
Case 1 is resolved when the union of datatypes used like above. But when the record is used like shown below,

```
public type USCorePatientExtensions (r4:Extension | USCoreEthnicityExtension | USCoreRaceExtension);

public type USCorePatientProfile record {|
    *r4:DomainResource;

    RESOURCE_NAME_USCOREPATIENTPROFILE resourceType = RESOURCE_NAME_USCOREPATIENTPROFILE;

    USCorePatientExtensions[] extension?;
    USCorePatientProfileGender gender;
    r4:Extension[] modifierExtension?;
|};
```
and attempts to be parsed,

```
import ballerinax/health.fhir.r4.parser;

function parse() returns error? {
    json patientPayload = { <<Patient json for USCore700>> };
    USCorePatientProfile patientProfile = check parser:parse(patientPayload, USCorePatientProfile).ensureType();
}
```

returns an error as:

`error {ballerinax/health.fhir.r4:6}FHIRError&{ballerinax/health.fhir.r4:6}FHIRErrorType ("Provided type does not represent a FHIR resource",issues=[{"severity":"error","code":"structure","details":{"coding":[{"system":"http://hl7.org/fhir/issue-type","code":"400"}],"text":"Provided type does not represent a FHIR resource"},"diagnostic":(),"expression":()}],internalError=false,httpStatusCode=400,uuid="01f078cf-2c94-1d4e-844f-221e16ca42c0")`

where as ideally it should at least be mapped to **r4:Extension**.

### Steps to Reproduce

1. Get the [USCore700 ](https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4/tree/main/uscore700) package
2. Create a file named extensions.bal in the project.
3. Copy the content from the extensions.txt to it.
4. In the `resource_uscore_patient_profile.bal` of the package, create a new type as:
`public type USCorePatientExtensions (r4:Extension | USCoreEthnicityExtension | USCoreRaceExtension);`
5. Replace the `r4:Extension[] extension?; ` of Patient domain resource to `USCorePatientExtensions[] extension?;`
6. Copy the content of the parse.txt to a test file.
7. Run the test.

[extensions.txt](https://github.com/user-attachments/files/21766900/extensions.txt)
[test_parse.txt](https://github.com/user-attachments/files/21766963/test_parse.txt)

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

Ballerina: 2201.12.3
OS; Windows 11

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by heshanpadmasiri**
## Purpose
$subject
Fixes #44239,  #44207,  #44264

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/TypeIdSupplier.java [hunk 1]
```diff
@@ -63,14 +63,18 @@ public static int namedId(TypeIdentifier id) {
         return newId;
     }
 
-    public static int getReservedId() {
+    public static synchronized int getReservedId() {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/TypeIdSupplier.java]: Shall we use ReentrantLock since synchronized blocks at the OS thread level

Comment (heshanpadmasiri) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/TypeIdSupplier.java]: As discussed offline removed the synchronized
