### PR TITLE
Add auto completion fixes

### LINKED ISSUE #25139: Non-public constructs are getting picked by LS
**Description:**
We had this issue [1] where it exposes internal (query/transaction) functions through LS. So to prevent that from happening, we made them private (without `public` keyword) [2]. But still, LS seems to pickup those constructs. Shall we limit LS to only pick up public constructs?

**Steps to reproduce:**
n/a

**Affected Versions:**
slp1

**OS, DB, other environment details and versions:**
n/a

**Related Issues (optional):**
[1] https://github.com/ballerina-platform/ballerina-lang/issues/24943
[2] https://github.com/ballerina-platform/ballerina-lang/issues/24943

### PR DESCRIPTION
**Pull request by nadeeshaan**
- Revamp the assignment statement context completions
- Add scope entry filter to filter out the public entries

Fixes #25139

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java [hunk 1]
```diff
@@ -41,13 +57,57 @@ public AssignmentStatementNodeContext() {
...
 
     @Override
     public boolean onPreValidation(AssignmentStatementNode node) {
         return !node.equalsToken().isMissing();
     }
+
+    private List<LSCompletionItem> getNewExprCompletionItems(LSContext context, AssignmentStatementNode node) {
+        List<LSCompletionItem> completionItems = new ArrayList<>();
+        ArrayList<Scope.ScopeEntry> visibleSymbols = new ArrayList<>(context.get(CommonKeys.VISIBLE_SYMBOLS_KEY));
+        Optional<BObjectTypeSymbol> objectType;
```
Comment (rasika) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java:95]: this local variable seems to be redundant. can we add merge  `ifPresent` logic in https://github.com/ballerina-platform/ballerina-lang/pull/25214/files#diff-3fef1a396b3d9462c79c38bf09b51ca3R108 into https://github.com/ballerina-platform/ballerina-lang/pull/25214/files#diff-3fef1a396b3d9462c79c38bf09b51ca3R103. And else block can be safely removed. WDYT?

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/AssignmentStatementNodeContext.java:95]: +1
Sending this in next commit.
