### PR TITLE
Fix illegal cyclic reference identified in a custom listener with service reference

### LINKED ISSUE #32898: Cannot declare the service type when a custom listener with service reference is used
**Description:**
$subject

**Steps to reproduce:**
Sample code
```
import ballerina/http;

service class DispatcherService {
   private map<SimpleHttpService> services = {};

   isolated resource function get event() returns error? {
      // Do stuff
   }

   isolated function addRef(SimpleHttpService serviceRef) returns error? {
      // add Reference to services map
   }

   isolated function removeRef() returns error? {
      // remove Reference from services map
   }
}

class CustomListener {
   private http:Listener httpListener;
   private DispatcherService dispatcherService; //Service ref

   public isolated function init() returns error? {
      self.httpListener = check new (8090);
      self.dispatcherService = new DispatcherService();
   }

    public isolated function attach(SimpleHttpService serviceRef, () attachPoint) returns @tainted error? {
        check self.dispatcherService.addRef(serviceRef);
        check self.httpListener.attach(self.dispatcherService, attachPoint);
    }

    public isolated function detach(service object {} s) returns error? {
        check self.dispatcherService.removeRef();
        return self.httpListener.detach(s);
    }

    public isolated function 'start() returns error? {
        return self.httpListener.'start();
    }

    public isolated function gracefulStop() returns @tainted error? {
        return self.httpListener.gracefulStop();
    }

    public isolated function immediateStop() returns error? {
        return self.httpListener.immediateStop();
    }
}

public type SimpleHttpService service object {
   remote function onAppCreated();
};

listener CustomListener customListener = new (); // This line shows illegal cyclic reference error
service SimpleHttpService on customListener { // Service type SimpleHttpService  is used
   remote function onAppCreated() {
   }
}

```
This causes the below error
```
ERROR [usercode.bal:(56:1,56:49)] illegal cyclic reference '[customListener, CustomListener, DispatcherService, SimpleHttpService, $anonType$_1]'
```

But if we remove the service type from service declaration the error won't pop up.

```
listener CustomListener customListener = new (); 
service on customListener { // Service type SimpleHttpService  is not used
   remote function onAppCreated() {
   }
}

```
**Affected Versions:**
Swan Lake Beta 3

### PR DESCRIPTION
**Pull request by rpjayasekara**
Fixes #32898 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by KRVPerera — APPROVED** [review]
LGTM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 1]
```diff
@@ -1638,11 +1638,7 @@ public void visit(BLangUserDefinedType userDefinedType) {
             return;
         }
         BTypeSymbol tsymbol = resolvedType.tsymbol;
-        BSymbol pop = this.currDependentSymbolDeque.pop();
-        this.currDependentSymbolDeque.push(tsymbol);
-        recordGlobalVariableReferenceRelationship(pop);
-        this.currDependentSymbolDeque.pop();
-        this.currDependentSymbolDeque.push(pop);
+        recordGlobalVariableReferenceRelationship(tsymbol);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java:1641]: With this change, we no longer log an error for

```ballerina
type Foo record {
    typedesc i = x;
};

final typedesc x = Foo;
```

That's not correct, right?

Comment (rpjayasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java:1641]: I think it is not because of this change. Even without the change, error does not log

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java:1641]: Seems to be a regression master. I get the error on slbeta4 also. Created https://github.com/ballerina-platform/ballerina-lang/issues/34097.

I'm still not sure if this is the correct place for the change though. Isn't the issue we are trying to solve specifically applicable to service declarations? Looping in @rdhananjaya also.

Comment (rdhananjaya) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java:1641]: I think the issue is when dataflow analyzer sees a reference to a used-defined type, they way it records the dependency is wrong

**Review by rdhananjaya — APPROVED** [review]

**Review by hasithaa — APPROVED** [review]
