### PR TITLE
Fix completions for table type descriptor and table constructor expressions

### LINKED ISSUE #35117: Missing completions in table type descriptor
**Description:**
1. Missing completions for `Person`
Screenshot 2022-02-15 at 21 03 50

2. Missing completions for `name`
Screenshot 2022-02-15 at 21 05 09

**Steps to reproduce:**
```
type Student record {
    readonly string name;
    int age;
};
type Employee record {
    readonly string name;
    float salary;
};
type Person Student|Employee;
type PersonTable table<Person> key(name); // missing completions for 'Person', 'name' 

 PersonTable tbl = table key(name)[ // missing completions for 'name' 
      { name: "A", age: 1 },
      { name: "B", salary: 10.0},
      { name: "C", age: 2 }
    ];
```

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
$subject

Fixes #35117

## Approach
Added completion support for union (of records) row type parameters.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java [hunk 1]
```diff
@@ -89,23 +92,49 @@ public KeySpecifierNodeContext() {
...
             rowTypeSymbol = CommonUtil.getRawType(typeSymbol.get());
+            // If the context type is again a table, need to derive row type.
+            // This is valid for cases where table type is defined separately as a user defined type.
+            // ex:
+            //      type PersonTable table<Person> key(name);
+            //      PersonTable tbl = table key(<cursor>);
+            if (rowTypeSymbol.typeKind() == TypeDescKind.TABLE) {
+                TableTypeSymbol tableTypeSymbol = (TableTypeSymbol) rowTypeSymbol;
+                rowTypeSymbol = CommonUtil.getRawType(tableTypeSymbol.rowTypeParameter());
+            }
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java:103]: Can't we handle this within the `ContextTypeResolver`? Also, if we look at the outer-most `if` clause, we check the type of the node's parent and it is better if we can get the context type from the resolver itself.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java [hunk 2]
```diff
@@ -89,23 +92,49 @@ public KeySpecifierNodeContext() {
...
+                    .map(typeSymbol -> (RecordTypeSymbol) typeSymbol)
+                    .map(RecordTypeSymbol::fieldDescriptors)
+                    .reduce((map1, map2) -> map1.entrySet().stream()
+                            .filter(e -> map2.containsKey(e.getKey()))
+                            .filter(e -> !fieldNames.contains(e.getKey()))
+                            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue)))
+                    .map(fieldMap -> new ArrayList<>(fieldMap.values()))
+                    .orElse(new ArrayList<>());
+            completionItems.addAll(this.getCompletionItemList(commonFields, context));
+        }
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java:137]: Shall we move this to a separate utility method for a cleaner approach?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java [hunk 3]
```diff
@@ -89,23 +92,49 @@ public KeySpecifierNodeContext() {
...
+            List<RecordFieldSymbol> commonFields = unionTypeSymbol.memberTypeDescriptors().stream()
+                    .map(CommonUtil::getRawType)
+                    .map(typeSymbol -> (RecordTypeSymbol) typeSymbol)
+                    .map(RecordTypeSymbol::fieldDescriptors)
+                    .reduce((map1, map2) -> map1.entrySet().stream()
+                            .filter(e -> map2.containsKey(e.getKey()))
+                            .filter(e -> !fieldNames.contains(e.getKey()))
+                            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue)))
+                    .map(fieldMap -> new ArrayList<>(fieldMap.values()))
+                    .orElse(new ArrayList<>());
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java:135]: Use `Collections.emptyList()`

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TableTypeDescriptorNodeContext.java [hunk 4]
```diff
@@ -83,6 +84,12 @@ private boolean onSuggestKeyKw(BallerinaCompletionContext context, TableTypeDesc
...
         TypeSymbol typeSymbol = CommonUtil.getRawType((TypeSymbol) symbol.get());
         // key specifier or key constraint not allowed for map types
-        return typeSymbol.typeKind() == TypeDescKind.RECORD;
+        if (typeSymbol.typeKind() == TypeDescKind.RECORD) {
+            return true;
+        }
+        
+        // Check if type is a union of records
+        return typeSymbol.typeKind() == TypeDescKind.UNION &&
+                CommonUtil.isUnionOfType((UnionTypeSymbol) typeSymbol, TypeDescKind.RECORD);
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TableTypeDescriptorNodeContext.java:93]: Can we merge these two?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

**Review by gayalkuruppu — COMMENTED** [review]
Shouldn't we provide completions for the following scenario as well? Or can we ignore this since `Person` is redundant?
```
type Student record {
    readonly string name;
    int age;
};

type Person Student;
type PersonTable table<Person> key(name); // missing completions for 'name' 

 PersonTable tbl = table key(name)[ // missing completions for 'name' 
      { name: "A", age: 1 },
      { <cursor>}   // missing completions for 'name'
    ];
    ```

File: language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/source/table_typedesc11.bal [hunk 5]
```diff
@@ -0,0 +1,11 @@
...
+    readonly string name;
+    int age;
+};
+type Employee record {
+    readonly string name;
+    float salary;
+};
+type Person Student|Employee;
+
+type PersonTable table<>
```
Comment (gayalkuruppu) [inline language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/source/table_typedesc11.bal:11]: Shall we add a new line here?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TableTypeDescriptorNodeContext.java (hunk 4 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TableTypeDescriptorNodeContext.java:93]: +1

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java (hunk 3 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java:135]: If we use `Collections.emptyList()`, it identify return type as `List<Object>` and give a compilation error.

**Review by nadeeshaan — DISMISSED** [review]
LGTM

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java (hunk 2 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java]: Done!

File: language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/source/table_typedesc11.bal (hunk 5 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/test/resources/completion/typedesc_context/source/table_typedesc11.bal:11]: > Shouldn't we provide completions for the following scenario as well? Or can we ignore this since `Person` is redundant?
> 
> ```
> type Student record {
>     readonly string name;
>     int age;
> };
> 
> type Person Student;
> type PersonTable table<Person> key(name); // missing completions for 'name' 
> 
>  PersonTable tbl = table key(name)[ // missing completions for 'name' 
>       { name: "A", age: 1 },
>       { <cursor>}   // missing completions for 'name'
>     ];
>     ```
> ```

I had a look at this. When using type aliases like this, we have to use recursion and it may lead to stack overflow issues we had with default value generation. Therefore, IMO, we should ignore this case. @nadeeshaan WDYT?

**Comment by IMS94** [comment]
> Shouldn't we provide completions for the following scenario as well? Or can we ignore this since `Person` is redundant?
> 
> ```
> type Student record {
>     readonly string name;
>     int age;
> };
> 
> type Person Student;
> type PersonTable table<Person> key(name); // missing completions for 'name' 
> 
>  PersonTable tbl = table key(name)[ // missing completions for 'name' 
>       { name: "A", age: 1 },
>       { <cursor>}   // missing completions for 'name'
>     ];
>     ```
> ```

I had a look at this. When using type aliases like this, we have to use recursion and it may lead to stack overflow issues we had with default value generation. Therefore, IMO, we should ignore this case. @nadeeshaan WDYT?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 6]
```diff
@@ -1277,6 +1276,44 @@ public static TypeSymbol getRawType(TypeSymbol typeDescriptor) {
...
+     * can be a record or a union of records for this to work.
+     *
+     * @param typeSymbol Type symbol from which record types need to be extracted.
+     * @return List of record type symbols, wrapped with a raw type and broader type container.
+     */
+    public static List<RawTypeSymbolWrapper<RecordTypeSymbol>> getRecordTypeSymbols(TypeSymbol typeSymbol) {
+        TypeSymbol rawType = CommonUtil.getRawType(typeSymbol);
+        if (rawType.typeKind() == TypeDescKind.RECORD) {
+            return Collections.singletonList(RawTypeSymbolWrapper.from(typeSymbol, (RecordTypeSymbol) rawType));
+        } else if (rawType.typeKind() == TypeDescKind.UNION) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1305]: Since we return, we don't need `else-if`. Let's stick to a set of `if` clauses for better readability

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java [hunk 7]
```diff
@@ -90,22 +91,30 @@ public KeySpecifierNodeContext() {
...
+                .reduce((map1, map2) -> map1.entrySet().stream()
+                        .filter(e -> map2.containsKey(e.getKey()))
+                        .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue))
+                )
+                .stream()
+                .flatMap(map -> map.entrySet().stream())
+                .filter(entry -> !fieldNames.contains(entry.getKey()))
+                .map(Map.Entry::getValue)
+                .filter(recordFieldSymbol -> recordFieldSymbol.getName().isPresent())
+                .filter(recordFieldSymbol -> SyntaxInfo.isIdentifier(recordFieldSymbol.getName().get()))
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java:114]: Can't we use a single filter?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TableTypeDescriptorNodeContext.java [hunk 8]
```diff
@@ -83,6 +83,11 @@ private boolean onSuggestKeyKw(BallerinaCompletionContext context, TableTypeDesc
 
         TypeSymbol typeSymbol = CommonUtil.getRawType((TypeSymbol) symbol.get());
         // key specifier or key constraint not allowed for map types
-        return typeSymbol.typeKind() == TypeDescKind.RECORD;
+        if (typeSymbol.typeKind() == TypeDescKind.RECORD) {
+            return true;
+        }
+        
+        // Check if type is a union of records
+        return CommonUtil.isUnionOfType(typeSymbol, TypeDescKind.RECORD);
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TableTypeDescriptorNodeContext.java:91]: Shall we merge these two into a single condition?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterContextProvider.java [hunk 9]
```diff
@@ -108,8 +108,12 @@ public TypeParameterContextProvider(Class<T> attachmentPoint) {
...
                 return false;
             }
-            TypeDescKind rawType = CommonUtil.getRawType(((TypeDefinitionSymbol) symbol).typeDescriptor()).typeKind();
-            return rawType == TypeDescKind.MAP || rawType == TypeDescKind.RECORD;
+            TypeSymbol rawType = CommonUtil.getRawType(((TypeDefinitionSymbol) symbol).typeDescriptor());
+            if (rawType.typeKind() == TypeDescKind.MAP || rawType.typeKind() == TypeDescKind.RECORD) {
+                return true;
+            }
+
+            return CommonUtil.isUnionOfType(rawType, TypeDescKind.RECORD);
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterContextProvider.java:116]: We can merge these together

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java (hunk 7 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/KeySpecifierNodeContext.java:114]: Good point actually :D. Let's proceed.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 10]
```diff
@@ -1305,6 +1304,45 @@ public static TypeSymbol getRawType(TypeSymbol typeDescriptor) {
...
+    }
+
+    /**
+     * Given a type symbol, this method will get the record type symbols in the provided type. i.e. the provided type
+     * can be a record or a union of records for this to work.
+     *
+     * @param typeSymbol Type symbol from which record types need to be extracted.
+     * @return List of record type symbols, wrapped with a raw type and broader type container.
+     */
+    public static List<RawTypeSymbolWrapper<RecordTypeSymbol>> getRecordTypeSymbols(TypeSymbol typeSymbol) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1329]: Is it intended that we neglect the non-record type member types in the union types? If so shall we clearly mention that in the documentations?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterContextProvider.java [hunk 11]
```diff
@@ -108,8 +108,9 @@ public TypeParameterContextProvider(Class<T> attachmentPoint) {
             if (symbol.kind() != SymbolKind.TYPE_DEFINITION) {
                 return false;
             }
-            TypeDescKind rawType = CommonUtil.getRawType(((TypeDefinitionSymbol) symbol).typeDescriptor()).typeKind();
-            return rawType == TypeDescKind.MAP || rawType == TypeDescKind.RECORD;
+            TypeSymbol rawType = CommonUtil.getRawType(((TypeDefinitionSymbol) symbol).typeDescriptor());
+            return rawType.typeKind() == TypeDescKind.MAP || rawType.typeKind() == TypeDescKind.RECORD ||
+                    CommonUtil.isUnionOfType(rawType, TypeDescKind.RECORD);
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterContextProvider.java:113]: Should we consider union of maps as well?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 10 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1406]: @nadeeshaan It wasn't my original idea. But I was refactoring the following method in CommonUtil. And it had considered only the record type members.
```
    protected List<Pair<TypeSymbol, TypeSymbol>> getRecordTypeDescs(BallerinaCompletionContext context,
                                                                    Node node) {
        ContextTypeResolver typeResolver = new ContextTypeResolver(context);
        Optional<TypeSymbol> resolvedType = node.apply(typeResolver);
        if (resolvedType.isEmpty()) {
            return Collections.emptyList();
        }
        TypeSymbol rawType = CommonUtil.getRawType(resolvedType.get());
        if (rawType.typeKind() == TypeDescKind.RECORD) {
            return Collections.singletonList(Pair.of(rawType, resolvedType.get()));
        }
        if (rawType.typeKind() == TypeDescKind.UNION) {
            return ((UnionTypeSymbol) rawType).memberTypeDescriptors().stream()
                    .filter(typeSymbol -> CommonUtil.getRawType(typeSymbol).typeKind() == TypeDescKind.RECORD)
                    .map(typeSymbol -> Pair.of(CommonUtil.getRawType(typeSymbol), typeSymbol))
                    .collect(Collectors.toList());
        }

        return Collections.emptyList();
    }
```
That's why I kept it this way. WDYT?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterContextProvider.java (hunk 11 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterContextProvider.java]: +1

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 10 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1406]: For now, mentioned that this method will disregard non-record type members as a comment.

**Comment by mohanvive** [comment]
@IMS94 There are some checkstyle failures.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RawTypeSymbolWrapper.java [hunk 12]
```diff
@@ -0,0 +1,48 @@
...
+ */
+package org.ballerinalang.langserver.common.utils;
+
+import io.ballerina.compiler.api.symbols.TypeSymbol;
+
+/**
+ * A utility bean to hold a record's raw type symbol and broader type symbol (type reference, etc.).
+ *
+ * @param <T> Raw TypeSymbol type
+ * @since 2201.0.x
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/RawTypeSymbolWrapper.java:24]: Version

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 13]
```diff
@@ -582,12 +581,12 @@ public static List<LSCompletionItem> getRecordFieldCompletionItems(BallerinaComp
      *
      * @param context Language Server Operation Context
      * @param fields  A non empty map of fields
-     * @param symbol  Pair of Raw TypeSymbol and broader TypeSymbol
+     * @param wrapper  Pair of Raw TypeSymbol and broader TypeSymbol
      * @return {@link Optional}   Completion Item to fill all the options
      */
     public static Optional<LSCompletionItem> getFillAllStructFieldsItem(BallerinaCompletionContext context,
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:587]: Shall we change the name of the method to `getFillAllRecordFieldsCompletionItem`

**Review by malinthar — APPROVED** [review]
LGTM!
