### PR TITLE
Fix missing module in InteropValidator diagnostic reporting

### LINKED ISSUE #30679: Test fails with failed to load init class runtime error when using interop
**Description:**
A Runtime exception occurs when running a particular Ballerina project using interop. It is a unit test that makes use of a particular java class to test dependently typed variables. Class `VariableReturnType` resides in testerina-integration-test and the interop paths to the `build/libs/integration-test.jar`
The project can be found [here](https://github.com/Ibaqu/ballerina-lang/tree/master_COPY).

Test fails with :

```
Compiling source
        intg_tests/object_mocking:0.0.0

Running Tests with Coverage

        object_mocking
error: failed to load init class :intg_tests.object_mocking.0_0_0.$_init
```

Generated module jar and Testable jar do not contain any classes. Only the manifest.mf file. 

**Steps to reproduce:**

**Affected Versions:**beta 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by azinneera**
Fixes #30679

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropValidator.java [hunk 1]
```diff
@@ -70,6 +70,7 @@ public static InteropValidator getInstance(CompilerContext context) {
     }
 
     public void validate(ModuleId moduleId, CompilerBackend compilerBackend, BLangPackage bLangPackage) {
+        dlog.setCurrentPackageId(bLangPackage.packageID);
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropValidator.java:73]: Shall we add a test for this or improve existing test?

Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropValidator.java:73]: Created #31539 to track writing test cases

**Review by warunalakshitha — APPROVED** [review]
