### PR TITLE
Fix compiler crash for self referring record in configurable variables

### LINKED ISSUE #31295: Compiler crash with StackOverflowError when we have configurable record type variable with self reference
**Description:**
```ballerina
type Person record {|
    string name;
    Person child?;
|};

configurable Person p = ?; 
```

```
[2021-06-19 14:26:19,088] SEVERE {b7a.log.crash} - null 
java.lang.StackOverflowError
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSameType(Types.java:335)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isSameType(Types.java:306)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:636)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:631)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:939)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:910)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:929)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:910)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:929)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isSupportedConfigType(SemanticAnalyzer.java:910)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.isS

```
**Affected Versions:**
slbeta2

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject

Fixes #31295 

## Approach
adding `unresolvedTypes` check to the recursive method

## Samples
```ballerina
type Person record {|
    string name;
    Person child?;
|};

configurable Person p = ?; 
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 1]
```diff
@@ -886,7 +885,11 @@ private void checkSupportedConfigType(BType type, Location location, String varN
         }
     }
 
-    private boolean isSupportedConfigType(BType type, List<String> errors, String varName) {
+    private boolean isSupportedConfigType(BType type, List<String> errors, String varName,
+                                          Set<BType> unresolvedTypes) {
+        if (!unresolvedTypes.add(type) && isRecordType(type)) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:890]: IMO we do not need a record type check. There can be cyclic union types as well.
