### PR TITLE
Fix issue in member access expression

### LINKED ISSUE #34072: BAD sad error when using constant expression in index access expression
```
const N = 2;
const M = 3;

type T1 int[N][M]; // same as (int[M])[N]

public function main() {

    T1 x1 = [[1, 2, 3], [1, 2, 3]]; 
    int[M] _ = x1[N-1]; // Problem is here
}
```

```
2021-12-01 09:03:23,277] SEVERE {b7a.log.crash} - class org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef (org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr and org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef are in unnamed module of loader 'app')
java.lang.ClassCastException: class org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr cannot be cast to class org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef (org.wso2.ballerinalang.compiler.tree.expressions.BLangBinaryExpr and org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef are in unnamed module of loader 'app')
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getConstIndex(TypeChecker.java:7621)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkArrayIndexBasedAccess(TypeChecker.java:7639)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkListIndexBasedAccess(TypeChecker.java:7685)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkIndexAccessExpr(TypeChecker.java:7500)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2731)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangIndexBasedAccess.accept(BLangIndexBasedAccess.java:56)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:376)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:355)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:978)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
```

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
Fix issue in member access expression when a binary expression or group expression is used as the key expression

Fixes #34072

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java [hunk 1]
```diff
@@ -370,6 +370,23 @@ public void testInvalidMemberAccessOnStrings2() {
...
+
+    @Test
+    public void testMemberAccessWithGroupExprAsIndex() {
+        BRunUtil.invoke(result, "testMemberAccessWithGroupExprAsIndex");
+    }
+
+    @Test(expectedExceptions = BLangRuntimeException.class,
+            expectedExceptionsMessageRegExp = ".*\\{ballerina/lang.array\\}IndexOutOfRange \\{\"message\":\"array " +
+                    "index out of range: index: 3, size: 3\"\\}.*")
+    public void testMemberAccessOutOfRangeWithBinaryExpr() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java:386]: We can use `trap` with the access and assert this also in b7a itself.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 2]
```diff
@@ -771,6 +771,41 @@ public function testNestedMemberAccessOnIntersectionTypes() {
     assertEquality((), v3);
 }
 
+type myrec record {|
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:774]: Shall we use

```suggestion
type MyRec record {|
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 3]
```diff
@@ -771,6 +771,41 @@ public function testNestedMemberAccessOnIntersectionTypes() {
...
+    string name;
+|};
+
+const LENGTH = 10;
+
+function testMemberAccessWithBinaryExprAsIndex() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:780]: Shall we add some tuple and map tests also?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 4]
```diff
@@ -771,6 +771,41 @@ public function testNestedMemberAccessOnIntersectionTypes() {
...
+    int[3] intArr = [0, 1, 2];
+    assertEquality(1, intArr[10 - 9]);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:782]: Instead of passing these in-line shall we assign it to a variable of the relevant type and pass it? So that that bit is also validated.

We can write negative tests with tuples and records also.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 5]
```diff
@@ -771,6 +771,41 @@ public function testNestedMemberAccessOnIntersectionTypes() {
...
+    
+    int x = 8;
+    assertEquality(2, intArr[10 - x]);
+    
+    assertEquality(0, intArr[10 - LENGTH]);
+    
+    myrec myRecVar = {name: "Ballerina"};
+    assertEquality("Ballerina", myRecVar["na" + "me"]);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:790]: When we fix https://github.com/ballerina-platform/ballerina-lang/issues/33090 and https://github.com/ballerina-platform/ballerina-lang/issues/34188 the static type of some of these will change. So for other cases also shall we add tests when at least one of the operands in the binary expression is not of a singleton type? Like L785.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java (hunk 1 above)
Comment (rdulmina) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java:386]: Will update

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 6]
```diff
@@ -8162,16 +8175,18 @@ private boolean couldHoldTableValues(BType type, List<BType> encounteredTypes) {
...
     private boolean isConst(BLangExpression expression) {
-
-        if (ConstantAnalyzer.isValidConstantExpressionNode(expression)) {
-            return true;
-        }
-
-        if (expression.getKind() != NodeKind.SIMPLE_VARIABLE_REF) {
-            return false;
+        switch (expression.getKind()) {
+            case LITERAL:
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8179]: Are these codecov warnings false negatives?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 7]
```diff
@@ -771,6 +771,101 @@ public function testNestedMemberAccessOnIntersectionTypes() {
...
+function testMemberAccessOutOfRangeWithBinaryExpr() {
+    int[3] intArr = [0, 1, 2];
+    int|error a = trap intArr[2 + 1];
+    if a is error {
+        assertEquality("error(\"{ballerina/lang.array}IndexOutOfRange\",message=\"array index out of range: " + 
+        "index: 3, size: 3\")", a.toString());
+    } else {
+        assertEquality("error(\"{ballerina/lang.array}IndexOutOfRange\",message=\"array index out of range: " + 
+        "index: 3, size: 3\")", a.toString());
+    }
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:854]: Instead, how about

```suggestion
    assertTrue(a is error);
    error e = <error> a;
    // assert `e.message()` and `<string> checkpanic e.detail()["message"]`
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 6 above)
Comment (rdulmina) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8179]: Yes :-)

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal (hunk 7 above)
Comment (rdulmina) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:854]: +1 will updated

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 8]
```diff
@@ -2803,8 +2803,7 @@ public void visit(BLangIndexBasedAccess indexBasedAccessExpr) {
                         exprType);
                 resultType = symTable.semanticError;
                 return;
-            } else if (types.isSubTypeOfBaseType(exprType, TypeTags.RECORD) &&
-                    (indexExpr.getKind() == NodeKind.LITERAL || isConst(indexExpr)) &&
+            } else if (types.isSubTypeOfBaseType(exprType, TypeTags.RECORD) && isConst(indexExpr) &&
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2806]: Shall we rename `isConst` to `isConstExpr`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 6 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8179]: Shall we sync the PR with master and rerun the build also?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 9]
```diff
@@ -771,6 +771,97 @@ public function testNestedMemberAccessOnIntersectionTypes() {
...
+    string name;
+|};
+
+const LENGTH = 10;
+
+function testMemberAccessWithBinaryExprAsIndex() {
+    int x = 8;
+    int[3] intArr = [0, 1, 2];
+    int member1 = intArr[10 - 9];
+    assertEquality(1,member1);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:784]:
```suggestion
    assertEquality(1, member1);
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 10]
```diff
@@ -771,6 +771,97 @@ public function testNestedMemberAccessOnIntersectionTypes() {
...
+    assertEquality("Ballerina", member3);
+    
+    map<int> mapVar = {field1: 202};
+    int? member4 = mapVar[("field1")];
+    assertEquality(202, member4);
+}
+
+function testMemberAccessOutOfRangeWithBinaryExpr() {
+    int[3] intArr = [0, 1, 2];
+    int|error a = trap intArr[2 + 1];
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:847]: These may result in compilation errors when we introduce https://github.com/ballerina-platform/ballerina-lang/issues/33090, Shall we update the test with that change in mind?

**Review by MaryamZi — APPROVED** [review]
