### PR TITLE
[Testerina] Fix incorrect coverage for multi module projects

### LINKED ISSUE #28680: Testerina produces incorrect coverage for multimodule projects
**Description:**

In multimodule projects, both testable jar and the normal jar have to be taken into account when generating the coverage report. The current implementation only considers the testable jar when generating the coverage. 

_Current Implementation:_
For each module, we get the jars in the execution classpath which will contain the testable jar of the current module along with the normal jars of dependencies and there is a condition [[1](https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java#L170)] to write coverage of only the current module. 

_Required improvement:_
We should remove this condition and add the coverage information of other modules as well. We could create a <Module, ModuleCoverage> map in RunTestsTask and pass it on to CoverageReport to update the coverages

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java#L170

### PR DESCRIPTION
**Pull request by Dilhasha**
## Purpose
Fix incorrect coverage for multi module projects
Fixes #28680

## Approach
Aggregate coverage information from all modules

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java [hunk 1]
```diff
@@ -165,30 +165,60 @@ private void createReport(final IBundleCoverage bundleCoverage, ModuleCoverage m
...
-                        List<Integer> missedLines = new ArrayList<>();
-
-                        for (int i = sourceFileCoverage.getFirstLine(); i <= sourceFileCoverage.getLastLine(); i++) {
-                            ILine line = sourceFileCoverage.getLine(i);
-                            if (line.getStatus() == NOT_COVERED) {
-                                missedLines.add(i);
-                            } else if (line.getStatus() == PARTLY_COVERED || line.getStatus() == FULLY_COVERED) {
-                                coveredLines.add(i);
+                        if (moduleCoverage.containsSourceFile(sourceFileCoverage.getName())) {
+                            //Update coverage for missed lines if covered
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java:178]:
```suggestion
                            // Update coverage for missed lines if covered
```

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java [hunk 2]
```diff
@@ -165,30 +165,60 @@ private void createReport(final IBundleCoverage bundleCoverage, ModuleCoverage m
...
+                            List<Integer> missedLines = moduleCoverage.getMissedLinesList(
+                                    sourceFileCoverage.getName());
+                            List<Integer> coveredLines =
+                                    moduleCoverage.getCoveredLinesList(
+                                            sourceFileCoverage.getName());
+                            List<Integer> existingMissedLines = new ArrayList<>(missedLines);
+                            if (coveredLines != null && missedLines != null) {
+                                boolean isCoverageUpdated = false;
+                                for (int missedLine : existingMissedLines) {
+                                    ILine line = sourceFileCoverage.getLine(missedLine);
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java:188]: Shall we explain with a comment on what is done here?

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java [hunk 3]
```diff
@@ -165,30 +165,60 @@ private void createReport(final IBundleCoverage bundleCoverage, ModuleCoverage m
...
+                                    }
+                                }
                             }
-                        }
-                        Document document = null;
-                        for (DocumentId documentId : module.documentIds()) {
-                            if (module.document(documentId).name().equals(sourceFileCoverage.getName())) {
-                                document = module.document(documentId);
+                        } else {
+                            //Calculate coverage for new source file
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java:203]:
```suggestion
                            // Calculate coverage for new source file
```

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java [hunk 4]
```diff
@@ -208,4 +238,23 @@ private void createReport(final IBundleCoverage bundleCoverage, ModuleCoverage m
...
+     *
+     * @param sourceFileName String
+     * @return Document
+     */
+    private Document getDocument(String sourceFileName) {
+        Document document = null;
+        for (Module moduleInstance : module.packageInstance().modules()) {
+            for (DocumentId documentId : moduleInstance.documentIds()) {
+                if (moduleInstance.document(documentId).name().equals(sourceFileName)) {
+                    document = moduleInstance.document(documentId);
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java:253]: We can break the loop once the document is found

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/ModuleCoverage.java [hunk 5]
```diff
@@ -76,6 +115,37 @@ public String getName() {
...
+     * @param sourceFileName String
+     * @return list of missed lines
+     */
+    public List<Integer> getMissedLinesList(String sourceFileName) {
+        for (SourceFile sourceFile : this.sourceFiles) {
+            if (sourceFile.getName().equals(sourceFileName)) {
+                return sourceFile.missedLines;
+            }
+        }
+        return null;
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/ModuleCoverage.java:130]: Shall we return an optional instead of null?

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/ModuleCoverage.java [hunk 6]
```diff
@@ -76,6 +115,37 @@ public String getName() {
...
+     * @param sourceFileName String
+     * @return list of covered lines
+     */
+    public List<Integer> getCoveredLinesList(String sourceFileName) {
+        for (SourceFile sourceFile : this.sourceFiles) {
+            if (sourceFile.getName().equals(sourceFileName)) {
+                return sourceFile.coveredLines;
+            }
+        }
+        return null;
```
Comment (azinneera) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/ModuleCoverage.java:145]: Shall we return an optional instead of null?

**Review by azinneera — APPROVED** [review]
