### PR TITLE
[Formatter] Fix and enable formatting test scenarios 

### LINKED ISSUE #25372: [Formatter] Fix and enable all the formatting test scenarios
**Description:**
All the test scenarios in the new formatter implementation have to be verified with the Ballerina specification and fixed there are any formatting issues. The tests in the formatter test suite should then be enabled.

Test Suite - https://docs.google.com/document/d/1dQ1Z_fNHgrdGqp5Nkf2aBar97kjlo2kjIf71O34u6j0/edit?usp=sharing

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
Sub Task: https://github.com/ballerina-platform/ballerina-lang/issues/25347

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by IrushiL**
## Purpose
Enables formatting test scenarios and refactors the code implementation.

Fixes #25372 

## Check List 
- [X] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 1]
```diff
@@ -0,0 +1,230 @@
...
+            return parent;
+        } else if (parentKind == SyntaxKind.FUNCTION_DEFINITION ||
+                parentKind == SyntaxKind.IF_ELSE_STATEMENT ||
+                parentKind == SyntaxKind.ELSE_BLOCK ||
+                parentKind == SyntaxKind.WHILE_STATEMENT ||
+                parentKind == SyntaxKind.CONST_DECLARATION ||
+                parentKind == SyntaxKind.METHOD_DECLARATION ||
+                parentKind == SyntaxKind.TYPE_DEFINITION) {
+            return parent;
+        } else if (syntaxKind == SyntaxKind.SIMPLE_NAME_REFERENCE) {
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:79]: We could use a switch-case in-place of the if-else. It can nicely handle these multiple matches as well.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 2]
```diff
@@ -0,0 +1,230 @@
...
+
+    // TODO: Use a generic way to get the parent node using querying.
+    static <T extends Node> Node getParent(T node, SyntaxKind syntaxKind) {
+        Node parent = node.parent();
+        if (parent == null) {
+            parent = node;
+        }
+        SyntaxKind parentKind = parent.kind();
+        if (parentKind == SyntaxKind.MODULE_VAR_DECL) {
+            if (parent.parent() != null && parent.parent().kind() == SyntaxKind.MODULE_PART &&
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:66]: since `parent.parent()` is used multiple times within the function, we can extract it to a variable

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 3]
```diff
@@ -0,0 +1,230 @@
...
+     */
+    static DiagnosticPos getPosition(Node node) {
+        if (node == null) {
+            return null;
+        }
+        LineRange range = node.lineRange();
+        LinePosition startPos = range.startLine();
+        LinePosition endPos = range.endLine();
+        int startOffset = startPos.offset();
+        if (node.kind().equals(SyntaxKind.FUNCTION_DEFINITION) || node.kind().equals(SyntaxKind.TYPE_DEFINITION) ||
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:50]: Shall we we use `==` instead of `.equals()`?
Lets fix in all places.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 4]
```diff
@@ -0,0 +1,230 @@
...
+            return null;
+        }
+    }
+
+    static int getIndentation(Node node, int indentation, FormattingOptions formattingOptions) {
+        if (node == null) {
+            return indentation;
+        }
+        if (node.parent() != null && (node.parent().kind().equals(SyntaxKind.BLOCK_STATEMENT) ||
+                node.parent().kind().equals(SyntaxKind.FUNCTION_BODY_BLOCK) ||
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:123]: can extract `node.parent().kind()` to a variable

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 5]
```diff
@@ -913,10 +972,17 @@ public MetadataNode transform(MetadataNode metadataNode) {
...
-        if (!isInLineRange(blockStatementNode)) {
+        if (!isInLineRange(blockStatementNode, lineRange)) {
             return blockStatementNode;
         }
-        int startColumn = getStartColumn(blockStatementNode, blockStatementNode.kind(), false);
+        boolean addSpaces = false;
+        if (blockStatementNode.parent().kind().equals(SyntaxKind.NAMED_WORKER_DECLARATION) ||
+                blockStatementNode.parent().kind().equals(SyntaxKind.QUERY_ACTION) ||
+                blockStatementNode.parent().kind().equals(SyntaxKind.FOREACH_STATEMENT) ||
+                blockStatementNode.parent().kind().equals(SyntaxKind.FUNCTION_BODY_BLOCK)) {
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:982]: extract ` blockStatementNode.parent().kind()` to a variable

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 6]
```diff
@@ -1437,18 +1636,29 @@ public ByteArrayLiteralNode transform(ByteArrayLiteralNode byteArrayLiteralNode)
 
     @Override
     public ListConstructorExpressionNode transform(ListConstructorExpressionNode listConstructorExpressionNode) {
+        if (!isInLineRange(listConstructorExpressionNode, lineRange)) {
+            return listConstructorExpressionNode;
+        }
+        int newLines = 0;
+        if (listConstructorExpressionNode.children().get(1).kind().equals(SyntaxKind.MAPPING_CONSTRUCTOR)) {
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:1643]: Whats the node we are getting here by `listConstructorExpressionNode.children().get(1)`?

Can we use the specific method in `ListConstructorExpressionNode` class?

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java [hunk 7]
```diff
@@ -0,0 +1,116 @@
...
+                ((parent.kind().equals(SyntaxKind.TYPED_BINDING_PATTERN) &&
+                        grandParent.kind().equals(SyntaxKind.FOREACH_STATEMENT)) ||
+                (parent.kind().equals(SyntaxKind.UNION_TYPE_DESC) &&
+                        grandParent.kind().equals(SyntaxKind.PARAMETERIZED_TYPE_DESC)) ||
+                (parent.kind().equals(SyntaxKind.OBJECT_FIELD) &&
+                        ((ObjectFieldNode) parent).visibilityQualifier().isPresent()) ||
+                (grandParent.kind().equals(SyntaxKind.LOCAL_VAR_DECL) &&
+                        grandParent.children().get(1).equals(parent)) ||
+                grandParent.kind().equals(SyntaxKind.FROM_CLAUSE) ||
+                grandParent.kind().equals(SyntaxKind.PARAMETERIZED_TYPE_DESC)))) {
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java:74]: Condition of this is-block is a tad too big. Let's extract it to a separate function.

We can simply do: `addSpaces = newlyAddedFunction();`

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java [hunk 8]
```diff
@@ -0,0 +1,116 @@
...
+                        SyntaxKind.FIELD_ACCESS,
+                        SyntaxKind.RECORD_FIELD_WITH_DEFAULT_VALUE,
+                        SyntaxKind.OPTIONAL_TYPE_DESC,
+                        SyntaxKind.ARRAY_TYPE_DESC));
+        if (parent != null && ((parentNodes.contains(parent.kind())) || grandParent != null &&
+                ((parent.kind().equals(SyntaxKind.INDEXED_EXPRESSION) &&
+                        grandParent.kind().equals(SyntaxKind.ASSIGNMENT_STATEMENT)) ||
+                ((parent.kind().equals(SyntaxKind.ASYNC_SEND_ACTION) ||
+                parent.kind().equals(SyntaxKind.ASSIGNMENT_STATEMENT)) &&
+                        parent.children().get(0).equals(node))))) {
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java:98]: Same as above

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java [hunk 9]
```diff
@@ -0,0 +1,116 @@
...
+
+    private void setNodeMetrics() {
+        if (node instanceof BuiltinSimpleNameReferenceNode) {
+            handleBuiltinSimpleNameReferenceNode();
+        }
+    }
+
+    boolean handleBuiltinSimpleNameReferenceNode() {
+        boolean addSpaces = true;
+        ArrayList<SyntaxKind> parentNodes = new ArrayList<>(
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java:56]: Do we need the outer wrapper `new ArrayList<>()`? I think `Arrays.asList()` returns an array-list

**Comment by SupunS** [comment]
Suggestions I added are all related to code cleanups.
So +1 to merge this PR, and fix those in a separate pr.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java (hunk 9 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java]: Fixed.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java (hunk 2 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java]: Fixed.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java (hunk 3 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java]: Done.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java (hunk 4 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java]: Done.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 5 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java]: Fixed.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java (hunk 1 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java]: Planning on refactoring and simplifying the logic separately in a different PR.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java (hunk 8 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java]: Planning on refactoring and simplifying the logic separately in a different PR.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java (hunk 7 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeFormattingMetrics.java]: Thanks for the input, planning on refactoring and simplifying the logic separately in a different PR.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java (hunk 6 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java]: The expected node here is a `MappingConstructorExpressionNode`.

`ListConstructorExpressionNode` class returns a `SeparatedNodeList` as the set of expressions, so both ways would result in a similar code implementation AFAIU, but I will check on as to whether this could be improved.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 10]
```diff
@@ -0,0 +1,415 @@
...
+        if (node.kind() == (SyntaxKind.FUNCTION_DEFINITION) || node.kind() == (SyntaxKind.TYPE_DEFINITION) ||
+                node.kind() == (SyntaxKind.CONST_DECLARATION) || node.kind() == (SyntaxKind.OBJECT_TYPE_DESC)) {
+            startOffset = (startOffset / 4) * 4;
+        }
+        return new DiagnosticPos(null, startPos.line() + 1, endPos.line() + 1,
+                startOffset, endPos.offset());
+    }
+
+    // TODO: Use a generic way to get the parent node using querying.
+    static <T extends Node> Node getParent(T node, SyntaxKind syntaxKind) {
```
Comment (nadeeshaan) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:68]: Instead of returning a possibly null node, shall we use Optional here?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 11]
```diff
@@ -0,0 +1,415 @@
...
+        }
+        return preserve;
+    }
+
+    private static ArrayList<NonTerminalNode> nestedIfBlock(NonTerminalNode node) {
+        NonTerminalNode parent = node.parent();
+        ArrayList<NonTerminalNode> nestedParent = new ArrayList<>();
+        if (parent == null) {
+            return new ArrayList<>(0);
+        } else {
```
[the remark this answers is not in the document]
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:311]: Fixed.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 12]
```diff
@@ -0,0 +1,415 @@
...
+        return token.modify(newLeadingMinutiaeList, newTrailingMinutiaeList);
+    }
+
+    private static MinutiaeList modifyMinutiaeList(int spaces, int newLines) {
+        Minutiae minutiae = createWhitespaceMinutiae(getWhiteSpaces(spaces, newLines));
+        return createMinutiaeList(minutiae);
+    }
+
+    private static int getChildLocation(NonTerminalNode parent, Node child) {
+        if (parent != null && child != null) {
```
[the remark this answers is not in the document]
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:246]: Done.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 13]
```diff
@@ -0,0 +1,415 @@
...
+
+import static io.ballerinalang.compiler.syntax.tree.AbstractNodeFactory.createMinutiaeList;
+import static io.ballerinalang.compiler.syntax.tree.AbstractNodeFactory.createWhitespaceMinutiae;
+
+/**
+ * Class that contains the util functions used by the formatting tree modifier.
+ */
+class FormatterUtils {
+
+    private static final String LINE_SEPARATOR = "line.separator";
```
[the remark this answers is not in the document]
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:43]: Done

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeIndentation.java [hunk 14]
```diff
@@ -0,0 +1,128 @@
...
+    }
+
+    static int builtinSimpleNameReferenceNode(Node node, FormattingOptions options) {
+        NonTerminalNode parent = node.parent();
+        NonTerminalNode grandParent = null;
+        if (parent != null) {
+            grandParent = parent.parent();
+        }
+        boolean addSpaces = true;
+        List parentNodes = Arrays.asList(
```
[the remark this answers is not in the document]
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/NodeIndentation.java:45]: Not really, added the parameter.

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 15]
```diff
@@ -0,0 +1,415 @@
...
+                Arrays.asList(
+                        SyntaxKind.WHILE_STATEMENT,
+                        SyntaxKind.FUNCTION_DEFINITION));
+        ArrayList<SyntaxKind> parentWithoutSpaces = new ArrayList<>(
+                Arrays.asList(
+                        SyntaxKind.NAMED_WORKER_DECLARATION,
+                        SyntaxKind.LOCAL_VAR_DECL,
+                        SyntaxKind.FOREACH_STATEMENT));
+
+        if (parentWithSpaces.contains(parent.kind())) {
```
[the remark this answers is not in the document]
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:380]: Done

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 16]
```diff
@@ -0,0 +1,415 @@
...
+            return new ArrayList<>(0);
+        } else {
+            while (parent != null) {
+                if (parent.kind() == (node.kind())) {
+                    nestedParent.add(parent);
+                }
+                parent = parent.parent();
+            }
+        }
+        return nestedParent.isEmpty() ? null : nestedParent;
```
[the remark this answers is not in the document]
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:319]: Done

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 17]
```diff
@@ -0,0 +1,415 @@
...
+
+    // TODO: Use a generic way to get the parent node using querying.
+    static <T extends Node> Node getParent(T node, SyntaxKind syntaxKind) {
+        Node parent = node.parent();
+        if (parent == null) {
+            parent = node;
+        }
+        Node grandParent = parent.parent();
+        SyntaxKind parentKind = parent.kind();
+        if (parentKind == (SyntaxKind.MODULE_VAR_DECL)) {
```
[the remark this answers is not in the document]
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:75]: Fixed

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java [hunk 18]
```diff
@@ -0,0 +1,415 @@
...
+     * @param leadingSpaces    leading spaces
+     * @param trailingSpaces   trailing spaces
+     * @param leadingNewLines  leading new lines
+     * @param trailingNewLines trailing new lines
+     * @return updated token
+     */
+    static Token formatToken(Token token, int leadingSpaces, int trailingSpaces, int leadingNewLines,
+                             int trailingNewLines) {
+        if (token == null) {
+            return token;
```
[the remark this answers is not in the document]
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:245]: Here the intended behavior is to return the token itself if the token value sent for the `formatToken` method is null. Since we can't really replace a null token with a different value, is there a benefit of wrapping it around an Optional?

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java (hunk 10 above)
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:72]: Since this method is called recursively to find the effective parent node for indentation, converting its return type to optional seems to clutter the code without much of a benefit IMO, or is there something that I might be missing here?

A null return value is expected in a case where a node has no parent. Here, there won't be an addition of columns to the existing indentation.

**Review by SupunS — APPROVED** [review]

**Review by nadeeshaan — APPROVED** [review]

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java (hunk 18 above)
[the remark this answers is not in the document]
Comment (nadeeshaan) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:245]: When we wrapping inside an Optional, particular API usage has to explicitly check for the isPresent. Otherwise there is a chance we are missing the null check and run into NPEs.

[the remark this answers is not in the document]
Comment (IrushiL) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormatterUtils.java:245]: I see. I will incorporate this in the refactoring PR.
