### PR TITLE
Fix create variable with type code action

### LINKED ISSUE #39270: [Bug]:Create variable code action adds Invalid text edits
### Description

Consider the following capture 
createvar

### Steps to Reproduce

```Ballerina
import ballerina/http;
import ballerinax/mongodb;

configurable string password = ?;
configurable string database = ?;
configurable string username = ?;

mongodb:ConnectionConfig mongoConfig = {
    connection: {
        host: "localhost",
        auth: {
            username: username,
            password: password
        },
        options: {
            sslEnabled: false,
            serverSelectionTimeout: 15000
        }
    },
    databaseName: database
};

mongodb:Client mongo = check new (mongoConfig);

type Joureny record {|
    string 'start;
    string end;
    decimal cost;
    int days;
    int numOfPeople;
|};

service /journey on new http:Listener(9090) {
    resource function get .() returns Joureny {
        stream<rowType, error?>|mongodb:DatabaseError|mongodb:ApplicationError|ballerina/lang.annotations:0.0.0: find = mongo->find("journeys", database, limit = 1);
    }
}

```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by mindula**
Fixes #39270 

## Samples
https://user-images.githubusercontent.com/61020198/213923648-9c08ecef-f64a-4302-bf9a-3e7b0896f622.mov

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableWithTypeCodeAction.java [hunk 1]
```diff
@@ -224,16 +224,21 @@ private String getTypeName(TypeSymbol symbol, CodeActionContext context) {
         Optional<ModuleSymbol> module = symbol.getModule();
         if (module.isPresent()) {
             String fqPrefix = "";
-            if (!(ProjectConstants.ANON_ORG.equals(module.get().id().orgName()))) {
-                ModuleID id = module.get().id();
+            ModuleID id = module.get().id();
+            if (!(ProjectConstants.ANON_ORG.equals(id.orgName())) && !isLangAnnotationModule(id)) {
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableWithTypeCodeAction.java:228]:
```suggestion
            if (!ProjectConstants.ANON_ORG.equals(id.orgName()) && !isLangAnnotationModule(id)) {
```
Shall we remove the additional brackets?

**Review by IMS94 — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableWithTypeCodeAction.java (hunk 1 above)
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableWithTypeCodeAction.java]: Done

**Review by IMS94 — APPROVED** [review]

**Review by IMS94 — APPROVED** [review]
