### PR TITLE
Fix sorting in fail statement

### LINKED ISSUE #34731: Improve sorting in fail statement
**Description:**

In the fail statement we can only have expressions, which are subtype of error. So we can prfioritize error type variables, functions which returns error type. Please check whether we can give a priority to `error` keyword and `error constructor` as well. 

```
import ballerina/io;

public function main() {
    int a = 1;
    error b = error("test error");
    do {
        fail <cur>;
    } on fail var e {
    	io:println(e);
    }
}
```

### PR DESCRIPTION
**Pull request by gayalkuruppu**
Fixes #34731 

## Samples
Screenshot from 2022-02-07 19-14-43

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java [hunk 1]
```diff
@@ -57,4 +68,63 @@ public FailStatementNodeContext() {
...
+                lsCItem.getCompletionItem().setSortText(SortingUtil.genSortText(2));
+            } else {
+                int rank = SortingUtil.toRank(context, lsCItem);
+                lsCItem.getCompletionItem().setSortText(SortingUtil.genSortText(rank));
+            }
+
+        }
+    }
+
+    private boolean isUnionSymbolSubtypeError(UnionTypeSymbol unionTypeSymbol) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java:94]: shall we rename this to `isUnionOfErrors`?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java [hunk 2]
```diff
@@ -57,4 +67,67 @@ public FailStatementNodeContext() {
...
         return completionItems;
     }
+
+    @Override
+    public void sort(BallerinaCompletionContext context, FailStatementNode node,
+                     List<LSCompletionItem> completionItems) {
+        for (LSCompletionItem lsCItem : completionItems) {
+            if (lsCItem.getType() == LSCompletionItem.CompletionItemType.SYMBOL) {
+                SymbolCompletionItem symbolCompletionItem = (SymbolCompletionItem) lsCItem;
+                if (isCompletionItemSubTypeOfError(symbolCompletionItem)) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java:77]: If we merge this condition with line 75, the else clause would drop to the outermost else, right? What if we do that since we set priority 3 in both cases?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java [hunk 3]
```diff
@@ -57,4 +67,67 @@ public FailStatementNodeContext() {
...
+        return rawType.typeKind() == TypeDescKind.ERROR;
+    }
+    
+    private boolean isCompletionItemSubTypeOfError(SymbolCompletionItem symbolCompletionItem) {
+        Optional<Symbol> symbol = symbolCompletionItem.getSymbol();
+        if (symbol.isEmpty()) {
+            return false;
+        }
+        Optional<TypeSymbol> tSymbol = SymbolUtil.getTypeDescriptor(symbol.get());
+        if (symbol.get().kind() == SymbolKind.TYPE_DEFINITION) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java:115]: Merge this with line 111

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java [hunk 4]
```diff
@@ -57,4 +67,67 @@ public FailStatementNodeContext() {
...
+            return false;
+        }
+
+        if (tSymbol.isPresent()) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java:119]: Use early return here

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java [hunk 5]
```diff
@@ -57,4 +67,67 @@ public FailStatementNodeContext() {
...
+            TypeSymbol typeSymbol = CommonUtil.getRawType(tSymbol.get());
+            if (typeSymbol.typeKind() == TypeDescKind.ERROR) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java:121]: After having an early return, change the order of the if-clauses. Get union and function check first and at the else clause we can use `return typeSymbol.typeKind() == TypeDescKind.ERROR`. WDYT?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java (hunk 5 above)
Comment (gayalkuruppu) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java:121]: Agree +1

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java (hunk 2 above)
Comment (gayalkuruppu) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FailStatementNodeContext.java:77]: +1

**Review by nadeeshaan — APPROVED** [review]
LGTM

**Comment by mohanvive** [comment]
@gayalkuruppu Shall we send this to patch branch (not required for the master)

**Review by mohanvive — APPROVED** [review]
