### PR TITLE
Fix Issue #14476

### LINKED ISSUE #14476: Language Server diff based source alteration do not honour existing new lines
**Description:**
Language Server diff based source alteration do not honour existing new lines

### PR DESCRIPTION
**Pull request by nadeeshaan**

### CODE REVIEW

File: language-server/modules/langserver-compiler/src/test/java/org/ballerinalang/langserver/compiler/workspace/WorkspaceDocumentContentUpdateTest.java [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+        documentManager.clearAllFilePaths();
+    }
+
+    @Test(description = "Test the document range updating")
+    public void testDocumentRangeUpdate() throws IOException, WorkspaceDocumentException {
+        Path sourcePath1 = RES_DIR.resolve("source").resolve("docUpdateSource1.bal");
+        Path sourcePath2 = RES_DIR.resolve("source").resolve("docUpdateSource2.bal");
+        Path sourcePath3 = RES_DIR.resolve("source").resolve("docUpdateSource3.bal");
+        Path expected1Path = RES_DIR.resolve("expected").resolve("expected1.bal");
+        Path expected2Path = RES_DIR.resolve("expected").resolve("expected2.bal");
```
Comment (NipunaMarcus) [inline language-server/modules/langserver-compiler/src/test/java/org/ballerinalang/langserver/compiler/workspace/WorkspaceDocumentContentUpdateTest.java]: can we these type of expected data to a data provider and then use a common logic to assert them ... ??

Comment (nadeeshaan) [reply language-server/modules/langserver-compiler/src/test/java/org/ballerinalang/langserver/compiler/workspace/WorkspaceDocumentContentUpdateTest.java]: @NipunaMarcus yes, There is a separate PR for optimizing the test with several other fixes.
