### PR TITLE
Fix object type inclusion

### LINKED ISSUE #26969: Fix inclusion with readonly classes
**Description:**
See https://github.com/ballerina-platform/ballerina-spec/issues/649#issuecomment-728617706

### LINKED ISSUE #27224: Inclusion of object type descriptor with qualifiers
Spec issue to capture https://github.com/ballerina-platform/ballerina-spec/issues/650

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$title.

This PR fixes

- Inclusion of object type descriptor with qualifiers

When object type inclusion is used with an object type descriptor with qualifiers (`isolated`, `client`, and/or `service`), it is now mandatory for the referencing object to also have these qualifiers.

Fixes #27224

- Fix inclusion with readonly classes

  - Object type descriptors can no longer use object type inclusion with `readonly` classes
  - Classes can use object type inclusion with `readonly` classes only if the referencing classes themselves are `readonly`
  - The type reference in an object constructor expression can refer to a `readonly` class only if the object being constructed is `readonly`

Fixes #26969

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by dulajdilshan — DISMISSED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -2978,11 +2979,16 @@ public void visit(BLangTypeInit cIExpr) {
                 if (isObjectConstructorExpr(cIExpr, actualObjectType)) {
                     BLangClassDefinition classDefForConstructor = getClassDefinitionForObjectConstructorExpr(cIExpr,
                                                                                                              env);
+                    List<BLangType> typeRefs = classDefForConstructor.typeRefs;
 
                     SymbolEnv pkgEnv = symTable.pkgEnvMap.get(env.enclPkg.symbol);
 
                     if (Symbols.isFlagOn(expType.flags, Flags.READONLY)) {
-                        handleObjectConstrExprForReadOnlyCET(cIExpr, actualObjectType, classDefForConstructor, pkgEnv);
+                        handleObjectConstrExprForReadOnly(cIExpr, actualObjectType, classDefForConstructor, pkgEnv,
```
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2987]: But then we'll have to repeat at least one check, right?

[the remark this answers is not in the document]
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2987]: Yes, let's keep this.

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 2]
```diff
@@ -1628,3 +1628,15 @@ error.invalid.isolated.qualifier.on.module.no.init.var.decl=\
...
 error.binding.pattern.not.yet.supported.in.module.var.decl=\
   ''{0}'' binding pattern not yet supported in module variable declaration
+
+error.invalid.read.only.class.inclusion.in.object.type.descriptor=\
+  object type inclusion cannot be used with a ''readonly class'' in an object type descriptor
+
+error.invalid.inclusion.with.mismatched.qualifiers=\
+  invalid object type inclusion: missing ''{0}'' qualifier(s) in the referencing object
+
+error.invalid.read.only.class.inclusion.in.non.read.only.class=\
```
Comment (KRVPerera) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:1638]: In `object constructor` type-reference is implemented as a type inclusion. This may be confusing in some scenarios if the error refers to it as "type inclusion".

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1638]: This error will only be logged for user-defined classes, not for object constructor expressions.

In an object constructor expression, if the type reference is a `readonly class`, the rules that apply are somewhat the same as those within a `readonly class`.

e.g.,

The fields become final and the types becomes the types with their read-only bit set.
```ballerina
readonly class Foo {
    int i;

    function init(int i) {
        self.i = i;
    }
}

public function main() {
    object { } x =  object Foo { 
        int i = 1;
        map<string> m = mp; // `mp` should be a subtype of `map<string> & readonly`
    }; 
}
```

If the type reference is a read-only class, the object constructor's fields have to be `readonly` compatible.
```ballerina
readonly class Foo {
    int i;

    function init(int i) {
        self.i = i;
    }
}

public function main() {
    object { } x =  object Foo { 
        int i = 1;
        stream<int> str; // can never be a subtype of `readonly`

        function init() {
            int[] arr = [1, 2, 3, 4];
            self.str = arr.toStream();
        }
    }; 
}
```
The error logged here will be "invalid field in an object constructor expression with a 'readonly' reference: 'stream<int>' can never be 'readonly'"

Spec discussion - https://github.com/ballerina-platform/ballerina-spec/issues/649

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2987]: yes. Lets not change.

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 2 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1638]: Sorry for not being clear. Check this example.
```
isolated class Foo {
    int i;

    function init(int i) {
        self.i = i;
    }
}

public function main() {
    object { } x =  object Foo { 
        int i = 1;
    }; 
}
```

```LogTalk
ERROR [t14.bal:(10:28,10:31)] invalid object type inclusion: missing 'isolated' qualifier(s) in the referencing object
```

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/resources/compiler.properties:1641]: Introduced a separate error for object constructor expressions in d057072.

**Review by KRVPerera — APPROVED** [review]
