### PR TITLE
Handle typeParam when parameter type is not availabe in function

### LINKED ISSUE #34694: Getting `table<$UndefinedType$>` as  the type when executing "change variable code action"
**Description:**
$title

**Steps to reproduce:**
Try executing the *change variable type* code action for the following code (On the line 
```ballerina
type DataRecord record {|
    string date;
    string state;
    int death;
    int positive;
|};

type DataRow record {|
    time:Utc dateTime;
    string state;
    int death;
    int positive;
|};

function sortTable(table<DataRecord> a) returns table<DataRow> {
    table<DataRow> aa = a.map(function(drecord) returns DataRow {
        return {
            dateTime: [0, 0],
            death: 0,
            positive: 0,
            state: ""
        };
    });
}
```
Screenshot from 2022-01-18 12-06-23
Screenshot from 2022-01-18 12-08-30

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake) Snapshot build 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose

Fixes #34694

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java [hunk 1]
```diff
@@ -408,6 +421,12 @@ private void visitType(Location loc, BType expType, BType actualType, SymbolEnv
                     findTypeParamInInvokableType(loc, (BInvokableType) expType, (BInvokableType) actualType, env,
                             resolvedTypes, result);
                 }
+                if (actualType.tag == TypeTags.SEMANTIC_ERROR) {
+                    if (expr != null && expr.getKind() == NodeKind.LAMBDA) {
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java:425]: Can we merge these two` if`'s to one?

File: langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal [hunk 2]
```diff
@@ -137,3 +137,35 @@ function testStringIntFloatSimpleAndArrayUnionReturnParameterNarrowing() {
...
+type DataRecord record {|
+    string name;
+|};
+
+type DataRow record {|
+    string name;
+|};
+
+function foo(table<DataRecord> a) returns table<DataRow> {
+    table<DataRow> aa = a.map(function(dRecord) returns DataRow {
```
Comment (gimantha) [inline langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal:150]: Shall we add similar tests for langlib functions with one typeparam as well?

Comment (KavinduZoysa) [reply langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal]: Added more tests

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java (hunk 1 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java:425]: Yes, we can, but I think, having it like this will be more readable. It is something like,
```ballerina
if (actualType.tag == TypeTags.SEMANTIC_ERROR) { // type-tag check
        // do something
}
```
WDYT?

**Review by MaryamZi — CHANGES_REQUESTED** [review]
With this change, for something like 

```ballerina
type DataRecord record {|
    string state;
    int death;
    int positive;
|};

type DataRow record {|
    string state;
    int positive;
|};

function sortTable(table<DataRecord> a) {
    table<DataRow> aa = a.map(function(drecord) returns DataRow {
        return {
            positive: 0,
            state: ""
        };
    });
}
```

the difference is that we no longer log

```cmd
incompatible types: expected 'table<DataRow>', found 'table<other> key<never>'
```

Is this what we discussed? IIRC, we discussed looking into the possibility of the RHS type being `table<DataRow>` since we can compute that based on the return type.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java:425]: They both read pretty much the same though?

**Comment by KavinduZoysa** [comment]
> With this change, for something like
> 
> ```ballerina
> type DataRecord record {|
>     string state;
>     int death;
>     int positive;
> |};
> 
> type DataRow record {|
>     string state;
>     int positive;
> |};
> 
> function sortTable(table<DataRecord> a) {
>     table<DataRow> aa = a.map(function(drecord) returns DataRow {
>         return {
>             positive: 0,
>             state: ""
>         };
>     });
> }
> ```
> 
> the difference is that we no longer log
> 
> ```batchfile
> incompatible types: expected 'table<DataRow>', found 'table<other> key<never>'
> ```
> 
> Is this what we discussed? IIRC, we discussed looking into the possibility of the RHS type being `table<DataRow>` since we can compute that based on the return type.

@MaryamZi, this error is removed as we identify the rhs type correctly. Can you please check.

**Comment by chiranSachintha** [comment]
```ballerina
type DataRecord record {|
    string name;
|};

type DataRow record {|
    string name;
|};

function foo1(table<DataRecord> a) {
    table<DataRow> aa = a.map(function(dRecord) returns dRecord { 
        return {
            name: ""
        };
    });
}
```
If the return type is not defined still we are getting table<$UndefinedType$> as the type when executing code action. Is it correct?

**Comment by gimantha** [comment]
> ```ballerina
> type DataRecord record {|
>     string name;
> |};
> 
> type DataRow record {|
>     string name;
> |};
> 
> function foo1(table<DataRecord> a) {
>     table<DataRow> aa = a.map(function(dRecord) returns dRecord { 
>         return {
>             name: ""
>         };
>     });
> }
> ```
> 
> If the return type is not defined still we are getting table<$UndefinedType$> as the type when executing code action. Is it correct?

Are you talking about the return type of the lambda function as the argument right? if so, it has to be fixed.

**Comment by chiranSachintha** [comment]
> Are you talking about the return type of the lambda function as the argument right? if so, it has to be fixed.

Yes.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java [hunk 3]
```diff
@@ -408,6 +421,10 @@ private void visitType(Location loc, BType expType, BType actualType, SymbolEnv
                     findTypeParamInInvokableType(loc, (BInvokableType) expType, (BInvokableType) actualType, env,
                             resolvedTypes, result);
                 }
+                if (actualType.tag == TypeTags.SEMANTIC_ERROR && expr != null && expr.getKind() == NodeKind.LAMBDA) {
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java:424]: This can be null, please check 
https://github.com/ballerina-platform/ballerina-lang/pull/35460/files#diff-de9cff80105102f5b314d27f1c08c3a65f5034cc0b27e92999d9130bacb6d51cR292

**Comment by KavinduZoysa** [comment]
> ```ballerina
> type DataRecord record {|
>     string name;
> |};
> 
> type DataRow record {|
>     string name;
> |};
> 
> function foo1(table<DataRecord> a) {
>     table<DataRow> aa = a.map(function(dRecord) returns dRecord { 
>         return {
>             name: ""
>         };
>     });
> }
> ```
> 
> If the return type is not defined still we are getting table<$UndefinedType$> as the type when executing code action. Is it correct?

@gimantha, @chiranSachintha As you mentioned there is an issue we need to fix here. Since the return type is not available, we have to get the return type from lhs. But I think this cannot be done based on the current type param resolving logic. This may be a design change. Please check https://github.com/ballerina-platform/ballerina-lang/issues/35187

I think we have to ignore this for now. WDYT?

**Comment by MaryamZi** [comment]
> > ```ballerina
> > type DataRecord record {|
> >     string name;
> > |};
> > 
> > type DataRow record {|
> >     string name;
> > |};
> > 
> > function foo1(table<DataRecord> a) {
> >     table<DataRow> aa = a.map(function(dRecord) returns dRecord { 
> >         return {
> >             name: ""
> >         };
> >     });
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If the return type is not defined still we are getting table<$UndefinedType$> as the type when executing code action. Is it correct?
> 
> @gimantha, @chiranSachintha As you mentioned there is an issue we need to fix here. Since the return type is not available, we have to get the return type from lhs. But I think this cannot be done based on the current type param resolving logic. This may be a design change. Please check this similar issue #35187
> 
> I think we have to ignore this for now. WDYT?

What if we set semantic error as the type if the argument cannot be resolved properly? 

This would mean that in the original example, the type of the RHS won't even be resolved to a table, which IMO is OK and we won't need these special cases. The behaviour will be uniform for all error scenarios also. WDYT?

**Comment by MaryamZi** [comment]
Please also sync the PR with master, in case we are going ahead with this.

**Comment by KavinduZoysa** [comment]
> 

Currently, we are setting the semantic error for the places that cannot resolve type.
We are getting `table<$UndefinedType$>` because we cannot set the type. Therefore I think we have to properly set the type. Please check https://github.com/ballerina-platform/ballerina-lang/issues/35187

But as per your explanation, in order to be uniform with all error scenarios, I also feel that existing behavior is OK.

**Comment by KavinduZoysa** [comment]
> Please also sync the PR with master, in case we are going ahead with this.

Done

**Review by gimantha — DISMISSED** [review]

**Comment by gimantha** [comment]
BTW, with this PR, now the following code works

```ballerina
public function main() {
    EvenNumberGenerator evenGen = new();
    stream evenNumberStream = new(evenGen);
   // stream<int,error?> str = <stream<int,error?>>evenNumberStream;
}

class EvenNumberGenerator {
    int i = 0;
    public isolated function next() returns record {| int value; |}|error? {
        self.i += 2;
        return { value: self.i };
    }
}
```
But if I uncomment the commented line, it crashes at runtime

File: langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal [hunk 4]
```diff
@@ -137,3 +137,42 @@ function testStringIntFloatSimpleAndArrayUnionReturnParameterNarrowing() {
...
+
+public function foo2(int[] ia) {
+    int[] _ = ia.filter(function (x) returns boolean { // error
+        return x > 0; // error
+    });
+}
+
+function testAnonymousFunctionsWithMissingParameterType() {
+    _ = foo1(table []);
+    _ = foo2([1, 2, 3]);
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal:165]: Why do we need these?

Comment (KavinduZoysa) [reply langlib/langlib-test/src/test/resources/test-src/type-param/type_param_test_negative.bal]: Changed

**Comment by MaryamZi** [comment]
This is patch-compatible, right? Shall we send the PR to https://github.com/ballerina-platform/ballerina-lang/tree/2201.1.x?

**Comment by KavinduZoysa** [comment]
> This is patch-compatible, right? Shall we send the PR to https://github.com/ballerina-platform/ballerina-lang/tree/2201.1.x?

changed

**Review by MaryamZi — APPROVED** [review]
