### PR TITLE
Fix incorrect member types for union type definition

### LINKED ISSUE #32569: Incorrect member types for union type definition
**Description:**

Consider the scenario,

```
type t "0"|"1"|t1;
type t1 "a"|"b"|"c";
```
In `memberTypeDescriptors()`,  we get `"0|1"` as a union type.

Refer to https://github.com/ballerina-platform/ballerina-lang/pull/32540#discussion_r701611819

image

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #32569

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java [hunk 1]
```diff
@@ -70,7 +71,17 @@ public BallerinaUnionTypeSymbol(CompilerContext context, ModuleID moduleID, BFin
                 TypesFactory typesFactory = TypesFactory.getInstance(this.context);
 
                 for (BType memberType : ((BUnionType) this.getBType()).getMemberTypes()) {
-                    members.add(typesFactory.getTypeDescriptor(memberType));
+                    if (typesFactory.isTypeReference(memberType, memberType.tsymbol, false)
+                            || memberType.getKind() != TypeKind.FINITE) {
+                        members.add(typesFactory.getTypeDescriptor(memberType));
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java:76]: Why do we have to check whether it's a type ref? Isn't checking whether it's not a finite type isn't enough? 🤔

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java:76]: Let's say we have 
```ballerina
type T2 1|2|3;
type T4 "1"|"2"|T2;
```
If we get members of `T4` we get two `FiniteType`s (`T2` and `"1"|"2"|`). Therefore, we need to check whether `T2` is a type ref or not.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java [hunk 2]
```diff
@@ -70,7 +71,17 @@ public BallerinaUnionTypeSymbol(CompilerContext context, ModuleID moduleID, BFin
...
+                        continue;
+                    }
+
+                    BFiniteType finiteType = (BFiniteType) memberType;
+                    for (BLangExpression value : finiteType.getValueSpace()) {
+                        ModuleID moduleID = getModule().isPresent() ? getModule().get().id() : null;
+                        members.add(new BallerinaSingletonTypeSymbol(this.context, moduleID, value, value.getBType()));
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaUnionTypeSymbol.java:83]: Not sure this is the correct way to do this. Doesn't `value.getBType()` return the broader type of that expression? IINM, we'll have to create individual `BFiniteType` types here for each of the member values.

**Review by pubudu91 — APPROVED** [review]
