### PR TITLE
Fix scoping issue with type narrowed symbols for arrow expressions

### LINKED ISSUE #24956: Bad Sad Error Thrown When using Anonymous Functions
**Description:**
I got a bad sad error when I built [module-ballerinax-microsoft.sheets](https://github.com/miyurud/module-ballerinax-microsoft.sheets.git). This happens because of I started to use an anonymous function as an argument for a `log:printDebug()`statement. The log is shown below

``
[2020-07-27 13:12:47,207] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:155)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:387)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$5(BIROptimizer.java:117)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:117)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:346)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:94)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:94)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
	at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:74)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:249)
	at org.wso2.ballerinalang.compiler.CompilerDriver.birGen(CompilerDriver.java:354)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:301)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:68)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:433)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
``

**Steps to reproduce:**
Clone the repo [module-ballerinax-microsoft.sheets](https://github.com/miyurud/module-ballerinax-microsoft.sheets.git) and build it using the command `ballerina build -a -c --skip-tests=true`. Should use the code from this [commit](https://github.com/miyurud/module-ballerinax-microsoft.sheets/commit/e0eb57f5c00890e81f65495812b54bd28eb32730) which caused this bad sad error.

**Affected Versions:**
Ballerina Swan Lake Preview 2

**OS, DB, other environment details and versions:**
Ubuntu 18.04, JDK 1.8

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

### PR DESCRIPTION
**Pull request by Kishanthan**
## Purpose
Currently, in a type narrowing situation, the narrowed symbols are visible inside the scope of arrow function. However, for any lambda, it was deciede not to type narrow and use the original symbol as it it.

The follwing will now fail with compilation error.

```ballerina
function testArrowExpressionWithTypeNarrowing() {
    string|int s = "World";
    if (s is string) {
        // should fail operator '+' not defined for 'string' and '(string|int)'
        function() returns string a = () => "Hello " + s;
    }
}
```

This PR fixes the issue with arrow expresions. Lambda functions are working as expected.

Fixes #24956

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java [hunk 1]
```diff
@@ -181,8 +181,14 @@ public static SymbolEnv createResourceActionSymbolEnv(BLangInvokableNode node, S
...
 
     public static SymbolEnv createArrowFunctionSymbolEnv(BLangArrowFunction node, SymbolEnv env) {
-        SymbolEnv symbolEnv = new SymbolEnv(node, new Scope(env.scope.owner));
-        symbolEnv.enclEnv = env;
+        Scope scope = new Scope(env.scope.owner);
+        env.scope.entries.entrySet().stream()
+                // skip the type narrowed symbols when taking the snapshot for closures.
+                .filter(entry -> (entry.getValue().symbol.tag & SymTag.VARIABLE) != SymTag.VARIABLE ||
+                        ((BVarSymbol) entry.getValue().symbol).originalSymbol == null)
+                .forEach(entry -> scope.entries.put(entry.getKey(), entry.getValue()));
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java:189]: Should we try and extract this logic out to a separate method, since it seems to be used across multiple methods?

Comment (Kishanthan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java:189]: Yes, we should do it. Let me check.
