### PR TITLE
Fix multiline string support in config API

### LINKED ISSUE #13278: [Config-API] Multiple line support required
**Description:**
Following conf file resulted in a syntax error. Error resolved when string was presented in a single line. Seems like multiple line support is not available.
```
["b7a.websub"]

["b7a.websub.subscriber"]
token="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYWxs" +
      "iJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJigiurwgwufbofbfb"
```

### PR DESCRIPTION
**Pull request by pubudu91**

### CODE REVIEW

File: stdlib/config-api/src/test/java/org/ballerinalang/stdlib/config/ConfigTest.java [hunk 1]
```diff
@@ -318,6 +318,28 @@ public void testBackwardSlashInString() throws IOException {
...
+                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor " +
+                                    "incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis " +
+                                    "nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. " +
+                                    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu " +
+                                    "fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in " +
+                                    "culpa qui officia deserunt mollit anim id est laborum.");
+    }
+
+    @Test(description = "Test multiline config strings")
+    public void testMultilineConfigStrings2() throws IOException {
```
Comment (chamil321) [inline stdlib/config-api/src/test/java/org/ballerinalang/stdlib/config/ConfigTest.java]: Shall we add a meaningful name and a description? 
suggestion: testMultiSpacedConfigStrings
