### PR TITLE
Set eventual type for all expression types in wait-future-expr

### LINKED ISSUE #29844: Wait action should return an error (wait failure) if ask to wait on a completed future
**Description:**
$title.

Spec issue:https://github.com/ballerina-platform/ballerina-spec/issues/802

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by KRVPerera**
## Purpose

Fixes #29844

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -3786,15 +3793,14 @@ private boolean isReferencingNonWorker(BLangExpression expression) {
...
             String varRefSymbolName = varRefSymbol.getName().value;
             if (workerExists(env, varRefSymbolName)) {
-                return false;
+                return varRefSymbolName;
             }
-            nonWorkerReferenceName = varRefSymbolName;
-        } 
-        return true;
+        }
+        return "";
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3789]: what does empty string represent here?

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3789]: I will refactor the code. 
As of now if no worker is found for the name it will return "".

**Review by rdhananjaya — APPROVED** [review]
