### PR TITLE
On Fail error handler implementation

### LINKED ISSUE #25282: Improve type checking and add tests for handing failures with on-fail clause
$subject

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #25282

## Samples
```ballerina
do {
   check foo();
   check bar();
}
on fail var e {
   // this will be executed if the block-stmt following do fails
   // which will happen if and only if one of the two
   // check actions fails
   // type of e will be union of the error types that can be
   // returned by foo and bar
   io:println("whoops");
   return e;
}

```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by gimantha — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/statements/DoNode.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+ *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ *  KIND, either express or implied.  See the License for the
+ *  specific language governing permissions and limitations
+ *  under the License.
+ */
+package org.ballerinalang.model.tree.statements;
+
+import org.ballerinalang.model.clauses.OnFailClauseNode;
+
+/**
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/statements/DoNode.java:22]: Shall we have a proper description here

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangDo.java [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+import org.ballerinalang.model.clauses.OnFailClauseNode;
+import org.ballerinalang.model.tree.NodeKind;
+import org.ballerinalang.model.tree.statements.BlockStatementNode;
+import org.ballerinalang.model.tree.statements.DoNode;
+import org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor;
+import org.wso2.ballerinalang.compiler.tree.clauses.BLangOnFailClause;
+
+/**
+ * @since Swan Lake
+ */
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangDo.java:29]: Lets give a brief description to this class

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STDoStatementNode.java [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+import io.ballerinalang.compiler.syntax.tree.NonTerminalNode;
+import io.ballerinalang.compiler.syntax.tree.SyntaxKind;
+
+import java.util.Collection;
+import java.util.Collections;
+
+/**
+ * This is a generated internal syntax tree node.
+ *
+ * @since 2.0.0
```
Comment (gimantha) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STDoStatementNode.java:31]: @since Swan Lake

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STFailStatementNode.java [hunk 4]
```diff
@@ -30,62 +30,66 @@
  *
  * @since 2.0.0
```
Comment (gimantha) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STFailStatementNode.java:31]: version should be Swan Lake

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STOnFailClauseNode.java [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+import io.ballerinalang.compiler.syntax.tree.OnFailClauseNode;
+import io.ballerinalang.compiler.syntax.tree.SyntaxKind;
+
+import java.util.Collection;
+import java.util.Collections;
+
+/**
+ * This is a generated internal syntax tree node.
+ *
+ * @since 2.0.0
```
Comment (gimantha) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STOnFailClauseNode.java:31]: @since Swan Lake

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/DoStatementNode.java [hunk 6]
```diff
@@ -0,0 +1,133 @@
...
+
+import io.ballerinalang.compiler.internal.parser.tree.STNode;
+
+import java.util.Objects;
+import java.util.Optional;
+
+/**
+ * This is a generated syntax tree node.
+ *
+ * @since 2.0.0
```
Comment (gimantha) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/DoStatementNode.java:28]: @since Swan Lake

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/DoStatementNode.java [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+    }
+
+    public DoStatementNodeModifier modify() {
+        return new DoStatementNodeModifier(this);
+    }
+
+    /**
+     * This is a generated tree node modifier utility.
+     *
+     * @since 2.0.0
```
Comment (gimantha) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/DoStatementNode.java:90]: version

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/OnFailClauseNode.java [hunk 8]
```diff
@@ -0,0 +1,168 @@
...
+package io.ballerinalang.compiler.syntax.tree;
+
+import io.ballerinalang.compiler.internal.parser.tree.STNode;
+
+import java.util.Objects;
+
+/**
+ * This is a generated syntax tree node.
+ *
+ * @since 2.0.0
```
Comment (gimantha) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/OnFailClauseNode.java:27]: version

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 9]
```diff
@@ -7362,7 +7378,13 @@ private STNode parseLockStatement() {
         STNode lockKeyword = parseLockKeyword();
         STNode blockStatement = parseBlockNode();
         endContext();
-        return STNodeFactory.createLockStatementNode(lockKeyword, blockStatement);
+        STNode onFailClause;
+        if (peek().kind == SyntaxKind.ON_KEYWORD) {
+            onFailClause = parseOnFailClause();
+        } else {
+            onFailClause = STNodeFactory.createEmptyNode();
+        }
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:7386]: We need to for error recovery here, if the next token is not the `on` keyword nor any statement-starting token.
eg: missing `on` keyword, but the rest is present from the `fail` keyword.

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STFailStatementNode.java (hunk 4 above)
Comment (mohanvive) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STFailStatementNode.java:31]: Actually, we have decided to move ahead with 2.0.0. Let's use "2.0.0" instead of Swan Lake.

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 10]
```diff
@@ -10690,6 +10730,25 @@ private STNode parseRetryBody() {
...
+    private STNode parseOnFailClause() {
+        STNode onKeyword = parseOnKeyword();
+        STNode failKeyword;
+        STToken nextToken = peek();
+        if (nextToken.kind == SyntaxKind.FAIL_KEYWORD) {
+            failKeyword = parseFailKeyword();
+        } else {
+            // No other cases for now
+            failKeyword = STNodeFactory.createEmptyNode();
+        }
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:10742]: According to the grammar, fail keyword is not optional.

**Review by SupunS — DISMISSED** [review]

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java (hunk 9 above)
Comment (SupunS) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:7386]: Seems on on fail clause is not optional.

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 11]
```diff
@@ -10690,6 +10730,25 @@ private STNode parseRetryBody() {
         }
     }
 
+    private STNode parseOnFailClause() {
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:10733]: Shall we add the grammar rule as a doc comment?

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 12]
```diff
@@ -5056,75 +5085,66 @@ private STNode parseCheckingKeyword() {
...
+            recover(token, ParserRuleContext.CONTINUE_KEYWORD);
+            return parseContinueKeyword();
         }
     }
 
     /**
-     * Parse continue statement.
-     * <code>continue-stmt := continue ; </code>
+     * Parse fail statement.
+     * <code>fail-stmt := return [ action-or-expr ] ;</code>
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:5118]: grammar rule seems to be incorrect

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 13]
```diff
@@ -4963,7 +4986,13 @@ private STNode parseWhileStatement() {
         STNode condition = parseExpression();
         STNode whileBody = parseBlockNode();
         endContext();
-        return STNodeFactory.createWhileStatementNode(whileKeyword, condition, whileBody);
+        STNode onFailClause;
+        if (peek().kind == SyntaxKind.ON_KEYWORD) {
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:4990]: Need to update the doc comment with the new grammar. 
Applicable for all places.

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/WhileStatementTest.java [hunk 14]
```diff
@@ -36,6 +36,11 @@ public void testWhileWithBody() {
         testFile("while-stmt/while_stmt_source_02.bal", "while-stmt/while_stmt_assert_02.json");
     }
 
+    @Test
+    public void testWhileWithOnFailClause() {
```
Comment (SupunS) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/WhileStatementTest.java:40]: Shall we add some negative tests as well?
eg: missing certain parts of the on-fail-clause, having additional tokens in between the tokens in on-fail-clause, etc.

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 15]
```diff
@@ -2859,10 +2862,11 @@ protected STNode parseStatement() {
             case RETRY_KEYWORD:
             case ROLLBACK_KEYWORD:
             case MATCH_KEYWORD:
+            case ON_KEYWORD:
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:2865]: is `on_keyword` statement start token?

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 16]
```diff
@@ -5056,75 +5085,66 @@ private STNode parseCheckingKeyword() {
...
+
         STToken token = peek();
-        if (token.kind == SyntaxKind.CONTINUE_KEYWORD) {
+        if (token.kind == SyntaxKind.FAIL_KEYWORD) {
             return consume();
         } else {
-            recover(token, ParserRuleContext.CONTINUE_KEYWORD);
-            return parseContinueKeyword();
+            Solution sol = recover(token, ParserRuleContext.FAIL_KEYWORD);
+            return sol.recoveredNode;
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:5147]: Shouldn't this be ?
```suggestion
            recover(token, ParserRuleContext.FAIL_KEYWORD);
            return parseFailKeyword();
```

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 17]
```diff
@@ -10690,6 +10730,25 @@ private STNode parseRetryBody() {
...
+        STToken nextToken = peek();
+        if (nextToken.kind == SyntaxKind.FAIL_KEYWORD) {
+            failKeyword = parseFailKeyword();
+        } else {
+            // No other cases for now
+            failKeyword = STNodeFactory.createEmptyNode();
+        }
+        STNode typeDescriptorNode = parseTypeDescriptor(ParserRuleContext.TYPE_DESC_IN_TYPE_BINDING_PATTERN,
+                true, false);
+        STNode identifierNode = parseIdentifier(ParserRuleContext.VARIABLE_REF);
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:10745]: shouldn't we use parseTypedBindingPattern() instead?

File: compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json [hunk 18]
```diff
@@ -4058,6 +4093,53 @@
...
+                    "name": "failKeyword",
+                    "type": "Token"
+                },
+                {
+                    "name": "typeDescriptor",
+                    "type": "TypeDescriptorNode"
+                },
+                {
+                    "name": "failErrorName",
+                    "type": "IdentifierToken"
```
Comment (lochana-chathura) [inline compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json:4116]: shouldn't we use typedBindingPatternNode here?
```json
               {
                    "name": "typedBindingPattern",
                    "type": "TypedBindingPatternNode"
                },
```

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 19]
```diff
@@ -3001,6 +3006,7 @@ private void startContextIfRequired(ParserRuleContext currentCtx) {
             case CONTINUE_STATEMENT:
             case BREAK_STATEMENT:
             case RETURN_STMT:
+            case FAIL_STATEMENT:
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParserErrorHandler.java:3009]: Don't we need to start a context for `DO_BLOCK` also?

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java (hunk 13 above)
Comment (pcnfernando) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:4989]: Fixed with 3189bc6c6a9ee435ca57fa863f10d8e4f357ab6b

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java (hunk 12 above)
Comment (pcnfernando) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java]: Fixed with 3189bc6c6a9ee435ca57fa863f10d8e4f357ab6b

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java (hunk 11 above)
Comment (pcnfernando) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:10738]: Fixed with 3189bc6c6a9ee435ca57fa863f10d8e4f357ab6b

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java (hunk 15 above)
Comment (pcnfernando) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java]: No. Fixed with 3189bc6c6a9ee435ca57fa863f10d8e4f357ab6b

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/statements/DoNode.java (hunk 1 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/statements/DoNode.java:22]: Added in 3cd62b5aa3dd887f5272949bd3cbb00faad8030c

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangDo.java (hunk 2 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/statements/BLangDo.java:35]: Added in 3cd62b5aa3dd887f5272949bd3cbb00faad8030c

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java (hunk 10 above)
Comment (pcnfernando) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java]: Fixed with 3189bc6c6a9ee435ca57fa863f10d8e4f357ab6b

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java (hunk 11 above)
Comment (pcnfernando) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:10738]: Fixed with 3189bc6c6a9ee435ca57fa863f10d8e4f357ab6b

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java (hunk 12 above)
Comment (pcnfernando) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java]: Fixed with 3189bc6c6a9ee435ca57fa863f10d8e4f357ab6b

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java (hunk 13 above)
Comment (pcnfernando) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:4989]: Fixed with 3189bc6c6a9ee435ca57fa863f10d8e4f357ab6b

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java (hunk 15 above)
Comment (pcnfernando) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java]: Fixed with 3189bc6c6a9ee435ca57fa863f10d8e4f357ab6b

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/WhileStatementTest.java (hunk 14 above)
Comment (pcnfernando) [reply compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/statements/WhileStatementTest.java:40]: We'll improve error handling and negative test cases separately. Created https://github.com/ballerina-platform/ballerina-lang/issues/25711 to track the progress.

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 20]
```diff
@@ -10703,6 +10742,24 @@ private STNode parseRetryBody() {
...
+    /**
+     * Parse on fail clause.
+     * <code>on-fail-clause := on fail typed-binding-pattern block-stmt</code>
+     *
+     * @return While statement
+     */
+    private STNode parseOnFailClause() {
+        STNode onKeyword = parseOnKeyword();
+        STNode failKeyword = parseFailKeyword();
+        STNode typeDescriptorNode = parseTypeDescriptor(ParserRuleContext.TYPE_DESC_IN_TYPE_BINDING_PATTERN,
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:10754]: Don't we need to start context for on fail clause?

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:10754]: I thing we need to add error handler logic for on fail clause as well.

**Review by mohanvive — APPROVED** [review]

**Review by mohanvive — APPROVED** [review]
