### PR TITLE
Fix failing unit tests for Java 21 migration

### LINKED ISSUE #43337: [Task]: Fix failing tests for Java 21 migration
### Description

$subject

### Describe your task(s)

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject

Fixes #43337 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/async/BasicAsyncOperationsTest.java [hunk 1]
```diff
@@ -91,8 +91,7 @@ public void testAsyncNonNativeBasic8() {
 
     @Test
     public void testAsyncNonNativeBasic9() {
-        Object returns = BRunUtil.invoke(result, "testAsyncNonNativeBasic9", new Object[0]);
-        Assert.assertEquals(returns, 7L);
+        BRunUtil.invoke(result, "testAsyncNonNativeBasic9", new Object[0]);
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/async/BasicAsyncOperationsTest.java:94]: Why we remove assertion here

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/async/basic-async-operations.bal [hunk 2]
```diff
@@ -90,12 +91,18 @@ function testAsyncNonNativeBasic8() returns int {
     return result;
 }
 
-function testAsyncNonNativeBasic9() returns int {
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/async/basic-async-operations.bal:93]: Why this test changed?

Comment (HindujaB) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/async/basic-async-operations.bal:93]: For alternative wait the expected behavior depends on the non-error return value. In this test case, `future f1` is cancelled
In this test, the alternate wait panics with future cancelled error as we manually cancel the f1 before the wait.
Since it's a panic the wait should terminate as per the spec. 
I moved the assertion to Ballerina side for handling the error.
And I added the if condition as there may be a chance of f2 completing before which will result in 7.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/async/BasicAsyncOperationsTest.java (hunk 1 above)
Comment (HindujaB) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/async/BasicAsyncOperationsTest.java:94]: The assertion is moved to Ballerina side to assert error details.

**Review by warunalakshitha — APPROVED** [review]
LGTM
