### PR TITLE
Fix module constant usage in xml attribute access

### LINKED ISSUE #32624: Wrong behaviour with XML attribute access with qualified name where the qualified name referring to a module const string
**Description:**
```ballerina

// public const string A = "{NSURL}B"; this is in module `y`

// import org/y;

xmlns "NSURL" as ns;
public function main() {
    
    io:println(y:A);
    xml x = xml `<a ns:A="content"></a>`;
    io:println(x.y:A); // y:A should refer to the value from `y` === `{NSURL}B`
}
```

Reproduceble with:
[X.zip](https://github.com/ballerina-platform/ballerina-lang/files/7126953/X.zip)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by poorna2152**
## Purpose

Fixes #32624

## Approach
Previously, the assumption was that when a `qualifiedName:identifier` appeared in an XML attribute access, the qualified name referred to an XML namespace. This assumption originated at the BLangNodeBuilder level (referenced [here](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java#L2165-L2173)). At the `BLangNodeBuilder` level,  there is not enough information to differentiate whether this referred to a moduleName constant or an XML namespace. A class `BLangFieldBasedAccess.BLangNSPrefixedFieldBasedAccess`  was created at the `BLangNodeBuilder` level which stored a `BXMLNSSymbol`.
Since it was not possible to differentiate between the module constant and the xml namespace the existing class was renamed and modified to store a BSymbol rather than a XMLNSymbol. 
Thus in the case of a module constant this field stored a BConstantSymbol and in the presence of a xml namespace this stored a BXMLNSSymbol.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -5776,6 +5776,10 @@ private BSymbol findXMLNamespaceFromPackageConst(String localname, String prefix
             return null;
         }
 
+        if (pkgSymbol.getKind() == SymbolKind.PACKAGE && !PackageID.isLangLibPackageID(pkgSymbol.pkgID)) {
```
Comment (LakshanWeerasinghe) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5779]:
```suggestion
        if (!PackageID.isLangLibPackageID(pkgSymbol.pkgID)) {
```
Do we need to check the symbol kind since we are already passing a package symbol?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 2]
```diff
@@ -720,7 +720,7 @@ error.invalid.xml.ns.interpolation=\
   xml namespaces cannot be interpolated
 
 error.cannot.find.xml.namespace.prefix=\
```
Comment (LakshanWeerasinghe) [inline compiler/ballerina-lang/src/main/resources/compiler.properties:722]:
```suggestion
error.cannot.find.xml.prefix=\
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/XMLAttrAccessWithModulePrefix.java [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+
+import java.util.Arrays;
+
+import static org.ballerinalang.test.BAssertUtil.validateError;
+import static org.testng.Assert.assertEquals;
+
+/**
+ * @since 2201.9.0
+ */
+public class XMLAttrAccessWithModulePrefix {
```
Comment (LakshanWeerasinghe) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/XMLAttrAccessWithModulePrefix.java:37]:
```suggestion
public class XMLAttrAccessWithModulePrefixTest {
```
This will be helpful to differentiate test classes

**Comment by chiranSachintha** [comment]
Consider the following scenario
module/Foo
```ballerina
public final string A = "B";
```

module/Bar
```ballerina
public function main() {
    xml x = xml `<a B="content"></a>`;
    io:println(x.Foo:A); 
}
```
For above scenario, getting an error as `undefined symbol 'Foo:A'`. That is not correct.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 4]
```diff
@@ -972,6 +972,27 @@ public BSymbol lookupMemberSymbol(Location pos,
...
 
+    /**
+     * Return the symbol with the given name even with a different package.
+     *
+     * @param scope     current scope
+     * @param name      symbol name
+     * @param expSymTag expected symbol type/tag
+     * @return resolved symbol
+     */
+    public BSymbol lookupPossibleMemberSymbol(Scope scope, Name name, long expSymTag) {
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:983]: The function `lookupMemberSymbol` works similar to this function. What we have to do is create a function that looks for member symbol (keep lookupMemberSymbol function). Then, wherever we need to check if access to that symbol is allowed, we need to do `isMemberAccessAllowed` check

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangFieldBasedAccess.java [hunk 5]
```diff
@@ -117,21 +117,21 @@ public <T, R> R apply(BLangNodeTransformer<T, R> modifier, T props) {
      *
      * @since 1.2.0
      */
-    public static class BLangNSPrefixedFieldBasedAccess extends BLangFieldBasedAccess {
+    public static class BLangPrefixedFieldBasedAccess extends BLangFieldBasedAccess {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangFieldBasedAccess.java:120]: What was the reason for this change?

Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangFieldBasedAccess.java:120]: From the approach [above](https://github.com/ballerina-platform/ballerina-lang/pull/41984#issue-2083753161). Previously, the assumption was that when a qualifiedName:identifier appeared in an XML attribute access, the qualified name referred to an XML namespace. This assumption originated at the BLangNodeBuilder level [here](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java#L2165-L2173). At the BLangNodeBuilder level, there is not enough information to differentiate whether this referred to a moduleName constant or an XML namespace. An object of class `BLangFieldBasedAccess.BLangNSPrefixedFieldBasedAccess` was created at the BLangNodeBuilder level which stored a BXMLNSSymbol. Having the class name as `BLangPrefixedFieldBasedAccess` is generic for namespace prefix access and the module level prefix access.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 6]
```diff
@@ -5956,22 +5956,31 @@ public void visit(BLangXMLQName bLangXMLQName, AnalyzerData data) {
...
                                                      BPackageSymbol pkgSymbol, Location pos, AnalyzerData data) {
         // Resolve a const from module scope.
-        BSymbol constSymbol = symResolver.lookupMemberSymbol(pos, pkgSymbol.scope, data.env,
-                Names.fromString(localname), SymTag.CONSTANT);
+        BSymbol constSymbol =
+                symResolver.lookupPossibleMemberSymbol(pkgSymbol.scope, names.fromString(localname), SymTag.CONSTANT);
         if (constSymbol == symTable.notFoundSymbol) {
             if (!missingNodesHelper.isMissingNode(prefix) && !missingNodesHelper.isMissingNode(localname)) {
-                dlog.error(pos, DiagnosticErrorCode.UNDEFINED_SYMBOL, prefix + ":" + localname);
+                dlog.error(pos, DiagnosticErrorCode.UNDEFINED_CONSTANT_SYMBOL, prefix + ":" + localname);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5963]: Please recheck the pos, seems to be for the entire expression atm.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 7]
```diff
@@ -5956,22 +5956,31 @@ public void visit(BLangXMLQName bLangXMLQName, AnalyzerData data) {
...
+        }
+
         // If Resolved const is not a string, it is an error.
         BConstantSymbol constantSymbol = (BConstantSymbol) constSymbol;
         if (constantSymbol.literalType.tag != TypeTags.STRING) {
             dlog.error(pos, DiagnosticErrorCode.INCOMPATIBLE_TYPES, symTable.stringType, constantSymbol.literalType);
             return null;
         }
 
+        if (!PackageID.isLangLibPackageID(pkgSymbol.pkgID)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:5980]: Why do we need to special case langlib?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/XMLAttrAccessWithModulePrefixTest.java [hunk 8]
```diff
@@ -0,0 +1,81 @@
...
+import org.testng.annotations.DataProvider;
+import org.testng.annotations.Test;
+
+import static org.ballerinalang.test.BAssertUtil.validateError;
+import static org.testng.Assert.assertEquals;
+
+/**
+ * Tests for xml attribute access using module constants.
+ *
+ * @since 2201.9.0
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/types/XMLAttrAccessWithModulePrefixTest.java:35]: Please update versions.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 7 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: This was because this function being used for xml attribute access as well as generating xmlnamespace symbols for prefix based names. Thus refactored the code

**Review by gimantha — APPROVED** [review]
