### PR TITLE
Validate missing key expr in invalid member access expressions in parser

### LINKED ISSUE #25432: Node Transformer fails with a NPE
**Description:**
Consider the following source snippet,

```
import ballerina/http;
function testFunction() {
    int[] myList = [1, 2, 3];

    myList[]
}

```

This fails at the NodeTransformer with the following exception,
```
Caused by: java.lang.NullPointerException
	at io.ballerinalang.compiler.internal.syntax.ExternalTreeNodeList.childInBucket(ExternalTreeNodeList.java:56)
	at io.ballerinalang.compiler.syntax.tree.SeparatedNodeList.get(SeparatedNodeList.java:46)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1887)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:415)
	at io.ballerinalang.compiler.syntax.tree.IndexedExpressionNode.apply(IndexedExpressionNode.java:58)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createActionOrExpression(BLangNodeTransformer.java:3762)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:3733)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2488)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:415)
	at io.ballerinalang.compiler.syntax.tree.ExpressionStatementNode.apply(ExpressionStatementNode.java:50)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:3644)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1284)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:415)
	at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1197)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1168)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:415)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:67)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:510)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:415)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:440)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:144)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:117)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compilePackagesSafe(LSModuleCompiler.java:291)
	... 11 more
```

**Affected Versions:**
SLP3 at least

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$Subject

Fixes #25432

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -14165,7 +14165,15 @@ private STNode parseTypedBindingPatternOrMemberAccessRhs(STNode typeDescOrExpr,
...
-                    keyExpr = STNodeFactory.createNodeList(member);
+                    if (member == null) {
+                        STNode missingVarRef = STNodeFactory.createSimpleNameReferenceNode(
+                                SyntaxErrors.createMissingToken(SyntaxKind.IDENTIFIER_TOKEN));
+                        keyExpr = STNodeFactory.createNodeList(missingVarRef);
+                        closeBracket = SyntaxErrors.addDiagnostic(closeBracket,
+                                DiagnosticErrorCode.ERROR_MISSING_KEY_EXPR_IN_MEMBER_ACCESS_EXPR);
+                    } else {
+                        keyExpr = STNodeFactory.createNodeList(member);
+                    }
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:14176]: Inside the same method, there seems to be multiple places where we call `STNodeFactory.createNodeList(member);` with member possibly being null. 

Shall we fix those as well? :)

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:14176]: +1

**Review by SupunS — APPROVED** [review]
