### PR TITLE
Fix not providing new line when muliple functions available

### LINKED ISSUE #34772: [Shell] Shell doesn't provide a new line when mutliple functions available
**Description:**

Consider following example

Screenshot from 2022-01-21 12-17-49

### PR DESCRIPTION
**Pull request by DamithaSenevirathne**
## Purpose

Fixes #34772

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/validator/ValidatorTest.java [hunk 1]
```diff
@@ -34,7 +34,6 @@ public void testValidator() {
         InputValidator inputValidator = new InputValidator();
 
         // Variable declarations
-        Assert.assertTrue(inputValidator.isComplete("int i = 12;"));
```
Comment (gayalkuruppu) [inline ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/validator/ValidatorTest.java:37]: Any specific reason to remove this test?

File: ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/validator/ModuleMemberValidator.java [hunk 2]
```diff
@@ -52,6 +53,16 @@ public boolean evaluate(String source) {
         ModulePartNode node = tree.rootNode();
         // Ignore code segments including imports
         Node parsedNode = NodeParser.parseModuleMemberDeclaration(source);
+        if (node.members().size() > 1) {
+            Node lastNode = node.members().get(node.members().size() - 1);
+            // Avoid false ModuleVariableDeclarations and special case functions
+            // Sample testcase : if (x == y) { x = x + 1; x = x + 1;
+            if (lastNode.kind() == SyntaxKind.FUNCTION_DEFINITION) {
```
Comment (gayalkuruppu) [inline ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/validator/ModuleMemberValidator.java:60]: Shouldn't we consider these scenarios as well?
`"int a = 10; if (a>5) {} else {"`

File: ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/validator/ValidatorTest.java (hunk 1 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-cli/src/test/java/io/ballerina/shell/cli/test/validator/ValidatorTest.java]: Added missing test case in 1064ce4f587e71a510eba19b47c9dd37ea3da89a

File: ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/validator/ModuleMemberValidator.java (hunk 2 above)
Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-cli/src/main/java/io/ballerina/shell/cli/jline/validator/ModuleMemberValidator.java:60]: Since we are considering the `Module Level` above example wont execute. If we are considering above case we need to update the shell parser side as well.

**Review by dulajdilshan — APPROVED** [review]
LGTM
