### PR TITLE
Fix incorrect rename popup on create var

### LINKED ISSUE #39301: [Bug]: Missing rename popup in create variable and check error code action
### Description

Consider the following scenario,

https://user-images.githubusercontent.com/61020198/213349934-3ea2c296-a144-461d-88e3-9a59229ad4e2.mov

### Steps to Reproduce

```
import ballerina/http;
import ballerinax/mongodb;

configurable string password = ?;
configurable string database = ?;
configurable string username = ?;

mongodb:ConnectionConfig mongoConfig = {
    connection: {
        host: "localhost",
        auth: {
            username: username,
            password: password
        },
        options: {
            sslEnabled: false,
            serverSelectionTimeout: 15000
        }
    },
    databaseName: database
};

mongodb:Client mongo = check new (mongoConfig);

type Joureny record {|
    string 'start;
    string end;
    decimal cost;
    int days;
    int numOfPeople;
|};

service /journey on new http:Listener(9090) {
    resource function get .() returns Joureny {
        mongo->getDatabasesNames();
    }
}

```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
$subject with check error code action

Fixes #39301

## Approach
The logic of calculating the new rename position was incorrect for the text position based approach. Improved that.

## Samples
rename_popup_fix

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by malinthar — APPROVED** [review]
LGTM!

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java [hunk 1]
```diff
@@ -103,7 +103,7 @@ public List<CodeAction> getCodeActions(Diagnostic diagnostic,
                 positionDetails.matchedNode(), context));
         edits.addAll(importsAcceptor.getNewImportTextEdits());
 
-        int renamePosition = modifiedTextEdits.renamePositions.get(0) - UNION_ERROR_CHAR_OFFSET;
+        int renamePosition = modifiedTextEdits.renamePositions.get(0);
```
Comment (mindula) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java:106]: Since we are no longer using `UNION_ERROR_CHAR_OFFSET`, we can remove the constant created in line number 52.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java [hunk 2]
```diff
@@ -133,9 +133,13 @@ private CreateVariableOut getModifiedCreateVarTextEdits(Diagnostic diagnostic,
         String typeWithError = createVarTextEdits.types.get(0);
         String typeWithoutError = getTypeWithoutError(unionTypeDesc, context, importsAcceptor);
 
+        int lengthtDiff = typeWithError.length() - typeWithoutError.length();
```
Comment (mindula) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java:136]:
```suggestion
        int lengthDiff = typeWithError.length() - typeWithoutError.length();
```

Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java]: Done

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java (hunk 1 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/ErrorHandleOutsideCodeAction.java:105]: +1

**Review by mindula — APPROVED** [review]
