### PR TITLE
Fix sorting in Record type descriptor node context

### LINKED ISSUE #40617: [Improvement]: Improve sorting of trie completion items
### Description

Consider the following capture

image

The `log: setOutput()` completion item depicted above should not be given the highest priority in the above context. basic types and other user-defined types should be given the highest priority. 

### Describe your problem(s)

```ballerina
import ballerina/log;
import ballerina/http;

final http:Client clientEP = check new ("http://localhost:9090/");

type Person record {|
    string name;
    int age;
    s<cursor>
|};

type Params record {|

|};

public function main() returns error? {
    // http:Response res = check clientEP->/test;
    // log:printInfo("response obtained", statuscode = res.statusCode, payload = check res.getTextPayload());
    test("hello", 1, 2);
    testIncludedRecordParams();
}

public function test(string arg1, int... restArg) {

}

public function testIncludedRecordParams() {

}

```

### Describe your solution(s)

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
This PR fixes the sorting order in record type descriptor node context.

Fixes #40617

## Samples
Screenshot 2023-07-25 at 14 01 39

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by malinthar — COMMENTED** [review]
IIUC, this change does not change the sorting order. It rather fixes the invalid sorting caused when the filter text is incorrect, right? If so, can you mention the order of the completion items(kinds)

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java [hunk 1]
```diff
@@ -308,6 +308,9 @@ private List<LSCompletionItem> getTypeItems(BallerinaCompletionContext context)
                 completionItem.setInsertText(moduleName + ":" + insertText);
                 completionItem.setLabel(moduleName + ":" + label);
                 completionItems.add(lsCompletionItem);
+                if (completionItem.getFilterText() != null) {
+                    completionItem.setFilterText(moduleName + "_" + completionItem.getFilterText());
```
Comment (KavinduZoysa) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java:312]: Can't we set this filter text(i.e: filter text with module name) inside `getCompletionItemList` function(L:299)?

**Comment by mindula** [comment]
> IIUC, this change does not change the sorting order. It rather fixes the invalid sorting caused when there is a filter text available and the filtertexts of some completion items are incorrect, right? If so, can you mention the order of the completion items(kinds)

Yes this fix doesn't specifically change the sorting order, but due to the change in the filter text there is some sort of a change in the sorting. You can refer to https://github.com/ballerina-platform/ballerina-lang/issues/40617#issuecomment-1649889052.
The order of the completion items is as follows,
1. Types defined in the same module
2. Types visible from other modules (StrandData, Thread in lang.value)
3. Visible Modules
4. Constant
5. Enums
6. Enum Member
7. Basic Types (boolean, int, string, etc.)
8. Type Descriptor snippets (record snippet, object snippet)
9. keywords (true, false, record, object)

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java (hunk 1 above)
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java:312]: No we can't because we only want to set the filter text for the types of external modules.

**Review by KavinduZoysa — APPROVED** [review]

**Review by malinthar — APPROVED** [review]
