### PR TITLE
Fix sorting in call expression context

### LINKED ISSUE #35343: Improve sorting in call expression context
**Description:**
Consider the following scenario
image

The symbols of `int` type should be sorted to the top of the completion list.

```ballerina

public function main() {
    string a;
    int b;
    int[] arr = [];

    arr.push();
}



```

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject

Fixes #35343 

## Samples
image

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java [hunk 1]
```diff
@@ -293,7 +293,7 @@ public ContextTypeResolver(PositionedOperationContext context) {
         if (typeRefSymbol.isEmpty()) {
             return Optional.empty();
         }
-        
+
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:296]: I think still the sorting order is not finalized. We get the following, where `b` should be at the top. Are we having the context type resolving issue here for the langlib methods?
Screen Shot 2022-03-24 at 8 56 17 AM

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java (hunk 1 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:296]: For some reason https://github.com/ballerina-platform/ballerina-lang/blob/02411da0cf01ac4f76c768ed911728b0e0ad115b/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/MethodCallExpressionNodeContext.java#L111 we have decided to rank the methods/functions first. Should we change this behavior. Is there a specific reason behind this @IMS94

Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:296]: @malinthar Seems like the logic should be improved. If we are within the parameter context, we should rank `symbolKind.VARIABLE` higher. Adding a new `else if` condition for `Variables` will do the trick IMO.
```java
                    } else if (symbol.stream().anyMatch(sym -> sym.kind() == SymbolKind.VARIABLE)) {
                        rank = withinParameterCtx ? 1 : 3;
                        break;
                    } else {
```

Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:296]: Or we can SortingUtil.toRank() method which ranks the completion items in the standard order

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:296]: My concern here is, since the main method returns `()` while b is already an int variable, why we are not showing the variable `b` at the top.

Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:296]: @nadeeshaan We haven't considered assignability when sorting here. That's the issue. If we consider assignability, then this issue will be sorted automatically.

Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:296]: I have fixed the sorting order as follows. 
image

Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:296]: Can we move the `arr` to bottom? What's the context type we get here? `int[]` or `int`?

Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:296]: https://github.com/ballerina-platform/ballerina-lang/blob/95f08123f94dafc0e1a7758917f6f6822b6c83c1/langlib/lang.array/src/main/ballerina/array.bal#L245

As depicted above the first parameter of the push method is of type Type[]. Hence, sorting `arr` to the top is correct in this case IMO.

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:296]: @malinthar not really. What we are looking at here is method access where the method is coming from a standard library. For the standard libraries, the first parameter is being ignored if the types of the first parameter and the expression's type are the same. Hence we have to revamp this sorting

**Review by IMS94 — DISMISSED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 2]
```diff
@@ -1451,83 +1455,118 @@ private static String getQualifiedModuleName(Module module) {
...
+        if (isLangLibFunction) {
+            argIndex = argIndex + 1;
+        }
+
+        // We can be in required params or rest params
+        if (parameterSymbols.get().size() > argIndex) {
+            return Optional.of(parameterSymbols.get().get(argIndex));
+        } else if (restParam.isPresent()) {
+            return Optional.of(restParam.get());
+        }
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1503]: We can use `if` clause, instead of `else if`

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 3]
```diff
@@ -1451,83 +1455,118 @@ private static String getQualifiedModuleName(Module module) {
...
+                                                                            PositionedOperationContext context) {
+
+        if (methodCallExprNode.methodName().kind() != SyntaxKind.SIMPLE_NAME_REFERENCE) {
+            return Optional.empty();
+        }
+        SimpleNameReferenceNode typeRefNode = (SimpleNameReferenceNode) methodCallExprNode.methodName();
+        Optional<TypeSymbol> typeSymbol = context.currentSemanticModel()
+                .flatMap(semanticModel -> semanticModel.typeOf(methodCallExprNode.expression()));
+        return typeSymbol.flatMap(value -> value.langLibMethods().stream()
+                .filter(method -> method.getName().isPresent() &&
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1566]: In a simpler manner, we can use `method.getName().orElse("").equals(...)`

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 3 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java]: Done

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 2 above)
Comment (malinthar) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java]: +1

**Review by mohanvive — APPROVED** [review]
