### PR TITLE
Fix issue in isSameType() check for object types

### LINKED ISSUE #17912: incompatible types:, even if the types are the same
**Description:**
$subject, when there are two modules involved.

**Steps to reproduce:**
1. Create a project and add two modules (i.e `core_module`, `sub_module`). 
2. Add the following in `core_module` source;
```ballerina
import ballerinax/java.jdbc;

jdbc:Client dbClient = new({
    url: "jdbc:mysql://localhost:3306/productsdb_300_wso2umuat?useTimezone=true&serverTimezone=UTC",
    username: "root",
    password: "root",
    poolOptions: { maximumPoolSize: 5 },
    dbOptions: { useSSL: false }
});

public function getClient() returns jdbc:Client {
    return dbClient;
}
```
3. Add following in `sub_module` source;
```ballerina
import ballerina/io;
import core_module;
import ballerinax/java.jdbc;

public function main() {
    jdbc:Client dbClient = core_module:getClient();
}
```
4.  Build the project, and at the compile time you'll get;
```
error: grainier/sub_module:0.1.0::main.bal:6:28: incompatible types: expected 'ballerinax/java.jdbc:0.0.0:Client', found 'ballerinax/java.jdbc:0.0.0:Client'
```

**Affected Versions:**
1.0.0-alpha

**OS, DB, other environment details and versions:**
Windows, Mac

**Related Issues (optional):**
https://stackoverflow.com/questions/57503996/ballerina-identical-types-are-incompatible

### PR DESCRIPTION
**Pull request by pubudu91**
Fixes #17912

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -1933,7 +1941,7 @@ private BAttachedFunction getMatchingInvokableType(List<BAttachedFunction> rhsFu
 
     private boolean isInSameVisibilityRegion(BSymbol lhsSym, BSymbol rhsSym) {
         if (Symbols.isPrivate(lhsSym)) {
-            return Symbols.isPrivate(rhsSym) && lhsSym.pkgID.equals(rhsSym.pkgID) && lhsSym.name.equals(rhsSym.name);
+            return Symbols.isPrivate(rhsSym) && lhsSym.pkgID.equals(rhsSym.pkgID);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Shouldn't we consider the type name too? This would produce incorrect results if called independently right?

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Added with 52a9876
