### PR TITLE
Fix NPE with ballerina.observe.StartSpan #startSpan due to observability not enabled

### LINKED ISSUE #39717: [Bug]: Start a span for tracing gives java.lang.NullPointerException
### Description

Start a span using `observe:startSpan()` gives `java.lang.NullPointerException`

### Steps to Reproduce

```ballerina
import ballerina/http;
import ballerina/observe;
import ballerinax/jaeger as _;

service /hello on new http:Listener(9090) {

    resource function get sayHello (http:Caller caller, http:Request request) returns error? {
        map<string> tags = {"app.name": "hello-service", "http.method": request.method, "http.path": request.rawPath};
        int|error span = observe:startSpan("greet-span", tags);

        // string? name = request.getQueryParamValue("name");
        // string message = "Hello, " + (name ?: "world") + "!";
        string message = "hello world!";
        http:Response response = new;
        response.setPayload(message);

        // Finish the tracing span
        check observe:finishSpan(check span);

        check caller->respond(response);
    }
}
```
commands:
>$ bal run
>$ curl http://localhost:9090/hello/sayHello

result:
```
ballerina: started publishing traces to Jaeger on localhost:55680
error: java.lang.NullPointerException
        at ballerina.observe.1:startSpan(natives.bal:43)
           $anonType$_0:$get$sayHello(hello_world_service.bal:42)
```

### Affected Version(s)

2201.3.x

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #39717 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java [hunk 1]
```diff
@@ -58,6 +60,10 @@ public void setTracerGenerator(TracerProvider tracerProvider) {
      * @return trace implementations i.e: zipkin, jaeger
      */
     public Tracer getTracer(String serviceName) {
+        if (!isInitialized()) {
+            throw ErrorCreator.createError(StringUtils.fromString("error: tracer store is not initialized " +
+                    "due to observability has not been enabled"));
```
Comment (Nadeeshan96) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java:65]:
```suggestion
            throw ErrorCreator.createError(StringUtils.fromString("error: tracer store is not initialized " +
                    "because observability is disabled"));
```

Comment (Nadeeshan96) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java:65]:
```suggestion
            throw ErrorCreator.createError(StringUtils.fromString("error: tracer store is not initialized " +
                    "because observability has not been enabled"));
```

**Review by warunalakshitha — APPROVED** [review]
LGTM

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java [hunk 2]
```diff
@@ -58,6 +60,10 @@ public void setTracerGenerator(TracerProvider tracerProvider) {
      * @return trace implementations i.e: zipkin, jaeger
      */
     public Tracer getTracer(String serviceName) {
+        if (!isInitialized()) {
+            throw ErrorCreator.createError(StringUtils.fromString("error: tracer store is not initialized " +
```
[the remark this answers is not in the document]
Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java:64]: We follow a convention to start the error messages with simple letter

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java [hunk 3]
```diff
@@ -73,7 +79,7 @@ public Tracer getTracer(String serviceName) {
                 store.put(serviceName, tracer);
             } else {
                 tracer = io.opentelemetry.api.trace.TracerProvider.noop().get("");
-                consoleError.println("error: tracing disabled as tracer provider had not been initialized");
+                consoleError.println("error: tracing disabled as tracer provider had not been initialized.");
```
Comment (Nadeeshan96) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java:82]:
```suggestion
                consoleError.println("error: tracing is disabled as the tracer provider has not been initialized.");
```

Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java:82]: Yes, we can keep it as "tracing disabled".

Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java:82]: We can add an integration test with the observability disabled to cover these error lines.

**Review by praneesha — APPROVED** [review]

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java (hunk 3 above)
Comment (gabilang) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/tracer/TracersStore.java]: In order to recreate this scenario, we need to import the `ballerina/observe` module. It's not desirable to import a stdlib module for test cases here. We can add a test to `ballerina/observe` module. Created a task there to add missing negative test cases https://github.com/ballerina-platform/module-ballerina-observe/issues/66.

**Review by warunalakshitha — APPROVED** [review]
LGTM
