### PR TITLE
Fix the type of the maps which are created with Query-expressions

### LINKED ISSUE #36695: Query-expressions that construct maps and tables should not always have error type
**Description:**
$title. This should be fixed after fixing https://github.com/ballerina-platform/ballerina-lang/issues/36181. 

**Steps to reproduce:**

Ex.
```ballerina
type Employee record {|
    readonly int id;
    string firstName;
|};

public function main() {
    table<Employee> key(id) employees = table [
        {id: 1, firstName: "John"}
    ];

    table<Employee> key(id) highPaidEmployees = table key(id) from var e in employees
                            select e; // expected 'table<Employee> key(id)', found '(table<Employee> key(id)|error)'
// Here, both `from-clause` and `select-clause` will not complete early with an error value. 
// Therefore, for this scenario, compiler should allow this statement.
// Same for map case also
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by SandaruJayawardana**
Fixes #36695

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 1]
```diff
@@ -326,6 +324,25 @@ BLangStatementExpression desugar(BLangQueryExpr queryExpr, SymbolEnv env,
         return streamStmtExpr;
     }
 
+    private BType getMapType(BType type) {
+        BType refType = Types.getReferredType(type);
+        BType resultantType = symTable.mapType;
+        if (refType.tag == TypeTags.UNION) {
```
Comment (lasinicl) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:330]: When can this be a union?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 2]
```diff
@@ -326,6 +324,25 @@ BLangStatementExpression desugar(BLangQueryExpr queryExpr, SymbolEnv env,
...
+            for (BType memberType : ((BUnionType) type).getMemberTypes()) {
+                BType resultType = getMapType(memberType);
+                if (resultType != symTable.mapType) {
+                    resultantType = resultType;
+                    break;
+                }
+            }
+        } else if (refType.tag == TypeTags.INTERSECTION) {
+            resultantType = getMapType(((BIntersectionType) refType).effectiveType);
```
Comment (lasinicl) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:339]:
```suggestion
            return getMapType(((BIntersectionType) refType).effectiveType);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 3]
```diff
@@ -326,6 +324,25 @@ BLangStatementExpression desugar(BLangQueryExpr queryExpr, SymbolEnv env,
...
+        } else if (refType.tag == TypeTags.MAP) {
+            resultantType = refType;
```
Comment (lasinicl) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:341]:
```suggestion
            return refType;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 4]
```diff
@@ -326,6 +324,25 @@ BLangStatementExpression desugar(BLangQueryExpr queryExpr, SymbolEnv env,
...
+        }
+        return resultantType;
```
Comment (lasinicl) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:343]:
```suggestion
        return symTable.mapType;
````

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal [hunk 5]
```diff
@@ -1252,6 +1247,66 @@ function testReadonlyMap2() {
...
+
+    map<int>|error map3 = map from var firstNo in [1, 4, 4, 10]
+                            select [firstNo.toBalString(), firstNo] on conflict error("Error");
+    assertEqual(map3, error("Error"));
+
+    table<NumberRecord> key(id)|error table6 = table key(id) from var firstNo in [1, 4, 4, 10]
+                            select {id: firstNo, value: firstNo.toBalString()} on conflict error("Error");
+    assertEqual(table6, error("Error"));
+}
+
```
Comment (lasinicl) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal:1309]: Shall we also test this in inner and nested queries?

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal [hunk 6]
```diff
@@ -624,7 +621,6 @@ type TokenTable table<Token> key(idx);
 
 function testQueryConstructingTableWithOnConflictClauseHavingNonTableQueryInLetClause() {
     TokenTable|error tbl1 = table key(idx) from int i in 1 ... 3
-        let int[] arr = from var j in 1 ... 3 select j
```
Comment (lasinicl) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal:627]: Why are we removing this?

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal [hunk 7]
```diff
@@ -643,7 +639,6 @@ function testQueryConstructingTableWithOnConflictClauseHavingNonTableQueryInLetC
     }
 
     TokenTable|error tbl2 = table key(idx) from int i in [1, 2, 1]
-        let int[] arr = from var j in 1 ... 3 select j
```
Comment (lasinicl) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal:646]: Here as well?

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal (hunk 6 above)
Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal:627]: There was an unused variable warning. Then we can improve this test with use this arr variable. Will revert the changes.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 1 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:330]: Ex. with on-conflict clause

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal (hunk 7 above)
Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal:646]: https://github.com/ballerina-platform/ballerina-lang/pull/36743#discussion_r909179729

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal (hunk 6 above)
Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal:627]: My bad. I didn't notice the test title (... InLetCluase). Shall I update this test with using `arr` in the select clause to avoid unused variable warning. WDYT @lasinicl ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 1 above)
Comment (lasinicl) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:330]: ah yes. missed that!

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal (hunk 6 above)
Comment (lasinicl) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal:627]: that would be okay.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 2 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:339]: I used this format to avoid codecov warnings for the last line in this method.

Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:339]: This method returns `symTable.mapType` when I can't find a map type from the queryExpr. I am not quite sure whether that logic is needed since we are doing the invalid scenarios at typeChecker level. I couldn't find a code sample to trigger that logic too. I used this default case because similar kind of approach is used for table constructing scenario. For safe side we can keep this logic. WDYT @lasinicl @pcnfernando

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal (hunk 5 above)
Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal:1309]: Added in https://github.com/ballerina-platform/ballerina-lang/pull/36743/commits/4a331040c56f5f6c278cc5f797f6d888dbb14e3e.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 2 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:339]: +1. Will update. Thanks.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 8]
```diff
@@ -326,6 +324,23 @@ BLangStatementExpression desugar(BLangQueryExpr queryExpr, SymbolEnv env,
...
 
+    private BType getMapType(BType type) {
+        BType refType = Types.getReferredType(type);
+        if (refType.tag == TypeTags.UNION) {
+            for (BType memberType : ((BUnionType) type).getMemberTypes()) {
+                BType tempType = getMapType(memberType);
+                if (tempType != symTable.noType) {
+                    return tempType;
+                }
+            }
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:335]: Can we check and add few tests for the uncovered paths

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 9]
```diff
@@ -283,9 +283,7 @@ BLangStatementExpression desugar(BLangQueryExpr queryExpr, SymbolEnv env,
             onConflictExpr = (onConflictExpr == null)
                     ? ASTBuilderUtil.createLiteral(pos, symTable.nilType, Names.NIL_VALUE)
                     : onConflictExpr;
-            BMapType mapType = (BMapType) ((BUnionType) queryExpr.getBType()).getMemberTypes()
-                    .stream().filter(m -> Types.getReferredType(m).tag == TypeTags.MAP)
-                    .findFirst().orElse(symTable.mapType);
+            BMapType mapType = (BMapType) getMapType(queryExpr.getBType());
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:286]: Why wouldn't the queryExpr type be resolved to a single type? Ideally, it should.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 8 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:335]: Seems we have to change the logic similar to https://github.com/ballerina-platform/ballerina-lang/pull/36743/commits/cfdb025ccf56d098e7b485b4a583d7e86e31527e. But I changed that logic to address the review suggestions. Shall I revert the changes? @pcnfernando

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 9 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:286]: This happens in 2 scenarios. 
1. When the contextually expected type is readonly, type of the query expression will be a `BIntersectionType` type.
2. When `On-Conflict` clause is available, type of the query expression will be a `BUnionType` of `BMapType` and `BError` type.

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:286]: That makes sense

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 10]
```diff
@@ -326,6 +324,23 @@ BLangStatementExpression desugar(BLangQueryExpr queryExpr, SymbolEnv env,
...
+                if (tempType != symTable.noType) {
+                    return tempType;
+                }
+            }
+        } else if (refType.tag == TypeTags.INTERSECTION) {
+            return getMapType(((BIntersectionType) refType).effectiveType);
+        } else if (refType.tag == TypeTags.MAP) {
+            return refType;
+        }
+        return symTable.noType;
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:341]: When can noType be returned?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 8 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:335]: This depends on when noType be returned https://github.com/ballerina-platform/ballerina-lang/pull/36743/files#r938427461

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 10 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:341]: I guess, it cannot be happened in here. I will change the logic to return `refType` in `else` case.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 8 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:335]: But it is already covered with tests. I debug and check few examples.
I noticed that the `mapType` is placed earlier compared `errorType` inside the `memberType` list in the `unionType`. Therefore, seems we cannot cover this line in current implementation. But I think there is a possibility to fill up the `memberTypes` in `unionType` in different order. Therefore, we have to keep this logic. isn't it? @pcnfernando ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 10 above)
Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:341]: See https://github.com/ballerina-platform/ballerina-lang/pull/36743#discussion_r938450434

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java (hunk 8 above)
Comment (lasinicl) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:335]: The type of the query expr resolved via `resolveQueryType()` method creates the union at this line right? https://github.com/ballerina-platform/ballerina-lang/blob/a2c659217a59162a7deb54bcf001a1c44bedbd34/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L5658
The `completionType` (which is `error` type here) will anyway come after the `actualType` when creating the union.? :thinking:

Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java]: Yeah. Updated in https://github.com/ballerina-platform/ballerina-lang/pull/36743/commits/5b3e2ea4988362bb08b7ec1054dbe1a13eb7ffc4.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java [hunk 11]
```diff
@@ -326,6 +324,16 @@ BLangStatementExpression desugar(BLangQueryExpr queryExpr, SymbolEnv env,
         return streamStmtExpr;
     }
 
+    private BType getMapType(BType type) {
+        BType refType = Types.getReferredType(type);
+        if (refType.tag == TypeTags.UNION) {
+            return getMapType(types.getSafeType(refType, false, true));
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java:330]: getSafeType() handles unions, hence we don't need the union check

Comment (SandaruJayawardana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/QueryDesugar.java]: Addressed in https://github.com/ballerina-platform/ballerina-lang/pull/36743/commits/fb95e5587428225ee1a8284b66e3a2efd22b28c2.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java [hunk 12]
```diff
@@ -204,6 +204,43 @@ public void testNegativeScenarios() {
                 "incompatible types: expected '(Department & readonly)', found 'Department'", 283, 55);
         validateError(negativeResult, index++, "incompatible types: expected '[string,string]', " +
                 "found '([string,int]|[string,int]|[string,int]|[string,int])'", 286, 48);
+        validateError(negativeResult, index++, "incompatible types: expected 'map<(int[2] & readonly)> & readonly'," +
+                " found '((map<(int[2] & readonly)> & readonly)|error)'", 292, 34);
+        validateError(negativeResult, index++, "incompatible types: expected '(Department & readonly)'," +
+                " found 'Department'", 297, 55);
+        validateError(negativeResult, index++, "incompatible types: expected '[string,string]', " +
```
Comment (pcnfernando) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java:211]: Here, why are we getting the collection type?

Comment (pcnfernando) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java:211]: It seems it's the same behavior as `foreach`. Type resolved for item is `[string, int]|[string, int]|[string, int]|[string, int]`
```ballerina
public function main() {
    foreach var item in [["1", 1], ["2", 2], ["3", 3], ["4", 4]] {
        string _ = item; //incompatible types: expected 'string', found '([string,int]|[string,int]|[string,int]|[string,int])
    }
}

```

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal (hunk 6 above)
Comment (pcnfernando) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal:627]: I still see the deletion in the diff

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java (hunk 12 above)
Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/QueryExprWithQueryConstructTypeTest.java:211]: Yeah. Therefore, we don't need to improve the error msg here right?

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal (hunk 6 above)
Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal:627]: will check

Comment (SandaruJayawardana) [reply tests/jballerina-unit-test/src/test/resources/test-src/query/query-expr-with-query-construct-type.bal:627]: Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/36743/commits/64c0b2d78125625a7b66f5a8070b505115c99de0.

**Review by pcnfernando — APPROVED** [review]
LGTM
