### PR TITLE
Fix enum type shadowing

### LINKED ISSUE #30805: Type definition shadows Enum symbol
Observed in SL-Beta1-RC4.

```ballerina
public enum Foo {
    foo, 
    bar
}

type Foo int; // Should be an error.

public function main() {
    Foo x = "foo"; // Not working.
}
```

### PR DESCRIPTION
**Pull request by gimantha**
Fixes #30805 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 1]
```diff
@@ -313,7 +313,10 @@ private boolean isDistinctSymbol(BSymbol symbol, BSymbol foundSym) {
 
     private boolean hasSameOwner(BSymbol symbol, BSymbol foundSym) {
         // check whether the given symbol owner is same as found symbol's owner
-        if (foundSym.owner == symbol.owner) {
+        if (foundSym.owner == symbol.owner ||
+                (foundSym.owner.tag & SymTag.PACKAGE) == SymTag.PACKAGE &&
+                (symbol.owner.tag & SymTag.PACKAGE) == SymTag.PACKAGE &&
+                foundSym.pkgID.equals(symbol.pkgID)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:319]: Isn't this issue due to/related to https://github.com/ballerina-platform/ballerina-lang/issues/26284, https://github.com/ballerina-platform/ballerina-lang/issues/30688. etc. 

```ballerina
public enum Foo {
    foo, 
    bar
}

type Foo int;
```

The owner of the symbol for `type Foo int` is what is incorrect here (lang.annotations), right? I think we need to fix the type aliasing issues before/instead of introducing these changes here.

@pubudu91, thoughts please?

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:319]: This check is ok I guess. But wondering how this fixed the issue though. Like Maryam said, in the type def's symbol the owner would be the `lang.annotations` module. 🤔

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:319]: We do have a symbol for `Foo` in `type Foo int;` here and the `pkgID` is the current package's ID. It's just that the owner of that is the lang.annotations module.

We shouldn't need this check though, right? I think we should be able to rely on the owner. IINM, there shouldn't be scenarios where two symbols' package IDs are the same but the owner package symbols are different?

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:319]: Ah I see. Yeah, with the fix for type aliases, ideally shouldn't need this. IIRC, we don't create package symbols like we do for other kinds of symbols. But for now, don't see any harm in this though.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 2]
```diff
@@ -313,7 +313,11 @@ private boolean isDistinctSymbol(BSymbol symbol, BSymbol foundSym) {
 
     private boolean hasSameOwner(BSymbol symbol, BSymbol foundSym) {
         // check whether the given symbol owner is same as found symbol's owner
-        if (foundSym.owner == symbol.owner) {
+        if (foundSym.owner == symbol.owner ||
+                //TODO: remove this, once #26284, #30688 are fixed
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:317]: Shall we create an issue too?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/natives/BuiltinLoadingTest.java [hunk 3]
```diff
@@ -31,17 +31,18 @@
     @Test
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/natives/BuiltinLoadingTest.java:31]: Sorry, missed this previously, but should we add the new test to `org.ballerinalang.test.variable.shadowing.ShadowingNegativeTest` instead?

File: tests/jballerina-unit-test/src/test/resources/test-src/natives/builtin-symbol-negative.bal [hunk 4]
```diff
@@ -9,3 +9,10 @@ type 'int int;
 type 'never never;
 type 'readonly readonly;
 type 'xml xml;
+
+public enum Foo {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/natives/builtin-symbol-negative.bal:13]: Shall we add a positive test to `org.ballerinalang.test.variable.shadowing.ShadowingTest` also?

e.g.,
```ballerina
type Foo int;

public function main() {
    string Foo = "hello";
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 2 above)
Comment (gimantha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:317]: sure

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/natives/BuiltinLoadingTest.java (hunk 3 above)
Comment (gimantha) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/natives/BuiltinLoadingTest.java:31]: sure, will move the test

File: tests/jballerina-unit-test/src/test/resources/test-src/natives/builtin-symbol-negative.bal (hunk 4 above)
Comment (gimantha) [reply tests/jballerina-unit-test/src/test/resources/test-src/natives/builtin-symbol-negative.bal:13]: sure

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 2 above)
Comment (gimantha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:317]: created https://github.com/ballerina-platform/ballerina-lang/issues/31433

**Review by MaryamZi — APPROVED** [review]
