### PR TITLE
[master] Fix annotation passing for immutable inline records

### LINKED ISSUE #39156: [Bug]: Annotations are not passed in the type if the type is readonly
### Description

The field level annotations are not passed with the type when the type is readonly. Due to this `constraint:validate()` method is not able to validate the constraints. 

Related to : https://github.com/ballerina-platform/ballerina-standard-library/issues/3742

### Steps to Reproduce

See the following code :

```ballerina
import ballerina/io;
import ballerina/constraint;

type Album readonly & record {|
    @constraint:String {
        maxLength: 5,
        minLength: 1
    }
    string title;
    string artist;
|};

public function main() returns error? {
    Album a = {
        artist: "test",
        title: "testss"
    };
    Album validAlbum = check constraint:validate(a);
    io:println(validAlbum);
}
```

The `<AnnotatableType>.getAnnotations()` is `null` when the record is `readonly`. If we remove `readonly`, we can get the annotations.

### Affected Version(s)

Ballerina SwanLake 2201.2.x
Ballerina SwanLake 2201.3.x

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes #39156

## Approach
As for inline records, the global annotation map is passed with `anonaType` key, it is not populated to the runtime record type.  So, we don't pass the `anonType` internal name to the runtime for retrieving the annotations which causes the issue. 
This PR passes the internal name to runtime to be used when populating annotations. 

## Samples
```ballerina
import ballerina/io;
import ballerina/constraint;

type Album readonly & record {|
    @constraint:String {
        maxLength: 5,
        minLength: 1
    }
    string title;
    string artist;
|};

public function main() returns error? {
    Album a = {
        artist: "test",
        title: "testss"
    };
    Album validAlbum = check constraint:validate(a); // should fail
    io:println(validAlbum);
}
```
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java [hunk 1]
```diff
@@ -443,4 +444,21 @@ public static BArray getTupleWithInitialValues(BTypedesc typedesc, BArray array)
...
 
+    public static Boolean checkInlineRecordAnnotations(BTypedesc typedesc, BTypedesc constraint) {
+        Type describingType = typedesc.getDescribingType();
+        if (describingType.getTag() == TypeTags.TYPE_REFERENCED_TYPE_TAG &&
+                ((ReferenceType) describingType).getReferredType().getTag() == TypeTags.INTERSECTION_TAG) {
+            describingType = ((IntersectionType)
+                    ((ReferenceType) describingType).getReferredType()).getConstituentTypes().get(0);
+        }
+        if (!(describingType instanceof AnnotatableType)) {
+            throw ErrorCreator.createError(StringUtils.fromString("Invalid type found."));
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Values.java:455]: Should we print type name here in the error?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BRecordType.java [hunk 2]
```diff
@@ -61,8 +61,9 @@ public class BRecordType extends BStructureType implements RecordType {
      * @param sealed flag indicating the sealed status
      * @param typeFlags flags associated with the type
      */
-    public BRecordType(String typeName, Module pkg, long flags, boolean sealed, int typeFlags) {
+    public BRecordType(String typeName, String internalName, Module pkg, long flags, boolean sealed, int typeFlags) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BRecordType.java:64]: should we remove other constructor where internal name can be null? or we can set internal name = typeName and add only declaration in the class private String internalName ;

Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BRecordType.java:64]: Updated the constructor to use the `typeName`

**Review by warunalakshitha — APPROVED** [review]
LGTM
