### PR TITLE
Correct the runtime behaviour for non-existent key access in records

### LINKED ISSUE #10393: Non-existent key access is not handled in open records
**Description:**
Consider the following program:
```ballerina
import ballerina/io;

type Foo record {
    string a;
    string b;
    string c;
    string...
};

function main(string... args) {
    Foo f = {a: "A", b: "B"};
    io:println(f.d);
}
```
The program above results in the following error:
```
error: error
	at main(test3.bal:12)
```
If we get rid of the rest descriptor (`string...`) in the type definition and run this, it runs without any error. This behaviour is invalid and needs to be changed to how maps behave.

### PR DESCRIPTION
**Pull request by pubudu91**
## Samples
```ballerina
import ballerina/io;

type Foo record {
    string a;
    int x;
    string...
};

public function main() {
    Foo f = {a: "foo"};
    string? indexAccess = f["rest"]; // index based access always returns `T|()`
    string fieldAccess = f.rest; // field based access returns T, but throws a runtime error if the key is not present.
}
```
Running the above results in the following output:
```
error: error, message: cannot find key 'rest'
	at main(rec.bal:12)
```

### CODE REVIEW

File: tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java [hunk 1]
```diff
@@ -318,6 +318,12 @@ public void testDocumentationNegative() {
                 "incompatible types: expected 'int', found 'float'", 70, 10);
         BAssertUtil.validateError(compileResult, 11,
                 "operator '+' not defined for 'int' and '(int,int)'", 76, 5);
+        BAssertUtil.validateError(compileResult, 12,
+                "operator '+' not defined for 'int?' and 'int?'", 93, 5);
```
Comment (Shan1024) [inline tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java]: Doesn't look like we need to have these in a newline.

File: tests/ballerina-unit-test/src/test/resources/test-src/expressions/fieldaccess/safe_navigation.bal [hunk 2]
```diff
@@ -4,12 +4,12 @@ type Person record {
     int a;
     string fname = "John";
     string lname;
-    Info|error info1;
+    Info|error|() info1;
```
Comment (Shan1024) [inline tests/ballerina-unit-test/src/test/resources/test-src/expressions/fieldaccess/safe_navigation.bal]: We can use `(Info|error)?` as well.

File: tests/ballerina-unit-test/src/test/resources/test-src/structs/anon-struct.bal [hunk 3]
```diff
@@ -49,5 +49,5 @@ function testAnonStructAsStructField() returns (string) {
     employee e = {fname:"sam", lname:"json", age:100,
                      address:{line01:"12 Gemba St APT 134", city:"Los Altos", state:"CA", zipcode:"95123"},
                     dateOfBirth:{}};
-    return e.dateOfBirth.month + ":" + e.address.line01 + ":" + e.address["state"] + ":" + e.fname;
+    return e.dateOfBirth.month + ":" + e.address.line01 + ":" + (e.address["state"] ?: "-") + ":" + e.fname;
 }
```
Comment (Shan1024) [inline tests/ballerina-unit-test/src/test/resources/test-src/structs/anon-struct.bal]: Missing newline at the end.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 4]
```diff
@@ -1084,14 +1084,23 @@ public void visit(BLangFieldBasedAccess fieldAccessExpr) {
         fieldAccessExpr.expr = rewriteExpr(fieldAccessExpr.expr);
         BLangLiteral stringLit = createStringLiteral(fieldAccessExpr.pos, fieldAccessExpr.field.value);
         BType varRefType = fieldAccessExpr.expr.type;
-        if (varRefType.tag == TypeTags.OBJECT || varRefType.tag == TypeTags.RECORD) {
+        if (varRefType.tag == TypeTags.OBJECT) {
+            if (fieldAccessExpr.symbol != null && fieldAccessExpr.symbol.type.tag == TypeTags.INVOKABLE
+                    && ((fieldAccessExpr.symbol.flags & Flags.ATTACHED) == Flags.ATTACHED)) {
```
Comment (Shan1024) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java]: Better to break the line after the operator.

File: tests/ballerina-unit-test/src/test/resources/test-src/expressions/fieldaccess/safe_navigation.bal (hunk 2 above)
Comment (pubudu91) [reply tests/ballerina-unit-test/src/test/resources/test-src/expressions/fieldaccess/safe_navigation.bal]: Not necessary in this case right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 5]
```diff
@@ -1812,6 +1827,20 @@ private BType checkStructFieldAccess(BLangVariableReference varReferExpr, Name f
             return symTable.errType;
         }
 
+        // If it's an index-based access, the return type is a nil-able.
+        if (varReferExpr.getKind() == NodeKind.INDEX_BASED_ACCESS_EXPR) {
+            Set<BType> types = new LinkedHashSet<>();
```
Comment (SupunS) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: I think logic is same as `checkTypeForIndexBasedAccess(...)`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 6]
```diff
@@ -2061,22 +2090,25 @@ private BType checkIndexAccessExpr(BLangIndexBasedAccess indexBasedAccessExpr, B
...
+                    String fieldName = (String) ((BLangLiteral) indexExpr).value;
+                    actualType = checkStructFieldAccess(indexBasedAccessExpr, names.fromString(fieldName), varRefType);
+                }
+                break;
             case TypeTags.RECORD:
                 indexExprType = checkIndexExprForStructFieldAccess(indexExpr);
                 if (indexExprType.tag == TypeTags.STRING) {
                     String fieldName = (String) ((BLangLiteral) indexExpr).value;
                     actualType = checkStructFieldAccess(indexBasedAccessExpr, names.fromString(fieldName), varRefType);
+                    actualType = checkTypeForIndexBasedAccess(indexBasedAccessExpr, actualType);
```
Comment (SupunS) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: As per my prev comment, if we can merge `checkTypeForIndexBasedAccess()` with `checkStructFieldAccess()`, then we can have only one case for both objects and records, like how we had previously.

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Need to keep these separate since `checkStructFieldAccess()` returns the type of the record field and it can return from multiple places in the method body.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 5 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: This code was unnecessary. Hence removed it.
