### PR TITLE
Fix not exposing symbols within on fail clause through semantic API 

### LINKED ISSUE #28189: On Fail variable definition not suggested within the clause
**Description:**
onFailVar

On fail variable definition is visible within its clause. Atm, the reference is not among the suggestions.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Swan Lake Alpha

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #28189

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java [hunk 1]
```diff
@@ -411,6 +411,14 @@ public void visit(BLangWhile whileNode) {
...
             this.acceptNode(whileNode.body, this.symbolEnv);
         }
+        visitOnFailClause(whileNode.onFailClause);
+    }
+
+    private void visitOnFailClause(BLangOnFailClause onFailClause) {
+        if (onFailClause != null) {
+            SymbolEnv onFailEnv = SymbolEnv.createOnFailEnv(onFailClause, this.symbolEnv);
+            this.acceptNode(onFailClause, onFailEnv);
+        }
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java:421]: Shouldn't this logic be in the visit() method for the on fail clause?

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java:421]: this was to avoid null check duplication within multiple nodes. we can move the environment creating to onfail visit if needed. wdyt?

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java:421]: this was to avoid null check duplication in multiple places

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java:421]: we can move the env creation to onfail clause if needed? wdyt?

Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java:421]: There won't be any duplication right? What I meant was to move this logic to the `visit(BLangOnFailClause)` method. And since the on fail clause seem to have a block stmt, I think we can just simply call `acceptNode(onFail.body, symbolEnv)` in the visit.

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java]: Updated in 1b130a542273ac48fa116aeee3fb56c14953dba2

**Comment by anupama-pathirage** [comment]
@pcnfernando The commit messages and PR heading is not according to the best practices. Please correct them.

A properly formed Git commit subject line should always be able to complete the following sentence:

If applied, this commit will your subject line here

Refer [1] for more details.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md#submit-your-contribution

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java [hunk 2]
```diff
@@ -411,6 +411,7 @@ public void visit(BLangWhile whileNode) {
             this.scope = this.symbolEnv;
             this.acceptNode(whileNode.body, this.symbolEnv);
         }
+        this.acceptNode(whileNode.onFailClause, symbolEnv);
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java:414]: The while stmt's pos includes the on fail clause right? If so, this call should be within the above if block.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java [hunk 3]
```diff
@@ -474,6 +479,7 @@ public void visit(BLangMatch matchNode) {
             this.scope = this.symbolEnv;
             matchNode.patternClauses.forEach(patternClause -> acceptNode(patternClause, this.symbolEnv));
         }
+        this.acceptNode(matchNode.onFailClause, symbolEnv);
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java:482]: Same comment as above regarding this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java [hunk 4]
```diff
@@ -222,13 +222,15 @@ public static SymbolEnv createRetryEnv(BLangRetry node, SymbolEnv env) {
     }
 
     public static SymbolEnv createOnFailEnv(BLangOnFailClause node, SymbolEnv env) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java:224]: Not exactly related to this PR. But if the on fail clause has a block stmt in it, do we need to be creating a separate env like this? Wouldn't it automatically be handled when analyzing the block stmt?

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java (hunk 2 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java]: Updated in b12ab10395f186458914384cb49212a460a18833

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java (hunk 4 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java]: Seems when the node changed, the environment creation was not reflected. Updated in b12ab10395f186458914384cb49212a460a18833

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolEnv.java:224]: It seems unless the OnFailClause is used to create the symbol environment, the variable definition symbol within on fail clause needs to be added manually while desugaring it to a lambda function. Hence reverted this change

**Review by mohanvive — APPROVED** [review]
