### PR TITLE
Fix readonly-ness of slice of readonly arrays

### LINKED ISSUE #30353: slice of readonly array should not be readonly
This program

```
public function main() {
   readonly & string[] roNames = ["x"];
   string[] rwNames = roNames.slice(0);
   rwNames[0] = "y";
}
```

gets a panic at runtime:

```
{ballerina/lang.array}InvalidUpdate {"message":"modification not allowed on readonly value"}
```

The spec isn't as clear as it should be here. But the declaration of `slice` does not say that the result should get its readonly-ness from the input. If the docs don't say to create something as readonly, then in general you shouldn't.

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #30353

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java [hunk 1]
```diff
@@ -801,27 +802,33 @@ public ArrayValueImpl slice(long startIndex, long endIndex) {
...
                 System.arraycopy(floatValues, (int) startIndex, slicedArray.floatValues, 0, slicedSize);
                 break;
             case TypeTags.STRING_TAG:
             case TypeTags.CHAR_STRING_TAG:
-                slicedArray = new ArrayValueImpl(new BString[slicedSize], arrayType.isReadOnly());
+                slicedArray = new ArrayValueImpl(new BString[slicedSize], false);
                 System.arraycopy(bStringValues, (int) startIndex, slicedArray.bStringValues, 0, slicedSize);
                 break;
             default:
+                if (this.elementType.getTag() == TypeTags.INTERSECTION_TAG) {
```
Comment (HindujaB) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java:826]: Shall we add this as a new case?
```java
case TypeTags.INTERSECTION_TAG:
```

**Review by warunalakshitha — APPROVED** [review]
