### PR TITLE
Fix missing error type in stream type's string representation

### LINKED ISSUE #21817: The string representation of stream type is incomplete
Consider the error message given for the following line of code:
```
stream<Student, sql:Error> result = customerDBEP->
        query("SELECT firstname FROM student WHERE registration_id = " +
                args[0], ());
```
The error:
```
error: .::taint_checking.bal:27:45: incompatible types: expected 'stream<Student>', found 'stream<record {| anydata...; |}>'
```
Note how only the record type is mentioned in the type's string representation. The error type is missing.

### PR DESCRIPTION
**Pull request by lasinicl**
Fixes #21817

Error message - Before bug fix
```
incompatible types: expected 'stream<Student>', found 'stream<record {| anydata...; |}>'
```
Error message - After bug fix
```
incompatible types: expected 'stream<Student,(ballerina/sql:DatabaseError|ballerina/sql:ApplicationError)>', found 'stream<record {| anydata...; |},(ballerina/sql:DatabaseError|ballerina/sql:ApplicationError)>'
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BStreamType.java [hunk 1]
```diff
@@ -70,7 +70,8 @@ public String toString() {
         if (constraint == BTypes.typeAny) {
             return super.toString();
         } else {
-            return "stream" + "<" + constraint.getName() + ">";
+            return super.toString() + "<" + constraint + ((TypeConstants.ERROR == null) ?
```
Comment (pcnfernando) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/types/BStreamType.java:73]: You don't need this change unless you can add the Error field to the class and populate it.

**Comment by mohanvive** [comment]
@pcnfernando can we merge this please?
@lasinicl can you please send this fix to 1.2.x branch as well (include a test case if possible)?
