### PR TITLE
Fix refactor the ballerina OpenAPI commands 

### LINKED ISSUE #25015: OpenAPI to Ballerina conversion needs to support Quoted Identifiers with special characters
**Description:**
The current OpenAPI to Ballerina tool does not support parsing special characters. The generated outcomes have deviations from the expected bal program.

**Steps to reproduce:**
Considering quoted identifiers in ballerina, there can be 3 places where we need to support.

Case 1 : operationId -> service resource function
```yaml
...
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets resource_!$:[;  
#This should generate a function with identifier " 'listPets\ resource_\!\$\:\[\;"
      tags:
        - pets
      parameters:
       ...
      responses:
...
```
Case 2 : component -> record type objects
```yaml
...
components:
  schemas:
    Pet_sample_!$:[; : 
#This should generate a record type object with identifier " 'Pet_sample_\!\$\:\[\;"
      required:
        - sample_resource_!$:[;_id
        #The object should have a field with identifier " 'sample_resource_\!\$\:\[\;_id"
        - name
      properties:
...
```
Case 3: service name argument in command line -> service name

The following command must generate a service with identifier `'sample_service_\ \!\:\[\;` (same as the argument)

`$BAL_HOME/bin/ballerina openapi gen-service petStore:sample_service_\ \!\:\[\; hello.openapi.yaml
`

Currently the special characters are replaced with `_`

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#18720 

**Suggested Labels (optional):**
Area/Tooling

**Suggested Assignees (optional):**

### LINKED ISSUE #25213: OpenAPI to ballerina conversion does not support non local references
Description:
I have an open api spec with models split out into separate yaml files and the service held in a resource file that access the models in "../models". However ballerina currently gives the following message when I try and generate:

```
ballerina openapi gen-service costcharging:ccsvc ./OpenApi/reference/mu-costcharging-svc.v1.yaml 
Note: This is an experimental tool, which only supports a limited set of functionality. 
error: Error occurred when generating service for openapi contract at
 ./OpenApi/reference/mu-costcharging-svc.v1.yaml. 
Invalid reference value : ../models/Costlet-Service-Request.v1.yaml Ballerina only supports local reference values..
```

My only work around is to flatten everything into a single file, however is there any chance that this is going to be addressed?

Suggested Labels:

Suggested Assignees:

Affected Product Version:
Ballerina 1.2.6
OS, Browser, other environment details and versions:
WSL2, Windows 10.
Steps to reproduce:
Create an open API spec that has non local references, try and run the ballerina openapi gen-service command.

Related Issues:

### LINKED ISSUE #25274: Refactor the Ballerina OpenAPI commands
**Description:**

Refactor OpenAPI service, client and code-generator commands to enhance the user experience with Ballerina OpenAPI Tool. 

- [x] Set the yaml contract file path in the generated service ballerina file for command execution location.
- [x] Recreate both service and client file with one command instead of the previous two commands.
- [x] Improve the command for creating a service file with the given service name.
- [x] Recreate code-generator command. 
- [x]  When service is created the openapi path should be relative to the bal file path of the service. 
- [x] If files already exist prompt the user if it is ok to overwrite.
- [x] Add support to tags and operationIds. 
     - -[x] tag handling : ballerina openapi --input openapi.yaml -o ./ --tags pet,user
     - -[x] operationId handling : ballerina openapi --input openapi.yaml -o ./ --operation-id getPets,
- [x] Adding command tags and operations to openApi annotation
- [x] Generate openApi specification for multiple services in ballerina file
- [ ] Update BBE

**Suggested Labels (optional):**
 Area/BuildTools,  Component/ToolSwagger ,  Type/Improvement

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
Fixes #25274 
Fixes #25015 
Fixes #25213 

- ballerina openapi --input swagger.yaml -o ./
> OpenApi spec generation command for given ballerina service
- ballerina openapi --input service.bal -o ./

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/openapi/openapitoballerina/CreateOpenApiServiceResourceMethodExecutor.java [hunk 1]
```diff
@@ -267,7 +268,14 @@ static OpenAPI parseOpenAPIFile(String definitionURI) {
             BallerinaOpenApiPath typePath = new BallerinaOpenApiPath();
 
             typePath.setPath(pathName);
-            typePath.setOperationsList(extractOpenApiOperations(pathObject.readOperationsMap(), pathName));
+
+            List<String> tag = new ArrayList<>();
+            List<String> operation = new ArrayList<>();
+//            List<String> tag = null;
```
Comment (azinneera) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/openapi/openapitoballerina/CreateOpenApiServiceResourceMethodExecutor.java:274]: Shall we remove these unnecessary comments?

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java [hunk 2]
```diff
@@ -17,47 +17,300 @@
...
+                    "contract at " + argList.get(0) + ". " + e.getMessage() + ".");
+        }
+    }
+
+    /**
+     * A util method to check a given module name actually exists in the current command location.
+     * @param moduleName - module name to be checked
+     * @return true if module exists.
+     */
+    private boolean checkModuleExist(String moduleName) {
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:310]: Shall we use the existing method to check instead of having a new one?

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/typemodel/BallerinaOpenApiType.java [hunk 3]
```diff
@@ -37,6 +38,24 @@
...
+
+    public List<Operation> getOperations() {
+        return operations;
+    }
+
+    public void setOperations(List<Operation> operations) {
+        this.operations = operations;
+    }
+
+    public List<Tag> getFilteredTags() {
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/typemodel/BallerinaOpenApiType.java:52]: This is not used anywhere. Shall we remove this?

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java [hunk 4]
```diff
@@ -48,4 +66,77 @@ public void testOpenAPICmdHelpWithoutFlag() throws IOException {
...
+
+        Stream<String> expectedSchemaLines = Files.lines(expectedSchemaFile);
+        String expectedSchemaContent = expectedSchemaLines.collect(Collectors.joining("\n"));
+        expectedSchemaLines.close();
+
+        if (Files.exists(resourcePath.resolve("petstoreClient.bal"))
+                && Files.exists(resourcePath.resolve("petstoreService.bal"))
+                && Files.exists(resourcePath.resolve("schema.bal"))) {
+
+//            Stream<String> serviceLines = Files.lines(resourcePath.resolve("petstoreService.bal"));
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java:124]: Shall we remove this commented lines?

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/test/resources/expected_gen/petstore_schema.bal [hunk 5]
```diff
@@ -1,16 +1,15 @@
...
-    int code;
-    string message;
+
+type Pet record {
+     int id;
+     string name;
+     string tag?;
+     string 'type?;
+};
+type Dog record {
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/test/resources/expected_gen/petstore_schema.bal:8]: Shall we leave a line between each record type?

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/test/resources/expected_gen/petstore_schema.bal [hunk 6]
```diff
@@ -1,16 +1,15 @@
...
-public type Error record { 
-    int code;
-    string message;
+
+type Pet record {
+     int id;
+     string name;
+     string tag?;
+     string 'type?;
+};
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/test/resources/expected_gen/petstore_schema.bal:7]: Shall we leave a line between each record type?

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/typemodel/BallerinaOpenApiType.java (hunk 3 above)
Comment (lnash94) [reply misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/typemodel/BallerinaOpenApiType.java:52]: `operatoins` attribute I used for the future purpose of implementation. Need to have some clarification with team its further implementation.

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/Filter.java [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+    public Filter(List<String> tags, List<String> operations) {
+        this.tags = tags;
+        this.operations = operations;
+    }
+
+    public List<String> getTags() {
+        return tags;
+    }
+
+    public void setTags(List<String> tags) {
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/Filter.java:37]: Seems not used anywhere. Shall we remove this?

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java [hunk 8]
```diff
@@ -17,47 +17,300 @@
...
+    /**
+     * A util to generate service file.
+     * @param generator     generator object
+     * @param serviceName   service name uses for naming the generated file
+     * @param resourcePath  resource Path
+     */
+    private void generateServiceFile(CodeGenerator generator, String serviceName, Path resourcePath, Filter filter) {
+
+        try {
+            assert resourcePath != null;
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:273]: What if resourcePath is null?

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 9]
```diff
@@ -60,18 +74,22 @@ EXAMPLES
...
+          $ ballerina openapi -i hello_service.bal --serviceName hello -o ./
+
+       Generate both Ballerina client and service file.
+          $ballerina openapi --input petstore.yaml -o ./example
+
+       Generate services for given tags
+          $ ballerina openapi -i hello.yaml --mode service --tags pets
+
+       Generate services for given operations
+                 $ ballerina openapi -i hello.yaml --mode service --operations listPets
```
Comment (suganyasuven) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:95]: Please add EOF

File: misc/openapi-ballerina/modules/ballerina-to-openapi-generator/src/main/java/org/ballerinalang/ballerina/openapi/convertor/service/OpenApiConverterUtils.java [hunk 10]
```diff
@@ -385,9 +387,66 @@ public static void generateOAS3Definitions(Path servicePath, Path outPath, Strin
         String openApiName = getOpenApiFileName(servicePath, serviceName);
 
         String openApiSource = generateOAS3Definitions(balSource, serviceName);
+        openApiName = checkDuplicateFiles(outPath, openApiName);
         writeFile(outPath.resolve(openApiName), openApiSource);
     }
 
+    /**
+     * This util for generating files when not available with specific service name.
+     * @param servicePath               resource path
```
Comment (azinneera) [inline misc/openapi-ballerina/modules/ballerina-to-openapi-generator/src/main/java/org/ballerinalang/ballerina/openapi/convertor/service/OpenApiConverterUtils.java:396]:
```suggestion

     * @param servicePath               resource path
```

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java [hunk 11]
```diff
@@ -17,47 +17,300 @@
...
+     * @param fileName  input resource file
+     */
+    private void ballerinaToOpenApi(String fileName) {
+        final File balFile = new File(fileName);
+        String serviceName = service;
+        getTargetOutputPath();
+        Path resourcePath = getResourcePath(balFile, this.targetOutputPath.toString());
+        //ballerina openapi -i service.bal --serviceName serviceName --module exampleModul -o ./
+        // Check service name it is mandatory
+        if ((module != null) && (service != null)) {
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:154]:
```suggestion
        if (module != null && service != null) {
```

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java (hunk 8 above)
Comment (lnash94) [reply misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:273]: It will handle by an exception.

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/utils/TypeExtractorUtil.java [hunk 12]
```diff
@@ -396,8 +432,13 @@ public static String escapeIdentifier(String identifier) {
             if (identifier.equals("error")) {
                 identifier = "_error";
             } else {
-                identifier = identifier.replaceAll("([\\\\?!<>*\\-=^+()_{}|.$])", "$1");
+                identifier = identifier.replaceAll("([\\[\\]\\\\?!<>@#&~`*\\-=^+();:\\_{}\\s|.$])", "\\\\$1");
```
Comment (NipunaRanasinghe) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/utils/TypeExtractorUtil.java:435]: Shall we consider using this regex as a constant, as I've noticed that this same pattern is duplicated in few other places as well. WDYT?

File: misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java [hunk 13]
```diff
@@ -17,47 +17,300 @@
...
+     * @return path of given resource file
+     */
+    private Path getResourcePath(File resourceFile, String targetOutputPath) {
+        Path resourcePath = null;
+        Path relativePath = null;
+        try {
+            resourcePath = Paths.get(resourceFile.getCanonicalPath());
+            relativePath =
+                    Paths.get(new File(targetOutputPath).toURI().relativize(new File(resourcePath.toString()).toURI())
+                            .getPath());
```
Comment (NipunaRanasinghe) [inline misc/openapi-ballerina/modules/openapi-to-ballerina-generator/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java:223]: Shall we format these lines properly?

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 14]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
        Note: This is an experimental tool, which only supports a limited
        set of functionality.
 
+OPTIONS
+        (-i| --input) <openapi-contract> | <ballerina service file>
+            This is mandatory input. Openapi contract as a given input will generate a Ballerina service and client
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:23]:
```suggestion
            This is a mandatory input. The given OpenAPI contract input will generate a Ballerina service and the client
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 15]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+            stub files for given openapi contract. This generated service can be used as a code template
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:24]:
```suggestion
            stub files for the given OpenAPI contract. This generated service can be used as a code template
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 16]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+            to start the service implementation. Generated sources contain a service definition, schema definition and
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:25]:
```suggestion
            to start the service implementation. Generated sources contain a service definition, schema definition, and
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 17]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+            a copy of the OpenAPI contract which is used for the template generation. Generated client stub is used to
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:26]:
```suggestion
            a copy of the OpenAPI contract, which is used for the template generation. The generated client stub is used to
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 18]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+            start the client application implementation to call the service defined in the OpenAPI file.
+            Ballerina service file as a given input will generate the relevant openApi specification for the service
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:28]:
```suggestion
            The given Ballerina service file input will generate the relevant OpenAPI specification for the service
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 19]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
-           which is used for the template generation.
-
-       gen-client
-           Generate a Ballerina client stub for the service defined
-           in the OpenAPI file. Generated client stub is used to start the
-           client application implementation to call the service defined in
-           the OpenAPI file.
+        (-o| --output) <target location>
+            Location of the generated Ballerina source code. If this path is not specified,
+            the output will be written onto the same directory from where the command is run.
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:33]:
```suggestion
            the output will be written to the same directory from which the command is run.
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 20]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+
+        (--mode) <mode-type>
+            Mode type can be service or client. Generate a ballerina service and client only
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:36]:
```suggestion
            Mode type can be `service` or `client`. This generates a Ballerina service and client only
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 21]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+            according to the mode. This is optional input.
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:37]:
```suggestion
            according to the mode. This is an optional input.
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 22]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+
+        (-m| --module) <module name>
+            This use when ballerina file convert to openapi contract
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:40]:
```suggestion
            This is used when a Ballerina file converts to an OpenAPI contract
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 23]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+
+        (--service-name) <service name>
+            This use for allocating specific user-given name to generated service and client stub according to openapi
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:43]:
```suggestion
            This is used for allocating specific user-given name to the generated service and client stub according to the OpenAPI
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 24]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+            contract. This option uses with the command of openApi to ballerina file generation.
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:44]:
```suggestion
            contract. This option is used with the command of OpenAPI to Ballerina file generation.
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 25]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+
+
+        (-s| --service ) <current service name>
+            This service name is used to identify the service that need to documented as openApi specification. This
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:48]:
```suggestion
            This service name is used to identify the service that needs to be documented as per the OpenAPI specification. This
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 26]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+            option uses with the command of ballerina to openApi specification generation.
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:49]:
```suggestion
            option is used with the command of the Ballerina to OpenAPI specification generation.
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 27]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
 
+        (--tags) <tag names>
+            This tags use to filter the operations tag need to generate services. This option uses with command
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:52]:
```suggestion
            This tags are used to filter the operations tags that are needed to generate services. This option is used with the command
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 28]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+            of openApi to ballerina file generation.
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:53]:
```suggestion
            of OpenAPI to Ballerina file generation.
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 29]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+
+        (--operations) <operation names>
+            This operations use to filter the operations wise need to generate services. This option uses with command
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:56]:
```suggestion
            These operations are used to filter the operations that are needed to generate services. This option is used with the command
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 30]
```diff
@@ -28,21 +18,45 @@ DESCRIPTION
...
+            of openApi to ballerina file generation.
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:57]:
```suggestion
            of the OpenAPI to Ballerina file generation.
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 31]
```diff
@@ -60,18 +74,22 @@ EXAMPLES
...
        Generate a Ballerina client with client name helloclient
        and write the output to the client_project folder.
-          $ ballerina openapi gen-client helloclient hello.yaml -o client_project
+          $ ballerina openapi -i hello.yaml --mode client
 
        Export an OpenAPI definition for hello_service.bal for the hello service.
-          $ ballerina openapi gen-contract hello -i hello_service.bal
+          $ ballerina openapi -i hello_service.bal --serviceName hello -o ./
+
+       Generate both Ballerina client and service file.
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:88]:
```suggestion
       Generate both the Ballerina client and service file.
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 32]
```diff
@@ -60,18 +74,22 @@ EXAMPLES
           $ ballerina openapi
           $ ballerina openapi -h
 
-       Print usage details of the OpenAPI sub commands.
-          $ ballerina openapi gen-service -h
-          $ ballerina openapi gen-client -h
-          $ ballerina openapi gen-contract -h
-
        Generate a Ballerina mock service with module name hellomock
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:77]:
```suggestion
       Generate a Ballerina mock service with the module name `hellomock`
```

File: cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help [hunk 33]
```diff
@@ -60,18 +74,22 @@ EXAMPLES
...
        and service name hello using hello.yaml OpenAPI contract.
```
Comment (praneesha) [inline cli/ballerina-tool/src/main/resources/cli-help/ballerina-openapi.help:78]:
```suggestion
       and service name `hello` using the `hello.yaml` OpenAPI contract.
```

**Review by hevayo — APPROVED** [review]
