### PR TITLE
Add test cases to verify fix for 28348

### LINKED ISSUE #28348: Invalid "incompatible types" error
This gets an "incompatible types" error in alpha1

```
import ballerina/io;

type X record {
   int x;
};

json j = { x: 1};

public function main() returns error? {
   json r = j.cloneReadOnly();
   X x = <X>r;
   io:println(x.x);
}
```

I don't see anything wrong with it.

It compiles (and works) if I change the offending line to:

```
X x = <X><anydata>r;
```

### PR DESCRIPTION
**Pull request by KRVPerera**
## Purpose
Add test cases for already fixed issue

Fixes #28348

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/MapToRecordAssignabilityTest.java [hunk 1]
```diff
@@ -97,6 +97,8 @@ public void testComplexSubtyping2() {
                 {"testBasicDataTypeMaps"},
                 {"testInclusiveRecordTypes"},
                 {"testRecordsWithOptionalFields"},
+                {"testImmutableJsonMappingToExclusiveRecord"},
+                {"testImmutableJsonMappingToInclusiveRecord"},
         };
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/MapToRecordAssignabilityTest.java:102]: Since we are testing casting here, IMO, we should move this to a type cast test.

File: tests/jballerina-unit-test/src/test/resources/test-src/record/map_to_record.bal [hunk 2]
```diff
@@ -177,6 +177,23 @@ function testComplexSubtyping2() {
     gR.x = rC;
 }
 
+json jsonMapping = {a : 1};
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/map_to_record.bal:180]:
```suggestion
json jsonMapping = {a: 1};
```

File: tests/jballerina-unit-test/src/test/resources/test-src/record/map_to_record.bal [hunk 3]
```diff
@@ -177,6 +177,23 @@ function testComplexSubtyping2() {
...
+
+function testImmutableJsonMappingToExclusiveRecord() {
+    json readonlyJsonMapping = jsonMapping.cloneReadOnly();
+    Bar intBar = <Bar>readonlyJsonMapping;
+    assert(1, intBar.a);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/map_to_record.bal:185]: Shall we add negative runtime tests also? 

```
Bar|error res = trap <Bar>mapping; // and assert error
```

Comment (KRVPerera) [reply tests/jballerina-unit-test/src/test/resources/test-src/record/map_to_record.bal]: Please check now 751bc346250f938df72c4a123829017d1a9aca79

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/MapToRecordAssignabilityTest.java (hunk 1 above)
Comment (KRVPerera) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/record/MapToRecordAssignabilityTest.java]: done

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type_cast_expr.bal [hunk 4]
```diff
@@ -831,3 +831,42 @@ function testContexuallyExpectedType() returns Employee {
...
+    int a;
+|};
+
+function testImmutableJsonMappingToExclusiveRecordPositive() {
+    json readonlyJsonMapping = jsonMapping.cloneReadOnly();
+    Bar intBar = <Bar>readonlyJsonMapping;
+    assert(1, intBar.a);
+}
+
+function testImmutableJsonMappingToInclusiveRecordPOsitive() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/typecast/type_cast_expr.bal:852]:
```suggestion
function testImmutableJsonMappingToInclusiveRecordPositive() {
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java [hunk 5]
```diff
@@ -354,6 +361,19 @@ public void testUntaintedWithoutType2() {
         Assert.assertEquals(((BMap) returns[0]).get("id").stringValue(), "1100");
     }
 
+    @DataProvider
+    public Object[] mappingToRecordTests() {
+        return new Object[]{
+                "testImmutableJsonMappingToExclusiveRecordPositive",
+                "testImmutableJsonMappingToInclusiveRecordPOsitive"
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java:368]:
```suggestion
                "testImmutableJsonMappingToInclusiveRecordPositive"
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java [hunk 6]
```diff
@@ -183,6 +183,13 @@ public void testDirectlyUnmatchedUnionToUnionCastNegativeTwo() {
         BRunUtil.invoke(result, "testDirectlyUnmatchedUnionToUnionCastNegative_2");
     }
 
+    @Test(expectedExceptions = BLangRuntimeException.class,
+            expectedExceptionsMessageRegExp = "error: \\{ballerina\\}TypeCastError \\{\"message\":\"incompatible " +
+                    "types: 'map<json>' cannot be cast to 'Bar'.*")
+    public void testMutableJsonMappingToExclusiveRecordNegative() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java:189]: We can use trap and assert this in b7a itself?

Comment (hasithaa) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java:189]: +1, Let's improve this test case like that.

**Review by hasithaa — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java (hunk 6 above)
Comment (KRVPerera) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/typecast/TypeCastExpressionsTest.java]: Updated the test case.

**Review by MaryamZi — APPROVED** [review]
