### PR TITLE
Fix invalid function type qualifier stored location in ST

### LINKED ISSUE #31946: Invalid token stored in wrong location in the ST for the invalid code
**Description:**
Consider the following code snippet.
```bal
function testFunctionTypedescWithTransactionalQualifier() {
    transactional function func;
}
```
It is parsed as below,
```bal
function testFunctionTypedescWithTransactionalQualifier() {
    function INVALID[transactional] func;
}
```
Invalid `transactional` keyword should be in the leading minutiae of `function` keyword.

This will fix the TODO added to `org.ballerinalang.test.types.function.AnyFunctionTypeTest.testAnyFunctionTypeNegative` test in PR #31933

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #31946 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -10721,15 +10726,16 @@ private STNode createFuncTypeQualNodeList(List<STNode> qualifierList, boolean ha
...
+                functionKeyword = SyntaxErrors.cloneWithLeadingInvalidNodeMinutiae(functionKeyword, qualifier,
+                        DiagnosticErrorCode.ERROR_QUALIFIER_NOT_ALLOWED, ((STToken) qualifier).text());
             } else {
                 updateANodeInListWithLeadingInvalidNode(qualifierList, nextIndex, qualifier,
                         DiagnosticErrorCode.ERROR_QUALIFIER_NOT_ALLOWED, ((STToken) qualifier).text());
             }
         }
 
-        return STNodeFactory.createNodeList(validatedList);
+        STNode nodeList = STNodeFactory.createNodeList(validatedList);
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:10737]: Any test case to cover this line?

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:10737]: Seems the no coverage is false positive. It would be impossible to call `createFuncTypeQualNodeList()` without reaching this line right?

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:10737]: Yeah :-D

**Review by rdulmina — APPROVED** [review]
