### PR TITLE
Fix several recovery scenarios triggering fail-safe mechanism

### LINKED ISSUE #29947: Fix all LS tests hitting the fail safe mechansim
**Description:**
Address the TODO added with https://github.com/ballerina-platform/ballerina-lang/pull/29874/commits/d4fcd8df553efd0683beae91be6141f6fcccef24 in PR #29874

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #29947 

## Approach
N/A

## Samples
Source:
```bal
function testIterableOperation() {
    string outputNameString = from var person in personList
                              join//<cursor>
}

type Person record {|
    string firstName;
    string lastName;
    int age;
|};

```
Old recovery:
```bal
function testIterableOperation() {
    string outputNameString = from var person in personList
                              join MISSING[object] MISSING[{]} INVALID[type] Person 
                              MISSING[in] MISSING[<]record {|
                                                      string firstName;
                                                      string lastName;
                                                      int age;
                                                    |} MISSING[>] MISSING[]
                              MISSING[on] MISSING[] MISSING[equals] MISSING[]
                              MISSING[select] MISSING[] MISSING[;]
MISSING[}] INVALID[;]
```
New recovery:
```bal
function testIterableOperation() {
    string outputNameString = from var person in personList
                              join MISSING[] MISSING[] MISSING[in] MISSING[]
                              MISSING[on] MISSING[] MISSING[equals] MISSING[]
                              MISSING[select] MISSING[] MISSING[;]
}

type Person record {|
    string firstName;
    string lastName;
    int age;
|};
```

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -2437,8 +2437,16 @@ private STNode parseTypeDescriptorInternal(List<STNode> qualifiers, ParserRuleCo
...
                     return parseSimpleTypeDescriptor();
                 }
+                
+                nextToken = peek();
+                if (isRecoveryAtFuncBodyEnd(nextToken)) {
+                    // Special case the func-body-block end.
+                    STNode identifier = SyntaxErrors.createMissingTokenWithDiagnostics(SyntaxKind.IDENTIFIER_TOKEN,
+                            DiagnosticErrorCode.ERROR_MISSING_TYPE_DESC);
+                    return STNodeFactory.createSimpleNameReferenceNode(identifier);
+                }
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:2447]: Can u add an example as a comment

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java [hunk 2]
```diff
@@ -134,6 +134,8 @@ public void test(String fileName, String path) throws IOException {
                 "assignment_stmt_source_11.bal", "assignment_stmt_source_10.bal", "assignment_stmt_source_14.bal",
                 "match_stmt_source_09.bal", "match_stmt_source_13.bal", "match_stmt_source_04.bal",
                 "match_stmt_source_15.bal", "match_stmt_source_03.bal", "match_stmt_source_16.bal",
+                "match_stmt_source_06.bal", "match_stmt_source_07.bal", "match_stmt_source_11.bal",
```
Comment (nadeeshaan) [inline misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java:137]: Any specific reason to disable these test cases? Since these we passing earlier, shall we have a look at it @IrushiL ?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java (hunk 2 above)
Comment (lochana-chathura) [reply misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java:137]: The above line was already there. I only replaced it from L156 to here. And only "match_stmt_source_19.bal" was added newly which is a new test case.

**Review by rdulmina — APPROVED** [review]
Parser changes LGTM

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java (hunk 2 above)
Comment (lochana-chathura) [reply misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java:137]: "match_stmt_source_19.bal" also enabled with 1613179.

Comment (nadeeshaan) [reply misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/ParserTestFormatter.java:137]: +1

**Review by nadeeshaan — APPROVED** [review]
LGTM

**Review by hasithaa — APPROVED** [review]
