### PR TITLE
Fix issue in safe navigation

### LINKED ISSUE #10000: Error lifting on json converted xml fails with class cast exception
**Description:**
Following error lifting scenario fails.

```ballerina
import ballerina/io;
function main (string... args) {
    Contact contact = {};
    xml xml1 = xml `<entry>
                    <id>1234</id>
                    <updated>yes</updated>
                    <title>Some</title>
                   </entry>`;

    json json1 = xml1.toJSON({});
    contact = check <Contact>json1;
    string|error str = contact!entry!id;
    io:println(str);
}

type Entry record {
    string|error id;
};

type Contact record {
    Entry|error entry;
};

```

Error from the compiler.

```
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BConversionOperatorSymbol
        at org.wso2.ballerinalang.compiler.desugar.Desugar.addConversionExprIfRequired(Desugar.java:2283)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.getMatchPatternBody(Desugar.java:2247)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:2232)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:2202)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:873)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:61)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1933)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:1943)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:549)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1933)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1735)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:1918)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1144)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangFieldBasedAccess.accept(BLangFieldBasedAccess.java:58)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:1918)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:539)
        at org.wso2.ballerinalang.compiler.tree.BLangVariable.accept(BLangVariable.java:91)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:555)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangVariableDef.accept(BLangVariableDef.java:42)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1933)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:1943)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:549)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1933)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:429)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:66)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1950)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:295)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:150)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1893)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:255)
        at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:196)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:167)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:139)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:154)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:173)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:85)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
        at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:258)
        at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:87)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:66)
```

### LINKED ISSUE #12308: Error lifting operator on xml type makes the compiler crash
**Description:**
Man, it took me a few hours to isolate this compiler crash from a fairly complex project, but I finally did it!
This is the smallest sample of code reproducing the crash, just type `ballerina build compiler_crash.bal` to get this
````
Compiling source
    compiler_crash.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
````

**Steps to reproduce:**
Here is the file `compiler_crash.bal`
```
function crash(xml obj) {
    _ = obj!getTextValue();
}
```
and the generated `ballerina-internal.log`
```
[2018-12-03 23:58:26,676] ERROR {org.ballerinalang.launcher.Main} - org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BConversionOperatorSymbol 
java.lang.ClassCastException: org.wso2.ballerinalang.compiler.semantics.model.symbols.BSymbol cannot be cast to org.wso2.ballerinalang.compiler.semantics.model.symbols.BConversionOperatorSymbol
	at org.wso2.ballerinalang.compiler.desugar.Desugar.addConversionExprIfRequired(Desugar.java:2337)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.getMatchPatternBody(Desugar.java:2299)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:2284)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:2254)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:865)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:61)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:2034)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:2044)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:638)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:2034)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1825)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:2019)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1223)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:108)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:2019)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:666)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:2034)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:2044)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:638)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:2034)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:526)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:66)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:2051)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:403)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:150)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:1994)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:264)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:211)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:178)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:145)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:112)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:100)
	at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:70)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:162)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.ballerinalang.launcher.Main.main(Main.java:65)
```

**Affected Versions:**
0.983.0
0.983.1-SNAPSHOT (Dec 01, 2018)

**OS, DB, other environment details and versions:**
Windows 10

**Related Issues (optional):**
Issues #6693 and #10000

**Suggested Labels (optional):**
Type/Bug, Component/Compiler

### LINKED ISSUE #12495: Issue in safe navigation
**Description:**
```ballerina
function test(json obj) {
    _ = obj!toString();
}
```

```
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types$3.visit(Types.java:1358)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types$3.visit(Types.java:1150)
	at org.wso2.ballerinalang.compiler.semantics.model.types.BErrorType.accept(BErrorType.java:43)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.getConversionOperator(Types.java:882)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveConversionOperator(SymbolResolver.java:285)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.addConversionExprIfRequired(Desugar.java:3636)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.getMatchPatternBody(Desugar.java:3559)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:3495)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.generateIfElseStmt(Desugar.java:3468)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1518)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:89)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3224)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:3234)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:633)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3224)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2765)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:3209)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:2012)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:112)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:3209)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1059)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:81)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3224)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:3234)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:633)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3224)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:564)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:68)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3241)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:438)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:159)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:3184)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:297)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:208)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:171)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:133)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:102)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:161)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:326)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:238)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:205)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:217)
	at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:117)
	at org.ballerinalang.test.access.AccessLevelsNegativeTest.testPrivateAccessLevel(AccessLevelsNegativeTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

### PR DESCRIPTION
**Pull request by Shan1024**
Don't merge.

## Purpose
Resolves #10000
Resolves #12308
Resolves #12495

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -957,6 +963,9 @@ public void visit(BLangInvocation iExpr) {
         }
 
         BType varRefType = iExpr.expr.type;
+
+        checkSafeNavigation(iExpr, varRefType);
+
         varRefType = getSafeType(varRefType, iExpr);
```
Comment (SupunS) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: We should get the safe type only if checkSafeNavigation() check passes...
Otherwise `varRefType = symTable.semanticError`

Same for all places

Comment (Shan1024) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Changed with https://github.com/ballerina-platform/ballerina-lang/pull/12507/commits/0e634983cff6a5fdd707a28026920b7f4de7d3e4.
