### PR TITLE
Fix bala resolution when download is interrupted

### LINKED ISSUE #34939: Killing `bal pull` while the package is downloading leaves a partially written bala in the repo
**Description:**
$subject and due to this the subsequent commands are failing. Deleting the bala manually is the only way to recover. We should first download to a temp location and copy it to the correct location when the download is successful. 

**Steps to reproduce:**

1. Run `bal pull ballerinax/redis:2.1.1` and kill the process (`Ctrl + C`) while its getting downloaded.
2. Run `bal build`
    This will produce the following output:
```
Compiling source
	user/foo:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-02-03 13:46:36,424] SEVERE {b7a.log.crash} - invalid bala file: /home/user/.ballerina/repositories/central.ballerina.io/bala/ballerinax/redis/2.1.1/java11 
io.ballerina.projects.exceptions.InvalidBalaException: invalid bala file: /home/user/.ballerina/repositories/central.ballerina.io/bala/ballerinax/redis/2.1.1/java11
	at io.ballerina.projects.internal.ProjectFiles.validateBalaProjectPath(ProjectFiles.java:286)
	at io.ballerina.projects.internal.PackageConfigCreator.createBalaProjectConfig(PackageConfigCreator.java:95)
	at io.ballerina.projects.bala.BalaProject.loadProject(BalaProject.java:55)
	at io.ballerina.projects.internal.repositories.FileSystemRepository.getPackage(FileSystemRepository.java:109)
	at io.ballerina.projects.internal.repositories.RemotePackageRepository.getPackage(RemotePackageRepository.java:98)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolveFromRepository(DefaultPackageResolver.java:216)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolvePackage(DefaultPackageResolver.java:178)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.lambda$resolvePackages$3(DefaultPackageResolver.java:169)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolvePackages(DefaultPackageResolver.java:170)
	at io.ballerina.projects.PackageResolution.buildPackageGraph(PackageResolution.java:316)
	at io.ballerina.projects.PackageResolution.resolveSourceDependencies(PackageResolution.java:273)
	at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:212)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:92)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:99)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:248)
	at io.ballerina.projects.PackageCompilation.<init>(PackageCompilation.java:74)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:108)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
	at io.ballerina.projects.Package.getCompilation(Package.java:145)
	at io.ballerina.projects.Package.runCodeGeneratorPlugins(Package.java:250)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:84)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:249)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
3. Rerun `bal pull ballerinax/redis:2.1.1`
This will produce the following output:
```
package already exists in the home repository: /home/user/.ballerina/repositories/central.ballerina.io/bala/ballerinax/redis/2.1.1/java11
```
**_Note: Step 2 and 3 are independent to each other. Both are caused by step 1_**

**Affected Versions:**
2201.0.0

### PR DESCRIPTION
**Pull request by Ibaqu**
Fixes #34939 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java [hunk 1]
```diff
@@ -129,9 +130,23 @@ public static void createBalaInHomeRepo(Response balaDownloadResponse, Path pkgP
                     logFormatter.formatLog("error accessing bala : " + balaCacheWithPkgPath.toString()));
         }
 
-        createBalaFileDirectory(balaCacheWithPkgPath, logFormatter);
-        writeBalaFile(balaDownloadResponse, balaCacheWithPkgPath.resolve(balaFile), pkgOrg + "/" + pkgName +
+        // Create the following temp path bala/<org-name>/<pkg-name>/<pkg-version>/temp
+        Path tempPath = pkgPathInBalaCache.resolve(validPkgVersion).resolve("temp");
```
Comment (azinneera) [inline cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java:134]: In FileSystemRepository, we check for the availability of packages by version directory. There can be invalid balas captured as valid with this temp directory structure. Shall we take the temp directory as `bala/<org-name>/<pkg-name>/<pkg-version>temp` (e.g. ballerina/io/1.2.1temp) to avoid this?

File: cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java [hunk 2]
```diff
@@ -129,9 +130,23 @@ public static void createBalaInHomeRepo(Response balaDownloadResponse, Path pkgP
...
+        createBalaFileDirectory(tempPath, logFormatter);
+
+        // Write balaFiles to tempPath
+        writeBalaFile(balaDownloadResponse, tempPath.resolve(balaFile),
```
Comment (azinneera) [inline cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java:138]: What happens when there is a temp location is left over from the previous run? Does it override?

Comment (Ibaqu) [reply cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java:138]: Since we are renaming the `temp` file, if it runs successfully there wont be any leftovers. However, if there is an issue, and a temp file remains, it will be overwritten with the newly downloaded deps and it will attempt to rename the temp folder again

File: cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java (hunk 1 above)
Comment (Ibaqu) [reply cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java]: As suggested, i am now modifying the version folder with an appended temp. When the files are written to the platform directory, the version folder is renamed.

**Review by azinneera — DISMISSED** [review]

**Review by azinneera — APPROVED** [review]
