### PR TITLE
Fix a issue where a stream in a stream array does not behave as expected

### LINKED ISSUE #13406: Adding elements to a streams array
**Description:**
The following code breaks when trying to insert a new stream.
```ballerina
stream<int>[] intStreamArray = [];
intStreamArray[0] = new;
```
On a side note should we allow creating stream arrays?

### PR DESCRIPTION
**Pull request by gimantha**
Fixes #13406

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamValue.java [hunk 1]
```diff
@@ -35,36 +35,29 @@
...
-        /*if (constraintType instanceof BIndexedType) {
-            this.topicName = TOPIC_NAME_PREFIX + ((BIndexedType) constraintType).getElementType() + "_" + name;
-        } */
-
         if (constraintType != null) {
-            this.topicName = TOPIC_NAME_PREFIX + constraintType + "_" + name;
+            this.streamId = STREAM_NAME + constraintType;
         } else {
-            this.topicName = TOPIC_NAME_PREFIX + name; //TODO: check for improvement
+            this.streamId = STREAM_NAME; //TODO: check for improvement
```
[the remark this answers is not in the document]
Comment (gimantha) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamValue.java]: +1

**Comment by gimantha** [comment]
> Shall we also add a test for newing up a stream as an argument?
> 
> ```ballerina
> public function main() {
>     takeStream(new);
> }
> 
> function takeStream(stream<int> s) {
>     
> }
> ```

+1

File: compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal [hunk 2]
```diff
@@ -638,11 +638,13 @@ function generateBasicBlocks(jvm:MethodVisitor mv, bir:BasicBlock?[] basicBlocks
             } else if (inst is bir:NewMap) {
                 instGen.generateMapNewIns(inst);
             } else if (inst is bir:NewTypeDesc) {
-                instGen.generateNewTypedescIns(inst);
+                 if (inst.kind == bir:INS_KIND_NEW_TYPEDESC) {
```
Comment (MaryamZi) [inline compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal]: This is due to `NewStream` being structurally equivalent to `NewTypeDesc` I assume?

Wondering if instead, we should update `NewStream` to have a field of a different name (maybe rename `typeValue` as `constraint`) so that it isn't structurally equivalent to `NewTypeDesc`?

Both stream and typedesc going in the same path doesn't seem right?

Comment (gimantha) [reply compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal]: This is not the constraint.. it is the streamType. may be streamType or sType?

Comment (MaryamZi) [reply compiler/ballerina-backend-jvm-old/src/main/ballerina/compiler_backend_jvm/jvm_method_gen.bal]: +1
