### PR TITLE
Fix Improve semantic analyzing support in documentations

### LINKED ISSUE #9704: Improve semantic analyzing support in documentations
**Description:**
Only the parameters, fields and return value are validated. Content in **`` `...` ``** are not validated. 

## Spec

BFM also provides conventions for referring to Ballerina-defined names from within documentation strings in a source file. An identifier in backticks `X`, when preceded by one of the following words:

- type
- endpoint
- service
- variable
- var
- annotation
- module
- function
- parameter

is assumed to be a reference to a Ballerina-defined name of the type indicated by the word. In the case of parameter, the name must be unqualified and be the name of a parameter of the function to which the documentation string is attached. For other cases, if the name is unqualified it must refer to a public name of the appropriate type in the source file's module; if it is a qualified name M:X, then the source file must have imported M, and X must refer to a public name of an appropriate type in M. BFM also recognizes `f()` as an alternative to function `f`. In both cases, f can have any of the following forms (where m is a module import, x is a function name, t is an object type name, and y is a method name):

```ballerina
    x()
    m:x()
    t.y()
    m:t.y()
```

**Example**

    # Adds parameter `x` and parameter `y`
    # + x - one thing to be added
    # + y - another thing to be added
    # + return - the sum of them
    function add (int x, int y) returns int  { return x + y; }

### PR DESCRIPTION
**Pull request by dulvinw**
## Purpose
Validating documentation References
Fixes #9704

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
+/*
+ *  Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java]: License Version number upgrade

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+package org.ballerinalang.model.tree.expressions;
+
+import org.ballerinalang.model.tree.types.DocumentationReferenceType;
+import org.wso2.ballerinalang.compiler.semantics.model.symbols.BVarSymbol;
+
+/**
+* Interface to extend to make a node Documentable.
+*
+* @since 1.0.2
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java]: Version number 1.1.0

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+ *  under the License.
+ */
+
+package org.ballerinalang.model.tree.expressions;
+
+import org.ballerinalang.model.tree.types.DocumentationReferenceType;
+import org.wso2.ballerinalang.compiler.semantics.model.symbols.BVarSymbol;
+
+/**
+* Interface to extend to make a node Documentable.
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java]: Documentable -> documentable

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+ *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ *  KIND, either express or implied.  See the License for the
+ *  specific language governing permissions and limitations
+ *  under the License.
+ */
+
+package org.ballerinalang.model.tree.expressions;
+
+import org.ballerinalang.model.tree.types.DocumentationReferenceType;
+import org.wso2.ballerinalang.compiler.semantics.model.symbols.BVarSymbol;
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java]: do not refer to implementations

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+*/
+public interface MarkdownDocumentationBReferenceAttributeNode extends ExpressionNode {
+
+    String getReferenceName();
+
+    void setReferenceName(String referenceName);
+
+    BVarSymbol getSymbol();
+
+    void setSymbol(BVarSymbol symbol);
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java]: No need as of now for implememntations

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+
+import org.ballerinalang.model.tree.types.DocumentationReferenceType;
+import org.wso2.ballerinalang.compiler.semantics.model.symbols.BVarSymbol;
+
+/**
+* Interface to extend to make a node Documentable.
+*
+* @since 1.0.2
+*/
+public interface MarkdownDocumentationBReferenceAttributeNode extends ExpressionNode {
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java]: Refactor name

Comment (dulvinw) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/expressions/MarkdownDocumentationBReferenceAttributeNode.java]: Expression NOde usage is out of data model

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/types/DocumentationReferenceType.java [hunk 7]
```diff
@@ -0,0 +1,16 @@
+package org.ballerinalang.model.tree.types;
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/types/DocumentationReferenceType.java]: Add license Header

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java [hunk 8]
```diff
@@ -326,6 +326,8 @@
     VARIABLE_ALREADY_DOCUMENTED("variable.already.documented"),
     UNDOCUMENTED_RETURN_PARAMETER("undocumented.return.parameter"),
     NO_DOCUMENTABLE_RETURN_PARAMETER("no.documentable.return.parameter"),
+    INVALID_IDENTIFIER("invalid.identifier"),
+    INVALID_REFERENCE("invalid.reference"),
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java]: Refactor Naming

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/MarkdownDocumentationNode.java [hunk 9]
```diff
@@ -49,4 +50,8 @@
     Map<String, BLangMarkdownParameterDocumentation> getParameterDocumentations();
 
     String getReturnParameterDocumentation();
+
+    LinkedList<BLangMarkdownBReferenceDocumentation> getReferences();
+
+    void addReference(BLangMarkdownBReferenceDocumentation reference);
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/MarkdownDocumentationNode.java]: Reorder

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java [hunk 10]
```diff
@@ -3414,6 +3414,25 @@ public void exitVariableReferenceExpression(BallerinaParser.VariableReferenceExp
...
 
+    @Override
+    public void exitDocumentationReference(BallerinaParser.DocumentationReferenceContext ctx) {
+        if (isInErrorState) {
+            return;
+        }
+        BallerinaParser.ReferenceTypeContext referenceType  = ctx.referenceType();
+        BallerinaParser.SingleBacktickedContentContext backtickedContent = ctx.singleBacktickedContent();
+
+        this.pkgBuilder.endDocumentationReference(getCurrentPos(backtickedContent), referenceType.getText(),
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangParserListener.java]: get position from the keyword

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java [hunk 11]
```diff
@@ -2321,6 +2323,70 @@ void endParameterDocumentationLine(Set<Whitespace> ws) {
         markdownDocumentationNode.addWS(ws);
     }
 
+    void endDocumentationReference(DiagnosticPos pos, String referenceType, String identifier) {
+        MarkdownDocumentationNode markdownDocumentationNode = markdownDocumentationStack.peek();
+        if (markdownDocumentationNode == null) {
+            return;
+        }
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangPackageBuilder.java]: remove

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java [hunk 12]
```diff
@@ -75,10 +95,27 @@ public static DocumentationAnalyzer getInstance(CompilerContext context) {
...
+        this.symResolver = SymbolResolver.getInstance(context);
         this.dlog = BLangDiagnosticLog.getInstance(context);
+        this.names = Names.getInstance(context);
+        this.symTable = SymbolTable.getInstance(context);
+        instantiateDocumentationReferenceGrammer();
+    }
+
+    private static void instantiateDocumentationReferenceGrammer() {
+        String initialChar = "a-zA-Z_";
+        String unicodeNonidentifierChar = "\u0000-\u007F\uE000-\uF8FF\u200E\u200F\u2028\u2029\u00A1-\u00A7" +
```
Comment (Shan1024) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java]: `unicodeNon[i]dentifierChar` -> `unicodeNon[I]dentifierChar`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java [hunk 13]
```diff
@@ -167,6 +211,117 @@ public void visit(BLangResource resourceNode) {
...
+
+    private void validateReferences(DocumentableNode documentableNode) {
+        BLangMarkdownDocumentation documentation = documentableNode.getMarkdownDocumentationAttachment();
+        if (documentation == null) {
+            return;
+        }
+
+        Stack<BLangMarkdownReferenceDocumentation> references = documentation.getReferences();
+        references.forEach(reference -> {
+            boolean isValidIdentifier = validateIdentifier(reference.getPosition(), documentableNode,
```
Comment (Shan1024) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java]: Better to pass the `reference` and `documentableNode` to `validateIdentifier` method rather than passing various attributes of the reference separately. Within the method, these attributes can be assigned to new variables if required.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java [hunk 14]
```diff
@@ -167,6 +211,117 @@ public void visit(BLangResource resourceNode) {
...
+            return symResolver.lookupSymbolInPackage(pos, env, pkgName, identifierName, tag);
+        }
+
+        //Check for type in the environment
+        BSymbol typeSymbol = symResolver.lookupSymbolInPackage(pos, env, pkgName, typeName, SymTag.TYPE);
+        if (typeSymbol == symTable.notFoundSymbol) {
+            return symTable.notFoundSymbol;
+        }
+
+        if (typeSymbol instanceof BObjectTypeSymbol) {
```
Comment (Shan1024) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java]: Can't we use `typeSymbol.tag == SymTag.OBJECT` here instead of the `instanceof` check?

File: compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4 [hunk 15]
```diff
@@ -1188,3 +1192,50 @@ tripleBacktickedBlock
...
     ;
+
+documentationTextContent
+    :   DocumentationText
+    |   DocumentationEscapedCharacters
+    ;
+
+// Rules for parsing the content in the backticked block for documentation validation
+documentationFullyqualifiedIdentifier
+    :   documentationIdentifierQualifier?  documentationIdentifierTypename? documentationIdentifier braket?
```
Comment (Shan1024) [inline compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4]:
```suggestion
    :   documentationIdentifierQualifier? documentationIdentifierTypename? documentationIdentifier braket?
```

File: compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4 [hunk 16]
```diff
@@ -1188,3 +1192,50 @@ tripleBacktickedBlock
...
+    ;
+
+documentationFullyqualifiedFunctionIdentifier
+    :   documentationIdentifierQualifier?  documentationIdentifierTypename? documentationIdentifier braket
```
Comment (Shan1024) [inline compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4]:
```suggestion
    :   documentationIdentifierQualifier? documentationIdentifierTypename? documentationIdentifier braket
```

File: compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4 [hunk 17]
```diff
@@ -1188,3 +1192,50 @@ tripleBacktickedBlock
...
+    |   TYPE_STREAM
+    |   TYPE_ANY
+    |   TYPE_DESC
+    |   TYPE_FUTURE
+    |   TYPE_ANYDATA
+    |   TYPE_HANDLE
+    ;
+
+braket
+    : LEFT_PARENTHESIS RIGHT_PARENTHESIS
```
Comment (Shan1024) [inline compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4]:
```suggestion
    :   LEFT_PARENTHESIS RIGHT_PARENTHESIS
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java [hunk 18]
```diff
@@ -64,6 +76,14 @@
             new CompilerContext.Key<>();
 
     private BLangDiagnosticLog dlog;
+    private final SymbolResolver symResolver;
+    private final SymbolTable symTable;
+    private SymbolEnv env;
+    private Names names;
+
```
Comment (Shan1024) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java]: Extra newline.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java [hunk 19]
```diff
@@ -167,6 +211,117 @@ public void visit(BLangResource resourceNode) {
...
+        if (pkgName != Names.EMPTY) {
+            BSymbol pkgSymbol = symResolver.resolvePrefixSymbol(env, pkgName,
+                            names.fromString(pos.getSource().getCompilationUnitName()));
+
+            if (pkgSymbol == symTable.notFoundSymbol) {
+                return symTable.notFoundSymbol;
+            }
+
+            if (pkgSymbol instanceof BPackageSymbol) {
```
Comment (Shan1024) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java]: Cant we use `pkgSymbol.tag == SymTag.PACKAGE` here instead of the `instanceof` check?

**Comment by pubudu91** [comment]
We don't commit the `composer/package-lock.json` file. The tooling team will commit it if required. Shall we exclude that file?

File: composer/package.json [hunk 20]
```diff
@@ -1,7 +1,7 @@
 {
     "private": true,
     "name": "@ballerina/composer",
-    "version": "1.0.2-SNAPSHOT",
+    "version": "1.0.1",
```
Comment (irshadnilam) [inline composer/package.json]: Do we need this change? Was this changed when you run build command?

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/MarkdownDocumentationReferenceAttributeNode.java [hunk 21]
```diff
@@ -0,0 +1,27 @@
...
+ *  KIND, either express or implied.  See the License for the
+ *  specific language governing permissions and limitations
+ *  under the License.
+ */
+
+package org.ballerinalang.model.tree;
+
+/**
+* Interface to extend to make a node documentable.
+* @since 1.1.0
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/MarkdownDocumentationReferenceAttributeNode.java]: Add Newline before since annotation.

File: langlib/lang.array/src/main/ballerina/src/lang.array/array.bal [hunk 22]
```diff
@@ -67,7 +67,7 @@ public function enumerate(Type[] arr) returns [int, Type][] = external;
 public function 'map(Type[] arr, function(Type val) returns Type1 func) returns Type1[] = external;
 
 # Applies a function to each member of an array.
-# The function `func` is applied to each member of array `arr` in order.
+# The function-`func` is applied to each member of array `arr` in order.
```
Comment (hasithaa) [inline langlib/lang.array/src/main/ballerina/src/lang.array/array.bal]:
```suggestion
# The parameter `func` is applied to each member of array `arr` in order.
```

File: langlib/lang.array/src/main/ballerina/src/lang.array/array.bal [hunk 23]
```diff
@@ -86,7 +86,7 @@ public function filter(Type[] arr, function(Type val) returns boolean func) retu
 #
 # + arr - the array
 # + func - combining function
-# + initial - initial value for the first argument of combining function `func`
+# + initial - initial value for the first argument of combining function-`func`
```
Comment (hasithaa) [inline langlib/lang.array/src/main/ballerina/src/lang.array/array.bal]:
```suggestion
# + initial - initial value for the first argument of combining parameter `func`
```

File: langlib/lang.map/src/main/ballerina/src/lang.map/map.bal [hunk 24]
```diff
@@ -70,11 +70,11 @@ public function entries(map<Type> m) returns map<[string, Type]> = external;
 #
 # + m - the map
 # + func - a function to apply to each member
-# + return - new map containing result of applying function `func` to each member
+# + return - new map containing result of applying function 'func' to each member
```
Comment (hasithaa) [inline langlib/lang.map/src/main/ballerina/src/lang.map/map.bal]:
```suggestion
# + return - new map containing result of applying parameter `func` to each member
```

File: langlib/lang.map/src/main/ballerina/src/lang.map/map.bal [hunk 25]
```diff
@@ -70,11 +70,11 @@ public function entries(map<Type> m) returns map<[string, Type]> = external;
...
 public function 'map(map<Type> m, function(Type val) returns Type1 func) returns map<Type1> = external;
 
 # Applies a function to each member of a map.
-# The function `func` is applied to each member of `m`.
+# The function 'func' is applied to each member of `m`.
```
Comment (hasithaa) [inline langlib/lang.map/src/main/ballerina/src/lang.map/map.bal]:
```suggestion
# The parameter `func` is applied to each member of `m`.
```

File: langlib/lang.map/src/main/ballerina/src/lang.map/map.bal [hunk 26]
```diff
@@ -93,7 +93,7 @@ public function filter(map<Type> m, function(Type val) returns boolean func) ret
 #
 # + m - the map
 # + func - combining function
-# + initial - initial value for the first argument of combining function `func`
+# + initial - initial value for the first argument of combining function 'func'
```
Comment (hasithaa) [inline langlib/lang.map/src/main/ballerina/src/lang.map/map.bal]:
```suggestion
# + initial - initial value for the first argument of combining parameter `func`
```

File: langlib/lang.typedesc/src/main/ballerina/src/lang.typedesc/typedesc_lib.bal [hunk 27]
```diff
@@ -23,7 +23,7 @@ type AnydataType anydata;
 # Constructs a value with a specified type by copying another value.
 # + t - the type for the copy to be constructed
 # + v - the value to be copied
-# + return - a new value that belongs to type `t`, or an error if this cannot be done
+# + return - a new value that belongs to type 't', or an error if this cannot be done
```
Comment (hasithaa) [inline langlib/lang.typedesc/src/main/ballerina/src/lang.typedesc/typedesc_lib.bal]:
```suggestion
# + return - a new value that belongs to the type of `t`, or an error if this cannot be done
```

File: langlib/lang.xml/src/main/ballerina/src/lang.xml/xml.bal [hunk 28]
```diff
@@ -177,7 +177,7 @@ public function elements(xml x) returns xml = external;
 #
 # + x - the xml value
 # + func - a function to apply to each child or `item`
-# + return - new xml value containing result of applying function `func` to each child or `item`
+# + return - new xml value containing result of applying function 'func' to each child or `item`
```
Comment (hasithaa) [inline langlib/lang.xml/src/main/ballerina/src/lang.xml/xml.bal]:
```suggestion
# + return - new xml value containing result of applying parameter `func` to each child or `item`
```

File: stdlib/websub/src/main/ballerina/src/websub/commons.bal [hunk 29]
```diff
@@ -23,25 +23,25 @@ import ballerina/log;
 import ballerina/mime;
 import ballerina/stringutils;
 
-# Intent verification request parameter `hub.challenge` representing the challenge that needs to be echoed by
+# Intent verification request parameter 'hub.challenge' representing the challenge that needs to be echoed by
```
Comment (hasithaa) [inline stdlib/websub/src/main/ballerina/src/websub/commons.bal]:
```suggestion
# Intent verification request parameter ``hub.challenge`` representing the challenge that needs to be echoed by
```

File: stdlib/websub/src/main/ballerina/src/websub/commons.bal [hunk 30]
```diff
@@ -23,25 +23,25 @@ import ballerina/log;
...
 # susbscribers to verify intent.
 const string HUB_CHALLENGE = "hub.challenge";
 
 # Parameter `hub.mode` representing the mode of the request from hub to subscriber or subscriber to hub.
 const string HUB_MODE = "hub.mode";
 
-# Subscription change or intent verification request parameter `hub.topic` representing the topic relevant to the for
+# Subscription change or intent verification request parameter 'hub.topic' representing the topic relevant to the for
```
Comment (hasithaa) [inline stdlib/websub/src/main/ballerina/src/websub/commons.bal]:
```suggestion
# Subscription change or intent verification request parameter ``hub.topic`` representing the topic relevant to the for
```

File: stdlib/websub/src/main/ballerina/src/websub/commons.bal [hunk 31]
```diff
@@ -23,25 +23,25 @@ import ballerina/log;
...
 # which the request is initiated.
 const string HUB_TOPIC = "hub.topic";
 
-# Subscription change request parameter `hub.callback` representing the callback to which notification should happen.
+# Subscription change request parameter 'hub.callback' representing the callback to which notification should happen.
```
Comment (hasithaa) [inline stdlib/websub/src/main/ballerina/src/websub/commons.bal]:
```suggestion
# Subscription change request parameter ``hub.callback`` representing the callback to which notification should happen.
```

File: stdlib/websub/src/main/ballerina/src/websub/commons.bal [hunk 32]
```diff
@@ -23,25 +23,25 @@ import ballerina/log;
...
 const string HUB_CALLBACK = "hub.callback";
 
-# Subscription request parameter `hub.lease_seconds` representing the period for which the subscription is expected to
+# Subscription request parameter 'hub.lease_seconds' representing the period for which the subscription is expected to
```
Comment (hasithaa) [inline stdlib/websub/src/main/ballerina/src/websub/commons.bal]:
```suggestion
# Subscription request parameter ``hub.lease_seconds`` representing the period for which the subscription is expected to
```

File: stdlib/websub/src/main/ballerina/src/websub/commons.bal [hunk 33]
```diff
@@ -23,25 +23,25 @@ import ballerina/log;
...
 # be active.
 const string HUB_LEASE_SECONDS = "hub.lease_seconds";
 
-# Subscription parameter `hub.secret` representing the secret key to use for authenticated content distribution.
+# Subscription parameter 'ub.secret' representing the secret key to use for authenticated content distribution.
```
Comment (hasithaa) [inline stdlib/websub/src/main/ballerina/src/websub/commons.bal]:
```suggestion
# Subscription parameter ``hub.secret`` representing the secret key to use for authenticated content distribution.
```

File: stdlib/streams/src/main/ballerina/src/streams/window/window.bal [hunk 34]
```diff
@@ -19,7 +19,7 @@
 # inside the `Select` object to return the events in the window to perform joining.
 # The window names in the window objects cannot be used in the queries. Always a function which returns the specific
 # window has to be used in streaing query.
-# E.g. If `LengthWindow` has to be used in a streaming query, the function `streams:length` has to be used for
+# E.g. If `LengthWindow` has to be used in a streaming query, the function 'streams:length' has to be used for
```
Comment (hasithaa) [inline stdlib/streams/src/main/ballerina/src/streams/window/window.bal]:
```suggestion
# E.g. If `LengthWindow` has to be used in a streaming query, the function `length` has to be used for
```
@gimantha what do you think?

File: stdlib/streams/src/main/ballerina/src/streams/processor/output-processor.bal [hunk 35]
```diff
@@ -16,7 +16,7 @@
 
 import ballerina/stringutils;
 
-# The `OutputProcess` object is responsible for sending the output (only the events of type `streams:CURRENT` to the
+# The `OutputProcess` object is responsible for sending the output (only the events of type 'streams:CURRENT' to the
```
Comment (hasithaa) [inline stdlib/streams/src/main/ballerina/src/streams/processor/output-processor.bal]:
```suggestion
# The `OutputProcess` object is responsible for sending the output (only the events of type `CURRENT` to the
```

File: stdlib/streams/src/main/ballerina/src/streams/processor/output-processor.bal [hunk 36]
```diff
@@ -27,7 +27,7 @@ public type OutputProcess object {
     }
 
     # Sends the output to the streaming action. most of the time the output is published to a destination stream
-    # at the streaming action. Only the events with type `streams:CURRENT` are passed to the `outputFunc`.
+    # at the streaming action. Only the events with type-`streams:CURRENT` are passed to the `outputFunc`.
```
Comment (hasithaa) [inline stdlib/streams/src/main/ballerina/src/streams/processor/output-processor.bal]:
```suggestion
    # at the streaming action. Only the events with type `CURRENT` are passed to the `outputFunc`.
```

File: stdlib/http/src/main/ballerina/src/http/http_commons.bal [hunk 37]
```diff
@@ -245,7 +245,7 @@ function buildResponse(ResponseMessage message) returns Response {
     return response;
 }
 
-# The HEAD remote function implementation of the Circuit Breaker. This wraps the `head()` function of the underlying
+# The HEAD remote function implementation of the Circuit Breaker. This wraps the `head` function of the underlying
```
Comment (hasithaa) [inline stdlib/http/src/main/ballerina/src/http/http_commons.bal]:
```suggestion
# The HEAD remote function implementation of the Circuit Breaker. This wraps the `head()` function of the underlying
```

Shall we revert this change? This description is misleading. @arukshani Could you please verify this?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 38]
```diff
@@ -1059,6 +1059,14 @@ error.not.supported.source.for.stamp=\
...
 # Compiler warning messages
 # -------------------------
+warning.invalid.documentation.identifier=\
+  invalid identifier in documentation reference ''{0}''
+
+warning.invalid.documentation.reference=\
+  invalid reference in documentation ''{0}'' for type ''{1}''
+
+warning.invalid.use.of.parameter.reference=\
+  invalid usage of parameter reference outside of function definition ''{0}''
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/resources/compiler.properties]: Can we have test cases covering these warning messages?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/SilentParserErrorStrategy.java [hunk 39]
```diff
@@ -0,0 +1,95 @@
...
+import org.antlr.v4.runtime.FailedPredicateException;
+import org.antlr.v4.runtime.InputMismatchException;
+import org.antlr.v4.runtime.NoViableAltException;
+import org.antlr.v4.runtime.Parser;
+import org.antlr.v4.runtime.RecognitionException;
+import org.wso2.ballerinalang.compiler.parser.BLangReferenceParserListener;
+
+/**
+ * Class is responsible for issuing warnings when Documentation Reference is in an invalid format
+ * @since 1.1.0
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/SilentParserErrorStrategy.java]: Add new line before since annotation.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/DocReferenceErrorType.java [hunk 40]
```diff
@@ -0,0 +1,31 @@
...
+ *  KIND, either express or implied.  See the License for the
+ *  specific language governing permissions and limitations
+ *  under the License.
+ */
+
+package org.ballerinalang.model.tree;
+
+/**
+ * This class contains a list of diagnostic codes.
+ * @since 1.1.0
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/DocReferenceErrorType.java]: Add new line before since.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/DocReferenceErrorType.java [hunk 41]
```diff
@@ -0,0 +1,31 @@
...
+ */
+public enum DocReferenceErrorType {
+    NO_ERROR,
+    BACKTICK_IDENTIFIER_ERROR, // Identifier invalid in `reference` type of reference.
+    IDENTIFIER_ERROR, // Identifier invalid in keyword `reference` type of reference.
+    REFERENCE_ERROR, // Invalid reference.
+    PARAMETER_REFERENCE_ERROR // Incorrectly used parameter `reference` in a place other than a function.
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/DocReferenceErrorType.java]: Shall we improve the doc comments with, some examples scenarios?

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/DocumentationReferenceType.java [hunk 42]
```diff
@@ -0,0 +1,46 @@
...
+ *  KIND, either express or implied.  See the License for the
+ *  specific language governing permissions and limitations
+ *  under the License.
+ */
+
+package org.ballerinalang.model.tree;
+
+/**
+ * Used to identify the type of backticked reference in Markdown Documentation strings.
+ * @since 1.1.0
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/model/tree/DocumentationReferenceType.java]: Add NL before since.

File: tool-plugins/vscode/package-lock.json [hunk 43]
```diff
@@ -1,6 +1,6 @@
 {
     "name": "ballerina",
-    "version": "1.0.3",
+    "version": "1.0.4-SNAPSHOT",
```
Comment (hasithaa) [inline tool-plugins/vscode/package-lock.json]: It seems like this file modified by mistake. Please revert it.

File: tool-plugins/vscode/package.json [hunk 44]
```diff
@@ -2,7 +2,7 @@
     "name": "ballerina",
     "displayName": "Ballerina",
     "description": "Intellisense, Diagram View, Debugging, code formatting and refactoring for Ballerina",
-    "version": "1.0.3",
+    "version": "1.0.4-SNAPSHOT",
```
Comment (hasithaa) [inline tool-plugins/vscode/package.json]: It seems like these changes were added by mistake.

**Comment by hasithaa** [comment]
This PR has lang changes that can affect/improve the tooling experience. Please note. @NipunaRanasinghe @nadeeshaan @NipunaMarcus @rasika

**Comment by NipunaRanasinghe** [comment]
@hasithaa Ack :)

@dulvinw Shall we create a separate issue requesting tooling changes (with a brief explaination) so that the tooling team can estimate and start working on the required changes/improvements.

**Comment by dulvinw** [comment]
Hi @NipunaRanasinghe Created the following issue https://github.com/ballerina-platform/ballerina-lang/issues/19985.
