### PR TITLE
Fix dynamic service registration issue in gRPC

### LINKED ISSUE #21151: [gRPC] Dynamic gRPC service registration fails
**Description:**
When we dynamically register gRPC service like below, 
```ballerina
listener grpc:Listener ep = new (9110);

service helloService =
    @grpc:ServiceDescriptor {
        descriptor: ROOT_DESCRIPTOR_20,
        descMap: getDescriptorMap20()
    }
    @grpc:ServiceConfig {
        name: "HelloWorld101"
    }
    service {
        resource function hello(grpc:Caller caller, string name) {
            log:printInfo("name: " + name);
            string message = "Hello " + name;
            grpc:Error? err = caller->send(message);
            if (err is grpc:Error) {
                log:printInfo("Error when sending the response: " + <string>err.detail()["message"]);
            } else {
                log:printInfo("Server send response : " + message);
            }
            checkpanic caller->complete();
        }
    };

public function main() {
    error? attach = ep.__attach(helloService);
    error? 'start = ep.__start();
}
```
Registration fails giving following error,
```
{ballerina/grpc}InternalError message=Error when initializing service register builder. Couldn't find the service descriptor for the service: anonymous
```

**Affected Versions:**
1.1.2

### PR DESCRIPTION
**Pull request by daneshk**
Fixes #21151

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ServicesBuilderUtils.java [hunk 1]
```diff
@@ -69,16 +69,32 @@ public static ServerServiceDefinition getServiceDefinition(BRuntime runtime, Obj
...
+        String serviceName = null;
+        Object serviceConfigData = service.getType().getAnnotation("ballerina/grpc:ServiceConfig");
+        if (serviceConfigData != null) {
+            MapValue<String, Object> configMap = (MapValue) serviceConfigData;
+            String providedName = configMap.getStringValue("name");
+            if (providedName != null && !providedName.isEmpty()) {
+                serviceName = providedName;
+            }
+        }
+        if (serviceName == null) {
```
Comment (chamil321) [inline stdlib/grpc/src/main/java/org/ballerinalang/net/grpc/ServicesBuilderUtils.java]: If we return the providedName from L87, we would not need this null check. WDYT?
If so, serviceName variable can be also removed
