### PR TITLE
Fix default value generation for error types in CommonUtil and ignore variable code action

### LINKED ISSUE #34719: Ignore unused variable code action results in an invalid binding pattern
**Description:**
Peek 2022-01-18 22-49

As depicted above the code action results in an invalid binding pattern
**Steps to reproduce:**

```ballerina
function demo() {
    int a;
}
```

**Affected Versions:**
stage-sl-snapshot

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
$subject

Fixes a part of #34656
Fixes #34719

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 1]
```diff
@@ -381,12 +381,15 @@ public static Position toPosition(LinePosition linePosition) {
                 TypeSymbol errorType = CommonUtil.getRawType(((ErrorTypeSymbol) rawType).detailTypeDescriptor());
                 StringBuilder errorString = new StringBuilder("error (\"\"");
                 if (errorType.typeKind() == TypeDescKind.RECORD) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:383]: Shall we add the max depth validation as well? If not there is a chance of SO for the following

```
type ER1 error<record {| ER1 e?; |}>;

public function main() {
    ER1 er1 = getER1();
}

function getER1() {
return error("", e<cursor>)
```

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 2]
```diff
@@ -381,12 +381,15 @@ public static Position toPosition(LinePosition linePosition) {
...
-                    errorString.append(", ");
-                    errorString.append(getMandatoryRecordFields((RecordTypeSymbol) errorType).stream()
-                            .map(recordFieldSymbol -> recordFieldSymbol.getName().get()
-                                    + " = " + getDefaultValueForType(recordFieldSymbol.typeDescriptor(), depth + 1)
-                                    .orElse(""))
-                            .collect(Collectors.joining(", ")));
+                    List<RecordFieldSymbol> mandatoryFields = getMandatoryRecordFields((RecordTypeSymbol) errorType);
+                    if (!mandatoryFields.isEmpty() && depth <= MAX_DEPTH) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:385]: If we use `depth > MAX_DEPTH` as a guard clause, before line 384, we can avoid the field filtering as well

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 2 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java]: +1. Done.

**Review by mohanvive — APPROVED** [review]
