### PR TITLE
[2201.9.x] Fix worker send hangs when worker early return within if stmt

### LINKED ISSUE #42555: [Bug]: Worker send hangs when the worker early return within `if`
### Description

$subject

### Steps to Reproduce

The following codes hang.
Case 1
```ballerina
import ballerina/io;
import ballerina/lang.'error as e;

public function main() {
    io:println("main called");
    worker w1 {
        io:println("w1");
        boolean b = true;
        if (b) {
            return;
        } else {
            30 -> w2;
        }
    }
    worker w2 {
        io:println("w2");
        int|e:NoMessage m = <- w1;
        io:println(m);
    }
    wait w2;
}
```

Case 2 
```ballerina
import ballerina/io;
import ballerina/lang.'error as e;

 public function main() {
    io:println("main");
    worker w2 {
        io:println("w2");
        int|e:NoMessage|error m = <- w1;
        io:println(m);
    }

    worker w1 returns error? {
        io:println("w3");
        boolean b = true;
        if b {
            return;
        }
        30 -> w2;
    }
    wait w2;
}
```

But, the following works as expected.
```ballerina
import ballerina/io;
import ballerina/lang.'error as e;

 public function main() {
    io:println("main");
    worker w2 {
        io:println("w2");
        int|e:NoMessage|error m = <- w1;
        io:println(m);
    }

    worker w1 returns error? {
        io:println("w3");
        boolean b = true;
        if b {
            return error("error");
        }
        30 -> w2;
    }
    wait w2;
}
```

### Affected Version(s)

2201.9.0 RC1

### OS, DB, other environment details and versions

MacOS

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #42555

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by gabilang** [comment]
This PR addresses the case 1 mentioned in the original problem. 
```ballerina
import ballerina/io;
import ballerina/lang.'error as e;

public function main() {
    io:println("main called");
    worker w1 {
        io:println("w1");
        boolean b = true;
        if (b) {
            return;
        } else {
            30 -> w2;
        }
    }
    worker w2 {
        io:println("w2");
        int|e:NoMessage m = <- w1;
        io:println(m);
    }
    wait w2;
}
```

**Review by HindujaB — APPROVED** [review]
LGTM

File: langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/WorkerChannels.java [hunk 1]
```diff
@@ -40,9 +41,20 @@ public static void autoClose(BString[] channelIds) {
         Strand currentStrand = Scheduler.getStrand();
         Strand channelHoldingStrand = Objects.requireNonNullElse(currentStrand.parent, currentStrand);
         for (BString channelId : channelIds) {
-            String channelName = channelId.getValue() + ":" + (channelHoldingStrand.functionInvocation - 1);
```
Comment (warunalakshitha) [inline langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/WorkerChannels.java:43]: Do we still need hannelHoldingStrand.functionInvocation?

**Review by warunalakshitha — APPROVED** [review]
