### PR TITLE
Fix invalid error in using spread field with never-typed optional field

### LINKED ISSUE #41363: [Bug]: Invalid error when using a spread field with a `never`-typed optional field
### Description

$title.

### Steps to Reproduce

```ballerina
type Employee record {|
    int id;
    string name;
|};

public function main() {
    record {|
        int id;
        string name;
        never dept?;
    |} rec = {
        name: "Joy",
        id: 1023
    };
    Employee _ = {...rec}; // error: undefined field 'dept' in record 'Employee'

    Employee e = rec; // OK
    Employee _ = {...e}; // OK
}
```

### Affected Version(s)

2201.7.2, 2201.8.0-SNAPSHOT

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by poorna2152**
Fixes #41363 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -7576,6 +7576,9 @@ private BType checkMappingField(RecordLiteralNode.RecordField field, BType mappi
                     boolean errored = false;
                     for (BField bField : ((BRecordType) spreadExprType).fields.values()) {
                         BType specFieldType = bField.type;
+                        if (specFieldType.tag ==  TypeTags.NEVER) {
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7579]: Why this specific name `specFieldType` here?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal [hunk 2]
```diff
@@ -159,6 +159,9 @@ function testSpreadFieldWithRecordTypeHavingNeverField() {
     Grades grades = { physics: 75 };
     Address address= { street: "Main Street" };
 
+    record {| string street; |} addressInline = {...address};
+    assertEquality("Main Street", addressInline.street);
```
Comment (prakanth97) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal:163]: Shall we add a test where we assign `()` to the never type field. like below 
```
record {|
        int id;
        string name;
        never dept?;
    |} rec = {
        name: "Joy",
        id: 1023,
        dept: ()
    };
```

Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal:163]: Add below test as well

```
type Employee record {|
    int id;
    string name;
    string dept;
|};

public function dummyTest() {
    record {|
        int id;
        string name;
        never dept?;
    |} rec = {
        name: "Joy",
        id: 1023,
        dept: ()
    };
    Employee _ = {dept:"a", ...rec};
}

```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7579]: `fieldName` is already defined in the scope and this is referring to a `type` not a name right?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal (hunk 2 above)
Comment (poorna2152) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal:170]: Added

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7579]: My mistake, It should be `fieldType`

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7579]: We expect only one instance of the never type, which is `org.wso2.ballerinalang.compiler.semantics.model.SymbolTable#neverType`.

So we can do

```suggestion
                        if (specFieldType ==  symTable.neverType) {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal [hunk 3]
```diff
@@ -155,10 +155,55 @@ type Address record {
...
+    string name;
+    string dept;
+|};
+
+
 function testSpreadFieldWithRecordTypeHavingNeverField() {
     Grades grades = { physics: 75 };
     Address address= { street: "Main Street" };
 
+    record {| string street; |} addressInline = {...address};
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal:169]: Not related to your change, but this should have failed anyway since `Address` is an open record - https://github.com/ballerina-platform/ballerina-lang/issues/41740. 

Shall we fix this test so that it continues to pass even when the other bug is fixed?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal [hunk 4]
```diff
@@ -155,10 +155,55 @@ type Address record {
...
+    record {|
+        int id;
+        string name;
+        never dept?;
+    |} empInLine = {
+        id: 1023,
+        name: "Joy",
+        dept: ()
+    };
+    Employee emp = {dept:"a", ...empInLine};
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal:204]:
```suggestion
    Employee emp = {dept: "a", ...empInLine};
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal [hunk 5]
```diff
@@ -155,10 +155,55 @@ type Address record {
...
+    assertEquality("Joy", emp.name);
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal:206]: Let's add a test with multiple spread fields also.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal:1]: Add a few negative tests (compilation errors) where there are never-typed fields, but the spread field is still incompatible because

1. the other fields are incompatible
    i. type mismatch
    ii. field count mismatch

2. the field is expected to be there and can't be a never-typed field

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal [hunk 6]
```diff
@@ -155,10 +155,55 @@ type Address record {
...
+        int i;
+        string s;
+        never n?;
+    |} bar2InLine = {
+        i: 2,
+        s: "S",
+        n: ()
+    };
+    Bar bar2 = {...bar2InLine};
+    assertEquality("S", bar2.s);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal:193]: I would test the entire value.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7579]: Anyway, this will not work when the type is effectively `never`. E.g.,

```ballerina
record {|
    never x;
|}
```

or 

```ballerina
never|never
```

You will have to use `org.wso2.ballerinalang.compiler.semantics.analyzer.Types#isNeverTypeOrStructureTypeWithARequiredNeverMember(org.wso2.ballerinalang.compiler.semantics.model.types.BType)`.

Please add a few tests too.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal (hunk 3 above)
Comment (poorna2152) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal]: Changed the Address record into a closed record

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal [hunk 7]
```diff
@@ -150,15 +150,84 @@ type Grades record {|
     int...;
 |};
 
-type Address record {
+type Address record {|
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal:153]: I would leave this as is and add a new record since this was already used in a different test.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal [hunk 8]
```diff
@@ -150,15 +150,84 @@ type Grades record {|
...
+    string name;
+    string dept;
+|};
+
 
 function testSpreadFieldWithRecordTypeHavingNeverField() {
     Grades grades = { physics: 75 };
     Address address= { street: "Main Street" };
 
+    record {|string street;|} addressInline = {...address};
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field.bal:169]: I would also move the new tests to the end.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field_semantic_analysis_negative.bal [hunk 9]
```diff
@@ -53,6 +53,24 @@ function testUndeclaredSpreadOpField() {
     Foo f = {s, i: 2, ...b};
 }
 
+function testFieldWithNeverType() {
+    record {|string s; string i; never x?;|} rec1 = {s: "a", i: "1023"};
+    Foo foo1 = {...rec1};
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/mappingconstructor/spread_op_field_semantic_analysis_negative.bal:58]:
```suggestion
    Foo _ = {...rec1};
```

Update wherever the variable isn't used.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (poorna2152) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: `fieldType` is already defined in this scope. https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L7540

**Review by MaryamZi — APPROVED** [review]
