### PR TITLE
Fix transactional function node in the incremental-parser

### LINKED ISSUE #24262: Fix transactional function node in the incremental-parser
**Description:**
$title

**Suggested Labels (optional):**
component/parser

**Suggested Assignees (optional):**
@dulvinw

### PR DESCRIPTION
**Pull request by dulvinw**
Fixes #24262

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 1]
```diff
@@ -531,7 +532,8 @@ public BLangNode transform(ImportDeclarationNode importDeclaration) {
     @Override
     public BLangNode transform(MethodDeclarationNode methodDeclarationNode) {
         BLangFunction bLFunction = createFunctionNode(methodDeclarationNode.methodName(),
-                methodDeclarationNode.visibilityQualifier(), methodDeclarationNode.methodSignature(), null);
+                methodDeclarationNode.visibilityQualifier(), methodDeclarationNode.methodSignature(), null,
+                Optional.ofNullable(null));
```
Comment (SupunS) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:536]: can use `Optional.empty()`
