### PR TITLE
Fix diagnostic when `match-pattern-list` is empty

### LINKED ISSUE #28850: Bad sad error with unusual/invalid match clause
**Description:**
Consider the following code:
```
const KEY2 = 2;

function testMatch() {
    boolean found = false;
    int[5] nums = [0, 1, 2, 3, 4];
    foreach var counter in nums {
        match counter {
            0 => {

            }
            if true => {

            }
            KEY2 => {

            }
        }
    }
}
```
**This has one of the following 2 issues:**
1. Not sure if the match clause `if true` is valid. But the spec mentions about a `match-guard`. However, the above code doesn't give a compilation error in VSCode.
2. When we run the above code (single file), it prints a bad sad error: 
```
[2021-02-23 17:33:25,786] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.createConditionFromMatchPatterns(Desugar.java:3337)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.convertMatchClauseToIfStmt(Desugar.java:3317)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.convertMatchClausesToIfElseStmt(Desugar.java:3310)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3297)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangMatchStatement.accept(BLangMatchStatement.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7660)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7670)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1374)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7660)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:4926)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangWhile.accept(BLangWhile.java:78)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7660)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7670)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1374)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7660)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:4633)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForeach.accept(BLangForeach.java:105)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7660)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7670)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1169)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1214)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7677)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:808)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:448)
	at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:249)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:158)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:388)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:54)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:136)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:122)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:129)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:155)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```
The cause for this is in `org.wso2.ballerinalang.compiler.desugar.Desugar#createConditionFromMatchPatterns()`, it access the 1st match pattern without checking if the match patterns are empty.
 
**Steps to reproduce:**
See the description

**Affected Versions:**
SLA2

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #28850 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -13712,6 +13712,20 @@ private STNode parseMatchClause() {
         STNode matchGuard = parseMatchGuard();
         STNode rightDoubleArrow = parseDoubleRightArrow();
         STNode blockStmt = parseBlockNode();
+        
+        if (isNodeListEmpty(matchPatterns)) {
+            STToken identifier = SyntaxErrors.createMissingToken(SyntaxKind.IDENTIFIER_TOKEN);
+            STNode constantPattern = STNodeFactory.createSimpleNameReferenceNode(identifier);
+            matchPatterns = STNodeFactory.createNodeList(constantPattern);
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:13719]: Shouldn't we add this test inside `parseMatchPatternList` itself?

Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:13719]: We seem to do the validation outside the list in other places. 
e.g. https://github.com/ballerina-platform/ballerina-lang/blob/f2b6853b3d59b1fbb28f1d10f6be1899425c5440/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java#L12079-L12080

Also if we do it inside, then we won't be able to give diagnostic to the next token?

**Review by rdulmina — APPROVED** [review]
LGTM
