### PR TITLE
String Improvements and Bug fixes for Toml Parser

### LINKED ISSUE #26865: Decide best expected  tokens for missing tokens in toml parser
**Description:**
$Subject.

### LINKED ISSUE #26971: Toml parser throws a NumberFormatException when a double quote is missing in a string value
Here is the sample toml that I've used.

```
[package]
name = "winery
org = "foo"
version = "0.1.0"
```

### PR DESCRIPTION
**Pull request by xlight05**
## Purpose

- Improves support for 
  - Strings
  - Multi line strings
- Improves string escaping
- Node recovery improvements

## Fixes 
Resolves #26971 
Resolves #26865 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java [hunk 1]
```diff
@@ -672,4 +786,27 @@ private int peek() {
...
     }
+
+    /**
+     * Process string numeric escape.
+     * <p>
+     * <code>StringNumericEscape := \u00E9 </code>
+     */
+    private void processStringNumericEscape() {
+        // Process '\ u {'
+        this.reader.advance(3);
```
Comment (SupunS) [inline misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java:797]: you reach here after peeking only 2 tokens. So this should advance only 2 tokens.
Comment in L#796 is also not correct.

File: misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java [hunk 2]
```diff
@@ -297,10 +408,13 @@ private STToken getSyntaxToken(SyntaxKind kind) {
         return STNodeFactory.createToken(kind, leadingTrivia, trailingTrivia);
     }
 
-    private STToken getUnquotedKey() {
+    private STToken getUnquotedKey(boolean skipTrailingTrivia) {
         STNode leadingTrivia = getLeadingTrivia();
         String lexeme = getLexeme();
-        STNode trailingTrivia = processTrailingTrivia();
+        STNode trailingTrivia = STNodeFactory.createEmptyNodeList();
+        if (!skipTrailingTrivia) {
```
Comment (SupunS) [inline misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java:415]: Why do we need a flag here?

**Review by SupunS — CHANGES_REQUESTED** [review]

File: misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java [hunk 3]
```diff
@@ -230,27 +234,47 @@ private STToken readStringToken() {
...
-                return getSyntaxToken(SyntaxKind.TRIPLE_DOUBLE_QUOTE_TOKEN);
-            }
             reader.advance();
             return getSyntaxToken(SyntaxKind.DOUBLE_QUOTE_TOKEN);
-        } else {
-            while (!reader.isEOF()) {
-                nextChar = this.reader.peek();
-                if (nextChar != LexerTerminals.DOUBLE_QUOTE) {
+        }
+        while (!reader.isEOF()) {
```
Comment (SupunS) [inline misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java:242]: keep a newline after a block

File: misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java [hunk 4]
```diff
@@ -261,27 +285,74 @@ private STToken readLiteralStringToken() {
...
-                return getSyntaxToken(SyntaxKind.TRIPLE_SINGLE_QUOTE_TOKEN);
-            }
             reader.advance();
             return getSyntaxToken(SyntaxKind.SINGLE_QUOTE_TOKEN);
-        } else {
-            while (!reader.isEOF()) {
-                nextChar = this.reader.peek();
-                if (nextChar != LexerTerminals.SINGLE_QUOTE) {
+        }
+        while (!reader.isEOF()) {
```
Comment (SupunS) [inline misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java:293]: same here

File: misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java [hunk 5]
```diff
@@ -261,27 +285,74 @@ private STToken readLiteralStringToken() {
...
+        char nextChar = this.reader.peek();
+        char secondNextChar = this.reader.peek(1);
+        char thirdNextChar = this.reader.peek(2);
+        if (nextChar == LexerTerminals.DOUBLE_QUOTE && secondNextChar == LexerTerminals.DOUBLE_QUOTE && thirdNextChar
+                == LexerTerminals.DOUBLE_QUOTE) {
+            endMode();
+            reader.advance(3);
+            return getSyntaxToken(SyntaxKind.TRIPLE_DOUBLE_QUOTE_TOKEN);
+        }
+        while (!reader.isEOF()) {
```
Comment (SupunS) [inline misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java:324]: same for all places

File: misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java [hunk 6]
```diff
@@ -261,27 +285,74 @@ private STToken readLiteralStringToken() {
...
+            nextChar = this.reader.peek();
+            if (nextChar == LexerTerminals.DOUBLE_QUOTE && this.reader.peek(1) == LexerTerminals.DOUBLE_QUOTE &&
```
Comment (SupunS) [inline misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java:326]: since `nextChar == LexerTerminals.DOUBLE_QUOTE && this.reader.peek(1) == LexerTerminals.DOUBLE_QUOTE && this.reader.peek(2) == LexerTerminals.DOUBLE_QUOTE` is used at L#318 as well, we can take it to a common method

File: misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java [hunk 7]
```diff
@@ -261,27 +285,74 @@ private STToken readLiteralStringToken() {
...
+                    continue;
+                case 'u':
+                case 'U':
+                    processStringNumericEscape();
+                    continue;
+                default:
+                    String escapeSequence = String.valueOf(this.reader.peek(2));
+                    reportLexerError(DiagnosticErrorCode.ERROR_INVALID_ESCAPE_SEQUENCE, escapeSequence);
+                    this.reader.advance();
+            }
```
Comment (SupunS) [inline misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/TomlLexer.java:354]: Would be clean to extract this to a separate method like `readStringEscapeSequence`

**Review by SupunS — APPROVED** [review]
Added some comments on code-styling and refactoring. We can fix those in a separate PR
