### PR TITLE
[ballerina-1.2.x] Fix handling namespaces in `BallerinaXMLSerializer`

### LINKED ISSUE #40107: [Bug]: Using xml namespace gives bad sad in `1.2.x`
### Description

```bal
import ballerina/io;
public function main() {
    io:println(xmlWithDefaultNamespace());
}

public function xmlWithDefaultNamespace() returns string {
    xmlns "http://atestorgthatdoesntexist.org/";
    xml body2 = xml `<Add>
                     <intA foo="bar">12</intA>
                   </Add>`;
    string s2 = body2.toString();
    return s2;
}
```

Gives

```
[2023-04-04 18:22:54,976] SEVERE {b7a.log.crash} - failed to get xml as string: error occurred during writing the message to the output stream: {ballerina/lang.xml}XMLOperationError 
org.ballerinalang.jvm.util.exceptions.BallerinaException: failed to get xml as string: error occurred during writing the message to the output stream: {ballerina/lang.xml}XMLOperationError
	at org.ballerinalang.jvm.values.XMLValue.handleXmlException(XMLValue.java:136)
	at org.ballerinalang.jvm.values.XMLItem.stringValue(XMLItem.java:499)
	at org.ballerinalang.jvm.values.utils.StringUtils.getStringValue(StringUtils.java:91)
	at org.ballerinalang.langlib.value.ToString.toString(ToString.java:43)
	at ballerina.lang_value.value.toString(value.bal:86)
	at test.xmlWithDefaultNamespace(test.bal:21)
	at test.main(test.bal:13)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:489)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:261)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:229)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Seem this is fixed in SL Update 4, but exists in 1.2.37. Need to enable `XMLLiteralTest.xmlWithDefaultNamespace` after fixing this in `ballerina-1.2.x` branch

### Steps to Reproduce

_No response_

### Affected Version(s)

1.2.37

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #40313: [Task]: Fix handling namespaces in `BallerinaXMLSerializer` in `1.2.x`
### Description

$title

### Describe your task(s)

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/40107

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #40313.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaXMLSerializer.java [hunk 1]
```diff
@@ -52,20 +51,30 @@
...
+    private static final String XML_NS_URI_PREFIX = "{" + XMLConstants.XMLNS_ATTRIBUTE_NS_URI + "}";
+    private static final String OUTPUT_VALIDATE_PROPERTY = "com.ctc.wstx.outputValidateStructure";
+    private static final String OUTPUT_FACTORY = "com.ctc.wstx.stax.WstxOutputFactory";
+    private static final String AUTOMATIC_END_ELEMENTS = "com.ctc.wstx.automaticEndElements";
 
     private XMLStreamWriter xmlStreamWriter;
     private Deque<Set<String>> parentNSSet;
     private int nsNumber;
     private boolean withinElement;
+    private static boolean isDefaultFactory = false;
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaXMLSerializer.java:67]: Since 1.2.x use woodstox do we need this isDefaultFactory change?

Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaXMLSerializer.java]: Reverted the unwanted changes with 81a236285e3e60d48ead606fb808144077009b0c.
