### PR TITLE
Fix "Not giving a compile error for negative index array access"

### LINKED ISSUE #32326: Array member access with negative key value does not give any compilation error
**Description:**
Consider the below sample 
```bal
public function main() {
    byte[2] d = [1, 33];
    d[-1] = 3; // @error list index out of range
}
```
Note the `-1` is used as the key. This program compiles successfully but gives errors at runtime.

**Affected Versions:**
Current master

### PR DESCRIPTION
**Pull request by gimantha**
Fixes #32326 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by pcnfernando — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -7549,7 +7549,8 @@ private BType checkArrayIndexBasedAccess(BLangIndexBasedAccess indexBasedAccess,
                     actualType = arrayType.eType;
                     break;
                 }
-                actualType = getConstIndex(indexExpr) >= arrayType.size ? symTable.semanticError : arrayType.eType;
+                var indexVal = getConstIndex(indexExpr);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7552]: From a readability perspective, should we avoid using `var`?

Comment (hasithaa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:7552]: yes, we need to avoid using var in java code.

Comment (gimantha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: fixed

**Review by MaryamZi — APPROVED** [review]
