### PR TITLE
Fix object attached function pointer invocation issue

### LINKED ISSUE #9086: Calling a lambda function which contains a foreach, inside another lambda function is not working
**Description:**
Consider the following sample code.

```
import ballerina/runtime;
import ballerina/io;

type Teacher {
    string name;
    int age;
    string status;
    string batch;
    string school;
};

function main(string... args) {

    Teacher[] teachers = [];
    Teacher t1 = { name: "Raja", age: 25, status: "single", batch: "LK2014", school: "Hindu College" };
    teachers[0] = t1;


    Obj2 obj2 = new((Teacher [] t) => {
            io:println("Invoked the last lambda");
        });

    Obj1 filter = new(obj2.process);


    filter.process(teachers);

    runtime:sleep(1000);
}

public type Obj1 object {
    private {
        function (Teacher[]) nextProcessorPointer;
    }

    new(nextProcessorPointer) {

    }

    public function process(Teacher [] objs) {
        Teacher [] arr = [];
        int index = 0;

        foreach obj in objs {
            arr[index] = obj;
            index += 1;
        }

        if (index > 0) {
            nextProcessorPointer(arr);
        }
    }
};

public type Obj2 object {
    private {
        function (Teacher []) nextProcessorPointer1;
    }

    new(nextProcessorPointer1) {

    }

    public function process(Teacher [] objs) {
        Teacher [] arr2 = [];
        int index = 0;
        foreach obj in objs {
            arr2[index] = obj;
            index += 1;
        }
        io:println("eventArr:", arr2);
        if (index > 0) {
            nextProcessorPointer1(arr2);
        }
    }
};
```

**Steps to reproduce:**
Run the above code, the output of the line "io:println("eventArr:", arr2);" will printed repeatedly nonstop. 

**Note:** 
Commenting out the following code 
```
if (index > 0) {
            nextProcessorPointer1(arr2);
}
```
or 
```
foreach obj in objs {
            arr2[index] = obj;
            index += 1;
}
```
which is inside Obj2.process will stop the repeated execution.

**Affected Versions:**
0.974.1-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Kishanthan**
This PR fixes the object attached function pointer invocation issue. Resolves #9086

### CODE REVIEW

File: bvm/ballerina-core/src/main/java/org/ballerinalang/util/codegen/PackageInfoReader.java [hunk 1]
```diff
@@ -1446,6 +1434,43 @@ private void readInstructions(PackageInfo packageInfo) throws IOException {
...
+        int h;
+        int i;
+        int j;
+        int k;
+        h = codeStream.readInt();
+        i = codeStream.readInt();
+        j = codeStream.readInt();
+        k = codeStream.readInt();
+        int[] operands;
+        if (k == -1) { // no additional reading is needed
```
Comment (hasithaa) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/util/codegen/PackageInfoReader.java]: shall we change -1,0, "else case" to 0,1 and "number of pairs".

**Comment by hasithaa** [comment]
By looking at this implementation we found that currently, we don't support closers in anonymous objects. So created issue https://github.com/ballerina-platform/ballerina-lang/issues/9144 to capture this requirement. 

We are going ahead with PR for now as it is blocking streaming development.
