### PR TITLE
[Shell] Update shell invalid command message

### LINKED ISSUE #31930: Misleading error message provided for invalid shell commands
**Description:**
Consider the following screen capture.

Screenshot 2021-07-28 at 16 56 16

**Steps to reproduce:**
Enter any invalid command in the shell. This gives a parsing error. Instead we should provide a proper message specifying that the command is an invalid command

**Affected Versions:**
SwanLake-Beta2 at least

### PR DESCRIPTION
**Pull request by DamithaSenevirathne**
Fixes #31930
 
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java [hunk 1]
```diff
@@ -78,8 +79,14 @@ public Node parse(String source) throws TreeParserException {
                 errorMessage = "Code contains syntax error(s).";
             }
         }
-        addErrorDiagnostic(errorMessage);
-        addErrorDiagnostic("Parsing aborted due to errors.");
+        if (source.startsWith(COMMAND_PREFIX)) {
+            errorMessage = "Can not find the command : " + source.substring(0, source.length() - 1).trim();
```
Comment (pubudu91) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java:83]: Typically the we use the colon in messages as `<message>: <additional-info>`

Comment (DamithaSenevirathne) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/parser/SerialTreeParser.java]: Updated in 13a87c7ddf4772d1855f9f491949e8e02878ef59

**Review by pubudu91 — APPROVED** [review]
