### PR TITLE
Fix NPE for strand metadata at `dumpState` method

### LINKED ISSUE #38058: [Bug]: NPE at dumpState() when strand metadata is null
### Description

$title

Field `metadata` in a `Strand` object may be null. Hence a null pointer may happen in `dumpState()` method in `Strand` class.

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

Ballerina 2201.2.0 (Swan Lake Update 2)

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #38058

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java [hunk 1]
```diff
@@ -438,8 +438,14 @@ public String dumpState() {
         }
 
         strandInfo.append(" [");
-        strandInfo.append(this.metadata.getModuleOrg()).append(".").append(this.metadata.getModuleName()).append(".")
-                .append(this.metadata.getModuleVersion()).append(":").append(this.metadata.getParentFunctionName());
+        StrandMetadata strandMetadata = this.metadata;
+        if (strandMetadata == null) {
+            strandInfo.append("N/A");
+        } else {
+            strandInfo.append(strandMetadata.getModuleOrg()).append(".").append(strandMetadata.getModuleName())
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java:445]: Shall we create an separate issue to handle null values with metadata module org, name etc.

**Review by warunalakshitha — APPROVED** [review]
LGTM

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java (hunk 1 above)
Comment (Nadeeshan96) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java:445]: Will do.
