### PR TITLE
Make parser tests run all compiler phases

### LINKED ISSUE #27931: Run parser tests through all compiler phases
**Description:**
As the transformation logic has been written in a passive manner in BLangNodetraformer, it tends to crash with CCEs, etc with the syntax API changes in parser. Best way to identify those issues beforehand is, making parser tests run through all compiler phases.

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #27931 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+    public void test(String fileName, String path) throws IOException {
+        try {
+            BCompileUtil.compile(path);
+        } catch (Exception e) {
+            Assert.fail("failed to compile parser test: \"" + fileName + "\"", e);
+        }
+    }
+
+    public List<String> skipList() {
+        return Arrays.asList(
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java:50]: Hashmap or a HashSet will improve efficiency.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+                "match_stmt_source_11.bal"
+        );
+    }
+
+    @DataProvider(name = "parser-test-file-provider")
+    public Object[][] dataProvider() {
+        return getParserTestConfigs();
+    }
+
+    Object[][] getParserTestConfigs() {
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java:100]: Can be merged into the above method.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+            return Files.walk(parserDir.resolve("src").resolve("test").resolve("resources"))
+                    .filter(path -> {
+                        File file = path.toFile();
+                        return file.isFile() && file.getName().endsWith(".bal")
+                                && !skippedTests.contains(file.getName());
+                    })
+                    .map(path -> new Object[]{path.toFile().getName(), path.toString()})
+                    .toArray(size -> new Object[size][2]);
+        } catch (IOException e) {
+            return new Object[0][];
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java:112]: Instead of returning an empty object, we should fail the test here.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+                    .filter(path -> {
+                        File file = path.toFile();
+                        return file.isFile() && file.getName().endsWith(".bal")
+                                && !skippedTests.contains(file.getName());
+                    })
+                    .map(path -> new Object[]{path.toFile().getName(), path.toString()})
+                    .toArray(size -> new Object[size][2]);
+        } catch (IOException e) {
+            Assert.fail("Can't resolve parser tests", e);
+            return new Object[0][];
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java:107]: Can remove the try-catch block and declare the method throws IOExcepion. 
Letting it crash like that, is not a good practice right? Rather catch and Assert fail?

Comment (hasithaa) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/ParserTestRunner.java:107]: Catch and Assert fail is fine.

**Review by hasithaa — APPROVED** [review]
