### PR TITLE
Fix visibility of let expression inner variables

### LINKED ISSUE #28883: [Debugger] `let` expression inner variables are visible outside the expression
**Description:**
Currently `let` expression variables are visible in debug mode. Those variables should not be visible.

**Steps to reproduce:**
- Consider the code segment:
```
public function main() {
    string greeting = let string hello = "Hello ",
                          string ballerina = "Ballerina!"
                      in hello + ballerina;
}
```
- Run the above program in debbubg mode.
- We can see the `greeting`, `hello` and `ballerina` are visible in the local variables panel.
- Expected behaviour is only `greeting` variable should be visible. Other variables (`hello` and `ballerina`) should not be visible

image

### LINKED ISSUE #32477: [Debugger] Variables defined inside the conditional blocks and loops are also visible outside the blocks
**Description:**

The variables defined inside the `if` statements and, `while` and `foreach` loops are visible at the outside of the blocks and loops. Ideally they should not visible outside. 

Consider the following code example:
```
public function main() {
    int i = 1;
    if (i == 1) {
        int j = i;
    }
}
```
The variable `j` is visible outside the `if` block also.
 
ifblock

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

https://github.com/ballerina-platform/ballerina-lang/issues/28883

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #28883
Fixes #32477

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java [hunk 1]
```diff
@@ -1635,7 +1645,18 @@ public void visit(BLangWhile astWhileStmt) {
         astWhileStmt.body.accept(this);
         this.env.unlockVars.pop();
         if (this.env.enclBB.terminator == null) {
-            this.env.enclBB.terminator = new BIRTerminator.GOTO(null, whileExprBB, this.currentScope);
+            if (astWhileStmt.body.pos != null) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java:1648]: Can we get this null?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java [hunk 2]
```diff
@@ -616,6 +618,7 @@ private void rewriteObservableFunctionInvocations(BIRFunction func, BIRPackage p
                         BIRBasicBlock observeEndBB = insertBasicBlock(func, eeTargetIndex + 1);
                         BIRBasicBlock newTargetBB = insertBasicBlock(func, eeTargetIndex + 2);
                         swapBasicBlockContent(errorEntry.targetBB, newTargetBB);
+                        resetLocalVarEndBBs(func, errorEntry.targetBB, newTargetBB);
```
Comment (nadundesilva) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:621]: Does it make more sense to move this into the `swapBasicBlockContent` method itself ?
(Also there is another `swapBasicBlockTerminator` method as well where we only swap the terminator.)

Comment (nadundesilva) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:621]: I think when we have an observability terminator (eg:- HTTP Client call), the the immediate local vars might not be visible when not swapped. But it's not the exact bug we are trying to fix I think.

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:621]: Yes, adding this to when we do the terminator swap only is not be relevant to the fix for this particular issue. IMO reassigning endBBs of local variables after the `Return` or `Panic` terminator swap may not be useful. As you mentioned, when the terminator instruction is `Call` and it is observable, the endBBs may need to be reassigned after the terminator swap. I'll make changes accordingly.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java (hunk 1 above)
Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java]: We can remove the null check since the position never takes null here. Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/32667/commits/d6c32a58981fff76246a855c20aef34596fead4f

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java (hunk 2 above)
Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:622]: Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/32667/commits/3d12d91fd7257fcb7f4417157a159d0be72b84cd

Comment (nadundesilva) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:622]: Yes for return and panic it's probably not required 👍🏻

**Review by nadundesilva — APPROVED** [review]
Observability related changes LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM
