### PR TITLE
Fix NPE related to record-type-inclusion

### LINKED ISSUE #29753: Bad, sad error when record type inclusion overrides a field with a type defined after
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public type Foo record {|
    anydata body;
|};

// Works when defined before `Bar`.
// type Baz record {|
//     int id;
// |};

type Bar record {| 
    *Foo;
    Baz body;
|};

type Baz record {|
    int id;
|};
```

```log
[2021-03-31 22:27:31,618] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.IsPureTypeUniqueVisitor.visit(IsPureTypeUniqueVisitor.java:252)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.IsAnydataUniqueVisitor.visit(IsAnydataUniqueVisitor.java:281)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.IsAnydataUniqueVisitor.visit(IsAnydataUniqueVisitor.java:293)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAnydata(Types.java:319)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:695)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:636)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$resolveReferencedFields$32(SymbolEnter.java:4058)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveReferencedFields(SymbolEnter.java:4066)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveFields(SymbolEnter.java:3249)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineFieldsOfObjectOrRecordTypeDef(SymbolEnter.java:3181)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineFields(SymbolEnter.java:3146)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:388)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:305)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:267)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:260)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:369)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:323)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:176)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:168)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:97)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:130)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:166)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Affected Versions:**
slalpha3, slalpha4-SNAPSHOT

### LINKED ISSUE #29965: Bad sad error when casting to inline record type
**Description:**
$title

**Steps to reproduce:**
Refer the following code where the return type is cast to the inline record type. The resource definitions and schemas were generated from an open API spec using the open-api tool. 
Note that Error is a record (as generated from the tool) and hence the approach with casting. Please suggest if there is a different way to achieve this. 

```
import  ballerina/http;

listener  http:Listener  ep0  = new (8085);

service  /v1  on  ep0  {

    resource function post developers(@http:Payload Developer payload) 
            returns record {| *http:Created; Developer  body; |}|Error {
        Developer dev1 = {id: "123", name: "Jane Doe"};
        return <record {| *http:Created; Developer  body; |}>{body: dev1};
    }
    
}
```

```
type  Error record  { 
    string  errorType?;
    string  message?;
};

type  Developer record  { 
    string  id?;
    string  name?;
    string  team?;
    string[]  skils?;
    string  createdAt?;
    string  updatedAt?;
};
```

```
[2021-04-10 19:31:15,921] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.IsPureTypeUniqueVisitor.visit(IsPureTypeUniqueVisitor.java:252)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.IsAnydataUniqueVisitor.visit(IsAnydataUniqueVisitor.java:281)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.IsAnydataUniqueVisitor.visit(IsAnydataUniqueVisitor.java:293)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAnydata(Types.java:327)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:706)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.Types.isAssignable(Types.java:647)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$resolveReferencedFields$32(SymbolEnter.java:4044)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveReferencedFields(SymbolEnter.java:4052)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.resolveFields(SymbolEnter.java:3242)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineFieldsOfObjectOrRecordTypeDef(SymbolEnter.java:3174)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineFields(SymbolEnter.java:3140)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:388)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:305)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:165)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:267)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:260)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:369)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:323)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:168)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:160)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:96)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:130)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:168)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
 

```
**Affected Versions:** Swan Lake Alpha 3

**OS, DB, other environment details and versions:** OSX

**Related Issues (optional):**
This was an alternative approach suggested to resolve issue reported in https://github.com/ballerina-platform/ballerina-lang/issues/29753
Also see : https://ballerina-platform.slack.com/archives/C47EAELR1/p1617191396102900

### PR DESCRIPTION
**Pull request by KRVPerera**
Fixes #29753
Fixes #29965

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java [hunk 1]
```diff
@@ -278,7 +278,8 @@ public Boolean visit(BRecordType type) {
                 return false;
             }
         }
-        type.isAnyData = type.sealed || isPureTypeUniqueVisitor.visit(type.restFieldType);
+        type.isAnyData =
+                type.sealed || (type.restFieldType != null && isPureTypeUniqueVisitor.visit(type.restFieldType));
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java:282]: What's the scenario where the `restFieldType` becomes null? Usually, `noType` is set. But if this is while resolving, is this called again later to reset `isAnyData`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 2]
```diff
@@ -3276,23 +3277,29 @@ private void resolveFields(BStructureType structureType, BLangStructureTypeNode
                 })
                 .collect(getFieldCollector());
 
-        List<BType> list = new ArrayList<>();
+        // Resolve referenced types and their fields of structural type
+        resolveReferencedFields(structureTypeNode, typeDefEnv);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:3281]: Any particular reason to change the order here?

Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:3281]: Yes because they are not resolved yet. We are collecting invalid types. Then we try to write them 
```writeTypeInclusions(bRecordType.typeInclusions);```
If you look at the same logic in BLangClassDefinition visitor in SymbolEnter we only collect valid refs.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java (hunk 1 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java]: Fixed by 67ab648409dba4dece5cb50f655125d24c950828

File: tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_type_inclusion_negative.bal [hunk 3]
```diff
@@ -95,3 +95,17 @@ type Employee record {
...
+
+// Out of order inclusion test : added to test a NPE
+type Bar record {
+    *Foo;
+    Baz body;   // defined after the type definition
+};
+
+type Baz record {
+    int id;
+};
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_type_inclusion_negative.bal:111]: These should work, right? I get a `redeclared symbol 'body'` error for this example.

But when I define `Baz` before `Bar` it compiles as expected.

```ballerina
public type Foo record {
    anydata body;
};

type Baz record {
    int id;
};

// Out of order inclusion test : added to test a NPE
type Bar record {
    *Foo;
    Baz body;   // defined after the type definition
};
```

Comment (KRVPerera) [reply tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_type_inclusion_negative.bal:111]: Yes, this should be allowed. I am looking into this. I have focused only on the crash.

File: tests/jballerina-unit-test/src/test/resources/test-src/record/anon_record.bal [hunk 4]
```diff
@@ -89,6 +89,17 @@ function testAnonRecordAsRestFieldOfAnonRecord() {
     assertEquality((), rec2["c"]?.i);
 }
 
+type Foo record {
+    int x = 1;
+};
+
+public function anonymousRecordWithTypeInclusion() {
+    var rec = <record { *Foo; }>{
+        x : 3
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/anon_record.bal:98]:
```suggestion
        x: 3
```

File: tests/jballerina-unit-test/src/test/resources/test-src/record/closed_record_type_inclusion_negative.bal [hunk 5]
```diff
@@ -174,3 +174,17 @@ type Employee record {|
     *PersonTwo;
     int age;
 |};
+
+public type Foo record {|
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/closed_record_type_inclusion_negative.bal:178]: No longer a negative test?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java]: Shall we also add a test for subsequent resolution of `isAnyData` if we don't have one already?

File: tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_type_inclusion.bal [hunk 6]
```diff
@@ -198,6 +198,26 @@ function testCreatingRecordWithOverriddenFields() {
...
 }
 
+public type Foo record {
+    anydata body;
+};
+
+// Out of order inclusion test : added to test a NPE
+type Bar record {
+    *Foo;
+    Baz body;   // defined after the type definition
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_type_inclusion.bal:208]: Let's add a negative test where `Baz` is not a subtype of anydata too.

**Review by MaryamZi — DISMISSED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_type_inclusion.bal (hunk 6 above)
Comment (KRVPerera) [reply tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_type_inclusion.bal:208]: Will send a separate PR for this.

Comment (KRVPerera) [reply tests/jballerina-unit-test/src/test/resources/test-src/record/open_record_type_inclusion.bal:208]: Done 018e39750fef025355f91e69905e7b5bc00d6af1

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java [hunk 7]
```diff
@@ -279,6 +279,11 @@ public Boolean visit(BRecordType type) {
                 return false;
             }
         }
+
+        if (!type.sealed && (type.restFieldType == null)) {
+            return false;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java:284]: There's a codecov comment? Shall we verify if this is covered via tests?

**Review by MaryamZi — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java (hunk 7 above)
Comment (KRVPerera) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsAnydataUniqueVisitor.java:284]: +1.
Maybe the latest commit to updating type precedence for unresolved fields may have made this code redundant.
