### PR TITLE
[Java 21] Support ballerina lang to build with Java 21

### LINKED ISSUE #43146: [Bug]: Debugger evaluation tests are failing with Java 21
### Description

If we use Java 21 to run the ballerina debugger integration tests with minimum changes, tests are failing as below.

```
debugger-intg-test-suite > debugger-intg-tests > org.ballerinalang.debugger.test.adapter.evaluation.SingleFileEvaluationTest > literalEvaluationTest FAILED
    java.lang.AssertionError: expected [-20] but found [null]
        at org.testng.Assert.fail(Assert.java:110)
        at org.testng.Assert.failNotEquals(Assert.java:1413)
        at org.testng.Assert.assertEqualsImpl(Assert.java:149)
        at org.testng.Assert.assertEquals(Assert.java:131)
        at org.testng.Assert.assertEquals(Assert.java:655)
        at org.testng.Assert.assertEquals(Assert.java:665)
        at org.ballerinalang.debugger.test.utils.DebugTestRunner.assertExpression(DebugTestRunner.java:676)
        at org.ballerinalang.debugger.test.adapter.evaluation.ExpressionEvaluationTest.literalEvaluationTest(ExpressionEvaluationTest.java:45)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at org.testng.TestRunner.privateRun(TestRunner.java:829)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
        at org.testng.SuiteRunner.run(SuiteRunner.java:330)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
        at org.testng.TestNG.runSuites(TestNG.java:1099)
        at org.testng.TestNG.run(TestNG.java:1067)
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:153)
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:96)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy2/jdk.proxy2.$Proxy5.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

debugger-intg-test-suite > debugger-intg-tests STANDARD_ERROR
    Jul 22, 2024 11:09:37 AM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireStreamClosed
    INFO: Socket closed
    java.net.SocketException: Socket closed
        at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1093)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:79)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)

debugger-intg-test-suite STANDARD_ERROR
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Steps to Reproduce
You can simply run the current main branch with Java 21 and skip checkstyle (-x check). 
Please use https://github.com/ballerina-platform/ballerina-lang/pull/43087 PR for all the changes done fixing checkstyle as well. 
Note: I have temporary disable debugger tests in workflow to check other test cases.

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Debugger

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by warunalakshitha**
## Purpose
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/43119
Fixes #43146

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by warunalakshitha** [comment]
We need to revisit spotbugs exclude for lang repository as a separate task later.

**Review by HindujaB — COMMENTED** [review]
Shall we add the `java21` branch to the PR build workflows?

**Comment by warunalakshitha** [comment]
> Shall we add the `java21` branch to the PR build workflows?

Added ubuntu and windows build. Full build pipeline will fail without stdlib migration. We can add that later.

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java [hunk 1]
```diff
@@ -57,7 +57,7 @@ public class TesterinaConstants {
     public static final String TESTABLE = "testable";
     public static final String MODIFIED = "mod";
     public static final String CACHE_DIR = "cache";
-    public static final String JAVA_17_DIR = "java17";
+    public static final String JAVA_21_DIR = "java21";
```
Comment (Dilhasha) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaConstants.java:60]: Shall we use a generic name for the constant e.g. `JAVA_PLATFORM_DIR`? so that we don't have to rename the variable for every update?

File: project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBalaWriter.java [hunk 2]
```diff
@@ -149,7 +149,7 @@ public void testBalaWriter(ITestContext ctx) throws IOException {
 
             Assert.assertEquals(packageJson.getVisibility(), "private");
 
-            Assert.assertEquals(packageJson.getPlatform(), "java17");
+            Assert.assertEquals(packageJson.getPlatform(), "java21");
```
Comment (Dilhasha) [inline project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBalaWriter.java:152]:
```suggestion
            Assert.assertEquals(packageJson.getPlatform(), JvmTarget.JAVA_21);
```

File: cli/ballerina-cli/src/test/resources/test-resources/tool-gayals/target-dir/.DS_Store
Comment (gayaldassanayake) [inline cli/ballerina-cli/src/test/resources/test-resources/tool-gayals/target-dir/.DS_Store:1]: This file must have been mistakenly added.

**Review by gayaldassanayake — APPROVED** [review]
Other than the comment added LGTM
