### PR TITLE
Fix Refactor OpenAPI validator plugin

### LINKED ISSUE #23611: Implement record to schema validation in openapi
**Description:**

- It got null point exception when handling validation in the resource against openapi contract for the nested record type in open API schema and ballerina resource. 

- The record validation openapi contract against the ballerina resource didn't happen for request body parameters.

> Implement BjsonSchemaUtil function for record validation
- [x] Implement the validate missing field in json schema 
- [x] Implement the validate missing filed in ballerina record
- [x] Implement the validate the type mismatching for given JSON and ballerina record
- - [x] validate record field has array type
- - [x] validate record field has different type item  with an array with respect to the JSON schema
- - [x] validate record field has nested array
- [x] Add valid unit tests for function
- [x] Add unit tests
- [x] Implement the validate nested record type
- [x] Implement the validate allOf, oneOf types

> Implement ResolveComponentUtil function for replacing the reference link with related schema
- [x] Replace reference in pathItems
- [x] Replace the reference in parameters
- [x] Replace the reference in http methods 
> Replace the reference with responses
-  [x] Multiple responses
- [x] One response has multiple MIME type
- [x] Response has multiple  reference ex: oneOf, anyOf
- [x] Replace the reference inside the component schemas
- - [x] Reference resolve with schema section
- - [x] Reference resolve with parameter section
- - [x] Reference resolve with response section 
- [x] Replace the reference inside the request body 
- [x] Add unit tests

>Invoke the validation function for the validator util
- [x] Implement ballerina record against openApi Schema validation
- [x] Implement openApi schema against ballerina record validation

### LINKED ISSUE #24722: Request body internal ref not resolved OpenAPI
**Description:**
Basically, when OpenApiV3Parser parses a post reusable response, parameters with the relevant ref but request body with a schema ref and reusable request body ref, the ref isn't being resolved for the request body.

**Suggested Labels (optional):**
 Area/BuildTools  , Component/ToolSwagger

### LINKED ISSUE #24988: Refactor openapi validator plugin
**Description:**

Refactor openapi validator plugin

>   Match available resources with the operation ID 
- [x] Implement  model for getting a summary of all the resource  path with paths' available methods
- [x] If the resource is missing service will be highlighted with the missing resource error
- [x] If there is an extra resource in service the resource will be highlighted with an error
- [x] To match consider the tags and operations provided with the annotation.

> Separate Util will be written to match a resource and operation 
- Input would be OpenAPI Operation Model and Ballerina Resource Node
- [x] Resource function node validates against the operation model  
- [x] Operation model validate against the resource function node

> Implement the Service validator

- [x] Filter out operations using filters and find matching resources for the operations 
- [x] If resources are missing for the operation issue errors and Check if there are additional resources defined in service if so issue errors 
- [x]  Resource validation for each matching operation and resource

**Suggested Labels (optional):**
 Area/Tooling,  Component/APIDesigner ,  Type/Improvement 

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
Fixes   #23611 
Fixes   #24722 
Fixes   #24988

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/BTypeToJsonValidatorUtil.java [hunk 1]
```diff
@@ -0,0 +1,785 @@
...
+import org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType;
+
+import java.util.ArrayList;
+import java.util.HashSet;
+import java.util.Iterator;
+import java.util.List;
+import java.util.Map;
+import java.util.Set;
+
+
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/BTypeToJsonValidatorUtil.java:45]: Shall we remove this extra line?

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/BTypeToJsonValidatorUtil.java [hunk 2]
```diff
@@ -0,0 +1,785 @@
...
+     * @throws OpenApiValidatorException
+     */
+    private static void validateOneOftypeRecord(List<ValidationError> validationErrors, List<Schema> oneOflist,
+                                                List<ValidationError> validationErrorsBa, BType member)
+            throws OpenApiValidatorException {
+
+        if ((!(oneOflist.isEmpty())) && member instanceof BRecordType) {
+            Iterator<Schema> oneOfSchema = oneOflist.iterator();
+            while (oneOfSchema.hasNext()) {
+                Schema schema2 = oneOfSchema.next();
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/BTypeToJsonValidatorUtil.java:240]: Can we rename this variable? Check other places as well.

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/Filters.java [hunk 3]
```diff
@@ -0,0 +1,56 @@
+package org.ballerinalang.openapi.validator;
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/Filters.java:1]: License header is missing.

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java [hunk 4]
```diff
@@ -0,0 +1,534 @@
+/*
+ * Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java:2]: Shall we change the year to '2020' in the license header?

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java [hunk 5]
```diff
@@ -0,0 +1,534 @@
...
+                // Else if exclude tag filtering available validate only the operations that are not include
+                // exclude Tags.
+                // Else proceed only to validate filtered operations.
+                if (tagFilteringEnabled) {
+                    Iterator<Map.Entry<String, Operation>> operations =
+                            openAPIPathSummary.getOperations().entrySet().iterator();
+                    while (operations.hasNext()) {
+                        Map.Entry<String, Operation> operationMap = operations.next();
+//                        Check operationId is null scenario.
+                        if ((filters.getOperation().contains(operationMap.getValue().getOperationId())) ||
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java:78]:
```suggestion
                        if (filters.getOperation().contains(operationMap.getValue().getOperationId()) ||
```

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java [hunk 6]
```diff
@@ -0,0 +1,534 @@
+/*
```
Comment (parkavi11) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java:1]: Can we rename the class name? IMO, we do not use imperative forms for naming classes. Better to refer to some documentations regarding naming conventions.

File: misc/openapi-ballerina/modules/openapi-validator/src/test/resources/project-based-tests/src/contractValidation/ballerina/valid/petstore.bal [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+
+listener http:Listener ep0 = new(80, config = {host: "petstore.openapi.io"});
+
+listener http:Listener ep1 = new(443, config = {host: "petstore.swagger.io"});
+
+@openapi:ServiceInfo {
+    contract: "resources/petstore.yaml",
+    tags: [ ],
+    operations:[]
+    //excludeTags: [],
```
Comment (parkavi11) [inline misc/openapi-ballerina/modules/openapi-validator/src/test/resources/project-based-tests/src/contractValidation/ballerina/valid/petstore.bal:12]: Can we remove these commented lines if not required?

File: misc/openapi-ballerina/modules/openapi-validator/src/test/resources/project-based-tests/src/operationHandle/ballerina/valid/petstoreNestedArrayType.bal [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+    string password;
+    int [][][][] phone;
+};
+
+service hello on new http:Listener(9090) {
+    @http:ResourceConfig {
+            methods:["POST"],
+            path:"/user",
+            body: "body"
+
```
Comment (parkavi11) [inline misc/openapi-ballerina/modules/openapi-validator/src/test/resources/project-based-tests/src/operationHandle/ballerina/valid/petstoreNestedArrayType.bal:18]: Can we remove this extra line?

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java [hunk 9]
```diff
@@ -0,0 +1,534 @@
...
+//                                    tag then remove operations.
+                            if (operationMap.getValue().getTags() == null) {
+                                operations.remove();
+                            } else if (Collections.disjoint(filters.getTag(), operationMap.getValue().getTags())) {
+//                                        Remove operation
+                                operations.remove();
+                            }
+                        } else {
+                            operations.remove();
+                        }
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java:90]: Here for all conditions, doing the same operations (```operations.remove();```). Can't we simplify this code block?

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java [hunk 10]
```diff
@@ -0,0 +1,534 @@
...
+        List<OpenapiServiceValidationError> validationErrors = new ArrayList<>();
+        List<ResourcePathSummary> resourcePathSummaries = summarizeResources(serviceNode);
+//        check the contract paths are available at the resource
+        for (OpenAPIPathSummary openAPIPathSummary: openAPISummaries) {
+            Boolean isServiceExit = false;
+            for (ResourcePathSummary resourcePathSummary: resourcePathSummaries) {
+                if (openAPIPathSummary.getPath().equals(resourcePathSummary.getPath())) {
+                    isServiceExit = true;
+//                    check whether documented operations are available at resource file
+                    if ((!openAPIPathSummary.getAvailableOperations().isEmpty())) {
```
Comment (parkavi11) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java:272]: Can we remove that extra bracket?
```suggestion
                    if (!openAPIPathSummary.getAvailableOperations().isEmpty()) {
```

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java (hunk 9 above)
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java:90]: Here for all condition checks, doing the same operations (operations.remove();). Can't we simplify this code block?

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java [hunk 11]
```diff
@@ -0,0 +1,534 @@
...
+     */
+    public static List<ResourcePathSummary>  summarizeResources(ServiceNode serviceNode) {
+        // Iterate resources available in a service and extract details to be validated.
+        List<ResourcePathSummary> resourceSummaryList = new ArrayList<>();
+        for (FunctionNode resource : serviceNode.getResources()) {
+            AnnotationAttachmentNode annotation = null;
+
+            // Find the "ResourceConfig" annotation.
+            for (AnnotationAttachmentNode ann : resource.getAnnotationAttachments()) {
+
```
Comment (parkavi11) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java:320]: Can we remove this extra line? Better to check other places too

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java [hunk 12]
```diff
@@ -0,0 +1,534 @@
...
+                            if (operationMap.getValue().getTags() == null) {
+                                operations.remove();
+                            } else if (Collections.disjoint(filters.getTag(), operationMap.getValue().getTags())) {
+                                operations.remove();
+                            }
+                        } else {
+                            operations.remove();
+                        }
+                    }
+                } else {
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java:158]: If we are doing the same operations for all places, Why we are having these checks separately? Please correct me, If I missed anything.

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenApiValidatorUtil.java [hunk 13]
```diff
@@ -0,0 +1,194 @@
...
+                            .compileModule(sourceRootPath, getModuleName(moduleName));
+
+                    // If there are no compilation errors do not continue the process.
+                    if (bLangPackage.diagCollector.hasErrors()) {
+                        return;
+                    }
+                }
+            }
+        } catch (IOException | NullPointerException e) {
+//            throw LauncherUtils.createLauncherException(Messages.getException());
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenApiValidatorUtil.java:104]: Why this is commented? Don't we need to catch the exception here?

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenApiValidatorUtil.java [hunk 14]
```diff
@@ -0,0 +1,194 @@
...
+    }
+
+    /**
+     * Check whether the given file is a ballerina file.
+     *
+     * @param fileName file name to be check whether a ballerina file
+     * @return {@link Boolean} true or false
+     */
+    private static boolean isBalFile(String fileName) {
+        return fileName.endsWith(".bal");
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenApiValidatorUtil.java:115]: Shall we use this constant ```BLANG_SOURCE_EXT``` inside ProjectDirConstants class?

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenApiValidatorUtil.java [hunk 15]
```diff
@@ -0,0 +1,194 @@
...
+    public static BLangPackage compileFile(Path sourceRoot, String packageName) throws UnsupportedEncodingException {
+        emptyPrintStream = new EmptyPrintStream();
+        CompilerContext context = getCompilerContext(sourceRoot);
+        // Set the SourceDirectory to process this compilation as a program directory.
+        context.put(SourceDirectory.class, new FileSystemProgramDirectory(sourceRoot));
+        Compiler compiler = Compiler.getInstance(context);
+        // Set an EmptyPrintStream to hide unnecessary outputs from compiler.
+        compiler.setOutStream(emptyPrintStream);
+        return compiler.compile(packageName);
+    }
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenApiValidatorUtil.java:150]: Can't we merge these two methods using SourceType?

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/Filters.java [hunk 16]
```diff
@@ -0,0 +1,56 @@
...
+        this.tag = tag;
+        this.excludeTag = excludeTag;
+        this.operation = operation;
+        this.excludeOperation = excludeOperation;
+        this.kind = kind;
+    }
+
+    public List<String> getTag() {
+        return tag;
+    }
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/Filters.java:28]: Please add a line between these getters and setters.

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceMethod.java [hunk 17]
```diff
@@ -0,0 +1,103 @@
...
+
+    ResourceMethod() {
+        this.method = null;
+        this.methodPosition = null;
+        this.resourcePosition = null;
+        this.parameters = new HashMap<>();
+        this.body = null;
+    }
+
+    Diagnostic.DiagnosticPosition getMethodPosition() {
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceMethod.java:45]:
```suggestion
    public Diagnostic.DiagnosticPosition getMethodPosition() {
```

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceMethod.java [hunk 18]
```diff
@@ -0,0 +1,103 @@
...
+        return methodPosition;
+    }
+
+    void setMethodPosition(Diagnostic.DiagnosticPosition methodsPosition) {
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceMethod.java:49]:
```suggestion
    public void setMethodPosition(Diagnostic.DiagnosticPosition methodsPosition) {
```

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourcePathSummary.java [hunk 19]
```diff
@@ -0,0 +1,72 @@
...
+
+    void setPath(String path) {
+        this.path = path;
+    }
+
+    public Map<String, ResourceMethod> getMethods() {
+        return methods;
+    }
+
+    void addMethod(String method, ResourceMethod resourceMethod) {
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourcePathSummary.java:51]: Add modifiers to the methods. Please check other places as well.

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceValidator.java [hunk 20]
```diff
@@ -0,0 +1,250 @@
...
+     * @return  boolean value for indicating parameter is available
+     * @throws OpenApiValidatorException
+     */
+    private static Boolean validateRequestBodyResourceToOpenApi(Operation operation,
+                                                                List<ValidationError> validationErrors,
+                                                                ResourceParameter resourceParameter,
+                                                                Boolean isParameterExit, RequestBody requestBody)
+            throws OpenApiValidatorException {
+
+        if ((requestBody.getContent() != null) && !getOperationRequestBody(operation).isEmpty()) {
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceValidator.java:107]:
```suggestion
        if (requestBody.getContent() != null && !getOperationRequestBody(operation).isEmpty()) {
```

File: misc/openapi-ballerina/modules/openapi-validator/src/test/resources/project-based-tests/src/recordValidation/ballerina/invalidTests/oneOf/oneOf.bal [hunk 21]
```diff
@@ -0,0 +1,32 @@
...
+};
+type Dog record {
+    *Pet;
+     boolean bark;
+};
+//type Category record {
+//    int id;
+//    string name;
+//};
+
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/test/resources/project-based-tests/src/recordValidation/ballerina/invalidTests/oneOf/oneOf.bal:17]: Shall we remove this commented lines, if it is not required?

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/BTypeToJsonValidatorUtil.java [hunk 22]
```diff
@@ -0,0 +1,785 @@
...
+
+                                        if ((traversSchemaNestedArraySchema instanceof ArraySchema) &&
+                                                (traversNestedArrayBtype instanceof BArrayType)) {
+                                            traversSchemaNestedArray = (ArraySchema) traversSchemaNestedArraySchema;
+                                            traversNestedArray = (BArrayType) traversNestedArrayBtype;
+                                        }
+                                    }
+                                }
+                                //  Handle record type in item array
+                                if ((traversNestedArray.eType instanceof BRecordType) &&
```
Comment (parkavi11) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/BTypeToJsonValidatorUtil.java:489]: There is a small typo. `traversNestedArray` has to be `traverseNestedArray`. `traverse` is misspelled everywhere

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java (hunk 9 above)
Comment (lnash94) [reply misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/MatchResourcewithOperationId.java:90]: Yes, of course, we can simplify this first two if conditions, but the main block can not be replaced because it contains different another case that we need to skip by checking. :)

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceValidator.java [hunk 23]
```diff
@@ -0,0 +1,250 @@
...
+                Boolean isOParamExit = false;
+                // Temporary solution for skipping the query parameter, this if condition can be removed when openApi
+                // tool available with query parameter
+                if (param instanceof QueryParameter) {
+                    isOParamExit = true;
+                }
+                if (!resourceMethod.getParamNames().isEmpty()) {
+                    for (ResourceParameter resourceParam: resourceMethod.getParamNames()) {
+                        //  Check whether it is path parameter
+                        if ((param instanceof PathParameter) && (param.getName().equals(resourceParam.getName()))) {
```
Comment (suganyasuven) [inline misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceValidator.java:167]:
```suggestion
                        if (param instanceof PathParameter && param.getName().equals(resourceParam.getName())) {
```

File: misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenApiValidatorUtil.java (hunk 15 above)
Comment (lnash94) [reply misc/openapi-ballerina/modules/openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenApiValidatorUtil.java]: yes we can, I removed unused functions for test

File: misc/openapi-ballerina/modules/openapi-validator/build.gradle [hunk 24]
```diff
@@ -25,8 +27,54 @@ configurations.all {
 dependencies {
     implementation 'io.swagger.parser.v3:swagger-parser'
 
-    implementation project(':ballerina-tool')
+    // Standard libs
     implementation project(':ballerina-lang')
+    implementation project(':language-server:language-server-compiler')
+
+    implementation project(':ballerina-runtime')
```
Comment (hevayo) [inline misc/openapi-ballerina/modules/openapi-validator/build.gradle:34]: Can we check why do we need all this std lib dependencies ?

**Review by hevayo — CHANGES_REQUESTED** [review]

File: misc/openapi-ballerina/modules/openapi-validator/build.gradle (hunk 24 above)
Comment (lnash94) [reply misc/openapi-ballerina/modules/openapi-validator/build.gradle]: previously used this for creating the tests run, we can remove these. I will remove unused dependencies.

**Review by hevayo — APPROVED** [review]
