### PR TITLE
[Semantic API] Add Support for Markdown Documentation Parameter Symbol Lookup

### LINKED ISSUE #31964: Symbol of a documentation parameter comes as empty
**Description:**
The symbol of a markdown documentation parameter results in an empty `Optional<Symbol>`.

**Steps to reproduce:**
```
# Description
#
# + x - Field Description  
public type Coord record {
    readonly int x;
    # + y - Field Description
    int y;
};
```
Get the symbol of `x` documentation parameter.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by sanjana**
- Type definitions 
   - Record type definitions
   - Object type definitions
- Class definitions
- Function definitions

Fixes #31964

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java [hunk 1]
```diff
@@ -283,6 +285,10 @@ public void visit(BLangFunction funcNode) {
             return;
         }
 
+        if (funcNode.getMarkdownDocumentationAttachment() != null) {
+            lookupNodes(funcNode.markdownDocumentationAttachment.parameters);
+        }
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java:290]: Better if these are also handled in the normal flow of the visitor, instead of adding null checks everywhere and checking.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java [hunk 2]
```diff
@@ -1595,6 +1609,19 @@ private boolean isWithinNodeMetaData(TopLevelNode node) {
             }
         }
 
+        if (node instanceof DocumentableNode) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java:1612]: Need to rethink this. **This is only working by chance, not design**.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java (hunk 1 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java]: Replaced with `lookupNode()` for `markdownDocumentationAttachment` property.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java [hunk 3]
```diff
@@ -147,6 +147,11 @@ public void testTypeDefPositions(int sLine, int sCol, String expSymbolName, int
             return new Object[][] {
                     {88, 4, "Module", 78, 12, 78, 18},
                     {80, 5, "TypeDef", 80, 5, 80, 12},
+                    {96, 4, "abc", 98, 17, 98, 20},
```
Comment (pubudu91) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java:150]: Why add tests as position tests for these? 🤔

Comment (sanjana) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java:150]: When looking up a symbol of a documentation parameter, the actually defined position of the symbol is different from the cursor position. 
Therefore, in order to verify that info as well, decided to use the Position Tests for these.

The first two parameters are the cursor position, followed by the symbol name, and the position where the symbol is actually defined.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java (hunk 2 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java:1602]: Updated the logic which prevented from reaching this code segment.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java (hunk 3 above)
Comment (pubudu91) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java:150]: I see. I think it'd be best to move these tests to their own test class since what we are primarily interested in is whether `symbol()` works for doc params as well. This position test is for testing particular scenarios where we need to check whether the symbol's position is correct.

Comment (sanjana) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java:150]: @pubudu91 The https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/ballerina-compiler-api-test/src/test/resources/test-src/documentation_test.bal source file contains a couple of compilation errors that block the `CompilerPhaseRunner` from proceeding after the Type Checking phase. 

Therefore, would it be better if a separate source file is created if the `DocumentationTest` class is to be used for these tests as well?

Comment (sanjana) [reply tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolPositionTest.java]: Moved to `DocumentationTest` class.

**Review by pubudu91 — APPROVED** [review]
