### PR TITLE
Fix member access with valid union type expression

### LINKED ISSUE #39959: [Bug]: Compilation error when using value with union of same type as expression of member access
### Description

$title. 
```ballerina
public function main() {
    record {|
        int a;
    |} r = {a: 1};
    string|string s = "a";
    r[s] = 2; 
}
```
Encountered a compilation error when attempting to use an expression with a union of the same type as the expression of member access. Received the error message `invalid record member access expression: value space 'string' out of range` for the above program.

Following program compiles without an error
```ballerina
public function main() {
    record {|
        int a;
    |} r = {a: 1};
    string s = "a";
    r[s] = 2; 
}
```
**Expected Behavior:**
The above programs should compile without any errors.

### Steps to Reproduce

_No response_

### Affected Version(s)

2201.4.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by ushirask**
Fixes #39959

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -8568,24 +8568,25 @@ private BType checkArrayIndexBasedAccess(BLangIndexBasedAccess indexBasedAccess,
...
-                        .collect(Collectors.toList());
-
-                BFiniteType finiteType;
-                if (finiteTypes.size() == 1) {
-                    finiteType = finiteTypes.get(0);
-                } else {
-                    Set<BLangExpression> valueSpace = new LinkedHashSet<>();
-                    finiteTypes.forEach(constituent -> valueSpace.addAll(constituent.getValueSpace()));
-                    finiteType = new BFiniteType(null, valueSpace);
+                // address the case where we have a union of types
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8571]: Example 1
```ballerina
public function main() {
    record {|
        int a;
    |} r = {a: 1};
    string s = "a";
    r[s] = 2; 
}
```
Example 2
```ballerina
public function main() {
    record {|
        int a;
    |} r = {a: 1};
    string|string s = "a";
    r[s] = 2; 
}
```
When considering the first example, it is working. In the second example, we model `string|string` as a union type with only one member (which is `string`). Isn't this the actual root cause?

If it is a union type, it should contain more than one member. So here`string|string` should be equivelent to the `string` type.

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8571]: Here, I have a different opinion. The `string|string:Char` type should be modelled as a `string` type, rather than a union of those two types.

Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8571]: I think we'll still need this change for a case like,
```
int[] arr = [1, 2, 3];
int:Signed16|int:Unsigned16 a = 1;
arr[a] = 4;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -9428,6 +9413,16 @@ private LinkedHashSet<BType> getTypeWithoutNilForNonAnyTypeWithNil(BType type) {
         return memberTypes;
     }
 
+    private BFiniteType createFiniteTypeFromFiniteTypeList(List<BFiniteType> finiteTypes) {
+        if (finiteTypes.size() == 1) {
+            return finiteTypes.get(0);
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:9418]: Shall we add a test to cover this?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 3]
```diff
@@ -1178,6 +1178,64 @@ function testUnspecifiedFieldRecordMemberAccessWithStringCharKeyExpr() {
...
+    |} r2 = {a: "a", b: 1};
+    string|STR2 s2 = "b";
+    r2[s2] = 2;
+    assertEquality(2, r2.b);
+
+    float[] arr2 = [0.1, 1.2, 2.3];
+    INT2|int:Signed8 x2 = 0;
+    arr2[x2] = 4.5;
+    assertEquality(4.5, arr2[0]);
+}
```
Comment (prakanth97) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:1237]: Shall we add more tests like this 
```
type INTUNION 1|2|3|4;

public function main() {
    int[] arr = [1, 2, 3];
    int|INTUNION x = 1;
    arr[x] = 4;

    record {|
        int a;
    |} r = {a: 1};
    "a"|"b" s = "a";
    r[s] = 2;
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 4]
```diff
@@ -8701,23 +8702,15 @@ private BType checkTupleIndexBasedAccess(BLangIndexBasedAccess accessExpr, BTupl
...
-                BType possibleType = checkTupleIndexBasedAccess(accessExpr, tuple, finiteType);
-                if (possibleType.tag == TypeTags.UNION) {
-                    possibleTypesByMember.addAll(((BUnionType) possibleType).getMemberTypes());
-                } else {
-                    possibleTypesByMember.add(possibleType);
+                if (!finiteTypes.isEmpty()) {
+                    BFiniteType finiteType = createFiniteTypeFromFiniteTypeList(finiteTypes);
+                    BType possibleType = checkTupleIndexBasedAccess(accessExpr, tuple, finiteType);
+                    if (possibleType.tag == TypeTags.UNION) {
+                        possibleTypesByMember.addAll(((BUnionType) possibleType).getMemberTypes());
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8709]: Do we have a test that reach this point?

**Comment by prakanth97** [comment]
@ushirask could you pls resolve the conflicts and sync with the master?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8596]: @lochana-chathura will this fixed by your semtype integration? 
```
int[] arr = [1, 2, 3];
int:Signed16|int:Unsigned16 a = 1;
arr[a] = 4;
```
Even for this scenario also, we can represent the union type `int:Signed16|int:Unsigned16` as set containing union of both types. Is it possible with the current `BType` implementation? 

WDYT?

looping @hasithaa as well

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java [hunk 5]
```diff
@@ -531,6 +543,10 @@ public void testNestedMemberAccessOnIntersectionTypes() {
         BRunUtil.invoke(result, "testNestedMemberAccessOnIntersectionTypes");
     }
 
+    @Test
+    public void testNestedMemberAccessWithSameTypeUnionExprAsIndex() {
+        BRunUtil.invoke(result, "testUnionTypeExprMemberAccess");
+
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java:549]: Can't see the closing brace of the method. Hence, fail to compile

Comment (ushirask) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java:550]: Seems to be a merge conflict. Fixed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8620]: Yes, semtype can fix this. `BFiniteType` keeps a list of literal values. So adding all the values of `int:Signed16|int:Unsigned16` to it is not practical.  The current logic from the PR looks okay to me.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 4 above)
Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8733]: try this.
```
public function main() {
    [int, string] tup = [1, "x"];
    0|1|int a = 0;
    tup[a] = 4;
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access_negative.bal [hunk 6]
```diff
@@ -376,3 +376,32 @@ function testCustomTupleTypesAccessNegative() {
     var x14 = t7[2][index];
     boolean _ = x14; //error: incompatible types: expected 'boolean', found 'int'
 }
+
+type STR string;
+type STRINT string|int;
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access_negative.bal:381]: Usually, for constants, we use the UPPERCASE. 
Hbt `Str` and `StrOrInt`?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access_negative.bal [hunk 7]
```diff
@@ -376,3 +376,32 @@ function testCustomTupleTypesAccessNegative() {
...
+
+function testMemberAccessWithInvalidUnionTypeExpr() {
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access_negative.bal:383]:
```suggestion
function testMemberAccessWithUnionTypedIndexExprNegative() {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 8]
```diff
@@ -1178,6 +1178,64 @@ function testUnspecifiedFieldRecordMemberAccessWithStringCharKeyExpr() {
     assertTrue(v is ());
 }
 
+type INT int;
+type INT2 int|int:Signed16;
+type STR2 string|string:Char;
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:1183]: for names how about `Int1`, `Int2`, `Str1`?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 9]
```diff
@@ -1178,6 +1178,64 @@ function testUnspecifiedFieldRecordMemberAccessWithStringCharKeyExpr() {
...
+
+function testUnionTypeExprMemberAccess() {
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:1185]: The name is misleading. We are not member-accessing a union-typed expr. 
```suggestion
function testMemberAccessWithUnionTypedIndexExpr() {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal (hunk 8 above)
Comment (ushirask) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:1183]: Changed to `IntType1` etc, is that acceptable?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java [hunk 10]
```diff
@@ -531,6 +543,11 @@ public void testNestedMemberAccessOnIntersectionTypes() {
         BRunUtil.invoke(result, "testNestedMemberAccessOnIntersectionTypes");
     }
 
+    @Test
+    public void testNestedMemberAccessWithSameTypeUnionExprAsIndex() {
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java:547]: NestedMemberAccess? Fix the name.

Comment (ushirask) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/access/MemberAccessTest.java]: Fixed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 4 above)
Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:8733]: Added suggested example.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal (hunk 8 above)
Comment (lochana-chathura) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal]: Ok. Then, IntType1, IntType2, StrType1 ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (ushirask) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:9442]: Will be covered by newly added tests.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal (hunk 8 above)
Comment (ushirask) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal]: Currently it's `IntType`, `IntType2`, `Str`, will change as originally suggested for a common format

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 11]
```diff
@@ -1178,11 +1178,12 @@ function testUnspecifiedFieldRecordMemberAccessWithStringCharKeyExpr() {
     assertTrue(v is ());
 }
 
-type INT int;
-type INT2 int|int:Signed16;
-type STR2 string|string:Char;
+type IntType int;
+type IntType2 int|int:Signed16;
+type Str2 string|string:Char;
+type IntUnion 1|2|3|4;
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:1184]: We better use a consistent pattern when naming. It improves readability.

IntType, Str2 is not consistent. 
IntUnion is again not good as `int|int:Signed16` is also an int union.  

HBT IntType, IntType2, StrType, IntType3?

Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal]: Instead of `IntType` better to use `IntType1`

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal [hunk 12]
```diff
@@ -1178,11 +1178,12 @@ function testUnspecifiedFieldRecordMemberAccessWithStringCharKeyExpr() {
     assertTrue(v is ());
 }
 
-type INT int;
-type INT2 int|int:Signed16;
-type STR2 string|string:Char;
+type Int1 int;
+type Int2 int|int:Signed16;
+type Str1 string|string:Char;
+type IntUnion 1|2|3|4;
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal:1184]: Let's call it Int3 for the consistency

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal (hunk 11 above)
Comment (lochana-chathura) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/access/member_access.bal]: +1

**Review by lochana-chathura — APPROVED** [review]

**Review by prakanth97 — APPROVED** [review]
