### PR TITLE
Validate the LHS expression in compound assignment

### LINKED ISSUE #19116: LHS expression cannot be a function invocation in compound assignment
**Description:**
$subject

**Steps to reproduce:**
```
import ballerina/io;

public function main() {
    Bar ba = {};

    foo(ba).bar += 10;
    io:println(ba);
}

function foo(Bar b) returns Bar {
    b.bar += 1;
    return b;
}

type Bar record {
    int bar = 0;
};
```
Above code runs without throwing an error.

**Affected Versions:**
Ballerina 1.0.0
Language specification 2019R3

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose
In the compound assignment, LHS expression cannot be a function invocation. This issue is fixed here.

Fixes #19116

## Approach
Validate the LHS expression. It throws an error once it found a function invocation in LHS.

## Remarks
#17998

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by SupunS** [comment]
Please refer: https://github.com/ballerina-platform/ballerina-lang/issues/19116#issuecomment-533761863

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java [hunk 1]
```diff
@@ -382,6 +382,7 @@ public void testCompoundAssignmentNegative() {
         BAssertUtil.validateError(compileResult, i++, "operator '>>>' not defined for 'int' and 'string'", 120, 5);
         BAssertUtil.validateError(compileResult, i++, "operator '+' not defined for 'int?' and 'int?'", 132, 5);
         BAssertUtil.validateError(compileResult, i++, "operator '+' not defined for 'int?' and 'int?'", 140, 5);
-        BAssertUtil.validateError(compileResult, i, "operator '+' not defined for 'int?' and 'int'", 150, 11);
+        BAssertUtil.validateError(compileResult, i++, "operator '+' not defined for 'int?' and 'int'", 150, 11);
+        BAssertUtil.validateError(compileResult, i, "invalid assignment in variable 'foo(bar)'", 156, 5);
```
Comment (SupunS) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java]: should we have a more specific error message? something like `function invocation are not allowed in lhs...`

Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/compoundassignment/CompoundAssignmentTest.java]: Fixed.
