### PR TITLE
Filter out Visible Worker Symbols within their Declaration Body

### LINKED ISSUE #33665: Invalid worker is captured at send-action context
**Description:**
Consider the following source snippet,

```
function getIntVal() returns int {
    worker w1 {
        int x = 12;
        x-><cursor>
    }

    worker w2 {
        
    }
}
```

Here, the `w1` is captured as a visible symbol at the cursor position. 

**Steps to reproduce:**

**Affected Versions:**
SwanLake-beta3 at least

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #33665

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java [hunk 1]
```diff
@@ -469,12 +471,24 @@ private boolean withinRange(LineRange range, LineRange specifiedRange) {
...
+
+        // Checks if the enclosed node is within a worker declaration body and the encountered symbol is the same
+        // worker that is being declared.
+        if (Symbols.isFlagOn(symbolEnvScopeOwner.flags, Flags.WORKER)
+                && Symbols.isFlagOn(symbol.flags, Flags.WORKER)
+                && symbolEnv.enclEnv != null
+                && symbolEnv.enclEnv.node.getKind() == NodeKind.FUNCTION
+                && isWithinCurrentWorker(((BLangFunction) symbolEnv.enclEnv.node).defaultWorkerName, symbol)) {
+            return;
+        }
```
Comment (nadeeshaan) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java:490]: What if we enclose this whole if check within `isWithinCurrentWorker` so the logic will be much cleaner? WDYT? Other than that, the changes looks good

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java (hunk 1 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java]: @nadeeshaan updated.

**Review by mohanvive — APPROVED** [review]

**Review by nadeeshaan — APPROVED** [review]
LGTM
