### PR TITLE
Revamp completion router logic and the type descriptor contexts's completions

### LINKED ISSUE #31382: [LS] Incorrect resolution of context when the cursor is positioned within leading minutiae
**Description:**
$subject observed for the following cases.
```ballerina
public function testFunction() {
    isolated <cursor>
}
```
```ballerina
public class TestClass {
    isolated <cursor>
}
```
The resolved context for the completion provider is functionBodyBlockNodeContext in the first case instead of variable declaration and ClassDef in the second in the second case.

Following is the syntax tree for the first case
syntax tree

### LINKED ISSUE #31398: Revamp Completion item sorting in stream type descriptor context
**Description:**
$title

### PR DESCRIPTION
**Pull request by nadeeshaan**
Fixes #31398 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterNodeContext.java [hunk 1]
```diff
@@ -15,44 +15,21 @@
  */
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterNodeContext.java:15]: Could you provide an instance where we would need to extend the TypeParameterContextProvider besides TypeParameterNodeContext

**Review by malinthar — APPROVED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterNodeContext.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeParameterNodeContext.java:15]: You can refer `StreamTypeParamsNodeContext`

**Review by IMS94 — APPROVED** [review]
LGTM!
