### PR TITLE
Fix module and program execution order

### LINKED ISSUE #14375: Fix Module and program execution wrt 2019r1
Refer 2019r1 Spec section "Module and program execution"

TODO: Add task Items here.

### PR DESCRIPTION
**Pull request by pubudu91**
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVMExecutor.java [hunk 1]
```diff
@@ -262,7 +230,7 @@ private static BValue populateReturnData(StrandCallback strandCallback, Callable
      *
      * @param programFile to be invoked.
      */
-    private static void invokePackageInitFunctions(ProgramFile programFile) {
+    public static void invokePackageInitFunctions(ProgramFile programFile) {
         for (PackageInfo info : programFile.getPackageInfoEntries()) {
             BValue result = execute(programFile, info.getInitFunctionInfo(), new BValue[0], null, true);
```
Comment (Shan1024) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVMExecutor.java]: Seems like we always pass `null` as the 4th argument and `true` as the 5th argument. Shall we refactor them in this PR as well?

File: settings.gradle [hunk 2]
```diff
@@ -52,7 +52,7 @@ include(':ballerina-streaming')
 include(':ballerina-logging')
 include(':ballerina-launcher')
 include(':ballerina-packerina')
-include(':ballerina-backend-llvm')
+//include(':ballerina-backend-llvm')
```
Comment (Shan1024) [inline settings.gradle]: Shall we remove these dependencies if not needed?

File: tests/ballerina-integration-test/src/test/resources/testng.xml [hunk 3]
```diff
@@ -107,7 +107,7 @@
             <class name="org.ballerinalang.test.auth.AuthzConfigInheritanceTest"/>
             <class name="org.ballerinalang.test.auth.ResourceLevelAuthTest"/>
             <class name="org.ballerinalang.test.auth.ServiceLevelAuthnTest"/>
-            <class name="org.ballerinalang.test.auth.OAuthConfigTest"/>
+            <!--<class name="org.ballerinalang.test.auth.OAuthConfigTest"/>-->
```
Comment (Shan1024) [inline tests/ballerina-integration-test/src/test/resources/testng.xml]: Shall we remove this as well if not needed?

File: cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java [hunk 4]
```diff
@@ -404,16 +351,59 @@ private static void runBal(Path sourceRootPath, Path sourcePath, String[] args,
...
+        try {
+            exitCode = executeCompiledProgram(programFile, args);
+        } catch (BLangUsageException | BallerinaException e) {
+            throw createUsageException(makeFirstLetterLowerCase(e.getLocalizedMessage()));
         }
+
         BLangProgramRunner.resumeStates(programFile);
         listeners.forEach(listener -> listener.afterRunProgram(runServicesOnly));
+
+        if (!programFile.isServiceEPAvailable()) {
```
Comment (MaryamZi) [inline cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java]: The spec says "If the main function returns an error, then the program terminates."

IINM, we are not checking if the main function returns an error here right? So even if an error is returned, if there are services, the execution continues?

Comment (pubudu91) [reply cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java]: Ah yes, should exit if the exit code is not 0. Will modify this.

File: settings.gradle (hunk 2 above)
Comment (pubudu91) [reply settings.gradle]: Commented because this module is commented out in build profiles in the parent pom as well. I think it's just temporarily disabled. So just commented it out in Gradle files as well.

File: tests/ballerina-integration-test/src/test/resources/testng.xml (hunk 3 above)
Comment (pubudu91) [reply tests/ballerina-integration-test/src/test/resources/testng.xml]: This is needed. This test needs to be refactored to align with the changes introduced in this PR. Created #15049 to track this.

File: bvm/ballerina-core/src/main/java/org/ballerinalang/BLangProgramRunner.java [hunk 5]
```diff
@@ -36,44 +41,71 @@
...
+        }
+
+        if (programFile.isServiceEPAvailable()) {
+            executeListenPhase(programFile);
+        }
+        return returnVal;
+    }
 
-        BVMExecutor.initProgramFile(programFile);
+    public static BValue[] runProgram(ProgramFile programFile, String... args) {
```
[the remark this answers is not in the document]
Comment (pubudu91) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/BLangProgramRunner.java]: This handles the case you mentioned as well since `args` is a vararg.

File: cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java (hunk 4 above)
Comment (pubudu91) [reply cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/LauncherUtils.java]: Actually, the listen phase will not be executed if there is an error in the main(). But here, the problem is the exit code returned by the main() will not be passed on to the runtime when exiting.

File: bvm/ballerina-core/src/main/java/org/ballerinalang/BLangProgramRunner.java [hunk 6]
```diff
@@ -36,44 +41,71 @@
...
-        // Get the service package
-        PackageInfo servicesPackage = programFile.getEntryPackage();
-        if (servicesPackage == null) {
-            throw new BallerinaException("no services found in '" + programFile.getProgramFilePath() + "'");
+    public static BValue[] runProgram(ProgramFile programFile, FunctionInfo functionInfo, String[] args) {
+        BValue[] bValArgs;
+        if (functionInfo != null) {
+            bValArgs = extractEntryFuncArgs(functionInfo, args);
+        } else {
+            bValArgs = new BValue[0];
```
Comment (hasithaa) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/BLangProgramRunner.java]: There can be a scenario, the user has provided args, but a FunctionInfo. In such a case, we are overriding args with empty BValue[], which is incorrect.

File: bvm/ballerina-core/src/main/java/org/ballerinalang/BLangProgramRunner.java [hunk 7]
```diff
@@ -36,44 +41,71 @@
...
         Debugger debugger = new Debugger(programFile);
         initDebugger(programFile, debugger);
+        return runProgram(programFile, debugger, functionInfo, args);
+    }
+
+    public static BValue[] runProgram(ProgramFile programFile, Debugger debugger, FunctionInfo functionInfo,
+                                      BValue... args) {
+        BVMExecutor.invokePackageInitFunctions(programFile);
+
+        BValue[] returnVal = null;
```
Comment (hasithaa) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/BLangProgramRunner.java]: Shall we try to remove BValue[], and use BValue instead?

File: bvm/ballerina-core/src/main/java/org/ballerinalang/BLangProgramRunner.java [hunk 8]
```diff
@@ -103,4 +135,17 @@ public static FunctionInfo getMainFunctionInfo(PackageInfo entryPkgInfo) {
...
     }
+
+    private static void executeListenPhase(ProgramFile programFile) {
+        PrintStream outStream = System.out;
+
+        ServerConnectorRegistry serverConnectorRegistry = new ServerConnectorRegistry();
+        programFile.setServerConnectorRegistry(serverConnectorRegistry);
+        serverConnectorRegistry.initServerConnectors();
+
+        outStream.println("Initiating service(s) in '" + programFile.getProgramFilePath() + "'");
```
Comment (hasithaa) [inline bvm/ballerina-core/src/main/java/org/ballerinalang/BLangProgramRunner.java]: IMO, we shouldn't print anything to the outstream implicitly. That is Endpoint authors responsibility to put such logs. So shall we remove this?

Comment (pubudu91) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/BLangProgramRunner.java]: This has been there since the early days though. I just moved it to BLangProgramRunner.

Comment (hasithaa) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/BLangProgramRunner.java]: let's remove it.

Comment (pubudu91) [reply bvm/ballerina-core/src/main/java/org/ballerinalang/BLangProgramRunner.java]: Ok, will do
