### PR TITLE
Fix incorrect diagnostic codes related to RegExp errors

### LINKED ISSUE #40656: [Bug]: Incorrect error codes used for RegExp related errors
### Description

$subject for https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java#L799C5-L802

User impact:
```ballerina
   //diagnostic code for below error changes from `BCS4044` to `BCE4044`
    _ = re ``; //@error: regular expression is not allowed: empty RegExp 
```

```ballerina
   //diagnostic code for below error changes from `BCS4045` to `BCE4045`
    _ = re `[]`; //@error: empty character class disallowed 
```

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #40656 

```ballerina
   //diagnostic code for below error changes from `BCS4044` to `BCE4044`
    _ = re ``; //@error: regular expression is not allowed: empty RegExp 
```

```ballerina
   //diagnostic code for below error changes from `BCS4045` to `BCE4045`
    _ = re `[]`; //@error: empty character class disallowed 
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by MaryamZi — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 1]
```diff
@@ -797,9 +797,9 @@ public enum DiagnosticErrorCode implements DiagnosticCode {
     WORKER_RECEIVE_ACTION_NOT_ALLOWED_IN_LOCK_STATEMENT(
             "BCE4043", "worker.receive.action.not.allowed.in.lock.statement"),
     EMPTY_REGEXP_STRING_DISALLOWED(
-            "BCS4044", "empty.regexp.string.disallowed"),
+            "BCE4044", "empty.regexp.string.disallowed"),
     UNSUPPORTED_EMPTY_CHARACTER_CLASS(
-            "BCS4045", "unsupported.empty.character.class")
+            "BCE4045", "unsupported.empty.character.class")
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:802]: Can't we write these inline? I don't think they will exceed 120.

**Review by MaryamZi — APPROVED** [review]

**Review by lochana-chathura — APPROVED** [review]
