### PR TITLE
Fix NodeCloner issue in let expression

### LINKED ISSUE #21528: Symbol Reference mismatch for the let expressions
**Description:**
Consider the following example,

`int helloVar = let int `**testLetVar** `= 4 in 2*` **testLetVar** `*globalVar;`

in the above example, testLetVar reference in the let letVarDeclaration is being different from the one in the expression (two code segments which are bold having different symbol references)

### PR DESCRIPTION
**Pull request by irshadnilam**
## Purpose
$title

Fixes #21528

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java [hunk 1]
```diff
@@ -991,7 +991,7 @@ public void visit(BLangLetExpression source) {
         BLangLetExpression clone = new BLangLetExpression();
         source.cloneRef = clone;
         clone.letVarDeclarations = cloneLetVarDeclarations(source.letVarDeclarations);
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java]: Can't you use the `cloneList()` method for this?

Comment (irshadnilam) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java]: BLangLetVariable does not extends `Node`

`private <T extends Node> List<T> cloneList(List<T> nodes) {`
