### PR TITLE
Fix issues with handling empty keyed tables

### LINKED ISSUE #35310: Compiling a table with an empty key field throws ArrayIndexOutOfBoundsException
**Description:**

Consider the scenario below.

Screenshot 2022-03-02 at 22 13 24

It shows no error diagnostics, but throws the following ArrayIndexOutOfBoundsException once compiled.

```
[2022-03-02 22:04:52,418] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at io.ballerina.runtime.internal.values.TableValueImpl$KeyHashValueHolder$DefaultKeyWrapper.wrapKey(TableValueImpl.java:699)
        at io.ballerina.runtime.internal.values.TableValueImpl$KeyHashValueHolder.addData(TableValueImpl.java:553)
        at io.ballerina.runtime.internal.values.TableValueImpl.addData(TableValueImpl.java:137)
        at io.ballerina.runtime.internal.values.TableValueImpl.<init>(TableValueImpl.java:127)
        at $_init.$gen$$0046$0060init$0062(.:370)
        at $_init.$moduleInit(.)
        at $_init.$lambda$$moduleInit$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
**Steps to reproduce:**

Compile the following.
```
type Employee record {|
   readonly string name;
|};
 

public function main() {
    table <Employee> key() t = table [{name: ""}];
}
```
**Affected Versions:**
2201.0.1 (Swan Lake)

### LINKED ISSUE #35731: Incorrect compilation errors with a table having empty key fields
**Description:**
$title

**Steps to reproduce:**
```ballerina
type Employee record {|
    readonly string name;
|};

public function main() {
    table<Employee> t2 = table [{name: "A"}];
    _ = t2["A"]; // member access is not supported for keyless table 't2'

    table<Employee> key() t = table [{name: "A"}];
    _ = t["A"]; // invalid key constraint provided for member access. key constraint expected with type '[]' 
    // incompatible types: expected '[]', found 'string'
    // But the error should be same as the above.
}

```

Need to fix other applicable places as well.

**Affected Versions:**
SL-GA

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/35310

### PR DESCRIPTION
**Pull request by lasinicl**
## Purpose
$title

Fixes #35310
Fixes #35731

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java [hunk 1]
```diff
@@ -110,7 +110,7 @@ public TableValueImpl(TableType type) {
         this.indexToKeyMap = new LinkedHashMap<>();
         this.fieldNames = type.getFieldNames();
         this.keyValues = new LinkedHashMap<>();
-        if (type.getFieldNames() != null) {
+        if (type.getFieldNames() != null && type.getFieldNames().length != 0) {
```
Comment (gimantha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java:113]: Wouldnt this be much simpler if we get rid of the null check and use an empty list for `fieldNames` and `type.fieldNameList` everywhere? then we don't need to check for both null and emptiness.

Comment (lasinicl) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java]: Updated.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTableTypeSymbol.java [hunk 2]
```diff
@@ -70,16 +70,8 @@ public Optional<TypeSymbol> keyConstraintTypeParameter() {
...
-            List<String> specifiers = ((BTableType) this.getBType()).fieldNameList;
-
-            if (specifiers == null) {
-                specifiers = new ArrayList<>();
-            }
-
-            this.keySpecifiers = Collections.unmodifiableList(specifiers);
-        }
-
+        List<String> specifiers = ((BTableType) this.getBType()).fieldNameList;
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTableTypeSymbol.java:73]: Why should we always do this instead of passing the module level var?

Comment (lasinicl) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTableTypeSymbol.java:73]: It seems we have populated the `keySpecifiers`(module-level var) in this function itself.

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTableTypeSymbol.java:73]: That's fine; my point was it should be populated just once. ie; when `this.keySpecifier` is empty

Comment (lasinicl) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTableTypeSymbol.java:73]: got it! yes, that's correct. will fix.

**Review by pcnfernando — APPROVED** [review]
LGTM

**Review by gimantha — APPROVED** [review]
