### PR TITLE
[Formatter] Fix Review Changes of Test Case Addition for Range formatting

### LINKED ISSUE #27383: Address the comments in PR#26764
**Description:**

PR: https://github.com/ballerina-platform/ballerina-lang/pull/26764

There are some comments that needs to be addressed in the above PR.

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #27383

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/text/TextDocument.java [hunk 1]
```diff
@@ -50,6 +50,10 @@ public int textPositionFrom(LinePosition linePosition) {
         return lines().textPositionFrom(linePosition);
     }
 
+    public LineMap getLines() {
+        return this.lines();
+    }
+
```
Comment (SupunS) [inline compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/text/TextDocument.java:56]: Do we need this method?

File: misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/range-test-config.json [hunk 2]
```diff
@@ -0,0 +1,232 @@
+{
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/range-test-config.json:1]: I feel this structure can be improved. What we need is a 'list' of filenames and their ranges. The best data structure to represent a list is a json array, not a json object. That will make it easier to iterate as well.

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java [hunk 3]
```diff
@@ -113,26 +105,34 @@ public void testParserResources(String sourcePath) throws IOException, Formatter
...
-                    .filter(path -> {
-                        File file = path.toFile();
-                        return file.isFile() && file.getName().endsWith(".bal")
-                                && !skippedTests.contains(file.getName());
-                    })
-                    .map(path -> new Object[]{path.toFile().getName(), this.getTestResourceDir()})
-                    .toArray(size -> new Object[size][2]);
-        } catch (IOException e) {
+            File jsonConfigFile = Paths.get(resourceDirectory.toString(), this.getTestResourceDir(),
+                    this.getConfigJsonFileName()).toFile();
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java:117]: As a practice, we don't really need to use `this` for function calls. It's fine to use it for instance variables, to distinguish them with local variables. But since functions doesn't have such a concept, using `this` for function calls can be an overkill.

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java [hunk 4]
```diff
@@ -38,46 +44,32 @@
...
     private final Path resourceDirectory = Paths.get("src").resolve("test").resolve("resources").toAbsolutePath();
-    private Path buildDirectory = Paths.get("build").toAbsolutePath().normalize();
     private static final String ASSERT_DIR = "assert";
     private static final String SOURCE_DIR = "source";
 
+    private static final Gson gson = new Gson();
+
     @Test(dataProvider = "test-file-provider")
-    public void test(String source, int[][] positions)
+    public void test(String sourcePath, String source, JsonArray positions)
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java:57]: What is the difference between the `source` and the `sourcePath`?

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java [hunk 5]
```diff
@@ -38,46 +44,32 @@
...
-        for (int[] position : positions) {
-            LinePosition startPos = LinePosition.from(position[0], position[1]);
-            LinePosition endPos = LinePosition.from(position[2], position[3]);
-            LineRange lineRange = LineRange.from(null, startPos, endPos);
+        for (JsonElement position : positions) {
+            JsonObject start = position.getAsJsonObject().get("startPos").getAsJsonObject();
+            LinePosition startPos = LinePosition.from(start.get("lineNo").getAsInt(), start.get("colNo").getAsInt());
+            JsonObject end = position.getAsJsonObject().get("endPos").getAsJsonObject();
+            LinePosition endPos = LinePosition.from(end.get("lineNo").getAsInt(), end.get("colNo").getAsInt());
+            LineRange lineRange = LineRange.from(sourceFilePath.toString(), startPos, endPos);
```
Comment (SupunS) [inline misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java:69]: Converting JSON to  `LineRange` is not part of the test case. Can we do this calculation at the data-provider's side?

**Review by SupunS — CHANGES_REQUESTED** [review]

File: compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/text/TextDocument.java (hunk 1 above)
Comment (sanjana) [reply compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/text/TextDocument.java]: Removed this function since it was not necessary in the newly proposed approach.

File: misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/range-test-config.json (hunk 2 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/test/resources/misc/ranges/range-test-config.json]: Implemented as an array within the JSON file.

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java (hunk 3 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java]: Removed all the `this` for function calls.

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java (hunk 4 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java]: The method signature was referred from the currently implemented `FormatterTest` class as following: 

https://github.com/ballerina-platform/ballerina-lang/blob/155a4957fa9ec4415cde7c44ca5c3098788e296a/misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/FormatterTest.java#L56 

- The `source` is the file name. 
  - e.g.: _"checking_action_01.bal"_

- The `sourcePath` is the relative directory where the testcase related files are in (relative to the `resource` directory). 
  - e.g.: "actions/checking"

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java (hunk 5 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java]: Moved to the data-provider's side. Now it's being calculated in the `getConfigsList()` method.

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java (hunk 4 above)
Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java]: In the newly suggested approach, this test function signature was changed to `test(Path sourceFilePath, Path assertFilePath, ArrayList<LineRange> lineRanges)` whereas it has been implemented here.

File: misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java [hunk 6]
```diff
@@ -38,46 +44,25 @@
...
-        Path sourceFilePath = Paths.get(resourceDirectory.toString(), this.getTestResourceDir(), SOURCE_DIR, source);
+    private static final Gson gson = new Gson();
 
-        String content = getSourceText(sourceFilePath);
+    @Test(dataProvider = "test-file-provider")
+    public void test(Path sourceFilePath, Path assertFilePath, ArrayList<LineRange> lineRanges) throws IOException,
+            FormatterException {
+        String content = getFileContent(sourceFilePath);
         TextDocument textDocument = TextDocuments.from(content);
         SyntaxTree syntaxTree = SyntaxTree.from(textDocument, sourceFilePath.toString());
```
Comment (IrushiL) [inline misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java:61]: Is there a reason for using this overloaded `SyntaxTree.from` method?

Comment (sanjana) [reply misc/formatter/modules/formatter-core/src/test/java/org/ballerinalang/formatter/core/RangeFormatterTest.java]: It was used as the previous approach required to access the positions of the syntax tree. 
The revised approach no longer requires the overloaded method call. 
Fixed it.

**Review by IrushiL — APPROVED** [review]

**Review by SupunS — APPROVED** [review]
