### PR TITLE
Fix cloneReadonly behavior for recursive tuple

### LINKED ISSUE #31721: colneReadonly on recursive tuple type doesn't work as expected
**Description:**
$title

**Steps to reproduce:**
```
type A [int, string|xml, A...];

public function main() {
A x = [1, ""];
A y = x.cloneReadOnly();
}
```
results in a type cast error where it should ideally work

> {"message":"incompatible types: '[int,((string|xml<(lang.xml:Element|lang.xml:Comment|lang.xml:ProcessingInstruction|lang.xml:Text)>) & readonly),([int,(string|xml<(lang.xml:Element|lang.xml:Comment|lang.xml:ProcessingInstruction|lang.xml:Text)>),A...] & readonly)...]' cannot be cast to '(ballerina/lang.value:1.0.0:CloneableType & readonly)'"}

### LINKED ISSUE #31722: Is JSON check with recursive tuple results in SO
**Description:**
$title might be related to #31721

**Steps to reproduce:**
```
type A [int, string|xml, A...];

public function main() {
A x = [1, ""];
A y = x.cloneReadOnly();
boolean a =  y is json;
}
```

### PR DESCRIPTION
**Pull request by suleka96**
Fixes #31722
Fixes #31721

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java [hunk 1]
```diff
@@ -317,6 +317,13 @@ public void testFrozenTupleUpdate() {
         BRunUtil.invoke(result, "testFrozenTupleUpdate", new BValue[0]);
     }
 
+    @Test(expectedExceptions = BLangRuntimeException.class,
+            expectedExceptionsMessageRegExp = "error: \\{ballerina/lang.array}InvalidUpdate \\{\"message\":" +
+                    "\"modification not allowed on readonly value\".*")
+    public void testFrozenRecursiveTupleUpdate() {
+        BRunUtil.invoke(result, "testFrozenRecursiveTupleUpdate", new BValue[0]);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java:324]:
```suggestion
        BRunUtil.invoke(result, "testFrozenRecursiveTupleUpdate");
```

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java:324]: Let's write this test in b7a itself. Using trap to capture the error.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java [hunk 2]
```diff
@@ -364,6 +371,11 @@ public void testValidComplexMapFreeze() {
                 "was encountered");
     }
 
+    @Test(description = "test recursive tuple")
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java:374]: IMO, the test name explains what we're testing for and the description doesn't add value here.

**Review by MaryamZi — COMMENTED** [review]
Typo in the title - colneReadonly -> cloneReadonly

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java [hunk 3]
```diff
@@ -317,6 +317,13 @@ public void testFrozenTupleUpdate() {
         BRunUtil.invoke(result, "testFrozenTupleUpdate", new BValue[0]);
     }
 
+    @Test(expectedExceptions = BLangRuntimeException.class,
+            expectedExceptionsMessageRegExp = "error: \\{ballerina/lang.array}InvalidUpdate \\{\"message\":" +
+                    "\"modification not allowed on readonly value\".*")
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/builtinoperations/FreezeAndIsFrozenTest.java:322]: Can't/shouldn't we get rid of this? Can you verify if the test is running? I was under the impression this should fail because we are trapping the panic in testFrozenRecursiveTupleUpdate.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen.bal [hunk 4]
```diff
@@ -361,6 +361,35 @@ function testFrozenTupleUpdate() {
...
+type B [int, boolean, B[]...];
+
+function cloneReadonlyTupleNegative(A tupleTemp1) {
+    tupleTemp1[2] = true;
+}
+
+function testFrozenRecursiveTupleUpdate() {
+    A tupleTest1 = [1, "text"];
+    A tupleTemp1 = tupleTest1.cloneReadOnly();
+    error|() cloneErr = cloneReadonlyTupleNegative(tupleTemp1);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/builtinoperations/freeze-and-isfrozen.bal:374]:
```suggestion
    error? cloneErr = cloneReadonlyTupleNegative(tupleTemp1);
```

**Review by KRVPerera — APPROVED** [review]
