### PR TITLE
Skip adding observe imports to BALA projects in ObservabilityDesugar

### LINKED ISSUE #29142: Error building ballerina/io which was pushed to central
**Description:**
The DEV central currently has 0.6.0 version of ballerina/io pushed using https://drive.google.com/file/d/1U4r9Q1aQ1vlRmC9C2pzhPutBXDuSebn-/view?usp=sharing.

When trying to run a hello world main, a ballerina-internal.log is created with an error.

Screenshot 2021-03-11 at 7 53 58 PM

```
[2021-03-11 19:30:55,647] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:592)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:79)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.lambda$visit$1(BIRGen.java:390)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.visit(BIRGen.java:390)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:265)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:253)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:163)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:388)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:141)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:127)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:103)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:144)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:102)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:247)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Steps to reproduce:**
- Use the above pack to create a hello world main
- Set env var for DEV central. i.e `export BALLERINA_DEV_CENTRAL=true`
- Using the above pack, build the hello world main by invoking `bal build`

**Affected Versions:**
Post Alpha2 pack

**OS, DB, other environment details and versions:**
MAC

### PR DESCRIPTION
**Pull request by azinneera**
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java [hunk 1]
```diff
@@ -324,6 +325,10 @@ void compile(CompilerContext compilerContext) {
     }
 
     void generatePlatformSpecificCode(CompilerContext compilerContext, CompilerBackend compilerBackend) {
+        // adding the source type which will be used to avoid bala projects
+        // when injecting observability imports at desugar phase.
+        CompilerOptions options = CompilerOptions.getInstance(compilerContext);
```
Comment (hevayo) [inline compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java:330]: This might fail in a parallel build right since we update the same context ? alternatively is there a way in observability desugger to determine if it is the current package.

Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java:330]: We don't have any Project API related information in ObservabilityDesugar class. Only the bLangPackge is available. Will check more for an alternative solution.

Comment (azinneera) [reply compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java]: Fixed with dab93c9

**Review by nadundesilva — APPROVED** [review]
Observability related changes for skipping balo projects LGTM

**Review by hasithaa — APPROVED** [review]
Looks Ok, But I think, we can handle this differently. Can you create an issue to clean this up later?

**Comment by azinneera** [comment]
> Looks Ok, But I think, we can handle this differently. Can you create an issue to clean this up later?

Created #29251 to track this.

**Review by hevayo — APPROVED** [review]
