### PR TITLE
Fix the visibility range of local variables in debugger view

### LINKED ISSUE #28064: 'int' variables are initialized to 0 by default in debug variables
**Description:**
int varibales are initialized to 0 in the debug variables view before the varible is actualled assigned with any value, which is misleading to the user.
Screenshot 2021-01-21 at 16 28 41

Screenshot 2021-01-21 at 16 31 32

**Steps to reproduce:**

**Affected Versions:**
SLP9

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #31385: The function returned values and their assigned variables are not visible in the debugger view
**Description:**
The function returned values and its assigned variables are not visible in the debugger view

**Steps to reproduce:**
Consider the below code segment:

```
public function main() {
    int a = getNumber(); // Add a debug point here
    int b = getNumber();
    int c = getNumber();
    int d = getNumber();
}

function getNumber() returns int {
    return 123;
}
```
- Add a debug point in the first line of `main()` function as shown above and start the program in debug mode.
- Once the debug point gets hit, `STEP_OVER` to the next few lines. We can observe that the function returned values and its assigned variables are not visible in the debug view.
Screen Shot 2021-06-23 at 11 07 02 AM

- In the above example, all variables will get visible once we go to the last line of the main method.
Screen Shot 2021-06-23 at 11 07 37 AM

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #28064
Fixes #31385

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java [hunk 1]
```diff
@@ -469,19 +470,23 @@ void generateBasicBlocks(MethodVisitor mv, LabelGenerator labelGen, JvmErrorGen
...
             BIRTerminator terminator = bb.terminator;
             pushShort(mv, stateVarIndex, caseIndex);
             caseIndex += 1;
 
             processTerminator(mv, func, module, funcName, terminator, jvmTypeGen, localVarOffset);
+
             termGen.genTerminator(terminator, moduleClassName, func, funcName, localVarOffset,
                                   returnVarRefIndex, attachedType);
 
+            lastScope = getLastScopeFromProcessTerminator(mv, bb, funcName, labelGen, lastScope, visitedScopesSet);
```
Comment (riyafa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:483]: Maybe we might have to do the same thing in the InteropMethodGen as well? Can you write an interop function for the same usecase and verify and do the same thing there as well? Probably add this code to `JvmCodeGenUtil` and call in both places

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java [hunk 2]
```diff
@@ -927,6 +944,9 @@ private void createLocalVariableTable(BIRFunction func, BIRVarToJVMIndexMap inde
             mv.visitLocalVariable("self", String.format("L%s;", B_OBJECT), null, methodStartLabel, methodEndLabel, 0);
         }
         BIRBasicBlock endBB = func.basicBlocks.get(func.basicBlocks.size() - 1);
+        if (endBB.terminator.thenBB != null) {
+            endBB = endBB.terminator.thenBB;
+        }
```
Comment (riyafa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:949]: just for my understanding, why is this change required?

File: docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java [hunk 3]
```diff
@@ -155,7 +154,7 @@ private static void assertFunctions(BIRNode.BIRPackage expectedBIR, Bir.Module b
             assertBasicBlocks(actualFunctionBody.functionBasicBlocksInfo(), expectedFunction.basicBlocks,
                     constantPoolEntries);
 
-            assertScopes(actualFunction.scopeEntries(), expectedFunction);
+//            assertScopes(actualFunction.scopeEntries(), expectedFunction);
```
Comment (riyafa) [inline docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java:157]: Why is this commented?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java (hunk 1 above)
Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java]: Yes, addressed with https://github.com/ballerina-platform/ballerina-lang/pull/31829/commits/2ce332c239451f46555c9590b3bf4311baf2a1cf

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java (hunk 2 above)
Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java]: Sorry, forgot to remove before send the PR. Removed

File: docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java (hunk 3 above)
Comment (gabilang) [reply docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java]: Added cases for terminators as well. Enabled this test.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java [hunk 4]
```diff
@@ -698,6 +698,7 @@ public void visit(BLangFunction astFunc) {
         BIRBasicBlock enclBB = this.env.enclBB;
         if (enclBB.instructions.size() == 0 && enclBB.terminator == null && this.env.returnBB != null) {
             enclBB.terminator = new BIRTerminator.GOTO(null, this.env.returnBB);
+            setScope(enclBB.terminator);
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java:701]: Shall we move the setScope inside constructor. We need to pass the current scope. Then we do not need to duplicate the code.

Comment (warunalakshitha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java:701]: We need to do for all terminators which can have scope..

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java [hunk 5]
```diff
@@ -477,9 +478,13 @@ void generateBasicBlocks(MethodVisitor mv, LabelGenerator labelGen, JvmErrorGen
             caseIndex += 1;
 
             processTerminator(mv, func, module, funcName, terminator, jvmTypeGen, localVarOffset);
+
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MethodGen.java:481]: Lets remove unnecessary empty line.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java [hunk 6]
```diff
@@ -88,13 +87,19 @@ void writeBBs(List<BIRBasicBlock> bbList) {
...
+    void writeScopes(BIRNonTerminator instruction) {
         this.instructionOffset++;
         BirScope currentScope = instruction.scope;
 
         writeScope(currentScope);
     }
 
+    void writeScopes(BIRTerminator terminator) {
+        BirScope currentScope = terminator.scope;
+
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java:99]: Addtional empty line

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java [hunk 7]
```diff
@@ -138,6 +143,9 @@ public void visit(BIRBasicBlock birBasicBlock) {
 
         // write pos and kind
         writePosition(terminator.pos);
+        if (terminator.kind != InstructionKind.RETURN) {
+            writeScopes(terminator);
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java:147]: Should be writeScope?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java [hunk 8]
```diff
@@ -88,13 +87,19 @@ void writeBBs(List<BIRBasicBlock> bbList) {
...
 
-    void writeScopes(BIRAbstractInstruction instruction) {
+    void writeScopes(BIRNonTerminator instruction) {
         this.instructionOffset++;
         BirScope currentScope = instruction.scope;
 
         writeScope(currentScope);
     }
 
+    void writeScopes(BIRTerminator terminator) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java:97]: writeScopes

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java (hunk 7 above)
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java:147]: Can we move if condition inside writeScopes method?

File: docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java [hunk 9]
```diff
@@ -194,14 +196,30 @@ private static int generateExpectedScopeEntries(List<BIRNode.BIRBasicBlock> bbLi
...
                         instructionOffset,  hasParent ? 1 : 0, hasParent ? instructionScope.parent.id : null);
                 scopes.put(instructionScope.id, expectedScopeEntry);
                 putParentScopesAsWell(scopes, instructionScope.parent, instructionOffset);
 
             }
+            BIRTerminator terminator = bb.terminator;
+            BirScope terminatorScope = terminator.scope;
+
+            if (terminatorScope != null) {
+
```
Comment (warunalakshitha) [inline docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java:211]: Shall we remove unnecessary empty lines.

File: docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java [hunk 10]
```diff
@@ -194,14 +196,30 @@ private static int generateExpectedScopeEntries(List<BIRNode.BIRBasicBlock> bbLi
...
+                if (visitedScopes.contains(terminatorScope)) {
+                    continue;
+                }
+
+                visitedScopes.add(terminatorScope);
```
Comment (warunalakshitha) [inline docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java:216]: Why we need this change?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java (hunk 8 above)
Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java]: Yeah, that would be right since every basic block has only one terminator.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java (hunk 7 above)
Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/writer/BIRInstructionWriter.java]: Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/31829/commits/111094729f69d3296a3c694581dabfdebc283d93

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java (hunk 4 above)
Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java]: Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/31829/commits/111094729f69d3296a3c694581dabfdebc283d93

File: docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java (hunk 10 above)
Comment (gabilang) [reply docs/bir-spec/src/test/java/org/ballerinalang/birspec/BIRTestUtils.java:214]: Previous BirSpec test only considered scopes of non-terminator instructions and scopes for terminators also generated with this change. In order to incorporate the new changes with the existing test, these changes are needed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java [hunk 11]
```diff
@@ -583,7 +583,7 @@ private void rewriteObservableFunctionInvocations(BIRFunction func, BIRPackage p
                         objectTypeOperand = generateGlobalConstantOperand(pkg, symbolTable.nilType, null);
                         action = callIns.name.value;
                     }
-                    currentBB.terminator = new GOTO(desugaredInsPosition, observeStartBB);
+                    currentBB.terminator = new GOTO(desugaredInsPosition, observeStartBB, null);
```
Comment (riyafa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:586]: Shall we have multiple constructors for these classes to avoid passing null?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java [hunk 12]
```diff
@@ -1429,7 +1433,7 @@ private void createCall(BLangInvocation invocationExpr, boolean isVirtual) {
         // TODO: make vCall a new instruction to avoid package id in vCall
         if (invocationExpr.functionPointerInvocation) {
             this.env.enclBB.terminator = new BIRTerminator.FPCall(invocationExpr.pos, InstructionKind.FP_CALL,
-                    fp, args, lhsOp, invocationExpr.async, transactional, thenBB);
+                    fp, args, lhsOp, invocationExpr.async, transactional, thenBB, this.currentScope);
```
Comment (riyafa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java:1436]: If function call return values are assigned to a variable, would it be needed to increment the `currentScope`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java (hunk 11 above)
Comment (riyafa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:586]: Shall we fix in all places?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java (hunk 12 above)
Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java:1436]: We need to create new scopes for the local variables and increment the scope ids by 1. It has been done in https://github.com/ballerina-platform/ballerina-lang/blob/d4eb62a39664bbee06b2a624751bd453d3a5c9c2/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java#L1163 and the current scopes are needed to be set for relevant instructions. So no need for the increment everywhere.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java (hunk 11 above)
Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:586]: If we want to do so we need to consider other already existing parameters also. For example we are passing null for the position here https://github.com/ballerina-platform/ballerina-lang/blob/d4eb62a39664bbee06b2a624751bd453d3a5c9c2/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BIRGen.java#L700 So we might end up with several constructors with different combinations. IMO, it is good to keep them as it instead of having multiple constructors. WDYT?

Comment (riyafa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmObservabilityGen.java:586]: Normally we try to reduce technical debt in the new code that we write irrespective of the code already there. If we can improve the old code that is fine, but in the new code it is good to follow the best practices.

**Review by riyafa — APPROVED** [review]
LGTM
