### PR TITLE
Add possible fix for memory leak in CodeAnalyzer and IsolationAnalyzer

### LINKED ISSUE #32289: Several memory leaks due to `BType` and `BSymbol` being used in sets/maps
**Description:**
While debugging to identify root cause for #32020, we noticed an out of memory issue. Corresponding heap dumps (2 dumps for 2 occasions) point to `CodeAnalyzer` and `IsolationAnalyzer`. I have attached a heap dump (for the `CodeAnalyzer` scenario). 

In both cases, each class uses either , 
1. A `Set` with elements of type `BSymbol`/`BType`
2. A `Map` with `BType`/`BSymbol` as key

Since both `BType` and `BSymbol` do not implement `hashCode()` and when a Ballerina project is sufficiently large, entries are retained in memory without being GCed.

**Heap Dump**
https://drive.google.com/file/d/1DTho2ewn8UJhyGjG99wJxjzOjmQM8xzK/view?usp=sharing

CodeAnalyzer-2

**Steps to reproduce:**
We reproduced this OOM scenario in `nballerina` project following the steps mentioned in [this comment](https://github.com/ballerina-platform/ballerina-lang/issues/32020#issuecomment-903504701).

**Affected Versions:**
SL Beta 3 Snapshot

### PR DESCRIPTION
**Pull request by gimantha**
Fixes #32289

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by IMS94** [comment]
Merged this locally and did some tests. This was the memory usage:
Screenshot from 2021-08-24 13-10-18

When the heap dump was analyzed, the cause for memory growth seems to be #32290. 

Screenshot from 2021-08-24 13-25-44

Screenshot from 2021-08-24 13-25-56


Memory leak from `CodeAnalyzer`/`IsolationAnalyzer` is not there.

**Review by hasithaa — APPROVED** [review]

**Review by IMS94 — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java [hunk 1]
```diff
@@ -319,6 +319,8 @@ private void analyzeNode(BLangNode node, SymbolEnv env) {
     }
 
     public BLangPackage analyze(BLangPackage pkgNode) {
+        this.arrowFunctionTempSymbolMap.clear();
+        this.isolationInferenceInfoMap.clear();
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java:323]: These are [already cleared](https://github.com/ballerina-platform/ballerina-lang/blob/274e1dca660da80cc2854bbba37cec60a9b51acb/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java#L3527) at the end of this method though, via [`inferIsolation`](https://github.com/ballerina-platform/ballerina-lang/blob/274e1dca660da80cc2854bbba37cec60a9b51acb/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java#L332).

Comment (hasithaa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java:323]: These are getting accumulate somehow when running in the LangServer mode. Need to check why.
