### PR TITLE
Fix few parser issues related match pattern parsing

### LINKED ISSUE #35010: `int:MAX_VALUE` and `int:MIN_VALUE` cannot be used as match patterns
**Description:**
$title.
```ballerina
function test(int x) returns int {
    match x {
        int:MAX_VALUE => {
            return 2;
        }
    }
}
```
output:
```
ERROR [test2.bal:(3:9,3:12)] invalid token 'int'
ERROR [test2.bal:(3:12,3:12)] missing identifier
ERROR [test2.bal:(3:12,3:22)] undefined module '$missingNode$_0'
ERROR [test2.bal:(3:12,3:22)] variable 'MAX_VALUE' should be declared as constant
```
`int:MIN_VALUE` also behaves in similar way.

**Affected Versions:**
SL 2201.0.0

### LINKED ISSUE #35131: No syntax errors are shown
**Description:**
Consider the following source snippet where there is a syntax error at the cursor. 

```
public type MyRecord record {
      int field1;
      int field2;
};

const temp = 1;
public function main() {
    MyRecord r1= {field1: 0, field2: 0};

//     int myInt = 1;

    match r1 {
          {field1:0, <cursor>} => {
                
          }
    }
}
```

This should show a syntax error due to the extra `comma` added. 

**Affected Versions:**
`2201.0.1-SNAPSHOT` at least

### LINKED ISSUE #35265: Qualified reference not allowed parsing in `error-match-pattern`
**Description:**
$subject.

```bal
function errorMatch(error e) {
    match  e {
        error (myError:MSG_1) => { // Cannot parse
            io:println("msg_1");
        }
        _ => {
            io:println("defualt");
        }
    }
}
```

**Affected Versions:**
2201.0.0

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #35131
Fixes #35010
Fixes #35265

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -14482,55 +14484,88 @@ private STNode parseListMatchPatternMemberRhs() {
...
+        STNode closeBraceToken = parseCloseBrace();
+        endContext();
+        return STNodeFactory.createMappingMatchPatternNode(openBraceToken, fieldMatchPatterns, closeBraceToken);
+    }
+
+    private STNode parseFieldMatchPatternList() {
+        List<STNode> fieldMatchPatterns = new ArrayList<>();
+        if (isEndOfMappingMatchPattern()) {
+            return STNodeFactory.createEmptyNodeList();
+        }
```
Comment (rdulmina) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:14497]: We don't need this right? `parseFieldMatchPatternMember()` will return `null` if  peek is `CLOSE_BRACE_TOKEN`. We can also add `EOF_TOKEN` to `parseFieldMatchPatternMember` as well

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternNegativeTest.java [hunk 2]
```diff
@@ -117,6 +117,26 @@ public void testMappingMatchPatternTypeNegative() {
...
     }
 
+    @Test
+    public void testMappingMatchPatternNegativeSyntax() {
+        CompileResult negativeResult =
+                BCompileUtil.compile("test-src/statements/matchstmt/mapping_match_pattern_syntax_negative.bal");
+        int i = 0;
+        BAssertUtil.validateError(negativeResult, i++,  "missing field match pattern member", 18, 17);
+        BAssertUtil.validateError(negativeResult, i++,
+                "variable '$missingNode$_1' should be declared as constant", 18, 17);
```
Comment (rdulmina) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternNegativeTest.java:127]: Tho this is a known issue, can't we just not log that error since it is not needed?

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal [hunk 3]
```diff
@@ -627,6 +627,56 @@ function testConstPatternWithNegativeLiteral() {
     assertEquals("other", constPatternWithNegativeLiteral(-123.4));
 }
 
+function testConstPatternWithPredeclaredPrefix() {
+    assertEquals(0,constPatternWithPredeclaredPrefix1(int:MAX_VALUE));
```
Comment (rdulmina) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/const-pattern.bal:631]:
```suggestion
    assertEquals(0, constPatternWithPredeclaredPrefix1(int:MAX_VALUE));
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternNegativeTest.java (hunk 2 above)
Comment (lochana-chathura) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternNegativeTest.java:127]: How can we not log the error? Special casing here and there is not a good idea.

Comment (rdulmina) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternNegativeTest.java:127]: I mean in general

**Review by rdulmina — APPROVED** [review]
LGTM

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternNegativeTest.java (hunk 2 above)
Comment (rdulmina) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStmtMappingMatchPatternNegativeTest.java:127]: Approved since this is not related to this PR

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/error-match-project/main.bal [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+        error(module1:ERROR_MESSAGE_2) => {
+            return 2;
+        }
+        error(module1:ERROR_MESSAGE_3) => {
+            return 3;
+        }
+        error(module1:ERROR_MESSAGE_4, error(module1:ERROR_MESSAGE_3)) => {
+            return 4;
+        }
+    }
```
Comment (lasinicl) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/matchstmt/error-match-project/main.bal:47]: Shall we test this in the detail field of an error binding too?

**Review by lasinicl — DISMISSED** [review]

**Comment by lochana-chathura** [comment]
Need to decide the branch.

**Review by rdulmina — APPROVED** [review]

**Review by rdulmina — APPROVED** [review]
