### PR TITLE
Separate filtering for testerina coverage and codecov coverage

### LINKED ISSUE #28951: [Testerina] Doesn't show coverage when tests and source are in different ballerina projects
**Description:**
Doesn't show coverage when tests and source are in different ballerina projects

**Steps to reproduce:**
Create 2 separate projects, one with the source files(project 1) and the other project contains the tests(project 2).
Generate coverage for project2 and it doesn't show the correct coverage.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Dilhasha**
Fixes #28951

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java [hunk 1]
```diff
@@ -322,6 +334,22 @@ private Document getDocumentFromModule(Module moduleInstance, String sourceFileN
         return exclusionPathList;
     }
 
+    private List<Path> getDependencyJarList(JBallerinaBackend jBallerinaBackend) {
```
Comment (hevayo) [inline misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java:337]: Check getJarFilePathsRequiredForExecution in JarResolver I guess you can get the dependencies list directly from that

Comment (Dilhasha) [reply misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/CoverageReport.java:322]: We still need to remove the runtime libraries and test dependencies to avoid errors as discussed.

**Review by azinneera — APPROVED** [review]
