### PR TITLE
Fix an issue in top level variable definition

### LINKED ISSUE #10865: Issue in top level variable definition
**Description:**
```ballerina
int A = 10;
A a = 2;
```

The above code snippet works without giving an error. If the same code snippet is in a function, this will give an error.

### LINKED ISSUE #20864: "JVM generation is not supported for type none" for invalid global types
**Description:**
It looks like the below code fails to compile but prints a stack trace rather than an actual compiler error.

#### Code
```Ballerina
var myVar = 1 | 2 | 3 | 4 ;
myVar x = 7;
```

#### Output
```
error: JVM generation is not supported for type none
	at ballerina.compiler_backend_jvm:generateField(jvm_method_gen.bal:2173)
	   ballerina.compiler_backend_jvm:generatePackageVariable(jvm_package_gen.bal:247)
	   ballerina.compiler_backend_jvm:generatePackage(jvm_package_gen.bal:186)
	   ballerina.compiler_backend_jvm:generateJarBinary(main.bal:86)
	   ballerina.compiler_backend_jvm:main(main.bal:60)
error: error: JVM generation is not supported for type none
	at ballerina.compiler_backend_jvm:generateField(jvm_method_gen.bal:2173)
	   ballerina.compiler_backend_jvm:generatePackageVariable(jvm_package_gen.bal:247)
	   ballerina.compiler_backend_jvm:generatePackage(jvm_package_gen.bal:186)
	   ballerina.compiler_backend_jvm:generateJarBinary(main.bal:86)
	   ballerina.compiler_backend_jvm:main(main.bal:60)
```
**Steps to reproduce:**
Run above code in Ballerina

**Affected Versions:**
jBallerina 1.1.1
Language specification 2019R3
Ballerina tool 0.8.0

**OS, DB, other environment details and versions:**
MacOs

**Related Issues (optional):**
Looks similar to #10865 but this does not compile

**Suggested Labels (optional):**
Area/Language Type/Bug Component/Compiler

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose
$subject.

Fixes #10865
Fixes #20864

## Approach
Change SymTags in order to fix the issue.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 1]
```diff
@@ -202,7 +202,7 @@ private boolean isDistinctSymbol(DiagnosticPos pos, BSymbol symbol, BSymbol foun
         }
 
         // Type names should be unique and cannot be shadowed
-        if ((foundSym.tag & SymTag.TYPE) == SymTag.TYPE) {
+        if ((foundSym.tag & SymTag.TYPE) == SymTag.TYPE && !((foundSym.tag & SymTag.CONSTANT) == SymTag.CONSTANT)) {
```
Comment (dulvinw) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: I feel like if we move the complex logic to a function it would enhance readability. WDYT?

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/var-negative.bal [hunk 2]
```diff
@@ -73,3 +73,8 @@ function test10 () {
     var x = <Foo> bar;
     string result1 = x + ex;
 }
+
+function test11 () {
```
Comment (Shan1024) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/var-negative.bal]: Shall we add more test cases? Eg- https://github.com/ballerina-platform/ballerina-lang/issues/10865#issuecomment-440537102

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 1 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: It is not used anymore.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/var-negative.bal (hunk 2 above)
Comment (KavinduZoysa) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/var-negative.bal]: Added more test cases.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 3]
```diff
@@ -135,15 +135,31 @@ public SymbolResolver(CompilerContext context) {
         this.types = Types.getInstance(context);
     }
 
-    public boolean checkForUniqueSymbol(DiagnosticPos pos, SymbolEnv env, BSymbol symbol, int expSymTag) {
+    // TODO : Remove the 'expSymTag'
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: is this todo still relevant? `expSymTag` seems to be removed

Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: Yes, it is removed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 4]
```diff
@@ -1579,8 +1579,7 @@ private boolean workerExists(BType type, String workerName) {
 
     // Asynchronous Send Statement
     public void visit(BLangWorkerSend workerSendNode) {
-        BSymbol receiver = symResolver.lookupSymbol(env,
-                names.fromIdNode(workerSendNode.workerIdentifier), SymTag.VARIABLE);
+        BSymbol receiver = symResolver.lookupMainSpaceSymbol(env, names.fromIdNode(workerSendNode.workerIdentifier));
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Shouldn't we verify the resolved symbol is a variable here? I think we should.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java [hunk 5]
```diff
@@ -301,7 +301,7 @@ private void handleServiceTypeProcesses(CompilerPlugin plugin) {
             BPackageSymbol symbol = this.packageCache.getSymbol(packageQName);
             if (symbol != null) {
                 SymbolEnv pkgEnv = symTable.pkgEnvMap.get(symbol);
-                final BSymbol listenerSymbol = symResolver.lookupSymbol(pkgEnv, listenerName, SymTag.OBJECT);
+                final BSymbol listenerSymbol = symResolver.lookupMainSpaceSymbol(pkgEnv, listenerName);
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java]: Need to check for Object symbol after this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 4 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Changed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java (hunk 5 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java]: Changed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 6]
```diff
@@ -576,7 +576,7 @@ public void visit(BLangInvocation invocationExpr) {
 
             // Todo: test lambdas and function arguments
 
-            BSymbol dependsOnFunctionSym = symResolver.lookupSymbol(this.env, name, SymTag.FUNCTION);
+            BSymbol dependsOnFunctionSym = symResolver.lookupMainSpaceSymbol(this.env, name);
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: We need to add SymTag validation here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 7]
```diff
@@ -1644,8 +1647,7 @@ private BType createAccumulatedErrorTypeForMatchingRecive(DiagnosticPos pos, BTy
 
     @Override
     public void visit(BLangWorkerSyncSendExpr syncSendExpr) {
-        BSymbol receiver = symResolver.lookupSymbol(env,
-                names.fromIdNode(syncSendExpr.workerIdentifier), SymTag.VARIABLE);
+        BSymbol receiver = symResolver.lookupMainSpaceSymbol(env, names.fromIdNode(syncSendExpr.workerIdentifier));
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: We need to add SymTag validation here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 8]
```diff
@@ -1672,8 +1674,7 @@ public void visit(BLangWorkerSyncSendExpr syncSendExpr) {
     public void visit(BLangWorkerReceive workerReceiveNode) {
         // Validate worker receive
         validateActionParentNode(workerReceiveNode.pos, workerReceiveNode);
-        BSymbol sender = symResolver.lookupSymbol(env,
-                names.fromIdNode(workerReceiveNode.workerIdentifier), SymTag.VARIABLE);
+        BSymbol sender = symResolver.lookupMainSpaceSymbol(env, names.fromIdNode(workerReceiveNode.workerIdentifier));
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: We need to add SymTag validation here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java [hunk 9]
```diff
@@ -323,11 +323,17 @@ private BSymbol resolveFullyQualifiedSymbol(DiagnosticPos pos, SymbolEnv env, St
 
         // If there is no type in the reference we need to search in the package level and the current scope only.
         if (typeName == Names.EMPTY) {
-            return symResolver.lookupSymbolInPackage(pos, env, pkgName, identifierName, tag);
+            if ((tag & SymTag.IMPORT) == SymTag.IMPORT) {
+                return symResolver.lookupPrefixSpaceSymbolInPackage(pos, env, pkgName, identifierName);
+            } else if ((tag & SymTag.ANNOTATION) == SymTag.ANNOTATION) {
+                return symResolver.lookupAnnotationSpaceSymbolInPackage(pos, env, pkgName, identifierName);
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java]: I think this validation is not needed. `type` defined only in the main symbol space.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 10]
```diff
@@ -1419,8 +1419,8 @@ private boolean validateErrorReasonMatchPatternSyntax(BLangErrorVariable errorVa
                 && errorVariable.reasonMatchConst == null
                 && isReasonSpecified(errorVariable)) {
 
-            BSymbol reasonConst = symResolver.lookupSymbol(
-                    this.env.enclEnv, names.fromString(errorVariable.reason.name.value), SymTag.CONSTANT);
+            BSymbol reasonConst = symResolver.lookupMainSpaceSymbol(this.env.enclEnv,
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: Need to validate SymTag.CONSTANT

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java (hunk 6 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java]: Same comment as above. For phases after semantic analyzer, we don't need to validate the sym tag since it would already have been caught if the sym tag was invalid.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 11]
```diff
@@ -546,6 +537,22 @@ public BSymbol lookupSymbol(SymbolEnv env, Name name, int expSymTag) {
         return symTable.notFoundSymbol;
     }
 
+    public BSymbol lookupMainSpaceSymbol(SymbolEnv env, Name name) {
```
[the remark this answers is not in the document]
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: Or `lookupInMainSymbolSpace`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 7 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Tested the above example with this change, and it throws above error

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java (hunk 9 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java]: But according to [this](https://github.com/ballerina-platform/ballerina-lang/blob/f5db13f2fbec192b2906644ff517d4abc0e5bb3f/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DocumentationAnalyzer.java#L256), SymTag can be ANNOTATION, or IMPORT. Therefore don't we need to validate the symbol.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 10 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: Done

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 12]
```diff
@@ -1579,8 +1579,11 @@ private boolean workerExists(BType type, String workerName) {
 
     // Asynchronous Send Statement
     public void visit(BLangWorkerSend workerSendNode) {
-        BSymbol receiver = symResolver.lookupSymbol(env,
-                names.fromIdNode(workerSendNode.workerIdentifier), SymTag.VARIABLE);
+        BSymbol receiver = symTable.notFoundSymbol;
+        BSymbol tempSymbol = symResolver.lookupMainSpaceSymbol(env, names.fromIdNode(workerSendNode.workerIdentifier));
+        if ((tempSymbol.tag & SymTag.VARIABLE) == SymTag.VARIABLE) {
+            receiver = tempSymbol;
+        }
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Done

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java [hunk 13]
```diff
@@ -301,8 +301,10 @@ private void handleServiceTypeProcesses(CompilerPlugin plugin) {
             BPackageSymbol symbol = this.packageCache.getSymbol(packageQName);
             if (symbol != null) {
                 SymbolEnv pkgEnv = symTable.pkgEnvMap.get(symbol);
-                final BSymbol listenerSymbol = symResolver.lookupSymbol(pkgEnv, listenerName, SymTag.OBJECT);
-                if (listenerSymbol != symTable.notFoundSymbol) {
+                BSymbol listenerSymbol;
+                BSymbol tempListenerSymbol = symResolver.lookupMainSpaceSymbol(pkgEnv, listenerName);
+                if ((tempListenerSymbol.tag & SymTag.OBJECT) == SymTag.OBJECT) {
+                    listenerSymbol = tempListenerSymbol;
```
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CompilerPluginRunner.java]: Done

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: Done

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java (hunk 8 above)
Comment (KavinduZoysa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java]: Done
