### PR TITLE
Replace CodeActionContextTypeResolver with expectedType API

### LINKED ISSUE #39108: [Bug]: Missing fill required fields code action in select clause
### Description

Consider the following scenario where Fill required fields code action is not suggested,

Screenshot 2022-12-19 at 12 23 33

### Steps to Reproduce

```
type Result record {|
    string name;
    string college;
    int grade;
|};

type Person record {|
    string name;
    int age;
|};

function filterResults(Person[] persons, map<int> grades) returns Result[] {
    Result[] results = from var person in persons
                        let int lgrade = (grades[person.name] ?: 0), string targetCollege = "Stanford"
                        where lgrade > 75
                        select {<cursor>};
    return results;
}
```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #39225: [Bug]: Missing Fill required fields code action in object fields
### Description

Consider the following scenario,
Screenshot 2023-01-11 at 10 07 04

Here, we get the `Fill required fields` completion item but not the code action. 

### Steps to Reproduce

```
type Employee record {|
    readonly int empId;
    string name;
|}; 

class TestClass {
    table<Employee> key(empId) employees = table [{}];
}
```

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

#37625

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
This PR replaces the usages of codeActionContextTypeResolver with the new expectedType API.

Fixes #39108 
Fixes #39225

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by IMS94 — DISMISSED** [review]
LGTM!

**Review by IMS94 — DISMISSED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/FillRecordFieldsCodeAction.java [hunk 1]
```diff
@@ -90,8 +89,12 @@ public List<CodeAction> getCodeActions(CodeActionContext context,
         if (expressionNode.isEmpty()) {
             return Collections.emptyList();
         }
-        CodeActionContextTypeResolver contextTypeResolver = new CodeActionContextTypeResolver(context);
-        Optional<TypeSymbol> typeSymbol = expressionNode.get().apply(contextTypeResolver);
+
+        Optional<TypeSymbol> typeSymbol = Optional.empty();
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/FillRecordFieldsCodeAction.java:93]: you don't have to initialize the typeSymbol to Optional.empty. Alternatively, we can move the logic inside the if condition 94 to the initializer,  by doing an early return if `context.currentSemanticModel().isEmpty()  || context.currentDocument().isEmpty()`.

**Review by malinthar — CHANGES_REQUESTED** [review]

**Review by IMS94 — APPROVED** [review]

**Review by malinthar — APPROVED** [review]
LGTM!
