### PR TITLE
Fix create object value getting null strand passing

### LINKED ISSUE #21018: Cannot create objects with async calls in the initialiser, for array filling
**Description:**
 Looks like array default object initializer with async calls are not handled by the runtime object creation properly. This happens if we create a worker inside the object's initializer as well. 

#### Code
```Ballerina
import ballerina/io;

type Student object {
    public string name;
    public function __init() {
        future<int> accumulator = start sum(2, 4); // line 6
        self.name = "unknown";
    }

    public function toString() returns string {
        return self.name;
    }
};

function sum(int a, int b) returns int {
    return a + b;
}

public function main() {

    Student s = new();
    io:println(s);
    Student[] arr = [];
    arr[0] = s; // NO crash here
    arr[2] = s; // crash here

    io:println("arr : ", arr);
}

```

#### Output
```
unknown
ballerina: Oh no, something really went wrong.
```
$ cat ballerina-internal.log
```Nim
[2020-02-12 13:45:10,002] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
	at $value$Student.__init(ObjectWithDirtyCtor.bal:6)
	at $value$Student.call(ObjectWithDirtyCtor.bal)
	at $value$Student.$__init$(ObjectWithDirtyCtor.bal:4)
	at $value$Student.call(ObjectWithDirtyCtor.bal)
	at ___init.createObjectValue(.)
	at org.ballerinalang.jvm.BallerinaValues.createObjectValue(BallerinaValues.java:88)
	at org.ballerinalang.jvm.types.BObjectType.getZeroValue(BObjectType.java:49)
	at org.ballerinalang.jvm.values.ArrayValueImpl.fillValues(ArrayValueImpl.java:709)
	at org.ballerinalang.jvm.values.ArrayValueImpl.prepareForAdd(ArrayValueImpl.java:825)
	at org.ballerinalang.jvm.values.ArrayValueImpl.add(ArrayValueImpl.java:315)
	at ObjectWithDirtyCtor.main(ObjectWithDirtyCtor.bal:25)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:748)

[2020-02-12 13:45:10,005] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
	at $value$Student.__init(ObjectWithDirtyCtor.bal:6)
	at $value$Student.call(ObjectWithDirtyCtor.bal)
	at $value$Student.$__init$(ObjectWithDirtyCtor.bal:4)
	at $value$Student.call(ObjectWithDirtyCtor.bal)
	at ___init.createObjectValue(.)
	at org.ballerinalang.jvm.BallerinaValues.createObjectValue(BallerinaValues.java:88)
	at org.ballerinalang.jvm.types.BObjectType.getZeroValue(BObjectType.java:49)
	at org.ballerinalang.jvm.values.ArrayValueImpl.fillValues(ArrayValueImpl.java:709)
	at org.ballerinalang.jvm.values.ArrayValueImpl.prepareForAdd(ArrayValueImpl.java:825)
	at org.ballerinalang.jvm.values.ArrayValueImpl.add(ArrayValueImpl.java:315)
	at ObjectWithDirtyCtor.main(ObjectWithDirtyCtor.bal:25)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
	at java.lang.Thread.run(Thread.java:748)
```

**Affected Versions:**
jBallerina 1.1.1
Language specification 2019R3
Ballerina tool 0.8.0

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**
#20983 
#20721 

**Suggested Labels (optional):**
Area/Language
Type/Bug
Component/JVMCodeGen

### PR DESCRIPTION
**Pull request by HindujaB**
Fixes #21018 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java [hunk 1]
```diff
@@ -468,19 +472,33 @@ private static void generateObjectValueCreateMethod(ClassWriter cw, @Nilable Lis
...
             mv.visitVarInsn(ALOAD, propertiesIndex);
             mv.visitMethodInsn(INVOKESPECIAL, STRAND, "<init>",
                     String.format("(L%s;L%s;L%s;)V", SCHEDULER, STRAND, MAP), false);
-            BIRVariableDcl strandVar = new BIRVariableDcl(symbolTable.anyType, new Name("strandVar"), VarScope.FUNCTION,
-                    VarKind.LOCAL);
-
-            int strandVarIndex = indexMap.getIndex(strandVar);
             mv.visitVarInsn(ASTORE, strandVarIndex);
+            Label conditionLinkLabel = new Label();
+            mv.visitLabel(conditionLinkLabel);
```
Comment (manuranga) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmTypeGen.java:493]: don't think `conditionLinkLabel` is used, we can remove it.

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java [hunk 2]
```diff
@@ -85,8 +87,41 @@ public static ObjectValue createObjectValue(BPackage packageId, String objectTyp
             fields[j++] = fieldValues[i];
             fields[j++] = true;
         }
-        //passing scheduler, strand and properties as null for the moment, but better to expose them via this method
-        return valueCreator.createObjectValue(objectTypeName, null, null, null, fields);
+        return valueCreator.createObjectValue(objectTypeName, getScheduler(), getStrand(), null, fields);
```
Comment (manuranga) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java:90]: please remove `getScheduler` method, since `Scheduler.getStrand()` is costly (because it access a thread local) it should be called ones. assign the strand to a local var and access the scheduler form there.

Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java]: I modified considering all suggestions in [this](https://github.com/ballerina-platform/ballerina-lang/pull/22913/commits/515f7fe10aadde5656b821ccb180e31abba89504)

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java [hunk 3]
```diff
@@ -79,14 +81,46 @@
...
+        //passing scheduler of current strand
+        return valueCreator.createObjectValue(objectTypeName, currentStrand.scheduler, currentStrand,
+                null, fields);
+    }
+
+    private static Scheduler getScheduler(Strand currentStrand) {
+        try {
+            return currentStrand.scheduler;
+        } catch (Exception ex) {
+            return null;
```
Comment (Kishanthan) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java:113]: when can an exception occur here?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java [hunk 4]
```diff
@@ -79,14 +81,46 @@
...
+        }
+    }
+
+    private static Strand getStrand() {
+        try {
+            return Scheduler.getStrand();
+        } catch (Exception ex) {
+            //ignore : isssue is opened to fix this
```
Comment (Kishanthan) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java:121]: can we link the created issue here ?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java (hunk 3 above)
Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java:113]: Null pointer exception is thrown if the strand is null.

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java (hunk 4 above)
Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java]: Added issue reference in the latest commit

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java [hunk 5]
```diff
@@ -79,14 +81,45 @@
     public static ObjectValue createObjectValue(BPackage packageId, String objectTypeName, Object... fieldValues) {
```
Comment (manuranga) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java:81]: let's add a deprecated annotation here.

Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java:82]: Did it in the last commit

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java [hunk 6]
```diff
@@ -79,14 +81,46 @@
...
         ValueCreator valueCreator = ValueCreator.getValueCreator(packageId.toString());
         Object[] fields = new Object[fieldValues.length * 2];
+        Strand currentStrand = getStrand();
+        // Adding boolean values for each arg
+        for (int i = 0, j = 0; i < fieldValues.length; i++) {
+            fields[j++] = fieldValues[i];
+            fields[j++] = true;
+        }
+        return valueCreator.createObjectValue(objectTypeName, getScheduler(currentStrand), currentStrand, null, fields);
```
[the remark this answers is not in the document]
Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java]: Changed in the latest commit

File: tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-for-one-actions.bal [hunk 7]
```diff
@@ -124,3 +124,18 @@ function add_panic(int i, int j) returns int {
     }
     return k;
 }
+
+type Student object {
+    public string name;
+    public function __init() {
+        future<int> accumulator = start add(2, 4);
```
Comment (riyafa) [inline tests/jballerina-unit-test/src/test/resources/test-src/workers/wait-for-one-actions.bal:131]: Shall we wait for accumulator and assign to a field and assert?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForOneActionsTest.java [hunk 8]
```diff
@@ -101,4 +101,9 @@ public void waitTest9() {
         Assert.assertEquals(vals.length, 1);
         Assert.assertEquals(vals[0], null);
     }
+
+    @Test
+    public void waitTest10() {
```
Comment (riyafa) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForOneActionsTest.java:106]: Shall we use a meaningful name for the testcase?

**Comment by Kishanthan** [comment]
@HindujaB , can you also update the section "Approach" on how you fixed this issue?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java [hunk 9]
```diff
@@ -76,17 +79,51 @@
...
     public static ObjectValue createObjectValue(BPackage packageId, String objectTypeName, Object... fieldValues) {
+        return createObjectValue(packageId, objectTypeName, getStrand(), fieldValues);
+    }
+
+    private static ObjectValue createObjectValue(BPackage packageId, String objectTypeName, Strand currentStrand,
+                                                Object... fieldValues) {
+        //This method duplicates the createObjectValue with referencing the issue in runtime API getting strand
         ValueCreator valueCreator = ValueCreator.getValueCreator(packageId.toString());
         Object[] fields = new Object[fieldValues.length * 2];
+        Scheduler scheduler = currentStrand != null ? currentStrand.scheduler : null;
```
Comment (manuranga) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java:92]: can we remove individual null checks and move it to the if block below (at line 104)

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java [hunk 10]
```diff
@@ -76,17 +79,51 @@
...
         // Adding boolean values for each arg
         for (int i = 0, j = 0; i < fieldValues.length; i++) {
             fields[j++] = fieldValues[i];
             fields[j++] = true;
         }
-        //passing scheduler, strand and properties as null for the moment, but better to expose them via this method
-        return valueCreator.createObjectValue(objectTypeName, null, null, null, fields);
+        try {
+            //Check for non-blocking call
+            if (currentStrand != null && currentStrand.getState() != State.RUNNABLE) {
```
Comment (manuranga) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java:104]: Isn't it enough to check `currentStrand != null` why do we check `currentStrand.getState() != State.RUNNABLE` ?

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java [hunk 11]
```diff
@@ -76,17 +79,54 @@
      * @param fieldValues values to be used for fields when creating the object value instance.
      * @return value of the object.
      */
+    @Deprecated
     public static ObjectValue createObjectValue(BPackage packageId, String objectTypeName, Object... fieldValues) {
+        return createObjectValue(packageId, objectTypeName, getStrand(), fieldValues);
+    }
+
+    private static ObjectValue createObjectValue(BPackage packageId, String objectTypeName, Strand currentStrand,
+                                                Object... fieldValues) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java:88]:
```suggestion
                                                 Object... fieldValues) {
```
