### PR TITLE
 Fix intersection type issues due to constituent type ordering

### LINKED ISSUE #24116: Error when defining an intersection type definition with a type defined after the type definition
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Bar Foo & readonly;

type Foo abstract object {
    function qwe();
};
```

```cmd
$ ballerina run test.bal 
Compiling source
        test.bal
error: .::test.bal:1:10: invalid intersection type with 'readonly', 'other' can never be 'readonly'
```

### LINKED ISSUE #24167: No type-checking error for invalid readonly intersection field where the invalid member type is defined after
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Foo record {|
    Bar & readonly b; // shouldn't be allowed
|};

type Bar record {|
    future<int> fr;
|};

public function main() {
    future<int> fr = start qwe();
    Foo f = {b: {fr}};
}

function qwe() returns int { 
    return 1;
}
```

Fails later with `error: jVM generation is not supported for type other`

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$title.

Fixes #24167 - No type-checking error for invalid readonly intersection field where the invalid member type is defined after

Fixes #24116 Error when defining an intersection type definition with a type defined after the type definition 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 1]
```diff
@@ -1552,6 +1564,81 @@ private void defineMembers(List<BLangTypeDefinition> typeDefNodes, SymbolEnv pkg
...
+    private void validateReadOnlyIntersectionTypeDefinitions(List<BLangTypeDefinition> typeDefNodes) {
+        List<BType> loggedTypes = new ArrayList<>();
+
+        for (BLangTypeDefinition typeDefNode : typeDefNodes) {
+            BLangType typeNode = typeDefNode.typeNode;
+            NodeKind kind = typeNode.getKind();
+            if (kind == NodeKind.INTERSECTION_TYPE_NODE) {
+                BType currentType = typeNode.type;
+
+                if (currentType.tag != TypeTags.INTERSECTION) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1576]: Isn't the type an intersection type if the type node is an intersection type node?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 2]
```diff
@@ -1552,6 +1564,81 @@ private void defineMembers(List<BLangTypeDefinition> typeDefNodes, SymbolEnv pkg
...
+                    continue;
+                }
+
+                BIntersectionType intersectionType = (BIntersectionType) currentType;
+
+                BType effectiveType = intersectionType.effectiveType;
+                if (loggedTypes.contains(effectiveType)) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1583]: If the purpose of the `loggedTypes` list is to keep track of the already checked types, a Set would be a better option from a performance POV right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java [hunk 3]
```diff
@@ -1552,6 +1564,81 @@ private void defineMembers(List<BLangTypeDefinition> typeDefNodes, SymbolEnv pkg
...
+                    continue;
+                }
+
+                loggedTypes.add(effectiveType);
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1587]: If the purpose of the `loggedTypes` list is to keep track of the already checked types, a Set would be a better option from a performance POV right? And the above can even be written as,
```java
if (!loggedTypes.add(effectiveType)) {
    continue;
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 4]
```diff
@@ -1588,11 +1588,19 @@ private BType computeIntersectionType(BLangIntersectionTypeNode intersectionType
 
         BLangType bLangTypeOne = constituentTypeNodes.get(0);
         BType typeOne = resolveTypeNode(bLangTypeOne, env);
+
+        if (typeOne == symTable.noType) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1592]: When can these types be `noType`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1576]: This can be `symTable.noType` if a member type could not be resolved.

e.g., where `Foo` is not defined
```ballerina
type MyType Foo & readonly;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 3 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1587]: +1, will send a separate PR to fix this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 4 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1592]: If the member type definition is after intersection type definition, this can happen. It is handled later on via unresolved types.

```ballerina
type MyType Foo & readonly;

type Foo record {
    int i;
};
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java (hunk 3 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java:1587]: Fixed in d964ea0.
