### PR TITLE
Fix Completion Issues

### LINKED ISSUE #25964: Record Type Descriptor and Object Type Descriptors are not suggested in Language Server
**Description:**
$title where the type descriptors are expected. LS should suggest `record` and `object` keywords as well.

### LINKED ISSUE #25972: Standard libraries are not suggested for the auto completions
**Description:**
Standard libraries should be loaded to LS cache from bir, lib and jar caches as well as from lib/repo

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose
With this, fixes the following,

Fixes #25972
Fixes #25964

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSPackageLoader.java [hunk 1]
```diff
@@ -91,36 +92,45 @@ public static BLangPackage getPackageById(CompilerContext context, PackageID pac
...
-                            String[] versions = versionDir.list();
-                            if (versions != null) {
-                                for (String version : versions) {
-                                    BallerinaPackage ballerinaPackage = new BallerinaPackage(repo, name, version);
-                                    ballerinaPackages.add(ballerinaPackage);
-                                    if (!visibleOrgs.contains(repo)) {
-                                        visibleOrgs.add(repo);
-                                    }
+            String libRepoDir = Paths.get(ballerinaSDKHome, LIB_REPO_DIR).toString();
+            String baloCacheDir = Paths.get(ballerinaSDKHome, BALO_CACHE_DIR).toString();
```
Comment (rasika) [inline language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSPackageLoader.java:96]: Would this change allow literally any balo pulled from Ballerina Central?

**Review by rasika — APPROVED** [review]
