### PR TITLE
[LS] Fix several issues and add serveral completion/codeaction improvements

### LINKED ISSUE #29522: Suggestions are not shown for NATS message record fields
**Description:**
It supposed to show the record fields of NATS message type. But not being shown.
Screenshot 2021-03-23 at 23 49 04

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #29738: "Create variable" code action doesn't work as expected with intersection types
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    int[] x = [1, 2];
    x.cloneReadOnly(); // returns `int[] & readonly`

    func(); // returns `int[] & readonly`
}

function func() returns int[] & readonly => [1, 2];
```

Using the create variable code action with both the `x.cloneReadOnly()` and `func()` calls add a variable of type `int[]` even though the actual type is `int[] & readonly`.

**Affected Versions:**
slalpha4-SNAPSHOT

### LINKED ISSUE #30319: [LS] Create function code action not suggested when creating strands with `start undefinedMethod()`
**Description:**
Consider the following code:
```
future<int> f1 = start testAsync();
```
where the `testAsync()` function is not defined. Created function code action is not suggested here. 

**Steps to reproduce:**
See description

**Affected Versions:**
SLA5

**OS, DB, other environment details and versions:**

**Suggested Labels (optional):**
Language server

**Suggested Assignees (optional):**
IMS94

### LINKED ISSUE #30435: Create Function code action adds an empty line within the function generated
**Description:**
$title as per bellow

```
function calGraduationYear(int a) returns int {
    <empty-line here>
    return 0;
}
```

Shall we avoid adding this empty line?

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
- Create function code action now supports creating undefined functions in start actions (when creating strands)
- Create variable code action supports intersection types fully (it was fixed mostly by #30226, this includes addressing some edge cases)
- Add completion support for init function in classes
- Add completions for records (mapping constructor) at function/method parameters and implicit/explicit new expressions.

Fixes #29738
Fixes #29522
Fixes #30319
Fixes #30435

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java [hunk 1]
```diff
@@ -307,7 +307,7 @@ public static CodeActionNodeType codeActionNodeType(Node node) {
         }
 
         // Remove brackets of the unions, except the nil "()" type
-        types = types.stream().map(v -> v.replaceAll("^\\((.+)\\)$", "$1")).collect(Collectors.toList());
+//        types = types.stream().map(v -> v.replaceAll("^\\((.+)\\)$", "$1")).collect(Collectors.toList());
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java:310]: if not needed shall we remove this line instead of commenting?

Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java:310]: if not needed shall we remove this line instead of commenting?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ClassDefinitionNodeContextUtil.java [hunk 2]
```diff
@@ -22,10 +20,21 @@ public static boolean onSuggestResourceSnippet(Node node) {
...
-                    .map(Token::text).collect(Collectors.toList())
-                    .contains("service");
+                    .anyMatch(token -> token.kind() == SyntaxKind.SERVICE_KEYWORD);
         }
         
         return false;
     }
+
+    public static boolean onSuggestInitFunction(Node node) {
+        if (node.kind() == SyntaxKind.CLASS_DEFINITION) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ClassDefinitionNodeContextUtil.java:30]: Maybe we can early return from here?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ClassDefinitionNodeContextUtil.java (hunk 2 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ClassDefinitionNodeContextUtil.java:30]: Yes, that's better. Addressed.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java (hunk 1 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java]: Yes, we can remove this. Done.

**Review by nadeeshaan — APPROVED** [review]
LGTM

**Review by malinthar — DISMISSED** [review]

**Review by nadeeshaan — APPROVED** [review]
