### PR TITLE
Fix error constructors with invalid named arguments

### LINKED ISSUE #39581: [Bug]: Compiler crashes for `error` construction when a detail field's name is a qualified identifier
### Description

$title

### Steps to Reproduce

```
public function main() {
    error<record {| int err\:code; |}> e = error("er:ror!", err:code = 1001);
}
```
>[2023-02-13 14:01:35,048] SEVERE {b7a.log.crash} - class io.ballerina.compiler.syntax.tree.QualifiedNameReferenceNode cannot be cast to class io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode (io.ballerina.compiler.syntax.tree.QualifiedNameReferenceNode and io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.compiler.syntax.tree.QualifiedNameReferenceNode cannot be cast to class io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode (io.ballerina.compiler.syntax.tree.QualifiedNameReferenceNode and io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode are in unnamed module of loader 'app')
        at io.ballerina.compiler.syntax.tree.NamedArgumentNode.argumentName(NamedArgumentNode.java:36)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:3239)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2237)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.ErrorConstructorExpressionNode.apply(ErrorConstructorExpressionNode.java:63)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createActionOrExpression(BLangNodeBuilder.java:5427)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createExpression(BLangNodeBuilder.java:5400)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createBLangVarDef(BLangNodeBuilder.java:2983)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:2958)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.generateAndAddBLangStatements(BLangNodeBuilder.java:5299)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1670)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:63)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.populateFunctionNode(BLangNodeBuilder.java:1573)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.createFunctionNode(BLangNodeBuilder.java:1551)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:1529)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:654)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.transform(BLangNodeBuilder.java:514)
        at io.ballerina.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeBuilder.accept(BLangNodeBuilder.java:553)
        at io.ballerina.projects.DocumentContext.compilationUnit(DocumentContext.java:111)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:419)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:381)
        at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:202)
        at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:186)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:99)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:94)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
        at io.ballerina.projects.Package.getCompilation(Package.java:148)
        at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:256)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:126)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:221)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by ushirask**
Fixes #39581 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -6484,9 +6484,14 @@ private STNode parseNamedOrPositionalArg() {
...
-                STNode valExpr = parseExpression();
-                return STNodeFactory.createNamedArgumentNode(argNameOrExpr, equal, valExpr);
+                if (argNameOrExpr.kind == SyntaxKind.SIMPLE_NAME_REFERENCE) {
+                    STNode equal = parseAssignOp();
+                    STNode valExpr = parseExpression();
+                    return STNodeFactory.createNamedArgumentNode(argNameOrExpr, equal, valExpr);
+                }
+                // Treat invalid NamedArgument as a positional argument
+                argNameOrExpr = parseExpressionRhs(DEFAULT_OP_PRECEDENCE, argNameOrExpr, true, false);
+                return STNodeFactory.createPositionalArgumentNode(argNameOrExpr);
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:6494]: L6493-L6494 is same as the default case logic. So shall we refactor like this to avoid duplication?
and then you need to extract the default case logic out of the switch.

```suggestion
                if (argNameOrExpr.kind != SyntaxKind.SIMPLE_NAME_REFERENCE) {
                    break;
                }
                STNode equal = parseAssignOp();
                STNode valExpr = parseExpression();
                return STNodeFactory.createNamedArgumentNode(argNameOrExpr, equal, valExpr);
```

**Review by lochana-chathura — APPROVED** [review]
Looks gd. Re-triggered the failed job.
