### PR TITLE
Fix references issue for type inference in records

### LINKED ISSUE #30899: [LS] Record type inclusion within a record is not renamed/shown as a reference
**Description:**
$subject

```
public type Vehicle record {|
    Brand brand;
    string model;
    int manufactoredYear;
|};

public type Car record {|
    *Vehicle;
    
|};
```
Consider above example, when we rename `Vehicle`, only the original record is renamed. Type inclusion in `Car` is not renamed.

**Steps to reproduce:**
See description

**Affected Versions:**
Beta1 RC6

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose
Fixes #30899

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindAllReferencesTest.java [hunk 1]
```diff
@@ -123,11 +124,18 @@ protected Location location(int line, int startCol, int endCol, String fileName)
...
         assertEquals(locations.size(), expLocations.size());
 
-        for (int i = 0; i < expLocations.size(); i++) {
-            Location expLocation = expLocations.get(i);
-            Location location = locations.get(i);
-
-            assertEquals(location.lineRange(), expLocation.lineRange());
+        for (Location expLocation : expLocations) {
+            boolean matched = false;
+            for (Location location : locations) {
```
Comment (IMS94) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindAllReferencesTest.java:129]: We can simply use
```
Assert.assertTrue(locations.contins(expLocation))
```
right?

**Review by IMS94 — APPROVED** [review]
LGTM! There's a comment on the way we check equality of locations.

File: tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindAllReferencesTest.java [hunk 2]
```diff
@@ -123,11 +124,18 @@ protected Location location(int line, int startCol, int endCol, String fileName)
...
+                if (location.lineRange().equals(expLocation.lineRange())) {
+                    matched = true;
+                    break;
+                }
+            }
+
+            if (!matched) {
+                Assert.fail("No matching reference found for: " + expLocation);
+            }
```
Comment (pubudu91) [inline tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/allreferences/FindAllReferencesTest.java:138]: Wouldn't `locations.contains(expLocation)` do for this? 🤔

**Review by IMS94 — APPROVED** [review]
