### PR TITLE
Fix incorrect interop error message

### LINKED ISSUE #33658: Incorrect Error Message
Adding the following function to a program gives an exception error, 

```
function read(handle receiver) returns int = @java:Method {
   'class: "java.io.InputStream"
} external;
```

Error :
`ERROR [main.bal:(28:1,30:12)] {ballerina/jballerina.java}METHOD_SIGNATURE_DOES_NOT_MATCH 'No such Java method 'read' which throws checked exception found in class 'class java.io.InputStream''`

This error should be corrected as,
METHOD_SIGNATURE_DOES_NOT_MATCH ‘No such Java method ‘read’ which **does not** throw checked exception found in 'class java.io.InputStream 

Or it should have mentioned to return **int|error** instead of **int**.

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #33658

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java [hunk 1]
```diff
@@ -272,8 +272,10 @@ private void validateExceptionTypes(JMethodRequest jMethodRequest, JMethod jMeth
         if ((throwsCheckedException && !jMethodRequest.returnsBErrorType) ||
                 (jMethodRequest.returnsBErrorType && !throwsCheckedException && !returnsErrorValue)) {
             throw new JInteropException(DiagnosticErrorCode.METHOD_SIGNATURE_DOES_NOT_MATCH,
-                    "No such Java method '" + jMethodRequest.methodName + "' which throws checked exception " +
-                            "found in class '" + jMethodRequest.declaringClass + "'");
+                    "Incompatible ballerina return type for the Java method '" + jMethodRequest.methodName +
+                            "' which throws checked exception found in class '" + jMethodRequest.declaringClass +
+                            "': expected '" + jMethodRequest.bReturnType + "|error', found '" +
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:277]: Can `jMethodRequest.bReturnType` have an error type? If so, this can lead to multiple `error` in the diagnostic message.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/NegativeValidationTest.java [hunk 2]
```diff
@@ -161,9 +161,11 @@ public void testMethodSignatureNotMatch1() {
...
         Assert.assertEquals(compileResult.getDiagnostics().length, 1);
         BAssertUtil.validateError(compileResult, 0,
-                "{ballerina/jballerina.java}METHOD_SIGNATURE_DOES_NOT_MATCH 'No such Java method " +
-                        "'acceptIntReturnIntThrowsCheckedException' which throws checked exception found in class " +
-                        "'class org.ballerinalang.nativeimpl.jvm.tests.StaticMethods''",
+                "{ballerina/jballerina.java}METHOD_SIGNATURE_DOES_NOT_MATCH 'Incompatible ballerina " +
+                        "return type for the Java method 'acceptIntReturnIntThrowsCheckedException' which throws " +
+                        "checked exception found in class " +
+                        "'class org.ballerinalang.nativeimpl.jvm.tests.StaticMethods': " +
+                        "expected 'int|error', found 'int''",
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/NegativeValidationTest.java:168]: Shall we have something like this? 
```java
"{ballerina/jballerina.java}METHOD_SIGNATURE_DOES_NOT_MATCH 'Incompatible ballerina return type found for Java method 'acceptIntReturnIntThrowsCheckedException' from 'class org.ballerinalang.nativeimpl.jvm.tests.StaticMethods' which throws checked exception : \n expected 'int|error', found 'int'"
```
or
```java
"{ballerina/jballerina.java}METHOD_SIGNATURE_DOES_NOT_MATCH 'Incompatible ballerina return type found for Java method 'acceptIntReturnIntThrowsCheckedException' from 'class org.ballerinalang.nativeimpl.jvm.tests.StaticMethods' : \n expected 'int|error', found 'int'"
```
?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java (hunk 1 above)
Comment (warunalakshitha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:277]: Also we need to check jMethodRequest.bReturnType is nill, since we can directly shoe error

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java]: > If `jMethodRequest.bReturnType` is error type or union of error, it will not result in this compilation error. Added some test cases regarding this.

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java]: Addressed the suggestions with https://github.com/ballerina-platform/ballerina-lang/pull/33876/commits/825ec8d4ae49527d3e993b4aa9dd1969b5d6c23f

**Review by warunalakshitha — APPROVED** [review]
LGTM

File: tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal [hunk 3]
```diff
@@ -226,6 +233,10 @@ public function getArrayValueFromMapWhichThrowsCheckedException(string key, map<
     'class:"org/ballerinalang/nativeimpl/jvm/tests/StaticMethods"
 } external;
 
+public function acceptIntErrorUnionReturnWhichThrowsCheckedException(int flag) returns int|error = @java:Method {
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal:236]: Shall we have a test case with distinct errors as well?

Comment (gabilang) [reply tests/jballerina-unit-test/src/test/resources/test-src/javainterop/ballerina_types_as_interop_types.bal:236]: Added with https://github.com/ballerina-platform/ballerina-lang/pull/33876/commits/f19a60666316fc0e9477b452977692e3e34be8da

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java [hunk 4]
```diff
@@ -271,9 +272,27 @@ private void validateExceptionTypes(JMethodRequest jMethodRequest, JMethod jMeth
...
+            BType returnType = jMethodRequest.bReturnType;
+            BType modifiedRetType = returnType;
+            if (returnType.tag == TypeTags.UNION) {
+                LinkedHashSet<BType> memTypes = new LinkedHashSet<>();
+                for (BType bType : ((BUnionType) returnType).getMemberTypes()) {
+                    if (!(bType instanceof BTypeReferenceType &&
+                            ((BTypeReferenceType) bType).referredType.tag == TypeTags.ERROR)) {
+                        memTypes.add(bType);
+                    }
+                }
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:284]: Shall we have a separate method for this? something like `getNonErrorMembers()`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java [hunk 5]
```diff
@@ -271,10 +272,33 @@ private void validateExceptionTypes(JMethodRequest jMethodRequest, JMethod jMeth
 
         if ((throwsCheckedException && !jMethodRequest.returnsBErrorType) ||
                 (jMethodRequest.returnsBErrorType && !throwsCheckedException && !returnsErrorValue)) {
+            BType returnType = jMethodRequest.bReturnType;
+            BType modifiedRetType = returnType;
+            if (returnType.tag == TypeTags.UNION) {
+                BUnionType bUnionReturnType = (BUnionType) returnType;
+                modifiedRetType = BUnionType.create(null, getNonErrorMembers(bUnionReturnType));
+            }
+            String expectedRetTypeName = modifiedRetType + "|error";
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:281]: We do not need to run this code if it is null. 

ex. 
if (returnType.tag == TypeTags.NIL || returnType instanceof BTypeReferenceType &&
                    ((BTypeReferenceType) returnType).referredType.tag == TypeTags.ERROR) {
                expectedRetTypeName = "error";
            } else ((returnType.tag == TypeTags.UNION)){
   BUnionType bUnionReturnType = (BUnionType) returnType;
                BType  modifiedRetType = BUnionType.create(null, getNonErrorMembers(bUnionReturnType));
String expectedRetTypeName = modifiedRetType + "|error";
} else {
 expectedRetTypeName = returnType + "|error";
}

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java]: Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/33876/commits/88f9cd6bd08f78633724cfcad49797b6cab31330
