### PR TITLE
Fix issues with fromBalString

### LINKED ISSUE #28455: When you pass a string value to fromBalString method, panic with error
**Description:**

```
error: java.util.regex.PatternSyntaxException {"message":"Stack overflow during pattern compilation near index 11
[+-]?[0-9]+([.][0-9]+)?([Ee][+-]?[0-9]+)?
           ^"}
        at ballerina.lang.value.1_0_0:fromBalString(value.bal:135)
           main:main(main.bal:3)
```
**Steps to reproduce:**
```
import ballerina/lang.'value;
public function main() {
    var e = value:fromBalString("hello");
}
```

**Affected Versions:**
SL-aplha1

**OS, DB, other environment details and versions:**
Ubuntu

### PR DESCRIPTION
**Pull request by lasinicl**
## Purpose

- Fix panic when an invalid expression style string value is used with `fromBalString`  
- Fix bug in parsing empty values

Fixes #28455

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/StringUtils.java [hunk 1]
```diff
@@ -293,8 +294,9 @@ public static String getExpressionStringValue(Object value, BLink parent) {
      *
      * @param value The value on which the function is invoked
      * @return Ballerina value represented by Ballerina expression syntax
+     * @throws BError for any parsing error
      */
-    public static Object parseExpressionStringValue(String value, BLink parent) {
+    public static Object parseExpressionStringValue(String value, BLink parent) throws BError {
```
Comment (rdhananjaya) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/StringUtils.java:299]: BError is not a checked exception right?

Comment (lasinicl) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/utils/StringUtils.java]: Fixed in 7f00924

**Review by mohanvive — APPROVED** [review]
