### PR TITLE
Reorder the desugaring of type definitions before the desugaring of global variables and configurables in the desugar phase

### LINKED ISSUE #42829: [Bug]: When trying to create a Java String for a enum value a `TypeCastError` is thrown
### Description

> $subject

### Steps to Reproduce

Consider the following code segment:

```ballerina
import ballerina/jballerina.java as java;

public enum LogLevel {
    DEBUG,
    INFO,
    WARNING,
    ERROR,
    FATAL,
    OFF
}

public type CustomConfiguration record {
    LogLevel logLevel = OFF;
};

configurable CustomConfiguration customConfiguration = {};

public isolated client class SampleClient {
    private final readonly & LogLevel logLevel;

    public isolated function init() returns error? {
        self.logLevel = customConfiguration.logLevel;
        handle logHandle = java:fromString(self.logLevel);
    }
}

public function main() returns error? {
    SampleClient clientEp = check new;
}
```

Following runtime error is thrown when trying to run the above program:
```
error: {ballerina}TypeCastError {"message":"incompatible types: '()' cannot be cast to 'string'"}
	at ayesh.asb_issue_test.0.SampleClient:init(client.bal:25)
	   ayesh.asb_issue_test.0:main(client.bal:31)
```

### Affected Version(s)

Ballerina SL 2201.9.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)
- [#6573](https://github.com/ballerina-platform/ballerina-library/issues/6573)

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fixes #42829 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -794,6 +794,8 @@ public void visit(BLangPackage pkgNode) {
 
         pkgNode.constants = removeDuplicateConstants(pkgNode);
 
+        rewrite(pkgNode.typeDefinitions, env);
```
Comment (dulajdilshan) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:797]: Why aren't we assigning the value to `pkgNode.typeDefinitions` here as previous?

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:797]: Earlier also, we didn't need to do that because within the rewrite function, we set the desugared value to the node list.

**Review by dulajdilshan — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 1 above)
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:797]: Don't you need the sorting by precedence done  in L809 before this?

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:797]: Can you briefly explain how changing the order fixes the issue?

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_var_decl.bal [hunk 2]
```diff
@@ -25,9 +25,22 @@ configurable UserInfo admin = {
...
 
+public type CustomConfiguration record {
+    string username;
+    string logLevel = "OFF";
+};
+
+configurable CustomConfiguration customConfig1 = {username: "chiranS"};
+
+configurable CustomConfiguration customConfig2 = {username: "chiranS", logLevel: "DEBUG"};
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_var_decl.bal:36]: Please add a test when the entire value is provided too. Maybe with ?.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 1 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:797]: In the current implementation, we desugar the value of global variables after adding the init function, but for configurables, we desugar before adding them to the init function. 

In the `desugarGlobalVariables` function, we perform the following actions: if there's a global variable defined as `record{int x = 10;}  k = {}`, we create a variable declaration `record{int x = 10;}  k` and add it to the global variable list. Additionally, we create another variable reference `k = {}` and add it to the initialization function. 
The values of global variables are desugared during the desugaring process of the initialization function.(So global variables are working properly as expected)

In the current implementation, the desugaring of configurable variables' values takes place when visiting the global variables, rather than during the desugaring of the init function, as previously mentioned.

Due to this, we need to desugar type definitions before desugaring configurables.

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:797]: I checked that. What I understand is After desugaring also, we can sort that (that sort is needed only for annotations as I understand).

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:797]: Can't we change configurables to be similar to global variables? Not suggesting that we do it, but checking on the feasibility. Changing the order can have unexpected effects, and therefore, updating configurables may be a safer choice.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_var_decl.bal (hunk 2 above)
Comment (chiranSachintha) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_var_decl.bal:36]: What you mean by entire value? Small example?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java (hunk 1 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:797]: Yeah, I will check that.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_var_decl.bal (hunk 2 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/configurable_var_decl.bal:36]: configurable CustomConfiguration customConfig3 = ?;

**Review by MaryamZi — APPROVED** [review]

**Review by dulajdilshan — APPROVED** [review]
