### PR TITLE
[Testerina] Derive test suite from Syntax tree and Semantic API

### LINKED ISSUE #27256: [Testerina] Derive test suite from syntax tree and semantic model
**Description:**
Look into an approach to derive test suite from syntax tree and semantic model

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Dilhasha**
## Purpose
Derive test suite from syntax tree

Fixes #27256

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/MockAnnotationProcessor.java [hunk 1]
```diff
@@ -0,0 +1,237 @@
+/*
+ * Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (azinneera) [inline misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/MockAnnotationProcessor.java:2]:
```suggestion
 * Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```

File: misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java [hunk 2]
```diff
@@ -0,0 +1,480 @@
...
+            });
+        }
+        return syntaxTreeMap;
+    }
+
+    /**
+     * Generate the testsuite for module using syntax and semantic APIs.
+     *
+     * @param module  Module
+     */
```
Comment (azinneera) [inline misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java:125]: missing return statement

File: misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java [hunk 3]
```diff
@@ -0,0 +1,480 @@
...
+            for (Qualifier qualifier : qualifiers) {
+                if (Flag.RESOURCE.name().equals(qualifier.getValue()) ||
+                        Flag.REMOTE.name().equals(qualifier.getValue())) {
+                    isUtility = false;
+                    break;
+                }
+            }
+            if (pos != null && isUtility) {
+                // Remove the duplicated annotations.
+                String className = pos.lineRange().filePath().replace(".bal", "")
```
Comment (azinneera) [inline misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java:280]: Shall we use the constant in ProjectConstants instead of hardcoding `.bal`

File: misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TesterinaRegistry.java [hunk 4]
```diff
@@ -17,7 +17,7 @@
 */
 package org.ballerinalang.testerina.core;
 
-import org.ballerinalang.test.runtime.entity.TestSuite;
+import io.ballerina.projects.testsuite.TestSuite;
```
Comment (azinneera) [inline misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TesterinaRegistry.java:20]: shall we remove the `io.ballerina.projects.testsuite` package and move all the classes back to testerina runtime module?

File: cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java [hunk 5]
```diff
@@ -160,15 +161,15 @@ public void execute(Project project) {
...
+        TestProcessor testProcessor = new TestProcessor();
         // Only tests in packages are executed so default packages i.e. single bal files which has the package name
         // as "." are ignored. This is to be consistent with the "ballerina test" command which only executes tests
         // in packages.
         for (ModuleId moduleId : project.currentPackage().moduleIds()) {
             Module module = project.currentPackage().module(moduleId);
             ModuleName moduleName = module.moduleName();
 
-            TestSuite suite = jBallerinaBackend.testSuite(module).orElse(null);
+            TestSuite suite = testProcessor.testSuite(module, project).orElse(null);
```
Comment (azinneera) [inline cli/ballerina-cli/src/main/java/io/ballerina/cli/task/RunTestsTask.java:172]: we can access the project from the module using `module.project()`

**Comment by azinneera** [comment]
LGTM

**Review by Ibaqu — APPROVED** [review]
