### PR TITLE
Split `init` functions in to multiple classes

### LINKED ISSUE #41555: [Bug]: "file is too large" is thrown when building a Ballerina project with version `1.2.x`
### Description

$title

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #41555

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/LargeMethodSplitter.java [hunk 1]
```diff
@@ -136,6 +164,12 @@ private BLangFunction splitInitFunction(BLangPackage packageNode, SymbolEnv env)
                 if (newFuncBody.stmts.size() + chunkStmts.size() > methodSize) {
                     generatedFunctions.add(newFunc);
                     newFunc = createIntermediateInitFunction(packageNode, env);
+                    splitFuncCount++;
+                    if (splitFuncCount % INIT_FUNC_COUNT_PER_CLASS == 0) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/LargeMethodSplitter.java:168]: Shall we check why these lines not covered?

Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/LargeMethodSplitter.java]: Removed the lines not getting covered.

File: tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/modules/mod/mod.bal [hunk 2]
```diff
@@ -0,0 +1,466 @@
+// Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
```
Comment (gabilang) [inline tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/modules/mod/mod.bal:1]: We need to remove `All Rights Reserved` part from the license header.

File: tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/main.bal [hunk 3]
```diff
@@ -0,0 +1,475 @@
+// Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
```
Comment (gabilang) [inline tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/main.bal:1]:
```suggestion
// Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com).
```

File: tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/main.bal [hunk 4]
```diff
@@ -0,0 +1,475 @@
...
+    remote function action2(string s, boolean b) returns int {
+        return 10;
+    }
+
+    function func() {
+        count = count + 1;
+    }
+
+    function func1(string s) {
+
```
Comment (gabilang) [inline tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/main.bal:262]:
```suggestion
```

File: tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/modules/mod/mod.bal [hunk 5]
```diff
@@ -0,0 +1,466 @@
...
+    remote function action1(string s, int i) returns boolean {
+        return false;
+    }
+
+    remote function action2(string s, boolean b) returns int {
+        return 10;
+    }
+
+    function func() {
+
```
Comment (gabilang) [inline tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/modules/mod/mod.bal:253]:
```suggestion
```

File: tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/modules/mod/mod.bal [hunk 6]
```diff
@@ -0,0 +1,466 @@
...
+    }
+
+    function func1(string s) {
+
```
Comment (gabilang) [inline tests/jballerina-unit-test/src/test/resources/test-src/execution/large-init/modules/mod/mod.bal:257]:
```suggestion
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/LargeMethodSplitter.java [hunk 7]
```diff
@@ -295,8 +279,8 @@ private BLangFunction splitStopFunction(BLangPackage packageNode, SymbolEnv env)
         newFuncBody.stmts.add(stmts.get(stmts.size() - 1));
         generatedFunctions.add(newFunc);
 
-        // for the stop function, splitting is done same as the start function except here
-        // here just need only to call the next created stop function because the return value is () and not ()|error
+        // for the stop function, splitting is done same as the start function except here.
+        // here just need only to call the next created stop function because the return value is () and not ()|error.
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/LargeMethodSplitter.java:283]:
``` suggestion
        // For the stop function, splitting is done the same as the start function except here.
        // Here, it is only required to call the next created stop function because the return value is () and not ()|error.
```

**Review by HindujaB — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM
