### PR TITLE
Include description-section in API docs generation

### LINKED ISSUE #41928: [Bug]: Description sections are not handled in API docs generation
### Description

Description sections can be added in a description of an API in Ballerina.

e.g.; https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/blob/66907fec1ce68a47e8fa08733dbb8e0918abae0b/ballerina/client.bal#L1142

But in the API docs generation, this scenario is not handled and issues also have been reported as well related to this.
https://github.com/ballerina-platform/ballerina-library/issues/5881

We need to implement handling description sections in API docs generation. Design of a description in an API as follows.
Untitled Diagram (4)

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by NipunaMadhushan**
## Purpose
Include description sections in API docs generation.

Fixes #41928

## Approach
Design for the implementation for description section and the specification has been mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/41928

### CODE REVIEW

**Review by sm1990 — DISMISSED** [review]

**Review by sm1990 — APPROVED** [review]

File: misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Variable.java [hunk 1]
```diff
@@ -24,8 +24,9 @@ public class Variable extends Construct {
     @Expose
     public Type type;
 
-    public Variable(String name, String description, boolean isDeprecated, Type type) {
-        super(name, description, isDeprecated);
+    public Variable(String name, String description, boolean isDeprecated,
+                    Type type) {
+        super(name, description, null, isDeprecated);
```
Comment (keizer619) [inline misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Variable.java:29]: Can't we overload super constructor instead of passing `null`?

Comment (NipunaMadhushan) [reply misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Variable.java:29]: Sure we can. I will update the PR.

Comment (NipunaMadhushan) [reply misc/docerina/src/main/java/org/ballerinalang/docgen/generator/model/Variable.java]: addressed review suggestions

**Review by keizer619 — APPROVED** [review]
