### PR TITLE
Fix not showing empty lines in the code snippets in the description

### LINKED ISSUE #38963: [Bug]: Empty lines are not visible in ballerina langlib api docs examples
### Description

When we add an example for an api for readability purposes we keep empty lines. 

```ballerina
table<Employee> key(id) employees = table [
       {name: "Jo", salary: 1200, id: 2121},
       {name: "Emma", salary: 800, id: 2122},
       {name: "John", salary: 1500, id: 2123}
 ];

 Employee[] employeeArray = employees.toArray();

 type Employee record {|
   readonly int id;
   string name;
   decimal salary;
 |};
 ```
Above code snippet should have two empty lines for `toArray()` api doc in table langlib. But when we generate the docs it is not visible. 
Screenshot 2022-12-06 at 11 03 53

### Steps to Reproduce

```
# Returns a list of all the members of a table.
#
# ```ballerina
# table<Employee> key(id) employees = table [
#       {name: "Jo", salary: 1200, id: 2121},
#       {name: "Emma", salary: 800, id: 2122},
#       {name: "John", salary: 1500, id: 2123}
# ];
#
# Employee[] employeeArray = employees.toArray();
#
# type Employee record {|
#   readonly int id;
#   string name;
#   decimal salary;
# |};
# ```
#
# + t - the table
# + return - an array whose members are the members of parameter `t`
```

Replace the above snippet with the existing documentation in `toArray()` api in the `table` langlib. Run below two commands.

`cd langlib/lang.table/src/main/ballerina/`

`bal doc`

### Affected Version(s)

2201.3.0

### PR DESCRIPTION
**Pull request by NipunaMadhushan**
## Purpose
$subject

Fixes #38963

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by keizer619 — APPROVED** [review]

**Review by sm1990 — APPROVED** [review]

File: misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java [hunk 1]
```diff
@@ -1076,7 +1076,11 @@ private static String getDocCodeBlockString(MarkdownCodeBlockNode markdownCodeBl
         markdownCodeBlockNode.langAttribute().ifPresent(langAttribute -> doc.append(langAttribute));
 
         for (MarkdownCodeLineNode codeLineNode : markdownCodeBlockNode.codeLines()) {
-            doc.append(codeLineNode.codeDescription().toString());
+            if (codeLineNode.codeDescription().toString().isEmpty()) {
+                doc.append("\n");
+            } else {
+                doc.append(codeLineNode.codeDescription().toString());
+            }
```
Comment (chiranSachintha) [inline misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java:1083]:
```java
doc.append(codeLineNode.codeDescription().toString().isEmpty() ? "\n" codeLineNode.codeDescription().toString());
```
