### PR TITLE
[1.2.x] Add support for map -> record assignment

### LINKED ISSUE #17202: Compatible map to record assignment is not allowed
**Description:**
$subject.

**Steps to reproduce:**
```ballerina
// works
record {| string...; |} x = {"a":"aaa", "b":"bbb"};
map<any> y = x;

// doesn't work. However, this should also work.
map<string> y = {"a":"aaa", "b":"bbb"};
record {| string...; |} x = y;
```

### PR DESCRIPTION
**Pull request by pubudu91**
## Samples
```ballerina
import ballerina/io;

public function main() {
    map<string> m = {"a":"aaa", "b":"bbb"};
    record {| string...; |} r = m;

    io:println(r);
} 
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -631,6 +627,21 @@ private boolean recordFieldsAssignableToMap(BRecordType recordType, BMapType tar
...
     }
 
+    private boolean isAssignableMapType(BMapType sourceMapType, BRecordType targetRecType) {
+        if (targetRecType.sealed) {
+            return false;
+        }
+
+        for (BField field : targetRecType.fields) {
+            if (!Symbols.isFlagOn(field.symbol.flags, Flags.OPTIONAL) ||
+                    !isAssignable(targetRecType.restFieldType, field.type)) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Shouldn't this be 
```suggestion
                    !isAssignable(sourceMapType.constraint, field.type)) {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/record/negative/map_to_record_negative.bal [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+    record {|
+        Bar...;
+    |} r1 = m1;
+
+    map<Bar> m2 = {"bb": {a: 10}, "x": {a: 20}};
+    record {|
+        Baz x?;
+        Foo...;
+    |} r2 = m2;
+}
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/negative/map_to_record_negative.bal]: Missing a new line.

File: tests/jballerina-unit-test/src/test/resources/test-src/record/map_to_record.bal [hunk 3]
```diff
@@ -0,0 +1,208 @@
...
+
+// Util functions
+
+function assert(anydata expected, anydata actual) {
+    if (expected != actual) {
+        typedesc<anydata> expT = typeof expected;
+        typedesc<anydata> actT = typeof actual;
+        string reason = "expected [" + expected.toString() + "] of type [" + expT.toString()
+                            + "], but found [" + actual.toString() + "] of type [" + actT.toString() + "]";
+        panic error(reason);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/record/map_to_record.bal]: Shall we use a simple literal (e.g., `AssertionError`) and use the current reason as the `message` of the detail?
