### PR TITLE
Use ballerina module run approach for single bal files

### LINKED ISSUE #22002: Revert `RunExecutableTask` to use process builder approach for single bal files
**Description:**
To support the current debugger implementation, both ballerina modules and single files should be having a common approach when running (either use the same process(class loader approach) or in a separate process(Process builder approach)). But due to some recent changes introduced to packerina implementation, modules and single files takes different approaches, which ends up the debugger being not connected for single bal files. Therefore after having a offline discussion with @warunalakshitha, it was decided to fix single bal file run implementation to use process build builders, which same to ballerina module run approach.

**Steps to reproduce:**

**Affected Versions:**
1.2.0 and below.

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by suganyasuven**
Fixes #22002

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java [hunk 1]
```diff
@@ -158,49 +148,15 @@ private void runGeneratedExecutable(BLangPackage executableModule, BuildContext
...
-    }
-
     private String getAllClassPaths(BLangPackage executableModule, BuildContext buildContext) {
         StringJoiner cp = new StringJoiner(File.pathSeparator);
         // Adds executable thin jar path.
         cp.add(this.executableJarPath.toString());
         // Adds all the dependency paths.
+        if (buildContext.getSourceType() == SINGLE_BAL_FILE) {
+            cp.add(System.getProperty(BALLERINA_HOME) + "/bre/lib/*");
+            return cp.toString();
```
Comment (NipunaRanasinghe) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java]: Better to use comments to describe what we do here and the reason behind to always add all the jars inside `/bre/lib` for single bal file scenario :)

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java [hunk 2]
```diff
@@ -158,49 +148,17 @@ private void runGeneratedExecutable(BLangPackage executableModule, BuildContext
...
-
     private String getAllClassPaths(BLangPackage executableModule, BuildContext buildContext) {
         StringJoiner cp = new StringJoiner(File.pathSeparator);
         // Adds executable thin jar path.
         cp.add(this.executableJarPath.toString());
-        // Adds all the dependency paths.
+        if (buildContext.getSourceType() == SINGLE_BAL_FILE) {
+            // Adds '<ballerina-home>/bre/lib/*' to the class-path since we need to have ballerina runtime
+            // related dependencies when running single bal files.
+            cp.add(System.getProperty(BALLERINA_HOME) + "/bre/lib/*");
```
Comment (warunalakshitha) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java]: Shall we use   String balHomePath = buildContext.get(BuildContextField.HOME_REPO).toString() for getting ballerina home as we did in other tasks

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java [hunk 3]
```diff
@@ -158,49 +148,17 @@ private void runGeneratedExecutable(BLangPackage executableModule, BuildContext
...
-        } catch (NoSuchMethodException e) {
-            throw createLauncherException("main method cannot be found for init class " + initClassName);
-        } catch (IllegalAccessException | IllegalArgumentException e) {
-            throw createLauncherException("invoking main method failed due to " + e.getMessage());
-        } catch (InvocationTargetException | NoSuchFieldException e) {
-            throw createLauncherException("invoking main method failed due to ", e.getCause());
-        }
-    }
-
     private String getAllClassPaths(BLangPackage executableModule, BuildContext buildContext) {
```
Comment (warunalakshitha) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java]: Shall we make this method to get the parameters instead of calculating inside method which would be more clear.

ex. getAllClassPaths(BLangPackage executableModule, boolean isSingleFileContext, String ballerinaHome)

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java [hunk 4]
```diff
@@ -158,49 +148,18 @@ private void runGeneratedExecutable(BLangPackage executableModule, BuildContext
...
-        } catch (IllegalAccessException | IllegalArgumentException e) {
-            throw createLauncherException("invoking main method failed due to " + e.getMessage());
-        } catch (InvocationTargetException | NoSuchFieldException e) {
-            throw createLauncherException("invoking main method failed due to ", e.getCause());
-        }
-    }
-
-    private String getAllClassPaths(BLangPackage executableModule, BuildContext buildContext) {
+    private String getAllClassPaths(BLangPackage executableModule, boolean isSingleFileContext,
+                                    BuildContext buildContext) {
```
Comment (warunalakshitha) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java]:
```suggestion
    private String getAllClassPaths(BLangPackage executableModule, BuildContext buildContext) {
```

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java [hunk 5]
```diff
@@ -158,49 +148,18 @@ private void runGeneratedExecutable(BLangPackage executableModule, BuildContext
...
         StringJoiner cp = new StringJoiner(File.pathSeparator);
         // Adds executable thin jar path.
         cp.add(this.executableJarPath.toString());
-        // Adds all the dependency paths.
+        if (isSingleFileContext) {
```
Comment (warunalakshitha) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java]:
```suggestion
        if (buildContext.getSourceType().equals(SINGLE_BAL_FILE)) {
```

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java [hunk 6]
```diff
@@ -138,12 +127,13 @@ private void runGeneratedExecutable(BLangPackage executableModule, BuildContext
...
         String initClassName = BFileUtil.getQualifiedClassName(executableModule.packageID.orgName.value,
                 executableModule.packageID.name.value, MODULE_INIT_CLASS_NAME);
+        boolean isSingleFileContext = buildContext.getSourceType().equals(SINGLE_BAL_FILE);
         try {
             List<String> commands = new ArrayList<>();
             commands.add("java");
             // Sets classpath with executable thin jar and all dependency jar paths.
             commands.add("-cp");
-            commands.add(getAllClassPaths(executableModule, buildContext));
+            commands.add(getAllClassPaths(executableModule, isSingleFileContext, buildContext));
```
Comment (warunalakshitha) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java]:
```suggestion
            commands.add(getAllClassPaths(executableModule, buildContext));
```

File: cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java [hunk 7]
```diff
@@ -138,12 +127,13 @@ private void runGeneratedExecutable(BLangPackage executableModule, BuildContext
 
         String initClassName = BFileUtil.getQualifiedClassName(executableModule.packageID.orgName.value,
                 executableModule.packageID.name.value, MODULE_INIT_CLASS_NAME);
+        boolean isSingleFileContext = buildContext.getSourceType().equals(SINGLE_BAL_FILE);
```
Comment (warunalakshitha) [inline cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/RunExecutableTask.java]:
```suggestion
```

**Comment by warunalakshitha** [comment]
@suganyasuven Please send a PR for 1.2.0 branch as well
