### PR TITLE
Fix issue in recursively recovering let clause

### LINKED ISSUE #36385: `BallerinaErrorHandler` reaching fail-safe for incomplete code sample
**Description:**

Below sample is reaching fail-safe  in `BallerinaErrorHandler`
```bal
var x = from var a in m = {
```
<details>
  <summary>Stack trace.(Click to expand)</summary>

```
Exception in thread "main" java.lang.AssertionError: fail safe reached
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.recover(AbstractParserErrorHandler.java:115)
	at io.ballerina.compiler.internal.parser.AbstractParser.recover(AbstractParser.java:111)
	at io.ballerina.compiler.internal.parser.BallerinaParser.recover(BallerinaParser.java:19067)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseIntermediateClause(BallerinaParser.java:11932)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseQueryExprRhs(BallerinaParser.java:11809)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTableConstructorOrQueryInternal(BallerinaParser.java:11726)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTableConstructorOrQuery(BallerinaParser.java:11716)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:5134)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:5065)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTerminalExpression(BallerinaParser.java:5059)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:5037)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:5032)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:5027)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:4958)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseVarDeclRhs(BallerinaParser.java:4628)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseVariableDecl(BallerinaParser.java:4567)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseModuleVarDecl(BallerinaParser.java:1084)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:1038)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:984)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:499)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:431)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:335)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:100)
	at io.ballerinalang.compiler.parser.test.TestParser.testParser(TestParser.java:46)
	at io.ballerinalang.compiler.parser.test.TestParser.main(TestParser.java:40)
```
</details>

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$title

Fixes #36385

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -12357,8 +12361,7 @@ private STNode parseSignedIntOrFloat() {
         return STNodeFactory.createUnaryExpressionNode(operator, literal);
     }
 
-    private boolean isSingletonTypeDescStart(SyntaxKind tokenKind) {
-        STToken nextNextToken = getNextNextToken();
+    static boolean isSingletonTypeDescStart(SyntaxKind tokenKind, STToken nextNextToken) {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:12364]:
```suggestion
    private static boolean isSingletonTypeDescStart(SyntaxKind tokenKind, STToken nextNextToken) {
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 2]
```diff
@@ -9857,7 +9857,11 @@ private STNode parsePipeToken() {
     }
 
     private boolean isTypeStartingToken(SyntaxKind nodeKind) {
-        switch (nodeKind) {
+        return isTypeStartingToken(nodeKind, getNextNextToken());
+    }
+    
+    static boolean isTypeStartingToken(SyntaxKind nextTokenKind, STToken nextNextToken) {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:9863]:
```suggestion
    private static boolean isTypeStartingToken(SyntaxKind nextTokenKind, STToken nextNextToken) {
```

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java [hunk 3]
```diff
@@ -3888,6 +3893,13 @@ private ParserRuleContext getNextRuleForKeywords(ParserRuleContext currentCtx, i
             case LET_KEYWORD:
                 parentCtx = getParentContext();
                 if (parentCtx == ParserRuleContext.QUERY_EXPRESSION) {
+                    STToken nextToken = this.tokenReader.peek(nextLookahead);
+                    STToken nextNextToken = this.tokenReader.peek(nextLookahead + 1);
+                    // This is a special case since parser quite parsing let clauses if
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java:3898]:
```suggestion
                    // This is a special case since parser quit parsing let clauses if 
```

File: compiler/ballerina-parser/src/test/resources/misc/resiliency/resiliency_source_05.bal [hunk 4]
```diff
@@ -0,0 +1 @@
+var x = from var a in m = {
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/resources/misc/resiliency/resiliency_source_05.bal:1]: Do we run this test? Seems the test  is not added to the `ResiliencyTest` class

Comment (rdulmina) [reply compiler/ballerina-parser/src/test/resources/misc/resiliency/resiliency_source_05.bal:1]: Thanx

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 2 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:9863]: This is call by `isEndOfLetVarDeclarations` which is a static method. Hence `isTypeStartingToken` has to be static

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 1 above)
Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:12364]: This is called by `isTypeStartingToken` which is a static method. Hence `isSingletonTypeDescStart` has to be static

**Review by lochana-chathura — APPROVED** [review]

**Review by gimantha — APPROVED** [review]
