### PR TITLE
Fix possible NPE in SymbolResolver

### LINKED ISSUE #35958: NullPointerException in SymbolResolver
nBallerina nightly failing with  following error

```
java.lang.NullPointerException
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.populateConfigurableVars(SymbolResolver.java:2550)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.getConfigVarSymbolsIncludingImportedModules(SymbolResolver.java:2542)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeModuleConfigurableAmbiguity(SemanticAnalyzer.java:1082)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:330)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:235)
    at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:172)
    at org.wso2.ballerinalang.compiler.tree.SimpleBLangNodeAnalyzer.visitNode(SimpleBLangNodeAnalyzer.java:201)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:282)
    at io.ballerina.projects.internal.CompilerPhaseRunner.typeCheck(CompilerPhaseRunner.java:188)
    at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:114)
    at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:438)
    at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
    at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:387)
    at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:213)
    at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:198)
    at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:114)
    at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:109)
    at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:233)
    at io.ballerina.projects.Package.getCompilation(Package.java:147)
    at io.ballerina.projects.Package.runCodeGenAndModifyPlugins(Package.java:254)
    at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:95)
    at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
    at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:248)
    at java.base/java.util.Optional.ifPresent(Optional.java:183)
    at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

https://github.com/ballerina-platform/nballerina/runs/6203970625?check_suite_focus=true

### PR DESCRIPTION
**Pull request by pcnfernando**
Fixes #35958

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 1]
```diff
@@ -2545,9 +2545,15 @@ public Set<BVarSymbol> getConfigVarSymbolsIncludingImportedModules(BPackageSymbo
 
     private void populateConfigurableVars(BPackageSymbol pkgSymbol, Set<BVarSymbol> configVars) {
         for (Scope.ScopeEntry entry : pkgSymbol.scope.entries.values()) {
-            BSymbol symbol = entry.symbol.tag == SymTag.TYPE_DEF ? entry.symbol.type.tsymbol : entry.symbol;
-            if (symbol != null && symbol.tag == SymTag.VARIABLE && Symbols.isFlagOn(symbol.flags, Flags.CONFIGURABLE)) {
-                configVars.add((BVarSymbol) symbol);
+            BSymbol symbol = entry.symbol;
+            if (symbol != null) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2549]: Was it a symbol from an improperly resolved dependency that was null here?

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2549]: Yes. It was the `os` symbol from the `file` import

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2549]: So this would just delay the failure, right? Shall we add a comment on https://github.com/ballerina-platform/ballerina-lang/issues/35385 to undo this change once that is properly fixed? If not, we may end up with quite a few unnecessary checks, right?

Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2549]: No right. This fix should be there. It's wrong anyway to access a null. ie; assuming the symbol would not be null is wrong IMO. I understand it's irrespective of the actual bug

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:2549]: Given that we are looping through the entries defined in the scope, IMO, we can assume them to be not null. For example, we don't have the null check even in `org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver#lookupSymbol` which is called frequently. I don't think we would define it in the scope if the symbol is null.
