### PR TITLE
Handle java.lang.OutOfMemoryError

### LINKED ISSUE #13159: Adding a value at the maximum allowed index causes an OOM
Consider the following program:
```ballerina
public function main(string... args) {
    int[] a = [];
    a[2147483647-9] = 10; 
}
```
The above program causes an out of memory error. 
```
[2019-01-12 01:05:10,301] ERROR {org.ballerinalang.bre.bvm.BVMScheduler} - Java heap space 
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3308)
	at org.ballerinalang.model.values.BValueArray.grow(BValueArray.java:513)
	at org.ballerinalang.model.values.BNewArray.ensureCapacity(BNewArray.java:122)
	at org.ballerinalang.model.values.BNewArray.prepareForAdd(BNewArray.java:82)
	at org.ballerinalang.model.values.BValueArray.add(BValueArray.java:210)
	at org.ballerinalang.bre.bvm.BVM.execStoreOpcodes(BVM.java:1769)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:330)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:171)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:163)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at org.ballerinalang.launcher.Main$$Lambda$8/1510067370.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
 
[2019-01-12 01:05:10,317] ERROR {org.ballerinalang.launcher.Main} - java.lang.OutOfMemoryError: Java heap space 
java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:77)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:171)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:163)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3308)
	at org.ballerinalang.model.values.BValueArray.grow(BValueArray.java:513)
	at org.ballerinalang.model.values.BNewArray.ensureCapacity(BNewArray.java:122)
	at org.ballerinalang.model.values.BNewArray.prepareForAdd(BNewArray.java:82)
	at org.ballerinalang.model.values.BValueArray.add(BValueArray.java:210)
	at org.ballerinalang.bre.bvm.BVM.execStoreOpcodes(BVM.java:1769)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:330)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runEntryFunc(BLangProgramRunner.java:74)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:171)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:163)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at org.ballerinalang.launcher.Main$$Lambda$8/1510067370.accept(Unknown Source)
	... 2 more
```

### PR DESCRIPTION
**Pull request by Nadeeshan96**
Ballerina error is now thrown instead of java.lang.OutOfMemoryError

Fixes #13159

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by Nadeeshan96** [comment]
I did not need to add a unit test because already a unit test was there to check this.
[unit test](https://github.com/ballerina-platform/ballerina-lang/blob/e835057e99bafa59ca1ca26357b2bbf5e0b06721/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java#L80)

**Comment by riyafa** [comment]
Did we try adding a test for this?

**Comment by Nadeeshan96** [comment]
> I did not need to add a unit test because already a [unit test](https://github.com/ballerina-platform/ballerina-lang/blob/e835057e99bafa59ca1ca26357b2bbf5e0b06721/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java#L80) was there to check this.

There was a previously written test for this, but I will edit that to catch the newly introduced balllerina error and error message. What had been done previously was to initialize a large array of about 16 GB to give this out of memory error without setting Xmx parameters. That had worked and also for this time it will work because it is a large value. I think the default values are sometimes given as a percentage of the available memory. Therefore it is better to set the Xmx parameters when running the test. How do I specify that in the test?

**Comment by riyafa** [comment]
can you check what is the `Xmx` parameters for the current ballerina runtime? If 16GB exceeds that value then that should be fine

**Comment by Nadeeshan96** [comment]
Okay. Thanks!

**Comment by warunalakshitha** [comment]
Any idea why code patch coverage is less than 30%

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java [hunk 1]
```diff
@@ -76,15 +75,12 @@ public void testSelfReferencingObject() {
...
     public void testRuntimeOOMError() {
-        try {
-            CompileResult compileResult = BCompileUtil.compile("test-src/jvm/runtime-oom-error.bal");
-            BRunUtil.runMain(compileResult, new String[]{});
-        } catch (Throwable e) {
-            return;
-        }
-        Assert.fail("runtime out of memory errors are not handled");
+        CompileResult compileResult = BCompileUtil.compile("test-src/jvm/runtime-oom-error.bal");
+        BRunUtil.runMain(compileResult, new String[]{});
```
Comment (riyafa) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java:83]: we can get rid of the array because the method expects a vararg:
```suggestion
        BRunUtil.runMain(compileResult);
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java [hunk 2]
```diff
@@ -76,15 +75,12 @@ public void testSelfReferencingObject() {
         BRunUtil.invoke(compileResult, "testSelfReferencingError");
     }
 
-    @Test
+    @Test(description = "Test runtime out of memory error", expectedExceptions = java.lang.RuntimeException.class,
```
[the remark this answers is not in the document]
Comment (riyafa) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java:78]: @Nadeeshan96 try rebasing and pushing again. This sometimes help in fixing the code coverage. There's some issue with it.

[the remark this answers is not in the document]
Comment (Nadeeshan96) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java:78]: I will look into this. Actually the lines #L445 - L448 were covered by this test. This may be due to the same issue I reported.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java (hunk 1 above)
Comment (Nadeeshan96) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/jvm/ErrorTest.java:83]: I will look into this.

File: tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java [hunk 3]
```diff
@@ -1323,6 +1323,42 @@ public static String runMain(CompileResult compileResult, String... args) {
         return exitDetails.consoleOutput;
     }
 
+    public static String runMainWithJavaOpts(CompileResult compileResult, String[] javaOpts, String... args) {
```
Comment (warunalakshitha) [inline tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java:1326]: Here you can change existing runMain with (CompileResult compileResult, String[] javaOpts, String... args)  and then create another method same as existing runMain and call the  the new runMAin passing empty array

**Review by warunalakshitha — COMMENTED** [review]
LGTM

File: tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java [hunk 4]
```diff
@@ -1334,10 +1342,13 @@ public static ExitDetails run(CompileResult compileResult, String... args) {
         try {
             final List<String> actualArgs = new ArrayList<>();
             actualArgs.add(0, "java");
-            actualArgs.add(1, "-cp");
+            for (int indexNum = 0; indexNum < javaOpts.size(); indexNum++) {
+                actualArgs.add(indexNum + 1, javaOpts.get(indexNum));
+            }
```
Comment (riyafa) [inline tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java:1347]: can't we call this parameter `index` instead of `indexNum`?
Shall we initialize this parameter outside of the loop. 
1. Initiate index outside of the loop as `int index = 0`
2. Use it throughout when accessing indices of `actualArgs` by incrementing it
3. change the check for the loop as `index <= javaOpts.size()`. We can very well use a while loop here

File: tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java [hunk 5]
```diff
@@ -1334,10 +1342,13 @@ public static ExitDetails run(CompileResult compileResult, String... args) {
...
+            actualArgs.add(javaOpts.size() + 1, "-cp");
             String classPath = System.getProperty("java.class.path") + ":" + getClassPath(classLoader);
-            actualArgs.add(2, classPath);
-            actualArgs.add(3, initClassName);
+            actualArgs.add(javaOpts.size() + 2, classPath);
+            actualArgs.add(javaOpts.size() + 3, initClassName);
             actualArgs.addAll(Arrays.asList(args));
```
Comment (riyafa) [inline tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java:1352]: As mentioned in the previous comment we can continue to use `index++` here, instead of messing with using `javaOpts.size()`

File: tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java (hunk 4 above)
Comment (Nadeeshan96) [reply tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java:1347]: I will look into this.

File: tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java (hunk 5 above)
Comment (Nadeeshan96) [reply tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java:1352]: I will look into this.

File: tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java [hunk 6]
```diff
@@ -1333,11 +1341,15 @@ public static ExitDetails run(CompileResult compileResult, String... args) {
 
         try {
             final List<String> actualArgs = new ArrayList<>();
-            actualArgs.add(0, "java");
-            actualArgs.add(1, "-cp");
+            int index = 0;
+            actualArgs.add(index, "java");
+            while (index++ < javaOpts.size()) {
+                actualArgs.add(index, javaOpts.get(index - 1));
+            }
```
Comment (riyafa) [inline tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java:1348]: This is good 🙂. One small change that would look nice while we are at it.
```suggestion
            int index = 0;
            actualArgs.add(index++, "java");
            while (index < javaOpts.size()) {
                actualArgs.add(index++, javaOpts.get(index - 1));
            }
```

Comment (riyafa) [reply tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java:1348]: Shall we also use a different index for `javaOpts`? Then we can bring back the for loop:
```suggestion
            int index = 0;
            actualArgs.add(index++, "java");
            for (int i = 0; i < javaOpts.size(); i++) {
                actualArgs.add(index++, javaOpts.get(i));
            }
```
This is because to allow code to be easily changed, when someone wants to add another value to the `actualArgs` before the loop.

Comment (Nadeeshan96) [reply tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/BRunUtil.java:1348]: I will look into these.

**Review by riyafa — APPROVED** [review]
