### PR TITLE
Fix NPE in PositionUtil when checking with-in-range

### LINKED ISSUE #31422: PositionUtil throws NPE
**Description:**
Try invoking the References API over the nBallerina repo, then the following exception is thrown. Due to this reason non of the references related operations are working. Such as `rename` and `find all references`.

```
java.lang.NullPointerException
	at io.ballerina.compiler.api.impl.PositionUtil.withinRange(PositionUtil.java:63)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupTopLevelNodes(NodeFinder.java:230)
	at io.ballerina.compiler.api.impl.NodeFinder.lookup(NodeFinder.java:212)
	at io.ballerina.compiler.api.impl.NodeFinder.lookupEnclosingContainer(NodeFinder.java:221)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.references(BallerinaSemanticModel.java:199)
	at io.ballerina.compiler.api.impl.BallerinaSemanticModel.references(BallerinaSemanticModel.java:178)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.lambda$getReferences$0(ReferencesUtil.java:84)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:928)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at org.ballerinalang.langserver.util.references.ReferencesUtil.getReferences(ReferencesUtil.java:82)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$references$6(BallerinaTextDocumentService.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**
sl-beta2-RC3

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #31422 

## Approach
Set the location for the finite-type node

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by dulajdilshan** [comment]
Here, we have discussed and decided to add a null check in the `PositionUtil.withInRange()` temporary

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java [hunk 1]
```diff
@@ -769,7 +769,8 @@ public void visit(BLangSimpleVarRef varRefExpr) {
             return;
         }
 
-        if (!varRefExpr.pkgAlias.value.isEmpty() && addIfSameSymbol(varRefExpr.symbol.owner, varRefExpr.pkgAlias.pos)) {
+        if (varRefExpr.pkgAlias != null && !varRefExpr.pkgAlias.value.isEmpty() &&
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ReferenceFinder.java:772]: For what sorta scenarios did `varRefExpr.pkgAlias` become `null`?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java [hunk 2]
```diff
@@ -874,6 +874,7 @@ public BLangNode transform(UnionTypeDescriptorNode unionTypeDescriptorNode) {
             unionTypeNode.memberTypeNodes.add(createTypeNode(unionElement));
         }
 
+        bLangFiniteTypeNode.setPosition(unionTypeNode.pos);
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java:877]: For now, this is ok I guess. But this should be set to the position covering the finite type elements. i.e., starting pos should be the first element's starting pos and the ending pos should be the last element's ending pos.
