### PR TITLE
Handle instantiation of abstract classes interoperably

### LINKED ISSUE #41452: [Bug]: Interop call to a Java abstract method gives `java.lang.InstantiationError`
### Description

$Subject

### Steps to Reproduce

```Ballerina
import ballerina/jballerina.java;
import ballerina/io;

public function main() {
    handle foo = getFoo();
    handle message = getMessage(foo);
    string? value = java:toString(message);
    io:println(value);
}

function getMessage(handle receiver) returns handle = @java:Method {
    name: "getMessage",
    'class: "app.app.Foo"
} external;

function getFoo() returns handle = @java:Constructor {
    'class: "app.app.Foo"
} external;
```

Java code:
`Foo.java`
```java
package app.app;

public abstract class Foo {

    public abstract String getMessage();
}
```

`FooValue.java`
```java
package app.app;

public class FooValue extends Foo {

    public String getMessage() {
        return "Hello      World!";
    }
}
```

Output:
```
error: java.lang.InstantiationError {"message":"app.app.Foo"}
        at testorg.interop_proj.0:getFoo(main.bal:18)
           testorg.interop_proj.0:main(main.bal:5)
```

### Affected Version(s)

2201.7.2
2201.8.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #41452

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java [hunk 1]
```diff
@@ -897,6 +898,10 @@ private Executable resolveMethod(Class<?> clazz, String name, Class<?>... paramT
     private List<Executable> getExecutables(Class<?> clazz, String methodName, JMethodKind kind) {
 
         if (kind == JMethodKind.CONSTRUCTOR) {
+            if (Modifier.isAbstract(clazz.getModifiers())) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:901]: Should we check interfaces?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/AbstractClass.java [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+ * software distributed under the License is distributed on an
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ * KIND, either express or implied. See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+package org.ballerinalang.nativeimpl.jvm.tests;
+
+import io.ballerina.runtime.api.values.BString;
+
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/AbstractClass.java:21]: missing Since and class java doc

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java (hunk 1 above)
Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:901]: An interface cannot contain a constructor. It will give `CONSTRUCTOR_NOT_FOUND` error when an interface is being tried to instantiate via interop calls.

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:901]: IMO for similar scenarios with interfaces, it's better to provide `INSTANTIATION_ERROR`. Since `Modifier.isAbstract(clazz.getModifiers())` returns `true` for interfaces as well, we can keep this check to cover both abstract class and interface cases.

Comment (warunalakshitha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:902]: Lets add test case if it is not there

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:902]: Added a test case with interface.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/NegativeValidationTest.java [hunk 3]
```diff
@@ -539,4 +539,21 @@ public void testMethodSignatureNotMatch17() {
...
+        BAssertUtil.validateError(
+                compileResult, 0,
+                "{ballerina/jballerina.java}INSTANTIATION_ERROR 'Cannot instantiate abstract class " +
+                        "'org.ballerinalang.nativeimpl.jvm.tests.AbstractClass''",
+                19, 1);
+        BAssertUtil.validateError(
+                compileResult, 1,
+                "{ballerina/jballerina.java}INSTANTIATION_ERROR 'Cannot instantiate interface " +
+                        "'org.ballerinalang.nativeimpl.jvm.tests.Interface''",
+                23, 1);
```
Comment (Nadeeshan96) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/NegativeValidationTest.java:557]:
```suggestion
        BAssertUtil.validateError(compileResult, 0,
                "{ballerina/jballerina.java}INSTANTIATION_ERROR 'Cannot instantiate abstract class " +
                        "'org.ballerinalang.nativeimpl.jvm.tests.AbstractClass''", 19, 1);
        BAssertUtil.validateError(compileResult, 1,
                "{ballerina/jballerina.java}INSTANTIATION_ERROR 'Cannot instantiate interface " +
                        "'org.ballerinalang.nativeimpl.jvm.tests.Interface''", 23, 1);
```

Comment (Nadeeshan96) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/basic/NegativeValidationTest.java:557]: Other changes LGTM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java [hunk 4]
```diff
@@ -897,6 +898,11 @@ private Executable resolveMethod(Class<?> clazz, String name, Class<?>... paramT
...
+                String classType = clazz.isInterface() ? "interface" : "abstract class";
+                throw new JInteropException(DiagnosticErrorCode.INSTANTIATION_ERROR,
+                        "Cannot instantiate " + classType + " '" + clazz.getName() + "'");
```
Comment (Nadeeshan96) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:904]:
```suggestion
                        "'" + clazz.getName() + "' is abstract; cannot be instantiated");
```
We can say like this for both the interfaces and abstract classes.

Comment (Nadeeshan96) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:904]: Then we can remove the line 902 also.

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:904]: Is the usual format we use in ballerina compilation errors?

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:904]: Adapting this suggestion since Java also provides the same compilation errors.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java [hunk 5]
```diff
@@ -897,6 +898,10 @@ private Executable resolveMethod(Class<?> clazz, String name, Class<?>... paramT
     private List<Executable> getExecutables(Class<?> clazz, String methodName, JMethodKind kind) {
 
         if (kind == JMethodKind.CONSTRUCTOR) {
+            if (Modifier.isAbstract(clazz.getModifiers())) {
+                throw new JInteropException(DiagnosticErrorCode.INSTANTIATION_ERROR,
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:902]: This error message is the same as the Java error. Shall we verify whether this error message format is in compliance with Ballerina?

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:902]: Modified it as `'Clazz' is abstract, and cannot be instantiated` per discussion.

**Review by Nadeeshan96 — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM
