### PR TITLE
Revamp annotation support for `NodeFinder`

### LINKED ISSUE #40668: [Bug]: The code completion for annotation field is not working for some fields
### Description

When we have a union-typed field for an annotation (union of `int` and `record`) and when we try to give it as a record value, the code completions are not working properly.

> **Note:** This tooling support is required for this new feature in the constraint package - https://github.com/ballerina-platform/module-ballerina-constraint/pull/79

### Steps to Reproduce

Check the following code in vscode:
```bal
annotation StringConstraints String on type, record field;

type ConstraintRecord record {|
    anydata value;
    string message;
|};

type StringConstraints record {|
    int|record{| *ConstraintRecord; int value; |} length?;
|};

@String {
    length : {} // enter the curly braces and try to type the field name it does not complete with the proper fields
}
type TestString string;
```

### Affected Version(s)

Ballerina SwanLake 2201.6.0

### OS, DB, other environment details and versions

Mac OS with Apple M1 chip

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #41186: [Bug]: nodeFinder.typeOf() returns null as BLangNode for annotation fields
### Description

Consider the following scenario where we're trying to get completions for annotation field,

```
annotation StringConstraints String on type, record field;
type ConstraintRecord record {|
    anydata value;
    string message;
|};

type StringConstraints record {|
    int|record{| *ConstraintRecord; int value; |} length?;
|};

@String {
    length : {<cursor>} 
}
type TestString string;
```

here, we get null as the bLangNode.

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by nipunayf**
## Purpose
An AST node does not consider the range of the annotation nodes when computing the range of the annotation-attached node. As a result, the current implementation of the `NodeFinder` cannot narrow to the correct scope when the provided range is within an annotation, as it only considers the range of the attached node (excluding the annotation nodes). Thus, the lookup API returns `null` when the given range is within an annotation.

Fixes #40668
Fixes #41186

## Approach

The PR modifies the `NodeFinder` so that it aligns with the `SymbolFinder` in considering the annotation ranges when finding the respective node.

## Samples
The PR revamps the annotation support for NodeFinder, so that respective completions are provided as shown below.

image

## Remarks
Some of annotations are yet to be supported due to the blocked issues:

#41805
#41787
#41803

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java [hunk 1]
```diff
@@ -1522,4 +1565,33 @@ private boolean isClassForService(TopLevelNode node) {
...
+            }
+        }
+
+        if (node instanceof DocumentableNode) {
+            BLangMarkdownDocumentation markdown = ((DocumentableNode) node).getMarkdownDocumentationAttachment();
+            if (markdown != null) {
+                LinkedList<BLangMarkdownParameterDocumentation> parameters = markdown.getParameters();
+                for (BLangMarkdownParameterDocumentation parameter : parameters) {
+                    if (PositionUtil.isRangeWithinNode(this.range, parameter.getPosition())) {
+                        return true;
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java:1588]: Can you please check why this is not watched by Codecov?

Comment (nipunayf) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java]: After an offline discussion, we realized that `NodeFinder` does not have a requirement to determine the type in markdown documentation. Hence, we removed this implementation from the `NodeFinder`.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/annotation_test.bal [hunk 2]
```diff
@@ -0,0 +1,297 @@
...
+
+// var fnPointer = function() {};
+
+// function testFunctionPointer() {
+//     @CustomAnnotation {
+//         info: {},
+//         doc: {}
+//     }
+//     fnPointer();
+// }
```
Comment (dulajdilshan) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/annotation_test.bal:279]: commented?

Comment (dulajdilshan) [reply tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/annotation_test.bal:279]: If this breaks the other test, that's okay to keep this comment. But, if this is because we are waiting for a fix to a test case and not breaking a test, it's okay to make it uncommented since we have anyway commenting the java test case.

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/annotation_test.bal [hunk 3]
```diff
@@ -0,0 +1,297 @@
...
+    doc: {}
+}
+service / on new TestClass() {
+    @CustomAnnotation {
+        info: {},
+        doc: {}
+    }
+    remote function name() {
+
+    }
```
Comment (dulajdilshan) [inline tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/annotation_test.bal:114]:
```suggestion
    remote function name() {
    }
```

If we don't want a new line within the function body block, we can remove it. Please check other places too

File: tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/annotation_test.bal (hunk 2 above)
Comment (dulajdilshan) [reply tests/ballerina-compiler-api-test/src/test/resources/test-src/expected-type/annotation_test.bal:267]: Ack
