### PR TITLE
Fix 'no such method' error for imported resource method

### LINKED ISSUE #42988: [Bug]: Getting a runtime error while invoking the client methods for a generated client
### Description

We have generated a client for Slack API using the Ballerina OpenAPI tool and when trying to invoke methods in the connector we are getting a runtime error.

### Steps to Reproduce

1. Publish the Slack client [1] to local ballerina central.  
2. Write a small test case using the Slack client.
    ```ballerina
    import ballerinax/slack;
    
    configurable string token = ?;
    public function main() returns error? {
        slack:Client slack = check new({ auth: {token} });
        var response = check slack->/users\.getPresence();
    }
    ```

3. Following error is thrown.
    ```sh
    error: No such method: $gen$Client&0046$get$users&0046getPresence
        at nivedhtith.test_function.0:main(main.bal:14)
    ```

[1] - https://github.com/adibmbrk/module-ballerinax-slack

### Affected Version(s)

Ballerina SL 2201.9.0

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes #42988

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java [hunk 1]
```diff
@@ -518,20 +518,18 @@ public static String generateReturnType(BType bType) {
...
+    static String cleanupObjectTypeName(String callName, BType objectType) {
+        // For attached functions from another module the call name will be in the format `objectTypeName.funcName`.
+        // We need to remove the type name.
+        if (!objectType.tsymbol.name.value.isEmpty() && callName.startsWith(objectType.tsymbol.name.value)) {
+            callName = callName.replace(objectType.tsymbol.name.value + ".", "").trim();
         }
-        
-        return typeName;
+        // For attached functions from another module where the type is an anonType, the call name will be in
+        // the format `(objectTypeName).funcName`. We need to remove the type name.
```
Comment (gabilang) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java:528]: Is this format consistent for all cases?

Comment (HindujaB) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/JvmCodeGenUtil.java:528]: yes. I checked from unit and integration tests as well. An ideal fix is to pass the type name from the compilation which will affect the BIR.
 I will add that fix and a test in the master PR.
 https://github.com/ballerina-platform/ballerina-lang/pull/42999

**Review by warunalakshitha — APPROVED** [review]
LGTM.

**Review by gabilang — APPROVED** [review]
