### PR TITLE
[Master] Fix Invalid type inferring for literal expression

### LINKED ISSUE #37750: [Bug]: Invalid type inferring for literal expression
### Description

```ballerina
type Foo4 decimal|2f;

public function main() {
    Foo4 f5 = 3;  // type of 3 is `int` but should be `float`
}
```

Even if this example fails, the type of `3` is inferred as `int`. But it should be a float.

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #38270: [Bug]: No compile error found for integer literal assignment
### Description

Consider following code.

```
2f|1 a = 2; // no compile error found
```

According to the Ballerina specification literal `2` should have type `int`. So compiler should throw a compile time error.
expected error: `incompatible types: expected '2f|1', found 'int'`

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #38498: [Bug]: Invalid error message on numeric literal assignment
### Description

Following code gives error message, `ERROR [app.bal:(3:10,3:13)] incompatible types: expected '2.0d', found 'float'`

```
2.0d a = 3.0; // ERROR [app.bal:(3:10,3:13)] incompatible types: expected '2.0d', found 'float'
```
But according to the spec the the type of the `3.0` is decimal. So the correct error message should be `ERROR [app.bal:(3:10,3:13)] incompatible types: expected '2.0d', found 'decimal'`

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #38499: [Bug]:  No compile time error for numeric literal assignment
### Description

Following code doesn't give any compile time error.

```
type A 4d|3.0;

A a = 4;
```
According to the spec, the type of the `4` is float.
So there should be a compile time error for above code.

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by SasinduDilshara**
Fixes #37750 
Fixes #38270
Fixes #38498
Fixes #38499

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -534,23 +534,45 @@ private BType getFiniteTypeMatchWithIntLiteral(BLangLiteral literalExpr, BFinite
...
+            BType type = symTable.getTypeFromTag(tag);
+            for (BLangExpression memType : finiteType.getValueSpace()) {
+                if (memType.getBType().tag == tag) {
+                    matchingType = type;
+                    break;
+                }
+            }
+
+            if (matchingType != null) {
+                break;
```
Comment (ushirask) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:569]: We can move the loops to a helper function and return instead of breaking to avoid this check.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -534,23 +534,45 @@ private BType getFiniteTypeMatchWithIntLiteral(BLangLiteral literalExpr, BFinite
...
+            }
+        }
+
+        if (matchingType != null && matchingType != symTable.semanticError && matchingType != symTable.noType) {
+            return matchingType;
+        }
         return symTable.intType;
```
Comment (ushirask) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:576]:
```suggestion
        if (matchingType == null || matchingType == symTable.semanticError || matchingType == symTable.noType) {
            return symTable.intType;
        }
        return  matchingType;
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -888,6 +939,27 @@ private BType getTypeMatchingFloatOrDecimal(BType finiteType, List<BType> member
...
+                if (matchingType != null) {
+                    break;
+                }
+            }
+        }
+
+        if (matchingType != null && matchingType != symTable.semanticError && matchingType != symTable.noType) {
+            return matchingType;
+        }
         return symTable.intType;
```
Comment (ushirask) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:963]:
```suggestion
        if (matchingType == null || matchingType == symTable.semanticError || matchingType == symTable.noType) {
            return symTable.intType;
        }
        return matchingType;
```

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal [hunk 4]
```diff
@@ -668,18 +668,12 @@ function testFiniteTypeInUnionAsComplexFiniteTypes_4() returns boolean {
 }
 
 function testFiniteTypeInUnionAsComplexFiniteTypes_5() returns boolean {
-    FooBarOneTwoBoolean f = 1;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal:671]: For

```ballerina
type FooBarOneTwoBoolean "foo"|"bar"|1|2.0|boolean;

function fn() {
    FooBarOneTwoBoolean _ = 1;
}
```
an error is logged

```
incompatible types: expected 'FooBarOneTwoBoolean', found 'float'
```

This is not correct. The type of `1` here is `int`, so it will be compatible.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal [hunk 5]
```diff
@@ -140,3 +140,34 @@ function assignTableCtrToIncompatibleType() {
...
+
+function assignCustomTypeToFloat() {
+    Foo _ = 3; // error: incompatible types: expected 'Foo', found 'float'
+    Foo _ = 2;
+}
+
+type Foo2 decimal|3d|1|5d|3f|4d|2f|7d|6;
+
+function assignCustomTypeToFloat2() {
+    Foo2 _ = 1; // error: incompatible types: expected 'Foo2', found 'float'
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal:154]: Why is this `float`?

**Review by MaryamZi — CHANGES_REQUESTED** [review]
I don't think the fix is correct. Please check the comments on the test changes.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal (hunk 5 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal:154]: Will fix it

**Comment by SasinduDilshara** [comment]
> I don't think the fix is correct. Please check the comments on the test changes.

will check. Thanks.

**Comment by KavinduZoysa** [comment]
I think you can pass the `compatibleType` into this function https://github.com/ballerina-platform/ballerina-lang/blob/4c29c699793761cd1a183efc207988dccbea7d35/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L634 and we can return `compatibleType` at this point https://github.com/ballerina-platform/ballerina-lang/blob/4c29c699793761cd1a183efc207988dccbea7d35/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L556

**Comment by SasinduDilshara** [comment]
> I don't think the fix is correct. Please check the comments on the test changes.

Updated the PR. Please check.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java [hunk 6]
```diff
@@ -117,7 +117,7 @@ public void testNegative() {
         BAssertUtil.validateError(compileResult, index++, "incompatible types: expected 'IntTypeWithoutType', " +
                 "found 'int'", 183, 28);
         BAssertUtil.validateError(compileResult, index++, "incompatible types: expected 'ByteTypeWithType', " +
-                "found 'int'", 194, 26);
+                "found 'byte'", 194, 26);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java:120]: I'm not sure if this correct. Types of numeric literals at the moment (without singleton types) are int, float, or decimal.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal [hunk 7]
```diff
@@ -152,3 +152,41 @@ function testOptionalFieldAssignment() {
...
+
+function assignCustomTypeToFloat2() {
+    Foo2 _ = 1;
+    Foo2 _ = 2; // error: incompatible types: expected 'Foo2', found 'int'
+    Foo2 _ = 3; // error: incompatible types: expected 'Foo2', found 'int'
+    Foo2 _ = 4; // error: incompatible types: expected 'Foo2', found 'int'
+    Foo2 _ = 5; // error: incompatible types: expected 'Foo2', found 'int'
+    Foo2 _ = 6;
+    Foo2 _ = 7; // error: incompatible types: expected 'Foo2', found 'int'
+    Foo2 _ = 7.1;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal:173]: This should also result in an error?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java (hunk 6 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/constant/SimpleConstantNegativeTest.java]: Updated. 424163fb2d7a81b614d6440d153fe0035b34b6e3

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal (hunk 7 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/assign/assign-stmt-negative.bal]: Updated.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/numeric_literal_assignment_negative.bal [hunk 8]
```diff
@@ -0,0 +1,441 @@
...
+type Bar22 2f|2.1;
+type Bar23 3.0|1;
+type Bar24 3.0|byte;
+type Bar25 3.0|2.1;
+type Bar26 1|byte;
+type Bar27 1|2.1;
+type Bar28 byte|2.1;
+
+function test() {
+    Bar1 _ = 8.0;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/numeric_literal_assignment_negative.bal:130]: Do all of these have to be tests with separate type definitions? IMO, we can have a few like this and for the others use in-line unions so that's easier to figure out the scenario being tested.

E.g.,
```
decimal|4d _ = 8.0;
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/numeric_literal_assignment_negative.bal [hunk 9]
```diff
@@ -0,0 +1,441 @@
...
+// specific language governing permissions and limitations
+// under the License.
+
+type Foo decimal|2f;
+type Foo2 decimal|3d|1|5d|3f|4d|2f|7d|6;
+type Foo3 decimal|5d|3f|4d|2f|7d;
+type Foo4 decimal|5d|4d|7d;
+type Foo5 decimal|4d|2f|3.0|2.1|1;
+
+function assignCustomTypeToFloat() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/numeric_literal_assignment_negative.bal:23]: Is this name valid?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/numeric_literal_assignment.bal [hunk 10]
```diff
@@ -123,9 +123,9 @@ function testFloatLiteralAsDecimalInUnion() returns boolean {
 }
 
 function testFloatLiteralAsDecimalInUnion_2() returns boolean {
-    Bar|decimal y = 123.0;
-    decimal dec = 123.0;
-    return y is decimal && dec == y;
+    Bar|decimal y = 12.0;
+    float dec = 12.0;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/literals/numeric_literal_assignment.bal:127]: The name of the function is `testFloatLiteralAsDecimalInUnion_2`. Does this logic still match that?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 11]
```diff
@@ -578,10 +585,18 @@ private BType silentIntTypeCheck(BLangLiteral literalExpr, Object literalValue,
     private BType silentCompatibleLiteralTypeCheck(BFiniteType finiteType, BLangLiteral literalExpr,
                                                       Object literalValue, AnalyzerData data) {
         BType resIntType = symTable.semanticError;
+        List<BType> compatibleTypes = new ArrayList<>();
         for (BLangExpression valueExpr : finiteType.getValueSpace()) {
             resIntType = silentIntTypeCheck(literalExpr, literalValue, valueExpr.getBType(), data);
             if (resIntType != symTable.semanticError) {
-                return resIntType;
+                compatibleTypes.add(resIntType);
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:592]: Can we confirm that `resIntType` is not always a referenced type?

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:592]: `resIntType` is a type of a integer literal. So it can be either `byte`, `decimal`, `float` and `int`

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:592]: Shall we rename the variable? Kinda implies an int type.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:592]: I think the name is ok. It is the type of the integer. wdyt?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:592]: It is the type of the integer literal, not integer.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Updated c9505a5002babe8ddffca64eb5b46dcb9a7eca05

**Comment by pcnfernando** [comment]
@SasinduDilshara can you bring this to buldable state

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 12]
```diff
@@ -543,29 +544,35 @@ private BType getFiniteTypeMatchWithIntType(BLangLiteral literalExpr, BFiniteTyp
...
         // Handle out of range ints
         if (literalValue instanceof Double) {
             return symTable.floatType;
         }
         if (literalValue instanceof String) {
             return symTable.decimalType;
         }
-        return symTable.intType;
+        if (compatibleType.tag == TypeTags.BYTE) {
+            return symTable.intType;
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:573]: Can you please add a test to cover this

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 13]
```diff
@@ -588,15 +595,23 @@ private BType silentIntTypeCheck(BLangLiteral literalExpr, Object literalValue,
...
-                return resIntType;
+            resIntegerLiteralType = silentIntTypeCheck(literalExpr, literalValue, valueExpr.getBType(), data);
+            if (resIntegerLiteralType != symTable.semanticError) {
+                compatibleTypes.add(resIntegerLiteralType);
             }
         }
-        return resIntType;
+        for (int i = TypeTags.INT; i <= TypeTags.DECIMAL; i++) {
+            for (BType type: compatibleTypes) {
+                if (type.tag == i) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:609]: Shouldn't you unwrap type references here as well?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/literals/NumericLiteralNegativeTest.java [hunk 14]
```diff
@@ -0,0 +1,126 @@
+/*
+ * Copyright (c) 2022, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (LakshanWeerasinghe) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/literals/NumericLiteralNegativeTest.java:2]:
```suggestion
 * Copyright (c) 2023, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```

Comment (LakshanWeerasinghe) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/literals/NumericLiteralNegativeTest.java:2]: Ditto.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 13 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:609]: compatible types contains int, decimal and float.
I think we don't need to unwrap.
Will check

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 12 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:573]: Added in 66880340d6b009c02dad9a84ccedd32a43447f17

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/literals/NumericLiteralNegativeTest.java (hunk 14 above)
Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/literals/NumericLiteralNegativeTest.java]: 66880340d6b009c02dad9a84ccedd32a43447f17

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 15]
```diff
@@ -921,6 +953,9 @@ private BType getTypeMatchingFloatOrDecimal(BType finiteType, List<BType> member
                 }
             }
         }
+        if (finiteType != symTable.semanticError) {
```
[the remark this answers is not in the document]
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: 66880340d6b009c02dad9a84ccedd32a43447f17

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 13 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: 66880340d6b009c02dad9a84ccedd32a43447f17

**Review by LakshanWeerasinghe — APPROVED** [review]

**Review by pcnfernando — APPROVED** [review]
