### PR TITLE
Fix map<json> map access negative cases

### LINKED ISSUE #33294: Runtime crashes when trying to access missing key in `map<map<json>>`
**Description:**
$title. It works properly for `json`.

**Steps to reproduce:**
```ballerina
import ballerina/io;

map<map<json>> x4 = {};

public function main() {
    io:println(x4.__.__);
}
```
Output:
```
Running executable

[2021-10-19 18:06:20,799] SEVERE {b7a.log.crash} - class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.MapValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.MapValue are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.MapValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.MapValue are in unnamed module of loader 'app')
        at a.main(a.bal:6)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:608)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:333)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:301)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
**Affected Versions:**
Swan Lake Beta 3

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes #33294 

## Approach
Since `map<json>` is represented as `MapValue`, it gives a CCE when the map access returns an error value. This PR fixes it by changing the temperory variable type to `map<json>|error`

## Samples
```ballerina
public function main() {
    map<map<json>> x = {};
    json|error result = x.__.__;
}
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -9545,7 +9545,7 @@ private void handleSafeNavigation(BLangAccessExpression accessExpr, BType type,
 
         if (!(accessExpr.errorSafeNavigation || accessExpr.nilSafeNavigation)) {
             BType originalType = accessExpr.originalType;
-            if (TypeTags.isXMLTypeTag(originalType.tag)) {
+            if (TypeTags.isXMLTypeTag(originalType.tag) || isMapJson(originalType)) {
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:9548]: The other types (object & records) supports field access expression don't need to be checked here. Because, the access keys are validated with their fields at compile time, so that it will never return a runtime error.

**Review by warunalakshitha — APPROVED** [review]
LGTM
