### PR TITLE
Fix goto definition in object reference types

### LINKED ISSUE #17370: [IntelliJ Plugin] Type guard suggestion adds invalid characters
**Description:**

$title. Note the typeguard for `payload`

```ballerina
import ballerina/io;
import ballerina/http;

listener http:Listener airlineEP = new(9091);

const string ECONOMY = "Economy";
const string BUSINESS = "Business";
const string FIRST = "First";

@http:ServiceConfig {
    basePath: "/airline"
}
service airlineReservationService on airlineEP {

    @http:ResourceConfig {
        methods: ["POST"],
        path: "/reserve",
        consumes: ["application/json"],
        produces: ["application/json"]
    }
   resource function reserveTicket(http:Caller caller, http:Request request) {
       http:Response response = new;
       json reqPayload = {};

       var payload = request.getJsonPayload();
       if (payload is error) {

} else {
   ${20}
}

   }
}
```

**Affected Versions:**
0.992.0-m2 (alpha)
IntelliJ IDEA 2019.1.3 (Community Edition)

### LINKED ISSUE #17473: Import statements are added in invalid places when using language server code completion
**Description:**
$subject.

**Steps to reproduce:**
1. Open a stream based ballerina file. (i.e. `join_multiple_streams.bal` BBE file).
2. Add a code snippet which requires a additional package import, at the end of the files. (i.e grpc service snippet)
3. You can see the import statement being add in the middle of the file.

**Affected Versions:**
1.0.0-alpha

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #17477: Go to Definition, Rename, find all references and hover not working for Object type references
**Description:**
Go to Definition, Rename, find all references and hover not working for Object type references

**Steps to reproduce:**
```
# Description
public type Person abstract object {
};

type Student object {
    *Person;
};
```

**Affected Versions:**
1.0.0-alpha at least

### PR DESCRIPTION
**Pull request by nadeeshaan**
Fixes #17477 
Fixes #17370 
Fixes #17473 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/SymbolReferenceFindingVisitor.java [hunk 1]
```diff
@@ -572,10 +573,11 @@ public void visit(BLangUnionTypeNode unionTypeNode) {
 
     @Override
     public void visit(BLangObjectTypeNode objectTypeNode) {
-        super.visit(objectTypeNode);
+        objectTypeNode.typeRefs.forEach(this::addObjectReferenceType);
         objectTypeNode.fields.forEach(this::acceptNode);
         objectTypeNode.functions.forEach(this::acceptNode);
         this.acceptNode(objectTypeNode.initFunction);
+
```
Comment (NipunaMarcus) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/references/SymbolReferenceFindingVisitor.java]: unnecessary new line ...
