### PR TITLE
Fix unreachable code issue in match-stmt

### LINKED ISSUE #25813: Dataflow analysis doesn't seem to happen for `match`
**Description:**
$title, with the latest changes.

Marking this as a blocker since this used to work previously (including slp3). 

**Steps to reproduce:**
```ballerina
function foo(int i) returns string {
    string s;

    match i {
        1 => {
            s = "ONE";
        }
        2 => {
            s = "TWO";
        }
        _ => {
            s = "OTHER";
        }
    }
    return s;
}
```

This results in a compilation error
```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
error: .::qwe.bal:15:12: variable 's' is not initialized
```

**Affected Versions:**
Current master.

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose
$subject. Changed the DataFlowAnalyser in order to fix the issue.
Fixes #25813 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java [hunk 1]
```diff
@@ -569,9 +571,53 @@ public void visit(BLangIf ifNode) {
...
+        this.uninitializedVars = uninitVars;
+    }
+
+    @Override
+    public void visit(BLangMatchClause matchClause) {
+
+        analyzeNode(matchClause.blockStmt, env);
+    }
+
+    private boolean isLastPatternContainsIn(BLangMatchClause matchClause) {
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/DataflowAnalyzer.java:613]: I think this should be named is last clause

**Review by rdhananjaya — APPROVED** [review]
