### PR TITLE
Fix init issue in type referenced record fields

### LINKED ISSUE #11883: Default values are not being set for fields from a referenced record type
**Description:**
```ballerina
public type A record {
    int id = 0;
    string name = "";
    !...
};

public type B record {
    string address = "";
    *A;
    !...
};
```
Here `id` and `name` fields of the record type B are not being set to the default values.

### LINKED ISSUE #11888: Getting ambiguous type compilation error when a passing a record as a union type function argument
**Description:**
```ballerina
public type InMemoryConfig record {
    string name = "";
    string username = "";
    string password = "";
    sql:PoolOptions poolOptions = {};
    map dbOptions = {};
    !...
};

public type ServerModeConfig record {
    string host = "";
    int port = 9092;
    *InMemoryConfig;
    !...
};

public type EmbeddedModeConfig record {
    string path = "";
    *InMemoryConfig;
    !...
};
public function __init(InMemoryConfig|ServerModeConfig|EmbeddedModeConfig c) {
        //Impl
}
```
When passing `InMemoryConfig` record, getting the following error.
```bash
 ambiguous type 'ballerina/h2:InMemoryConfig|ballerina/h2:ServerModeConfig|ballerina/h2:EmbeddedModeConfig'
```

### PR DESCRIPTION
**Pull request by pubudu91**

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -464,6 +463,12 @@ public void visit(BLangRecordLiteral recordLiteral) {
     }
 
     private boolean isRecordLiteralCompatible(BRecordType bRecordType, BLangRecordLiteral recordLiteral) {
+        if (recordLiteral.getKeyValuePairs().isEmpty()) {
```
Comment (SupunS) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Do we need this check here. AFAIK we do a similar check at the `checkMissingRequiredFields(..)` method..
