### PR TITLE
Fix NPE thrown when the required configs not provided for metrics

### LINKED ISSUE #29754: Error initialising Counter
**Description:**
Failing to initialize `observe:Counter`.

**Steps to reproduce:**
Run the following

```ballerina
import ballerina/http;
import ballerina/log;
import ballerina/observe;
import ballerinax/prometheus as _;

observe:Counter globalCounter = new ("total_orders", desc = "Total quantity required");

service /onlineStoreService on new http:Listener(9090) {
    
    resource function get makeOrder(http:Caller caller, http:Request req) {
        globalCounter.increment();

        http:Response res = new;

        res.setPayload("Order Processed!");

        var result = caller->respond(res);
        if (result is error) {
            log:printError("Error sending response", err = result.toString());
        }
    }
}
```

[2021-03-31 18:13:33,671] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at io.ballerina.runtime.observability.metrics.Counter$Builder.build(Counter.java:84)
	at org.ballerinalang.observe.nativeimpl.CounterInitialize.initialize(CounterInitialize.java:35)
	at ballerina.observe.0_9_0.natives.externCounterInit(natives.bal:163)
	at ballerina.observe.0_9_0.$value$Counter.init(natives.bal:123)
	at ballerina.observe.0_9_0.$value$Counter.call(natives.bal)
	at ballerina.observe.0_9_0.$value$Counter.$init$(natives.bal:98)
	at ballerina.observe.0_9_0.$value$Counter.call(natives.bal)
	at elondombonze.hierar.0_1_0.hierar.$gen$elondombonze$0047hierar$00580$00461$00460$0046$0060init$00620(hierar:6)
	at elondombonze.hierar.0_1_0.$_init.$gen$$0046$0060init$0062(hierar:0)
	at elondombonze.hierar.0_1_0.$_init.$moduleInit(hierar)
	at elondombonze.hierar.0_1_0.$_init.$lambda$$moduleInit$(hierar)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Unknown Source)

**Affected Versions:**
slalpha3

**OS, DB, other environment details and versions:**
Windows 10 Pro for Workstations

### PR DESCRIPTION
**Pull request by madushajg**
## Purpose
Fix NPE thrown when the required configs not provided for metrics

Fixes #29754

## Approach
Introduce a no-op metrics registry as the default metrics registry

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/metrics/MetricRegistry.java [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
+ * Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (madushajg) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/metrics/MetricRegistry.java:2]: This `MetricRegistry.java` file was added as a new file with 85333883d3c12edcc4521ded0aab3c7c533410e5. Also IDE detects this as a new file.

Screenshot 2021-06-14 at 19 01 44

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/metrics/MetricRegistryImpl.java [hunk 2]
```diff
@@ -0,0 +1,162 @@
+/*
+ * Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
+ *
```
Comment (madushajg) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/observability/metrics/MetricRegistryImpl.java:3]: To preserve the old commits, the old `MetricRegistry.java` was renamed to `MetricRegistryImpl.java` with ba1f8a769e58bd6c370eacc2f90dd45019a7325e.  Here this detected as a new file. However, the IDE is displaying the old commits.

Screenshot 2021-06-14 at 19 01 55

**Review by nadundesilva — APPROVED** [review]
LGTM
