### PR TITLE
Fix inconsistencies with defaultable cli args

### LINKED ISSUE #39586: [Bug]: Main args with default values retrieved for numerical `0`
### Description

$subject

### Steps to Reproduce

```ballerina
import ballerina/io;

public function main(int a = 3) {
    io:println(a);
}
```
When running the following
```
bal run -- 0
```
This prints `3` which is the default value. This is because we provide `0` if a CLI argument is not provided, and it retrieves the default value `3`. 

### Affected Version(s)

current master

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/39563

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #39586

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/cli/OperandTest.java [hunk 1]
```diff
@@ -31,12 +31,14 @@ public class OperandTest {
...
-//                {"operand_default_only", new String[0]}, {"operand_int_and_default", new String[]{"1"}},
-//                {"operand_int_and_default", new String[]{"2", "John"}},
+                {"operand_default_only", new String[0]}, {"operand_int_and_default", new String[]{"1"}},
+                {"operand_int_and_default", new String[]{"2", "John"}},
                 {"operand_rest_param_only", new String[]{"Riyafa", "John"}},
                 {"operand_rest_param_without_value", new String[0]},
                 {"operand_rest_param_without_value", new String[0]}, {"option_defaultable_optional_with_arg",
-                new String[]{"--name=Riyafa", "--score=100", "--height=5.6"}}};
+                new String[]{"--name=Riyafa", "--score=100", "--height=5.6"}},
+                {"operands_with_defaultable_values", new String[]{"10", "12", "0", " ", "0", "0", "0"}}
```
Comment (HindujaB) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/cli/OperandTest.java:40]: Shall we pass `0.0` for float value and `""` for string value without space?

**Review by HindujaB — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM
