### PR TITLE
Change the regex used to identify module ids in Ballerina Shell

### LINKED ISSUE #29366: Ballerina Shell does not work with external modules that have alphanumeric characters in the version
**Description:**
For example, importing `ballerina/http` does not work. The reason being `http` module containing `-alphaX` substring which is not captured by the regex used in Ballerina Shell to detect imports.

**Steps to reproduce:**
Import http module and use it as,
```ballerina
=$ import ballerina/http
=$ http:Client|http:ClientError clientEndpoint = new("https://my-simple-backend.com");
``` 
After this, the Shell goes into an error state

**Affected Versions:**
Alpha3, after #28746

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#29109

**Suggested Labels (optional):**
`Area/Shell`

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by kdsuneraavinash**
## Purpose

Fixes #29366 

## Approach
Change the regex to identify module ids with alphanumeric characters

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ImportsManager.java [hunk 1]
```diff
@@ -51,7 +51,8 @@
     // Regex patterns
     private static final Pattern CLONEABLE_SIGNATURE_PATTERN =
             Pattern.compile("readonly\\|xml<[^>]*>\\|\\(Cloneable\\)\\[]\\|map<Cloneable>\\|table<map<Cloneable>>");
-    private static final Pattern FULLY_QUALIFIED_MODULE_ID_PATTERN = Pattern.compile("([\\w]+)/([\\w.]+):([\\d.]+):");
+    private static final Pattern FULLY_QUALIFIED_MODULE_ID_PATTERN =
```
Comment (MaryamZi) [inline ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ImportsManager.java:54]: Shall we create an issue to track adding tests with the kind of version that caused issues?

Comment (kdsuneraavinash) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ImportsManager.java:54]: There is an issue #28038 to test external library support. or shall I create another issue?

Comment (MaryamZi) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ImportsManager.java:54]: Let's create another one. This is something we can try and test by introducing our own project, right?

Comment (kdsuneraavinash) [reply ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/classload/ImportsManager.java:54]: Done #29649

**Review by MaryamZi — APPROVED** [review]
