### PR TITLE
Fix parser doesn't support empy list binding pattern

### LINKED ISSUE #24648: Parser doesn't support empy list binding pattern.
**Description:**
$Subject

**Suggested Labels (optional):**

- Component/Parser
- Type/Bug

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose

- $Subject
- Enable ExprBodiedFunctionTest.testSyntaxErrors 

Fixes #24648

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -14253,6 +14253,14 @@ private STNode parseListBindingPattern() {
     }
 
     private STNode parseListBindingPattern(STNode openBracket, List<STNode> bindingPatternsList) {
+        if (isEndOfListBindingPattern(peek().kind) && bindingPatternsList.size() == 0) {
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:14256]: Do we need to check whether the size is zero?

Comment (rdulmina) [reply compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java:14256]: Yes, this block is only to handle empty case. and there are some cases in which the list is not empty and the next token is `close_bracket' which will produce the wrong results if we don't use that check.
