### PR TITLE
[IntelliJ Plugin] Add code formatting fix

### LINKED ISSUE #12143: Code formatting issue in intelliJ IDEA
**Description:**
 If there's any grammar violation presents in a ballerina file, horizontal formatting for the whole file will break as follows in ballerina IntelliJ plugin.

**Before:**
screenshot from 2018-11-30 19-09-19

**After:**
screenshot from 2018-11-30 19-09-44

**Steps to reproduce:**
Refer the above sample code snippet.

**Affected Versions:**
0.983.0 and below.

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by NipunaRanasinghe**
## Purpose
This PR adds improvements for the code formating so that formatting is preserved even when the plugin grammar rules are violated.

Fixes #12143.

### CODE REVIEW

File: tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/formatter/BallerinaFormattingModelBuilder.java [hunk 1]
```diff
@@ -261,13 +269,52 @@
...
+                    return new LinkedList<>();
+                }
+            };
+            return FormattingModelProvider
+                    .createFormattingModelForPsiFile(element.getContainingFile(), rootBlock, settings);
+        }
+    }
+
+    // Checks whether the PSI tree for the file is properly generated.
+    private static boolean grammarViolated(ASTNode rootNode) {
```
Comment (Shan1024) [inline tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/formatter/BallerinaFormattingModelBuilder.java]: Shall we rename to `isGrammarViolated`.

Comment (NipunaRanasinghe) [reply tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/formatter/BallerinaFormattingModelBuilder.java]: Changed
