### PR TITLE
Fix NPE for filePath in Syntax Tree

### LINKED ISSUE #25925: File-path in LineRange can be null
**Description:**
Root cause: https://github.com/ballerina-platform/ballerina-lang/blob/ee83d258a4a7e95d1e397dcc334793e9fe4c9603/compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/SyntaxTree.java#L46

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #25925 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/WorkspaceDocument.java [hunk 1]
```diff
@@ -72,14 +78,24 @@ public String getContent() {
...
     public void setIncrementContent(String content) {
         this.content = content;
         // TODO: Fix this, each time creates a new tree
-        setTree(SyntaxTree.from(TextDocuments.from(this.content)));
+        Path namePath = this.path.getFileName();
+        if (namePath != null) {
+            setTree(SyntaxTree.from(TextDocuments.from(this.content), namePath.toString()));
+        } else {
+            setTree(SyntaxTree.from(TextDocuments.from(this.content)));
+        }
```
Comment (SupunS) [inline language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/WorkspaceDocument.java:98]: This code seems to be duplicate. Extract this to a separate method, and use in all places.

**Review by SupunS — APPROVED** [review]

File: language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/WorkspaceDocument.java (hunk 1 above)
Comment (dulajdilshan) [reply language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/WorkspaceDocument.java:98]: Cool
