### PR TITLE
Fix completion issues and improve completion item sorting

### LINKED ISSUE #31727: Path parameters not suggested at initializer context
**Description:**
```
service / on new http:Listener(8090) {
    resource function get [int abc](http:Caller caller) returns error? {
        int test = <cursor>
    }
}

```

In the given cursor position, `abc` is not suggested

**Affected Versions:**
swanlake beta2 at least

### LINKED ISSUE #31733: Completions are failing with No Such Element Exception
**Description:**
Completions fail with No Such Element Exception for the following source snippet.

```
function testFunction() {
    
    function hello;
    <cursor>
}
```

**Affected Versions:**
Swanlake beta2 at least

### LINKED ISSUE #31755: XML and String template expressions' completions are not intelligent enough
**Description:**
$title
1. Currently we suggest action keywords and similar false positives.
2. Module contents are not suggested
3. XML template expressions does not suggest the xml variables and sort accordingly.

**Affected Versions:**
SwanLake Beta2 at least

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose
Fixes #31755
Fixes #31727
Fixes #31733 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java [hunk 1]
```diff
@@ -43,6 +43,7 @@
 import io.ballerina.compiler.syntax.tree.IdentifierToken;
 import io.ballerina.compiler.syntax.tree.ImplicitNewExpressionNode;
 import io.ballerina.compiler.syntax.tree.IndexedExpressionNode;
+import io.ballerina.compiler.syntax.tree.InterpolationNode;
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java:46]: This class has not been used. Shall we remove this?

**Review by IMS94 — DISMISSED** [review]

**Review by IMS94 — APPROVED** [review]

**Review by malinthar — APPROVED** [review]
LGTM
