### PR TITLE
Handle ProjectAPI package resolution errors in LS

### LINKED ISSUE #37092: Suggestions are not working in Windows10 + WSL2
**Description:**
Module level and block level suggestions are not working. Suggestions are only coming when I type an import alias(eg: ```io:```)

image (1)
image

image (2)

But for the same project and versions, it works in Mac OSX.

Screenshot 2022-07-21 at 12 01 48

**Steps to reproduce:**

**Affected Versions:**
Ballerina 2201.1.1 (Swan Lake Update 1)
Language specification 2022R2
Update Tool 1.3.9
VSCode Extension 3.0.2

**OS, DB, other environment details and versions:**
Windows 10 and WSL2 (Ubuntu)

**Related Issues (optional):**

**Suggested Labels (optional):**

Priority/Blocker
Team/LanguageServer

**Suggested Assignees (optional):**

### LINKED ISSUE #37147: No VSCode suggestion if one of the modules breaks
**Description:**
```
io.ballerina.projects.exceptions.InvalidBalaException: invalid bala file: /Users/chamil/.ballerina/repositories/central.ballerina.io/bala/ballerinax/mssql.driver/1.2.0/java11
    at io.ballerina.projects.internal.ProjectFiles.validateBalaProjectPath(ProjectFiles.java:286)
    at io.ballerina.projects.internal.PackageConfigCreator.createBalaProjectConfig(PackageConfigCreator.java:95)
    at io.ballerina.projects.bala.BalaProject.loadProject(BalaProject.java:55)
    at io.ballerina.projects.internal.repositories.FileSystemRepository.getPackage(FileSystemRepository.java:111)
    at io.ballerina.projects.internal.repositories.RemotePackageRepository.getPackage(RemotePackageRepository.java:92)
    at org.ballerinalang.langserver.LSPackageLoader.lambda$getPackagesFromRepository$6(LSPackageLoader.java:161)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
    at org.ballerinalang.langserver.LSPackageLoader.lambda$getPackagesFromRepository$7(LSPackageLoader.java:148)
    at java.base/java.util.HashMap.forEach(HashMap.java:1336)
    at org.ballerinalang.langserver.LSPackageLoader.getPackagesFromRepository(LSPackageLoader.java:144)
    at org.ballerinalang.langserver.LSPackageLoader.getRemoteRepoPackages(LSPackageLoader.java:92)
    at org.ballerinalang.langserver.LSPackageLoader.getAllVisiblePackages(LSPackageLoader.java:132)
    at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getModuleCompletionItems(AbstractCompletionProvider.java:332)
    at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getTypeDescContextItems(AbstractCompletionProvider.java:288)
    at org.ballerinalang.langserver.completions.providers.context.ModulePartNodeContext.getModulePartContextItems(ModulePartNodeContext.java:162)
    at org.ballerinalang.langserver.completions.providers.context.ModulePartNodeContext.getCompletions(ModulePartNodeContext.java:89)
    at org.ballerinalang.langserver.completions.providers.context.ModulePartNodeContext.getCompletions(ModulePartNodeContext.java:49)
    at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:125)
    at org.ballerinalang.langserver.completions.providers.context.ModuleVariableDeclarationNodeContext.getCompletions(ModuleVariableDeclarationNodeContext.java:105)
    at org.ballerinalang.langserver.completions.providers.context.ModuleVariableDeclarationNodeContext.getCompletions(ModuleVariableDeclarationNodeContext.java:50)
    at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:125)
    at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:81)
    at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:65)
    at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:40)
    at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:122)
    at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:147)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject

Fixes #37147 
Fixes #37092 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java [hunk 1]
```diff
@@ -150,28 +151,31 @@ private List<PackageInfo> getPackagesFromRepository(PackageRepository repository
...
+                    PackageVersion pkgVersion = PackageVersion.from(version);
+                    PackageDescriptor pkdDesc = PackageDescriptor.from(packageOrg, packageName, pkgVersion);
+                    ResolutionRequest request = ResolutionRequest.from(pkdDesc, PackageDependencyScope.DEFAULT);
+
+                    Optional<Package> repoPackage = repository.getPackage(request,
+                            ResolutionOptions.builder().setOffline(true).build());
+                    repoPackage.ifPresent(pkg -> packages.add(new PackageInfo(pkg)));
+                });
+            } catch (Throwable e) {
+                //ignore
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java:176]: Let's add an error log here, using the `LSClientLogger`

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java [hunk 2]
```diff
@@ -150,28 +151,31 @@ private List<PackageInfo> getPackagesFromRepository(PackageRepository repository
         Map<String, List<String>> packageMap = repository.getPackages();
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java:151]: Let's move this inside the try. Because we cannot trust this as well :laughing:

**Review by IMS94 — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java [hunk 3]
```diff
@@ -150,28 +151,31 @@ private List<PackageInfo> getPackagesFromRepository(PackageRepository repository
...
+                    }
+                    String nameComponent = components[0];
+                    String version = components[1];
+                    PackageOrg packageOrg = PackageOrg.from(key);
+                    PackageName packageName = PackageName.from(nameComponent);
+                    PackageVersion pkgVersion = PackageVersion.from(version);
+                    PackageDescriptor pkdDesc = PackageDescriptor.from(packageOrg, packageName, pkgVersion);
+                    ResolutionRequest request = ResolutionRequest.from(pkdDesc, PackageDependencyScope.DEFAULT);
+
+                    Optional<Package> repoPackage = repository.getPackage(request,
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java:171]: What if we wrap this part? Since this is the part that's going to fail? That way, only the erroneous packages won't be loaded. (Ignore my last comment about try if we wrap this part only)

**Review by IMS94 — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java [hunk 4]
```diff
@@ -163,15 +168,22 @@ private List<PackageInfo> getPackagesFromRepository(PackageRepository repository
...
-                repoPackage.ifPresent(pkg -> packages.add(new PackageInfo(pkg)));
+                try {
+                    PackageDescriptor pkdDesc = PackageDescriptor.from(packageOrg, packageName, pkgVersion);
+                    ResolutionRequest request = ResolutionRequest.from(pkdDesc, PackageDependencyScope.DEFAULT);
+
+                    Optional<Package> repoPackage = repository.getPackage(request,
+                            ResolutionOptions.builder().setOffline(true).build());
+                    repoPackage.ifPresent(pkg -> packages.add(new PackageInfo(pkg)));
+                } catch (Throwable e) {
+                    clientLogger.logTrace("Failed to resolve package "
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java:180]: It's better if we logged an error. But ok for now.

**Review by IMS94 — APPROVED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java (hunk 4 above)
Comment (mohanvive) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSPackageLoader.java:180]: @malinthar let's push this as a separate PR.
