### PR TITLE
Fix covariant return type issue with overridden methods

### LINKED ISSUE #20942: Compilation Error of Overloaded Java Method without parameter
**Description:**
I have defined Jedis Sentinel overloaded Java method for getResource of class JedisSentinelPool class as follow:

```
function getResource(handle receiver) returns handle = @java:Method {
    name: "getResource",
    class: "redis.clients.jedis.JedisSentinelPool"
} external;
```

When I try to run 'ballerina build --all', I got the following error

```
{ballerinax/java}OVERLOADED_METHODS message=Overloaded methods 'getResource' with '0' parameter(s) in class 'class redis.clients.jedis.JedisSentinelPool', please specify class names for each parameter with 'paramTypes' field in the annotation
```

**Steps to reproduce:**

Run "ballerina build --all"

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Kishanthan**
## Purpose
This PR will fix covariant return type issue with overridden methods

Fixes #20942

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java [hunk 1]
```diff
@@ -144,6 +150,23 @@ private JMethod resolve(JMethodRequest jMethodRequest, List<JMethod> jMethods) {
         return jMethod;
     }
 
+    private Optional<JMethod> findCovariantReturnTypeMethod(List<JMethod> jMethods) {
+
+        for (JMethod ithMethod : jMethods) {
+            for (JMethod kthMethod : jMethods) {
```
Comment (manuranga) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java:156]: here we can reduce the number of iterations by half by changing `i=1..N x k=1..N` to `i=1..N x k=i..N`

Comment (Kishanthan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/JMethodResolver.java]: Yep, updated the logic.
