### PR TITLE
Code action fixes

### LINKED ISSUE #27283: [CodeAction] Add Change Parameter Type CodeAction for incompatible types assignment
**Description:**
Add Change Parameter Type Code Action for incompatible types assignment. Suppose below incompatible types assignment.

```ballerina
1. function foo(float a) {
2.    int intVal = a;
3. }
```
In above line 2; we are getting `incompatible types` compiler error and a possible code-action would be to change the parameter 'a' type to `int` from `float`

**After execution**
```ballerina
1. function foo(int a) {
2.     int intVal = a;
3. }
```

**Affected Versions:**
2.0.0-SLP6

### LINKED ISSUE #27286: Create variable, Create Variable and Check Error code actions add duplicate imports
**Description:**
$subject

**Affected Versions:**
SLP7 at least

### LINKED ISSUE #27442: [CodeAction] Add new type-guard and add-error-check code-actions for union-type variables
**Description:**
Add code-actions to type guard and add error check, for union type variables. These code-actions will be available based on the node-type of the variable.

**Type Guard Code Action, Before Execution**
```ballerina
int|boolean a = getValue();
```

**Type Guard Code Action, After Execution**
```ballerina
int|boolean a = getValue();
if (a is int) {

} else {

}
```

**Add Error Check Code Action, Before Execution**
```ballerina
function foo() {
    boolean|int|error a = getValue();
}

function getValue() returns int|error {

}
```

**Add Error Check Code Action, After Execution**
```ballerina
function foo() returns error? {
    boolean|int a = check getValue();
}

function getValue() returns int|error {

}
```

**Affected Versions:**
2.0.0-SLP8-SNAPSHOT

### PR DESCRIPTION
**Pull request by rasika**
Fixes #27283
Fixes #27286
Fixes #27442

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java [hunk 1]
```diff
@@ -77,87 +87,47 @@ private CodeActionUtil() {
...
-            if (!isWithinStartSegment && !isWithinBody) {
-                continue;
-            }
-
-            if (member.kind() == SyntaxKind.SERVICE_DECLARATION) {
-                if (isWithinStartSegment) {
-                    // Cursor on the service
-                    return Optional.of(new ImmutablePair<>(CodeActionNodeType.SERVICE, member));
+        switch (node.kind()) {
+            case SERVICE_DECLARATION:
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java:98]: What would be the consequence if we try to depend on the node kind instance of code action node kind?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java [hunk 2]
```diff
@@ -459,7 +327,127 @@ public static PositionDetails findCursorDetails(Range range, SyntaxTree syntaxTr
             matchedSymbol = null;
         }
         matchedExprTypeSymbol = semanticModel.type(relPath, largestExpressionNode(cursorNode, range).lineRange());
-        return PositionDetailsImpl.from(matchedNode, matchedSymbol, matchedExprTypeSymbol.orElse(null));
+        return CodeActionPositionDetails.from(matchedNode, matchedSymbol, matchedExprTypeSymbol.orElse(null));
+    }
+
+    public static List<TextEdit> getTypeGuardCodeActionEdits(String varName, Range range, UnionTypeSymbol unionType,
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java:333]: Shall we add a doc comment here

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java [hunk 3]
```diff
@@ -469,17 +457,236 @@ public static PositionDetails findCursorDetails(Range range, SyntaxTree syntaxTr
...
-        Predicate<NonTerminalNode> isWithinScope =
+    public static Node largestExpressionNode(Node node, Range range) {
+        Predicate<Node> isWithinScope =
                 tNode -> tNode != null && !(tNode instanceof ExpressionStatementNode) &&
                         CommonUtil.isWithinRange(CommonUtil.toPosition(tNode.lineRange().startLine()), range) &&
                         CommonUtil.isWithinRange(CommonUtil.toPosition(tNode.lineRange().endLine()), range);
         while (isWithinScope.test(node.parent())) {
             node = node.parent();
         }
+        if (node.kind() == SyntaxKind.ASSIGNMENT_STATEMENT) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java:468]: can convert to if ladder

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java [hunk 4]
```diff
@@ -469,17 +457,236 @@ public static PositionDetails findCursorDetails(Range range, SyntaxTree syntaxTr
...
+        int cursorPosOffset = syntaxTree.textDocument().textPositionFrom(cursorPosition);
+        while (member != null) {
+            boolean isWithinStartSegment = isWithinStartCodeSegment(member, cursorPosOffset);
+            boolean isWithinBody = isWithinBody(member, cursorPosOffset);
+            if (!isWithinStartSegment && !isWithinBody) {
+                member = member.parent();
+                continue;
+            }
+
+            if (member.kind() == SyntaxKind.SERVICE_DECLARATION) {
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java:497]: Following checks are bit hard to understand. Shall we try to simplify this? There are common conditions with the same return, we can merge them as well

**Review by nadeeshaan — APPROVED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionModuleId.java [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+ * version and alias.
+ *
+ * @since 2.0.0
+ */
+public class CodeActionModuleId implements ModuleID {
+    private static final String ORG_SEPARATOR = "/";
+    private final String orgName;
+    private final String moduleName;
+    private final String version;
+    private final String alias;
```
[the remark this answers is not in the document]
Comment (rasika) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionModuleId.java:39]: Added alias to support ModuleID interface. I think we need to remove `alias` from this class since it doesn't affect the equality of the two separate imports. `equal` implementation ignores it here.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java (hunk 1 above)
Comment (rasika) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java:98]: I tried to implement it that way, issue is we cannot distinguish nodes in different contexts with node syntax-kind alone. For instance when you have a function definition syntax-kind, there's no clue whether it is a resource-function or a top-level function.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java (hunk 2 above)
Comment (rasika) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java:333]: Sure will add

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java (hunk 3 above)
Comment (rasika) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java:468]: not clear what you meant here?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java (hunk 4 above)
Comment (rasika) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionUtil.java:497]: First part checks whether it is within `start segment` of the node. `isWithinStartSegment` has separate calculations base on the node-type. We can merge only variables, imports and assignments. Others are bit different.
