### PR TITLE
Modify configurable TOML file specification

### LINKED ISSUE #27698: Change `configurable` toml file name to `Config.toml`
**Description:**
$subject

Additional :
- Add support for environment variable specifying for the file location

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$title

Fixes #27698 
Part of #27431 

## Approach

- Change file name `configuration.toml` to `Config.toml`

- Add support for environment variable to specify config file location

   While locating Config.toml for program execution, the preference is as follows :
             1.  Path is given in an environment variable (temporarily - "BAL_CONFIG_FILE")
             2.  If no environment var given then we look for Config.toml in the current working directory
             
- Change org information in TOML file to be optional

## Samples
N/A

## Remarks
This PR is depending on #27670 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java [hunk 1]
```diff
@@ -59,34 +56,34 @@
...
             return;
         }
         for (Map.Entry<Module, VariableKey[]> moduleEntry : configurationData.entrySet()) {
-            String orgName = moduleEntry.getKey().getOrg();
-            String moduleName = moduleEntry.getKey().getName();
-            TomlTableNode orgNode = orgName.equals(ANON_ORG) ? tomlNode : extractOrganizationNode(tomlNode, orgName);
-            TomlTableNode moduleNode = moduleName.equals(DEFAULT_MODULE) ? orgNode : extractModuleNode(orgNode,
-                    moduleName);
+            TomlTableNode moduleNode = retrieveModuleNode(tomlNode, moduleEntry.getKey());
+            if (moduleNode == null) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java:84]: Why can this be null? retrieveModuleNode method inside throw a exception if it null.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java [hunk 2]
```diff
@@ -156,15 +168,36 @@ private void generateMethodCall(String initClass, MethodVisitor mv,
         genReturn(mv, indexMap, futureVar);
     }
 
+    private void generateGetFilePath(ClassWriter cw) {
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/methodgen/MainMethodGen.java:171]: Can we move this to runtime package and just generate static call instead of generating the full method.

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java [hunk 3]
```diff
@@ -98,6 +95,21 @@ public static void populateConfigMap(Map<Module, VariableKey[]> configurationDat
...
+    private static TomlTableNode retrieveModuleNode(TomlTableNode tomlNode, Module module) {
+        String orgName = module.getOrg();
+        String moduleName = module.getName();
+        if (tomlNode.entries().containsKey(orgName)) {
+            tomlNode =  (TomlTableNode) tomlNode.entries().get(orgName);
+        }
+        TomlTableNode moduleNode = moduleName.equals(DEFAULT_MODULE) ? tomlNode : extractModuleNode(tomlNode,
+                moduleName);
+        if (moduleNode == null) {
+            throw new TomlException(
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java:107]: shall we break the exception message instead of (.

**Review by manuranga — APPROVED** [review]
