### PR TITLE
Fix formatter adding of spaces in consecutive use of format command

### LINKED ISSUE #41698: [Bug]: Formatter keeps adding spaces to an invalid code when formatted repeatedly
### Description

$subject.

https://github.com/ballerina-platform/ballerina-lang/assets/39232462/b6ee2240-d9ce-46ad-873f-f7d5ec6a4501

Code:

```bal
function baz() {
    worker w3 {
        int b = 2;
    } on f

    worker w4 {
        int b = 2;
    }
}
```

Related PR: #41683

### PR DESCRIPTION
**Pull request by poorna2152**
Fixes #41698 

## Approach
When calculating the number of spaces to add to the start of a line, formatter uses the start offset of the token to calculate the number of spaces. When there are invalid tokens in between the start of the line and the token formatter assumes that these are also spaces. This is handled in this PR by using the start offset of the first invalid token/node in the same line as the token.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 1]
```diff
@@ -4481,17 +4484,20 @@ private void preserveIndentation(boolean value) {
      */
     private int getPreservedIndentation(Token token) {
         int position = token.lineRange().startLine().offset();
+        int startLine = token.lineRange().startLine().line();
```
Comment (lochana-chathura) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:4487]: Let's extract repeated call `token.lineRange().startLine()` to a variable say, `startLinePos`

**Review by lochana-chathura — COMMENTED** [review]
Add a minor comment. Let's sync the PR with the master as well.

**Review by lochana-chathura — APPROVED** [review]

File: misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java [hunk 2]
```diff
@@ -4492,18 +4496,23 @@ private void preserveIndentation(boolean value) {
      * @param token token of which the indentation is required.
      */
     private int getPreservedIndentation(Token token) {
-        int position = token.lineRange().startLine().offset();
+        LinePosition startLinePos = token.lineRange().startLine();
+        int position = startLinePos.offset();
+        int startLine = startLinePos.line();
+        for (Token invalidToken : token.leadingInvalidTokens()) {
+            LinePosition invalidTokenStartLinePos = invalidToken.lineRange().startLine();
+            if (invalidTokenStartLinePos.line() == startLine) {
```
Comment (SasinduDilshara) [inline misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:4504]: According to the codcov, we need to add a test for `invalidTokenStartLinePos.line() != startLine`

Comment (lochana-chathura) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:4504]: The line shown in the codecov is L4508 which is a close brace token. We do reach here for the test. I think codecov warning was mistaken.

Comment (lochana-chathura) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:4504]: @poorna2152 can u confirm it as well.

Comment (poorna2152) [reply misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingTreeModifier.java:4504]: Added a test

**Review by lochana-chathura — APPROVED** [review]

**Review by SasinduDilshara — APPROVED** [review]
