### PR TITLE
Fix self variable completions inside object constructor

### LINKED ISSUE #34309: [LS] No completions for methods defined inside an object constructor within a function
**Description:**
Please consider the following source code.
```ballerina
function testObjectConstructor() {
    int y = 0;

    var obj = object {
        string name = "";
        int age;

        function init() {
            self.age = 0;
            var s = self.getName(); <cursor>
        }

        function getName() returns string {
            return self.name;
        }
    };
}
```
Here we are not getting completions for `getName`.

The reason here is we only considered classes (at the module level) in this function.
https://github.com/ballerina-platform/ballerina-lang/blob/314499149f1834801898ea25cbf8be69ab2cee3a/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java#L1635

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
This PR adds completions for methods defined inside an object constructor within a function.

Fixes #34309

## Samples
Screenshot from 2022-02-21 14-56-10

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 1]
```diff
@@ -1624,6 +1624,29 @@ public static boolean isSelfClassSymbol(Symbol symbol, PositionedOperationContex
...
+
+    public static boolean isSelfObjectSymbol(Symbol symbol, Node nodeAtCursor) {
+        Node currentNode = nodeAtCursor;
+        while (currentNode != null) {
+            if (currentNode.kind() == SyntaxKind.OBJECT_CONSTRUCTOR) {
+                break;
+            }
+            currentNode = currentNode.parent();
+        }
+        if (currentNode != null) {
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1643]: We can rewrite these conditions as below:
```ballerina
if (currentNode == null || currentNode.kind() != SyntaxKind.OBJECT_CONSTRUCTOR) {
    return false;
}

return symbol.getName().isPresent() && symbol.getName().get().equals(SELF_KW);
```

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java [hunk 2]
```diff
@@ -604,7 +604,8 @@ private CompletionItem getModuleCompletionItem(String label, String insertText,
     private List<LSCompletionItem> populateSelfClassSymbolCompletionItems(Symbol symbol, BallerinaCompletionContext ctx,
                                                                           TypeSymbol rawType) {
         Optional<ModuleMemberDeclarationNode> moduleMember = ctx.enclosedModuleMember();
-        if (moduleMember.isEmpty() || !CommonUtil.isSelfClassSymbol(symbol, ctx, moduleMember.get())) {
+        if (moduleMember.isEmpty() || !(CommonUtil.isSelfClassSymbol(symbol, ctx, moduleMember.get())
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java:607]: Let's rewrite this condition as below for better readability:
```java
if (moduleMember.isEmpty() || (!CommonUtil.isSelfClassSymbol(symbol, ctx, moduleMember.get() && !CommonUtil.isSelfObjectSymbol(symbol, ctx.getNodeAtCursor())) {
```

**Review by IMS94 — CHANGES_REQUESTED** [review]
Logic is correct. Let's refactor the code for better readability.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 1 above)
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java]: Done

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 3]
```diff
@@ -1624,6 +1624,29 @@ public static boolean isSelfClassSymbol(Symbol symbol, PositionedOperationContex
...
+    /**
+     * Check if the symbol is an object symbol with self as the name.
+     *
+     * @param symbol               Symbol
+     * @param nodeAtCursor         Node
+     * @return {@link Boolean} whether the symbol is a self object symbol.
+     */
+
+    public static boolean isSelfObjectSymbol(Symbol symbol, Node nodeAtCursor) {
+        Node currentNode = nodeAtCursor;
```
Comment (gayalkuruppu) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1636]: Can we use  the `nodeAtCursor` variable instead of declaring a new variable `currentNode`? WDYT? @mindula  @IMS94

**Review by IMS94 — DISMISSED** [review]
LGTM!

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 4]
```diff
@@ -1624,6 +1624,28 @@ public static boolean isSelfClassSymbol(Symbol symbol, PositionedOperationContex
...
+        while (currentNode != null) {
+            if (currentNode.kind() == SyntaxKind.OBJECT_CONSTRUCTOR) {
+                break;
+            }
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1640]: What if we merge this condition (Actually the negation of it) with the while clause's condition?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 5]
```diff
@@ -1624,6 +1624,28 @@ public static boolean isSelfClassSymbol(Symbol symbol, PositionedOperationContex
...
+            currentNode = currentNode.parent();
+        }
+        if (currentNode == null || currentNode.kind() != SyntaxKind.OBJECT_CONSTRUCTOR) {
+            return false;
+        }
+        return symbol.getName().isPresent() && symbol.getName().get().equals(SELF_KW);
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1646]: We can merge these together into a single return statement

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 6]
```diff
@@ -1624,6 +1624,28 @@ public static boolean isSelfClassSymbol(Symbol symbol, PositionedOperationContex
...
     }
 
+    /**
+     * Check if the symbol is an object symbol with self as the name.
+     *
+     * @param symbol               Symbol
+     * @param nodeAtCursor         Node
+     * @return {@link Boolean} whether the symbol is a self object symbol.
+     */
+
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1634]: Extra space

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java (hunk 5 above)
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java]: Done

**Review by TharushiJay — DISMISSED** [review]
LGTM!

**Review by malinthar — DISMISSED** [review]
LGTM!

**Review by gayalkuruppu — DISMISSED** [review]
LGTM

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java [hunk 7]
```diff
@@ -1631,19 +1631,13 @@ public static boolean isSelfClassSymbol(Symbol symbol, PositionedOperationContex
...
-            }
+        while (currentNode != null && currentNode.kind() != SyntaxKind.OBJECT_CONSTRUCTOR) {
             currentNode = currentNode.parent();
         }
-        if (currentNode == null || currentNode.kind() != SyntaxKind.OBJECT_CONSTRUCTOR) {
-            return false;
-        }
-        return symbol.getName().isPresent() && symbol.getName().get().equals(SELF_KW);
+        return currentNode != null && currentNode.kind() == SyntaxKind.OBJECT_CONSTRUCTOR
+                && symbol.getName().isPresent() && symbol.getName().get().equals(SELF_KW);
```
Comment (nadeeshaan) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java:1640]: you can use `symbol.getName().orElse("").equals(SELF_KW)` instead of `symbol.getName().isPresent() && symbol.getName().get().equals(SELF_KW)`

**Review by nadeeshaan — CHANGES_REQUESTED** [review]

**Review by mohanvive — APPROVED** [review]

**Review by nadeeshaan — APPROVED** [review]
LGTM
