### PR TITLE
[Master] Resolve invalid `unreachable code` error in is expression with tuple types

### LINKED ISSUE #35694: Invalid "unreachable code" error
**Description:**
```ballerina
public type Type A|Tuple|List;
public type A "A";
public type Tuple ["tuple", Type, Type...];
public type List ["list", int?, Type];

function foo(Type t) {
    if t is List {
        return;
    }
    int i = 0; // unreachable code(BCE2106)
}
```

**Steps to reproduce:**

**Affected Versions:**
Ballerina 2201.0.2 (Swan Lake)
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #37271: Type checker does not throw an error for Invalid assignment.
```
type Type A|Tuple|List;
type A "A";
type Tuple ["tuple", Type, Type...];
type List ["list", int?, Type];

function incompatibilityAssignInTupleTypes() {
    Type a = ["tuple", "A", "A", "A"];                                            
    List b = a; // No Compile time Error
}
```

**Suggested Labels (optional):**
Bug

### PR DESCRIPTION
**Pull request by SasinduDilshara**
Fixes #35694
Fixes #37271

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -895,9 +895,16 @@ private boolean isAssignable(BType source, BType target, Set<TypePair> unresolve
             return isFiniteTypeAssignable((BFiniteType) source, target, unresolvedTypes);
         }
 
-        if ((targetTag == TypeTags.UNION || sourceTag == TypeTags.UNION) &&
-                isAssignableToUnionType(source, target, unresolvedTypes)) {
-            return true;
+        if ((targetTag == TypeTags.UNION || sourceTag == TypeTags.UNION)) {
+            boolean isAssignableToUnion = isAssignableToUnionType(source, target, unresolvedTypes);
+            if (isAssignableToUnion) {
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:900]:
```suggestion
            if (isAssignableToUnionType(source, target, unresolvedTypes)) {
```
Shall we remove that variable ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 2]
```diff
@@ -895,9 +895,16 @@ private boolean isAssignable(BType source, BType target, Set<TypePair> unresolve
...
+                return true;
+            }
+
+            TypePair pair = new TypePair(source, target);
+            if (unresolvedTypes.contains(pair)) {
+                unresolvedTypes.remove(pair);
+            }
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:907]: We can remove `contains` check

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 1 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:900]: I will remove

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 2 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:907]: Yes. I will remove.

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:907]: https://github.com/ballerina-platform/ballerina-lang/blob/9355b815333b7b8b874bb7245d0a816259f6df45/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L3441

In here only cyclic unions are added to unresolvedTypes.
So I think we can't remove contains check.

Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:907]: The `remove ` method check element is present in the Set and then remove it. (otherwise, it returns False) So do we need a `contains` check?

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Yes we don't need that. Removed in 4c82e4f1dfb0dba993c5a76e28b7ee7497fdc204

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 1 above)
Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Updated. 4c82e4f1dfb0dba993c5a76e28b7ee7497fdc204

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 3]
```diff
@@ -895,9 +895,13 @@ private boolean isAssignable(BType source, BType target, Set<TypePair> unresolve
...
-        if ((targetTag == TypeTags.UNION || sourceTag == TypeTags.UNION) &&
-                isAssignableToUnionType(source, target, unresolvedTypes)) {
-            return true;
+        if ((targetTag == TypeTags.UNION || sourceTag == TypeTags.UNION)) {
+            if (isAssignableToUnionType(source, target, unresolvedTypes)) {
+                return true;
+            }
+
+            TypePair pair = new TypePair(source, target);
+            unresolvedTypes.remove(pair);
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:904]: I think that it will be more clear if we can do this on the places where we return false in function `isAssignableToUnionType`

Comment (SasinduDilshara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Updated. 038381060edf8bc011bfcde35a826687cd830d25

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/if-stmt.bal [hunk 4]
```diff
@@ -217,6 +217,46 @@ function testResetTypeNarrowingWithBlockStmt() {
     }
 }
 
+type Type A|Tuple|List;
+type A "A";
+type Tuple ["tuple", Type, Type...];
+type List ["list", int?, Type];
+
+function testCustomCircularTupleTypeWithIsCheck() {
```
Comment (lasinicl) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/if-stmt.bal:225]: These are rather type narrowing tests. Shall we move them to https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/type-guard.bal

Comment (SasinduDilshara) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/ifelse/if-stmt.bal]: Updated. 9db7b4456e47d7a3eccf59d70f8d182750da400f

**Review by lasinicl — APPROVED** [review]

**Review by prakanth97 — APPROVED** [review]

**Review by pcnfernando — APPROVED** [review]

**Comment by pcnfernando** [comment]
@SasinduDilshara can you backport these to relevant branches

**Comment by pcnfernando** [comment]
Scratch that. Since it's a breaking change, no need to backport
