### PR TITLE
Fix `map` keyword using as an identifier when it is followed by `<`

### LINKED ISSUE #39016: [Bug]: Invalid syntax tree around qualified name ref followed by a map variable declaration
### Description

Consider  this code:
```ballerina
import ballerina/module1;

public function main() {
    module1:<cursor>

    map<int> m = {};
}
```
Cursor is at `<cursor>`. When we visualize the syntax tree, node at cursor is ` simple name reference` of the following form:
```
 MISSING[     INVALID[module1] INVALID[:]

     INVALID[map] INVALID[<] INVALID[int] INVALID[>]  INVALID[m] ]
```
Ideally it should have been a qualified name reference. This doesn't happen for cases like below:
```ballerina
import ballerina/http;

public function main() {
    http:

    string m = "";
}
```
and
```ballerina
import ballerina/http;

type Data record {|

|};

public function main() {
    http:

    table<Data> tbl = table [];
}
```

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by rdulmina**
## Purpose
$title

Fixes  #39016

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/QualifiedIdentifierTest.java [hunk 1]
```diff
@@ -68,4 +68,10 @@ public void testInterveningWSNotAllowed() {
         testFile("qualified-identifier/qualified_identifier_assert_08.bal", 
                 "qualified-identifier/qualified_identifier_assert_08.json");
     }
+
+    @Test
+    public void testMapTypeAfterColon() {
+        testFile("qualified-identifier/qualified_identifier_assert_09.bal",
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/QualifiedIdentifierTest.java:74]:
```suggestion
        testFile("qualified-identifier/qualified_identifier_source_09.bal",
```

Comment (rdulmina) [reply compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/QualifiedIdentifierTest.java]: Fixed

**Review by lochana-chathura — APPROVED** [review]

**Review by lochana-chathura — APPROVED** [review]
