### PR TITLE
Disallow in query actions assignments to variables narrowed outside the loop

### LINKED ISSUE #34450: Disallow in query actions assignments to variables narrowed outside the loop
**Description:**
https://github.com/ballerina-platform/ballerina-spec/issues/904#issuecomment-1000001995

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/32131

### LINKED ISSUE #34451: Reachability analysis doesn't run for query actions
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    error? n = from int i in 0 ... 2 
    do {
        return;
        int _ = 1; // no error!
    };

    _ = n is error;
}
```

**Affected Versions:**
slbeta6

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
This PR
- Fixes #34450
- Fixes #34451

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java [hunk 1]
```diff
@@ -179,6 +182,11 @@ public void visit(BLangLock lockNode) {
     @Override
     public void visit(BLangSimpleVariableDef varDefNode) {
         checkStatementExecutionValidity(varDefNode);
+
+        BLangExpression expr = varDefNode.var.expr;
+        if (expr != null && expr.getKind() == NodeKind.DO_ACTION) {
+            analyzeReachability(expr, env);
+        }
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:189]: Alternatively we could implement empty visit methods for all the other kinds of expressions/actions. Not sure if we need it though since reachability applies to pretty much none of them.

Anonymous function expressions seem to be handled separately.

Comment (hasithaa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:189]: We should be able to utilize new visitors for this.

**Review by hasithaa — APPROVED** [review]
