### PR TITLE
Fix create variable and check error code action to not return $CompilationError$

### LINKED ISSUE #37252: `$CompilationError$` is returned with create variable and check error code action
**Description:**
Consider the following scenario where we only have `returns` without the return type.

https://user-images.githubusercontent.com/61020198/182784542-9263a5c0-40f9-49db-8d4a-f47bcdc002a3.mov

In this scenario when we apply the Create variable and check error code action, `$CompilationError$|error` is returned with the variable creation.

**Steps to reproduce:**
```
function createIntWithError() returns int|error {
    return 0;
}

class MyClass {
    function testFunction() returns {
       createIntWithError();
    }
}
```

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
This PR fixes the create variable and check error code action to not return `$CompilationError$` when we only have `returns` without the return type.

Fixes #37252

## Samples

https://user-images.githubusercontent.com/61020198/188059583-845829de-6c26-49db-8c38-70ee10797ff1.mov

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by gayalkuruppu — COMMENTED** [review]
The change fixes the intended problem in the issue (#37252), but for this scenario we should not provide code action since the return-type-descriptor is invalid. Hence we need to improve the CodeActionNodeValidator to validate this scenario (and other scenarios where we have incorrect return-type-descriptors) and not provide any code action.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionNodeValidator.java [hunk 1]
```diff
@@ -291,6 +292,8 @@ public Boolean transform(FunctionSignatureNode node) {
                 && !node.closeParenToken().isMissing()
                 && node.leadingInvalidTokens().isEmpty()
                 && node.trailingInvalidTokens().isEmpty()
+                && (node.returnTypeDesc().isEmpty()
+                || node.returnTypeDesc().get().apply(this))
```
Comment (gayalkuruppu) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionNodeValidator.java:296]: Keeping these two in a single line is more readable IMO. WDYT?

Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionNodeValidator.java:296]: +1

**Review by gayalkuruppu — APPROVED** [review]
LGTM
