### PR TITLE
Fix error-arg-list-BP recovery issues

### LINKED ISSUE #25724: Parser crashes when reocvering with error-binding-pattern
**Description:**
Consider the following code snippet

```bal
public function test() {
    int i = 0;
    {
        i = i + 1;
        error err = error("Custom error thrown explicitly.");
        fail err;
    } on fail error e {
        io:println("Exception thrown...");
    }
}
```

Parser crashes with stackoverflow.

</details>
<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```java
Exception in thread "main" java.lang.StackOverflowError
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.getNextRuleInternal(BallerinaParserErrorHandler.java:2712)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.getNextRule(BallerinaParserErrorHandler.java:2434)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:386)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1062)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:1901)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1761)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:1901)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1761)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ba</details>llerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1062)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInExprRelatedAlternativePaths(BallerinaParserErrorHandler.java:1901)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1761)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1062)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1765)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1062)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1765)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:387)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:328)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1062)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:248)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInStmtRelatedAlternativePaths(BallerinaParserErrorHandler.java:1765)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:1537)
	at io.ballerinalang.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1051)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:199)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.seekMatch(AbstractParserErrorHandler.java:181)
	at io.ballerinalang.compiler.internal.parser.AbstractParserErrorHandler.recover(AbstractParserErrorHandler.java:102)
	at io.ballerinalang.compiler.internal.parser.AbstractParser.recover(AbstractParser.java:106)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13214)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
	at io.ballerinalang.compiler.internal.parser.BallerinaParser.parseErrorArgListBindingPattern(BallerinaParser.java:13215)
```

</details>

**Suggested Labels**
Team/CompilerFE, Area/Parser, Type/Bug, Priority/Blocker

### LINKED ISSUE #26989: No error is given for wrong usage of rest-binding-pattern in some scenarios
**Description:**
```bal
function testErrorBindingPatternRecovery() {
    var error (a, ... b, ... c) = a; // can have only one rest-binding-pattern
    var error (a, ... b, c = d, ... e) = a; // can't have rest-binding-pattern in the middle
}
```

**Affected Versions:**
Current Master

**Suggested Labels (optional):**
Team/CompilerFE, Area/Parser, Type/Bug

**Suggested Assignees (optional):**
@lochana-chathura

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #25724 
Fixes #26989

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Parser Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java [hunk 1]
```diff
@@ -14188,25 +14215,31 @@ private STNode parseErrorArgsBindingPatternEnd(ParserRuleContext currentCtx) {
...
-    private STNode parseErrorArgListBindingPattern(ParserRuleContext context) {
+    private STNode parseErrorArgListBindingPattern(ParserRuleContext context, boolean isFirstArg) {
         switch (peek().kind) {
             case ELLIPSIS_TOKEN:
                 return parseRestBindingPattern();
             case IDENTIFIER_TOKEN:
                 // Identifier can means two things: either its a named-arg, or its simple binding pattern.
-                return parseNamedOrSimpleArgBindingPattern();
+                STNode argNameOrSimpleBindingPattern = consume();
+                return parseNamedOrSimpleArgBindingPattern(argNameOrSimpleBindingPattern);
```
Comment (SupunS) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:14225]: Seem this change has no effect?

**Review by SupunS — APPROVED** [review]

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java (hunk 1 above)
Comment (lochana-chathura) [reply compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java:14225]: yea. Earlier we call consume() immediately inside the parseNamedOrSimpleArgBindingPattern. Thought taking it out would be cleaner.
