### PR TITLE
Fix TypeConverter error

### LINKED ISSUE #27549: Error in using `cloneWithType` to union targets
**Description:**

When using cloneWithType to convert to union targets, when the actual type of the source value is a member of the union, and there is another valid type as well, the current implementation cannot proceed.

**Steps to reproduce:**

Please consider the following scenario

```public type Scalar int|string|float|boolean;

public type Argument record {|
    Scalar value;
|};

public function testConvertToUnionWithActualType() {
    json expectedJson = {"value": 132};

    Argument expected = {"value": 132};
    var actual = expectedJson.cloneWithType(Argument);
}
```
**Affected Versions:**

SLP7

**OS, DB, other environment details and versions:**
MacOS BigSur

### PR DESCRIPTION
**Pull request by dulvinw**
When a converting to a record, if a union type is present and the value was convertible to multiple options of the union type converter assumed this is an error.

Also added test cases to check json with decimal using `fromJsonWithType` langlib function

Fixes #27549

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionWithStampTypesTest.java [hunk 1]
```diff
@@ -133,4 +133,9 @@ public void testConvertMapJsonWithDecimalToOpenRecord() {
     public void testConvertMapJsonWithDecimalUnionTarget() {
         BRunUtil.invoke(compileResult, "testConvertMapJsonWithDecimalUnionTarget");
     }
+
+    @Test
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionWithStampTypesTest.java:137]: Shall we move these tests to org.ballerinalang.langlib.test.LangLibValueTest#testFromJsonWithType?

Comment (dulvinw) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionWithStampTypesTest.java:137]: Fixed.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal [hunk 2]
```diff
@@ -104,6 +104,25 @@ function testConvertMapJsonWithDecimalUnionTarget() {
...
 }
 
+public type Scalar int|string|float|boolean;
+
+public type Argument record {|
+    Scalar value;
+|};
+
+public function testConvertUnion() {
+    json expectedJson = { "value": 132 };
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal:114]:
```suggestion
    json expectedJson = {"value": 132};
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal [hunk 3]
```diff
@@ -104,6 +104,25 @@ function testConvertMapJsonWithDecimalUnionTarget() {
...
+
+    Argument expected = { "value": 132 };
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal:116]:
```suggestion
    Argument expected = {"value": 132};
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal [hunk 4]
```diff
@@ -104,6 +104,25 @@ function testConvertMapJsonWithDecimalUnionTarget() {
...
+    var actual = expectedJson.cloneWithType(Argument);
+
+    if (actual is error) {
+        panic error("`cloneWithType` returned an error.");
+    } else {
+        assert(actual, expected);
+    }
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal:123]:
```suggestion
    }
    assert(actual, expected);
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal [hunk 5]
```diff
@@ -78,7 +78,7 @@ type OpenRecordWithUnionTarget record {|
 map<json> mp = {
         name: "foo",
         factor: 1.23d
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal:80]:
```suggestion
    name: "foo",
    factor: 1.23d
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionWithStampTypesTest.java [hunk 6]
```diff
@@ -133,4 +133,9 @@ public void testConvertMapJsonWithDecimalToOpenRecord() {
...
+    void testConvertUnion() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/conversion/NativeConversionWithStampTypesTest.java:138]: Shouldn't the name reflect that it's conversion with numeric types?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal [hunk 7]
```diff
@@ -104,6 +104,25 @@ function testConvertMapJsonWithDecimalUnionTarget() {
...
+
+public type Argument record {|
+    Scalar value;
+|};
+
+public function testConvertUnion() {
+    json expectedJson = { "value": 132 };
+
+    Argument expected = { "value": 132 };
+    var actual = expectedJson.cloneWithType(Argument);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal:117]: Were we able to reproduce the original CCE mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/26632? Both this example and the one in the issue seem to result in "ballerina/lang.typedesc}ConversionError" errors on slp7.

File: langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal [hunk 8]
```diff
@@ -1245,3 +1245,23 @@ function testEnsureTypeNegative() {
...
 }
+
+type OpenRecordWithUnionTarget record {|
+    string|decimal...;
+|};
+
+function tesFromJsonWithTypeMapWithDecimal() {
+    map<json> mp = {
+            name: "foo",
+            factor: 1.23d
```
Comment (MaryamZi) [inline langlib/langlib-test/src/test/resources/test-src/valuelib_test.bal:1256]:
```suggestion
        name: "foo",
        factor: 1.23d
```

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 9]
```diff
@@ -355,7 +355,7 @@ private static boolean isConvertibleToRecordType(Object sourceValue, BRecordType
             } else {
                 if (targetFieldTypes.containsKey(fieldName)) {
                     if (getConvertibleTypes(valueEntry.getValue(), targetFieldTypes.get(fieldName),
-                            unresolvedValues).size() != 1) {
+                            unresolvedValues).size() == 0) {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:358]: Don't we still have to check for > 1 convertible types? That should also be an error, right? Let's add a test for the same.

The following should fail.

```ballerina
public type Maps record {|int i; int...;|}|record {|int i?;|};

public type Value record {|
    Maps value;
|};

public function main() {
    json j = {"value": <map<int>> {i: 1}};
    Value res = checkpanic j.cloneWithType(Value);
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal (hunk 7 above)
Comment (dulvinw) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal:117]: CCE is not reproducible. Found a different bug and fixed it.

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal:117]: I tried the same on slp3 also but still couldn't reproduce the CCE. Fails with the following which I believe has/is been fixed.

```cmd
error: {ballerina/lang.typedesc}ConversionError message='map<json>' value cannot be converted to 'Argument'
        at ballerina.lang_value.1_0_0:cloneWithType(value.bal:67)
           xyz:main(xyz.bal:174)
```

But since the CCE has been observed shall we keep that issue open to try and reproduce the CCE and fix it, and create a new issue for what we're fixing here? Let's also add a comment on the issue to say the CCE is not reproducible with that code.

Comment (dulvinw) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion-stampable-values.bal:117]: +1. Will do that

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 10]
```diff
@@ -267,6 +270,15 @@ static boolean isConvertibleToFloatingPointTypes(Object value) {
         return convertibleTypes;
     }
 
+    private static boolean checkIsType(Object value, Type targetType) {
+        Type valueType = TypeChecker.getType(value);
+        if (valueType.equals(targetType)) {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:275]: In L248 shouldn't we directly check `io.ballerina.runtime.internal.TypeChecker#checkIsType(java.lang.Object, io.ballerina.runtime.api.types.Type)` instead? 

Checking `.equals()` may not work for subtypes, right?

Comment (dulvinw) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:275]: For anything which is not the exact type shouldn't we resort to getConvertibleTypes method?

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:275]: Yeah, I guess we should look for an exact match, or we won't be able to widen the type using `cloneWithType`. This is OK.

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:275]: We should ideally be able to rely on `==` here though, right?

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java [hunk 11]
```diff
@@ -267,6 +270,15 @@ static boolean isConvertibleToFloatingPointTypes(Object value) {
         return convertibleTypes;
     }
 
+    private static boolean checkIsType(Object value, Type targetType) {
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:273]: Shall we call this `checkIsSameType` instead? Because `checkIsType` means something else in `TypeChecker`?

Comment (dulvinw) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:273]: +1. Will do

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java:273]: Should we just move this in-line?

```
TypeChecker.getType(value) == targetType
```

**Review by MaryamZi — APPROVED** [review]
