### PR TITLE
Fix Symbol Position of SimpleNameReferenceNode

### LINKED ISSUE #31962: The symbol position of a SimpleNameReferenceNode comes incorrectly
**Description:**
The symbol position of `Module` token at https://github.com/jclark/semtype/blob/master/modules/b/bbuild.bal#L4 comes as `table<TypeDef> key(name)` at https://github.com/jclark/semtype/blob/master/modules/b/bparse.bal#L3 (expected the `Module` token)

**Steps to reproduce:**
Get the symbol of `Module` token at https://github.com/jclark/semtype/blob/master/modules/b/bbuild.bal#L4

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #31962

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java [hunk 1]
```diff
@@ -142,6 +142,11 @@ public Location location() {
             return Optional.of(this.location);
         }
 
+        if (this.tSymbol != null) {
+            this.location = this.tSymbol.pos;
+            return Optional.of(this.location);
+        }
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java:148]: This seems like an arbitrary hack. Dig a bit deeper to identify what the issue is, why it is occurring and at what place can it be fixed.

Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaTypeReferenceTypeSymbol.java]: When the `tSymbol != tSymbol.type.tsymbol`, the location has to be either set in the constructor or obtained from the `tSymbol.pos` (within the `getLocation()` method). 
Updated to explicitly set the location in the constructor.

**Review by pubudu91 — APPROVED** [review]
