### PR TITLE
[Master] Make async-send an action

### LINKED ISSUE #18639: Make async-send an action
**Description:**
$title, it is currently a statement.

### LINKED ISSUE #24849: Refactor BLangWorkerSend so that it can work as a expression.
**Description:**
Refer https://ballerina.io/ballerina-spec/spec.html#async-send-action

`BLangWorkerSend` is modeled as a statement, it need to be modeled as a action (hence as an expression and validate later)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### LINKED ISSUE #40759: [Bug]:CCE when `sync-send-action` used with `check` expression
### Description

```
function testAsyncSendAsExpressionWithCheckExpr() {
    worker w1 {
        () a = check (5 ->> w2);
    }

    worker w2 returns error? {
        int x = <- w1;
    }

    map<error?> mapResult = wait {w1, w2};
}
```

Got `error: error while generating method '$lambda$_0' in class 'prakanth/test/0/main'` for above example.

### Steps to Reproduce

_No response_

### Affected Version(s)

2201.6.0 and master

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by prakanth97**
## Purpose

Fixes #18639
Fixes #24849
Fixes #40759

## Approach
Refactor BLangWorkerSend so that it can work as an expression.

## Samples
```
public function main() {
    worker w1 {
        () a = 5 -> w2;
    }

    worker w2 {
        int a = <- w1;
    }
}
```
This will not give `async send action not yet supported as expression` error.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java [hunk 1]
```diff
@@ -744,15 +744,15 @@ public void visit(BLangLetExpression letExpression, AnalyzerData data) {
         data.statementReturnsPanicsOrFails = returnStateBefore;
     }
 
-    private void checkStatementExecutionValidity(BLangStatement statement, AnalyzerData data) {
+    private void checkStatementExecutionValidity(BLangNode statement, AnalyzerData data) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:747]: It is better to rename the parameter name too.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -2772,6 +2773,40 @@ public void visit(BLangWorkerSyncSendExpr syncSendExpr, AnalyzerData data) {
         data.resultType = data.expType == symTable.noType ? symTable.nilType : data.expType;
     }
 
+    @Override
+    public void visit(BLangWorkerAsyncSendExpr asyncSendExpr, AnalyzerData data) {
+        BSymbol symbol =
+                symResolver.lookupSymbolInMainSpace(data.env, names.fromIdNode(asyncSendExpr.workerIdentifier));
+
+        if (symTable.notFoundSymbol.equals(symbol)) {
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2781]: Let's check the symbol tag here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java (hunk 1 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:747]: I will update

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java]: Updated d40fecc2014d4adb35b8b1117ca9de143e36010

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java [hunk 3]
```diff
@@ -728,8 +728,8 @@ public void visit(BLangDoClause doClause, AnalyzerData data) {
     }
 
     @Override
-    public void visit(BLangWorkerSend workerSendNode, AnalyzerData data) {
-        checkStatementExecutionValidity(workerSendNode, data);
+    public void visit(BLangWorkerAsyncSendExpr asyncSendExpr, AnalyzerData data) {
+        checkStatementExecutionValidity(asyncSendExpr, data);
```
Comment (KavinduZoysa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:732]: It seems this line is not covered. Please check

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java [hunk 4]
```diff
@@ -3172,11 +3166,11 @@ public BLangNode transform(StartActionNode startActionNode) {
         BLangNode expression = createActionOrExpression(startActionNode.expression());
 
         BLangInvocation invocation;
-        if (!(expression instanceof BLangWorkerSend)) {
+        if (!(expression instanceof BLangWorkerAsyncSendExpr)) {
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java:3169]: I know the code was there already, but checking `instanceof` is not a good practice. Please check the NodeKind instead. like below expression.getKind() == NodeKind.WORKER_SEND.. etc

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeAnalyzer.java [hunk 5]
```diff
@@ -619,7 +619,7 @@
 
     public abstract void visit(BLangWhile node, T data);
 
-    public abstract void visit(BLangWorkerSend node, T data);
+    public abstract void visit(BLangWorkerAsyncSendExpr node, T data);
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeAnalyzer.java:622]: Lets first deprecate these and later remove it

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java (hunk 3 above)
Comment (lasinicl) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:732]: Since `BLangWorkerAsyncSendExpr` is a `BLangExpression` now, we don't need to check statement validity for `asynSendExpr`. Therefore we can get rid of calling this function here.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java [hunk 6]
```diff
@@ -744,25 +744,25 @@ public void visit(BLangLetExpression letExpression, AnalyzerData data) {
...
+                        ((BLangWhile) node).expr);
                 break;
             case IF:
-                data.unreachableBlock = statement.parent != null && statement.parent.getKind() == NodeKind.IF
+                data.unreachableBlock = node.parent != null && node.parent.getKind() == NodeKind.IF
                         && data.booleanConstCondition == symTable.trueType;
                 data.booleanConstCondition = ConditionResolver.checkConstCondition(types, symTable,
-                        ((BLangIf) statement).expr);
+                        ((BLangIf) node).expr);
                 break;
```
Comment (lasinicl) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java:766]: > Since `BLangWorkerAsyncSendExpr` is a `BLangExpression` now, we don't need to check statement validity for `asynSendExpr`. Therefore we can get rid of calling this function here.

 As per the above comment we don't need to change these methods as we only do this for statements.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeAnalyzer.java (hunk 5 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/BLangNodeAnalyzer.java:622]: These are blang nodes, if we create a new expression for `AsyncSend` and direct it to a that blang node then these nodes can't be accessed at all. Hence no need to keep those nodes

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 7]
```diff
@@ -2005,43 +2005,43 @@ private boolean workerExists(BType type, String workerName, SymbolEnv env) {
...
 
-        BType type = workerSendNode.expr.getBType();
+        BType type = asyncSendExpr.expr.getBType();
         if (type == symTable.semanticError) {
             // Error of this is already printed as undef-var
             was.hasErrors = true;
-        } else if (workerSendNode.expr instanceof ActionNode) {
-            this.dlog.error(workerSendNode.expr.pos, DiagnosticErrorCode.INVALID_SEND_EXPR);
+        } else if (asyncSendExpr.expr instanceof ActionNode) {
+            this.dlog.error(asyncSendExpr.expr.pos, DiagnosticErrorCode.INVALID_SEND_EXPR);
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:2023]: Due to this issue https://github.com/ballerina-platform/ballerina-lang/issues/38782 could not write a test

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java (hunk 4 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeBuilder.java]: Updated 40cc512e09d1ce6989618c1c7392ab833ab772b5

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java (hunk 3 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java]: Updated 40cc512e09d1ce6989618c1c7392ab833ab772b5

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java (hunk 6 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java]: Updated 40cc512e09d1ce6989618c1c7392ab833ab772b5

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java (hunk 3 above)
Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ReachabilityAnalyzer.java]: Updated https://github.com/ballerina-platform/ballerina-lang/commit/40cc512e09d1ce6989618c1c7392ab833ab772b5

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClassClosureDesugar.java [hunk 8]
```diff
@@ -919,9 +919,9 @@ public void visit(BLangStringTemplateLiteral stringTemplateLiteral) {
     }
 
     @Override
-    public void visit(BLangWorkerSend workerSendNode) {
-        workerSendNode.expr = rewriteExpr(workerSendNode.expr);
-        result = workerSendNode;
+    public void visit(BLangWorkerAsyncSendExpr asyncSendExpr) {
+        asyncSendExpr.expr = rewriteExpr(asyncSendExpr.expr);
+        result = asyncSendExpr;
```
Comment (prakanth97) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClassClosureDesugar.java:924]: Closures seem not identified properly due to this issue https://github.com/ballerina-platform/ballerina-lang/issues/38810

File: tests/jballerina-unit-test/src/test/resources/test-src/workers/worker_async_send_as_expression.bal [hunk 9]
```diff
@@ -14,12 +14,51 @@
...
+        int x = <- w1;
+        if (x == 5) {
+            return error("This is an error");
+        }
+        x = <- w1;
+    }
+
+     map<error??> mapResult = wait {w1, w2};
+}
+
```
Comment (lasinicl) [inline tests/jballerina-unit-test/src/test/resources/test-src/workers/worker_async_send_as_expression.bal:54]: Shall we add more tests to test the behavior of async send in all places where this is allowed to be used now? 
Check places where `action` and `action-or-expr` are allowed in the spec. ex:type casts, check expr, trap, lvexpr etc

**Review by lasinicl — COMMENTED** [review]
> Shall we add more tests to test the behavior of async send in all places where this is allowed to be used now? Check places where `action` and `action-or-expr` are allowed in the spec. ex:type casts, check expr, trap, lvexpr etc

Has this comment been addressed?

**Comment by prakanth97** [comment]
> > Shall we add more tests to test the behavior of async send in all places where this is allowed to be used now? Check places where `action` and `action-or-expr` are allowed in the spec. ex:type casts, check expr, trap, lvexpr etc
> 
> Has this comment been addressed?

No, I will address them ASAP.

**Comment by DamithaSenevirathne** [comment]
Shall we add a testcase in expectedType API tests to verify whether https://github.com/ballerina-platform/ballerina-lang/issues/38522 is fixed by this change ?

You can add a testcase similar to the following testcase

tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/expectedtype/RemoteActionNodeTest.java

File: tests/jballerina-unit-test/src/test/resources/test-src/workers/worker_async_send_as_expression.bal (hunk 9 above)
Comment (prakanth97) [reply tests/jballerina-unit-test/src/test/resources/test-src/workers/worker_async_send_as_expression.bal:138]: Added tests for this https://github.com/ballerina-platform/ballerina-lang/pull/38245/commits/00909f206139900d02b95963101209f7cb0f45e7

**Review by hasithaa — APPROVED** [review]
