### PR TITLE
Fix default worker crash with error return

### LINKED ISSUE #41626: [Bug]: Runtime Crash when using worker interaction to default worker with error return
### Description

Please refer the example.

```ballerina
import ballerina/http;

service /payments on new http:Listener(9095) {

    resource function post orders/[string orderID]/reserve() returns int|error {

        worker w1 returns error? {
            int a = 10;
            a -> function;
        }
        int b = <- w1;
        return b;
    }
}

```

When running above progran, runtime crash with following log.

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    waruna/httpService/0/$value$$anonType$_0.$post$orders$^$reserve(Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/api/values/BString;)Ljava/lang/Object; @1206: invokestatic
  Reason:
    Type 'waruna/httpService/0/$value$$anonType$_0' (current frame, stack[1]) is not assignable to 'io/ballerina/runtime/internal/scheduling/Strand'
  Current Frame:
    bci: @1206
    flags: { }

```

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #41626 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/MockListener.java [hunk 1]
```diff
@@ -61,4 +66,14 @@ public void notifyFailure(BError error) {
         }
         return err;
     }
+
+    public static BFuture invokeResourceWithUnionReturn(Environment env, BString name) {
+        if (service != null) {
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/MockListener.java:71]: Do we need this null check?

File: tests/jballerina-unit-test/src/test/resources/test-src/services/error_union_return_with_default_worker.bal [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+    }
+}
+
+isolated function externAttach(service object {} s) returns error? = @java:Method {
+    'class: "org.ballerinalang.nativeimpl.jvm.tests.MockListener",
+    name: "attach"
+} external;
+
+listener Listener lsn = new();
+
```
Comment (warunalakshitha) [inline tests/jballerina-unit-test/src/test/resources/test-src/services/error_union_return_with_default_worker.bal:43]: Do we need to add a service here. Simple object test case would be enough i think

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/MockListener.java (hunk 1 above)
Comment (gabilang) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/tests/MockListener.java:71]: ATM it has been only used for a test which involve with a service test case. Hence the service will not be null here and we can remove it.

File: tests/jballerina-unit-test/src/test/resources/test-src/services/error_union_return_with_default_worker.bal (hunk 2 above)
Comment (gabilang) [reply tests/jballerina-unit-test/src/test/resources/test-src/services/error_union_return_with_default_worker.bal:43]: Yes, The issue can be reproduced with the error union return when the `self` is included to localVars and with the existence of worker channels.  Added the provided case in the issue as a test case since there are less number of unit tests added to mock the service.

Comment (gabilang) [reply tests/jballerina-unit-test/src/test/resources/test-src/services/error_union_return_with_default_worker.bal:30]: Removed the service test case.

**Review by Nadeeshan96 — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM
