### PR TITLE
Fix inconsistency behaviour in named-arg in error constructor and function-call

### LINKED ISSUE #36356: Inconsistency behavior in named-arg in error constructor and function-call
**Description:**

CASE 1:
```ballerina
type Application record {|
    string id;
    string name;
    int 'version;
|};

type ErrorData record {
    string errorCode;
    Application application;
};

type CustomError error<ErrorData>;

public function checkError() returns CustomError? {
    return error CustomError("Custom error", errorCode = "123", application = <1>{}<2>);
}
```

CASE 2:
```ballerina
type Application record {|
    string id;
    string name;
    int 'version;
|};

function test() returns error? {
    testFuncCall(a = 1, application = <3>{}<4>);
}

function testFuncCall(int a, Application application) {
}
```
Here in CASE 1, We get `invalid arg type in error detail field 'application', expected 'Application', found 'record {| |} & readonly'` as the error. But in CASE 2, we get `missing non-defaultable required record field 'id'(BCE2520)`, 
`missing non-defaultable required record field 'name'(BCE2520)` and
`missing non-defaultable required record field 'version'(BCE2520)`.

Screenshot from 2022-05-30 13-47-45

Screenshot from 2022-05-30 13-45-41

**Steps to reproduce:**

**Affected Versions:**
'master` branch

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by prakanth97**
## Purpose
Fixes #36356 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -6459,10 +6459,15 @@ private List<BLangNamedArgsExpression> checkProvidedErrorDetails(BLangErrorConst
         for (BLangNamedArgsExpression namedArgsExpression : errorConstructorExpr.namedArgs) {
             BType target = checkErrCtrTargetTypeAndSetSymbol(namedArgsExpression, expectedType);
 
+            namedArgsExpression.cloneAttempt++;
             BLangNamedArgsExpression clone = nodeCloner.cloneNode(namedArgsExpression);
-            BType type = checkExpr(clone, target, data);
+            BType type = checkExprSilent(clone, target, data);
             if (type == symTable.semanticError) {
-                checkExpr(namedArgsExpression, data);
+                if (Types.getReferredType(target).tag == TypeTags.RECORD) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6466]: Why special case just the record type? Shouldn't that be any non union?

Comment (prakanth97) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6466]:
```type MyError2 error <map<string>>;
function testErrorTypeRefNegative() {
    MyError2 me2 = error MyError2("Message", c = 2); // invalid arg type in error detail field 'c', expected "
                                                     //                   "'string', found 'int'
}``` 
if we consider c=2, the error should be as mentioned in the comment.  
To get the type of c as int, in the checkExpr target should noType 
then we will evaluate the type as int. This is one of the non union case 
has to be go through else statement. But only for the record type, we have to check 
the availability of individual fields.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/errorconstructorexpr/error-constructor-expr-negative.bal [hunk 2]
```diff
@@ -65,3 +65,26 @@ error uc3 = error ErrorU3("Hello");
 
 int|string uc4 = error ErrorA("msg");
 int|string b = error("err");
+
+// Test cases for issue fix: https://github.com/ballerina-platform/ballerina-lang/issues/36356
```
Comment (SasinduDilshara) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/errorconstructorexpr/error-constructor-expr-negative.bal:69]: Do we need this comment?

**Comment by pcnfernando** [comment]
Seems a completion test has failed. Will have to check whether the completions have changed @prakanth97

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -6459,10 +6459,15 @@ private List<BLangNamedArgsExpression> checkProvidedErrorDetails(BLangErrorConst
         for (BLangNamedArgsExpression namedArgsExpression : errorConstructorExpr.namedArgs) {
             BType target = checkErrCtrTargetTypeAndSetSymbol(namedArgsExpression, expectedType);
 
+            namedArgsExpression.cloneAttempt++;
             BLangNamedArgsExpression clone = nodeCloner.cloneNode(namedArgsExpression);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6463]: `cloneNode` also increments the `cloneAttempt`, right? Do we know why we need this here?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 4]
```diff
@@ -6460,9 +6460,13 @@ private List<BLangNamedArgsExpression> checkProvidedErrorDetails(BLangErrorConst
             BType target = checkErrCtrTargetTypeAndSetSymbol(namedArgsExpression, expectedType);
 
             BLangNamedArgsExpression clone = nodeCloner.cloneNode(namedArgsExpression);
-            BType type = checkExpr(clone, target, data);
```
Comment (lochana-chathura) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6463]: The spec says, 
> The arg-name of every named-arg must be specified as the field-name of an individual-field-descriptor occurring in D, **unless there are no such field names**. 

Therefore, if we consider the scenarios with expression in named-arge having no user speficied CET,
```bal
type E1 error<record {}>;
type E2 error<map<string>>;
type E3 error<record {||}>;

error err1 = error("error message 1", fatal = false, msg = "msg"); // OK  [1]
error err2 = error E1("error message 2", fatal = false, msg = "msg"); // OK  [2]
error err3 = error E2("error message 3", fatal = "false", msg = "msg"); // OK [3]
error err3 = error E3("error message 3", fatal = "false", msg = "msg"); // ERROR [4]
```
from the `checkErrCtrTargetTypeAndSetSymbol` we get the the target type for named arg's expression,
[1] - `value:Clonable` from `map<value:Clonable>`
[2] - `anydata` from `record {}`
[3] - `string` from map<string>
[4] - `symbleTable.noType` from record {||} 

So, I think it is correct to type check with the target type. The whole logic here should be,
```bal
            BType target = checkErrCtrTargetTypeAndSetSymbol(namedArgsExpression, expectedType);
            checkExpr(namedArgsExpression, target, data);
            namedArgs.add(namedArgsExpression);
```

Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6463]: Currently, we allow this because of the existing logic i guess. 
`error err = error("Error", code1 = [12, "A", 10.5, 1], code2 = {a: "A", b: [1, 2]});`

But, this should result in complication error,
>Each named-arg specifies a field of the error detail mapping; **the static type of each named-arg must be a subtype of value:Cloneable**.

Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6463]: Resolving as per the offline discussion with @pcnfernando @prakanth97.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (lochana-chathura) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6465]: +1 to type check with `target` for non-unions.

Also, we will need to modify the below to check if the `field.type` is union and is not assignable.  (to avoid duplicate diagnostics as we already type checked for non unions and logged errors)
https://github.com/ballerina-platform/ballerina-lang/blob/3d4e9517b98d902383d0d49282e29736d2804d78/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L3349-L3351

**Review by lochana-chathura — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 5]
```diff
@@ -3318,7 +3318,8 @@ public void visit(BLangErrorConstructorExpr errorConstructorExpr, AnalyzerData d
         if (Types.getReferredType(detailType).tag == TypeTags.MAP) {
             BType errorDetailTypeConstraint = ((BMapType) Types.getReferredType(detailType)).constraint;
             for (BLangNamedArgsExpression namedArgExpr: namedArgs) {
-                if (!types.isAssignable(namedArgExpr.expr.getBType(), errorDetailTypeConstraint)) {
+                if (errorDetailTypeConstraint.tag == TypeTags.UNION &&
+                        !types.isAssignable(namedArgExpr.expr.getBType(), errorDetailTypeConstraint)) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3322]: In here `errorDetailTypeConstraint` is a union; its wrapped inside a type reference
```ballerina
type StringType string|int;

type ErrorR1 error<map<StringType>>;

function dummyTest() {
    ErrorR1 er1 = error ErrorR1("Custom error", errorCode = "104", application = {});
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 6]
```diff
@@ -3346,7 +3347,7 @@ public void visit(BLangErrorConstructorExpr errorConstructorExpr, AnalyzerData d
                     }
                 } else {
                     missingRequiredFields.remove(namedArg.name.value);
-                    if (!types.isAssignable(namedArg.expr.getBType(), field.type)) {
+                    if (field.type.tag == TypeTags.UNION && !types.isAssignable(namedArg.expr.getBType(), field.type)) {
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3350]: Same as https://github.com/ballerina-platform/ballerina-lang/pull/36544/files#r904156212
