### PR TITLE
Fix issue with intersection of readonly and record type with defaults

### LINKED ISSUE #42523: [Bug]: Intersection of readonly and record type with defaults doesn't function correctly when it is within a Ballerina package
### Description

$title.

Following program compiles without any error when it is in ballerina package.
```ballerina
type Temp record {|
    any[] initalValues = [10, 20, 30];
|};

function value() {
    // Now results in compile-time error.
    Temp & readonly _ = {};
}
```

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fixes #42523

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by LakshanWeerasinghe** [comment]
Shall we add a test case with compiling project?

**Review by LakshanWeerasinghe — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/RecordInBalaTest.java [hunk 1]
```diff
@@ -71,4 +71,12 @@ public void testComplexCyclicRecordTypeResolution() {
         BRunUtil.invoke(typeResolution, "testCreatingComplexRecWithIncTypeFromBala");
         BRunUtil.invoke(typeResolution, "testCreatingComplexRecWithIncTypeFromBalaWithCM");
     }
+
+    @Test
+    public void testIntersectionOfReadonlyAndRecordTypeWithDefaults() {
+        CompileResult result = BCompileUtil.compile("test-src/bala/test_projects/test_project_records_negative");
+        int count = 0;
+        BAssertUtil.validateError(result, count, "missing non-defaultable required record field 'initialValues'",
+                                  22, 25);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/bala/record/RecordInBalaTest.java:80]: Assert count at the end against the diagnostic count from result.

**Review by MaryamZi — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_records_negative/records.bal [hunk 2]
```diff
@@ -0,0 +1,23 @@
+// Copyright (c) 2024 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
+//
+// WSO2 Inc. licenses this file to you under the Apache License,
```
Comment (lochana-chathura) [inline tests/jballerina-unit-test/src/test/resources/test-src/bala/test_projects/test_project_records_negative/records.bal:3]:
```suggestion
// Copyright (c) 2024 WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
```

**Review by lochana-chathura — APPROVED** [review]
