### PR TITLE
Panic when attempting to retrieve a config as an incompatible type

### LINKED ISSUE #19369: Bad Sad error occured when there is a invalid configuration on ballerina.conf
**Description:**
I have below configuration in ballerina.conf (generated by helm)
```toml
[idp.cache]
        expirationPeriod=1.8e+06
        size=1000
```
I do following in my ballerina code:
```ballerina
final int cacheExpiryInterval = config:getAsInt("idp.cache.expirationPeriod");
```
Then I get this in bellerina-internal.log

`
[2019-10-11 15:47:44,569] SEVERE {b7a.log.crash} - idp.cache.expirationPeriod does not map to a valid int
java.lang.IllegalArgumentException: idp.cache.expirationPeriod does not map to a valid int
at org.ballerinalang.config.ConfigRegistry.getAsInt(ConfigRegistry.java:248)
at org.ballerinalang.stdlib.config.GetConfig.get(GetConfig.java:49)
at ballerina.config.natives.get(natives.bal:29)
at ballerina.config.config.getAsInt(config.bal:59)
at choreo.idp.___init.choreo_idp_0_1_0__init_(idp:21)
at choreo.api.___init.$moduleInit(api:65535)
at choreo.api.___init.$lambda$$moduleInit$(api)
at choreo.api.___init$$Lambda$6.0000000024349070.apply(Unknown Source)
at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:486)
at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:237)
at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:207)
at org.ballerinalang.jvm.scheduling.Scheduler.start(Scheduler.java:194)
at choreo.api.___init.main(api)
`
There are two issues here:

1. Config API can't parse scientific notation
2. This error should have been on sysout (than in ballerina-internal.log). It makes devOp's day a bad one.

**Steps to reproduce:**
1. Put above code in a ballerina program.
2. configure the ballerina.conf
3. execute the program.
**Affected Versions:**
1.0.1
**OS, DB, other environment details and versions:**
K8, AWS
**Related Issues (optional):**

**Suggested Labels (optional):**
blocker
**Suggested Assignees (optional):**
@chamil321 @hasithaa

### PR DESCRIPTION
**Pull request by pubudu91**
Fixes #19369

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-config/src/main/java/org/ballerinalang/config/ConfigRegistry.java [hunk 1]
```diff
@@ -281,7 +281,7 @@ public double getAsFloat(String key) {
                 }
                 return (Double) value;
             } catch (ClassCastException | NumberFormatException e) {
-                throw new IllegalArgumentException(key + " does not map to a valid float");
+                throw new IllegalArgumentException("The config key '" + key + "' does not map to a valid 'float'");
```
Comment (wggihan) [inline bvm/ballerina-config/src/main/java/org/ballerinalang/config/ConfigRegistry.java]: Shouldn't that error message start with lower cases?

Comment (pubudu91) [reply bvm/ballerina-config/src/main/java/org/ballerinalang/config/ConfigRegistry.java]: We haven't followed one convention for error messages at the moment. Checked some of the panics being created and it has a mix of upper and lower case first letters. Will check with the others as well and see.

Comment (pubudu91) [reply bvm/ballerina-config/src/main/java/org/ballerinalang/config/ConfigRegistry.java]: Changed it to lower case with 27826ad
