### PR TITLE
Fix Language Server Issues

### LINKED ISSUE #26455: Disabled a langserver-test
**Description:**
A test which is related to match-stmt is disabled (match_stmt_ctx_config1.json). It should be enabled.

This is disabled in PR #25863

### LINKED ISSUE #28849: Listener new expression completion in a service declaration adds a semicolon at the end
**Description:**
$title, this only seems to happen when there is no explicit `init` method in the listener class.

**Steps to reproduce:**
listener_completion

Accepting this adds
```ballerina
public class Listener {
    public isolated function 'start() returns error? { }

    public isolated function gracefulStop() returns error? { }

    public isolated function immediateStop() returns error? { }

    public isolated function detach(service object {} s) returns error? { }

    public isolated function attach(service object {} s, string? name) returns error? { }
}

service /foo on new Listener();
```

But this does not happen when `Listener` is defined as
```
public class Listener {
    function init() { }

    public isolated function 'start() returns error? { }

    public isolated function gracefulStop() returns error? { }

    public isolated function immediateStop() returns error? { }

    public isolated function detach(service object {} s) returns error? { }

    public isolated function attach(service object {} s, string[]? name) returns error? { }
}
```

**Affected Versions:**
slalpha2

### LINKED ISSUE #28934: Create Variable code action generates invalid variable name
**Description:**
Consider the following source,

```
class File {
   string path;
   string contents;
   function init(string p)
                     returns error? {
      self.path = p;
      self.contents =
         check io:fileReadString(p);         
   }
}

function name() {
    new File("test.txt");
}
```

For ` new File("test.txt");` this generates variable name as `1` which is invalid.

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose

Fixes #28934
Fixes #28849
Fixes #26455 

1. Add the completion support for the match statement context

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumDeclarationNodeContext.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
+/*
+ * Copyright (c) 2020, WSO2 Inc. (http://wso2.com) All Rights Reserved.
```
Comment (prabushi) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumDeclarationNodeContext.java:2]: Shall we update license headers?

Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/EnumDeclarationNodeContext.java]: updated

**Review by prabushi — APPROVED** [review]
