### PR TITLE
Fix crash when using let expressions in xml-template-expr

### LINKED ISSUE #33077: Using let expressions in xml-template-expr crashes the compiler
Consider the following code.

```
public function main() {
    xml x = xml `<Books>${xml `<Book>"${let int y = 5 in y}"</Book>`}</Books>`;
}
```

Compiling the above code gives the following exception.

```
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:674)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangLetExpression.accept(BLangLetExpression.java:55)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:1565)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:969)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangXMLTextLiteral.accept(BLangXMLTextLiteral.java:52)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:1565)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExprs(ClosureDesugar.java:1582)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:962)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangXMLElementLiteral.accept(BLangXMLElementLiteral.java:111)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:1565)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExprs(ClosureDesugar.java:1582)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:962)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangXMLElementLiteral.accept(BLangXMLElementLiteral.java:111)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:1565)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:898)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:72)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteExpr(ClosureDesugar.java:1565)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:554)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:1545)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:417)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:1545)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewriteStmt(ClosureDesugar.java:1574)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:292)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:1545)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:284)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.rewrite(ClosureDesugar.java:1545)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.lambda$visit$1(ClosureDesugar.java:218)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.wso2.ballerinalang.compiler.desugar.ClosureDesugar.visit(ClosureDesugar.java:217)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:811)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8135)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:455)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:234)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:412)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:345)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:183)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
```

### PR DESCRIPTION
**Pull request by rpjayasekara**
Fixes #33077 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java [hunk 1]
```diff
@@ -972,7 +972,6 @@ public void visit(BLangXMLElementLiteral xmlElementLiteral) {
 
     @Override
     public void visit(BLangXMLTextLiteral xmlTextLiteral) {
-        xmlTextLiteral.textFragments.forEach(this::rewriteExpr);
```
Comment (chiranSachintha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:975]: What is the reason to not resolving closures of `textFragments` in xmlTextLiteral? Anyway we need to visit the expressions in the `textFragments` and the closure resolving logic will handle in visitors related to each expression.

Comment (rpjayasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:975]: Because `xmlTextLiteral.concatExpr` is made from desugaring `textFragments` and I think `textFragments` are no longer used. Only the `xmlTextLiteral.concatExpr` is used.

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:975]: Shall we similarly fix the other XML kinds also?

e.g., the following also fails.

```ballerina
public function main() {
    xml _ = xml `<Books>${xml `<Book><!--${let int y = 5 in y}--></Book>`}</Books>`;
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-negative.bal [hunk 2]
```diff
@@ -84,6 +84,14 @@ class Person {
     }
 }
 
+type A record {
+    int a;
+};
+
+function testLetWithXMLTemplateExpression() {
+    xml x = xml `<Books>${xml `<Book>"${let A y = {a:1} in y}"</Book>`}</Books>`;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-negative.bal:92]:
```suggestion
    xml _ = xml `<Books>${xml `<Book>"${let A y = {a: 1} in y}"</Book>`}</Books>`;
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal [hunk 3]
```diff
@@ -362,6 +362,11 @@ function testLetWithClass() {
     assert(6, foo2.m);
 }
 
+function testLetWithXMLTemplateExpression() {
+    xml x = xml `<Books>${xml `<Book>"${let int y = 5 in y}"</Book>`}</Books>`;
+    assert("<Book>\"5\"</Book>", (x[0]/*).toString());
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal:367]: Shall we try to avoid using `toString()` and assert the actual value? We may lose relevant type info when we assert the string representation.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java [hunk 4]
```diff
@@ -972,14 +972,12 @@ public void visit(BLangXMLElementLiteral xmlElementLiteral) {
...
         xmlTextLiteral.concatExpr = rewriteExpr(xmlTextLiteral.concatExpr);
         result = xmlTextLiteral;
     }
 
     @Override
     public void visit(BLangXMLCommentLiteral xmlCommentLiteral) {
-        xmlCommentLiteral.textFragments.forEach(this::rewriteExpr);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:982]: Need to also fix `BLangXMLQuotedString`.

```ballerina
public function main() {
   xml _ = xml `<Book x="${let int y = 5 in y}"></Book>`;
}
```

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:982]: Shouldn't `concatExpr` be rewritten?

The following still crashes.

```ballerina
public function main() {
   int i = 1;
   xml _ = xml `<Books>${xml `<Book><!--${let function () returns int y = (() => i) in y()}--></Book>`}</Books>`;
}
```

Let's add tests like this for `BLangXMLCommentLiteral`, `BLangXMLTextLiteral`, and `BLangXMLQuotedString`.

Comment (rpjayasekara) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ClosureDesugar.java:982]: It should rewrite. Will fix it

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-negative.bal [hunk 5]
```diff
@@ -84,6 +84,14 @@ class Person {
     }
 }
 
+type A record {
+    int a;
+};
+
+function testLetWithXMLTemplateExpression() {
+    xml _ = xml `<Books>${xml `<Book>"${let A y = {a:1} in y}"</Book>`}</Books>`;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-negative.bal:92]:
```suggestion
    xml _ = xml `<Books>${xml `<Book>"${let A y = {a: 1} in y}"</Book>`}</Books>`;
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal [hunk 6]
```diff
@@ -362,6 +362,25 @@ function testLetWithClass() {
...
+    xml x = xml `<Books>${xml `<Book>"${let int y = 5 in y}"</Book>`}</Books>`;
+    assert(xml `<Book>"5"</Book>`, (x[0]/*));
+}
+
+function testLetExprWithBLangXMLCommentLiteral(){
+    xml x = xml `<Books>${xml `<Book><!--${let int y = 5 in y}--></Book>`}</Books>`;
+    assert(xml `<Book><!--5--></Book>`, (x[0]/*));
+
+    int i = 1;
+    xml z = xml `<Books>${xml `<Book><!--${let function () returns int y = (() => i) in y()}--></Book>`}</Books>`;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/let/let-expression-test.bal:375]: We need to add such tests for the other two kinds also. Or we won't be testing rewriting the concatExpr.

**Review by MaryamZi — APPROVED** [review]

**Review by hasithaa — APPROVED** [review]
