### PR TITLE
[Bindgen] Make improvements to error handling and output messages

### LINKED ISSUE #28584: [Bindgen] Improve and make the output error messages consistent
**Description:**
The output error messages should be made consistent with the other CLI tools. Could use a format like the one given below.
```
error: <error-message>
```
Or could use the format used in the CLI commands.
```
ballerina: <error-message>
```
Decide on finer details such as whether the sentences should start with a simple letter or a capital letter etc.

**Steps to reproduce:**

**Affected Versions:**
SLP Alpha 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by IrushiL**
## Purpose
* Improve error output messages and make them consistent.
* Capture and handle errors encountered when generating functions instead of skipping the entire class.
* Check for diagnostic errors after generating a syntax tree.
* Add output error messages for failed function generations.
* Add missing test cases for error paths.

Fixes #28584

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java [hunk 1]
```diff
@@ -115,13 +117,13 @@ public void execute() {
         }
 
         if (classNames == null) {
-            setOutError("One or more class names should be specified to generate the Ballerina bindings.");
+            setOutError("error: one or more class names are required");
```
Comment (hemikak) [inline misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java:120]: Can we move "error: " prefix to the `setOutError` function ?

File: misc/ballerina-bindgen/src/test/resources/mvn-test-resources/balProject/tests/main_test.bal [hunk 2]
```diff
@@ -0,0 +1,7 @@
+import ballerina/io;
```
Comment (hemikak) [inline misc/ballerina-bindgen/src/test/resources/mvn-test-resources/balProject/tests/main_test.bal:1]: Add copyright header if we usually add them to test files.

File: misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenNodeFactory.java [hunk 3]
```diff
@@ -382,7 +381,7 @@ private static ReturnTypeDescriptorNode getExternalFunctionSignatureReturnType(B
     }
 
     private static boolean isMultiDimensionalArray(String className) {
-        return className.lastIndexOf('[') > 0;
+        return className.codePoints().filter(ch -> ch == '[').count() > 1;
```
Comment (hemikak) [inline misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenNodeFactory.java:384]: Can we use `anyMatch` here ?

Comment (IrushiL) [reply misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/utils/BindgenNodeFactory.java:384]: Here the logic is to check if the count is greater than 1, therefore, it would be difficult to use `anyMatch` here.

File: misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java (hunk 1 above)
Comment (IrushiL) [reply misc/ballerina-bindgen/src/main/java/org/ballerinalang/bindgen/command/BindgenCommand.java]: Done.

File: misc/ballerina-bindgen/src/test/resources/mvn-test-resources/balProject/tests/main_test.bal (hunk 2 above)
Comment (IrushiL) [reply misc/ballerina-bindgen/src/test/resources/mvn-test-resources/balProject/tests/main_test.bal:1]: Most of the test `.bal` files do not seem to contain the copyright header.

**Review by hemikak — APPROVED** [review]
