### PR TITLE
Fix XML template not properly working with query expressions

### LINKED ISSUE #28490: XML template does not work properly with query expressions
Consider the following example

```ballerina
import ballerina/io;


type Person record {|
   string name;
   string country;
|};

function personsToXml(Person[] persons) returns xml {
   return xml`<data>${
      from var {name, country} in Persons
      select xml`<person country="${country}">${name}</person>`
   }</data>`;
}



public function main() {
   Person p = {name: "FDF", country: "FFFF"};
   Person e = {name:"EEEE", country: "EWFRWRFW"}; 
   Person r = {name: "FFDF", country: "FDFD"};
   Person[] arr = [];
   arr.push(p);
   arr.push(e);
   arr.push(r);   
   xml ee = personsToXml(arr);
   io:println(ee);
}
```
When compiling the above code, the following errors are printed. But the program should compile propery and the xml should be printed

```
ERROR [test.bal:(11:7,12:64)] incompatible types: expected '(int|float|decimal|string|boolean|xml)', found 'xml:Element[]'
ERROR [test.bal:(11:16,11:31)] invalid record binding pattern with type 'other'
ERROR [test.bal:(11:35,11:42)] undefined symbol 'Persons'
ERROR [test.bal:(12:37,12:44)] undefined symbol 'country'
ERROR [test.bal:(12:49,12:53)] undefined symbol 'name'
error: compilation contains errors
```

### PR DESCRIPTION
**Pull request by lasinicl**
Fixes #28490

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by grainier — APPROVED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -6201,7 +6201,12 @@ private void checkStringTemplateExprs(List<? extends BLangExpression> exprs, boo
         List<BLangExpression> tempConcatExpressions = new ArrayList<>();
 
         for (BLangExpression expr : exprs) {
-            BType exprType = checkExpr(expr, xmlElementEnv);
+            BType exprType;
+            if (expr.getKind() == NodeKind.QUERY_EXPR) {
+                exprType = checkExpr(expr, xmlElementEnv, expType);
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6206]: what will be the `expType` here?

Comment (lasinicl) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:6206]: xml
