### PR TITLE
Check assigning of array and tuple literals to unions

### LINKED ISSUE #9164: Tuple type able to be assigned to any variable type
**Description:**
A tuple type is allowed to be assigned to any variable type. Compile error should occur at such an instance

**Steps to reproduce:**
Following function compiles and prints `false`
``` ballerina
import ballerina/io;

function main(string... args) {
    boolean x = (3, "A");
    io:println(x);
}
```
**Affected Versions:**
0.975.0

### PR DESCRIPTION
**Pull request by Anoukh**
Fixes #9164

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -270,10 +270,33 @@ public boolean isAssignable(BType source, BType target) {
...
+        if (source.tag == TypeTags.TUPLE || target.tag == TypeTags.TUPLE) {
+            return isTupleTypeAssignable(source, target);
+        }
+
         return source.tag == TypeTags.ARRAY && target.tag == TypeTags.ARRAY &&
                 isArrayTypesAssignable(source, target);
     }
 
+    private boolean isTupleTypeAssignable(BType source, BType target) {
+        if (source.tag == TypeTags.TUPLE && target.tag == TypeTags.TUPLE) {
```
Comment (lankavitharana) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: shall we simply this logic?(like check and return at the begning?)

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 2]
```diff
@@ -1687,11 +1687,19 @@ private void validateVariableDefinition(BLangExpression expr) {
...
         final NodeKind kind = expr.getKind();
         if (kind == NodeKind.RECORD_LITERAL_EXPR || kind == NodeKind.ARRAY_LITERAL_EXPR
                 || (kind == NodeKind.Type_INIT_EXPR && ((BLangTypeInit) expr).userDefinedType == null)) {
             dlog.error(expr.pos, DiagnosticCode.INVALID_ANY_VAR_DEF);
         }
+        if (kind == NodeKind.BRACED_TUPLE_EXPR) {
+            BLangBracedOrTupleExpr bracedOrTupleExpr = (BLangBracedOrTupleExpr) expr;
+            if (bracedOrTupleExpr.expressions.size() > 1 &&
+                    bracedOrTupleExpr.expressions.stream().anyMatch(literal -> literal.getKind() == NodeKind.LITERAL)) {
+                dlog.error(expr.pos, DiagnosticCode.INVALID_ANY_VAR_DEF);
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: we should check the status of the validateVariableDefinition in the caller method and set it's typed to error.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 3]
```diff
@@ -357,31 +357,16 @@ public void visit(BLangArrayLiteral arrayLiteral) {
...
-                            count++;
-                        }
-                    }
-                }
-                if (count > 1) {
-                    dlog.error(arrayLiteral.pos, DiagnosticCode.INVALID_ARRAY_LITERAL, expType);
-                    resultType = symTable.errType;
-                    return;
+            List<BType> arrayCompatibleType = getArrayCompatibleTypes(expType, actualType);
+            if (arrayCompatibleType.stream().anyMatch(t -> t.tag == TypeTags.ANY)) {
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: This check has to be done after Line 366. Also, this should give INVALID_ARRAY_LITERAL error.
