### PR TITLE
Change stream completion type from error|never to error|()

### LINKED ISSUE #29309: [Streams] Remove never from completion type in stream<T,E>
**Description:**
$subject

**Steps to reproduce:**

**Affected Versions:**
sl alpha3

### PR DESCRIPTION
**Pull request by pcnfernando**
So that `stream<T>` and `stream<T, error>` is assignable to `stream<T, error?>`. And `stream<T>` is equivalent to `stream<T, ()>`.

Fixes #29309

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaStreamTypeSymbol.java [hunk 1]
```diff
@@ -50,24 +52,24 @@ public TypeSymbol typeParameter() {
     }
 
     @Override
-    public TypeSymbol completionValueTypeParameter() {
+    public Optional<TypeSymbol> completionValueTypeParameter() {
         if (this.completionValueTypeParameter == null) {
             BType completionType = ((BStreamType) this.getBType()).error;
-            TypesFactory typesFactory = TypesFactory.getInstance(this.context);
-            this.completionValueTypeParameter = typesFactory.getTypeDescriptor(completionType);
+            if (completionType != null) {
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaStreamTypeSymbol.java:58]: This won't be null right? So we don't have to make completion type an Optional<TypeSymbol> right?

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/StreamTypeSymbol.java [hunk 2]
```diff
@@ -36,5 +38,5 @@
      *
      * @return The type of the completion value
      */
-    TypeSymbol completionValueTypeParameter();
+    Optional<TypeSymbol> completionValueTypeParameter();
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/symbols/StreamTypeSymbol.java:41]: Same as above comment

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 3]
```diff
@@ -1163,7 +1163,7 @@ public void visit(BLangRecordTypeNode recordTypeNode) {
     public void visit(BLangStreamType streamTypeNode) {
         BType type = resolveTypeNode(streamTypeNode.type, env);
         BType constraintType = resolveTypeNode(streamTypeNode.constraint, env);
-        BType error = streamTypeNode.error != null ? resolveTypeNode(streamTypeNode.error, env) : symTable.neverType;
+        BType error = streamTypeNode.error != null ? resolveTypeNode(streamTypeNode.error, env) : null;
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1166]: Shall we make this null to `symTable.nilType`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 4]
```diff
@@ -3250,11 +3258,7 @@ private BUnionType createNextReturnType(Location pos, BStreamType streamType) {
 
         LinkedHashSet<BType> retTypeMembers = new LinkedHashSet<>();
         retTypeMembers.add(recordType);
-        List<BType> errorTypes = getTypesList(streamType.error);
-        errorTypes.removeIf(type -> type.tag == TypeTags.NEVER);
-        if (!errorTypes.isEmpty()) {
-            retTypeMembers.addAll(errorTypes);
-        }
+        retTypeMembers.addAll(types.getAllTypes(streamType.error));
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3261]: This `streamType.error`  can be a `()` or a union with `()` right? If so, after executing the following line, there will be 2 `()`s get added to the union type right?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java [hunk 5]
```diff
@@ -475,7 +475,8 @@ private void findTypeParamInTuple(Location loc, BTupleType expType, BTupleType a
     private void findTypeParamInStream(Location loc, BStreamType expType, BStreamType actualType,
                                        SymbolEnv env, HashSet<BType> resolvedTypes, FindTypeParamResult result) {
         findTypeParam(loc, expType.constraint, actualType.constraint, env, resolvedTypes, result);
-        findTypeParam(loc, expType.error, actualType.error, env, resolvedTypes, result);
+        findTypeParam(loc, expType.error, (actualType.error != null) ? actualType.error : symTable.nilType, env,
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java:478]: now that the default value of stream type error is set to nil, `(actualType.error != null)` is redundant

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java [hunk 6]
```diff
@@ -485,7 +486,7 @@ private void findTypeParamInStreamForUnion(Location loc, BStreamType expType, BU
         for (BType type : actualType.getMemberTypes()) {
             if (type.tag == TypeTags.STREAM) {
                 constraints.add(((BStreamType) type).constraint);
-                if (((BStreamType) type).error.tag != TypeTags.NEVER) {
+                if (((BStreamType) type).error != null) {
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java:489]: This is redundant

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java [hunk 7]
```diff
@@ -686,18 +687,9 @@ private BType getMatchingBoundType(BType expType, SymbolEnv env, HashSet<BType>
...
-                        streamError = symTable.neverType;
-                    } else {
-                        streamError = getMatchingOptionalBoundType((BUnionType) streamError, env, resolvedTypes);
-                    }
-                } else if (streamError.tag == TypeTags.ERROR) {
-                    streamError = getMatchingBoundType(streamError, env, resolvedTypes);
-                } else {
-                    streamError = symTable.neverType;
+                BType streamError = getMatchingBoundType(((BStreamType) expType).error , env, resolvedTypes);
+                if (streamError.tag == TypeTags.NONE) {
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java:691]: Shall we add a small comment mentioning that we are intentionally adding nil if the matching bound type is not resolved.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 4 above)
Comment (pcnfernando) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:3261]: since it's a HashSet, there won't be duplicates

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 8]
```diff
@@ -1849,8 +1849,7 @@ private boolean checkNextFuncReturnType(BType returnType) {
             return false;
         }
 
-        List<BType> types = getAllTypes(returnType);
-        types.removeIf(type -> type.tag == TypeTags.NEVER);
+        List<BType> types = new ArrayList<>(((BUnionType) returnType).getMemberTypes());
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:1852]: Why change `getAllTypes(returnType);` to new `ArrayList<>(((BUnionType) returnType).getMemberTypes());`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 9]
```diff
@@ -2514,7 +2513,7 @@ public Boolean visit(BTupleType t, BType s) {
 
         @Override
         public Boolean visit(BStreamType t, BType s) {
-            return s.tag == TypeTags.STREAM && isSameStreamType(s, t, this.unresolvedTypes);
+            return t == s;
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:2516]: Please revisit this change

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java [hunk 10]
```diff
@@ -830,7 +830,7 @@ private void defineCloneableCyclicTypeAndDependentTypes() {
         futureType.constraint = anyOrErrorType;
 
         pureType = BUnionType.create(null, anydataType, errorType);
-        streamType = new BStreamType(TypeTags.STREAM, pureType, neverType, null);
+        streamType = new BStreamType(TypeTags.STREAM, pureType, null, null);
```
Comment (grainier) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java:833]: use `nil` here.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal [hunk 11]
```diff
@@ -387,25 +387,29 @@ function testEmptyStreamConstructs() returns boolean {
...
+
     testPassed = testPassed && (emptyStream5.next() === ());
-    testPassed = testPassed && (emptyStream6.next() === ());
+
     testPassed = testPassed && (emptyStream7.next() === ());
     testPassed = testPassed && (emptyStream8.next() === ());
-    testPassed = testPassed && (emptyStream9.next() === ());
 
-    // test the assignability of stream<int> and stream<int, never>
+    //todo will revisit during unbounded stream implementation
```
Comment (grainier) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal:407]: Shall we add an issue to re-visit these?

Comment (pcnfernando) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/stream/stream-value.bal:407]: https://github.com/ballerina-platform/ballerina-lang/issues/29638

**Review by grainier — APPROVED** [review]
