### PR TITLE
Prevent access to semantic model when the compiler is crashed

### LINKED ISSUE #37293: Track and handle BAD_SAD diagnostics at LS
**Description:**
When a bad sad error occurs, a diagnostic is added with that information. At LS, we should look at that diagnostic and prevent providing functionalities that depend on the compilation. 

**Describe your task(s)**
Under completions, codeactions etc, we should check if the compilation is in a bad sad state. If yes, we should not provide completions/code actions.

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject

Fixes #37293

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java [hunk 1]
```diff
@@ -1145,6 +1158,24 @@ public Project project() {
         public void setProject(Project project) {
             this.project = project;
         }
+
+        /**
+         * Check if the project in a crashed state.
```
Comment (mindula) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java:1163]:
```suggestion
         * Check if the project is in a crashed state.
```

**Review by IMS94 — APPROVED** [review]
LGTM!
