### PR TITLE
Fix context stack recovery when error handler fails with an exception

### LINKED ISSUE #33576: Original context stack is not recovered correctly when error handler fails with an exception
**Description:**
$subject. 

Here we need to set the `this.ctxStack = tempCtxStack;` in the catch block.

https://github.com/ballerina-platform/ballerina-lang/blob/8adfc0ac5b12d60c70d33893a15e49e7eba2920e/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java#L248-L255

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #33576 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java [hunk 1]
```diff
@@ -253,6 +254,8 @@ private Result seekMatch(ParserRuleContext currentCtx) {
                     "seekMatch caught " + exception;
             bestMatch = new Result(new ArrayDeque<>(), LOOKAHEAD_LIMIT - 1);
             bestMatch.solution = new Solution(Action.REMOVE, currentCtx, SyntaxKind.NONE, currentCtx.toString());
+        } finally {
+            this.ctxStack = tempCtxStack;
```
Comment (lochana-chathura) [inline compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/AbstractParserErrorHandler.java:258]: Adding this line at the end of the catch block is enough. Since spotBugs fails with unused variable for L245 added as a finally block.

**Review by rdulmina — APPROVED** [review]

**Review by hasithaa — APPROVED** [review]
