### PR TITLE
[master] Add support for record -> json assignment

### LINKED ISSUE #18697: JSON compatible record to JSON assignment not allowed
Consider the following:
```ballerina
public function main() {
    Person p = {};
    json j = p; // Currently not allowed. Compile error
}

type Person record {|
    string name = "";
    int age = 0;
|};
```
The above case should be allowed. Attempts to add additional fields to the `json` should result in panics.

### LINKED ISSUE #22306: Field access and optional field access not allowed for records assigned to a JSON variable
Consider the following:
```ballerina
import ballerina/io;

public function main() {
    testNestedRecordModification();
}

function testNestedRecordModification() {
    record {|
        string name;
        record {|
            record {|
                int x;
                float...;
            |} nestedL2;
        |} nestedL1;
    |} rec = {
        name: "John",
        nestedL1: {
            nestedL2: {
                x: 100
            }
        }
    };

    json jR = rec;

    json nestedL2 = checkpanic jR.nestedL1.nestedL2;
    map<json> l2M = <map<json>>nestedL2;
    l2M["restF1"] = 12.34;
}
```
Currently the above panics.
```
error: {ballerina}JSONOperationError message=JSON value is not a mapping
	at 18697:testNestedRecordModification(18697.bal:48)
	   18697:main(18697.bal:6)
```
The reason is since the value referred to by `jR` is actually a record, it's not considered a JSON object.

### PR DESCRIPTION
**Pull request by pubudu91**
## Samples
```ballerina
public function main() {
    Person p = {};
    json j = p; // Used to be a compile error
}

type Person record {|
    string name = "";
    int age = 0;
|};
```
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/JSONUtils.java [hunk 1]
```diff
@@ -297,7 +297,8 @@ public static boolean isJSONObject(Object json) {
         }
 
         BType type = ((RefValue) json).getType();
-        return type.getTag() == TypeTags.JSON_TAG || type.getTag() == TypeTags.MAP_TAG;
+        int typeTag = type.getTag();
+        return typeTag == TypeTags.JSON_TAG || typeTag == TypeTags.MAP_TAG || typeTag == TypeTags.RECORD_TYPE_TAG;
```
Comment (MaryamZi) [inline bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/JSONUtils.java]: Not related to this PR, but returning true for `isJSONObject` if ` typeTag == TypeTags.JSON_TAG` is wrong right? And we need to check the map's constraint too assuming this is a generic method.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 2]
```diff
@@ -618,17 +622,34 @@ private boolean isAssignable(BType source, BType target, Set<TypePair> unresolve
...
+        BType targetType;
+        switch (type.tag) {
+            case TypeTags.MAP:
+                targetType = ((BMapType) type).constraint;
+                break;
+            case TypeTags.JSON:
+                targetType = type;
+                break;
+            default:
+                throw new IllegalArgumentException("Incompatible target type: " + type.toString());
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Shouldn't we just return false?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 3]
```diff
@@ -618,17 +622,34 @@ private boolean isAssignable(BType source, BType target, Set<TypePair> unresolve
...
+        }
+
         if (recordType.sealed) {
-            return recordFieldsAssignableToMap(recordType, targetMapType);
+            return recordFieldsAssignableToType(recordType, targetType);
         } else {
-            return isAssignable(recordType.restFieldType, targetMapType.constraint)
-                    && recordFieldsAssignableToMap(recordType, targetMapType);
+            return recordFieldsAssignableToType(recordType, targetType) &&
+                    isAssignable(recordType.restFieldType, targetType);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Shall we move this logic to `recordFieldsAssignableToType`. Rest fields are also record fields?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/RecordToJSONTest.java [hunk 4]
```diff
@@ -0,0 +1,81 @@
+/*
+ *   Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/json/RecordToJSONTest.java]:
```suggestion
 *   Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 2 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Added this default case since I changed the method signature to accept `BType` and wanted to ensure this method is used only in contexts with the supported types (`map` and `json`).

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 3 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: +1.. That'd actually simplify things a bit

File: bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/JSONUtils.java (hunk 1 above)
Comment (pubudu91) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/JSONUtils.java]: Just checked this. It seems simple literals are in their original type, so it doesn't count as a JSON tag. For example, the following works as expected:
```ballerina
import ballerina/io;

public function main() {
    json j1 = 10;
    io:println(j1.name);
}
```
`j1` is a `Long` when you check at this point.

Comment (MaryamZi) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/JSONUtils.java]: Yeah but `typeTag == TypeTags.JSON_TAG` will never be true right?

Comment (pubudu91) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/JSONUtils.java]: Ah just checked it.. yeah, you're right.. for JSON objects, it's `map<json>`.. I'll remove this condition and see..

Comment (pubudu91) [reply bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/JSONUtils.java]: Removed it in 4b4eaeab6e39b5cf11c6e0dbd24855b4643cf582
