### PR TITLE
Fix compiler crashes for raw template with interpolations when used as a default value of a parameter

### LINKED ISSUE #43775: [Bug]: Compiler (BIROptimizer) crashes for raw template with interpolations when used as a default value of a parameter
### Description

$title.

### Steps to Reproduce

```ballerina
type Employee record {|
    string firstName;
    string lastName;
|};

public type RT object {
    *object:RawTemplate;
    public string[] & readonly strings;
    public anydata[] insertions;
};

function fn(Employee e, RT fullName = `${e}`) {
}
```

### Affected Version(s)

2201.11.0-SNAPSHOT

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fixes #43775 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by gimantha — APPROVED** [review]

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithDefaultableParametersTest.java [hunk 1]
```diff
@@ -268,6 +268,11 @@ public void testFuncWithSpreadFieldInMappingConstructorForDefaultValue() {
         BRunUtil.invoke(result, "testFuncWithSpreadFieldInMappingConstructorForDefaultValue");
     }
 
+    @Test
+    public void testFuncWithDefaultRawTemplateValue() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/functions/FunctionsWithDefaultableParametersTest.java:272]: I'd just say RawTemplate, without the Default part.

**Review by MaryamZi — DISMISSED** [review]

**Review by gimantha — APPROVED** [review]
