### PR TITLE
Correct TextRange and LineRange information in diagnostic location

### LINKED ISSUE #25933: TextRange and LineRange information is incorrect in diagnostic locations
See https://github.com/ballerina-platform/ballerina-lang/blob/ee83d258a4a7e95d1e397dcc334793e9fe4c9603/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java#L38

The values set for the columns in line range and the offsets set in text range are incorrect. The text range is supposed to be the absolute position as an offset from (0, 0).

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
Correct TextRange and LineRange information in diagnostic location and its usages

Fixes #25933 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java [hunk 1]
```diff
@@ -35,8 +35,9 @@
     private TextRange textRange;
 
     public BLangDiagnosticLocation(String filePath, int startLine, int endLine, int startColumn, int endColumn) {
-        this.lineRange = LineRange.from(filePath, LinePosition.from(startLine, 0), LinePosition.from(endLine, 0));
-        this.textRange = TextRange.from(startColumn, endColumn - startColumn);
+        this.lineRange = LineRange.from(filePath, LinePosition.from(startLine, startColumn),
+                LinePosition.from(endLine, endColumn));
+        this.textRange = TextRange.from(0, 0);
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java:40]: Is it ok to hard code this? In the compiler we don't have this information. But the syntax errors may have this information right? Or is it using something else?

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java:40]: It uses different `io.ballerinalang.compiler.syntax.tree.Node` to create the text range and parse it when creating `SyntaxDiagnostics`. hardcoding to "0" is done only for now. Will have to change the behaviour later.

**Review by SupunS — APPROVED** [review]
