### PR TITLE
Fix CCE when map json field access

### LINKED ISSUE #37322: CCE when trying to access missing key in map<map<map<json>>>
**Description:**
$title

**Steps to reproduce:**
```ballerina
import ballerina/io;

map<map<map<json>>> x = {};

public function main() {
    io:println(x.__.__);
}
```

Output:
```
[2022-08-09 16:13:42,929] SEVERE {b7a.log.crash} - class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.MapValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.MapValue are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.MapValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.MapValue are in unnamed module of loader 'app')
        at org.sample_project.0.main.main(main.bal:19)
        at org.sample_project.0.$_init.$lambda$main$(sample_project)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:569)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:303)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:270)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Affected Versions:**
2201.0.x, 2201.1.x

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #37322 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 1]
```diff
@@ -9525,7 +9525,19 @@ private void handleSafeNavigation(BLangAccessExpression accessExpr, BType type,
     }
 
     private boolean isMapJson(BType originalType) {
-        return originalType.tag == TypeTags.MAP && ((BMapType) originalType).getConstraint().tag == TypeTags.JSON;
+        if (originalType.tag != TypeTags.MAP) {
+            return false;
+        }
+        BType constraintType = getConstraintType((BMapType) originalType);
+        return constraintType.tag == TypeTags.JSON;
```
Comment (HindujaB) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:9532]: We can refactor this logic like the following.
```java
    private boolean isMapJson(BType originalType) {
        if (originalType.tag == TypeTags.MAP) {
            return isMapJson(((BMapType) originalType).getConstraint());
        }
        return originalType.tag == TypeTags.JSON;
    }
```

Comment (gabilang) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:9532]: This logic is going to return `true` when the `originalType` is `json`. Anyway we can accommodate that by calling `originalType.tag == TypeTags.MAP && isMapJson(originalType)`.

Comment (HindujaB) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:9532]: or we can pass a boolean parameter like 
```java
 private boolean isMapJson(BType originalType, boolean fromMap) {
        if (originalType.tag == TypeTags.MAP) {
            return isMapJson(((BMapType) originalType).getConstraint(), true);
        }
        return originalType.tag == TypeTags.JSON && fromMap;
    }
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 2]
```diff
@@ -9528,8 +9528,11 @@ private void handleSafeNavigation(BLangAccessExpression accessExpr, BType type,
         pushToMatchStatementStack(matchStmt, successClause, pos);
     }
 
-    private boolean isMapJson(BType originalType) {
-        return originalType.tag == TypeTags.MAP && ((BMapType) originalType).getConstraint().tag == TypeTags.JSON;
+    private boolean isMapJson(BType originalType, boolean fromMap) {
+        if (originalType.tag == TypeTags.MAP) {
+            return isMapJson(((BMapType) originalType).getConstraint(), true);
+        }
+        return originalType.tag == TypeTags.JSON && fromMap;
```
Comment (warunalakshitha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:9535]: We can directly return
return (originalType.tag == TypeTags.MAP && isMapJson(((BMapType) originalType).getConstraint(), true)) || 
originalType.tag == TypeTags.JSON && fromMap

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java [hunk 3]
```diff
@@ -9528,8 +9528,9 @@ private void handleSafeNavigation(BLangAccessExpression accessExpr, BType type,
         pushToMatchStatementStack(matchStmt, successClause, pos);
     }
 
-    private boolean isMapJson(BType originalType) {
-        return originalType.tag == TypeTags.MAP && ((BMapType) originalType).getConstraint().tag == TypeTags.JSON;
+    private boolean isMapJson(BType originalType, boolean fromMap) {
+        return originalType.tag == TypeTags.MAP && isMapJson(((BMapType) originalType).getConstraint(), true)
+                || originalType.tag == TypeTags.JSON && fromMap;
```
Comment (Nadeeshan96) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java:9533]: Shall we add parentheses here? Otherwise it is difficult to read.

**Comment by Nadeeshan96** [comment]
LGTM

**Review by HindujaB — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM
