### PR TITLE
Fix choosing incorrect class-method in http:Client

### LINKED ISSUE #37282: [Semantic API] Required parameter information are missing in function type symbol
**Description:**
Refer to the below output values of the `functionSymbol.params()` and `functionSymbol.parameters()`(deprecated) APIs on the same function type symbol. 

Note the the information related to the required parameter `path` is missing (hence showing only 3 parameters), when trying to retrieve using the `params()` API.

Also note that debugger expression evaluation feature is broken for remote method invocations due to the above issue, and therefore this is an update 2 release blocker for the debugger side.
  
## `params()` output
Screenshot 2022-08-05 at 16 58 53

## `parameters()` (deprecated API) output
Screenshot 2022-08-05 at 16 59 13

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #37282

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/expression/MethodCallExpressionEvaluator.java [hunk 1]
```diff
@@ -248,14 +249,20 @@ && modifyName(symbol.getName().get()).equals(className))
                 .findFirst()
                 .map(symbol -> (ClassSymbol) symbol);
     }
-
-    protected Optional<MethodSymbol> findObjectMethodInClass(ClassSymbol classDef, String methodName) {
+    protected Optional<MethodSymbol> findObjectMethodInClass(ClassSymbol classDef,
+                                                             String methodName,
+                                                             Qualifier qualifier) {
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/expression/MethodCallExpressionEvaluator.java:254]: Shouldn't we accept a list/collection of qualifiers instead, as there can be more than one qualifier for a given method?

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/expression/MethodCallExpressionEvaluator.java [hunk 2]
```diff
@@ -164,7 +165,7 @@ private Value invokeObjectMethod(BVariable resultVar) throws EvaluationException
                 throw createEvaluationException(CLASS_NOT_FOUND, className);
             }
 
-            Optional<MethodSymbol> objectMethodDef = findObjectMethodInClass(classDef.get(), methodName);
+            Optional<MethodSymbol> objectMethodDef = findObjectMethodInClass(classDef.get(), methodName, null);
```
Comment (NipunaRanasinghe) [inline misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/expression/MethodCallExpressionEvaluator.java:168]: Shall we have an overloaded method definition for `findObjectMethodInClass` so that we won't have to pass `null` in here?

File: misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/expression/MethodCallExpressionEvaluator.java (hunk 1 above)
Comment (dulajdilshan) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/expression/MethodCallExpressionEvaluator.java:254]: You accept list of qualifiers and we select the function which has all these qualifiers?

Comment (NipunaRanasinghe) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/expression/MethodCallExpressionEvaluator.java:254]: yes exactly. So in your usecase, we can pass a singleton list right?

Comment (dulajdilshan) [reply misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/expression/MethodCallExpressionEvaluator.java:254]: Sure

**Review by NipunaRanasinghe — DISMISSED** [review]
LGTM

**Review by mohanvive — APPROVED** [review]
