### PR TITLE
Fix field access completions

### LINKED ISSUE #34513: No field access completion support for anonymous function call expression
**Description:**
anon

**Steps to reproduce:**
```Ballerina
function testAnon() {
    function (int) returns string myFunc = function(int arg)  returns string {return "abc";};
    string result  = myFunc().<cursor>
}
```
**Affected Versions:**
stage-sl-snapshot

### LINKED ISSUE #34517: No field access completion support for query expressions
**Description:**
qexpr

**Steps to reproduce:**
```Ballerina
function testQueryExpr() {
    int[] arr = [1,2,3];
    int[] intResult = (from int element in arr let int mul = element * 2 select mul).
    
}
```

**Affected Versions:** 
 stage-sl-snapshot

### LINKED ISSUE #34523: No optional field access support for check expression
**Description:**
optional_fieldaccess

**Steps to reproduce:**
```Ballerina
function test() returns error?{
    int? result = (check testCheck())?.<cursor>
}

function testCheck() returns Type2|error {
    return {field1: 0,
    field2: 0};
}
```
**Affected Versions:**
2201.0.0-snapshot

### PR DESCRIPTION
**Pull request by nadeeshaan**
Fixes #34523 
Fixes #34517
Fixes #34513 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java [hunk 1]
```diff
@@ -307,6 +314,28 @@ public FieldAccessCompletionResolver(PositionedOperationContext context) {
...
+                        || ((UnionTypeSymbol) rawType).memberTypeDescriptors().size() != 2) {
+                    break;
+                }
+                List<TypeSymbol> members = ((UnionTypeSymbol) rawType).memberTypeDescriptors().stream()
+                        .map(CommonUtil::getRawType)
+                        .collect(Collectors.toList());
+                List<TypeDescKind> memberTypes = members.stream()
+                        .map(TypeSymbol::typeKind)
+                        .collect(Collectors.toList());
+                if (!memberTypes.contains(TypeDescKind.NIL) || !memberTypes.contains(TypeDescKind.RECORD)) {
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java:328]: We can rewrite line 325 to 330 as below since we know the member list size is 2:
```java
if (members.stream().allMatch(typeSymbol -> typeSymbol.typeKind() == TypeDescKind.NIL || typeSymbol.typeKind() == TypeDescKind.RECORD)) {
   break;
}
```

**Review by IMS94 — CHANGES_REQUESTED** [review]
Implementation looks good. There's a single place we can rewrite differently. Can you check that?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java (hunk 1 above)
Comment (nadeeshaan) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/FieldAccessCompletionResolver.java]: Fixed

**Review by IMS94 — APPROVED** [review]
