### PR TITLE
Disallow additive expression with operands that contain a union of basic types

### LINKED ISSUE #35825: Additive expression allowed with operands of subtypes that contain both xml and string
**Description:**
The [spec](https://ballerina.io/spec/lang/master/#additive-expr) says 

> It is required that either:
>
> - the static type of both operand expressions is a subtype of the same basic type, in which case the static type of the result will be this basic type, modified by the usual [singleton typing](https://ballerina.io/spec/lang/master/#singleton_typing) rules; or
> - **the static type of one operand expression must be a subtype of xml and of the other operand expression must be a subtype of string, in which case the static type of the result is xml.**

**Steps to reproduce:**
But we seem to now allow 
```ballerina
type Strings "A"|"foo";

function errorFunction(string:Char|xml a, xml:Element|Strings b, xml<xml:Comment|xml:Text>|string c) {
    xml _ = a + a; 
    xml _ = a + b; 
    xml _ = a + c; 
    xml _ = b + b; 
    xml _ = b + c; 
    xml _ = c + c; 
}
```

May be related to https://github.com/ballerina-platform/ballerina-lang/pull/35763.

May also have to clarify in the spec if we can allow this instead of disallowing it.

**Affected Versions:**
2201.1.0-SNAPSHOT, current master

### LINKED ISSUE #36003: Additive expression allowed with operands that contain a union of basic types
**Description:**
The [spec](https://ballerina.io/spec/lang/2021R1/#section_6.24) says,
- the static type of both operand expressions is a subtype of the same basic type, in which case this basic type will be the static type of the result, 
But we allow the following scenarios also

```ballerina
import ballerina/io;
public function main() {
    int|float a = 10;
    int|float b = 15.3;
    io:print(a + b); // prints 25
}
```
**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/35825

### PR DESCRIPTION
**Pull request by chiranSachintha**
Fixes #35825
Fixes #36003

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by gimantha — APPROVED** [review]
LGTM

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 1]
```diff
@@ -4274,19 +4278,26 @@ private boolean equalityIntersectionExists(Set<BType> lhsTypes, Set<BType> rhsTy
         return matchFound;
     }
 
-    boolean validNumericTypeExists(BType type) {
-
+    boolean validNumericStringOrXmlTypeExists(BType type, boolean isNumericType) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4281]: Is this the cleanest way to do this? Looks like we are mixing up multiple things. Why can't we have two separate methods for numeric vs string/xml?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4281]: The `isNumericType` param name is also misleading IMO. Reads like it indicates if `type` is a numeric type, but that's now what it represents.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 2]
```diff
@@ -4274,19 +4278,26 @@ private boolean equalityIntersectionExists(Set<BType> lhsTypes, Set<BType> rhsTy
...
+            if (isBasicNumericType(type)) {
+                return true;
+            }
+        } else if (TypeTags.isStringTypeTag(type.tag) || TypeTags.isXMLTypeTag(type.tag)) {
             return true;
         }
+        return validTypeExists(type, isNumericType);
+    }
+
+    boolean validTypeExists(BType type, boolean isNumericType) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4295]: Can we improve the method name? Not self-explanatory/clear atm.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 3]
```diff
@@ -4387,59 +4386,15 @@ boolean validIntegerTypeExists(BType bType) {
...
-                        return false;
-                    }
-                    if (!validStringOrXmlTypeExists(expr.getBType())) {
-                        return false;
-                    }
-                }
-                return true;
-            default:
-                return false;
+    public BType getBasicType(BType type) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4389]: Again, not the best name since we are only handling certain kinds of types.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 4]
```diff
@@ -4387,59 +4386,15 @@ boolean validIntegerTypeExists(BType bType) {
...
+        if (TypeTags.isIntegerTypeTag(type.tag) || type.tag == TypeTags.BYTE) {
+            return symTable.intType;
+        } else if (TypeTags.isStringTypeTag(type.tag)) {
+            return symTable.stringType;
+        } else if (TypeTags.isXMLTypeTag(type.tag)) {
+            return symTable.xmlType;
+        } else {
+            return type;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4397]: Else ifs can be ifs. Last else is not required.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 3 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4389]: Any suggestion for this?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 1 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Create separate methods

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 2 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: Removed this method.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java (hunk 3 above)
Comment (chiranSachintha) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java]: changed to `getBasicTypeOfBuiltinSubtype`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 5]
```diff
@@ -4340,16 +4343,66 @@ boolean validNumericTypeExists(BType type) {
         }
     }
 
-    private boolean checkValidNumericTypesInUnion(BType memType, int firstTypeTag) {
-        if (memType.tag != firstTypeTag && !checkTypesBelongToInt(memType.tag, firstTypeTag)) {
-            return false;
+    boolean validStringOrXmlTypeExists(BType type) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4346]: Isn't this a duplicate of `validNumericTypeExists` with just minor changes? Can't we rewrite this in a better way, minimizing duplicate code? Maybe using functional interfaces.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 6]
```diff
@@ -4274,19 +4278,12 @@ private boolean equalityIntersectionExists(Set<BType> lhsTypes, Set<BType> rhsTy
...
 
-    boolean validNumericTypeExists(BType type) {
-
-        if (type.isNullable() && type.tag != TypeTags.NIL) {
-            type = getSafeType(type, true, false);
-        }
-        if (isBasicNumericType(type)) {
-            return true;
-        }
+    boolean validNumericStringOrXmlTypeExists(BType type, ValidateType validateType) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:4281]: We should probably use something like `ValidationFunction`.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java [hunk 7]
```diff
@@ -6039,6 +5998,15 @@ private interface TypeEqualityPredicate {
         boolean test(BType source, BType target, Set<TypePair> unresolvedTypes);
     }
 
+    /**
+     * A functional interface for validate numeric, string or xml type exists.
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java:6002]:
```suggestion
     * A functional interface to validate numeric, string, or xml type existence.
```

**Review by MaryamZi — COMMENTED** [review]
@chiranSachintha, please fix the suggestions in a separate PR.
