### PR TITLE
Reimplement old function mocking

### LINKED ISSUE #28410: [Testerina] Function mocking throws NullPointer when used to initialize global values
**Description:**

NPE is thrown when function mocking is used to initialize global values

A temporary workaround would be to move the initialization inside another function

```
[2021-02-03 10:54:50,394] SEVERE {b7a.log.crash} - java.lang.NullPointerException 
org.ballerinalang.test.runtime.exceptions.BallerinaTestException: java.lang.NullPointerException
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:54)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:543)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:264)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:115)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:75)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:70)
	at org.ballerinalang.test.runtime.Main.main(Main.java:54)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by Ibaqu**
## Purpose
Reimplement the old function mocking to be compatible with functions that initialize global variables

Fixes #28410

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/MockAnnotationProcessor.java [hunk 1]
```diff
@@ -122,6 +134,95 @@ public void process(SimpleVariableNode simpleVariableNode, List<AnnotationAttach
...
+                        if (MODULE.equals(name)) {
+                            value = formatPackageName(value, parent);
+                            vals[0] = value;
+                        } else if (FUNCTION.equals(name)) {
+                            vals[1] = value;
+                        }
+                    });
+
+                    // Check if Function in annotation is empty
+                    if (vals[1].isEmpty()) {
```
Comment (keizer619) [inline misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/MockAnnotationProcessor.java:184]: Can this cause NPE  ?

Comment (Ibaqu) [reply misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/MockAnnotationProcessor.java:184]: I just verified it. Yes. If you provide only the `moduleName` and forget to put the `functionName` in the annotation an NPE is thrown. I will change the implementation.

Comment (Ibaqu) [reply misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/MockAnnotationProcessor.java:183]: I initialized vals[1] with an empty by default so that the NPE wouldnt arise. 

But ideally, the default value provided in the mock annotation should be applied in this case.

**Review by Dilhasha — APPROVED** [review]

**Review by keizer619 — APPROVED** [review]
