### PR TITLE
Add support for record literals with mapping binding patterns and fix using mapping-binding pattern within a list binding pattern against an open record

### LINKED ISSUE #19804: Re-enable support for using mapping constructors with record binding patterns
Support for using record binding patterns with mapping constructors was removed with https://github.com/ballerina-platform/ballerina-lang/pull/11053/commits/009046794e35f5ea8ab3c986176b2248734be762

Need  to re-enable this. I had a quick look at this, with the check added here to disable the support removed. It seems to be working. Need to test more and re-enable.

### LINKED ISSUE #39324: [Bug]: Can't use a mapping binding pattern within a list binding pattern against an open record
### Description

$title.

### Steps to Reproduce

```ballerina
public function main() {
    [record { int a; int b; }] r = [{a: 1, b: 2}];

    int a;
    int b;
    {a, b} = r[0]; // OK

    [{a, b}] = r; // error
}
```

```cmd
$ bal run test.bal 
Compiling source
        test.bal
ERROR [test.bal:(8:16,8:17)] incompatible types: expected '[record {| int a; int b; |}]', found '[record {| int a; int b; anydata...; |}]'
```

Seems like the type computed for the mapping binding pattern here is a closed record.

### Affected Version(s)

2201.3.2

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #39324 
Fixes #19804

Original PR: https://github.com/ballerina-platform/ballerina-lang/pull/40113 (invalidated)

### Encountered the following issue
- https://github.com/ballerina-platform/ballerina-lang/issues/41174

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by MaryamZi** [comment]
Please update the title to reflect what's actually being fixed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -2980,8 +2980,7 @@ public void visit(BLangRecordVarRef varRefExpr, AnalyzerData data) {
                                            SOURCE);
 
         if (restParam == null) {
-            bRecordType.sealed = true;
-            bRecordType.restFieldType = symTable.noType;
+            bRecordType.restFieldType = symTable.anydataType;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java:2983]: Still won't work for 

```ballerina
public function main() {
    [record { int a; int b; stream<int> c; }] r = [{a: 1, b: 2, c: new}];

    int a;
    int b;
    {a, b} = r[0]; // OK

    [{a, b}] = r; // error
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 2]
```diff
@@ -369,6 +369,23 @@ function testMappingBindingWithSingleNameFieldBinding() {
...
+
+        [{a, b}] = r1;
+        [record {int a; int b;}] v = r1;
+
+        [Some, Some] r2 = [{var1: "A", var2: "B"}, {var1: "C", var2: "D"}];
+
+        string y1;
+        string y2;
+
+        [{var1: y1}, {var1: y2}] = r2;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:386]: Formatting is off.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 3]
```diff
@@ -369,6 +369,23 @@ function testMappingBindingWithSingleNameFieldBinding() {
     assertEquality("bar4", b);
 }
 
+function testMappingBindingPatternInsideTupleBinding() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:372]: Let's move these to list (tuple) binding pattern tests.

```suggestion
function testMappingBindingPatternInListBindingPattern() {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 4]
```diff
@@ -369,6 +369,23 @@ function testMappingBindingWithSingleNameFieldBinding() {
...
+    [record {int a; int b;}] r1 = [{a: 1, b: 2}];
+
+        int a;
+        int b;
+
+        [{a, b}] = r1;
+        [record {int a; int b;}] v = r1;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:379]: Also add tests with arrays on the RHS.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 5]
```diff
@@ -369,6 +369,40 @@ function testMappingBindingWithSingleNameFieldBinding() {
...
+
+    [{id, fname, lname}, {id: nextId, age}] = [{id: "u1001", fname: "John", lname: "doe"}, {id: "xVar", age: 10}];
+
+    int p1;
+    int p2;
+    int p3;
+    int p4;
+    int p5;
+
+    [[{p1, p2}], [[{p3, p4}], {p5}]] = [[{p1: 10, p2: 12}], [[{p3: 13, p4: 14}], {p5: 15}]];
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:403]: Add tests for mapping binding patterns in 

i. mapping binding patterns - not directly related to this fix because how it is type checked, but goes through the modified path
ii. error binding patterns - this fails at the moment due to a different issue (https://github.com/ballerina-platform/ballerina-lang/issues/40312), but let's add a simple test because it compiles now and keep it disabled/commented out

```ballerina
function fn(error<record { record { int a; } x; }> r) {
    int a;
    error(x = {a}) = r;
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 6]
```diff
@@ -369,6 +369,57 @@ function testMappingBindingWithSingleNameFieldBinding() {
     assertEquality("bar4", b);
 }
 
+function testMappingBindingPatternInListBindingPattern() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:372]: Name is no longer accurate?

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:372]: Let's also update the name to reflect the actual test scenario. i.e., when used with an open record. The name is too vague atm.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 7]
```diff
@@ -369,6 +369,57 @@ function testMappingBindingWithSingleNameFieldBinding() {
...
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:373]: Unnecessary new line?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 8]
```diff
@@ -369,6 +369,57 @@ function testMappingBindingWithSingleNameFieldBinding() {
...
+    [Some, Some] r1 = [{var1: "A", var2: "B"}, {var1: "C", var2: "D"}];
+
+    [record {int a; int b;}] r2 = [{a: 1, b: 2}];
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:376]: Reorder/move variables closer to usage.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 9]
```diff
@@ -369,6 +369,57 @@ function testMappingBindingWithSingleNameFieldBinding() {
...
+    // TODO: Uncomment after fixing #40312
+    // int d;
+    // error<record { record { int d; } x; }> err = error("Transaction Failure", x = {d: 0});
+
+    // error(x = {d}) = err;
+}
+
+function getMap() returns record {record {int p1; int p2;} p3;} {
+    return {p3: {p1: 2, p2: 3}};
+}
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:421]: Can be an expression-bodied function.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 10]
```diff
@@ -369,6 +369,44 @@ function testMappingBindingWithSingleNameFieldBinding() {
     assertEquality("bar4", b);
 }
 
+function testMappingBindingPatternWithinOtherStructs() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:372]:
```suggestion
function testMappingBindingPatternsAsMemberBindingPatterns() {
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 11]
```diff
@@ -369,6 +369,44 @@ function testMappingBindingWithSingleNameFieldBinding() {
...
+    [Some, Some] r1 = [{var1: "A", var2: "B"}, {var1: "C", var2: "D"}];
+    string xVar1;
+    string xVar2;
+    [{var1: xVar1}, {var1: xVar2}] = r1;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:376]: We need to assert the values.

**Comment by dulajdilshan** [comment]
Experiencing an NPE in ballerina runtime for the following
```
public function main() {
  int a;
  int b;
  [{a, b}] = [{a: 10, b: 11}];
}
```

**Comment by dulajdilshan** [comment]
> Experiencing an NPE in ballerina runtime for the following
> 
> ```
> public function main() {
>   int a;
>   int b;
>   [{a, b}] = [{a: 10, b: 11}];
> }
> ```
> 
> Working on fixing it

This issue seems to be fixe via https://github.com/ballerina-platform/ballerina-lang/pull/37184

**Comment by dulajdilshan** [comment]
> This scenario seems to be fixed via #37184

Had a chat with @MaryamZi and @chiranSachintha. It seems this scenario needs to be disallowed

**Comment by dulajdilshan** [comment]
@MaryamZi Seems like, we better disallow having list-constructor in list binding-pattern

**Comment by MaryamZi** [comment]
> @MaryamZi Seems like, we better disallow having a list-constructor in list binding-pattern

Can you explain why we should consider doing that?

**Comment by dulajdilshan** [comment]
> Can you explain why we should consider doing that?

Had a live discussion with Maryam, and we thought to go with disallowing having record literals within the list-constr in list BP

**Comment by dulajdilshan** [comment]
Depriorotized for now. Will get back to this soon.

**Comment by dulajdilshan** [comment]
closing this for now, will re-open once started again

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 12]
```diff
@@ -2341,6 +2342,16 @@ public void visit(BLangTupleDestructure tupleDeStmt, AnalyzerData data) {
 
         setTypeOfVarRef(tupleDeStmt.varRef, data);
 
+        if (tupleDeStmt.expr.getKind() == LIST_CONSTRUCTOR_EXPR) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2345]: The error is logged for the following also. That's not necessary?

```ballerina
type Record record {|
    int a;
|};

public function main() {
    Record x;
    [x] = [{a: 1}];
}
```

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 13]
```diff
@@ -369,6 +369,69 @@ function testMappingBindingWithSingleNameFieldBinding() {
     assertEquality("bar4", b);
 }
 
+function testMappingBindingPatternsAsMemberBindingPatterns() {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:372]: The name doesn't reflect testing with open records IMO.

Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:372]: I would also include tests with open records with an explicit rest descriptor.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2345]: We have avoided having record literals for record destructures by logging an error. We had a live discussion on this and came to conclusion to avoid having record literals within a list destructure for scenarios with mapping BP within list BP.

[the remark this answers is not in the document]
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2345]: But, as a second thought, we should allow this.

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 14]
```diff
@@ -1246,6 +1246,9 @@ error.invalid.usage.of.keyword=\
 error.invalid.list.binding.pattern=\
   invalid list binding pattern; member variable count mismatch with member type count
 
+error.record.literal.within.list.constr.not.supported.in.list.bp=\
+    record literal within list constructor is not supported in list binding pattern
```
[the remark this answers is not in the document]
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: Removed the error text

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 12 above)
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: This is fixed now

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal (hunk 13 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:372]: Do you mean something like this?
```ballerina
[record {int x; int y;}] [{...x}] = [{x: 1, y: 2}];
```

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:372]: No. 

> open records with an explicit rest descriptor

```ballerina
record {| int x; int y; anydata...; |}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 15]
```diff
@@ -2347,6 +2350,61 @@ public void visit(BLangTupleDestructure tupleDeStmt, AnalyzerData data) {
...
+        int noOfNonRestVars = tupleVars.size();
+
+        for (BLangExpression expr: exprs) {
+            int remainingNonRestVars = noOfNonRestVars - nonRestTupleVarIndex;
+
+            if (remainingNonRestVars == 0) {
+                return;
+            }
+
+            // remainingNonRestVars > 0
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2375]: Self-explanatory, right?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_negative.bal [hunk 16]
```diff
@@ -46,3 +46,16 @@ function tupleDestructureTest4() returns [int, int] {
     [a, b] = x;
     return [a, b];
 }
+
+function tupleDestructureTest5() returns [int, int] {
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_negative.bal:50]: return type is unnecessary?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 17]
```diff
@@ -2347,6 +2350,61 @@ public void visit(BLangTupleDestructure tupleDeStmt, AnalyzerData data) {
...
+
+                nonRestTupleVarIndex = nonRestTupleVarIndex + noOfSpreadMembers;
+                continue;
+            }
+
+            BLangExpression tupleMemberVar = tupleVars.get(nonRestTupleVarIndex++);
+            if (expr.getKind() == LIST_CONSTRUCTOR_EXPR && tupleMemberVar.getKind() == TUPLE_VARIABLE_REF) {
+                analyzeListConstrExprInTupleDestructure(
+                        (BLangTupleVarRef) tupleMemberVar, (BLangListConstructorExpr) expr);
+                continue;
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2402]: May have to handle errors also accordingly.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java [hunk 18]
```diff
@@ -423,6 +423,8 @@ public enum DiagnosticErrorCode implements DiagnosticCode {
             "invalid.field.binding.pattern.with.non.required.field"),
     INFER_SIZE_ONLY_SUPPORTED_IN_FIRST_DIMENSION("BCE2654", "infer.size.only.supported.in.the.first.dimension"),
     FUNCTION_CALL_SYNTAX_NOT_DEFINED("BCE2655", "function.call.syntax.not.defined"),
+    RECORD_LITERAL_WITHIN_LIST_CONSTR_NOT_SUPPORTED_IN_LIST_BP("BCE2656",
+            "record.literal.within.list.constr.not.supported.in.list.bp"),
```
[the remark this answers is not in the document]
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:427]: Not in used. removed it.

[the remark this answers is not in the document]
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java:427]: This enum is not used. Removed.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 19]
```diff
@@ -2347,6 +2350,61 @@ public void visit(BLangTupleDestructure tupleDeStmt, AnalyzerData data) {
...
+                return;
+            }
+
+            // remainingNonRestVars > 0
+            if (expr.getKind() == NodeKind.LIST_CONSTRUCTOR_SPREAD_OP) {
+                BLangExpression spreadOpExpr = ((BLangListConstructorSpreadOpExpr) expr).expr;
+                int noOfSpreadMembers = switch (spreadOpExpr.getBType().tag) {
+                    case TypeTags.ARRAY -> {
+                        BArrayType spreadArrayType = (BArrayType) spreadOpExpr.getBType();
+                        yield spreadArrayType.size;
```
[the remark this answers is not in the document]
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2380]: Solved

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 20]
```diff
@@ -2347,6 +2350,60 @@ public void visit(BLangTupleDestructure tupleDeStmt, AnalyzerData data) {
...
+
+        for (BLangExpression expr: exprs) {
+            int remainingNonRestVars = noOfNonRestVars - nonRestTupleVarIndex;
+
+            if (remainingNonRestVars == 0) {
+                return;
+            }
+
+            if (expr.getKind() == NodeKind.LIST_CONSTRUCTOR_SPREAD_OP) {
+                BLangExpression spreadOpExpr = ((BLangListConstructorSpreadOpExpr) expr).expr;
```
Comment (poorna2152) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2376]: Can't we simplify and reduce calls to getBType() function by  making `spreadOpType`as the variable than `spreadOpExpr`.
```suggestion
                BType spreadOpType = ((BLangListConstructorSpreadOpExpr) expr).expr.getBType();

```

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2376]: Good catch

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 21]
```diff
@@ -2347,6 +2350,61 @@ public void visit(BLangTupleDestructure tupleDeStmt, AnalyzerData data) {
         if (type.tag != TypeTags.SEMANTIC_ERROR) {
             checkTupleVarRefEquivalency(tupleDeStmt.pos, tupleDeStmt.varRef,
                                         tupleDeStmt.expr.getBType(), tupleDeStmt.expr.pos, data);
+            if (tupleDeStmt.expr.getKind() == LIST_CONSTRUCTOR_EXPR) {
```
[the remark this answers is not in the document]
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2353]: For error destructuring, it was already enabled.

```ballerina
type RecType record {|
    [Value] values;
|};

type Value record {|
    int one;
    int two;
|};

type SampleError error<RecType>;

function testErrorBP() {
    var error RecType(_, cause3, values = [{one, two}]) = <SampleError> error("Update Fail", error("DB Error"), values = [{one: 1, two: 2}]);
}
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 17 above)
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2401]: https://github.com/ballerina-platform/ballerina-lang/pull/40283#discussion_r1481183514

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 22]
```diff
@@ -2347,6 +2350,60 @@ public void visit(BLangTupleDestructure tupleDeStmt, AnalyzerData data) {
...
+                if (remainingNonRestVars < noOfSpreadMembers) {
+                    return;
+                }
+
+                nonRestTupleVarIndex += noOfSpreadMembers;
+                continue;
+            }
+
+            BLangExpression tupleMemberVar = tupleVars.get(nonRestTupleVarIndex++);
+            if (expr.getKind() == LIST_CONSTRUCTOR_EXPR && tupleMemberVar.getKind() == TUPLE_VARIABLE_REF) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2398]: Codecov warning?

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2398]: The following test covers this.

```
[[e7, e8]] = [[...[...[employee1, employee2]]]];
```

already added to https://github.com/ballerina-platform/ballerina-lang/pull/40283/files#diff-134c57a0d31d5ced27fd93ca77e8b0c17998533bcd4e91666477901565e5ead3

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 23]
```diff
@@ -2355,6 +2358,58 @@ public void visit(BLangTupleDestructure tupleDeStmt, AnalyzerData data) {
...
+                };
+
+                // remainingNonRestVars < noOfSpreadMembers case is ignored since it is already invalid scenario
+
+                nonRestTupleVarIndex += noOfSpreadMembers;
+                continue;
+            }
+
+            BLangExpression tupleMemberVar = tupleVars.get(nonRestTupleVarIndex++);
+            if (expr.getKind() == LIST_CONSTRUCTOR_EXPR && tupleMemberVar.getKind() == TUPLE_VARIABLE_REF) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2404]: Exteact `expr.getKind()` (used above also) and `tupleMemberVar.getKind()` out to variables.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 24]
```diff
@@ -2355,6 +2358,58 @@ public void visit(BLangTupleDestructure tupleDeStmt, AnalyzerData data) {
...
+                        yield spreadArrayType.size;
+                    }
+                    case TypeTags.TUPLE -> {
+                        BTupleType spreadTupleType = (BTupleType) spreadOpType;
+                        yield spreadTupleType.getTupleTypes().size();
+                    }
+                    default -> 0;
+                };
+
+                // remainingNonRestVars < noOfSpreadMembers case is ignored since it is already invalid scenario
```
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2397]: Do we have a simple test for this?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 25]
```diff
@@ -369,6 +369,74 @@ function testMappingBindingWithSingleNameFieldBinding() {
     assertEquality("bar4", b);
 }
 
+function testMappingBindingPatternAgainstOpenRecordInTupleDestructuring() {
+    [Some, Some] r1 = [{var1: "A", var2: "B"}, {var1: "C", var2: "D"}];
+    string xVar1;
+    string xVar2;
+    [{var1: xVar1}, {var1: xVar2}] = r1;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:376]: Not sure if the variable names are ideal. i.e., binding var1 to something that includes Var2 when there's a var2 field.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 26]
```diff
@@ -369,6 +369,74 @@ function testMappingBindingWithSingleNameFieldBinding() {
...
+    assertEquality("A", xVar1);
+    assertEquality("C", xVar2);
+
+    [record {int a; int b;}] r2 = [{a: 1, b: 2}];
+    int a;
+    int b;
+    [{a, b}] = r2;
+    assertEquality(1, a);
+    assertEquality(2, b);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:385]: In addition to this, let's add one where the value has rest fields.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 27]
```diff
@@ -369,6 +369,74 @@ function testMappingBindingWithSingleNameFieldBinding() {
...
+    assertEquality(12, p2);
+    assertEquality(13, p3);
+    assertEquality(14, p4);
+    assertEquality(15, p5);
+
+    [record {| int a; int b; anydata...; |}] r6 = [{a: 1, b: 2}];
+    [{a, b}] = r6;
+    assertEquality(1, a);
+    assertEquality(2, b);
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:424]: Same comment as above to include one where the value has rest fields.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_negative.bal [hunk 28]
```diff
@@ -46,3 +46,16 @@ function tupleDestructureTest4() returns [int, int] {
     [a, b] = x;
     return [a, b];
 }
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_negative.bal:49]: Add comments for these tests too, to say temporary.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal [hunk 29]
```diff
@@ -109,3 +109,23 @@ function tupleDestructureTest9() returns [boolean, string, [int, float]] {
...
+    Employee e4;
+    [e3, e4] = [...[employee1, employee2]];
+
+    Employee e5;
+    Employee e6;
+    [[e5, e6]] = [...[...[employees]]];
+
+    Employee e7;
+    Employee e8;
+    [[e7, e8]] = [[...[...[employee1, employee2]]]];
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal:130]: Why aren't we asserting anything?

Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal:131]: Added assertion in the java side

Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal:131]: Why are we doing it on the Java side? The practice is to assert in b7a.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal [hunk 30]
```diff
@@ -109,3 +109,26 @@ function tupleDestructureTest9() returns [boolean, string, [int, float]] {
 
     return [a, b, c];
 }
+
+// TODO: This is temporary. Remove this once #42352 gets fixed
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal:113]: Why does this have to be removed and how is this relevant to #42352?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal (hunk 26 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:385]: Were these added?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleDestructureTest.java [hunk 31]
```diff
@@ -98,8 +106,17 @@ public void testNegativeTupleDestructure() {
                 "string...]'", 30, 17);
         BAssertUtil.validateError(resultNegative, i++, "incompatible types: expected '[int,string[]]', found '[int," +
                 "string...]'", 38, 14);
-        BAssertUtil.validateError(resultNegative, i, "incompatible types: expected '[int,int]', found '[int,int," +
+        BAssertUtil.validateError(resultNegative, i++, "incompatible types: expected '[int,int]', found '[int,int," +
                 "int]'", 46, 14);
+
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleDestructureTest.java:111]: Unnecessary empty line.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleDestructureTest.java [hunk 32]
```diff
@@ -87,6 +87,14 @@ public void testTupleDestructure() {
         Assert.assertEquals(returns.get(0).toString(), "true");
         Assert.assertEquals(returns.get(1).toString(), "string value");
         Assert.assertEquals(returns.get(2).toString(), "[25,12.5]");
+
+        // TODO: This is temporary. Remove this once #42352 gets fixed
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleDestructureTest.java:91]: ?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 24 above)
[the remark this answers is not in the document]
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2400]: Have you added this as a test?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 33]
```diff
@@ -2355,6 +2359,61 @@ public void visit(BLangTupleDestructure tupleDeStmt, AnalyzerData data) {
...
                                         tupleDeStmt.expr.getBType(), tupleDeStmt.expr.pos, data);
+            if (tupleDeStmt.expr.getKind() == LIST_CONSTRUCTOR_EXPR) {
+                analyzeDestructuringWithListBindingPattern(tupleDeStmt.varRef,
+                        (BLangListConstructorExpr) tupleDeStmt.expr);
+            }
+        }
+    }
+
+    // TODO: This is temporary. Remove this once #42352 gets fixed
+    private void analyzeDestructuringWithListBindingPattern(BLangTupleVarRef tupleVarRef,
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2370]:
```suggestion
    private void disallowDestructuringMappingConstructorToMappingBindingPattern(BLangTupleVarRef tupleVarRef,
```

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2370]: No errors logged for something like

```
[{name: n2}, {name: n3}, {name: n4}] = [...[{name: "", id: 0}, {name: "", id: 0}, {name: "", id: 0}]];
```

which was previously also an error.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal (hunk 29 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal:131]: We can do this for just the new code being added.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 24 above)
[the remark this answers is not in the document]
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2400]: We already have similar negative tests for this. Do we need to add with this change as well?

e.g.:
https://github.com/ballerina-platform/ballerina-lang/blob/dc1845940f94e37a33124d55266705f2291f2561/tests/jballerina-unit-test/src/test/resources/test-src/expressions/listconstructor/list_constructor_spread_op_negative.bal

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal (hunk 26 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:385]: I have added L387-L390

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal (hunk 29 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal:131]: I thought of aligning with the other tests. I'll add it.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal (hunk 30 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal:113]: The idea is to have this function implemented to report an error aligning with previous behaviour.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleDestructureTest.java (hunk 32 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/tuples/TupleDestructureTest.java:91]: My bad. Will correct this

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal (hunk 30 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal:113]: We don't have to remove this though? It's the negative test that has to be removed?

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal (hunk 29 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal:133]: Fixed

**Comment by dulajdilshan** [comment]
After this gets merged, need to fix this https://github.com/ballerina-platform/ballerina-lang/issues/42595

**Comment by MaryamZi** [comment]
> After this gets merged, need to fix #42595

What we decided was to enable that with this change, right? We shouldn't be allowing partially.

File: tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal (hunk 30 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/types/tuples/tuple_destructure_test.bal]: Removed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 33 above)
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java]: Now we support this, hence fixed

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 34]
```diff
@@ -2387,11 +2387,6 @@ public void visit(BLangRecordDestructure recordDeStmt, AnalyzerData data) {
         typeChecker.checkExpr(recordDeStmt.varRef, currentEnv, symTable.noType, data.prevEnvs,
                 data.commonAnalyzerData);
 
-        if (recordDeStmt.expr.getKind() == RECORD_LITERAL_EXPR) {
-            // TODO: 10/18/18 Need to support record literals as well
-            dlog.error(recordDeStmt.expr.pos, DiagnosticErrorCode.INVALID_RECORD_LITERAL_BINDING_PATTERN);
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2392]: Can't we remove INVALID_RECORD_LITERAL_BINDING_PATTERN and the relevant entry in compiler.properties?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/RecordVariableReferenceTest.java [hunk 35]
```diff
@@ -136,43 +136,17 @@ public void testRestParameterType() {
...
+    public void testVarAssignmentOfRecordLiteral() {
+        BRunUtil.invoke(result, "testVarAssignmentOfRecordLiteral1");
+        BRunUtil.invoke(result, "testVarAssignmentOfRecordLiteral2");
+        BRunUtil.invoke(result, "testVarAssignmentOfRecordLiteral3");
+        BRunUtil.invoke(result, "testVarAssignmentOfRecordLiteral4");
+        BRunUtil.invoke(result, "testVarAssignmentOfRecordLiteral5");
+        BRunUtil.invoke(result, "testVarAssignmentOfRecordLiteral6");
+        BRunUtil.invoke(result, "testVarAssignmentOfRecordLiteral7");
+        BRunUtil.invoke(result, "testVarAssignmentOfRecordLiteral8");
+    }
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/varref/RecordVariableReferenceTest.java:149]: The usual practice is to use a data provider, so that the rest of the tests can run even when one fails.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/GroupByClauseTest.java [hunk 36]
```diff
@@ -248,8 +248,9 @@ public void testNegativeCases() {
                 65, 33);
         BAssertUtil.validateError(negativeResult, i++, "incompatible types: expected '[int,int]', found '[int...]'",
                 70, 36);
-        BAssertUtil.validateError(negativeResult, i++, "record literal is not supported for record binding pattern",
+        BAssertUtil.validateError(negativeResult, i++, "incompatible types: expected 'record type', found 'other'",
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/GroupByClauseTest.java:251]: This is an unnecessary error, since it doesn't add value.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 37]
```diff
@@ -191,56 +191,188 @@ function testRestParameterType() returns boolean {
...
+    boolean married;
+    int theAge;
+    string format;
 
-//function testVarAssignmentOfRecordLiteral() returns (string, boolean, int, string) {
-//    string fName;
-//    boolean married;
-//    int theAge;
-//    string format;
-//    map theMap;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:209]: Why aren't we (fixing and) adding theMap also?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal (hunk 26 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:517]: Can you point to the updated line numbers?

Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:517]: L355..L371

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal (hunk 37 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:209]: it's handled in other test scenarios.

File: tests/jballerina-unit-test/src/test/resources/test-src/query/query-action.bal [hunk 38]
```diff
@@ -882,6 +882,17 @@ function testQueryActionWithCollectClauseInsideLeClause2() {
     };
 }
 
+function testRecordDestructureWithRecordLiteralInsideDoClause() {
+    int[] prices;
+    _ = from var {name, price} in [{name: "John", price: 10}]
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/query/query-action.bal:887]: Can we make this a more meaningful test with a few more entries?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/GroupByClauseTest.java [hunk 39]
```diff
@@ -248,8 +248,6 @@ public void testNegativeCases() {
                 65, 33);
         BAssertUtil.validateError(negativeResult, i++, "incompatible types: expected '[int,int]', found '[int...]'",
                 70, 36);
-        BAssertUtil.validateError(negativeResult, i++, "record literal is not supported for record binding pattern",
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/GroupByClauseTest.java:251]: Wasn't this test removed from the bal file?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 40]
```diff
@@ -191,56 +191,188 @@ function testRestParameterType() returns boolean {
...
+    assertEquality(true, married);
+    assertEquality(12, age.get("age"));
+    assertEquality("Y", age.get("format"));
+}
+
+function testVarAssignmentOfRecordLiteral4() returns error? {
+    string fName;
+    boolean married;
+    json age;
+    map<anydata> theMap;
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:275]: For one, let's make this map<any|error>.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 41]
```diff
@@ -191,56 +191,188 @@ function testRestParameterType() returns boolean {
...
+            department: {
+                id: 123,
+                name: "Marketing",
+                location: {floor: 2, area: "B"}
+            }
+        }
+    };
+    assertEquality(1, id);
+    assertEquality("John Doe", name);
+    assertEquality(2, (<map<anydata>>(<map<anydata>>otherDetails.get("department")).get("location")).get("floor"));
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:374]: Why isn't the whole thing being asserted?

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal (hunk 26 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:517]: Not exactly what I suggested? Please add a simple test like this with rest fields.

Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:534]: Added. L543...L546

**Comment by MaryamZi** [comment]
Please fix the build/test failures.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal (hunk 26 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:534]: What I meant was like just

```ballerina
[record {int a; int b;}] r2 = [{a: 1, b: 2, "c": "three", "d": 4}];
```

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/GroupByClauseTest.java (hunk 39 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/query/GroupByClauseTest.java:251]: It's removed. `tests/jballerina-unit-test/src/test/resources/test-src/query/group_by_clause_negative.bal` L74:82

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal (hunk 26 above)
Comment (MaryamZi) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:534]: That's a spread field in mapping constructors - https://ballerina.io/spec/lang/master/#spread-field

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 42]
```diff
@@ -191,56 +191,205 @@ function testRestParameterType() returns boolean {
...
+    string fName;
+    boolean married;
+    Age age;
+    map<anydata> theMap;
+
+    {
+        name: fName,
+        age,
+        married,
+        ...theMap
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:237]: theMap isn't asserted

Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:237]: That's intentional. We don't need to assert it. We have asserted it in the other tests.

Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:237]: we can remove this test. It seems this test is not necessary.

Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:237]: Fixed via [6568a25](https://github.com/ballerina-platform/ballerina-lang/pull/40283/commits/6568a25b943625b81aba3d44930295716bca906b)

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java [hunk 43]
```diff
@@ -2199,11 +2199,6 @@ public void visit(BLangSimpleVariableDef varDefNode, AnalyzerData data) {
 
     @Override
     public void visit(BLangRecordVariableDef varDefNode, AnalyzerData data) {
-        // TODO: 10/18/18 Need to support record literals as well
-        if (varDefNode.var.expr != null && varDefNode.var.expr.getKind() == RECORD_LITERAL_EXPR) {
-            dlog.error(varDefNode.pos, DiagnosticErrorCode.INVALID_LITERAL_FOR_TYPE, "record binding pattern");
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2204]: Why isn't this DiagnosticErrorCode removed?

Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2204]: Where have the tests been added for this?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2204]: Noticed that they've been added in RecordVariableReferenceTest.java. That's not the correct class. Should go in RecordVariableDefinitionTest.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal [hunk 44]
```diff
@@ -369,7 +519,110 @@ function testMappingBindingWithSingleNameFieldBinding() {
...
+    assertEquality("Highway 61", street);
+    assertEquality({lat: 37.30, lon: -90.40}, coordinates);
+
+    record {string state;} {state: state2, ...other} = {state: "Colorado", "zipCode": 80001};
+    assertEquality("Colorado", state2);
+    assertEquality({zipCode: 80001}, other);
+
+    var {country, ...rest} = {country: "USA", zipCode: 80001};
+    assertEquality("USA", country);
+    assertEquality({zipCode: 80001}, rest);
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal:622]: Add more tests including where the member binding patterns are in turn structured binding patterns.

Also add negative tests for unspecified fields, optional field binding, etc.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java (hunk 43 above)
Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2204]: Ack

Comment (dulajdilshan) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java:2204]: Removed via [08f5e57c](https://github.com/ballerina-platform/ballerina-lang/pull/40283/commits/08f5e57c1ad10f85c19eb19448ad3ee195da0825)

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt.bal [hunk 45]
```diff
@@ -774,6 +774,57 @@ function testNestedRecordVariableWithAnonymousType() {
...
+        string number;
+    |}[2] contact;
+|};
+
+function testRecordTypedBindingPatternAgainstRecordLiteralInRecordDestructuring() {
+    record {|string state; int postalCode;|} {state, postalCode} = {state: "Alabama", postalCode: 35004};
+    assertEquality("Alabama", state);
+    assertEquality(35004, postalCode);
+
+    record {|string street; float...;|} {street, ...coordinates} = {street: "Highway 61", "lat": 37.30, "lon": -90.40};
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt.bal:790]: Also add for when some of the required fields are bound as rest.

**Review by MaryamZi — COMMENTED** [review]
Title needs to be changed too.

File: tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt.bal (hunk 45 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/statements/variabledef/record-variable-definition-stmt.bal:790]: Added in https://github.com/ballerina-platform/ballerina-lang/pull/40283/commits/edebb78afebb8f6e60721465d50959820908d968

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal (hunk 44 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference.bal]: Added in https://github.com/ballerina-platform/ballerina-lang/pull/40283/commits/edebb78afebb8f6e60721465d50959820908d968

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference-in-destructuring-negative.bal [hunk 46]
```diff
@@ -0,0 +1,53 @@
...
+// specific language governing permissions and limitations
+// under the License.
+
+function testTupleDestructuringWithOptionalFieldBindingPattern() {
+    [record {|int a; int b?;|}] l1 = [{a: 1, b: 2}];
+    int a;
+    int b;
+    int c;
+    [{a, b}]= l1;
+    [int, [record {int b?;}]] l2= [1, [{b: 1}]];
```
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference-in-destructuring-negative.bal:23]:
```suggestion
    [int, [record {int b?;}]] l2 = [1, [{b: 1}]];
```

Fix everywhere.

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference-in-destructuring-negative.bal
Comment (MaryamZi) [inline tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference-in-destructuring-negative.bal:1]: Use underscores for file names.

Also proper terms for new files/code - e.g., record_bp_in_list_bp_destructuring_assignment_negative.bal

File: tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference-in-destructuring-negative.bal (hunk 46 above)
Comment (dulajdilshan) [reply tests/jballerina-unit-test/src/test/resources/test-src/expressions/varref/record-variable-reference-in-destructuring-negative.bal]: Addressed via https://github.com/ballerina-platform/ballerina-lang/pull/40283/commits/3de0d3ecb958f3cd9e9b45bacf4c094cbeb9d859

**Review by MaryamZi — APPROVED** [review]
