### PR TITLE
[master] Add missing completions in conditional expressions and Fix extract to function code action

### LINKED ISSUE #38090: [Bug]: Missing completion item for `toString()` method
### Description

Missing completion item for `toString()` method in the below scenario.

Screenshot 2022-10-05 at 21 50 42

Screenshot 2022-10-05 at 21 50 16

### Steps to Reproduce

```
type RecordType record {
    json|error fieldName;
};

function name(RecordType r) {
    json|error s1 = r.fieldName;
    string s2 = s1 is json? s1.toString() : ""; 
}
```

### Affected Version(s)

2201.2.1 (Swan Lake Update 2)

### OS, DB, other environment details and versions

_No response_

### Related area

-> Other Area

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
This PR adds missing completion items and fixes the extract to function code action in conditional expressions.
Fixes #38090

## Samples

https://user-images.githubusercontent.com/61020198/197474380-dd357bec-e133-4956-8767-e0d82e6ccf54.mov

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java [hunk 1]
```diff
@@ -490,6 +501,15 @@ private Optional<ArgListsHolder> getArgLists(CodeActionContext context, List<Sym
         return Optional.of(argListsHolder);
     }
 
+    private Optional<TypeSymbol> getTypeSymbol(CodeActionContext context, TypeSymbol typeSymbol,
+                                               NonTerminalNode node) {
+        if (typeSymbol.typeKind() == TypeDescKind.UNION) {
+            return Optional.of(context.currentSemanticModel().flatMap(semanticModel ->
+                    semanticModel.typeOf(node.children().get(0)).flatMap(SymbolUtil::getTypeDescriptor)).get());
```
Comment (LakshanWeerasinghe) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java:508]:
```suggestion
            return context.currentSemanticModel().flatMap(semanticModel ->
                    semanticModel.typeOf(node.children().get(0)).flatMap(SymbolUtil::getTypeDescriptor));
```

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java [hunk 2]
```diff
@@ -490,6 +501,15 @@ private Optional<ArgListsHolder> getArgLists(CodeActionContext context, List<Sym
         return Optional.of(argListsHolder);
     }
 
+    private Optional<TypeSymbol> getTypeSymbol(CodeActionContext context, TypeSymbol typeSymbol,
```
Comment (LakshanWeerasinghe) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java:504]: Better if we can rename this method or add a comment because here we are using a type symbol to get another type symbol.

**Review by LakshanWeerasinghe — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java [hunk 3]
```diff
@@ -490,6 +501,16 @@ private Optional<ArgListsHolder> getArgLists(CodeActionContext context, List<Sym
...
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java:504]: Let's add a java doc describing this method

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java [hunk 4]
```diff
@@ -490,6 +501,16 @@ private Optional<ArgListsHolder> getArgLists(CodeActionContext context, List<Sym
...
+                                               NonTerminalNode node) {
+        // If the type symbol kind is union, return the narrowed type using typeOf() for the particular node.
+        if (typeSymbol.typeKind() == TypeDescKind.UNION) {
+            return context.currentSemanticModel().flatMap(semanticModel ->
+                    semanticModel.typeOf(node.children().get(0)).flatMap(SymbolUtil::getTypeDescriptor));
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java:509]: Here we shouldn't use `node.children().get(0)`. Instead, let's check the SyntaxKind of `node` and access the child we want using relevant methods.

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java (hunk 3 above)
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java:504]: Let's change this name to something like getTypeForArgument()

**Review by malinthar — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java (hunk 4 above)
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java:509]: We can check if the SyntaxKind of `node.parent()` is `ConditionalExpressionNode` and then use `((ConditionalExpressionNode)node.parent()).middleExpression().children().get(0)`
WDYT?

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java (hunk 3 above)
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java:504]: +1

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java [hunk 5]
```diff
@@ -612,4 +629,36 @@ private static class ArgListsHolder {
...
+            }
+        }
+
+        @Override
+        public void visit(SimpleNameReferenceNode simpleNameReferenceNode) {
+            for (String symbolName: symbolNamesList) {
+                if (!nodeList.containsKey(symbolName) && symbolName.equals(simpleNameReferenceNode.name().text())) {
+                    nodeList.put(symbolName, simpleNameReferenceNode);
+                }
+            }
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java:661]:
```suggestion
            symbolNamesList.stream().filter(symbolName -> !nodeList.containsKey(symbolName) 
                    && symbolName.equals(simpleNameReferenceNode.name().text())).findFirst().ifPresent(symbolName-> nodeList.put(symbolName,simpleNameReferenceNode));
```

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java [hunk 6]
```diff
@@ -612,4 +629,36 @@ private static class ArgListsHolder {
...
+
+        public Map<String, NonTerminalNode> getSymbolTypes() {
+            return nodeList;
+        }
+
+        public void findType(NonTerminalNode matchedCodeActionNode) {
+            if (matchedCodeActionNode.kind() == SyntaxKind.LIST) {
+                for (Node node : matchedCodeActionNode.children()) {
+                    node.accept(this);
+                }
```
Comment (malinthar) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java:649]: We can add a `return; ` here and remove the else part

**Review by IMS94 — CHANGES_REQUESTED** [review]

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java [hunk 7]
```diff
@@ -457,29 +462,41 @@ private Optional<List<Symbol>> getVarAndParamSymbolsWithinRangeForExprs(LineRang
...
+        Map<String, NonTerminalNode> symbolTypes = typeFinder.getSymbolTypes();
+        List<String> sortedSymbolNames = new ArrayList<>();
 
-            Optional<String> possibleType = Optional.empty();
-            if (symbol.kind() == SymbolKind.VARIABLE) {
-                possibleType = CodeActionUtil
-                        .getPossibleType(((VariableSymbol) symbol).typeDescriptor(), new ArrayList<>(), context);
+        for (Map.Entry<String, NonTerminalNode> entry : symbolTypes.entrySet()) {
+            sortedSymbolNames.add(entry.getKey());
+            sortedSymbolNames.sort(Comparator.comparing(symbolNamesList::indexOf));
```
[the remark this answers is not in the document]
Comment (mindula) [reply language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToFunctionCodeAction.java]: fixed in [88a416a](https://github.com/ballerina-platform/ballerina-lang/pull/38357/commits/88a416ab42896f938bbbe1978c05c562c4e43dde)

**Review by IMS94 — APPROVED** [review]

**Review by malinthar — APPROVED** [review]
LGTM!
