### PR TITLE
Fix code actions which are not supported in the code but passes the tests, to work

### LINKED ISSUE #37128: Code action tests passing where it should be failing
**Description:**
AbstractCodeActionTest fails tests only when there are mismatched code actions are available between the config file and the code action responses. When there are extra code action results in the config files and when the code action response does not include those results, code action does not fail. 

As a result, when the code base dis-continue to support a code action, the test does not fail. 

**Steps to reproduce:**
```
public function testFunction() {
    io<cur>:
}
```
Here at the cursor you don't get the code action(in master) `import module ballerina/io`, where you should get it. But still the test case does not fail. [importModule3.json](language-server/modules/langserver-core/src/test/resources/codeaction/import-module/config/importModule3.json)

**Affected Versions:**
master

### PR DESCRIPTION
**Pull request by gayalkuruppu**
Fixes #37128

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionNodeValidator.java [hunk 1]
```diff
@@ -271,8 +271,13 @@ public Boolean transform(TypeTestExpressionNode node) {
...
     @Override
     public Boolean transform(QualifiedNameReferenceNode node) {
+        /*
+            We need to suggest import module code action when,
+            ex: "io<cursor>:" hence we have special cased typed binding pattern.
+         */
         return isVisited(node) || !node.colon().isMissing() && !node.modulePrefix().isMissing()
-                && node.parent() != null ? node.parent().apply(this) : true;
+                && node.parent() != null && node.parent().kind() != SyntaxKind.TYPED_BINDING_PATTERN
+                ? node.parent().apply(this) : true;
```
Comment (IMS94) [inline language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionNodeValidator.java:280]: We can rewrite this as:
```
&& node.parent() != null && (node.parent().kind() == SyntaxKind.TYPED_BINDING_PATTERN || node.parent().apply(this));
```

**Review by IMS94 — CHANGES_REQUESTED** [review]
LGTM! Added a minor suggestion.

**Review by IMS94 — APPROVED** [review]

**Review by TharushiJay — APPROVED** [review]
LGTM

**Review by IMS94 — APPROVED** [review]
