### PR TITLE
Fix usages of "invalid literal for type" error message

### LINKED ISSUE #17360: Cannot figure out actual error from the error message
**Description:**
```ballerina

import ballerina/http;

http:Client circuitBreakerEP = new("http://localhost:9092", {
        circuitBreaker: {
            timeoutMillis: 2000
        }
    });
```

When trying to compile the above code, following error is shown:
```
error: .::Untitled-1.bal:5:25: invalid literal for type 'ballerina/http:CircuitBreakerConfig?'
```

This doesn't say what the error is, or no information on how to resolve the error.

**Affected Versions:**
1.0-alpha

### PR DESCRIPTION
**Pull request by pubudu91**
Fixes #17360

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 1]
```diff
@@ -944,8 +943,31 @@ public void visit(BLangRecordLiteral recordLiteral) {
         }
     }
 
-    private List<BType> getRecordCompatibleType(BType bType, BLangRecordLiteral recordLiteral) {
+    private boolean isMappingConstructorCompatibleType(BType type) {
+        return type.tag == TypeTags.RECORD || type.tag == TypeTags.MAP || type.tag == TypeTags.JSON;
+    }
+
+    private void reportIncompatibleMappingConstructorError(BLangRecordLiteral mappingConstructorExpr, BType expType) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Should we special case the `T?` case where T is a record? If so, can provide an even better error message for the particular issue mentioned in #17360

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 2]
```diff
@@ -944,8 +944,31 @@ public void visit(BLangRecordLiteral recordLiteral) {
...
+            return;
+        }
+
+        BUnionType unionType = (BUnionType) expType;
+        Set<BType> memberTypes = unionType.getMemberTypes();
+
+        for (BType bType : memberTypes) {
+            if (isMappingConstructorCompatibleType(bType)) {
+                dlog.error(mappingConstructorExpr.pos, DiagnosticCode.INCOMPATIBLE_MAPPING_CONSTRUCTOR, unionType);
+                return;
```
Comment (gimantha) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: should we not print all the incompatible member types at once?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java [hunk 3]
```diff
@@ -79,7 +79,9 @@ public void testNegativeWorkerActions() {
         BAssertUtil.validateError(resultNegative, index++,
                 "missing non-defaultable required record field 'f2'", 86, 25);
         BAssertUtil.validateError(resultNegative, index++,
-                "invalid literal for type 'sealedRec'", 87, 26);
+                                  "incompatible types: expected 'sealedRec', found 'record {| other id; other name; " +
+                                          "other status; |}",
```
Comment (hasithaa) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java]: Not related to this, but Saying "other" is confusing here.  We need to come up with a better name for `other`.  One option is to make it special. like, `<unknown_type>` Shall we create an issue?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 4]
```diff
@@ -1184,3 +1184,12 @@ error.invalid.package.name.qualifier=\
...
   identifier literal only supports alphanumeric characters
+
+error.incompatible.mapping.constructor.expression=\
+  incompatible mapping constructor expression for type ''{0}''
+
+error.mapping.constructor.compatible.type.not.found =\
+  a type compatible with mapping constructor expressions not found in type ''{0}''
+
+error.cannot.infer.types.for.tuple.binding =\
+  invalid expression: types cannot be inferred for ''{0}''
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/resources/compiler.properties]: The error message is not related to a tuple, but the error key says tuple binding.

Comment (hasithaa) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: It seems like no test case is added for this particular case.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java [hunk 5]
```diff
@@ -189,6 +189,9 @@
     UNSAFE_CONVERSION_ATTEMPT("unsafe.conversion.attempt"),
 
     INVALID_LITERAL_FOR_TYPE("invalid.literal.for.type"),
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java]: Are we removing all usage of this with this PR?

File: compiler/ballerina-lang/src/main/resources/compiler.properties [hunk 6]
```diff
@@ -1184,3 +1184,12 @@ error.invalid.package.name.qualifier=\
 
 error.identifier.literal.only.supports.alphanumerics=\
   identifier literal only supports alphanumeric characters
+
+error.incompatible.mapping.constructor.expression=\
+  incompatible mapping constructor expression for type ''{0}''
```
Comment (hasithaa) [inline compiler/ballerina-lang/src/main/resources/compiler.properties]: Shall we add test cases for this one as well?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 1 above)
Comment (hasithaa) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: +1, `T?` is 80% of the case, when considering unions.

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java (hunk 3 above)
Comment (pubudu91) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitActionsNegativeTest.java]: Created #19876 to track this.

File: compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java (hunk 5 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticCode.java]: There's one usage in record binding patterns. #19804 is to take a look and address this as well.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: This is just to isolate instances where the union has a type with which we can use record literals (i.e., records, maps an JSON), but for this particular case, the given record literal isn't compatible with that type.

File: compiler/ballerina-lang/src/main/resources/compiler.properties (hunk 4 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/resources/compiler.properties]: This error is only for tuples (lists). Will modify the error message to make it clear.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 7]
```diff
@@ -1870,6 +1894,23 @@ public void visit(BLangWaitForAllExpr waitForAllExpr) {
         }
     }
 
+    private BRecordType getWaitForAllExprReturnType(List<BLangWaitForAllExpr.BLangWaitKeyValue> keyVals) {
+        BRecordType retType = new BRecordType(null);
+        
+        for (BLangWaitForAllExpr.BLangWaitKeyValue keyVal : keyVals) {
+            BSymbol symbol = symResolver.lookupSymbol(env, names.fromIdNode(keyVal.key), SymTag.VARIABLE);
```
Comment (rdhananjaya) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: I think what we expect here is to get the constraint type of the `future`
If so I think we need to do something in the line of 
```java
BType t = ((BFutureType) checkExpr(keyVal.valueExpr, env)).constraint
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: How about cases like 

`Foo|Bar x = {};`

where both `Foo` and `Bar` are records but `{}` is not valid for either of them?

That still reaches here right? If it does IMO, we should mention both of them.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java [hunk 8]
```diff
@@ -947,8 +947,63 @@ public void visit(BLangRecordLiteral recordLiteral) {
...
+                       expType);
+            return;
+        }
+
+        BUnionType unionType = (BUnionType) expType;
+        BType[] memberTypes = unionType.getMemberTypes().toArray(new BType[0]);
+
+        // Special case handling for `T?` where T is a record type. This is done to give more user friendly error
+        // messages for this common scenario.
+        if (memberTypes.length == 2) {
```
Comment (MaryamZi) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Can't we make this a generic check for any union with just a single record type?

Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: e.g., `Foo|int?`

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 7 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Not quite. Consider something like below:
```ballerina
int x = wait {w1, w2};
```
What I want is to create a record type for the RHS so that in the error message I can say expected `int`, but found this type of record. If I call checkExpr(), it'll go in the normal type checking flow, which means if there are any errors there, the compiler will log errors for those as well.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 8 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Can do. But went with the `T?` case (at least for now) since it's the most common one.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: The error message says the mapping constructor is not valid for the union. It doesn't mention individual types. For example, for the above case you mentioned:
```
incompatible mapping constructor expression for type '(Foo|Bar)'
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 7 above)
Comment (rdhananjaya) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: If I understand correctly your concern is around duplicate error message due to `checkExpr` right,
```ballerina
 int x = wait { w1+1, nonFutureRef };
```
Because of caching I don't think there will be multiple error messages.

Anyway for `wait { someKey: w1, someKey1: w1 }` resolving symbol for the `key` will always result in undefined symbol (other)

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 2 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: ah yeah, missed that we were using `unionType`, sorry!

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java (hunk 7 above)
Comment (pubudu91) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java]: Fixed this with 1be935a. Have a look
