### PR TITLE
Fix escaping chars in XML texts twice

### LINKED ISSUE #32673: Printing XML CDATA section gives incorrect output
**Description:**
Consider the bellow sample of XML CDATA added via #32564
```bal
public function main() {
    xml x7 = xml `<![CDATA[ abc --> <!-- --> some more text ]]>`;
    io:println(x7);
}
```
This prints `abc --&amp;gt; &amp;lt;!-- --&amp;gt; some more text` where it should print `abc --&gt; &lt;!-- --&gt; `some more text

**Affected Versions:**
Current master

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
In the implementation for xml `stringValue()` we use `XMLStreamWriter` to convert the xml texts from byte array stream to string. 
The stream writer instance is created from different classes when we run unit tests and when we externally run using `bal run`. 

Fixes #32673 

## Approach
When the unit tests are running,  the stream writer uses the default configurations where it escapes the characters in  the string output which is already escaped by the native implementation.  
https://github.com/ballerina-platform/ballerina-lang/blob/243aa0746732976f520802677cba1f257f096f0f/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java#L158

This PR unsets the `escapeCharacters` property for default stream writers to fix this error.

## Samples
Need to be tested within unit tests.
```ballerina
public function main() {
    xml x7 = xml `<![CDATA[ abc --> <!-- --> some more text ]]>`;
    assertTrue(x7.toString() == " abc --&gt; &lt;!-- --&gt; some more text ");  
}
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java [hunk 1]
```diff
@@ -141,8 +147,9 @@ private void writeXMLComment(XmlComment xmlValue) throws XMLStreamException {
     }
 
     private void writeXMLText(XmlText xmlValue) throws XMLStreamException {
-        // No need to escape xml text when they are within xml element, it's handle from xml stream writer.
-        if (this.withinElement) {
+        // No need to escape xml text when they are within xml element or if it is not from default stream writer.
+        // It's handled by xml stream  writer.
+        if (this.withinElement && !isDefaultFactory) {
```
Comment (warunalakshitha) [inline bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java:152]: Can we use xmlOutputFactory.getProperty("escapeCharacters") != null. and equal to true here

Comment (HindujaB) [reply bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/BallerinaXmlSerializer.java:152]: If we use the `xmlOutputFactory.getProperty("escapeCharacters")` in this check, it  gives an `IllegalStateException` for the non-default stream writer (Since it is not a predefined property for `WstxOutputFactory`).

**Review by warunalakshitha — APPROVED** [review]
