### PR TITLE
Fix isolation analysis for query expressions and on fail clauses

### LINKED ISSUE #30797: References to variables defined in query expressions are considered to be invalid attempts to transfer a value into a lock statement
**Description:**
$title, we seem to not be looking in the correct scope/env.

**Steps to reproduce:**
```ballerina
isolated class Foo {
    private int i = 0;
}

isolated class Bar {
    private int[][] arrs = [];

    function func() {
        lock {
            int[][] x = [];

            foreach var item in x {
                self.arrs.push(item);
            }

            self.arrs = from var item in x select item; // ERROR: invalid attempt to transfer a value into a 'lock' statement with restricted variable usage
        }
    }
}
```

**Affected Versions:**
slbeta1-rc4

### LINKED ISSUE #31567: Isolation analysis does not happen for certain on-fail clauses
**Description:**
$title.

Specifically for
- foreach-stmt
- while-stmt
- lock-stmt

**Steps to reproduce:**
The following should result in errors since the isolated variable `i` is accessed outside a lock statement.

```ballerina
isolated int i = 1;

isolated function f2() {
    foreach var item in 1 ..< 2 {
        
    } on fail error e {
        i += 1;
    }

    int m = 1;

    while m < 2 {
        m += 1;
    } on fail error e {
        i += 1;
    }

    lock {

    } on fail error e {
        i += 1;
    }
}
```

**Affected Versions:**
slbeta2-rc4

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$title.

Fixes #30797
Fixes #31567

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java [hunk 1]
```diff
@@ -813,24 +813,32 @@ public void visit(BLangMatchClause matchClause) {
...
+        analyzeNode(fromClause.collection, fromEnv);
     }
 
     @Override
     public void visit(BLangJoinClause joinClause) {
-        analyzeNode((BLangNode) joinClause.getVariableDefinitionNode(), env);
-        analyzeNode(joinClause.collection, env);
+        SymbolEnv joinEnv = joinClause.env;
+        analyzeNode((BLangNode) joinClause.getVariableDefinitionNode(), joinEnv);
+        analyzeNode(joinClause.collection, joinEnv);
```
Comment (pcnfernando) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java:834]:
```suggestion
        analyzeNode(joinClause.collection, joinEnv);
        analyzeNode((BLangNode) joinClause.onClause, joinEnv);
```

**Review by pcnfernando — DISMISSED** [review]

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java:834]: Thanks, had missed this. Fixed and added tests in 8dc7bef.

**Review by pcnfernando — APPROVED** [review]
