### PR TITLE
[Semantic API] Fix the Symbol Lookup of Error Type Descriptor Symbols

### LINKED ISSUE #32196: [Semantic API] `symbol()` not working for error type descs
e.g.,
```ballerina
<cursor>error<ErrorData> err;
```

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #32196

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java [hunk 1]
```diff
@@ -1264,6 +1264,10 @@ public void visit(BLangTupleTypeNode tupleTypeNode) {
     @Override
     public void visit(BLangErrorType errorType) {
         lookupNode(errorType.detailType);
+
+        if (symbolAtCursor == null && errorType.getBType() != null) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java:1268]: Was there a case where the type gets null?

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java [hunk 2]
```diff
@@ -90,7 +90,12 @@ public String signature() {
             return this.signature;
         }
 
-        String definitionName = getBType().tsymbol.name.value;
+        String definitionName;
+        if (detailTypeDescriptor().typeKind() == TypeDescKind.TYPE_REFERENCE) {
+            definitionName = getBType().toString();
+        } else {
+            definitionName = "error";
+        }
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java:98]: Couple of points:
- Detail type is not necessarily a type reference. It's a mapping type.
- Better to be depending on the signature of the detail type, instead of using the internal type's string representation.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java [hunk 3]
```diff
@@ -90,7 +90,10 @@ public String signature() {
             return this.signature;
         }
 
-        String definitionName = getBType().tsymbol.name.value;
+        String definitionName = "error";
+        if (detailTypeDescriptor().typeKind() == TypeDescKind.TYPE_REFERENCE) {
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java:94]: This is redundant and restrictive. e.g., `error<record {| int code; |}>` We just simply need the detail type's signature.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java [hunk 4]
```diff
@@ -1384,23 +1384,32 @@ public void visit(BLangErrorType errorTypeNode) {
...
 
         PackageID packageID = env.enclPkg.packageID;
         if (env.node.getKind() != NodeKind.PACKAGE) {
             errorTypeSymbol.name = names.fromString(
                     anonymousModelHelper.getNextAnonymousTypeKey(packageID));
             symbolEnter.defineSymbol(errorTypeNode.pos, errorTypeSymbol, env);
+        } else {
+            // If the error type descriptor is at the module level, the error type symbol's owner should be the current
+            // environment's scope owner.
+            errorTypeSymbol.owner = env.scope.owner;
```
Comment (pubudu91) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java:1412]: This is problematic for module level defined error type vars. 
e.g.,
```ballerina
<cursor1>error<DetailType> err1;

function test() {
    <cursor2>error<DetailType> err2;
}
```
The module returned for the above 2 cases will be,
- the default(current) module for `cursor1`
- the `lang.annotations` module for `cursor2`.

For both cases above it should've returned the `lang.annotations` module.

File: language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config19.json [hunk 5]
```diff
@@ -60,11 +60,11 @@
     {
       "label": "filter(function () func)",
       "kind": "Function",
-      "detail": "stream<any|ErrorType, ErrorType?>",
+      "detail": "stream<any|error, error?>",
```
Comment (pubudu91) [inline language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config19.json:63]: This change means this change has broken the current type ref checks for error. This change may be due to the above issue I pointed.

Comment (IMS94) [reply language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config19.json:63]: Agreed with @pubudu91. This shouldn't be changed

**Review by IMS94 — CHANGES_REQUESTED** [review]

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java (hunk 1 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/SymbolFinder.java]: This was an additional check placed in order to avoid a possible NPE. Removed it since no instances were found where the type gets null.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java (hunk 3 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java]: Placed an additional check to handle this.

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java (hunk 4 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java]: Handled the issue caused by this in the `SymbolEnter`.

File: language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config19.json (hunk 5 above)
Comment (IMS94) [reply language-server/modules/langserver-core/src/test/resources/completion/statement_context/config/foreach_stmt_ctx_config19.json:63]: Seems like the one suggested earlier was wrong. The `filter()` function in streams has `stream<Type,CompletionType>` as return type and those type params represent subtypes `any|error` and `error` respectively.

File: compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java (hunk 2 above)
Comment (sanjana) [reply compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java]: Resolved. 
https://github.com/ballerina-platform/ballerina-lang/pull/32390#discussion_r699100705

**Review by IMS94 — APPROVED** [review]
LGTM!

**Review by pubudu91 — APPROVED** [review]
