### PR TITLE
Fix typo in error messages

### LINKED ISSUE #27021: Compilation error which says Failed to Read Markdown Documentation
**Description:**
A compilation error is thrown saying `error: failed to read Markdown Documenation` when building a newly created Ballerina module or even a single .bal file with slp6 latest SNAPSHOT.

**Steps to reproduce:**
First, we need to build a Ballerina slp6 SNAPSHOT distribution using the latest code in ballerina-lang master branch.
Then add that distribution's bin folder to the system PATH variable.
Then issue the following sequence of commands.

```
ballerina new proj1
cd proj1
ballerina add mod1
cd src/mod1
ballerina build -a -c
```
Execution of the final command should throw the following error. Note that here the error message also has a typo `Documenation`.

```
error: failed to read Markdown Documenation
```
The same error gets thrown even if we try to build a simple Hello World `.bal` file with the following command.

`ballerina build main.bal`

**Affected Versions:**
I have used the latest code from Ballerina lang master branch which will be release as slp6 near future.

**OS, DB, other environment details and versions:**
Ubuntu 18.04, Balerina slp6 latest SNAPSHOT

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes #27021

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BinaryFileWriter.java [hunk 1]
```diff
@@ -222,7 +222,7 @@ private void createDirectory(Path tempDir) {
         try {
             Files.createDirectories(tempDir);
         } catch (IOException e) {
-            throw new BLangCompilerException("failed create directory '" + tempDir.toString() + "'", e);
+            throw new BLangCompilerException("failed to create directory '" + tempDir.toString() + "'", e);
```
Comment (riyafa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BinaryFileWriter.java:225]: Do you think it would be nice to have first letter as capital:
```suggestion
            throw new BLangCompilerException("Failed to create directory '" + tempDir.toString() + "'", e);
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/FileSystemProjectDirectory.java [hunk 2]
```diff
@@ -181,7 +181,7 @@ private void createDirectory(Path targetPath) {
         try {
             Files.createDirectory(targetPath);
         } catch (IOException e) {
-            throw new BLangCompilerException("failed create directory '" + targetPath.toString() + "'");
+            throw new BLangCompilerException("failed to create directory '" + targetPath.toString() + "'");
```
Comment (riyafa) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/FileSystemProjectDirectory.java:184]: same here:
```suggestion
            throw new BLangCompilerException("Failed to create directory '" + targetPath.toString() + "'");
```

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BinaryFileWriter.java (hunk 1 above)
Comment (MaryamZi) [reply compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BinaryFileWriter.java:225]: We usually start diagnostic messages with lower-case letters. I think we should continue to do the same here. We can change the error in `BIRPackageSymbolEnter.java` too.

**Review by riyafa — APPROVED** [review]

**Review by MaryamZi — APPROVED** [review]
