### PR TITLE
[IntelliJ Plugin] Fix indentation issue when working with ballerina documentation syntax

### LINKED ISSUE #20594: [IntelliJ Plugin] Indentation issue with newly inserted documentation line when pressing enter
**Description:**
When editing ballerina documentation using the intellij plugin, the indentation of the newly added line might be incorrect in some contexts, when pressing enter at the end of the current documentation line.

**Steps to reproduce:**

**Affected Versions:**
Plugin version - 1.1.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by NipunaRanasinghe**
## Purpose
Fixes #20594.

## Related PRs
#20599.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [x] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/editor/inserthandlers/BallerinaEnterInDocumentationHandler.java [hunk 1]
```diff
@@ -29,48 +30,53 @@
...
+            PsiDocumentManager.getInstance(project).commitDocument(doc);
         }
         return Result.Continue;
     }
 
-    private void enterNewLine(Editor editor, String str, int col) {
-        StringBuilder strBuilder = new StringBuilder("# " + str);
-        // Left padding with whitespaces in order to be vertically aligned with the previous doc line.
-        for (int i = 0; i < col; i++) {
+    // Inserts the splitted documentation at the next line.
```
Comment (nadeeshaan) [inline tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/editor/inserthandlers/BallerinaEnterInDocumentationHandler.java]: Better to use method documentation format instead of the single line comment

Comment (NipunaRanasinghe) [reply tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/editor/inserthandlers/BallerinaEnterInDocumentationHandler.java]: @nadeeshaan As per my knowledge,
1. javadocs comes forward when the info presents which the user of a class needs to know and 
2. Info that a developer modifying a class might better go into a normal comment (block or line).

Above context (private method without function args descriptions) is more related to the scenario (2) IMO :) WDYT?

Please also refer this [SO Thread](https://stackoverflow.com/questions/3607641/javadoc-comments-vs-block-comments) as well.
