### PR TITLE
Fix no error when attempting to invoke a remote transactional method in a non-transactional scope

### LINKED ISSUE #25017: No error when attempting to invoke a remote transactional method in a non-transactional scope
**Description:**
$title.

May also be the case for normal methods, can't test due to #25016 

**Steps to reproduce:**
```ballerina
type Foo client object {
    remote transactional function baz() {  
    }

    function bar() {
        transaction {
            checkpanic commit;
            modFunc(); // error - OK - invoking transactional function outside transactional scope is prohibited
            self->baz(); // no error
        }
    }
};

transactional function modFunc() {    
}
```

**Affected Versions:**
Current master (slp3-SNAPSHOT)

### PR DESCRIPTION
**Pull request by lasinicl**
Fixes #25017

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/TransactionStmtTest.java [hunk 1]
```diff
@@ -30,7 +30,7 @@
 /**
  * Test cases for flow validation in TransactionStatement.
  */
-
+@Test(groups = {"disableOnOldParser"})
```
Comment (mohanvive) [inline tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/TransactionStmtTest.java:33]: Any reason for avoiding transaction statement test for old parser?

File: compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java [hunk 2]
```diff
@@ -2170,6 +2170,11 @@ public void visit(BLangInvocation invocationExpr) {
     }
 
     public void visit(BLangInvocation.BLangActionInvocation actionInvocation) {
+        BSymbol funcSymbol = actionInvocation.symbol;
+        if (Symbols.isFlagOn(funcSymbol.flags, Flags.TRANSACTIONAL) && !withinTransactionScope) {
+            dlog.error(actionInvocation.pos, DiagnosticCode.TRANSACTIONAL_FUNC_INVOKE_PROHIBITED, actionInvocation);
+            return;
+        }
```
Comment (mohanvive) [inline compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java:2177]: Can we please revisit this condition check with the code in lines 2178-2182 ?

File: tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/TransactionStmtTest.java (hunk 1 above)
Comment (lasinicl) [reply tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/transaction/TransactionStmtTest.java:33]: A compilation error(`invalid token 'transactional'`) is given for `transactional` keyword in the old parser.
